NAME = 'AP® Environmental Science'
ABBREV = 'apes'
SLUG = 'ap-environmental-science'
COURSE_FILE = 'ap-environmental-science.html'
ACCENT_COLOR = '#22c55e'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Environmental+Science+'

COURSE_QS = [
    ('The 10% rule in ecology states that',
     'only about 10% of energy is transferred to the next trophic level; the rest is lost as heat',
     ['10% of species in an ecosystem are keystone species', 'photosynthesis converts 10% of solar energy to glucose', '10% of water in the hydrologic cycle evaporates']),
    ('Which greenhouse gas has the highest global warming potential per molecule?',
     'Nitrous oxide (N₂O) and fluorinated gases have higher GWP than CO₂, though CO₂ is most abundant',
     ['Water vapor (H₂O)', 'Carbon dioxide (CO₂)', 'Oxygen (O₂)']),
    ('The IPAT equation describes environmental impact as',
     'Impact = Population × Affluence × Technology (resource use per unit of production)',
     ['I = Pollution + Adaptation + Temperature', 'I = Income × Population × Area × Time', 'I = Industry × Population × Agriculture']),
    ('Eutrophication in water bodies is caused by',
     'excess nutrient runoff (nitrogen, phosphorus) that causes algal blooms, oxygen depletion, and fish kills',
     ['acid rain reducing pH below 5', 'introduction of invasive species', 'thermal pollution from power plants']),
    ('Ozone depletion in the stratosphere is primarily caused by',
     'chlorofluorocarbons (CFCs) releasing chlorine atoms that catalytically destroy ozone molecules',
     ['carbon dioxide accumulation in the upper atmosphere', 'methane from agricultural activities', 'nitrogen oxides from vehicle emissions']),
    ('The Coriolis effect influences global wind patterns by',
     'deflecting moving air to the right in the Northern Hemisphere and left in the Southern Hemisphere due to Earth\'s rotation',
     ['creating thermal gradients between land and ocean', 'causing warm air to rise at the equator', 'reversing trade winds seasonally']),
    ('Primary succession occurs on',
     'bare, lifeless substrate (e.g., bare rock, lava flows) with no existing soil',
     ['disturbed land that still has soil and seed banks', 'agricultural fields after harvest', 'mature forests after selective logging']),
    ('The tragedy of the commons describes',
     'how individuals overexploit shared (common) resources because each gains full benefit while costs are shared',
     ['the inefficiency of government-owned land', 'pollution from tragedy-causing industrial accidents', 'the loss of biodiversity in national parks']),
    ('Cap-and-trade programs reduce pollution by',
     'setting a total pollution limit and allowing polluters to buy and sell permits, incentivizing the cheapest reductions first',
     ['taxing all carbon emissions equally regardless of output', 'banning the most polluting industries', 'requiring all firms to use the same technology']),
    ('Integrated pest management (IPM) differs from conventional pesticide use in that IPM',
     'combines biological, cultural, mechanical, and chemical controls to minimize pesticide use while managing pests effectively',
     ['relies exclusively on chemical pesticides', 'eliminates all pest control measures', 'uses only genetically modified crops']),
    ('The hydrologic cycle moves water primarily through',
     'evaporation, condensation, precipitation, surface runoff, infiltration, and transpiration',
     ['photosynthesis, respiration, and nitrogen fixation', 'tidal forces and ocean currents only', 'volcanic outgassing and plate tectonics']),
    ('Soil horizons from top to bottom are',
     'O (organic), A (topsoil), E (eluviation), B (subsoil), C (parent material), R (bedrock)',
     ['A, B, C, D, E from surface to bedrock', 'humus, clay, sand, gravel, bedrock', 'topsoil, subsoil, clay pan, parent rock']),
    ('The Safe Drinking Water Act (SDWA) in the U.S.',
     'sets maximum contaminant levels for drinking water and requires public water system testing and reporting',
     ['bans all industrial discharge into rivers and lakes', 'requires states to reduce groundwater extraction', 'regulates air quality near water sources']),
    ('Biomagnification refers to',
     'the increasing concentration of persistent pollutants (e.g., DDT, mercury) at higher trophic levels',
     ['the accumulation of nutrients in soil over time', 'growth in population size over multiple generations', 'the increasing size of organisms at higher trophic levels']),
    ('ENSO (El Niño-Southern Oscillation) events affect global climate by',
     'shifting warm Pacific waters eastward (El Niño) or westward (La Niña), altering precipitation and temperature patterns globally',
     ['reversing Earth\'s rotation during peak solar years', 'changing the tilt of Earth\'s axis seasonally', 'increasing volcanic activity in the Pacific Ring of Fire']),
    ('The Clean Air Act regulates',
     'six criteria air pollutants including particulate matter, ozone, CO, NO₂, SO₂, and lead, and sets National Ambient Air Quality Standards',
     ['only indoor air quality in workplaces', 'greenhouse gas emissions only', 'water quality near industrial facilities']),
    ('A keystone species is one that',
     'has a disproportionately large effect on its ecosystem relative to its abundance, and its removal causes dramatic ecological change',
     ['is the most abundant species in an ecosystem', 'is only found in one geographic location', 'performs photosynthesis as the primary producer']),
    ('Non-renewable energy sources differ from renewable sources in that they',
     'form over millions of years and are depleted faster than they can be replenished',
     ['cannot be used to generate electricity', 'always produce more pollution than renewable sources', 'are only found in developing countries']),
    ('The Montreal Protocol (1987) was significant for environmental policy because it',
     'established international agreement to phase out ozone-depleting substances (CFCs), a model for global environmental cooperation',
     ['committed nations to reducing carbon emissions 50% by 2000', 'created the first international nuclear waste disposal standards', 'banned ocean dumping of plastic globally']),
    ('Carrying capacity in population ecology is the',
     'maximum population size a given environment can sustain indefinitely given available resources',
     ['maximum possible growth rate of a population', 'average population size over any 10-year period', 'number of individuals that can survive a single disaster']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 1,
        'title': 'Unit 1: The Living World — Ecosystems',
        'file': 'ap-environmental-science-1-unit-1-the-living-world-ecosystems.html',
        'desc': 'Energy flow, nutrient cycles, and ecosystem structure from producers to decomposers.',
        'gateway': [
            'Explain how energy flows through trophic levels.',
            'Describe the carbon, nitrogen, and phosphorus cycles.',
            'Distinguish producers, consumers, and decomposers.',
            'Calculate net primary productivity and energy transfer efficiency.',
        ],
        'lessons': [
            _l('Ecosystem Structure',
               [
                   _t('Biotic and Abiotic Factors', 'Ecosystems include living (biotic) and nonliving (abiotic) components that interact to sustain life.', 'Abiotic factors like temperature and pH are not living but strongly control biotic communities.', 'Identify biotic vs. abiotic components and predict how changes affect the ecosystem.'),
                   _t('Trophic Levels', 'Energy moves from producers (autotrophs) through primary, secondary, and tertiary consumers; only ~10% transfers per level.', 'The 10% rule is an approximation; actual efficiency varies by ecosystem.', 'Calculate energy available at each trophic level given primary productivity.'),
                   _t('Food Webs', 'Food webs show multiple feeding relationships; removing one species can cascade through the web.', 'Food chains are simplified; real systems are webs with many interconnections.', 'Predict consequences of removing a keystone species from a food web.'),
               ],
               [('producer (autotroph)', 'Organism that makes its own food via photosynthesis or chemosynthesis.'),
                ('consumer (heterotroph)', 'Organism that obtains energy by eating other organisms.'),
                ('decomposer', 'Organism (fungi, bacteria) that breaks down dead organic matter, returning nutrients to soil.'),
                ('trophic level', 'Position in a food chain based on feeding relationships.'),
                ('keystone species', 'Species with disproportionately large ecological impact relative to its abundance.')],
               ['Describe energy flow through trophic levels using the 10% rule.', 'Distinguish producers, consumers, and decomposers.', 'Predict cascading effects of species removal from a food web.'],
               ['Calculating energy available at higher trophic levels.', 'Interpreting food web diagrams.', 'Identifying keystone species and their removal effects.'],
               ['Khan Academy: Ecology', 'Bozeman Science: Ecosystems'],
               [('Which trophic level has the most energy?', ['Producers', 'Primary consumers', 'Secondary consumers', 'Tertiary consumers', 'Decomposers']),
                ('Approximately what percentage of energy is transferred between trophic levels?', ['10%', '1%', '50%', '90%', '100%']),
                ('A food web differs from a food chain because it:', ['Shows multiple feeding relationships', 'Has only one producer', 'Includes only carnivores', 'Ignores decomposers', 'Is simpler']),
                ('Removing a keystone species typically:', ['Causes cascading effects on other species', 'Has no effect on the ecosystem', 'Increases ecosystem stability', 'Only affects producers', 'Decreases biodiversity slightly']),
                ('Decomposers are important because they:', ['Return nutrients to the soil', 'Produce oxygen', 'Eat primary consumers', 'Fix nitrogen gas', 'Are the top of the food web']),
               ],
               [('Bozeman Science: Ecosystems', 'Covers trophic levels, food webs, and energy flow.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the 10% rule in energy transfer?', 'What is the role of decomposers in an ecosystem?', 'Why is a food web more realistic than a food chain?']
            ),
            _l('Energy Flow and Productivity',
               [
                   _t('Gross and Net Primary Productivity', 'GPP is total photosynthetic energy fixed; NPP = GPP − respiration by plants; NPP is energy available to consumers.', 'NPP, not GPP, determines how much energy is available to consumers.', 'Calculate NPP from GPP and respiration data; compare productivity across biomes.'),
                   _t('Ecosystem Energy Budget', 'Energy enters as sunlight, flows through trophic levels, and exits as heat; no energy is recycled (unlike matter).', 'Unlike matter, energy does not cycle — it flows in one direction and is lost as heat.', 'Explain why energy must continually enter an ecosystem while matter cycles.'),
                   _t('Productivity Limits', 'Temperature, light, water, and nutrient availability limit productivity in terrestrial and aquatic biomes.', 'Tropical rainforests have high NPP due to warmth and rain; tundra has low NPP despite sunlight in summer.', 'Identify the limiting factor for productivity in a described biome.'),
               ],
               [('gross primary productivity (GPP)', 'Total energy fixed by photosynthesis per unit time.'),
                ('net primary productivity (NPP)', 'Energy available to consumers: NPP = GPP − plant respiration.'),
                ('biomass', 'Total mass of living organic material in an area.'),
                ('limiting factor', 'Abiotic factor that most constrains growth or productivity.'),
                ('secondary productivity', 'Rate of energy storage by consumers (animals); lower than NPP due to inefficiency.')],
               ['Calculate NPP from GPP and respiration values.', 'Explain why energy flows unidirectionally while matter cycles.', 'Identify limiting factors for productivity in different biomes.'],
               ['Calculating energy available at each trophic level from NPP data.', 'Comparing productivity across biomes and explaining the differences.', 'Free-response: calculating biomass supported at higher trophic levels.'],
               ['Khan Academy: Primary Productivity', 'Bozeman Science: NPP'],
               [('NPP = GPP − ?', ['Plant respiration', 'Consumer respiration', 'Sunlight input', 'Decomposer activity', 'Evapotranspiration']),
                ('Which biome generally has the highest NPP?', ['Tropical rainforest', 'Desert', 'Tundra', 'Temperate grassland', 'Open ocean']),
                ('Why must energy continually enter ecosystems?', ['Energy exits as heat and cannot be recycled', 'Energy is destroyed by consumers', 'Matter is lost each trophic level', 'Nutrients leave the ecosystem', 'Decomposers consume all energy']),
                ('If GPP = 8000 kcal/m²/yr and plant respiration = 3200, NPP =', ['4800 kcal/m²/yr', '11200 kcal/m²/yr', '3200 kcal/m²/yr', '8000 kcal/m²/yr', '1600 kcal/m²/yr']),
                ('The main limiting factor for productivity in a desert is:', ['Water', 'Sunlight', 'Temperature', 'CO₂', 'Nitrogen']),
               ],
               [('Bozeman Science: NPP and GPP', 'Explains GPP, NPP, and productivity limits across biomes.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between GPP and NPP?', 'Why does energy not cycle the way matter does?', 'What limits productivity in the tundra?']
            ),
            _l('Biogeochemical Cycles',
               [
                   _t('Carbon Cycle', 'Carbon cycles through photosynthesis (atmosphere → biosphere), respiration and decomposition (biosphere → atmosphere), and ocean absorption.', 'Human burning of fossil fuels adds ancient stored carbon to the active cycle, disrupting the balance.', 'Trace carbon through the cycle and identify human impacts on each pathway.'),
                   _t('Nitrogen Cycle', 'N₂ is fixed by bacteria (or lightning) to NH₃/NH₄⁺, nitrified to NO₃⁻, used by plants, and denitrified back to N₂.', 'Plants cannot use N₂ directly; nitrogen fixation is the critical entry point.', 'Sequence the steps of nitrogen cycling and identify the organisms responsible.'),
                   _t('Phosphorus Cycle', 'Phosphorus cycles from rock (weathering) → soil/water → organisms → decomposition; there is no atmospheric reservoir.', 'Unlike carbon and nitrogen, phosphorus has no significant atmospheric form.', 'Explain why phosphorus is a limiting nutrient and how it enters aquatic systems.'),
               ],
               [('nitrogen fixation', 'Conversion of atmospheric N₂ to ammonia (NH₃) by bacteria such as Rhizobium.'),
                ('nitrification', 'Bacterial conversion of NH₃ to nitrite then nitrate (plant-available form).'),
                ('denitrification', 'Bacterial conversion of nitrate back to N₂ gas; removes nitrogen from soil.'),
                ('weathering', 'Physical and chemical breakdown of rock releasing minerals (including phosphorus).'),
                ('eutrophication', 'Excessive nutrient (N, P) enrichment of water causing algal blooms and oxygen depletion.')],
               ['Trace carbon through the major reservoirs and pathways.', 'Sequence nitrogen cycling steps and name responsible organisms.', 'Explain why phosphorus lacks an atmospheric reservoir and is often limiting.'],
               ['Identifying steps where human activity disrupts nutrient cycles.', 'Explaining eutrophication as a consequence of nutrient cycle disruption.', 'Comparing carbon, nitrogen, and phosphorus cycles.'],
               ['Khan Academy: Biogeochemical Cycles', 'Bozeman Science: Carbon and Nitrogen Cycles'],
               [('Nitrogen fixation converts N₂ into:', ['Ammonia (NH₃)', 'Nitrate (NO₃⁻)', 'N₂O', 'Urea', 'Nitric acid']),
                ('Which step in the nitrogen cycle removes nitrogen from soil?', ['Denitrification', 'Nitrification', 'Nitrogen fixation', 'Assimilation', 'Decomposition']),
                ('Unlike the carbon and nitrogen cycles, the phosphorus cycle lacks a significant:', ['Atmospheric reservoir', 'Aquatic reservoir', 'Soil reservoir', 'Biological component', 'Decomposer pathway']),
                ('Burning fossil fuels disrupts the carbon cycle by:', ['Adding ancient stored carbon to the active cycle', 'Removing carbon from the atmosphere', 'Increasing nitrogen fixation', 'Decreasing ocean absorption of CO₂', 'Speeding up the phosphorus cycle']),
                ('Eutrophication is caused by excess:', ['Nitrogen and phosphorus runoff', 'Carbon dioxide', 'Sediment', 'Acid rain', 'Methane']),
               ],
               [('Bozeman Science: Biogeochemical Cycles', 'Covers carbon, nitrogen, and phosphorus cycles in detail.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What organisms perform nitrogen fixation?', 'How does phosphorus enter aquatic ecosystems?', 'Explain how burning fossil fuels disrupts the carbon cycle.']
            ),
            _l('Aquatic and Terrestrial Biomes',
               [
                   _t('Terrestrial Biomes', 'Biomes are defined by climate (temperature and precipitation); major types include tropical rainforest, desert, grassland, temperate forest, taiga, and tundra.', 'Biomes are defined by climate, not geography — similar climates produce similar biomes on different continents.', 'Match climate conditions (precipitation × temperature graphs) to biome types.'),
                   _t('Aquatic Biomes', 'Marine biomes (open ocean, coral reefs, estuaries) and freshwater biomes (streams, lakes, wetlands) differ in salinity, productivity, and biodiversity.', 'Estuaries are among the most productive ecosystems due to nutrient inputs from both freshwater and marine sources.', 'Compare productivity and biodiversity of marine vs. freshwater biomes.'),
                   _t('Freshwater Zones', 'Lakes have littoral (near-shore), limnetic (open water), and profundal (deep, dark) zones; stratification changes seasonally.', 'Thermal stratification in summer limits nutrient mixing between surface and deep layers.', 'Describe lake zones and explain how seasonal turnover affects nutrient distribution.'),
               ],
               [('biome', 'Large-scale community defined by characteristic climate and vegetation.'),
                ('estuary', 'Transition zone where freshwater and saltwater mix; highly productive.'),
                ('littoral zone', 'Shallow near-shore area of a lake with rooted aquatic plants.'),
                ('thermocline', 'Layer of rapid temperature change with depth in a stratified lake.'),
                ('upwelling', 'Vertical movement of cold, nutrient-rich water to the ocean surface; supports high productivity.')],
               ['Match climate graphs to terrestrial biome types.', 'Compare productivity of marine, freshwater, and terrestrial biomes.', 'Explain lake stratification and seasonal turnover.'],
               ['Identifying biomes from climate data.', 'Explaining why estuaries are highly productive.', 'Describing how thermal stratification affects lake oxygen and nutrients.'],
               ['Khan Academy: Biomes', 'Bozeman Science: Biomes'],
               [('Which biome has the highest biodiversity?', ['Tropical rainforest', 'Temperate deciduous forest', 'Taiga', 'Desert', 'Tundra']),
                ('Estuaries are highly productive because:', ['They receive nutrients from freshwater and marine sources', 'They are very deep', 'They lack predators', 'They have high salinity', 'They have low temperatures']),
                ('The defining characteristic of a biome is its:', ['Climate (temperature and precipitation)', 'Latitude only', 'Soil type', 'Animal species', 'Human land use']),
                ('Lake thermal stratification in summer limits:', ['Nutrient mixing between deep and surface water', 'Sunlight penetration', 'Photosynthesis', 'Oxygen production', 'Fish populations']),
                ('Upwelling along coastlines causes high marine productivity because it:', ['Brings nutrients to the surface', 'Warms the water', 'Reduces salinity', 'Increases sunlight', 'Decreases wave action']),
               ],
               [('Bozeman Science: Biomes', 'Covers major terrestrial and aquatic biomes with climate charts.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What two climate variables most define terrestrial biomes?', 'Why are estuaries so productive?', 'What happens during seasonal lake turnover?']
            ),
        ],
        'unit_qs': [
            ('Which organisms are found at the base of every food chain?', ['Producers (autotrophs)', 'Herbivores', 'Carnivores', 'Decomposers', 'Omnivores']),
            ('If a prairie has NPP = 5000 kcal/m²/yr, how much energy is available to secondary consumers?', ['~50 kcal (10% × 10% × 5000)', '500 kcal', '50 kcal', '5000 kcal', '450 kcal']),
            ('Which nutrient cycle lacks an atmospheric reservoir?', ['Phosphorus', 'Carbon', 'Nitrogen', 'Sulfur', 'Oxygen']),
            ('Nitrifying bacteria convert:', ['Ammonia to nitrate', 'N₂ to ammonia', 'Nitrate to N₂', 'Organic N to ammonia', 'Nitrate to nitrous oxide']),
            ('Coral reefs are highly productive despite nutrient-poor water because:', ['Tight nutrient recycling within the reef community', 'Upwelling nearby', 'High water temperature', 'Freshwater input', 'Low predation']),
            ('Removing wolves from Yellowstone caused elk populations to overgraze streamside vegetation. This demonstrates:', ['Trophic cascade from a keystone species', 'Competitive exclusion', 'Eutrophication', 'Limiting factors', 'Biomagnification']),
            ('What biome would you find at high altitude near the equator?', ['Alpine/tundra (cold and low productivity)', 'Tropical rainforest', 'Desert', 'Taiga', 'Temperate grassland']),
            ('Human agricultural runoff causes eutrophication primarily because of excess:', ['Nitrogen and phosphorus', 'Carbon dioxide', 'Sediment', 'Pesticides', 'Heavy metals']),
            ('The 10% rule means a tertiary consumer obtains what fraction of producer energy?', ['0.1% (10% × 10% × 10%)', '10%', '1%', '30%', '0.01%']),
            ('Which process adds carbon to the atmosphere?', ['Cellular respiration and combustion', 'Photosynthesis', 'Nitrogen fixation', 'Weathering', 'Ocean absorption']),
        ],
    },
    {
        'num': 2,
        'title': 'Unit 2: The Living World — Biodiversity',
        'file': 'ap-environmental-science-2-unit-2-the-living-world-biodiversity.html',
        'desc': 'Ecosystem services, threats to biodiversity, island biogeography, and ecological succession.',
        'gateway': [
            'Explain the value of biodiversity and ecosystem services.',
            'Describe the major threats to biodiversity.',
            'Apply island biogeography theory to habitat fragments.',
            'Distinguish primary and secondary succession.',
        ],
        'lessons': [
            _l('Biodiversity and Ecosystem Services',
               [
                   _t('Types of Biodiversity', 'Biodiversity encompasses genetic, species, and ecosystem diversity; high diversity increases ecosystem resilience.', 'Biodiversity is more than just species count — genetic and ecosystem diversity matter equally.', 'Distinguish genetic, species, and ecosystem diversity and explain each\'s contribution to stability.'),
                   _t('Ecosystem Services', 'Provisioning (food, water), regulating (climate, flood control), cultural (recreation), and supporting services (nutrient cycling) all depend on biodiversity.', 'Ecosystem services are often undervalued until lost; economic valuation helps highlight their importance.', 'Categorize ecosystem services and connect them to biodiversity.'),
                   _t('Biodiversity Hotspots', 'Hotspots are regions with exceptional species richness and endemism that face significant habitat loss.', 'Hotspots cover only ~2.5% of Earth\'s surface but contain over 50% of the world\'s plant species.', 'Identify characteristics of biodiversity hotspots and explain why they are conservation priorities.'),
               ],
               [('genetic diversity', 'Variety of genes within a species; enables adaptation to change.'),
                ('species richness', 'Total number of different species in an area.'),
                ('ecosystem services', 'Benefits that humans derive from healthy ecosystems.'),
                ('endemic species', 'Species found only in a specific geographic area and nowhere else.'),
                ('biodiversity hotspot', 'Region with high species richness and endemism that is under threat.')],
               ['Distinguish three types of biodiversity.', 'Categorize ecosystem services by type.', 'Explain why hotspots are conservation priorities.'],
               ['Identifying ecosystem services from examples.', 'Connecting biodiversity loss to loss of ecosystem services.', 'Explaining why hotspot conservation is cost-effective.'],
               ['Khan Academy: Biodiversity', 'Bozeman Science: Biodiversity'],
               [('Which type of diversity allows species to adapt to new diseases?', ['Genetic diversity', 'Species richness', 'Ecosystem diversity', 'Structural diversity', 'Functional diversity']),
                ('Flood control by wetlands is an example of a __ ecosystem service.', ['Regulating', 'Provisioning', 'Cultural', 'Supporting', 'Extractive']),
                ('A biodiversity hotspot must have:', ['High endemism and significant habitat loss', 'Only rainforest', 'No human impact', 'More than 1000 species', 'Government protection']),
                ('Losing a pollinator species primarily affects which ecosystem service?', ['Provisioning (food production)', 'Regulating (climate)', 'Cultural (recreation)', 'Supporting (soil formation)', 'Extractive (mining)']),
                ('Genetic diversity within a crop population is important because:', ['It provides resistance to disease and pests', 'It increases yield immediately', 'It reduces water needs', 'It makes harvesting easier', 'It eliminates soil erosion']),
               ],
               [('Bozeman Science: Biodiversity', 'Covers types of biodiversity, ecosystem services, and hotspots.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What are the three types of biodiversity?', 'Give one example each of provisioning and regulating ecosystem services.', 'What makes a biodiversity hotspot a conservation priority?']
            ),
            _l('Threats to Biodiversity',
               [
                   _t('HIPPO Threats', 'The main threats to biodiversity are Habitat loss, Invasive species, Pollution, Population growth, and Overharvesting (HIPPO); habitat loss is the leading cause.', 'Climate change is increasingly recognized as a sixth major threat, sometimes added to form HIPPO+C.', 'Rank and explain the HIPPO threats; identify the most significant cause of biodiversity loss.'),
                   _t('Habitat Fragmentation', 'Fragmentation breaks continuous habitat into patches, isolating populations and reducing genetic diversity (edge effects increase, interior habitat decreases).', 'Small, isolated fragments support fewer species than one large equivalent area.', 'Explain edge effects and how corridors mitigate fragmentation.'),
                   _t('Invasive Species', 'Invasive species outcompete natives by lacking predators, parasites, and competitors in their new environment.', 'Not all introduced species become invasive; invasiveness depends on traits and available niches.', 'Describe how invasive species affect native communities and identify examples.'),
               ],
               [('habitat fragmentation', 'Breaking large habitat into smaller, isolated patches.'),
                ('edge effect', 'Altered conditions at the boundary of two habitat types; often unfavorable for interior species.'),
                ('invasive species', 'Non-native organism that spreads rapidly and harms native species or ecosystems.'),
                ('wildlife corridor', 'Strip of habitat connecting isolated fragments; allows gene flow and migration.'),
                ('overharvesting', 'Removing individuals from a population faster than they can reproduce.')],
               ['Identify and rank HIPPO threats to biodiversity.', 'Explain how habitat fragmentation reduces biodiversity.', 'Describe mechanisms by which invasive species harm native ecosystems.'],
               ['Applying HIPPO framework to a case study.', 'Explaining why wildlife corridors help fragmented populations.', 'Evaluating management strategies for invasive species.'],
               ['Khan Academy: Threats to Biodiversity', 'Bozeman Science: HIPPO'],
               [('The leading cause of biodiversity loss globally is:', ['Habitat loss and destruction', 'Invasive species', 'Overharvesting', 'Pollution', 'Climate change']),
                ('Edge effects from habitat fragmentation typically:', ['Increase stress on interior species by changing microclimate', 'Increase interior habitat', 'Have no effect on species', 'Benefit all species equally', 'Reduce invasive species']),
                ('Invasive species succeed in new environments primarily because:', ['They lack natural predators and competitors', 'They are larger than native species', 'They are better adapted to all climates', 'They reproduce more slowly', 'They require more resources']),
                ('A wildlife corridor helps fragmented populations by:', ['Allowing gene flow and migration between patches', 'Eliminating edge effects', 'Increasing fragment size', 'Removing invasive species', 'Reducing human impact']),
                ('Overharvesting is best controlled by:', ['Catch limits and protected areas', 'Introducing more predators', 'Increasing habitat fragmentation', 'Adding invasive species', 'Removing wildlife corridors']),
               ],
               [('Bozeman Science: Threats to Biodiversity', 'Covers HIPPO threats, fragmentation, and invasive species.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What does HIPPO stand for?', 'What is an edge effect?', 'Why do invasive species often outcompete native species?']
            ),
            _l('Island Biogeography',
               [
                   _t('Species-Area Relationship', 'Larger islands support more species because they have more habitat and can sustain larger populations; S ∝ A^z (z ≈ 0.25).', 'The species-area relationship applies to habitat "islands" like forest fragments, not just oceanic islands.', 'Predict species number from island area using the species-area relationship.'),
                   _t('Immigration and Extinction Rates', 'Species richness equilibrium occurs where immigration rate equals extinction rate; closer/larger islands reach higher equilibria.', 'Equilibrium is dynamic — species composition changes even when richness stays constant.', 'Use the immigration-extinction graph to predict equilibrium species number.'),
                   _t('Application to Conservation', 'Island biogeography theory predicts that larger and less-isolated nature reserves support more species; design should maximize size and connectivity.', 'One large reserve is generally better than several small reserves of equal total area (though debate continues).', 'Apply island biogeography principles to reserve design decisions.'),
               ],
               [('island biogeography', 'Theory predicting species richness on islands based on area and isolation.'),
                ('species-area relationship', 'Larger areas support more species; S ∝ A^z.'),
                ('immigration rate', 'Rate at which new species colonize an island; higher for closer islands.'),
                ('extinction rate', 'Rate at which species disappear from an island; lower on larger islands.'),
                ('equilibrium species number', 'Stable number of species where immigration = extinction rates.')],
               ['Apply the species-area relationship to predict species richness.', 'Interpret immigration-extinction equilibrium diagrams.', 'Apply island biogeography to conservation reserve design.'],
               ['Comparing two nature reserves using island biogeography principles.', 'Predicting effect of increasing isolation on extinction rate.', 'Explaining the SLOSS debate (Single Large Or Several Small reserves).'],
               ['Khan Academy: Island Biogeography', 'Bozeman Science: Island Biogeography'],
               [('According to species-area relationship, doubling island area:', ['Increases species number (S ∝ A^0.25)', 'Doubles species number', 'Has no effect on species', 'Halves extinction rate', 'Doubles immigration rate']),
                ('Species richness equilibrium on an island occurs when:', ['Immigration rate equals extinction rate', 'Immigration rate is zero', 'Extinction rate is zero', 'Island area increases', 'Species number reaches maximum']),
                ('A large island closer to the mainland has a higher equilibrium richness because:', ['Higher immigration, lower extinction', 'Higher extinction, lower immigration', 'Lower immigration, higher extinction', 'Same immigration and extinction', 'Larger species only']),
                ('Island biogeography applies to nature reserves because:', ['Reserves are habitat islands surrounded by inhospitable land', 'Reserves are on oceanic islands', 'All reserves are the same size', 'Reserves have no edge effects', 'Immigration is irrelevant to reserves']),
                ('Which reserve design best maximizes species richness?', ['One large connected reserve', 'Many small scattered reserves', 'Reserves with no corridors', 'Fragmented reserves', 'Reserves far from each other']),
               ],
               [('Bozeman Science: Island Biogeography', 'Covers species-area relationship and equilibrium theory.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['State the species-area relationship in words.', 'What happens to extinction rate as an island gets larger?', 'How does island biogeography theory inform reserve design?']
            ),
            _l('Ecological Succession',
               [
                   _t('Primary Succession', 'Primary succession begins on bare rock with no soil; pioneer species (lichens, mosses) break down rock and build soil over centuries.', 'Primary succession does not start from existing soil — this is the key distinction from secondary succession.', 'Describe the sequence of primary succession from bare rock to climax community.'),
                   _t('Secondary Succession', 'Secondary succession occurs after disturbance on land that retains soil; it is faster than primary succession because soil and seed banks remain.', 'Secondary succession does not restore the exact original community — disturbance history matters.', 'Explain why secondary succession is faster and predict the successional stages after abandonment.'),
                   _t('Climax Communities and Disturbance', 'Climax community is the stable end-state of succession for a given climate; disturbance resets succession.', 'The climax community concept is idealized — most ecosystems exist in shifting mosaics maintained by disturbances.', 'Explain the role of fire and other disturbances in maintaining ecosystem diversity.'),
               ],
               [('primary succession', 'Succession beginning on bare substrate with no existing soil.'),
                ('secondary succession', 'Succession on disturbed land where soil remains intact.'),
                ('pioneer species', 'First colonizers of bare or disturbed habitat; often hardy generalists.'),
                ('climax community', 'Theoretically stable, self-sustaining community at the end of succession.'),
                ('disturbance', 'Event that disrupts an ecosystem and resets or redirects succession.')],
               ['Distinguish primary and secondary succession with examples.', 'Identify pioneer species and explain their role.', 'Explain how fire maintains certain ecosystems.'],
               ['Sequencing successional stages after a volcanic eruption or farm abandonment.', 'Comparing timescales of primary vs. secondary succession.', 'Analyzing intermediate disturbance hypothesis.'],
               ['Khan Academy: Succession', 'Bozeman Science: Ecological Succession'],
               [('Primary succession begins on:', ['Bare rock with no soil', 'Burned forest floor', 'Abandoned agricultural field', 'Drained lake bed', 'Logged forest']),
                ('Why is secondary succession faster than primary succession?', ['Soil and seed bank remain', 'Climate is warmer', 'Pioneer species are larger', 'Disturbance is less severe', 'More rain is available']),
                ('The first colonizers in primary succession are called:', ['Pioneer species', 'Climax species', 'K-strategists', 'Secondary consumers', 'Invasive species']),
                ('Fire-adapted ecosystems (like savannas) often require periodic fire to:', ['Prevent succession to forest and maintain grassland', 'Kill all species equally', 'Add nutrients through decomposition only', 'Destroy all plant life', 'Increase rainfall']),
                ('The climax community is best described as:', ['Stable community suited to the local climate', 'Always a forest', 'The first stage of succession', 'A single species population', 'An unstable transitional state']),
               ],
               [('Bozeman Science: Succession', 'Covers primary succession, secondary succession, and climax communities.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between primary and secondary succession?', 'Why are pioneer species important?', 'How does fire maintain savanna ecosystems?']
            ),
        ],
        'unit_qs': [
            ('The three types of biodiversity are:', ['Genetic, species, and ecosystem diversity', 'Plant, animal, and fungal diversity', 'Marine, terrestrial, and freshwater diversity', 'Producer, consumer, and decomposer diversity', 'Local, regional, and global diversity']),
            ('Habitat loss is the leading cause of biodiversity loss. The second most significant threat is:', ['Invasive species', 'Pollution', 'Climate change', 'Overharvesting', 'Disease']),
            ('A wildlife corridor primarily addresses the problem of:', ['Habitat fragmentation isolating populations', 'Invasive species spread', 'Overharvesting', 'Pollution', 'Climate change']),
            ('According to island biogeography, a nature reserve that is closer to other natural areas will have:', ['Higher immigration rate and higher species richness', 'Lower immigration rate', 'Higher extinction rate', 'Smaller species only', 'No change in species richness']),
            ('Pioneer species in primary succession include:', ['Lichens and mosses', 'Oak trees', 'Grasses only', 'Large mammals', 'Decomposers only']),
            ('Ecosystem services include all of the following EXCEPT:', ['Mining fossil fuels from the Earth', 'Flood control by wetlands', 'Carbon storage in forests', 'Pollination of crops', 'Water purification by wetlands']),
            ('Eutrophication results from:', ['Excess nutrient runoff (N and P)', 'Acid rain', 'Oil spills', 'Sedimentation', 'Thermal pollution']),
            ('A forest fragment of 100 ha will support __ species than one of 10 ha.', ['More', 'Fewer', 'The same number of', 'Twice as many', 'Half as many']),
            ('Climax community is determined primarily by:', ['Regional climate', 'Soil type alone', 'Human land use', 'Pioneer species composition', 'Disturbance frequency']),
            ('An endemic species is one that:', ['Is found only in one specific geographic area', 'Is invasive in multiple regions', 'Has been introduced by humans', 'Is at risk of extinction everywhere', 'Can live in any biome']),
        ],
    },
    {
        'num': 3,
        'title': 'Unit 3: Populations',
        'file': 'ap-environmental-science-3-unit-3-populations.html',
        'desc': 'Population dynamics, carrying capacity, survivorship curves, and human population growth.',
        'gateway': [
            'Calculate population growth rate from birth and death rates.',
            'Explain logistic vs. exponential growth.',
            'Describe r- and K-selected life history strategies.',
            'Analyze human population demographics using age-structure diagrams.',
        ],
        'lessons': [
            _l('Population Growth Models',
               [
                   _t('Exponential Growth', 'Populations grow exponentially when resources are unlimited; J-shaped curve. Growth rate: dN/dt = rN.', 'Exponential growth is unsustainable in nature because resources are finite.', 'Calculate population size after a given time using exponential growth; identify conditions where it occurs.'),
                   _t('Logistic Growth', 'Logistic growth slows as population approaches carrying capacity (K); S-shaped curve. dN/dt = rN(K−N)/K.', 'Populations don\'t always reach a smooth K — they can overshoot and oscillate around K.', 'Predict population trajectory near K; identify the inflection point where growth rate is maximum.'),
                   _t('Carrying Capacity', 'K is the maximum population size a habitat can sustain indefinitely based on resource availability; environmental factors determine K.', 'K is not fixed — it changes if resources improve or degrade.', 'Explain what limits K and predict how resource changes shift K.'),
               ],
               [('exponential growth', 'Population growth at a constant rate; produces a J-shaped curve.'),
                ('logistic growth', 'Growth that slows as population approaches carrying capacity; S-shaped curve.'),
                ('carrying capacity (K)', 'Maximum population size sustainable by available resources.'),
                ('intrinsic rate of increase (r)', 'Maximum growth rate per capita under ideal conditions.'),
                ('overshoot', 'Temporary population size exceeding carrying capacity, followed by die-off.')],
               ['Distinguish exponential and logistic growth with graphs.', 'Calculate maximum growth rate in logistic model.', 'Explain what determines carrying capacity.'],
               ['Interpreting population growth graphs (J vs. S curve).', 'Identifying where on the logistic curve growth rate is maximum (at N = K/2).', 'Predicting overshoot and crash scenarios.'],
               ['Khan Academy: Population Growth', 'Bozeman Science: Population Growth'],
               [('Exponential population growth produces a:', ['J-shaped curve', 'S-shaped curve', 'Bell curve', 'Flat line', 'Declining curve']),
                ('In the logistic growth model, growth rate is maximum when N =', ['K/2', 'K', '0', 'r', '2K']),
                ('Carrying capacity is determined by:', ['Resource availability (food, water, space)', 'Birth rate only', 'Death rate only', 'Population size at time 0', 'Species body size']),
                ('A population that exceeds K will likely:', ['Decline due to resource limitation', 'Continue growing exponentially', 'Stabilize immediately', 'Begin primary succession', 'Evolve a higher K']),
                ('The logistic growth equation includes a term (K−N)/K because:', ['It slows growth as N approaches K', 'It increases growth near K', 'It measures death rate', 'It accounts for immigration', 'It represents r']),
               ],
               [('Bozeman Science: Population Growth', 'Covers exponential and logistic models with examples.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between J-shaped and S-shaped population curves?', 'At what population size is logistic growth rate maximum?', 'What happens when a population overshoots K?']
            ),
            _l('Life History Strategies',
               [
                   _t('r-selected Species', 'r-selected species: short lifespan, rapid reproduction, many offspring with little parental care, early maturity (weeds, insects, small mammals).', 'r-selected species thrive in unstable, unpredictable environments where rapid reproduction is advantageous.', 'Identify r-selected traits and explain when this strategy is advantageous.'),
                   _t('K-selected Species', 'K-selected species: long lifespan, slow reproduction, few offspring with high parental investment, late maturity (elephants, whales, humans).', 'K-selected species are more vulnerable to extinction because they reproduce slowly.', 'Identify K-selected traits and explain vulnerability to overharvesting.'),
                   _t('Survivorship Curves', 'Type I (humans, elephants): most die old. Type II (birds, squirrels): constant mortality. Type III (fish, insects): most die young.', 'Survivorship curves describe population-level patterns, not individual lifespan.', 'Classify species by survivorship curve type and relate to r/K strategy.'),
               ],
               [('r-selected species', 'Adapted to unstable environments; produce many offspring with little parental care.'),
                ('K-selected species', 'Adapted to stable environments; produce few offspring with high parental investment.'),
                ('Type I survivorship', 'Most individuals survive to old age; late mortality (large mammals).'),
                ('Type II survivorship', 'Constant mortality rate throughout life (many birds).'),
                ('Type III survivorship', 'Most die young; few survive to adulthood (fish, insects, plants).')],
               ['Distinguish r- and K-selected life history strategies.', 'Classify species by survivorship curve type.', 'Explain why K-selected species are more vulnerable to extinction.'],
               ['Predicting which strategy is advantageous in stable vs. disturbed environments.', 'Matching species to survivorship curve types.', 'Connecting K-selection to vulnerability in overharvesting scenarios.'],
               ['Khan Academy: Life History', 'Bozeman Science: r and K Selection'],
               [('Which of the following is most r-selected?', ['Dandelion', 'Blue whale', 'Elephant', 'Condor', 'Human']),
                ('K-selected species are more vulnerable to extinction because:', ['They reproduce slowly and recover slowly from population declines', 'They have too many offspring', 'They live in unstable environments', 'They have no predators', 'They lack genetic diversity']),
                ('A Type III survivorship curve applies to species that:', ['Produce many offspring; most die young', 'Have constant mortality throughout life', 'Live to old age', 'Are K-selected', 'Have few offspring']),
                ('Organisms with high parental investment typically:', ['Have few offspring and long lifespans', 'Have many offspring and short lifespans', 'Show Type III survivorship', 'Are r-selected', 'Die before reproducing']),
                ('A meadow weed and a whale both produce offspring. Which is more r-selected?', ['The weed (many small seeds, no parental care)', 'The whale (one calf, years of care)', 'Neither — they are equally r-selected', 'Both are K-selected', 'The whale (larger body size)']),
               ],
               [('Bozeman Science: r and K Selection', 'Explains life history strategies and survivorship curves.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['List three traits of r-selected species.', 'Why are elephants considered K-selected?', 'What does a Type I survivorship curve look like?']
            ),
            _l('Human Population Growth',
               [
                   _t('Demographic Transition Model', 'The DTM shows four stages: pre-industrial (high birth/death), transitional (declining death, high birth), industrial (declining birth), and post-industrial (low birth/death; stable or declining population).', 'Countries can stall in Stage 2, experiencing rapid population growth as death rates fall before birth rates do.', 'Identify a country\'s DTM stage from birth/death rate data and predict population trajectory.'),
                   _t('Age-Structure Diagrams', 'Age-structure pyramids show population by age and sex; wide base = rapid growth, uniform = stable, narrow base = declining.', 'Age-structure diagrams show future trends, not current growth rate.', 'Interpret age-structure diagrams to predict future population growth.'),
                   _t('Total Fertility Rate and Population Momentum', 'Replacement-level TFR ≈ 2.1 in developed countries; population momentum means growth continues even after TFR drops to replacement due to a large young cohort.', 'Even if TFR reaches replacement, population keeps growing for decades — this is momentum.', 'Explain how population momentum and age structure affect future population size.'),
               ],
               [('demographic transition model (DTM)', 'Model showing stages of population growth as societies develop economically.'),
                ('total fertility rate (TFR)', 'Average number of children a woman has in her lifetime.'),
                ('replacement-level fertility', 'TFR at which population size remains stable (~2.1 in developed countries).'),
                ('population momentum', 'Continued population growth after TFR drops to replacement, due to large young cohort.'),
                ('age-structure diagram', 'Bar graph showing population distribution by age and sex; predicts future growth.')],
               ['Identify DTM stages and predict population change.', 'Interpret age-structure diagrams for growth trend.', 'Explain population momentum.'],
               ['Classifying countries by DTM stage from data.', 'Predicting growth from age-structure diagrams.', 'Explaining why global population keeps growing despite falling TFR in many countries.'],
               ['Khan Academy: Human Population', 'Bozeman Science: Human Population'],
               [('In the demographic transition model, Stage 2 is characterized by:', ['Falling death rates but high birth rates → rapid population growth', 'Both high birth and death rates', 'Both low birth and death rates', 'Falling birth rates and stable death rates', 'Zero population growth']),
                ('A wide-base age-structure pyramid indicates:', ['Rapid population growth', 'Stable population', 'Declining population', 'High death rates among youth', 'Low birth rates']),
                ('Replacement-level fertility in developed countries is approximately:', ['2.1 children per woman', '1.0', '3.5', '4.0', '2.5']),
                ('Population momentum explains why:', ['Population keeps growing after TFR reaches replacement due to large youth cohort', 'Population declines as soon as TFR drops', 'Old countries have the most births', 'Birth rates always exceed death rates', 'Death rates control population more than birth rates']),
                ('Which factor most strongly promotes transition from Stage 2 to Stage 3 of the DTM?', ['Increased access to education and family planning for women', 'Higher death rates', 'Food scarcity', 'Disease outbreaks', 'Increased infant mortality']),
               ],
               [('Bozeman Science: Human Population', 'Covers DTM, age-structure diagrams, and population momentum.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What are the four stages of the demographic transition model?', 'What does a narrow base on an age-structure pyramid indicate?', 'What is population momentum?']
            ),
            _l('Factors Limiting Population Growth',
               [
                   _t('Density-Dependent Factors', 'Density-dependent limiting factors (disease, predation, competition) become more intense as population density increases.', 'Not all disease outbreaks are density-dependent — some spread regardless of density.', 'Identify density-dependent factors and predict how they change with population density.'),
                   _t('Density-Independent Factors', 'Density-independent factors (frost, drought, fire) affect populations regardless of their size.', 'Natural disasters are the classic density-independent factor — they kill the same proportion at any density.', 'Distinguish density-dependent from density-independent factors and predict population impact.'),
                   _t('Reproductive Strategies and Population Management', 'Maximum sustainable yield (MSY) for harvested populations = harvest at K/2 where logistic growth rate is highest.', 'Harvesting beyond MSY drives population toward extinction; below MSY wastes potential.', 'Calculate MSY and explain the rationale for harvesting at population level K/2.'),
               ],
               [('density-dependent factor', 'Limiting factor whose effect increases with population density (disease, competition, predation).'),
                ('density-independent factor', 'Limiting factor whose effect is the same regardless of population density (drought, frost, fire).'),
                ('maximum sustainable yield (MSY)', 'Largest harvest that can be taken indefinitely; occurs at N = K/2.'),
                ('intraspecific competition', 'Competition between members of the same species for the same resources.'),
                ('predator-prey cycle', 'Oscillating relationship between predator and prey populations (e.g., lynx-hare).')],
               ['Distinguish density-dependent and density-independent limiting factors.', 'Explain the concept of maximum sustainable yield.', 'Analyze predator-prey cycle dynamics.'],
               ['Classifying limiting factors as density-dependent or independent.', 'Applying MSY to fisheries management scenarios.', 'Interpreting predator-prey cycle graphs.'],
               ['Khan Academy: Limiting Factors', 'Bozeman Science: Population Limiting Factors'],
               [('Which is a density-dependent limiting factor?', ['Disease spread through crowded populations', 'A hurricane destroying habitat', 'A drought reducing water', 'A volcanic eruption', 'A sudden cold snap']),
                ('A hard frost killing 20% of a population regardless of density is a:', ['Density-independent factor', 'Density-dependent factor', 'Carrying capacity change', 'Biotic factor', 'Competitive exclusion event']),
                ('Maximum sustainable yield occurs at population size:', ['K/2', 'K', '0', 'r', '2K']),
                ('In a predator-prey cycle, prey population peaks:', ['Just before predator population peaks', 'After predator peak', 'At the same time as predator', 'When predators are absent', 'At carrying capacity']),
                ('Overfishing is problematic because:', ['It drives populations below MSY and can cause collapse', 'It increases carrying capacity', 'It reduces disease', 'It increases density-independent mortality', 'It increases genetic diversity']),
               ],
               [('Bozeman Science: Population Limiting Factors', 'Covers density-dependent and independent factors and MSY.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Give two examples each of density-dependent and density-independent factors.', 'Why is maximum sustainable yield found at K/2?', 'Describe the pattern of a predator-prey cycle.']
            ),
        ],
        'unit_qs': [
            ('A population growing at its maximum logistic rate is at population size:', ['K/2', 'K', '0', 'r/K', '2K']),
            ('Which pair of organisms are both K-selected?', ['Elephant and blue whale', 'Dandelion and house fly', 'Mosquito and weed', 'Bacteria and yeast', 'Salmon and frog']),
            ('A country with a TFR of 1.5 is in DTM Stage:', ['Stage 4 (post-industrial, declining)', 'Stage 1 (pre-industrial)', 'Stage 2 (transitional)', 'Stage 3 (industrial)', 'Stage 0 (pre-agricultural)']),
            ('Population momentum means:', ['Population grows even after TFR drops to replacement because of large youth cohort', 'Growth rate is constant regardless of K', 'Death rate always equals birth rate', 'Age structure has no effect on future growth', 'Population shrinks immediately when TFR < 2.1']),
            ('Which survivorship curve applies to most fish species?', ['Type III (most die young)', 'Type I (most survive to old age)', 'Type II (constant mortality)', 'Type IV (not applicable)', 'Type I for some populations']),
            ('Carrying capacity is NOT changed by:', ['The intrinsic growth rate (r) of a species', 'Deforestation reducing habitat', 'Climate change altering food availability', 'Introduction of a new pathogen', 'Human water extraction']),
            ('In the logistic growth equation, when N = K:', ['Growth rate = 0', 'Growth rate is maximum', 'Growth rate = r', 'Population doubles', 'K increases']),
            ('A wide-based age pyramid compared to a narrow-based one suggests:', ['More rapid future population growth', 'Population decline', 'Stable population', 'High death rates at all ages', 'Low birth rates']),
            ('Which DTM stage has the highest rate of population growth?', ['Stage 2 (death rates fall, birth rates still high)', 'Stage 1', 'Stage 3', 'Stage 4', 'Stage 0']),
            ('Intraspecific competition intensifies as population density increases; this makes it a:', ['Density-dependent factor', 'Density-independent factor', 'Abiotic factor', 'Climatic factor', 'Biotic but density-independent factor']),
        ],
    },
    {
        'num': 4,
        'title': 'Unit 4: Earth Systems and Resources',
        'file': 'ap-environmental-science-4-unit-4-earth-systems-and-resources.html',
        'desc': 'Earth\'s geologic processes, soil formation, water systems, and atmosphere.',
        'gateway': [
            'Explain plate tectonic processes and their environmental consequences.',
            'Describe soil formation and properties relevant to agriculture.',
            'Trace water through the hydrologic cycle.',
            'Explain the role of the atmosphere in climate and weather.',
        ],
        'lessons': [
            _l('Earth\'s Geologic Systems',
               [
                   _t('Plate Tectonics', 'Tectonic plate movement causes earthquakes, volcanoes, and mountain building; driven by convection in the mantle.', 'Plate tectonics operates over millions of years but causes sudden events (earthquakes) at plate boundaries.', 'Match tectonic boundary type (convergent, divergent, transform) to geological features.'),
                   _t('Volcanoes and Environmental Effects', 'Volcanic eruptions release CO₂, SO₂, and ash; large eruptions can cause short-term global cooling by blocking sunlight.', 'Volcanic eruptions add CO₂ to the atmosphere, but the total amount is small compared to human emissions.', 'Describe how volcanic eruptions affect climate and soils.'),
                   _t('Earthquakes and Tsunamis', 'Earthquakes along fault lines release energy; tsunamis are generated by underwater earthquakes displacing water.', 'Tsunamis are not tidal waves — they are generated by seismic activity, not tides.', 'Explain how earthquakes and tsunamis pose environmental and human risks.'),
               ],
               [('plate tectonics', 'Theory that Earth\'s lithosphere is divided into moving plates driven by mantle convection.'),
                ('convergent boundary', 'Where two plates move toward each other; produces subduction zones, mountains, or volcanoes.'),
                ('divergent boundary', 'Where two plates move apart; produces mid-ocean ridges or rift valleys.'),
                ('transform boundary', 'Where two plates slide past each other; produces earthquakes (e.g., San Andreas Fault).'),
                ('subduction', 'Process where one tectonic plate slides beneath another into the mantle.')],
               ['Match plate boundary types to geological features.', 'Explain volcanic environmental effects (cooling, soil enrichment).', 'Describe how tsunamis form and their environmental impacts.'],
               ['Identifying boundary types from descriptions of geological features.', 'Explaining why volcanic soils are fertile.', 'Comparing environmental risks at different plate boundaries.'],
               ['Khan Academy: Plate Tectonics', 'Bozeman Science: Earth Systems'],
               [('A convergent boundary between two oceanic plates produces:', ['Volcanic islands and trenches', 'Mid-ocean ridges', 'Mountain ranges only', 'Rift valleys', 'Transform faults']),
                ('Large volcanic eruptions cause short-term global cooling by:', ['Injecting SO₂ and ash that block sunlight', 'Releasing large amounts of CO₂', 'Absorbing solar radiation', 'Melting ice caps', 'Increasing cloud cover']),
                ('A transform boundary is characterized by:', ['Plates sliding past each other; earthquakes common', 'Plates colliding; mountains form', 'Plates separating; new crust forms', 'One plate subducting under another', 'Volcanic activity only']),
                ('Volcanic soils (Andisols) are often very fertile because:', ['Volcanic ash weathers into nutrient-rich mineral soil', 'They lack clay', 'They are very dry', 'They have no organic matter', 'They are near the ocean']),
                ('Tsunamis are generated by:', ['Underwater earthquakes displacing ocean water', 'Strong winds over deep ocean', 'Tidal forces from the moon', 'Volcanic eruptions above sea level', 'Hurricane storm surges']),
               ],
               [('Bozeman Science: Plate Tectonics', 'Covers boundary types and environmental consequences.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What drives plate movement?', 'Why do large volcanic eruptions cool climate temporarily?', 'How does a tsunami form?']
            ),
            _l('Soil Formation and Properties',
               [
                   _t('Soil Formation (Pedogenesis)', 'Soil forms from parent material through weathering + organic matter addition over centuries; influenced by climate, organisms, topography, and time.', 'Soil formation takes hundreds to thousands of years; it is a nonrenewable resource on human timescales.', 'Identify factors that affect rate of soil formation and explain why soil is considered nonrenewable.'),
                   _t('Soil Horizons', 'Soil profile includes O (organic litter), A (topsoil, humus-rich), E (eluviated), B (subsoil, accumulated minerals), C (parent material), and R (bedrock) horizons.', 'Topsoil (A horizon) is most important for agriculture; erosion removes the most fertile layer.', 'Identify soil horizons and explain how erosion threatens agricultural productivity.'),
                   _t('Soil Properties', 'Soil texture (sand, silt, clay proportions) determines drainage and nutrient retention; loam (balanced texture) is ideal for agriculture. Organic matter and pH also affect fertility.', 'Clay soils hold more nutrients but drain poorly; sandy soils drain quickly but hold few nutrients.', 'Predict soil drainage and fertility from texture; explain how pH affects nutrient availability.'),
               ],
               [('pedogenesis', 'Process of soil formation from parent material over time.'),
                ('humus', 'Decomposed organic matter in soil; improves water retention and nutrient availability.'),
                ('soil horizon', 'Distinct layer in a soil profile (O, A, E, B, C, R horizons).'),
                ('loam', 'Balanced mixture of sand, silt, and clay; ideal agricultural soil texture.'),
                ('soil erosion', 'Removal of topsoil by wind or water; major threat to agricultural productivity.')],
               ['Describe factors controlling soil formation rate.', 'Identify soil horizons and their importance.', 'Relate soil texture to drainage and fertility.'],
               ['Identifying threats to soil quality (erosion, compaction, salinization).', 'Explaining why loam is ideal for farming.', 'Calculating erosion consequences for agricultural productivity.'],
               ['Khan Academy: Soil', 'Bozeman Science: Soil'],
               [('The most fertile layer of a soil profile is the:', ['A horizon (topsoil)', 'B horizon (subsoil)', 'C horizon (parent material)', 'R horizon (bedrock)', 'O horizon (leaf litter)']),
                ('Soil erosion is most damaging because it removes:', ['The nutrient-rich A horizon', 'Bedrock only', 'Subsoil nutrients', 'Water from soil', 'Clay from B horizon']),
                ('Loam is considered ideal for agriculture because it:', ['Balances drainage and nutrient retention', 'Contains only clay', 'Has no organic matter', 'Drains immediately', 'Is found only in tropical regions']),
                ('Which factor most speeds up soil formation?', ['Warm, moist climate with abundant vegetation', 'Cold, dry climate', 'Hard, resistant parent rock', 'No vegetation', 'High elevation']),
                ('Clay soils have poor drainage because:', ['Clay particles are small and tightly packed, leaving little pore space', 'Clay has no organic matter', 'Clay is found only in subsoil', 'Clay drains through bedrock quickly', 'Clay repels water']),
               ],
               [('Bozeman Science: Soil', 'Covers soil horizons, texture, and formation.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the A horizon?', 'Why is soil considered a nonrenewable resource?', 'How does soil texture affect water retention?']
            ),
            _l('The Hydrologic Cycle',
               [
                   _t('Hydrologic Cycle Pathways', 'Water cycles through evaporation, transpiration, condensation, precipitation, runoff, infiltration, and groundwater flow; solar energy and gravity drive the cycle.', 'Transpiration (water released by plants) is often underappreciated but can exceed evaporation in forested areas.', 'Trace water through all hydrologic cycle pathways and identify the driving forces.'),
                   _t('Groundwater and Aquifers', 'Aquifers store groundwater in porous rock; recharge depends on infiltration. Overdraft (pumping faster than recharge) depletes aquifers and can cause land subsidence.', 'Once an aquifer is depleted, recharge can take thousands of years.', 'Explain aquifer recharge, overdraft, and consequences of groundwater depletion.'),
                   _t('Freshwater Availability', 'Only ~2.5% of Earth\'s water is fresh; most is locked in glaciers. Surface water and groundwater are the usable sources. Agriculture accounts for ~70% of global freshwater withdrawals.', 'Despite abundant total water, freshwater is unevenly distributed and often over-exploited.', 'Identify major human uses of freshwater and the consequences of over-extraction.'),
               ],
               [('evapotranspiration', 'Combined water loss from evaporation and plant transpiration.'),
                ('aquifer', 'Underground layer of porous rock or sediment storing groundwater.'),
                ('infiltration', 'Water moving from the surface down through soil into the water table.'),
                ('water table', 'Upper boundary of the saturated zone in soil or rock.'),
                ('overdraft', 'Pumping groundwater faster than it is naturally recharged.')],
               ['Trace water through the hydrologic cycle.', 'Explain aquifer recharge and consequences of overdraft.', 'Identify major freshwater uses and threats to availability.'],
               ['Explaining how deforestation affects the hydrologic cycle.', 'Predicting consequences of aquifer overdraft.', 'Calculating freshwater use from data.'],
               ['Khan Academy: Hydrologic Cycle', 'Bozeman Science: Water Cycle'],
               [('Evapotranspiration includes both:', ['Evaporation from water surfaces and transpiration by plants', 'Precipitation and runoff', 'Infiltration and groundwater flow', 'Condensation and precipitation', 'Runoff and infiltration']),
                ('Overdraft of an aquifer can cause:', ['Land subsidence and saltwater intrusion in coastal areas', 'Increased rainfall', 'More rapid recharge', 'Decreased evaporation', 'Increased river flow']),
                ('The largest human use of freshwater globally is:', ['Agriculture (irrigation)', 'Municipal use (drinking/sanitation)', 'Industrial cooling', 'Hydroelectric generation', 'Recreation']),
                ('Deforestation typically increases:', ['Surface runoff and decreases infiltration', 'Transpiration', 'Aquifer recharge', 'Soil water retention', 'Cloud formation']),
                ('What percentage of Earth\'s water is fresh?', ['~2.5%', '~70%', '~50%', '~10%', '~97%']),
               ],
               [('Bozeman Science: Hydrologic Cycle', 'Covers water cycle pathways, aquifers, and freshwater availability.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['List four pathways water can take in the hydrologic cycle.', 'What is aquifer overdraft?', 'Why is freshwater scarce despite covering 70% of Earth?']
            ),
            _l('The Atmosphere',
               [
                   _t('Atmospheric Layers', 'The troposphere (weather), stratosphere (ozone layer), mesosphere, and thermosphere each have distinct temperature profiles and roles.', 'Weather occurs in the troposphere; ozone protection occurs in the stratosphere — students often confuse these layers.', 'Identify atmospheric layers and their key characteristics.'),
                   _t('Coriolis Effect and Wind Patterns', 'Earth\'s rotation deflects moving air and water rightward in the Northern Hemisphere (leftward in Southern), creating trade winds, westerlies, and polar easterlies.', 'The Coriolis effect does NOT determine the direction of drain whirlpools — the effect is too weak at that scale.', 'Explain how the Coriolis effect creates global wind patterns and influences weather.'),
                   _t('Ocean Currents and Climate', 'Surface ocean currents are driven by wind; thermohaline circulation (deep-water) is driven by temperature and salinity differences. Both affect regional climate significantly.', 'Ocean currents warm or cool adjacent land areas; disrupting them (e.g., AMOC slowdown) could dramatically alter climates.', 'Explain how ocean currents like the Gulf Stream moderate regional climates.'),
               ],
               [('troposphere', 'Lowest atmospheric layer, 0–12 km; contains weather and most water vapor.'),
                ('stratosphere', 'Layer 12–50 km; contains ozone layer that absorbs UV radiation.'),
                ('Coriolis effect', 'Deflection of moving air/water caused by Earth\'s rotation.'),
                ('thermohaline circulation', 'Deep ocean circulation driven by density differences from temperature and salinity.'),
                ('trade winds', 'Persistent winds near the equator flowing from subtropical high-pressure zones toward the equator.')],
               ['Identify atmospheric layers and their functions.', 'Explain the Coriolis effect and resulting wind patterns.', 'Describe how ocean currents affect regional climates.'],
               ['Predicting wind direction from Coriolis effect.', 'Explaining how thermohaline circulation is affected by freshwater input (glacial melt).', 'Connecting ocean currents to the climate of Western Europe.'],
               ['Khan Academy: Atmosphere', 'Bozeman Science: Atmosphere and Climate'],
               [('The ozone layer is located in the:', ['Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere', 'Exosphere']),
                ('The Coriolis effect deflects winds in the Northern Hemisphere:', ['To the right', 'To the left', 'Downward', 'Upward', 'Not at all']),
                ('Thermohaline circulation is driven by:', ['Temperature and salinity differences creating density gradients', 'Wind only', 'Tidal forces', 'Coriolis effect only', 'Volcanic heating of the ocean']),
                ('The Gulf Stream warms Western Europe because:', ['It carries warm tropical water northward', 'It deflects cold Arctic air', 'It creates more rainfall', 'It decreases wind speed', 'It is part of the trade winds']),
                ('Weather occurs primarily in the:', ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere', 'Ionosphere']),
               ],
               [('Bozeman Science: Atmosphere', 'Covers layers, wind patterns, and ocean circulation.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['In which atmospheric layer does weather occur?', 'How does the Coriolis effect affect wind direction?', 'Why does the Gulf Stream warm Western Europe?']
            ),
        ],
        'unit_qs': [
            ('Convergent boundaries between a continental and oceanic plate produce:', ['Subduction zones, volcanoes, and mountain ranges', 'Mid-ocean ridges', 'Only earthquakes', 'Rift valleys', 'Transform faults']),
            ('Why is soil a nonrenewable resource?', ['Formation takes hundreds to thousands of years; erosion can remove it quickly', 'It cannot be replenished at all', 'It contains fossil fuels', 'It is found only in one location', 'It is made of nonrenewable minerals only']),
            ('Which soil texture has the best balance of drainage and nutrient retention?', ['Loam', 'Sand', 'Clay', 'Silt', 'Gravel']),
            ('Deforestation increases surface runoff because:', ['Less transpiration and fewer roots to absorb water', 'More rain falls on cleared land', 'Soil becomes more porous', 'Evaporation decreases', 'Wind increases']),
            ('Aquifer overdraft in coastal areas can cause:', ['Saltwater intrusion into freshwater supply', 'Increased recharge from the ocean', 'Land elevation to increase', 'Faster water table recharge', 'Decreased salinity']),
            ('The Coriolis effect is caused by:', ['Earth\'s rotation', 'Earth\'s revolution around the sun', 'The moon\'s gravity', 'Ocean density differences', 'Temperature gradients in the atmosphere']),
            ('Which is NOT a pathway in the hydrologic cycle?', ['Photosynthesis producing water vapor', 'Evaporation', 'Transpiration', 'Precipitation', 'Infiltration to groundwater']),
            ('Volcanic soils are fertile because volcanic ash:', ['Weathers into mineral-rich soil', 'Contains organic matter', 'Retains more water', 'Has neutral pH', 'Lacks clay']),
            ('Thermohaline circulation could be disrupted by:', ['Increased freshwater input from glacial melt reducing salinity and density', 'Decreased wind speed', 'Colder tropics', 'More volcanic eruptions', 'Increased trade wind strength']),
            ('The A horizon (topsoil) is important to agriculture because it:', ['Contains the most organic matter and nutrients', 'Is the deepest layer', 'Is made of bedrock', 'Has the lowest infiltration', 'Contains the most clay']),
        ],
    },
    {
        'num': 5,
        'title': 'Unit 5: Land and Water Use',
        'file': 'ap-environmental-science-5-unit-5-land-and-water-use.html',
        'desc': 'Agriculture, forestry, fishing, mining, and urban development impacts on land and water.',
        'gateway': [
            'Describe major agricultural practices and their environmental impacts.',
            'Explain sustainable forestry and fishing management strategies.',
            'Identify environmental impacts of mining and urbanization.',
            'Compare irrigation methods by water efficiency.',
        ],
        'lessons': [
            _l('Agriculture and Soil Management',
               [
                   _t('Industrial Agriculture', 'Industrial agriculture uses monocultures, synthetic fertilizers, pesticides, and mechanization to maximize yield; it increases productivity but reduces biodiversity and degrades soil.', 'Monocultures increase efficiency but are highly vulnerable to pest outbreaks and disease.', 'Evaluate trade-offs of industrial agriculture vs. sustainable alternatives.'),
                   _t('Soil Degradation', 'Salinization (irrigated soil salt buildup), erosion (removal of topsoil), and desertification (degradation of dryland soil) reduce agricultural productivity.', 'Salinization is caused by evaporation of irrigation water leaving salt behind, not by the salt in crops.', 'Describe causes and prevention of salinization, erosion, and desertification.'),
                   _t('Sustainable Agriculture', 'Contour plowing, terracing, cover crops, crop rotation, no-till farming, and integrated pest management (IPM) reduce erosion, restore nutrients, and cut chemical use.', 'Sustainable practices often reduce short-term yield while improving long-term productivity and ecosystem health.', 'Identify and explain sustainable soil and pest management practices.'),
               ],
               [('monoculture', 'Growing a single crop over a large area; efficient but vulnerable to pests and disease.'),
                ('salinization', 'Buildup of salts in soil from evaporation of irrigation water; reduces fertility.'),
                ('contour plowing', 'Plowing across slopes (along contour lines) to reduce water erosion.'),
                ('integrated pest management (IPM)', 'Combining biological, cultural, and minimal chemical controls to manage pests.'),
                ('no-till farming', 'Planting without plowing; reduces erosion and preserves soil structure.')],
               ['Identify environmental impacts of industrial agriculture.', 'Explain how salinization and erosion reduce soil productivity.', 'Describe sustainable agricultural practices and their benefits.'],
               ['Comparing conventional vs. sustainable farming methods.', 'Explaining why contour plowing and terracing reduce erosion.', 'Evaluating IPM as a pest control strategy.'],
               ['Khan Academy: Agriculture', 'Bozeman Science: Agriculture'],
               [('Salinization of agricultural soil is caused by:', ['Evaporation of irrigation water leaving salt behind', 'Planting salt-tolerant crops', 'Acid rain dissolving soil minerals', 'Heavy rainfall leaching minerals', 'Deep plowing']),
                ('Monocultures are vulnerable because:', ['All plants are genetically similar, so one pest can destroy the whole crop', 'They require more labor', 'They use more water than polycultures', 'They cannot use fertilizer', 'They reduce yield per acre']),
                ('Contour plowing reduces:', ['Water erosion by slowing runoff on slopes', 'Wind erosion only', 'Fertilizer use', 'Salinization', 'Pesticide runoff']),
                ('IPM (integrated pest management) is preferred over pesticides alone because:', ['It minimizes chemical use while effectively controlling pests', 'It uses only biological controls', 'It eliminates all pests', 'It is cheaper than all pesticides', 'It requires no monitoring']),
                ('Desertification is driven by:', ['Overgrazing, deforestation, and poor land management in drylands', 'Increased rainfall', 'Volcanic activity', 'Glacial retreat', 'Urbanization in wet regions']),
               ],
               [('Bozeman Science: Agriculture', 'Covers industrial farming impacts, soil degradation, and sustainable practices.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is salinization and how is it caused?', 'How does contour plowing reduce erosion?', 'What is integrated pest management?']
            ),
            _l('Forestry and Fisheries Management',
               [
                   _t('Logging Methods', 'Clear-cutting removes all trees and causes erosion, habitat loss, and stream sedimentation; selective cutting and shelterwood cutting are more sustainable.', 'Clear-cutting is efficient and economically profitable but has severe ecological impacts.', 'Compare logging methods by ecological impact.'),
                   _t('Sustainable Forestry', 'Sustainable forestry maintains biodiversity, old-growth characteristics, and watershed function; certification (FSC) helps consumers identify sustainably harvested wood.', 'Tree plantations are NOT sustainable forests — they lack biodiversity and ecosystem services of native forests.', 'Distinguish tree plantations from sustainable forests; explain FSC certification.'),
                   _t('Fisheries Management', 'Overfishing depletes fish stocks; management tools include catch limits, size limits, gear restrictions, marine protected areas (MPAs), and aquaculture.', 'Aquaculture (fish farming) can reduce pressure on wild stocks but introduces its own environmental problems (disease, waste, escape of non-native species).', 'Evaluate fisheries management strategies and trade-offs of aquaculture.'),
               ],
               [('clear-cutting', 'Removing all trees from an area; maximizes timber yield but causes severe ecological damage.'),
                ('selective cutting', 'Removing only specific trees while leaving the forest structure mostly intact.'),
                ('marine protected area (MPA)', 'Designated ocean area where fishing and other activities are restricted.'),
                ('aquaculture', 'Farming of fish, shellfish, or aquatic plants; can reduce wild-catch pressure.'),
                ('bycatch', 'Non-target species accidentally caught in fishing gear; major source of unintended mortality.')],
               ['Compare logging methods by ecological impact.', 'Explain strategies for sustainable fisheries management.', 'Evaluate aquaculture as a solution to overfishing.'],
               ['Recommending a logging method for a specific context.', 'Explaining why MPAs help fish populations recover.', 'Weighing pros and cons of aquaculture.'],
               ['Khan Academy: Forests and Fisheries', 'Bozeman Science: Fisheries'],
               [('Clear-cutting causes environmental problems including:', ['Erosion, habitat loss, and stream sedimentation', 'Increased biodiversity', 'Improved water quality', 'Greater carbon storage', 'Faster forest regeneration']),
                ('A marine protected area helps fish populations by:', ['Providing a refuge where fish can reproduce without being harvested', 'Eliminating all fishing globally', 'Increasing aquaculture production', 'Reducing ocean temperature', 'Preventing bycatch in all areas']),
                ('Aquaculture reduces pressure on wild fish but can:', ['Introduce disease and pollutants to surrounding water', 'Eliminate overfishing entirely', 'Increase wild fish populations', 'Replace all ocean fishing', 'Improve marine biodiversity']),
                ('Bycatch refers to:', ['Non-target species accidentally caught in fishing gear', 'Intentional harvesting of smaller fish', 'Fish that escape aquaculture farms', 'Dead fish left after processing', 'Fish caught over quota']),
                ('Selective cutting is more sustainable than clear-cutting because:', ['It maintains forest structure and biodiversity', 'It removes more timber per hectare', 'It is faster to implement', 'It eliminates all old-growth trees', 'It requires no regulation']),
               ],
               [('Bozeman Science: Forestry and Fisheries', 'Covers logging methods, MPAs, and aquaculture.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Why is clear-cutting environmentally damaging?', 'What is the role of a marine protected area?', 'List two environmental problems associated with aquaculture.']
            ),
            _l('Mining and Urban Land Use',
               [
                   _t('Mining Impacts', 'Surface mining (strip mining, open-pit) destroys habitats and creates acid mine drainage; underground mining causes subsidence and releases pollutants. Reclamation can partially restore mined land.', 'Acid mine drainage forms when sulfide minerals in exposed rock react with air and water, producing sulfuric acid.', 'Describe environmental impacts of surface and underground mining and reclamation strategies.'),
                   _t('Urban Sprawl', 'Urban sprawl converts farmland and natural habitat to suburbs; increases impervious surfaces, stormwater runoff, air pollution, and car dependence.', 'Urban sprawl is often considered environmentally worse than compact urban development per capita.', 'Explain how urban sprawl affects land use, water quality, and energy consumption.'),
                   _t('Smart Growth and Land Use Planning', 'Smart growth principles include compact development, transit-oriented design, mixed land use, and green space preservation; they reduce sprawl impacts.', 'Smart growth benefits both environment and human health, but faces political and economic resistance.', 'Identify smart growth strategies and explain their environmental benefits.'),
               ],
               [('acid mine drainage', 'Acidic water formed when sulfide minerals from mining react with air and water; toxic to aquatic life.'),
                ('surface mining', 'Removing soil and rock to extract near-surface mineral deposits; includes strip and open-pit mining.'),
                ('urban sprawl', 'Low-density spread of cities into surrounding natural or agricultural land.'),
                ('impervious surface', 'Hard surfaces (pavement, rooftops) that prevent water infiltration and increase runoff.'),
                ('smart growth', 'Urban planning approach emphasizing compact, transit-connected, mixed-use development.')],
               ['Describe environmental impacts of surface and underground mining.', 'Explain how urban sprawl degrades land and water.', 'Identify smart growth strategies and their benefits.'],
               ['Comparing surface and underground mining environmental impacts.', 'Explaining why impervious surfaces worsen stormwater problems.', 'Evaluating smart growth policies.'],
               ['Khan Academy: Land Use', 'Bozeman Science: Mining and Urban Land Use'],
               [('Acid mine drainage is formed when:', ['Sulfide minerals react with air and water to produce sulfuric acid', 'Heavy metals dissolve in rainwater', 'Mining equipment leaks oil', 'Coal burns incompletely', 'Smelting releases SO₂']),
                ('Urban sprawl increases nonpoint source water pollution because:', ['Impervious surfaces increase runoff carrying pollutants to waterways', 'Dense cities release more chemicals', 'Farms are converted to wetlands', 'Trees increase precipitation', 'Population decreases in cities']),
                ('Smart growth reduces environmental impact by:', ['Encouraging compact, transit-oriented development that reduces car use and land conversion', 'Promoting low-density housing', 'Eliminating all urban development', 'Requiring all buildings to be tall', 'Removing green spaces for efficiency']),
                ('Surface mining is more damaging than underground mining primarily because:', ['It destroys entire habitats and topsoil over large areas', 'It produces more acid drainage', 'It uses more energy', 'It employs fewer workers', 'It is more expensive']),
                ('Impervious surfaces in cities cause:', ['Increased surface runoff and flooding; reduced groundwater recharge', 'Increased infiltration', 'Cooler urban temperatures', 'Reduced stormwater velocity', 'Improved water quality']),
               ],
               [('Bozeman Science: Mining and Urban Land Use', 'Covers mining impacts, sprawl, and smart growth.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is acid mine drainage and why is it harmful?', 'How do impervious surfaces affect the water cycle?', 'Name two smart growth strategies.']
            ),
            _l('Irrigation and Water Management',
               [
                   _t('Irrigation Methods', 'Flood irrigation is cheap but wastes water; drip irrigation is most efficient (90%+ delivery to roots); sprinkler irrigation is intermediate. Irrigation accounts for ~70% of freshwater use.', 'Drip irrigation saves water but is expensive to install, limiting its use in developing countries.', 'Compare irrigation methods by water efficiency and environmental impact.'),
                   _t('Water Diversion and Dams', 'Dams provide hydroelectric power, flood control, and irrigation water but fragment river habitat, block fish migration, trap sediment, and displace communities.', 'Dams may seem "green" (hydropower) but have major ecological costs downstream and upstream.', 'Explain benefits and costs of large dams and water diversion projects.'),
                   _t('Water Conservation', 'Water conservation strategies include pricing reform (true-cost pricing), demand management, water recycling, xeriscaping, and drought-resistant crop breeding.', 'True-cost pricing can reduce waste but disproportionately affects low-income users if not accompanied by equity measures.', 'Identify water conservation strategies and analyze trade-offs.'),
               ],
               [('drip irrigation', 'Delivers water directly to plant roots via tubes; most water-efficient method.'),
                ('flood irrigation', 'Flooding fields with water; least efficient method with high evaporation loss.'),
                ('dam', 'Structure that impounds a river; provides benefits but fragments aquatic habitat.'),
                ('xeriscaping', 'Landscaping using drought-tolerant plants to reduce irrigation needs.'),
                ('true-cost pricing', 'Charging the full environmental and resource cost of water to encourage conservation.')],
               ['Compare irrigation methods by efficiency.', 'Evaluate costs and benefits of large dams.', 'Identify water conservation strategies.'],
               ['Recommending irrigation methods for different contexts.', 'Analyzing environmental trade-offs of dam construction.', 'Applying conservation strategies to a water scarcity scenario.'],
               ['Khan Academy: Water Management', 'Bozeman Science: Water Use'],
               [('Drip irrigation is preferred over flood irrigation because:', ['It delivers water directly to roots with minimal evaporation loss', 'It is cheaper to install', 'It works for all crop types', 'It does not require electricity', 'It increases soil salinity']),
                ('Dams harm river ecosystems by:', ['Blocking fish migration and trapping sediment downstream', 'Increasing river velocity', 'Improving water quality', 'Reducing flood risk only', 'Providing habitat for all fish species']),
                ('Xeriscaping reduces water demand by:', ['Using drought-tolerant plants that need little irrigation', 'Covering soil with concrete', 'Planting only grass', 'Using drip systems only', 'Planting only exotic species']),
                ('True-cost pricing of water encourages conservation because:', ['Higher prices incentivize reduced use and more efficient practices', 'It gives free water to poor communities', 'It subsidizes irrigation equipment', 'It reduces dam construction', 'It makes water cheaper for farmers']),
                ('Sediment trapped behind dams reduces:', ['Downstream sediment deposition needed for delta and floodplain fertility', 'Upstream flooding', 'River velocity above the dam', 'Water storage capacity', 'Fish population upstream']),
               ],
               [('Bozeman Science: Water Use and Conservation', 'Covers irrigation methods, dams, and conservation strategies.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Which irrigation method is most water-efficient?', 'Name two environmental costs of large dams.', 'What is xeriscaping?']
            ),
        ],
        'unit_qs': [
            ('Salinization of soil is most associated with:', ['Irrigated agriculture in arid regions', 'Contour plowing', 'No-till farming', 'Rain-fed farming in humid areas', 'Afforestation projects']),
            ('Clear-cutting is ecologically damaging primarily because:', ['It removes all trees and causes erosion, habitat loss, and stream sedimentation', 'It uses heavy machinery', 'It removes only old trees', 'It requires herbicides', 'It is expensive']),
            ('Aquaculture can harm wild fish populations by:', ['Spreading disease from farmed to wild fish', 'Reducing available food for wild fish', 'Competing for ocean space', 'Providing no food for predators', 'Increasing water temperature globally']),
            ('Which farming practice most effectively reduces wind erosion?', ['No-till farming and cover crops', 'Contour plowing', 'Flood irrigation', 'Monocultures', 'Clear-cutting adjacent forest']),
            ('Acid mine drainage primarily harms aquatic ecosystems by:', ['Lowering pH and killing acid-sensitive organisms', 'Increasing nutrient levels', 'Warming water temperature', 'Adding heavy metals that are beneficial', 'Reducing water flow']),
            ('Urban impervious surfaces increase:', ['Stormwater runoff and flooding; decrease groundwater recharge', 'Groundwater recharge', 'Transpiration', 'Infiltration', 'Biodiversity in streams']),
            ('Drip irrigation is more water-efficient than sprinkler irrigation because:', ['Water is delivered directly to roots with less evaporation', 'It uses pumps only', 'It requires less maintenance', 'It uses recycled water', 'It is cheaper']),
            ('A marine protected area (MPA) helps fisheries by:', ['Providing a no-take zone where fish reproduce and repopulate adjacent areas', 'Eliminating all commercial fishing', 'Reducing bycatch globally', 'Increasing water temperature', 'Preventing aquaculture']),
            ('Monoculture farming is associated with:', ['Higher short-term yield but greater vulnerability to pests', 'Greater biodiversity', 'Less fertilizer use', 'More resilient food systems', 'Lower energy inputs']),
            ('Dams fragment river habitat by:', ['Blocking fish migration and altering downstream flow and sediment', 'Increasing sediment downstream', 'Improving water quality', 'Reducing flood risk with no ecological cost', 'Warming water upstream only']),
        ],
    },
]
