NAME = 'AP® Environmental Science'
ABBREV = 'apes'
SLUG = 'ap-environmental-science'
COURSE_FILE = 'ap-environmental-science.html'
ACCENT_COLOR = '#22c55e'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Environmental+Science+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 6,
        'title': 'Unit 6: Energy Resources and Consumption',
        'file': 'ap-environmental-science-6-unit-6-energy-resources-and-consumption.html',
        'desc': 'Fossil fuels, nuclear power, and renewable energy sources with their environmental impacts.',
        'gateway': [
            'Compare fossil fuels by environmental impact.',
            'Explain how nuclear fission generates electricity.',
            'Describe advantages and limitations of renewable energy sources.',
            'Calculate energy efficiency and EROI.',
        ],
        'lessons': [
            _l('Fossil Fuels',
               [
                   _t('Coal, Oil, and Natural Gas', 'Fossil fuels are ancient organic matter compressed over millions of years; combustion releases CO₂, SO₂, NOₓ, and particulates, driving climate change and air pollution.', 'Natural gas is the cleanest-burning fossil fuel but still emits CO₂ and can leak methane (a more potent greenhouse gas).', 'Compare coal, oil, and natural gas by environmental impact and uses.'),
                   _t('Environmental Impacts of Extraction', 'Coal mining destroys habitat (mountaintop removal), oil spills harm marine ecosystems, hydraulic fracturing (fracking) risks groundwater contamination and induces earthquakes.', 'Fracking itself does not contaminate groundwater in most cases — leaks from poorly cased wells are the main risk.', 'Identify environmental risks of each fossil fuel extraction method.'),
                   _t('Energy Return on Investment (EROI)', 'EROI = energy out / energy in; high EROI means more net energy. Fossil fuels historically have high EROI, but it declines as easy reserves are depleted.', 'EROI for tar sands and shale oil is much lower than for conventional oil.', 'Calculate EROI and use it to compare energy sources.'),
               ],
               [('fossil fuel', 'Non-renewable energy formed from ancient organic matter; includes coal, oil, natural gas.'),
                ('combustion', 'Burning of fuels in oxygen to produce CO₂, H₂O, and energy.'),
                ('fracking (hydraulic fracturing)', 'Injecting high-pressure fluid into rock to release natural gas or oil.'),
                ('mountaintop removal', 'Surface mining that blasts off mountain summits to expose coal seams.'),
                ('EROI (energy return on investment)', 'Ratio of energy produced to energy invested in extraction and processing.')],
               ['Compare environmental impacts of coal, oil, and natural gas.', 'Identify extraction risks for each fossil fuel.', 'Calculate and interpret EROI.'],
               ['Evaluating trade-offs between fossil fuel types.', 'Explaining why fracking is controversial.', 'Using EROI to compare energy sources.'],
               ['Khan Academy: Fossil Fuels', 'Bozeman Science: Energy Resources'],
               [('Which fossil fuel produces the most CO₂ per unit energy when burned?', ['Coal', 'Oil', 'Natural gas', 'Hydrogen', 'Ethanol']),
                ('Fracking is controversial primarily because of concerns about:', ['Groundwater contamination and induced earthquakes', 'Air pollution only', 'Habitat destruction from pipelines', 'CO₂ emissions only', 'High cost']),
                ('EROI = 20:1 means:', ['For every 1 unit of energy invested, 20 units are produced', '20% of energy is wasted', 'Energy costs 20 times more to extract', '20 workers are needed per unit', 'Only 1/20 of energy is usable']),
                ('Mountaintop removal is a form of:', ['Surface coal mining', 'Underground coal mining', 'Oil extraction', 'Natural gas drilling', 'Uranium mining']),
                ('Natural gas burns cleaner than coal but is still problematic because:', ['Methane leaks during extraction and transport; methane is a potent greenhouse gas', 'It produces more SO₂', 'It is more radioactive', 'It creates acid rain', 'Its EROI is too low']),
               ],
               [('Bozeman Science: Fossil Fuels', 'Covers extraction methods, combustion emissions, and EROI.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Which fossil fuel is most carbon-intensive?', 'What are two environmental risks of fracking?', 'What does a high EROI indicate about an energy source?']
            ),
            _l('Nuclear Energy',
               [
                   _t('Nuclear Fission', 'Nuclear fission splits uranium-235 or plutonium-239 atoms, releasing enormous energy; chain reactions are controlled in a reactor.', 'Nuclear power produces no CO₂ during operation, but uranium mining and waste storage have environmental costs.', 'Explain how nuclear fission produces electricity and identify its advantages and risks.'),
                   _t('Nuclear Waste', 'Spent nuclear fuel is highly radioactive and remains dangerous for thousands of years; no permanent storage solution exists in the U.S.', 'Low-level waste (gloves, tools) is much less hazardous than high-level waste (spent fuel rods).', 'Describe the challenge of nuclear waste management.'),
                   _t('Nuclear Accidents', 'Meltdowns (Chernobyl 1986, Fukushima 2011) can release radioactive material over large areas; risk is low probability but high consequence.', 'Modern reactor designs are much safer than Chernobyl-era designs.', 'Evaluate nuclear energy in terms of safety, waste, and climate benefits.'),
               ],
               [('nuclear fission', 'Splitting of a heavy nucleus (U-235) releasing large amounts of energy.'),
                ('chain reaction', 'Self-sustaining series of fission events; controlled in reactors, uncontrolled in bombs.'),
                ('radioactive waste', 'Byproduct of nuclear reactions that emits radiation for thousands of years.'),
                ('meltdown', 'Overheating of reactor core due to cooling failure; can release radioactive material.'),
                ('half-life', 'Time for half of a radioactive substance to decay; determines waste storage duration.')],
               ['Explain how nuclear fission generates electricity.', 'Describe the nuclear waste challenge.', 'Evaluate nuclear energy trade-offs vs. fossil fuels and renewables.'],
               ['Comparing nuclear energy to fossil fuels on CO₂ and safety.', 'Explaining why nuclear waste is difficult to manage.', 'Analyzing trade-offs of nuclear expansion.'],
               ['Khan Academy: Nuclear Energy', 'Bozeman Science: Nuclear Power'],
               [('Nuclear power plants produce electricity by:', ['Using fission heat to boil water and spin turbines', 'Burning uranium directly', 'Using fusion reactions', 'Converting gamma rays to electricity', 'Splitting water molecules']),
                ('The main advantage of nuclear power over fossil fuels is:', ['No CO₂ emissions during operation', 'No waste produced', 'Infinite fuel supply', 'No safety risks', 'Low upfront cost']),
                ('The biggest challenge for nuclear waste management is:', ['Finding permanent storage for high-level waste that is safe for thousands of years', 'Cooling the waste', 'Preventing CO₂ release', 'Shipping waste safely', 'Low-level waste from hospitals']),
                ('Chernobyl and Fukushima demonstrate that nuclear accidents:', ['Are rare but can have severe, wide-ranging consequences', 'Are common in modern reactors', 'Only affect workers at the plant', 'Have no environmental impact', 'Are completely preventable with current technology']),
                ('A long half-life for nuclear waste means:', ['The material remains radioactive for a very long time', 'It decays quickly', 'It is less dangerous', 'It can be stored above ground safely', 'It has low energy output']),
               ],
               [('Bozeman Science: Nuclear Power', 'Covers fission, waste management, and safety trade-offs.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['How does a nuclear power plant generate electricity?', 'Why is nuclear waste storage so challenging?', 'What is the main environmental advantage of nuclear power over coal?']
            ),
            _l('Renewable Energy Sources',
               [
                   _t('Solar and Wind', 'Solar PV converts sunlight to electricity; wind turbines convert kinetic energy. Both are intermittent (dependent on sun/wind availability) and require storage or backup.', 'Solar and wind produce no emissions during operation but require energy and materials to manufacture.', 'Compare solar and wind energy by advantages, limitations, and environmental impacts.'),
                   _t('Hydroelectric, Geothermal, and Biomass', 'Hydroelectric is reliable but requires dams with ecological costs; geothermal taps Earth\'s heat (limited to geologically active areas); biomass burns organic matter and can be carbon-neutral if managed sustainably.', 'Biomass can be worse than coal if forests are cleared for fuel crops; sustainability depends on source.', 'Evaluate hydroelectric, geothermal, and biomass energy sources.'),
                   _t('Energy Efficiency', 'Energy efficiency reduces demand at the source; more effective per dollar than building new generation. Conservation (behavioral) differs from efficiency (technological).', 'Efficiency improvements can rebound (Jevons paradox): using less per unit may increase total use.', 'Distinguish efficiency from conservation; explain the rebound effect.'),
               ],
               [('solar photovoltaic (PV)', 'Converts sunlight directly to electricity using semiconductor cells.'),
                ('wind turbine', 'Converts wind kinetic energy to electricity; most cost-effective in high-wind areas.'),
                ('intermittency', 'Variable output of solar and wind energy depending on weather conditions.'),
                ('geothermal energy', 'Heat from Earth\'s interior used for electricity generation or direct heating.'),
                ('energy efficiency', 'Ratio of useful energy output to total energy input; reducing waste energy.')],
               ['Compare renewable sources by reliability, cost, and environmental impact.', 'Explain why energy efficiency is often the most cost-effective strategy.', 'Describe the rebound effect.'],
               ['Evaluating renewable energy trade-offs for a given location.', 'Calculating efficiency improvements and their effects.', 'Applying Jevons paradox to energy policy.'],
               ['Khan Academy: Renewable Energy', 'Bozeman Science: Renewable Energy'],
               [('Solar and wind are described as intermittent because:', ['Their output varies with weather and time of day', 'They are expensive', 'They produce waste', 'They require water', 'They are not widely deployed']),
                ('Geothermal energy is limited because:', ['It is only viable in geologically active areas with accessible heat', 'It produces CO₂', 'It requires dams', 'It is intermittent like solar', 'It has low EROI']),
                ('Which renewable has the highest ecological impact on rivers?', ['Hydroelectric (requires dams)', 'Solar PV', 'Wind', 'Geothermal', 'Biomass']),
                ('Energy efficiency is often the most cost-effective strategy because:', ['It reduces demand at the source, requiring less generation capacity', 'It eliminates all emissions', 'It replaces all fossil fuels', 'It costs nothing to implement', 'It improves EROI automatically']),
                ('The rebound effect (Jevons paradox) refers to:', ['Efficiency gains leading to increased total consumption', 'Renewable energy increasing fossil fuel use', 'Conservation efforts failing', 'EROI declining over time', 'Population growth offsetting efficiency']),
               ],
               [('Bozeman Science: Renewable Energy', 'Covers solar, wind, hydro, and efficiency.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Why is solar energy considered intermittent?', 'What is geothermal energy and where is it best used?', 'What is the rebound effect?']
            ),
            _l('Energy Policy and the Future',
               [
                   _t('Energy Mix and Transition', 'A diversified energy portfolio balances reliability, cost, and environmental impact; transitioning from fossil fuels requires grid modernization, storage, and policy support.', 'No single renewable source can replace fossil fuels alone — an energy mix is needed.', 'Evaluate energy transition strategies and barriers.'),
                   _t('Carbon Capture and Storage (CCS)', 'CCS captures CO₂ from power plant emissions and stores it underground; still expensive and unproven at large scale, but could reduce emissions from fossil fuel use.', 'CCS does not prevent all fossil fuel emissions and is not a substitute for renewable deployment.', 'Explain CCS technology and its limitations.'),
                   _t('Energy Poverty and Equity', 'Energy poverty affects ~800 million people lacking electricity; renewable microgrids can provide access without fossil fuel infrastructure.', 'Energy poverty is primarily a developing-world issue but also affects low-income communities in wealthy nations.', 'Discuss equity dimensions of energy access and transition.'),
               ],
               [('energy portfolio', 'Combination of energy sources used to meet electricity demand.'),
                ('carbon capture and storage (CCS)', 'Technology that captures CO₂ from combustion and stores it underground.'),
                ('smart grid', 'Electricity network with digital controls to balance supply and demand, integrate renewables.'),
                ('energy poverty', 'Lack of access to reliable, affordable, modern energy services.'),
                ('feed-in tariff', 'Policy that pays renewable energy producers a guaranteed price for electricity fed to the grid.')],
               ['Explain why a diverse energy mix is needed for a reliable grid.', 'Describe CCS technology and its limitations.', 'Analyze equity issues in energy transitions.'],
               ['Designing an energy mix for a given region.', 'Evaluating CCS as a climate strategy.', 'Explaining barriers to renewable adoption in developing countries.'],
               ['Khan Academy: Energy Policy', 'Bozeman Science: Energy and Climate'],
               [('A diversified energy portfolio is preferred because:', ['No single source is reliable, affordable, and low-impact in all conditions', 'It always costs less', 'It eliminates all CO₂ emissions', 'It requires no storage', 'It ignores environmental factors']),
                ('Carbon capture and storage (CCS) is limited by:', ['High cost and unproven large-scale viability', 'Lack of CO₂ sources', 'CO₂ being harmless underground', 'No suitable geological formations', 'Low CO₂ capture rates']),
                ('Renewable microgrids benefit energy-poor communities by:', ['Providing electricity without requiring large infrastructure investment', 'Being cheaper than all other options globally', 'Eliminating energy poverty in all countries', 'Working without any equipment', 'Being exempt from regulation']),
                ('A smart grid improves renewable energy integration by:', ['Balancing supply and demand in real time', 'Storing all renewable energy', 'Replacing transmission lines', 'Eliminating intermittency', 'Reducing efficiency losses']),
                ('Feed-in tariffs promote renewable energy by:', ['Guaranteeing a fixed price for electricity sold to the grid', 'Taxing fossil fuels only', 'Subsidizing fossil fuels', 'Requiring energy efficiency', 'Mandating nuclear power']),
               ],
               [('Bozeman Science: Energy Policy', 'Covers energy transition, CCS, and equity.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Why do we need a mix of energy sources rather than just one?', 'What is CCS and what are its limitations?', 'How do renewable microgrids help energy-poor communities?']
            ),
        ],
        'unit_qs': [
            ('Which fossil fuel produces the least CO₂ per unit energy?', ['Natural gas', 'Coal', 'Oil', 'Peat', 'Tar sands']),
            ('EROI = 5:1 means:', ['5 units of energy produced per 1 unit invested', '5% efficiency', 'Energy is wasted at 5:1 ratio', '5 workers per unit energy', '1 unit produced per 5 invested']),
            ('The main environmental advantage of nuclear power is:', ['No operational CO₂ emissions', 'No waste produced', 'Unlimited fuel', 'No accident risk', 'Low cost']),
            ('Intermittency is a challenge for which renewable sources?', ['Solar and wind', 'Geothermal and hydroelectric', 'Biomass and tidal', 'Nuclear', 'Natural gas']),
            ('Fracking raises environmental concerns primarily about:', ['Groundwater contamination and induced earthquakes', 'High CO₂ emissions', 'Acid rain', 'Habitat for birds', 'Ocean acidification']),
            ('Energy efficiency is cost-effective because:', ['Reducing demand is cheaper than building new generation capacity', 'Efficiency creates no waste', 'It eliminates all fossil fuel use', 'It requires no infrastructure', 'It reduces energy poverty instantly']),
            ('Which renewable energy is most reliable (not intermittent)?', ['Geothermal', 'Solar PV', 'Wind', 'Tidal', 'Hydrogen']),
            ('The Jevons paradox (rebound effect) states that:', ['Efficiency gains can increase total energy use by making energy cheaper', 'Efficiency always reduces total energy use', 'Renewable energy causes more emissions', 'Conservation equals efficiency', 'CCS reduces all emissions']),
            ('High-level nuclear waste requires:', ['Storage isolated from the environment for thousands of years', 'Only a few decades of storage', 'Burial in the ocean', 'Immediate incineration', 'Conversion to low-level waste']),
            ('Mountaintop removal coal mining is criticized for:', ['Destroying habitats and causing water pollution from mining waste', 'Emitting CO₂ only', 'Being underground', 'Using fracking', 'Producing radioactive waste']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=6IDLSvCNPTs',
    },
    {
        'num': 7,
        'title': 'Unit 7: Atmospheric Pollution',
        'file': 'ap-environmental-science-7-unit-7-atmospheric-pollution.html',
        'desc': 'Air quality, acid rain, ozone depletion, and indoor air pollution.',
        'gateway': [
            'Identify primary and secondary air pollutants.',
            'Explain the formation and effects of photochemical smog.',
            'Describe how acid deposition forms and its ecological impacts.',
            'Explain stratospheric ozone depletion and the role of CFCs.',
        ],
        'lessons': [
            _l('Air Pollutants and Smog',
               [
                   _t('Primary vs. Secondary Pollutants', 'Primary pollutants are emitted directly (CO, SO₂, NOₓ, particulates); secondary pollutants form from reactions in the atmosphere (ozone, sulfuric acid, nitric acid).', 'Tropospheric ozone is a harmful secondary pollutant, unlike stratospheric ozone which protects us.', 'Distinguish primary and secondary pollutants and give examples of each.'),
                   _t('Photochemical Smog', 'Photochemical smog forms when NOₓ and VOCs react in sunlight to produce ozone (O₃) and other secondary pollutants; worst on hot, sunny, still days in cities with traffic.', 'Ground-level ozone and stratospheric ozone are opposite: ground-level harms health; stratospheric ozone protects it.', 'Describe conditions that produce photochemical smog and its health effects.'),
                   _t('Industrial Smog', 'Industrial (gray/London) smog forms from SO₂ and particulates in cold, humid conditions; primarily from coal burning.', 'Industrial smog is associated with older industrial cities; photochemical smog with modern car-dependent cities.', 'Compare photochemical and industrial smog by source and conditions.'),
               ],
               [('primary pollutant', 'Pollutant emitted directly from a source into the atmosphere.'),
                ('secondary pollutant', 'Pollutant formed by chemical reactions among primary pollutants in the atmosphere.'),
                ('photochemical smog', 'Brown haze formed when NOₓ and VOCs react in sunlight to produce ground-level ozone.'),
                ('volatile organic compound (VOC)', 'Organic chemicals that evaporate easily and contribute to smog formation.'),
                ('particulate matter (PM)', 'Tiny solid or liquid particles suspended in air; PM2.5 most harmful to health.')],
               ['Distinguish primary and secondary air pollutants.', 'Explain photochemical smog formation and health effects.', 'Compare industrial and photochemical smog.'],
               ['Identifying pollutants as primary or secondary.', 'Explaining why ground-level ozone is harmful despite being the same molecule as protective stratospheric ozone.', 'Analyzing conditions that worsen smog.'],
               ['Khan Academy: Air Pollution', 'Bozeman Science: Air Pollution'],
               [('Ground-level ozone (O₃) is classified as a:', ['Secondary pollutant (formed from NOₓ + VOCs in sunlight)', 'Primary pollutant (emitted directly)', 'Greenhouse gas only', 'Beneficial atmospheric component', 'Indoor pollutant']),
                ('Photochemical smog is worst on days that are:', ['Hot, sunny, and calm with heavy traffic', 'Cold and rainy', 'Windy and cloudy', 'Cool and humid', 'Cold with snow']),
                ('Industrial smog differs from photochemical smog because it:', ['Forms from SO₂ and particulates from coal burning; occurs in cold, humid conditions', 'Forms from car exhaust only', 'Is a secondary pollutant', 'Contains ozone', 'Is found only in tropical cities']),
                ('Which is a PRIMARY air pollutant?', ['Carbon monoxide (CO) from vehicle exhaust', 'Ground-level ozone', 'Sulfuric acid droplets', 'Nitric acid in rain', 'Smog']),
                ('Fine particulate matter (PM2.5) is most dangerous because:', ['It penetrates deep into the lungs and enters the bloodstream', 'It blocks sunlight', 'It reacts with ozone', 'It is visible smog', 'It causes acid rain']),
               ],
               [('Bozeman Science: Air Pollution', 'Covers primary/secondary pollutants, smog types, and health effects.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between a primary and secondary pollutant?', 'What conditions worsen photochemical smog?', 'Why is PM2.5 the most dangerous particulate?']
            ),
            _l('Acid Deposition',
               [
                   _t('Formation of Acid Rain', 'SO₂ and NOₓ from fossil fuel combustion react with water vapor to form H₂SO₄ and HNO₃, which fall as acid precipitation (pH < 5.6).', 'Normal rain is already slightly acidic (pH ~5.6) due to dissolved CO₂; acid rain is significantly more acidic.', 'Trace the chemical pathway from SO₂/NOₓ emissions to acid rain formation.'),
                   _t('Ecological Effects', 'Acid rain acidifies lakes (killing acid-sensitive organisms), damages forests, and leaches calcium and other nutrients from soil.', 'Acidification affects entire ecosystems, not just the most acid-sensitive species.', 'Describe ecological impacts of acid deposition on aquatic and terrestrial ecosystems.'),
                   _t('Control and Solutions', 'Scrubbers remove SO₂ from power plant emissions; catalytic converters reduce NOₓ from vehicles; switching to low-sulfur coal or renewables reduces acid rain at the source.', 'Liming lakes treats symptoms (low pH) but does not address the root cause (emissions).', 'Evaluate acid rain control strategies by addressing source vs. symptom.'),
               ],
               [('acid deposition', 'Wet (rain, snow) or dry deposition of acids formed from SO₂ and NOₓ emissions.'),
                ('scrubber', 'Industrial device that removes SO₂ from power plant emissions before release.'),
                ('catalytic converter', 'Device in vehicles that converts NOₓ, CO, and VOCs to less harmful gases.'),
                ('buffering capacity', 'Ability of soil or water to neutralize acid inputs; granite areas have low buffering capacity.'),
                ('liming', 'Adding lime (CaCO₃) to acidified lakes to raise pH; treats symptoms, not causes.')],
               ['Trace acid rain formation from SO₂/NOₓ to deposition.', 'Describe impacts of acid rain on lakes and forests.', 'Evaluate acid rain control technologies.'],
               ['Explaining the chemistry of acid rain formation.', 'Comparing scrubbers vs. fuel switching as solutions.', 'Analyzing why granite-bedrock areas are more vulnerable to acidification.'],
               ['Khan Academy: Acid Rain', 'Bozeman Science: Acid Deposition'],
               [('Acid rain forms primarily from atmospheric reactions involving:', ['SO₂ and NOₓ from combustion', 'CO₂ and methane', 'CFCs and ozone', 'VOCs and particulates', 'CO and ozone']),
                ('Areas with granite bedrock are especially vulnerable to acid rain because granite:', ['Has low buffering capacity (cannot neutralize acid)', 'Has high calcium content', 'Absorbs rain rapidly', 'Reacts to form more acid', 'Is found only in urban areas']),
                ('Scrubbers help reduce acid rain by:', ['Removing SO₂ from power plant emissions before they leave the smokestack', 'Capturing CO₂', 'Neutralizing rain', 'Reducing NOₓ from cars', 'Liming nearby lakes']),
                ('Acid rain most directly affects aquatic ecosystems by:', ['Lowering lake pH and killing acid-sensitive organisms', 'Warming water temperature', 'Adding nutrients', 'Reducing oxygen', 'Increasing mercury']),
                ('Liming is only a short-term solution to lake acidification because:', ['It treats pH but does not reduce the SO₂ and NOₓ causing acid rain', 'It adds nutrients', 'It kills fish', 'It is too expensive', 'It only works in saltwater']),
               ],
               [('Bozeman Science: Acid Deposition', 'Covers acid rain formation, ecological impacts, and control strategies.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What two pollutants primarily cause acid rain?', 'How does acid rain harm forest ecosystems?', 'Why is liming only a temporary fix for acidified lakes?']
            ),
            _l('Stratospheric Ozone Depletion',
               [
                   _t('Ozone Layer Function', 'Stratospheric ozone (O₃) absorbs UV-B radiation, protecting life from DNA damage, skin cancer, and cataracts.', 'Stratospheric ozone and ground-level ozone are the same molecule but have opposite effects on human health.', 'Explain the importance of the stratospheric ozone layer.'),
                   _t('CFCs and Ozone Depletion', 'Chlorofluorocarbons (CFCs) release chlorine in the stratosphere; one Cl atom can destroy 100,000 ozone molecules. The ozone hole forms over Antarctica in spring.', 'The ozone hole forms due to ice crystal surfaces in polar stratospheric clouds that accelerate CFC reactions — it\'s not just from direct CFC emissions.', 'Describe the mechanism of CFC-caused ozone depletion.'),
                   _t('Montreal Protocol', 'The Montreal Protocol (1987) phased out CFCs globally; ozone layer is slowly recovering, demonstrating effective international environmental policy.', 'Ozone recovery is slow because CFCs persist in the stratosphere for decades.', 'Explain the success of the Montreal Protocol as a model for global environmental agreements.'),
               ],
               [('stratospheric ozone', 'O₃ layer 15–35 km altitude that absorbs harmful UV-B radiation.'),
                ('chlorofluorocarbon (CFC)', 'Industrial compound once used in refrigerants and aerosols; destroys ozone in stratosphere.'),
                ('ozone hole', 'Seasonal area of severe ozone depletion over Antarctica, caused by CFCs.'),
                ('UV-B radiation', 'Ultraviolet radiation that damages DNA; absorbed by stratospheric ozone.'),
                ('Montreal Protocol', '1987 international treaty that phased out CFCs; considered the most successful environmental treaty.')],
               ['Explain how CFCs destroy stratospheric ozone.', 'Describe the Antarctic ozone hole.', 'Evaluate the Montreal Protocol as a policy success.'],
               ['Explaining the catalytic chain reaction of ozone destruction.', 'Comparing ozone depletion to climate change as international policy challenges.', 'Predicting ozone recovery timeline.'],
               ['Khan Academy: Ozone Depletion', 'Bozeman Science: Ozone Layer'],
               [('Stratospheric ozone is important because it:', ['Absorbs UV-B radiation that damages DNA and causes skin cancer', 'Absorbs CO₂', 'Reflects sunlight to cool Earth', 'Produces oxygen for breathing', 'Blocks infrared radiation']),
                ('CFCs deplete ozone because they:', ['Release chlorine atoms that catalytically destroy O₃ molecules', 'React with UV to form acid rain', 'Block sunlight from reaching the ozone layer', 'Absorb ozone directly', 'React with CO₂ to produce chlorine']),
                ('The ozone hole forms primarily over Antarctica because:', ['Polar stratospheric clouds provide surfaces that accelerate CFC chemistry', 'Antarctica is closest to the sun', 'CFCs are produced there', 'Wind patterns concentrate CFCs over Antarctica', 'Antarctica has no UV protection']),
                ('The Montreal Protocol succeeded in reducing ozone depletion by:', ['Phasing out CFC production and use globally', 'Mandating scrubbers on all industry', 'Reducing CO₂ emissions', 'Increasing UV-blocking clouds', 'Banning all aerosol use']),
                ('The ozone layer is recovering slowly because:', ['CFCs already in the stratosphere persist for decades', 'Countries have not complied with the Montreal Protocol', 'CFCs are still being produced at high rates', 'Recovery requires ozone injections', 'UV-B levels are too high']),
               ],
               [('Bozeman Science: Ozone Depletion', 'Covers CFC chemistry, ozone hole, and Montreal Protocol.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What does stratospheric ozone protect us from?', 'How do CFCs destroy ozone?', 'Why is the Montreal Protocol considered a policy success?']
            ),
            _l('Indoor Air Pollution',
               [
                   _t('Radon and Carbon Monoxide', 'Radon (radioactive gas from uranium decay in soil) seeps into buildings and causes lung cancer; CO from incomplete combustion is colorless and odorless, causing poisoning.', 'Radon is a significant cancer risk even in well-sealed homes; testing and ventilation are the solutions.', 'Identify radon and CO as indoor air pollutants and describe their sources and health effects.'),
                   _t('VOCs and Sick Building Syndrome', 'VOCs from paints, furnishings, and cleaning products cause health problems indoors; sick building syndrome describes non-specific symptoms from poor indoor air quality.', 'Indoor air is often more polluted than outdoor air in developed countries due to synthetic materials and poor ventilation.', 'Describe indoor VOC sources and sick building syndrome.'),
                   _t('Indoor Pollution in Developing Countries', 'In developing countries, burning biomass (wood, dung, charcoal) for cooking indoors causes severe air pollution; a leading cause of respiratory disease globally.', 'Indoor biomass burning kills more people annually than outdoor air pollution in many developing regions.', 'Explain indoor biomass combustion as a major global health issue.'),
               ],
               [('radon', 'Radioactive gas produced from uranium decay in soil; seeps into buildings and causes lung cancer.'),
                ('carbon monoxide (CO)', 'Odorless, colorless gas from incomplete combustion; prevents oxygen transport in blood.'),
                ('sick building syndrome', 'Health condition caused by poor indoor air quality from chemicals, mold, or poor ventilation.'),
                ('biomass burning', 'Combustion of wood, dung, or agricultural residues for cooking; major indoor pollutant in developing countries.'),
                ('ventilation', 'Air exchange that dilutes indoor pollutants; key strategy for improving indoor air quality.')],
               ['Identify major indoor air pollutants and their health effects.', 'Explain sick building syndrome.', 'Describe the global health impact of indoor biomass burning.'],
               ['Comparing indoor vs. outdoor air quality in developed countries.', 'Identifying solutions to indoor air pollution.', 'Analyzing equity dimensions of indoor air pollution globally.'],
               ['Khan Academy: Indoor Air Pollution', 'Bozeman Science: Indoor Air Quality'],
               [('Radon causes lung cancer by:', ['Emitting radioactive particles that damage lung tissue', 'Blocking oxygen in the blood', 'Producing CO₂ indoors', 'Reacting with VOCs to form smog', 'Increasing humidity']),
                ('Carbon monoxide is dangerous because:', ['It binds to hemoglobin, preventing oxygen transport', 'It reacts with ozone', 'It is highly acidic', 'It irritates eyes', 'It is visible as brown haze']),
                ('Indoor air is often more polluted than outdoor air because:', ['Synthetic materials and poor ventilation concentrate VOCs and other pollutants indoors', 'Outdoor air contains more ozone', 'Buildings filter out outdoor pollutants', 'Indoor plants absorb all oxygen', 'Outdoor air circulates more']),
                ('In developing countries, the leading indoor air pollutant comes from:', ['Burning biomass (wood, dung) for cooking', 'Vehicle exhaust entering homes', 'Radon from soil', 'Industrial chemicals', 'Air conditioning']),
                ('The best solution to indoor radon exposure is:', ['Ventilation and sealing basement cracks', 'Installing air conditioners', 'Painting all surfaces', 'Removing all carpets', 'Increasing indoor temperature']),
               ],
               [('Bozeman Science: Indoor Air Pollution', 'Covers radon, CO, VOCs, and indoor biomass combustion.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is radon and how does it enter buildings?', 'Why is carbon monoxide particularly dangerous?', 'Why is indoor biomass burning a major health issue in developing countries?']
            ),
        ],
        'unit_qs': [
            ('Ground-level ozone is formed from:', ['NOₓ and VOCs reacting in sunlight', 'SO₂ and water vapor', 'CFC decomposition', 'CO₂ and methane', 'Particulates and humidity']),
            ('The pH of normal (clean) rain is approximately:', ['5.6 (slightly acidic due to dissolved CO₂)', '7.0 (neutral)', '4.0 (strongly acidic)', '6.0', '8.0 (slightly alkaline)']),
            ('Which control technology reduces SO₂ from power plant smokestacks?', ['Scrubbers', 'Catalytic converters', 'Liming', 'Carbon capture', 'Filters for PM only']),
            ('CFCs are dangerous to the stratosphere because:', ['They release chlorine atoms that catalytically destroy ozone', 'They are greenhouse gases', 'They absorb UV-B', 'They produce acid rain', 'They react with water to form sulfuric acid']),
            ('Photochemical smog is worst in cities with:', ['Heavy traffic, hot sunny days, and calm wind', 'Lots of industry and cold winters', 'High altitude and low humidity', 'Marine climates', 'Frequent rain']),
            ('The Montreal Protocol is considered a model environmental policy because:', ['It achieved global CFC phase-out with measurable ozone recovery', 'It reduced CO₂ by 50%', 'It replaced all CFCs with safe alternatives immediately', 'It required no economic sacrifice', 'It was passed unanimously by all nations instantly']),
            ('Acid deposition acidifies lakes by:', ['Lowering pH below levels tolerable for acid-sensitive organisms', 'Adding excess nutrients', 'Raising water temperature', 'Adding heavy metals directly', 'Reducing light penetration']),
            ('Radon is most dangerous in:', ['Poorly ventilated basements in homes built on uranium-bearing soil', 'Outdoor environments', 'Factories', 'High-rise apartments', 'Cars']),
            ('Industrial smog differs from photochemical smog in that it forms from:', ['SO₂ and particulates from coal in cold humid conditions', 'NOₓ and VOCs in hot sunny conditions', 'CFCs and ozone reactions', 'Radon and CO₂', 'Natural sources']),
            ('Fine particulate matter (PM2.5) causes the most harm by:', ['Penetrating deeply into lungs and entering the bloodstream', 'Blocking sunlight only', 'Causing acid rain', 'Reacting with ozone', 'Reflecting heat']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=6IDLSvCNPTs',
    },
    {
        'num': 8,
        'title': 'Unit 8: Aquatic and Terrestrial Pollution',
        'file': 'ap-environmental-science-8-unit-8-aquatic-and-terrestrial-pollution.html',
        'desc': 'Water pollution sources, solid waste, hazardous waste, and environmental remediation.',
        'gateway': [
            'Distinguish point and nonpoint source pollution.',
            'Explain how eutrophication creates dead zones.',
            'Describe solid and hazardous waste management strategies.',
            'Identify heavy metal and pesticide pathways in ecosystems.',
        ],
        'lessons': [
            _l('Water Pollution Sources',
               [
                   _t('Point vs. Nonpoint Sources', 'Point sources have identifiable discharge locations (pipes, drains); nonpoint sources are diffuse (agricultural runoff, urban stormwater).', 'Nonpoint source pollution is harder to regulate and is the leading cause of water quality degradation in the U.S.', 'Distinguish point and nonpoint sources and explain why each is challenging to control.'),
                   _t('Nutrient Pollution and Eutrophication', 'Excess N and P (from fertilizers, sewage) cause algal blooms; decomposers consume the dead algae using oxygen, creating hypoxic dead zones.', 'Algal blooms cause dead zones by depleting oxygen during decomposition, not directly by blocking sunlight.', 'Trace the eutrophication process from nutrient input to hypoxic dead zone.'),
                   _t('Thermal and Sediment Pollution', 'Thermal pollution (warm water from power plant cooling) decreases dissolved oxygen and stresses aquatic organisms. Sediment from erosion smothers bottom habitats and blocks light.', 'Warm water holds less dissolved oxygen — even without toxic chemicals, thermal pollution can suffocate fish.', 'Explain how thermal and sediment pollution harm aquatic ecosystems.'),
               ],
               [('point source pollution', 'Pollution from a specific, identifiable source (pipe, outfall).'),
                ('nonpoint source pollution', 'Diffuse pollution from multiple, dispersed sources (runoff).'),
                ('eutrophication', 'Nutrient enrichment of water leading to algal blooms and oxygen depletion.'),
                ('hypoxic dead zone', 'Area of low dissolved oxygen in water where most aquatic life cannot survive.'),
                ('thermal pollution', 'Addition of excess heat to water bodies, reducing dissolved oxygen.')],
               ['Distinguish point and nonpoint source pollution.', 'Trace the eutrophication process step by step.', 'Explain how thermal and sediment pollution harm aquatic life.'],
               ['Identifying sources of nutrient pollution in a watershed.', 'Explaining why dead zones form in coastal areas near river mouths.', 'Proposing solutions to thermal pollution.'],
               ['Khan Academy: Water Pollution', 'Bozeman Science: Water Quality'],
               [('Which is an example of a nonpoint source of pollution?', ['Agricultural runoff from fields after rain', 'A factory pipe discharging into a river', 'A sewage treatment plant outfall', 'An oil tanker spill', 'A mine drainage pipe']),
                ('In eutrophication, the dead zone forms because:', ['Decomposers consume dead algae, depleting oxygen', 'Algae directly remove oxygen', 'Nutrients kill fish directly', 'Water temperature rises', 'Sediment blocks light']),
                ('Thermal pollution decreases aquatic life primarily by:', ['Reducing dissolved oxygen in warm water', 'Adding toxic chemicals', 'Lowering pH', 'Increasing nutrients', 'Blocking light']),
                ('The Gulf of Mexico dead zone is primarily caused by:', ['Nitrogen and phosphorus runoff from Midwest agriculture via the Mississippi River', 'Industrial effluent from Gulf Coast factories', 'Oil drilling in the Gulf', 'Thermal pollution from Gulf power plants', 'Saltwater intrusion']),
                ('Nonpoint source pollution is harder to control than point source because:', ['It comes from many diffuse sources across the landscape', 'It contains more toxic chemicals', 'It cannot be detected', 'It occurs only in oceans', 'It is legally exempt from regulation']),
               ],
               [('Bozeman Science: Water Pollution', 'Covers point/nonpoint sources, eutrophication, and dead zones.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between point and nonpoint source pollution?', 'What causes a hypoxic dead zone to form?', 'How does thermal pollution harm fish?']
            ),
            _l('Toxic Pollutants',
               [
                   _t('Biomagnification', 'Fat-soluble toxins (DDT, PCBs, mercury) accumulate in fatty tissue and become more concentrated at higher trophic levels (biomagnification); top predators are most affected.', 'Bioaccumulation is within one organism; biomagnification is increasing concentration across trophic levels.', 'Explain biomagnification and identify which organisms are most at risk.'),
                   _t('Heavy Metals', 'Mercury (from coal combustion, industrial processes) methylates in water, bioaccumulates in fish, and causes neurological damage. Lead from old pipes causes developmental harm.', 'Mercury methylation by bacteria converts inorganic mercury to toxic methylmercury that bioaccumulates.', 'Trace mercury from source to human health impact; explain methylation.'),
                   _t('Pesticides', 'DDT bioaccumulates in predatory birds, thinning eggshells (by inhibiting calcium deposition), causing reproductive failure; led to the Endangered Species Act.', 'DDT was banned in the U.S. but is still used for malaria control in some countries — a genuine trade-off.', 'Describe DDT\'s history and the concept of eggshell thinning; evaluate pesticide trade-offs.'),
               ],
               [('biomagnification', 'Increasing concentration of a fat-soluble toxin in organisms at higher trophic levels.'),
                ('bioaccumulation', 'Build-up of a substance in an organism\'s tissues over time.'),
                ('methylmercury', 'Highly toxic organic form of mercury produced by bacteria; accumulates in fish.'),
                ('DDT', 'Persistent organochlorine pesticide; bioaccumulates and causes eggshell thinning in birds.'),
                ('fat-soluble toxin', 'Toxin that dissolves in fat rather than water; accumulates in fatty tissues and bioaccumulates.')],
               ['Explain biomagnification and identify most-at-risk organisms.', 'Trace mercury from coal combustion to human health impacts.', 'Describe DDT\'s ecological effects and policy history.'],
               ['Comparing bioaccumulation vs. biomagnification.', 'Explaining why top predators (eagles, dolphins) are most affected by fat-soluble toxins.', 'Evaluating trade-offs of DDT use for malaria control vs. ecological harm.'],
               ['Khan Academy: Toxic Pollutants', 'Bozeman Science: Biomagnification'],
               [('Biomagnification describes how:', ['Fat-soluble toxin concentration increases at higher trophic levels', 'Toxins accumulate in one organism over time', 'Toxins degrade in the food chain', 'Water-soluble toxins concentrate', 'Nutrients increase up the food chain']),
                ('Which organism is most affected by DDT biomagnification?', ['Bald eagle (tertiary predator)', 'Phytoplankton (producer)', 'Zooplankton (primary consumer)', 'Small fish (secondary consumer)', 'Bacteria']),
                ('Mercury in water is converted to toxic methylmercury by:', ['Bacteria in aquatic sediments', 'Sunlight reacting with inorganic mercury', 'Acid rain dissolving mercury', 'Fish metabolism', 'Industrial processes in water']),
                ('DDT caused reproductive failure in birds by:', ['Thinning eggshells so they broke before hatching', 'Directly killing chicks', 'Reducing food supply', 'Increasing egg temperature', 'Blocking nesting behavior']),
                ('Fat-soluble toxins are more dangerous than water-soluble ones because:', ['They are stored in fatty tissue and accumulate rather than being excreted', 'They are more reactive chemically', 'They dissolve more easily in water', 'They degrade more quickly', 'They are produced only by industry']),
               ],
               [('Bozeman Science: Biomagnification', 'Covers biomagnification, DDT, and mercury pathways.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between bioaccumulation and biomagnification?', 'Why are top predators most harmed by DDT and mercury?', 'How does DDT cause reproductive failure in birds?']
            ),
            _l('Solid and Hazardous Waste',
               [
                   _t('Municipal Solid Waste', 'Solid waste hierarchy: reduce → reuse → recycle → recover (energy) → dispose. Landfills produce methane (from decomposition) and leachate that can contaminate groundwater.', 'Recycling saves energy and materials but is only viable when there is a market for recovered materials.', 'Apply the solid waste hierarchy and evaluate trade-offs of each disposal method.'),
                   _t('Hazardous Waste', 'Hazardous waste (flammable, corrosive, reactive, toxic) must be treated, stored, and disposed of safely. Superfund (CERCLA) funds cleanup of contaminated sites.', 'NIMBY (not in my back yard) opposition often leads to siting hazardous waste facilities in low-income communities — an environmental justice issue.', 'Describe hazardous waste characteristics and the Superfund program.'),
                   _t('E-Waste and Plastics', 'Electronic waste contains heavy metals (lead, cadmium, mercury); informal recycling in developing countries exposes workers to toxins. Plastics persist in the environment and break into microplastics.', 'Microplastics are now found in virtually every ecosystem, including human blood and breast milk.', 'Describe e-waste and plastic pollution as emerging environmental concerns.'),
               ],
               [('solid waste hierarchy', 'Priority order: reduce, reuse, recycle, recover energy, landfill/incinerate.'),
                ('leachate', 'Liquid formed when water percolates through landfill waste, potentially contaminating groundwater.'),
                ('Superfund (CERCLA)', 'U.S. federal program that identifies and funds cleanup of hazardous waste sites.'),
                ('e-waste', 'Discarded electronic equipment containing toxic heavy metals.'),
                ('microplastics', 'Tiny plastic particles (<5mm) from degradation of larger plastic items; found in all environments.')],
               ['Apply the solid waste hierarchy.', 'Describe Superfund and hazardous waste management.', 'Explain e-waste and microplastic pollution.'],
               ['Ranking waste management options by environmental preference.', 'Analyzing environmental justice issues in waste siting.', 'Explaining microplastic pathways into ecosystems and human bodies.'],
               ['Khan Academy: Waste Management', 'Bozeman Science: Solid Waste'],
               [('The highest-priority option in the solid waste hierarchy is:', ['Reduce (use less in the first place)', 'Recycle', 'Reuse', 'Recover energy', 'Landfill']),
                ('Landfills produce methane because:', ['Anaerobic bacteria decompose organic waste, releasing CH₄', 'Incineration occurs underground', 'Plastic degrades to methane', 'Oxygen reacts with leachate', 'Chemical reactions produce natural gas']),
                ('Superfund was created to:', ['Fund cleanup of contaminated hazardous waste sites in the U.S.', 'Regulate new industrial emissions', 'Create recycling programs', 'Tax plastic producers', 'Monitor air quality']),
                ('E-waste is hazardous because it contains:', ['Heavy metals like lead, cadmium, and mercury that leach from improper disposal', 'Radioactive materials only', 'Corrosive acids', 'Biological agents', 'Flammable gases only']),
                ('Microplastics in the environment come from:', ['Degradation of larger plastic items into tiny particles', 'Direct industrial discharge only', 'Synthetic fertilizers', 'E-waste only', 'Fossil fuel combustion']),
               ],
               [('Bozeman Science: Solid Waste', 'Covers waste hierarchy, landfills, hazardous waste, and plastics.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['State the solid waste hierarchy in order.', 'What is Superfund?', 'Why are microplastics concerning?']
            ),
            _l('Remediation and Pollution Prevention',
               [
                   _t('Bioremediation', 'Bioremediation uses microorganisms to break down pollutants in soil or water; phytoremediation uses plants to absorb heavy metals.', 'Bioremediation is cost-effective but slow; it works for organic pollutants but not for heavy metals (use phytoremediation instead).', 'Describe bioremediation and phytoremediation and identify which pollutants each addresses.'),
                   _t('Wastewater Treatment', 'Primary treatment removes solids (settling); secondary treatment uses bacteria to decompose dissolved organic matter; tertiary treatment removes nutrients (N, P) and pathogens.', 'Secondary treatment is biological, not chemical; it uses microorganisms to break down BOD.', 'Describe each stage of wastewater treatment and the pollutants removed.'),
                   _t('Pollution Prevention', 'Green chemistry, cleaner production, and industrial ecology reduce pollution at the source rather than treating it after release.', 'Pollution prevention is more effective and cheaper than end-of-pipe treatment — but requires design changes.', 'Contrast source reduction with end-of-pipe treatment as pollution control strategies.'),
               ],
               [('bioremediation', 'Use of microorganisms to detoxify contaminated soil or water.'),
                ('phytoremediation', 'Use of plants to absorb and concentrate heavy metals from contaminated soil.'),
                ('primary wastewater treatment', 'Physical removal of large solids from wastewater by screening and settling.'),
                ('secondary wastewater treatment', 'Biological degradation of dissolved organic matter by bacteria.'),
                ('tertiary wastewater treatment', 'Advanced treatment removing nutrients (N, P) and pathogens; produces near-drinkable water.')],
               ['Distinguish bioremediation and phytoremediation.', 'Describe the three stages of wastewater treatment.', 'Contrast source reduction with end-of-pipe pollution control.'],
               ['Selecting remediation method for a given pollutant type.', 'Explaining why tertiary treatment is needed to prevent eutrophication.', 'Evaluating pollution prevention vs. cleanup costs.'],
               ['Khan Academy: Remediation', 'Bozeman Science: Wastewater Treatment'],
               [('Phytoremediation is most effective for cleaning up:', ['Heavy metal contamination (plants absorb metals from soil)', 'Oil spills in oceans', 'Airborne pollutants', 'Radioactive gases', 'Indoor VOCs']),
                ('Secondary wastewater treatment differs from primary by:', ['Using bacteria to biologically decompose dissolved organic matter', 'Settling solids only', 'Adding chemicals to remove nutrients', 'Filtering with charcoal', 'Using UV to kill pathogens']),
                ('Tertiary treatment is important for preventing eutrophication because:', ['It removes nitrogen and phosphorus that would otherwise enrich receiving water bodies', 'It reduces BOD', 'It removes large solids', 'It kills bacteria only', 'It improves water taste']),
                ('Bioremediation is preferred for organic pollutants because:', ['Microorganisms break down compounds into harmless byproducts', 'It removes heavy metals quickly', 'It requires no monitoring', 'It is faster than all alternatives', 'It works in any climate']),
                ('Pollution prevention is better than end-of-pipe treatment because:', ['It eliminates waste at the source rather than treating it after production', 'It is always more expensive', 'It produces more byproducts', 'It only works for water pollutants', 'It requires less regulation']),
               ],
               [('Bozeman Science: Remediation', 'Covers bioremediation, wastewater treatment, and pollution prevention.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between bioremediation and phytoremediation?', 'Why is tertiary wastewater treatment important for water quality?', 'What is the advantage of pollution prevention over treatment?']
            ),
        ],
        'unit_qs': [
            ('Eutrophication leads to dead zones through:', ['Algal blooms followed by decomposition that depletes oxygen', 'Direct toxicity of nutrients to fish', 'Thermal pollution from algae', 'Sediment from algal blooms', 'Salt accumulation']),
            ('Biomagnification means that DDT concentration is highest in:', ['Top predators (e.g., eagles, dolphins)', 'Producers (phytoplankton)', 'Primary consumers', 'The water', 'Sediment only']),
            ('The preferred approach in solid waste management is to first:', ['Reduce waste generation', 'Recycle materials', 'Recover energy', 'Landfill safely', 'Incinerate']),
            ('Nonpoint source pollution is difficult to control because:', ['It originates from many dispersed, unidentifiable sources across the landscape', 'It contains radioactive materials', 'It is always underground', 'It only occurs in oceans', 'It is regulated differently in each country']),
            ('Methylmercury bioaccumulates in aquatic food chains because:', ['It is fat-soluble and not easily excreted', 'It is water-soluble', 'Bacteria produce it only in fresh water', 'Fish actively concentrate it', 'It is found only near coal plants']),
            ('Superfund (CERCLA) was created to:', ['Clean up abandoned hazardous waste sites in the U.S.', 'Regulate air pollution', 'Tax industrial waste producers', 'Fund water treatment plants', 'Protect biodiversity hotspots']),
            ('Thermal pollution reduces dissolved oxygen because:', ['Warmer water holds less dissolved oxygen', 'Chemicals are added to warm water', 'Biological activity decreases', 'Sunlight is blocked', 'Pressure increases with temperature']),
            ('Leachate from landfills is dangerous because:', ['It can contaminate groundwater with toxic chemicals', 'It is flammable', 'It emits radioactive particles', 'It acidifies rain', 'It produces methane']),
            ('Phytoremediation is best used to clean up:', ['Heavy metal contaminated soil', 'Organic chemical spills in oceans', 'Air pollution', 'Sewage in water treatment', 'Radioactive gas leaks']),
            ('E-waste in developing countries is a problem because:', ['Informal recycling exposes workers to toxic heavy metals from electronics', 'Electronic devices are hard to disassemble', 'Developing countries lack electricity', 'It produces microplastics only', 'It contains radioactive materials exclusively']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=6IDLSvCNPTs',
    },
    {
        'num': 9,
        'title': 'Unit 9: Global Change',
        'file': 'ap-environmental-science-9-unit-9-global-change.html',
        'desc': 'Climate change causes, evidence, impacts, and strategies for mitigation and adaptation.',
        'gateway': [
            'Explain the greenhouse effect and how human activities enhance it.',
            'Summarize the evidence for current climate change.',
            'Predict consequences of climate change for ecosystems and humans.',
            'Distinguish mitigation from adaptation strategies.',
        ],
        'lessons': [
            _l('The Greenhouse Effect and Climate',
               [
                   _t('Natural Greenhouse Effect', 'Greenhouse gases (H₂O, CO₂, CH₄, N₂O, O₃) trap outgoing infrared radiation, warming Earth to a habitable 15°C average; without it, Earth would be −18°C.', 'The greenhouse effect itself is natural and essential for life; the problem is human enhancement of it.', 'Explain the natural greenhouse effect and distinguish it from the enhanced (human-caused) greenhouse effect.'),
                   _t('Enhanced Greenhouse Effect', 'Human activities (fossil fuel combustion, deforestation, agriculture, cement production) have increased atmospheric CO₂ from 280 ppm (pre-industrial) to over 420 ppm today.', 'CO₂ is not the most potent greenhouse gas (methane is ~80× stronger per molecule), but it is emitted in the largest quantities.', 'Identify human sources of major greenhouse gases and explain why CO₂ is the primary driver of current warming.'),
                   _t('Carbon Cycle and Feedback Loops', 'Positive feedbacks (ice-albedo, permafrost methane release, water vapor) amplify warming; negative feedbacks (increased plant growth, ocean absorption) partially offset it.', 'Positive feedback does not mean beneficial — it means self-amplifying; ice-albedo feedback is a major amplifier of warming.', 'Describe positive and negative climate feedback loops.'),
               ],
               [('greenhouse effect', 'Warming of Earth\'s surface by greenhouse gases trapping outgoing infrared radiation.'),
                ('greenhouse gas', 'Gas that absorbs and re-emits infrared radiation (CO₂, CH₄, N₂O, H₂O, O₃).'),
                ('albedo', 'Reflectivity of a surface; ice has high albedo, ocean and forests have low albedo.'),
                ('positive feedback', 'Self-amplifying process that increases the original change (e.g., ice melts → lower albedo → more warming → more ice melts).'),
                ('carbon sink', 'Reservoir that absorbs more carbon than it releases (forests, oceans).')],
               ['Explain the greenhouse effect and the role of each GHG.', 'Identify human sources of CO₂, CH₄, and N₂O.', 'Describe climate feedback loops.'],
               ['Distinguishing natural vs. enhanced greenhouse effect.', 'Explaining the ice-albedo feedback loop.', 'Identifying which human activities produce which greenhouse gases.'],
               ['Khan Academy: Climate Change', 'Bozeman Science: Global Warming'],
               [('The natural greenhouse effect keeps Earth warm by:', ['GHGs absorbing outgoing infrared radiation and re-radiating it back to Earth', 'Blocking incoming UV radiation', 'Increasing solar radiation reaching the surface', 'Preventing cloud formation', 'Producing heat through chemical reactions']),
                ('Atmospheric CO₂ has increased from ~280 ppm to over 420 ppm due to:', ['Burning fossil fuels and deforestation', 'Volcanic eruptions only', 'Natural climate cycles', 'Ocean outgassing', 'Increased plant respiration']),
                ('The ice-albedo feedback is a positive feedback because:', ['Melting ice exposes darker ocean/land that absorbs more heat → more melting', 'Ice reflects heat, cooling the planet', 'Ice formation increases with warming', 'Albedo increases as ice melts', 'Dark surfaces reflect more heat']),
                ('Methane (CH₄) is produced primarily by:', ['Agriculture (livestock, rice paddies) and landfills', 'Burning oil only', 'Deforestation only', 'Industrial cooling systems', 'Coal combustion only']),
                ('A carbon sink is important because it:', ['Absorbs CO₂ from the atmosphere, partially offsetting emissions', 'Produces carbon dioxide', 'Increases methane in the atmosphere', 'Amplifies warming', 'Reflects infrared radiation']),
               ],
               [('Bozeman Science: Greenhouse Effect', 'Covers GHGs, enhanced greenhouse effect, and feedback loops.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the greenhouse effect?', 'Name three human activities that produce greenhouse gases.', 'Explain the ice-albedo feedback loop.']
            ),
            _l('Evidence and Consequences of Climate Change',
               [
                   _t('Evidence for Climate Change', 'Lines of evidence: direct temperature measurements, ice core records, sea level rise, shrinking glaciers/Arctic ice, species range shifts, and phenological changes all confirm warming.', 'Ice cores provide temperature records going back 800,000 years — long before human thermometers.', 'Summarize multiple lines of evidence for current climate change.'),
                   _t('Climate Change Impacts', 'Consequences include: sea level rise (thermal expansion + ice melt), increased extreme weather, ocean acidification (CO₂ + H₂O → H₂CO₃), coral bleaching, biome shifts, and increased disease vectors.', 'Ocean acidification is separate from temperature rise — it is caused directly by CO₂ dissolving in water, lowering pH.', 'Predict consequences of climate change for ecosystems, coastlines, and human society.'),
                   _t('Ocean Acidification', 'Oceans absorb ~25% of human CO₂ emissions; CO₂ dissolves to form carbonic acid, lowering ocean pH (from 8.2 to 8.1 since industrial revolution — a 26% increase in H⁺).', 'A decrease of 0.1 pH units represents a 26% increase in acidity because pH is logarithmic.', 'Explain ocean acidification chemistry and impacts on marine organisms.'),
               ],
               [('ice core', 'Cylindrical sample from polar ice containing trapped air bubbles with ancient atmospheric CO₂ records.'),
                ('sea level rise', 'Increase in global mean sea level from thermal expansion of water and melting glaciers/ice sheets.'),
                ('ocean acidification', 'Decrease in ocean pH caused by absorption of atmospheric CO₂.'),
                ('coral bleaching', 'Expulsion of symbiotic algae from coral when water temperature rises; leads to coral death if prolonged.'),
                ('phenological change', 'Shift in timing of biological events (flowering, migration) in response to climate change.')],
               ['List multiple lines of evidence for climate change.', 'Predict impacts of climate change on ecosystems and coastlines.', 'Explain the chemistry of ocean acidification.'],
               ['Interpreting CO₂ and temperature graphs from ice cores.', 'Explaining how ocean acidification affects shell-forming organisms.', 'Connecting sea level rise to coastal displacement of human populations.'],
               ['Khan Academy: Evidence for Climate Change', 'Bozeman Science: Climate Change Impacts'],
               [('Ice core data provides evidence of climate change by:', ['Showing atmospheric CO₂ and temperature correlations going back 800,000 years', 'Measuring current air temperature', 'Tracking glacier retreat', 'Showing sea level records', 'Recording species extinction dates']),
                ('Ocean acidification is caused by:', ['CO₂ dissolving in seawater forming carbonic acid, lowering pH', 'Thermal expansion of warm water', 'Acid rain entering oceans', 'Industrial chemical discharge', 'Melting of polar ice']),
                ('Coral bleaching occurs when:', ['Warm water causes corals to expel symbiotic algae; corals turn white and may die', 'Pollution adds bleach to water', 'Ocean pH rises', 'Algae overgrow corals', 'Sea level falls']),
                ('A sea level rise of 1 meter would most harm:', ['Low-lying coastal and island nations (Bangladesh, Pacific islands)', 'Mountainous regions', 'High-latitude continents', 'Deserts', 'Forested interiors']),
                ('Ocean pH has decreased from 8.2 to 8.1 since industrialization. This represents:', ['A 26% increase in H⁺ concentration (pH scale is logarithmic)', 'A tiny, insignificant change', 'A 10% decrease in acidity', 'A neutral change', 'A 1% change in H⁺']),
               ],
               [('Bozeman Science: Climate Change Evidence', 'Covers ice cores, sea level rise, and ocean acidification.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['Name three lines of evidence for current climate change.', 'What causes ocean acidification?', 'How does coral bleaching occur?']
            ),
            _l('Mitigation Strategies',
               [
                   _t('Reducing Emissions', 'Mitigation reduces GHG emissions by switching to renewables, improving energy efficiency, electrifying transportation, and sustainable land use.', 'Mitigation does not mean ending climate change — some warming is already locked in; it reduces future harm.', 'Identify and evaluate major mitigation strategies for climate change.'),
                   _t('Carbon Sequestration', 'Reforestation, soil carbon storage, ocean fertilization, and direct air capture store CO₂; these supplement (but cannot replace) emission reductions.', 'Planting trees absorbs CO₂ but takes decades and may not offset emissions if trees burn or die.', 'Evaluate carbon sequestration methods and their limitations.'),
                   _t('International Climate Policy', 'Paris Agreement (2015) sets voluntary targets to limit warming to 1.5–2°C above pre-industrial levels; challenges include enforcement, equity between nations, and ambition gap.', 'The Paris Agreement is voluntary and non-binding — its effectiveness depends on national commitment.', 'Explain the Paris Agreement framework and challenges for international climate policy.'),
               ],
               [('mitigation', 'Actions that reduce greenhouse gas emissions or enhance carbon sinks to slow climate change.'),
                ('carbon sequestration', 'Capturing and storing carbon dioxide from the atmosphere in biological or geological reservoirs.'),
                ('reforestation', 'Planting trees in deforested areas; removes CO₂ from atmosphere over decades.'),
                ('Paris Agreement', '2015 international accord aiming to limit global warming to 1.5–2°C above pre-industrial levels.'),
                ('net-zero emissions', 'State where GHG emissions equal removals; the global target to stop climate change.')],
               ['Identify major GHG mitigation strategies.', 'Evaluate carbon sequestration methods and limitations.', 'Explain the Paris Agreement and challenges for climate policy.'],
               ['Comparing mitigation strategies by cost and effectiveness.', 'Evaluating reforestation vs. direct air capture.', 'Analyzing equity issues in the Paris Agreement.'],
               ['Khan Academy: Climate Mitigation', 'Bozeman Science: Climate Solutions'],
               [('Mitigation of climate change focuses on:', ['Reducing greenhouse gas emissions to slow future warming', 'Adapting communities to already-occurring changes', 'Removing CO₂ only through trees', 'Reducing fossil fuel costs', 'Increasing cloud cover']),
                ('The Paris Agreement aims to limit warming to:', ['1.5–2°C above pre-industrial levels', '4°C above today\'s level', '0.5°C total', '1°C below pre-industrial', '3°C above industrial average']),
                ('A limitation of tree planting as a carbon sequestration strategy is:', ['Trees take decades to grow, and may burn or die, releasing the stored CO₂', 'Trees produce oxygen, not absorb CO₂', 'There is no suitable land for trees', 'Trees only work in the tropics', 'Reforestation is more expensive than CCS']),
                ('The Paris Agreement is criticized because:', ['Targets are voluntary and not legally binding', 'It focuses only on adaptation', 'It mandates fossil fuel phase-out immediately', 'It ignores developing nations', 'It was signed by only a few countries']),
                ('Net-zero emissions means:', ['Remaining emissions are balanced by equivalent carbon removal', 'No emissions are produced at all', 'All fossil fuels are banned', 'Only renewable energy is used', 'Emissions are 50% below 1990 levels']),
               ],
               [('Bozeman Science: Climate Solutions', 'Covers mitigation strategies, sequestration, and Paris Agreement.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between mitigation and adaptation?', 'What is net-zero emissions?', 'What is the goal of the Paris Agreement?']
            ),
            _l('Adaptation and Sustainability',
               [
                   _t('Climate Adaptation', 'Adaptation adjusts human systems to cope with actual or expected climate impacts: sea walls, drought-resistant crops, early warning systems, and managed retreat from flood zones.', 'Adaptation does not stop climate change — it reduces harm from changes that are already occurring or locked in.', 'Distinguish mitigation from adaptation and give examples of each.'),
                   _t('Sustainable Development', 'Sustainable development meets present needs without compromising the ability of future generations to meet their own needs (Brundtland definition); balances economic, social, and environmental goals.', 'Sustainability is not just environmental — social equity and economic viability are equally important pillars.', 'Apply the three pillars of sustainability to evaluate development decisions.'),
                   _t('Environmental Justice', 'Environmental justice recognizes that environmental burdens (pollution, climate impacts) fall disproportionately on low-income and minority communities; solutions must address equity alongside ecology.', 'Climate change is an environmental justice issue: those least responsible for emissions (poor nations, poor communities) are most vulnerable.', 'Explain environmental justice and apply it to climate and pollution case studies.'),
               ],
               [('adaptation', 'Adjusting human systems to minimize harm from climate change impacts that are already occurring.'),
                ('sustainable development', 'Development that meets present needs without compromising future generations\' ability to meet theirs.'),
                ('three pillars of sustainability', 'Environmental, economic, and social dimensions that must all be balanced.'),
                ('managed retreat', 'Planned relocation of communities away from high-risk coastal or flood areas.'),
                ('environmental justice', 'Equitable distribution of environmental benefits and burdens across all communities.')],
               ['Distinguish mitigation from adaptation with examples.', 'Apply the Brundtland definition of sustainable development.', 'Explain environmental justice and its relevance to climate change.'],
               ['Evaluating adaptation strategies for a coastal city.', 'Applying three pillars of sustainability to a development scenario.', 'Analyzing who bears climate change burdens and why.'],
               ['Khan Academy: Sustainability', 'Bozeman Science: Sustainable Development'],
               [('An example of climate ADAPTATION (not mitigation) is:', ['Building sea walls to protect coastal cities from rising seas', 'Switching from coal to solar energy', 'Planting trees to absorb CO₂', 'Installing more efficient appliances', 'Signing the Paris Agreement']),
                ('The Brundtland definition of sustainable development emphasizes:', ['Meeting present needs without compromising future generations\' ability to do the same', 'Maximum economic growth regardless of environmental cost', 'Environmental protection at any economic cost', 'Technology as the only solution', 'National development over global concerns']),
                ('Environmental justice is concerned with:', ['Equitable distribution of environmental burdens and benefits across communities', 'Environmental policy in wealthy nations only', 'Protecting only endangered species', 'International trade agreements', 'Carbon pricing systems']),
                ('Which population is most vulnerable to climate change impacts?', ['Low-income communities in flood-prone coastal areas of developing nations', 'Wealthy nations with the most emissions', 'Polar bear populations in the Arctic', 'High-altitude communities', 'Desert nations with no coastline']),
                ('Managed retreat addresses climate change by:', ['Relocating communities away from high-risk areas rather than defending them', 'Stopping sea level rise', 'Building walls around vulnerable areas', 'Reducing emissions from coastal cities', 'Planting mangroves only']),
               ],
               [('Bozeman Science: Sustainability', 'Covers adaptation, sustainable development, and environmental justice.', 'https://www.youtube.com/watch?v=6IDLSvCNPTs')],
               ['What is the difference between mitigation and adaptation?', 'State the Brundtland definition of sustainable development.', 'Why is climate change an environmental justice issue?']
            ),
        ],
        'unit_qs': [
            ('The greenhouse effect works by:', ['GHGs absorbing and re-radiating outgoing infrared radiation back to Earth\'s surface', 'Blocking incoming solar radiation', 'Increasing solar energy reaching the surface', 'Preventing convection in the atmosphere', 'Reflecting UV radiation']),
            ('Atmospheric CO₂ has increased primarily because of:', ['Burning fossil fuels and deforestation', 'Natural volcanic activity', 'Ocean outgassing', 'Changes in Earth\'s orbit', 'Increased plant respiration']),
            ('The ice-albedo feedback amplifies warming because:', ['Melting ice exposes darker surfaces that absorb more heat, causing more melting', 'Ice reflects infrared radiation', 'Dark surfaces cool faster than ice', 'Ice formation is slowed by CO₂', 'Albedo increases with warming']),
            ('Ocean acidification differs from global warming because:', ['It is directly caused by CO₂ dissolving in water, independent of temperature rise', 'It makes oceans warmer', 'It is caused by methane only', 'It has no effect on marine life', 'It raises pH']),
            ('Which provides 800,000 years of CO₂ and temperature data?', ['Ice core records', 'Weather station records', 'Tree ring data', 'Ocean sediment only', 'Satellite records']),
            ('Mitigation of climate change focuses on:', ['Reducing GHG emissions to limit future warming', 'Adapting infrastructure to sea level rise', 'Moving communities away from coasts', 'Studying climate models', 'Removing existing CO₂ only']),
            ('The Paris Agreement aims to limit global warming to:', ['1.5–2°C above pre-industrial levels', '4°C above pre-industrial', '1°C above today', '2°C below current temperatures', 'Zero warming immediately']),
            ('An adaptation strategy (not mitigation) for climate change is:', ['Building sea walls and drought-resistant crops', 'Installing solar panels', 'Improving car fuel efficiency', 'Carbon cap-and-trade', 'Reducing deforestation']),
            ('Environmental justice recognizes that:', ['Environmental burdens fall disproportionately on low-income and minority communities', 'Rich nations bear most climate impacts', 'All communities face equal environmental risks', 'Only developing nations create pollution', 'Pollution affects only nonhuman species']),
            ('A positive climate feedback:', ['Amplifies initial warming (e.g., melting ice → lower albedo → more warming)', 'Counteracts warming', 'Has beneficial effects on ecosystems', 'Reduces CO₂ in the atmosphere', 'Is produced by renewable energy']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=6IDLSvCNPTs',
    },
]
