NAME = 'AP® Human Geography'
ABBREV = 'aphug'
SLUG = 'ap-human-geography'
COURSE_FILE = 'ap-human-geography.html'
ACCENT_COLOR = '#f97316'

def _t(ti, co, mi, ht):
    return {'title': ti, 'content': co, 'misconception': mi, 'how_tested': ht}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, ext):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': ext}

UNITS = [
  {
    'num': 4,
    'title': 'Unit 4: Political Patterns and Processes',
    'file': 'ap-human-geography-4-unit-4-political-patterns-and-processes.html',
    'desc': 'Explores how political power is organized across space, including state formation, boundaries, centripetal and centrifugal forces, and supranational organizations.',
    'gateway': [
        'What distinguishes a state from a nation?',
        'How do borders reflect and reinforce political power?',
        'What forces hold states together or pull them apart?',
        'How has supranationalism reshaped traditional sovereignty?',
    ],
    'lessons': [
      _l('States, Nations, and Sovereignty',
        [
          _t('State vs. Nation vs. Nation-State',
             'A state is a politically organized territory with sovereignty; a nation is a group sharing cultural identity; a nation-state ideally merges both.',
             'Students confuse "nation" with "country"—a nation is cultural, a state is political.',
             'FRQ asks you to distinguish these terms using real-world examples like the Kurds (nation without a state).'),
          _t('Territoriality and Sovereignty',
             'Territoriality is the effort to control and defend an area; sovereignty is the right of a state to govern itself free from external interference.',
             'Sovereignty is often treated as absolute, but international law and supranational bodies limit it in practice.',
             'MCQ may show scenarios where sovereignty is challenged and ask you to identify the concept.'),
          _t('Stateless Nations and Multinational States',
             'Stateless nations (Kurds, Palestinians) lack an independent state; multinational states (Russia, India) contain multiple national groups within one political unit.',
             'Not all multinational states are unstable—many manage diversity through federalism or power-sharing.',
             'FRQ may ask you to identify consequences of stateless nations using geographic evidence.'),
        ],
        ['State', 'Nation', 'Nation-state', 'Sovereignty', 'Stateless nation'],
        ['Define state, nation, and nation-state with examples.',
         'Explain how territoriality underpins political authority.',
         'Analyze challenges that stateless nations pose to state sovereignty.'],
        ['Terms defined in short-answer with real-world examples.',
         'MCQ scenarios test conceptual distinctions between nation and state.',
         'FRQ asks for spatial reasoning about political identity.'],
        ['Create a comparison table: state vs. nation vs. nation-state.',
         'Identify three stateless nations and map their territories.'],
        [
          ('Which term best describes the Kurdish people who share a common culture but lack their own independent country?',
           ['Nation-state', 'Sovereign state', 'Stateless nation', 'Multinational state']),
          ('A country that contains several distinct cultural groups within its borders is best described as a',
           ['Nation-state', 'Multinational state', 'Stateless nation', 'Unitary state']),
          ('Sovereignty primarily refers to a state\'s right to',
           ['Control immigration policy only', 'Govern itself free from external interference', 'Join supranational organizations', 'Expand its territory']),
          ('Territoriality is best defined as',
           ['The physical size of a country', 'The effort to control and defend an area', 'The cultural homogeneity of a population', 'The economic output of a region']),
          ('Which scenario best illustrates a nation-state?',
           ['The United States, a highly diverse country', 'Japan, where one dominant ethnic group aligns with the state', 'The European Union, a supranational body', 'The Kurdish region of Turkey']),
        ],
        ['https://www.youtube.com/watch?v=lku6fhr0q1c'],
        ['What is the difference between a nation and a state?',
         'Give one example of a stateless nation and explain its situation.',
         'How does sovereignty limit outside interference in a state\'s affairs?']),

      _l('Political Boundaries',
        [
          _t('Types of Boundaries',
             'Boundaries can be physical (rivers, mountains), cultural (language, religion), geometric (straight lines), or relic (no longer functioning but visible).',
             'Physical boundaries are not always stable—rivers shift and mountains don\'t always separate cultures effectively.',
             'MCQ and FRQ both ask you to classify boundaries by type using maps or written descriptions.'),
          _t('Boundary Evolution: Antecedent, Subsequent, Superimposed',
             'Antecedent boundaries predate settlement; subsequent boundaries evolve with cultural landscape; superimposed boundaries are drawn by outside powers ignoring existing cultures.',
             'Superimposed does not mean "recent"—the term describes origin, not timing.',
             'FRQ frequently uses Africa\'s colonial borders as a case study for superimposed boundaries.'),
          _t('Boundary Disputes',
             'Disputes include positional (where the line is), territorial (who owns the land), resource (access to resources crossing borders), and functional (how the border operates).',
             'Territorial and positional disputes are often conflated—positional is about the line itself, territorial is about ownership of larger areas.',
             'MCQ asks you to classify dispute types based on scenario descriptions.'),
        ],
        ['Antecedent boundary', 'Subsequent boundary', 'Superimposed boundary', 'Relic boundary', 'Geometric boundary'],
        ['Classify boundary types using real-world examples.',
         'Explain why superimposed boundaries often create political instability.',
         'Distinguish between types of boundary disputes.'],
        ['Map-based MCQ showing boundary types requiring classification.',
         'FRQ citing African colonial borders as evidence.',
         'Scenario questions testing dispute type identification.'],
        ['Sketch a world map marking 3 antecedent and 3 superimposed boundaries.',
         'Research one active boundary dispute and classify its type.'],
        [
          ('The boundary between the United States and Canada along the 49th parallel is best classified as a',
           ['Physical boundary', 'Relic boundary', 'Geometric boundary', 'Subsequent boundary']),
          ('African colonial boundaries that divided ethnic groups across multiple countries are called',
           ['Antecedent boundaries', 'Superimposed boundaries', 'Subsequent boundaries', 'Relic boundaries']),
          ('A dispute over which country has the right to drill for oil beneath the ocean floor near a shared maritime border is a',
           ['Positional dispute', 'Territorial dispute', 'Resource dispute', 'Functional dispute']),
          ('A boundary that formed before significant human settlement of the area is termed',
           ['Relic', 'Superimposed', 'Antecedent', 'Subsequent']),
          ('The former boundary between East and West Germany, which no longer functions politically but remains visible in settlement patterns, is an example of a',
           ['Geometric boundary', 'Relic boundary', 'Antecedent boundary', 'Superimposed boundary']),
        ],
        ['https://www.youtube.com/watch?v=lku6fhr0q1c'],
        ['What makes a boundary "superimposed" rather than "subsequent"?',
         'Name one resource dispute and explain the geographic cause.',
         'How do relic boundaries continue to shape landscapes after they stop functioning?']),

      _l('Centripetal and Centrifugal Forces',
        [
          _t('Centripetal Forces',
             'Centripetal forces unify a state, including shared language, religion, national symbols, strong institutions, and common historical narrative.',
             'A single centripetal force is rarely sufficient—states need multiple unifying factors for long-term cohesion.',
             'FRQ asks you to explain how centripetal forces maintain political stability using specific examples.'),
          _t('Centrifugal Forces',
             'Centrifugal forces divide a state, including ethnic conflict, regional economic inequality, separatism, and religious differences.',
             'Centrifugal forces don\'t automatically cause state collapse—they create pressure but states often manage them.',
             'MCQ may present a scenario of regional inequality and ask you to identify the centrifugal force at work.'),
          _t('Devolution',
             'Devolution transfers power from a central government to regional governments, often as a response to centrifugal pressures (e.g., Catalonia, Scotland, Quebec).',
             'Devolution does not mean independence—it is a partial transfer of authority within an existing state.',
             'FRQ may ask you to explain devolution using a case study and connect it to centrifugal forces.'),
        ],
        ['Centripetal force', 'Centrifugal force', 'Devolution', 'Separatism', 'Balkanization'],
        ['Identify specific centripetal and centrifugal forces in named states.',
         'Explain how devolution responds to centrifugal pressures.',
         'Analyze conditions under which balkanization may occur.'],
        ['FRQ scenarios presenting political instability for force analysis.',
         'MCQ identifies forces from descriptions of real events.',
         'Case studies of devolution movements tested in short answer.'],
        ['List 3 centripetal and 3 centrifugal forces for one country.',
         'Research the Scottish independence movement as a devolution case.'],
        [
          ('A shared national language that promotes unity within a state is an example of a',
           ['Centrifugal force', 'Centripetal force', 'Devolutionary force', 'Balkanizing force']),
          ('When ethnic minorities demand greater autonomy within a state, this represents a',
           ['Centripetal force', 'Supranational trend', 'Centrifugal force', 'Federal consolidation']),
          ('The process by which a central government transfers power to regional governments is called',
           ['Balkanization', 'Devolution', 'Annexation', 'Supranationalism']),
          ('Which scenario best illustrates balkanization?',
           ['France granting Corsica limited regional autonomy', 'The breakup of Yugoslavia into multiple smaller states', 'Germany reunifying after the Cold War', 'The UK joining the European Union']),
          ('Significant regional economic inequality within a state acts as a',
           ['Centripetal force promoting investment', 'Centrifugal force encouraging separatism', 'Supranational integration driver', 'Federal stabilizing mechanism']),
        ],
        ['https://www.youtube.com/watch?v=lku6fhr0q1c'],
        ['Define devolution and give one real-world example.',
         'How can regional economic inequality act as a centrifugal force?',
         'What is balkanization and why is it named after a specific region?']),

      _l('Electoral Geography and Supranationalism',
        [
          _t('Gerrymandering and Electoral Districts',
             'Gerrymandering manipulates district boundaries to favor one political party or group; it can dilute minority voting power (cracking) or concentrate it (packing).',
             'Gerrymandering is not always illegal—courts have upheld many districts even when partisan intent is clear.',
             'MCQ presents district maps and asks you to identify gerrymandering effects.'),
          _t('Supranational Organizations',
             'Supranational organizations (UN, EU, NATO, WTO) require member states to cede some sovereignty in exchange for collective benefits like security, trade, or diplomacy.',
             'Joining a supranational organization does not eliminate state sovereignty—states retain significant independent authority.',
             'FRQ asks you to evaluate benefits and challenges of supranationalism using specific organizations as evidence.'),
          _t('Shatterbelt and Choke Points',
             'A shatterbelt is a politically fragmented region caught between competing great powers (e.g., Eastern Europe, Middle East); choke points are strategic narrow passages controlling trade routes.',
             'Shatterbelts are defined by geopolitical competition, not just internal fragmentation alone.',
             'MCQ and FRQ may use maps to test identification of shatterbelts and choke points.'),
        ],
        ['Gerrymandering', 'Supranationalism', 'Shatterbelt', 'Choke point', 'Electoral geography'],
        ['Explain how gerrymandering affects political representation.',
         'Evaluate trade-offs of joining supranational organizations.',
         'Identify examples of shatterbelts and choke points on a map.'],
        ['Map-based questions showing district shapes for gerrymandering analysis.',
         'FRQ asks for evaluation of EU or UN as supranational bodies.',
         'MCQ tests definitions of geopolitical terms.'],
        ['Draw a hypothetical gerrymandered vs. fair district for the same population.',
         'Research one supranational organization and list 3 benefits and 2 challenges.'],
        [
          ('Drawing legislative districts to concentrate opposition voters into as few districts as possible is called',
           ['Cracking', 'Packing', 'Redlining', 'Zoning']),
          ('When states transfer some decision-making authority to a supranational body in exchange for collective benefits, this is called',
           ['Devolution', 'Federalism', 'Supranationalism', 'Balkanization']),
          ('Eastern Europe\'s history of being contested by competing great powers makes it an example of a',
           ['Buffer state', 'Shatterbelt region', 'Federal zone', 'Unitary region']),
          ('The Strait of Hormuz, through which a large percentage of the world\'s oil passes, is best described as a',
           ['Shatterbelt', 'Choke point', 'Buffer state', 'Relic boundary']),
          ('A primary challenge of supranational organizations is that member states must',
           ['Give up all independent military control', 'Cede some sovereignty to collective decision-making', 'Adopt a single currency immediately', 'Eliminate all internal border controls']),
        ],
        ['https://www.youtube.com/watch?v=lku6fhr0q1c'],
        ['What is gerrymandering and how does it affect minority representation?',
         'Name one supranational organization and explain one trade-off of membership.',
         'What distinguishes a shatterbelt from simply a politically unstable region?']),
    ],
    'unit_qs': [
      ('A country where one ethnic group seeks independence from the central government is experiencing primarily',
       ['Supranationalism', 'Centripetal consolidation', 'Devolutionary pressure', 'Electoral realignment']),
      ('Which type of boundary was most commonly imposed on African nations during the colonial period?',
       ['Antecedent', 'Subsequent', 'Superimposed', 'Relic']),
      ('The European Union requires member nations to follow certain trade regulations, illustrating',
       ['Balkanization', 'Supranationalism', 'Devolution', 'Gerrymandering']),
      ('A state with a high degree of cultural and linguistic homogeneity is most likely to have strong',
       ['Centrifugal forces', 'Centripetal forces', 'Devolutionary pressures', 'Boundary disputes']),
      ('Catalonia\'s push for independence from Spain is best explained by',
       ['Supranationalism', 'Centripetal unity', 'Devolutionary separatism', 'Geometric boundary disputes']),
      ('Which term describes a region where several small, ethnically distinct states have replaced a larger political unit?',
       ['Shatterbelt', 'Buffer state', 'Balkanized region', 'Federal district']),
      ('A positional boundary dispute involves disagreement over',
       ['The exact location of the boundary line', 'Which country owns a territory', 'Access to natural resources crossing the border', 'How border regulations are enforced']),
      ('The Kurds represent which political geographic concept?',
       ['Nation-state', 'Multinational state', 'Stateless nation', 'Buffer state']),
      ('Gerrymandering primarily affects',
       ['Economic development patterns', 'Political representation through district manipulation', 'Supranational membership eligibility', 'Boundary classification systems']),
      ('Which geographic feature is most commonly used to establish physical boundaries?',
       ['Deserts only', 'Mountain ranges and rivers', 'Latitudinal parallels', 'Population density contours']),
    ],
  },

  {
    'num': 5,
    'title': 'Unit 5: Agriculture and Rural Land-Use Patterns and Processes',
    'file': 'ap-human-geography-5-unit-5-agriculture-and-rural-land-use-patterns-and-processes.html',
    'desc': 'Examines the origins, diffusion, and evolution of agriculture, modern farming systems, rural settlement patterns, and challenges of food security in a globalizing world.',
    'gateway': [
        'How and why did agriculture originate in specific hearths?',
        'How have green revolution technologies changed food production?',
        'What spatial patterns characterize rural settlement and land use?',
        'How does globalization affect food systems and sustainability?',
    ],
    'lessons': [
      _l('Agricultural Origins and Diffusion',
        [
          _t('First Agricultural Revolution',
             'The First Agricultural Revolution (Neolithic Revolution) involved the domestication of plants and animals beginning around 10,000 BCE in multiple hearths including the Fertile Crescent, Huang He Valley, and Mesoamerica.',
             'Agriculture did not originate in one place and spread—it developed independently in multiple hearths around the world.',
             'FRQ asks you to identify hearths and explain how domestication shaped early civilizations.'),
          _t('Agricultural Hearths and Diffusion',
             'Agricultural practices diffused from hearths through relocation and expansion diffusion; crop and animal domestication spread via trade routes and human migration.',
             'Diffusion does not mean crops spread exactly as practiced—they were often adapted to local environments.',
             'MCQ may test knowledge of specific hearths or ask you to trace diffusion pathways on a map.'),
          _t('Second Agricultural Revolution',
             'The Second Agricultural Revolution (17th–19th centuries) coincided with the Industrial Revolution, introducing crop rotation, selective breeding, and mechanization that increased yields and freed labor for industry.',
             'The Second Agricultural Revolution was primarily European and preceded the Green Revolution—they are distinct events.',
             'FRQ may ask you to connect the Second Agricultural Revolution to population growth or urbanization.'),
        ],
        ['First Agricultural Revolution', 'Domestication', 'Hearth', 'Second Agricultural Revolution', 'Crop rotation'],
        ['Identify primary agricultural hearths and the crops/animals associated with each.',
         'Trace the diffusion of key agricultural practices from hearths.',
         'Explain how the Second Agricultural Revolution enabled industrialization.'],
        ['MCQ tests hearth locations and domestication knowledge.',
         'FRQ uses maps to ask about diffusion pathways.',
         'Short-answer connects agricultural revolutions to demographic changes.'],
        ['Map the 5 major agricultural hearths and list one crop domesticated in each.',
         'Explain how crop rotation improved yields without chemical fertilizers.'],
        [
          ('The domestication of wheat and barley is most closely associated with the agricultural hearth of',
           ['Mesoamerica', 'The Fertile Crescent', 'The Huang He Valley', 'Sub-Saharan Africa']),
          ('The First Agricultural Revolution is significant primarily because it',
           ['Introduced chemical fertilizers to farming', 'Enabled the transition from nomadic foraging to settled farming', 'Created industrial food processing systems', 'Began the large-scale exportation of crops']),
          ('Crop rotation, selective breeding, and early mechanization are hallmarks of the',
           ['First Agricultural Revolution', 'Green Revolution', 'Second Agricultural Revolution', 'Third Agricultural Revolution']),
          ('Agricultural practices spreading gradually from a hearth outward to neighboring regions best illustrates',
           ['Relocation diffusion', 'Hierarchical diffusion', 'Expansion diffusion', 'Stimulus diffusion']),
          ('The Second Agricultural Revolution most directly contributed to',
           ['Global warming from deforestation', 'Urbanization by freeing rural laborers for factory work', 'The development of genetically modified organisms', 'The decline of European empires']),
        ],
        ['https://www.youtube.com/watch?v=SUKIVu133s4'],
        ['Name two agricultural hearths and one crop domesticated in each.',
         'How did the Second Agricultural Revolution differ from the First?',
         'Why did agriculture develop independently in multiple world regions?']),

      _l('Modern Agricultural Practices and the Green Revolution',
        [
          _t('Green Revolution',
             'The Green Revolution (mid-20th century) introduced high-yield seed varieties, chemical fertilizers, pesticides, and irrigation to developing nations, dramatically increasing food production especially in Asia and Latin America.',
             'The Green Revolution solved hunger in some regions but increased inequality—wealthier farmers could afford inputs, marginalizing subsistence farmers.',
             'FRQ often asks you to evaluate both benefits and criticisms of the Green Revolution with specific geographic evidence.'),
          _t('Industrial vs. Subsistence Agriculture',
             'Industrial (commercial) agriculture is market-oriented, capital-intensive, and uses large machinery; subsistence agriculture produces food primarily for the farming household with little surplus.',
             'Subsistence farming is not primitive—it involves complex knowledge systems adapted to local environments.',
             'MCQ presents agricultural descriptions and asks you to classify them as intensive, extensive, subsistence, or commercial.'),
          _t('Third Agricultural Revolution and GMOs',
             'The Third Agricultural Revolution uses biotechnology, including genetically modified organisms (GMOs), precision agriculture, and genetic engineering to boost yields and create pest resistance.',
             'GMOs are controversial globally but are not inherently unsafe according to scientific consensus—student answers should reflect geographic debate, not personal opinion.',
             'FRQ may ask you to evaluate environmental and economic impacts of biotechnology in agriculture.'),
        ],
        ['Green Revolution', 'High-yield variety', 'Subsistence agriculture', 'Commercial agriculture', 'GMO'],
        ['Evaluate geographic impacts of the Green Revolution on food security.',
         'Distinguish between subsistence and commercial agriculture using examples.',
         'Analyze environmental and social consequences of the Third Agricultural Revolution.'],
        ['FRQ evaluates Green Revolution using benefit/criticism framework.',
         'MCQ classifies agricultural types from scenario descriptions.',
         'Data-based questions interpret yield statistics or maps.'],
        ['Compare crop yields before and after Green Revolution in one country.',
         'Research one GMO crop and evaluate its geographic adoption pattern.'],
        [
          ('The Green Revolution primarily helped increase food production by introducing',
           ['Traditional farming techniques to new regions', 'High-yield seed varieties and chemical inputs', 'Organic farming standards globally', 'Community-supported agriculture networks']),
          ('A major criticism of the Green Revolution is that it',
           ['Reduced total crop diversity worldwide', 'Increased inequality by favoring wealthier farmers who could buy inputs', 'Was only applied in European countries', 'Eliminated the need for irrigation']),
          ('Farming that uses large machinery, relies on chemicals, and produces surplus for sale in markets is called',
           ['Subsistence farming', 'Commercial/industrial agriculture', 'Intensive subsistence agriculture', 'Shifting cultivation']),
          ('Biotechnology, precision agriculture, and genetically modified crops characterize which revolution?',
           ['First Agricultural Revolution', 'Second Agricultural Revolution', 'Green Revolution', 'Third Agricultural Revolution']),
          ('Which agricultural practice involves temporarily clearing land, farming it until depleted, then moving to a new plot?',
           ['Crop rotation', 'Shifting cultivation', 'Double cropping', 'Monoculture']),
        ],
        ['https://www.youtube.com/watch?v=SUKIVu133s4'],
        ['What were two benefits and two criticisms of the Green Revolution?',
         'How does commercial agriculture differ from subsistence in terms of inputs and outputs?',
         'What role do GMOs play in the Third Agricultural Revolution?']),

      _l('Agricultural Land Use: Von Thünen and Rural Settlement',
        [
          _t('Von Thünen\'s Model',
             'Von Thünen\'s model explains agricultural land use patterns around a city based on transportation costs: perishable goods are produced closest to the market, and extensive farming occurs furthest away.',
             'Von Thünen\'s model assumes a flat plain with uniform soil and one market city—real landscapes rarely match these assumptions.',
             'MCQ frequently shows a diagram of concentric rings and asks you to identify what is produced in each zone.'),
          _t('Rural Settlement Patterns',
             'Rural settlements are arranged in clustered (nucleated), dispersed, or linear patterns based on physical geography, culture, history, and agricultural system.',
             'Dispersed settlements are common in the U.S. due to the township-and-range survey system, not just personal preference.',
             'FRQ may ask you to identify settlement patterns from a map and explain their geographic causes.'),
          _t('Survey Systems and Land Division',
           'The metes-and-bounds system uses natural features; the township-and-range system uses a grid; the long-lot system creates narrow parcels perpendicular to rivers.',
           'The township-and-range system created the checkerboard pattern visible in the American Midwest—students often confuse grid patterns with other survey types.',
           'MCQ may show aerial photographs of land division patterns and ask you to identify the survey system.'),
        ],
        ['Von Thünen model', 'Nucleated settlement', 'Dispersed settlement', 'Long-lot survey', 'Township-and-range'],
        ['Apply Von Thünen\'s model to explain concentric agricultural zones.',
         'Classify rural settlement types using maps and examples.',
         'Distinguish survey systems and their geographic contexts.'],
        ['Diagram interpretation of Von Thünen rings tested in MCQ.',
         'Aerial photo analysis of settlement patterns in FRQ.',
         'Survey system identification from map descriptions.'],
        ['Draw Von Thünen rings and label what agricultural activity belongs in each.',
         'Compare long-lot settlements in Louisiana to township-and-range in Iowa.'],
        [
          ('According to Von Thünen\'s model, dairy farming occurs close to the central market because',
           ['Dairy cows require urban proximity', 'Milk is perishable and transportation costs are high', 'Dairy is the most profitable land use', 'Government policy mandates dairy near cities']),
          ('A rural settlement pattern in which homes and farms are scattered across the landscape rather than clustered together is called',
           ['Nucleated', 'Linear', 'Long-lot', 'Dispersed']),
          ('The township-and-range land survey system created the characteristic _______ landscape of the American Midwest.',
           ['Long-lot river pattern', 'Grid checkerboard pattern', 'Metes-and-bounds irregular pattern', 'Nucleated village pattern']),
          ('In Von Thünen\'s model, which agricultural activity would be found in the outermost ring?',
           ['Market gardening', 'Dairy farming', 'Extensive grain farming or ranching', 'Forest products']),
          ('The long-lot survey system, found in Louisiana and Quebec, creates settlement patterns characterized by',
           ['Square parcels on a grid', 'Narrow strips of land perpendicular to a river or road', 'Irregular shapes following natural features', 'Circular parcels around a central point']),
        ],
        ['https://www.youtube.com/watch?v=SUKIVu133s4'],
        ['Describe the agricultural activity Von Thünen places in each of his four zones.',
         'What physical or historical factor most often explains nucleated vs. dispersed settlement patterns?',
         'How does the long-lot survey system reflect French colonial land use practices?']),

      _l('Food Security, Sustainability, and Agricultural Challenges',
        [
          _t('Food Security and Hunger',
             'Food security exists when all people have consistent access to sufficient, safe, and nutritious food; food insecurity is often linked to poverty, conflict, drought, and market failures rather than absolute food scarcity.',
             'Food insecurity is not simply about producing enough food globally—it is primarily a problem of distribution, access, and affordability.',
             'FRQ asks you to explain causes of food insecurity using geographic evidence from specific regions.'),
          _t('Sustainable Agriculture',
             'Sustainable agriculture practices (organic farming, agroforestry, crop diversification, conservation tillage) aim to maintain productivity while reducing environmental degradation.',
             'Sustainable agriculture is not always synonymous with low-yield or pre-industrial techniques—modern precision agriculture can be highly sustainable.',
             'MCQ and FRQ test your ability to evaluate trade-offs between productivity and sustainability.'),
          _t('Environmental Impacts of Agriculture',
             'Agriculture contributes to deforestation, soil erosion, water pollution from runoff, aquifer depletion, and biodiversity loss; monocultures are especially vulnerable to disease and climate disruption.',
             'Agricultural pollution is often diffuse (nonpoint source), making it harder to regulate than point-source industrial pollution.',
             'FRQ may ask you to connect specific farming practices to environmental consequences using geographic examples.'),
        ],
        ['Food security', 'Monoculture', 'Sustainable agriculture', 'Aquifer depletion', 'Agroforestry'],
        ['Explain geographic causes of food insecurity beyond simple food scarcity.',
         'Evaluate environmental trade-offs of industrial vs. sustainable farming.',
         'Analyze how monoculture systems increase agricultural vulnerability.'],
        ['FRQ uses case studies (Sahel, South Asia) to test food security explanation.',
         'MCQ evaluates sustainable practices from descriptions.',
         'Data interpretation questions use graphs of yield vs. environmental cost.'],
        ['Research one region experiencing food insecurity and identify its top three geographic causes.',
         'Compare monoculture corn production in Iowa with polyculture in smallholder African farms.'],
        [
          ('Food insecurity is primarily caused by',
           ['A global shortage of total food production', 'Unequal distribution, poverty, and limited access to food', 'Overpopulation in all regions equally', 'Lack of agricultural technology globally']),
          ('Which farming practice is most associated with soil erosion and long-term land degradation?',
           ['Agroforestry', 'Crop rotation', 'Monoculture', 'Terracing']),
          ('Sustainable agriculture differs from conventional industrial farming primarily in its emphasis on',
           ['Maximum short-term yield at any environmental cost', 'Maintaining long-term productivity while minimizing environmental harm', 'Exclusive use of GMO crops for efficiency', 'Elimination of all synthetic fertilizers globally']),
          ('The Ogallala Aquifer in the Great Plains is threatened by',
           ['Chemical runoff from urban areas', 'Overextraction for irrigation exceeding natural recharge rates', 'Rising sea levels from climate change', 'Deforestation reducing groundwater recharge']),
          ('Which of the following best illustrates a food desert?',
           ['A region with poor soil quality and low agricultural yields', 'An urban area where residents lack access to affordable fresh food', 'A country experiencing a famine from crop failure', 'A rural area practicing subsistence agriculture']),
        ],
        ['https://www.youtube.com/watch?v=SUKIVu133s4'],
        ['Identify two geographic causes of food insecurity that are not related to food production totals.',
         'What makes monoculture farming environmentally risky?',
         'How does agroforestry contribute to both food production and environmental sustainability?']),
    ],
    'unit_qs': [
      ('The First Agricultural Revolution was significant because it',
       ['Introduced chemical fertilizers to increase crop yields', 'Led to the transition from nomadic foraging to permanent settlements', 'Created global food trade networks', 'Eliminated famines in most world regions']),
      ('Von Thünen\'s model predicts that perishable goods like dairy will be produced nearest to the market because',
       ['Dairy cows prefer urban environments', 'Transportation costs are highest for perishables', 'Government regulations require it', 'Dairy is the least profitable land use']),
      ('A major criticism of the Green Revolution is that it',
       ['Failed to increase food production', 'Increased inequality between wealthy and poor farmers', 'Was rejected by all developing nations', 'Eliminated traditional crop varieties globally']),
      ('Which survey system creates the narrow, elongated land parcels characteristic of Louisiana\'s river parishes?',
       ['Township-and-range', 'Metes-and-bounds', 'Long-lot system', 'Grid overlay system']),
      ('Food insecurity is best described as',
       ['A global shortage of calories produced each year', 'Unequal access to sufficient, safe, and nutritious food', 'A problem affecting only developing nations', 'A result of overpopulation alone']),
      ('Which of the following agricultural practices most directly contributes to aquifer depletion?',
       ['Crop rotation', 'Large-scale irrigation from underground water sources', 'Organic composting techniques', 'Agroforestry systems']),
      ('The Third Agricultural Revolution is most distinguished by the use of',
       ['Animal-drawn plows and simple irrigation', 'High-yield seed varieties and chemical fertilizers', 'Biotechnology and genetically modified organisms', 'Crop rotation and selective breeding']),
      ('Dispersed rural settlement patterns in the American Midwest are largely explained by',
       ['Cultural preference for isolation', 'The township-and-range land survey system', 'Long-lot French colonial land division', 'Physical barriers preventing nucleated settlement']),
      ('Which agricultural hearth is most associated with the domestication of maize (corn)?',
       ['The Fertile Crescent', 'The Indus Valley', 'Mesoamerica', 'Sub-Saharan Africa']),
      ('Monoculture farming systems are particularly vulnerable to',
       ['Overproduction of diverse food types', 'Crop disease and environmental disruption due to lack of diversity', 'Excessive water retention in soils', 'High labor costs compared to diversified farms']),
    ],
  },

  {
    'num': 6,
    'title': 'Unit 6: Cities and Urban Land-Use Patterns and Processes',
    'file': 'ap-human-geography-6-unit-6-cities-and-urban-land-use-patterns-and-processes.html',
    'desc': 'Analyzes urban origins, city structure models, suburbanization, urban challenges, and revitalization strategies in the context of global urbanization trends.',
    'gateway': [
        'Why did cities first emerge where they did?',
        'How do internal city structures reflect economic and social forces?',
        'What forces drive suburbanization and urban sprawl?',
        'How do cities address inequality, environmental challenges, and decay?',
    ],
    'lessons': [
      _l('Urban Origins and World Cities',
        [
          _t('Origins of Urbanization',
             'Cities first emerged in river valley civilizations (Mesopotamia, Nile, Indus, Huang He) due to agricultural surplus, trade, and administrative needs; urbanization accelerated with industrialization.',
             'Early cities were not primarily centers of manufacturing—they were administrative, religious, and trade centers.',
             'FRQ may ask you to explain conditions that gave rise to early cities using specific hearths as evidence.'),
          _t('World Cities and Global Urban Hierarchy',
             'World cities (global cities) like New York, London, and Tokyo serve as command-and-control centers of the global economy, concentrating finance, media, and corporate headquarters.',
             'A world city is defined by its global economic function, not simply its population size—Shanghai is large but debates persist about its world city status.',
             'MCQ may ask you to identify characteristics of world cities or rank cities in a global hierarchy.'),
          _t('Primate Cities and Urban Primacy',
             'A primate city is at least twice the size of the next largest city in a country and dominates the national economy, culture, and politics (e.g., Bangkok in Thailand, Paris in France).',
             'Not all large capital cities are primate cities—the U.S. has no primate city because no single metro dominates as decisively as Bangkok dominates Thailand.',
             'FRQ asks you to explain consequences of urban primacy for national development.'),
        ],
        ['World city', 'Primate city', 'Urban primacy', 'Global city hierarchy', 'Urbanization'],
        ['Explain geographic conditions that supported early city formation.',
         'Describe characteristics and functions of world/global cities.',
         'Analyze consequences of urban primacy for national development.'],
        ['MCQ tests definitions and examples of world cities and primate cities.',
         'FRQ uses specific cities to ask about global economic roles.',
         'Short-answer connects primate city dominance to regional inequality.'],
        ['List 5 world cities and justify each using economic criteria.',
         'Research Bangkok as a primate city—what share of Thailand\'s GDP does it produce?'],
        [
          ('Cities that serve as command-and-control centers of the global economy, concentrating finance and multinational headquarters, are called',
           ['Primate cities', 'Edge cities', 'World/global cities', 'Megacities']),
          ('A primate city is defined primarily as',
           ['A city with a population over 10 million', 'A city that dominates the national urban hierarchy and is twice the size of the next largest city', 'The political capital of a country', 'A city with a port and international airport']),
          ('Bangkok, Thailand is frequently cited as a primate city because it',
           ['Has the highest GDP per capita in Asia', 'Dominates Thailand\'s economy, culture, and politics far beyond any other Thai city', 'Is the oldest city in Southeast Asia', 'Serves as the headquarters of ASEAN']),
          ('Early cities most commonly emerged at',
           ['Sites of early industrial factories', 'Locations with agricultural surplus, defensive position, and trade access', 'The geographic center of large landmasses', 'Coastal cliffs with natural harbors']),
          ('Which country does NOT have a primate city?',
           ['France', 'Thailand', 'The United States', 'Mexico']),
        ],
        ['https://www.youtube.com/watch?v=fzFJtpovOiE'],
        ['What three economic functions define a world city?',
         'Give one example of a primate city and explain its dominance.',
         'Why did early cities emerge at river valley locations rather than elsewhere?']),

      _l('Urban Land Use Models',
        [
          _t('Concentric Zone Model (Burgess)',
             'The Concentric Zone Model shows a city organized in rings from the CBD outward: transition zone (industry/poor housing), working-class homes, middle-class homes, and commuter zone.',
             'The model was based on Chicago in the early 20th century—it fits older industrial cities poorly and fails for newer polycentric cities.',
             'MCQ shows a concentric ring diagram and asks you to identify zones or match the model to a city type.'),
          _t('Sector Model (Hoyt) and Multiple Nuclei Model (Harris and Ullman)',
             'The Sector Model shows pie-slice shaped sectors of land use radiating from the CBD along transportation routes; the Multiple Nuclei Model recognizes multiple growth centers rather than one CBD.',
             'The Multiple Nuclei Model does not assume that all cities began from a single CBD—it acknowledges that cities can develop from several nuclei simultaneously.',
             'FRQ asks you to match a city\'s layout to the appropriate model and justify your choice with evidence.'),
          _t('Latin American, Southeast Asian, and African City Models',
             'Alternative urban models reflect different development paths: the Latin American city model shows a spine of commercial development and elite residential areas extending from the CBD; Southeast Asian cities lack a clear CBD and have colonial port zones.',
             'Western land use models do NOT apply universally—using Burgess or Hoyt to describe cities in the Global South is a common error.',
             'FRQ asks you to compare city structures across world regions using the appropriate model for each.'),
        ],
        ['Concentric Zone Model', 'Sector Model', 'Multiple Nuclei Model', 'CBD', 'Latin American city model'],
        ['Describe each urban model and identify the city type it best represents.',
         'Explain why Western models do not apply to cities in the Global South.',
         'Apply the correct model to a described city and justify the choice.'],
        ['Diagram interpretation of city models is heavily tested in MCQ.',
         'FRQ asks you to apply or critique a model using a real city.',
         'Comparative questions match models to city descriptions.'],
        ['Draw all three Western models side-by-side with labeled zones.',
         'Research São Paulo and identify which model best fits its structure.'],
        [
          ('The Concentric Zone Model was developed primarily based on observations of',
           ['Los Angeles in the 1970s', 'Chicago in the early 20th century', 'London during the Industrial Revolution', 'New York after World War II']),
          ('The Sector Model differs from the Concentric Zone Model in that it shows land use organized in',
           ['Concentric rings', 'Random clusters with no pattern', 'Pie-slice sectors radiating from the CBD along transportation routes', 'Separate nuclei with no single dominant center']),
          ('The Multiple Nuclei Model is most applicable to',
           ['Small industrial cities with a single downtown', 'Large, complex cities that have grown around multiple centers of activity', 'Medieval European cities built around a cathedral', 'Planned colonial cities with a grid layout']),
          ('In the Latin American city model, the zone of elite residences typically extends',
           ['In a ring around the outermost city edge', 'Along a commercial spine from the CBD outward', 'In the transition zone near factories', 'In suburban areas far from the CBD']),
          ('Which urban model would be LEAST applicable to describing the structure of a rapidly growing city in Sub-Saharan Africa?',
           ['A model based on local colonial port history', 'The Concentric Zone Model developed for Chicago', 'The McGee model for Southeast Asian cities', 'An informal settlement growth model']),
        ],
        ['https://www.youtube.com/watch?v=fzFJtpovOiE'],
        ['Describe one key difference between the Concentric Zone Model and the Sector Model.',
         'Why is the Multiple Nuclei Model considered more realistic for modern cities?',
         'What feature distinguishes the Latin American city model from Western models?']),

      _l('Suburbanization, Edge Cities, and Urban Sprawl',
        [
          _t('Suburbanization and White Flight',
             'Suburbanization accelerated in the U.S. after WWII due to federal highway construction, FHA mortgage subsidies, and preference for single-family homes; white flight describes the migration of white middle-class residents from cities to suburbs as minority populations grew.',
             'White flight was enabled by government policy (redlining, discriminatory FHA loans)—it was not simply individual preference.',
             'FRQ asks you to explain structural causes of suburbanization beyond personal preference.'),
          _t('Edge Cities and Boomburbs',
             'Edge cities are suburban nodes with significant office, retail, and employment (e.g., Tysons Corner, VA); boomburbs are rapidly growing suburban cities that have crossed 100,000 population while maintaining suburban character.',
             'Edge cities are not simply large malls—they function as secondary CBDs with significant employment concentration.',
             'MCQ and FRQ test definitions of edge cities and their economic functions.'),
          _t('Urban Sprawl and Smart Growth',
             'Urban sprawl is low-density, automobile-dependent development spreading outward from a city core; smart growth policies counter sprawl with mixed-use zoning, transit-oriented development, and infill construction.',
             'Smart growth is not anti-growth—it seeks to concentrate growth in existing urban areas rather than eliminating development entirely.',
             'FRQ evaluates pros and cons of sprawl and asks for smart growth solutions.'),
        ],
        ['Suburbanization', 'White flight', 'Redlining', 'Edge city', 'Smart growth'],
        ['Explain government policies that enabled suburbanization in the U.S.',
         'Distinguish edge cities from traditional suburbs.',
         'Evaluate smart growth as a response to urban sprawl.'],
        ['FRQ asks for explanation of suburbanization causes beyond preference.',
         'MCQ tests edge city definitions and examples.',
         'Policy evaluation questions assess smart growth strategies.'],
        ['Research one federal housing policy (FHA, GI Bill, Interstate Highway Act) and its spatial impact.',
         'Identify two edge cities near a major metropolitan area using a map.'],
        [
          ('The term "white flight" refers to',
           ['Migration of white residents to the Sun Belt region', 'Movement of white middle-class residents from cities to suburbs following minority in-migration', 'The emigration of skilled workers to Europe', 'Urban renewal policies displacing minority residents']),
          ('Edge cities are characterized by',
           ['Exclusively residential single-family housing', 'Significant concentrations of office space, retail, and employment at suburban locations', 'High-density mixed-use development in city centers', 'Industrial manufacturing zones on urban peripheries']),
          ('The federal government contributed to suburbanization primarily through',
           ['Urban renewal programs in city centers', 'Highway construction and FHA mortgage subsidies favoring suburban development', 'Public housing construction in suburbs', 'Zoning laws requiring dense urban development']),
          ('Smart growth policies typically include',
           ['Low-density single-use zoning on greenfields', 'Mixed-use development, infill construction, and transit-oriented design', 'Unlimited outward expansion with no density targets', 'Elimination of all automobile infrastructure']),
          ('Urban sprawl is primarily characterized by',
           ['High density mixed-use development', 'Low-density auto-dependent development spreading outward from urban cores', 'Concentration of services in walkable neighborhoods', 'Vertical construction replacing horizontal growth']),
        ],
        ['https://www.youtube.com/watch?v=fzFJtpovOiE'],
        ['How did redlining contribute to racial residential segregation in U.S. cities?',
         'What distinguishes an edge city from a typical suburb?',
         'Name one smart growth strategy and explain how it reduces sprawl.'],),

      _l('Urban Challenges: Inequality, Gentrification, and Sustainability',
        [
          _t('Gentrification',
             'Gentrification occurs when higher-income residents move into low-income urban neighborhoods, renovating housing and attracting businesses, but displacing existing lower-income residents.',
             'Gentrification is not simply neighborhood improvement—displacement of long-term residents is a defining and contested consequence.',
             'FRQ asks you to evaluate both benefits (investment, reduced crime) and harms (displacement) of gentrification.'),
          _t('Segregation and Inequality',
             'Residential segregation by race and income persists in U.S. cities through discriminatory housing policies (redlining), exclusionary zoning, and income inequality; hyper-segregation concentrates poverty and limits social mobility.',
             'Segregation is not just historical—contemporary zoning and lending practices continue to reinforce spatial inequality.',
             'FRQ may ask you to explain the geographic consequences of residential segregation on access to schools, jobs, and services.'),
          _t('Sustainable Urban Development',
             'Sustainable cities reduce carbon emissions through transit investment, green building, urban green space, compact development, and renewable energy; the UN Sustainable Development Goals include targets for inclusive, safe, and resilient cities.',
             'Sustainable urban development is not exclusively about environment—social equity (affordable housing, access to services) is equally central.',
             'FRQ asks you to evaluate urban sustainability initiatives and their effectiveness in reducing inequality and environmental impact.'),
        ],
        ['Gentrification', 'Displacement', 'Redlining', 'Exclusionary zoning', 'Sustainable city'],
        ['Explain geographic causes and consequences of gentrification.',
         'Analyze how past policies created persistent residential segregation.',
         'Evaluate strategies cities use to achieve environmental and social sustainability.'],
        ['FRQ evaluates gentrification with benefit/harm framework.',
         'MCQ tests definitions of redlining and exclusionary zoning.',
         'Policy questions assess sustainable urban development strategies.'],
        ['Research one gentrifying neighborhood and document evidence of change.',
         'Identify one city recognized for sustainability and list three specific policies it uses.'],
        [
          ('Gentrification primarily harms existing neighborhood residents by',
           ['Reducing property values for homeowners', 'Displacing lower-income residents who can no longer afford rising rents', 'Increasing crime rates in transitioning areas', 'Reducing access to highways and transportation']),
          ('Redlining refers to the discriminatory practice of',
           ['Drawing gerrymandered electoral districts', 'Denying mortgage loans or insurance to residents in minority neighborhoods', 'Restricting zoning to single-family housing only', 'Building highways through minority neighborhoods']),
          ('Exclusionary zoning contributes to residential segregation primarily by',
           ['Banning construction in all areas', 'Requiring large minimum lot sizes that price out lower-income residents', 'Concentrating industry in residential areas', 'Mandating racial segregation in housing law']),
          ('A sustainable city strategy that places high-density mixed-use development near transit stations is called',
           ['Urban sprawl management', 'Transit-oriented development', 'Exclusionary zoning', 'Greenfield development']),
          ('The displacement of lower-income residents due to rising property values in a neighborhood is a defining consequence of',
           ['Suburbanization', 'White flight', 'Gentrification', 'Blockbusting']),
        ],
        ['https://www.youtube.com/watch?v=fzFJtpovOiE'],
        ['What is gentrification and what geographic process drives it?',
         'How does exclusionary zoning perpetuate income segregation in suburbs?',
         'Name one characteristic of a sustainable city and explain its environmental benefit.']),
    ],
    'unit_qs': [
      ('The Concentric Zone Model was developed to describe',
       ['Los Angeles in the 1960s', 'Chicago in the early 20th century', 'London during industrialization', 'São Paulo in the 1980s']),
      ('A city that dominates its national economy and is at least twice the size of the second-largest city is called a',
       ['World city', 'Primate city', 'Edge city', 'Megacity']),
      ('Gentrification in a neighborhood most directly results in',
       ['Increased affordable housing for all residents', 'Displacement of lower-income residents due to rising costs', 'Decline in property values for homeowners', 'Reduction in commercial investment']),
      ('Edge cities are distinguished from traditional suburbs primarily because they',
       ['Have exclusively residential land use', 'Contain significant employment and commercial activity', 'Were built before the 20th century', 'Are located within the CBD']),
      ('The federal policy of redlining contributed to urban residential segregation by',
       ['Mandating separate schools for minority students', 'Denying mortgage loans to residents in minority neighborhoods', 'Building highways only in white suburban communities', 'Requiring separate water and sanitation systems']),
      ('Smart growth policies are designed primarily to',
       ['Encourage low-density suburban expansion', 'Concentrate development and reduce automobile dependence', 'Eliminate all new construction permits', 'Move industries to rural areas']),
      ('Which urban model best explains a city with multiple business and employment centers rather than a single CBD?',
       ['Concentric Zone Model', 'Sector Model', 'Multiple Nuclei Model', 'Latin American City Model']),
      ('World cities are defined primarily by their',
       ['Total population size', 'Role as command-and-control centers of the global economy', 'Status as national capitals', 'Geographic location on major rivers']),
      ('Urban sprawl most directly contributes to',
       ['Higher density housing options', 'Increased automobile dependence and loss of agricultural land', 'Stronger public transit ridership', 'Lower carbon emissions per household']),
      ('The Latin American city model differs from Western models in that it typically shows',
       ['Exclusively industrial zones surrounding the CBD', 'A spine of elite commercial development extending from the CBD', 'No central business district', 'Uniform concentric rings of decreasing wealth']),
    ],
  },

  {
    'num': 7,
    'title': 'Unit 7: Industrial and Economic Development Patterns and Processes',
    'file': 'ap-human-geography-7-unit-7-industrial-and-economic-development-patterns-and-processes.html',
    'desc': 'Examines global patterns of industrial location, development models, economic indicators, and strategies for reducing inequality between more and less developed countries.',
    'gateway': [
        'How do geographers measure and compare economic development?',
        'What factors influence where industries locate?',
        'Why do development gaps persist between world regions?',
        'How have globalization and women\'s empowerment affected development?',
    ],
    'lessons': [
      _l('Measuring Development: Indicators and Indices',
        [
          _t('GDP, GNI, and HDI',
             'GDP (Gross Domestic Product) measures total economic output within a country; GNI (Gross National Income) includes income earned abroad; HDI (Human Development Index) combines income, education, and health to give a broader measure of well-being.',
             'GDP growth does not automatically improve quality of life—it measures output, not distribution or human welfare.',
             'MCQ asks you to identify the correct indicator for a given scenario; FRQ asks you to explain why HDI is a more complete measure than GDP alone.'),
          _t('More Developed vs. Less Developed Countries',
             'MDCs (More Developed Countries) have higher incomes, longer life expectancy, and more advanced economies; LDCs (Less Developed Countries) have lower incomes, higher birth rates, and greater reliance on primary sector activities.',
             'MDC/LDC is not a permanent category—countries move between them over time as illustrated by South Korea and Singapore.',
             'FRQ asks you to compare MDC and LDC characteristics using specific demographic and economic data.'),
          _t('Limitations of Development Indicators',
             'Traditional indicators like GDP per capita hide internal inequality (measured by the Gini coefficient), ignore informal economies, undercount unpaid labor (especially women\'s work), and miss environmental sustainability.',
             'High GDP per capita in oil-rich states (Qatar, Kuwait) does not reflect broad-based development if wealth is concentrated and social indicators lag.',
             'MCQ may present a country profile and ask you to identify why standard indicators misrepresent its actual development level.'),
        ],
        ['GDP', 'GNI', 'HDI', 'Gini coefficient', 'Informal economy'],
        ['Distinguish between GDP, GNI, and HDI as development measures.',
         'Compare MDC and LDC characteristics using demographic and economic data.',
         'Evaluate limitations of standard development indicators.'],
        ['MCQ tests which indicator fits a given scenario.',
         'FRQ asks for explanation of why HDI is more complete than GDP.',
         'Data interpretation questions use tables of development indicators.'],
        ['Compare HDI rankings to GDP per capita rankings for 5 countries.',
         'Research one country where GDP per capita is high but HDI components diverge.'],
        [
          ('The Human Development Index (HDI) is considered more comprehensive than GDP per capita because it',
           ['Measures only economic output', 'Combines income with education and health indicators', 'Focuses exclusively on agricultural productivity', 'Tracks only industrial manufacturing output']),
          ('Which measure best captures the internal inequality of income distribution within a country?',
           ['GDP per capita', 'HDI ranking', 'Gini coefficient', 'GNI per capita']),
          ('Countries classified as LDCs typically exhibit',
           ['Low birth rates and aging populations', 'High reliance on primary sector activities and lower life expectancy', 'Dominant service and technology sectors', 'High rates of net emigration of unskilled workers']),
          ('GDP per capita overstates development in oil-rich states because it',
           ['Counts only manufacturing output', 'Hides unequal wealth distribution where income is concentrated among few', 'Excludes natural resource exports from calculations', 'Measures purchasing power parity incorrectly']),
          ('The informal economy refers to',
           ['Government-regulated financial markets', 'Economic activity not officially recorded or taxed, often including subsistence work', 'International trade in agricultural commodities', 'Black market criminal enterprises only']),
        ],
        ['https://www.youtube.com/watch?v=dO6mREMniUo'],
        ['Why does HDI measure development more completely than GDP alone?',
         'What is the Gini coefficient and what does a high value indicate?',
         'Name two characteristics that distinguish an MDC from an LDC.']),

      _l('Industrial Location Theory and Deindustrialization',
        [
          _t('Weber\'s Least-Cost Theory',
             'Alfred Weber\'s Least-Cost Theory holds that industries locate where the combined costs of transportation, labor, and agglomeration are minimized; industries that lose weight in production (bulk-reducing) locate near raw materials.',
             'Weber\'s model is theoretical—it assumes perfect information and ignores political and cultural factors that influence real industrial location.',
             'MCQ frequently shows a triangle diagram and asks you to identify the least-cost location; FRQ asks you to apply the theory to a specific industry.'),
          _t('Agglomeration and Deglomeration',
             'Agglomeration economies occur when businesses cluster together to share infrastructure, labor pools, and supplier networks (e.g., Silicon Valley, Detroit auto industry); deglomeration occurs when costs of clustering outweigh benefits and firms disperse.',
             'Agglomeration does not always benefit all firms equally—larger established firms often gain more than small startups.',
             'FRQ asks you to explain why tech companies cluster in Silicon Valley using agglomeration economy reasoning.'),
          _t('Deindustrialization and the Rust Belt',
             'Deindustrialization is the decline of manufacturing employment as industries move to lower-cost regions or are automated; the U.S. Rust Belt (Great Lakes region) lost millions of manufacturing jobs as firms relocated to the Sun Belt or Global South.',
             'Deindustrialization does not mean the end of economic activity—it is often accompanied by growth in the service and knowledge sectors.',
             'FRQ asks you to explain geographic consequences of deindustrialization for affected communities.'),
        ],
        ['Weber\'s Least-Cost Theory', 'Agglomeration', 'Deglomeration', 'Deindustrialization', 'Rust Belt'],
        ['Apply Weber\'s Least-Cost Theory to predict industrial location.',
         'Explain agglomeration economies using a real industry cluster.',
         'Analyze geographic consequences of deindustrialization.'],
        ['Diagram interpretation of Weber\'s triangle is heavily tested.',
         'FRQ asks you to justify industrial clustering using agglomeration.',
         'Rust Belt case study used for deindustrialization explanation.'],
        ['Apply Weber\'s theory to locate a hypothetical steel plant given raw material and market locations.',
         'List 3 agglomeration benefits that explain why tech firms cluster in Silicon Valley.'],
        [
          ('According to Weber\'s Least-Cost Theory, a bulk-reducing industry (one that loses weight in production) should locate',
           ['Near the market for finished goods', 'Near the raw material source', 'Equidistant between raw materials and market', 'Wherever labor costs are lowest']),
          ('Agglomeration economies refer to the benefits firms gain from',
           ['Locating in isolated rural areas to reduce competition', 'Clustering with similar firms to share infrastructure, labor, and suppliers', 'Moving manufacturing to low-wage countries', 'Investing in automation to reduce labor costs']),
          ('The U.S. Rust Belt is characterized by',
           ['Rapid growth of high-tech industries', 'Decline of manufacturing and population loss in former industrial cities', 'Strong agricultural base and rural population', 'Major Pacific Coast port cities']),
          ('Deglomeration occurs when',
           ['Costs of industrial clustering outweigh benefits, causing firms to disperse', 'Government mandates force firms to relocate', 'Environmental regulations prevent industrial clustering', 'Multiple firms merge into a single monopoly']),
          ('Silicon Valley\'s concentration of tech firms is best explained by',
           ['Government mandate to build a tech hub there', 'Agglomeration economies including shared labor pools and supplier networks', 'Abundant natural resources for electronics manufacturing', 'Low land costs encouraging large campuses']),
        ],
        ['https://www.youtube.com/watch?v=dO6mREMniUo'],
        ['What three costs does Weber\'s Least-Cost Theory seek to minimize?',
         'Explain one benefit of agglomeration for a small tech startup in Silicon Valley.',
         'What happened to Rust Belt cities when manufacturing deindustrialized, and why?']),

      _l('Development Theories and Global Economic Patterns',
        [
          _t('Rostow\'s Stages of Growth',
             'Rostow\'s model proposes five stages of economic development: traditional society, preconditions for takeoff, takeoff, drive to maturity, and high mass consumption; all countries presumably follow this linear path.',
             'Rostow\'s model is criticized as Eurocentric—it assumes all countries will and should follow the Western industrialization path.',
             'FRQ asks you to apply or critique Rostow\'s stages using a specific country\'s development trajectory.'),
          _t('Dependency Theory and World-Systems Theory',
             'Dependency theory argues that LDCs remain underdeveloped because core countries (MDCs) extract resources and cheap labor, perpetuating inequality; World-Systems Theory classifies countries as core, semi-periphery, and periphery based on their role in the global economy.',
             'World-Systems Theory is not pessimistic about all LDCs—semi-peripheral countries like Brazil and China have moved between categories over time.',
             'MCQ asks you to classify a country in Wallerstein\'s world-system; FRQ asks you to compare Rostow and Dependency Theory.'),
          _t('Neoliberalism, Structural Adjustment, and Fair Trade',
             'Neoliberal development promotes free markets, privatization, and reduced government spending; structural adjustment programs (SAPs) imposed by the World Bank/IMF required these reforms as conditions for loans, often harming social services in LDCs; fair trade certification tries to ensure farmers receive fair prices.',
             'SAPs are controversial—proponents cite economic efficiency gains, critics point to cuts in health and education spending that harmed vulnerable populations.',
             'FRQ asks you to evaluate trade-offs of neoliberal development policies using geographic evidence.'),
        ],
        ['Rostow\'s model', 'Dependency theory', 'World-systems theory', 'Core', 'Periphery', 'Structural adjustment'],
        ['Apply and critique Rostow\'s stages of economic development.',
         'Compare dependency theory and world-systems theory explanations for global inequality.',
         'Evaluate trade-offs of neoliberal structural adjustment programs.'],
        ['FRQ compares development theories using specific country evidence.',
         'MCQ classifies countries in world-systems framework.',
         'Short-answer evaluates SAPs using geographic data.'],
        ['Classify 5 countries as core, semi-periphery, or periphery and justify each.',
         'Research one country that underwent IMF structural adjustment and evaluate outcomes.'],
        [
          ('Rostow\'s Stages of Economic Development model is criticized primarily for being',
           ['Too focused on agriculture', 'Eurocentric in assuming all countries will follow the Western industrialization path', 'Based on communist economic theory', 'Applicable only to island nations']),
          ('According to dependency theory, LDCs remain underdeveloped primarily because',
           ['They lack natural resources', 'Core countries extract resources and cheap labor, perpetuating inequality', 'Their populations are too small to generate sufficient internal demand', 'Their governments refuse foreign investment']),
          ('In Wallerstein\'s world-systems theory, "semi-peripheral" countries are characterized by',
           ['Exclusive control of global finance and manufacturing', 'Providing only raw materials to core countries', 'A mix of core and peripheral economic activities, often industrializing', 'Complete economic isolation from the global system']),
          ('Structural adjustment programs required LDCs to',
           ['Increase social spending and nationalize industries', 'Privatize state industries and reduce government spending in exchange for loans', 'Impose high tariffs on imports to protect domestic industries', 'Invest in military infrastructure as a condition of IMF loans']),
          ('Fair trade certification attempts to address global inequality by',
           ['Eliminating all tariffs between core and peripheral countries', 'Ensuring producers in LDCs receive fair prices for their goods', 'Transferring manufacturing from LDCs to core countries', 'Standardizing wages globally through international law']),
        ],
        ['https://www.youtube.com/watch?v=dO6mREMniUo'],
        ['Name Rostow\'s five stages and identify one country at each stage.',
         'How does dependency theory differ from Rostow\'s model in explaining LDC poverty?',
         'What is fair trade and how does it challenge conventional global trade patterns?']),

      _l('Gender, Inequality, and Sustainable Development',
        [
          _t('Gender and Development',
             'Gender inequality limits economic development because restricting women\'s education, employment, and property rights reduces a country\'s productive capacity and perpetuates intergenerational poverty.',
             'Gender equality is not just a social goal—it is an economic development strategy with measurable impacts on GDP and poverty reduction.',
             'FRQ asks you to explain how improving women\'s education and employment affects national development using specific evidence.'),
          _t('Microfinance and Empowerment',
             'Microfinance provides small loans to entrepreneurs (often women) in LDCs who lack access to traditional banking, enabling small business creation and economic independence; the Grameen Bank in Bangladesh is the most cited example.',
             'Microfinance alone does not solve poverty—critics note high interest rates and that structural inequalities require broader policy changes beyond individual loans.',
             'MCQ and FRQ test knowledge of microfinance as a development strategy and its geographic reach.'),
          _t('Sustainable Development Goals (SDGs)',
             'The UN\'s 17 SDGs (adopted 2015) set targets for eliminating poverty, reducing inequality, achieving gender equality, protecting the environment, and building sustainable cities by 2030.',
             'The SDGs are aspirational targets, not legally binding treaties—progress varies widely by country and goal.',
             'FRQ may ask you to evaluate progress toward specific SDGs and identify geographic barriers to achieving them.'),
        ],
        ['Gender inequality', 'Microfinance', 'Grameen Bank', 'SDGs', 'Women\'s empowerment'],
        ['Explain how gender equality contributes to economic development.',
         'Evaluate microfinance as a development tool with specific examples.',
         'Apply the SDG framework to assess development progress in a specific region.'],
        ['FRQ connects gender equality to development outcomes with data.',
         'MCQ tests microfinance definitions and geographic examples.',
         'Short-answer uses SDG targets to evaluate a country\'s development strategy.'],
        ['Research Grameen Bank: how many borrowers does it serve and what is its repayment rate?',
         'Identify which 3 SDGs are most interconnected and explain their linkages.'],
        [
          ('Improving women\'s education in LDCs is considered an effective development strategy because it',
           ['Increases agricultural output by improving traditional farming', 'Reduces birth rates, improves child health, and expands the labor force', 'Encourages emigration of skilled workers to MDCs', 'Primarily benefits urban rather than rural populations']),
          ('The Grameen Bank is most associated with which development strategy?',
           ['Structural adjustment programs', 'Microfinance loans to low-income entrepreneurs', 'Foreign direct investment from core countries', 'Nationalization of banking industries']),
          ('A major criticism of microfinance as a development tool is that',
           ['It is limited to urban areas only', 'High interest rates and structural inequality cannot be solved by small loans alone', 'It exclusively benefits large corporations', 'It was invented by the World Bank as a control mechanism']),
          ('The UN Sustainable Development Goals are best described as',
           ['Legally binding treaties requiring immediate compliance', 'Aspirational targets covering poverty, inequality, environment, and sustainability through 2030', 'Economic performance benchmarks for MDCs only', 'Replacement for the Human Development Index']),
          ('Which of the following best illustrates the link between gender equality and economic development?',
           ['Countries with higher female labor force participation tend to have higher GDP per capita', 'Gender equality has no measurable economic impact', 'Men\'s education returns are always higher than women\'s', 'Gender equality is solely a social issue unrelated to development']),
        ],
        ['https://www.youtube.com/watch?v=dO6mREMniUo'],
        ['How does restricting women\'s access to education reduce a country\'s economic potential?',
         'What is microfinance and how does the Grameen Bank implement it?',
         'Name two Sustainable Development Goals and explain how they are interconnected.']),
    ],
    'unit_qs': [
      ('Weber\'s Least-Cost Theory predicts that bulk-reducing industries locate near',
       ['The market for finished goods', 'Raw material sources', 'The largest available labor pool', 'Major transportation hubs only']),
      ('The Human Development Index is preferred over GDP per capita as a development measure because it',
       ['Focuses exclusively on economic output', 'Combines income, education, and health into a broader picture of well-being', 'Measures only environmental sustainability', 'Tracks military spending and infrastructure investment']),
      ('World-systems theory classifies Brazil as "semi-peripheral" because it',
       ['Is exclusively dependent on raw material exports', 'Has both core-like manufacturing sectors and peripheral raw material exports', 'Controls global finance and multinational corporations', 'Has no significant industrial base']),
      ('Deindustrialization in the U.S. Rust Belt primarily resulted from',
       ['Government policy banning manufacturing in the region', 'Firms relocating to lower-cost regions or automating production', 'Environmental disasters destroying manufacturing facilities', 'Foreign trade agreements eliminating domestic industry']),
      ('Rostow\'s model is criticized for being Eurocentric because it',
       ['Excludes European countries from its analysis', 'Assumes all nations must follow the Western industrialization path to develop', 'Was written to justify colonialism explicitly', 'Applies only to tropical economies']),
      ('Agglomeration economies benefit firms primarily through',
       ['Isolated locations reducing competition', 'Shared infrastructure, labor pools, and supplier networks from clustering', 'Government subsidies for each clustered firm', 'Reduction of all environmental regulations in cluster zones']),
      ('Microfinance programs like the Grameen Bank primarily serve',
       ['Large multinational corporations seeking startup capital', 'Low-income entrepreneurs, often women, lacking access to traditional banking', 'Government infrastructure projects in LDCs', 'Core-country investors seeking high returns']),
      ('Dependency theory argues that global inequality persists because',
       ['LDCs lack sufficient natural resources', 'Core countries extract resources and cheap labor, preventing LDC development', 'LDC governments are uniformly corrupt', 'Geographic isolation limits LDC trade access']),
      ('Structural adjustment programs required by the IMF typically included',
       ['Increased social spending and nationalization of key industries', 'Privatization, reduced government spending, and market liberalization', 'Higher tariffs to protect domestic industries', 'Mandatory adoption of a single global currency']),
      ('Improving women\'s education in LDCs most directly affects development by',
       ['Increasing agricultural subsistence output only', 'Reducing birth rates, improving child health, and expanding economic participation', 'Encouraging emigration of skilled female workers', 'Primarily benefiting urban areas and ignoring rural populations']),
    ],
  },
]
