NAME = 'AP Human Geography'
ABBREV = 'aphug'
SLUG = 'ap-human-geography'
COURSE_FILE = 'ap-human-geography.html'
_H = 'https://www.youtube.com/results?search_query=heimler+history+ap+human+geography+'

def _t(ti, co, mi, ht): return {'title':ti,'content':co,'misconception':mi,'how_tested':ht}
def _l(title,topics,vocab,obj,ht,prac,qs,vids,ext):
    return {'title':title,'topics':topics,'vocab':vocab,'objectives':obj,
            'how_tested':ht,'practice':prac,'questions':qs,'videos':vids,'exit_ticket':ext}

UNITS = [
 {'num':1,'title':'Thinking Geographically',
  'file':'ap-human-geography-1-unit-1-thinking-geographically.html',
  'desc':'Geographers use spatial thinking to examine where things are, why they are there, and what consequences follow from their location.',
  'gateway':['Apply the spatial perspective to explain geographic patterns','Distinguish absolute from relative location','Compare formal, functional, and perceptual regions','Interpret maps and evaluate their distortions'],
  'lessons':[
   _l('Spatial Thinking and Geographic Perspectives',
    [_t('The Spatial Perspective','Geographers ask where things are, why they are there, and what patterns result across Earth\'s surface — this is the spatial perspective. Absolute location uses coordinates; relative location describes position relative to other places.',
        'Geography is not memorizing capitals — AP Human Geography requires explaining WHY spatial patterns exist, not just WHERE things are.',
        'MCQ presents a scenario and asks which geographic concept or perspective best explains the observed pattern.'),
     _t('Space vs. Place','Space is an objective, measurable location. Place is a location given meaning by human experience — topophilia (Yi-Fu Tuan, 1974) describes deep emotional attachment to a place. Placelessness occurs when globalization erases local distinctiveness.',
        'Students confuse space (objective coordinates) with place (subjective meaning). A street address is space; a neighborhood with cultural identity is place.',
        'FRQ may ask how globalization creates placelessness and require an example of a place that has lost its unique local character.'),
     _t('Scale of Analysis','Geographic patterns look different at local, regional, and global scales — the same phenomenon may appear at one scale but be invisible at another. A large-scale map shows a small area in great detail; a small-scale map shows a large area with less detail.',
        'Students consistently reverse large/small scale: large-scale = zoomed IN (more detail, smaller area); small-scale = zoomed OUT (less detail, larger area).',
        'MCQ may show two maps of the same area at different scales and ask how the visible spatial pattern changes.')],
    [('spatial perspective','Geographic lens asking where, why there, and what the spatial consequences are'),
     ('absolute location','Precise position using latitude and longitude coordinates'),
     ('relative location','Position described in relation to surrounding places or features'),
     ('topophilia','Deep emotional attachment to a specific place; coined by Yi-Fu Tuan'),
     ('scale of analysis','The geographic level — local to global — at which a phenomenon is studied')],
    ['Explain how the spatial perspective differs from other ways of understanding events','Distinguish absolute from relative location with examples','Describe how scale of analysis changes the patterns a geographer observes'],
    ['Identify which type of region (formal/functional/perceptual) a description represents','Apply the concept of topophilia to explain resistance to urban displacement','Explain why a geographer would choose a large-scale vs. small-scale map for a given task'],
    ['Map your school campus identifying site (physical features) and situation (relation to city)','Find a news article and identify the scale of analysis the author is using'],
    [('Explain the difference between space and place and why both are essential to geographic analysis.',
      ['Space is objective — a measurable location defined by coordinates or distance',
       'Place is subjective — a location given meaning, identity, and emotional value by human experience',
       'Geographers use space to compare and measure; place explains cultural behavior and attachment',
       'Example: a GPS coordinate is space; a neighborhood with ethnic identity like Chinatown is place']),
     ('How does scale of analysis affect what geographic patterns are visible when studying urban poverty?',
      ['Local scale reveals block-level variation — redlined neighborhoods, census tract poverty rates',
       'Regional scale shows urban-rural or Sun Belt vs. Rust Belt disparities',
       'National scale reveals structural inequalities but obscures neighborhood-level detail',
       'Choosing the wrong scale can make a real pattern invisible or suggest a false pattern']),
     ('Define and give a geographic example of each type of region.',
      ['Formal region: uniform shared characteristic — the Corn Belt (dominant crop), the Bible Belt (religious adherence)',
       'Functional region: organized around a central node — a city metropolitan area defined by commuting patterns',
       'Perceptual (vernacular) region: defined by cultural perception — "the South" has no sharp boundary, only cultural identity',
       'Formal regions have precise edges; perceptual regions have fuzzy transition zones']),
     ('How do site and situation explain why major cities developed where they did?',
      ['Site: physical characteristics of the location — flat land, fresh water, defensible terrain',
       'Situation: the location\'s relationship to surrounding areas — trade routes, river systems, other cities',
       'Cities grew at favorable sites (water access) and thrived based on situation (trade crossroads)',
       'Example: New Orleans has a poor site (below sea level) but superb situation (Mississippi River mouth and Gulf access)']),
     ('What is distance decay and how does technology affect it?',
      ['Distance decay: spatial interaction intensity decreases as distance between places increases',
       'Based on Tobler\'s First Law: near things interact more than far things',
       'Technology (internet, air travel) compresses space-time and reduces — but does not eliminate — distance decay',
       'Example: people still shop locally more than online for fresh goods, showing residual distance decay'])],
    [('Heimler\'s History: APHUG Unit 1 — Thinking Geographically','Spatial perspective, maps, regions, and geographic concepts','https://www.youtube.com/results?search_query=heimler+history+aphug+unit+1+thinking+geographically')],
    ['What distinguishes a formal from a perceptual region?','Why does scale matter when analyzing geographic issues?','Give a personal example of topophilia.']),
   _l('Maps and Spatial Data',
    [_t('Types of Maps','Reference maps show geographic features and locations (political, physical, road maps). Thematic maps display spatial distributions of a specific variable — choropleth maps use shading, dot maps use dots, and isoline maps connect points of equal value.',
        'Students confuse reference maps with thematic maps — reference maps orient you in space; thematic maps show patterns of a specific attribute.',
        'MCQ presents a map type and asks what geographic question it best answers; FRQ asks you to choose and justify an appropriate map type for a given data set.'),
     _t('Map Projections and Distortion','Every flat map distorts Earth\'s spherical surface in one or more of four properties: shape, area, distance, or direction. The Mercator projection preserves shape and direction but distorts area (Greenland appears as large as Africa). The Peters projection preserves area but distorts shape.',
        'No map is "correct" — all projections involve tradeoffs. Students often assume Mercator is the accurate default.',
        'MCQ asks which projection is appropriate for a given use case (navigation = Mercator; comparing country sizes = equal-area projection).'),
     _t('GIS and Remote Sensing','Geographic Information Systems (GIS) layer multiple data sets on a base map to reveal spatial relationships invisible in any single data layer. Remote sensing captures Earth surface data from satellites or aircraft without physical contact.',
        'GIS is not just digital cartography — it is an analytical tool for finding spatial correlations across data layers.',
        'FRQ may ask how a geographer would use GIS to analyze a spatial problem such as disease spread or urban planning.')],
    [('choropleth map','Thematic map using graduated shading to show data values across areas'),
     ('isoline map','Map connecting points of equal value — topographic contour lines are isolines'),
     ('cartogram','Map that distorts area to represent a quantitative variable like population or GDP'),
     ('GIS','Geographic Information System — software that layers and analyzes multiple spatial data sets'),
     ('remote sensing','Collecting geographic data from satellites or aircraft without physical contact')],
    ['Distinguish reference maps from thematic maps and explain when each is appropriate','Describe the four properties that map projections can distort','Explain how GIS layers data to support geographic analysis'],
    ['Identify a map type (choropleth, dot, isoline) from its description and state what it shows','Explain why a navigator would use Mercator projection and an economist would use an equal-area projection','Describe a geographic question GIS could help answer and what data layers would be needed'],
    ['Compare a physical map and a thematic map of the same region — what does each reveal?','Sketch a choropleth map of your state using a variable of your choice'],
    [('Explain why no flat map can perfectly represent Earth\'s spherical surface.',
      ['Earth is a sphere and cannot be flattened without distortion — this is the fundamental map projection problem',
       'Projections preserve some properties (shape, area, distance, direction) at the expense of others',
       'Mercator preserves shape and direction but exaggerates area at high latitudes — Greenland appears as large as Africa',
       'Choosing a projection depends on purpose: navigation uses Mercator; land area comparison uses equal-area projections']),
     ('How does a GIS help a city planner analyze where to build a new hospital?',
      ['GIS layers data sets — population density, existing hospitals, road networks, income levels — on a base map',
       'Overlaying layers reveals underserved areas where distance to care is greatest',
       'Spatial analysis identifies optimal locations minimizing average travel time for the greatest number of residents',
       'GIS also allows scenario modeling — "what if" the hospital is placed at location A vs. B']),
     ('What is the difference between a dot map and a choropleth map and when is each preferred?',
      ['Dot map: each dot represents a set quantity of a phenomenon — shows actual point distribution',
       'Choropleth map: shading intensity shows data value within pre-defined areas (counties, states)',
       'Dot maps are better for showing clustering and dispersal of individual phenomena (e.g., farms)',
       'Choropleth maps are better for showing regional averages or totals (e.g., % population below poverty line)']),
     ('Explain the geographic concept of mental maps and why they matter.',
      ['Mental (cognitive) map: an individual\'s personal internal representation of spatial knowledge',
       'Mental maps reflect personal experience, cultural background, and media exposure — not objective reality',
       'They influence spatial behavior: people navigate, migrate, and invest based on their mental maps, not actual maps',
       'Example: Americans often have detailed mental maps of their home region but vague maps of other continents']),
     ('What is the difference between quantitative and qualitative geographic data and give an example of each?',
      ['Quantitative data: numerical, measurable — population counts, temperature readings, income levels',
       'Qualitative data: descriptive, non-numerical — interviews about sense of place, field sketches, oral histories',
       'Geographers use both: satellite imagery (quantitative) paired with interviews (qualitative) for complete analysis',
       'Mixing methods is called mixed-methods research — increasingly common in human geography'])],
    [('Heimler\'s History: APHUG Maps and Projections','Map types, projections, GIS, and geographic data tools',_H+'maps+projections+GIS')],
    ['What are the four properties that projections distort?','When is a choropleth map preferable to a dot map?','How does GIS support geographic decision-making?']),
   _l('Types of Regions and Geographic Models',
    [_t('Formal, Functional, and Perceptual Regions','A formal region has a uniform defining characteristic throughout — the Corn Belt, the European Union. A functional (nodal) region is organized around a focal node — a city\'s metropolitan area defined by commuting patterns. A perceptual (vernacular) region exists in the cultural imagination — "the South" or "the Middle East."',
        'Students often classify based on the word "region" alone. Ask: Is it uniform? (formal) Does it radiate from a node? (functional) Is it a cultural perception? (perceptual)',
        'MCQ presents a regional description and asks which type it represents; knowing the defining criterion for each type is essential.'),
     _t('Site and Situation','Site refers to the physical characteristics of a location — terrain, climate, water access. Situation refers to a location\'s relative position to surrounding places — trade routes, other cities, transportation networks. Both affect urban growth and land value.',
        'Students confuse site (physical place itself) with situation (place\'s relationship to surroundings). Site = internal; situation = external connections.',
        'FRQ asks you to explain why a specific city grew using both site and situation factors.'),
     _t('Tobler\'s First Law and Spatial Autocorrelation','Tobler\'s First Law states that near things are more related than distant things — distance decay. Spatial autocorrelation means geographically close observations tend to have similar values (positive) or dissimilar values (negative).',
        'Spatial autocorrelation is not causation — it describes a pattern, not an explanation for why the pattern exists.',
        'AP exam asks you to apply Tobler\'s Law to explain why a disease cluster appears, or why migration flows decrease with distance.')],
    [('formal region','Area defined by a uniform shared characteristic throughout its extent'),
     ('functional region','Area organized around a central node or focal point — defined by flows and connections'),
     ('perceptual region','Area defined by cultural perception, identity, and imagination rather than objective data'),
     ('site','Physical characteristics of a location — terrain, water, soil, climate'),
     ('situation','A location\'s position relative to surrounding areas, routes, and other places')],
    ['Distinguish formal, functional, and perceptual regions with original examples','Explain how site and situation together explain urban growth','Apply Tobler\'s First Law to predict the intensity of spatial interaction'],
    ['Classify a described region as formal, functional, or perceptual and justify your answer','Use site and situation to explain why a given city grew large','Explain why distance decay does not always apply in the age of the internet'],
    ['Classify five regions you can name as formal, functional, or perceptual','Describe your city\'s site (physical features) and situation (connections to other places)'],
    [('A student describes the "Rocky Mountain region" as an area of high elevation and rugged terrain. What type of region is this and why?',
      ['This is a formal region — it is defined by a uniform physical characteristic (high elevation, rugged terrain)',
       'Formal regions have relatively clear boundaries determined by the defining attribute',
       'The Rocky Mountain region\'s boundary corresponds to the extent of the mountain range',
       'Contrast with a perceptual region like "the West," which has no precise physical boundary']),
     ('Explain how a television broadcast market is an example of a functional region.',
      ['A functional (nodal) region is organized around a central node — here, the TV broadcast tower or network hub',
       'The region\'s boundary is defined by signal range or market area — where the station\'s viewership flows',
       'As you move away from the node, the connection weakens — this shows distance decay',
       'Other functional region examples: a bank\'s branch service area, a city\'s commuter shed']),
     ('How does the concept of the "American South" illustrate a perceptual region?',
      ['"The South" is defined by cultural perception, not a uniform attribute or central node',
       'No two people draw the same boundary — it shifts based on dialect, cuisine, history, and identity',
       'Perceptual regions have fuzzy, transitional edges rather than sharp borders',
       'They reflect shared cultural imagination and are powerful in politics and marketing despite their subjectivity']),
     ('Explain how site and situation influenced the growth of Chicago, Illinois.',
      ['Site: Chicago sits on flat glacial plains beside Lake Michigan — excellent for building and lake access',
       'Situation: Chicago is at the junction of Great Lakes water routes and interior river systems — a natural trade hub',
       'As rail networks developed, Chicago\'s situation as a hub of converging rail lines made it the largest inland city',
       'Both site (physical suitability) and situation (strategic connectivity) were essential to Chicago\'s growth']),
     ('What does Tobler\'s First Law predict about the relationship between two neighboring cities?',
      ['Tobler\'s First Law: near things are more related than distant things (the basis of distance decay)',
       'Neighboring cities will have stronger trade flows, migration, commuting, and cultural exchange than distant cities',
       'Land prices, disease spread, and innovation diffusion all follow Tobler\'s Law — clustering near origin',
       'Technology reduces but does not eliminate this effect — even online commerce shows geographic clustering'])],
    [('Heimler\'s History: APHUG Regions and Models','Formal, functional, perceptual regions, site, situation, and spatial laws',_H+'regions+site+situation')],
    ['What is the key criterion that defines a formal region?','How is a commuter shed an example of a functional region?','Why does Tobler\'s First Law predict distance decay?']),
   _l('Geographic Tools: GIS, GPS, and Remote Sensing',
    [_t('Geographic Information Systems','GIS stores, analyzes, and visualizes geographic data as layered maps. Analysts stack layers — roads, population, land use, elevation — to reveal spatial patterns and relationships invisible in any single layer. GIS is used in urban planning, epidemiology, environmental management, and business location decisions.',
        'GIS is not just making digital maps — it is a spatial analysis tool. Students underestimate its analytical power.',
        'FRQ may present a geographic problem (e.g., locating a new clinic) and ask how GIS layers would be used to choose the best site.'),
     _t('GPS and Volunteered Geographic Information','GPS uses satellite signals to determine precise locations on Earth\'s surface. Volunteered Geographic Information (VGI) refers to spatial data contributed by the public — OpenStreetMap contributors, geotagged social media posts. VGI has democratized mapping but introduces accuracy concerns.',
        'GPS gives location; GIS analyzes location data. Students confuse the two — GPS is a tool that feeds data into GIS.',
        'MCQ may ask about the advantages and limitations of VGI compared to professionally collected geographic data.'),
     _t('Remote Sensing and Satellite Imagery','Remote sensing acquires geographic data from a distance — primarily through satellite or aerial sensors. It is used to monitor land cover change, deforestation, urban growth, and natural disasters without ground surveys. Different wavelengths (infrared, visible) reveal different surface characteristics.',
        'Remote sensing collects data; GIS analyzes data. They are complementary, not interchangeable.',
        'AP exam may ask how remote sensing could detect agricultural land use change or urban sprawl.')],
    [('GIS','Geographic Information System — software that layers, queries, and analyzes spatial data sets'),
     ('GPS','Global Positioning System — satellite-based system providing precise absolute location data'),
     ('remote sensing','Collecting Earth surface data from satellites or aircraft without physical contact'),
     ('VGI','Volunteered Geographic Information — crowd-sourced spatial data contributed by users online'),
     ('spatial analysis','Using GIS tools to find patterns, relationships, and trends in geographic data')],
    ['Explain how GIS layers work together to answer a geographic question','Distinguish GPS from GIS in terms of purpose and output','Describe one advantage and one limitation of volunteered geographic information'],
    ['Identify which technology (GPS, GIS, or remote sensing) is best suited for a described geographic task','Explain how remote sensing could detect urban heat islands','Evaluate the reliability of VGI compared to government-collected geographic data'],
    ['Design a GIS analysis for a real problem in your community — list the data layers you would need','Find an example of remote sensing imagery used in the news and explain what it shows'],
    [('Explain how GIS would help a public health official identify neighborhoods at highest risk during a disease outbreak.',
      ['GIS overlays multiple data layers: disease case locations, population density, income levels, access to healthcare',
       'Spatial clustering analysis identifies hotspots where cases concentrate above expected rates',
       'Socioeconomic layers reveal correlations between poverty, crowding, and disease incidence',
       'Output maps guide resource allocation — mobile clinics sent to highest-risk underserved areas']),
     ('What is the difference between GPS and GIS and how do they work together?',
      ['GPS: satellite-based system that determines precise absolute location (coordinates) of a point',
       'GIS: software that stores, layers, and analyzes spatial data to reveal patterns and relationships',
       'GPS collects location data that becomes input for GIS analysis — they are complementary tools',
       'Example: GPS tracks delivery trucks; GIS analyzes routing efficiency across the network']),
     ('What are the advantages and disadvantages of volunteered geographic information?',
      ['Advantage: VGI vastly increases spatial data coverage — OpenStreetMap maps areas never covered by official sources',
       'Advantage: VGI is real-time — geotagged social media captures events as they unfold',
       'Disadvantage: accuracy is uneven — contributors may have bias, make errors, or have uneven distribution',
       'Disadvantage: VGI coverage mirrors internet access — areas with low connectivity are underrepresented']),
     ('How does remote sensing help geographers monitor deforestation in the Amazon?',
      ['Satellites capture multispectral imagery — different wavelengths reveal vegetation, bare soil, and water',
       'Change detection compares images over time to identify where forest cover has been lost',
       'Near-infrared bands distinguish healthy vegetation from disturbed or cleared land',
       'This allows near-real-time monitoring of deforestation rates without sending researchers into remote terrain']),
     ('How do mental maps differ from GIS maps and what does each reveal?',
      ['Mental map: an individual\'s internal cognitive representation of space — shaped by experience and perception',
       'GIS map: objective, data-driven spatial representation of measurable phenomena',
       'Mental maps reveal biases, knowledge gaps, and emotional geography — useful for understanding behavior',
       'GIS maps reveal patterns in objective data — useful for planning and policy decisions'])],
    [('Khan Academy: Geographic Tools and Technology','GIS, GPS, remote sensing, and spatial data in geography','https://www.khanacademy.org/humanities/ap-geography')],
    ['What types of data layers would you include in a GIS analysis of food deserts?','How does remote sensing differ from direct field observation?','What makes VGI both valuable and unreliable?']),
  ],
  'unit_qs':[
   ('Compare the three types of regions and explain which type is most useful for studying cultural identity.',
    ['Formal region: uniform characteristic throughout — useful for mapping language or religion boundaries','Functional region: organized around a central node — useful for economic or media market analysis','Perceptual region: defined by cultural perception — most directly useful for studying cultural identity','Perceptual regions capture how people define themselves culturally, even without objective boundaries']),
   ('Explain how the spatial perspective helps geographers understand the spread of a contagious disease.',
    ['Spatial perspective asks where cases are, why there, and what spatial pattern results','Mapping case locations reveals clusters, corridors, and distance decay from the origin','Scale matters: local maps show neighborhood transmission; national maps show regional spread','Spatial analysis informs intervention — closing routes of spatial diffusion slows spread']),
   ('Why is it important for geographers to use multiple scales of analysis for the same phenomenon?',
    ['Different scales reveal different patterns — local scale shows neighborhood detail; global shows continental trends','A process visible at global scale (climate change) may not appear in local data and vice versa','Using multiple scales prevents the modifiable areal unit problem — patterns that shift with boundary choices','Example: income inequality looks different at city block vs. national scale']),
   ('Evaluate the advantages of GIS over traditional paper maps for geographic analysis.',
    ['GIS allows layering of multiple data sets — paper maps show one variable at a time','GIS supports querying: "find all areas within 2 km of a hospital with income below poverty threshold"','GIS is updatable in real time; paper maps become outdated as conditions change','GIS can model spatial scenarios — paper maps cannot simulate "what if" outcomes']),
   ('How does distance decay apply to migration patterns and what factors can overcome it?',
    ['Distance decay predicts that migration volume decreases as distance from origin increases','Most migrants move short distances — supporting Ravenstein\'s Laws of Migration','Intervening opportunities closer to home reduce the motivation to migrate to distant destinations','Factors overcoming distance decay: strong pull factors (high wages), chain migration networks, refugee displacement']),
   ('Explain how cartographic distortion affects the political messages maps can send.',
    ['All projections distort shape, area, distance, or direction — the choice of projection is never neutral','Mercator exaggerates the size of high-latitude countries (Europe, Russia) relative to equatorial ones','This can reinforce imperial worldviews — Peters projection was created to correct Mercator\'s area distortions','Map makers choose projections, colors, and labels — these choices shape how viewers interpret geographic reality']),
   ('How does topophilia explain why communities resist gentrification?',
    ['Topophilia is deep emotional attachment to a specific place, coined by Yi-Fu Tuan','Long-term residents have place identity — the neighborhood is part of who they are, not just where they live','Gentrification brings displacement — residents lose not just housing but the place that holds their identity and memory','Topophilia explains why resistance is emotional and intense, not just economic']),
   ('Distinguish site from situation and explain which factor is more likely to change over time.',
    ['Site: physical characteristics of a location — terrain, water, soil — these are relatively stable','Situation: relative position to surrounding areas — trade routes, other cities — these change as infrastructure and politics change','Situation is far more likely to change: a new highway can transform a remote site into a regional hub overnight','Example: Las Vegas had poor site (desert, scarce water) but transformed due to changing situation (transportation, tourism economy)']),
   ('How does volunteered geographic information change who can participate in geographic knowledge production?',
    ['Historically, geographic knowledge was produced by states, militaries, and professional cartographers','VGI platforms like OpenStreetMap allow anyone with a smartphone to contribute spatial data','This democratizes mapping — remote or crisis areas get mapped by local volunteers faster than official agencies','However, digital divides mean VGI still underrepresents areas with low internet access']),
   ('Explain what is meant by "the death of distance" and evaluate whether it is occurring.',
    ['"Death of distance": technology (internet, air travel) eliminates geographic barriers to interaction','Evidence for: global e-commerce, remote work, and video calling reduce the cost of distance','Evidence against: distance decay persists — local businesses still outperform distant ones for fresh goods and services','Conclusion: distance is reduced but not eliminated — Tobler\'s First Law still holds in modified form']),
  ]},

 {'num':2,'title':'Population and Migration Patterns and Processes',
  'file':'ap-human-geography-2-unit-2-population-and-migration-patterns-and-processes.html',
  'desc':'Population distribution, demographic change, and human migration are shaped by environmental, economic, social, and political forces.',
  'gateway':['Explain global population distribution using physical and human factors','Apply the Demographic Transition Model to explain population change','Classify types of migration and explain their causes','Analyze the effects of migration on origin and destination regions'],
  'lessons':[
   _l('Population Distribution and Density',
    [_t('Arithmetic vs. Physiological Density','Arithmetic (crude) density = total population ÷ total land area. Physiological density = total population ÷ arable (farmable) land — a better measure of agricultural pressure. Egypt has low arithmetic density but extremely high physiological density because only the Nile Valley is habitable.',
        'Students confuse arithmetic density (total land) with physiological density (arable land). Physiological density reveals more about food security pressure.',
        'MCQ presents population and land data and asks which density measure best reveals agricultural stress on a country.'),
     _t('Factors Affecting Population Distribution','Populations cluster in areas with favorable physical geography: flat terrain, mild climate, fertile soil, fresh water access — these are ecumene (permanently inhabited areas). Extreme environments — deserts, high mountains, polar regions — are sparsely populated non-ecumene.',
        'Physical geography limits but does not fully determine distribution — Tokyo exists in an earthquake zone; Amsterdam is below sea level. Human factors (economic opportunity, governance) also drive distribution.',
        'FRQ asks you to explain why a specific region is densely or sparsely populated using both physical and human factors.'),
     _t('Population Pyramids','A population pyramid graphs the age-sex structure of a population. A wide base and narrow top indicate high birth and death rates (Stage 2 DTM). A column-shaped pyramid indicates low birth and death rates (Stage 4). An inverted pyramid (narrow base) indicates below-replacement fertility (Stage 5).',
        'Students read pyramids incorrectly — the LEFT side is always MALE; the RIGHT is FEMALE. A wide cohort does not mean a high proportion of elderly; it means many people in that age group.',
        'MCQ shows a pyramid and asks you to identify the DTM stage, likely growth trajectory, or a policy challenge the country faces.')],
    [('arithmetic density','Total population divided by total land area'),
     ('physiological density','Total population divided by arable land — measures agricultural pressure'),
     ('ecumene','Permanently inhabited areas of Earth\'s surface'),
     ('population pyramid','Bar graph showing age and sex distribution of a population'),
     ('dependency ratio','Ratio of non-working (young + elderly) to working-age population')],
    ['Distinguish arithmetic from physiological density and explain when physiological density is more informative','Identify physical and human factors that explain population clustering','Interpret a population pyramid to identify demographic stage and policy challenges'],
    ['Calculate physiological density from given data and explain what a high value means','Describe what a wide base vs. a narrow base on a population pyramid indicates','Explain why Egypt has low arithmetic density but high physiological density'],
    ['Compare population pyramids of two countries at different DTM stages and list three differences','Look up physiological density data for three countries and explain what the variation reveals'],
    [('Why does Egypt have low arithmetic density but extremely high physiological density?',
      ['Arithmetic density = total population ÷ total land; Egypt\'s vast desert keeps this low',
       'Physiological density = population ÷ arable land; only the Nile Valley and Delta are farmable — very small area',
       'Egypt\'s population concentrates in ~4% of the country\'s land along the Nile',
       'High physiological density signals intense agricultural pressure and food security risk']),
     ('What does a wide base on a population pyramid indicate about a country\'s demographic situation?',
      ['A wide base indicates a large proportion of young people — high recent birth rates',
       'This is typical of Stage 2 or Stage 3 of the DTM — high fertility, declining mortality',
       'Implications: rapid population growth in coming decades as young cohort enters reproductive age',
       'Policy challenge: high dependency ratio — many young dependents relative to working-age population']),
     ('Explain the concept of the ecumene and give two examples of non-ecumene regions.',
      ['Ecumene: permanently inhabited areas of Earth where sustained human settlement is possible',
       'Defined by favorable physical factors: mild climate, fresh water, arable soil, navigable terrain',
       'Non-ecumene examples: Sahara Desert (extreme heat and aridity), Antarctica (extreme cold)',
       'Non-ecumene is not uninhabited — temporary research stations, nomadic routes exist — but not permanently settled']),
     ('How does dependency ratio affect a country\'s economic development?',
      ['Dependency ratio = (population under 15 + over 65) ÷ working-age population (15–64)',
       'High dependency ratio: many dependents relative to workers — strains social services, education, healthcare',
       'Low dependency ratio: more workers per dependent — a "demographic dividend" that can boost economic growth',
       'Example: Japan\'s aging population creates an extremely high elderly dependency ratio, straining pension systems']),
     ('Compare the population distribution patterns of Bangladesh and Canada and explain the difference.',
      ['Bangladesh: very high arithmetic density (~1,200/km²) — small country, large population, fertile floodplains',
       'Canada: very low arithmetic density (~4/km²) — vast land area, most uninhabitable (Arctic, boreal forest)',
       'Bangladesh clusters in ecumene (Ganges-Brahmaputra delta); Canada clusters in narrow southern corridor near US border',
       'Physical geography (climate, terrain, water) explains most of the difference in distribution'])],
    [('Heimler\'s History: APHUG Unit 2 — Population',_H+'unit+2+population+distribution+density','https://www.youtube.com/results?search_query=heimler+history+aphug+unit+2+population')],
    ['What is the difference between arithmetic and physiological density?','Why do populations cluster in ecumene zones?','What does a narrow base on a population pyramid suggest about future growth?']),
   _l('The Demographic Transition Model',
    [_t('The DTM and Its Five Stages','The Demographic Transition Model (DTM) describes how populations shift from high birth and death rates to low birth and death rates as countries industrialize. Stage 1: high CBR, high CDR, stable population. Stage 2: CDR drops (medical advances), CBR stays high — population EXPLODES. Stage 3: CBR drops as urbanization, education, and women\'s rights increase. Stage 4: low CBR and CDR, stable. Stage 5: below-replacement fertility, population decline.',
        'Students confuse which rate drops first — the DEATH rate drops first in Stage 2 (medical/sanitation advances), not the birth rate. Birth rate drops later in Stage 3.',
        'MCQ presents a country\'s vital rates and asks which DTM stage it is in; FRQ asks you to explain the cause of rate changes.'),
     _t('Natural Increase Rate and Doubling Time','Natural Increase Rate (NIR) = CBR − CDR (expressed as a %). Population doubles in approximately 70 ÷ NIR years (Rule of 70). A country with NIR of 2% doubles in ~35 years. NIR peaks in Stage 2 when CDR falls sharply but CBR remains high.',
        'NIR does not account for migration — it only measures births minus deaths. Total population change also includes net migration.',
        'MCQ asks you to calculate NIR from CBR and CDR data, or apply the Rule of 70 to estimate doubling time.'),
     _t('Epidemiological Transition Model','The Epidemiological Transition Model (ETM) complements the DTM by tracking how causes of death change as countries develop. Stage 2: infectious/parasitic diseases dominate. Stages 3–4: chronic diseases (heart disease, cancer) dominate as people live longer. Stage 5: diseases of affluence and re-emerging diseases (antibiotic resistance).',
        'Students forget the ETM is about CAUSES OF DEATH, not about birth rates. It explains why death rates fall in DTM Stage 2 (infectious disease control).',
        'FRQ may ask you to link the ETM to the DTM, explaining how controlling infectious disease drives the CDR decline in Stage 2.')],
    [('crude birth rate','Number of births per 1,000 people per year'),
     ('crude death rate','Number of deaths per 1,000 people per year'),
     ('natural increase rate','CBR minus CDR — the rate of population growth excluding migration'),
     ('total fertility rate','Average number of children born to a woman over her lifetime'),
     ('replacement-level fertility','TFR of ~2.1 needed to maintain a stable population without migration')],
    ['Describe the five stages of the DTM and the vital rate changes at each stage','Calculate NIR using CBR and CDR data and apply the Rule of 70','Explain how the Epidemiological Transition Model complements the DTM'],
    ['Identify a country\'s DTM stage from given CBR, CDR, and NIR data','Explain why CDR falls before CBR in the transition from Stage 1 to Stage 2','Describe the policy challenges a Stage 4 country faces due to an aging population'],
    ['Plot CBR, CDR, and NIR for three countries at different DTM stages on the same graph','Research Japan\'s TFR and identify its DTM stage; explain one consequence for that country'],
    [('A country has a CBR of 35 and a CDR of 12. What is its NIR and what DTM stage is it likely in?',
      ['NIR = CBR − CDR = 35 − 12 = 23 per 1,000 = 2.3%',
       'By the Rule of 70: doubling time ≈ 70 ÷ 2.3 ≈ 30 years — very rapid growth',
       'A high CBR (35) with falling CDR (12) is characteristic of DTM Stage 2 or early Stage 3',
       'The country is likely experiencing rapid population growth driven by declining death rates while birth rates remain high']),
     ('Why does the death rate fall before the birth rate in the DTM?',
      ['CDR falls first due to external interventions: vaccines, antibiotics, improved sanitation, and food security',
       'These improvements can be implemented rapidly without major cultural change',
       'CBR falls later because it requires cultural shifts: urbanization, women\'s education, family planning access',
       'The gap between falling CDR and falling CBR creates the population explosion in Stage 2']),
     ('What is the Epidemiological Transition Model and how does it relate to the DTM?',
      ['ETM tracks how dominant causes of death change as a country develops',
       'Stage 2 (DTM): infectious and parasitic diseases (cholera, smallpox, tuberculosis) dominate',
       'Stages 3–4 (DTM): chronic diseases (heart disease, cancer, diabetes) become dominant as life expectancy rises',
       'The ETM explains WHY the CDR falls in DTM Stage 2 — control of infectious disease is the mechanism']),
     ('What demographic challenges does a Stage 5 DTM country face?',
      ['Stage 5: TFR below replacement level (~2.1) — population is shrinking or aging rapidly',
       'Challenge 1: aging population — rising elderly dependency ratio, pension and healthcare strain',
       'Challenge 2: shrinking labor force — fewer workers to support economic output and social services',
       'Policy responses: immigration encouragement, pronatalist policies (child benefits, parental leave), raising retirement age']),
     ('How does total fertility rate differ from crude birth rate and which is more useful for demographic analysis?',
      ['CBR: births per 1,000 total population — simple but sensitive to age structure (many elderly distorts it)',
       'TFR: average number of children per woman over her lifetime — controls for age structure',
       'TFR is more useful for predicting long-run population trends — it shows actual childbearing behavior',
       'Example: a country with many elderly and few women of reproductive age has low CBR but TFR may still be high'])],
    [('Heimler\'s History: DTM and Population Change','Demographic Transition Model stages, vital rates, and NIR calculations',_H+'demographic+transition+model')],
    ['Which DTM stage has the highest NIR and why?','What does a TFR below 2.1 mean for long-run population?','How does the ETM explain the CDR decline in Stage 2?']),
   _l('Types and Causes of Migration',
    [_t('Push and Pull Factors','Migration is driven by push factors (forces driving people away from origin — poverty, conflict, environmental disaster) and pull factors (forces attracting people to destination — jobs, safety, family). Ravenstein\'s Laws (1885) describe migration patterns: most migrants move short distances, step-migrate through urban hierarchy, and are young adults.',
        'Students confuse push and pull by listing vague factors. Always ask: does this force REPEL from origin (push) or ATTRACT to destination (pull)?',
        'MCQ presents a migration scenario and asks you to classify the factors as push, pull, or intervening obstacles.'),
     _t('Types of Migration','Voluntary migration: individuals choose to move — economic migrants, lifestyle migration. Forced migration: people are compelled to move — refugees (cross international borders), internally displaced persons (IDPs, move within home country), asylum seekers. Internal migration: within a country — rural-to-urban. International migration: across national borders.',
        'Refugees cross INTERNATIONAL borders — IDPs are displaced within their own country. Students often confuse these two.',
        'FRQ may ask you to distinguish refugees from IDPs and explain the legal protections (or lack thereof) each group receives.'),
     _t('Intervening Obstacles and Opportunities','Intervening obstacles are barriers that discourage migration: physical (mountains, oceans), cultural (language, discrimination), economic (cost of moving), political (border controls). Intervening opportunities are attractive alternatives encountered en route — they can stop a migrant before reaching the original destination.',
        'Intervening opportunities explain why migrants often stop short of their intended destination when they find a suitable place along the way.',
        'MCQ may ask why migration from rural Mexico to Chicago stops in Texas cities — Texas provides intervening opportunities.')],
    [('push factor','A condition at the origin that drives people to leave — poverty, conflict, natural disaster'),
     ('pull factor','A condition at the destination that attracts migrants — employment, safety, family networks'),
     ('refugee','Person forced to cross an international border due to persecution, conflict, or disaster'),
     ('IDP','Internally Displaced Person — forced from home but remains within home country borders'),
     ('intervening obstacle','A barrier that discourages or prevents migration between origin and destination')],
    ['Classify migration factors as push, pull, or intervening obstacles','Distinguish refugees from IDPs and explain the difference in legal status','Apply Ravenstein\'s Laws to predict migration patterns from a given scenario'],
    ['Identify push and pull factors from a described migration case study','Explain why most international migrants move to neighboring countries','Describe how chain migration sustains a migration flow over time'],
    ['Map the push and pull factors for Syrian refugee migration since 2011','Explain how Ravenstein\'s Laws apply to rural-to-urban migration in India'],
    [('Using push-pull theory, explain why Syrian refugees moved to Germany and Turkey in large numbers after 2011.',
      ['Push factors: civil war violence, government persecution, destroyed infrastructure, economic collapse in Syria',
       'Pull factors: Germany offered asylum, economic opportunity, and established Syrian communities (chain migration)',
       'Turkey offered geographic proximity and open border policy — an intervening opportunity for many',
       'Distance decay: Turkey received more refugees due to proximity; Germany received those with resources to travel further']),
     ('Explain the legal difference between a refugee and an internally displaced person.',
      ['Refugee: crosses an international border fleeing persecution, conflict, or disaster — protected under 1951 UN Refugee Convention',
       'IDP: displaced from home but remains within national borders — NOT covered by Refugee Convention',
       'IDPs often have fewer legal protections than refugees — they rely on their own government, which may be the source of persecution',
       'Example: in 2023, Sudan\'s civil war created millions of IDPs (within Sudan) and refugees (who crossed into Chad, Egypt, Ethiopia)']),
     ('How does chain migration sustain a migration flow over decades?',
      ['Chain migration: established migrants send information, money, and assistance to family and community members at origin',
       'This reduces intervening obstacles — new migrants have a social network, housing, and job leads at destination',
       'Chain migration creates ethnic enclaves at destination — Chinatowns, Little Italys — which further attract compatriots',
       'A flow started by economic conditions can persist long after conditions change, sustained by social networks']),
     ('Describe three of Ravenstein\'s Laws of Migration and evaluate their applicability today.',
      ['Most migrants move short distances — still true: majority of migration is internal or to neighboring countries',
       'Migration proceeds step-by-step through the urban hierarchy — rural to small town to city to metropolis',
       'Every migration flow generates a counterflow — return migration and reverse flows are common',
       'Modern exceptions: refugee crises and high-skilled international migration can violate distance prediction']),
     ('What is the difference between voluntary and forced migration and why does the distinction matter legally?',
      ['Voluntary migration: migrants choose to move based on economic or lifestyle motivations — no legal special status',
       'Forced migration: migrants are compelled by violence, persecution, or disaster — may qualify for refugee status',
       'The distinction matters: refugees have rights under international law; economic migrants do not',
       'However, the line is blurry — "climate refugees" fleeing rising seas may not qualify under current legal definitions'])],
    [('Heimler\'s History: APHUG Migration Types','Push-pull theory, types of migration, refugees, and Ravenstein\'s Laws',_H+'migration+types+push+pull')],
    ['What is the difference between a refugee and an IDP?','How does chain migration reduce intervening obstacles?','Which of Ravenstein\'s Laws best predicts most migration today?']),
   _l('Effects of Migration on Origin and Destination',
    [_t('Brain Drain and Remittances','Brain drain: emigration of highly educated and skilled workers from developing countries to developed ones, reducing human capital at origin. Remittances: money sent by migrants back to their home country — for many developing nations, remittances exceed foreign direct investment and foreign aid.',
        'Brain drain is not always permanent — brain circulation describes return migration of skilled workers who bring back capital and skills.',
        'FRQ may ask you to evaluate whether emigration overall helps or hurts a developing country given both brain drain and remittances.'),
     _t('Cultural Effects of Migration','Migrants bring cultural traits — language, food, religion, music — to destination countries, creating cultural diffusion and diaspora communities. At origin, out-migration can reduce cultural vitality. Destination countries experience acculturation (cultural change through contact), assimilation (adopting host culture), and sometimes nativist backlash.',
        'Assimilation and acculturation are not the same: acculturation = change through contact (retain home identity); assimilation = full adoption of host culture (lose home identity).',
        'MCQ may distinguish between cultural diffusion types: relocation diffusion (migrants carry culture physically) vs. expansion diffusion (ideas spread through networks).'),
     _t('Demographic Effects of Migration','Immigration typically increases fertility rates at destination (immigrants often have higher TFR than native population, at least initially). Emigration of young adults reduces birth rates and workforce at origin. Immigration is increasingly used by Stage 4/5 countries to offset aging populations and labor shortages.',
        'Students assume immigration always increases population at destination proportionally. Immigration also changes age structure — working-age immigrants shift the dependency ratio.',
        'AP FRQ asks how immigration affects demographic indicators in both origin and destination countries.')],
    [('brain drain','Emigration of highly skilled or educated workers from a country, reducing its human capital'),
     ('remittances','Money sent by migrants back to their home country — a major income source for developing nations'),
     ('diaspora','Community of people living outside their homeland who maintain cultural connection to it'),
     ('acculturation','Cultural change resulting from contact between two cultures — partial adoption of new traits'),
     ('assimilation','Process by which an immigrant group fully adopts the culture of the host society')],
    ['Explain the concept of brain drain and identify a country severely affected by it','Describe how remittances benefit origin countries and their limitations','Distinguish between acculturation and assimilation with examples'],
    ['Evaluate whether emigration is net positive or net negative for a developing country','Explain how immigration affects the age structure and dependency ratio of a destination country','Describe cultural effects of migration on both origin and destination regions'],
    ['Research the top remittance-receiving countries and explain what this reveals about migration flows','Find an example of cultural diffusion through migration in your own community'],
    [('Explain how remittances can simultaneously help and fail a developing country.',
      ['Help: remittances provide foreign currency, fund education, healthcare, and housing for recipient families',
       'Help: in some countries (Philippines, El Salvador), remittances exceed 10% of GDP — larger than foreign aid',
       'Fail: remittances create dependency — communities may reduce local economic investment expecting migrant income',
       'Fail: if global economy slows or migrants lose jobs, remittance flows collapse, devastating dependent communities']),
     ('How does brain drain affect the healthcare systems of sub-Saharan African countries?',
      ['Brain drain: skilled workers (doctors, nurses, engineers) emigrate to higher-wage countries',
       'Sub-Saharan Africa trains medical professionals who then emigrate to UK, USA, Canada — leaving critical shortages',
       'Effect: remaining population has reduced access to healthcare, worse health outcomes, higher CDR',
       'Some countries tie scholarships to mandatory service periods or offer incentives to retain graduates']),
     ('How does immigration help Stage 4 and Stage 5 countries manage aging populations?',
      ['Stage 4/5: low TFR leads to aging population and shrinking working-age cohort',
       'Immigration typically brings young working-age adults — improving dependency ratio',
       'Immigrants pay taxes and social security contributions that fund elderly pensions and healthcare',
       'Example: Germany, Japan face severe aging — Germany actively recruits skilled immigrants; Japan has resisted but is changing']),
     ('Describe the cultural landscape changes that result from large-scale immigration to a city.',
      ['Ethnic enclaves form: Chinatowns, Little Havana, Koreatown — concentrated cultural geography',
       'Language diversity: signage, newspapers, schools, and services appear in immigrant languages',
       'Religious landscapes change: mosques, temples, or churches built to serve new communities',
       'Cuisine and entertainment: restaurants, festivals, and markets reflecting immigrant cultures reshape urban character']),
     ('What is the difference between relocation and expansion diffusion and how does migration fit in?',
      ['Relocation diffusion: cultural traits move WITH people as they migrate — the trait leaves the origin',
       'Expansion diffusion: traits spread OUTWARD from origin without the originators leaving — hierarchical or contagious',
       'Migration is a primary mechanism of relocation diffusion — migrants physically carry language, food, religion to new places',
       'Example: West African drumming traditions arrived in Brazil through forced migration (relocation diffusion)'])],
    [('Heimler\'s History: APHUG Migration Effects','Brain drain, remittances, cultural diffusion, and demographic effects of migration',_H+'migration+effects+brain+drain+remittances')],
    ['What is brain drain and how do remittances partially offset it?','How does immigration change the age structure at destination?','Give an example of relocation diffusion through migration.']),
  ],
  'unit_qs':[
   ('A country in Stage 2 of the DTM has a CBR of 40 and CDR of 15. Calculate its NIR and estimate its doubling time.',
    ['NIR = CBR − CDR = 40 − 15 = 25 per 1,000 = 2.5%','Doubling time = 70 ÷ 2.5 = 28 years — extremely rapid growth','This country will double its population in less than 30 years if NIR remains constant','Policy implications: massive investment needed in schools, housing, food, and healthcare for growing young population']),
   ('Explain why physiological density is a more meaningful measure than arithmetic density for food security analysis.',
    ['Arithmetic density spreads population across ALL land, including deserts and mountains','Physiological density counts only arable land — the land that actually produces food','A country with vast but unusable territory will have low arithmetic but high physiological density','High physiological density means intense pressure on farmland — signaling food security vulnerability']),
   ('Using Ravenstein\'s Laws, predict the most likely migration pattern from a poor rural region to a distant major city.',
    ['Most migrants will NOT go directly — step migration predicts movement through intermediate cities','Young adults will dominate the migrant stream — family-age workers seeking economic opportunity','A counterflow of return migrants will develop over time as some fail or choose to return','Intervening opportunities in medium-sized cities may capture many migrants before they reach the major destination']),
   ('How does the stage of the DTM affect a country\'s dependency ratio?',
    ['Stage 1: high youth and elderly dependency — high birth and death rates, short life expectancy','Stage 2-3: high youth dependency as birth rates stay high; elderly dependency low (shorter lifespans)','Stage 4: declining youth dependency as TFR falls; rising elderly dependency as life expectancy grows','Stage 5: very high elderly dependency — below-replacement fertility means proportionally very few young workers']),
   ('Compare voluntary economic migration with forced migration in terms of migrant characteristics and legal status.',
    ['Economic migrants: voluntary, often educated or skilled, seeking better wages — no special legal protection','Forced migrants: compelled by violence or persecution — refugees receive UN protection and potential asylum','Economic migrants can return freely; forced migrants may face danger if returned to origin','Distinction matters for policy: host countries have legal obligations to refugees but not economic migrants']),
   ('Explain how cultural diffusion through migration creates ethnic enclaves in cities.',
    ['Migrants cluster in areas with affordable housing and established compatriot communities — chain migration effect','Enclaves provide cultural familiarity: language, food, religion, social networks reduce cultural shock','Over time, enclaves develop distinct cultural landscapes — signage, architecture, festivals become visible','Examples: Chinatown (San Francisco), Little Italy (NYC), Somali communities in Minneapolis']),
   ('Why do most refugees not migrate to wealthy Western countries despite common political assumptions?',
    ['Most refugees move to neighboring countries — distance decay and limited resources prevent long-distance movement','Top refugee-hosting countries are typically developing neighbors: Turkey, Colombia, Uganda, Pakistan','Wealthier Western countries receive a small fraction of global refugees despite high media visibility','This challenges the narrative that refugees predominantly seek wealthy destinations']),
   ('How does emigration of young adults affect the population pyramid of a sending country?',
    ['Young adult cohorts shrink as emigrants leave — the working-age bulge narrows in the pyramid','Birth rates at origin may decline — fewer women of reproductive age remain','Elderly cohorts become proportionally larger — dependency ratio shifts upward','Over time, origin country may face labor shortages and declining NIR from reduced reproductive-age population']),
   ('Explain the concept of a refugee crisis using one specific modern example.',
    ['A refugee crisis occurs when displacement exceeds the capacity of host systems to respond','Example: Syrian Civil War (2011–present) — over 6 million Syrians became refugees','Push factors: government violence, barrel bombing, ISIS, economic collapse','Host countries: Turkey (3.5M), Lebanon (1.5M) faced overwhelming strain; EU received ~1M in 2015 peak year']),
   ('How do pronatalist and antinatalist policies attempt to change natural increase rates?',
    ['Pronatalist: government encourages higher birth rates — used in Stage 4/5 countries (France, Sweden) via paid parental leave, child benefits, tax incentives','Antinatalist: government discourages birth rates — used in Stage 2/3 countries with rapid growth (India\'s family planning campaigns, China\'s One-Child Policy 1980–2015)','Effectiveness varies: Sweden\'s policies modestly increased TFR; China\'s One-Child Policy dramatically reduced TFR but created gender imbalance','Population policy is contested — involves reproductive rights, gender equality, and cultural values']),
  ]},

 {'num':3,'title':'Cultural Patterns and Processes',
  'file':'ap-human-geography-3-unit-3-cultural-patterns-and-processes.html',
  'desc':'Culture — language, religion, ethnicity, and customs — spreads across space through diffusion and shapes the cultural landscape of places.',
  'gateway':['Describe how cultural traits spread through diffusion','Explain the geographic distribution of world languages and language families','Compare universalizing and ethnic religions in their spatial patterns','Analyze how globalization and cultural identity interact'],
  'lessons':[
   _l('Cultural Traits and Diffusion',
    [_t('Types of Cultural Diffusion','Expansion diffusion: the trait spreads outward from origin while remaining at origin. Three types: hierarchical (spreads from major cities downward — fashion, music trends), contagious (spreads outward like a wave to all nearby areas — disease, memes), stimulus (the idea spreads but adapts — McDonald\'s localizes menu globally). Relocation diffusion: migrants physically carry the trait to new locations.',
        'Students confuse hierarchical and contagious diffusion. Hierarchical follows the urban hierarchy (city to city, then small towns); contagious spreads to ALL nearby areas regardless of size.',
        'MCQ presents a diffusion scenario and asks which type of diffusion it represents based on how the pattern spreads.'),
     _t('Cultural Landscape','The cultural landscape is the visible imprint of human activity on the physical landscape — shaped by religion (cathedrals, mosques), language (signage), economic activity (agricultural field patterns), and ethnicity (architecture styles). Carl Sauer coined the term, emphasizing culture as the agent transforming natural landscape into cultural landscape.',
        'The cultural landscape is what you CAN SEE — it is the material expression of culture. Students sometimes conflate culture itself with cultural landscape.',
        'FRQ asks you to identify features of a cultural landscape and explain which cultural force created them.'),
     _t('Sequent Occupance','Sequent occupance: successive societies leave their cultural imprint on a place, creating layers of cultural landscape. A location may show Roman walls, medieval churches, industrial mills, and modern apartments — each layer visible in the current landscape.',
        'Sequent occupance does not mean earlier layers disappear — they persist alongside newer layers.',
        'AP exam may present an image or description of a site and ask you to explain it using sequent occupance.')],
    [('cultural diffusion','The spread of cultural traits from one place to another'),
     ('hierarchical diffusion','Diffusion from nodes of power downward — from cities to smaller towns'),
     ('contagious diffusion','Rapid, widespread diffusion to nearby areas regardless of rank'),
     ('stimulus diffusion','The underlying idea spreads but the specific trait adapts to local conditions'),
     ('cultural landscape','Visible modification of the physical landscape by a cultural group — buildings, fields, signage')],
    ['Distinguish the four types of cultural diffusion with geographic examples','Explain what the cultural landscape reveals about the culture that created it','Describe how sequent occupance creates layers of cultural meaning in a single place'],
    ['Classify a diffusion example as hierarchical, contagious, stimulus, or relocation','Identify cultural landscape features that reveal religious, linguistic, or economic culture','Explain how a city\'s cultural landscape reflects sequent occupance'],
    ['Photograph five examples of cultural landscape in your community and explain what cultural force created each','Create a timeline of sequent occupance for your city or a famous historical city'],
    [('How does McDonald\'s global expansion illustrate stimulus diffusion?',
      ['Stimulus diffusion: the idea (fast food restaurant) spreads globally but adapts the specific trait to local conditions',
       'McDonald\'s offers McAloo Tikki burgers in India (no beef), Teriyaki burgers in Japan, McBaguette in France',
       'The American fast food concept diffuses worldwide, but specific menu items adapt to local food cultures',
       'This distinguishes stimulus from hierarchical diffusion, which does not require adaptation']),
     ('Explain how fashion trends illustrate hierarchical diffusion.',
      ['Hierarchical diffusion: traits spread from major nodes (cities) downward through the urban hierarchy',
       'High fashion originates in Paris, Milan, New York — then diffuses to regional capitals, then small cities, then rural areas',
       'The trend reaches large cities first and small towns last — following population rank, not geographic distance',
       'This contrasts with contagious diffusion, which spreads to all nearby areas simultaneously']),
     ('What does the presence of a cathedral, a mosque, and a synagogue within one city block reveal about cultural geography?',
      ['This illustrates sequent occupance: successive cultural groups have left their religious imprint on the landscape',
       'A cathedral suggests Catholic or Protestant European settlement; mosque suggests Muslim community; synagogue Jewish',
       'The cultural landscape preserves layers of history — each structure represents a different period of cultural dominance',
       'This is visible evidence of cultural diffusion, migration, and coexistence']),
     ('How does Carl Sauer\'s concept of cultural landscape differ from the physical landscape?',
      ['Physical landscape: natural environment before human modification — terrain, climate, vegetation',
       'Cultural landscape: the physical landscape transformed by human culture — fields, roads, cities, religious structures',
       'Sauer (1925) argued culture is the AGENT, natural environment the MEDIUM, cultural landscape the RESULT',
       'Example: the Rhine Valley\'s terraced vineyards are natural terrain (physical) shaped by centuries of wine culture (cultural landscape)']),
     ('Give an example of relocation diffusion and explain why the trait left the origin region.',
      ['Relocation diffusion: migrants physically carry cultural traits — the trait moves WITH the people',
       'Example: West African musical traditions (drumming, call-and-response) relocated to the Americas through forced migration',
       'The trait was lost at origin during the Transatlantic Slave Trade\'s disruption — relocated without returning',
       'Another example: English language relocated to North America, Australia, and India through British colonization'])],
    [('Heimler\'s History: APHUG Cultural Diffusion','Types of diffusion, cultural landscape, and sequent occupance',_H+'cultural+diffusion+landscape')],
    ['What is the difference between hierarchical and contagious diffusion?','How does sequent occupance shape a city\'s visible landscape?','Give an example of stimulus diffusion from daily life.']),
   _l('Language Families and Distribution',
    [_t('World Language Families','The Indo-European family is the world\'s largest by speakers — includes Germanic (English, German), Romance (Spanish, French), Slavic (Russian), and Indo-Iranian (Hindi, Farsi) branches. Sino-Tibetan is second (Mandarin, Cantonese). Language families share a common ancestral proto-language and diverged through geographic isolation.',
        'A language family is not a language — English and Hindi are in the same FAMILY (Indo-European) but are mutually unintelligible. Students confuse family with branch and language.',
        'MCQ asks you to identify which language family a given language belongs to, or which language is in the same family as a given example.'),
     _t('Lingua Franca and Language Diversity','A lingua franca is a language used for communication between groups with different native languages — English is the global lingua franca of business and diplomacy. Pidgin languages develop as simplified contact languages; creoles form when pidgins become native languages for children. Language diversity is highest in tropical regions (Papua New Guinea has ~850 languages).',
        'A pidgin becomes a creole when children grow up speaking it as their first language — at that point it has full grammatical complexity.',
        'FRQ may ask you to explain why English became the global lingua franca and what the consequences are for linguistic diversity.'),
     _t('Language and Power','Language is a marker of political identity and power. Official language policies can suppress minority languages (French-only policy in Francophone Canada; Mandarin standardization in China). Endangered languages lose speakers as younger generations shift to dominant languages — when the last speaker dies, the language is extinct.',
        'Language policies are not politically neutral — they reflect power relationships between ethnic groups.',
        'AP exam may ask about language revival movements (Welsh in Wales, Hebrew in Israel) and their geographic dimensions.')],
    [('language family','Group of languages descended from a common ancestral proto-language'),
     ('lingua franca','A language used as a common means of communication between speakers of different native languages'),
     ('pidgin','A simplified language that develops as a contact language between groups with no common tongue'),
     ('creole','A pidgin that has become the native language of children — with full grammatical complexity'),
     ('isogloss','A geographic boundary line marking the extent of a linguistic feature')],
    ['Explain what it means for two languages to belong to the same language family','Distinguish pidgin from creole and explain how one evolves into the other','Describe how language serves as a marker of cultural and political identity'],
    ['Identify the language family and branch of a given language','Explain why linguistic diversity is highest in tropical regions','Describe one example of a language revival movement and its geographic context'],
    ['Map the Indo-European language family branches and label three languages in each','Research an endangered language and explain the factors threatening it'],
    [('Why is English considered a global lingua franca and what are the consequences of its dominance?',
      ['English became global lingua franca through British colonialism, then American economic and cultural dominance',
       'It is now dominant in science, technology, business, diplomacy, and entertainment worldwide',
       'Consequence: linguistic imperialism — non-English speakers face disadvantage in global markets and academia',
       'Consequence: extinction pressure on minority languages — younger generations abandon native language for English economic opportunity']),
     ('How do Hindi and English being in the same language family (Indo-European) help explain the history of South Asia?',
      ['Indo-European spread into South Asia via migration of Indo-Aryan peoples ~3,500 years ago',
       'Hindi/Urdu (Indo-Iranian branch) and English (Germanic branch) share a distant common proto-language ancestor',
       'British colonization brought English — now Hindi and English coexist as India\'s official languages',
       'Their shared family tree reflects overlapping migrations: ancient Indo-Aryan, then modern British colonial']),
     ('What is an isogloss and how is it used in linguistic geography?',
      ['An isogloss is a line on a map marking the boundary of a specific linguistic feature — a word, pronunciation, or grammar rule',
       'Isoglosses show dialect boundaries — where "pop" becomes "soda" in American English',
       'Bundles of isoglosses (many coinciding) mark strong dialect or language boundaries',
       'They reveal how geography (mountains, rivers) and history (settlement patterns) shaped language variation']),
     ('Explain why Papua New Guinea has more languages than any other country.',
      ['Papua New Guinea has ~850 languages despite a small population (~9 million)',
       'The mountainous terrain created extreme geographic isolation — valley populations developed independently for millennia',
       'Without contact (pre-colonialism), no lingua franca or language dominance emerged',
       'This illustrates how physical barriers prevent language spread and preserve diversity — the opposite of globalization\'s effect']),
     ('What is the difference between a language and a dialect and who decides?',
      ['Linguistic difference: dialects are mutually intelligible varieties of a language; separate languages are not',
       'Political reality: the distinction is often political — Norwegian and Danish are linguistically very similar but called separate languages (separate nations)',
       'Yiddish and Hebrew are called separate languages; Serbian and Croatian are nearly identical but called separate for political reasons',
       '"A language is a dialect with an army and a navy" — Max Weinreich\'s famous observation about political power'])],
    [('Heimler\'s History: APHUG Language','Language families, lingua franca, and language geography',_H+'language+families+lingua+franca')],
    ['What distinguishes a language family from a language branch?','How does a pidgin become a creole?','Why does geographic isolation create linguistic diversity?']),
   _l('Religion: Distribution and Cultural Impact',
    [_t('Universalizing vs. Ethnic Religions','Universalizing religions actively seek converts worldwide — Christianity (~2.4B), Islam (~1.9B), Buddhism (~500M). Ethnic (cultural) religions are tied to a specific ethnic group and do not actively proselytize — Judaism, Hinduism, Sikhism. Universalizing religions spread through missionaries and migration; ethnic religions stay concentrated geographically.',
        'Hinduism is an ethnic religion — you cannot convert to Hinduism in the traditional sense. Students often assume all major religions are universalizing.',
        'MCQ asks whether a described religion is universalizing or ethnic and asks you to justify using spatial diffusion patterns.'),
     _t('Sacred Spaces and Religious Landscape','Religions shape the cultural landscape: churches, mosques, synagogues, temples define urban form. Sacred spaces — Jerusalem, Mecca, Varanasi, the Western Wall — attract pilgrimage and generate conflict. Cemeteries, dietary restrictions (halal slaughterhouses, kosher butchers), and religious calendars all imprint on the landscape.',
        'Sacred space conflict arises from multiple religions claiming the same site — Jerusalem\'s Temple Mount/Al-Aqsa Mosque illustrates this tension.',
        'FRQ may describe a photograph of a cityscape and ask what religious features you can identify in the cultural landscape.'),
     _t('Religious Conflict and Geopolitics','Religious differences fuel boundary conflicts (India-Pakistan partition along Hindu-Muslim lines), theocracies (Iran, Vatican City), and civil wars. Fundamentalism — the belief in strict literal interpretation of religious texts — has shaped global politics. Religious diaspora communities (Jewish diaspora, Sikh diaspora) maintain cultural ties across borders.',
        'Fundamentalism is not limited to Islam — Christian, Jewish, and Hindu fundamentalist movements all exist. Avoid assuming religious conflict is always about Islam.',
        'AP FRQ may ask you to explain how religion serves as a centrifugal or centripetal force in a specific country.')],
    [('universalizing religion','Religion that actively seeks converts globally — Christianity, Islam, Buddhism'),
     ('ethnic religion','Religion tied to a specific cultural or ethnic group — does not actively proselytize — Hinduism, Judaism'),
     ('sacred space','A place given religious significance — may attract pilgrimage and generate territorial conflict'),
     ('pilgrimage','A journey to a sacred place — Hajj to Mecca, Camino to Santiago — reinforces religious identity'),
     ('religious fundamentalism','Movement emphasizing strict, literal interpretation of religious texts and doctrines')],
    ['Distinguish universalizing from ethnic religions and explain the geographic consequence of each','Describe how religion shapes the cultural landscape of cities','Explain how religious conflict can be both a centripetal and centrifugal force in a state'],
    ['Classify a described religion as universalizing or ethnic and justify using diffusion evidence','Identify religious features in a described cultural landscape','Explain how the Hindu-Muslim religious divide shaped the borders of South Asia'],
    ['Map the global distribution of Christianity, Islam, Buddhism, and Hinduism and identify overlap zones','Describe how two religions you can identify from the landscape of your community'],
    [('Why do universalizing religions have more geographically widespread distributions than ethnic religions?',
      ['Universalizing religions actively seek converts — missionaries and trade routes spread them globally',
       'Christianity spread via Roman roads, European colonialism, and missionary networks across the Americas, Africa, Asia',
       'Islam spread via Arab trade routes, conquest, and missionary activity across Africa, Central Asia, Southeast Asia',
       'Ethnic religions (Hinduism, Judaism) remain concentrated because they are tied to specific ethnic communities and do not proselytize']),
     ('How does religion shape the urban cultural landscape? Give three specific examples.',
      ['Skyline: church steeples, mosque minarets, temple rooftops define city skylines — visible from a distance',
       'Zoning: religious enclaves cluster around places of worship — halal markets and Islamic schools near mosques',
       'Temporal landscape: religious holidays create rhythms in the city — churches busy on Sunday, mosques on Friday, markets closed on holy days',
       'Dietary culture: kosher delis, halal butchers, and vegetarian restaurants (Hindu influence) shape the food landscape']),
     ('Explain why Jerusalem is a contested sacred space for three major religions.',
      ['Judaism: Temple Mount is the site of the First and Second Temple — holiest site in Judaism',
       'Christianity: Jerusalem is the site of Jesus\'s crucifixion, burial, and resurrection — Church of Holy Sepulchre',
       'Islam: Al-Aqsa Mosque and the Dome of the Rock on the Temple Mount — Prophet Muhammad\'s Night Journey',
       'All three religions claim ultimate sovereignty — the conflict is territorial, political, and deeply spiritual simultaneously']),
     ('How did the 1947 partition of India reflect religious geography?',
      ['British India was partitioned into Hindu-majority India and Muslim-majority Pakistan along religious lines',
       'The partition boundary (Radcliffe Line) separated populations that had coexisted — creating mass forced migration',
       '~14 million people relocated: Muslims to Pakistan, Hindus and Sikhs to India — one of history\'s largest forced migrations',
       'The religious boundary did not perfectly match ethnic or linguistic boundaries — Punjab was split, creating ongoing tension']),
     ('What is the difference between a theocracy and a secular state in terms of religious influence on governance?',
      ['Theocracy: government based on religious law — religious leaders hold political power (Iran: Supreme Leader is a cleric; Vatican City)',
       'Secular state: government operates independently of religion — religious practice is private (France\'s laïcité)',
       'In practice, most states fall between these poles — US is secular but religion heavily influences politics',
       'Theocracies create a state-religion fusion that affects law (dress codes, alcohol bans), foreign policy, and minority rights'])],
    [('Heimler\'s History: APHUG Religion','Universalizing vs. ethnic religions, sacred spaces, religious landscape',_H+'religion+universalizing+ethnic')],
    ['What makes a religion universalizing rather than ethnic?','How does religion create conflict over sacred spaces?','How did religion shape the borders of South Asia in 1947?']),
   _l('Cultural Change and Globalization',
    [_t('Globalization and Cultural Homogenization','Globalization is the increasing interconnection of the world\'s economies, cultures, and politics through trade, migration, and technology. Critics argue globalization creates cultural homogenization — the spread of American consumer culture (McDonald\'s, Disney, English) erasing local distinctiveness. Placelessness — landscapes that look the same everywhere — is one result.',
        'Globalization does not always destroy local culture — it can also create hybridization where global and local cultures blend.',
        'AP exam asks you to evaluate whether globalization strengthens or weakens cultural diversity, using specific examples.'),
     _t('Cultural Hybridization and Glocalization','Glocalization: global products and ideas adapt to local cultural contexts — a combination of globalization and localization. Cultural hybridization produces new cultural forms blending global and local traits: Bollywood blends Hollywood film style with Indian music and dance; Korean pop (K-pop) blends Western pop production with East Asian aesthetics.',
        'Glocalization is NOT just adaptation — it is a genuine two-way cultural exchange that produces new hybrid forms.',
        'MCQ may present an example of a global brand operating locally and ask whether it represents homogenization or glocalization.'),
     _t('Cultural Conflict: Acculturation vs. Assimilation','Acculturation: cultural change through contact — a group adopts some traits of another while retaining its own identity. Assimilation: full absorption into the dominant culture — original culture is abandoned. Forced assimilation (requiring immigrants to abandon native language) is politically and ethically contested. Syncretism: blending of two belief systems into a new form.',
        'Acculturation ≠ assimilation: acculturation is partial and mutual; assimilation is total and usually one-directional.',
        'FRQ may ask you to distinguish acculturation from assimilation in a described immigrant community scenario.')],
    [('globalization','The increasing worldwide integration of economies, cultures, and politics through trade, migration, and technology'),
     ('cultural homogenization','The spread of one culture globally at the expense of local cultural diversity'),
     ('glocalization','The adaptation of global products and ideas to fit local cultural contexts'),
     ('acculturation','Partial cultural change through contact with another culture while retaining core identity'),
     ('syncretism','The blending of elements from two different belief systems into a new hybrid form')],
    ['Explain how globalization can both threaten and enrich cultural diversity','Distinguish cultural homogenization from glocalization with examples','Define acculturation, assimilation, and syncretism and explain when each occurs'],
    ['Give an example of glocalization and explain what makes it different from pure cultural diffusion','Evaluate whether McDonald\'s global expansion represents homogenization or glocalization','Describe a syncretic cultural practice and explain its two source traditions'],
    ['Find three examples of glocalization in global brands operating in different countries','Identify a syncretic religious or cultural tradition and research its origins'],
    [('How does globalization contribute to placelessness? Give a specific example.',
      ['Placelessness: the loss of unique local character as global consumer culture spreads',
       'Globalization standardizes retail, architecture, and entertainment — airports, malls, and fast food strips look identical worldwide',
       'Example: a shopping mall in Dubai, São Paulo, or Chicago shares the same brands, layout, and atmosphere',
       'Geographer Edward Relph (1976) coined placelessness — arguing that authentic places are being replaced by standardized spaces']),
     ('Using K-pop as an example, explain how glocalization works.',
      ['K-pop is a hybrid cultural product: South Korean artists adopt Western pop music production, dance choreography, and social media marketing',
       'They add distinctly Korean aesthetics — fashion, visual culture, language, and fan interaction practices',
       'The result is a new global genre that is neither purely Korean nor purely Western — a genuine hybrid',
       'Glocalization: the global music industry model is adapted to Korean cultural context, producing something new that is now globally influential']),
     ('Explain the difference between acculturation and assimilation using an immigrant community example.',
      ['Acculturation: an immigrant community adopts some host culture traits while maintaining home culture — Spanish-speaking Cuban-Americans in Miami who learn English but retain Cuban food, music, and identity',
       'Assimilation: complete absorption into host culture — third-generation Irish-Americans who no longer speak Irish or identify primarily as Irish',
       'Key difference: acculturation preserves dual identity; assimilation erases original cultural identity',
       'Forced assimilation (e.g., Canadian residential schools for Indigenous children) is widely condemned as cultural genocide']),
     ('What is syncretism and give two examples from religion or cultural practice.',
      ['Syncretism: blending elements from two different belief systems to create a new hybrid',
       'Example 1: Candomblé (Brazil) — West African Yoruba religion blended with Portuguese Catholicism during slavery, producing a unique Afro-Brazilian faith',
       'Example 2: Christmas traditions blend Christian (nativity) and pre-Christian European (Yule trees, gift-giving) elements',
       'Syncretism often occurs under cultural pressure — dominated groups blend new beliefs with existing ones to preserve identity']),
     ('Evaluate whether globalization ultimately strengthens or weakens cultural diversity globally.',
      ['Argument for weakening: dominant cultures (American, Western) spread through media, commerce, and tourism, threatening minority languages and traditions',
       'Argument for strengthening: globalization enables minority cultures to reach global audiences — K-pop, Bollywood, Afrobeats gained global reach through global platforms',
       'Reality is complex: globalization simultaneously threatens some local cultures and amplifies others',
       'Key variable: whether a culture has the economic and technological resources to participate in globalization on its own terms'])],
    [('Heimler\'s History: APHUG Globalization and Culture','Cultural homogenization, glocalization, acculturation, and syncretism',_H+'globalization+cultural+change')],
    ['What is the difference between acculturation and assimilation?','Give an example of a syncretic cultural practice','How does glocalization differ from pure cultural homogenization?']),
  ],
  'unit_qs':[
   ('Explain how the spread of Christianity illustrates expansion diffusion rather than relocation diffusion.',
    ['Expansion diffusion: the trait spreads outward while remaining strong at origin — Rome, Jerusalem, Antioch remained Christian centers','Missionaries carried the faith outward without the origin population relocating','Hierarchical diffusion first: spread through Roman cities; then contagious diffusion to rural areas','Contrast with relocation diffusion (Buddhism leaving India) where the trait weakened at origin']),
   ('Compare the spatial distribution of Islam and Hinduism and explain why they differ.',
    ['Islam: global universalizing religion — concentrated in Middle East, North Africa, South/Southeast Asia, Sub-Saharan Africa','Hinduism: ethnic religion — almost entirely concentrated in South Asia (India, Nepal) with diaspora communities','Islam spread through trade routes, conquest, and missionary activity; Hinduism spread with Indian diaspora migration','The universalizing vs. ethnic distinction directly explains the spatial difference']),
   ('How does language serve as both a centripetal and centrifugal force within a country?',
    ['Centripetal: a shared official language unifies a country — people can communicate, creating national identity','Example: Mandarin standardization in China creates a single communicative community across diverse dialects','Centrifugal: minority language suppression creates resentment and separatist movements','Example: Catalan in Spain, Québécois French in Canada — linguistic minorities seeking political autonomy']),
   ('What is cultural hearth and give three examples of major cultural hearths and what diffused from them?',
    ['Cultural hearth: the source area from which a culture or innovation originates and diffuses','Mesopotamia (Fertile Crescent): agriculture, writing, urban civilization diffused outward','China: Buddhism, paper, printing, gunpowder diffused along Silk Road','Mesoamerica: maize agriculture, calendar systems diffused through the Americas']),
   ('Explain how the concept of sequent occupance helps geographers understand a city like Rome.',
    ['Sequent occupance: successive cultures leave visible layers of cultural landscape','Rome shows: ancient Roman temples and forums; early Christian churches built over Roman sites; medieval piazzas; Renaissance palaces','Each layer reflects a different cultural group and period — all visible simultaneously in the modern city','Geographers use sequent occupance to read landscape as historical text']),
   ('How does religion create sacred space and what conflicts can arise when multiple groups claim the same sacred space?',
    ['Sacred space: a location given religious significance — it becomes the focus of pilgrimage, ritual, and identity','Multiple claims arise when different religious traditions attach significance to the same site — Jerusalem\'s Old City','Conflict at Jerusalem: Jewish claim (Temple Mount), Muslim claim (Al-Aqsa Mosque on same site), Christian claim (Church of Holy Sepulchre nearby)','Political conflict becomes religious because controlling sacred space is seen as existential, not just territorial']),
   ('Explain how glocalization allows global companies to succeed in diverse cultural markets.',
    ['Glocalization: adapting global products to local cultural contexts — not imposing a single global standard','McDonald\'s success in India: vegetarian menu, no beef, local spices — respects Hindu dietary norms','Disney in Japan: Tokyo Disneyland adapted to Japanese culture — punctuality, cleanliness, kawaii aesthetics','Companies that glocalize outperform those that impose uniform global products in culturally distinct markets']),
   ('What is a lingua franca and why has English replaced French as the global lingua franca since the 20th century?',
    ['Lingua franca: a language used for communication between groups with different native tongues','French dominated diplomacy from 17th to early 20th century — European power balance centered on France','English replaced French after WWI and especially WWII — American economic and military dominance shifted linguistic power','American cultural exports (films, music, technology) and the internet cemented English as the global standard']),
   ('Explain how the post-colonial borders of Africa illustrate the geographic consequences of cultural geography being ignored.',
    ['Colonial borders drawn at Berlin Conference (1884–85) followed geometric lines, ignoring ethnic, linguistic, and religious distributions','Borders split ethnic groups (Somali people across four countries), created ethnically fragmented states (Nigeria: 250+ ethnic groups)','This created centrifugal forces — ethnic conflict, civil wars, separatist movements — in post-colonial African states','Example: the Yoruba, Igbo, and Hausa peoples were combined in Nigeria despite centuries of distinct cultural development']),
   ('Evaluate whether globalization is creating a global monoculture or a more complex multicultural world.',
    ['Evidence for monoculture: English dominance, American brands, Western media homogenize surface-level culture','Evidence for multiculturalism: diaspora communities preserve and revitalize home cultures globally; social media amplifies minority cultures','Reality: globalization creates simultaneous homogenization AND heterogenization — global brands coexist with local revival movements','Example: Welsh language revival (dying under English dominance) now thrives partly due to digital tools that globalization enabled']),
  ]},
]

# Units 4–7 continue in aphug part 2 — loaded as aphug_b.py
# To keep this file under safe output size, units 4–7 are in ap_content/aphug_b.py
