NAME = 'AP® U.S. History'
ABBREV = 'apush'
SLUG = 'ap-u-s-history'
COURSE_FILE = 'ap-u-s-history.html'
ACCENT_COLOR = '#c9a96e'

def _t(ti, co, mi, ht):
    return {'title': ti, 'content': co, 'misconception': mi, 'how_tested': ht}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, ext):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': ext}

UNITS = [
  {
    'num': 6,
    'title': 'Period 6: 1865–1898',
    'file': 'ap-u-s-history-6-period-6-1865-1898.html',
    'desc': 'Covers Gilded Age industrialization, the rise of big business, labor movements, immigration, the New South, Populism, and America\'s first overseas empire.',
    'gateway': [
        'How did industrialization transform American society and create new inequalities?',
        'What responses did workers, farmers, and immigrants develop to Gilded Age conditions?',
        'How did the New South mythology obscure post-Reconstruction realities?',
        'What motivated American imperialism in the 1890s?',
    ],
    'lessons': [
      _l('Industrialization and the Gilded Age',
        [
          _t('Rise of Big Business',
             'Gilded Age industrialists (Carnegie, Rockefeller, Morgan) used vertical integration, horizontal integration, and trusts to dominate industries; Social Darwinism and the Gospel of Wealth justified wealth concentration as natural and beneficial.',
             'Robber barons vs. captains of industry is a genuine historical debate—these men built transformative industries while engaging in exploitative practices; the APUSH exam expects you to evaluate both sides.',
             'LEQ evaluates whether Gilded Age industrialists helped or harmed American society.'),
          _t('Labor and the Worker',
             'Industrialization created dangerous working conditions, 12-hour days, and child labor; labor organizations (Knights of Labor, AFL under Gompers) sought better conditions; the Homestead Strike (1892) and Pullman Strike (1894) showed the limits of labor power against business and government.',
             'The federal government consistently sided with business over labor in this era—using courts, injunctions, and federal troops to break strikes.',
             'SAQ asks you to evaluate labor movement strategies and their effectiveness.'),
          _t('Social Darwinism and Reform Responses',
             'Social Darwinism (Herbert Spencer) applied natural selection to human society, justifying inequality as natural; the Social Gospel movement (Jane Addams, settlement houses) countered with Christian obligation to address poverty; the Mugwumps sought political reform against corruption.',
             'Social Darwinism was not Darwin\'s idea—Spencer applied evolutionary concepts to justify the status quo; Darwin himself did not endorse this application.',
             'DBQ uses Social Darwinist and reformer documents to analyze competing responses to industrialization.'),
        ],
        ['Vertical integration', 'Trust', 'Social Darwinism', 'Gospel of Wealth', 'Knights of Labor'],
        ['Compare Social Darwinism and the Social Gospel as responses to industrialization.',
         'Evaluate labor organizations\' strategies and their effectiveness.',
         'Analyze how big business practices concentrated economic power.'],
        ['LEQ evaluates Gilded Age industrialists as robber barons vs. captains of industry.',
         'SAQ evaluates labor movement strategies.',
         'DBQ uses competing reform documents.'],
        ['Compare Carnegie\'s "Gospel of Wealth" to Jane Addams\'s Hull House philosophy.',
         'Research the Homestead Strike and identify what it revealed about labor-business-government relations.'],
        [
          ('Andrew Carnegie\'s use of vertical integration in the steel industry means he',
           ['Merged with all other steel companies to eliminate competition', 'Controlled every stage of production from raw materials to finished product', 'Hired workers at every skill level from unskilled to management', 'Invested in steel companies across multiple countries']),
          ('The federal government\'s response to the Pullman Strike (1894) demonstrated that',
           ['The government supported workers\' right to strike', 'The government would use injunctions and federal troops to break strikes and protect business interests', 'President Cleveland was sympathetic to labor unions', 'The courts ruled in favor of workers\' organizing rights']),
          ('Social Darwinism justified economic inequality by arguing',
           ['That government should redistribute wealth to achieve social equality', 'That the struggle for survival naturally produced the fittest individuals at the top of society', 'That Christian charity required helping those at the bottom of society', 'That immigration was the primary cause of economic inequality']),
          ('The American Federation of Labor (AFL) under Samuel Gompers focused primarily on',
           ['Organizing all workers regardless of skill into one industrial union', 'Bread-and-butter issues: wages, hours, and conditions for skilled craft workers', 'Achieving socialist political transformation of the economic system', 'Organizing immigrant and female workers excluded from craft unions']),
          ('The Gospel of Wealth argued that wealthy industrialists had a responsibility to',
           ['Pay their workers higher wages to stimulate the economy', 'Use their surplus wealth for philanthropic purposes that benefited society', 'Invest their wealth in expanding their businesses further', 'Support labor unions as partners in economic growth']),
        ],
        ['https://www.youtube.com/watch?v=mn3-S4FHW5U'],
        ['What distinguished vertical from horizontal integration as business strategies?',
         'Why did the federal government side with business over labor during Gilded Age strikes?',
         'How did the Social Gospel movement challenge Social Darwinist justifications for inequality?']),

      _l('Immigration, Urbanization, and the New South',
        [
          _t('New Immigration and Nativism',
             'The "New Immigration" (1880s–1920s) brought millions from Southern and Eastern Europe (Italians, Poles, Jews) and Asia; nativists responded with the Chinese Exclusion Act (1882) and calls for literacy tests; immigrants settled in ethnic urban enclaves.',
             'The distinction between "old" (Northern/Western European) and "new" (Southern/Eastern European) immigration was a nativist construction used to justify restrictions—both groups faced discrimination.',
             'SAQ and DBQ use immigration documents and restriction debates to analyze nativist responses.'),
          _t('Urbanization and Political Machines',
             'Rapid urbanization created overcrowded tenements, inadequate sanitation, and political machines (Tammany Hall) that traded services for votes; Jacob Riis\'s How the Other Half Lives (1890) exposed urban poverty through photography and journalism.',
             'Political machines were corrupt but provided real services (jobs, housing assistance) to immigrant communities that government otherwise ignored—they were simultaneously exploitative and functional.',
             'MCQ and SAQ ask you to evaluate political machines\' role in immigrant communities.'),
          _t('The New South and Jim Crow',
             'New South advocates (Henry Grady) promoted industrial development while maintaining white supremacy; Jim Crow laws codified racial segregation after Reconstruction; Plessy v. Ferguson (1896) upheld "separate but equal," giving constitutional cover to segregation.',
             'The "New South" was economically still primarily agrarian and poor—industrialization lagged far behind the North despite boosters\' claims.',
             'LEQ evaluates the contrast between New South ideology and the reality of Black life under Jim Crow.'),
        ],
        ['New Immigration', 'Chinese Exclusion Act', 'Political machines', 'Jim Crow', 'Plessy v. Ferguson'],
        ['Analyze nativist responses to New Immigration using specific policies as evidence.',
         'Evaluate political machines as simultaneously exploitative and functional.',
         'Explain how Jim Crow and Plessy v. Ferguson constructed legal racial segregation.'],
        ['SAQ evaluates political machines\' role.',
         'DBQ uses immigration restriction and nativist documents.',
         'LEQ evaluates New South ideology vs. Jim Crow reality.'],
        ['Research Jacob Riis\'s photos and identify three specific conditions they documented.',
         'Compare Booker T. Washington\'s and W.E.B. Du Bois\'s responses to Jim Crow.'],
        [
          ('The Chinese Exclusion Act (1882) was significant primarily because',
           ['It was the first law restricting immigration based on national origin and race', 'It permanently ended all immigration to the United States', 'It applied only to Chinese railroad workers after completion of the transcontinental railroad', 'It was immediately ruled unconstitutional by the Supreme Court']),
          ('Political machines like Tammany Hall provided immigrant communities with',
           ['Legal advocacy against discriminatory employment practices', 'Jobs, housing assistance, and social services in exchange for political loyalty', 'Language education and citizenship preparation programs', 'Protection from anti-immigrant violence']),
          ('Plessy v. Ferguson (1896) most significantly affected African American civil rights by',
           ['Overturning the 14th Amendment\'s equal protection clause', 'Providing constitutional justification for racial segregation through "separate but equal"', 'Restricting Black voting rights in southern states', 'Upholding the Civil Rights Act of 1875']),
          ('Jacob Riis\'s How the Other Half Lives (1890) was significant primarily because',
           ['It proposed specific legislation to solve urban poverty', 'It used photography and journalism to expose urban tenement conditions to middle-class readers', 'It argued for restriction of immigration to solve urban overcrowding', 'It documented political machine corruption in New York City']),
          ('New South advocates like Henry Grady promoted industrial development while',
           ['Advocating for full political equality for Black Southerners', 'Maintaining white supremacy and racial hierarchy in the social and political order', 'Seeking Northern investment for Black-owned businesses', 'Rejecting the plantation agricultural system entirely']),
        ],
        ['https://www.youtube.com/watch?v=mn3-S4FHW5U'],
        ['What distinguished "new" from "old" immigration and why did nativists draw that distinction?',
         'How did Plessy v. Ferguson use the Constitution to protect racial segregation?',
         'What was the New South ideology and how did it coexist with Jim Crow?']),

      _l('Farmers, Populism, and the West',
        [
          _t('Western Settlement and Native Americans',
             'The Homestead Act (1862) promoted westward settlement; railroad expansion enabled agricultural commercialization; the destruction of the bison and the reservation system devastated Native peoples; Wounded Knee (1890) marked the end of organized Native resistance.',
             'The reservation system was designed to assimilate Native peoples, not preserve their cultures—the Dawes Act (1887) broke up tribal land to "civilize" individual Native families.',
             'SAQ and LEQ evaluate the impact of western expansion on Native peoples.'),
          _t('Farmers\' Problems and the Grange Movement',
             'Commercial farmers faced falling crop prices, rising railroad freight costs, credit problems, and deflation; the Grange movement organized farmers for political action; the Farmers\' Alliance and cooperatives sought collective solutions to market problems.',
             'Farmers\' economic problems were structural (global overproduction, railroad monopolies, credit scarcity), not due to individual failure—Populists correctly identified systemic causes.',
             'DBQ uses Populist documents to analyze agrarian reform arguments.'),
          _t('Populist Party and Election of 1896',
             'The People\'s (Populist) Party (1892) demanded a graduated income tax, government ownership of railroads, direct election of senators, and currency inflation (free silver); William Jennings Bryan\'s "Cross of Gold" speech united silver Democrats and Populists in 1896, but Bryan lost to McKinley.',
             'Bryan\'s 1896 defeat marked the end of significant agrarian political challenge to industrial capitalism—the alliance of eastern workers and western farmers never materialized.',
             'LEQ evaluates Populism\'s significance and why it ultimately failed.'),
        ],
        ['Dawes Act', 'Homestead Act', 'Populist Party', 'Free silver', 'Cross of Gold speech'],
        ['Analyze the impact of western expansion on Native peoples using the Dawes Act.',
         'Explain farmers\' structural economic problems and their organizational responses.',
         'Evaluate Populism\'s platform and explain why it failed in 1896.'],
        ['SAQ evaluates Native American policy.',
         'DBQ uses Populist documents.',
         'LEQ evaluates Populism\'s significance.'],
        ['Research Bryan\'s "Cross of Gold" speech and identify its main economic argument.',
         'Compare the Dawes Act\'s stated goals with its actual effects on Native communities.'],
        [
          ('The Dawes Act (1887) primarily aimed to',
           ['Protect Native American tribal land from railroad encroachment', 'Break up communal tribal land into individual family allotments to force assimilation', 'Expand the reservation system to include more Native territory', 'Grant full citizenship to all Native Americans immediately']),
          ('Farmers in the Gilded Age were most harmed economically by',
           ['High crop prices that led to overproduction', 'Falling crop prices, high railroad freight rates, and tight credit that squeezed profit margins', 'Lack of access to western lands due to railroad monopolies', 'Competition from cheap imported agricultural products']),
          ('William Jennings Bryan\'s "Cross of Gold" speech (1896) advocated for',
           ['Higher tariffs to protect American agriculture from foreign competition', 'Free coinage of silver to expand the money supply and help debt-burdened farmers', 'Government ownership of railroads to reduce freight costs', 'Graduated income tax to redistribute wealth from industrialists to farmers']),
          ('The Populist Party\'s demand for a graduated income tax was significant because',
           ['It had been proposed previously by both major parties', 'It challenged the Gilded Age assumption that wealth concentration was natural and beneficial', 'It was immediately adopted by Congress', 'It would only affect farmers and western residents']),
          ('Bryan\'s defeat in the 1896 election most directly resulted from',
           ['His inability to communicate his economic message clearly', 'Failure to attract eastern industrial workers who feared inflation would reduce their real wages', 'Republican voter fraud in key midwestern states', 'The Supreme Court ruling his platform unconstitutional']),
        ],
        ['https://www.youtube.com/watch?v=mn3-S4FHW5U'],
        ['How did the Dawes Act aim to "solve" the Native American question and what were its consequences?',
         'What structural economic forces made farming difficult in the Gilded Age?',
         'Why did the Populist coalition of farmers and workers fail in 1896?']),

      _l('American Imperialism in the 1890s',
        [
          _t('Causes of American Imperialism',
             'American imperialism in the 1890s was driven by: economic interests (new markets for surplus goods), strategic concerns (naval bases, coaling stations), Social Darwinism and the "White Man\'s Burden," and the Turner Thesis (frontier closure requiring new outlets for expansion).',
             'Imperialism was not simply economic—racial ideology (belief in Anglo-Saxon superiority) and strategic anxiety about global competition were equally important motivations.',
             'LEQ evaluates the relative importance of different causes of American imperialism.'),
          _t('Spanish-American War and Its Consequences',
             'The Spanish-American War (1898) began with the explosion of the USS Maine and yellow journalism stoking public opinion; the U.S. quickly defeated Spain, acquiring Puerto Rico, Guam, and the Philippines for $20 million; the Philippines acquisition triggered a brutal guerrilla war.',
             'The Philippines was not a passive acquisition—Filipino independence fighters (Emilio Aguinaldo) had fought Spain and expected independence, then fought the U.S. in the Philippine-American War (1899–1902) that killed hundreds of thousands.',
             'DBQ and SAQ use anti-imperialist and imperialist documents to analyze the debate over Philippine annexation.'),
          _t('Anti-Imperialism and Debate',
             'The Anti-Imperialist League (Mark Twain, Andrew Carnegie) argued that imperialism violated American democratic principles, the Constitution didn\'t follow the flag, and that governing subject peoples without consent contradicted the Declaration of Independence.',
             'Anti-imperialists were not necessarily allies of colonial peoples—some opposed imperialism for racist reasons (not wanting to incorporate nonwhite peoples as citizens), while others opposed it on democratic principle.',
             'DBQ uses anti-imperialist and imperialist writings to analyze competing visions of American identity and purpose.'),
        ],
        ['Yellow journalism', 'Spanish-American War', 'Philippine-American War', 'Anti-Imperialist League', 'Turner Thesis'],
        ['Identify and evaluate multiple causes of American imperialism in the 1890s.',
         'Analyze the Spanish-American War\'s origins and consequences, including the Philippine-American War.',
         'Compare imperialist and anti-imperialist arguments about Philippine annexation.'],
        ['LEQ evaluates imperialism causes.',
         'DBQ uses imperialist vs. anti-imperialist documents.',
         'SAQ analyzes Spanish-American War consequences.'],
        ['Read an excerpt from Alfred Thayer Mahan\'s The Influence of Sea Power on History.',
         'Research the Philippine-American War\'s scale and compare it to the Spanish-American War.'],
        [
          ('The Turner Frontier Thesis (1893) contributed to imperialist sentiment by arguing that',
           ['Americans needed to convert indigenous peoples to Christianity', 'The closing of the western frontier required finding new frontiers abroad for American expansion', 'America\'s democratic institutions should be exported to all nations', 'Naval power was essential to U.S. economic prosperity']),
          ('Yellow journalism\'s role in the Spanish-American War was primarily to',
           ['Report accurate news about Spanish atrocities in Cuba', 'Use sensationalized and often false stories to whip up public support for war with Spain', 'Expose American government lies about the USS Maine explosion', 'Build support for the Anti-Imperialist League\'s position']),
          ('The Philippine-American War (1899–1902) resulted from',
           ['Spanish military forces remaining in the Philippines after the Spanish-American War', 'Filipino independence fighters who had fought Spain expecting independence, not American rule', 'A German attempt to seize the Philippines from American control', 'A Philippine request for U.S. military assistance against Spain']),
          ('The Anti-Imperialist League argued against Philippine annexation primarily on the grounds that',
           ['The Philippines had no economic value for American commerce', 'Governing subject peoples without their consent violated American democratic principles', 'The Philippines was too far from the continental United States to defend', 'Spain still had legitimate claims to the Philippines']),
          ('Alfred Thayer Mahan\'s influence on American imperialism came primarily from his argument that',
           ['Continental expansion westward must continue into Canada', 'A powerful navy and overseas bases were essential to national power and economic prosperity', 'America should avoid all foreign entanglements as Washington had advised', 'Democratic values required the U.S. to liberate all colonized peoples worldwide']),
        ],
        ['https://www.youtube.com/watch?v=mn3-S4FHW5U'],
        ['What were the three main causes of American imperialism in the 1890s?',
         'How did the Philippine-American War contradict American stated ideals about the Spanish-American War?',
         'What was the strongest anti-imperialist argument against Philippine annexation?']),
    ],
    'unit_qs': [
      ('Social Darwinism justified Gilded Age inequality by arguing',
       ['That government should redistribute wealth to achieve fairness', 'That economic competition naturally elevated the fittest to the top of society', 'That Christian charity required wealthy individuals to support the poor', 'That industrial monopolies created more efficient economies']),
      ('The federal government\'s response to the Pullman Strike (1894) demonstrated',
       ['Support for workers\' right to organize and strike', 'Willingness to use injunctions and federal troops to break strikes and protect business', 'President Cleveland\'s neutrality between labor and business', 'Congressional support for labor union recognition']),
      ('Plessy v. Ferguson (1896) was most significant because it',
       ['Overturned the 13th Amendment\'s abolition of slavery', 'Gave constitutional cover to racial segregation through the "separate but equal" doctrine', 'Limited African Americans\' voting rights under the 15th Amendment', 'Required racial integration in public transportation']),
      ('The Populist Party\'s platform was most significant for',
       ['Achieving all its major reforms through the 1896 election', 'Articulating structural critiques of industrial capitalism that influenced later Progressive reforms', 'Uniting northern urban workers with southern and western farmers', 'Permanently ending the two-party system in American politics']),
      ('The Dawes Act (1887) primarily harmed Native Americans by',
       ['Forcibly removing them from their reservations to urban areas', 'Breaking up tribal communal lands and forcing individual land ownership, enabling land loss', 'Banning Native religious and cultural practices by federal law', 'Denying Native children access to any formal education']),
      ('Yellow journalism contributed to the Spanish-American War primarily by',
       ['Providing accurate reporting on Cuban suffering under Spanish rule', 'Using sensationalized stories to build public outrage and pressure for war with Spain', 'Exposing government lies about the USS Maine explosion', 'Supporting the Anti-Imperialist League\'s opposition to war']),
      ('The Anti-Imperialist League\'s strongest argument against Philippine annexation was',
       ['That the Philippines had no economic value', 'That governing subject peoples without consent contradicted American democratic ideals', 'That the Philippines was too distant to defend militarily', 'That annexation would provoke war with European powers']),
      ('Carnegie\'s vertical integration strategy most directly',
       ['Merged Carnegie Steel with all competitor companies', 'Controlled every stage of production from raw materials to finished product, reducing costs', 'Created a union of steel workers to negotiate wages collectively', 'Relied on government subsidies and tariffs for profitability']),
      ('The Homestead Act (1862) promoted western settlement by',
       ['Granting 160 acres of public land to settlers who farmed it for five years', 'Selling western lands at high prices to fund the Civil War', 'Reserving western lands exclusively for railroad companies', 'Granting land only to Civil War veterans']),
      ('Bryan\'s failure in the 1896 election most directly revealed',
       ['That farmers\' economic concerns were not legitimate', 'That the coalition of eastern workers and western farmers Populists sought could not be built', 'That the Democratic Party had permanently abandoned agrarian interests', 'That the monetary supply had no effect on agricultural prices']),
    ],
    'review_video': 'https://www.youtube.com/watch?v=DNOs1lHnHho',
  },

  {
    'num': 7,
    'title': 'Period 7: 1890–1945',
    'file': 'ap-u-s-history-7-period-7-1890-1945.html',
    'desc': 'Covers the Progressive Era, World War I, the 1920s, the Great Depression, the New Deal, and World War II.',
    'gateway': [
        'What problems did Progressives identify and how did they try to fix them?',
        'How did WWI transform America at home and abroad?',
        'What caused the Great Depression and how did the New Deal respond?',
        'How did WWII reshape American society and America\'s global role?',
    ],
    'lessons': [
      _l('The Progressive Era',
        [
          _t('Progressive Reform Goals',
             'Progressivism (1890s–1920s) sought to address industrial society\'s problems: regulating big business (Sherman Antitrust Act enforcement), protecting workers (labor laws), expanding democracy (direct election of senators, initiative/referendum), and social welfare (settlement houses, prohibition).',
             'Progressivism was not a unified movement—it included contradictions: championing democracy while supporting racist disfranchisement; promoting social welfare while imposing middle-class Protestant values.',
             'LEQ evaluates Progressive achievements and limitations.'),
          _t('Muckrakers and Reform',
             'Muckraking journalists exposed corruption and abuses: Ida Tarbell investigated Standard Oil, Upton Sinclair\'s The Jungle exposed meatpacking conditions, Lincoln Steffens documented municipal corruption; their work built public support for reform legislation.',
             'Sinclair\'s The Jungle was intended to build sympathy for workers but instead sparked outrage about contaminated food—he said he aimed for the public\'s heart but hit its stomach.',
             'DBQ uses muckraker documents to analyze Progressive reform motivations.'),
          _t('Progressive Amendments and Limits',
             'Constitutional amendments reflected Progressive goals: 16th (income tax), 17th (direct Senate election), 18th (Prohibition), 19th (women\'s suffrage); however, Progressivism largely excluded Black Americans—Theodore Roosevelt dis-invited Booker T. Washington from the White House after one dinner.',
             'The Progressive movement\'s racial exclusion was not incidental—many Progressives supported racial segregation as "scientific" and "progressive" based on eugenics.',
             'SAQ evaluates which groups were included in and excluded from Progressive reforms.'),
        ],
        ['Muckraking', 'Sherman Antitrust Act', '16th Amendment', '19th Amendment', 'Eugenics'],
        ['Identify specific Progressive reforms and evaluate their effectiveness.',
         'Analyze muckraking journalism\'s role in building reform support.',
         'Evaluate Progressive exclusions, especially racial limitations.'],
        ['LEQ evaluates Progressive achievements and limits.',
         'DBQ uses muckraker documents.',
         'SAQ evaluates Progressive racial exclusions.'],
        ['Research Ida Tarbell\'s Standard Oil investigation and its legislative result.',
         'List four Progressive Era constitutional amendments and explain what each accomplished.'],
        [
          ('Upton Sinclair\'s The Jungle (1906) most directly contributed to passage of',
           ['The Sherman Antitrust Act', 'The Pure Food and Drug Act and Meat Inspection Act', 'The 16th Amendment establishing the income tax', 'Child labor laws restricting factory employment of minors']),
          ('The 17th Amendment\'s direct election of senators was a Progressive reform because',
           ['Senators had previously been appointed by the president', 'State legislators who chose senators were often corrupted by business interests', 'The Senate had repeatedly blocked all Progressive legislation', 'Direct election would give labor unions more influence over Senate races']),
          ('Progressive Era eugenics demonstrated that Progressivism',
           ['Was universally committed to scientific advancement and human welfare', 'Could embrace racist "scientific" ideas while claiming to pursue social improvement', 'Was primarily a southern movement to maintain racial hierarchy', 'Consistently protected marginalized groups from discrimination']),
          ('Theodore Roosevelt\'s approach to trusts, called "trust busting," distinguished between',
           ['Legal and illegal corporations based on size', 'Good trusts that served the public and bad trusts that harmed competition and consumers', 'Foreign and domestic corporations in antitrust enforcement', 'Manufacturing trusts and financial trusts as separate categories']),
          ('The 19th Amendment (1920) was a Progressive Era achievement that',
           ['Granted suffrage to all women in the United States regardless of race', 'Formally granted white women suffrage while Black women in the South remained disenfranchised through Jim Crow', 'Had been unanimously supported by all Progressive reformers since Seneca Falls', 'Immediately transformed American political representation']),
        ],
        ['https://www.youtube.com/watch?v=j7v3_wmnEfI'],
        ['Which three muckrakers had the most significant legislative impact and why?',
         'How did the Progressive Era constitutional amendments reflect democratic reform goals?',
         'Why was the Progressive movement\'s racial exclusion a structural feature rather than an oversight?']),

      _l('World War I and the 1920s',
        [
          _t('U.S. Entry into WWI and Home Front',
             'The U.S. entered WWI in 1917 after German unrestricted submarine warfare and the Zimmermann Telegram; the war transformed the home front: the Espionage Act (1917) and Sedition Act (1918) suppressed dissent; the Great Migration accelerated as Black Americans moved north for factory jobs.',
             'WWI civil liberties suppression (prosecution of Eugene Debs, Schenck v. U.S.) set dangerous precedents; the Supreme Court ruled "clear and present danger" could limit free speech.',
             'SAQ evaluates civil liberties trade-offs during wartime.'),
          _t('Wilson\'s 14 Points and the Treaty of Versailles',
             'Wilson\'s 14 Points proposed a peace based on self-determination and a League of Nations; the Treaty of Versailles (1919) imposed harsh terms on Germany; the Senate rejected the treaty (Article X controversy); the U.S. returned to "normalcy" and isolation.',
             'The Senate did not reject the treaty because of isolationism alone—Henry Cabot Lodge had specific constitutional objections to Article X\'s collective security commitment.',
             'LEQ evaluates Wilson\'s idealism vs. European power politics in shaping the treaty.'),
          _t('1920s: Prosperity, Culture, and Tension',
             'The 1920s brought mass consumer culture (automobiles, radio, movies), the Harlem Renaissance, and women\'s new social roles (flappers); but also the Red Scare, Ku Klux Klan revival, immigration restriction (National Origins Act 1924), and Prohibition.',
             'The 1920s were not uniformly prosperous—farmers remained economically depressed throughout the decade, and rural/urban cultural conflict was intense.',
             'DBQ uses 1920s cultural documents to analyze tensions between tradition and modernity.'),
        ],
        ['Zimmermann Telegram', 'Great Migration', 'Wilson\'s 14 Points', 'League of Nations', 'Harlem Renaissance'],
        ['Explain U.S. entry into WWI and analyze home front civil liberties suppression.',
         'Evaluate Wilson\'s 14 Points and why the Senate rejected the Treaty of Versailles.',
         'Analyze 1920s cultural tensions between modernity and tradition.'],
        ['SAQ evaluates WWI civil liberties.',
         'LEQ evaluates Wilson\'s 14 Points and treaty.',
         'DBQ uses 1920s cultural documents.'],
        ['Research Schenck v. U.S. and explain the "clear and present danger" test.',
         'Compare the Harlem Renaissance to 1920s nativist movements as responses to cultural change.'],
        [
          ('The Zimmermann Telegram (1917) contributed to U.S. entry into WWI by',
           ['Proving Germany had attacked American shipping', 'Revealing a German proposal that Mexico attack the U.S. in exchange for territories', 'Showing Germany had violated U.S. neutrality by mining the Atlantic', 'Documenting German atrocities against Belgian civilians']),
          ('The Senate\'s rejection of the Treaty of Versailles primarily reflected',
           ['Complete American isolationism and opposition to any foreign involvement', 'Specific concerns about Article X\'s commitment to collective defense without Senate approval', 'Republican support for Germany against British imperialism', 'Opposition to Wilson\'s goal of self-determination for European peoples']),
          ('The Great Migration during WWI most directly resulted from',
           ['Federal government programs relocating Black families to northern cities', 'Economic opportunity in northern war industries and the desire to escape southern Jim Crow violence', 'The movement of southern agricultural work to northern states', 'Draft exemptions offered to Black workers in northern factories']),
          ('The Harlem Renaissance was significant primarily as',
           ['A federal government cultural program for Black artists', 'A Black artistic and intellectual movement affirming African American culture and challenging racial oppression', 'An exclusively musical movement centered on jazz and blues', 'A political movement seeking integration into mainstream white culture']),
          ('The National Origins Act (1924) reflected 1920s nativist sentiment by',
           ['Banning all immigration to the United States permanently', 'Setting immigration quotas that severely restricted Southern and Eastern European immigration', 'Restricting immigration only from Asian countries', 'Requiring all immigrants to pass English language tests']),
        ],
        ['https://www.youtube.com/watch?v=j7v3_wmnEfI'],
        ['What were Wilson\'s two specific goals for the peace and why did he fail to achieve them?',
         'How did the Great Migration transform both the South and northern cities?',
         'What tensions between tradition and modernity defined 1920s American culture?']),

      _l('Great Depression and the New Deal',
        [
          _t('Causes of the Great Depression',
             'The Great Depression (1929–39) resulted from multiple causes: overspeculation in the stock market, weak banking system, overproduction in agriculture and industry, high tariffs (Smoot-Hawley), and the Federal Reserve\'s contractionary monetary policy.',
             'The stock market crash (October 1929) did not cause the Depression—it was a symptom of deeper structural weaknesses; the Depression resulted from policy failures as much as market failures.',
             'SAQ asks you to evaluate multiple causes of the Great Depression.'),
          _t('Hoover\'s Response and FDR\'s New Deal',
             'Hoover believed in "voluntarism"—private charity rather than federal relief—and refused direct aid; FDR\'s New Deal (1933–39) used federal power for relief (FERA), recovery (NRA, AAA), and reform (FDIC, SEC, Social Security); the Second New Deal (1935) was more liberal.',
             'The New Deal did not end the Depression—WWII did; but it permanently expanded the federal government\'s role in the economy and created the modern social safety net.',
             'LEQ evaluates whether the New Deal was a radical departure or a conservative preservation of capitalism.'),
          _t('New Deal\'s Limits and Critics',
             'The New Deal excluded many Black Americans (AAA displaced sharecroppers, Social Security excluded domestic workers), faced criticism from the right (Liberty League) and left (Huey Long\'s Share Our Wealth), and FDR\'s court-packing plan (1937) damaged his coalition.',
             'The New Deal\'s racial exclusions were largely deliberate bargains with Southern Democratic congressmen whose support FDR needed—racial equality was traded for economic reform.',
             'DBQ uses New Deal documents and critic writings to analyze its successes and failures.'),
        ],
        ['Great Depression causes', 'New Deal', 'Social Security', 'FDR', 'Smoot-Hawley Tariff'],
        ['Analyze multiple causes of the Great Depression.',
         'Evaluate the New Deal as relief, recovery, and reform.',
         'Assess New Deal critics from left and right and explain FDR\'s racial compromises.'],
        ['SAQ evaluates Great Depression causes.',
         'LEQ evaluates New Deal as radical vs. conservative.',
         'DBQ uses New Deal and critic documents.'],
        ['Compare FDR\'s first and second New Deals in terms of goals and programs.',
         'Research why Social Security excluded domestic workers and agricultural workers in 1935.'],
        [
          ('The Great Depression was most directly triggered by',
           ['The stock market crash of 1929, which was the single cause of economic collapse', 'Multiple factors including overspeculation, weak banking, overproduction, and poor monetary policy', 'German reparations payments that disrupted global trade', 'The Smoot-Hawley Tariff alone, which caused global retaliation']),
          ('Hoover\'s response to the Depression differed from FDR\'s primarily in that Hoover',
           ['Believed federal direct relief would undermine self-reliance and favored voluntary private action', 'Opposed all government intervention in the economy on constitutional grounds', 'Believed the Depression would naturally resolve itself through market forces within months', 'Supported international trade agreements over domestic relief programs']),
          ('The New Deal\'s Social Security Act (1935) initially excluded domestic workers and agricultural laborers primarily because',
           ['These workers were already covered by state-level programs', 'Southern Democratic congressmen demanded exclusions to maintain control over Black workers', 'These occupations were too difficult to administer through a payroll tax system', 'Roosevelt believed these workers should be covered by private pensions']),
          ('FDR\'s court-packing plan (1937) most significantly damaged',
           ['The Supreme Court\'s ability to hear cases', 'FDR\'s political coalition and public trust by appearing to threaten judicial independence', 'The New Deal\'s legislative program in Congress', 'The Democratic Party\'s electoral prospects in the 1938 midterms']),
          ('The New Deal is best characterized as',
           ['A radical socialist restructuring of American capitalism', 'A pragmatic series of programs that expanded federal power while preserving capitalism', 'A conservative rejection of all government economic intervention', 'A coherent ideological program based on Keynesian economic theory']),
        ],
        ['https://www.youtube.com/watch?v=j7v3_wmnEfI'],
        ['What structural weaknesses made the U.S. economy vulnerable to the 1929 crash?',
         'How did FDR\'s "3 R\'s" framework (Relief, Recovery, Reform) structure the New Deal?',
         'Why did the New Deal exclude many Black Americans and what does this reveal about its politics?']),

      _l('World War II',
        [
          _t('U.S. Entry and Military Mobilization',
             'Japan\'s attack on Pearl Harbor (December 7, 1941) brought the U.S. into WWII; industrial mobilization transformed the economy, achieving full employment and massive production; the war required sacrifice (rationing, war bonds) but ended the Depression.',
             'The U.S. did not enter WWII purely for moral reasons—strategic interests (controlling the Pacific, preserving European allies) drove policy; moral condemnation of fascism and the Holocaust came later and incompletely.',
             'SAQ evaluates how WWII mobilization transformed the American economy and society.'),
          _t('Home Front: Women, Minorities, and Civil Liberties',
             'WWII opened new opportunities for women ("Rosie the Riveter") and Black Americans (Double V campaign—victory against fascism abroad and racism at home); but Japanese American internment (Executive Order 9066) and Korematsu v. U.S. showed civil liberties violations.',
             'Women\'s wartime work in factories was largely temporary—employers expected women to return home after the war; real structural change in women\'s workforce participation came later.',
             'LEQ evaluates WWII\'s contradictory impact on American civil liberties and minority rights.'),
          _t('Allied Strategy and Atomic Bombs',
             'Allied strategy prioritized Europe first (D-Day, June 6, 1944) while fighting Japan in the Pacific (island-hopping); the U.S. dropped atomic bombs on Hiroshima and Nagasaki (August 1945), ending the Pacific war; the bombs\' use remains debated.',
             'Truman\'s decision to use atomic bombs is genuinely debated—defenders cite invasion casualty projections, critics note Japan was near surrender and the bombs killed hundreds of thousands of civilians.',
             'DBQ uses documents about the atomic bomb decision to analyze competing historical interpretations.'),
        ],
        ['Pearl Harbor', 'Executive Order 9066', 'Double V campaign', 'D-Day', 'Atomic bomb decision'],
        ['Explain how WWII transformed the American economy and created new social opportunities.',
         'Evaluate WWII\'s contradictory impact on civil liberties through internment and minority service.',
         'Analyze debates over the atomic bomb decision using multiple perspectives.'],
        ['SAQ evaluates WWII home front transformation.',
         'LEQ evaluates WWII\'s civil liberties contradictions.',
         'DBQ uses atomic bomb decision documents.'],
        ['Research the Double V campaign and explain its dual goals.',
         'Compare the treatment of Japanese Americans with German Americans during WWII.'],
        [
          ('Executive Order 9066 (1942) authorized the internment of Japanese Americans primarily based on',
           ['Evidence of Japanese American espionage activities', 'Racial prejudice and wartime hysteria rather than demonstrated security threat', 'Congressional legislation requiring relocation of all Axis-nation immigrants', 'Supreme Court precedent from World War I']),
          ('The "Double V" campaign among Black Americans during WWII demanded',
           ['Double military service in exchange for citizenship rights', 'Victory against fascism abroad and victory against racial discrimination at home', 'Equal pay for Black soldiers and war workers', 'Integration of the U.S. military before fighting overseas']),
          ('WWII\'s most significant economic impact on the United States was',
           ['Creating the permanent welfare state through new social programs', 'Ending the Great Depression through massive military-industrial production and full employment', 'Making the U.S. permanently dependent on military spending for economic growth', 'Causing inflation that lasted through the 1950s']),
          ('Historians who defend Truman\'s decision to drop atomic bombs on Japan argue primarily that',
           ['Japan had no military capability to resist an American invasion', 'The bombs avoided a costly land invasion that would have killed far more people on both sides', 'The bombs were only aimed at military targets with minimal civilian casualties', 'Japan had been warned and had failed to surrender despite multiple opportunities']),
          ('"Rosie the Riveter" as a cultural symbol was significant because',
           ['It represented a permanent transformation in women\'s workforce participation', 'It promoted women\'s temporary wartime factory work, though women were largely expected to return home after the war', 'It was a government-sponsored campaign to permanently integrate women into industrial labor', 'It was created by women\'s rights activists to demand permanent workforce equality']),
        ],
        ['https://www.youtube.com/watch?v=j7v3_wmnEfI'],
        ['How did WWII end the Great Depression and what does that reveal about the Depression\'s causes?',
         'What was the Double V campaign and why was it significant for postwar civil rights?',
         'What are the strongest arguments for and against Truman\'s decision to drop atomic bombs?']),
    ],
    'unit_qs': [
      ('The Sherman Antitrust Act was most effectively used during the Progressive Era by',
       ['Congress, which expanded it to cover all corporations', 'Theodore Roosevelt, who selectively prosecuted "bad" trusts harming consumers', 'William Howard Taft, who refused to use it against any corporation', 'Woodrow Wilson, who eliminated it and replaced it with the FTC']),
      ('The Espionage and Sedition Acts (1917–18) most directly',
       ['Protected American civil liberties during wartime', 'Suppressed antiwar dissent, resulting in prosecution of socialists and labor leaders', 'Were immediately ruled unconstitutional by the Supreme Court', 'Applied only to foreign nationals living in the United States']),
      ('The Senate\'s rejection of the Treaty of Versailles most directly resulted in',
       ['American isolation from all European affairs', 'The weakening of the League of Nations by U.S. absence and a return to independent diplomacy', 'A second treaty that satisfied Senate concerns', 'Wilson\'s decision to submit to the Senate\'s specific reservations']),
      ('The Great Migration was most significant for African American history because',
       ['It ended racial discrimination in northern cities', 'It relocated millions of Black Americans from Jim Crow South to northern cities, creating new political power and cultural movements', 'It was organized by the NAACP as a political strategy', 'It permanently ended southern Black agricultural labor']),
      ('The New Deal\'s most lasting impact on American government was',
       ['Ending the Great Depression within two years of FDR\'s inauguration', 'Permanently expanding federal government\'s role in economic and social welfare', 'Establishing socialist economic planning as the basis of U.S. policy', 'Creating a balanced budget through progressive taxation']),
      ('Hoover\'s response to the Depression differed from FDR\'s primarily because Hoover',
       ['Believed government had no constitutional authority to address economic crises', 'Preferred voluntary private relief over direct federal assistance to protect self-reliance', 'Was ideologically opposed to all capitalism and sought a different system', 'Believed the Depression was caused by European financial instability beyond U.S. control']),
      ('Japanese American internment during WWII was most significant as a historical lesson about',
       ['The legitimate security threats posed by ethnic communities during wartime', 'How racial prejudice and wartime hysteria can lead to severe civil liberties violations', 'The effectiveness of preventive detention in protecting national security', 'The Supreme Court\'s consistent protection of civil liberties during wartime']),
      ('The Harlem Renaissance was most significant because it',
       ['Achieved immediate political rights for Black Americans', 'Created a flowering of Black artistic and intellectual expression that challenged racial oppression', 'Was funded by Progressive Era white philanthropists', 'Remained confined to New York City with no national influence']),
      ('The Smoot-Hawley Tariff (1930) worsened the Great Depression by',
       ['Causing the stock market crash of October 1929', 'Triggering retaliatory tariffs from trading partners, reducing global trade and deepening economic contraction', 'Increasing unemployment by making American exports too expensive', 'Causing hyperinflation that destroyed consumer purchasing power']),
      ('The atomic bomb\'s use in 1945 most immediately',
       ['Led to Germany\'s surrender ending the European theater', 'Ended the Pacific War and prevented a planned land invasion of Japan', 'Demonstrated the U.S. commitment to multilateral action through the UN', 'Created the Cold War by provoking Soviet nuclear weapons development']),
    ],
    'review_video': 'https://www.youtube.com/watch?v=NvwTfCaWK8s',
  },

  {
    'num': 8,
    'title': 'Period 8: 1945–1980',
    'file': 'ap-u-s-history-8-period-8-1945-1980.html',
    'desc': 'Examines the Cold War, postwar prosperity and social change, the Civil Rights Movement, the Great Society, and the social upheavals of the 1960s–70s.',
    'gateway': [
        'How did Cold War containment policy shape American foreign and domestic policy?',
        'How did postwar prosperity reshape American society and create new social tensions?',
        'How did the Civil Rights Movement achieve legal equality and what remained unfinished?',
        'What caused the social and political upheavals of the late 1960s–70s?',
    ],
    'lessons': [
      _l('Cold War Origins and Containment',
        [
          _t('Truman Doctrine and Marshall Plan',
             'The Truman Doctrine (1947) committed U.S. support to any nation threatened by communist expansion; the Marshall Plan ($13 billion to rebuild Western Europe) prevented economic desperation that communists might exploit; both reflected the containment strategy.',
             'Containment was not a military-first strategy—Kennan originally envisioned political and economic containment; the militarization of containment (NSC-68) was a later development.',
             'SAQ evaluates the Truman Doctrine and Marshall Plan as complementary containment strategies.'),
          _t('Korean War and McCarthyism',
             'The Korean War (1950–53) tested containment in Asia with 36,000 American deaths; McCarthyism (Senator Joseph McCarthy\'s anti-communist crusade) created a climate of fear and destroyed careers through unsubstantiated accusations; the Red Scare suppressed dissent.',
             'McCarthy did not start the Red Scare—it began before him with HUAC and loyalty oaths; McCarthy exploited an existing climate of fear and was eventually discredited by Edward R. Murrow\'s journalism.',
             'LEQ evaluates the domestic consequences of Cold War anti-communism.'),
          _t('Nuclear Deterrence and Korea-to-Vietnam',
             'Massive retaliation and mutual assured destruction (MAD) created Cold War stability through terror; the Vietnam War (1955–75) showed containment\'s limits—the U.S. committed 500,000 troops and lost to North Vietnamese forces, revealing overextension of containment logic.',
             'Vietnam was not primarily a military failure—U.S. forces won most military engagements; it was a political failure because the South Vietnamese government lacked legitimacy and popular support.',
             'DBQ uses Vietnam War documents to analyze containment\'s evolution and limits.'),
        ],
        ['Containment', 'Truman Doctrine', 'Marshall Plan', 'McCarthyism', 'Mutual assured destruction'],
        ['Explain containment strategy using Truman Doctrine and Marshall Plan as evidence.',
         'Evaluate the domestic consequences of Cold War anti-communism through McCarthyism.',
         'Analyze Vietnam as a test case for containment\'s limitations.'],
        ['SAQ evaluates Truman Doctrine and Marshall Plan.',
         'LEQ evaluates domestic consequences of anti-communism.',
         'DBQ uses Vietnam documents.'],
        ['Compare Kennan\'s original containment vision with NSC-68\'s militarized version.',
         'Research the Army-McCarthy hearings and explain how they ended McCarthy\'s influence.'],
        [
          ('The Truman Doctrine (1947) most directly committed the United States to',
           ['Providing military aid only to democratic governments', 'Supporting any nation threatened by communist expansion or internal communist movements', 'Rebuilding European economies to prevent communist political gains', 'Mutual defense with NATO members only']),
          ('McCarthyism\'s most significant harm to American society was',
           ['Identifying actual Soviet spies in the federal government', 'Creating a climate of fear that suppressed political dissent and destroyed careers through unsubstantiated accusations', 'Strengthening American military readiness against the Soviet Union', 'Unifying both political parties against the communist threat']),
          ('The Marshall Plan contributed to containment primarily by',
           ['Providing military equipment to Western European nations', 'Rebuilding Western European economies to reduce the appeal of communist parties', 'Creating a military alliance against Soviet expansion', 'Funding covert CIA operations against Soviet influence in Europe']),
          ('The Vietnam War demonstrated a limitation of containment theory because',
           ['U.S. forces were militarily defeated in every major engagement', 'Military success could not compensate for the South Vietnamese government\'s lack of popular legitimacy', 'Congress refused to fund the war adequately', 'The Soviet Union directly intervened with combat troops']),
          ('Mutual assured destruction (MAD) maintained Cold War stability through',
           ['Conventional military superiority that discouraged Soviet aggression', 'The certainty that any nuclear first strike would trigger a devastating retaliation, deterring both sides', 'U.S. nuclear superiority that gave it a decisive first-strike advantage', 'International treaties that verifiably eliminated nuclear weapons']),
        ],
        ['https://www.youtube.com/watch?v=DNOs1lHnHho'],
        ['How did the Truman Doctrine and Marshall Plan complement each other as containment strategies?',
         'How did McCarthyism demonstrate that Cold War anti-communism had domestic costs?',
         'Why did military success in Vietnam not translate to political victory?']),

      _l('Postwar Prosperity and Social Change',
        [
          _t('Baby Boom and Suburban Growth',
             'The postwar baby boom and GI Bill (education, mortgages) drove suburban growth; Levittown-style suburbs provided affordable homes for white middle-class families; the highway system (Interstate Highway Act, 1956) enabled suburban commuting but reinforced racial segregation.',
             'Suburban growth was racially exclusive—FHA loan policies and restrictive covenants denied mortgages to Black families, creating white suburbs and Black urban neighborhoods.',
             'SAQ asks you to analyze how postwar prosperity was unevenly distributed.'),
          _t('Conformity and Counter-Culture Seeds',
             'The 1950s featured cultural conformity pressure (corporate culture, suburban domesticity) but also seeds of dissent: Beat Generation (Kerouac, Ginsberg), early rock \'n\' roll, and youth culture challenging conformity; the decade\'s consensus masked deep tensions.',
             'The 1950s were not uniformly conformist—the decade saw enormous cultural ferment beneath the surface that erupted in the 1960s.',
             'LEQ evaluates the 1950s as an era of conformity vs. emerging dissent.'),
          _t('Eisenhower and the Military-Industrial Complex',
             'Eisenhower\'s Farewell Address (1961) warned against the "military-industrial complex"—the dangerous alliance between defense contractors and the military that could distort national priorities; his warning reflected his own experience managing Cold War defense spending.',
             'Eisenhower was not an anti-military isolationist—he expanded the nuclear arsenal significantly; his warning was about institutional capture, not military spending per se.',
             'DBQ may use Eisenhower\'s Farewell Address to analyze Cold War domestic effects.'),
        ],
        ['GI Bill', 'Levittown', 'Baby boom', 'Military-industrial complex', 'Interstate Highway Act'],
        ['Analyze how postwar prosperity was racially uneven.',
         'Evaluate 1950s conformity and emerging cultural dissent.',
         'Explain Eisenhower\'s warning about the military-industrial complex.'],
        ['SAQ evaluates uneven distribution of postwar prosperity.',
         'LEQ evaluates 1950s conformity.',
         'DBQ uses Farewell Address.'],
        ['Research FHA redlining practices and explain how they created segregated suburbs.',
         'Compare Levittown\'s racial policies with its affordability for white families.'],
        [
          ('The GI Bill\'s most significant limitation was that',
           ['It applied only to officers, not enlisted soldiers', 'It was formally race-neutral but implemented in racially discriminatory ways, excluding most Black veterans', 'It provided too little funding to enable actual college attendance', 'It was only available for two years after discharge']),
          ('The Interstate Highway Act (1956) most significantly contributed to',
           ['Urban renewal and revitalization of downtown areas', 'Suburban sprawl and white middle-class exodus from cities, reinforcing racial segregation', 'Public transportation development reducing automobile dependence', 'Economic integration between urban and rural communities']),
          ('Eisenhower\'s warning about the military-industrial complex primarily concerned',
           ['The Soviet Union\'s growing military capability', 'The dangerous influence of defense contractors on military and political decision-making', 'The nuclear arms race\'s potential for global destruction', 'Congressional underfunding of the conventional military']),
          ('The Beat Generation of the 1950s was significant primarily because',
           ['It achieved immediate political transformation of American society', 'It challenged 1950s conformity and materialism, planting seeds for 1960s counterculture', 'It represented mainstream American cultural values', 'It focused exclusively on racial equality rather than cultural experimentation']),
          ('The baby boom\'s most significant social consequence was',
           ['Creating immediate labor shortages in the postwar economy', 'Producing a massive generational cohort whose passage through life stages shaped each decade\'s culture and politics', 'Increasing demand for urban housing rather than suburban development', 'Reducing women\'s workforce participation permanently']),
        ],
        ['https://www.youtube.com/watch?v=DNOs1lHnHho'],
        ['How did FHA mortgage policies create racially segregated suburbs?',
         'What cultural tensions beneath 1950s conformity foreshadowed the 1960s?',
         'What specifically did Eisenhower warn about regarding the military-industrial complex?']),

      _l('Civil Rights Movement',
        [
          _t('Legal Strategies: Brown and the Courts',
             'The NAACP\'s legal strategy culminated in Brown v. Board of Education (1954), which overturned Plessy v. Ferguson and declared school segregation unconstitutional; Little Rock (1957) tested implementation when Eisenhower sent federal troops to enforce integration.',
             'Brown did not immediately integrate American schools—massive resistance, white flight to private schools, and de facto segregation through housing patterns meant integration was slow and incomplete.',
             'SAQ evaluates Brown v. Board\'s significance and limitations.'),
          _t('Direct Action: Montgomery to Birmingham',
             'The Montgomery Bus Boycott (1955–56), sit-ins, Freedom Rides, and Birmingham demonstrations used nonviolent direct action to expose southern segregation\'s brutality; televised images of police violence built northern white support for federal legislation.',
             'Martin Luther King Jr.\'s nonviolent strategy was deliberately provocative—it was designed to force a violent response that would expose segregation\'s reality to outside observers.',
             'DBQ uses Civil Rights Movement primary sources to analyze strategy and ideology.'),
          _t('Civil Rights Act, Voting Rights Act, and Beyond',
             'The Civil Rights Act (1964) banned racial discrimination in public accommodations and employment; the Voting Rights Act (1965) dismantled barriers to Black voting; but King\'s Chicago Campaign (1966) showed de facto northern segregation was harder to address than southern legal segregation.',
             'The Civil Rights Movement had a northern problem—de facto segregation through housing, schools, and employment discrimination could not be addressed by simple legal prohibition.',
             'LEQ evaluates the Civil Rights Movement\'s achievements and unfinished agenda.'),
        ],
        ['Brown v. Board', 'Montgomery Bus Boycott', 'Civil Rights Act of 1964', 'Voting Rights Act', 'Nonviolent direct action'],
        ['Trace the Civil Rights Movement from legal strategy to direct action.',
         'Evaluate Civil Rights legislation of 1964–65 and its limitations.',
         'Analyze why northern de facto segregation proved more resistant to civil rights strategies.'],
        ['SAQ evaluates Brown v. Board\'s significance.',
         'DBQ uses civil rights primary sources.',
         'LEQ evaluates movement achievements and unfinished agenda.'],
        ['Compare the NAACP\'s legal strategy to SNCC\'s direct action approach.',
         'Research the Civil Rights Act of 1964\'s major provisions and who opposed it.'],
        [
          ('Brown v. Board of Education (1954) was significant primarily because it',
           ['Immediately integrated all American public schools', 'Overturned Plessy v. Ferguson\'s "separate but equal" doctrine as inherently unequal', 'Was the first Supreme Court decision limiting racial discrimination', 'Applied to private schools and universities as well as public schools']),
          ('Nonviolent direct action strategies in the Civil Rights Movement were effective primarily because',
           ['They avoided all confrontation with law enforcement', 'They exposed southern segregation\'s brutality to national and international audiences through televised violence against peaceful protesters', 'They had the support of the Eisenhower administration from the beginning', 'They quickly converted most white southerners to support integration']),
          ('The Civil Rights Act of 1964\'s most significant provisions banned',
           ['Racial segregation only in public transportation', 'Racial discrimination in public accommodations, employment, and federally funded programs', 'All racial discrimination including in private housing', 'Literacy tests used to disenfranchise Black voters']),
          ('Martin Luther King Jr.\'s Chicago Campaign (1966) revealed that',
           ['Northern white liberals were fully committed to racial equality', 'De facto residential and school segregation in northern cities was resistant to civil rights strategies effective against legal southern segregation', 'Economic inequality rather than racial discrimination was the core issue', 'Nonviolent direct action was inappropriate for northern contexts']),
          ('The Voting Rights Act (1965) was necessary even after the 15th Amendment because',
           ['The 15th Amendment had been ruled unconstitutional in 1896', 'Southern states used literacy tests, poll taxes, and violence to systematically disenfranchise Black voters despite the amendment', 'The 15th Amendment only applied to federal elections, not state and local contests', 'Supreme Court rulings had limited the 15th Amendment\'s scope to northern states']),
        ],
        ['https://www.youtube.com/watch?v=DNOs1lHnHho'],
        ['How did nonviolent direct action build support for federal civil rights legislation?',
         'What was the strategic logic of the NAACP\'s legal approach before Brown?',
         'Why did civil rights strategies effective in the South struggle with northern de facto segregation?']),

      _l('Great Society, Vietnam, and Social Upheaval',
        [
          _t('LBJ\'s Great Society',
             'Lyndon Johnson\'s Great Society programs (1964–68) created Medicare, Medicaid, federal education funding (ESEA), the Voting Rights Act, and immigration reform (Hart-Celler Act); the War on Poverty used community action programs; this was the most ambitious domestic legislation since the New Deal.',
             'The Great Society was undermined by Vietnam War spending that created inflation and diverted political capital—LBJ\'s foreign policy destroyed his domestic legacy.',
             'LEQ evaluates the Great Society\'s achievements and limitations.'),
          _t('Vietnam War\'s Domestic Impact',
             'The Vietnam War created a "credibility gap" between government statements and reality; the antiwar movement grew from campus teach-ins to massive demonstrations; the My Lai massacre (1968) and Pentagon Papers (1971) confirmed the war\'s moral and strategic failures.',
             'The antiwar movement was not uniformly counter-cultural—it included veterans (Vietnam Veterans Against the War), mainstream liberals, and eventually the majority of the American public.',
             'DBQ uses antiwar movement and pro-war documents to analyze Vietnam\'s domestic divisions.'),
          _t('Social Movements of the Late 1960s-70s',
             'The late 1960s–70s saw second-wave feminism (NOW, Ms. magazine, Title IX), the Chicano Movement (César Chávez, United Farm Workers), American Indian Movement (AIM), and the gay rights movement (Stonewall 1969); these movements challenged traditional hierarchies and expanded rights claims.',
             'These movements were partly inspired by the Civil Rights Movement but also criticized its limitations—many questioned why their groups had been left out of mainstream civil rights gains.',
             'SAQ analyzes how late 1960s–70s social movements built on and extended civil rights traditions.'),
        ],
        ['Great Society', 'Medicare/Medicaid', 'Antiwar movement', 'Second-wave feminism', 'Title IX'],
        ['Evaluate the Great Society\'s major programs and how Vietnam undermined them.',
         'Analyze Vietnam War\'s domestic political consequences.',
         'Compare social movements of the 1960s–70s to the Civil Rights Movement.'],
        ['LEQ evaluates Great Society achievements and limitations.',
         'DBQ uses antiwar movement documents.',
         'SAQ compares social movements.'],
        ['List five Great Society programs and explain what each addressed.',
         'Research how the Hart-Celler Immigration Act of 1965 changed immigration patterns.'],
        [
          ('LBJ\'s Great Society programs most significantly expanded the federal government\'s role in',
           ['Military defense and foreign policy', 'Health care (Medicare/Medicaid), education funding, and poverty alleviation', 'Regulating corporate mergers and monopolies', 'Environmental protection and natural resource management']),
          ('The "credibility gap" during the Vietnam War referred to',
           ['The military capability gap between U.S. and North Vietnamese forces', 'The growing public distrust created by the difference between government claims and war realities', 'The cultural divide between antiwar protesters and pro-war supporters', 'Congressional skepticism about military requests for more troops']),
          ('Title IX (1972) was most significant for',
           ['Mandating racial integration in all federally funded educational programs', 'Prohibiting sex discrimination in federally funded education programs, dramatically expanding women\'s athletics', 'Guaranteeing equal pay for women in federally funded workplaces', 'Creating federal programs to recruit women into STEM fields']),
          ('The Stonewall Riots (1969) were significant primarily because',
           ['They were the first instance of LGBT Americans organizing politically', 'They sparked the modern LGBT rights movement by transforming resistance into political activism', 'They resulted in immediate decriminalization of homosexuality in New York', 'They were organized by the Democratic Party as a political strategy']),
          ('The Vietnam War\'s most significant long-term political consequence was',
           ['Permanent decline of the antiwar movement after 1975', 'Deep public skepticism toward government and military intervention (the Vietnam Syndrome)', 'Congressional reaffirmation of presidential war powers', 'The permanent dissolution of the Democratic Party coalition']),
        ],
        ['https://www.youtube.com/watch?v=DNOs1lHnHho'],
        ['How did Vietnam War spending undermine the Great Society\'s domestic programs?',
         'What was the "credibility gap" and how did it erode public trust in government?',
         'How did second-wave feminism build on but also critique the Civil Rights Movement?']),
    ],
    'unit_qs': [
      ('The Truman Doctrine committed U.S. foreign policy to',
       ['Military alliances only with democratic governments', 'Supporting nations threatened by communist expansion regardless of their democratic character', 'Economic aid programs rather than military assistance', 'Multilateral action through the United Nations only']),
      ('McCarthyism\'s most significant domestic legacy was',
       ['Exposing genuine Soviet espionage networks in the government', 'Creating a climate of political fear that suppressed dissent and civil liberties', 'Building bipartisan consensus against communism', 'Strengthening the FBI\'s counterintelligence capabilities']),
      ('Brown v. Board\'s immediate impact was limited primarily because',
       ['The Supreme Court lacked constitutional authority to enforce desegregation', 'White southern resistance and de facto segregation through housing patterns slowed actual integration', 'The Eisenhower administration opposed the ruling and refused to enforce it', 'The ruling only applied to Kansas, not all southern states']),
      ('The GI Bill\'s racial exclusion was most significant because',
       ['It created a generation of Black veterans with college degrees and homeownership', 'It denied most Black veterans the benefits that built white middle-class wealth, widening the racial wealth gap', 'It was overturned by the Civil Rights Act of 1964', 'It applied only to veterans who had served in segregated units']),
      ('LBJ\'s Great Society programs most significantly expanded',
       ['Military capabilities and defense spending', 'Federal government\'s role in health care, education, and poverty through Medicare, Medicaid, and ESEA', 'International aid and development programs', 'Environmental protection through the EPA']),
      ('Nonviolent direct action during the Civil Rights Movement worked primarily by',
       ['Avoiding all confrontation with white supremacist opposition', 'Provoking violent responses that exposed segregation\'s reality on national television', 'Building gradual white southern support for integration', 'Applying economic pressure through boycotts to bankrupt segregated businesses']),
      ('The Vietnam War\'s domestic political consequence was most significant for',
       ['Increasing public confidence in military judgment', 'Creating deep skepticism toward government and military intervention that shaped foreign policy for decades', 'Unifying Americans around anti-communist foreign policy goals', 'Strengthening presidential war powers over congressional opposition']),
      ('The Marshall Plan\'s most significant contribution to Cold War containment was',
       ['Providing military equipment to Western European nations', 'Rebuilding Western European economies to reduce communist parties\' appeal to desperate populations', 'Funding covert CIA operations against Soviet agents in Europe', 'Creating the NATO military alliance for collective defense']),
      ('Second-wave feminism of the 1960s–70s differed from first-wave feminism primarily in its focus on',
       ['Suffrage and voting rights as the primary goal', 'Broader social equality including workplace discrimination, reproductive rights, and cultural representation', 'Religious arguments for women\'s equality', 'International women\'s rights rather than domestic American issues']),
      ('The Voting Rights Act (1965) was necessary beyond the 15th Amendment because',
       ['The 15th Amendment had expired after 50 years', 'Southern states had systematically used legal tools (literacy tests, poll taxes) to disenfranchise Black voters despite the amendment', 'The 15th Amendment was ruled unconstitutional in 1896', 'Federal enforcement of the 15th Amendment required specific new legislation']),
    ],
    'review_video': 'https://www.youtube.com/watch?v=j7v3_wmnEfI',
  },

  {
    'num': 9,
    'title': 'Period 9: 1980–Present',
    'file': 'ap-u-s-history-9-period-9-1980-present.html',
    'desc': 'Examines the Reagan Revolution and conservative ascendancy, the end of the Cold War, economic globalization, and challenges facing the United States in the 21st century.',
    'gateway': [
        'What was the Reagan Revolution and how did it reshape American politics?',
        'How did the Cold War end and what was America\'s post-Cold War role?',
        'How did globalization and technological change transform American society?',
        'What major domestic challenges has the U.S. faced in the 21st century?',
    ],
    'lessons': [
      _l('Reagan Revolution and Conservative Ascendancy',
        [
          _t('Rise of the New Right',
             'The New Right coalition (Reagan 1980) united economic conservatives (tax cuts, deregulation), social conservatives (evangelical Christians opposing abortion and gay rights), and Cold Warriors; Reagan\'s "Morning in America" optimism contrasted with Carter\'s malaise.',
             'Reagan\'s coalition was not simply a white backlash to civil rights—it included genuine ideological commitments to free markets, limited government, and Cold War anti-communism.',
             'LEQ evaluates the causes and significance of the conservative ascendancy.'),
          _t('Reaganomics',
             'Reagan\'s economic program (supply-side economics/"trickle-down") cut top income tax rates from 70% to 28%, reduced social spending, increased military spending, and deregulated industries; the economy recovered after a 1982 recession but inequality grew significantly.',
             'Supply-side economics promised that tax cuts for the wealthy would "trickle down" to all Americans—critics note that while GDP grew, income inequality increased significantly during and after Reagan\'s presidency.',
             'SAQ evaluates Reaganomics using economic evidence.'),
          _t('Social Conservatism and Culture Wars',
             'The Moral Majority (Jerry Falwell) organized evangelical Christians politically around opposition to abortion, feminism, and gay rights; the culture wars produced intense social conflict over values, identity, and the role of religion in public life.',
             'The culture wars were not simply about social issues—they reflected deeper conflicts over what America was and whose values would define it.',
             'DBQ uses culture war documents to analyze competing visions of American identity.'),
        ],
        ['Supply-side economics', 'Reaganomics', 'Moral Majority', 'Culture wars', 'Deregulation'],
        ['Explain the New Right coalition\'s ideological components.',
         'Evaluate Reaganomics\' economic record and its impact on inequality.',
         'Analyze the culture wars as a conflict over American identity.'],
        ['LEQ evaluates conservative ascendancy causes.',
         'SAQ evaluates Reaganomics with economic evidence.',
         'DBQ uses culture war documents.'],
        ['Compare Reagan\'s economic record (GDP growth, income inequality, deficit) using statistics.',
         'Research Jerry Falwell\'s Moral Majority and identify its policy priorities.'],
        [
          ('The Reagan coalition united three main groups: economic conservatives, social conservatives, and',
           ['Labor unions seeking to protect workers from deindustrialization', 'Cold War hawks who opposed détente and favored confronting Soviet expansion', 'Civil rights advocates who supported Reagan\'s opposition to affirmative action', 'Environmentalists who supported Reagan\'s deregulation of industry']),
          ('Supply-side economics (Reaganomics) argued that cutting taxes on the wealthy would',
           ['Immediately reduce the federal deficit through reduced government spending', 'Stimulate investment that would create jobs and eventually benefit all Americans through growth', 'Primarily benefit the middle class rather than wealthy individuals', 'Fund increased social spending through economic growth']),
          ('The Moral Majority\'s significance for American politics was that it',
           ['Represented the first time religious groups had organized politically', 'Mobilized evangelical Christians as a reliable conservative voting bloc reshaping the Republican Party', 'Achieved immediate constitutional bans on abortion and gay rights', 'Appealed equally to Protestant and Catholic conservatives']),
          ('Reagan\'s economic record is most accurately described as',
           ['Achieving sustained economic growth while reducing inequality and the federal deficit', 'Producing GDP growth and economic recovery while significantly increasing income inequality and the national debt', 'Eliminating stagflation without any associated costs or trade-offs', 'Creating the longest peacetime economic expansion in American history without recession']),
          ('The culture wars of the 1980s–90s most fundamentally reflected',
           ['A conflict over specific policy outcomes like abortion law', 'Deep divisions over whose values would define American public life and national identity', 'A simple urban-rural divide with no ideological content', 'A continuation of the 1960s counterculture vs. mainstream conflict']),
        ],
        ['https://www.youtube.com/watch?v=NvwTfCaWK8s'],
        ['What were the three main components of the New Right coalition and how did they unite?',
         'What was the theory behind supply-side economics and what evidence challenges it?',
         'What issues defined the culture wars and why were they so politically divisive?']),

      _l('End of the Cold War and Post-Cold War America',
        [
          _t('Reagan\'s Cold War Policy and Soviet Collapse',
             'Reagan\'s massive military buildup and Reagan Doctrine (arming anti-communist guerrillas) pressured the Soviet Union; Gorbachev\'s reforms (glasnost, perestroika) unleashed forces that collapsed the USSR (1991); the Cold War ended not through military confrontation but Soviet internal collapse.',
             'Reagan\'s role in ending the Cold War is debated—internal Soviet contradictions and Gorbachev\'s reforms were arguably more important than U.S. military pressure.',
             'SAQ evaluates Reagan\'s role in the Cold War\'s end.'),
          _t('Gulf War and Post-Cold War Foreign Policy',
             'The Gulf War (1991) established a "new world order" of multilateral action under Bush; Clinton navigated a post-Cold War world with humanitarian interventions (Bosnia, Kosovo) but no clear strategic framework; the U.S. emerged as the sole superpower without a clear new foreign policy doctrine.',
             'The Gulf War\'s success created false confidence in U.S. military superiority—the "Powell Doctrine" of overwhelming force with clear objectives was not always followed in later conflicts.',
             'LEQ evaluates the challenges of U.S. foreign policy after the Cold War ended.'),
          _t('September 11 and the War on Terror',
             'The September 11, 2001 terrorist attacks reshaped U.S. foreign policy; the USA PATRIOT Act expanded surveillance; the invasions of Afghanistan (2001) and Iraq (2003) began costly wars; the Iraq War\'s justification (WMD) proved false, reviving Vietnam-era credibility gaps.',
             'The Iraq War was more consequential than 9/11 itself—it destabilized the Middle East, produced ISIS, and damaged U.S. credibility in ways that still shape global politics.',
             'DBQ uses post-9/11 policy documents to analyze foreign policy decisions.'),
        ],
        ['Reagan Doctrine', 'Soviet collapse', 'Gulf War', 'September 11', 'PATRIOT Act'],
        ['Evaluate Reagan\'s role in ending the Cold War using evidence.',
         'Analyze post-Cold War foreign policy challenges under Bush and Clinton.',
         'Assess the consequences of post-9/11 foreign policy decisions.'],
        ['SAQ evaluates Reagan\'s Cold War role.',
         'LEQ evaluates post-Cold War foreign policy.',
         'DBQ uses post-9/11 documents.'],
        ['Research the Bush "New World Order" speech and explain its foreign policy vision.',
         'Compare the Gulf War\'s multilateral approach to the Iraq War\'s unilateral approach.'],
        [
          ('The Soviet Union\'s collapse (1991) was most directly caused by',
           ['U.S. military superiority forcing Soviet surrender', 'Internal contradictions exposed by Gorbachev\'s reforms, which unleashed forces the system could not control', 'Reagan\'s Strategic Defense Initiative (Star Wars) making Soviet missiles obsolete', 'Soviet military defeat in Afghanistan ending their superpower status']),
          ('The Gulf War (1991) was significant in U.S. foreign policy history primarily because',
           ['It was the first time the U.S. used nuclear weapons since World War II', 'It demonstrated the effectiveness of multilateral coalitions and established Bush\'s "new world order" concept', 'It ended the Cold War by defeating a Soviet-backed military', 'It permanently resolved Middle Eastern instability']),
          ('The USA PATRIOT Act (2001) was controversial primarily because',
           ['It declared war on Afghanistan without congressional debate', 'It expanded government surveillance powers in ways critics argued threatened civil liberties', 'It authorized torture of terrorism suspects', 'It imposed martial law in New York City after 9/11']),
          ('The Iraq War\'s most damaging long-term consequence for U.S. foreign policy was',
           ['The financial cost of military operations exceeding $2 trillion', 'The failure to find WMD destroyed U.S. credibility and destabilized the region, contributing to ISIS\'s rise', 'The loss of Saudi Arabian oil access', 'Permanent alienation of all European allies']),
          ('Reagan\'s role in ending the Cold War is historically debated because',
           ['Soviet archives show Reagan had no military advantage over the USSR', 'Internal Soviet contradictions and Gorbachev\'s reforms may have been more decisive than U.S. pressure', 'Reagan actually wanted to maintain Cold War tension for political reasons', 'The Cold War did not actually end during Reagan\'s presidency']),
        ],
        ['https://www.youtube.com/watch?v=NvwTfCaWK8s'],
        ['What internal factors made the Soviet Union vulnerable to collapse in 1991?',
         'How did the Iraq War\'s WMD justification connect to earlier credibility gaps like Vietnam?',
         'What foreign policy doctrine, if any, guided U.S. action in the post-Cold War decade?']),

      _l('Economic Globalization and Domestic Inequality',
        [
          _t('NAFTA and Globalization',
             'NAFTA (1994) created a free trade zone among the U.S., Canada, and Mexico; globalization accelerated deindustrialization as manufacturing moved to low-wage countries; technology (internet, automation) disrupted labor markets; the benefits of globalization were unevenly distributed.',
             'Globalization\'s benefits (cheaper goods, corporate profits) were concentrated, while its costs (job loss, wage stagnation) were spread across specific communities and workers.',
             'LEQ evaluates globalization\'s economic and social consequences.'),
          _t('Inequality and the Great Recession',
             'Income inequality grew from the 1970s through the 2000s as wages stagnated for most workers while incomes soared for the top 1%; the 2008 Great Recession (caused by housing bubble and financial deregulation) produced the worst economic crisis since the Depression.',
             'The Great Recession\'s causes included deregulation decisions made by both parties over decades—blaming a single party or president misses the long-term structural causes.',
             'SAQ evaluates the causes and consequences of the 2008 financial crisis.'),
          _t('Technological Revolution and Social Change',
             'The internet, smartphones, and social media transformed communication, commerce, and politics; the "knowledge economy" rewarded education while displacing routine jobs; globalization and technology together restructured American labor markets in ways that increased inequality.',
             'Technology is not politically neutral—it has amplified existing inequalities while creating new opportunities; access to technology is itself unequally distributed.',
             'DBQ uses economic and technological change documents to analyze inequality\'s causes.'),
        ],
        ['NAFTA', 'Globalization', 'Great Recession', 'Deindustrialization', 'Knowledge economy'],
        ['Evaluate globalization\'s benefits and costs for different Americans.',
         'Analyze the Great Recession\'s causes and consequences.',
         'Assess how technological change has transformed American labor markets.'],
        ['LEQ evaluates globalization\'s consequences.',
         'SAQ evaluates Great Recession causes.',
         'DBQ uses economic change documents.'],
        ['Research one community affected by deindustrialization and document specific consequences.',
         'Compare the Great Recession to the Great Depression in terms of causes and government response.'],
        [
          ('NAFTA\'s most significant domestic consequence was',
           ['Creating millions of manufacturing jobs in U.S. border regions', 'Accelerating deindustrialization as manufacturing moved to lower-wage Mexico', 'Reducing the U.S. trade deficit with Canada and Mexico', 'Providing new export markets that offset manufacturing job losses equally']),
          ('Income inequality\'s growth from the 1970s to the 2000s was most directly caused by',
           ['Government welfare programs discouraging work', 'Wage stagnation for most workers combined with soaring incomes for the wealthiest, driven by technology, globalization, and tax policy', 'Immigration increasing labor supply and reducing wages', 'Educational attainment declining among American workers']),
          ('The 2008 Great Recession was most directly caused by',
           ['Federal deficit spending under the Bush administration', 'A housing bubble fueled by deregulated financial products and risky mortgage lending that collapsed, triggering a financial crisis', 'Oil price shocks following Hurricane Katrina in 2005', 'China\'s currency manipulation reducing U.S. export competitiveness']),
          ('The "knowledge economy" has most significantly',
           ['Created equal opportunities for all workers regardless of education', 'Rewarded highly educated workers while displacing those in routine jobs through automation', 'Eliminated manufacturing as a viable economic sector entirely', 'Reduced inequality by creating plentiful jobs across all skill levels']),
          ('Globalization\'s uneven distribution of benefits means that',
           ['No Americans benefit from global trade and investment', 'Benefits (cheap goods, corporate profits) are concentrated while costs (job loss, wage stagnation) are spread to specific communities', 'Rural Americans have benefited more than urban residents', 'Only college-educated workers are affected by global competition']),
        ],
        ['https://www.youtube.com/watch?v=NvwTfCaWK8s'],
        ['How did NAFTA affect different groups of Americans differently?',
         'What deregulatory decisions contributed to the 2008 financial crisis?',
         'How has technological change both expanded and limited economic opportunity?']),

      _l('21st Century Challenges and American Identity',
        [
          _t('Obama and Political Polarization',
             'Barack Obama\'s election (2008) as the first African American president reflected civil rights progress; his presidency saw passage of the Affordable Care Act but intense partisan polarization; the Tea Party movement reflected backlash to both Obama\'s policies and demographic change.',
             'Obama\'s presidency demonstrated both how far America had come on race and how far it had to go—his election did not usher in "post-racial America" as some claimed.',
             'SAQ evaluates what Obama\'s election and presidency reveal about race in contemporary America.'),
          _t('Immigration and Demographic Change',
             'The Hart-Celler Act (1965) transformed immigration sources from Europe to Latin America and Asia; the U.S. became increasingly diverse; debates over undocumented immigration, DACA, and border policy reflected anxiety about demographic and cultural change.',
             'Immigration debates conflate economic, cultural, and legal issues—separating them reveals that most economic evidence shows immigration benefits the economy, while cultural anxieties drive much of the political opposition.',
             'LEQ evaluates how immigration has shaped American identity debates.'),
          _t('21st Century Social Movements',
             'Black Lives Matter (2013) emerged to protest police violence; #MeToo (2017) addressed sexual harassment and assault; environmental justice movements connected climate change to racial and economic inequality; these movements used social media for unprecedented organizing.',
             'Social media amplified these movements\' reach but also created backlash communities—technology\'s role in social movements is complex and cuts both ways.',
             'DBQ uses 21st century social movement documents to analyze continuity and change in American reform traditions.'),
        ],
        ['Affordable Care Act', 'Tea Party', 'DACA', 'Black Lives Matter', '#MeToo'],
        ['Evaluate Obama\'s presidency and what it revealed about race in contemporary America.',
         'Analyze immigration\'s role in American identity debates.',
         'Compare 21st century social movements to earlier reform traditions.'],
        ['SAQ evaluates Obama\'s presidency and race.',
         'LEQ evaluates immigration and American identity.',
         'DBQ uses social movement documents.'],
        ['Research the Affordable Care Act\'s major provisions and political opposition.',
         'Compare Black Lives Matter\'s strategies to the 1960s Civil Rights Movement.'],
        [
          ('Obama\'s presidency most directly demonstrated that',
           ['Racial discrimination had been eliminated from American society', 'Significant racial progress had occurred while deep racial inequalities and tensions persisted', 'Democrats had achieved permanent majority status in American politics', 'The Civil Rights Movement had fully achieved its goals']),
          ('The Tea Party movement\'s rise during Obama\'s presidency reflected',
           ['Universal opposition to deficit spending regardless of which party proposed it', 'A combination of genuine fiscal conservatism, cultural anxiety about demographic change, and opposition to Obama\'s policies', 'Bipartisan grassroots concern about the Great Recession\'s economic impact', 'A libertarian movement seeking to reduce both military and social spending']),
          ('The Hart-Celler Immigration Act (1965) most significantly changed American immigration by',
           ['Dramatically increasing total immigration while maintaining European-dominated sources', 'Eliminating national origin quotas, shifting immigration sources from Europe to Latin America and Asia', 'Creating the DACA program for children of undocumented immigrants', 'Restricting immigration overall while prioritizing family reunification']),
          ('Black Lives Matter differed from the 1960s Civil Rights Movement primarily in its',
           ['Goals, which focused on economic equality rather than legal rights', 'Organizational structure—decentralized and social media-based rather than led by formal organizations like the NAACP', 'Opposition to nonviolent direct action as a strategy', 'Focus on international human rights rather than American domestic racism']),
          ('Immigration debates in the 21st century most fundamentally reflect',
           ['Purely economic concerns about job competition', 'Intertwined economic, cultural, and legal anxieties about who belongs in America and what it means to be American', 'Bipartisan consensus that current immigration levels are too high', 'Evidence that immigration primarily harms the American economy']),
        ],
        ['https://www.youtube.com/watch?v=NvwTfCaWK8s'],
        ['What did Obama\'s election and presidency reveal about the state of race in America?',
         'How did the Hart-Celler Act transform American demographics over 50 years?',
         'How have 21st century social movements used technology differently from earlier movements?']),
    ],
    'unit_qs': [
      ('Reaganomics\' most significant long-term consequence was',
       ['Eliminating the federal deficit through economic growth', 'Growing income inequality as tax cuts benefited the wealthy more than middle and lower-income Americans', 'Permanently ending inflation through tight monetary policy', 'Creating a manufacturing renaissance in the American Midwest']),
      ('The Soviet Union\'s collapse in 1991 most directly resulted from',
       ['U.S. military victories over Soviet forces in proxy wars', 'Internal contradictions exposed by Gorbachev\'s reforms, creating forces the Soviet system could not control', 'Economic sanctions that prevented Soviet food imports', 'Reagan\'s Star Wars missile defense system rendering Soviet missiles obsolete']),
      ('The 2008 Great Recession was most directly caused by',
       ['Excessive government spending under Bush creating economic imbalances', 'A housing bubble fueled by deregulated financial products collapsing and triggering a financial crisis', 'Globalization and Chinese competition destroying the American economy', 'Federal Reserve interest rate increases that burst the technology bubble']),
      ('NAFTA\'s most controversial consequence was',
       ['Increasing U.S. manufacturing employment in border regions', 'Accelerating the movement of manufacturing jobs to Mexico, devastating specific American communities', 'Increasing immigration from Mexico beyond what previous policy allowed', 'Creating a common currency between the U.S., Canada, and Mexico']),
      ('The culture wars of the 1980s–90s most fundamentally represented',
       ['A policy debate about specific legislation like abortion law', 'A deep conflict over whose values and what vision of America would define public life', 'A primarily regional conflict between the South and the North', 'An extension of Vietnam-era generational conflict']),
      ('Obama\'s presidency most significantly demonstrated',
       ['That racial discrimination in America had been overcome', 'That significant racial progress coexisted with persistent racial inequalities and political backlash', 'That Democrats could build a permanent governing majority', 'That African American candidates had no specific electoral challenges']),
      ('September 11\'s most lasting impact on American domestic policy was',
       ['Creating permanent bipartisan consensus on foreign policy', 'Expanding surveillance powers through the PATRIOT Act and establishing new national security structures', 'Unifying Americans behind a sustained foreign policy doctrine', 'Reducing civil liberties debates through universal support for security measures']),
      ('The Iraq War\'s most significant long-term consequence was',
       ['Successfully creating a stable democratic Iraq as a model for the region', 'Destabilizing the Middle East and damaging U.S. credibility through the false WMD justification', 'Permanently eliminating al-Qaeda as a terrorist threat', 'Building a lasting multilateral coalition of allies']),
      ('The Hart-Celler Immigration Act (1965) most significantly changed America by',
       ['Dramatically reducing total immigration to preserve American culture', 'Shifting immigration sources from Europe to Latin America and Asia, fundamentally transforming American demographics', 'Creating the first guest worker program for agricultural laborers', 'Restricting immigration only from countries without democratic governments']),
      ('Income inequality\'s growth since the 1970s most directly reflects',
       ['Government welfare programs discouraging work', 'Technological change, globalization, and tax policy creating gains concentrated among the wealthiest', 'Declining educational achievement among American workers', 'Immigration increasing labor supply and suppressing wages for all workers']),
    ],
    'review_video': 'https://www.youtube.com/watch?v=mn3-S4FHW5U',
  },
]
