NAME        = 'AP® Art History'
ABBREV      = 'arthistory'
SLUG        = 'ap-art-history'
COURSE_FILE = 'ap-art-history.html'
ACCENT_COLOR = '#c9a84c'

_Y = 'https://www.youtube.com/results?search_query=AP®+Art+History+'
_K = 'https://www.khanacademy.org/humanities/ap-art-history/'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 6,
        'title': 'Africa: 1100–1980 CE',
        'file': 'ap-art-history-6-unit-6-africa-1100-1980-ce.html',
        'desc': 'Court art, masks, architecture, and textiles of sub-Saharan African kingdoms and cultures.',
        'gateway': [
            'How does African court art express political and spiritual authority?',
            'What is the role of masks in African ritual performance?',
            'How do African textiles communicate identity and status?',
            'What assumptions about African art have Western scholars challenged?',
        ],
        'lessons': [
            _l('West African Court Art: Ife, Benin, and Great Zimbabwe',
               [_t('Ife and Benin Bronze Casting',
                    'The Yoruba kingdom of Ile-Ife (Nigeria, c. 1000–1400 CE) produced naturalistic copper-alloy portrait heads of rulers using lost-wax casting. The Benin kingdom (c. 1400–1897) continued this tradition with elaborate bronze plaques commemorating court ceremonies and the divine Oba (king).',
                    'Students assume Africa had no sophisticated metalworking; Ife and Benin casting rivals the best of Renaissance Europe in naturalism and technical mastery.',
                    'Describe lost-wax process; explain how Benin bronzes communicate royal power; compare Ife naturalism with contemporary European portrait conventions.'),
                _t('Great Zimbabwe and Architecture of Power',
                    'Great Zimbabwe (Zimbabwe, c. 1200–1450 CE) is the largest pre-colonial stone enclosure in sub-Saharan Africa, built by the Shona without mortar. Its granite walls restricted access to sacred royal space, communicating hierarchy through architecture.',
                    'Students confuse Great Zimbabwe with Egyptian structures; it is entirely African in origin built by the Shona people, not by Egyptians or outsiders.',
                    'Explain how architecture communicates hierarchy; analyze its political and spiritual functions; identify regional variation in African monumental architecture.')],
               [('lost-wax casting', 'Sculptural process where wax is modeled, encased in clay, burned out, and replaced with molten metal — used by Ife and Benin artists'),
                ('Oba', 'The divine king of the Benin Kingdom; central subject of bronze plaques and sculptures'),
                ('Benin bronzes', 'Bronze reliefs depicting court life and royal power that lined the pillars of the Oba\'s palace; looted by Britain in 1897'),
                ('Great Zimbabwe', 'Monumental stone enclosure (c. 1200–1450 CE) in southern Africa; political center of the Shona kingdom'),
                ('Kente cloth', 'Woven Asante textile of Ghana; specific patterns carry symbolic meanings related to history and identity')],
               ['Describe the lost-wax casting process', 'Explain how Benin bronzes communicated royal authority', 'Analyze Great Zimbabwe as an expression of political power'],
               ['Apply formal analysis to an Ife head', 'Explain why Great Zimbabwe\'s dry-stone technique is architecturally significant'],
               ['What functions did masks serve in African ritual performance?', 'How does Kente cloth communicate status and identity?'],
               [('The naturalistic Ife bronze portrait heads (Nigeria, c. 1000–1400 CE) are significant because they',
                 'demonstrate highly sophisticated lost-wax casting and naturalism equal to contemporary works in other world traditions',
                 ['were the first African metalworks ever created', 'were made by Portuguese craftsmen visiting the court', 'depict subjects in a deliberately abstracted non-naturalistic style']),
                ('Benin bronze plaques served the primary function of',
                 'commemorating and legitimizing royal power by depicting the Oba, court ceremonies, and military victories inside the palace',
                 ['recording trade transactions for Benin merchants', 'decorating public temples for communal worship', 'serving as currency in trade with Europeans']),
                ('Great Zimbabwe\'s granite walls were built using',
                 'dry-stone masonry — fitted stones without mortar — demonstrating advanced Shona architectural skill',
                 ['Egyptian-derived pyramid construction techniques', 'clay bricks fired in kilns', 'stones held together with iron rods']),
                ('Kente cloth communicates',
                 'specific meanings through woven patterns — different combinations signal historical events, proverbs, royal identity, and social status',
                 ['only the wearer\'s age and gender', 'purely aesthetic choices with no symbolic content', 'religious affiliation only']),
                ('African masks are typically understood as',
                 'activating spiritual forces when worn in performance — they are not static art objects but part of living ritual involving costume, music, and dance',
                 ['purely decorative objects carved for aesthetic appreciation', 'portraits of specific individuals', 'trade goods made for export to Europe'])],
               [('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Ife and Benin Bronze Casting', 'https://www.youtube.com/watch?v=t6Wc7OMks4U'),
                ('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Great Zimbabwe Architecture', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
               ['What does the production of Benin bronzes tell us about Benin\'s social organization?',
                'How does architecture establish hierarchy at Great Zimbabwe?',
                'Why did European scholars initially doubt African origins of these works?']),
        ],
        'unit_qs': [
            ('The Benin bronzes were looted by British forces in 1897 — this fact is relevant to art history because',
             'it raises questions of cultural patrimony, colonial violence, and the ethical responsibilities of museums holding objects taken by force',
             ['it proves the bronzes were made by Europeans', 'it has no relevance to formal analysis of the bronzes', 'it explains why the bronzes are no longer functional']),
            ('Nok terracottas (Nigeria, c. 500 BCE–200 CE) are significant as',
             'among the earliest known sub-Saharan figurative sculpture, showing sophisticated ceramic technique and possible ancestor veneration',
             ['the earliest African bronzes', 'colonial-period decorative objects', 'Egyptian-influenced imports']),
            ('The use of scarification in African cultures',
             'marks social transitions, group identity, and spiritual status — body art is as culturally significant as object-based art',
             ['is evidence of ritual with no artistic intent', 'was practiced only by lower-class members of society', 'was adopted from European colonial practices']),
            ('Dogon architecture (Mali) integrates cosmological principles because',
             'village layout mirrors the Dogon creation myth, with the toguna (meeting house) and granaries reflecting social and spiritual order',
             ['it uses Greek classical proportions', 'it has purely functional design with no symbolic content', 'it derives from Islamic architectural forms']),
            ('Asante goldwork (Ghana, c. 1700–present) used gold primarily to',
             'assert royal authority — the Asantehene\'s gold regalia, including the Golden Stool, symbolized the soul of the entire Asante nation',
             ['create currency for trade with Europeans', 'decorate religious temples', 'pay tribute to neighboring kingdoms']),
            ('African art was systematically misunderstood by early Western observers because',
             'colonial frameworks labeled non-Western art as "primitive," denying its sophistication, diversity, and context-specific meaning',
             ['it genuinely was simpler than European art in technique', 'African artists refused to explain their work to outsiders', 'Western museums refused to display African objects']),
            ('Dan masks (Liberia/Côte d\'Ivoire) demonstrate that',
             'a mask only fully functions in performance with costume, music, and dance — separating the mask as a static object loses its meaning',
             ['African masks are designed for permanent wall display', 'masks are purely secular decorative objects', 'the carved mask is the complete artwork with no performance component']),
            ('Kongo power figures (nkisi nkondi, Congo, c. 1800s) were used to',
             'activate spiritual contracts and oaths — each nail sealed an agreement, making the figure a receptacle of accumulated spiritual power',
             ['punish criminals through sympathetic magic', 'record historical events like a written document', 'mark graves of deceased community members']),
            ('The term "African art" is problematic because',
             'it homogenizes an enormous continent with thousands of distinct cultures, languages, and artistic traditions into a single misleading category',
             ['there are no significant differences between African art traditions', 'all African art forms derive from a single ancient tradition', 'African artists prefer not to have their work discussed academically']),
            ('West African brass casting traditions survived in the Americas via the slave trade, demonstrating',
             'that African artistic traditions persisted in diaspora contexts, informing Brazilian candomblé objects and Caribbean ironwork',
             ['African metalworking disappeared entirely after the slave trade', 'enslaved Africans had no opportunity to practice art forms', 'diaspora traditions have no connection to African originals']),
        ],
    },

    {
        'num': 7,
        'title': 'West and Central Asia: 500 BCE–1980 CE',
        'file': 'ap-art-history-7-unit-7-west-and-central-asia-500-bce-1980-ce.html',
        'desc': 'Art and architecture of the Persian Empire, Islamic civilizations, Ottoman Empire, and Mughal India.',
        'gateway': [
            'How did Islamic architecture adapt to function as a space for prayer?',
            'What role does calligraphy play in Islamic art?',
            'How did Mughal miniature painting combine Persian and Indian traditions?',
            'What distinguishes Achaemenid Persian art from other ancient empires?',
        ],
        'lessons': [
            _l('Persian and Islamic Art and Architecture',
               [_t('Achaemenid Persian Art and Persepolis',
                    'The Achaemenid Persian Empire (c. 550–330 BCE) created Persepolis as a ceremonial capital. Its apadana (audience hall) features processional reliefs depicting tribute bearers from across the empire — art as political propaganda communicating universal rule by synthesizing Babylonian, Egyptian, and Greek artistic traditions.',
                    'Students assume Persepolis was a military fortress; it was a ceremonial palace demonstrating the king\'s role as ruler of diverse peoples.',
                    'Identify Persian architectural features; explain how processional reliefs function as propaganda; compare Persian and Greek approaches to monumental art.'),
                _t('Islamic Architecture: Mosque Design and Ornament',
                    'The mosque (masjid) is organized around the qibla wall (facing Mecca), mihrab (prayer niche), and minaret (tower for call to prayer). Key examples: Dome of the Rock (Jerusalem, 691 CE); Alhambra (Granada, 1238–1358) with muqarnas, arabesque, and calligraphic decoration; Suleymaniye Mosque (Istanbul, 1550–1558).',
                    'Students assume all mosques look alike; there is enormous regional variation — Arab, Persian, Ottoman, and South Asian mosque designs differ significantly in layout and ornament.',
                    'Identify key components of a mosque; explain the function of each element; compare Ottoman and Moorish mosque design.')],
               [('apadana', 'Audience hall of an Achaemenid Persian palace, supported by tall columns with animal-capital tops'),
                ('mihrab', 'A niche in the qibla wall of a mosque indicating the direction of Mecca'),
                ('muqarnas', 'Decorative vaulting using small three-dimensional cells; creates a "stalactite" effect in Islamic architecture'),
                ('arabesque', 'Surface decoration in Islamic art using interlaced plant forms in geometric rhythm'),
                ('calligraphy', 'In Islamic art, the visual art of writing — especially Quranic verses — the highest art form due to its connection to the divine word'),
                ('Mughal miniature', 'Small-scale paintings of the Mughal court combining Persian, Indian, and European influences')],
               ['Identify the architectural components of a mosque and their functions', 'Explain how the Alhambra demonstrates Moorish Islamic art', 'Compare Achaemenid and Islamic approaches to monumental design'],
               ['Analyze the Dome of the Rock — why was it built on that specific site?', 'How do muqarnas serve both structural and decorative functions?'],
               ['What is the role of calligraphy in Islamic religious art?', 'How does the Alhambra differ from a European palace of the same period?'],
               [('The processional reliefs at Persepolis depict tribute bearers because',
                 'the artwork communicated Persian imperial ideology — diverse subjugated peoples presenting gifts demonstrates the king\'s claim to universal rule',
                 ['Persepolis was a commercial marketplace where tribute was collected daily', 'the reliefs were made by conquered peoples as a gift to Persia', 'the figures represent the Persian army in battle']),
                ('The Dome of the Rock (Jerusalem, 691 CE) is significant as',
                 'the earliest surviving Islamic monument and a statement of Islamic presence at a site sacred to Judaism and Christianity',
                 ['the first building to use a dome anywhere in the world', 'an exclusively Jewish monument later adapted by Muslims', 'a monument celebrating an Islamic military victory over Rome']),
                ('The Alhambra\'s interior decoration uses',
                 'geometric patterns, arabesque, and calligraphic inscriptions — creating meditative visual complexity based on infinite variation',
                 ['realistic fresco painting of Islamic rulers', 'landscape scenes on interior walls', 'narrative battle scenes celebrating military victories']),
                ('Calligraphy holds the highest status in Islamic art because',
                 'it visually embodies the word of God (Quran), making it a form of sacred art connecting the visual and the divine',
                 ['it is the only art form permitted by Islamic law', 'it is the most commercially valuable Islamic art form', 'it developed from Chinese calligraphy via the Silk Roads']),
                ('The minaret\'s primary function in Islamic religious practice is',
                 'to serve as a tower from which the muezzin calls Muslims to prayer five times daily',
                 ['to house the mosque\'s treasury and sacred objects', 'to provide a military lookout above the mosque', 'to store the imam\'s library of religious texts'])],
               [('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Islamic Architecture Overview', 'https://www.youtube.com/watch?v=t6Wc7OMks4U'),
                ('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Persepolis and Persian Art', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
               ['How did Persepolis communicate Persian imperial power through art and architecture?',
                'What makes the mosque a distinctive architectural type from a church or temple?',
                'How does Islamic art use pattern and geometry as spiritual expression?']),
        ],
        'unit_qs': [
            ('Mughal miniature painting (India, 16th–18th century) is notable for',
             'combining Persian painting traditions with Indian visual culture and European naturalism to create a hybrid court style',
             ['being purely Persian in style with no Indian influences', 'exclusively depicting religious Islamic subjects', 'using European oil painting techniques on canvas']),
            ('The Ottoman architect Sinan (1489–1588) is significant for',
             'perfecting the centralized domed mosque form in works like the Suleymaniye Mosque, improving upon the structural achievement of the Hagia Sophia',
             ['designing the Alhambra in Spain', 'introducing the minaret to Turkish architecture', 'building the Dome of the Rock in Jerusalem']),
            ('Persian carpet weaving is considered a major art form because',
             'it involves complex geometric and floral compositions, requires highly skilled labor, and served both functional and ceremonial purposes in royal courts',
             ['it is the only form of Persian art surviving from antiquity', 'rugs were purely functional with no artistic dimension', 'carpet design was introduced by European merchants']),
            ('The Topkapi Palace (Istanbul) collection includes Chinese porcelain because',
             'Chinese blue-and-white porcelain was highly prized by Ottoman rulers as luxury goods displaying cosmopolitan wealth and cross-cultural contact',
             ['Ottoman sultans conquered China and took the porcelain as tribute', 'the porcelain was made by Chinese artists living at the Ottoman court', 'Chinese and Ottoman ceramic traditions are identical']),
            ('The Great Mosque of Cordoba (Spain, 785–976 CE) demonstrates',
             'Umayyad adaptation of an earlier Visigothic church using a hypostyle hall with distinctive horseshoe arches and alternating red-and-white voussoirs',
             ['a completely original Islamic invention with no earlier influences', 'strict Ottoman mosque design exported to Spain', 'a building simultaneously used for Christian and Islamic worship']),
            ('Islamic book arts (illuminated manuscripts) demonstrate that',
             'figural illustration was practiced in secular Islamic contexts — the prohibition on figural representation applied primarily to religious spaces',
             ['Islamic law prohibited all figural illustration in any context', 'Islamic books contained no imagery, only text', 'all Islamic manuscripts were Quran copies without decoration']),
            ('The Achaemenid Persian synthesis of art traditions at Persepolis',
             'created a deliberate unified imperial visual vocabulary incorporating Babylonian, Egyptian, and Greek elements to communicate universal rulership',
             ['forced all conquered peoples to abandon their own art traditions', 'used only Persian-native artistic forms with no foreign influence', 'was entirely designed by Greek craftsmen hired by Darius']),
            ('Central Asian nomadic art (e.g., Scythian goldwork) is characterized by',
             'the "animal style" — interlaced animals and combat scenes rendered in portable precious metal objects suited to a mobile lifestyle',
             ['monumental stone architecture reflecting permanent settlement', 'ceramic traditions identical to Chinese porcelain', 'purely abstract geometric design with no animal imagery']),
            ('Analyzing Islamic art requires understanding',
             'its diversity across regions — Arab, Persian, Ottoman, Mughal, and Moorish traditions each developed distinct regional expressions of shared Islamic principles',
             ['applying a single universal rule to all Islamic art across all regions', 'ignoring regional variations as unimportant', 'treating Islamic art as unchanging from 600 CE to the present']),
            ('Tile revetment in Islamic architecture serves',
             'combined decorative and symbolic functions — geometric patterns suggest divine order and infinity, covering surfaces in immersive all-over pattern',
             ['a purely structural function of holding walls together', 'a narrative function depicting Islamic history', 'a commercial function identifying the building\'s patron']),
        ],
    },

    {
        'num': 8,
        'title': 'South, East, and Southeast Asia: 300 BCE–1980 CE',
        'file': 'ap-art-history-8-unit-8-south-east-and-southeast-asia-300-bce-1980-ce.html',
        'desc': 'Buddhist and Hindu art of South Asia, Chinese landscape painting, Japanese architecture, and Southeast Asian temple complexes.',
        'gateway': [
            'How does Buddhist art express the dharma through visual form?',
            'What is the significance of the Hindu temple as a sacred cosmic mountain?',
            'How did Chinese landscape painting develop a distinctive artistic philosophy?',
            'What makes Angkor Wat architecturally and symbolically distinctive?',
        ],
        'lessons': [
            _l('Buddhist, Hindu, and East Asian Art Traditions',
               [_t('Buddhist Art: Stupa and Sculpture',
                    'The Great Stupa at Sanchi (India, c. 300 BCE–100 CE) is a hemispherical reliquary mound with four carved gateways (toranas) depicting jataka tales. Early Buddhist art was aniconic — the Buddha\'s presence indicated by symbols (footprints, wheel, empty throne). The Gandharan style (1st–5th century CE) introduced anthropomorphic Buddha imagery through contact with Hellenistic traditions along the Silk Road.',
                    'Students assume the Buddha was always shown as a human figure; for centuries early Buddhist art used aniconic symbols only. Gandhara introduced figural representation under Greek influence.',
                    'Identify stupa components; explain the shift from aniconic to iconic Buddha representation; compare Gandharan and Mathura Buddha types.'),
                _t('Hindu Temple Architecture',
                    'The Hindu temple (mandir) houses a deity in its innermost sanctum (garbhagriha, "womb-chamber"). The Kandariya Mahadeva Temple (Khajuraho, India, c. 1025–1050 CE) has a curving tower (shikhara) representing Mount Meru. The erotic sculpture at Khajuraho reflects tantric theology — physical union symbolizing spiritual union with the divine.',
                    'Students are confused by erotic sculpture on Hindu temples; this imagery reflects tantric theology, not moral decadence.',
                    'Identify key components of a Hindu temple; explain the symbolic meaning of the shikhara; analyze the sculptural program at Khajuraho.')],
               [('stupa', 'A hemispherical Buddhist reliquary mound symbolizing the cosmos and enlightened mind'),
                ('torana', 'A carved gateway at a stupa depicting stories from the Buddha\'s lives'),
                ('garbhagriha', 'The innermost sanctuary of a Hindu temple — the "womb-chamber" housing the deity\'s image (murti)'),
                ('shikhara', 'The curving tower of a North Indian Hindu temple, representing Mount Meru'),
                ('Angkor Wat', 'A 12th-century temple complex in Cambodia dedicated to Vishnu; the world\'s largest religious monument'),
                ('darshan', 'In Hindu worship, the auspicious sight of a deity — the worshipper both sees and is seen by the god\'s image')],
               ['Describe the symbolic meaning of stupa components', 'Explain the Hindu concept of the temple as cosmic mountain', 'Compare Buddhist and Hindu architectural traditions'],
               ['How does Angkor Wat synthesize Hindu cosmology and Khmer royal authority?', 'Explain the role of the murti (divine image) in Hindu worship'],
               ['What is the function of the exterior sculptural program at Khajuraho?', 'How did Silk Road trade influence Buddhist art in Gandhara?'],
               [('Early Buddhist art avoided depicting the Buddha directly by using',
                 'aniconic symbols — the wheel (dharma), Bodhi tree, footprints, and empty throne',
                 ['using a written description instead of imagery', 'depicting the Buddha as a ray of light', 'showing only the Buddha\'s shadow on the ground']),
                ('The stupa\'s hemispherical form symbolizes',
                 'the cosmos — the dome represents the heavens, the finial the world axis, and circumambulation is an act of worship',
                 ['a secular burial mound with no symbolic meaning', 'the shape of the Buddha\'s shaved head', 'a military defensive structure']),
                ('The erotic sculptures at Khajuraho are interpreted as',
                 'expressing tantric theology — physical and spiritual union representing cosmic abundance and the creative force',
                 ['evidence of moral decadence in medieval Hindu society', 'scenes from the private life of the temple\'s patron', 'purely decorative imagery with no theological meaning']),
                ('Angkor Wat (Cambodia, 1113–1150 CE) is significant as',
                 'the world\'s largest religious monument — a Hindu temple complex dedicated to Vishnu that later became Buddhist',
                 ['the largest Buddhist monastery ever built', 'a Khmer military fortress converted to a temple', 'a replica of an Indian Hindu temple built by Indian architects']),
                ('The Gandharan Buddha shows Greek influence through',
                 'realistic facial features, wavy hair, and toga-like robe — a fusion of Hellenistic naturalism with Buddhist iconography',
                 ['depicting the Buddha seated in the lotus position', 'the use of the wheel as a dharma symbol', 'the use of bronze rather than stone'])],
               [('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Great Stupa at Sanchi', 'https://www.youtube.com/watch?v=t6Wc7OMks4U'),
                ('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Angkor Wat Architecture', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
               ['Compare the Great Stupa at Sanchi with the Kandariya Mahadeva Temple as different religious architectural types',
                'How did Greek influence travel to Buddhist art in Gandhara?',
                'What is the function of circumambulation at a stupa?']),
        ],
        'unit_qs': [
            ('Chinese landscape painting (shan shui) is distinctive for',
             'expressing the Confucian and Daoist relationship between humans and nature — tiny human figures dwarfed by vast mountains embody humility before the cosmos',
             ['accurate topographic mapping of specific landscapes', 'celebrating military victories in mountain campaigns', 'purely decorative scenes with no philosophical content']),
            ('Fan Kuan\'s "Travelers Among Mountains and Streams" (Song Dynasty, c. 1000 CE) places human figures',
             'in the lower corner, dwarfed by towering rock — conveying Daoist humility and the insignificance of humanity against the eternal natural world',
             ['at the center as the primary subject', 'at the top of the mountain in dominance', 'outside the frame entirely']),
            ('The Japanese Ise Grand Shrine is rebuilt every 20 years because',
             'Shinto values of purity, renewal, and the transmission of sacred craft knowledge make the act of building as sacred as the structure itself',
             ['Japanese climate prevents buildings lasting longer than 20 years', 'a Buddhist doctrine about impermanence requires periodic renewal', 'a political ceremony marks new imperial dynasties']),
            ('The Mogao Caves (Dunhuang, China, c. 400–1000 CE) are significant for',
             'preserving thousands of Buddhist wall paintings blending Indian, Central Asian, and Chinese influences along the Silk Road',
             ['representing the earliest Chinese art form with no foreign influence', 'serving as the official portrait gallery of Chinese emperors', 'being the only site where Buddhist art survives in China']),
            ('Borobudur (Java, Indonesia, c. 800 CE) is significant as',
             'the world\'s largest Buddhist monument — a mandala-shaped stupa with three symbolic levels that pilgrims ascend to reach nirvana symbolically',
             ['the earliest Buddhist monument in Southeast Asia', 'a Hindu temple later converted to Buddhist use', 'a royal palace that adopted Buddhist exterior decoration']),
            ('The Terracotta Army (Xi\'an, China, c. 210 BCE) was created to',
             'protect Emperor Qin Shihuangdi in the afterlife — thousands of individualized soldier figures reflecting belief in the continuation of imperial power after death',
             ['celebrate a military victory over nomadic invaders', 'be displayed publicly during the emperor\'s lifetime', 'serve as training mannequins for the actual imperial army']),
            ('Ukiyo-e prints (Japan, Edo period) influenced Western art through',
             '"Japonisme" — French Impressionists and Post-Impressionists (Monet, Van Gogh, Toulouse-Lautrec) adopted Japanese flat color, cropping, and subject matter',
             ['only Chinese artists who adapted them to landscape painting', 'European artists through direct trade of original paintings', 'no Western artists, as Japanese art was unknown in Europe before 1900']),
            ('Korean celadon ceramics (Goryeo Dynasty, c. 918–1392 CE) are notable for',
             'a distinctive jade-green glaze superior in refinement even to Chinese Song ceramics — an example of Korean mastery within a shared East Asian ceramic tradition',
             ['directly copying Chinese porcelain without modification', 'using techniques imported from Europe via the Silk Road', 'being exclusively for Buddhist ritual with no royal patronage']),
            ('Japanese Zen Buddhist art (dry rock gardens, ink monochrome painting) is characterized by',
             'reduction and simplicity — elimination of unnecessary elements to achieve direct experience of emptiness (mu) and the essence of nature',
             ['elaborate iconographic programs depicting the Buddha\'s life', 'symmetrical garden design modeled on Chinese imperial gardens', 'maximalist decoration celebrating divine abundance']),
            ('The Hindu concept of darshan means that the murti is',
             'treated as a living divine presence — the worshipper receives blessings by seeing and being seen by the god\'s image',
             ['a purely decorative object with no ritual function', 'used only in private meditation', 'a representation of the deceased ruler']),
        ],
    },

    {
        'num': 9,
        'title': 'The Pacific: 700–1980 CE',
        'file': 'ap-art-history-9-unit-9-the-pacific-700-1980-ce.html',
        'desc': 'Art of Polynesia, Melanesia, Australia, and indigenous Pacific cultures including moai, ta moko, and featherwork.',
        'gateway': [
            'How do Pacific island cultures use art to connect the living with their ancestors?',
            'What roles do body art and tattooing play in Pacific cultural identity?',
            'How do the Easter Island moai communicate chiefly authority?',
            'What is the significance of the Māori meeting house (wharenui)?',
        ],
        'lessons': [
            _l('Polynesian and Pacific Art Traditions',
               [_t('Easter Island Moai and Chiefly Power',
                    'The moai of Rapa Nui (Easter Island, c. 1100–1680 CE) are monolithic carved stone figures representing deified ancestors (aringa ora — "living faces"). Erected on stone platforms (ahu) facing inward to protect the community, their mana (spiritual power) was believed to bless the living.',
                    'Students assume moai were religious idols for worship; they are ancestor figures whose mana protects the living community.',
                    'Describe the function of moai as ancestor figures; explain the role of mana; analyze how moai communicate chiefly authority.'),
                _t('Māori Art: Ta Moko and the Wharenui',
                    'Māori culture of New Zealand expresses identity through ta moko (facial tattoo) encoding an individual\'s genealogy, rank, and achievements in a unique pattern. The wharenui (meeting house) is conceived as the body of an ancestor — ridge beam as spine, rafters as ribs — covered with carved panels (poupou) depicting ancestral narratives.',
                    'Students assume ta moko is merely decorative; it is a biographical text encoding genealogical information that others can "read" to understand the wearer\'s lineage.',
                    'Explain ta moko as biographical text; describe the wharenui as an embodied ancestor; compare Pacific concepts of art with Western fine art categories.')],
               [('moai', 'Monolithic ancestor figures carved from volcanic tuff on Easter Island, erected on stone platforms (ahu)'),
                ('mana', 'In Polynesian culture, spiritual power or authority — chiefs and ancestors possess mana transmittable through objects and images'),
                ('ta moko', 'Māori facial tattoo encoding genealogy, rank, and personal identity; each design is unique to the individual'),
                ('wharenui', 'A Māori meeting house conceived as the body of an ancestor; a central space for community gathering and ceremony'),
                ('tapa', 'Cloth made from beaten bark used across Polynesia for clothing, exchange, and ceremonial decoration'),
                ('malangan', 'Complex carved ceremonial objects of New Ireland (Papua New Guinea) made for mortuary feasts; destroyed after use')],
               ['Explain the meaning and function of the Easter Island moai', 'Describe the role of mana in Pacific art and material culture', 'Analyze ta moko as a form of biographical text'],
               ['How does the wharenui function as both architecture and ancestral body?', 'What role do Pacific textiles (tapa cloth) play in ceremonial exchange?'],
               ['What is "Pacific art" as a scholarly category, and how do scholars debate it?', 'How does body art in Pacific cultures function as identity marker?'],
               [('The Easter Island moai were erected facing inland because',
                 'they represent deified ancestors whose gaze protects the living community — their mana watches over the people below',
                 ['they were astronomical instruments tracking star movements', 'they were defensive fortifications against seaborne invaders', 'they were religious idols requiring face-to-face worship']),
                ('The Māori ta moko (facial tattoo) is best understood as',
                 'a biographical text encoding the wearer\'s genealogy, social rank, and achievements in a pattern unique to each individual',
                 ['purely decorative body art with no symbolic content', 'a punishment marking for criminals and outcasts', 'a religious symbol identical across all tribal members']),
                ('The wharenui (Māori meeting house) is conceptually significant because',
                 'the building is conceived as the body of an ancestor — entering the house is equivalent to entering an ancestor\'s embrace',
                 ['it was designed using European architectural principles brought by missionaries', 'it serves only functional purposes with no symbolic dimension', 'it represents the New Zealand landscape mapped onto an architectural form']),
                ('Malangan objects of New Ireland (Papua New Guinea) are significant because',
                 'they are made specifically for mortuary ceremonies and destroyed after use — their value lies in the act of making and ritual use, not in permanence',
                 ['they are the oldest surviving Pacific artworks preserved for centuries', 'they are purely decorative objects for permanent display', 'they are trade goods made for exchange with European collectors']),
                ('Tapa cloth in Polynesian cultures functioned as',
                 'a prestige material used in ceremonial exchange, clothing royalty, marking life transitions, and as a medium for geometric decoration',
                 ['a purely functional material with no ceremonial significance', 'currency used exclusively in economic trade', 'a material exclusively used for wrapping sacred objects'])],
               [('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Easter Island Moai', 'https://www.youtube.com/watch?v=t6Wc7OMks4U'),
                ('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Māori Art and Pacific Traditions', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
               ['How did Polynesian navigators use material culture in their Pacific voyaging tradition?',
                'What is the role of featherwork in Hawaiian royal identity?',
                'Why is the placement of moai on the ahu (stone platform) significant?']),
        ],
        'unit_qs': [
            ('Hawaiian feather cloaks (ʻahu ʻula) were significant because',
             'they displayed the ali\'i (chief\'s) mana through the use of rare, sacred feathers requiring immense labor and thousands of individually placed bird feathers',
             ['they were practical cold-weather garments with no symbolic function', 'they were purely decorative items made for trade with European sailors', 'they were worn by common people as everyday dress']),
            ('Aboriginal Australian Dreaming paintings are distinctive for',
             'mapping the sacred ancestral time/space encoded in land, narrative, and ceremony through abstract patterns that are simultaneously maps, stories, and sacred knowledge',
             ['being purely decorative art with no relationship to spiritual beliefs', 'representing realistic portraits of ancestral beings', 'being a recent invention created for tourist sale with no traditional basis']),
            ('Pacific art was largely excluded from Western art history until the late 20th century because',
             'Western art history classified Pacific objects as "artifacts" or "ethnographic objects" rather than "art," denying their aesthetic significance',
             ['Pacific cultures did not create objects with artistic intent', 'Pacific art was genuinely unknown to Western scholars before 1900', 'Pacific artists themselves rejected the category of "art"']),
            ('Marshall Islands stick charts represent',
             'encoded geographic knowledge — ocean swell patterns and island positions using sticks and shells in patterns navigators memorized rather than carried at sea',
             ['purely decorative objects with no navigational function', 'religious maps of the spirit world', 'trade goods exchanged with other Pacific island cultures']),
            ('Asmat bis poles (Papua New Guinea) are significant because',
             'they honor the recently deceased and simultaneously call for revenge — combining ancestor veneration with social conflict resolution',
             ['they are permanent architectural elements of Asmat buildings', 'they are trade goods made for export to neighboring cultures', 'they are decorative carvings with no ceremonial function']),
            ('The concept of tapu (taboo) in Polynesian culture is relevant to art because',
             'certain objects, materials, or spaces are made sacred and restricted — art and material culture mark the boundary between the sacred and the ordinary',
             ['tapu applies only to persons, never to objects', 'all Pacific objects are tapu with equal levels of restriction', 'tapu is a legal system unrelated to spiritual practice']),
            ('Comparing Pacific art across Melanesia, Polynesia, and Micronesia reveals',
             'significant diversity of traditions despite geographic proximity — different relationships to ancestry, ritual, exchange, and visual expression characterize each sub-region',
             ['a single unified "Pacific style" shared across all island groups', 'that all Pacific traditions derived from a single Polynesian origin culture', 'that Melanesian and Polynesian art are indistinguishable in style']),
            ('Australian bark painting (Arnhem Land) demonstrates',
             'a living artistic tradition encoding Dreaming stories in cross-hatching (rarrk) patterns that simultaneously decorate and communicate sacred geographical and cosmological knowledge',
             ['a commercial art form invented in the 1960s for tourist markets', 'purely secular decoration with no connection to Dreaming narratives', 'a technique borrowed from Papuan New Guinean artists']),
            ('Contemporary Pacific artists reclaiming traditional forms are',
             'reinterpreting indigenous traditions in contemporary contexts — addressing colonialism, indigenous identity, and diaspora in global art venues',
             ['abandoning traditional forms entirely in favor of Western contemporary art', 'reproducing traditional objects exactly without any modification', 'working only within traditional communities rather than internationally']),
            ('The Abelam yam culture of Papua New Guinea demonstrates that',
             'agricultural practice can itself be an artistic and ritual act — growing ceremonially important giant yams displays spiritual power, blurring the boundary between art and life',
             ['yam cultivation is purely agricultural with no artistic or ritual dimension', 'the primary Abelam art form is ceramic yam containers', 'yam fibers are the main Abelam prestige textile material']),
        ],
    },

    {
        'num': 10,
        'title': 'Global Contemporary: 1980 CE–Present',
        'file': 'ap-art-history-10-unit-10-global-contemporary-1980-ce-present.html',
        'desc': 'Contemporary art in a global context: identity, postcolonialism, installation, digital media, and the expanding definition of art.',
        'gateway': [
            'How do contemporary artists challenge the boundaries of what art can be?',
            'What is the role of identity (race, gender, culture, diaspora) in contemporary art?',
            'How has globalization changed where art is made and exhibited?',
            'What is postcolonial art criticism and why does it matter?',
        ],
        'lessons': [
            _l('Contemporary Art: Identity, Globalization, and New Media',
               [_t('Identity and Postcolonial Art',
                    'Contemporary art since the 1980s has centered on questions of identity: race (Jean-Michel Basquiat, Kara Walker, Kerry James Marshall), gender and sexuality (Cindy Sherman, Zanele Muholi), diaspora and postcolonialism (Yinka Shonibare, Cai Guo-Qiang, El Anatsui). These artists use appropriation, photography, installation, and performance to challenge Western art historical canons and address ongoing legacies of colonialism.',
                    'Students assume contemporary art is purely conceptual with no craft; many contemporary artists possess exceptional technical skill alongside conceptual depth.',
                    'Analyze the use of identity in contemporary art; explain postcolonial critique; describe how artists use non-traditional media to challenge art historical assumptions.'),
                _t('Installation Art, Biennials, and Digital Media',
                    'Installation art creates immersive environments the viewer inhabits — examples include Judy Chicago\'s "The Dinner Party" (1974–1979), Kara Walker\'s "A Subtlety" (2014), and Ai Weiwei\'s "Sunflower Seeds" (2010). International biennials (Venice, São Paulo, Gwangju) have created a global infrastructure for contemporary art. Digital art (net art, AI art, NFTs) raises new questions about originality and authorship.',
                    'Students assume the art world is centered exclusively in New York and London; since the 1990s, biennials across Asia, Africa, and Latin America have shifted the art world\'s geography.',
                    'Describe the biennial as an art world institution; explain what installation art demands of its viewer; analyze how digital art challenges definitions of the art object.')],
               [('installation art', 'An art form creating an immersive three-dimensional environment for the viewer to inhabit; often site-specific and temporary'),
                ('appropriation', 'The use of pre-existing imagery, objects, or styles in new artworks, often to critique or recontextualize the original'),
                ('postcolonialism', 'A critical framework examining the cultural and artistic legacies of European colonialism'),
                ('biennial', 'A large-scale international contemporary art exhibition held every two years; Venice Biennale (est. 1895) is the oldest'),
                ('diaspora art', 'Art by artists living outside their ancestral homeland, often negotiating between multiple cultural identities'),
                ('NFT', 'Non-fungible token — a blockchain-based certificate of ownership for a digital artwork; raises questions of originality and value')],
               ['Explain how contemporary artists use identity as subject matter', 'Analyze the significance of international biennials for global art', 'Describe what installation art demands of the viewer'],
               ['How does Kara Walker use the silhouette form to address American racial history?', 'What is Ai Weiwei\'s significance as both artist and political dissident?'],
               ['Is digital art "real" art? What criteria should we use to evaluate it?', 'How does the art market influence what we consider great contemporary art?'],
               [('Jean-Michel Basquiat\'s paintings (1980s New York) are significant for',
                 'combining graffiti, African-American experience, art history, and social critique in a neo-expressionist style that challenged the predominantly white art market',
                 ['introducing abstract expressionism to American art', 'being the first artist to exhibit street art in a gallery', 'creating purely decorative paintings with no political content']),
                ('Kara Walker\'s large-scale silhouettes address',
                 'the history of American slavery and racial violence — using the decorative silhouette form to depict traumatic scenes, creating jarring contrast between elegant form and brutal content',
                 ['the experience of African immigration to the United States in the 20th century', 'the history of abstract painting in America', 'the Victorian silhouette tradition without political commentary']),
                ('International biennials have shifted contemporary art by',
                 'creating a global platform presenting non-Western artists alongside Western artists — decentralizing New York and London as sole arbiters of important art',
                 ['concentrating all important contemporary art in Western European cities', 'replacing national museums as the primary exhibition venue', 'focusing exclusively on emerging artists under 30']),
                ('Installation art differs from traditional painting and sculpture in that it',
                 'implicates the viewer\'s body in the work — the viewer inhabits the space rather than observing from outside',
                 ['uses no physical materials, existing only as concept', 'is always temporary and never documented', 'must fill an entire building to qualify as installation']),
                ('El Anatsui\'s (Ghana) metal tapestries made from liquor bottle caps are significant because',
                 'they reference the history of the alcohol trade in colonial Africa while using a postcolonial material in a form referencing both African textiles and Western abstract painting',
                 ['they represent purely formal exploration of color with no historical content', 'they were made using unmodified traditional Ghanaian metalworking techniques', 'the bottle caps are used only for color and texture with no historical meaning'])],
               [('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Contemporary Identity Art', 'https://www.youtube.com/watch?v=t6Wc7OMks4U'),
                ('https://www.youtube.com/watch?v=t6Wc7OMks4U', 'Global Contemporary Art and Biennials', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
               ['What is "global contemporary art" — and who gets to define it?',
                'How does Yinka Shonibare use Dutch wax-print fabric to address colonialism?',
                'What questions does AI-generated art raise about authorship and creativity?']),
        ],
        'unit_qs': [
            ('The "global turn" in contemporary art since the 1990s means',
             'art history now must account for artists from Asia, Africa, Latin America, and the Pacific as equal contributors — not as "world art" footnotes to a Western-centered narrative',
             ['Western artists have begun adopting non-Western styles as primary inspiration', 'contemporary art is now made exclusively outside Europe and America', 'the art market has declined in New York and London']),
            ('Cindy Sherman\'s "Untitled Film Stills" (1977–1980) are significant for',
             'using photography and self-portraiture to critique how cinema and media construct images of femininity — Sherman plays multiple stereotyped female roles, exposing their artificiality',
             ['being honest documentary photographs of women in everyday situations', 'critiquing the film industry\'s casting practices through interviews', 'celebrating classic Hollywood femininity as a positive cultural ideal']),
            ('Ai Weiwei\'s art and activism are inseparable because',
             'his work directly challenges Chinese government authority — "Sunflower Seeds," "Remembering," and his documentation of earthquake deaths constitute both art and political action',
             ['he creates purely formalist art with no political content', 'his activism occurs entirely outside his artistic practice', 'he works exclusively within Chinese government-approved institutions']),
            ('The concept of "cultural appropriation" is debated in contemporary art because',
             'it raises questions about who has the right to use symbols and traditions from cultures not their own — distinguishing respectful exchange from exploitative borrowing',
             ['all cultural exchange in art is automatically appropriation regardless of context', 'appropriation is universally celebrated as a sign of cultural exchange', 'it applies only to commercial mass media, not fine art']),
            ('Zanele Muholi\'s photographic portraits (South Africa) are significant for',
             'documenting and celebrating Black LGBTQ+ identity in South Africa — creating a counter-archive against invisibility and violence, grounding art in human rights',
             ['using classical European portrait traditions without modification', 'documenting South African wildlife and landscape', 'working exclusively in abstract photography']),
            ('The rise of street art (Banksy, Shepard Fairey) as a recognized art form has',
             'challenged gallery-system gatekeeping — demonstrating that artistic value and political critique can exist outside institutional validation in public space',
             ['been universally condemned by art institutions as mere graffiti', 'resulted in street artists permanently abandoning public spaces for galleries', 'proven that only formally trained artists can produce meaningful public art']),
            ('Postcolonial art criticism asks us to consider',
             'how Western museums, art history, and the market have systematically excluded, misrepresented, or appropriated non-Western art — and what reparative histories we need to tell',
             ['whether art from colonized regions is technically sophisticated enough for Western museums', 'how contemporary art movements derived from African and Asian traditions', 'whether postcolonial countries should develop entirely separate art histories']),
            ('Yinka Shonibare\'s use of Dutch wax-print fabric is a postcolonial critique because',
             'the fabric — marketed as "African" — was industrially produced in the Netherlands for African markets; using it exposes the fabricated nature of cultural identity under colonialism',
             ['the fabric is an authentic pre-colonial Yoruba handwoven textile', 'Shonibare uses it as a tribute to Dutch-African trade relations', 'the choice of fabric is purely aesthetic with no political implications']),
            ('The debate about NFTs and digital art in art history centers on',
             'questions of originality, authenticity, authorship, and the role of scarcity in creating value — the same questions Duchamp\'s readymades raised in 1917',
             ['whether digital art can ever have aesthetic value', 'the environmental impact of blockchain technology exclusively', 'whether digital artworks can be physically touched']),
            ('A postmodern approach to art history is characterized by',
             'skepticism toward master narratives, recognition of multiple equally valid traditions, attention to power relationships in what gets displayed, and questioning of aesthetic absolutes',
             ['celebrating the superiority of Western artistic achievement over all other traditions', 'returning to Renaissance ideals of beauty and proportion', 'rejecting all interpretation of art in favor of purely formal description']),
        ],
    },
]
