NAME        = 'AP® Art History'
ABBREV      = 'arthistory'
SLUG        = 'ap-art-history'
COURSE_FILE = 'ap-art-history.html'
ACCENT_COLOR = '#c9a84c'

_Y = 'https://www.youtube.com/results?search_query=AP®+Art+History+'
_K = 'https://www.khanacademy.org/humanities/ap-art-history/'

COURSE_QS = [
    ('Formal analysis in art history involves',
     'describing and analyzing the visual elements (line, shape, color, space, texture, composition) and principles of design',
     ['researching the historical context and patronage only', 'identifying the artist\'s biography', 'listing the date and medium']),
    ('Iconography in art history is the study of',
     'subject matter, symbols, and the meaning of imagery in works of art',
     ['the physical materials used to create a work', 'the stylistic evolution of an artist\'s career', 'the provenance and ownership history of works']),
    ('The Venus of Willendorf (c. 28,000–25,000 BCE) is significant because it',
     'is one of the earliest known examples of representational art, possibly associated with fertility or female identity',
     ['is the first painted image in human history', 'was created using advanced metalworking techniques', 'depicts a named historical figure']),
    ('The Great Pyramids at Giza (c. 2550–2490 BCE) functioned as',
     'royal tombs for pharaohs, designed to facilitate the king\'s journey to the afterlife and demonstrate royal power',
     ['temples for public religious worship', 'astronomical observatories', 'administrative centers for the Egyptian empire']),
    ('The Parthenon (Athens, 447–432 BCE) exemplifies the Classical Greek ideal of',
     'harmonia (harmony), proportion, and idealized human form through its mathematical ratios and sculptural program',
     ['raw naturalism and individual portraiture', 'Hellenistic emotional expressiveness', 'Byzantine spiritual abstraction']),
    ('Roman art and architecture differed from Greek by emphasizing',
     'realistic portraiture, narrative historical relief, and engineering innovations (arch, vault, concrete)',
     ['idealized human perfection and mythological subjects only', 'abstract non-representational decoration', 'small-scale portable objects exclusively']),
    ('The term "linear perspective" (developed in the Renaissance) refers to',
     'a mathematical system of depicting three-dimensional space on a flat surface using converging lines meeting at a vanishing point',
     ['the use of overlapping figures to suggest depth', 'a system of symbolic colors representing spiritual hierarchy', 'painting figures smaller in the foreground']),
    ('The Hagia Sophia (Istanbul, 532–537 CE) is architecturally significant for',
     'its massive dome appearing to float on a ring of windows, creating an ethereal interior space for Byzantine worship',
     ['its pointed Gothic arches and flying buttresses', 'its strict adherence to Greek temple proportions', 'being the first church built in the Roman Empire']),
    ('Ukiyo-e prints in Japanese art (Edo period) depicted',
     'the "floating world" — subjects like kabuki actors, courtesans, and landscapes, produced as affordable woodblock prints',
     ['imperial court ceremonies and royal portraits exclusively', 'religious Buddhist imagery for temple use', 'battle scenes commissioned by samurai patrons']),
    ('The development of the Gothic cathedral in medieval Europe was enabled by',
     'the ribbed vault and flying buttress, which redirected structural forces and allowed thinner walls with large stained glass windows',
     ['Roman concrete construction techniques', 'Islamic tilework and decorative patterns', 'Byzantine mosaic programs']),
    ('African art is often "functional" in the sense that',
     'many objects serve ritual, ceremonial, or social purposes (masks, figures, thrones) rather than being purely aesthetic',
     ['African art has no aesthetic dimension', 'all African objects are made for sale to outsiders', 'African art is always abstract with no recognizable imagery']),
    ('The Aztec Sun Stone (Coyolxauhqui Stone, Tenochtitlan, c. 1500 CE) represents',
     'a cosmological and calendrical monument depicting Aztec creation myth and timekeeping',
     ['a legal code inscribed in stone', 'a map of the Aztec Empire', 'a portrait of the ruling emperor']),
    ('The "hierarchy of scale" in ancient and medieval art refers to',
     'depicting more important figures larger than less important ones, regardless of physical distance or spatial logic',
     ['using perspective to make distant figures smaller', 'showing divine beings at the top of the composition always', 'a rule that all figures must be the same size']),
    ('Impressionist painters (e.g., Monet, Renoir, 1860s–1880s France) were revolutionary for',
     'capturing momentary light, atmosphere, and everyday scenes with loose, visible brushwork rather than polished academic finish',
     ['using geometric abstraction to eliminate all realistic representation', 'depicting only mythological and historical subjects', 'reviving medieval gold-leaf techniques']),
    ('The term "avant-garde" in early 20th-century art history refers to',
     'artists who pushed boundaries ahead of mainstream taste, experimenting with new styles (Cubism, Fauvism, Dada, Surrealism)',
     ['conservative artists defending academic traditions', 'art critics who evaluated exhibitions', 'patrons who funded new art movements']),
    ('In Islamic art and architecture, figural representation is often avoided in religious contexts in favor of',
     'geometric patterns, arabesque (floral interlace), and calligraphy (the word of God)',
     ['narrative fresco cycles depicting prophet stories', 'portrait sculpture of religious leaders', 'landscape painting of sacred sites']),
    ('The Baroque style (17th century) is characterized by',
     'dramatic use of light and shadow (chiaroscuro), emotional intensity, movement, and theatrical compositions',
     ['geometric simplicity and flat, even lighting', 'strict adherence to classical Greek proportions', 'abstract rejection of all figurative imagery']),
    ('Frida Kahlo\'s self-portraits are important in 20th-century art history because they',
     'explore personal identity, bodily trauma, Mexican cultural heritage, and gender through a Surrealist-influenced style',
     ['established the principles of American Abstract Expressionism', 'introduced photography as fine art in Mexico', 'rejected all political content in favor of pure form']),
    ('The readymade, pioneered by Marcel Duchamp (e.g., "Fountain," 1917), challenged art history by',
     'proposing that any ordinary object becomes art when designated as such by the artist, questioning authorship and aesthetics',
     ['showing that industrial manufacturing could produce beautiful objects', 'celebrating craft and skilled technique', 'reviving ancient classical sculpture traditions']),
    ('Postmodern art (1970s–present) is distinguished from modernism by',
     'its embrace of appropriation, irony, pastiche, and questioning of the "grand narratives" of progress and originality',
     ['strict adherence to pure abstraction without reference to mass culture', 'rejecting all technology and industrial materials', 'return to strict figurative realism']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

def _unit(num, title, filename, desc, gateway_pts, lesson_title, topic_title, topic_content, topic_mis, topic_ht, vocab_list, objectives, ht_list, practice_list, questions, exit_list, unit_qs_list):
    return {
        'num': num,
        'title': title,
        'file': filename,
        'desc': desc,
        'gateway': gateway_pts,
        'lessons': [_l(lesson_title,
                       [_t(topic_title, topic_content, topic_mis, topic_ht)],
                       vocab_list, objectives, ht_list, practice_list, questions,
                       [('Why We Study Art — Crash Course Art History', topic_title+' AP® Art History', 'https://www.youtube.com/watch?v=t6Wc7OMks4U')],
                       exit_list)],
        'unit_qs': unit_qs_list,
    }

UNITS = [
    _unit(1, 'Global Prehistory: 30,000–500 BCE',
          'ap-art-history-1-unit-1-global-prehistory-30-000-500-bce.html',
          'The earliest human art from cave paintings to megalithic monuments and prehistoric figurines.',
          ['What does early art tell us about human cognition and culture?',
           'How do we interpret objects without written records?',
           'What themes recur across prehistoric cultures (fertility, animal imagery, death)?',
           'How do Stonehenge and Lascaux differ in function and context?'],
          'Prehistoric Art Overview',
          'Cave Paintings and Early Figurines',
          'Cave paintings at Lascaux (France, c. 17,000 BCE) and Altamira (Spain, c. 14,000 BCE) feature animals and handprints made with mineral pigments; they may relate to ritual, storytelling, or marking territory.',
          'Students assume cave paintings were purely decorative; evidence suggests ritual or shamanistic purposes, though we cannot know with certainty.',
          'Describe formal qualities of a work; explain potential cultural function; compare prehistoric works across regions.',
          [('Lascaux', 'Cave site in France with Paleolithic paintings of horses, aurochs, and other animals (c. 17,000 BCE)'),
           ('Venus of Willendorf', 'Small limestone figurine (c. 28,000–25,000 BCE) with exaggerated female features; possible fertility symbol'),
           ('megalith', 'Large stone used in prehistoric monument construction; from Greek "megas" (great) + "lithos" (stone)'),
           ('Stonehenge', 'Prehistoric monument in England (c. 3000–1500 BCE); aligned with solstices; likely ceremonial and funerary')],
          ['Describe formal elements of prehistoric art', 'Propose theories about function of cave paintings', 'Compare prehistoric works from different regions'],
          ['Analyze a prehistoric work using formal analysis', 'Identify likely function from visual evidence', 'Compare global prehistoric traditions'],
          ['Write a brief formal analysis of the Venus of Willendorf', 'Compare Lascaux and Altamira — similarities and differences'],
          [('The Venus of Willendorf figurine\'s exaggerated physical features are most often interpreted as',
            'evidence of fertility symbolism or concepts of female power in prehistoric culture',
            ['a realistic portrait of a specific woman', 'a child\'s toy', 'a warning marker for territory']),
           ('Stonehenge is aligned with the solstices, suggesting its primary function was',
            'ceremonial or religious, possibly related to the agricultural cycle and ancestor veneration',
            ['astronomical research and navigation', 'defensive military fortification', 'storage of grain and livestock']),
           ('Formal analysis of a prehistoric cave painting would focus on',
            'line, shape, pigment, scale, and composition — the visual elements and how they create meaning',
            ['the identity of the artist and their biography', 'the market value of the artwork', 'the literary sources that inspired the images']),
           ('The term "prehistoric" in art history means',
            'before the invention of writing — a period known through material culture rather than written records',
            ['art made more than 10,000 years ago regardless of writing', 'art with no recognizable subject matter', 'art created by hunter-gatherers only']),
           ('The Paleolithic cave paintings at Lascaux and Altamira are significant because they',
            'demonstrate sophisticated artistic skill and symbolic thought in early modern humans',
            ['are the earliest human artifacts ever found', 'were made by Neanderthals rather than modern humans', 'show evidence of writing systems'])],
          ['What is formal analysis?', 'Why is it difficult to determine the function of prehistoric art?', 'What themes appear across global prehistoric art?'],
          [('The Hall of the Bulls at Lascaux (France, c. 17,000 BCE) is significant because it',
            'demonstrates sophisticated compositional skill and represents one of the earliest large-scale painted narratives',
            ['was the first artwork ever created by humans', 'uses linear perspective to suggest space', 'depicts a specific historical battle']),
           ('Prehistoric megalithic monuments such as Stonehenge were most likely used for',
            'communal ceremonial or funerary purposes related to seasonal cycles',
            ['defensive military purposes', 'astronomical research by scientists', 'agricultural storage']),
           ('The use of mineral pigments (ochre, manganese) in cave paintings demonstrates',
            'early humans\' ability to plan, prepare materials, and apply systematic artistic technique',
            ['that prehistoric artists had formal training', 'that painting was a commercial activity', 'that early humans had no symbolic thinking']),
           ('Prehistoric portable objects (figurines, beads, carved bones) differ from cave paintings in that they',
            'could be carried and exchanged, suggesting possible social and trade functions across communities',
            ['are always more recent than cave paintings', 'have no artistic merit compared to cave paintings', 'were only made by women']),
           ('The "handprints" at Cueva de las Manos (Argentina, c. 9000–13,000 BCE) are interpreted as',
            'assertions of individual presence and identity — "I was here" — as well as possible communal ritual',
            ['simple decoration with no meaning', 'calendar marks tracking seasons', 'ownership marks on territory']),
           ('Comparing global prehistoric art reveals',
            'universal human tendencies toward symbolic thinking, animal imagery, and marking of significant spaces',
            ['that all prehistoric cultures were in contact with each other', 'identical artistic styles across all regions', 'that only European cultures created sophisticated early art']),
           ('The formal element most important in distinguishing a mammoth from a horse in a cave painting is',
            'outline/contour line and the distinctive silhouette shape of each animal',
            ['color, since mammoths were always painted red', 'scale, since large animals are always shown larger', 'shading, which clearly distinguishes species']),
           ('Neolithic art (after c. 10,000 BCE) differs from Paleolithic art primarily in',
            'reflecting settled agricultural societies — including architecture, pottery, and weaving alongside continued figure-making',
            ['abandoning all animal imagery', 'adopting linear perspective', 'being entirely non-representational']),
           ('The study of objects without written records relies on',
            'archaeology, formal analysis, anthropological comparison with living cultures, and scientific dating methods',
            ['reading the artist\'s journal and letters', 'applying one universal theory of meaning to all objects', 'carbon-dating all artistic materials']),
           ('A Neolithic burial site with grave goods (tools, figurines, food) suggests',
            'belief in an afterlife and the spiritual significance of material objects for the deceased',
            ['early capitalism and property rights', 'evidence of warrior culture', 'that burial was rare in prehistoric times']),
          ]),

    _unit(2, 'Ancient Mediterranean: 3500 BCE–300 CE',
          'ap-art-history-2-unit-2-ancient-mediterranean-3500-bce-300-ce.html',
          'Art and architecture of ancient Mesopotamia, Egypt, Greece, and Rome.',
          ['How did ancient Mediterranean cultures use art to express power and religion?',
           'What is the difference between Egyptian idealism and Greek naturalism?',
           'How did Roman art synthesize earlier traditions?',
           'What architectural innovations defined ancient Mediterranean building?'],
          'Egyptian and Mesopotamian Art',
          'Egyptian Conventions and the Afterlife',
          'Egyptian art follows strict conventions: composite view (head in profile, eye frontal, shoulders frontal, legs in profile), hierarchy of scale, and registers. These conventions served religious functions, especially funerary contexts — art ensured the continued existence of the deceased.',
          'Students see Egyptian conventions as "primitive" inability to depict space; they are deliberate choices serving religious and symbolic functions, not failed attempts at naturalism.',
          'Identify Egyptian conventions in a work; explain their function; compare Egyptian and Greek approaches to the human figure.',
          [('composite view', 'Egyptian figure convention showing the most characteristic view of each body part simultaneously'),
           ('hierarchy of scale', 'Depicting important figures larger, regardless of spatial logic'),
           ('ka', 'The ancient Egyptian concept of a spiritual life force, housed in the body and associated tomb images'),
           ('ziggurat', 'Stepped pyramid-shaped temple of ancient Mesopotamia (e.g., Ur-Nammu\'s ziggurat)'),
           ('kouros', 'Greek standing nude male youth figure from the Archaic period; influenced by Egyptian posture')],
          ['Identify Egyptian conventions in artworks', 'Explain the function of funerary art', 'Compare Greek Archaic vs. Classical human figures'],
          ['Apply formal analysis to a Greek sculpture identifying its period', 'Explain why Egyptian art maintained conventions for 3,000 years'],
          ['Compare the Palette of Narmer to the Great Pyramids — what do they say about Egyptian kingship?'],
          [('The Egyptian convention of the "composite view" shows the human body',
            'with the head in profile, eyes frontal, shoulders frontal, and legs in profile to show all parts most completely',
            ['from a single consistent viewpoint', 'with naturalistic foreshortening', 'as a flat silhouette with no internal detail']),
           ('The Sphinx at Giza combines',
            'the head of a pharaoh with the body of a lion — symbolizing royal power and divine protection',
            ['the head of a falcon with the body of a human', 'the head of a bull with the wings of an eagle', 'the head of a god with the body of a cow']),
           ('Classical Greek sculpture (5th century BCE) is characterized by',
            'idealized proportions (Canon of Polyclitus), contrapposto stance, and calm expression (severe style giving way to naturalism)',
            ['rigid frontal poses and stylized forms (that\'s Archaic)', 'extreme emotional expression (that\'s Hellenistic)', 'realistic individual portraiture (that\'s Roman)']),
           ('Roman veristic portraiture differs from Greek idealism in that Roman portraits',
            'emphasize realistic, individualized features — wrinkles, age, and specific identity — asserting ancestral authority',
            ['always show subjects in their youth and idealized form', 'depict only gods and mythological heroes', 'were carved only from marble']),
           ('The Colosseum (Rome, 72–80 CE) demonstrated Roman engineering mastery through',
            'concrete construction, the barrel vault, the groin vault, and a sophisticated system of arches supporting tiered seating',
            ['Greek post-and-lintel construction throughout', 'purely decorative stone cladding with no structural function', 'the same techniques used in the Parthenon'])],
          ['Compare the Egyptian ka statue with a Greek kouros', 'Explain Roman verism vs. Greek idealism', 'What innovations enabled Roman monumental architecture?'],
          [('The Palette of Narmer (Egypt, c. 3100 BCE) is important because it',
            'commemorates the unification of Upper and Lower Egypt and establishes conventions used throughout Egyptian art',
            ['is the earliest known oil painting', 'depicts the first pyramid construction', 'records the first Egyptian legal code']),
           ('The Great Pyramids at Giza were built as',
            'royal tombs to house the mummified bodies of pharaohs and ensure their journey to the afterlife',
            ['temples for public worship of the sun god Ra', 'administrative centers for tax collection', 'astronomical observatories']),
           ('The Lamassu (Assyria, c. 883–859 BCE) guardian figures have five legs because',
            'when viewed from the front they appear stationary (two legs) and from the side they appear walking (four legs)',
            ['each leg represents a different Assyrian god', 'they were carved by two different sculptors', 'the fifth leg was added for stability']),
           ('The Elgin Marbles (Parthenon frieze) depicted',
            'the Panathenaic procession — citizens of Athens approaching the gods — combining religious and civic celebration',
            ['the Trojan War narrative', 'the genealogy of the Olympian gods', 'Alexander the Great\'s military victories']),
           ('Roman triumphal arches (e.g., Arch of Titus) functioned as',
            'monuments to military victories that reinforced imperial power through narrative relief sculpture',
            ['city gates for defensive purposes', 'temples dedicated to victory gods', 'aqueducts carrying water into the city']),
           ('Pompeian wall painting (1st century BCE–79 CE) is valuable because',
            'its preservation under volcanic ash provides the most complete surviving examples of ancient Roman painting',
            ['it is the oldest surviving Western painting', 'it was created by Greek artists and shows Greek style exclusively', 'it depicts only portraits of the Roman emperors']),
           ('The Canon of Polyclitus (5th century BCE) established',
            'ideal mathematical proportions for the human body, most famously realized in the "Doryphoros" (Spear-Bearer)',
            ['rules for Greek temple construction and column orders', 'the narrative program for the Parthenon frieze', 'the technique of bronze casting for sculpture']),
           ('Hellenistic sculpture (323–31 BCE) differs from Classical sculpture by',
            'showing more extreme emotion, dramatic poses, and psychological complexity (pathos)',
            ['depicting only ideal athletic youth', 'avoiding all emotional expression', 'using only marble rather than bronze']),
           ('The Roman Pantheon\'s (118–125 CE) most innovative feature is',
            'its large unreinforced concrete dome with an oculus (opening) at the top, 43 meters in diameter',
            ['its Corinthian column facade, which is the largest in antiquity', 'its use of the flying buttress to support the dome', 'its construction entirely from marble without concrete']),
           ('The term "verism" in Roman portraiture refers to',
            'hyper-realistic depiction of the subject\'s actual features, including age and imperfections, to assert authority and virtue',
            ['an idealized style borrowed from Greek sculpture', 'painting techniques using wax-based encaustic', 'the use of colored marble to depict skin tone']),
          ]),

    _unit(3, 'Early Europe and Colonial Americas: 200–1750 CE',
          'ap-art-history-3-unit-3-early-europe-and-colonial-americas-200-1750-ce.html',
          'Early Christian, Byzantine, Islamic, Romanesque, Gothic, Renaissance, and Baroque art in Europe and the Americas.',
          ['How did Christianity change European art from the 4th century onward?',
           'What is the relationship between Gothic architecture and light/spirituality?',
           'How did Renaissance artists revive classical ideals?',
           'How did colonialism shape art in the Americas after 1492?'],
          'Medieval and Renaissance European Art',
          'Byzantine Art and Its Conventions',
          'Byzantine art (330–1453 CE) is characterized by gold backgrounds representing divine light, stylized flat figures, frontal hieratic poses, and heavy use of mosaic. It prioritizes spiritual meaning over naturalism. Icons are devotional images believed to be conduits to the holy.',
          'Students assume Byzantine flatness indicates artistic inability; it represents a theological choice — earthly naturalism was inappropriate for depicting the divine.',
          'Identify Byzantine formal conventions and their theological meaning; compare Byzantine and Renaissance treatments of the same subjects.',
          [('icon', 'A devotional image of a holy figure in the Eastern Christian tradition, believed to be a window to the divine'),
           ('hieratic', 'A style that places more important figures higher and larger, conveying spiritual hierarchy'),
           ('mosaic', 'Art made from small pieces of colored glass, stone, or ceramic (tesserae) set in mortar'),
           ('tympanum', 'The semi-circular relief panel above a medieval church doorway, typically depicting the Last Judgment'),
           ('sfumato', 'Leonardo da Vinci\'s technique of blending tones so smoothly that forms seem to emerge from shadow')],
          ['Identify formal features of Byzantine art and their theological meaning', 'Analyze a Renaissance painting for use of perspective and classical references', 'Explain how Gothic cathedrals embodied medieval theology'],
          ['Compare a Byzantine icon to a Renaissance Madonna', 'Identify flying buttresses and their function in a Gothic cathedral diagram'],
          ['How does Hagia Sophia reflect the goals of Byzantine architecture?'],
          [('The development of linear perspective in early 15th-century Florence is attributed to',
            'Filippo Brunelleschi, whose mathematical demonstration inspired painters like Alberti and Masaccio',
            ['Leonardo da Vinci', 'Michelangelo', 'Raphael']),
           ('The Sistine Chapel ceiling (Michelangelo, 1508–1512) depicts',
            'scenes from Genesis, including the Creation of Adam, surrounded by figures of prophets and sibyls',
            ['the life of Christ from birth to resurrection', 'scenes from Dante\'s Divine Comedy', 'the history of the Catholic Church']),
           ('Gothic cathedrals used flying buttresses to',
            'transfer the lateral thrust of the stone vault to external piers, allowing thinner walls and larger windows',
            ['support the tower spires from collapsing', 'provide seating for pilgrims outside', 'create underground crypts beneath the nave']),
           ('The Baroque style (17th century) was promoted by the Catholic Church to',
            'create emotionally powerful art that would re-engage believers and counter Protestant criticism of Catholic imagery',
            ['imitate the style of classical Greek temples', 'reduce decoration and emphasize simplicity', 'promote Islamic geometric patterns']),
           ('The Virgin of Guadalupe (Mexico, 1531) is significant in colonial Latin American art because it',
            'represents the fusion of indigenous and Spanish Catholic traditions, becoming the most important religious image in Mexico',
            ['is the oldest surviving painting in the Americas', 'was created entirely by indigenous artists without European influence', 'was used exclusively by Spanish colonizers'])],
          ['What distinguishes Romanesque from Gothic architecture?', 'Why did the Council of Trent promote Baroque art?', 'What is mestizo or syncretist art in the colonial Americas?'],
          [('The Book of Kells (Ireland, c. 800 CE) represents Insular art through',
            'intricate interlace patterns, zoomorphic (animal-form) letters, and elaborate illumination serving Christian devotion',
            ['realistic portrait miniatures of Irish saints', 'scenes of Viking mythology', 'maps of the known medieval world']),
           ('Romanesque architecture (c. 1000–1150 CE) is identified by',
            'round arches, thick walls with small windows, barrel vaults, and massive piers',
            ['pointed arches and flying buttresses (those are Gothic)', 'large glass windows flooding interiors with light', 'classical columns and pediments']),
           ('The concept of the "tympanum" in a Romanesque or Gothic church refers to',
            'the semi-circular carved relief above the main portal, typically showing the Last Judgment',
            ['the bell tower attached to the main nave', 'the decorative floor pattern in the crossing', 'the stained glass window above the altar']),
           ('The gold backgrounds in Byzantine mosaics (e.g., Ravenna) represent',
            'divine, heavenly, eternal light — a non-earthly space signifying the presence of God',
            ['the wealth of the Byzantine emperor who commissioned them', 'the landscape of the Holy Land', 'the practical advantage of gold reflecting candlelight']),
           ('Leonardo da Vinci\'s "sfumato" technique creates',
            'soft, hazy transitions between light and shadow, giving forms a three-dimensional, atmospheric quality',
            ['hard, sharp outlines emphasizing the human figure', 'heavy impasto textures on the painted surface', 'gold leaf highlights on sacred figures']),
           ('High Renaissance painting (c. 1490–1527) is characterized by',
            'idealized forms, balanced composition, serene harmony, and reference to classical antiquity',
            ['emotional intensity and distorted proportions (Mannerism)', 'dramatic light/dark contrast (Baroque)', 'flat gold backgrounds and hieratic style (Byzantine)']),
           ('Mannerism (c. 1520–1600) in Italian painting is identified by',
            'elongated figures, unnaturally bright colors, complex poses, and ambiguous spatial logic',
            ['strict adherence to classical proportion and harmony', 'heavy impasto and broad gestural brushwork', 'illusionistic perspective ceilings (that\'s Baroque)']),
           ('El Greco\'s elongated figures and intense spiritual atmosphere are characteristic of',
            'Mannerism and his personal synthesis of Byzantine iconographic tradition with Italian Renaissance training',
            ['Dutch Golden Age realism', 'French Rococo style', 'Spanish Baroque after Caravaggio']),
           ('The Baroque sculptor Gianlorenzo Bernini is known for',
            'dynamic sculptures that capture movement, dramatic emotion, and theatrical integration of architecture and sculpture (e.g., Ecstasy of Saint Teresa)',
            ['serene idealized classical figures in white marble', 'politically satirical portraits of Roman senators', 'abstract geometric relief panels']),
           ('The syncretism of colonial Latin American art refers to',
            'the blending of indigenous and European artistic traditions in a single work or tradition, as in Andean-Catholic devotional images',
            ['exact copying of Spanish paintings by indigenous artists', 'rejection of all indigenous traditions by colonized peoples', 'importing European artworks unchanged to the Americas']),
          ]),

    _unit(4, 'Later Europe and Americas: 1750–1980 CE',
          'ap-art-history-4-unit-4-later-europe-and-americas-1750-1980-ce.html',
          'Neoclassicism, Romanticism, Realism, Impressionism, and the 20th-century avant-garde movements.',
          ['How did the French Revolution change European art?',
           'What is the significance of Impressionism\'s break from academic tradition?',
           'How do Modernist movements (Cubism, Surrealism, Abstraction) reflect the 20th century?',
           'What is the role of photography in the history of art after 1839?'],
          'Neoclassicism through Impressionism',
          'Neoclassicism and the Academy',
          'Neoclassicism (c. 1750–1830) revived Greco-Roman subject matter, style, and moral clarity in response to the Rococo\'s frivolity. Jacques-Louis David\'s "Oath of the Horatii" (1784) exemplifies this: heroic subject, clarity of line, architectural composition, and moral message tied to republican virtue.',
          'Students equate "neoclassical" with "old-fashioned"; Neoclassicism was politically radical — it opposed the decadent aristocratic Rococo with republican virtue and civic duty.',
          'Identify key works of Neoclassicism, Romanticism, and Realism; explain their political/social contexts; describe formal differences.',
          [('Neoclassicism', 'Late 18th–early 19th century movement reviving Greek and Roman forms, associated with Enlightenment ideals and republican politics'),
           ('Romanticism', 'Early 19th century movement emphasizing emotion, nature, the sublime, and individualism in reaction to rationalism'),
           ('Realism', 'Mid-19th century movement depicting everyday working-class life without idealization (Courbet, Daumier)'),
           ('Impressionism', 'French movement (1860s–80s) capturing momentary light with loose brushwork and everyday subjects (Monet, Renoir, Degas)'),
           ('chiaroscuro', 'Strong contrast between light and dark areas, used to create volume and dramatic effect (Caravaggio, Rembrandt)')],
          ['Identify formal features of major 19th–20th century movements', 'Explain how each movement responded to the previous one', 'Analyze a work by Cézanne, Picasso, or Pollock using formal analysis'],
          ['Compare Monet\'s garden series with a David Neoclassical work — what changed?', 'Identify the cultural context that produced Cubism'],
          ['What political events shaped Neoclassicism and Romanticism?'],
          [('The Impressionists were controversial when they first exhibited because',
            'their loose brushwork, unconventional subjects, and lack of academic finish violated the standards of the Paris Salon',
            ['they depicted only industrial and ugly subjects', 'they completely abandoned color in favor of black and white', 'they used photography instead of painting']),
           ('Pablo Picasso and Georges Braque developed Cubism (c. 1907–1914) to',
            'depict objects from multiple viewpoints simultaneously, fragmenting form to show full three-dimensionality on a flat surface',
            ['imitate African masks without any conceptual innovation', 'produce purely decorative geometric patterns', 'return to classical Greek ideals of beauty']),
           ('Surrealism (founded 1924) drew on __________ to access the unconscious.',
            'Freudian psychoanalysis and dream imagery, depicting irrational, dreamlike juxtapositions',
            ['Marxist political theory and class struggle', 'ancient mythology and religious symbolism', 'mathematical theories of space and time']),
           ('Abstract Expressionism (1940s–50s, New York) is characterized by',
            'large-scale canvases, gestural or color-field abstraction, and emphasis on the act of painting as expressive',
            ['precise geometric forms and flat color planes (Minimalism)', 'collaged newspaper headlines and commercial imagery (Pop Art)', 'geometric abstraction based on mathematical systems']),
           ('The advent of photography (1839) affected Western painting by',
            'freeing painters from the obligation to record reality, contributing to abstraction, Impressionism, and avant-garde experimentation',
            ['eliminating portrait painting completely within 20 years', 'having no effect — painters ignored photography entirely', 'causing the immediate death of academic painting'])],
          ['Compare Romanticism\'s emotion with Neoclassicism\'s reason', 'Explain why Courbet\'s Realism was politically controversial', 'How did Cézanne bridge Impressionism and Cubism?'],
          [('Jacques-Louis David\'s "Oath of the Horatii" (1784) was politically significant because',
            'it evoked Roman republican virtue, implicitly critiquing aristocratic decadence in pre-Revolutionary France',
            ['it celebrated the French monarchy', 'it depicted a scene from the Bible', 'it was the first French painting shown at a public exhibition']),
           ('Francisco Goya\'s "Third of May 1808" (1814) was revolutionary in war imagery because',
            'it portrayed the victims of war with pathos rather than glorifying military violence — an anti-heroic perspective',
            ['it was the first painting to depict a modern firearm', 'it celebrated the French invaders as liberators', 'it showed no human figures, only destroyed buildings']),
           ('Gustave Courbet\'s "A Burial at Ornans" (1849) was controversial because',
            'it depicted ordinary provincial people at a burial with the scale and seriousness reserved for epic history painting',
            ['it showed naked figures in a public setting', 'it depicted a violent political assassination', 'it was painted on an extremely small canvas']),
           ('Édouard Manet\'s "Olympia" (1865) scandalized Paris because',
            'it depicted a nude woman as a modern prostitute who stares boldly at the viewer, challenging academic idealization of the nude',
            ['it was the first French painting of a female nude', 'it depicted a historical goddess in an irreverent context', 'it used photographic techniques rather than traditional painting']),
           ('Paul Cézanne is considered a "bridge" to Modernism because',
            'his analysis of form through geometric simplification and multiple viewpoints directly influenced Cubism and 20th-century abstraction',
            ['he invented the Impressionist style of loose brushwork', 'he founded the Surrealist movement', 'he was the first painter to use photographs as references']),
           ('Wassily Kandinsky\'s move toward pure abstraction (c. 1910) was motivated by',
            'his belief that colors and forms could express spiritual and emotional states without reference to recognizable objects',
            ['his inability to draw the human figure accurately', 'the influence of Cubism and Picasso\'s work directly', 'his desire to mimic musical composition visually without a theory']),
           ('The Dada movement (1916–1920s) responded to World War I by',
            'creating deliberately irrational, provocative, and anti-art works to critique the culture that produced the war',
            ['celebrating nationalist military values through heroic imagery', 'reviving Renaissance ideals as a cultural cure', 'creating technically virtuosic works in the academic tradition']),
           ('Jackson Pollock\'s "drip paintings" (late 1940s) are best analyzed as',
            'process-based works where the act of painting (pouring, dripping, moving around the canvas) is itself the subject',
            ['carefully planned geometric compositions executed spontaneously', 'landscapes of the American West seen from above', 'portraits with the human figure dissolved into color']),
           ('Pop Art (1950s–60s, Warhol, Lichtenstein) used imagery from',
            'mass media, advertising, and consumer culture to comment on (and celebrate or critique) postwar American consumerism',
            ['prehistoric cave paintings and tribal art', 'scientific diagrams and architectural blueprints', 'Renaissance religious subjects reinterpreted for modern audiences']),
           ('The Feminist Art movement (1970s) challenged art history by',
            'arguing that women artists had been systematically excluded and that art history\'s canon reflected patriarchal values',
            ['claiming all great art was created by women', 'rejecting all figurative art as inherently gendered', 'arguing that gender was irrelevant to artistic judgment']),
          ]),

    _unit(5, 'Indigenous Americas: 1000 BCE–1980 CE',
          'ap-art-history-5-unit-5-indigenous-americas-1000-bce-1980-ce.html',
          'Art of Mesoamerica (Olmec, Maya, Aztec), South America (Chavin, Inca), and North America.',
          ['How does Mesoamerican art reflect cosmological beliefs?',
           'What is the function of monumental sculpture in indigenous American cultures?',
           'How do Andean textiles communicate cultural and religious meaning?',
           'How does indigenous American art continue to the present day?'],
          'Mesoamerican Art',
          'Maya Art and Architecture',
          'Maya civilization (c. 250–900 CE Classic period) produced monumental architecture (Tikal), hieroglyphic inscriptions, elaborate polychrome ceramics, and jade carving. The pyramid at Chichén Itzá (El Castillo) functioned as a calendar monument — 91 steps × 4 sides + 1 top = 365, aligning with the solar year.',
          'Students assume all Mesoamerican pyramids are tombs like Egyptian pyramids; most Mesoamerican pyramids are temple platforms for ceremonies, not tombs.',
          'Analyze formal features of a Maya stela or ceramic; explain cosmological symbolism; compare Mesoamerican and Andean traditions.',
          [('stela (pl. stelae)', 'An upright stone slab carved with images and hieroglyphic text, used by Maya rulers to record historical and astronomical events'),
           ('tzompantli', 'An Aztec skull rack displaying sacrificial victims\' skulls at temple complexes'),
           ('quipu', 'An Incan recording device of knotted strings used for record-keeping and communication'),
           ('featherwork', 'A prestige material art form in Mesoamerica using iridescent feathers of tropical birds to create elaborate mosaics, cloaks, and headdresses'),
           ('colossal heads', 'Monumental Olmec basalt heads (c. 900–400 BCE) depicting rulers; up to 9 feet tall')],
          ['Identify Mesoamerican and Andean art forms and explain their cultural function', 'Analyze the Aztec Sun Stone as a cosmological object', 'Compare Mesoamerican and Egyptian pyramid forms and functions'],
          ['Explain the significance of jade in Maya culture', 'What does the layout of Teotihuacan reveal about Mesoamerican cosmology?'],
          ['How do indigenous American textiles communicate cultural identity?'],
          [('The Olmec colossal heads (c. 900–400 BCE) are believed to represent',
            'individual Olmec rulers, serving as portraits of political authority',
            ['Olmec gods in human form', 'athletes who won the Mesoamerican ballgame', 'ancestor spirits watching over the city']),
           ('Mesoamerican pyramids differ functionally from Egyptian pyramids because Mesoamerican pyramids were primarily',
            'ceremonial temple platforms for ritual activities at their summit, not tombs',
            ['tombs for rulers buried inside them', 'observatories for astronomical research', 'granaries storing agricultural surplus']),
           ('The Aztec feathered headdress (Penacho, c. 1500 CE) communicates',
            'the wearer\'s elite status and connection to the divine through the use of rare, spiritually significant quetzal bird feathers',
            ['military rank based on the number of feathers', 'the wearer\'s clan membership', 'a decorative object with no symbolic significance']),
           ('The Incan city of Machu Picchu (c. 1450 CE) demonstrates Andean architectural skill through',
            'its dry-stone masonry (ashlar) that uses precisely fitting interlocking stones without mortar',
            ['its bronze reinforcing rods holding stones together', 'its exact copy of Spanish colonial architecture', 'its use of fired brick throughout']),
           ('Mississippian mound cultures of North America (c. 800–1600 CE) constructed',
            'large earthen platform mounds used as temple bases, burial sites, and chiefly residences at sites like Cahokia',
            ['stone pyramids similar to Maya structures', 'circular stone monuments like Stonehenge', 'underground kiva chambers for ceremony'])],
          ['What function did the ballgame have in Mesoamerican culture?', 'How did the Inca use quipus?', 'What is the significance of the feather in Mesoamerican art?'],
          [('The Mesoamerican ballgame court was',
            'a ritual space where the game had religious significance, possibly connected to sacrifice and cosmological reenactment',
            ['a commercial marketplace where teams competed for prizes', 'a training ground for Aztec military warriors', 'a site for agricultural festivals celebrating the harvest']),
           ('Aztec sculpture of Coatlicue (c. 1500 CE) shows the earth goddess with',
            'a skirt of writhing serpents, a necklace of human hearts and skulls, and clawed feet — embodying destruction and creation simultaneously',
            ['a serene, idealized human form in the Greek tradition', 'armor and weapons reflecting Aztec militarism', 'a child figure reflecting maternal tenderness']),
           ('Teotihuacan\'s Avenue of the Dead is organized',
            'along a cardinal axis aligned with astronomical observations, reflecting Mesoamerican cosmological order',
            ['randomly according to commercial traffic needs', 'following the natural contours of the landscape', 'in a spiral form representing time']),
           ('The Chavin culture (Peru, c. 900–200 BCE) is known for',
            'a pan-Andean religious art style featuring the Staff God and fanged supernatural beings at the site of Chavin de Huantar',
            ['gold jewelry and metalwork only', 'monumental freestanding figural sculpture', 'realistic portrait ceramics of individual rulers']),
           ('Andean textiles were significant luxury objects because',
            'they required immense labor, displayed technical mastery, communicated social rank, and served as ceremonial objects and tribute items',
            ['they were produced only by slave labor for export', 'their value derived entirely from the cost of imported dyes', 'they were purely functional items with no symbolic meaning']),
           ('The Nazca Lines (Peru, c. 500 BCE–500 CE) geoglyphs were most likely created for',
            'ritual and religious purposes, possibly related to water sources or astronomical alignments, visible from hills above or by the gods above',
            ['landing pads for extraterrestrial visitors', 'boundary markers between rival city-states', 'crop irrigation channels']),
           ('The Mayan calendar depicted in the Aztec Sun Stone is significant because',
            'it represents a complex cosmological worldview integrating time, creation myths, and the cosmos into a single monument',
            ['it was the first accurate calendar in human history', 'it was used exclusively to schedule agricultural activities', 'it depicts the same calendar as the Egyptian zodiac']),
           ('Indigenous American art "continues to the present day" — this statement acknowledges',
            'that indigenous artistic traditions are living, evolving practices, not merely historical artifacts',
            ['that all modern indigenous art exactly replicates pre-contact traditions', 'that indigenous art ended with European colonization', 'that contemporary artists reject indigenous heritage']),
           ('Comparing Aztec and Inca monumental art reveals',
            'both emphasized rulers\' divine authority and cosmological power, but used different materials and artistic vocabularies',
            ['identical artistic styles across two entirely separate cultures', 'that the Aztec had no monumental art compared to the Inca', 'that both cultures copied Mesoamerican Maya traditions']),
           ('The use of jade in Maya art indicates',
            'the material\'s sacred associations with water, vegetation, and rulership — jade was more valuable than gold to the Maya',
            ['trade connections with China where jade was common', 'purely aesthetic preference with no symbolic meaning', 'the availability of jade in local riverbeds']),
          ]),
]
