NAME = 'AP® Calculus BC'
ABBREV = 'calc'
SLUG = 'ap-calculus-bc'
COURSE_FILE = 'ap-calculus-bc.html'
ACCENT_COLOR = '#a78bfa'

_K = 'https://www.khanacademy.org/math/ap-calculus-ab/'
_P = 'https://www.youtube.com/results?search_query=Professor+Leonard+Calculus+'

def _t(title, content, mis, tested):
    return {'title': title, 'content': content, 'misconception': mis, 'how_tested': tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
{
  'num': 6, 'title': 'Integration and Accumulation of Change',
  'file': 'ap-calculus-bc-6-unit-6-integration-and-accumulation-of-change.html',
  'desc': 'Define the definite integral as a limit of Riemann sums, apply the Fundamental Theorem of Calculus, and compute basic antiderivatives.',
  'gateway': [
      'Define the definite integral as a limit of Riemann sums.',
      'State and apply both parts of the Fundamental Theorem of Calculus.',
      'Compute antiderivatives using basic rules and u-substitution.',
      'Interpret the definite integral as accumulated change.',
  ],
  'lessons': [
      _l('Riemann Sums and the Definite Integral',
         [_t('Riemann Sums', 'A Riemann sum approximates ∫_a^b f(x)dx by summing areas of rectangles: left, right, or midpoint. As n→∞ the sum approaches the exact integral.', 'Students think left/right sums give exact values; they are approximations whose accuracy improves with more subintervals.', 'Calculate left and right Riemann sums from a table of values and compare to the exact integral.'),
          _t('Definite Integral as a Limit', '∫_a^b f(x)dx = lim_{n→∞} Σf(x_i*)Δx. The definite integral gives the net signed area between f and the x-axis.', 'Students think the integral always gives positive area; it gives signed area — portions below the x-axis are negative.', 'Evaluate definite integrals geometrically for piecewise linear functions using area formulas.'),
          _t('Properties of Definite Integrals', '∫_a^a f dx=0; ∫_a^b f dx=−∫_b^a f dx; ∫_a^b cf dx=c∫_a^b f dx; ∫_a^b(f+g)dx=∫_a^b f dx+∫_a^b g dx; ∫_a^b f dx=∫_a^c f dx+∫_c^b f dx.', 'Students forget the sign flip when reversing limits: ∫_a^b=−∫_b^a.', 'Apply integral properties to evaluate integrals from known values without computing antiderivatives.')],
         [('Riemann sum', 'Approximation of ∫f dx as sum of rectangle areas'),
          ('left/right/midpoint sum', 'Three choices of where to sample f on each subinterval'),
          ('net signed area', 'What the definite integral computes: area above minus area below x-axis'),
          ('additivity of integrals', '∫_a^b f = ∫_a^c f + ∫_c^b f for any c')],
         ['Compute left and right Riemann sums from tables', 'Evaluate definite integrals geometrically', 'Apply integral properties to simplify expressions'],
         ['Riemann sums from tables appear in MC and FR', 'Geometric evaluation of integrals with triangles and semicircles', 'Integral properties tested in both MC and FR'],
         ['Compute 4-rectangle left sum for f(x)=x² on [0,4]', 'Use a graph to evaluate ∫_0^4 f dx where f has triangular regions'],
         [('Compute the left Riemann sum for f(x)=x² on [0,4] with n=4 subintervals.', ['Δx=1; sample points: 0,1,2,3', 'Sum=f(0)+f(1)+f(2)+f(3)=0+1+4+9=14', 'Actual value: ∫_0^4 x² dx=64/3≈21.3', 'Left sum underestimates since f is increasing']),
          ('Evaluate ∫_0^3 f(x)dx if the graph shows a triangle above x-axis with base 3 and height 4.', ['Area of triangle = (1/2)·base·height', '(1/2)(3)(4)=6', '∫_0^3 f dx=6', 'Geometric interpretation: signed area = positive triangle area']),
          ('If ∫_1^5 f dx=10 and ∫_1^3 f dx=4, find ∫_3^5 f dx.', ['Additivity: ∫_1^5=∫_1^3+∫_3^5', '10=4+∫_3^5 f dx', '∫_3^5 f dx=6', 'Property of definite integrals']),
          ('Evaluate ∫_2^0 f dx if ∫_0^2 f dx=7.', ['Reversing limits changes sign', '∫_2^0 f dx=−∫_0^2 f dx=−7', 'This is a fundamental property', 'Not the same as ∫_0^2']),
          ('A right Riemann sum overestimates ∫f dx. What does this tell you about f?', ['Right sum overestimates means rectangles are too tall', 'This happens when f is decreasing on the interval', 'For decreasing f: right sum ≤ actual ≤ left sum', 'For increasing f: left sum ≤ actual ≤ right sum'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Riemann Sums', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the three types of Riemann sums', 'Explain why the definite integral gives signed area', 'Apply integral additivity to compute a missing piece']),

      _l('Fundamental Theorem of Calculus',
         [_t('FTC Part 1', 'If F(x)=∫_a^x f(t)dt, then F\'(x)=f(x). Differentiating an integral with variable upper limit returns the integrand evaluated at that limit.', 'Students differentiate F(x) by computing the integral first; FTC Part 1 says directly F\'(x)=f(x).', 'Apply FTC Part 1 with chain rule: d/dx[∫_a^{g(x)} f(t)dt]=f(g(x))·g\'(x).'),
          _t('FTC Part 2', '∫_a^b f(x)dx=F(b)−F(a) where F is any antiderivative of f. This converts definite integrals into evaluation of antiderivatives.', 'Students compute F(b)−F(a) as F(a)−F(b); always subtract F(a) from F(b).', 'Find antiderivatives and evaluate them at the bounds to compute definite integrals.'),
          _t('Net Change Theorem', '∫_a^b F\'(x)dx=F(b)−F(a). The definite integral of a rate gives the net change in the original quantity.', 'Students confuse total change with total amount; ∫v dt gives displacement (net change), not total distance.', 'Interpret ∫_a^b r(t)dt as the net change in the quantity whose rate is r(t).')],
         [('FTC Part 1', 'd/dx[∫_a^x f(t)dt]=f(x)'),
          ('FTC Part 2', '∫_a^b f dx=F(b)−F(a)'),
          ('antiderivative', 'F(x) such that F\'(x)=f(x)'),
          ('net change', '∫_a^b rate dt = quantity(b)−quantity(a)')],
         ['Apply FTC Part 1 directly and with chain rule', 'Evaluate definite integrals using FTC Part 2', 'Interpret definite integrals as net change in context'],
         ['FTC Part 1 with chain rule appears in almost every AP® exam', 'Net change interpretation is standard FR context', 'FTC Part 2 computation in both MC and FR'],
         ['Differentiate G(x)=∫_0^{x²} sin(t)dt', 'Evaluate ∫_0^π cos(x)dx using FTC Part 2'],
         [('Differentiate G(x)=∫_0^x (t²+1)dt.', ['FTC Part 1: G\'(x)=x²+1', 'Just replace t with x', 'No need to compute the integral first', 'G\'(x)=x²+1']),
          ('Differentiate H(x)=∫_1^{x³} e^t dt.', ['FTC Part 1 + chain rule: H\'(x)=e^{x³}·3x²', 'Evaluate integrand at upper limit x³, multiply by (x³)\'=3x²', 'H\'(x)=3x²e^{x³}', 'Chain rule is essential when upper limit is a function']),
          ('Evaluate ∫_0^π sin(x)dx.', ['Antiderivative of sin x is −cos x', 'FTC Part 2: [−cos x]_0^π', '−cos(π)−(−cos 0)=1+1=2', 'Net area = 2']),
          ('Water flows into a tank at r(t)=2t+1 gallons/min. How much water enters from t=0 to t=3?', ['Net change = ∫_0^3(2t+1)dt', '=[t²+t]_0^3=9+3−0=12', '12 gallons enter the tank', 'FTC Part 2 applied to a rate function']),
          ('Find ∫_1^4 (√x−1/x)dx.', ['∫√x dx=(2/3)x^{3/2}; ∫1/x dx=ln|x|', 'F(x)=(2/3)x^{3/2}−ln x', 'F(4)−F(1)=(2/3)(8)−ln4−(2/3−0)', '=16/3−ln4−2/3=14/3−ln4'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — FTC', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State both parts of FTC in words', 'Differentiate G(x)=∫_2^{sin x}√(1+t²)dt', 'Interpret ∫_0^5 v(t)dt in a motion context']),

      _l('Basic Antiderivative Rules and u-Substitution',
         [_t('Power Rule for Integrals', '∫xⁿdx=x^{n+1}/(n+1)+C for n≠−1; ∫1/x dx=ln|x|+C. Always add +C for indefinite integrals.', 'Students forget +C or try to apply the power rule to n=−1; the antiderivative of 1/x is ln|x|, not x⁰/0.', 'Integrate polynomial expressions term by term; flag n=−1 and use ln|x|.'),
          _t('Trigonometric Antiderivatives', '∫cos x dx=sin x+C; ∫sin x dx=−cos x+C; ∫sec²x dx=tan x+C; ∫sec x tan x dx=sec x+C.', 'Students write ∫sin x dx=cos x+C (wrong sign); the antiderivative of sin x is −cos x.', 'Compute integrals of trig functions, checking signs carefully.'),
          _t('u-Substitution', 'If the integrand has f(g(x))·g\'(x), let u=g(x), du=g\'(x)dx. Replace all x-terms with u, integrate in u, then back-substitute.', 'Students forget to change limits for definite integrals with u-substitution, or forget to replace dx with du/g\'(x).', 'Perform u-substitution on indefinite and definite integrals; change limits for definite integrals.')],
         [('power rule (integration)', '∫xⁿdx=x^{n+1}/(n+1)+C'),
          ('constant of integration', '+C added to every indefinite integral'),
          ('u-substitution', 'Reversing the chain rule; let u=inner function'),
          ('changing limits', 'For definite integrals, substitute u(a) and u(b) as new bounds')],
         ['Apply power rule to integrate polynomials and rational functions', 'Integrate standard trig and exponential functions', 'Use u-substitution on composite integrands'],
         ['u-substitution is tested on both MC and FR sections', 'Power rule integration appears in every exam', 'Definite integral with u-substitution requires changing limits'],
         ['Integrate ∫(3x²+5x−2)dx and ∫x·e^{x²}dx', 'Evaluate ∫_0^1 2x(x²+1)⁴dx using u-substitution'],
         [('Evaluate ∫(4x³−6x+1)dx.', ['∫4x³ dx=x⁴; ∫6x dx=3x²; ∫1 dx=x', 'Result: x⁴−3x²+x+C', 'Apply power rule term by term', '+C is required']),
          ('Evaluate ∫_0^{π/2} cos(x)dx.', ['Antiderivative: sin(x)', '[sin x]_0^{π/2}=sin(π/2)−sin(0)=1−0=1', 'Net area = 1', 'FTC Part 2 applied']),
          ('Evaluate ∫2x(x²+1)⁵dx using u-substitution.', ['Let u=x²+1; du=2x dx', '∫u⁵ du=u⁶/6+C', 'Back-substitute: (x²+1)⁶/6+C', 'Check by differentiating']),
          ('Evaluate ∫_0^1 2x(x²+1)⁵dx.', ['u=x²+1; du=2x dx; new limits: u(0)=1, u(1)=2', '∫_1^2 u⁵ du=[u⁶/6]_1^2=64/6−1/6=63/6=21/2', 'Result: 21/2', 'Change limits when substituting in definite integral']),
          ('Evaluate ∫e^{3x}dx.', ['Let u=3x; du=3 dx → dx=du/3', '∫eᵘ·(du/3)=(1/3)eᵘ+C=(1/3)e^{3x}+C', 'Or recognize pattern directly', 'Chain rule in reverse'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — u-Substitution', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the power rule for integration', 'Identify when u-substitution applies', 'Evaluate ∫sin(2x)dx using u-substitution']),

      _l('Accumulation Functions and Area',
         [_t('Accumulation Functions', 'A(x)=∫_a^x f(t)dt accumulates area under f from a to x. A\'(x)=f(x) by FTC Part 1. A(x) inherits properties from f: A increases where f>0, has extrema where f=0.', 'Students interpret A(x) as a formula rather than a running total; A(x) changes as x increases and its rate of change is f(x).', 'Analyze an accumulation function A(x) given a graph of f: find max/min of A, determine concavity.'),
          _t('Area Between Curves', '∫_a^b [f(x)−g(x)]dx gives the area between f (upper) and g (lower) from a to b. Identify which function is on top on each subinterval.', 'Students integrate f−g over the full interval even when the curves cross; splitting at intersection points is required.', 'Find intersection points, then integrate (upper−lower) on each subinterval.'),
          _t('Area with Respect to y', 'Sometimes it is easier to integrate with respect to y: ∫_c^d [right(y)−left(y)]dy. Useful when the region is bounded by curves that are easier to express as x=f(y).', 'Students always integrate with respect to x; sometimes the region is described more simply with horizontal rectangles (dy).', 'Set up area integrals with respect to y for regions bounded by x=y² and x=y+2.')],
         [('accumulation function', 'A(x)=∫_a^x f(t)dt; its derivative is f(x)'),
          ('area between curves', '∫_a^b[upper−lower]dx'),
          ('intersection points', 'Where f(x)=g(x); needed to set up area between curves correctly'),
          ('integrating with respect to y', '∫_c^d[right(y)−left(y)]dy for horizontally oriented regions')],
         ['Analyze accumulation functions from graphs of f', 'Set up and evaluate area between curves', 'Integrate with respect to y when appropriate'],
         ['Accumulation functions appear in nearly every AP® exam', 'Area between curves guaranteed in FR', 'Sometimes a 3-part FR question: find intersection, set up integral, evaluate'],
         ['Given graph of f, analyze A(x)=∫_0^x f(t)dt for extrema and concavity', 'Find area between y=x² and y=x+2'],
         [('Given f(t) is positive on (0,3) and negative on (3,5), find where A(x)=∫_0^x f(t)dt has a local max.', ['A\'(x)=f(x); A increases where f>0, decreases where f<0', 'A\'(x)=f(x)>0 on (0,3) and f(x)<0 on (3,5)', 'A has a local maximum at x=3', 'A\' changes from + to −']),
          ('Find the area between f(x)=x+2 and g(x)=x² on their overlap.', ['Intersect: x+2=x² → x²−x−2=0 → (x−2)(x+1)=0 → x=−1,2', 'f≥g on [−1,2]', '∫_{-1}^2 (x+2−x²)dx=[x²/2+2x−x³/3]_{-1}^2', '=(2+4−8/3)−(1/2−2+1/3)=9/2']),
          ('Find area of region bounded by y=√x and y=x.', ['Intersect: √x=x → x=0,1', 'On [0,1]: √x≥x', '∫_0^1(√x−x)dx=[2/3x^{3/2}−x²/2]_0^1=2/3−1/2=1/6', 'Area=1/6']),
          ('Set up the area between x=y² and x=y+2 with respect to y.', ['Intersect: y²=y+2 → y²−y−2=0 → y=−1,2', 'Right curve: x=y+2; left curve: x=y²', '∫_{-1}^2(y+2−y²)dy', 'Evaluate: [y²/2+2y−y³/3]_{-1}^2=9/2']),
          ('The graph of f has A(0)=0. On (0,2): f>0; on (2,4): f<0 with same magnitude. What is A(4)?', ['A(2)=∫_0^2 f dt > 0', 'On (2,4): f<0, so A decreases', 'Since magnitudes equal, A(4)=0', 'A returns to 0; displacement is zero'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Area Between Curves', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Explain how to find local extrema of A(x) from a graph of f', 'Set up the area between y=e^x and y=x on [0,1]', 'Describe when integrating with respect to y is preferable']),
  ],
  'unit_qs': [
      ('Compute the right Riemann sum for f(x)=1/x on [1,3] with n=4.', ['Δx=0.5; right endpoints: 1.5,2,2.5,3', 'Sum=(1/1.5+1/2+1/2.5+1/3)·0.5', '=(0.667+0.5+0.4+0.333)·0.5=0.95', 'Actual ∫_1^3 1/x dx=ln3≈1.099; right sum underestimates (f decreasing)']),
      ('Differentiate G(x)=∫_0^{x²} tan(t)dt.', ['FTC Part 1 + chain rule', 'G\'(x)=tan(x²)·2x', '=2x tan(x²)', 'Upper limit is x²; chain rule gives factor 2x']),
      ('Evaluate ∫_0^2 (3x²−4x+1)dx.', ['Antiderivative: x³−2x²+x', '[x³−2x²+x]_0^2=8−8+2=2', 'Result: 2', 'FTC Part 2']),
      ('Use u-substitution to evaluate ∫cos(5x)dx.', ['u=5x; du=5dx → dx=du/5', '(1/5)∫cos u du=(1/5)sin u+C', '=(1/5)sin(5x)+C', 'Chain rule in reverse']),
      ('Water drains from a tank at r(t)=−4t+10 liters/min. Find net change from t=0 to t=3.', ['∫_0^3(−4t+10)dt=[−2t²+10t]_0^3', '=−18+30=12', 'Net change: 12 liters enter (positive)', 'Net change theorem applied']),
      ('Find area between y=x³ and y=x on [0,1].', ['On [0,1]: x≥x³ (check at x=0.5: 0.5>0.125)', '∫_0^1(x−x³)dx=[x²/2−x⁴/4]_0^1=1/2−1/4=1/4', 'Area=1/4', 'Intersect at 0 and 1']),
      ('Given ∫_0^6 f dx=15 and ∫_4^6 f dx=5, find ∫_0^4 f dx.', ['∫_0^6=∫_0^4+∫_4^6', '15=∫_0^4+5', '∫_0^4 f dx=10', 'Additivity of integrals']),
      ('Evaluate ∫_{-1}^1 (x³+x)dx without computing (explain using symmetry).', ['f(x)=x³+x is odd: f(−x)=−f(x)', 'For odd functions, ∫_{-a}^a f dx=0', 'Result: 0', 'Symmetry property of definite integrals']),
      ('Find A\'(3) where A(x)=∫_1^x (t²−4)dt, then state whether A is increasing or decreasing at x=3.', ['A\'(x)=x²−4 by FTC Part 1', 'A\'(3)=9−4=5>0', 'A is increasing at x=3', 'Because f(3)=5>0']),
      ('Evaluate ∫_0^{π/4} sec²(x)dx.', ['Antiderivative: tan(x)', '[tan x]_0^{π/4}=tan(π/4)−tan(0)=1−0=1', 'Result: 1', 'Standard trig antiderivative']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=fYyARMqiaag',
},

{
  'num': 7, 'title': 'Differential Equations',
  'file': 'ap-calculus-bc-7-unit-7-differential-equations.html',
  'desc': 'Solve separable differential equations, use slope fields to visualize solutions, and apply Euler\'s method (BC).',
  'gateway': [
      'Verify solutions to differential equations by differentiation.',
      'Use slope fields to sketch and interpret solution curves.',
      'Solve separable differential equations analytically.',
      'Apply initial conditions to find particular solutions.',
  ],
  'lessons': [
      _l('Slope Fields',
         [_t('Constructing Slope Fields', 'A slope field plots dy/dx at many points (x,y) as short line segments. Each segment has slope equal to f(x,y) evaluated at that point.', 'Students draw horizontal segments everywhere; the slope varies with both x and y in most differential equations.', 'Plot slope field segments at given lattice points and identify which solution curve matches.'),
          _t('Matching Slope Fields to DEs', 'Match a slope field to its DE by checking: where are slopes zero? Where are they steep? Slopes that depend only on x give vertical-strip patterns; only on y give horizontal-strip patterns.', 'Students match by guessing; systematically check where dy/dx=0 to identify the zero-slope curves and eliminate wrong DEs.', 'Identify which DE matches a given slope field by checking zero-slope isoclines.'),
          _t('Sketching Solution Curves', 'A solution curve follows the slope field — at each point, the curve\'s tangent matches the segment. Starting from an initial point, trace the curve through the field.', 'Students draw solution curves that cross slope field segments at wrong angles; the curve must be tangent to each segment it passes through.', 'Given a slope field and initial condition, sketch the particular solution through that point.')],
         [('slope field', 'A diagram of short line segments showing dy/dx at many points (x,y)'),
          ('isocline', 'Curve along which dy/dx is constant; e.g., dy/dx=0 is the zero-isocline'),
          ('particular solution', 'The specific solution curve passing through a given initial point'),
          ('general solution', 'Family of all solution curves to a DE, containing constant C')],
         ['Draw slope field segments at specified points', 'Match a slope field to its differential equation', 'Sketch particular solution curves through initial points'],
         ['Slope fields appear in AP® MC and FR; often the entire Unit 7 FR', 'Matching slope field to DE is a common MC question', 'Sketching a solution curve through given initial condition'],
         ['Draw slope field for dy/dx=x−y at 9 lattice points', 'Given slope field, sketch solution with y(0)=1'],
         [('For dy/dx=2x, describe the slope field pattern.', ['Slopes depend only on x (not y)', 'Horizontal strips of constant slope', 'Slope=0 along x=0; positive for x>0, negative for x<0', 'Solution curves are parabolas y=x²+C']),
          ('For dy/dx=y, where are slopes equal to 0?', ['dy/dx=0 when y=0', 'The x-axis is the zero-isocline', 'Slopes are positive above x-axis (y>0) and negative below (y<0)', 'Solutions are exponentials y=Ce^x']),
          ('Sketch the solution to dy/dx=x/y passing through (0,2).', ['Slopes at (0,2): 0/2=0 — horizontal start', 'As x increases, slope becomes x/y — gently increasing', 'Curve is part of an ellipse x²+y²=C', 'Through (0,2): x²+y²=4 → y=√(4−x²)']),
          ('Match slope field where segments are steepest on y-axis and slope=0 on x-axis to a DE.', ['Slope=0 on y=0 suggests dy/dx contains y as factor', 'Steepest on y-axis suggests large |dy/dx| when x=0... check xy or y', 'dy/dx=y fits: zero on y=0, positive above', 'Match: dy/dx=y']),
          ('Describe what makes a solution curve correct on a slope field.', ['At every point, the curve must be tangent to the slope field segment', 'The curve cannot cross a segment at a wrong angle', 'If initial condition given, start at that point', 'Follow segments smoothly — no sharp corners'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Slope Fields', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Explain the difference between a slope field and a solution curve', 'How do you find zero-isoclines?', 'Sketch the solution to dy/dx=−x/y through (2,0)']),

      _l('Separable Differential Equations',
         [_t('Separation of Variables', 'Rewrite dy/dx=f(x)g(y) as (1/g(y))dy=f(x)dx, then integrate both sides. Add +C on one side and solve for y.', 'Students add +C to both sides (only needed on one) or forget to include it at all.', 'Separate and integrate to find the general solution; apply initial condition to find particular solution.'),
          _t('Applying Initial Conditions', 'After finding y=F(x)+C, substitute the initial condition (x₀,y₀) to solve for C. The result is the particular solution.', 'Students forget to solve for C after integrating; the general solution with undetermined C is not the particular solution.', 'Correctly apply y(x₀)=y₀ to determine C in the general solution.'),
          _t('Exponential Growth and Decay', 'dy/dt=ky has solution y=y₀e^{kt}. If k>0: growth; k<0: decay. Half-life/doubling time derived from this model.', 'Students write y=Ce^{kt} but forget that C=y₀ (initial value) from the initial condition.', 'Set up and solve exponential growth/decay problems from initial conditions and given rate constant.')],
         [('separable DE', 'One that can be written as g(y)dy=f(x)dx'),
          ('general solution', 'y=F(x)+C; family of all solutions'),
          ('particular solution', 'Specific solution after C is determined by initial condition'),
          ('exponential model', 'dy/dt=ky → y=y₀e^{kt}')],
         ['Solve separable differential equations analytically', 'Apply initial conditions to find particular solutions', 'Set up and interpret exponential growth/decay models'],
         ['Separable DE is the #1 tested DE type on the AP® exam', 'Often appears as a multi-part FR: slope field → solve → apply IC → interpret', 'Exponential growth/decay in both context problems and pure math'],
         ['Solve dy/dx=xy with y(0)=3', 'A bacteria population doubles in 5 hours starting at 200; write the model'],
         [('Solve dy/dx=x/y with y(1)=2.', ['Separate: y dy=x dx', 'Integrate: y²/2=x²/2+C', 'Apply y(1)=2: 4/2=1/2+C → C=3/2', 'Particular: y²=x²+3 → y=√(x²+3)']),
          ('Solve dy/dx=2y with y(0)=5.', ['Exponential: y=Ce^{2x}', 'Apply IC: 5=Ce⁰=C', 'Particular: y=5e^{2x}', 'Alternatively separate: dy/y=2dx → ln|y|=2x+C']),
          ('A population grows at 3% per year. Starting at 1000, find P(t).', ['dP/dt=0.03P; solution P=Ce^{0.03t}', 'P(0)=1000 → C=1000', 'P(t)=1000e^{0.03t}', 'After 10 years: P(10)≈1350']),
          ('Carbon-14 decays at rate k=−0.000121/yr. How long until 75% remains?', ['y=y₀e^{kt}; set y=0.75y₀', '0.75=e^{−0.000121t}', 'ln(0.75)=−0.000121t', 't=−ln(0.75)/0.000121≈2384 years']),
          ('Solve dy/dx=e^{x+y} (hint: e^{x+y}=eˣ·eʸ).', ['Separate: e^{−y}dy=eˣ dx', 'Integrate: −e^{−y}=eˣ+C', 'Solve: e^{−y}=−eˣ−C → y=−ln(−eˣ−C)', 'Apply IC to find specific C'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Separable DEs', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the steps to solve a separable DE', 'Solve dy/dx=y·cos(x) with y(0)=2', 'Write the exponential decay formula and define each variable']),

      _l('Euler\'s Method (BC)',
         [_t('Euler\'s Method Algorithm', 'Start at (x₀,y₀). At each step: y_{n+1}=y_n+f(x_n,y_n)·Δx and x_{n+1}=x_n+Δx. Approximate the solution curve by following slope field segments.', 'Students use the new x-value when computing the slope for the current step; always use the current point (x_n, y_n) for the slope.', 'Apply Euler\'s method with given step size for 2–3 steps and compare to exact solution.'),
          _t('Accuracy of Euler\'s Method', 'Smaller step size Δx gives a more accurate approximation. If f is concave up, Euler\'s underestimates; concave down, it overestimates.', 'Students think Euler\'s method is always an underestimate; concavity of the solution determines the direction of error.', 'Determine whether Euler\'s estimate is an over- or under-estimate based on the concavity of the actual solution.'),
          _t('Logistic Growth (BC)', 'dP/dt=kP(1−P/M) where M is carrying capacity. Solution S-curves approach M asymptotically. Fastest growth at P=M/2.', 'Students confuse the logistic with exponential models; logistic growth slows as P approaches M, while exponential grows without bound.', 'Interpret parameters in logistic model; find where growth rate is maximum.')],
         [('Euler\'s method', 'y_{n+1}=y_n+f(x_n,y_n)·Δx; step-by-step approximation'),
          ('step size', 'Δx; smaller step gives better approximation'),
          ('logistic growth', 'dP/dt=kP(1−P/M); S-shaped solution curve'),
          ('carrying capacity', 'M; the upper limit that the logistic solution approaches')],
         ['Execute Euler\'s method for 2–3 steps from a given initial condition', 'Determine over/under-estimate based on concavity', 'Interpret logistic growth model parameters'],
         ['Euler\'s method is BC-only; tested in FR', 'Logistic growth tested in BC MC and FR', 'Over/under-estimate question common in Euler\'s method FR'],
         ['Apply Euler\'s to dy/dx=x+y, y(0)=1, Δx=0.5, two steps', 'Describe logistic growth behavior near P=0 and P=M'],
         [('Apply Euler\'s method to dy/dx=x+y, y(0)=1 with Δx=0.5 for two steps.', ['Step 1: slope at (0,1): 0+1=1; y₁=1+1(0.5)=1.5; x₁=0.5', 'Step 2: slope at (0.5,1.5): 0.5+1.5=2; y₂=1.5+2(0.5)=2.5; x₂=1', 'Euler approximation: y(1)≈2.5', 'Actual: y(1)=2e−1≈4.44; Euler underestimates (concave up)']),
          ('For Euler\'s method, is the estimate an over or underestimate if the solution is concave up?', ['Concave up means the slope is increasing', 'Euler\'s uses the slope at the left end of each interval', 'The actual curve rises faster than the Euler step predicts', 'Euler underestimates when solution is concave up']),
          ('A logistic model has dP/dt=0.4P(1−P/500). Find the carrying capacity and maximum growth rate point.', ['Carrying capacity M=500', 'Maximum growth at P=M/2=250', 'At P=250: dP/dt=0.4(250)(1−0.5)=50', 'Growth slows toward 0 as P→500']),
          ('Why does logistic growth produce an S-curve?', ['Near P=0: growth is nearly exponential (1−P/M≈1)', 'Near P=M: growth slows as (1−P/M)→0', 'Inflection at P=M/2: fastest growth', 'The curve rises quickly then levels off at M']),
          ('Apply one step of Euler\'s method to dy/dx=y², y(0)=1, Δx=0.1.', ['Slope at (0,1): 1²=1', 'y₁=1+1(0.1)=1.1; x₁=0.1', 'Euler approximation after one step: y(0.1)≈1.1', 'Actual solution y=1/(1−x) gives y(0.1)≈1.111'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Euler\'s Method', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the Euler\'s method update formula', 'Explain why smaller Δx gives a better approximation', 'Describe the shape and meaning of a logistic growth curve']),

      _l('Applications of Differential Equations',
         [_t('Newton\'s Law of Cooling', 'dT/dt=k(T−T_env). Solution: T(t)=T_env+(T₀−T_env)e^{kt}, k<0. Temperature approaches ambient exponentially.', 'Students forget to subtract T_env before applying exponential formula; the DE is for (T−T_env), not T itself.', 'Set up and solve Newton\'s cooling problems with given initial and ambient temperatures.'),
          _t('Mixing Problems', 'Rate of change of substance = rate in − rate out. Set up a DE for the amount Q(t) of substance in a tank, solve separably or recognize linear first-order DE.', 'Students forget that rate out depends on current concentration Q(t)/V(t), making the DE depend on Q.', 'Write the differential equation for Q(t) in a mixing problem and identify the variables.'),
          _t('Interpreting Solutions in Context', 'After solving a DE, interpret constants and behavior: What does C represent? When does the solution approach a limit? What are the units?', 'Students report mathematical answers without contextual interpretation; AP® FR always requires context-based explanation of results.', 'Translate mathematical results from DE solutions into meaningful contextual statements with correct units.')],
         [('Newton\'s Law of Cooling', 'dT/dt=k(T−T_a); T approaches ambient T_a exponentially'),
          ('mixing problem', 'dQ/dt = (rate in) − (rate out); Q is amount of substance'),
          ('initial condition', 'The value Q(t₀)=Q₀ used to find the particular solution'),
          ('long-term behavior', 'As t→∞, solutions to these DEs approach equilibrium values')],
         ['Set up Newton\'s cooling and mixing DEs from context', 'Solve the DE with initial conditions', 'Interpret the solution in context with correct units'],
         ['Context-heavy DE problems appear in FR', 'Newton\'s cooling is a standard template problem', 'Interpreting long-term behavior tested in MC and FR'],
         ['Coffee at 95°C cools in a 20°C room; write and solve the DE', 'Tank with 50L pure water; salt enters at 2g/min, exits at 2L/min'],
         [('Coffee at 90°C in a 20°C room. After 5 min, T=70°C. Find T(t).', ['dT/dt=k(T−20); solution T=20+Ce^{kt}', 'T(0)=90: 90=20+C → C=70', 'T(5)=70: 70=20+70e^{5k} → e^{5k}=50/70=5/7', 'k=(1/5)ln(5/7); T(t)=20+70e^{kt}']),
          ('Find when the coffee reaches 40°C.', ['40=20+70e^{kt}; e^{kt}=20/70=2/7', 't=ln(2/7)/k=ln(2/7)/[(1/5)ln(5/7)]', '=5·ln(2/7)/ln(5/7)', 'Approximately 17.5 minutes']),
          ('A tank has 100L of pure water. Salt enters at 3g/min and the well-mixed solution exits at 3L/min. Write the DE for Q(t).', ['Rate in: 3 g/min', 'Rate out: (Q/100)·3=3Q/100 g/min', 'dQ/dt=3−3Q/100', 'Linear first-order DE; long-term Q→100 g']),
          ('Interpret the constant C in T(t)=T_a+Ce^{kt}.', ['C=T(0)−T_a (initial temperature excess above ambient)', 'C measures how far above/below ambient the object starts', 'As t→∞, Ce^{kt}→0 (k<0), so T→T_a', 'T asymptotically approaches ambient temperature']),
          ('A population satisfies dP/dt=0.5P with P(0)=200. When does P=1000?', ['P=200e^{0.5t}', '1000=200e^{0.5t} → e^{0.5t}=5', 't=2ln5≈3.22', 'About 3.2 time units'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Khan Academy — Differential Equations', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write Newton\'s Law of Cooling DE from context', 'Interpret the long-term behavior of a mixing tank solution', 'Explain what the constant C represents in an exponential solution']),
  ],
  'unit_qs': [
      ('For dy/dx=xy, describe the zero-isoclines in the slope field.', ['dy/dx=0 when x=0 or y=0', 'Zero-isoclines are the x-axis and y-axis', 'Slopes are positive in Q1 and Q3 (same sign product)', 'Negative in Q2 and Q4']),
      ('Solve dy/dx=3x²y with y(0)=2.', ['Separate: dy/y=3x² dx', 'Integrate: ln|y|=x³+C', 'y=Ce^{x³}; y(0)=2 → C=2', 'Particular: y=2e^{x³}']),
      ('Apply Euler\'s method to dy/dx=y, y(0)=1, Δx=0.5, two steps. Compare to actual.', ['Step 1: y₁=1+1(0.5)=1.5; x₁=0.5', 'Step 2: y₂=1.5+1.5(0.5)=2.25; x₂=1', 'Actual y(1)=e≈2.718; Euler underestimates', 'Solution y=eˣ is concave up → Euler underestimates']),
      ('A logistic population has carrying capacity 800 and currently 200. Is growth speeding up or slowing down?', ['P=200 < M/2=400', 'Population is below the inflection point', 'Growth rate is still increasing (speeding up)', 'Will slow when P exceeds 400']),
      ('Verify that y=2e^{3x}−x is NOT a solution to dy/dx=3y.', ['Compute dy/dx=6e^{3x}−1', 'Compute 3y=6e^{3x}−3x', 'These are not equal (−1 ≠ −3x)', 'y=2e^{3x}−x is not a solution']),
      ('Solve dP/dt=0.02P(1−P/1000), find where growth is fastest.', ['Logistic DE; carrying capacity M=1000', 'Fastest growth at P=M/2=500', 'Rate there: 0.02(500)(0.5)=5 per time unit', 'This is the inflection point of the logistic S-curve']),
      ('A substance cools from 80°C to 60°C in 10 min in a 20°C room. Find k.', ['T(t)=20+60e^{kt}; T(10)=60', '60=20+60e^{10k} → e^{10k}=40/60=2/3', 'k=(1/10)ln(2/3)≈−0.0405/min', 'Negative k confirms cooling']),
      ('Find the general solution to dy/dx=(x+1)/y.', ['Separate: y dy=(x+1)dx', 'Integrate: y²/2=x²/2+x+C', 'y²=x²+2x+2C', 'y=±√(x²+2x+C) (rename 2C as C)']),
      ('Sketch and describe the solution curves to dy/dx=1 (slope field).', ['dy/dx=1 everywhere → all slopes equal 1', 'Slope field has identical 45° segments', 'Solution curves are lines y=x+C', 'Parallel lines shifted vertically by C']),
      ('A tank has Q(t) satisfying dQ/dt=5−Q/20. What is the long-term amount of substance?', ['At equilibrium: dQ/dt=0 → 5=Q/20 → Q=100', 'Q approaches 100 as t→∞', 'This is the steady-state concentration', 'Rate in equals rate out at equilibrium']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=fYyARMqiaag',
},

{
  'num': 8, 'title': 'Applications of Integration',
  'file': 'ap-calculus-bc-8-unit-8-applications-of-integration.html',
  'desc': 'Apply integration to compute volumes of solids, average values, arc length, and accumulated change in context.',
  'gateway': [
      'Compute the average value of a function on an interval.',
      'Find volumes of solids of revolution using disk, washer, and shell methods.',
      'Set up and evaluate arc length integrals (BC).',
      'Interpret and apply integration in motion and accumulation contexts.',
  ],
  'lessons': [
      _l('Average Value and Mean Value Theorem for Integrals',
         [_t('Average Value Formula', 'f_avg=(1/(b−a))∫_a^b f(x)dx. Divide the integral by the interval length. Represents the constant height whose rectangle has the same area as under f.', 'Students use (f(a)+f(b))/2 (trapezoidal average) instead of the integral formula; only the integral gives the true average value.', 'Compute average value using the integral formula and interpret it in context.'),
          _t('Mean Value Theorem for Integrals', 'If f is continuous on [a,b], there exists c in (a,b) such that f(c)=f_avg. Guarantees a point where f equals its average.', 'Students confuse MVT for integrals with MVT for derivatives; one guarantees f(c)=average value, the other f\'(c)=average rate.', 'Apply MVT for integrals to guarantee c and find its value for specific functions.'),
          _t('Interpreting Average Value in Context', 'Average value of a rate gives average rate; average value of a position gives average position. Always include units and interpret in the specific context given.', 'Students compute average value correctly but neglect to interpret what it means in the stated context.', 'State average value with correct units and give a sentence interpreting its meaning.')],
         [('average value', 'f_avg=(1/(b−a))∫_a^b f dx'),
          ('MVT for integrals', '∃c∈(a,b) with f(c)=f_avg'),
          ('interpretation', 'Average value represents the constant level with equal area'),
          ('units', 'Average value has same units as f(x)')],
         ['Compute average value using integration', 'Apply MVT for integrals to find c', 'Interpret average value in physical context'],
         ['Average value appears in both MC and FR', 'MVT for integrals tested as justify/explain', 'Always requires interpretation in FR'],
         ['Find average value of f(x)=x² on [0,3]', 'Find c guaranteed by MVT for integrals for f(x)=cos x on [0,π/2]'],
         [('Find the average value of f(x)=x² on [0,3].', ['f_avg=(1/3)∫_0^3 x² dx=(1/3)[x³/3]_0^3', '=(1/3)(9)=3', 'Average value = 3', 'There is some c∈(0,3) where f(c)=3, i.e., c=√3']),
          ('Find c guaranteed by MVT for integrals for f(x)=sin(x) on [0,π].', ['f_avg=(1/π)∫_0^π sin x dx=(1/π)(2)=2/π', 'Set f(c)=2/π: sin(c)=2/π', 'c=arcsin(2/π)≈0.69', 'c is in (0,π) ✓']),
          ('A car\'s velocity is v(t)=t²+2 mph on [0,3]. Find average velocity and interpret.', ['v_avg=(1/3)∫_0^3(t²+2)dt=(1/3)[t³/3+2t]_0^3', '=(1/3)(9+6)=5 mph', 'Average velocity is 5 mph', 'On average, the car traveled at 5 mph over the 3-hour trip']),
          ('Is average value the same as average of the endpoints? Explain.', ['No; (f(a)+f(b))/2 is the trapezoidal approximation', 'True average requires integrating f over the interval', 'For linear f, both agree; for curved f, they differ', 'Integral average accounts for all values, not just endpoints']),
          ('Find the average value of f(x)=eˣ on [0,2].', ['f_avg=(1/2)∫_0^2 eˣ dx=(1/2)[eˣ]_0^2', '=(1/2)(e²−1)=(e²−1)/2', 'Approximately (7.389−1)/2≈3.19', 'Guaranteed c: eᶜ=(e²−1)/2 → c=ln((e²−1)/2)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Average Value', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the average value formula', 'Interpret average value of a velocity function', 'Find c for f(x)=x³ on [0,2] using MVT for integrals']),

      _l('Volumes of Solids of Revolution',
         [_t('Disk Method', 'Volume=π∫_a^b [f(x)]² dx. Rotate a region bounded by f and the x-axis around the x-axis. Each cross-section is a disk with radius f(x).', 'Students forget the π and the square; V=π∫r² dx, not ∫r dx.', 'Set up and evaluate disk method integrals for revolution around the x-axis.'),
          _t('Washer Method', 'Volume=π∫_a^b ([R(x)]²−[r(x)]²) dx, where R is outer radius and r is inner radius. Used when the solid has a hole.', 'Students use R²−r² inside the square: (R−r)² ≠ R²−r². The formula subtracts areas, not radii.', 'Set up washer method when the region is between two curves rotated around an axis.'),
          _t('Shell Method', 'Volume=2π∫_a^b x·f(x)dx. Rotating a region around the y-axis using vertical strips. Useful when washer method is cumbersome.', 'Students use disk/washer for y-axis revolution; shell method avoids re-expressing x=g(y) by keeping integration in x.', 'Set up and evaluate shell method integrals for revolution around the y-axis.')],
         [('disk method', 'V=π∫[f(x)]²dx; rotation around x-axis'),
          ('washer method', 'V=π∫([R]²−[r]²)dx; rotation with hole'),
          ('shell method', 'V=2π∫x·f(x)dx; rotation around y-axis'),
          ('axis of revolution', 'The line around which the region is rotated')],
         ['Set up and evaluate disk, washer, and shell integrals', 'Identify outer and inner radius for washer problems', 'Choose the appropriate method based on axis and region'],
         ['Volume problems are guaranteed in AP® FR (Units 8)', 'Washer method most common; shell occasionally', 'Must set up integral correctly — partial credit for setup even with arithmetic errors'],
         ['Find volume of y=√x on [0,4] rotated around x-axis (disk)', 'Find volume between y=x and y=x² rotated around x-axis (washer)'],
         [('Find the volume when y=√x on [0,4] is rotated around the x-axis.', ['Disk method: V=π∫_0^4(√x)² dx=π∫_0^4 x dx', 'V=π[x²/2]_0^4=π(8)=8π', 'Volume = 8π cubic units', 'Each slice is a disk of radius √x']),
          ('Find volume between y=x and y=x² on [0,1] rotated around x-axis.', ['On [0,1]: x≥x²; R=x, r=x²', 'V=π∫_0^1(x²−x⁴)dx=π[x³/3−x⁵/5]_0^1', 'V=π(1/3−1/5)=π(2/15)', 'V=2π/15']),
          ('Find volume when y=x² on [0,2] is rotated around y-axis using shells.', ['Shell: V=2π∫_0^2 x·x² dx=2π∫_0^2 x³ dx', 'V=2π[x⁴/4]_0^2=2π(4)=8π', 'Volume = 8π', 'Shell method avoids solving for x as function of y']),
          ('Set up (don\'t evaluate) the volume of y=sin(x) on [0,π] rotated around x-axis.', ['Disk method: V=π∫_0^π sin²(x)dx', 'Cannot simplify further without trig identities', 'V=π∫_0^π sin²(x)dx=π·(π/2)=π²/2', 'Using identity sin²x=(1−cos2x)/2']),
          ('Find volume of y=1/x on [1,3] rotated around x-axis.', ['Disk: V=π∫_1^3(1/x)² dx=π∫_1^3 x^{-2} dx', 'V=π[−1/x]_1^3=π(−1/3+1)=2π/3', 'Volume = 2π/3', 'Gabriel\'s horn analogy'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Disk and Washer Method', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the disk method formula', 'Explain the difference between disk and washer methods', 'Set up the shell method for y=x³ on [0,2] around the y-axis']),

      _l('Arc Length and Surface Area (BC)',
         [_t('Arc Length Formula', 'L=∫_a^b √(1+[f\'(x)]²) dx. Derived by summing infinitesimal hypotenuses ds=√(dx²+dy²) along the curve.', 'Students forget the 1+ inside the square root; without it, the formula would give the projected length, not the actual curve length.', 'Set up arc length integrals; recognize they often cannot be simplified without a calculator.'),
          _t('Parametric Arc Length', 'For x=f(t), y=g(t): L=∫_α^β √((dx/dt)²+(dy/dt)²) dt. This is the integral of the speed over the time interval.', 'Students use the Cartesian arc length formula for parametric curves; the parametric version integrates speed, not 1+(dy/dx)².', 'Set up parametric arc length integral; identify the integrand as speed.'),
          _t('Surface Area of Revolution (BC)', 'S=2π∫_a^b f(x)√(1+[f\'(x)]²)dx when rotating around x-axis. Combines arc length with the circumference at each point.', 'Students confuse surface area with volume; surface area integrates 2πr·ds (strip of surface), volume integrates πr²·dx (disk).', 'Set up surface area integrals and distinguish them from volume integrals.')],
         [('arc length', 'L=∫√(1+(f\'(x))²)dx; total length along curve'),
          ('parametric arc length', 'L=∫√((dx/dt)²+(dy/dt)²)dt = ∫speed dt'),
          ('surface area', 'S=2π∫f(x)√(1+(f\'(x))²)dx; rotating curve around x-axis'),
          ('ds', 'Infinitesimal arc length element: √(dx²+dy²)')],
         ['Set up arc length integrals from function formula', 'Set up parametric arc length as integral of speed', 'Distinguish surface area from volume integrals'],
         ['Arc length tested in BC FR — must know the setup', 'Parametric arc length = speed integral (important connection)', 'Surface area in BC MC and FR'],
         ['Set up arc length of y=x² on [0,2]', 'Set up arc length of x=cos t, y=sin t for t∈[0,π]'],
         [('Set up the arc length of y=x² on [0,2].', ['f\'(x)=2x; (f\'(x))²=4x²', 'L=∫_0^2√(1+4x²)dx', 'Cannot simplify to closed form easily', 'Numerical value ≈ 4.65']),
          ('Find the arc length of y=x^{3/2} on [0,4].', ['f\'(x)=(3/2)x^{1/2}; (f\'(x))²=9x/4', 'L=∫_0^4√(1+9x/4)dx', 'Let u=1+9x/4; du=9/4 dx', 'L=(8/27)[(1+9x/4)^{3/2}]_0^4=(8/27)(10^{3/2}−1)']),
          ('Find arc length of parametric x=3cos t, y=3sin t on [0,π].', ['dx/dt=−3sin t; dy/dt=3cos t', 'Speed=√(9sin²t+9cos²t)=3', 'L=∫_0^π 3 dt=3π', 'Half the circumference of circle radius 3 ✓']),
          ('Set up the surface area when y=√x on [1,4] is rotated around x-axis.', ['f\'(x)=1/(2√x); (f\'(x))²=1/(4x)', 'S=2π∫_1^4√x·√(1+1/(4x))dx', 'S=2π∫_1^4√(x+1/4)dx', 'Simplify inside radical: x+1/4']),
          ('Interpret ∫_a^b √((dx/dt)²+(dy/dt)²)dt as speed.', ['The integrand is the magnitude of velocity vector', 'Speed = |v(t)| = √((dx/dt)²+(dy/dt)²)', 'Integrating speed over time gives total distance traveled', 'Not the same as displacement'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Arc Length', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write the arc length formula from memory', 'Explain why 1 appears under the square root in arc length', 'State how arc length and speed are related for parametric curves']),

      _l('Integration in Motion and Accumulation Contexts',
         [_t('Position from Velocity', 'If v(t) is given and s(t₀) is known, then s(t)=s(t₀)+∫_{t₀}^t v(τ)dτ. Total distance = ∫|v(t)|dt; displacement = ∫v(t)dt.', 'Students use total area under v(t) for both displacement and distance; only total area gives distance when split at sign changes of v.', 'Compute position at time t using FTC; compute total distance by splitting at zeros of v.'),
          _t('Accumulated Change from Rates', '∫_a^b r(t)dt = total accumulated change. Works for any rate: flow rate, birth rate, production rate. Always interpret with units.', 'Students compute the integral correctly but forget to add the initial quantity; ∫r dt gives the change, not the final amount.', 'Calculate total accumulation from a rate and add to initial condition to find final amount.'),
          _t('Analyzing Particle Motion with Integrals', 'Speed: |v(t)|. Speeding up: v·a>0. To find farthest right: integrate v from start, find when v=0, check cumulative displacement.', 'Students find where v=0 and assume that\'s the farthest point; they must also check whether the particle moved right or left before that zero.', 'Determine position of a particle at specific times by integrating velocity from known initial position.')],
         [('displacement', '∫v(t)dt; signed, gives net position change'),
          ('total distance', '∫|v(t)|dt; always positive, splits at zeros of v'),
          ('accumulated change', '∫rate dt; final − initial amount'),
          ('initial value', 'Must be added to the integral to get final position or amount')],
         ['Compute displacement and total distance from velocity', 'Add integral of rate to initial value to find final amount', 'Find position at specific time from v(t) and s(t₀)'],
         ['Motion FR problems appear every year on the AP® exam', 'Displacement vs. total distance distinguished in FR', 'Rate problems require adding initial amount to integral'],
         ['Given v(t)=t²−3t on [0,4] and s(0)=2, find s(4) and total distance', 'Water fills tank at r(t)=5+t gal/min; initial 20 gal; find amount after 6 min'],
         [('v(t)=t²−3t on [0,4], s(0)=2. Find s(4).', ['Displacement=∫_0^4(t²−3t)dt=[t³/3−3t²/2]_0^4', '=64/3−24=64/3−72/3=−8/3', 's(4)=2+(−8/3)=−2/3', 'Position is −2/3 at t=4']),
          ('Find total distance for v(t)=t²−3t on [0,4].', ['v=0 at t=0,3; v<0 on (0,3), v>0 on (3,4)', '∫_0^3|t²−3t|dt=∫_0^3(3t−t²)dt=[3t²/2−t³/3]_0^3=9/2', '∫_3^4(t²−3t)dt=[t³/3−3t²/2]_3^4=7/6', 'Total distance=9/2+7/6=27/6+7/6=34/6=17/3']),
          ('Water enters tank at r(t)=5+2t gal/min. Initial volume 30 gal. Find volume at t=4.', ['Change=∫_0^4(5+2t)dt=[5t+t²]_0^4=20+16=36', 'Final volume=30+36=66 gal', 'Must add initial amount', 'Rate × time = change, not total']),
          ('A particle at x=3 has v(t)=sin(πt) for t∈[0,2]. Find x at t=2.', ['Displacement=∫_0^2 sin(πt)dt=[−cos(πt)/π]_0^2', '=−cos(2π)/π+cos(0)/π=−1/π+1/π=0', 'x(2)=3+0=3', 'Particle returns to starting point']),
          ('Interpret: ∫_0^5 r(t)dt=120 where r(t) is population birth rate (people/year).', ['120 people were born over the 5-year period', 'This is the accumulated change, not the final population', 'Must add to initial population to get final count', 'Units: people (rate × time = count)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Motion and Integration', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Explain the difference between displacement and total distance', 'Write the formula for final amount given initial amount and rate', 'Calculate total distance for v(t)=cos(t) on [0,π]']),
  ],
  'unit_qs': [
      ('Find the average value of f(x)=sin(x) on [0,π].', ['f_avg=(1/π)∫_0^π sin x dx=(1/π)[−cos x]_0^π', '=(1/π)(1+1)=2/π', 'Average value = 2/π', 'c exists with sin(c)=2/π by MVT for integrals']),
      ('Find volume when y=x² on [0,3] is rotated around x-axis.', ['Disk: V=π∫_0^3 x⁴ dx=π[x⁵/5]_0^3', 'V=π(243/5)=243π/5', 'Volume = 243π/5', 'Each disk has radius x²']),
      ('Find volume between y=√x and y=x/2 on [0,4] rotated around x-axis.', ['On [0,4]: √x≥x/2; R=√x, r=x/2', 'V=π∫_0^4(x−x²/4)dx=π[x²/2−x³/12]_0^4', 'V=π(8−64/12)=π(8−16/3)=8π/3', 'Washer method']),
      ('Set up arc length of y=x^{1/2} on [1,9].', ['f\'(x)=1/(2√x); (f\')²=1/(4x)', 'L=∫_1^9√(1+1/(4x))dx', '=∫_1^9√((4x+1)/(4x))dx', 'Cannot simplify to elementary form']),
      ('A particle has v(t)=e^t−2, s(0)=0. Find s(ln 4).', ['s(t)=∫_0^t(eˣ−2)dx=[eˣ−2x]_0^t', 's(t)=eᵗ−2t−1', 's(ln4)=4−2ln4−1=3−2ln4', 'Approximately 0.23']),
      ('Water drains at r(t)=10−2t L/min for 0≤t≤5. Initial 200L. Find final volume.', ['∫_0^5(10−2t)dt=[10t−t²]_0^5=50−25=25', 'Final volume=200−25=175 L', 'Wait — rate is draining so subtract', '(Or treat r as negative: ∫(−10+2t)dt=−25; 200+(−25)=175 ✓)']),
      ('Find volume when the region between y=x and x-axis on [0,2] is rotated around the y-axis using shells.', ['Shell: V=2π∫_0^2 x·x dx=2π∫_0^2 x² dx', 'V=2π[x³/3]_0^2=2π(8/3)=16π/3', 'Volume = 16π/3', 'Shell formula: 2π∫x·f(x)dx']),
      ('Find c in (0,4) where f(c) equals its average, for f(x)=x+1.', ['f_avg=(1/4)∫_0^4(x+1)dx=(1/4)[x²/2+x]_0^4=(1/4)(8+4)=3', 'Set f(c)=3: c+1=3 → c=2', 'c=2∈(0,4) ✓', 'MVT for integrals guarantees this c exists']),
      ('Find total distance of v(t)=t−2 on [0,4].', ['v=0 at t=2; v<0 on (0,2), v>0 on (2,4)', '∫_0^2(2−t)dt=[2t−t²/2]_0^2=2', '∫_2^4(t−2)dt=[t²/2−2t]_2^4=2', 'Total distance=2+2=4']),
      ('Set up surface area when y=sin(x) on [0,π] is rotated around x-axis.', ['f\'(x)=cos x; (f\')²=cos²x', 'S=2π∫_0^π sin(x)√(1+cos²x)dx', 'Cannot evaluate in closed form without calculator', 'Setup is complete; numerical value ≈ 14.42']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=fYyARMqiaag',
},

{
  'num': 9, 'title': 'Infinite Sequences and Series (BC)',
  'file': 'ap-calculus-bc-9-unit-9-infinite-sequences-and-series.html',
  'desc': 'Study convergence of sequences and series, use convergence tests, and represent functions as power series and Taylor/Maclaurin series.',
  'gateway': [
      'Determine convergence or divergence of sequences and series.',
      'Apply convergence tests: Ratio, Alternating, Integral, Comparison.',
      'Find Taylor and Maclaurin series for standard functions.',
      'Bound approximation errors using the Alternating Series Estimation Theorem.',
  ],
  'lessons': [
      _l('Sequences and Series Convergence',
         [_t('Convergence of Sequences', 'A sequence {aₙ} converges if lim_{n→∞}aₙ = L (finite). Diverges if the limit does not exist or is ±∞.', 'Students confuse convergence of sequences with convergence of series; a convergent sequence means terms → L, while a convergent series means partial sums → S.', 'Evaluate lim_{n→∞}aₙ for given sequences and classify as convergent or divergent.'),
          _t('Geometric and p-Series', 'Geometric series Σarⁿ converges if |r|<1 to a/(1−r). p-Series Σ1/nᵖ converges if p>1. These are the reference series for comparison tests.', 'Students use p-series test on non-p-series; ensure the series is exactly 1/nᵖ before applying.', 'Identify geometric and p-series; state convergence condition and sum for geometric.'),
          _t('Divergence (nth Term) Test', 'If lim_{n→∞}aₙ ≠ 0, then Σaₙ diverges. If lim aₙ=0, the test is inconclusive — does not imply convergence.', 'Students conclude convergence when nth term limit = 0; the nth term test only proves divergence.', 'Apply nth term test to quickly identify divergent series; recognize when it is inconclusive.')],
         [('convergent sequence', 'lim_{n→∞}aₙ=L for finite L'),
          ('geometric series', 'Σarⁿ; converges to a/(1−r) when |r|<1'),
          ('p-series', 'Σ1/nᵖ; converges iff p>1'),
          ('nth term test', 'Diverges if lim aₙ ≠ 0; inconclusive if lim aₙ = 0')],
         ['Determine convergence of sequences by limits', 'Identify and evaluate geometric series', 'Apply nth term test correctly'],
         ['Geometric series tested in both MC and FR; must find sum', 'p-Series used in comparison tests', 'Nth term test a quick first check in MC'],
         ['Classify Σ(0.5)ⁿ and Σ1/n as convergent or divergent', 'Apply nth term test to Σn/(n+1)'],
         [('Does the sequence aₙ=(2n+1)/(n+3) converge?', ['lim_{n→∞}(2n+1)/(n+3)=2', 'Sequence converges to 2', 'Divide by n: (2+1/n)/(1+3/n)→2', 'Convergent']),
          ('Find the sum of Σ_{n=0}^∞ (2/3)ⁿ.', ['Geometric: a=1, r=2/3, |r|<1 → converges', 'Sum = 1/(1−2/3)=1/(1/3)=3', 'Sum = 3', 'Formula: a/(1−r)']),
          ('Does Σ1/n² converge?', ['p-series with p=2>1', 'Converges', 'Sum = π²/6 (known result)', 'p>1 guarantees convergence']),
          ('Apply nth term test to Σn/(n+1).', ['lim_{n→∞}n/(n+1)=1≠0', 'By nth term test, series diverges', 'Terms do not approach 0', 'Definitively divergent']),
          ('Apply nth term test to Σ1/n.', ['lim_{n→∞}1/n=0', 'Test is inconclusive', 'Cannot conclude convergence from this test', 'Harmonic series actually diverges (p=1, p-series)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Sequences and Series', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the conditions for geometric series convergence', 'Explain why nth term test cannot prove convergence', 'Classify Σ1/n^{1/2} using p-series test']),

      _l('Convergence Tests',
         [_t('Ratio and Root Tests', 'Ratio Test: if lim|a_{n+1}/aₙ|=L<1, converges; L>1, diverges; L=1, inconclusive. Best for factorials and exponentials. Root Test: lim|aₙ|^{1/n}=L, same criteria.', 'Students apply ratio test to series with polynomials (where it gives L=1, inconclusive); ratio test is for series with factorials or exponentials.', 'Apply ratio test to series with n! or aⁿ; recognize inconclusive result means switch tests.'),
          _t('Alternating Series Test', 'Σ(−1)ⁿbₙ converges if: (1) bₙ>0, (2) bₙ is decreasing, (3) lim bₙ=0. Error bounded by first omitted term.', 'Students apply AST without verifying bₙ is decreasing; all three conditions must be checked.', 'Verify all three AST conditions; use error bound to estimate partial sum accuracy.'),
          _t('Integral and Comparison Tests', 'Integral Test: if f is continuous, positive, decreasing and aₙ=f(n), then Σaₙ and ∫f converge/diverge together. Direct Comparison: Σaₙ≤Σbₙ; if Σbₙ converges, so does Σaₙ.', 'Students apply integral test to series with non-monotone terms; verify the function is decreasing first.', 'Use integral test for series like Σ1/(n ln n); use comparison to bound by known series.')],
         [('ratio test', 'lim|a_{n+1}/aₙ|; L<1 converges, L>1 diverges, L=1 inconclusive'),
          ('alternating series test', 'Σ(−1)ⁿbₙ converges if bₙ decreasing to 0'),
          ('AST error bound', '|Error| ≤ b_{n+1} (first omitted term)'),
          ('comparison test', 'Bound aₙ above/below by known convergent/divergent series')],
         ['Apply ratio test to factorial and exponential series', 'Verify all three AST conditions', 'Use comparison or integral test for series without factorials or alternating sign'],
         ['At least one convergence test question per exam', 'AST error bound is a distinct testable skill', 'Ratio test with n! in BC FR'],
         ['Test Σn!/3ⁿ with ratio test', 'Test Σ(−1)ⁿ/n with alternating series test'],
         [('Apply ratio test to Σn!/2ⁿ.', ['aₙ=n!/2ⁿ; a_{n+1}=(n+1)!/2^{n+1}', 'Ratio: (n+1)!/2^{n+1} · 2ⁿ/n!=(n+1)/2', 'As n→∞: (n+1)/2→∞>1', 'Series diverges']),
          ('Apply ratio test to Σ2ⁿ/n!.', ['a_{n+1}/aₙ=2^{n+1}/(n+1)!·n!/2ⁿ=2/(n+1)', 'As n→∞: 2/(n+1)→0<1', 'Series converges', 'Exponential grows slower than factorial']),
          ('Test Σ(−1)ⁿ/√n for convergence.', ['bₙ=1/√n; bₙ>0 ✓', 'bₙ decreasing since 1/√n→0 ✓', 'lim bₙ=0 ✓', 'All three AST conditions met; series converges']),
          ('Estimate error if Σ(−1)ⁿ/n² is approximated by first 3 terms.', ['AST error ≤ b₄=1/16', '|Error| ≤ 1/16', 'First 3 terms: 1−1/4+1/9', 'Actual sum minus partial sum is at most 1/16']),
          ('Use comparison to test Σ1/(n²+1) for convergence.', ['1/(n²+1)<1/n²', 'Σ1/n² is a convergent p-series (p=2)', 'By direct comparison, Σ1/(n²+1) converges', 'Upper bounding by a convergent series works'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Convergence Tests', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State three conditions for the alternating series test', 'Apply ratio test to Σn³/3ⁿ', 'Explain what the AST error bound guarantees']),

      _l('Power Series and Radius of Convergence',
         [_t('Power Series', 'A power series Σcₙ(x−a)ⁿ converges for |x−a|<R (radius of convergence R). At endpoints, test separately. Converges absolutely inside, may converge at endpoints.', 'Students include the endpoints automatically; endpoints must be tested individually (they may converge at one, both, or neither).', 'Find radius and interval of convergence using the ratio test.'),
          _t('Finding Radius of Convergence', 'Apply ratio test to power series: lim|c_{n+1}(x−a)^{n+1} / cₙ(x−a)ⁿ| = |x−a|·L < 1 gives R=1/L. If L=0, R=∞; L=∞, R=0.', 'Students solve incorrectly for R; the condition |x−a|·L<1 gives |x−a|<1/L=R.', 'Solve for the radius R by setting the ratio test limit < 1.'),
          _t('Differentiating and Integrating Power Series', 'A power series can be differentiated or integrated term by term within its interval of convergence. The radius of convergence is preserved; check endpoints again for the new series.', 'Students change the radius of convergence when differentiating/integrating; the radius stays the same (endpoints may change).', 'Differentiate or integrate a power series term by term and state the new interval of convergence.')],
         [('power series', 'Σcₙ(x−a)ⁿ; function defined by infinite polynomial centered at a'),
          ('radius of convergence', 'R; series converges for |x−a|<R'),
          ('interval of convergence', '[a−R, a+R] with endpoint tests'),
          ('term-by-term differentiation', 'Valid inside radius of convergence; radius unchanged')],
         ['Find radius and interval of convergence using ratio test', 'Differentiate and integrate power series term by term', 'Test endpoints separately to complete interval of convergence'],
         ['Power series radius/interval of convergence in BC FR', 'Term-by-term operations tested in MC', 'Endpoints require separate investigation'],
         ['Find interval of convergence of Σxⁿ/n', 'Differentiate Σxⁿ/n! term by term'],
         [('Find the radius of convergence of Σxⁿ/n.', ['Ratio test: |x^{n+1}/(n+1)|·|n/xⁿ|=|x|·n/(n+1)', 'As n→∞: |x|·1=|x|', 'Converges if |x|<1; R=1', 'Test x=±1 separately for interval']),
          ('Test endpoints x=1 and x=−1 for Σxⁿ/n.', ['x=1: Σ1/n harmonic → diverges', 'x=−1: Σ(−1)ⁿ/n alternating harmonic → converges', 'Interval of convergence: [−1,1)', 'Right endpoint excluded, left included']),
          ('Differentiate Σ_{n=0}^∞ xⁿ term by term.', ['Σxⁿ=1/(1−x) for |x|<1', 'Differentiate: Σnx^{n−1}=1/(1−x)²', 'Result: Σnx^{n−1}=1/(1−x)² for |x|<1', 'Radius unchanged; endpoint behavior may differ']),
          ('Integrate Σxⁿ term by term.', ['∫Σxⁿdx=Σx^{n+1}/(n+1)+C', 'This is −ln(1−x)+C for |x|<1', 'At x=−1: series converges (by AST)', 'Interval of convergence for integrated series: [−1,1)']),
          ('Find the radius of convergence of Σn!xⁿ.', ['Ratio: |(n+1)!x^{n+1}/(n!xⁿ)|=(n+1)|x|', 'As n→∞: (n+1)|x|→∞ for any x≠0', 'Converges only at x=0; R=0', 'Factorial growth prevents convergence anywhere else'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Power Series', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State what radius of convergence means', 'Find radius of convergence for Σx^n/n²', 'Explain why endpoints require separate testing']),

      _l('Taylor and Maclaurin Series',
         [_t('Taylor Series Formula', 'f(x)=Σ_{n=0}^∞ f^{(n)}(a)/n! · (x−a)ⁿ. Maclaurin series is Taylor at a=0. Memorize: eˣ, sin x, cos x, 1/(1−x).', 'Students try to derive all Taylor series from scratch on the exam; the four standard Maclaurin series must be memorized and recognized.', 'Write and apply the four standard Maclaurin series; manipulate them to find series for related functions.'),
          _t('Lagrange Error Bound', 'If P_n(x) is the nth-degree Taylor polynomial, |error| ≤ M|x−a|^{n+1}/(n+1)! where M is a bound on |f^{(n+1)}| on the interval.', 'Students use the wrong M or wrong n; M must bound the (n+1)th derivative, not the nth.', 'Apply Lagrange error bound to estimate the accuracy of a Taylor polynomial approximation.'),
          _t('Using Series to Evaluate Limits and Integrals', 'Replace f(x) with its Taylor series to evaluate limits (substitute 0/0 forms) or integrals of functions without elementary antiderivatives (like e^{−x²}).', 'Students apply L\'Hôpital\'s rule when a series substitution would be faster and cleaner.', 'Use Maclaurin series for sin x or eˣ to evaluate limits and definite integrals.')],
         [('Maclaurin for eˣ', 'Σxⁿ/n! = 1+x+x²/2!+x³/3!+...'),
          ('Maclaurin for sin x', 'Σ(−1)ⁿx^{2n+1}/(2n+1)! = x−x³/6+x⁵/120−...'),
          ('Maclaurin for cos x', 'Σ(−1)ⁿx^{2n}/(2n)! = 1−x²/2+x⁴/24−...'),
          ('Lagrange error bound', '|Rₙ(x)|≤M|x−a|^{n+1}/(n+1)!')],
         ['Write and recognize the four standard Maclaurin series', 'Apply Lagrange error bound', 'Use series to compute limits and integrals'],
         ['Taylor series is the largest BC FR topic', 'Lagrange error bound appears every year', 'Using series to evaluate limits/integrals tested in MC and FR'],
         ['Write Maclaurin series for e^{2x} and sin(x²)', 'Use Lagrange bound for cos x approximation error'],
         [('Write Maclaurin series for e^{2x}.', ['Replace x with 2x in eˣ series', 'e^{2x}=Σ(2x)ⁿ/n!=Σ2ⁿxⁿ/n!', '=1+2x+4x²/2!+8x³/3!+...', 'Valid for all x']),
          ('Evaluate lim_{x→0}(sin x−x)/x³ using Maclaurin series.', ['sin x=x−x³/6+x⁵/120−...', 'sin x−x=−x³/6+x⁵/120−...', '(sin x−x)/x³=−1/6+x²/120−...', 'As x→0: limit=−1/6']),
          ('Find the Lagrange error bound for cos x ≈ 1−x²/2 at x=0.3.', ['This is P₂(x); error bounded by M|x|³/3!', 'For cos x: |f^{(3)}(x)|=|sin x|≤1, so M=1', 'Error ≤ 1·(0.3)³/6=0.027/6=0.0045', '|Error|≤0.0045']),
          ('Set up ∫_0^1 e^{−x²}dx using series.', ['e^{−x²}=Σ(−x²)ⁿ/n!=Σ(−1)ⁿx^{2n}/n!', '∫_0^1 e^{−x²}dx=Σ(−1)ⁿ/(n!(2n+1)) evaluated 0 to 1', '=1−1/3+1/10−1/42+...', 'Alternating series; partial sums approximate the integral']),
          ('Write the first four terms of the Maclaurin series for sin(x²).', ['Replace x with x² in sin x series', 'sin(x²)=x²−(x²)³/6+(x²)⁵/120−...', '=x²−x⁶/6+x^{10}/120−...', 'Only odd powers of x²'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Taylor Series', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write all four standard Maclaurin series from memory', 'Compute Lagrange error bound for sin x ≈ x at x=0.5', 'Explain how series are used to integrate e^{−x²}']),
  ],
  'unit_qs': [
      ('Test Σ3/(n²+n) for convergence using comparison.', ['3/(n²+n)<3/n² for all n≥1', 'Σ3/n² is 3 times a convergent p-series', 'By comparison, Σ3/(n²+n) converges', 'Could also use limit comparison']),
      ('Find the sum of Σ_{n=1}^∞ (1/4)^n.', ['Geometric: a=1/4, r=1/4, |r|<1', 'Sum from n=1: a/(1−r)=(1/4)/(3/4)=1/3', 'Sum = 1/3', 'Note: starts at n=1, not n=0']),
      ('Apply alternating series test to Σ(−1)ⁿ·n/(n²+1).', ['bₙ=n/(n²+1); bₙ>0 ✓', 'bₙ decreasing (check b\' or compare terms) ✓', 'lim n/(n²+1)=0 ✓', 'All conditions met; series converges']),
      ('Find radius of convergence of Σn·xⁿ.', ['Ratio: |(n+1)x^{n+1}/(nxⁿ)|=|x|·(n+1)/n', 'As n→∞: |x|·1=|x|', 'R=1', 'Test endpoints separately']),
      ('Write Maclaurin series for cos(2x) through x⁴ term.', ['cos x=1−x²/2!+x⁴/4!−...', 'cos(2x)=1−(2x)²/2+(2x)⁴/24−...', '=1−2x²+2x⁴/3−...', 'Replace x with 2x']),
      ('Compute Lagrange error bound for eˣ ≈ 1+x at x=0.2.', ['P₁(x)=1+x; error uses n=1, so (n+1)=2', 'f^{(2)}(x)=eˣ; on [0,0.2], max eˣ=e^{0.2}<2, so M=2', 'Error ≤ 2(0.2)²/2=0.04', '|R₁(0.2)|≤0.04']),
      ('Does the sequence aₙ=cos(n)/n converge?', ['|cos(n)/n|≤1/n→0', 'By squeeze theorem, aₙ→0', 'Converges to 0', 'Even though cos(n) oscillates, 1/n dominates']),
      ('Use series to evaluate lim_{x→0}(1−cos x)/x².', ['cos x=1−x²/2+x⁴/24−...', '1−cos x=x²/2−x⁴/24+...', '(1−cos x)/x²=1/2−x²/24+...', 'As x→0: limit=1/2']),
      ('Test Σ(−1)ⁿ/n! for absolute convergence.', ['Σ1/n!: ratio test: (1/(n+1)!·n!)=1/(n+1)→0<1', 'Σ1/n! converges absolutely', 'Σ(−1)ⁿ/n! converges absolutely', 'Sum of |aₙ| converges → absolute convergence']),
      ('Integrate Maclaurin series for 1/(1−x) to find the series for −ln(1−x).', ['1/(1−x)=Σxⁿ for |x|<1', '∫1/(1−x)dx=−ln(1−x)+C=Σx^{n+1}/(n+1)+C', 'So −ln(1−x)=Σx^{n+1}/(n+1)=x+x²/2+x³/3+...', 'Valid for |x|<1; at x=−1 converges by AST']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=fYyARMqiaag',
},

{
  'num': 10, 'title': 'Parametric, Polar, and Vector Functions (BC)',
  'file': 'ap-calculus-bc-10-unit-10-parametric-polar-and-vector-functions.html',
  'desc': 'Extend calculus to parametric and polar coordinates, and analyze motion with vector-valued functions.',
  'gateway': [
      'Differentiate and integrate parametric equations.',
      'Convert between polar and rectangular coordinates.',
      'Find area and arc length in polar coordinates.',
      'Analyze vector-valued functions for position, velocity, and acceleration.',
  ],
  'lessons': [
      _l('Parametric Equations and Calculus',
         [_t('Area Under Parametric Curve', 'A=∫y dx=∫_α^β y(t)·x\'(t)dt. When x increases (x\'(t)>0), the formula gives the area between the curve and x-axis.', 'Students compute ∫y(t)dt instead of ∫y(t)·x\'(t)dt; the dx must be replaced by x\'(t)dt.', 'Set up area under a parametric curve by replacing dx with x\'(t)dt in the area integral.'),
          _t('Parametric Arc Length', 'L=∫_α^β √((dx/dt)²+(dy/dt)²) dt. Interpret as integrating speed over time.', 'Students use (dy/dx)² form instead of ((dx/dt)²+(dy/dt)²); the parametric form avoids computing dy/dx.', 'Set up and evaluate parametric arc length by computing dx/dt and dy/dt separately.'),
          _t('Second Derivative (Concavity) in Parametric', 'd²y/dx²=[d(dy/dx)/dt]/(dx/dt). This is NOT g\'\'(t)/f\'\'(t). Must differentiate dy/dx with respect to t, then divide by dx/dt.', 'Students compute g\'\'(t)/f\'\'(t) for d²y/dx²; the correct formula differentiates dy/dx (a t-function) then divides by dx/dt.', 'Compute second derivative of parametric curve using the correct two-step formula.')],
         [('parametric area', 'A=∫y(t)·x\'(t)dt'),
          ('parametric arc length', 'L=∫√((x\'(t))²+(y\'(t))²)dt'),
          ('parametric d²y/dx²', '[d(dy/dx)/dt]/(dx/dt)'),
          ('speed (parametric)', '|v(t)|=√((x\'(t))²+(y\'(t))²)')],
         ['Set up area under parametric curves', 'Compute arc length using speed integral', 'Find d²y/dx² correctly for parametric curves'],
         ['Parametric calculus in BC FR — all three types may appear', 'Area under parametric curve common in BC MC', 'Second derivative tested in BC FR'],
         ['Find area under x=t², y=t³ from t=0 to t=2', 'Find d²y/dx² for x=cos t, y=sin(2t) at t=π/4'],
         [('Find area under x=t², y=2t for t∈[0,2] (above x-axis).', ['A=∫_0^2 y·(dx/dt)dt=∫_0^2 2t·2t dt=∫_0^2 4t² dt', '[4t³/3]_0^2=32/3', 'Area=32/3', 'dx/dt=2t; substitute']),
          ('Find arc length of x=t−sin t, y=1−cos t for t∈[0,2π] (cycloid).', ['dx/dt=1−cos t; dy/dt=sin t', '(dx/dt)²+(dy/dt)²=(1−cos t)²+sin²t=2−2cos t', 'L=∫_0^{2π}√(2−2cos t)dt=∫_0^{2π}2|sin(t/2)|dt=8', 'Arc length = 8']),
          ('For x=t², y=t³, find d²y/dx² at t=1.', ['dy/dx=(3t²)/(2t)=3t/2', 'd/dt[3t/2]=3/2', 'd²y/dx²=(3/2)/(2t)=3/(4t)', 'At t=1: 3/4; concave up']),
          ('Set up (don\'t evaluate) area enclosed by the parametric curve x=sin t, y=sin(2t) for t∈[0,π].', ['x\'=cos t', 'A=∫_0^π sin(2t)·cos t dt', 'Note sign: check where y·x\' is positive', 'Numerical evaluation needed for exact area']),
          ('Find where x=t²−4, y=t³−3t has a vertical tangent.', ['dx/dt=2t=0 → t=0', 'dy/dt at t=0: −3≠0', 'Vertical tangent at t=0', 'Point: (−4,0)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Parametric Area', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write the area formula for a parametric curve', 'Explain why d²y/dx² ≠ g\'\'(t)/f\'\'(t)', 'Set up arc length of the unit circle parametrically']),

      _l('Polar Coordinates and Calculus',
         [_t('Polar Coordinates Basics', 'Point (r,θ): r is distance from origin, θ is angle from positive x-axis. Convert: x=r cos θ, y=r sin θ, r²=x²+y².', 'Students swap sin and cos: x=r cos θ (not sin), y=r sin θ (not cos).', 'Convert between polar and rectangular; plot polar curves like r=1+cos θ (cardioid).'),
          _t('Area in Polar Coordinates', 'A=(1/2)∫_α^β r² dθ. Area of a sector of angle dθ and radius r is (1/2)r²dθ; integrate over the angle range.', 'Students use ∫r dθ (circumference) instead of (1/2)∫r² dθ; the factor of 1/2 and r² come from the sector area formula.', 'Set up and evaluate polar area integrals; find intersection angles carefully.'),
          _t('Slope of Polar Curves', 'dy/dx = (dy/dθ)/(dx/dθ). Since y=r sin θ and x=r cos θ, differentiate with product rule: dy/dθ=(dr/dθ)sin θ+r cos θ; dx/dθ=(dr/dθ)cos θ−r sin θ.', 'Students differentiate r with respect to x directly; must use chain rule through θ.', 'Compute dy/dx for polar curves by differentiating x=r cos θ and y=r sin θ with product rule.')],
         [('polar conversion', 'x=r cos θ, y=r sin θ, r²=x²+y²'),
          ('polar area', 'A=(1/2)∫_α^β r² dθ'),
          ('polar slope', 'dy/dx=(dy/dθ)/(dx/dθ)'),
          ('cardioid', 'r=a(1+cos θ); a common polar curve')],
         ['Convert points between polar and rectangular', 'Set up and evaluate polar area integrals', 'Find slope of polar curves using parametric differentiation'],
         ['Polar area tested in BC FR — guaranteed', 'Area between two polar curves common', 'Polar slope in BC MC'],
         ['Find area enclosed by r=2cos θ', 'Find slope of r=1+sin θ at θ=π/2'],
         [('Find the area enclosed by r=2cos θ.', ['r=2cos θ is a circle; full loop: θ from −π/2 to π/2', 'A=(1/2)∫_{-π/2}^{π/2}(2cos θ)² dθ=2∫_{-π/2}^{π/2}cos²θ dθ', '=2·(π/2)=π', 'Area=π (radius 1 circle: πr²=π ✓)']),
          ('Set up area between r=2 and r=1+cos θ (outer minus inner).', ['Find intersections: 1+cos θ=2 → cos θ=1 → θ=0; also at θ=2π', 'Wait: 1+cos θ=2 → θ=0; check which is outer', 'For most θ: r=2 is outer; A=(1/2)∫_0^{2π}(4−(1+cos θ)²)dθ', 'Evaluate by expanding (1+cos θ)²']),
          ('Find dy/dx for r=1+sin θ at θ=0.', ['y=r sin θ=(1+sin θ)sin θ; dy/dθ=cos θ·sin θ+(1+sin θ)cos θ=cos θ(1+2sin θ)', 'x=r cos θ=(1+sin θ)cos θ; dx/dθ=cos θ·cos θ+(1+sin θ)(−sin θ)=cos²θ−sin θ−sin²θ', 'At θ=0: dy/dθ=1; dx/dθ=1', 'dy/dx=1']),
          ('Find the area enclosed by one petal of r=sin(2θ).', ['One petal: θ from 0 to π/2', 'A=(1/2)∫_0^{π/2}sin²(2θ)dθ=(1/2)·(π/4)=π/8', 'Using identity sin²(2θ)=(1−cos4θ)/2', 'Area of one petal = π/8']),
          ('Convert r=3sin θ to rectangular form.', ['Multiply by r: r²=3r sin θ', 'x²+y²=3y', 'x²+(y−3/2)²=9/4', 'Circle centered at (0,3/2) radius 3/2'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Polar Calculus', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the polar area formula and derive it from sector area', 'Find area enclosed by r=cos(3θ) (three-petal rose)', 'Convert r=4 to rectangular']),

      _l('Vector-Valued Functions',
         [_t('Position, Velocity, Acceleration Vectors', 'r(t)=⟨x(t),y(t)⟩; v(t)=r\'(t)=⟨x\'(t),y\'(t)⟩; a(t)=r\'\'(t). Speed=|v|=√(x\'²+y\'²). Displacement=r(b)−r(a).', 'Students compute speed as |x\'|+|y\'| (wrong); speed is the magnitude √(x\'²+y\'²), not the sum of component magnitudes.', 'Compute velocity, speed, and acceleration from a position vector; find displacement.'),
          _t('Total Distance vs. Displacement (Vector)', 'Total distance = ∫_a^b|v(t)|dt = ∫_a^b√(x\'²+y\'²)dt. Displacement vector = r(b)−r(a). Distance ≥ |displacement|.', 'Students compute displacement magnitude instead of integrating speed for total distance; these are different when the path curves.', 'Set up and evaluate total distance integral for vector-valued position functions.'),
          _t('Integration of Vector Functions', '∫r(t)dt=⟨∫x(t)dt,∫y(t)dt⟩+C. Each component integrated separately. Initial condition r(t₀)=r₀ determines the constant vector.', 'Students integrate the magnitude instead of integrating component by component.', 'Integrate a velocity vector to find position; apply initial conditions to determine constant vector.')],
         [('position vector', 'r(t)=⟨x(t),y(t)⟩'),
          ('velocity vector', 'v(t)=r\'(t)=⟨x\'(t),y\'(t)⟩'),
          ('speed', '|v(t)|=√(x\'(t)²+y\'(t)²)'),
          ('total distance (vector)', '∫|v(t)|dt = ∫√(x\'²+y\'²)dt')],
         ['Compute velocity, speed, and acceleration from position vector', 'Distinguish total distance from displacement magnitude', 'Integrate velocity vector with initial conditions'],
         ['Vector functions in BC FR — compute position from velocity', 'Speed and total distance tested', 'Integration of vector function with IC in FR'],
         ['Find velocity and speed of r(t)=⟨t², sin t⟩ at t=π', 'Find position from v(t)=⟨2t,3t²⟩ with r(0)=⟨1,−1⟩'],
         [('For r(t)=⟨t³,t²⟩, find velocity, speed, and acceleration at t=1.', ['v(t)=⟨3t²,2t⟩; at t=1: v=⟨3,2⟩', 'Speed=√(9+4)=√13', 'a(t)=⟨6t,2⟩; at t=1: a=⟨6,2⟩', 'Direction of motion: vector ⟨3,2⟩']),
          ('Find total distance traveled by r(t)=⟨cos t, sin t⟩ from t=0 to t=2π.', ['v(t)=⟨−sin t, cos t⟩; speed=√(sin²t+cos²t)=1', 'Total distance=∫_0^{2π}1 dt=2π', 'Displacement=r(2π)−r(0)=⟨1,0⟩−⟨1,0⟩=⟨0,0⟩', 'Distance=2π; displacement=0 (closed loop)']),
          ('Given v(t)=⟨2t,3t²⟩ and r(0)=⟨1,−1⟩, find r(t).', ['Integrate: ⟨t²,t³⟩+C', 'r(0)=⟨0,0⟩+C=⟨1,−1⟩ → C=⟨1,−1⟩', 'r(t)=⟨t²+1,t³−1⟩', 'Apply initial condition to each component']),
          ('Find displacement of r(t)=⟨e^t,t²⟩ from t=0 to t=2.', ['r(2)=⟨e²,4⟩; r(0)=⟨1,0⟩', 'Displacement=⟨e²−1,4⟩', 'Magnitude=√((e²−1)²+16)≈√(37.5)≈6.12', 'Not the same as total distance']),
          ('A particle has r(t)=⟨sin t,cos t⟩. Is it speeding up or slowing down at t=π/4?', ['v=⟨cos t,−sin t⟩; a=⟨−sin t,−cos t⟩', 'Speed=√(cos²t+sin²t)=1 (constant!)', 'Constant speed: neither speeding up nor slowing down', 'Acceleration is centripetal (perpendicular to v)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Vector Functions', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the formula for speed of a vector-valued function', 'Explain the difference between distance and displacement for vector motion', 'Find r(t) given v(t)=⟨e^t,cos t⟩ and r(0)=⟨2,1⟩']),

      _l('Integration in Polar and Parametric Contexts',
         [_t('Area Between Polar Curves', 'A=(1/2)∫_α^β(r_outer²−r_inner²)dθ. Find intersection angles by setting r₁=r₂; split the integral at each crossing.', 'Students use r_outer−r_inner instead of r_outer²−r_inner²; the area formula squares each radius.', 'Identify which curve is outer at each angle; integrate (r₁²−r₂²)/2 over the appropriate angle range.'),
          _t('Converting Polar to Parametric', 'Let x(θ)=r(θ)cos θ, y(θ)=r(θ)sin θ. Then calculus formulas for parametric (dy/dx, arc length, area) apply directly to polar curves.', 'Students treat polar curves as Cartesian; converting to parametric allows all parametric tools.', 'Convert a polar equation to parametric form and apply parametric calculus formulas.'),
          _t('Polar Arc Length', 'L=∫_α^β √(r²+(dr/dθ)²)dθ. Derived from parametric arc length with x=r cos θ, y=r sin θ.', 'Students use the Cartesian arc length formula for polar curves; polar arc length uses r and dr/dθ.', 'Set up polar arc length integral; note the formula involves r itself, not just dr/dθ.')],
         [('polar area between curves', 'A=(1/2)∫(r_outer²−r_inner²)dθ'),
          ('polar arc length', 'L=∫√(r²+(dr/dθ)²)dθ'),
          ('polar to parametric', 'x=r(θ)cos θ, y=r(θ)sin θ'),
          ('intersection in polar', 'Solve r₁(θ)=r₂(θ) for crossing angles; also check origin')],
         ['Set up area between two polar curves', 'Convert polar to parametric and apply parametric formulas', 'Set up polar arc length'],
         ['Area between polar curves guaranteed in BC FR', 'Polar arc length in BC MC', 'Conversion to parametric tested as method'],
         ['Find area inside r=2 and outside r=1+cos θ', 'Set up arc length of r=e^θ from 0 to π'],
         [('Find area inside r=3 and outside r=1+2cos θ.', ['Set r₁=r₂: 3=1+2cos θ → cos θ=1 → θ=0; also need θ where they cross', 'At θ=0: both=3; look for where 1+2cos θ<3 → cos θ<1: always except θ=0', 'Better approach: check θ=π: r=1+2(−1)=−1... use |r|', 'Set up: A=(1/2)∫_{-π/3}^{π/3}(9−(1+2cos θ)²)dθ where θ=±π/3 gives r=2 on inner']),
          ('Set up polar arc length of r=1+cos θ.', ['dr/dθ=−sin θ', 'L=∫_0^{2π}√((1+cos θ)²+sin²θ)dθ', '=∫_0^{2π}√(2+2cos θ)dθ', 'Using identity: √(2+2cos θ)=2|cos(θ/2)|; L=8']),
          ('Convert r=2sin θ to parametric form.', ['x(θ)=2sin θ·cos θ=sin(2θ)', 'y(θ)=2sin θ·sin θ=2sin²θ=1−cos(2θ)', 'Parametric: x=sin(2θ), y=1−cos(2θ)', 'This traces the circle x²+(y−1)²=1']),
          ('Find area inside both r=1 and r=2cos θ.', ['Intersect: 1=2cos θ → θ=π/3', 'On [0,π/3]: r=2cos θ is outer (2cos(0)=2>1)', 'On [π/3,π/2]: r=1 is outer', 'Area=2·[(1/2)∫_0^{π/3}(4cos²θ−1)dθ+(1/2)∫_{π/3}^{π/2}(1−4cos²θ)dθ]... symmetric over x-axis']),
          ('Why must you check the origin separately when finding intersections of polar curves?', ['r₁(θ₁)=0 and r₂(θ₂)=0 at different θ values both give the origin', 'Setting r₁=r₂ algebraically may miss the origin', 'Always test: does r=0 for either curve at any θ?', 'The origin may be a crossing point even if no algebraic solution exists'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Polar Area Between Curves', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the area formula between two polar curves', 'Explain why the origin requires special attention in polar intersections', 'Set up arc length of r=sin θ from θ=0 to π']),
  ],
  'unit_qs': [
      ('Find area under x=t², y=t for t∈[1,3] above x-axis.', ['A=∫_1^3 y·x\'dt=∫_1^3 t·2t dt=2∫_1^3 t² dt', '=2[t³/3]_1^3=2(9−1/3)=52/3', 'Area=52/3', 'Replace dx with x\'(t)dt=2t dt']),
      ('Find d²y/dx² for x=e^t, y=t² at t=0.', ['dy/dx=2t/e^t', 'd/dt[2t/e^t]=(2e^t−2te^t)/e^{2t}=2(1−t)/eᵗ', 'd²y/dx²=[2(1−t)/eᵗ]/eᵗ=2(1−t)/e^{2t}', 'At t=0: 2/1=2']),
      ('Find area enclosed by r=3sin θ.', ['Full circle: θ from 0 to π', 'A=(1/2)∫_0^π(3sin θ)²dθ=(9/2)∫_0^π sin²θ dθ', '=(9/2)·(π/2)=9π/4', 'Circle of radius 3/2: πr²=π(9/4)=9π/4 ✓']),
      ('For r(t)=⟨t sin t, t cos t⟩, find speed at t=π/2.', ['x\'=sin t+t cos t; at t=π/2: 1+0=1', 'y\'=cos t−t sin t; at t=π/2: 0−π/2=−π/2', 'Speed=√(1+π²/4)', 'Speed=√(1+π²/4)']),
      ('Convert r²=4cos(2θ) to rectangular (lemniscate).', ['r²=4cos(2θ)=4(cos²θ−sin²θ)', 'r²=4(cos²θ−sin²θ)=4((x/r)²−(y/r)²)·r²/r²', '(x²+y²)²=4(x²−y²)', 'Rectangular form of lemniscate']),
      ('Find total distance traveled by v(t)=⟨t,t²−1⟩ from t=0 to t=2.', ['Speed=√(t²+(t²−1)²)=√(t⁴−t²+1)', 'Distance=∫_0^2√(t⁴−t²+1)dt', 'No closed form; set up is complete', 'Numerical value ≈ 3.2']),
      ('Find area between r=2 (outer) and r=2−2cos θ (inner) for all θ.', ['Area of r=2 circle: π(2²)=4π', 'Area enclosed by cardioid r=2−2cos θ: (1/2)∫_0^{2π}(2−2cos θ)²dθ=6π', 'Wait: cardioid must be inner... check r at θ=π: 2−2(−1)=4>2', 'Re-evaluate: at θ=0: cardioid=0<2; at θ=π: cardioid=4>2; split integral']),
      ('Find polar arc length of r=e^θ from θ=0 to θ=1.', ['dr/dθ=e^θ', 'L=∫_0^1√(e^{2θ}+e^{2θ})dθ=∫_0^1e^θ√2 dθ', '=√2[e^θ]_0^1=√2(e−1)', 'Arc length=√2(e−1)']),
      ('A particle has v(t)=⟨2,3t⟩ and r(0)=⟨0,1⟩. Find r(2).', ['r(t)=∫v dt=⟨2t,3t²/2⟩+C', 'r(0)=⟨0,0⟩+C=⟨0,1⟩ → C=⟨0,1⟩', 'r(t)=⟨2t,3t²/2+1⟩', 'r(2)=⟨4,7⟩']),
      ('Find slope of r=2+sin θ at θ=π.', ['y=r sin θ=(2+sin θ)sin θ; dy/dθ=cos θ sin θ+(2+sin θ)cos θ=cos θ(2+2sin θ)', 'x=r cos θ=(2+sin θ)cos θ; dx/dθ=cos θ cos θ+(2+sin θ)(−sin θ)=cos²θ−2sin θ−sin²θ', 'At θ=π: dy/dθ=(−1)(2+0)=−2; dx/dθ=1−0−0=1', 'dy/dx=−2/1=−2']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=fYyARMqiaag',
},
]
