NAME = 'AP® Calculus BC'
ABBREV = 'calc'
SLUG = 'ap-calculus-bc'
COURSE_FILE = 'ap-calculus-bc.html'
ACCENT_COLOR = '#a78bfa'

_K = 'https://www.khanacademy.org/math/ap-calculus-ab/'
_P = 'https://www.youtube.com/results?search_query=Professor+Leonard+Calculus+'

COURSE_QS = [
    ('The formal definition of a limit states that lim_{x→a} f(x) = L means',
     'for every ε > 0, there exists δ > 0 such that 0 < |x−a| < δ implies |f(x)−L| < ε',
     ['f(a) = L exactly', 'f(x) equals L when x is very close to a', 'the derivative at x = a equals L']),
    ('L\'Hôpital\'s Rule applies when evaluating a limit that produces',
     'an indeterminate form (0/0 or ∞/∞), allowing differentiation of numerator and denominator separately',
     ['any rational function at a real number', 'the derivative of a product of functions', 'an infinite series']),
    ('The Intermediate Value Theorem guarantees that if f is continuous on [a, b] and N is between f(a) and f(b), then',
     'there exists at least one c in (a, b) where f(c) = N',
     ['f(a) = f(b) for all continuous functions', 'the function has a maximum on [a, b]', 'the derivative is zero somewhere on (a, b)']),
    ('The chain rule states that if y = f(g(x)), then dy/dx =',
     "f'(g(x)) · g'(x)",
     ["f'(x) · g'(x)", "f'(g'(x))", "f(g'(x)) + g(f'(x))"]),
    ('The Mean Value Theorem states that if f is continuous on [a, b] and differentiable on (a, b), then',
     "there exists c in (a, b) where f'(c) = [f(b) − f(a)] / (b − a)",
     ['f has a relative maximum at some c', 'f(a) = f(b)', "f'(x) = 0 somewhere on [a, b]"]),
    ("A function f has a relative minimum at x = c if f'(c) = 0 and",
     "f' changes from negative to positive at c (First Derivative Test)",
     ["f''(c) = 0", "f(c) is the global minimum", "f is increasing on both sides of c"]),
    ('The integral ∫ from a to b of f(x) dx represents',
     'the net signed area between the curve y = f(x) and the x-axis on [a, b]',
     ['the average value of f on [a, b]', 'the arc length of f on [a, b]', 'the total area regardless of sign']),
    ('The Fundamental Theorem of Calculus Part 1 states that if F(x) = ∫ from a to x of f(t) dt, then',
     "F'(x) = f(x) — differentiation and integration are inverse operations",
     ['F(x) = f(x) at all points', 'the definite integral equals the area under f', 'F is always increasing']),
    ('Integration by parts uses the formula',
     '∫ u dv = uv − ∫ v du, choosing u to differentiate and dv to integrate',
     ['∫ f(g(x))g\'(x) dx = F(g(x)) + C', '∫ f(x)g(x) dx = F(x)G(x) + C', '∫ u dv = u\'v + uv\'']),
    ('A power series ∑ aₙ(x − c)ⁿ converges absolutely when',
     'the ratio test yields |x − c| < R, where R is the radius of convergence',
     ['x = c always', 'the series has finitely many terms', 'the partial sums increase without bound']),
    ('The Taylor series for f(x) centered at x = a is',
     '∑ f⁽ⁿ⁾(a)/n! · (x−a)ⁿ — a polynomial approximation using derivatives at a single point',
     ['∑ f(n)/n! for integer n', 'the derivative of f at each integer', 'the Maclaurin series for any a']),
    ('For a slope field, the solution curve through a point (x₀, y₀) of dy/dx = f(x, y)',
     'is tangent to the slope field at every point along its path',
     ['always passes through the origin', 'must be a straight line', 'is unique only if f is a constant']),
    ('Euler\'s method approximates the solution to dy/dx = f(x, y) by',
     'using the tangent line at each step: yₙ₊₁ = yₙ + h · f(xₙ, yₙ)',
     ['computing the exact antiderivative', 'using second derivatives for greater accuracy', 'applying the trapezoidal rule']),
    ('Parametric equations describe a curve where',
     'both x and y are expressed as functions of a third variable t (the parameter)',
     ['x is a function of y directly', 'the curve is always a circle', 'motion is restricted to straight lines']),
    ('For polar coordinates, the area enclosed by r = f(θ) from θ = α to θ = β is',
     '(1/2) ∫ from α to β of [f(θ)]² dθ',
     ['∫ from α to β of f(θ) dθ', '∫ from α to β of 2πf(θ) dθ', '(1/2) ∫ from α to β of f(θ) dθ']),
    ('The Alternating Series Test says a series ∑ (−1)ⁿ bₙ converges if',
     'the terms bₙ are positive, decreasing, and approach zero',
     ['the ratio of consecutive terms is less than 1', 'the series has finite sum', 'bₙ increases without bound']),
    ('L\'Hôpital\'s Rule requires that before applying it, you verify',
     'the limit produces 0/0 or ∞/∞ (an indeterminate form)',
     ['the function is continuous everywhere', 'both functions are polynomials', 'the denominator is zero at the point']),
    ('The disk/washer method for volume of revolution about the x-axis gives',
     'V = π ∫ [f(x)]² dx (disk) or π ∫ {[f(x)]² − [g(x)]²} dx (washer)',
     ['V = 2π ∫ x·f(x) dx', 'V = ∫ f(x) dx', 'V = π ∫ f(x) dx']),
    ('Implicit differentiation is used when',
     'y cannot be easily solved explicitly as a function of x, so we differentiate both sides with respect to x treating y as a function of x',
     ['the function is not differentiable', 'we want to find the second derivative only', 'the function is defined piecewise']),
    ('A p-series ∑ 1/nᵖ converges if and only if',
     'p > 1',
     ['p > 0', 'p ≥ 1', 'p is an integer']),
]

def _t(title, content, mis, tested):
    return {'title': title, 'content': content, 'misconception': mis, 'how_tested': tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
{
  'num': 1, 'title': 'Limits and Continuity',
  'file': 'ap-calculus-bc-1-unit-1-limits-and-continuity.html',
  'desc': 'Understand the concept of a limit, evaluate limits analytically and graphically, and define continuity.',
  'gateway': [
      'Evaluate limits from graphs, tables, and algebraically.',
      'Apply limit laws and special limit techniques (factoring, conjugates, L\'Hôpital).',
      'Define and classify discontinuities.',
      'State and apply the Intermediate Value Theorem.',
  ],
  'lessons': [
      _l('Intuitive and Formal Definition of a Limit',
         [_t('What a Limit Means', 'A limit describes the value a function approaches as the input approaches a given point, not necessarily the function\'s value there.', 'Students confuse f(a) with lim_{x→a} f(x); limits describe approach, not the actual value.', 'Given a graph or table, identify lim_{x→a} f(x) vs f(a).'),
          _t('One-Sided Limits', 'The left-hand limit (x→a⁻) and right-hand limit (x→a⁺) must both exist and be equal for the two-sided limit to exist.', 'A two-sided limit can fail to exist even if both one-sided limits exist but differ.', 'Evaluate one-sided limits from piecewise graphs; determine if two-sided limit exists.'),
          _t('Limits at Infinity', 'As x→±∞, rational functions approach the ratio of leading coefficients if degrees match, 0 if denominator degree is higher, or ±∞ if numerator degree is higher.', 'Students forget to compare degrees; for equal degrees the limit is the ratio of leading coefficients, not 1.', 'Simplify rational expressions as x→∞ using dominant-term analysis.')],
         [('limit', 'The value a function approaches as the input nears a particular point'),
          ('one-sided limit', 'A limit evaluated as x approaches a value from only one direction'),
          ('limit at infinity', 'The value a function approaches as x grows without bound'),
          ('indeterminate form', 'An expression like 0/0 or ∞/∞ that requires further analysis')],
         ['Evaluate limits from graphs and tables', 'Distinguish one-sided from two-sided limits', 'Determine when limits at infinity are finite or infinite'],
         ['Multiple choice: read limit from graph or table', 'Free response: justify why a limit does or does not exist', 'Algebraic simplification before evaluating limit'],
         ['Sketch a function where f(2)=5 but lim_{x→2}f(x)=3', 'Practice limit tables with values approaching from both sides'],
         [('A function f has lim_{x→2⁻}f(x)=4 and lim_{x→2⁺}f(x)=4 but f(2)=7. Does lim_{x→2}f(x) exist?', ['State that lim_{x→2}f(x)=4 because both one-sided limits equal 4', 'Note that f(2)=7 is irrelevant to the limit\'s existence', 'Confirm the two-sided limit equals 4', 'Identify this as a removable discontinuity at x=2']),
          ('Evaluate lim_{x→∞} (3x²−1)/(5x²+2).', ['Divide numerator and denominator by x², the highest power', 'Simplify to (3−1/x²)/(5+2/x²)', 'As x→∞, terms with 1/x²→0, leaving 3/5', 'State the limit is 3/5']),
          ('From a graph, lim_{x→3⁻}f(x)=1 and lim_{x→3⁺}f(x)=−2. What can you conclude?', ['The two-sided limit lim_{x→3}f(x) does not exist (DNE)', 'The one-sided limits are different', 'f has a jump discontinuity at x=3', 'Neither one-sided limit alone gives the two-sided limit']),
          ('Evaluate lim_{x→0} sin(x)/x.', ['This is a fundamental trigonometric limit equal to 1', 'Use squeeze theorem justification or known result', 'Cannot be found by direct substitution (0/0 form)', 'Result: 1 (in radians)']),
          ('A table shows f(x) approaching 7 from both sides as x→5. State the limit and what it means.', ['lim_{x→5}f(x)=7', 'The function gets arbitrarily close to 7 as x approaches 5', 'This does not require f(5)=7', 'Numerical evidence supports but does not prove the limit'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Limits Introduction', 'https://www.youtube.com/watch?v=fYyARMqiaag'),
          ('https://www.youtube.com/watch?v=fYyARMqiaag', 'Khan Academy — Limits and Continuity Unit', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the definition of a limit in your own words', 'Give an example where lim_{x→a}f(x) exists but f(a) does not', 'Explain when a two-sided limit fails to exist']),

      _l('Evaluating Limits Algebraically',
         [_t('Direct Substitution and Indeterminate Forms', 'If direct substitution yields 0/0 or ∞/∞, algebraic manipulation (factoring, rationalizing) is needed to resolve the indeterminate form.', 'Students stop at 0/0 and say the limit does not exist; 0/0 is indeterminate, not undefined — it requires further work.', 'Factor and cancel common factors to evaluate limits algebraically.'),
          _t('Limit Laws', 'Limit laws allow limits of sums, products, and quotients to be computed from individual limits, provided the component limits exist.', 'The quotient law requires the denominator limit to be non-zero; if it is zero, the law cannot be applied directly.', 'Apply sum, product, and quotient laws step by step on multi-choice problems.'),
          _t('Squeeze Theorem', 'If g(x) ≤ f(x) ≤ h(x) near a and lim g = lim h = L, then lim f = L. Used for oscillating functions like x²sin(1/x).', 'Students try to apply squeeze theorem without verifying the inequality holds near the point.', 'Set up and apply squeeze theorem for x²sin(1/x) as x→0.')],
         [('direct substitution', 'Plugging the limit point directly into the function; valid when f is continuous there'),
          ('factoring technique', 'Canceling common (x−a) factors from numerator and denominator to resolve 0/0'),
          ('rationalizing', 'Multiplying by conjugate to eliminate radicals in limit expressions'),
          ('Squeeze Theorem', 'If a function is bounded between two functions with the same limit, it shares that limit')],
         ['Factor and cancel to resolve 0/0 indeterminate forms', 'Apply limit laws to break complex limits into parts', 'Use squeeze theorem for oscillating or bounded functions'],
         ['Algebraic limit problems appear on both MC and FR sections', 'Expect to show all algebraic steps in free response', 'Squeeze theorem may appear as a justify/explain question'],
         ['Show all steps when factoring to simplify', 'Practice conjugate multiplication for limits with radicals'],
         [('Evaluate lim_{x→3} (x²−9)/(x−3).', ['Factor numerator: x²−9=(x−3)(x+3)', 'Cancel (x−3) from numerator and denominator', 'Evaluate (x+3) at x=3: 3+3=6', 'The limit is 6']),
          ('Evaluate lim_{x→4} (√x−2)/(x−4).', ['Multiply by conjugate (√x+2)/(√x+2)', 'Numerator becomes x−4; cancel with denominator', 'Result is 1/(√x+2); substitute x=4', 'Limit = 1/(2+2) = 1/4']),
          ('Use limit laws to evaluate lim_{x→2}[3f(x)−g(x)] if lim f(x)=5 and lim g(x)=1.', ['Apply scalar multiple law: lim 3f(x)=3·5=15', 'Apply difference law: 15−lim g(x)=15−1', 'Result: 14', 'State the applicable limit laws used']),
          ('Explain why lim_{x→0} x·sin(1/x)=0 using the Squeeze Theorem.', ['Note −1 ≤ sin(1/x) ≤ 1 for all x≠0', 'Multiply by |x|: −|x| ≤ x·sin(1/x) ≤ |x|', 'lim_{x→0}(−|x|)=0 and lim_{x→0}|x|=0', 'By Squeeze Theorem, lim_{x→0}x·sin(1/x)=0']),
          ('Evaluate lim_{x→−2} (x²+5x+6)/(x+2).', ['Factor numerator: (x+2)(x+3)', 'Cancel (x+2); left with (x+3)', 'Substitute x=−2: −2+3=1', 'Limit = 1'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Evaluating Limits', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['List three techniques to resolve a 0/0 indeterminate form', 'State the Squeeze Theorem precisely', 'Give an example where direct substitution fails but the limit exists']),

      _l('Continuity',
         [_t('Definition of Continuity', 'A function is continuous at x=a if: (1) f(a) is defined, (2) lim_{x→a}f(x) exists, and (3) lim_{x→a}f(x)=f(a). All three conditions must hold.', 'Students think a function is continuous if "the graph looks smooth"; holes, jumps, and vertical asymptotes all violate continuity.', 'Given a piecewise function, find values of constants that make it continuous at a point.'),
          _t('Types of Discontinuities', 'Removable (hole): limit exists but ≠ f(a). Jump: one-sided limits are unequal. Infinite: vertical asymptote. Each has a distinct appearance on a graph.', 'Students call all discontinuities "holes"; removable, jump, and infinite discontinuities are categorically different.', 'Classify a discontinuity from a graph or formula and justify the classification.'),
          _t('Intermediate Value Theorem', 'If f is continuous on [a,b] and N is between f(a) and f(b), then there exists c in (a,b) with f(c)=N. Used to guarantee existence of zeros.', 'IVT guarantees existence of c but does not find c; students confuse it with actually solving the equation.', 'Use IVT to argue a function has a root on a given interval.')],
         [('continuous function', 'A function with no holes, jumps, or vertical asymptotes on its domain'),
          ('removable discontinuity', 'A hole in the graph where the limit exists but f(a) is wrong or missing'),
          ('jump discontinuity', 'A discontinuity where left- and right-hand limits exist but are unequal'),
          ('Intermediate Value Theorem', 'Guarantees a continuous function takes every value between f(a) and f(b)')],
         ['Verify all three continuity conditions at a point', 'Classify discontinuities by type with justification', 'Apply IVT to prove a root exists on an interval'],
         ['Piecewise functions tested for continuity by setting one-sided limits equal', 'IVT appears as justify/explain free-response questions', 'Graphs tested for identifying and classifying discontinuities'],
         ['Find k so f(x)={x²+1, x<2; kx−1, x≥2} is continuous', 'Verify or refute continuity of f(x)=1/(x−3) on [1,5]'],
         [('State the three conditions for continuity at x=a.', ['f(a) must be defined', 'lim_{x→a}f(x) must exist', 'The limit must equal f(a)', 'All three must hold simultaneously']),
          ('Classify the discontinuity of f(x)=(x²−4)/(x−2) at x=2.', ['Factor: (x−2)(x+2)/(x−2); limit = x+2 = 4 at x=2', 'f(2) is undefined (0 in denominator)', 'Limit exists (=4) but f(2) is not defined', 'Removable (hole) discontinuity at x=2']),
          ('Find k so that f(x)={2x+1, x≤3; kx−2, x>3} is continuous at x=3.', ['Left-hand limit: 2(3)+1=7', 'Right-hand limit: 3k−2', 'Set equal: 3k−2=7 → k=3', 'Verify f(3)=7 (left piece): continuous when k=3']),
          ('Use IVT to show f(x)=x³−x−1 has a root on (1,2).', ['f is continuous (polynomial)', 'f(1)=1−1−1=−1<0', 'f(2)=8−2−1=5>0', 'By IVT, ∃c∈(1,2) with f(c)=0']),
          ('A function has lim_{x→5⁻}f(x)=3 and lim_{x→5⁺}f(x)=7 and f(5)=3. Classify the discontinuity.', ['Left-hand limit (3) ≠ right-hand limit (7)', 'The two-sided limit does not exist', 'This is a jump discontinuity at x=5', 'Even though f(5) is defined, the jump makes it discontinuous'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Khan Academy — Continuity', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Recite the three continuity conditions from memory', 'Sketch one graph for each type of discontinuity', 'Write an IVT argument for f(x)=cos(x)−x on [0,1]']),

      _l('Infinite Limits and L\'Hôpital\'s Rule (BC)',
         [_t('Vertical Asymptotes and Infinite Limits', 'If lim_{x→a}f(x)=±∞, the line x=a is a vertical asymptote. This occurs when the denominator→0 and numerator→nonzero.', 'Students confuse "limit is infinity" with "limit does not exist"; technically both are true — the limit is unbounded hence DNE, but we write ±∞ to describe behavior.', 'Determine whether f→+∞ or −∞ from either side of a vertical asymptote.'),
          _t('L\'Hôpital\'s Rule', 'If lim f/g yields 0/0 or ∞/∞, then lim f/g = lim f\'/g\', provided the new limit exists. Apply repeatedly if needed.', 'Students apply L\'Hôpital without verifying the indeterminate form; it is only valid for 0/0 or ∞/∞.', 'Verify indeterminate form, then differentiate numerator and denominator separately before re-evaluating.'),
          _t('Improper Integrals via Limits (BC)', 'An improper integral ∫_a^∞ f dx is defined as lim_{t→∞}∫_a^t f dx. It converges if the limit is finite, diverges otherwise.', 'Students evaluate improper integrals as if the bound is a normal number; a limit must replace the infinite bound.', 'Set up and evaluate improper integrals using limit notation; classify as convergent or divergent.')],
         [('vertical asymptote', 'A vertical line x=a where f(x)→±∞'),
          ('L\'Hôpital\'s Rule', 'lim f/g = lim f\'/g\' when the form is 0/0 or ∞/∞'),
          ('improper integral', 'An integral with an infinite bound or discontinuous integrand, evaluated as a limit'),
          ('convergent/divergent', 'Whether an improper integral approaches a finite value or not')],
         ['Identify vertical asymptotes and determine sign of infinite limit', 'Apply L\'Hôpital\'s Rule correctly to 0/0 and ∞/∞ forms', 'Set up and evaluate basic improper integrals'],
         ['Infinite limit behavior tested via sign analysis near asymptote', 'L\'Hôpital\'s Rule is BC only but may appear on AB as a limit technique', 'Improper integrals tested on BC free response'],
         ['Evaluate lim_{x→0⁺} ln(x)/x using L\'Hôpital', 'Determine convergence of ∫_1^∞ 1/x dx'],
         [('Evaluate lim_{x→∞} (3x²)/(e^x).', ['Form is ∞/∞; apply L\'Hôpital: 6x/e^x', 'Still ∞/∞; apply again: 6/e^x', 'As x→∞, 6/e^x→0', 'Limit = 0; exponentials dominate polynomials']),
          ('Find lim_{x→0} (sin x)/x using L\'Hôpital\'s Rule.', ['Form 0/0; differentiate: cos(x)/1', 'Evaluate at x=0: cos(0)/1=1', 'Limit = 1', 'Consistent with the known fundamental limit']),
          ('Determine whether ∫_1^∞ 1/x² dx converges.', ['Write as lim_{t→∞}∫_1^t x^{−2} dx', 'Antiderivative: −x^{−1}; evaluate from 1 to t', 'Result: −1/t+1; as t→∞, gives 0+1=1', 'Converges to 1']),
          ('Determine whether ∫_1^∞ 1/x dx converges.', ['Write as lim_{t→∞}∫_1^t 1/x dx = lim_{t→∞} ln(t)', 'ln(t)→∞ as t→∞', 'Integral diverges', 'The harmonic series analogue — p-integral with p=1 diverges']),
          ('Find lim_{x→0} (x−sin x)/x³ using L\'Hôpital\'s Rule.', ['Form 0/0; differentiate: (1−cos x)/(3x²)', 'Still 0/0; differentiate: sin x/(6x)', 'Still 0/0; differentiate: cos x/6', 'Evaluate at x=0: cos(0)/6=1/6'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — L\'Hôpital\'s Rule', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the two indeterminate forms that allow L\'Hôpital\'s Rule', 'Define convergence of an improper integral', 'Explain why ∫_1^∞ 1/x diverges but ∫_1^∞ 1/x² converges']),
  ],
  'unit_qs': [
      ('Evaluate lim_{x→2} (x²−4)/(x−2) and classify what type of expression this is before simplification.', ['Factor: (x−2)(x+2); cancel; limit=4', 'Before simplification: 0/0 indeterminate form', 'Cannot use direct substitution; factoring resolves it', 'Limit = 4']),
      ('A piecewise function is f(x)={x²+1 for x<1; 3x−1 for x≥1}. Is f continuous at x=1?', ['Left limit: 1²+1=2', 'Right limit: 3(1)−1=2', 'f(1)=3(1)−1=2', 'All three equal; f is continuous at x=1']),
      ('Explain the Intermediate Value Theorem and use it to show x=cos(x) has a solution.', ['IVT: continuous function takes all values between f(a) and f(b)', 'Let g(x)=x−cos(x); g(0)=−1<0, g(π/2)=π/2>0', 'g is continuous; by IVT ∃c where g(c)=0', 'Therefore x=cos(x) has at least one solution']),
      ('Find all vertical asymptotes of f(x)=(x+1)/((x−2)(x+3)).', ['Denominator zero at x=2 and x=−3', 'Numerator non-zero at both points', 'Vertical asymptotes at x=2 and x=−3', 'Check sign on each side to describe behavior']),
      ('Apply L\'Hôpital\'s Rule to evaluate lim_{x→0} (1−cos x)/x².', ['Form 0/0; differentiate: sin x/(2x)', 'Still 0/0; differentiate: cos x/2', 'Evaluate at x=0: 1/2', 'Limit = 1/2']),
      ('Evaluate lim_{x→∞} (5x³−2x)/(x³+7).', ['Divide all terms by x³', 'Numerator→5, denominator→1', 'Limit = 5/1 = 5', 'Horizontal asymptote at y=5']),
      ('Classify the discontinuity of f(x)=|x|/x at x=0.', ['Left limit: −1 (for x<0, |x|/x=−1)', 'Right limit: 1 (for x>0, |x|/x=1)', 'One-sided limits differ; two-sided limit DNE', 'Jump discontinuity at x=0']),
      ('State and verify the three conditions of continuity for f(x)=√(x−1) at x=5.', ['f(5)=√4=2 (defined)', 'lim_{x→5}√(x−1)=√4=2 (exists)', 'Limit equals function value', 'All three conditions met; f is continuous at x=5']),
      ('Evaluate lim_{x→0⁺} x·ln(x).', ['Rewrite as ln(x)/(1/x) → −∞/∞; apply L\'Hôpital', 'Differentiate: (1/x)/(−1/x²)=−x', 'lim_{x→0⁺}(−x)=0', 'Limit = 0']),
      ('Does ∫_0^1 1/√x dx converge? Evaluate if yes.', ['Rewrite as lim_{t→0⁺}∫_t^1 x^{−1/2} dx', 'Antiderivative: 2√x; evaluate from t to 1', '2√1−2√t=2−2√t; as t→0⁺, gives 2', 'Converges to 2']),
  ],
},

{
  'num': 2, 'title': 'Differentiation: Definition and Fundamental Properties',
  'file': 'ap-calculus-bc-2-unit-2-differentiation-definition-fundamental-properties.html',
  'desc': 'Define the derivative as a limit and develop rules for differentiating algebraic, trigonometric, and composite functions.',
  'gateway': [
      'Define the derivative using the limit of a difference quotient.',
      'Apply power, product, quotient, and chain rules fluently.',
      'Differentiate trigonometric, exponential, and logarithmic functions.',
      'Interpret the derivative as slope and instantaneous rate of change.',
  ],
  'lessons': [
      _l('Definition of the Derivative',
         [_t('Limit Definition', 'The derivative f\'(a) = lim_{h→0} [f(a+h)−f(a)]/h measures the instantaneous rate of change at x=a.', 'Students confuse the average rate of change (slope of secant) with the derivative (slope of tangent); the limit converts secant to tangent.', 'Use the limit definition to find f\'(x) for quadratic and simple rational functions.'),
          _t('Differentiability and Continuity', 'Differentiability implies continuity, but continuity does not imply differentiability. Corners, cusps, and vertical tangents make a function non-differentiable.', 'Students think any continuous function is differentiable; |x| is continuous but not differentiable at x=0.', 'Identify points of non-differentiability from a graph and explain the reason.'),
          _t('Tangent Line Equation', 'The tangent line at (a, f(a)) has equation y−f(a)=f\'(a)(x−a). This is one of the most-tested calculus applications.', 'Students use the slope of the secant or forget to evaluate the derivative at the specific point.', 'Write the equation of the tangent line given a function and x-value.')],
         [('difference quotient', '[f(a+h)−f(a)]/h; the slope of a secant line'),
          ('derivative', 'The limit of the difference quotient as h→0; instantaneous rate of change'),
          ('differentiable', 'A function with a well-defined derivative at every point in its domain'),
          ('tangent line', 'The line touching the curve at one point with slope equal to the derivative')],
         ['Compute derivatives using the limit definition', 'Determine differentiability from a graph or formula', 'Write tangent line equations at given points'],
         ['Limit definition may appear in FR to derive a specific derivative', 'Tangent line equations are among the most common FR topics', 'Graphs tested: identify where f is not differentiable'],
         ['Use limit definition to find derivative of f(x)=x²+3x', 'Write tangent line to f(x)=x³ at x=2'],
         [('Use the limit definition to find f\'(x) for f(x)=x².', ['Write [f(x+h)−f(x)]/h = [(x+h)²−x²]/h', 'Expand: (x²+2xh+h²−x²)/h = (2xh+h²)/h', 'Factor: h(2x+h)/h = 2x+h', 'As h→0, f\'(x) = 2x']),
          ('Find the equation of the tangent line to f(x)=x³−2x at x=1.', ['f(1)=1−2=−1; point (1,−1)', 'f\'(x)=3x²−2; f\'(1)=3−2=1', 'y−(−1)=1(x−1)', 'y=x−2']),
          ('Is f(x)=|x−3| differentiable at x=3? Explain.', ['Left derivative: lim_{h→0⁻}|h|/h=−1', 'Right derivative: lim_{h→0⁺}|h|/h=1', 'Left and right derivatives differ', 'Not differentiable at x=3; corner point']),
          ('A function is continuous at x=5 but not differentiable. Give a possible graph feature.', ['The graph could have a sharp corner at x=5', 'Or a cusp, where the curve comes to a point', 'Or a vertical tangent where f\'→∞', 'Continuity is necessary but not sufficient for differentiability']),
          ('Interpret f\'(3)=−4 in context where f(t) is the temperature in °F at t hours.', ['The temperature is decreasing at t=3 hours', 'The instantaneous rate of change is −4°F per hour', 'Negative sign indicates temperature is falling', 'Units of derivative: °F/hour'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Definition of the Derivative', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write the limit definition of the derivative from memory', 'State why differentiability implies continuity', 'Write the tangent line equation formula']),

      _l('Basic Differentiation Rules',
         [_t('Power and Constant Rules', 'd/dx[xⁿ]=nxⁿ⁻¹; d/dx[c]=0. These are the foundation of polynomial differentiation.', 'Students forget to reduce the exponent by 1 or write nxⁿ without adjusting the power.', 'Differentiate polynomial and rational functions using the power rule, including negative and fractional exponents.'),
          _t('Product and Quotient Rules', 'Product: (fg)\'=f\'g+fg\'. Quotient: (f/g)\'=(f\'g−fg\')/g². Both require identifying which part is f and which is g.', 'Students subtract in the product rule or forget to square the denominator in the quotient rule.', 'Differentiate products and quotients of polynomials and trig functions correctly.'),
          _t('Derivatives of Trig Functions', 'd/dx[sin x]=cos x, d/dx[cos x]=−sin x, d/dx[tan x]=sec²x. The others follow from quotient rule.', 'Students confuse the derivative of cos x as +sin x instead of −sin x.', 'Differentiate expressions combining polynomial and trig functions.')],
         [('power rule', 'd/dx[xⁿ] = nxⁿ⁻¹'),
          ('product rule', 'd/dx[f·g] = f\'g + fg\''),
          ('quotient rule', 'd/dx[f/g] = (f\'g − fg\')/g²'),
          ('derivative of sin/cos', 'd/dx[sin x]=cos x and d/dx[cos x]=−sin x')],
         ['Apply power rule to polynomial, radical, and rational functions', 'Use product and quotient rules correctly', 'Differentiate standard trig functions'],
         ['Power rule questions appear in almost every exam', 'Product/quotient rule in FR requiring full differentiation', 'Trig derivatives tested in combination with other rules'],
         ['Differentiate f(x)=3x⁴−2x⁻¹+√x', 'Find f\'(x) for f(x)=x²·sin(x)'],
         [('Differentiate f(x)=4x³−5x+7.', ['Apply power rule term by term', 'd/dx[4x³]=12x², d/dx[−5x]=−5, d/dx[7]=0', 'f\'(x)=12x²−5', 'Constant term disappears']),
          ('Differentiate g(x)=x²·cos(x).', ['Product rule: u=x², v=cos(x)', 'u\'=2x, v\'=−sin(x)', 'g\'(x)=2x·cos(x)+x²·(−sin x)', 'g\'(x)=2x cos(x)−x² sin(x)']),
          ('Differentiate h(x)=sin(x)/(x²+1).', ['Quotient rule: f=sin x, g=x²+1', 'f\'=cos x, g\'=2x', 'h\'=[(cos x)(x²+1)−(sin x)(2x)]/(x²+1)²', 'h\'=(x² cos x+cos x−2x sin x)/(x²+1)²']),
          ('Find dy/dx for y=x^{−3/2}.', ['Apply power rule: dy/dx=(−3/2)x^{−3/2−1}', 'dy/dx=(−3/2)x^{−5/2}', 'Or equivalently −3/(2x^{5/2})', 'Be careful with negative fractional exponents']),
          ('Differentiate f(x)=tan(x) using the quotient rule applied to sin(x)/cos(x).', ['f=sin x, g=cos x', 'f\'=cos x, g\'=−sin x', 'Result: (cos²x+sin²x)/cos²x', '=1/cos²x=sec²x'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Product and Quotient Rules', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the product rule formula', 'Differentiate f(x)=x³·tan(x)', 'Find the slope of f(x)=cos(x)/x at x=π']),

      _l('Chain Rule and Implicit Differentiation',
         [_t('Chain Rule', 'If y=f(g(x)), then dy/dx=f\'(g(x))·g\'(x). Identify the outer and inner function, differentiate from outside in.', 'Students differentiate only the outer function and forget to multiply by the derivative of the inner function.', 'Identify inner and outer functions, then apply chain rule to composite expressions.'),
          _t('Implicit Differentiation', 'For equations relating x and y where y is not isolated, differentiate both sides with respect to x, applying chain rule to y terms (writing dy/dx), then solve for dy/dx.', 'Students forget to write dy/dx when differentiating y terms; every y term needs a chain rule factor.', 'Use implicit differentiation to find dy/dx for circles, ellipses, and other implicit curves.'),
          _t('Derivatives of Inverse Functions', 'If f and g are inverses, then g\'(x)=1/f\'(g(x)). Used to derive d/dx[arcsin x]=1/√(1−x²) and d/dx[arctan x]=1/(1+x²).', 'Students try to find the inverse function explicitly instead of using the inverse function derivative theorem.', 'Apply d/dx[arctan x] and d/dx[arcsin x] in chain rule contexts.')],
         [('chain rule', 'd/dx[f(g(x))]=f\'(g(x))·g\'(x)'),
          ('implicit differentiation', 'Differentiating both sides of an equation with respect to x, treating y as a function of x'),
          ('related rates', 'Using implicit differentiation with respect to time to relate rates of changing quantities'),
          ('inverse trig derivatives', 'd/dx[arcsin x]=1/√(1−x²); d/dx[arctan x]=1/(1+x²)')],
         ['Apply chain rule to compositions of functions', 'Use implicit differentiation to find dy/dx on implicit curves', 'Differentiate inverse trig functions using the formula'],
         ['Chain rule appears in almost every exam; often combined with product/quotient rule', 'Implicit differentiation in FR for tangent lines to curves', 'Inverse trig derivatives in MC and FR'],
         ['Differentiate y=sin(3x²) and y=(x²+1)⁵', 'Find dy/dx for x²+y²=25 using implicit differentiation'],
         [('Differentiate y=(3x²+1)⁴.', ['Outer function: u⁴, inner: 3x²+1', 'Outer derivative: 4u³; inner derivative: 6x', 'y\'=4(3x²+1)³·6x', 'y\'=24x(3x²+1)³']),
          ('Find dy/dx for x²+y²=25.', ['Differentiate both sides: 2x+2y·(dy/dx)=0', 'Solve: 2y·dy/dx=−2x', 'dy/dx=−x/y', 'At (3,4): dy/dx=−3/4']),
          ('Differentiate f(x)=sin(e^x).', ['Outer: sin(u), inner: e^x', 'f\'(x)=cos(e^x)·e^x', 'Cannot simplify further', 'Chain rule applied once']),
          ('Find the derivative of y=arctan(2x).', ['d/dx[arctan(u)]=1/(1+u²)·du/dx', 'u=2x, du/dx=2', 'y\'=1/(1+4x²)·2', 'y\'=2/(1+4x²)']),
          ('Differentiate y=x²·sin(3x) (product + chain).', ['Product rule: u=x², v=sin(3x)', 'u\'=2x; v\'=cos(3x)·3=3cos(3x)', 'y\'=2x·sin(3x)+x²·3cos(3x)', 'y\'=2x sin(3x)+3x² cos(3x)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Chain Rule', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Recite the chain rule formula', 'Find dy/dx for x³+xy+y²=10 using implicit differentiation', 'State d/dx[arctan x]']),

      _l('Derivatives of Exponential and Logarithmic Functions',
         [_t('Derivatives of eˣ and ln(x)', 'd/dx[eˣ]=eˣ; d/dx[ln x]=1/x. Combined with chain rule: d/dx[e^{u}]=eᵘ·u\' and d/dx[ln u]=u\'/u.', 'Students write d/dx[e^{f(x)}]=e^{f(x)} without the chain rule factor f\'(x).', 'Differentiate composite exponential and logarithmic expressions using chain rule.'),
          _t('Derivatives of aˣ and log_a(x)', 'd/dx[aˣ]=aˣ·ln(a); d/dx[log_a x]=1/(x·ln a). Base-a functions appear less often than base-e but are tested.', 'Students forget the ln(a) factor when differentiating aˣ; only eˣ is its own derivative.', 'Differentiate base-a exponential and logarithmic functions using the formula.'),
          _t('Logarithmic Differentiation', 'Take ln of both sides, differentiate implicitly, then solve for y\'. Useful for functions like y=x^x or complicated products and quotients.', 'Students try to apply product/power rules to y=x^x; logarithmic differentiation is required when both base and exponent contain x.', 'Use logarithmic differentiation to find the derivative of y=x^x and y=x^{sin x}.')],
         [('d/dx[eˣ]', 'eˣ (unchanged)'),
          ('d/dx[ln x]', '1/x'),
          ('d/dx[aˣ]', 'aˣ·ln(a)'),
          ('logarithmic differentiation', 'Taking ln of both sides and differentiating implicitly to handle variable exponents')],
         ['Differentiate exponential and log functions with chain rule', 'Apply base-a derivative formulas', 'Use logarithmic differentiation for variable-exponent functions'],
         ['e^x derivatives extremely common in FR and MC', 'Logarithmic differentiation tested in BC and advanced AB questions', 'Chain rule always needed for composite exponential/log'],
         ['Differentiate f(x)=e^{sin x} and g(x)=ln(x²+1)', 'Use logarithmic differentiation to find d/dx[x^x]'],
         [('Differentiate f(x)=e^{3x²}.', ['d/dx[e^u]=eᵘ·u\', u=3x²', 'u\'=6x', 'f\'(x)=e^{3x²}·6x', 'f\'(x)=6x e^{3x²}']),
          ('Differentiate g(x)=ln(x³+5).', ['d/dx[ln u]=u\'/u, u=x³+5', 'u\'=3x²', 'g\'(x)=3x²/(x³+5)', 'Numerator is derivative of argument']),
          ('Find dy/dx for y=2^x.', ['d/dx[aˣ]=aˣ·ln(a)', 'dy/dx=2^x·ln(2)', 'The ln(2) factor distinguishes it from eˣ', 'Approximately 0.693·2^x']),
          ('Use logarithmic differentiation to find dy/dx for y=x^x.', ['Take ln: ln y = x·ln x', 'Differentiate: y\'/y = ln x + x·(1/x) = ln x + 1', 'Multiply by y: y\'=y(ln x+1)', 'y\'=x^x(ln x+1)']),
          ('Differentiate h(x)=ln(sin x).', ['d/dx[ln u]=u\'/u, u=sin x', 'u\'=cos x', 'h\'(x)=cos x/sin x', 'h\'(x)=cot x'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Exp/Log Derivatives', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State d/dx[eˣ] and d/dx[ln x]', 'Explain why d/dx[2^x]≠2^x', 'Write the steps for logarithmic differentiation']),
  ],
  'unit_qs': [
      ('Use the limit definition of the derivative to find f\'(x) for f(x)=3x²−x.', ['Write [f(x+h)−f(x)]/h with f(x+h)=3(x+h)²−(x+h)', 'Expand and simplify numerator: 6xh+3h²−h', 'Divide by h: 6x+3h−1', 'As h→0: f\'(x)=6x−1']),
      ('Find the equation of the tangent line to f(x)=e^x at x=0.', ['f(0)=e⁰=1; point (0,1)', 'f\'(x)=eˣ; f\'(0)=1', 'y−1=1(x−0)', 'y=x+1']),
      ('Differentiate f(x)=(x²+3)·sin(x) using the product rule.', ['u=x²+3, v=sin x', 'u\'=2x, v\'=cos x', 'f\'=2x sin x+(x²+3)cos x', 'Cannot simplify further without context']),
      ('Differentiate y=e^{cos x} using the chain rule.', ['Outer: eᵘ, inner: cos x', 'Outer derivative: eᵘ; inner derivative: −sin x', 'y\'=e^{cos x}·(−sin x)', 'y\'=−sin x·e^{cos x}']),
      ('Find dy/dx for x³+y³=6xy using implicit differentiation.', ['Differentiate: 3x²+3y²·y\'=6y+6x·y\'', 'Collect y\' terms: 3y²y\'−6xy\'=6y−3x²', 'Factor: y\'(3y²−6x)=6y−3x²', 'y\'=(6y−3x²)/(3y²−6x)=(2y−x²)/(y²−2x)']),
      ('Differentiate f(x)=ln(x²+e^x).', ['d/dx[ln u]=u\'/u', 'u=x²+eˣ; u\'=2x+eˣ', 'f\'(x)=(2x+eˣ)/(x²+eˣ)', 'Apply chain rule correctly']),
      ('Find all points where f(x)=x³−3x has a horizontal tangent.', ['f\'(x)=3x²−3; set f\'=0', '3x²−3=0 → x²=1 → x=±1', 'f(1)=−2; f(−1)=2', 'Horizontal tangents at (1,−2) and (−1,2)']),
      ('Explain why f(x)=x^{1/3} is not differentiable at x=0 even though it is continuous.', ['f\'(x)=(1/3)x^{−2/3}; at x=0: (1/3)·0^{−2/3}→∞', 'The derivative is undefined (vertical tangent)', 'The graph has a cusp/vertical tangent at x=0', 'Continuity does not guarantee differentiability']),
      ('Find the derivative of y=arcsin(3x).', ['d/dx[arcsin u]=1/√(1−u²)·u\', u=3x', 'u\'=3', 'y\'=3/√(1−9x²)', 'Domain restricted to |3x|<1']),
      ('Use logarithmic differentiation to find dy/dx for y=(sin x)^x.', ['ln y=x·ln(sin x)', 'Differentiate: y\'/y=ln(sin x)+x·cos(x)/sin(x)', 'y\'/y=ln(sin x)+x·cot x', 'y\'=(sin x)^x·[ln(sin x)+x cot x]']),
  ],
},

{
  'num': 3, 'title': 'Differentiation: Composite, Implicit, and Inverse',
  'file': 'ap-calculus-bc-3-unit-3-differentiation-composite-implicit-inverse.html',
  'desc': 'Master the chain rule in complex settings, use implicit differentiation on curves, and differentiate inverse functions.',
  'gateway': [
      'Apply chain rule to multi-layer compositions.',
      'Use implicit differentiation to find slopes on curves.',
      'Differentiate inverse trigonometric and inverse functions.',
      'Set up and solve related rates problems.',
  ],
  'lessons': [
      _l('Multi-Layer Chain Rule',
         [_t('Chaining Multiple Compositions', 'For y=f(g(h(x))), dy/dx=f\'(g(h(x)))·g\'(h(x))·h\'(x). Work from outermost layer inward.', 'Students stop after one chain rule application when multiple compositions are nested.', 'Identify all layers before differentiating multi-layer compositions.'),
          _t('Chain Rule with Product/Quotient Rule', 'When a composite function also involves a product or quotient, apply product/quotient rule first, then chain rule within each factor.', 'Students apply chain rule before product rule, mixing up the order; use product/quotient rule at the "top level" first.', 'Differentiate expressions like (sin(x²))·(e^{3x}) requiring both product and chain rules.'),
          _t('Higher-Order Derivatives', 'f\'\'(x) is the derivative of f\'(x). Second derivatives measure concavity; f\'\'(x)>0 means concave up. In motion, f\'\'(t) is acceleration.', 'Students compute f\'\'(x) by squaring f\'(x) instead of differentiating f\'(x) again.', 'Find second derivatives of polynomial, trig, and exponential functions.')],
         [('composite function', 'A function formed by applying one function inside another: f(g(x))'),
          ('higher-order derivative', 'The derivative of a derivative; f\'\'(x) is the second derivative'),
          ('concavity', 'f\'\'(x)>0: concave up (cup); f\'\'(x)<0: concave down (frown)'),
          ('inflection point', 'Where concavity changes; f\'\'(x)=0 or undefined and sign changes')],
         ['Apply chain rule to compositions with 3+ layers', 'Combine product/quotient and chain rules in one expression', 'Compute and interpret second derivatives'],
         ['Multi-layer chain rule tested in FR requiring explicit notation', 'Second derivatives appear in concavity and motion questions', 'Mixed rule problems common in MC'],
         ['Differentiate y=e^{sin(3x)} and y=(ln(x²+1))³', 'Find f\'\'(x) for f(x)=x⁴−3x²'],
         [('Differentiate y=sin(e^{3x}).', ['Outer: sin(u), inner: e^{3x}, innermost: 3x', 'Outer deriv: cos(e^{3x}); inner: e^{3x}·3', 'y\'=cos(e^{3x})·e^{3x}·3', 'y\'=3e^{3x}cos(e^{3x})']),
          ('Differentiate y=(ln(x²+1))³.', ['Outer: u³, middle: ln(u), inner: x²+1', 'Outer deriv: 3u²; middle: 1/u; inner: 2x', 'y\'=3(ln(x²+1))²·(1/(x²+1))·2x', 'y\'=6x(ln(x²+1))²/(x²+1)']),
          ('Find f\'\'(x) for f(x)=x⁴−6x²+1.', ['f\'(x)=4x³−12x', 'f\'\'(x)=12x²−12', 'f\'\'(x)=12(x²−1)', 'f\'\'=0 at x=±1 (potential inflection points)']),
          ('Differentiate h(x)=e^{sin x}·cos(2x).', ['Product rule: u=e^{sin x}, v=cos(2x)', 'u\'=e^{sin x}·cos x; v\'=−2sin(2x)', 'h\'=e^{sin x}·cos x·cos(2x)+e^{sin x}·(−2sin(2x))', 'h\'=e^{sin x}[cos x·cos(2x)−2sin(2x)]']),
          ('If f\'\'(t) represents acceleration and f\'\'(3)=−5 m/s², interpret this.', ['The velocity is decreasing at t=3 seconds', 'Acceleration is −5 m/s² (decelerating)', 'The object is slowing down if moving in the positive direction', 'Sign of acceleration relative to velocity determines speeding up/slowing down'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Chain Rule & Higher Derivatives', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Differentiate y=ln(sin(x²)) using two chain rule applications', 'Find f\'\'(x) for f(x)=e^{2x}', 'Explain what f\'\'(x)>0 means geometrically']),

      _l('Implicit Differentiation Applications',
         [_t('Finding Tangent Lines to Implicit Curves', 'After finding dy/dx implicitly, substitute the point (x,y) to get the slope, then use point-slope form. Both x and y must be substituted.', 'Students substitute only x and forget to use the y-coordinate in expressions for dy/dx.', 'Find the equation of the tangent to x²+y²=25 at (3,4).'),
          _t('Second Derivative Implicitly', 'Differentiate dy/dx (which contains y) implicitly again with respect to x. Substitute dy/dx back to get d²y/dx² in terms of x and y only.', 'Students treat dy/dx as a constant when differentiating again; it must be differentiated as a function of x.', 'Find d²y/dx² for y²=x implicitly.'),
          _t('Related Rates', 'Differentiate an equation relating two quantities with respect to time t. Each variable gets a rate (dV/dt, dr/dt). Given rates let you find unknown rates.', 'Students forget to differentiate implicitly with respect to t and skip the chain rule factor; every variable changing with time needs a dx/dt term.', 'Set up related rates equations for volumes and areas and solve for an unknown rate.')],
         [('related rates', 'Differentiating an equation with respect to time to find how one rate relates to another'),
          ('implicit curve', 'A curve defined by an equation in x and y that cannot easily be solved for y explicitly'),
          ('d²y/dx²', 'Second derivative found by differentiating dy/dx implicitly again'),
          ('chain rule in time', 'dV/dt = (dV/dr)·(dr/dt); each quantity changing with time requires this factor')],
         ['Find tangent lines to implicitly defined curves', 'Compute second derivatives implicitly', 'Set up and solve related rates problems'],
         ['Related rates is a guaranteed multi-part FR question on the AP® exam', 'Implicit tangent lines in MC and FR', 'Second derivative implicitly in BC FR'],
         ['Find tangent to x²+xy+y²=7 at (1,2)', 'A ladder slides; relate dh/dt to dx/dt using implicit differentiation'],
         [('Find dy/dx and the tangent line to x²+y²=25 at (3,4).', ['2x+2y·dy/dx=0; dy/dx=−x/y', 'At (3,4): dy/dx=−3/4', 'Tangent: y−4=−3/4(x−3)', 'y=−3x/4+25/4']),
          ('Find d²y/dx² for y²=x.', ['Differentiate: 2y·y\'=1; y\'=1/(2y)', 'Differentiate y\' again: y\'\'=d/dx[1/(2y)]', 'Use quotient rule: y\'\'=−(1/(2y²))·y\'=−1/(2y²)·1/(2y)', 'y\'\'=−1/(4y³)']),
          ('A spherical balloon is inflated at 3 cm³/s. Find dr/dt when r=5 cm.', ['V=(4/3)πr³; dV/dt=(4πr²)·dr/dt', '3=4π(25)·dr/dt', 'dr/dt=3/(100π) cm/s', 'Units must be cm/s']),
          ('A 10 ft ladder leans against a wall. The base slides out at 2 ft/s. Find rate the top slides down when base is 6 ft from wall.', ['x²+y²=100; 2x·dx/dt+2y·dy/dt=0', 'x=6, y=8 (3-4-5 scaled); dx/dt=2', '12(2)+16·dy/dt=0', 'dy/dt=−24/16=−3/2 ft/s']),
          ('Find the slope of x³+y³=9 at (1,2).', ['3x²+3y²·y\'=0; y\'=−x²/y²', 'At (1,2): y\'=−1/4', 'Tangent slope is −1/4', 'Tangent line: y−2=−1/4(x−1)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Related Rates', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Set up dV/dt for a cone with changing radius', 'Find d²y/dx² for x²−y²=1 implicitly', 'Explain why both x and y must be substituted when finding tangent slope implicitly']),

      _l('Inverse Function Derivatives',
         [_t('Inverse Function Derivative Theorem', 'If g=f⁻¹, then g\'(x)=1/f\'(g(x)). To find g\'(a), find g(a) first, then evaluate 1/f\'(g(a)).', 'Students try to find the inverse function formula explicitly; the theorem avoids this by relating g\'sto f\'.', 'Use a table of f values to find (f⁻¹)\'(a) without finding f⁻¹ explicitly.'),
          _t('Derivatives of arcsin and arccos', 'd/dx[arcsin x]=1/√(1−x²) and d/dx[arccos x]=−1/√(1−x²). These are derived from the inverse function theorem applied to sin and cos.', 'Students get the sign wrong for arccos; it is the negative of arcsin\'s derivative.', 'Differentiate expressions involving arcsin x and arccos x with chain rule.'),
          _t('Derivatives of arctan and arccot', 'd/dx[arctan x]=1/(1+x²) and d/dx[arccot x]=−1/(1+x²). arctan is the most commonly tested inverse trig derivative.', 'Students forget the denominator is 1+x², not √(1−x²); arctan uses 1+x², arcsin uses √(1−x²).', 'Differentiate arctan(x) in combination with other functions and using chain rule.')],
         [('arcsin', 'Inverse of sin; d/dx[arcsin x]=1/√(1−x²)'),
          ('arctan', 'Inverse of tan; d/dx[arctan x]=1/(1+x²)'),
          ('inverse function theorem', 'g\'(x)=1/f\'(g(x)) where g=f⁻¹'),
          ('arccos', 'Inverse of cos; d/dx[arccos x]=−1/√(1−x²)')],
         ['Apply inverse function derivative theorem from a table', 'Differentiate arcsin and arctan with chain rule', 'Recognize when inverse trig derivatives appear in integrals'],
         ['Inverse function theorem tested via tables: "Given f(3)=7, f\'(3)=2, find (f⁻¹)\'(7)"', 'Arctan derivative integral forms tested in BC', 'Chain rule with inverse trig in FR'],
         ['From a table, find (f⁻¹)\'(5) given f and f\' values', 'Differentiate y=arctan(x²) and y=arcsin(2x)'],
         [('Given f(2)=5 and f\'(2)=3, find (f⁻¹)\'(5).', ['Let g=f⁻¹; g\'(x)=1/f\'(g(x))', 'g(5)=2 (since f(2)=5)', 'g\'(5)=1/f\'(2)=1/3', '(f⁻¹)\'(5)=1/3']),
          ('Differentiate y=arctan(3x).', ['d/dx[arctan u]=1/(1+u²)·u\'', 'u=3x, u\'=3', 'y\'=3/(1+9x²)', 'Chain rule factor is 3']),
          ('Differentiate y=arcsin(√x).', ['u=√x=x^{1/2}; u\'=1/(2√x)', 'd/dx[arcsin u]=1/√(1−u²)·u\'', 'y\'=(1/√(1−x))·(1/(2√x))', 'y\'=1/(2√(x(1−x)))']),
          ('Find (f⁻¹)\'(4) using a table: f(1)=4, f\'(1)=6, f(2)=7, f\'(2)=9.', ['g=f⁻¹; g(4)=1 since f(1)=4', 'g\'(4)=1/f\'(g(4))=1/f\'(1)=1/6', '(f⁻¹)\'(4)=1/6', 'No need to find f⁻¹ explicitly']),
          ('Differentiate y=x·arctan(x).', ['Product rule: u=x, v=arctan x', 'u\'=1, v\'=1/(1+x²)', 'y\'=arctan(x)+x/(1+x²)', 'Both terms present'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Inverse Function Derivatives', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the inverse function derivative theorem formula', 'Differentiate y=arctan(x)/x', 'Explain the difference between arcsin and arccos derivative formulas']),

      _l('Mean Value Theorem and Its Applications',
         [_t('Mean Value Theorem', 'If f is continuous on [a,b] and differentiable on (a,b), then ∃c where f\'(c)=[f(b)−f(a)]/(b−a). The instantaneous rate equals the average rate at some point.', 'Students confuse MVT with IVT; MVT is about derivatives equaling average rate of change, not just function values.', 'Verify MVT conditions and find c satisfying f\'(c)=average rate on a given interval.'),
          _t('Rolle\'s Theorem', 'If f is continuous on [a,b], differentiable on (a,b), and f(a)=f(b), then ∃c where f\'(c)=0. A special case of MVT.', 'Students apply Rolle\'s without verifying f(a)=f(b); all three conditions must hold.', 'Verify Rolle\'s conditions and conclude a horizontal tangent exists.'),
          _t('Extreme Value Theorem', 'If f is continuous on a closed interval [a,b], it attains both an absolute maximum and minimum. Candidates: critical points and endpoints.', 'Students check only critical points and forget endpoints when finding absolute extrema on a closed interval.', 'Find absolute extrema by evaluating f at all critical points and both endpoints.')],
         [('Mean Value Theorem', 'Guarantees f\'(c)=average rate of change on (a,b) for some c'),
          ('Rolle\'s Theorem', 'If f(a)=f(b), there exists c with f\'(c)=0'),
          ('Extreme Value Theorem', 'Continuous function on closed interval attains absolute max and min'),
          ('critical point', 'Where f\'(x)=0 or f\'(x) is undefined; candidate for local/absolute extrema')],
         ['State MVT conditions and apply it to specific functions', 'Use Rolle\'s Theorem to guarantee a horizontal tangent', 'Find absolute extrema on a closed interval using EVT'],
         ['MVT appears as justify/explain questions in FR', 'EVT and closed interval method tested in multi-part FR', 'Rolle\'s Theorem in MC and FR as a theoretical guarantee'],
         ['Verify MVT for f(x)=x²−3 on [1,4] and find c', 'Find absolute max/min of f(x)=x³−3x on [−2,2]'],
         [('Verify MVT for f(x)=x² on [1,3] and find c.', ['f continuous and differentiable (polynomial)', 'Average rate: (9−1)/(3−1)=4', 'f\'(x)=2x; set 2c=4 → c=2', 'c=2∈(1,3) ✓']),
          ('Does Rolle\'s Theorem apply to f(x)=sin x on [0,π]? Find c.', ['f continuous and differentiable; f(0)=f(π)=0', 'All Rolle\'s conditions met', 'f\'(x)=cos x=0 → x=π/2', 'c=π/2∈(0,π) ✓']),
          ('Find absolute max and min of f(x)=x³−3x on [−2,3].', ['f\'(x)=3x²−3=0 → x=±1', 'Evaluate: f(−2)=−2, f(−1)=2, f(1)=−2, f(3)=18', 'Absolute max: f(3)=18; absolute min: f(−1 or 1)=−2', 'Compare all critical points and endpoints']),
          ('A car travels 120 miles in 2 hours. Explain what MVT guarantees.', ['Average speed=60 mph', 'MVT guarantees the car was traveling exactly 60 mph at some moment', 'Requires the position function to be continuous and differentiable', 'Instantaneous rate equals average rate for some c']),
          ('Explain why MVT cannot be applied to f(x)=|x| on [−1,1].', ['f is continuous on [−1,1] ✓', 'But f is not differentiable at x=0 (corner)', 'MVT requires differentiability on the open interval (−1,1)', 'Condition fails; MVT does not apply'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Mean Value Theorem', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State all hypotheses of MVT', 'Give an example where MVT fails and explain why', 'List the candidates for absolute extrema on a closed interval']),
  ],
  'unit_qs': [
      ('Differentiate y=sin(ln(x²+1)) using two chain rule applications.', ['Outer: sin(u), inner: ln(v), innermost: x²+1', 'Outer deriv: cos(ln(x²+1)); inner: 1/(x²+1); innermost: 2x', 'y\'=cos(ln(x²+1))·(1/(x²+1))·2x', 'y\'=2x cos(ln(x²+1))/(x²+1)']),
      ('Find the equation of the tangent line to x²y+y³=10 at (1,2).', ['Differentiate: 2xy+x²y\'+(3y²)y\'=0', 'At (1,2): 4+y\'+(12)y\'=0 → 13y\'=−4', 'y\'=−4/13', 'Tangent: y−2=−4/13(x−1)']),
      ('Given f(4)=1 and f\'(4)=5, find (f⁻¹)\'(1).', ['g=f⁻¹; g(1)=4 since f(4)=1', 'g\'(1)=1/f\'(4)=1/5', '(f⁻¹)\'(1)=1/5', 'Inverse function derivative theorem applied']),
      ('A water tank\'s volume is V=(1/3)πr²h with r=h at all times. Water drains at 2 m³/min. Find dh/dt when h=3 m.', ['Since r=h: V=(1/3)πh³', 'dV/dt=πh²·dh/dt', '−2=π(9)dh/dt', 'dh/dt=−2/(9π) m/min']),
      ('Differentiate f(x)=arctan(e^x).', ['d/dx[arctan u]=1/(1+u²)·u\', u=eˣ', 'u\'=eˣ', 'f\'(x)=eˣ/(1+e^{2x})', 'Chain rule applied once']),
      ('Verify MVT applies to f(x)=√x on [1,9] and find c.', ['f continuous on [1,9], differentiable on (1,9) ✓', 'Average rate: (3−1)/(9−1)=1/4', 'f\'(x)=1/(2√x)=1/4 → √x=2 → x=4', 'c=4∈(1,9) ✓']),
      ('Find all critical points of f(x)=x·e^{−x} and classify them.', ['f\'(x)=e^{−x}+x·(−e^{−x})=e^{−x}(1−x)', 'f\'=0 when x=1 (e^{−x}≠0)', 'f\'(x)>0 for x<1, f\'(x)<0 for x>1', 'Local max at x=1']),
      ('Find f\'\'(x) for f(x)=x·sin(x).', ['f\'(x)=sin(x)+x·cos(x)', 'f\'\'(x)=cos(x)+[cos(x)+x·(−sin x)]', 'f\'\'(x)=2cos(x)−x sin(x)', 'Product rule applied twice']),
      ('Use Rolle\'s Theorem to argue that f(x)=x⁴−2x² has a critical point in (0,√2).', ['f(0)=0 and f(√2)=(4−4)=0; f(0)=f(√2)', 'f is continuous and differentiable', 'By Rolle\'s, ∃c∈(0,√2) with f\'(c)=0', 'f\'(x)=4x³−4x=4x(x²−1); c=1∈(0,√2) ✓']),
      ('Find d²y/dx² for y=sin(x) at x=π.', ['y\'=cos x; y\'\'=−sin x', 'At x=π: y\'\'=−sin(π)=0', 'Neither concave up nor down at this specific point', 'Check nearby values to describe concavity']),
  ],
},

{
  'num': 4, 'title': 'Contextual Applications of Differentiation',
  'file': 'ap-calculus-bc-4-unit-4-contextual-applications-of-differentiation.html',
  'desc': 'Apply derivatives to analyze motion, optimize functions, and sketch curves using calculus tools.',
  'gateway': [
      'Use first and second derivatives to analyze increasing/decreasing and concavity.',
      'Find local and absolute extrema using derivative tests.',
      'Solve optimization problems using calculus.',
      'Analyze motion using position, velocity, and acceleration.',
  ],
  'lessons': [
      _l('Increasing, Decreasing, and First Derivative Test',
         [_t('Monotonicity from f\'', 'f\'(x)>0 means f is increasing; f\'(x)<0 means f is decreasing. Critical points partition the number line into sign intervals.', 'Students evaluate f at the critical point to determine behavior; they must check the sign of f\' in intervals around the critical point.', 'Create a sign chart for f\'(x) and state where f increases and decreases.'),
          _t('First Derivative Test', 'If f\'(x) changes from + to − at c, f has a local max at c. If f\'(x) changes from − to + at c, f has a local min. No sign change means no local extremum.', 'Students classify a critical point as a max just because f\'\'(c)=0; they must check the sign change of f\' around c.', 'Apply first derivative test to classify critical points from a graph or formula of f\'.'),
          _t('Second Derivative Test', 'If f\'(c)=0 and f\'\'(c)<0, local max; if f\'\'(c)>0, local min; if f\'\'(c)=0, test is inconclusive — use first derivative test instead.', 'Students rely on the second derivative test when f\'\'(c)=0, forgetting it is inconclusive in that case.', 'Apply second derivative test where valid and switch to first derivative test when f\'\'(c)=0.')],
         [('critical point', 'x where f\'(x)=0 or undefined; potential extremum'),
          ('first derivative test', 'Classify extrema by the sign change of f\' around the critical point'),
          ('second derivative test', 'f\'(c)=0 and f\'\'(c)<0 → local max; f\'\'(c)>0 → local min'),
          ('sign chart', 'A number line showing the sign of f\' in each interval between critical points')],
         ['Build sign charts to find intervals of increase/decrease', 'Apply first derivative test to classify extrema', 'Use second derivative test as an alternative classification method'],
         ['f\' graphs are given; students must determine behavior of f', 'FR: "On what intervals is f increasing? Justify."', 'Both derivative tests may be tested on the same exam'],
         ['Find local extrema of f(x)=2x³−9x²+12x−4', 'Given a graph of f\', identify local max/min of f'],
         [('Find intervals where f(x)=x³−6x²+9x is increasing.', ['f\'(x)=3x²−12x+9=3(x−1)(x−3)', 'Critical points: x=1, x=3', 'Sign chart: f\'(x)>0 on (−∞,1) and (3,∞)', 'f increasing on (−∞,1) and (3,∞)']),
          ('Classify the critical points of f(x)=x⁴−4x³.', ['f\'(x)=4x³−12x²=4x²(x−3)', 'Critical points: x=0 and x=3', 'Sign chart: f\'<0 on (−∞,0) and (0,3); f\'>0 on (3,∞)', 'No sign change at x=0 (no extremum); local min at x=3']),
          ('Use the second derivative test to classify critical points of f(x)=x³−3x.', ['f\'(x)=3x²−3=0 → x=±1', 'f\'\'(x)=6x; f\'\'(1)=6>0 → local min; f\'\'(−1)=−6<0 → local max', 'Local max at x=−1, local min at x=1', 'Second derivative test conclusive here']),
          ('A graph of f\'(x) is given. f\'(x)>0 on (1,4) and f\'(x)<0 on (4,7). Describe f at x=4.', ['f\' changes from + to − at x=4', 'First derivative test: local maximum of f at x=4', 'f is increasing before x=4 and decreasing after', 'No need to compute f\'\'(4)']),
          ('Explain why x=2 is not a local extremum of f(x)=x³−2, even though f\'\'(2)=0 is inconclusive for the second derivative test.', ['f\'(x)=3x²; f\'(2)=12≠0, so x=2 is not even a critical point', 'Second derivative test only applies when f\'(c)=0', 'Since x=2 is not a critical point, it cannot be a local extremum', 'Always verify f\'(c)=0 before applying either test'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Derivative Tests', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Build a sign chart for f\'(x)=x²(x−3)(x+1)', 'State when the second derivative test is inconclusive', 'Explain how to identify local extrema from a graph of f\'']),

      _l('Concavity and Inflection Points',
         [_t('Concavity from f\'\'', 'f\'\'(x)>0 on an interval means f is concave up (opens upward); f\'\'(x)<0 means concave down. The second derivative measures how the slope is changing.', 'Students think concave up means increasing; a function can be decreasing and concave up simultaneously.', 'Sketch a function that is decreasing and concave up; identify the role of f\'\'.'),
          _t('Inflection Points', 'An inflection point occurs where concavity changes. f\'\'(c) must change sign at c; f\'\'(c)=0 alone is not sufficient (e.g., f(x)=x⁴ at x=0).', 'Students mark every zero of f\'\' as an inflection point; only those where f\'\' changes sign count.', 'Build a sign chart for f\'\' and identify inflection points by sign changes.'),
          _t('Curve Sketching', 'Use f, f\', and f\'\' together: x/y-intercepts, critical points, extrema, inflection points, and asymptotes. The complete picture requires all tools.', 'Students skip checking concavity or only use one derivative; AP® curve sketching requires explicitly justifying each feature.', 'Produce a complete curve sketch with labeled intercepts, extrema, and inflection points.')],
         [('concave up', 'f\'\'(x)>0; the slope of f is increasing; graph curves upward'),
          ('concave down', 'f\'\'(x)<0; the slope of f is decreasing; graph curves downward'),
          ('inflection point', 'Where concavity changes; f\'\' changes sign'),
          ('curve sketching', 'Using f, f\', f\'\' to produce an accurate graph with all features labeled')],
         ['Determine concavity intervals using f\'\'', 'Identify inflection points where f\'\' changes sign', 'Integrate f, f\', f\'\' to produce a complete curve sketch'],
         ['Concavity tested from graphs of f or f\'', 'Inflection points appear in both MC and FR', 'Curve sketching is a classic FR question'],
         ['Find inflection points of f(x)=x⁴−4x³', 'Sketch f(x)=xe^{−x} using all derivative tools'],
         [('Find inflection points of f(x)=x³−6x²+9x+1.', ['f\'\'(x)=6x−12; set equal to 0 → x=2', 'Sign: f\'\'<0 for x<2, f\'\'>0 for x>2', 'f\'\' changes sign at x=2 → inflection point', 'f(2)=8−24+18+1=3; inflection at (2,3)']),
          ('Does f(x)=x⁴ have an inflection point at x=0? Explain.', ['f\'\'(x)=12x²; f\'\'(0)=0', 'Sign: f\'\'(x)=12x²≥0 on both sides', 'f\'\' does not change sign at x=0', 'No inflection point at x=0 despite f\'\'(0)=0']),
          ('Determine concavity of f(x)=sin(x) on [0,2π].', ['f\'\'(x)=−sin(x)', 'f\'\'(x)<0 on (0,π): concave down', 'f\'\'(x)>0 on (π,2π): concave up', 'Inflection point at x=π']),
          ('Describe the relationship between f\' and concavity of f.', ['If f\' is increasing on (a,b), then f is concave up', 'If f\' is decreasing on (a,b), then f is concave down', 'f\'\' measures rate of change of f\' (slope of f\')', 'f\'\'=0 where f\' has a local extremum']),
          ('Given graph of f\': f\'(x) increases on (0,2) and decreases on (2,4). What is f\'\'(2)?', ['If f\' has a local max at x=2, f\' changes from increasing to decreasing', 'f\'\'(2)=0 (zero of second derivative)', 'f\'\'<0 just to right of 2 (f\' decreasing)', 'f has an inflection point at x=2'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Concavity', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Sketch a function that is concave up and decreasing simultaneously', 'Find all inflection points of f(x)=2x³−3x²−12x', 'Explain why f\'\'(c)=0 alone does not guarantee an inflection point']),

      _l('Optimization',
         [_t('Setting Up Optimization Problems', 'Identify the quantity to maximize/minimize (objective function) and any constraints. Express the objective in one variable using the constraint, then differentiate.', 'Students try to optimize multi-variable functions; the constraint must reduce the problem to one variable.', 'Write the objective function in one variable using a geometric or physical constraint.'),
          _t('Closed Interval vs. Unbounded Domains', 'On a closed interval, check critical points and endpoints. On an unbounded domain, verify the single critical point is a max or min using derivative tests.', 'Students skip endpoints on closed interval problems or fail to verify that the single critical point is the desired extremum on unbounded domains.', 'Distinguish closed-interval method from single-critical-point analysis for optimization problems.'),
          _t('Common Optimization Shapes', 'Fencing problems (rectangle with one side fixed), box problems (maximize volume with fixed surface area), distance problems (minimize distance from point to curve). Know the formulas.', 'Students set up the wrong objective function or forget a constraint (e.g., total fencing = fixed perimeter).', 'Recognize the setup pattern for each classic problem type and derive the correct one-variable function.')],
         [('objective function', 'The quantity to be maximized or minimized'),
          ('constraint', 'An equation relating the variables that limits the feasible solutions'),
          ('closed interval method', 'Evaluate f at critical points and endpoints to find absolute extrema'),
          ('optimization', 'Finding the max or min value of a function using calculus')],
         ['Translate word problems into objective + constraint equations', 'Differentiate, solve f\'=0, and verify the extremum', 'Apply closed interval method or single-critical-point test appropriately'],
         ['Optimization is a guaranteed FR topic on both AB and BC', 'Must explicitly justify that the critical point is a max or min', 'Real-world context (fencing, volume, profit) always used'],
         ['Maximize area of rectangle with 100 m of fencing along a river', 'Minimize total surface area of a cylindrical can of volume 500 cm³'],
         [('A farmer has 200 m of fence to enclose a rectangular field along a river (no fence on river side). Maximize area.', ['Let x=width, y=length; constraint: 2x+y=200', 'Objective: A=x·y=x(200−2x)', 'A\'=200−4x=0 → x=50', 'y=100; max area=50×100=5000 m²']),
          ('Find dimensions of a cylindrical can with volume 500π cm³ that minimizes total surface area.', ['V=πr²h=500π → h=500/r²', 'SA=2πr²+2πrh=2πr²+1000π/r', 'SA\'=4πr−1000π/r²=0 → r³=250', 'r=∛250 ≈ 6.3 cm; h=500/r²']),
          ('A box with square base and no lid has volume 32 cm³. Minimize surface area.', ['V=x²h=32 → h=32/x²', 'SA=x²+4xh=x²+128/x', 'SA\'=2x−128/x²=0 → x³=64 → x=4', 'h=2; minimum SA at x=4, h=2']),
          ('Find the point on y=x² closest to (3,0).', ['Distance²=D=(x−3)²+x⁴; minimize D', 'D\'=2(x−3)+4x³=0', 'Solve numerically or by inspection near x=1', 'Minimum distance at x≈1']),
          ('Why must you verify that a critical point from an optimization gives the desired max or min?', ['f\'(c)=0 only means horizontal tangent; could be max, min, or inflection', 'Use first or second derivative test, or check endpoints', 'On open/unbounded domains, must prove global extremum', 'Just because only one critical point exists does not guarantee it\'s a max without verification'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Optimization', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Set up and solve the classic fencing problem', 'Explain how to verify a critical point gives a maximum', 'Write the surface area formula for a cylinder']),

      _l('Motion Along a Line',
         [_t('Position, Velocity, and Acceleration', 'If s(t) is position, v(t)=s\'(t) is velocity, and a(t)=v\'(t)=s\'\'(t) is acceleration. Speed = |v(t)|.', 'Students confuse speed (always non-negative) with velocity (signed). Speed = |v(t)|, not v(t).', 'Given s(t), find v(t) and a(t); determine when the object moves right, left, or is at rest.'),
          _t('Speeding Up and Slowing Down', 'An object speeds up when v(t) and a(t) have the same sign; slows down when they have opposite signs.', 'Students think positive acceleration means speeding up; if v(t)<0 and a(t)>0, the object is actually slowing down.', 'Determine intervals of speeding up/slowing down by comparing signs of v and a.'),
          _t('Total Distance vs. Displacement', 'Displacement = s(b)−s(a). Total distance = ∫|v(t)| dt, which requires identifying zeros of v(t) and integrating each segment separately.', 'Students use displacement (net change) when total distance is asked; they must integrate |v| or split integral at direction changes.', 'Calculate total distance by splitting the integral at each zero of v(t).')],
         [('velocity', 'v(t)=s\'(t); signed rate of change of position'),
          ('acceleration', 'a(t)=v\'(t); rate of change of velocity'),
          ('speed', '|v(t)|; always non-negative'),
          ('displacement', 's(b)−s(a); net change in position (signed)')],
         ['Compute velocity and acceleration from a position function', 'Determine when an object is speeding up or slowing down', 'Distinguish total distance from displacement'],
         ['Motion problems appear in both FR and MC', '"When is the object at rest?" and "when is it speeding up?" are common', 'Displacement vs. total distance often distinguished in the same FR'],
         ['s(t)=t³−6t²+9t; find when at rest, moving right, speeding up', 'Compute displacement and total distance on [0,4]'],
         [('For s(t)=t³−9t²+24t, find velocity and acceleration functions.', ['v(t)=s\'(t)=3t²−18t+24', 'a(t)=v\'(t)=6t−18', 'v(t)=3(t−2)(t−4); zeros at t=2,4', 'a(t)=0 at t=3']),
          ('When is the object in the previous problem speeding up?', ['v(t)=0 at t=2,4; a(t)=0 at t=3', 'Check sign pairs: on (0,2): v>0,a<0 → slowing; (2,3): v<0,a<0 → speeding up', '(3,4): v<0,a>0 → slowing; (4,∞): v>0,a>0 → speeding up', 'Speeding up on (2,3) and (4,∞)']),
          ('Find displacement of s(t)=t²−4t on [1,5].', ['s(5)=25−20=5; s(1)=1−4=−3', 'Displacement=5−(−3)=8 units', 'Positive: net movement is 8 units to the right', 'Not the same as total distance']),
          ('Find total distance traveled for v(t)=t²−4 on [0,3].', ['v(t)=0 at t=2; v<0 on (0,2), v>0 on (2,3)', 'Distance=∫_0^2|t²−4|dt+∫_2^3(t²−4)dt', '=∫_0^2(4−t²)dt+∫_2^3(t²−4)dt', '=[4t−t³/3]_0^2+[t³/3−4t]_2^3=16/3+7/3=23/3']),
          ('Interpret v(t)=−3 at t=5 seconds in context of a particle.', ['The particle is moving in the negative direction at t=5', 'Speed is 3 units per second', 'Negative sign indicates direction, not magnitude', 'Acceleration sign determines if speeding up or slowing down'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Motion along a Line', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the relationship between position, velocity, and acceleration', 'Explain when an object is speeding up vs. slowing down', 'Calculate displacement vs. total distance for s(t)=t³−3t on [0,2]']),
  ],
  'unit_qs': [
      ('Find intervals where f(x)=2x³−3x²−36x+5 is increasing.', ['f\'(x)=6x²−6x−36=6(x−3)(x+2)', 'Critical points: x=3, x=−2', 'f\'(x)>0 on (−∞,−2) and (3,∞)', 'f increasing on (−∞,−2) and (3,∞)']),
      ('Classify critical points of f(x)=x⁴−8x².', ['f\'(x)=4x³−16x=4x(x²−4)=4x(x−2)(x+2)', 'Critical points: x=0,±2', 'f\'\'(x)=12x²−16; f\'\'(0)=−16<0 → local max; f\'\'(±2)=32>0 → local min', 'Local max at x=0; local min at x=±2']),
      ('Find all inflection points of f(x)=x⁴−6x².', ['f\'(x)=4x³−12x; f\'\'(x)=12x²−12=12(x²−1)', 'f\'\'=0 at x=±1; check sign change', 'f\'\'<0 on (−1,1) → concave down; f\'\'>0 outside → concave up', 'Inflection points at x=±1']),
      ('A particle\'s position is s(t)=t³−6t²+9t. When is it moving left?', ['v(t)=3t²−12t+9=3(t−1)(t−3)', 'v(t)<0 on (1,3)', 'Moving left (negative direction) on (1,3)', 'Moving right on (0,1) and (3,∞)']),
      ('Maximize the product of two numbers that sum to 40.', ['Let x and 40−x be the numbers', 'P=x(40−x)=40x−x²', 'P\'=40−2x=0 → x=20', 'Both numbers are 20; max product = 400']),
      ('For f(x)=xe^{−x}, find local extrema and inflection points.', ['f\'(x)=e^{−x}(1−x)=0 → x=1 (local max)', 'f\'\'(x)=e^{−x}(x−2); f\'\'=0 at x=2', 'f\'\' changes sign at x=2: inflection point', 'Local max at (1,e^{−1}); inflection at (2,2e^{−2})']),
      ('An object\'s velocity is v(t)=sin(t) on [0,2π]. Find total distance.', ['v=0 at t=0,π,2π; v>0 on (0,π), v<0 on (π,2π)', '∫_0^π sin t dt=2; ∫_π^{2π}|−sin t|dt=2', 'Total distance=2+2=4', 'Displacement=∫_0^{2π}sin t dt=0']),
      ('Use the second derivative to describe concavity of f(x)=ln(x) for x>0.', ['f\'(x)=1/x; f\'\'(x)=−1/x²<0 for all x>0', 'f is concave down on its entire domain (0,∞)', 'No inflection points since f\'\'<0 everywhere', 'The graph curves downward throughout']),
      ('Find absolute max and min of f(x)=x³−3x+2 on [−2,2].', ['f\'(x)=3x²−3=0 → x=±1', 'Evaluate: f(−2)=0, f(−1)=4, f(1)=0, f(2)=4', 'Absolute max: 4 at x=−1 and x=2', 'Absolute min: 0 at x=−2 and x=1']),
      ('An object\'s velocity v(t) is positive and decreasing. Describe the motion.', ['Positive velocity: moving in positive direction', 'Decreasing velocity: a(t)<0 (negative acceleration)', 'Object is slowing down (v and a have opposite signs)', 'Speed is decreasing even though position is increasing']),
  ],
},

{
  'num': 5, 'title': 'Analytical Applications of Differentiation',
  'file': 'ap-calculus-bc-5-unit-5-analytical-applications-of-differentiation.html',
  'desc': 'Use derivatives analytically to sketch curves, solve optimization, and understand function behavior from graphs of derivatives.',
  'gateway': [
      'Analyze f from graphs of f\' or f\'\'.',
      'Connect behavior of f, f\', and f\'\' in the same context.',
      'Apply differentiation to solve linearization and estimation problems.',
      'Use L\'Hôpital\'s rule for indeterminate limits in applied contexts.',
  ],
  'lessons': [
      _l('Connecting f, f\', and f\'\'',
         [_t('Reading f from a Graph of f\'', 'Where f\'>0, f increases; where f\'<0, f decreases; where f\'=0, f has a critical point. The shape of f\' tells you the shape of f.', 'Students read the graph of f\' as if it were f; they must translate derivative behavior back to the original function.', 'Given a graph of f\', sketch a plausible graph of f and identify all key features.'),
          _t('Reading f from a Graph of f\'\'', 'Where f\'\'(x)>0 (above x-axis), f is concave up; where f\'\'<0, concave down. Where f\'\' changes sign, f has an inflection point.', 'Students confuse where f\'\' is positive (f concave up) with where f\' is positive (f increasing); these are independent.', 'From a graph of f\'\', describe concavity and locate inflection points of f.'),
          _t('All Three Graphs Together', 'When three separate graphs of f, f\', and f\'\' are shown, features connect: local extrema of f appear as zeros of f\'; inflection points of f appear as local extrema of f\'.', 'Students treat each graph independently; the connections across all three graphs are what AP® questions test.', 'Match features across f, f\', and f\'\' graphs: critical points, inflection points, zeros.')],
         [('graph of f\'', 'A graph showing the derivative; used to analyze original function\'s behavior'),
          ('critical point on f\' graph', 'A zero crossing of f\' corresponds to a potential extremum of f'),
          ('sign of f\'\'', 'Positive f\'\' graph → concave up in f; negative → concave down'),
          ('corresponding features', 'Inflection points of f appear as local extrema of f\'')],
         ['Interpret a graph of f\' to determine behavior of f', 'Translate f\'\' graph into concavity information for f', 'Connect all three function graphs to each other'],
         ['Graph reading is a primary AP® skill; at least 2 MC questions guaranteed', 'FR parts often ask to justify using "graph of f\'" language', 'Matching graphs tested in MC'],
         ['Given graph of f\', find where f has local max/min', 'Sketch f from a given f\' graph'],
         [('From a graph of f\': f\'(x)>0 on (0,3), f\'(3)=0, f\'(x)<0 on (3,6). Describe f at x=3.', ['f\' changes from + to − at x=3', 'By first derivative test, f has a local maximum at x=3', 'f is increasing before x=3 and decreasing after', 'Height of f at x=3 is the highest nearby value']),
          ('From a graph of f\'\': f\'\'(x)>0 on (0,2), f\'\'(2)=0, f\'\'(x)<0 on (2,4). What happens to f at x=2?', ['f\'\' changes sign from + to −', 'f has an inflection point at x=2', 'f transitions from concave up to concave down', 'f\'(x) has a local maximum at x=2 (since f\' was increasing then decreasing)']),
          ('A graph shows f\'(x) has a local minimum at x=1. What does this mean for f?', ['f\'(x) has a local min: f\' was decreasing then increasing at x=1', 'This means f\'\' changes from − to + at x=1', 'f has an inflection point at x=1', 'f was concave down before x=1 and concave up after']),
          ('Sketch f given: f(0)=2, f\'(x)>0 on (0,2), f\'(2)=0, f\'(x)<0 on (2,5), f\'\'(x)<0 on (0,2), f\'\'(x)>0 on (2,5).', ['f increases on (0,2), decreases on (2,5)', 'Concave down on (0,2), concave up on (2,5)', 'Local max at x=2; inflection at x=2 also (concavity changes there)', 'Graph rises with downward curl, peaks, then falls with upward curl']),
          ('The graph of f\' is a straight line from (0,4) to (4,−4). Find the x-value where f has a local max.', ['f\' starts positive and decreases to negative', 'f\'(x)=0 when the line crosses the x-axis: at x=2', 'f\' changes from + to −', 'f has a local maximum at x=2'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — f, f\', f\'\' Connection', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Sketch f from a given f\' graph', 'List all features of f that can be read from the graph of f\'', 'Explain the relationship between local extrema of f\' and inflection points of f']),

      _l('Linearization and Differentials',
         [_t('Linear Approximation', 'L(x)=f(a)+f\'(a)(x−a) is the tangent line approximation. Near x=a, f(x)≈L(x). Accuracy decreases as x moves away from a.', 'Students confuse the linearization formula with the tangent line equation; they are the same equation written differently.', 'Use linearization to estimate f(a+0.1) or similar values without a calculator.'),
          _t('Differentials', 'dy=f\'(x)dx. A differential approximates the change in y for a small change in x. Δy ≈ dy when Δx is small.', 'Students confuse Δy (actual change) with dy (approximate change); dy is always the tangent line approximation.', 'Compute dy for a function and use it to estimate changes.'),
          _t('Error Estimation', 'If a quantity is computed from a measured value with error ε, the propagated error is approximately |f\'(x)|·ε. Used in problems about measurement uncertainty.', 'Students calculate the error as a percentage of the function value rather than using the differential.', 'Use differentials to estimate propagated error in calculations.')],
         [('linearization', 'L(x)=f(a)+f\'(a)(x−a); tangent line used as an approximation'),
          ('differential', 'dy=f\'(x)dx; approximates the change in y'),
          ('Δy vs dy', 'Δy is actual change; dy=f\'(x)dx is the linear approximation of that change'),
          ('error propagation', 'Using differentials to estimate error: Δy≈(dy/dx)·Δx')],
         ['Write and use linearization formula to approximate function values', 'Compute differentials and interpret them', 'Use differentials for error estimation in applied problems'],
         ['Linearization appears in BC FR and MC', 'Differentials tested in context of approximation problems', 'Often combined with: "Is this an overestimate or underestimate?"'],
         ['Use L(x) to estimate √9.1 using f(x)=√x, a=9', 'Find dy for y=x³ and estimate Δy when x changes from 2 to 2.01'],
         [('Use linearization to estimate √25.1.', ['f(x)=√x, a=25; f(25)=5, f\'(x)=1/(2√x), f\'(25)=1/10', 'L(x)=5+(1/10)(x−25)', 'L(25.1)=5+(1/10)(0.1)=5.01', 'Actual: √25.1≈5.00999; linearization is very close']),
          ('Find dy for y=sin(x) at x=π/6 with dx=0.02.', ['dy=cos(x)·dx', 'At x=π/6: cos(π/6)=√3/2', 'dy=(√3/2)(0.02)≈0.01732', 'Estimated change in sin(x) is about 0.017']),
          ('Is L(x.1) an overestimate or underestimate for f(x)=√x near x=25?', ['f\'\'(x)=−1/(4x^{3/2})<0 for all x>0', 'Concave down means tangent line lies above the curve', 'Linearization overestimates √x', 'Overestimate because f is concave down']),
          ('A sphere has radius 5 cm with error of 0.05 cm. Estimate the error in computed volume.', ['V=(4/3)πr³; dV=4πr²·dr', 'At r=5: dV=4π(25)(0.05)=5π cm³', 'Error in volume ≈ 5π ≈ 15.7 cm³', 'Relative error = 5π/((4/3)π(125))=3%']),
          ('Explain why linearization becomes less accurate further from x=a.', ['Tangent line approximates the curve locally', 'As x moves away from a, curvature accumulates', 'The approximation error grows with (x−a)²', 'f\'\'(a) controls the rate at which accuracy falls'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Khan Academy — Linear Approximation', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['Write the linearization of f(x)=cos(x) at x=0', 'Compute dy for y=ln(x) and interpret it', 'Explain when a linearization over- vs. underestimates']),

      _l('L\'Hôpital\'s Rule in Depth',
         [_t('All Indeterminate Forms', 'Beyond 0/0 and ∞/∞: 0·∞ (rewrite as 0/(1/∞)), ∞−∞ (combine fractions), 1^∞, 0⁰, ∞⁰ (take ln). Each can be converted to 0/0 or ∞/∞.', 'Students only recognize 0/0 and ∞/∞ as indeterminate; the other forms (especially 1^∞) require logarithmic conversion.', 'Identify the indeterminate form, convert to 0/0 or ∞/∞, then apply L\'Hôpital\'s Rule.'),
          _t('Repeated Application', 'If L\'Hôpital\'s Rule yields another indeterminate form, apply it again. Differentiate numerator and denominator independently each time.', 'Students differentiate f/g as a quotient (quotient rule) instead of differentiating f and g separately.', 'Apply L\'Hôpital\'s Rule multiple times until the limit is determinate.'),
          _t('When L\'Hôpital\'s Does Not Apply', 'If the form is not indeterminate (e.g., 2/0), L\'Hôpital\'s Rule cannot be used; the limit is ±∞. Applying it incorrectly to non-indeterminate forms gives wrong answers.', 'Students apply L\'Hôpital\'s Rule to 2/0, getting a wrong finite answer; verify indeterminate form first.', 'Check the form before applying L\'Hôpital\'s; if not indeterminate, analyze as an infinite limit.')],
         [('indeterminate form', '0/0, ∞/∞, 0·∞, ∞−∞, 1^∞, 0⁰, ∞⁰ — forms that require further analysis'),
          ('L\'Hôpital\'s Rule', 'If form is 0/0 or ∞/∞: lim f/g = lim f\'/g\''),
          ('0·∞ conversion', 'Rewrite f·g = f/(1/g) or g/(1/f) to get 0/0 or ∞/∞'),
          ('1^∞ conversion', 'Take ln: ln(f^g)=g·ln f, then exponentiate the final limit')],
         ['Classify all seven indeterminate forms', 'Convert 0·∞, ∞−∞, and exponential forms to apply L\'Hôpital\'s', 'Know when L\'Hôpital\'s does not apply'],
         ['All seven forms can appear on BC exam', 'Exponential indeterminate forms (1^∞) common in BC MC', 'AB: primarily 0/0 and ∞/∞'],
         ['Evaluate lim_{x→0⁺} x·ln(x) and lim_{x→∞}(1+1/x)^x', 'Evaluate lim_{x→0} (1/sin x − 1/x)'],
         [('Evaluate lim_{x→∞} x·e^{−x}.', ['Form 0·∞; rewrite as x/eˣ → ∞/∞', 'L\'Hôpital: 1/eˣ → 0', 'Limit = 0', 'Exponentials dominate polynomials']),
          ('Evaluate lim_{x→0⁺} x^x (form 0⁰).', ['Take ln: ln(x^x)=x·ln x → 0·(−∞)', 'Rewrite: ln x/(1/x) → −∞/∞; L\'Hôpital: (1/x)/(−1/x²)=−x', 'lim_{x→0⁺}(−x)=0, so ln(x^x)→0', 'Therefore x^x→e⁰=1']),
          ('Evaluate lim_{x→∞}(1+2/x)^x (form 1^∞).', ['Take ln: x·ln(1+2/x) → ∞·0; rewrite ln(1+2/x)/(1/x)', 'L\'Hôpital: (−2/x²)/(1+2/x)/(−1/x²)=2/(1+2/x)', 'As x→∞: limit of ln expression = 2', 'Therefore (1+2/x)^x → e²']),
          ('Evaluate lim_{x→0}(1/x − 1/sin x).', ['Combine fractions: (sin x−x)/(x·sin x) → 0/0', 'L\'Hôpital: (cos x−1)/(sin x+x cos x)', 'Still 0/0; L\'Hôpital again: (−sin x)/(2cos x−x sin x)', 'At x=0: 0/2=0; limit = 0']),
          ('Can L\'Hôpital\'s Rule be applied to lim_{x→2}(x²−4)/(x−2)?', ['Form: 0/0 when x=2 ✓', 'Can apply: lim 2x/1=4', 'But factoring gives same answer: cancel (x−2), evaluate x+2=4', 'Both methods valid for 0/0 form'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — All Indeterminate Forms', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['List all seven indeterminate forms', 'Explain how to handle the 1^∞ form', 'Give an example where L\'Hôpital\'s Rule should not be applied']),

      _l('Parametric and Vector-Valued Functions (BC)',
         [_t('Parametric Derivatives', 'For x=f(t), y=g(t): dy/dx=(dy/dt)/(dx/dt)=g\'(t)/f\'(t). Second derivative: d²y/dx²=[d(dy/dx)/dt]/(dx/dt).', 'Students compute dy/dx as g\'(t)/f\'(t) correctly but then compute d²y/dx² as g\'\'(t)/f\'\'(t) — wrong; use the formula above.', 'Compute first and second derivatives of parametric curves.'),
          _t('Slope and Tangent Lines in Parametric Form', 'Horizontal tangents where dy/dt=0 and dx/dt≠0; vertical tangents where dx/dt=0 and dy/dt≠0. The tangent line uses the parametric slope.', 'Students find where dy/dt=0 without checking dx/dt; if both are zero at the same t, the situation is indeterminate.', 'Find horizontal and vertical tangents of parametric curves by setting appropriate derivatives to zero.'),
          _t('Vectors and Motion (BC)', 'A particle\'s position vector is ⟨x(t),y(t)⟩. Velocity vector: ⟨x\'(t),y\'(t)⟩. Speed = √(x\'²+y\'²). Acceleration vector: ⟨x\'\'(t),y\'\'(t)⟩.', 'Students confuse speed (scalar magnitude) with velocity (vector); speed = |v| = √(x\'²+y\'²).', 'Compute speed and acceleration from parametric position; find direction of motion.')],
         [('parametric equations', 'x=f(t), y=g(t); position described as function of parameter t'),
          ('dy/dx parametric', 'g\'(t)/f\'(t) = (dy/dt)/(dx/dt)'),
          ('speed (parametric)', '|v|=√((dx/dt)²+(dy/dt)²)'),
          ('velocity vector', '⟨dx/dt, dy/dt⟩; direction and rate of motion')],
         ['Compute parametric derivatives and slopes', 'Find horizontal and vertical tangents for parametric curves', 'Calculate speed and acceleration vectors'],
         ['Parametric and vector functions are BC-only; tested in FR part', 'Speed calculation commonly tested', 'Second derivative of parametric curve in BC FR'],
         ['Find dy/dx and d²y/dx² for x=t², y=t³−t at t=1', 'Find horizontal tangents for x=sin t, y=cos(2t)'],
         [('Find dy/dx at t=1 for x=t², y=t³−3t.', ['dx/dt=2t; dy/dt=3t²−3', 'dy/dx=(3t²−3)/(2t)', 'At t=1: (3−3)/2=0', 'Horizontal tangent at t=1']),
          ('Find d²y/dx² for x=t², y=t³ at t=2.', ['dy/dx=(3t²)/(2t)=3t/2', 'd/dt[dy/dx]=3/2', 'd²y/dx²=(3/2)/(2t)=3/(4t)', 'At t=2: 3/8']),
          ('Find horizontal tangents for x=t−sin t, y=1−cos t.', ['dy/dt=sin t; set sin t=0 → t=0,π,2π,...', 'Check dx/dt=1−cos t at t=0: 1−1=0 (indeterminate)', 'At t=π: dx/dt=1−(−1)=2≠0; horizontal tangent', 'Horizontal tangent at t=π']),
          ('A particle moves with x(t)=cos t, y(t)=sin(2t). Find the speed at t=π/4.', ['dx/dt=−sin t; dy/dt=2cos(2t)', 'At t=π/4: dx/dt=−sin(π/4)=−√2/2; dy/dt=2cos(π/2)=0', 'Speed=√(1/2+0)=√(1/2)=√2/2', 'Speed=√2/2 units/time']),
          ('Find vertical tangents for x=t²−4, y=t³−12t.', ['dx/dt=2t; set 2t=0 → t=0', 'dy/dt=3t²−12; at t=0: dy/dt=−12≠0', 'Vertical tangent at t=0', 'Point: x(0)=−4, y(0)=0 → (−4,0)'])],
         [('https://www.youtube.com/watch?v=fYyARMqiaag', 'Professor Leonard — Parametric Derivatives', 'https://www.youtube.com/watch?v=fYyARMqiaag')],
         ['State the formula for dy/dx in parametric form', 'Explain how to find d²y/dx² parametrically', 'Compute speed for x=3cos t, y=4sin t at t=π/6']),
  ],
  'unit_qs': [
      ('From a graph: f\'(x)>0 on (−2,1), f\'(1)=0, f\'(x)<0 on (1,4). Describe f on this interval.', ['f is increasing on (−2,1), decreasing on (1,4)', 'f has a local maximum at x=1', 'Cannot determine absolute max without more info', 'Shape: rises to peak at x=1, then falls']),
      ('Use linearization to estimate e^{0.1} using f(x)=eˣ at a=0.', ['f(0)=1, f\'(0)=1', 'L(x)=1+1·(x−0)=1+x', 'L(0.1)=1.1', 'Actual e^{0.1}≈1.10517; linearization is an underestimate since f is concave up']),
      ('Evaluate lim_{x→0⁺} x·ln(x).', ['Form 0·(−∞); rewrite as ln(x)/(1/x) → −∞/∞', 'L\'Hôpital: (1/x)/(−1/x²)=−x', 'lim_{x→0⁺}(−x)=0', 'Limit=0']),
      ('For parametric x=t+1, y=t²−2t, find dy/dx and the slope at t=3.', ['dx/dt=1; dy/dt=2t−2', 'dy/dx=(2t−2)/1=2t−2', 'At t=3: dy/dx=4', 'Tangent line slope is 4']),
      ('Explain why linearization of f(x)=x³ at a=2 overestimates for x<2 and underestimates for x>2 (or neither — explain).', ['f\'\'(x)=6x; at x=2, f\'\'(2)=12>0 → concave up', 'Tangent line to concave up function lies below the curve', 'Linearization underestimates f(x) for x≠2', 'Concave up → tangent below → underestimate everywhere near a']),
      ('From a graph of f\'\': f\'\'(x)<0 on (0,3) and f\'\'(x)>0 on (3,6). What does this tell you about f\'?', ['f\'\'<0 means f\' is decreasing on (0,3)', 'f\'\'(x)>0 means f\' is increasing on (3,6)', 'f\' has a local minimum at x=3', 'f has an inflection point at x=3']),
      ('Evaluate lim_{x→∞}(1+1/x)^{3x} (form 1^∞).', ['Take ln: 3x·ln(1+1/x) → 3x·(1/x) via L\'Hôpital', 'lim = 3', 'Original limit = e³', 'This is related to the definition of e']),
      ('Find the speed of a particle with x(t)=t², y(t)=t³ at t=1.', ['dx/dt=2t; at t=1: dx/dt=2', 'dy/dt=3t²; at t=1: dy/dt=3', 'Speed=√(4+9)=√13', 'Units match position\'s units per time unit']),
      ('Determine if f(x)=x⁵ has an inflection point at x=0.', ['f\'\'(x)=20x³; f\'\'(0)=0', 'Sign: f\'\'(x)<0 for x<0, f\'\'(x)>0 for x>0', 'f\'\' changes sign at x=0', 'Inflection point at x=0 ✓']),
      ('A curve is defined by x=e^t, y=te^t. Find the tangent line at t=0.', ['dx/dt=eᵗ; dy/dt=eᵗ+teᵗ=eᵗ(1+t)', 'dy/dx=(1+t)', 'At t=0: slope=1; point=(1,0)', 'Tangent line: y−0=1(x−1) → y=x−1']),
  ],
},
]
