NAME = 'AP® Chemistry'
ABBREV = 'chem'
SLUG = 'ap-chemistry'
COURSE_FILE = 'ap-chemistry.html'
ACCENT_COLOR = '#2dd4bf'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Chemistry+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 6,
        'title': 'Unit 6: Thermodynamics',
        'file': 'ap-chemistry-6-unit-6-thermodynamics.html',
        'desc': 'Energy changes in chemical reactions, entropy, Gibbs free energy, and spontaneity.',
        'gateway': [
            'Define enthalpy and calculate ΔH using Hess\'s law.',
            'Relate entropy to disorder and predict sign of ΔS.',
            'Use ΔG = ΔH − TΔS to predict spontaneity.',
            'Connect ΔG° to equilibrium constant K.',
        ],
        'lessons': [
            _l('Enthalpy and Calorimetry',
               [
                   _t('Enthalpy Change', 'ΔH measures heat flow at constant pressure; negative ΔH = exothermic, positive ΔH = endothermic.', 'ΔH is not the same as ΔE (internal energy); they differ by PΔV work.', 'Calculate ΔH from q = mcΔT in calorimetry problems.'),
                   _t('Hess\'s Law', 'ΔH for a reaction equals the sum of ΔH values for any series of steps that add up to the overall reaction.', 'Reversing a reaction flips the sign of ΔH; multiplying by a factor scales ΔH.', 'Add or reverse given reactions to derive target; manipulate ΔH accordingly.'),
                   _t('Bond Enthalpy', 'ΔH ≈ Σ(bonds broken) − Σ(bonds formed); breaking bonds requires energy, forming bonds releases it.', 'Bond enthalpy values are averages and give approximate, not exact, ΔH.', 'Use provided bond enthalpies to estimate ΔH for gas-phase reactions.'),
               ],
               [('enthalpy (ΔH)', 'Heat flow at constant pressure; negative for exothermic reactions.'),
                ('calorimetry', 'Measurement of heat flow using q = mcΔT or q = CΔT.'),
                ('Hess\'s law', 'ΔH of a reaction is the sum of ΔH values for any valid sequence of steps.'),
                ('standard enthalpy of formation (ΔHf°)', 'Enthalpy change forming 1 mol of compound from elements in standard states.'),
                ('bond enthalpy', 'Energy required to break one mole of a bond in the gas phase.')],
               ['Calculate ΔH using q = mcΔT from calorimetry data.', 'Apply Hess\'s law by combining reaction steps.', 'Estimate ΔH from bond enthalpies.'],
               ['Multi-step Hess\'s law problems combining 3+ reactions.', 'Calorimetry calculations with coffee-cup or bomb calorimeter context.', 'Comparing ΔH from formation enthalpies vs. bond enthalpies.'],
               ['Khan Academy: Thermochemistry', 'Bozeman Science: Enthalpy'],
               [('What is the heat released when 50.0 g of water cools from 75°C to 25°C (c = 4.18 J/g·°C)?', ['10,450 J', '10,450 J', '2,090 J', '5,225 J', '8,360 J']),
                ('Hess\'s law is based on which property of enthalpy?', ['It is a state function', 'It is always negative', 'It depends on path', 'It equals entropy', 'It requires catalysts']),
                ('If ΔHf° for CO₂(g) = −393.5 kJ/mol, what does this represent?', ['Forming 1 mol CO₂ from C(s) and O₂(g)', 'Combusting 1 mol carbon', 'Breaking all bonds in CO₂', 'Dissolving CO₂ in water', 'Decompressing CO₂ gas']),
                ('A reaction has ΔH = +50 kJ. It is:', ['Endothermic', 'Exothermic', 'Isothermal', 'Spontaneous', 'Adiabatic']),
                ('Bond energy calculations are most accurate for:', ['Gas-phase reactions', 'Aqueous reactions', 'Solid-state reactions', 'Ionic compounds', 'Nuclear reactions']),
               ],
               [('Bozeman Science: Enthalpy', 'Covers ΔH, Hess\'s law, and calorimetry with worked examples.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What sign of ΔH indicates an exothermic reaction?', 'State Hess\'s law in your own words.', 'How does bond breaking vs. bond forming relate to ΔH?']
            ),
            _l('Entropy and the Second Law',
               [
                   _t('Entropy (ΔS)', 'Entropy measures dispersal of energy and matter; systems tend toward greater entropy (Second Law).', 'Entropy is not "disorder" in a colloquial sense but statistical dispersal of microstates.', 'Predict sign of ΔS: more moles of gas, mixing, or phase changes to gas increase entropy.'),
                   _t('Standard Entropy', 'S° values are absolute (not relative to elements) and increase with molecular complexity and phase.', 'Unlike ΔHf°, standard entropy of elements is NOT zero.', 'Calculate ΔS°rxn = ΣS°(products) − ΣS°(reactants).'),
                   _t('Third Law', 'Perfect crystalline solid at 0 K has S = 0; all real substances have positive S° at 298 K.', 'The Third Law sets the absolute scale; entropy can never be negative.', 'Use Third Law to understand why S° for elements is nonzero.'),
               ],
               [('entropy (S)', 'Measure of energy dispersal and number of accessible microstates in a system.'),
                ('Second Law of Thermodynamics', 'The entropy of the universe increases for any spontaneous process.'),
                ('Third Law of Thermodynamics', 'Perfect crystal at 0 K has zero entropy.'),
                ('microstates', 'Number of equivalent ways energy can be distributed among particles.'),
                ('standard molar entropy (S°)', 'Absolute entropy of one mole of a substance at 298 K and 1 atm.')],
               ['Predict the sign of ΔS for a reaction from inspection.', 'Calculate ΔS°rxn from tabulated S° values.', 'Explain the Third Law and its significance.'],
               ['Predicting sign of ΔS from changes in moles of gas or phase.', 'Calculating ΔS° from provided S° data.', 'Relating entropy to number of microstates.'],
               ['Khan Academy: Entropy', 'Bozeman Science: Entropy and Gibbs Free Energy'],
               [('Which process has the largest positive ΔS?', ['2H₂O(l) → 2H₂(g) + O₂(g)', 'H₂O(g) → H₂O(l)', 'NaCl(s) → NaCl(l)', 'CO₂(g) → CO₂(s)', 'Fe(s) → Fe(l)']),
                ('Standard entropy of elements at 298 K is:', ['Positive (nonzero)', 'Always zero', 'Negative', 'Equal to ΔHf°', 'Undefined']),
                ('ΔS°rxn is calculated as:', ['ΣS°(products) − ΣS°(reactants)', 'ΣS°(reactants) − ΣS°(products)', 'ΔH/T', 'ΔG − ΔH', 'ΣΔHf°']),
                ('A gas expanding into a vacuum has ΔS:', ['Positive', 'Negative', 'Zero', 'Equal to ΔH/T', 'Negative at low T']),
                ('The Third Law states entropy is zero for:', ['Perfect crystal at 0 K', 'Any element at 298 K', 'Ideal gases at STP', 'Ionic solids at 0°C', 'Pure liquids at 273 K']),
               ],
               [('Bozeman Science: Entropy', 'Explains microstates, Second Law, and entropy calculations.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What does entropy measure at the molecular level?', 'State the Second Law of Thermodynamics.', 'Why is S° for elements not zero?']
            ),
            _l('Gibbs Free Energy',
               [
                   _t('Gibbs Free Energy', 'ΔG = ΔH − TΔS; a reaction is spontaneous when ΔG < 0.', 'Spontaneous does not mean fast — kinetics and thermodynamics are independent.', 'Determine spontaneity from signs of ΔH and ΔS at given temperature.'),
                   _t('Temperature Dependence', 'When ΔH and ΔS have the same sign, spontaneity depends on temperature (T = ΔH/ΔS is the crossover point).', 'A reaction with ΔH > 0 and ΔS > 0 becomes spontaneous only above a threshold T.', 'Use T = ΔH/ΔS to find where ΔG = 0.'),
                   _t('ΔG° and Equilibrium', 'ΔG° = −RT ln K; a large K corresponds to a large negative ΔG°.', 'ΔG (not ΔG°) predicts spontaneity at non-standard conditions; they differ by RT ln Q.', 'Use ΔG° = −RT ln K to interconvert between ΔG° and K.'),
               ],
               [('Gibbs free energy (ΔG)', 'Thermodynamic potential predicting spontaneity: ΔG = ΔH − TΔS.'),
                ('spontaneous process', 'A process that occurs without continuous outside work; ΔG < 0.'),
                ('standard Gibbs free energy (ΔG°)', 'ΔG at standard conditions (1 atm, 1 M, 298 K).'),
                ('equilibrium constant (K)', 'Ratio of product to reactant activities at equilibrium; related to ΔG° by ΔG° = −RT ln K.'),
                ('reaction quotient (Q)', 'Ratio of product to reactant concentrations at any point; compared to K to predict direction.')],
               ['Apply ΔG = ΔH − TΔS to predict spontaneity.', 'Identify temperature conditions for spontaneity when ΔH and ΔS have same sign.', 'Interconvert ΔG° and K using ΔG° = −RT ln K.'],
               ['Calculating ΔG from ΔH and ΔS at a given T.', 'Predicting sign of ΔG for all four ΔH/ΔS combinations.', 'Relating ΔG° to K magnitude and reaction favorability.'],
               ['Khan Academy: Gibbs Free Energy', 'Bozeman Science: Gibbs Free Energy'],
               [('A reaction has ΔH = −80 kJ and ΔS = −200 J/K at 298 K. ΔG is:', ['−80 kJ − (298)(−0.200 kJ/K) = −20.4 kJ', '+40 kJ', '−80 kJ', '+20 kJ', '−140 kJ']),
                ('ΔG < 0 means the reaction is:', ['Spontaneous', 'Nonspontaneous', 'At equilibrium', 'Endothermic', 'Slow']),
                ('A reaction with ΔH > 0 and ΔS > 0 is spontaneous:', ['At high temperature', 'At low temperature', 'At all temperatures', 'Never', 'Only in solution']),
                ('When ΔG° = 0, the equilibrium constant K equals:', ['1', '0', '∞', '−1', 'e']),
                ('ΔG° = −RT ln K. If K > 1, then ΔG° is:', ['Negative', 'Positive', 'Zero', 'Equal to ΔH', 'Undefined']),
               ],
               [('Bozeman Science: Gibbs Free Energy', 'Covers ΔG = ΔH − TΔS, spontaneity, and connection to K.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What is the sign of ΔG for a spontaneous reaction?', 'How does temperature affect spontaneity when ΔH and ΔS are both positive?', 'What does it mean when ΔG° = −RT ln K?']
            ),
            _l('Thermodynamics Applications',
               [
                   _t('Coupled Reactions', 'Cells couple nonspontaneous reactions (ΔG > 0) to spontaneous ones (ATP hydrolysis) so the net ΔG is negative.', 'Coupling requires direct mechanistic connection, not just adding ΔG values.', 'Add ΔG values for coupled reactions to determine overall spontaneity.'),
                   _t('Electrochemistry Connection', 'ΔG° = −nFE°cell links thermodynamics to electrochemistry; positive E°cell means negative ΔG°.', 'Students confuse n (moles of electrons) with stoichiometric coefficients.', 'Calculate ΔG° from E°cell and number of moles of electrons transferred.'),
                   _t('Phase Transitions', 'At a phase transition (e.g., melting), ΔG = 0 and T = ΔH/ΔS; the two phases are in equilibrium.', 'ΔG = 0 at the transition temperature, not throughout the entire phase change.', 'Calculate boiling/melting point from ΔH and ΔS of the phase transition.'),
               ],
               [('coupled reactions', 'Pairing a nonspontaneous reaction with a spontaneous one to drive it forward.'),
                ('Faraday\'s constant (F)', '96,485 C/mol electrons; relates electrical charge to chemical change.'),
                ('cell potential (E°cell)', 'Voltage produced by a galvanic cell under standard conditions.'),
                ('phase transition', 'Change of state (solid↔liquid↔gas) occurring at constant T and P.'),
                ('standard conditions', '298 K, 1 atm pressure, 1 M concentration for all species.')],
               ['Explain how coupled reactions can drive nonspontaneous processes.', 'Use ΔG° = −nFE°cell to relate electrochemistry and thermodynamics.', 'Determine phase transition temperature from ΔH and ΔS.'],
               ['Calculating ΔG° from cell potential in electrochemistry context.', 'Determining T at which a phase transition occurs using ΔG = 0.', 'Explaining biological energy coupling conceptually.'],
               ['Khan Academy: Thermodynamics and Electrochemistry', 'Bozeman Science: Electrochemistry and Gibbs'],
               [('At a phase transition temperature, ΔG equals:', ['0', 'ΔH', '−TΔS', 'ΔH − ΔS', 'RT ln K']),
                ('ΔG° = −nFE°cell. If E°cell = +1.10 V and n = 2, ΔG° is:', ['−212 kJ', '+212 kJ', '−106 kJ', '+55 kJ', '−55 kJ']),
                ('A positive E°cell means the cell reaction is:', ['Spontaneous (ΔG < 0)', 'Nonspontaneous', 'At equilibrium', 'Endothermic', 'Slow']),
                ('ATP hydrolysis drives muscle contraction because:', ['ΔGtotal is negative when reactions are coupled', 'ΔH is always negative', 'Entropy decreases', 'K < 1', 'Temperature increases']),
                ('At the boiling point of water, liquid and vapor are:', ['In equilibrium (ΔG = 0)', 'Spontaneously converting to vapor', 'Spontaneously converting to liquid', 'At maximum entropy', 'At minimum enthalpy']),
               ],
               [('Bozeman Science: Thermodynamics Applications', 'Covers coupling, electrochemical connections, and phase equilibria.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['How can a nonspontaneous reaction be driven forward?', 'What is the sign of ΔG° when E°cell is positive?', 'What is ΔG at a phase transition temperature?']
            ),
        ],
        'unit_qs': [
            ('ΔH for a reaction is −200 kJ and ΔS = +100 J/K at 298 K. ΔG is:', ['−229.8 kJ', '−170.2 kJ', '+229.8 kJ', '−200 kJ', '+170.2 kJ']),
            ('Which combination of ΔH and ΔS is always spontaneous?', ['ΔH < 0 and ΔS > 0', 'ΔH > 0 and ΔS < 0', 'ΔH > 0 and ΔS > 0', 'ΔH < 0 and ΔS < 0', 'ΔH = 0 and ΔS = 0']),
            ('Standard enthalpy of formation of an element in its standard state is:', ['Zero', 'Positive', 'Negative', 'Equal to S°', 'Undefined']),
            ('A reaction has K = 1000. Its ΔG° is:', ['Large and negative', 'Large and positive', 'Zero', 'Equal to ΔH', 'Positive at high T']),
            ('Hess\'s law works because enthalpy is a:', ['State function', 'Path function', 'Kinetic property', 'Concentration-dependent variable', 'Temperature-independent quantity']),
            ('Which process has ΔS < 0?', ['2NO₂(g) → N₂O₄(g)', 'NaCl(s) → Na⁺(aq) + Cl⁻(aq)', 'H₂O(l) → H₂O(g)', 'CaCO₃(s) → CaO(s) + CO₂(g)', 'I₂(s) → I₂(g)']),
            ('The crossover temperature where ΔG = 0 is found by:', ['T = ΔH/ΔS', 'T = ΔG/ΔS', 'T = ΔH/ΔG', 'T = R ln K', 'T = nFE/R']),
            ('ΔG > 0 at standard conditions means K is:', ['Less than 1', 'Greater than 1', 'Equal to 1', 'Equal to e', 'Undefined']),
            ('In a bomb calorimeter (constant volume), the measured quantity is:', ['ΔE (internal energy)', 'ΔH (enthalpy)', 'ΔG (free energy)', 'ΔS (entropy)', 'ΔHf°']),
            ('The Second Law of Thermodynamics states:', ['Entropy of the universe increases in spontaneous processes', 'Energy is conserved', 'Entropy is zero at 0 K', 'Enthalpy drives all reactions', 'ΔG = ΔH at constant T']),
        ],
    },
    {
        'num': 7,
        'title': 'Unit 7: Equilibrium',
        'file': 'ap-chemistry-7-unit-7-equilibrium.html',
        'desc': 'Dynamic equilibrium, equilibrium expressions, Le Chatelier\'s principle, and solubility equilibria.',
        'gateway': [
            'Write equilibrium constant expressions (Kc, Kp) for reactions.',
            'Use ICE tables to find equilibrium concentrations.',
            'Apply Le Chatelier\'s principle to predict equilibrium shifts.',
            'Solve Ksp problems for solubility and precipitation.',
        ],
        'lessons': [
            _l('Equilibrium Expressions',
               [
                   _t('Dynamic Equilibrium', 'At equilibrium, forward and reverse reaction rates are equal; concentrations remain constant but reactions continue.', 'Equilibrium does not mean equal concentrations of reactants and products.', 'Recognize characteristics of equilibrium: constant concentrations, closed system, dynamic process.'),
                   _t('Kc and Kp', 'Kc uses molar concentrations; Kp uses partial pressures. They are related by Kp = Kc(RT)^Δn where Δn = moles gas products − moles gas reactants.', 'Pure solids and liquids are omitted from K expressions because their activity is 1.', 'Write Kc and Kp expressions for given reactions; relate them using Δn.'),
                   _t('Magnitude of K', 'K >> 1: products favored at equilibrium. K << 1: reactants favored. K ≈ 1: significant amounts of both.', 'K magnitude says nothing about reaction rate.', 'Interpret K values in terms of equilibrium position.'),
               ],
               [('equilibrium constant (Kc)', 'Ratio of product concentrations to reactant concentrations, each raised to stoichiometric power.'),
                ('Kp', 'Equilibrium constant expressed in terms of partial pressures of gases.'),
                ('Δn', 'Change in moles of gas (products − reactants) in a balanced equation.'),
                ('dynamic equilibrium', 'State where forward and reverse rates are equal; concentrations remain constant.'),
                ('activity', 'Effective concentration; pure solids/liquids have activity = 1 and are excluded from K.')],
               ['Write Kc expressions correctly excluding pure solids and liquids.', 'Interconvert Kc and Kp using Δn.', 'Interpret magnitude of K in terms of equilibrium position.'],
               ['Writing K expressions for heterogeneous equilibria.', 'Calculating Kp from Kc or vice versa.', 'Comparing K values to predict which direction equilibrium lies.'],
               ['Khan Academy: Equilibrium', 'Bozeman Science: Equilibrium Expressions'],
               [('For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), Kc =', ['[NH₃]²/([N₂][H₂]³)', '[N₂][H₂]³/[NH₃]²', '[NH₃]/([N₂][H₂])', '[2NH₃]/([N₂][3H₂])', '[NH₃]²/[N₂][H₂]']),
                ('Pure solids are excluded from K because:', ['Their activity is defined as 1', 'They are not reactive', 'They have zero concentration', 'They don\'t dissolve', 'They change volume']),
                ('K = 1.0 × 10⁻⁸ indicates:', ['Reactants heavily favored at equilibrium', 'Products heavily favored', 'Equal amounts of reactants and products', 'Fast forward reaction', 'Fast reverse reaction']),
                ('Kp = Kc(RT)^Δn. If Δn = 0, then:', ['Kp = Kc', 'Kp > Kc', 'Kp < Kc', 'Kp = 0', 'Kp = RT']),
                ('At equilibrium, which is true?', ['Forward rate = reverse rate', 'Concentrations are equal', 'ΔG = ΔG°', 'No reactions occur', 'K = 1']),
               ],
               [('Bozeman Science: Equilibrium Expressions', 'Covers Kc, Kp, and writing equilibrium expressions.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What is dynamic equilibrium?', 'Why are pure solids excluded from Kc expressions?', 'What does K >> 1 tell you about the equilibrium position?']
            ),
            _l('ICE Tables and Calculations',
               [
                   _t('ICE Table Method', 'ICE (Initial, Change, Equilibrium) tables organize concentration changes to solve for equilibrium values.', 'The change row must maintain stoichiometric ratios from the balanced equation.', 'Set up ICE tables correctly and solve for x using the K expression.'),
                   _t('Reaction Quotient Q', 'Q is calculated like K but at non-equilibrium conditions; comparing Q to K predicts reaction direction.', 'Q > K means too many products; reaction shifts left. Q < K means reaction shifts right.', 'Calculate Q and compare to K to predict equilibrium direction.'),
                   _t('Approximation Method', 'If K is very small (< 10⁻³), x is negligible compared to initial concentration; [A]eq ≈ [A]₀.', 'Always check that x < 5% of initial concentration to validate the approximation.', 'Apply the 5% approximation rule to simplify equilibrium calculations.'),
               ],
               [('ICE table', 'Organized method to track Initial, Change, and Equilibrium concentrations.'),
                ('reaction quotient (Q)', 'Same expression as K but calculated at any point, not just equilibrium.'),
                ('5% approximation', 'Simplification valid when K is small: assume x is negligible relative to initial concentration.'),
                ('shift left', 'Equilibrium moves toward reactants (reverse reaction favored).'),
                ('shift right', 'Equilibrium moves toward products (forward reaction favored).')],
               ['Construct ICE tables to find equilibrium concentrations.', 'Calculate Q and predict reaction direction by comparing to K.', 'Apply the 5% approximation where appropriate.'],
               ['Multi-step ICE table problems with Kc.', 'Determining direction of equilibrium shift from Q vs. K.', 'Validating the 5% approximation.'],
               ['Khan Academy: ICE Tables', 'Bozeman Science: Calculating Equilibrium Concentrations'],
               [('In an ICE table, "C" (change) entries must:', ['Follow stoichiometric ratios', 'Always be positive', 'Always be negative', 'Equal initial concentrations', 'Sum to zero']),
                ('Q < K means the reaction will:', ['Shift right (toward products)', 'Shift left (toward reactants)', 'Remain at equilibrium', 'Increase temperature', 'Decrease concentration']),
                ('For A ⇌ B with Kc = 0.01 and [A]₀ = 1.0 M, [B]₀ = 0, x at equilibrium ≈', ['0.099 M', '0.5 M', '0.01 M', '1.0 M', '0.001 M']),
                ('The 5% approximation is valid when:', ['x < 5% of initial concentration', 'K > 1', 'T > 298 K', 'Q = K', 'Products are favored']),
                ('Q > K means:', ['Products are in excess; reaction shifts left', 'Reactants are in excess; reaction shifts right', 'System is at equilibrium', 'K will increase', 'Temperature must rise']),
               ],
               [('Bozeman Science: ICE Tables', 'Step-by-step guidance on setting up and solving ICE table problems.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What do the letters I, C, and E stand for in an ICE table?', 'If Q > K, which direction does the reaction shift?', 'When is the 5% approximation valid?']
            ),
            _l('Le Chatelier\'s Principle',
               [
                   _t('Le Chatelier\'s Principle', 'When a system at equilibrium is disturbed, it shifts to partially counteract the disturbance and re-establish equilibrium.', 'Le Chatelier\'s principle predicts direction but not the final equilibrium position or K value.', 'Predict shifts for concentration, pressure, and temperature changes.'),
                   _t('Concentration Changes', 'Adding a reactant shifts equilibrium right; removing a product also shifts right. Adding a product shifts left.', 'Adding an inert gas at constant volume does not affect equilibrium because partial pressures are unchanged.', 'Predict equilibrium shift when specific concentrations are increased or decreased.'),
                   _t('Temperature Effects', 'Increasing T shifts equilibrium in the endothermic direction; K changes with temperature.', 'Unlike concentration and pressure changes, temperature changes alter the value of K.', 'Determine how K changes with temperature for exothermic vs. endothermic reactions.'),
               ],
               [('Le Chatelier\'s principle', 'System at equilibrium shifts to counteract a stress and re-establish equilibrium.'),
                ('stress', 'Any disturbance that shifts a system from equilibrium (concentration, pressure, temperature change).'),
                ('endothermic direction', 'Reaction direction that absorbs heat; favored by increasing temperature.'),
                ('exothermic direction', 'Reaction direction that releases heat; favored by decreasing temperature.'),
                ('inert gas', 'A gas that does not participate in the reaction; at constant volume, does not shift equilibrium.')],
               ['Apply Le Chatelier\'s principle to predict shifts from concentration changes.', 'Predict equilibrium shift from pressure changes by analyzing moles of gas.', 'Explain how temperature changes affect both equilibrium position and K.'],
               ['Multi-factor Le Chatelier problems (simultaneous changes).', 'Distinguishing between changes that affect K vs. those that only shift equilibrium.', 'Industrial applications (Haber process) connecting Le Chatelier to real chemistry.'],
               ['Khan Academy: Le Chatelier\'s Principle', 'Bozeman Science: Le Chatelier'],
               [('For N₂ + 3H₂ ⇌ 2NH₃, increasing pressure shifts equilibrium:', ['Right (toward fewer moles of gas)', 'Left', 'Not at all', 'K increases', 'K decreases']),
                ('Adding more reactant to a reaction at equilibrium:', ['Shifts equilibrium right', 'Shifts equilibrium left', 'Does not change equilibrium', 'Decreases K', 'Increases temperature']),
                ('Which change DOES alter the value of K?', ['Temperature change', 'Adding a reactant', 'Removing a product', 'Adding inert gas', 'Changing volume']),
                ('For an exothermic reaction, increasing temperature:', ['Shifts equilibrium left, decreasing K', 'Shifts equilibrium right, increasing K', 'Does not affect K', 'Increases concentration of products', 'Has no effect']),
                ('Adding an inert gas at constant volume:', ['Does not shift equilibrium', 'Shifts right', 'Shifts left', 'Increases K', 'Decreases partial pressures']),
               ],
               [('Bozeman Science: Le Chatelier\'s Principle', 'Predicting equilibrium shifts from various stresses.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['State Le Chatelier\'s principle in your own words.', 'Does adding a reactant change K? Why or why not?', 'How does increasing temperature affect an exothermic reaction\'s K?']
            ),
            _l('Solubility Equilibria',
               [
                   _t('Ksp Expressions', 'Ksp (solubility product) is the equilibrium constant for dissolving an ionic solid; larger Ksp means greater solubility.', 'Ksp compares solubility only for salts of the same ion stoichiometry.', 'Write Ksp expressions and calculate molar solubility from Ksp.'),
                   _t('Common Ion Effect', 'Adding an ion already in solution decreases solubility of a sparingly soluble salt (Le Chatelier: shifts left).', 'The common ion effect is a specific application of Le Chatelier\'s principle to solubility.', 'Calculate reduced solubility in a solution containing a common ion.'),
                   _t('Precipitation', 'Precipitation occurs when ion product Q > Ksp; no precipitation if Q < Ksp; saturated solution if Q = Ksp.', 'Q for precipitation uses actual concentrations before mixing (account for dilution).', 'Calculate Q after mixing solutions and predict whether precipitate forms.'),
               ],
               [('solubility product (Ksp)', 'Equilibrium constant for dissolution of sparingly soluble ionic compound.'),
                ('molar solubility', 'Moles of solute dissolved per liter of saturated solution.'),
                ('common ion effect', 'Reduction in solubility of a salt when a common ion is added to solution.'),
                ('ion product (Q)', 'Product of ion concentrations at a given moment; compared to Ksp to predict precipitation.'),
                ('saturated solution', 'Solution where dissolved and undissolved solute are in equilibrium; Q = Ksp.')],
               ['Write Ksp expressions and calculate molar solubility from Ksp.', 'Predict how the common ion effect reduces solubility.', 'Calculate ion product Q and predict precipitation.'],
               ['Calculating molar solubility with or without common ion.', 'Mixing two solutions and predicting precipitation using Q vs. Ksp.', 'Relating Ksp to molar solubility for different salt types.'],
               ['Khan Academy: Solubility Equilibria', 'Bozeman Science: Ksp'],
               [('For Ca₃(PO₄)₂ ⇌ 3Ca²⁺ + 2PO₄³⁻, Ksp =', ['[Ca²⁺]³[PO₄³⁻]²', '[Ca²⁺][PO₄³⁻]', '[Ca²⁺]²[PO₄³⁻]³', '[Ca²⁺]³[PO₄³⁻]² / [Ca₃(PO₄)₂]', '[Ca²⁺][PO₄³⁻]²']),
                ('Adding NaCl to a saturated AgCl solution:', ['Decreases Ag⁺ concentration (common ion effect)', 'Increases solubility', 'Does not change solubility', 'Increases Ksp', 'Precipitates NaCl']),
                ('A precipitate forms when:', ['Q > Ksp', 'Q < Ksp', 'Q = Ksp', 'K < 1', 'ΔG > 0']),
                ('Ksp for BaSO₄ = 1.1 × 10⁻¹⁰. Molar solubility =', ['1.05 × 10⁻⁵ M', '1.1 × 10⁻¹⁰ M', '2.2 × 10⁻¹⁰ M', '1.05 × 10⁻⁸ M', '1.1 × 10⁻⁵ M']),
                ('The common ion effect is an application of:', ['Le Chatelier\'s principle', 'Hess\'s law', 'The Arrhenius equation', 'Boyle\'s law', 'Coulomb\'s law']),
               ],
               [('Bozeman Science: Ksp and Solubility', 'Covers Ksp expressions, molar solubility, and the common ion effect.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What is Ksp and what does a larger value mean?', 'Explain the common ion effect using Le Chatelier\'s principle.', 'How do you determine if a precipitate will form?']
            ),
        ],
        'unit_qs': [
            ('For A(g) + 2B(g) ⇌ C(g), increasing pressure shifts equilibrium:', ['Right (fewer moles of gas)', 'Left', 'No change', 'K increases', 'K decreases']),
            ('At equilibrium, Q equals:', ['K', '0', '1', 'ΔG/RT', 'Ksp']),
            ('Which factor does NOT change K?', ['Adding a reactant at constant T', 'Increasing temperature', 'Decreasing temperature', 'Using a catalyst (wait — catalyst does not change K)', 'None']),
            ('For a reaction with K = 1.0 × 10⁻¹², the equilibrium strongly favors:', ['Reactants', 'Products', 'Neither', 'Depends on temperature', 'Depends on pressure']),
            ('In an ICE table, if initial [A] = 0.10 M and x = 0.005 M, [A] at equilibrium is:', ['0.095 M', '0.105 M', '0.010 M', '0.005 M', '0.100 M']),
            ('Le Chatelier\'s principle predicts:', ['Direction of equilibrium shift', 'New value of K', 'Activation energy', 'Reaction rate', 'Enthalpy change']),
            ('Ksp for AgCl = 1.8 × 10⁻¹⁰. In 0.10 M NaCl, molar solubility of AgCl ≈', ['1.8 × 10⁻⁹ M', '1.8 × 10⁻¹⁰ M', '1.34 × 10⁻⁵ M', '0.10 M', '1.8 × 10⁻⁵ M']),
            ('Removing a product from an equilibrium system:', ['Shifts equilibrium right', 'Shifts equilibrium left', 'Has no effect', 'Decreases K', 'Increases K']),
            ('For an endothermic reaction, increasing temperature:', ['Increases K', 'Decreases K', 'Does not change K', 'Shifts equilibrium left', 'Increases activation energy']),
            ('The relationship between K and ΔG° is:', ['ΔG° = −RT ln K', 'ΔG° = RT ln K', 'ΔG° = nFE°', 'ΔG° = ΔH − TΔS', 'ΔG° = −nRT']),
        ],
    },
    {
        'num': 8,
        'title': 'Unit 8: Acids and Bases',
        'file': 'ap-chemistry-8-unit-8-acids-and-bases.html',
        'desc': 'Acid-base theories, pH calculations, buffers, and titrations.',
        'gateway': [
            'Define acids and bases using Brønsted-Lowry and Lewis theories.',
            'Calculate pH, pOH, [H⁺], and [OH⁻] for strong and weak acids/bases.',
            'Explain how buffers resist pH change.',
            'Interpret titration curves for strong and weak acid-base systems.',
        ],
        'lessons': [
            _l('Acid-Base Theories and Equilibria',
               [
                   _t('Brønsted-Lowry Theory', 'Acids donate protons (H⁺); bases accept protons. Conjugate acid-base pairs differ by one H⁺.', 'Amphiprotic species (like H₂O, HCO₃⁻) can act as either acid or base depending on the partner.', 'Identify conjugate acid-base pairs and write proton-transfer equations.'),
                   _t('Lewis Theory', 'Lewis acids accept electron pairs; Lewis bases donate electron pairs. Broader than Brønsted-Lowry.', 'All Brønsted-Lowry acids are Lewis acids, but not all Lewis acids are Brønsted-Lowry acids.', 'Identify Lewis acid and Lewis base in coordinate bond formation.'),
                   _t('Water Autoionization', 'Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ at 25°C; pH + pOH = 14 at 25°C.', 'Kw changes with temperature; pH = 7 is neutral only at 25°C.', 'Use Kw to interconvert [H⁺], [OH⁻], pH, and pOH.'),
               ],
               [('Brønsted-Lowry acid', 'Species that donates a proton (H⁺) in a reaction.'),
                ('Brønsted-Lowry base', 'Species that accepts a proton (H⁺) in a reaction.'),
                ('conjugate acid-base pair', 'Two species differing by one proton; acid and its conjugate base.'),
                ('Lewis acid', 'Electron pair acceptor.'),
                ('autoionization of water', 'H₂O + H₂O ⇌ H₃O⁺ + OH⁻; Kw = 1.0 × 10⁻¹⁴ at 25°C.')],
               ['Identify Brønsted-Lowry conjugate acid-base pairs.', 'Distinguish Lewis acid-base from Brønsted-Lowry definitions.', 'Use Kw to relate [H⁺] and [OH⁻].'],
               ['Identifying conjugate pairs in acid-base reactions.', 'Recognizing Lewis acid-base interactions in coordinate chemistry.', 'Calculating pH from [H⁺] and vice versa.'],
               ['Khan Academy: Acids and Bases', 'Bozeman Science: Acid-Base Theories'],
               [('In HCl + H₂O → H₃O⁺ + Cl⁻, the conjugate base of HCl is:', ['Cl⁻', 'H₃O⁺', 'H₂O', 'OH⁻', 'HCl']),
                ('A Lewis acid:', ['Accepts an electron pair', 'Donates an electron pair', 'Donates a proton', 'Accepts a proton', 'Releases OH⁻']),
                ('At 25°C, [OH⁻] in pure water is:', ['1.0 × 10⁻⁷ M', '1.0 × 10⁻¹⁴ M', '7.0 M', '1.0 M', '0 M']),
                ('An amphiprotic species can:', ['Act as both acid and base', 'Only donate protons', 'Only accept protons', 'Never react with water', 'Form only Lewis acid-base pairs']),
                ('pH + pOH = 14 at:', ['25°C only (where Kw = 1.0 × 10⁻¹⁴)', 'All temperatures', '0°C', '100°C', 'Any temperature if in water']),
               ],
               [('Bozeman Science: Acid-Base Theories', 'Covers Brønsted-Lowry, Lewis theory, and water autoionization.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What is the difference between a Brønsted-Lowry acid and a Lewis acid?', 'What is a conjugate acid-base pair?', 'What is Kw, and what is its value at 25°C?']
            ),
            _l('Strong and Weak Acids/Bases',
               [
                   _t('Strong Acids and Bases', 'Strong acids (HCl, HBr, HI, HNO₃, HClO₄, H₂SO₄) dissociate 100%; [H⁺] = initial acid concentration.', 'H₂SO₄ is diprotic; only the first proton is fully dissociated in dilute solutions.', 'Calculate pH directly from concentration for strong acids and bases.'),
                   _t('Weak Acid Equilibria', 'Weak acids partially dissociate; use Ka and ICE table to find [H⁺] and pH.', 'Ka is not the same as percent dissociation; both must be calculated separately.', 'Set up Ka expression and ICE table to solve weak acid pH problems.'),
                   _t('Weak Bases and Kb', 'Weak bases partially accept protons; use Kb and ICE table to find [OH⁻] and pH.', 'For conjugate acid-base pairs: Ka × Kb = Kw; stronger acid has weaker conjugate base.', 'Use Kb to calculate [OH⁻] then convert to pH for weak base solutions.'),
               ],
               [('Ka', 'Acid dissociation constant; larger Ka means stronger acid.'),
                ('Kb', 'Base dissociation constant; larger Kb means stronger base.'),
                ('percent dissociation', 'Fraction of weak acid or base that ionizes, expressed as percent.'),
                ('strong acid', 'Acid that dissociates completely in aqueous solution; Ka >> 1.'),
                ('weak acid', 'Acid that only partially dissociates; Ka < 1.')],
               ['Calculate pH of strong acid and base solutions.', 'Use Ka and ICE tables to find pH of weak acid solutions.', 'Relate Ka and Kb for conjugate pairs using Kw.'],
               ['Multi-step weak acid pH calculations using ICE tables.', 'Calculating percent dissociation of a weak acid.', 'Comparing acidity of two weak acids from Ka values.'],
               ['Khan Academy: Weak Acid-Base Equilibria', 'Bozeman Science: Ka and Kb'],
               [('For a 0.1 M HCl solution, pH =', ['1', '2', '7', '13', '0']),
                ('Ka = 1.8 × 10⁻⁵ for acetic acid. This indicates acetic acid is:', ['A weak acid', 'A strong acid', 'A strong base', 'A weak base', 'Neutral']),
                ('Ka × Kb for a conjugate pair equals:', ['Kw (1.0 × 10⁻¹⁴)', '1', 'K', 'RT', 'Ka²']),
                ('Percent dissociation of a weak acid increases when:', ['Concentration decreases', 'Concentration increases', 'Temperature decreases', 'Ka decreases', 'pH increases']),
                ('For a 0.1 M NaOH solution, pOH =', ['1', '7', '13', '2', '14']),
               ],
               [('Bozeman Science: Ka and Kb', 'Explains weak acid/base equilibria, ICE table setup, and conjugate pair relationships.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['Why can\'t you use pH = −log[acid] for a weak acid?', 'What is the relationship between Ka and Kb for a conjugate pair?', 'How does dilution affect percent dissociation of a weak acid?']
            ),
            _l('Buffers',
               [
                   _t('Buffer Composition', 'A buffer contains a weak acid and its conjugate base (or weak base and its conjugate acid) in significant amounts.', 'Not every mixture of acid and base creates a buffer — stoichiometry must leave significant amounts of both components.', 'Identify whether a solution is a buffer from its composition.'),
                   _t('Henderson-Hasselbalch Equation', 'pH = pKa + log([A⁻]/[HA]) calculates buffer pH quickly.', 'Henderson-Hasselbalch is an approximation valid when [A⁻]/[HA] is between 0.1 and 10.', 'Use Henderson-Hasselbalch to calculate buffer pH and to design buffers at a target pH.'),
                   _t('Buffer Capacity', 'Buffer capacity is greatest when [HA] = [A⁻] (pH = pKa); large concentrations increase capacity.', 'A buffer is overwhelmed when strong acid or base added exceeds its buffering components.', 'Predict how addition of strong acid or base changes buffer pH.'),
               ],
               [('buffer', 'Solution that resists pH change upon addition of small amounts of strong acid or base.'),
                ('Henderson-Hasselbalch equation', 'pH = pKa + log([A⁻]/[HA]); calculates pH of a buffer.'),
                ('buffer capacity', 'Amount of acid or base a buffer can neutralize before significant pH change.'),
                ('pKa', 'Negative log of Ka; represents pH at which [HA] = [A⁻] in a buffer.'),
                ('conjugate base', 'Species formed after an acid donates its proton; the A⁻ component of a buffer.')],
               ['Identify buffer solutions from composition.', 'Apply Henderson-Hasselbalch to calculate buffer pH.', 'Explain buffer capacity and its dependence on concentration and ratio.'],
               ['Calculating pH after adding strong acid/base to a buffer.', 'Designing a buffer at a target pH using Henderson-Hasselbalch.', 'Comparing buffer capacities of different concentrations.'],
               ['Khan Academy: Buffer Solutions', 'Bozeman Science: Buffers'],
               [('A buffer is best described as:', ['Weak acid + conjugate base in significant amounts', 'Any mixture of acid and base', 'Strong acid + strong base', 'A solution with pH = 7', 'A pure weak acid']),
                ('pH = pKa + log([A⁻]/[HA]). If [A⁻] = [HA], then pH =', ['pKa', 'pKa + 1', 'pKa − 1', '7', '14 − pKa']),
                ('Buffer capacity is greatest when:', ['[HA] = [A⁻]', '[HA] >> [A⁻]', '[A⁻] >> [HA]', 'pH = 7', 'Temperature is low']),
                ('Adding HCl to a buffer containing CH₃COOH/CH₃COO⁻:', ['Converts A⁻ to HA, slightly decreasing pH', 'Converts HA to A⁻, slightly increasing pH', 'Has no effect', 'Destroys the buffer immediately', 'Increases Kw']),
                ('Which pair makes an effective buffer?', ['HF and NaF', 'HCl and NaCl', 'NaOH and NaCl', 'H₂SO₄ and Na₂SO₄', 'HNO₃ and NaNO₃']),
               ],
               [('Bozeman Science: Buffers', 'Covers buffer composition, Henderson-Hasselbalch, and buffer capacity.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What two components make up an acidic buffer?', 'What is pH equal to when [HA] = [A⁻] in a buffer?', 'How does adding strong acid affect a buffer?']
            ),
            _l('Titrations',
               [
                   _t('Titration Curve Shapes', 'Strong acid-strong base: sharp equivalence point at pH 7. Weak acid-strong base: equivalence point above pH 7 (conjugate base is basic).', 'The equivalence point is where moles of acid = moles of base added, not necessarily where pH = 7.', 'Sketch titration curves and identify equivalence points and half-equivalence points.'),
                   _t('Half-Equivalence Point', 'At the half-equivalence point in a weak acid titration, pH = pKa because [HA] = [A⁻].', 'Henderson-Hasselbalch directly gives pH = pKa at the half-equivalence point.', 'Use half-equivalence point to determine Ka from a titration curve.'),
                   _t('Indicators', 'Acid-base indicators are weak acids where HIn and In⁻ have different colors; they change color near their pKa.', 'A good indicator has a pKa within ±1 unit of the equivalence point pH.', 'Select appropriate indicator based on expected equivalence point pH.'),
               ],
               [('equivalence point', 'Point in a titration where moles of acid exactly equal moles of base.'),
                ('half-equivalence point', 'Point where half the acid has been neutralized; pH = pKa for weak acid titration.'),
                ('indicator', 'Weak acid or base that changes color at a characteristic pH.'),
                ('endpoint', 'Observed color change of indicator; ideally matches the equivalence point.'),
                ('titrant', 'Solution of known concentration added from a burette during a titration.')],
               ['Sketch and interpret strong and weak acid-base titration curves.', 'Identify and use the half-equivalence point to determine Ka.', 'Select an appropriate indicator for a given titration.'],
               ['Interpreting titration curves at equivalence and buffer regions.', 'Calculating Ka from pH at half-equivalence point.', 'Predicting equivalence point pH for weak acid/base titrations.'],
               ['Khan Academy: Titrations', 'Bozeman Science: Titrations'],
               [('In a strong acid-strong base titration, the equivalence point pH is:', ['7 (neutral)', 'Above 7', 'Below 7', 'Depends on acid concentration', 'Equal to pKa']),
                ('In a weak acid-strong base titration, equivalence point pH is:', ['Above 7 (conjugate base is basic)', 'Exactly 7', 'Below 7', 'Equal to pKa', 'Equal to pOH']),
                ('At the half-equivalence point of a weak acid titration:', ['pH = pKa', 'pH = 7', 'pH = pKb', '[HA] = 0', '[A⁻] = 0']),
                ('An indicator should be chosen so that its pKa:', ['Is close to the equivalence point pH', 'Is equal to 7', 'Is much lower than equivalence point pH', 'Is much higher than equivalence point pH', 'Matches the analyte pKa']),
                ('A diprotic acid titration curve has:', ['Two equivalence points', 'One equivalence point', 'No equivalence point', 'An equivalence point at pH 7 always', 'A flat curve']),
               ],
               [('Bozeman Science: Titrations', 'Covers titration curve shapes, equivalence points, and indicator selection.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['Why is the equivalence point above pH 7 for a weak acid-strong base titration?', 'How do you determine Ka from a titration curve?', 'What makes an indicator suitable for a particular titration?']
            ),
        ],
        'unit_qs': [
            ('pH of a 0.010 M HNO₃ solution is:', ['2', '1', '3', '7', '12']),
            ('For acetic acid (Ka = 1.8 × 10⁻⁵) at 0.1 M, approximate [H⁺] is:', ['1.34 × 10⁻³ M', '1.8 × 10⁻⁵ M', '0.1 M', '1.8 × 10⁻⁶ M', '1.0 × 10⁻⁷ M']),
            ('A buffer made from NH₃ and NH₄⁺ (pKa = 9.25) has pH = 9.25 when:', ['[NH₃] = [NH₄⁺]', '[NH₃] > [NH₄⁺]', '[NH₄⁺] > [NH₃]', 'Temperature = 37°C', 'Volume = 1.0 L']),
            ('The conjugate acid of HPO₄²⁻ is:', ['H₂PO₄⁻', 'PO₄³⁻', 'H₃PO₄', 'OH⁻', 'H₂O']),
            ('AlCl₃ in water forms an acidic solution because Al³⁺ acts as a:', ['Lewis acid (polarizes water to release H⁺)', 'Brønsted-Lowry acid', 'Lewis base', 'Weak base', 'Neutral species']),
            ('pOH of a solution with [OH⁻] = 1.0 × 10⁻³ M is:', ['3', '11', '7', '1', '14']),
            ('Which has the lowest pH at the same concentration?', ['HCl (strong acid)', 'CH₃COOH (Ka = 1.8 × 10⁻⁵)', 'HF (Ka = 6.8 × 10⁻⁴)', 'HCN (Ka = 6.2 × 10⁻¹⁰)', 'H₂CO₃ (Ka₁ = 4.3 × 10⁻⁷)']),
            ('Adding 0.01 mol HCl to 1 L of a well-designed buffer:', ['Slightly decreases pH', 'Drastically decreases pH', 'Does not change pH', 'Increases pH', 'Destroys the buffer immediately']),
            ('In a weak base-strong acid titration, the equivalence point pH is:', ['Below 7', 'Exactly 7', 'Above 7', 'Equal to pKb', 'Equal to 14']),
            ('The Henderson-Hasselbalch equation is a rearrangement of:', ['The Ka expression for weak acid equilibrium', 'The Nernst equation', 'Le Chatelier\'s principle', 'The Arrhenius equation', 'Hess\'s law']),
        ],
    },
    {
        'num': 9,
        'title': 'Unit 9: Electrochemistry',
        'file': 'ap-chemistry-9-unit-9-electrochemistry.html',
        'desc': 'Oxidation-reduction, galvanic cells, electrolysis, and the Nernst equation.',
        'gateway': [
            'Assign oxidation numbers and identify oxidizing/reducing agents.',
            'Calculate E°cell from standard reduction potentials.',
            'Relate E°cell to ΔG° and K.',
            'Explain electrolysis and calculate amounts using Faraday\'s law.',
        ],
        'lessons': [
            _l('Oxidation-Reduction Reactions',
               [
                   _t('Oxidation Numbers', 'Oxidation numbers track electron transfer: oxidation = increase in oxidation number; reduction = decrease.', 'Assigning oxidation numbers in polyatomic ions requires knowing common element oxidation states.', 'Assign oxidation numbers and identify which species is oxidized/reduced.'),
                   _t('Oxidizing and Reducing Agents', 'The oxidizing agent is reduced (gains electrons); the reducing agent is oxidized (loses electrons).', 'Students often confuse which agent is oxidized vs. reduced — the oxidizing agent undergoes reduction.', 'Identify the oxidizing agent, reducing agent, and the changes in each for a given redox reaction.'),
                   _t('Balancing Redox Reactions', 'Half-reaction method: split into oxidation and reduction half-reactions, balance atoms and charge, then combine.', 'In acidic solution, add H⁺ and H₂O to balance; in basic solution, add OH⁻ after balancing.', 'Balance redox reactions using the half-reaction method in acidic and basic solutions.'),
               ],
               [('oxidation', 'Loss of electrons; increase in oxidation number.'),
                ('reduction', 'Gain of electrons; decrease in oxidation number.'),
                ('oxidizing agent', 'Species that accepts electrons and is itself reduced.'),
                ('reducing agent', 'Species that donates electrons and is itself oxidized.'),
                ('half-reaction', 'Equation showing only the oxidation or only the reduction process in a redox reaction.')],
               ['Assign oxidation numbers to all atoms in compounds and ions.', 'Identify oxidizing agent and reducing agent from a redox equation.', 'Balance redox reactions using the half-reaction method.'],
               ['Balancing complex redox reactions in acidic or basic solution.', 'Identifying which species is oxidized and which is reduced.', 'Recognizing common oxidizing agents (MnO₄⁻, Cr₂O₇²⁻, O₂).'],
               ['Khan Academy: Redox Reactions', 'Bozeman Science: Oxidation-Reduction'],
               [('In MnO₄⁻, the oxidation number of Mn is:', ['+7', '+2', '+4', '−2', '0']),
                ('Oxidation is defined as:', ['Loss of electrons', 'Gain of electrons', 'Loss of protons', 'Gain of protons', 'Decrease in oxidation number']),
                ('In Zn + CuSO₄ → ZnSO₄ + Cu, the reducing agent is:', ['Zn', 'Cu', 'SO₄²⁻', 'CuSO₄', 'ZnSO₄']),
                ('When balancing redox in acidic solution, you can add:', ['H⁺ and H₂O', 'OH⁻ only', 'H₂O only', 'NaOH', 'Both H⁺ and OH⁻']),
                ('The half-reaction for Mn²⁺ → MnO₄⁻ (acidic) involves:', ['Oxidation (Mn goes from +2 to +7)', 'Reduction', 'No change in Mn', 'Addition of electrons to left side', 'Loss of oxygen atoms']),
               ],
               [('Bozeman Science: Oxidation-Reduction', 'Covers oxidation numbers, identifying redox reactions, and balancing half-reactions.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What is the difference between oxidation and reduction in terms of electrons?', 'Which species is the oxidizing agent in a redox reaction?', 'In what order do you add H⁺ and H₂O when balancing redox in acidic solution?']
            ),
            _l('Galvanic Cells',
               [
                   _t('Galvanic Cell Components', 'A galvanic cell converts chemical energy to electrical energy via spontaneous redox; oxidation occurs at the anode (−), reduction at the cathode (+).', 'Students confuse anode/cathode labels with sign: in galvanic cells, anode is negative.', 'Describe galvanic cell components: anode, cathode, salt bridge, and electron flow.'),
                   _t('Standard Cell Potential', 'E°cell = E°cathode − E°anode (using standard reduction potentials); positive E°cell means spontaneous reaction.', 'Standard reduction potentials are intensive properties — do not multiply by stoichiometric coefficients.', 'Calculate E°cell from a table of standard reduction potentials.'),
                   _t('Connecting to ΔG° and K', 'ΔG° = −nFE°cell; ΔG° = −RT ln K; therefore E°cell is directly related to K.', 'Larger positive E°cell corresponds to larger K and more negative ΔG°.', 'Interconvert E°cell, ΔG°, and K using the relevant equations.'),
               ],
               [('galvanic (voltaic) cell', 'Electrochemical cell that converts spontaneous chemical energy to electrical energy.'),
                ('anode', 'Electrode where oxidation occurs; negative in galvanic cells.'),
                ('cathode', 'Electrode where reduction occurs; positive in galvanic cells.'),
                ('standard reduction potential (E°red)', 'Tendency of a half-reaction to gain electrons under standard conditions.'),
                ('salt bridge', 'Allows ion flow between half-cells to maintain charge balance without mixing solutions.')],
               ['Identify anode, cathode, and direction of electron flow in a galvanic cell.', 'Calculate E°cell from standard reduction potentials.', 'Use ΔG° = −nFE°cell to connect electrochemistry and thermodynamics.'],
               ['Drawing and labeling galvanic cells from a given redox reaction.', 'Calculating E°cell and predicting spontaneity.', 'Interconverting E°cell, ΔG°, and K.'],
               ['Khan Academy: Galvanic Cells', 'Bozeman Science: Electrochemistry'],
               [('In a galvanic cell, oxidation occurs at the:', ['Anode', 'Cathode', 'Salt bridge', 'Both electrodes', 'Positive electrode']),
                ('E°cell = E°cathode − E°anode. If E°cathode = +0.80 V and E°anode = −0.44 V, E°cell =', ['+1.24 V', '+0.36 V', '−0.36 V', '−1.24 V', '+0.44 V']),
                ('Standard reduction potentials are NOT multiplied by stoichiometric coefficients because:', ['They are intensive properties (independent of amount)', 'They depend on concentration', 'They change with temperature', 'They are measured in kJ', 'They include entropy terms']),
                ('A positive E°cell means:', ['Spontaneous reaction (ΔG < 0)', 'Nonspontaneous', 'K < 1', 'ΔG > 0', 'Reaction requires energy']),
                ('Electrons in a galvanic cell flow from:', ['Anode to cathode through external circuit', 'Cathode to anode', 'Through the salt bridge', 'From + to − externally', 'From high to low reduction potential']),
               ],
               [('Bozeman Science: Galvanic Cells', 'Explains cell components, E°cell calculation, and thermodynamic connections.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['At which electrode does reduction occur in a galvanic cell?', 'How do you calculate E°cell from standard reduction potentials?', 'What is the relationship between positive E°cell and ΔG°?']
            ),
            _l('Nernst Equation',
               [
                   _t('Nernst Equation', 'E = E° − (RT/nF)ln Q relates cell potential to concentration at non-standard conditions; at 25°C, E = E° − (0.0592/n)log Q.', 'E is zero at equilibrium (Q = K), consistent with ΔG = 0 at equilibrium.', 'Use the Nernst equation to calculate cell potential at non-standard concentrations.'),
                   _t('Concentration Cells', 'A concentration cell has identical electrodes but different ion concentrations; EMF is driven entirely by the concentration difference.', 'The spontaneous direction moves ions from high to low concentration (reduces Q toward K).', 'Calculate E for a concentration cell using the Nernst equation.'),
                   _t('Cell Potential and Equilibrium', 'When E = 0, Q = K; the battery is "dead." Using K = e^(nFE°/RT) to find K from E°cell.', 'The cell potential decreases as it approaches equilibrium and Q → K.', 'Relate equilibrium constant to E°cell and interpret when a cell\'s potential reaches zero.'),
               ],
               [('Nernst equation', 'E = E° − (0.0592/n)log Q at 25°C; adjusts E for non-standard conditions.'),
                ('concentration cell', 'Galvanic cell with identical half-reactions but different ion concentrations.'),
                ('reaction quotient (Q)', 'Used in Nernst equation to account for current concentrations.'),
                ('standard conditions', '1 M concentrations, 1 atm, 25°C; E = E° under these conditions.'),
                ('dead battery', 'Cell at equilibrium (E = 0, Q = K); no more free energy available.')],
               ['Apply the Nernst equation to find E at non-standard concentrations.', 'Explain how concentration cells work.', 'Determine K from E°cell using the Nernst equation at equilibrium.'],
               ['Calculating E for cells with non-standard concentrations.', 'Predicting direction in concentration cells.', 'Finding K from E°cell.'],
               ['Khan Academy: Nernst Equation', 'Bozeman Science: Nernst Equation'],
               [('The Nernst equation at 25°C is: E = E° −', ['(0.0592/n) log Q', '(RT/F) ln Q', 'nF × E°', 'ΔG°/nF', '(0.0592 × n) log Q']),
                ('At equilibrium, cell potential E =', ['0 V', 'E°', 'ΔG°/nF', '0.0592 V', 'Kc × E°']),
                ('A concentration cell with [Zn²⁺] = 1.0 M (anode) and [Zn²⁺] = 0.01 M (cathode):', ['Has a cell potential of zero (both are Zn/Zn²⁺)', 'Actually a small positive potential from lower [cathode]', 'Has E > E°', 'Is not spontaneous', 'Never reaches equilibrium']),
                ('Increasing product concentration in a running cell:', ['Decreases E (Q increases, E decreases)', 'Increases E', 'Has no effect', 'Increases E°', 'Causes E = 0 immediately']),
                ('K for a cell reaction can be found from:', ['K = 10^(nE°/0.0592)', 'K = nFE°/RT', 'K = ΔG°/RT', 'K = E°/n', 'K = e^(ΔH/RT)']),
               ],
               [('Bozeman Science: Nernst Equation', 'Explains E at non-standard conditions and concentration cells.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['What does Q represent in the Nernst equation?', 'Why is E = 0 when Q = K?', 'What drives a concentration cell if E° = 0?']
            ),
            _l('Electrolysis and Faraday\'s Law',
               [
                   _t('Electrolysis', 'Electrolysis uses electrical energy to drive a nonspontaneous reaction; oxidation still at anode, reduction at cathode.', 'In electrolysis, the anode is connected to the positive terminal (opposite of galvanic cell labeling for current source).', 'Identify products of electrolysis of molten salts and aqueous solutions.'),
                   _t('Faraday\'s Law', 'Moles of electrons = (current × time) / F = (I × t) / 96485; links charge passed to moles deposited.', 'Students must include stoichiometry from half-reaction — 1 mol Cu²⁺ requires 2 mol e⁻.', 'Calculate mass deposited or gas produced in electrolysis from current and time.'),
                   _t('Electroplating and Applications', 'Electroplating deposits a thin metal layer on an object used as the cathode; plating metal dissolves from the anode.', 'The electrolyte must contain ions of the metal being plated for effective deposition.', 'Describe the setup for electroplating and explain how metal is transferred.'),
               ],
               [('electrolysis', 'Use of electrical energy to drive a nonspontaneous redox reaction.'),
                ('Faraday\'s constant (F)', '96,485 C/mol electrons; used to convert charge to moles of electrons.'),
                ('coulomb (C)', 'Unit of electrical charge; 1 C = 1 A × 1 s.'),
                ('electroplating', 'Electrolytic process depositing a thin metal coating on a surface.'),
                ('ampere (A)', 'Unit of electrical current; 1 A = 1 C/s.')],
               ['Describe electrolysis and identify products at anode and cathode.', 'Apply Faraday\'s law to calculate mass deposited or moles of gas produced.', 'Explain the electroplating process.'],
               ['Calculating mass deposited using current, time, and Faraday\'s law.', 'Predicting products of electrolysis of water or molten NaCl.', 'Describing setup of an electroplating cell.'],
               ['Khan Academy: Electrolysis', 'Bozeman Science: Electrolysis'],
               [('In electrolysis, reduction occurs at the:', ['Cathode', 'Anode', 'Salt bridge', 'Power source', 'Positive terminal']),
                ('To deposit 1 mol of Al from Al³⁺, how many moles of electrons are required?', ['3 mol e⁻', '1 mol e⁻', '2 mol e⁻', '6 mol e⁻', '1/3 mol e⁻']),
                ('A current of 2.0 A for 965 s passes through a CuSO₄ solution. Moles of e⁻ = (2.0 × 965) / 96485 ≈', ['0.020 mol', '0.200 mol', '0.010 mol', '0.965 mol', '1.93 mol']),
                ('In electroplating silver onto a fork:', ['Fork is the cathode; silver anode dissolves', 'Fork is the anode; silver deposits at cathode', 'Both electrodes are silver', 'No electrolyte is needed', 'Fork is connected to positive terminal']),
                ('Electrolysis of water produces:', ['H₂ at cathode and O₂ at anode', 'O₂ at cathode and H₂ at anode', 'Only H₂', 'Only O₂', 'H₂O at both electrodes']),
               ],
               [('Bozeman Science: Electrolysis', 'Covers electrolytic cells, Faraday\'s law calculations, and electroplating.', 'https://www.youtube.com/watch?v=DsgDoSHmq4c')],
               ['How does electrolysis differ from a galvanic cell?', 'State Faraday\'s law in your own words.', 'What is connected to the cathode in an electroplating setup?']
            ),
        ],
        'unit_qs': [
            ('In Cr₂O₇²⁻, the oxidation number of Cr is:', ['+6', '+3', '+7', '+2', '−2']),
            ('A galvanic cell is spontaneous because:', ['E°cell > 0 and ΔG° < 0', 'E°cell < 0', 'ΔG° > 0', 'K < 1', 'Current flows from cathode to anode']),
            ('E°cell is calculated as:', ['E°cathode − E°anode', 'E°anode − E°cathode', 'E°cathode + E°anode', 'ΔG°/nF', '−RT ln K']),
            ('Which species in the following is the strongest reducing agent? (most negative E°red is strongest reductant)', ['Li (E°red = −3.04 V)', 'Cu (E°red = +0.34 V)', 'Ag (E°red = +0.80 V)', 'Au (E°red = +1.50 V)', 'Fe (E°red = −0.44 V)']),
            ('The Nernst equation shows that cell potential decreases when:', ['Q increases (more products accumulate)', 'Q decreases', 'Temperature decreases', 'n increases', 'E° increases']),
            ('Electrolysis differs from galvanic cells in that:', ['It uses electrical energy to drive a nonspontaneous reaction', 'It produces electrical energy', 'Oxidation occurs at the cathode', 'Reduction occurs at the anode', 'It requires a salt bridge']),
            ('Mass of copper deposited from Cu²⁺ by 9648.5 C of charge is:', ['3.175 g (0.05 mol × 63.55 g/mol)', '6.35 g', '1.59 g', '12.7 g', '0.317 g']),
            ('When E = E°, this means:', ['All concentrations are at standard conditions (Q = 1)', 'Equilibrium has been reached', 'K = 1', 'ΔG = 0', 'No reaction occurs']),
            ('ΔG° = −nFE°cell. For n = 2 and E°cell = +0.46 V, ΔG° =', ['−88.8 kJ', '+88.8 kJ', '−44.4 kJ', '+44.4 kJ', '−177.6 kJ']),
            ('In electrolysis of molten NaCl, sodium metal forms at the:', ['Cathode (reduction of Na⁺)', 'Anode', 'Salt bridge', 'Positive electrode', 'Power source']),
        ],
    },
]
