NAME        = 'College Trigonometry'
ABBREV      = 'collegetrig'
SLUG        = 'college-trigonometry'
COURSE_FILE = 'college-trigonometry.html'
ACCENT_COLOR = '#818cf8'
NON_AP      = True

_Y = 'https://www.youtube.com/results?search_query=College+Trigonometry+'
_K = 'https://www.khanacademy.org/math/trigonometry/'

COURSE_QS = [
    ('An angle of 3π/2 radians is equivalent to',
     '270°, calculated as (3π/2) × (180°/π) = 270°',
     ['90°', '180°', '360°']),
    ('The unit circle is defined as',
     'a circle of radius 1 centered at the origin; coordinates on it are (cos θ, sin θ)',
     ['a circle of radius π centered at the origin', 'a circle centered at (1, 0) with radius 1', 'a semicircle with diameter 1']),
    ('In a right triangle, the sine of an acute angle θ equals',
     'opposite/hypotenuse',
     ['adjacent/hypotenuse', 'opposite/adjacent', 'hypotenuse/opposite']),
    ('The cosine function cos(θ) is an even function because',
     'cos(-θ) = cos(θ) — its graph is symmetric about the y-axis',
     ['it outputs only positive values', 'it has period π', 'cos(θ) = 1/sin(θ)']),
    ('The period of f(x) = sin(2x) is',
     'π — the period is 2π divided by the coefficient of x: 2π/2 = π',
     ['2π', '4π', '2']),
    ('The Pythagorean identity sin^2(θ) + cos^2(θ) equals',
     '1 — this is true for every angle θ and follows directly from the unit circle',
     ['0', 'tan^2(θ)', 'sin(θ)·cos(θ)']),
    ('tan(θ) is undefined when cos(θ) = 0, which happens at',
     'θ = π/2 + nπ (odd multiples of π/2) — because tan = sin/cos, division by zero',
     ['θ = nπ (multiples of π)', 'θ = π/4 + nπ', 'θ = 0']),
    ('The Law of Cosines c^2 = a^2 + b^2 - 2ab cos(C) generalizes',
     'the Pythagorean theorem — when C = 90°, cos(90°) = 0 and it reduces to c^2 = a^2 + b^2',
     ['the Law of Sines for right triangles only', 'the quadratic formula to triangles', 'the formula for the area of a triangle']),
    ('The inverse function arcsin (sin^(-1)) has the restricted domain',
     '[-1, 1] and range [-π/2, π/2] — restricted so the inverse is a function',
     ['[0, π] (that is arccos range)', '[-π, π]', '[0, 2π]']),
    ('The double angle formula for cosine: cos(2θ) equals',
     'cos^2(θ) - sin^2(θ), which can also be written as 2cos^2(θ)-1 or 1-2sin^2(θ)',
     ['2sin(θ)cos(θ) (that is sin(2θ))', 'cos^2(θ) + sin^2(θ) = 1', 'tan^2(θ) - sec^2(θ)']),
    ('A vector in polar form with magnitude r and angle θ has',
     'rectangular components (r cos θ, r sin θ) — convert using the unit circle relationships',
     ['components (r sin θ, r cos θ)', 'components (θ, r)', 'magnitude θ and angle r']),
    ('The polar equation r = 2 describes',
     'a circle of radius 2 centered at the origin — all points at distance 2 from the origin',
     ['a line at angle 2 radians from the origin', 'a parabola', 'an ellipse centered at (2, 0)']),
    ('The sum-to-product identity is useful for',
     'converting sums or differences of trig functions into products — helpful when solving trig equations',
     ['proving the Pythagorean identity', 'finding derivatives in calculus', 'converting polar to rectangular form']),
    ('An angle in standard position with vertex at the origin has its initial side',
     'along the positive x-axis — the terminal side is where measurement ends',
     ['along the positive y-axis', 'along the negative x-axis', 'at any convenient starting position']),
    ('The amplitude of f(x) = -3 sin(x) is',
     '3 — amplitude is |A| where A is the coefficient; the negative flips the graph but does not change amplitude',
     ['-3', '3π', '1']),
    ('Coterminal angles differ by',
     'multiples of 360° (or 2π radians) — they share the same terminal side',
     ['exactly 90°', '180°', 'any integer multiple of 90°']),
    ('The reference angle of 210° is',
     '30° — it is 210° - 180° = 30° from the negative x-axis',
     ['60°', '150°', '45°']),
    ('The product-to-sum formula converts',
     'a product of trig functions (like sin A · cos B) into a sum — useful in integral calculus',
     ['sums of angles into single trig functions', 'polar form to rectangular form', 'degrees into radians']),
    ('To solve sin(x) = 1/2 on [0, 2π), the solutions are',
     'x = π/6 and x = 5π/6 — sine equals 1/2 in quadrants I and II',
     ['x = π/6 only', 'x = π/3 and x = 2π/3', 'x = π/6 and x = 7π/6']),
    ('The area of a triangle using the formula K = (1/2)ab sin(C) requires',
     'two sides and the included angle between them',
     ['two angles and any side', 'all three sides', 'one side and the altitude']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 1,
        'title': 'Angles, Radians, and the Unit Circle',
        'file': 'college-trigonometry-1-unit-1-angles-radians-and-unit-circle.html',
        'desc': 'Angle measurement, radian-degree conversion, the unit circle, and exact trig values.',
        'gateway': [
            'What is a radian and why is it used in higher mathematics?',
            'How does the unit circle encode all trig values?',
            'What are coterminal angles and reference angles?',
            'How do you find exact values of trig functions at special angles?',
        ],
        'lessons': [
            _l('Angle Measurement and the Unit Circle',
               [_t('Degrees, Radians, and Angle Classification',
                    'Angles are measured in degrees (360° = full rotation) or radians (2π rad = full rotation). Conversion: rad = deg × π/180; deg = rad × 180/π. Coterminal angles share the same terminal side, differing by multiples of 2π (or 360°). A reference angle is the acute angle between the terminal side and the x-axis.',
                    'Students think radians are "harder" — they are simply a different unit where the angle equals the arc length on a unit circle; for calculus, radians are required.',
                    'Convert between degrees and radians; find coterminal angles; identify reference angles for angles in all quadrants.'),
                _t('The Unit Circle and Exact Trig Values',
                    'The unit circle (radius 1, centered at origin) defines trig functions: cos θ = x-coordinate; sin θ = y-coordinate; tan θ = y/x. Key exact values: sin(π/6)=1/2, sin(π/4)=√2/2, sin(π/3)=√3/2, sin(π/2)=1. Signs by quadrant: Q1 all positive; Q2 sin+; Q3 tan+; Q4 cos+ (ASTC: "All Students Take Calculus").',
                    'Students memorize values without understanding them — if you know the 30-60-90 and 45-45-90 special triangles, you can derive all unit circle values.',
                    'State exact trig values at special angles; determine signs of trig functions by quadrant; use the ASTC mnemonic.')],
               [('radian', 'The angle subtended at the center of a circle by an arc equal in length to the radius; 2π radians = 360°'),
                ('coterminal angles', 'Angles with the same terminal side; they differ by integer multiples of 2π (360°)'),
                ('reference angle', 'The positive acute angle between the terminal side of an angle and the x-axis; always between 0° and 90°'),
                ('unit circle', 'A circle of radius 1 centered at the origin; used to define trig functions: (cos θ, sin θ)'),
                ('ASTC', 'Mnemonic for signs of trig functions by quadrant: All (Q1), Sine (Q2), Tangent (Q3), Cosine (Q4) are positive')],
               ['Convert between degrees and radians', 'Find coterminal and reference angles', 'State exact values of sin, cos, tan at special angles', 'Determine the sign of any trig function by quadrant'],
               ['Convert 240° to radians and find its reference angle', 'State the exact values: sin(5π/6), cos(7π/4), tan(4π/3)'],
               ['Why must calculus use radians rather than degrees?'],
               [('π radians is equivalent to',
                 '180° — half a full rotation',
                 ['90°', '360°', '270°']),
                ('The reference angle for 300° is',
                 '60° — since 300° = 360° - 60°, it is 60° from the positive x-axis in Q4',
                 ['30°', '300°', '120°']),
                ('On the unit circle, sin(θ) represents',
                 'the y-coordinate of the point where the terminal side of θ intersects the unit circle',
                 ['the x-coordinate', 'the slope of the terminal side', 'the arc length from the positive x-axis']),
                ('In which quadrant does sin(θ) < 0 and cos(θ) > 0?',
                 'Quadrant IV — sine is negative (y<0) and cosine is positive (x>0)',
                 ['Quadrant I', 'Quadrant II', 'Quadrant III']),
                ('The exact value of cos(π/4) is',
                 '√2/2 — from the 45-45-90 triangle with sides 1, 1, √2',
                 ['1/2', '√3/2', '1'])],
               [('College Trigonometry — Professor Leonard', 'Angles, radians, unit circle, and exact trig values at special angles', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Trigonometry', 'Unit circle, angle measurement, and trig function definitions', 'https://www.khanacademy.org/math/trigonometry/unit-circle-trig-func')],
               [('An angle of 5π/3 radians in degrees equals',
                 '300° — (5π/3) × (180°/π) = 300°',
                 ['150°', '240°', '270°']),
                ('Two coterminal angles with 45° are',
                 '405° and -315° — add or subtract 360°',
                 ['135° and -45°', '90° and -90°', '225° and -225°']),
                ('The exact value of sin(π/3) is',
                 '√3/2 — from the 30-60-90 triangle: opposite/hypotenuse = √3/2',
                 ['1/2', '√2/2', '√3/3']),
                ('tan(3π/4) equals',
                 '-1 — in Q2, tan = sin/cos = (√2/2)/(-√2/2) = -1',
                 ['1', '√2/2', '-√3']),
                ('The arc length formula s = rθ requires',
                 'θ to be in radians — the formula breaks down if degrees are used',
                 ['θ to be in degrees', 'r to equal 1', 'θ to be less than π']),
                ('The six trig functions can be defined from sin and cos as',
                 'tan=sin/cos, cot=cos/sin, sec=1/cos, csc=1/sin — all derived from the unit circle definitions',
                 ['sin and cos derived from tan and sec', 'cos = 1/sin and tan = sin/cos', 'they are all independent definitions requiring no relationship']),
                ('cos(π/6) equals',
                 '√3/2 — from the 30-60-90 triangle; cosine of 30° is the longer leg/hypotenuse = √3/2',
                 ['1/2', '√2/2', '1']),
                ('An angle of -π/2 radians has its terminal side pointing',
                 'downward (in the direction of -y), equivalent to 270° or 3π/2',
                 ['upward (positive y-axis)', 'to the right (positive x-axis)', 'to the left (negative x-axis)']),
                ('The area of a sector with radius r and central angle θ (in radians) is',
                 '(1/2)r^2 θ — a fraction of the circle\'s area proportional to θ/(2π)',
                 ['rθ (that is arc length)', 'πr^2 θ', '2rθ']),
                ('Which quadrant has both sin and tan negative?',
                 'Quadrant IV — sin is negative (y<0), cos is positive (x>0), so tan = sin/cos is negative',
                 ['Quadrant I', 'Quadrant II', 'Quadrant III']),
               ]),
        ],
    },

    {
        'num': 2,
        'title': 'Right Triangle Trigonometry and Applications',
        'file': 'college-trigonometry-2-unit-2-right-triangle-trigonometry-and-applications.html',
        'desc': 'SOH-CAH-TOA, solving right triangles, angle of elevation/depression, and the Laws of Sines and Cosines.',
        'gateway': [
            'How do you use trig ratios to find missing sides and angles in right triangles?',
            'What is the difference between the Law of Sines and the Law of Cosines?',
            'When do you use the Law of Sines vs. the Law of Cosines?',
            'What is the ambiguous case (SSA) in triangle solving?',
        ],
        'lessons': [
            _l('Right Triangles, Law of Sines, and Law of Cosines',
               [_t('Right Triangle Trigonometry',
                    'For acute angle θ in a right triangle: sin θ = opp/hyp, cos θ = adj/hyp, tan θ = opp/adj (SOH-CAH-TOA). Inverse trig functions find angles: θ = arctan(opp/adj). Angles of elevation (looking up from horizontal) and depression (looking down from horizontal) use the same trig ratios with a horizontal reference.',
                    'Students confuse "angle of elevation" and "angle of depression" — both are measured from the horizontal, not from the vertical.',
                    'Apply SOH-CAH-TOA to find missing sides and angles; solve right triangle applications including angles of elevation and depression.'),
                _t('Law of Sines and Law of Cosines',
                    'Law of Sines: a/sin A = b/sin B = c/sin C — use when you know AAS, ASA, or SSA. Law of Cosines: c^2 = a^2 + b^2 - 2ab cos C — use when you know SAS or SSS. The ambiguous case (SSA) can produce 0, 1, or 2 triangles depending on whether the given side is long enough to reach the base. Area formula: K = (1/2)ab sin C.',
                    'Students always try to use the Law of Sines for every triangle — use the Law of Cosines when no angle-side pair is given (SSS or SAS).',
                    'Select and apply Law of Sines or Cosines; handle the ambiguous SSA case; calculate triangle area using the sine area formula.')],
               [('SOH-CAH-TOA', 'Mnemonic for right triangle trig ratios: Sin=Opp/Hyp, Cos=Adj/Hyp, Tan=Opp/Adj'),
                ('angle of elevation', 'The angle measured upward from the horizontal to the line of sight'),
                ('angle of depression', 'The angle measured downward from the horizontal to the line of sight'),
                ('Law of Sines', 'a/sin A = b/sin B = c/sin C; used for AAS, ASA, or SSA triangle cases'),
                ('Law of Cosines', 'c^2 = a^2 + b^2 - 2ab cos C; used for SAS or SSS triangle cases'),
                ('ambiguous case', 'The SSA situation where two triangles, one triangle, or no triangle may satisfy the given conditions')],
               ['Apply SOH-CAH-TOA to solve right triangles', 'Select the appropriate law (Sines or Cosines) for a given triangle', 'Solve the ambiguous SSA case'],
               ['A ladder 10 ft long leans against a wall, making a 65° angle with the ground. Find the height it reaches.', 'In triangle ABC, a=8, b=5, C=60°. Find side c using the Law of Cosines.'],
               ['How do you know whether SSA gives 0, 1, or 2 triangles?'],
               [('In a right triangle, if the opposite side = 5 and hypotenuse = 13, then sin θ equals',
                 '5/13 — sin = opposite/hypotenuse',
                 ['13/5', '5/12', '12/13']),
                ('The Law of Cosines is used when you know',
                 'SAS (two sides and the included angle) or SSS (all three sides)',
                 ['AAS or ASA (two angles and a side)', 'SSA only (ambiguous case)', 'only right triangles']),
                ('An angle of depression from a cliff to a boat is 25°. This angle is measured',
                 'downward from the horizontal at the observer\'s eye level',
                 ['downward from the vertical (straight down)', 'upward from the horizon at the boat', 'from the base of the cliff to the boat']),
                ('The Law of Sines fails to uniquely determine a triangle in the',
                 'SSA (side-side-angle) case — this is the ambiguous case where 0, 1, or 2 triangles may exist',
                 ['ASA case', 'SAS case', 'AAS case']),
                ('The area of triangle with sides a=6, b=8, and included angle C=30° is',
                 '12 — K = (1/2)(6)(8)sin(30°) = 24 × (1/2) = 12',
                 ['48', '24', '6√3'])],
               [('College Trigonometry — Professor Leonard', 'Right triangle trig, Law of Sines, Law of Cosines, and triangle applications', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Right Triangles & Trigonometry', 'SOH-CAH-TOA, Law of Sines, and Law of Cosines', 'https://www.khanacademy.org/math/trigonometry/trigonometry-right-triangles')],
               [('If sin θ = 0.6 in a right triangle, then cos θ equals',
                 '0.8 — use sin^2 θ + cos^2 θ = 1: cos θ = √(1 - 0.36) = √0.64 = 0.8',
                 ['0.4', '0.75', '1.6']),
                ('To find an angle from a known trig ratio, you use',
                 'an inverse trig function: θ = arcsin(value), arccos(value), or arctan(value)',
                 ['the reciprocal of the trig ratio', 'the Pythagorean theorem', 'the Law of Cosines with the known ratio']),
                ('In a 30-60-90 triangle with hypotenuse 10, the side opposite 30° has length',
                 '5 — the side opposite 30° is always half the hypotenuse',
                 ['5√3', '10√3', '10']),
                ('The Heron\'s formula computes the area of a triangle using',
                 'all three sides and the semi-perimeter s = (a+b+c)/2: Area = √[s(s-a)(s-b)(s-c)]',
                 ['one side and the altitude', 'two sides and the included angle', 'two angles and one side']),
                ('Two surveyors at each end of a 500-ft baseline sight a tree. If the angles from the baseline are 62° and 54°, the Law of Sines can find',
                 'the distance from each surveyor to the tree — AAS triangulation uses the Law of Sines',
                 ['only the height of the tree', 'nothing — SSA case is ambiguous here', 'the bearing to the tree but not the distance']),
                ('The Law of Cosines reduces to the Pythagorean theorem when',
                 'angle C = 90° — cos(90°) = 0, so the -2ab cos C term vanishes',
                 ['a = b (isosceles triangle)', 'all angles are equal (equilateral)', 'any angle is less than 90°']),
                ('In the ambiguous SSA case, no triangle exists when',
                 'the given side a < h (the altitude) — the side is too short to reach the base',
                 ['the angle is exactly 90°', 'the two known sides are equal', 'the given angle is obtuse and the side opposite it is longer than the other given side']),
                ('tan(45°) equals',
                 '1 — in a 45-45-90 triangle, opposite = adjacent, so tan = 1',
                 ['√2/2', '√3', '√2']),
                ('The Law of Sines formula a/sin A = b/sin B = c/sin C pairs each side with',
                 'the sine of the angle directly opposite that side',
                 ['the sine of the angle adjacent to that side', 'the cosine of the opposite angle', 'the tangent of the angle at the vertex']),
                ('Solving the equation cos θ = -0.5 for θ in [0°, 360°) gives',
                 '120° and 240° — cosine is -0.5 in Q2 and Q3 (reference angle = 60°)',
                 ['60° and 300°', '120° only', '150° and 210°']),
               ]),
        ],
    },

    {
        'num': 3,
        'title': 'Graphs of Trigonometric Functions',
        'file': 'college-trigonometry-3-unit-3-graphs-of-trigonometric-functions.html',
        'desc': 'Graphing sine, cosine, tangent, and their transformations including amplitude, period, phase shift, and vertical shift.',
        'gateway': [
            'What is the period of a trig function and how does it change?',
            'What is amplitude and what function families have it?',
            'How do horizontal shifts (phase shifts) work for trig functions?',
            'How do you match a trig equation to its graph?',
        ],
        'lessons': [
            _l('Graphing and Transforming Trig Functions',
               [_t('Graphs of Sine and Cosine',
                    'f(x) = A sin(Bx - C) + D has amplitude |A|, period 2π/|B|, phase shift C/B (right if positive), and vertical shift D. The sine graph starts at (0,0) going up; cosine starts at maximum (0,1). Key features: 5 special points per period (start, 1/4, 1/2, 3/4, full cycle). Negative A flips the graph over the midline.',
                    'Students think the phase shift is -C when it is actually C/B — you must factor B out of the argument first: A sin(B(x - C/B)) + D.',
                    'Identify A, B, C, D in a trig equation; calculate amplitude, period, phase shift, and vertical shift; sketch one complete cycle.'),
                _t('Graphs of Tangent, Cotangent, Secant, and Cosecant',
                    'The tangent function y = tan x has period π (not 2π), no amplitude, and vertical asymptotes where cos x = 0 (at x = π/2 + nπ). The cotangent has asymptotes where sin x = 0. Secant y = sec x = 1/cos x has the same asymptotes as tangent and is the reciprocal of cosine. Cosecant y = csc x = 1/sin x mirrors its relationship with sine.',
                    'Students apply the amplitude formula to tan, cot, sec, csc — these functions have no finite amplitude (they extend to ±∞).',
                    'Graph tangent and cotangent using asymptotes; graph secant and cosecant as reciprocals of cosine and sine; identify periods and asymptote positions.')],
               [('amplitude', 'Half the vertical distance between maximum and minimum values; equals |A| in y = A sin(Bx); undefined for tan, cot, sec, csc'),
                ('period', 'The horizontal length of one complete cycle; for sin/cos: 2π/|B|; for tan/cot: π/|B|'),
                ('phase shift', 'Horizontal shift of a trig graph; for y = A sin(Bx - C), the phase shift is C/B to the right'),
                ('vertical shift', 'The value D in y = A sin(Bx) + D; shifts the midline from y=0 to y=D'),
                ('midline', 'The horizontal line y = D around which the sine or cosine wave oscillates'),
                ('asymptote', 'For tangent and secant: vertical lines where the function is undefined, at x = π/2 + nπ')],
               ['Calculate amplitude, period, phase shift, and vertical shift from an equation', 'Sketch one complete cycle of a transformed trig function', 'Identify asymptotes for tangent and secant functions'],
               ['Write the equation of a sine function with amplitude 3, period π, phase shift π/4 right, and midline y=2', 'Sketch y = 2cos(3x - π/2) over one complete cycle'],
               ['How does the graph of y = sec x relate to the graph of y = cos x?'],
               [('The amplitude of f(x) = -4 sin(x) is',
                 '4 — amplitude is |A| = |-4| = 4; the negative reflects the graph but does not change amplitude',
                 ['-4', '4π', '1']),
                ('The period of f(x) = cos(3x) is',
                 '2π/3 — the period is 2π divided by the coefficient of x',
                 ['3π', '6π', '2π']),
                ('The phase shift of f(x) = sin(2x - π/2) is',
                 'π/4 to the right — phase shift = C/B = (π/2)/2 = π/4',
                 ['π/2 to the right', 'π/2 to the left', 'π/4 to the left']),
                ('The tangent function has period',
                 'π — it completes one full pattern every π units, not every 2π units',
                 ['2π', 'π/2', '4π']),
                ('The vertical asymptotes of y = tan(x) occur at',
                 'x = π/2 + nπ for integer n — where cosine (the denominator) equals zero',
                 ['x = nπ (multiples of π)', 'x = π/4 + nπ/2', 'x = 0'])],
               [('College Trigonometry — Professor Leonard', 'Graphing trig functions: amplitude, period, phase shift, and transformations', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Graphs of Trig Functions', 'Graphing and transforming sine, cosine, tangent, and reciprocal functions', 'https://www.khanacademy.org/math/trigonometry/trig-function-graphs')],
               [('A function with amplitude 2, period 4π, and midline y=-1 could be written as',
                 'y = 2 sin(x/2) - 1 — amplitude 2 means |A|=2; period 4π means B=2π/4π=1/2',
                 ['y = 2 sin(4πx) - 1', 'y = 4 sin(x) - 2', 'y = 2 cos(2x) - 1']),
                ('The cosecant function y = csc(x) has vertical asymptotes where',
                 'sin(x) = 0, at x = nπ — because csc = 1/sin, undefined when sin = 0',
                 ['cos(x) = 0', 'x = π/2 + nπ', 'x = 0 only']),
                ('Which of the following correctly describes a phase shift LEFT by π/3?',
                 'f(x) = sin(x + π/3) — adding to x shifts left',
                 ['f(x) = sin(x - π/3)', 'f(x) = sin(x) + π/3', 'f(x) = sin(x) - π/3']),
                ('The maximum value of y = 3 sin(x) + 1 is',
                 '4 — maximum of sin is 1; 3(1) + 1 = 4',
                 ['3', '1', '3π + 1']),
                ('The graph of y = cos x is the same as y = sin x shifted',
                 'π/2 units to the left — cos(x) = sin(x + π/2)',
                 ['π/2 units to the right', 'π units to the left', 'π/4 units to the left']),
                ('The function y = 2 tan(x/2) has period',
                 '2π — for tangent, period = π/B = π/(1/2) = 2π',
                 ['π', 'π/2', '4π']),
                ('Increasing the period of a sine wave means the wave',
                 'is stretched horizontally — it takes longer to complete one cycle (lower frequency)',
                 ['oscillates more quickly', 'has smaller amplitude', 'shifts to the right']),
                ('The range of y = 5 cos(x) - 2 is',
                 '[-7, 3] — cosine outputs [-1, 1]; multiply by 5 to get [-5, 5]; subtract 2 to get [-7, 3]',
                 ['[-5, 5]', '[-2, 2]', '[−7, 7]']),
                ('The y-intercept of f(x) = 3 sin(2x - π/2) + 1 is',
                 '-2 — evaluate at x=0: 3 sin(-π/2) + 1 = 3(-1) + 1 = -2',
                 ['1', '0', '-π/2 + 1']),
                ('The secant function y = sec x is the reciprocal of cosine, so where cosine has a maximum of 1,',
                 'secant also has a value of 1 — it touches (not crosses) the cosine curve at its maxima and minima',
                 ['secant has a minimum of -1', 'secant has a vertical asymptote', 'secant has a value of 0']),
               ]),
        ],
    },
]
