NAME        = 'College Algebra'
ABBREV      = 'collegealg'
SLUG        = 'college-algebra'
COURSE_FILE = 'college-algebra.html'
ACCENT_COLOR = '#38bdf8'
NON_AP      = True

_Y = 'https://www.youtube.com/results?search_query=College+Algebra+'
_K = 'https://www.khanacademy.org/math/algebra/'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 4,
        'title': 'Polynomial and Rational Functions',
        'file': 'college-algebra-4-unit-4-polynomial-and-rational-functions.html',
        'desc': 'Polynomial behavior, zeros, division, rational functions, and asymptotes.',
        'gateway': [
            'How do you find the zeros of a polynomial function?',
            'What do vertical, horizontal, and oblique asymptotes represent?',
            'How does the Rational Root Theorem narrow down possible zeros?',
            'What is the end behavior of a polynomial function?',
        ],
        'lessons': [
            _l('Polynomials, Division, and Rational Functions',
               [_t('Polynomial Functions and Their Zeros',
                    'A polynomial of degree n has at most n real zeros and at most n-1 turning points. The Fundamental Theorem of Algebra: every degree-n polynomial has exactly n zeros (counting multiplicity, in the complex numbers). The Rational Root Theorem: for integer-coefficient polynomials, any rational zero p/q has p dividing the constant term and q dividing the leading coefficient.',
                    'Students assume every polynomial of degree n has exactly n real zeros — they can have complex (non-real) zeros that come in conjugate pairs.',
                    'Find zeros by factoring or the Rational Root Theorem; apply synthetic division; sketch polynomials using end behavior and zeros.'),
                _t('Rational Functions and Asymptotes',
                    'A rational function is a ratio of polynomials p(x)/q(x). Vertical asymptotes occur where q(x)=0 (and p(x)≠0). Horizontal asymptotes depend on degrees: if deg(p)<deg(q), y=0; if deg(p)=deg(q), y=leading coefficients ratio; if deg(p)>deg(q), no horizontal asymptote (oblique or polynomial behavior). A hole (removable discontinuity) occurs where a factor cancels between numerator and denominator.',
                    'Students place vertical asymptotes wherever the denominator is zero even if the factor cancels — canceling factors create holes, not asymptotes.',
                    'Find vertical and horizontal asymptotes; identify holes; sketch the graph of a rational function.')],
               [('zeros (roots)', 'The x-values where a function equals zero; also called x-intercepts when real'),
                ('multiplicity', 'How many times a factor (x-r) appears; even multiplicity: graph touches x-axis; odd: crosses'),
                ('synthetic division', 'A shorthand method for dividing a polynomial by (x - c)'),
                ('vertical asymptote', 'A vertical line x = a where the rational function grows without bound'),
                ('horizontal asymptote', 'A horizontal line y = k that the function approaches as x → ±∞'),
                ('hole', 'A removable discontinuity in a rational function where a common factor cancels')],
               ['Find the zeros of a polynomial using factoring and the Rational Root Theorem', 'Apply synthetic division to divide polynomials', 'Identify asymptotes and holes in rational functions'],
               ['Find all zeros of f(x) = x^3 - 6x^2 + 11x - 6', 'Determine vertical and horizontal asymptotes of f(x) = (x^2-1)/(x^2-4)'],
               ['What does a zero with even multiplicity look like on a graph compared to odd multiplicity?'],
               [('The degree of the polynomial 4x^5 - 3x^2 + 7 is',
                 '5 — the degree is the highest power of the variable',
                 ['2', '7', '4']),
                ('The end behavior of f(x) = -2x^3 + 5x is',
                 'as x→+∞, f→-∞; as x→-∞, f→+∞ — odd degree, negative leading coefficient',
                 ['as x→+∞, f→+∞; as x→-∞, f→-∞', 'both ends go to +∞', 'both ends go to -∞']),
                ('For f(x) = (x+1)^2(x-3), the zero x=-1 has multiplicity 2, which means',
                 'the graph touches but does not cross the x-axis at x=-1',
                 ['the graph crosses the x-axis at x=-1', 'x=-1 is not actually a zero', 'the function has two values at x=-1']),
                ('The horizontal asymptote of f(x) = 3x^2/(x^2-1) is',
                 'y = 3 — equal degrees, so divide leading coefficients: 3/1 = 3',
                 ['y = 0', 'y = 1', 'there is no horizontal asymptote']),
                ('The Rational Root Theorem says that possible rational zeros of 2x^3 - x + 6 are',
                 'of the form ±p/q where p divides 6 (constant) and q divides 2 (leading coefficient)',
                 ['any rational number', 'only integers that divide 6', 'only ±1 and ±2'])],
               [('College Algebra — Professor Leonard', 'Polynomial zeros, synthetic division, rational functions, and asymptotes', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Polynomials', 'Graphing, factoring, and rational functions', 'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:poly-graphs')],
               [('A polynomial of degree 4 with real coefficients can have at most',
                 '4 real zeros and at least 0 real zeros — complex zeros come in conjugate pairs',
                 ['exactly 4 real zeros always', '2 real zeros always', '4 positive real zeros only']),
                ('Synthetic division divides a polynomial by',
                 'a linear factor of the form (x - c) only',
                 ['any polynomial', 'quadratic factors only', 'the leading coefficient of the polynomial']),
                ('f(x) = (x-2)(x+1)/(x-2)(x-3) has a hole at',
                 'x = 2 because the (x-2) factor cancels — creating a removable discontinuity',
                 ['x = 3 (vertical asymptote)', 'x = -1 (zero)', 'x = 0 (y-intercept)']),
                ('The graph of a polynomial with negative leading coefficient and odd degree',
                 'rises to the left and falls to the right',
                 ['falls to the left and rises to the right', 'rises on both ends', 'falls on both ends']),
                ('The Fundamental Theorem of Algebra guarantees that a degree-3 polynomial has',
                 'exactly 3 zeros counting multiplicity (in the complex numbers)',
                 ['exactly 3 real zeros', 'at most 3 zeros of any type', 'at least 1 real zero and exactly 3 complex zeros']),
                ('The vertical asymptotes of f(x) = 1/(x^2-9) are',
                 'x = 3 and x = -3 — the denominator factors as (x-3)(x+3)',
                 ['y = 3 and y = -3', 'x = 9', 'x = 0 only']),
                ('When the degree of the numerator exceeds the degree of the denominator by 1, a rational function has',
                 'an oblique (slant) asymptote — found by polynomial long division',
                 ['a horizontal asymptote', 'no asymptotes', 'two vertical asymptotes']),
                ('The Factor Theorem states that (x - r) is a factor of polynomial f(x) if and only if',
                 'f(r) = 0 — r is a zero of the polynomial',
                 ['f(r) = r', 'f(0) = r', 'r is a positive integer']),
                ('A rational function with more zeros than poles (vertical asymptotes)',
                 'has more x-intercepts than vertical asymptotes — this does not violate any rule',
                 ['is not a valid rational function', 'must have a horizontal asymptote at y=0', 'must have an equal number of each']),
                ('The remainder when dividing f(x) by (x - 3) equals',
                 'f(3) — by the Remainder Theorem, the remainder equals the polynomial evaluated at the divisor\'s zero',
                 ['f(0)', '3', 'the leading coefficient of f']),
               ]),
        ],
    },

    {
        'num': 5,
        'title': 'Exponential and Logarithmic Functions',
        'file': 'college-algebra-5-unit-5-exponential-and-logarithmic-functions.html',
        'desc': 'Exponential growth and decay, properties of logarithms, and solving exponential and logarithmic equations.',
        'gateway': [
            'What makes a function exponential vs. polynomial?',
            'What is a logarithm and how does it relate to an exponent?',
            'How do you use properties of logarithms to simplify expressions?',
            'How do you model real-world problems with exponential functions?',
        ],
        'lessons': [
            _l('Exponential and Logarithmic Functions',
               [_t('Exponential Functions',
                    'An exponential function has the form f(x) = ab^x where b>0, b≠1, a≠0. If b>1, the function grows exponentially; if 0<b<1, it decays. The natural exponential function f(x) = e^x (e ≈ 2.718) is especially important in continuous growth models. Compound interest: A = P(1+r/n)^(nt); continuous compounding: A = Pe^(rt).',
                    'Students confuse x^2 (polynomial, grows slower eventually) with 2^x (exponential, always eventually faster); exponential functions dominate polynomial functions for large x.',
                    'Identify exponential growth vs. decay; apply compound interest formulas; graph exponential functions and describe transformations.'),
                _t('Logarithms and Their Properties',
                    'The logarithm log_b(x) = y means b^y = x. Properties: log_b(MN) = log_b(M)+log_b(N); log_b(M/N) = log_b(M)-log_b(N); log_b(M^p) = p·log_b(M). Change of base: log_b(x) = ln(x)/ln(b). To solve exponential equations, take the logarithm of both sides; to solve logarithmic equations, exponentiate both sides (and check for domain restrictions).',
                    'Students think log(a+b) = log(a) + log(b) — there is no such property. Only products and quotients, not sums, split under logarithms.',
                    'Apply logarithm properties to expand/condense; solve exponential and logarithmic equations; apply to real-world growth and decay problems.')],
               [('exponential function', 'A function of the form f(x) = ab^x where the variable is in the exponent'),
                ('logarithm', 'The inverse of the exponential: log_b(x) = y means b^y = x'),
                ('natural logarithm', 'ln(x) = log_e(x); the inverse of e^x'),
                ('change of base formula', 'log_b(x) = log(x)/log(b) = ln(x)/ln(b) — converts any log to base 10 or base e'),
                ('half-life', 'The time for an exponentially decaying quantity to reduce to half its initial value'),
                ('asymptote', 'For exponential functions f(x) = ab^x, the x-axis (y=0) is a horizontal asymptote')],
               ['Identify exponential growth and decay from the base b', 'Apply logarithm properties to simplify and solve', 'Solve exponential and logarithmic equations'],
               ['Solve 3^(2x) = 81 and verify your answer', 'Condense ln(3) + 2ln(x) - ln(y) into a single logarithm'],
               ['What restrictions must x satisfy for log_b(x) to be defined?'],
               [('The function f(x) = (1/3)^x represents',
                 'exponential decay because the base 1/3 satisfies 0 < b < 1',
                 ['exponential growth', 'a polynomial function', 'a linear function']),
                ('log_2(32) equals',
                 '5, because 2^5 = 32',
                 ['4', '16', '6']),
                ('The property log(MN) = log(M) + log(N) comes from',
                 'the exponent rule b^m · b^n = b^(m+n) — multiplication becomes addition in log form',
                 ['the commutative property of addition', 'the chain rule of calculus', 'the distributive property']),
                ('To solve 5^x = 200, you should',
                 'take ln (or log) of both sides: x = ln(200)/ln(5)',
                 ['divide both sides by 5', 'take the square root of both sides', 'convert 200 to a power of 5']),
                ('The domain of f(x) = log(x - 3) is',
                 'x > 3 — the argument of a logarithm must be strictly positive',
                 ['x > 0', 'x ≥ 3', 'all real numbers'])],
               [('College Algebra — Professor Leonard', 'Exponential and logarithmic functions, properties, and equations', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Exponential & Logarithmic Functions', 'Exponential growth, logarithm properties, and solving log equations', 'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:logs')],
               [('The natural base e is approximately',
                 '2.718 — it arises naturally in continuous growth/decay models',
                 ['3.14 (that is π)', '2.0', '1.618 (that is the golden ratio)']),
                ('Continuous compound interest is calculated with',
                 'A = Pe^(rt) where P is principal, r is rate, t is time',
                 ['A = P(1 + r)^t (annual compounding)', 'A = Prt (simple interest)', 'A = P + e^(rt)']),
                ('ln(e^5) simplifies to',
                 '5 — ln and e^x are inverse functions, so they cancel',
                 ['e^5', '5e', '1/5']),
                ('Condensing log(4) + log(x^2) - log(y) gives',
                 'log(4x^2/y) — sum becomes product in argument; difference becomes quotient',
                 ['log(4 + x^2 - y)', 'log(4x^2) - log(y)', 'log(4) · log(x^2/y)']),
                ('The half-life formula Q(t) = Q_0 · (1/2)^(t/h) means',
                 'the initial quantity Q_0 is halved every h units of time',
                 ['the quantity is halved once and then stays constant', 'h is the total time until the quantity reaches zero', 'the base must be 2, not 1/2']),
                ('To solve log_3(x + 2) = 4, you',
                 'exponentiate both sides with base 3: x + 2 = 3^4 = 81, so x = 79',
                 ['multiply both sides by 3', 'subtract 4 from both sides', 'square both sides']),
                ('The change of base formula converts log_5(17) to',
                 'ln(17)/ln(5) (or log(17)/log(5)) — useful for calculator evaluation',
                 ['log(17-5)', '5·log(17)', 'log(17)/5']),
                ('An exponential function f(x) = 2^x has the y-intercept',
                 '(0, 1) because 2^0 = 1',
                 ['(0, 2)', '(1, 0)', '(0, 0)']),
                ('Solving ln(x) = -2 gives',
                 'x = e^(-2) ≈ 0.135 — exponentiate both sides: x = e^(-2)',
                 ['x = -2e', 'x = -e^2', 'x = 1/2']),
                ('Exponential functions eventually dominate polynomials because',
                 'exponential growth multiplies by a constant factor every unit, while polynomial growth adds — the multiplicative rate always outpaces additive growth',
                 ['polynomials have higher degree so they grow faster', 'exponential functions have smaller derivatives than polynomials', 'only exponential functions are continuous']),
               ]),
        ],
    },

    {
        'num': 6,
        'title': 'Systems, Matrices, and Modeling',
        'file': 'college-algebra-6-unit-6-systems-matrices-and-modeling.html',
        'desc': 'Solving systems of equations, matrix operations, and mathematical modeling with functions.',
        'gateway': [
            'What does the solution to a system of equations represent graphically?',
            'How do you use matrices to solve systems of equations?',
            'What is the difference between consistent, inconsistent, and dependent systems?',
            'How do you choose the right function model for real-world data?',
        ],
        'lessons': [
            _l('Systems of Equations, Matrices, and Modeling',
               [_t('Systems of Equations',
                    'A system of linear equations can be solved by substitution, elimination, or matrices. Graphically: the solution is the intersection point(s). A system is consistent (at least one solution) or inconsistent (no solution — parallel lines). A consistent system is independent (one solution) or dependent (infinitely many solutions — same line). For 3×3 systems, use Gaussian elimination (row reduction).',
                    'Students assume every system of two equations has exactly one solution; parallel lines give no solution, and identical lines give infinitely many.',
                    'Solve 2×2 systems by substitution and elimination; classify systems as consistent/inconsistent, independent/dependent.'),
                _t('Matrices and Mathematical Modeling',
                    'A matrix is a rectangular array of numbers. Matrix addition/subtraction requires same dimensions. Matrix multiplication (not commutative): rows of first × columns of second. The identity matrix I satisfies AI=IA=A. The inverse matrix A^(-1) satisfies AA^(-1)=I; systems Ax=b are solved as x=A^(-1)b. Modeling: choose linear for constant rate of change, quadratic for parabolic data, exponential for constant percent growth.',
                    'Students think matrix multiplication is commutative (AB=BA) — it is not; order matters in matrix multiplication.',
                    'Perform matrix operations; solve systems using inverse matrices; select appropriate function types to model real-world scenarios.')],
               [('system of equations', 'Two or more equations with the same variables; the solution satisfies all equations simultaneously'),
                ('matrix', 'A rectangular array of numbers; used to represent and solve systems of equations'),
                ('row reduction (Gaussian elimination)', 'A systematic method for solving systems using row operations on the augmented matrix'),
                ('identity matrix', 'A square matrix with 1s on the main diagonal and 0s elsewhere; satisfies AI = IA = A'),
                ('inverse matrix', 'For square matrix A, A^(-1) satisfies AA^(-1) = I; used to solve matrix equations'),
                ('mathematical modeling', 'Using mathematical functions to represent and predict real-world quantities')],
               ['Solve 2×2 systems by substitution and elimination', 'Classify a system as consistent/inconsistent and independent/dependent', 'Perform basic matrix operations and solve systems using matrices'],
               ['Solve the system: 2x + y = 7 and x - 3y = -1', 'A population grows by 5% per year. Write an exponential model and predict the population after 10 years.'],
               ['What real-world scenarios are best modeled by linear vs. quadratic vs. exponential functions?'],
               [('A system of two linear equations with no solution occurs when the lines are',
                 'parallel — same slope, different y-intercepts, so they never intersect',
                 ['perpendicular', 'identical', 'intersecting at a single point']),
                ('Matrix multiplication AB requires that the number of columns in A',
                 'equals the number of rows in B — the "inner" dimensions must match',
                 ['equals the number of columns in B', 'is greater than the rows in B', 'equals the rows in A']),
                ('The augmented matrix [2 1 | 7; 1 -3 | -1] represents',
                 'the system: 2x + y = 7 and x - 3y = -1 with coefficients and constants',
                 ['a matrix multiplication', 'a 2×2 determinant', 'the inverse of a 2×2 matrix']),
                ('If a 2×2 system has infinitely many solutions, the equations describe',
                 'the same line (dependent system) — one equation is a multiple of the other',
                 ['parallel lines', 'perpendicular lines', 'two unrelated lines']),
                ('To model a quantity that increases by 8% per year, you would use',
                 'an exponential function f(t) = P(1.08)^t',
                 ['a linear function f(t) = P + 0.08t', 'a quadratic function f(t) = 0.08t^2 + P', 'a logarithmic function f(t) = P·ln(0.08t)'])],
               [('College Algebra - Professor Leonard', 'Systems of equations, matrices, and real-world modeling', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Systems of Equations & Matrices', 'Solving systems by substitution, elimination, and matrix methods', 'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:systems')],
               [('Gaussian elimination uses "row operations" which include',
                 'swapping rows, multiplying a row by a non-zero constant, and adding a multiple of one row to another',
                 ['only swapping rows', 'dividing entire matrices by scalars', 'replacing rows with their sums only']),
                ('For matrix equation Ax = b, the solution is',
                 'x = A^(-1)b — multiply both sides on the left by A^(-1) (if it exists)',
                 ['x = b/A (divide by matrix)', 'x = A·b', 'x = bA^(-1)']),
                ('A 2×3 matrix has',
                 '2 rows and 3 columns — the first number always denotes rows',
                 ['2 columns and 3 rows', '2 diagonals and 3 off-diagonals', '6 diagonal entries']),
                ('The identity matrix I_2 is',
                 '[[1,0],[0,1]] — the 2×2 matrix with ones on the diagonal',
                 ['[[0,0],[0,0]]', '[[1,1],[1,1]]', '[[2,0],[0,2]]']),
                ('Linear regression is most appropriate when the scatterplot of data shows',
                 'a roughly constant rate of change — the points cluster around a straight line',
                 ['a J-shaped curve suggesting exponential growth', 'a U-shaped curve suggesting a parabola', 'an S-shaped curve suggesting logistic growth']),
                ('A negative determinant of a 2×2 matrix means',
                 'the matrix is invertible — a non-zero determinant (positive or negative) ensures an inverse exists',
                 ['the matrix has no inverse', 'the system it represents has no solution', 'all entries must be negative']),
                ('The solution to a system of two equations in two variables can be interpreted as',
                 'the coordinates of the intersection point of the two lines on a graph',
                 ['the sum of the two equations', 'the y-intercepts of each line', 'the product of the two equations']),
                ('Modeling with a quadratic function is appropriate when',
                 'data has a single maximum or minimum — the rate of change itself is changing at a constant rate',
                 ['data grows at a constant rate (that is linear)', 'data doubles at regular intervals (that is exponential)', 'data oscillates in a repeating pattern (that is sinusoidal)']),
                ('The system x + y = 5 and 2x + 2y = 10 is',
                 'dependent (consistent) — the second equation is exactly twice the first, giving infinitely many solutions',
                 ['inconsistent — the lines are parallel', 'independent — there is exactly one solution', 'unsolvable — no real values satisfy both']),
                ('The matrix product AB is generally NOT equal to BA because',
                 'matrix multiplication is not commutative — different row/column pairings produce different results',
                 ['AB is always larger than BA', 'only square matrices can be multiplied', 'the determinant changes sign when you swap order']),
               ]),
        ],
    },
]
