NAME        = 'College Trigonometry'
ABBREV      = 'collegetrig'
SLUG        = 'college-trigonometry'
COURSE_FILE = 'college-trigonometry.html'
ACCENT_COLOR = '#818cf8'
NON_AP      = True

_Y = 'https://www.youtube.com/results?search_query=College+Trigonometry+'
_K = 'https://www.khanacademy.org/math/trigonometry/'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 4,
        'title': 'Trigonometric Identities',
        'file': 'college-trigonometry-4-unit-4-trigonometric-identities.html',
        'desc': 'Fundamental identities, Pythagorean, reciprocal, quotient, co-function, even/odd, sum/difference, double-angle, and half-angle formulas.',
        'gateway': [
            'What is the Pythagorean identity and how is it derived?',
            'How do you prove a trig identity?',
            'What are the sum and difference formulas and when do you need them?',
            'How do the double-angle formulas relate to the sum formulas?',
        ],
        'lessons': [
            _l('Fundamental and Advanced Trig Identities',
               [_t('Fundamental Identities',
                    'The fundamental identities: Pythagorean (sin^2θ+cos^2θ=1, derived forms: tan^2θ+1=sec^2θ, 1+cot^2θ=csc^2θ), reciprocal (cscθ=1/sinθ, secθ=1/cosθ, cotθ=1/tanθ), quotient (tanθ=sinθ/cosθ, cotθ=cosθ/sinθ), and even/odd (cos(-θ)=cosθ even; sin(-θ)=-sinθ odd). To prove an identity: work on one side only, transforming it algebraically until it matches the other.',
                    'Students try to "cross multiply" or move terms across the equals sign when proving identities — you must work one side only.',
                    'Simplify trig expressions using fundamental identities; prove trig identities by transforming one side; apply Pythagorean identities.'),
                _t('Sum, Difference, Double-Angle, and Half-Angle Formulas',
                    'Sum/difference: sin(A±B) = sinAcosB ± cosAsinB; cos(A±B) = cosAcosB ∓ sinAsinB. Double-angle: sin(2θ) = 2sinθcosθ; cos(2θ) = cos^2θ-sin^2θ = 2cos^2θ-1 = 1-2sin^2θ. Half-angle: sin(θ/2) = ±√[(1-cosθ)/2]; cos(θ/2) = ±√[(1+cosθ)/2]. These formulas allow computation of exact values beyond the standard special angles.',
                    'Students think cos(A+B) = cosA+cosB — the sum formula is NOT additive; you must use the full formula with the cross terms.',
                    'Apply sum/difference formulas to find exact values; use double-angle formulas to simplify; solve equations using half-angle substitutions.')],
               [('Pythagorean identity', 'sin^2θ + cos^2θ = 1; derived from the unit circle equation x^2+y^2=1'),
                ('double-angle formula', 'Formulas for sin(2θ) and cos(2θ) in terms of sinθ and cosθ; derived from sum formulas with A=B=θ'),
                ('half-angle formula', 'sin(θ/2) = ±√[(1-cosθ)/2]; cos(θ/2) = ±√[(1+cosθ)/2]; the sign depends on the quadrant of θ/2'),
                ('co-function identity', 'sin(π/2-θ) = cosθ; cos(π/2-θ) = sinθ — complementary angles have swapped sin and cos'),
                ('even function', 'f(-x) = f(x); cosine is even: cos(-θ) = cosθ'),
                ('odd function', 'f(-x) = -f(x); sine is odd: sin(-θ) = -sinθ')],
               ['Simplify trig expressions using fundamental identities', 'Prove trig identities working one side only', 'Apply sum/difference and double-angle formulas'],
               ['Prove: (1-cos^2θ)/sinθ = sinθ', 'Find sin(75°) using the sum formula: sin(45°+30°)'],
               ['When do you use the half-angle formula vs. the double-angle formula?'],
               [('The identity 1 + tan^2θ equals',
                 'sec^2θ — derived from sin^2θ+cos^2θ=1 by dividing through by cos^2θ',
                 ['csc^2θ', '1', 'cos^2θ']),
                ('sin(A + B) is NOT equal to',
                 'sin A + sin B — you must use the full formula: sinAcosB + cosAsinB',
                 ['sinAcosB + cosAsinB (the correct formula)', 'cos(A+B) with terms swapped', 'sin(B+A) — order does not matter for sine']),
                ('The double-angle formula sin(2θ) equals',
                 '2sinθcosθ — derived from sin(θ+θ) = sinθcosθ + cosθsinθ',
                 ['sin^2θ + cos^2θ = 1', '2sin^2θ', 'sin^2θ - cos^2θ']),
                ('The exact value of cos(15°) = cos(45°-30°) requires',
                 'the difference formula: cos45°cos30° + sin45°sin30°',
                 ['the half-angle formula: cos(30°/2)', 'the Pythagorean identity only', 'the double-angle formula: cos(30°/2)']),
                ('The co-function identity cos(π/2 - θ) equals',
                 'sin θ — cosine of the complement equals sine of the angle',
                 ['cos θ', '-sin θ', '-cos θ'])],
               [('College Trigonometry - Professor Leonard', 'Trig identities: Pythagorean, sum/difference, double-angle, and half-angle formulas', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Trigonometric Identities & Equations', 'Proving identities and applying sum, difference, and double-angle formulas', 'https://www.khanacademy.org/math/trigonometry/trig-equations-and-identities')],
               [('Using sin^2θ + cos^2θ = 1, the expression 1 - sin^2θ simplifies to',
                 'cos^2θ — rearranging the Pythagorean identity',
                 ['tan^2θ', '-cos^2θ', '1']),
                ('The identity cot θ is equivalent to',
                 'cosθ/sinθ — cotangent is the ratio of cosine to sine',
                 ['sinθ/cosθ (that is tanθ)', '1/tanθ only — not cos/sin (they are equal but students forget)', 'sec θ']),
                ('The value of cos(2θ) when sinθ = 3/5 (Q1) is',
                 '7/25 — use cos(2θ) = 1 - 2sin^2θ = 1 - 2(9/25) = 1 - 18/25 = 7/25',
                 ['-7/25', '6/25', '24/25']),
                ('The product-to-sum formula converts sinA·cosB to',
                 '(1/2)[sin(A+B) + sin(A-B)] — useful in calculus for integration',
                 ['sin(AB)', '(sinA + cosB)/2', 'sin^2(A-B)']),
                ('The half-angle formula for sin(θ/2) includes a ± sign because',
                 'the sign of sin(θ/2) depends on the quadrant in which θ/2 is located',
                 ['the formula was derived with an error', 'sine is always positive', 'both signs give the same value']),
                ('The identity sec^2θ - 1 simplifies to',
                 'tan^2θ — from 1 + tan^2θ = sec^2θ, rearranged',
                 ['csc^2θ - 1', '1', 'sin^2θ']),
                ('The even/odd property sin(-x) = -sin(x) means',
                 'sine is an odd function — its graph has 180° rotational symmetry about the origin',
                 ['sine is always negative', 'sine is symmetric about the y-axis', 'sin(-x) = sin(x)']),
                ('An identity that is NOT always true is',
                 'sin(A + B) = sinA + sinB — this is false for most A and B (e.g., A=B=π/4)',
                 ['sin^2θ + cos^2θ = 1', 'tanθ = sinθ/cosθ', 'sec θ = 1/cos θ']),
                ('The sum formula for cosine: cos(A+B) = cosAcosB - sinAsinB has a minus sign because',
                 'the full derivation from dot products or the Euler formula requires subtraction of the cross terms for cosine (while sine addition has a plus sign)',
                 ['cosine is always negative', 'the minus sign is optional — you can use a plus sign', 'this applies only when A+B > π']),
                ('To simplify (sinθ + cosθ)^2, the correct expansion is',
                 '1 + 2sinθcosθ = 1 + sin(2θ) — using FOIL and then the Pythagorean and double-angle identities',
                 ['sin^2θ + cos^2θ = 1 (missing the cross terms)', 'sin^2(2θ)', '2 + sin(2θ)']),
               ]),
        ],
    },

    {
        'num': 5,
        'title': 'Trigonometric Equations and Inverse Functions',
        'file': 'college-trigonometry-5-unit-5-trigonometric-equations-and-inverses.html',
        'desc': 'Solving trig equations on intervals and in general form; inverse trig functions and their restricted domains.',
        'gateway': [
            'Why must inverse trig functions have restricted domains?',
            'How do you find all solutions vs. principal value solutions to a trig equation?',
            'How do you solve trig equations requiring the quadratic or identity substitution?',
            'What are the domains and ranges of arcsin, arccos, and arctan?',
        ],
        'lessons': [
            _l('Inverse Trig Functions and Solving Trig Equations',
               [_t('Inverse Trigonometric Functions',
                    'Since trig functions are periodic (not one-to-one), their inverses require restricted domains. arcsin: domain [-1,1], range [-π/2, π/2]. arccos: domain [-1,1], range [0, π]. arctan: domain (-∞,∞), range (-π/2, π/2). Composition: sin(arcsin x) = x for x ∈ [-1,1]; arcsin(sin x) = x only for x ∈ [-π/2, π/2] (principal range).',
                    'Students think arcsin(sin 200°) = 200° — arcsin only returns values in [-90°, 90°], so arcsin(sin 200°) = -20° (the equivalent angle in the principal range).',
                    'State domains and ranges of inverse trig functions; evaluate compositions; find principal values.'),
                _t('Solving Trigonometric Equations',
                    'To solve sin x = k: find the reference angle (arcsin|k|), then place the solution in the correct quadrant(s). On [0, 2π): sine positive in Q1 and Q2; cosine positive in Q1 and Q4; tangent positive in Q1 and Q3. General solutions add ±2πn (or πn for tangent). For equations requiring algebra first (e.g., 2sin^2x - sinx - 1 = 0), factor or use substitution u = sinx.',
                    'Students find one solution and stop — always find ALL solutions on the given interval, and use general form (±2πn) when the domain is unrestricted.',
                    'Find all solutions to trig equations on [0, 2π); write general solutions; solve trig equations requiring factoring or substitution.')],
               [('arcsin (sin^(-1))', 'The inverse of sin with restricted domain: takes input in [-1,1] and returns angle in [-π/2, π/2]'),
                ('arccos (cos^(-1))', 'The inverse of cos with restricted domain: returns angle in [0, π]'),
                ('arctan (tan^(-1))', 'The inverse of tan: returns angle in (-π/2, π/2)'),
                ('principal value', 'The unique output of an inverse trig function within its restricted range'),
                ('general solution', 'All solutions to a trig equation: for sin/cos add ±2πn; for tan add πn'),
                ('extraneous solution', 'A value that satisfies a derived equation but not the original; check domain after squaring or substituting')],
               ['Evaluate inverse trig functions and compositions', 'Solve trig equations on [0, 2π) and in general form', 'Factor and solve trig equations using algebraic substitution'],
               ['Solve 2cos^2x - cosx - 1 = 0 on [0, 2π)', 'Find arctan(tan(7π/4))'],
               ['Why does arcsin(sin(3π/4)) ≠ 3π/4?'],
               [('arcsin(1/2) equals',
                 'π/6 — sin(π/6) = 1/2, and π/6 is in the principal range [-π/2, π/2]',
                 ['π/3', '5π/6', '-π/6']),
                ('The solutions to sin x = -√3/2 on [0, 2π) are',
                 'x = 4π/3 and x = 5π/3 — sine is negative in Q3 and Q4; reference angle = π/3',
                 ['x = π/3 and x = 2π/3', 'x = 2π/3 and x = 4π/3', 'x = 4π/3 only']),
                ('arccos(-1) equals',
                 'π — cos(π) = -1, and π is in the principal range [0, π]',
                 ['0', '-π', 'π/2']),
                ('The general solution to cos x = 0 is',
                 'x = π/2 + nπ — cosine is zero at π/2 and 3π/2, spaced π apart',
                 ['x = nπ', 'x = π/2 + 2nπ', 'x = nπ/2']),
                ('To solve 2sin^2x - sinx - 1 = 0, you should',
                 'let u = sinx and factor: (2u + 1)(u - 1) = 0, giving u = -1/2 or u = 1',
                 ['take the square root of both sides immediately', 'divide all terms by sinx', 'graph the function to find solutions visually'])],
               [('College Trigonometry - Professor Leonard', 'Inverse trig functions and solving trig equations on restricted intervals', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Inverse Trig & Solving Trig Equations', 'arcsin, arccos, arctan, and solving trig equations', 'https://www.khanacademy.org/math/trigonometry/trig-equations-and-identities')],
               [('arctan(1) equals',
                 'π/4 — tan(π/4) = 1, and π/4 is in the principal range (-π/2, π/2)',
                 ['π/3', 'π/2', '-π/4']),
                ('The equation tan^2x - 1 = 0 has solutions on [0, 2π) at',
                 'x = π/4, 3π/4, 5π/4, 7π/4 — tanx = ±1 occurs in all four quadrants',
                 ['x = π/4 and 5π/4 only (tan = 1)', 'x = π/4 only', 'x = π/4 and 3π/4 only']),
                ('The composition arcsin(sin(7π/6)) equals',
                 '-π/6 — sin(7π/6) = -1/2; arcsin(-1/2) = -π/6 (in the principal range)',
                 ['7π/6', '5π/6', 'π/6']),
                ('Solving sinx = 0.4 on [0, 2π) gives two solutions because',
                 'sine is positive in Q1 and Q2 — there are two angles with the same positive sine value',
                 ['sine repeats every π', 'there are always exactly two solutions', 'the calculator gives two values']),
                ('When solving a trig equation by squaring both sides, you must',
                 'check all solutions in the original equation to eliminate any extraneous solutions introduced by squaring',
                 ['only accept positive solutions', 'add ±π to each solution', 'first verify the equation has real solutions']),
                ('The range of arctan is',
                 '(-π/2, π/2) — open interval because the tangent function approaches but never reaches ±π/2',
                 ['[0, π]', '[-π/2, π/2]', '(-∞, ∞)']),
                ('To solve cos(2x) = 1/2 on [0, 2π), you find',
                 'four solutions: 2x = π/3, 5π/3, 7π/3, 11π/3, so x = π/6, 5π/6, 7π/6, 11π/6',
                 ['two solutions: x = π/3 and 5π/3', 'one solution: x = π/6', 'three solutions only']),
                ('The equation sinx = 2 has',
                 'no real solutions — sine values are always in [-1, 1], so 2 is out of range',
                 ['two solutions per period', 'the solution x = arcsin(2)', 'an infinite number of solutions']),
                ('Inverse trig functions must have restricted domains because',
                 'trig functions are periodic (not one-to-one over their full domain), so their inverses would fail the vertical line test without restriction',
                 ['they are defined only for positive angles', 'their ranges would be infinite without restriction', 'inverse functions are not needed for trig']),
                ('The number of solutions to sin x = 0.7 on [0, 4π) is',
                 '4 — two per period (Q1 and Q2 each period), and there are 2 full periods in [0, 4π)',
                 ['2', '1', '6']),
               ]),
        ],
    },

    {
        'num': 6,
        'title': 'Polar Coordinates, Vectors, and Complex Numbers',
        'file': 'college-trigonometry-6-unit-6-polar-vectors-and-complex-numbers.html',
        'desc': 'Polar coordinates, polar graphs, vector operations, dot products, and complex numbers in polar (trigonometric) form.',
        'gateway': [
            'How do polar coordinates differ from rectangular coordinates?',
            'What is a vector and how do you add, subtract, and dot-multiply vectors?',
            'How do you multiply and divide complex numbers using polar form?',
            'What is De Moivre\'s Theorem and how do you find nth roots of complex numbers?',
        ],
        'lessons': [
            _l('Polar Coordinates, Vectors, and Complex Numbers',
               [_t('Polar Coordinates and Graphs',
                    'Polar coordinates (r, θ) describe a point by distance r from the origin and angle θ. Convert to rectangular: x = r cosθ, y = r sinθ. Convert to polar: r = √(x^2+y^2), θ = arctan(y/x) (adjust quadrant). Polar graphs: r = a (circle), r = 2a cosθ (circle shifted), r = a + b cosθ (limaçon); if a=b: cardioid; r = a sin(nθ) or cos(nθ): rose curve with 2n petals (n even) or n petals (n odd).',
                    'Students use θ = arctan(y/x) without checking the quadrant — the arctan formula only gives angles in Q1 or Q4; adjust for Q2 and Q3.',
                    'Convert between polar and rectangular coordinates; graph polar equations; identify limaçons, cardioids, and rose curves.'),
                _t('Vectors and Complex Numbers in Trigonometric Form',
                    'A vector v = ⟨a, b⟩ has magnitude |v| = √(a^2+b^2) and direction θ = arctan(b/a). Dot product: v·w = a₁a₂+b₁b₂ = |v||w|cosθ (θ = angle between vectors). A complex number z = a+bi can be written in polar form z = r(cosθ + i sinθ) = re^(iθ), where r=|z| and θ=arg(z). De Moivre\'s Theorem: z^n = r^n(cos(nθ) + i sin(nθ)). nth roots: n roots evenly spaced by 2π/n.',
                    'Students think all vectors can be "divided" like scalars — you can compute dot products but vector division is not defined.',
                    'Compute vector magnitudes and dot products; convert complex numbers to polar form; apply De Moivre\'s Theorem.')],
               [('polar coordinates', '(r, θ) — r is distance from origin; θ is angle from positive x-axis'),
                ('cardioid', 'A heart-shaped polar curve: r = a(1 + cosθ) or r = a(1 + sinθ); special case of limaçon with a=b'),
                ('rose curve', 'A polar curve r = a sin(nθ) or r = a cos(nθ); n petals if n is odd, 2n petals if n is even'),
                ('dot product', 'v·w = a₁a₂+b₁b₂; equals |v||w|cosθ where θ is the angle between vectors; result is a scalar'),
                ('trigonometric form', 'z = r(cosθ + i sinθ) — polar form of a complex number; r is modulus, θ is argument'),
                ('De Moivre\'s Theorem', 'z^n = r^n(cos nθ + i sin nθ); used to find powers and nth roots of complex numbers')],
               ['Convert between polar and rectangular coordinates', 'Identify and graph polar curves (cardioid, rose)', 'Compute dot products and find angles between vectors', 'Multiply/divide complex numbers in polar form; apply De Moivre\'s Theorem'],
               ['Convert (3, π/4) to rectangular form', 'Find the cube roots of 8(cos π + i sin π) = -8'],
               ['Two vectors are perpendicular — what does their dot product equal?'],
               [('The rectangular coordinates equivalent to the polar point (2, π/3) are',
                 '(1, √3) — x = 2cos(π/3) = 2(1/2) = 1; y = 2sin(π/3) = 2(√3/2) = √3',
                 ['(2, √3)', '(√3, 1)', '(1, 2)']),
                ('The polar equation r = 3 describes',
                 'a circle of radius 3 centered at the origin',
                 ['a line passing through the origin at angle 3', 'a spiral', 'a parabola']),
                ('If vectors v = ⟨3, 4⟩ and w = ⟨0, 1⟩, then v · w equals',
                 '4 — dot product: 3(0) + 4(1) = 4',
                 ['3', '7', '⟨0, 4⟩']),
                ('Two vectors are orthogonal (perpendicular) if their dot product is',
                 '0 — v·w = |v||w|cos(90°) = |v||w|(0) = 0',
                 ['1', 'equal to their magnitudes', 'negative']),
                ('The modulus of the complex number 3 + 4i is',
                 '5 — |z| = √(3^2+4^2) = √25 = 5',
                 ['7', '3', '√7'])],
               [('College Trigonometry - Professor Leonard', 'Polar coordinates, vectors, complex numbers in polar form, and De Moivre theorem', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Polar Coordinates & Complex Numbers', 'Polar graphing, vector operations, and complex number operations', 'https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:polar-coordinates')],
               [('The argument (angle) of the complex number -1 + i√3 is',
                 '2π/3 — in Q2 (x<0, y>0); reference angle = arctan(√3/1) = π/3; angle = π - π/3 = 2π/3',
                 ['π/3', '-π/3', '5π/3']),
                ('De Moivre\'s Theorem states that (r(cosθ + i sinθ))^n equals',
                 'r^n(cos nθ + i sin nθ) — raise the modulus to the nth power and multiply the angle by n',
                 ['r^n(cos θ + i sin θ)', 'r(cos nθ + i sin nθ)', 'n·r(cosθ + i sinθ)']),
                ('The three cube roots of 1 are',
                 '1, (-1+i√3)/2, and (-1-i√3)/2 — three roots equally spaced at 120° apart on the unit circle',
                 ['1, i, and -1', '1 only (the only real cube root)', '1, -1, and i']),
                ('The rose curve r = 3 cos(2θ) has',
                 '4 petals — for even n, the number of petals is 2n = 4',
                 ['2 petals', '3 petals', '6 petals']),
                ('The cardioid r = 1 + sinθ has its cusp (indentation) at',
                 'the origin (r = 0 when sinθ = -1, at θ = 3π/2) — the loop touches the pole at the bottom',
                 ['at θ = 0 (rightmost point)', 'at θ = π/2 (topmost point)', 'at θ = π (leftmost point)']),
                ('Multiplying two complex numbers in polar form multiplies their moduli and',
                 'adds their arguments (angles) — z₁z₂ = r₁r₂[cos(θ₁+θ₂) + i sin(θ₁+θ₂)]',
                 ['subtracts their arguments', 'multiplies their arguments', 'keeps the angles unchanged']),
                ('The magnitude of vector ⟨-5, 12⟩ is',
                 '13 — |v| = √(25 + 144) = √169 = 13',
                 ['17', '7', '√119']),
                ('Dividing complex numbers in polar form divides their moduli and',
                 'subtracts the argument of the denominator from the argument of the numerator',
                 ['adds their arguments', 'multiplies their arguments', 'divides the argument of the numerator by the denominator\'s']),
                ('The polar form of the complex number 2i is',
                 '2(cos(π/2) + i sin(π/2)) — modulus = 2; argument = π/2 (pointing straight up)',
                 ['2(cos 0 + i sin 0)', '2(cos π + i sin π)', 'i(cos 2 + i sin 2)']),
                ('A vector pointing in the direction of ⟨3, 4⟩ has the unit vector',
                 '⟨3/5, 4/5⟩ — divide each component by the magnitude (5)',
                 ['⟨1/3, 1/4⟩', '⟨4/5, 3/5⟩', '⟨3, 4⟩/5 is not a unit vector']),
               ]),
        ],
    },
]
