NAME        = 'College Algebra'
ABBREV      = 'collegealg'
SLUG        = 'college-algebra'
COURSE_FILE = 'college-algebra.html'
ACCENT_COLOR = '#38bdf8'
NON_AP      = True

_Y = 'https://www.youtube.com/results?search_query=College+Algebra+'
_K = 'https://www.khanacademy.org/math/algebra/'

COURSE_QS = [
    ('The real number property a(b + c) = ab + ac is called the',
     'Distributive Property',
     ['Commutative Property', 'Associative Property', 'Identity Property']),
    ('To simplify the expression (x^3)(x^5), you',
     'add the exponents: x^(3+5) = x^8',
     ['multiply the exponents: x^15', 'subtract the exponents: x^-2', 'keep the larger exponent: x^5']),
    ('The solution to |x - 3| = 7 is',
     'x = 10 or x = -4',
     ['x = 10 only', 'x = 4 or x = -4', 'x = 10 or x = 4']),
    ('A linear equation in one variable has',
     'exactly one solution (unless it is an identity or contradiction)',
     ['always exactly two solutions', 'no solutions', 'infinitely many solutions always']),
    ('The slope of a line passing through (2, 5) and (6, 13) is',
     '2, calculated as (13-5)/(6-2) = 8/4 = 2',
     ['1/2', '4', '8']),
    ('A function f is defined as a relation where',
     'each input (x-value) maps to exactly one output (y-value)',
     ['each output maps to exactly one input', 'inputs and outputs can be any relation', 'the graph must be a straight line']),
    ('The vertical line test is used to determine whether',
     'a graph represents a function — if any vertical line crosses the graph more than once, it is not a function',
     ['a function is one-to-one (injective)', 'a function is linear', 'a graph has a vertical asymptote']),
    ('The domain of f(x) = 1/(x - 4) excludes',
     'x = 4, because division by zero is undefined',
     ['x = 0', 'x = -4', 'all negative values of x']),
    ('The vertex form of a quadratic function is',
     'f(x) = a(x - h)^2 + k, where (h, k) is the vertex',
     ['f(x) = ax^2 + bx + c (standard form)', 'f(x) = (x - r)(x - s) (factored form)', 'f(x) = mx + b (slope-intercept form)']),
    ('The quadratic formula gives the solutions to ax^2 + bx + c = 0 as',
     'x = [-b ± √(b^2 - 4ac)] / (2a)',
     ['x = -b/a', 'x = (b ± √discriminant) / a', 'x = ±√(c/a)']),
    ('If the discriminant b^2 - 4ac is negative, the quadratic has',
     'no real solutions — only two complex (imaginary) solutions',
     ['one repeated real solution', 'two distinct real solutions', 'no solutions of any kind']),
    ('The function f(x) = x^2 - 4 factors as',
     '(x + 2)(x - 2) — a difference of squares',
     ['(x - 2)^2', '(x + 4)(x - 1)', '(x - 2)(x + 4)']),
    ('The composition (f ∘ g)(x) means',
     'f(g(x)) — apply g first, then apply f to the result',
     ['f(x) · g(x)', 'g(f(x)) — apply f first then g', 'the sum f(x) + g(x)']),
    ('The inverse function f^(-1) of f satisfies',
     'f(f^(-1)(x)) = x and f^(-1)(f(x)) = x — it "undoes" f',
     ['f^(-1)(x) = 1/f(x) (the reciprocal)', 'the inverse always exists for every function', 'f^(-1)(x) = -f(x)']),
    ('To find the inverse of y = 2x + 3, you',
     'swap x and y, then solve: x = 2y + 3 → y = (x - 3)/2, so f^(-1)(x) = (x-3)/2',
     ['take the negative of each term: y = -2x - 3', 'divide all terms by 2: y = x + 3/2', 'reflect the graph over the x-axis']),
    ('The slope of a horizontal line is',
     '0 — the line has no rise for any run',
     ['undefined', '1', 'infinite']),
    ('A system of two linear equations with no solution is called',
     'inconsistent — the lines are parallel and never intersect',
     ['consistent', 'dependent', 'orthogonal']),
    ('The expression √(-16) simplifies to',
     '4i, where i = √(-1)',
     ['4', '-4', 'undefined — square roots of negatives do not exist']),
    ('The absolute value |x| represents',
     'the distance of x from zero on the number line — always non-negative',
     ['the sign of x (positive or negative)', 'x squared', 'the reciprocal of x']),
    ('A rational expression is undefined when',
     'its denominator equals zero — division by zero is undefined in algebra',
     ['its numerator equals zero', 'the expression is negative', 'the variable is greater than 1']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 1,
        'title': 'Algebra Foundations',
        'file': 'college-algebra-1-unit-1-algebra-foundations.html',
        'desc': 'Real number properties, order of operations, exponent rules, and algebraic expressions.',
        'gateway': [
            'What are the properties of real numbers?',
            'How do exponent rules simplify expressions?',
            'What is the difference between an expression and an equation?',
            'How do you simplify radical and rational exponent expressions?',
        ],
        'lessons': [
            _l('Real Numbers, Properties, and Exponent Rules',
               [_t('Real Number Properties',
                    'The real numbers satisfy commutative (a+b=b+a), associative ((a+b)+c=a+(b+c)), distributive (a(b+c)=ab+ac), identity (a+0=a, a·1=a), and inverse (a+(-a)=0) properties. Order of operations: PEMDAS (Parentheses, Exponents, Multiplication/Division left-to-right, Addition/Subtraction left-to-right).',
                    'Students forget the distributive property when subtracting: a-(b+c) = a-b-c, not a-b+c.',
                    'Apply properties to simplify expressions; identify violations of properties; evaluate expressions using PEMDAS.'),
                _t('Exponent Rules and Radicals',
                    'Key exponent rules: x^a · x^b = x^(a+b), x^a/x^b = x^(a-b), (x^a)^b = x^(ab), x^0 = 1 (x≠0), x^(-n) = 1/x^n. Radicals: √(x^2) = |x|; √a · √b = √(ab); rational exponents: x^(m/n) = (x^(1/n))^m = (ⁿ√x)^m.',
                    'Students think √(a²+b²) = a+b (incorrect; you cannot distribute the radical over addition).',
                    'Apply exponent rules to simplify; convert between radical and rational exponent forms; evaluate numerical expressions with exponents.')],
               [('distributive property', 'a(b + c) = ab + ac; used to expand or factor expressions'),
                ('PEMDAS', 'Order of operations: Parentheses, Exponents, Multiplication/Division, Addition/Subtraction'),
                ('rational exponent', 'An exponent that is a fraction: x^(m/n) = the nth root of x, raised to the m power'),
                ('radical', 'An expression using a root symbol (√); √a means the principal (non-negative) square root of a'),
                ('absolute value', 'The distance of a number from zero; |x| ≥ 0 always')],
               ['Apply the distributive property to expand and factor', 'Simplify expressions using exponent rules', 'Convert between radical and rational exponent form'],
               ['Simplify 3(x - 2) + 5x using the distributive and combining-like-terms', 'Evaluate x^(-2) · x^5 using exponent rules'],
               ['What is √(x^6) simplified? What condition on x matters?'],
               [('The product rule for exponents states that x^3 · x^4 equals',
                 'x^7 — add the exponents when multiplying like bases',
                 ['x^12 (multiply exponents)', 'x^(3/4) (divide exponents)', 'x^1 (subtract exponents)']),
                ('The expression (2x^3y)^2 simplifies to',
                 '4x^6y^2 — square each factor including the coefficient',
                 ['2x^6y^2', '4x^6y', '2x^5y^2']),
                ('The expression x^(-3) is equivalent to',
                 '1/x^3 — negative exponents indicate reciprocals',
                 ['−x^3', 'x^(1/3)', '−1/x^3']),
                ('√(49x^4) simplifies to',
                 '7x^2 — take the square root of each factor (assuming x ≥ 0)',
                 ['7x^2 only when x > 0', '7|x^2|', '49x^2']),
                ('The number 16^(3/4) equals',
                 '8 — (⁴√16)^3 = 2^3 = 8',
                 ['4', '12', '64'])],
               [('College Algebra Full Course — Professor Leonard', 'Real numbers, exponent rules, radicals, and order of operations', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Algebra 1 & 2', 'Interactive lessons on algebra foundations and expressions', 'https://www.khanacademy.org/math/algebra2')],
               [('Simplifying -(3x - 5) gives',
                 '-3x + 5 — distribute the negative sign to every term inside the parentheses',
                 ['-3x - 5', '3x - 5', '-3x - 5 + x']),
                ('The expression 4^(-1/2) equals',
                 '1/2 — 4^(1/2) = 2, so 4^(-1/2) = 1/2',
                 ['2', '-2', '-1/2']),
                ('x^0 equals (for x ≠ 0)',
                 '1 — any non-zero base to the power zero is 1',
                 ['0', 'x', 'undefined']),
                ('The real number property a + b = b + a is called the',
                 'Commutative Property of Addition',
                 ['Associative Property', 'Distributive Property', 'Identity Property']),
                ('Which operation is performed first in 3 + 4 × 2?',
                 'Multiplication: 4 × 2 = 8, then 3 + 8 = 11',
                 ['Addition: 3 + 4 = 7, then 7 × 2 = 14', 'Left to right: 3 + 4 = 7 first', 'Both simultaneously']),
                ('The expression (x^2)^3 simplifies to',
                 'x^6 — multiply exponents when raising a power to a power',
                 ['x^5', 'x^8', 'x^23']),
                ('√12 simplifies to',
                 '2√3 — factor out the perfect square: √(4·3) = 2√3',
                 ['6', '3√2', '√12 cannot be simplified']),
                ('The Associative Property of Multiplication states',
                 '(ab)c = a(bc) — regrouping factors does not change the product',
                 ['ab = ba (that is commutative)', 'a(b+c) = ab+ac (that is distributive)', 'a·1 = a (that is identity)']),
                ('Which of the following is an irrational number?',
                 '√5 — it cannot be expressed as a ratio of integers',
                 ['√4 = 2', '0.75', '7/3']),
                ('The expression √a · √b equals',
                 '√(ab) — you can multiply under a single radical when both a, b ≥ 0',
                 ['√(a+b)', 'a·b', '√(a/b)']),
               ]),
        ],
    },

    {
        'num': 2,
        'title': 'Equations and Inequalities',
        'file': 'college-algebra-2-unit-2-equations-and-inequalities.html',
        'desc': 'Linear, quadratic, absolute value, and rational equations; linear and compound inequalities.',
        'gateway': [
            'How do you solve linear equations in one variable?',
            'What does the discriminant tell you about a quadratic?',
            'How do you solve absolute value equations and inequalities?',
            'What changes when you multiply an inequality by a negative number?',
        ],
        'lessons': [
            _l('Solving Equations and Inequalities',
               [_t('Linear and Quadratic Equations',
                    'Linear equations (ax + b = c) are solved by isolating x. Quadratic equations (ax^2+bx+c=0) can be solved by factoring, completing the square, or the quadratic formula: x = [-b ± √(b^2-4ac)]/(2a). The discriminant D = b^2-4ac tells you the number of real roots: D>0 (two distinct real roots), D=0 (one repeated root), D<0 (no real roots, two complex roots).',
                    'Students forget the ± in the quadratic formula, getting only one solution instead of two.',
                    'Solve linear equations; apply the quadratic formula; interpret the discriminant.'),
                _t('Inequalities and Absolute Value Equations',
                    'Solving inequalities follows the same steps as equations, with one critical difference: multiplying or dividing by a negative number reverses the inequality sign. Compound inequalities (a < x < b or x < a or x > b) require careful interval notation. Absolute value equations |f(x)| = k require splitting into two cases: f(x) = k and f(x) = -k. Absolute value inequalities: |x| < k means -k < x < k.',
                    'Students do not flip the inequality sign when multiplying by a negative — this is the most common error in inequality solving.',
                    'Solve linear inequalities; write solutions in interval notation; solve absolute value equations and inequalities.')],
               [('discriminant', 'b^2 - 4ac from the quadratic formula; determines the number and type of roots'),
                ('completing the square', 'A method of rewriting ax^2+bx+c as a(x-h)^2+k by adding and subtracting (b/2a)^2'),
                ('interval notation', 'A way to write solution sets: [a,b] = a≤x≤b; (a,b) = a<x<b; ∞ always uses parentheses'),
                ('compound inequality', 'Two inequalities joined by "and" (intersection) or "or" (union)'),
                ('absolute value inequality', '|x| < k means -k < x < k (and); |x| > k means x < -k or x > k (or)')],
               ['Apply the quadratic formula and interpret the discriminant', 'Solve linear inequalities including flipping the sign', 'Solve absolute value equations and inequalities'],
               ['Solve 2x^2 - 5x - 3 = 0 by factoring or quadratic formula', 'Solve -3x + 6 > 0 and write in interval notation'],
               ['What does it mean for an equation to have "no real solution"?'],
               [('The solutions to x^2 - 5x + 6 = 0 are',
                 'x = 2 and x = 3 — factor as (x-2)(x-3)=0',
                 ['x = -2 and x = -3', 'x = 5 and x = 6', 'x = 1 and x = 6']),
                ('If the discriminant of a quadratic is -9, the equation has',
                 'no real solutions — only two complex (imaginary) solutions',
                 ['one repeated real solution', 'two distinct real solutions', 'three solutions']),
                ('Solving the inequality -2x > 8 gives',
                 'x < -4 — dividing by -2 reverses the inequality sign',
                 ['x > -4', 'x > 4', 'x < 4']),
                ('|2x - 3| = 7 gives the solutions',
                 'x = 5 and x = -2 — set 2x-3=7 (x=5) and 2x-3=-7 (x=-2)',
                 ['x = 5 only', 'x = 2 and x = 5', 'x = -2 only']),
                ('Interval notation for -1 ≤ x < 5 is',
                 '[-1, 5) — square bracket for ≤, parenthesis for <',
                 ['(-1, 5]', '[-1, 5]', '(-1, 5)'])],
               [('College Algebra — Professor Leonard', 'Solving equations, inequalities, quadratic formula, and absolute value', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Solving Equations & Inequalities', 'Linear, quadratic, rational, and absolute value equations', 'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:solve-equations-inequalities')],
               [('The quadratic formula applies to equations in the form',
                 'ax^2 + bx + c = 0, where a ≠ 0',
                 ['ax^2 + bx = 0 only (c must be 0)', 'any polynomial equation', 'equations with exactly one term']),
                ('Solving 3(x - 2) = 12 gives',
                 'x = 6 — distribute (3x - 6 = 12), then add 6 and divide by 3',
                 ['x = 18', 'x = 2', 'x = 4']),
                ('A quadratic with discriminant = 0 has',
                 'exactly one repeated real solution (a perfect square trinomial)',
                 ['two distinct real solutions', 'no real solutions', 'infinitely many solutions']),
                ('The solution set of |x| ≤ 4 is',
                 '-4 ≤ x ≤ 4 (written [-4, 4]) — absolute value less-than means "between"',
                 ['x ≤ 4 (written (-∞, 4])', 'x ≤ -4 or x ≥ 4 (union)', 'x < -4 or x > 4 only']),
                ('When solving a rational equation, you must',
                 'multiply both sides by the LCD and then check for extraneous solutions where the denominator would be zero',
                 ['add fractions without clearing denominators first', 'only solve for positive values of x', 'divide both sides by the variable term first']),
                ('Completing the square on x^2 + 6x transforms the expression into',
                 '(x + 3)^2 - 9 — add and subtract (6/2)^2 = 9',
                 ['(x + 6)^2 - 36', '(x + 3)^2 + 9', '(x + 3)^2']),
                ('The solution to 2x - 3 ≤ 7 AND x + 1 > 0 is',
                 '-1 < x ≤ 5, written (-1, 5] — the intersection of both solution sets',
                 ['x ≤ 5 only', 'x > -1 only', 'all real numbers']),
                ('An extraneous solution in a radical equation',
                 'satisfies the algebraic manipulation but not the original equation — created when both sides are squared',
                 ['is a second valid solution', 'occurs only in linear equations', 'is always a negative number']),
                ('The equation x^2 = -16 has',
                 'no real solutions — a square cannot equal a negative number in the reals (solutions are ±4i)',
                 ['x = 4 and x = -4', 'x = ±8', 'no solutions at all, including complex']),
                ('Solving x/2 + 1 = 3 gives',
                 'x = 4 — subtract 1 from both sides, then multiply both sides by 2',
                 ['x = 8', 'x = 5', 'x = 2']),
               ]),
        ],
    },

    {
        'num': 3,
        'title': 'Functions and Graphs',
        'file': 'college-algebra-3-unit-3-functions-and-graphs.html',
        'desc': 'Function definition, domain/range, graphs, transformations, composition, and inverses.',
        'gateway': [
            'What is a function and how do you identify one?',
            'How do transformations shift, reflect, and stretch a graph?',
            'How do you find the domain and range of a function?',
            'What is the relationship between a function and its inverse?',
        ],
        'lessons': [
            _l('Functions: Definition, Graphs, and Transformations',
               [_t('Functions, Domain, and Range',
                    'A function assigns exactly one output to each input. The domain is the set of all valid inputs (x-values); the range is the set of all outputs (y-values). Common domain restrictions: denominators ≠ 0; radicands of even roots ≥ 0. The vertical line test: if any vertical line crosses a graph more than once, the relation is NOT a function.',
                    'Students confuse "not a function" with "has no value" — a graph can still have y-values at every x but fail the vertical line test (e.g., a circle).',
                    'Identify functions using the vertical line test; determine domain and range; state domain restrictions for rational/radical functions.'),
                _t('Transformations and Inverse Functions',
                    'Graph transformations: f(x)+k shifts up k; f(x+h) shifts left h; -f(x) reflects over x-axis; f(-x) reflects over y-axis; af(x) vertical stretch (a>1) or compression (0<a<1). Inverse functions reverse the mapping — to find f^(-1), swap x and y then solve for y. A function has an inverse that is also a function only if f is one-to-one (passes the horizontal line test).',
                    'Students confuse horizontal shift direction: f(x+3) shifts LEFT 3 (not right), because x+3=0 when x=-3.',
                    'Apply transformations to sketch graphs; find inverse functions algebraically; use the horizontal line test.')],
               [('domain', 'The set of all valid input (x) values for a function'),
                ('range', 'The set of all output (y) values produced by a function'),
                ('vertical line test', 'A graph represents a function if and only if no vertical line crosses the graph more than once'),
                ('horizontal line test', 'A function is one-to-one (has an inverse function) if and only if no horizontal line crosses the graph more than once'),
                ('piecewise function', 'A function defined by different formulas on different intervals of the domain'),
                ('even function', 'f(-x) = f(x) — symmetric about the y-axis; odd function: f(-x) = -f(x), symmetric about the origin')],
               ['Apply the vertical line test to identify functions', 'State the domain and range of common functions', 'Apply transformations and sketch the resulting graph', 'Find inverse functions algebraically'],
               ['Find the domain of f(x) = √(x-3) / (x-5)', 'If f(x) = 2x+1, find f^(-1)(x) and verify f(f^(-1)(x)) = x'],
               ['What does the horizontal line test tell you about a function\'s inverse?'],
               [('The domain of f(x) = 1/(x^2 - 9) is',
                 'all real numbers except x = ±3 (where the denominator is zero)',
                 ['all real numbers', 'x > 0 only', 'x ≠ 0']),
                ('The graph of f(x) + 3 is the graph of f(x) shifted',
                 'up 3 units (vertical shift)',
                 ['right 3 units', 'left 3 units', 'down 3 units']),
                ('The graph of f(x - 2) is the graph of f(x) shifted',
                 'right 2 units — replace x with x-2 means the graph moves in the positive x direction',
                 ['left 2 units', 'up 2 units', 'down 2 units']),
                ('The inverse of f(x) = 3x - 6 is',
                 'f^(-1)(x) = (x + 6)/3 — swap x and y: x = 3y-6, solve for y',
                 ['f^(-1)(x) = 3x + 6', 'f^(-1)(x) = 1/(3x-6)', 'f^(-1)(x) = -3x + 6']),
                ('(f ∘ g)(x) where f(x) = x^2 and g(x) = x+1 equals',
                 '(x+1)^2 — apply g first (x+1), then apply f (square it)',
                 ['x^2 + 1', 'x^2(x+1)', '(x^2)+1'])],
               [('College Algebra — Professor Leonard', 'Functions, graphs, transformations, domain, range, and inverses', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy: Functions', 'Defining, graphing, and transforming functions', 'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:functions')],
               [('A relation is a function only if',
                 'every input (x-value) maps to exactly one output — no x-value can pair with two different y-values',
                 ['every output maps to exactly one input', 'the graph is a smooth curve without gaps', 'the domain includes all real numbers']),
                ('The function f(x) = |x| has the range',
                 '[0, ∞) — absolute value outputs are always non-negative',
                 ['all real numbers (-∞, ∞)', '(-∞, 0]', '(0, ∞)']),
                ('Reflecting f(x) over the y-axis produces',
                 'f(-x) — replace x with -x to reflect over the y-axis',
                 ['-f(x) (reflection over x-axis)', 'f(x) + k (vertical shift)', 'f(x - k) (horizontal shift)']),
                ('A function is one-to-one if',
                 'every output corresponds to exactly one input — it passes both the vertical AND horizontal line tests',
                 ['it passes only the vertical line test', 'its domain is all real numbers', 'it is a polynomial function']),
                ('The notation f^(-1)(x) means',
                 'the inverse function of f — the function that undoes f; NOT the reciprocal 1/f(x)',
                 ['1/f(x) — the reciprocal of f', 'the derivative of f', 'f applied twice']),
                ('The domain of f(x) = √(2x - 8) is',
                 'x ≥ 4 — set 2x - 8 ≥ 0 and solve: x ≥ 4',
                 ['x ≥ 0', 'x ≥ 8', 'all real numbers']),
                ('A vertical stretch by factor 3 transforms f(x) to',
                 '3f(x) — multiply every y-value by 3, making the graph taller',
                 ['f(3x) (horizontal compression)', 'f(x/3) (horizontal stretch)', 'f(x) + 3 (vertical shift up)']),
                ('If f(2) = 7, then f^(-1)(7) equals',
                 '2 — the inverse function reverses the mapping: if f maps 2 to 7, then f^(-1) maps 7 to 2',
                 ['1/7', '7/2', '14']),
                ('An even function satisfies',
                 'f(-x) = f(x) — its graph is symmetric about the y-axis (e.g., f(x) = x^2)',
                 ['f(-x) = -f(x) (that is an odd function)', 'f(x) = f(x+2) (periodic)', 'f(x) > 0 for all x']),
                ('The range of f(x) = -x^2 + 4 is',
                 '(-∞, 4] — the parabola opens downward with vertex at (0, 4), so outputs are at most 4',
                 ['[4, ∞)', 'all real numbers', '[-4, 4]']),
               ]),
        ],
    },
]
