NAME        = 'AP® Computer Science A'
ABBREV      = 'csa'
SLUG        = 'ap-computer-science-a'
COURSE_FILE = 'ap-computer-science-a.html'
ACCENT_COLOR = '#5b9cf6'
_K = 'https://www.khanacademy.org/search?page_search_query='
_Y = 'https://www.youtube.com/results?search_query=AP®+CS+A+'

COURSE_QS = [
    ('In Java, the difference between == and .equals() for String comparison is that == checks',
     'reference equality (whether two variables point to the same object), while .equals() checks value equality (same characters)',
     ['.equals() checks reference, == checks value', 'both perform the same comparison', '== works for all object types correctly']),
    ('Which of the following correctly declares and initializes an integer array of size 5 in Java?',
     'int[] arr = new int[5];',
     ['int arr = new int[5];', 'int arr[5];', 'int[] arr = {5};']),
    ('In Java, a method declared "private" can only be accessed',
     'within the same class',
     ['within the same package', 'by subclasses through inheritance', 'from any class in the program']),
    ('What is the output of this code: int x = 5; System.out.println(x++);',
     '5 — the post-increment operator returns the original value before incrementing',
     ['6 — x is incremented first', '4', 'a compile error']),
    ('A recursive method requires a base case to',
     'stop the recursion and prevent infinite recursive calls (stack overflow)',
     ['improve performance over iteration', 'allow the method to call other methods', 'pass parameters correctly']),
    ('The ArrayList class in Java differs from a regular array in that ArrayList',
     'can grow and shrink dynamically and provides methods like add(), remove(), and size()',
     ['can only store integers', 'has fixed size like a regular array', 'is more memory-efficient than arrays']),
    ('In Java, inheritance is implemented using the keyword',
     'extends (a subclass extends a superclass)',
     ['implements', 'inherits', 'override']),
    ('Polymorphism in Java allows',
     'a superclass reference to call overridden methods of a subclass at runtime (dynamic dispatch)',
     ['a class to have multiple constructors only', 'a method to have multiple names', 'different classes to have the same exact methods with no variation']),
    ('What does "encapsulation" mean in object-oriented programming?',
     'Bundling data (fields) and methods together in a class, and restricting direct access to internal data using private fields and public getters/setters',
     ['inheriting methods from a parent class', 'creating multiple objects from one class', 'using abstract classes instead of concrete ones']),
    ('In a for loop "for (int i = 0; i < 10; i++)", the loop body executes',
     '10 times (i = 0, 1, 2, ..., 9)',
     ['11 times', '9 times', 'indefinitely if i is never updated']),
    ('A binary search requires the array to be',
     'sorted (in ascending or descending order) for the algorithm to work correctly',
     ['of even length', 'filled with unique values only', 'stored as an ArrayList']),
    ('The worst-case time complexity of selection sort is',
     'O(n²) — always makes n(n-1)/2 comparisons regardless of input order',
     ['O(n log n)', 'O(n)', 'O(log n)']),
    ('In Java, an interface differs from an abstract class in that an interface',
     'cannot have instance fields or concrete methods (before Java 8 default methods), and a class can implement multiple interfaces but only extends one class',
     ['can be instantiated directly', 'can only have static methods', 'replaces all need for inheritance']),
    ('What is the result of integer division 7/2 in Java?',
     '3 — Java truncates the decimal for integer division',
     ['3.5', '4', '3.5 rounded to 4']),
    ('A NullPointerException in Java is thrown when',
     'you try to call a method or access a field on a reference variable that holds null',
     ['an array index is out of bounds', 'you divide an integer by zero', 'a variable is declared but not initialized']),
    ('The toString() method in Java is useful because',
     'it provides a String representation of an object, called automatically by System.out.println()',
     ['it converts int to String using casting', 'it returns the memory address as a String', 'it compares two objects for equality']),
    ('In Java, the keyword "static" means the method or field belongs to',
     'the class itself, not to any particular instance (shared among all objects)',
     ['only the current object', 'subclasses that override it', 'private access only']),
    ('When an array is passed to a method in Java,',
     'the method receives a reference to the same array (changes inside the method affect the original)',
     ['a copy of the array is made', 'the array becomes read-only', 'the method cannot modify the array']),
    ('A 2D array in Java is declared as',
     'int[][] matrix = new int[rows][cols];',
     ['int[,] matrix = new int[rows, cols];', 'int matrix[][] = new int(rows)(cols);', 'int[rows][cols] matrix;']),
    ('The modulo operator % in Java returns',
     'the remainder after integer division (e.g., 7 % 3 = 1)',
     ['the quotient of division', 'the absolute value of the difference', 'the result rounded to nearest integer']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 1,
        'title': 'Using Objects and Methods',
        'file': 'ap-computer-science-a-1-unit-1-using-objects-and-methods.html',
        'desc': 'Primitive data types, variable declarations, object instantiation, and calling methods in Java.',
        'gateway': [
            'What are the primitive types in Java and how are they different from objects?',
            'How do you declare variables and assign values in Java?',
            'What is the difference between a class and an object?',
            'How do you call methods on objects and interpret return values?',
        ],
        'lessons': [
            _l('Primitive Types and Variables',
               [_t('Primitive Data Types', 'Java has eight primitive types; AP® CS A focuses on int (whole numbers), double (decimals), and boolean (true/false). Literals are written directly: 42, 3.14, true.', 'String is NOT a primitive — it is a class/reference type. Confusing String with primitive types is a common error.', 'MCQ identifies type of a value; FRQ declares correct types in method signatures.'),
                _t('Variable Declaration and Assignment', 'Declare: type name; or type name = value; Assignment uses = (not equality). Java is statically typed — the type cannot change after declaration.', 'The = operator is assignment, not equality. == tests equality for primitives.', 'Trace code to find the value of a variable after a series of assignments.'),
                _t('Casting and Arithmetic', 'Integer division truncates: 7/2 → 3. Cast with (double) to get 3.5. Modulo % gives remainder: 7%2 → 1. Mixed int/double arithmetic promotes to double.', 'Integer division silently truncates — a frequent source of off-by-one errors in AP® FRQ.', 'Predict result of arithmetic expressions including integer division and modulo.')],
               [('int', 'Primitive integer type; stores whole numbers; range ±2.1 billion'),
                ('double', 'Primitive floating-point type; stores decimals; IEEE 754'),
                ('boolean', 'Primitive type; stores true or false'),
                ('assignment', 'The = operator stores a value into a variable; does not test equality'),
                ('modulo %', 'Returns remainder of integer division; e.g., 7%3 = 1')],
               ['Declare and initialize int, double, and boolean variables.',
                'Trace arithmetic expressions involving integer division and modulo.',
                'Explain the difference between primitives and reference types.'],
               ['MCQ: evaluate expression with integer division and casting.',
                'FRQ: declare a variable with the correct type in a method.',
                'Tracing: find the final value of a variable after several assignments.'],
               ['Practice arithmetic operator precedence and integer division.',
                'Write declarations for a small program tracking a score and a balance.'],
               [('What is the output of: int x = 7; int y = 2; System.out.println(x/y);', ['Integer division truncates toward zero', '7/2 → 3 (not 3.5)', 'To get 3.5 you need (double)x/y or 7.0/2', 'Output: 3']),
                ('What is 17 % 5?', ['% is the modulo (remainder) operator', '17 / 5 = 3 remainder 2', '17 % 5 = 2', 'Useful for checking even/odd: n%2==0 means even']),
                ('Declare a double variable price initialized to 9.99.', ['Type keyword: double', 'Variable name: price', 'Initialization: = 9.99', 'Full statement: double price = 9.99;']),
                ('What is (int)(3.9)?', ['Casting truncates — does NOT round', '(int)(3.9) → 3', '(int)(-3.9) → -3 (truncates toward zero)', 'Use Math.round() if you need rounding']),
                ('What value does boolean done = false; x = true; produce for done?', ['done was declared false', 'Reassigning x does not affect done', 'done remains false', 'Variables are independent unless one is assigned the other'])],
               [('Khan Academy Java Variables', 'Declaring and using primitive variables', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('AP® CS A Unit 1 Overview', 'Primitive types, casting, and arithmetic', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['int, double, boolean are primitives; String is a reference type.',
                'Integer division truncates: 7/2 = 3; use (double) to cast.',
                'Modulo % gives remainder; useful for even/odd, cycling.']),

            _l('Objects and Method Calls',
               [_t('Classes and Objects', 'A class is a blueprint; an object is an instance. Create objects with new: String s = new String("hi"); or String s = "hi"; Objects live on the heap.', 'Using a variable name before assigning an object gives a NullPointerException, not a compile error.', 'Identify whether a variable holds a primitive or a reference; trace object creation.'),
                _t('Calling Instance Methods', 'Instance methods are called on an object: object.method(args). They may return a value or be void. The dot operator accesses members of an object.', 'Methods called on null throw NullPointerException — check that the variable has been initialized first.', 'Read and trace method calls; predict return values from method documentation.'),
                _t('String Methods', 'Key String methods (AP® CS A subset): length(), substring(i,j), indexOf(str), equals(str), compareTo(str). Strings are immutable — methods return new Strings without changing the original.', 'Strings are compared with .equals() not ==. Using == compares references, not content.', 'Apply String methods in code and predict return values; trace substring indices.')],
               [('class', 'Blueprint that defines data (fields) and behavior (methods) for objects'),
                ('object', 'Instance of a class created with new; holds its own copy of instance variables'),
                ('null', 'Default value of a reference variable before initialization; accessing it causes NullPointerException'),
                ('String.substring(i,j)', 'Returns characters from index i (inclusive) to j (exclusive)'),
                ('String.equals(s)', 'Compares String content; use instead of == for Strings')],
               ['Create objects using the new operator.',
                'Call instance methods and interpret return values.',
                'Apply String methods: length, substring, indexOf, equals.'],
               ['MCQ: identify the output of a sequence of method calls.',
                'FRQ: call the correct String methods to manipulate a String parameter.',
                'Trace NullPointerException scenarios.'],
               ['Practice all String methods from the AP® CS A Quick Reference.',
                'Write code to extract a substring and find its index in a larger String.'],
               [('What does "hello".substring(1,3) return?', ['substring(startInclusive, endExclusive)', 'Characters at index 1 and 2: "el"', 'Index 0 is "h", index 3 is "l" (excluded)', 'Returns: "el"']),
                ('How do you correctly compare two Strings s1 and s2 for equality?', ['Use s1.equals(s2)', '== tests if they are the same object in memory, not same content', 'On the AP® exam == on Strings almost always gives wrong answer', 'Correct: if (s1.equals(s2))']),
                ('What does "abcde".indexOf("cd") return?', ['"cd" starts at index 2', 'indexOf returns the starting index of the first occurrence', 'Returns 2', 'Returns -1 if not found']),
                ('What is the length of "AP® CSA"?', ['length() counts characters including spaces', '"AP® CSA" has 6 characters: A P [space] C S A', 'Returns 6', 'Indices run 0 through 5']),
                ('String s; System.out.println(s.length()); — what happens?', ['s was declared but not initialized → null', 'Calling a method on null throws NullPointerException', 'This is a runtime error, not a compile error', 'Fix: String s = "";'])],
               [('AP® CS A String Methods', 'Using length, substring, indexOf, equals', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Strings Java', 'String manipulation in Java', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Classes are blueprints; objects are instances created with new.',
                'Compare Strings with .equals(), never with ==.',
                'Strings are immutable; String methods return new values.']),

            _l('Math Class and Output',
               [_t('Math Class Static Methods', 'Math methods are static — called on the class, not an object. Key methods: Math.abs(x), Math.pow(base,exp), Math.sqrt(x), Math.random() → [0.0, 1.0). No import needed.', 'Math.random() returns a double in [0,1) — it never returns exactly 1.0. Scale by multiplying and casting: (int)(Math.random()*n) gives 0 to n-1.', 'Use Math methods in expressions; calculate random integer in a range.'),
                _t('System.out.print vs println', 'System.out.println(x) prints x then newline. System.out.print(x) prints x without newline. String concatenation with + converts other types to String automatically.', 'Concatenating an int and String can give unexpected results: "x=" + 2+3 → "x=23" not "x=5". Use parentheses: "x=" + (2+3).', 'Trace output of print/println sequences; predict output of concatenation expressions.'),
                _t('Final Variables and Constants', 'Declare a constant with final: final double PI = 3.14159; After initialization, a final variable cannot be reassigned. Convention: ALL_CAPS names for constants.', 'final prevents reassignment but does not make referenced objects immutable — it only prevents the variable from pointing to a new object.', 'Identify final variables; explain why constants improve readability and safety.')],
               [('Math.random()', 'Returns random double in [0.0, 1.0); multiply and cast to get integer range'),
                ('Math.pow(a,b)', 'Returns a^b as a double; e.g., Math.pow(2,10) → 1024.0'),
                ('Math.sqrt(x)', 'Returns square root of x as a double'),
                ('System.out.println', 'Prints the argument then moves to next line'),
                ('final', 'Modifier that prevents reassignment of a variable after initialization')],
               ['Use Math class static methods in arithmetic expressions.',
                'Trace output of print and println statements including concatenation.',
                'Declare and use final (constant) variables.'],
               ['MCQ: predict output of a println with mixed concatenation.',
                'FRQ: use Math.random() to generate a number in a specific range.',
                'MCQ: identify which statement correctly declares a constant.'],
               ['Practice generating random integers in different ranges.',
                'Trace output of multiple print/println calls.'],
               [('What does (int)(Math.random() * 6) + 1 produce?', ['Math.random() → [0.0, 1.0)', 'Multiply by 6 → [0.0, 6.0)', 'Cast to int → 0 through 5', 'Add 1 → 1 through 6 (simulates die roll)']),
                ('What is the output of: System.out.print("a"); System.out.println("b"); System.out.print("c");', ['print does not add newline; println does', 'Output: ab[newline]c', 'Printed on two lines: "ab" then "c" with cursor at end of "c"', 'Note: no newline after "c"']),
                ('What is the value of Math.pow(3, 4)?', ['Math.pow(3,4) = 3^4', '3×3×3×3 = 81', 'Returns 81.0 (double)', 'Cast to int if integer is needed: (int)Math.pow(3,4) → 81']),
                ('What is printed by: System.out.println("x=" + 2 + 3)?', ['"x=" + 2 → "x=2" (left-to-right, String concat)', '"x=2" + 3 → "x=23"', 'Addition happens left-to-right; first concatenation wins', 'Output: x=23 (not x=5)']),
                ('Why use final for constants?', ['Prevents accidental reassignment', 'Makes intent clear to readers of code', 'Compiler enforces the constraint', 'Convention: name in ALL_CAPS like MAX_SIZE'])],
               [('Math Class AP® CS A', 'Math.random, pow, sqrt, abs', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Java Output', 'print vs println and concatenation', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Math methods are static: call on class, not object.',
                'Math.random() → [0,1); scale with multiply and cast for integer range.',
                '"x="+2+3 → "x=23"; use ("x="+(2+3)) for "x=5".']),

            _l('Using Existing Classes and APIs',
               [_t('AP® CS A Quick Reference', 'The AP® exam provides a Quick Reference listing constructors and methods for String, Integer, Double, Math, List, and ArrayList. You must be able to read and apply method signatures from this reference.', 'You do not need to memorize exact method signatures — the exam provides them. But you must understand the parameter types and return types.', 'Read a method signature from the Quick Reference and use it correctly in code.'),
                _t('Wrapper Classes: Integer and Double', 'Integer and Double wrap primitives as objects. Key methods: Integer.MAX_VALUE, Integer.MIN_VALUE, Integer.parseInt(s), Double.parseDouble(s). Autoboxing converts int ↔ Integer automatically.', 'Integer.MAX_VALUE is the largest int (2,147,483,647) — exceeding it causes overflow, silently wrapping to negative. AP® MCQ sometimes tests this.', 'Use Integer and Double static methods; explain autoboxing.'),
                _t('Reading Preconditions and Postconditions', 'AP® FRQ often specifies preconditions (assumptions you can make about input) and postconditions (what the method must guarantee). You must write code that satisfies postconditions assuming preconditions hold.', 'Do NOT add extra validation code unless the FRQ requires it — if a precondition guarantees input is valid, test for it anyway wastes time and can confuse graders.', 'Write a method that meets a given postcondition; use preconditions to simplify code.')],
               [('API', 'Application Programming Interface; the set of constructors and methods a class provides'),
                ('Integer.parseInt(s)', 'Converts String s to an int; throws NumberFormatException if s is not numeric'),
                ('autoboxing', 'Automatic conversion between primitive int and Integer object by Java compiler'),
                ('precondition', 'An assumption guaranteed true before a method executes; stated in documentation'),
                ('postcondition', 'A guarantee about what a method produces or changes; defines correct behavior')],
               ['Read and apply method signatures from the AP® CS A Quick Reference.',
                'Use Integer.parseInt and Double.parseDouble to convert Strings.',
                'Write methods whose behavior satisfies stated pre- and postconditions.'],
               ['FRQ: write a method body that satisfies a given postcondition.',
                'MCQ: trace code that uses a method given only its signature.',
                'MCQ: identify the effect of Integer.MAX_VALUE overflow.'],
               ['Read all entries in the AP® CS A Quick Reference and practice calling each method.',
                'Write small methods with precondition/postcondition comments.'],
               [('What does Integer.parseInt("42") return?', ['Converts String "42" to int 42', 'Return type is int', 'Throws NumberFormatException if the String is not a valid integer', 'Example use: reading integer input stored as String']),
                ('What is Integer.MAX_VALUE + 1?', ['Integer.MAX_VALUE = 2,147,483,647', 'Adding 1 causes integer overflow', 'Result wraps to Integer.MIN_VALUE = -2,147,483,648', 'AP® CS A sometimes tests overflow behavior']),
                ('Explain autoboxing with an example.', ['Java automatically converts int to Integer when needed', 'Example: Integer x = 5; // autoboxes 5 (int) to Integer', 'Reverse (unboxing): int y = x; // unboxes Integer to int', 'Useful when storing ints in an ArrayList<Integer>']),
                ('What is the return type of Math.sqrt?', ['Math.sqrt returns double', 'Signature: public static double sqrt(double a)', 'Even if input is an int, result is double: Math.sqrt(4) → 2.0', 'Cast if int needed: (int)Math.sqrt(16) → 4']),
                ('A method has precondition: n >= 0. Can you assume n is never negative inside the method?', ['Yes — preconditions are guaranteed by the caller', 'You do not need to check n < 0 inside the method', 'Writing code that handles n < 0 is not wrong but is unnecessary', 'AP® FRQ: rely on preconditions to simplify your solution'])],
               [('AP® CS A Quick Reference Guide', 'Overview of all tested API methods', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Integer Wrapper', 'Integer class and autoboxing', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['The AP® exam provides a Quick Reference — learn to read method signatures.',
                'Integer.parseInt converts String to int; autoboxing converts int ↔ Integer.',
                'Rely on preconditions; write code satisfying postconditions.'])
        ],
        'unit_qs': [
            ('What is the output of: int a = 5; int b = 2; System.out.println(a/b + " " + a%b);', ['a/b is integer division: 5/2 = 2', 'a%b is remainder: 5%2 = 1', 'String concatenation: "2 1"', 'Output: 2 1']),
            ('Explain why "hello".substring(0,3) returns "hel" and not "hell".', ['substring(start, end) is start-inclusive, end-exclusive', 'Indices 0,1,2 are included; index 3 is excluded', '"hel" has characters at positions 0, 1, 2', 'This is the standard half-open interval convention in Java']),
            ('How would you generate a random integer between 10 and 20 inclusive?', ['Need range of 11 values (10 through 20)', '(int)(Math.random() * 11) gives 0..10', 'Add 10: (int)(Math.random() * 11) + 10', 'Gives values 10, 11, ..., 20 uniformly']),
            ('Declare a constant for the number of players (4) in a game. Write the declaration.', ['Use final modifier', 'Convention: ALL_CAPS name', 'final int NUM_PLAYERS = 4;', 'Compiler will reject any reassignment to NUM_PLAYERS']),
            ('What error occurs at runtime if you call a method on a null reference? How do you prevent it?', ['NullPointerException (NPE) at runtime', 'Occurs when a reference variable is null and you use dot notation', 'Prevent by initializing the variable before use', 'Or check: if (obj != null) before calling methods']),
            ('What does "Computer".indexOf("put") return?', ['"put" starts at index 3 in "Computer"', 'C=0 o=1 m=2 p=3 u=4 t=5 e=6 r=7', 'Returns 3', 'Returns -1 if the substring is not found']),
            ('Trace: int x = 10; x = x + 3; x = x * 2; System.out.println(x);', ['Start: x = 10', 'After x = x+3: x = 13', 'After x = x*2: x = 26', 'Output: 26']),
            ('What is the difference between System.out.print and System.out.println?', ['print outputs text without a newline at the end', 'println outputs text and then moves to the next line', 'Multiple print calls produce output on same line', 'println is equivalent to print + "\\n"']),
            ('What does Math.abs(-7.5) return?', ['Math.abs returns the absolute value', 'abs(-7.5) = 7.5', 'Return type is double (matches parameter type)', 'Math.abs(int) returns int; Math.abs(double) returns double']),
            ('A method requires precondition: index >= 0 && index < array.length. Should the method body check index bounds again?', ['No — the precondition guarantees the index is valid', 'Caller is responsible for satisfying preconditions', 'You may include a check for safety but it is not required by AP® FRQ', 'Relying on preconditions simplifies code'])
        ]
    },
    {
        'num': 2,
        'title': 'Selection and Iteration',
        'file': 'ap-computer-science-a-2-unit-2-selection-and-iteration.html',
        'desc': 'Control flow using boolean expressions, if/else statements, and for/while loops in Java.',
        'gateway': [
            'How do boolean expressions combine conditions in Java?',
            'When does an if-else chain execute? When does nested if differ?',
            'How does a for loop differ from a while loop?',
            'How do you trace the execution of nested loops?',
        ],
        'lessons': [
            _l('Boolean Expressions and Comparisons',
               [_t('Relational Operators', 'Java relational operators: == != < > <= >= produce boolean values. For primitives, == compares values. For objects (Strings), == compares references; use .equals() for content.', 'Using == to compare Strings tests whether they are the exact same object, not whether they have the same characters.', 'Evaluate relational expressions; identify correct operator for primitives vs objects.'),
                _t('Logical Operators', 'Logical operators: && (AND), || (OR), ! (NOT). Short-circuit evaluation: A && B — if A is false, B is not evaluated. A || B — if A is true, B is not evaluated.', 'Short-circuit evaluation prevents NullPointerExceptions: checking (obj != null && obj.method()) is safe; reversing the order would crash if obj is null.', 'Evaluate compound boolean expressions; explain short-circuit evaluation.'),
                _t('Operator Precedence', '! has higher precedence than && which has higher precedence than ||. Use parentheses to clarify complex expressions. De Morgan\'s Laws: !(A && B) = !A || !B; !(A || B) = !A && !B.', 'Forgetting precedence in compound conditions is a common source of logic errors. Always use parentheses in complex boolean expressions on the AP® exam.', 'Apply De Morgan\'s Laws to rewrite conditions; evaluate precedence in compound expressions.')],
               [('boolean', 'Primitive type holding true or false; result of relational and logical expressions'),
                ('&&', 'Logical AND: true only if both operands are true; short-circuits on false left'),
                ('||', 'Logical OR: true if at least one operand is true; short-circuits on true left'),
                ('!', 'Logical NOT: flips true to false and vice versa; highest logical precedence'),
                ('De Morgan\'s Laws', '!(A&&B) = !A||!B; !(A||B) = !A&&!B; useful for simplifying conditions')],
               ['Evaluate relational expressions for both primitives and objects.',
                'Apply && and || with short-circuit evaluation.',
                'Use De Morgan\'s Laws to rewrite boolean conditions.'],
               ['MCQ: evaluate a compound boolean expression step-by-step.',
                'FRQ: write a condition that combines multiple constraints.',
                'MCQ: identify the equivalent of a negated compound condition using De Morgan\'s Laws.'],
               ['Evaluate truth tables for &&, ||, ! with different inputs.',
                'Rewrite negated conditions using De Morgan\'s Laws.'],
               [('Evaluate: (3 > 2) && (5 == 4)', ['(3 > 2) is true', '(5 == 4) is false', 'true && false = false', 'Both sides must be true for && to return true']),
                ('Evaluate: (3 > 2) || (5 == 4)', ['(3 > 2) is true', 'Short-circuit: left is true → result is true immediately', '(5 == 4) is not evaluated', 'Returns true']),
                ('Apply De Morgan\'s Law to: !(x > 0 && y > 0)', ['!(A && B) = !A || !B', '= !(x > 0) || !(y > 0)', '= (x <= 0) || (y <= 0)', 'This is true when at least one of x or y is not positive']),
                ('Is String comparison with == reliable?', ['No — == compares references (memory addresses) for objects', 'Two Strings with same characters may not be the same object', 'Always use .equals() for String content comparison', 'AP® exam frequently tests this distinction']),
                ('What happens in: if (list != null && list.size() > 0) due to short-circuit?', ['Left side evaluated first: list != null', 'If list is null, the right side is NOT evaluated', 'Prevents NullPointerException when calling list.size()', 'This is the safe order; reversing would crash on null list'])],
               [('Boolean Expressions AP® CS A', 'Relational and logical operators', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Logical Operators', 'AND, OR, NOT and truth tables', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['== compares references for objects; use .equals() for Strings.',
                'Short-circuit: && stops on first false; || stops on first true.',
                'De Morgan\'s: !(A&&B) = !A||!B; !(A||B) = !A&&!B.']),

            _l('If and If-Else Statements',
               [_t('If, Else-If, Else', 'if (cond) {body} else if (cond2) {body2} else {body3}. Braces recommended even for single statements. Only one branch executes per run. Else catches everything not matched above.', 'Omitting braces in if-else chains makes indentation-based reasoning dangerous — Java ignores indentation.', 'Trace which branch executes for given inputs; write conditions for range-based classification.'),
                _t('Nested If Statements', 'An if statement inside another if. Useful when a second decision depends on the first. May be rewritten as compound condition: if (A && B) {...} instead of nested ifs.', 'The "dangling else" problem: else attaches to the nearest unmatched if. Always use braces to prevent this ambiguity.', 'Trace nested if-else behavior; rewrite as flat if-else chain when possible.'),
                _t('Common If-Else Patterns', 'Testing ranges: if (x < 0) ... else if (x == 0) ... else ... Checking divisibility: if (n%2 == 0). Assigning based on condition can use if-else or the ternary operator: type var = (cond) ? a : b;', 'Range tests must be mutually exclusive and exhaustive. Overlapping conditions cause logic bugs.', 'Write range-based if-else for grading or classification; use modulo for divisibility.')],
               [('if', 'Executes a block only when the condition is true'),
                ('else if', 'Alternative condition checked only when previous conditions were false'),
                ('else', 'Executes when all preceding conditions were false; no condition needed'),
                ('dangling else', 'Ambiguity when else matches nearest unmatched if — braces eliminate this'),
                ('ternary operator', 'type var = (cond) ? valueIfTrue : valueIfFalse; compact if-else for assignment')],
               ['Write if/else-if/else chains for range-based classification.',
                'Trace nested if-else to determine which block executes.',
                'Identify and fix the dangling else problem.'],
               ['FRQ: write a method that returns a String based on a numeric input range.',
                'MCQ: trace nested if-else to find the value printed.',
                'MCQ: identify the output of an if-else chain with a specific input.'],
               ['Write a grade calculator using if-else-if for score ranges.',
                'Trace a nested if-else with truth tables for inputs.'],
               [('Write code to print "positive", "negative", or "zero" for int x.', ['Use if-else-if chain', 'if (x > 0) print "positive"', 'else if (x < 0) print "negative"', 'else print "zero"']),
                ('What is the output of: int n=7; if(n>5) if(n>10) print("A"); else print("B");', ['Dangling else attaches to nearest unmatched if: if(n>10)', 'n=7: n>5 is true; n>10 is false → else branch → "B"', 'Output: B', 'Add braces to make intent explicit']),
                ('Write a ternary expression to assign "pass" or "fail" based on score >= 60.', ['String result = (score >= 60) ? "pass" : "fail";', 'Ternary: (condition) ? trueValue : falseValue', 'Equivalent to if (score>=60) result="pass"; else result="fail";', 'More concise for simple assignments']),
                ('How do you check if an integer n is divisible by both 3 and 5?', ['n%3 == 0 → divisible by 3', 'n%5 == 0 → divisible by 5', 'Combine: n%3==0 && n%5==0', 'Or equivalently n%15==0']),
                ('Explain why braces are recommended even for single-statement if bodies.', ['Without braces, only the first statement is part of the if', 'Adding a second statement later would not be in the if body', 'Indentation is for human readers; Java ignores it', 'Braces prevent bugs when code is modified later'])],
               [('If-Else AP® CS A', 'Writing and tracing conditional statements', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Conditionals Java', 'if, else-if, else patterns', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Only one branch of if-else-if-else executes.',
                'else attaches to nearest unmatched if — use braces to prevent ambiguity.',
                'Ternary: (cond) ? a : b; is compact if-else for assignment.']),

            _l('For and While Loops',
               [_t('For Loops', 'for (init; condition; update) {body}. Executes init once, checks condition, runs body, runs update, repeats. Loop variable scope limited to loop unless declared outside. Common: for (int i=0; i<n; i++).', 'Off-by-one errors: i<n iterates n times (0 to n-1); i<=n iterates n+1 times. AP® FRQ frequently requires choosing the correct boundary.', 'Trace a for loop for given start/end values; count iterations; identify off-by-one errors.'),
                _t('While Loops', 'while (condition) {body}. Checks condition before each iteration. If condition is initially false, body never executes. Use when the number of iterations is not known in advance.', 'An infinite loop results if the loop variable is never updated or the condition can never become false. Always ensure the loop makes progress toward termination.', 'Write while loops for input validation and search patterns; trace execution.'),
                _t('do-while and Loop Comparison', 'do {body} while (condition); executes body at least once. Less common in AP® CS A. Choosing for vs while: for when count is known; while when condition-driven; do-while for at-least-once scenarios.', 'AP® CS A rarely tests do-while directly, but knowing it prevents confusion when reading code that contains one.', 'Choose the correct loop type for a given scenario; convert between for and while loops.')],
               [('for loop', 'Loop with init, condition, update in header; best when iteration count is known'),
                ('while loop', 'Loop that repeats while condition is true; best for condition-driven iteration'),
                ('do-while', 'Loop that always executes body at least once before checking condition'),
                ('off-by-one error', 'Using < vs <= incorrectly, causing one too many or too few iterations'),
                ('infinite loop', 'Loop whose condition never becomes false; program hangs without terminating')],
               ['Write for loops that iterate n times with correct boundaries.',
                'Write while loops for condition-driven scenarios.',
                'Identify and fix off-by-one errors in loop boundaries.'],
               ['FRQ: write a loop to traverse an array or compute a sum.',
                'MCQ: count the number of iterations of a given loop.',
                'MCQ: trace a while loop to find the output.'],
               ['Count iterations and trace values for various loop bounds.',
                'Convert a for loop to an equivalent while loop.'],
               [('How many times does this loop execute: for(int i=1; i<=5; i++)?', ['Condition: i<=5; i goes 1,2,3,4,5', 'Executes 5 times', 'Last iteration: i=5; after update i=6; condition false', 'Use <=n when you want values 1 through n']),
                ('Write a while loop that sums integers from 1 to 100.', ['int sum = 0; int i = 1;', 'while (i <= 100) { sum += i; i++; }', 'Or equivalently use a for loop: cleaner when count known', 'Both produce sum = 5050']),
                ('What is wrong with: for(int i=0; i<10; i++) { ... } if you want to process 10 items?', ['for(int i=0; i<10; i++) is CORRECT for 10 items', 'i goes 0,1,...,9 → 10 iterations', 'Changing to i<=10 would give 11 iterations (off-by-one)', 'Use i < length for array traversal']),
                ('Trace: int x=0; while(x<3){x+=2;} System.out.println(x);', ['Start x=0; condition 0<3 true; x+=2 → x=2', 'Condition 2<3 true; x+=2 → x=4', 'Condition 4<3 false; exit loop', 'Output: 4']),
                ('When should you use a while loop instead of a for loop?', ['Use while when the number of iterations is not known in advance', 'Examples: reading until sentinel value, searching until found', 'For loops require knowing init and update structure', 'While is more flexible for condition-driven termination'])],
               [('For and While Loops AP® CS A', 'Loop syntax and tracing', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Loops Java', 'for, while, and do-while loops', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['for(int i=0; i<n; i++) iterates n times; i<n not i<=n.',
                'while executes while condition is true; may run zero times.',
                'Off-by-one: check < vs <= carefully for boundaries.']),

            _l('Nested Loops and String Traversal',
               [_t('Nested Loops', 'A loop inside another loop. Outer loop runs n times; inner loop runs m times per outer iteration → total n×m iterations. Used for 2D patterns, comparing all pairs, and matrix traversal.', 'Forgetting that the inner loop counter resets each time the outer loop runs is a common tracing error.', 'Trace nested loops to predict output; count total iterations; write nested loops for rectangular patterns.'),
                _t('String Traversal with Loops', 'Use a for loop with i from 0 to str.length()-1: char c = str.charAt(i) or str.substring(i,i+1). Process each character individually — search, count, or transform.', 'charAt returns a char (primitive); substring(i,i+1) returns a String of length 1. Comparing chars: use == for char; use .equals() for String.', 'Write a loop to count occurrences of a character in a String; trace character extraction.'),
                _t('Loop Invariants and Tracing', 'A loop invariant is a condition that holds before and after each iteration. Useful for reasoning about correctness. Track accumulator variables carefully when tracing.', 'When tracing, track ALL variables simultaneously through each iteration — focusing only on the loop counter while ignoring the accumulator causes incorrect traces.', 'Trace a loop with accumulator to find the final value; identify what a loop computes.')],
               [('nested loop', 'A loop inside another loop; inner loop completes all iterations for each outer iteration'),
                ('charAt(i)', 'Returns the char at index i of a String; char is a primitive'),
                ('accumulator', 'Variable that collects a running total or result across loop iterations'),
                ('loop invariant', 'A condition true before and after every iteration; helps verify correctness'),
                ('char', 'Primitive type holding a single character; compared with == not .equals()')],
               ['Trace nested loops to count iterations and predict output.',
                'Write a loop to traverse each character of a String.',
                'Identify what an accumulator computes after a loop completes.'],
               ['FRQ: write a method that counts or extracts characters from a String.',
                'MCQ: trace nested loops to find output pattern.',
                'MCQ: identify the number of total iterations in a nested loop.'],
               ['Trace a nested loop that prints a triangle pattern.',
                'Write a method that reverses a String using a loop.'],
               [('How many times is "hi" printed: for(int i=0;i<3;i++) for(int j=0;j<4;j++) print("hi");?', ['Outer loop: 3 iterations (i=0,1,2)', 'Inner loop: 4 iterations each time', 'Total: 3×4 = 12', '"hi" is printed 12 times']),
                ('Write a loop that counts how many times the char \'a\' appears in String s.', ['int count = 0;', 'for (int i=0; i<s.length(); i++) {', '  if (s.charAt(i) == \'a\') count++;', '} return count;']),
                ('Trace: int sum=0; for(int i=1;i<=4;i++) sum+=i; System.out.println(sum);', ['i=1: sum=0+1=1; i=2: sum=1+2=3', 'i=3: sum=3+3=6; i=4: sum=6+4=10', 'Condition i<=4 still true; i becomes 5; condition false', 'Output: 10']),
                ('What is the output of: for(int i=0;i<3;i++) { for(int j=i;j<3;j++) System.out.print(j); System.out.println(); }', ['i=0: j=0,1,2 → prints "012"', 'i=1: j=1,2 → prints "12"', 'i=2: j=2 → prints "2"', 'Three lines: 012, 12, 2']),
                ('What does str.charAt(i) return vs str.substring(i,i+1)?', ['charAt(i) returns a char (primitive): char c = str.charAt(i)', 'substring(i,i+1) returns a String of length 1', 'char compared with ==; String compared with .equals()', 'AP® FRQ usually uses charAt; be aware of the type difference'])],
               [('Nested Loops AP® CS A', 'Tracing and writing nested loops', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy String Traversal', 'Looping through String characters', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Nested loops: outer×inner total iterations; inner counter resets each outer pass.',
                'charAt(i) returns char (primitive); compare with ==.',
                'Track accumulators carefully when tracing loops.'])
        ],
        'unit_qs': [
            ('What does the expression (x >= 0) && (x <= 10) test?', ['Tests if x is in the range [0, 10] inclusive', '&& requires both conditions true', 'True for x = 0, 5, 10; false for x = -1 or 11', 'Equivalent to the closed interval 0 ≤ x ≤ 10']),
            ('Trace: int n=8; if(n%2==0) if(n>5) System.out.println("A"); else System.out.println("B"); else System.out.println("C");', ['n=8: n%2==0 is true; enter outer if', 'n>5 is true; execute inner if body: print "A"', 'Output: A', 'Both conditions must be true to reach "A"']),
            ('How many iterations does for(int i=2; i<10; i+=2) execute?', ['i goes 2, 4, 6, 8 (then 10 fails condition)', '4 iterations', 'Step size is 2 instead of 1', 'Count = (10-2)/2 = 4']),
            ('Write a while loop that halves a value x until x < 1.', ['int x = 64; (example starting value)', 'while (x >= 1) { x = x/2; }', 'Or: double x = ...; while (x >= 1.0) { x /= 2.0; }', 'Loop terminates when x < 1']),
            ('What is the output of this nested loop: for(int i=1;i<=3;i++) { for(int j=1;j<=i;j++) System.out.print("*"); System.out.println(); }', ['i=1: print "*" then newline → *', 'i=2: print "**" then newline → **', 'i=3: print "***" then newline → ***', 'Triangle pattern with increasing rows']),
            ('Explain the difference between = and == in Java.', ['= is assignment: stores a value in a variable', '== is equality comparison: evaluates to boolean', 'x = 5 sets x to 5; x == 5 tests if x is 5', 'Confusing them in conditions is a compile error for primitives but silent bug for booleans']),
            ('Write a for loop that prints even numbers from 2 to 20.', ['for (int i=2; i<=20; i+=2)', 'System.out.println(i);', 'Or: for(int i=2;i<=20;i++) if(i%2==0) println(i)', 'First method is more efficient']),
            ('What does !(a > 5 || b < 3) simplify to by De Morgan\'s Laws?', ['!(a>5 || b<3) = !(a>5) && !(b<3)', '= (a<=5) && (b>=3)', 'True only when a is at most 5 AND b is at least 3', 'De Morgan: !(A||B) = !A && !B']),
            ('Trace: String s="hello"; int cnt=0; for(int i=0;i<s.length();i++) if(s.charAt(i)==\'l\') cnt++; System.out.println(cnt);', ['"hello" has l at index 2 and 3', 'Loop counts chars equal to \'l\'', 'cnt increments twice', 'Output: 2']),
            ('When is a while loop preferred over a for loop? Give an example.', ['While is preferred when the number of iterations is unknown', 'Example: reading user input until a sentinel like -1', 'int x = scanner.nextInt(); while(x != -1) { process(x); x = scanner.nextInt(); }', 'For loop suits counting; while suits event-driven termination'])
        ]
    },
    {
        'num': 3,
        'title': 'Class Creation',
        'file': 'ap-computer-science-a-3-unit-3-class-creation.html',
        'desc': 'Designing classes with instance variables, constructors, accessors, mutators, and method implementation.',
        'gateway': [
            'What are instance variables and how do they differ from local variables?',
            'What does a constructor do and how does it differ from a regular method?',
            'What is encapsulation and why do we use private fields with public getters/setters?',
            'What is the difference between static and instance members of a class?',
        ],
        'lessons': [
            _l('Designing a Class',
               [_t('Class Structure', 'A class defines a type with fields (data) and methods (behavior). Fields are declared at class scope; local variables exist only within methods. Fields have default values (0, false, null) if not initialized.', 'Instance variables belong to the object; local variables belong to the method. They have separate scopes and lifetimes.', 'Identify which variables are instance vs local; design a class for a given real-world entity.'),
                _t('Writing a Basic Class', 'class ClassName { fields; constructors; methods; }. By convention class names are UpperCamelCase. Separate the class definition from its use (test in another class).', 'AP® FRQ often gives you a partial class and asks you to add a method. Read the existing fields and methods first to understand the design before writing.', 'Add a method to a given class skeleton; identify the class\'s fields and their types.'),
                _t('Object State and Behavior', 'State = values of instance variables at a moment in time. Behavior = what methods do. An object\'s state can change through mutator methods; behavior is defined by the class.', 'Two objects of the same class are independent — changing one does not change the other unless explicitly connected.', 'Describe the state of an object after a series of method calls; trace state changes.')],
               [('instance variable', 'Variable declared at class scope; each object has its own copy; persists for the object\'s lifetime'),
                ('local variable', 'Variable declared inside a method; exists only during that method\'s execution'),
                ('class', 'Blueprint defining fields and methods; instantiated to create objects'),
                ('state', 'Values of an object\'s instance variables at a point in time'),
                ('behavior', 'What an object can do; defined by its methods')],
               ['Design a class with appropriate fields for a given problem.',
                'Distinguish instance variables from local variables by scope.',
                'Describe an object\'s state after a sequence of method calls.'],
               ['FRQ: write a class skeleton with fields and method signatures for a described problem.',
                'MCQ: trace state changes of an object through method calls.',
                'FRQ: add a method to an existing class using its fields.'],
               ['Design a Student class with fields for name, grade, and GPA.',
                'Trace object state through a series of method calls.'],
               [('What is the default value of an int instance variable?', ['Uninitialized instance variables get default values', 'int defaults to 0; double to 0.0; boolean to false; reference to null', 'Local variables do NOT get defaults — compiler error if used uninitialized', 'Best practice: explicitly initialize fields in the constructor']),
                ('Two BankAccount objects a and b are created. Does changing a\'s balance affect b?', ['No — each object has independent instance variables', 'a and b each have their own copy of the balance field', 'Changing a.balance only affects object a', 'Objects are independent unless explicitly sharing a reference']),
                ('What is the purpose of separating a class definition from a test class?', ['Separation of concerns: class defines type; test class uses it', 'Allows testing without modifying the class itself', 'Reflects real-world practice of reusable class libraries', 'AP® FRQ often presents a class to use/extend without changing its core']),
                ('List the fields you would include in a Circle class.', ['double radius; — the essential field', 'Possibly double x, y; for center position', 'Methods would use Math.PI * radius * radius for area', 'Keep fields minimal: store what changes; derive what you can']),
                ('Why should instance variable names differ from local variable names?', ['Shadowing: a local with same name hides the instance variable', 'Use this.field = field; in constructor to resolve shadowing', 'Better: use different names to avoid ambiguity', 'AP® FRQ graders look for correct field assignment in constructors'])],
               [('Designing Classes AP® CS A', 'Instance variables, state, behavior', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Classes Java', 'Class structure and object creation', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Fields are instance variables; each object gets its own copy.',
                'Default values: int=0, boolean=false, reference=null.',
                'Objects are independent — changing one never changes another.']),

            _l('Constructors',
               [_t('Constructor Syntax', 'A constructor has the same name as the class and no return type. Called with new: ClassName obj = new ClassName(args). Used to initialize fields.', 'A constructor is NOT a method — it has no return type, not even void. Writing void before a constructor name creates an ordinary method instead.', 'Write a constructor that initializes all fields; identify constructor vs method.'),
                _t('Constructor Overloading', 'Multiple constructors can exist with different parameter lists. The default (no-arg) constructor is provided only if NO constructors are defined; once you write one, the default is gone.', 'If you define a parameterized constructor without a no-arg constructor, code using new ClassName() will fail to compile.', 'Write overloaded constructors; identify which constructor matches a given new call.'),
                _t('this Keyword', 'this refers to the current object. Used to resolve shadowing: this.name = name; Also used to call another constructor: this(args); must be the first statement.', 'this() can only be used as the first statement in a constructor. It delegates to another overloaded constructor of the same class.', 'Use this to disambiguate field names; use this() for constructor chaining.')],
               [('constructor', 'Special method with class name and no return type; initializes object fields'),
                ('overloading', 'Defining multiple methods/constructors with the same name but different parameter lists'),
                ('default constructor', 'No-arg constructor provided automatically only if no constructors are defined'),
                ('this', 'Reference to the current object; resolves field-parameter shadowing'),
                ('constructor chaining', 'Calling this(args) from a constructor to delegate to another constructor')],
               ['Write constructors that initialize all instance variables.',
                'Explain why the default no-arg constructor is lost when you define any constructor.',
                'Use this to assign shadowed fields correctly.'],
               ['FRQ: write two constructors — a full parameterized one and a no-arg default.',
                'MCQ: identify which constructor is called by a given new expression.',
                'MCQ: identify a constructor error (missing void? wrong name?).'],
               ['Write a BankAccount class with two constructors: one sets balance to 0; one accepts initial balance.',
                'Practice constructor chaining with this().'],
               [('Write a Dog constructor that sets name and breed.', ['public Dog(String name, String breed) {', '  this.name = name;', '  this.breed = breed;', '}', 'this.name refers to field; name refers to parameter']),
                ('What happens if you write: public void Dog(String name) {...}?', ['void makes this a regular method named Dog, not a constructor', 'It will compile, but new Dog("Fido") will use the default (empty) constructor', 'The fields won\'t be initialized by this "constructor"', 'Remove void to make it a real constructor']),
                ('A class has constructor: public Cat(String name). Can you call new Cat() elsewhere?', ['No — defining any constructor removes the automatic no-arg constructor', 'new Cat() would cause a compile error', 'Solution: add a no-arg constructor explicitly', 'Or use this("DefaultCat") to delegate']),
                ('Why use this.field = param instead of field = param when names match?', ['Parameter "name" shadows instance variable "name"', 'field = param assigns the parameter to itself — no effect on the field!', 'this.field = param correctly assigns parameter to the instance variable', 'Always use this.x = x when constructor parameter matches field name']),
                ('What restriction applies to this() constructor call?', ['this(args) must be the FIRST statement in a constructor', 'Cannot appear after any other statement', 'Used to call another overloaded constructor (constructor chaining)', 'Allows one constructor to reuse another\'s initialization logic'])],
               [('Constructors AP® CS A', 'Constructor syntax, overloading, and this', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Constructors Java', 'Writing and calling constructors', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Constructor: same name as class, no return type.',
                'Defining any constructor removes the default no-arg constructor.',
                'this.field = param when parameter name matches field name.']),

            _l('Encapsulation: Accessors and Mutators',
               [_t('Private Fields', 'Declaring fields private prevents direct access from outside the class. This is encapsulation — hiding internal state. Public fields can be changed by anyone; private fields can only be changed through methods you control.', 'On the AP® exam, all instance variables should be declared private. Making them public is a design flaw (loses encapsulation).', 'Identify which fields should be private; explain why encapsulation prevents invalid state.'),
                _t('Accessor (Getter) Methods', 'An accessor returns the value of a private field without allowing modification. Convention: getName(), getBalance(), isComplete(). Return type matches the field type.', 'AP® FRQ often requires you to write a getter. The method must have the correct return type and use return, not print.', 'Write accessor methods for all private fields; return the correct type.'),
                _t('Mutator (Setter) Methods', 'A mutator changes a private field\'s value, often with validation. Convention: setName(String name), deposit(double amount). Return type is usually void.', 'A setter without validation is little better than a public field. AP® FRQ sometimes requires adding validation (e.g., if amount > 0 before depositing).', 'Write mutators with simple validation; explain how they protect object invariants.')],
               [('encapsulation', 'Hiding fields as private and exposing controlled access through methods'),
                ('accessor', 'Method that returns the value of a private field; getter; return type matches field'),
                ('mutator', 'Method that changes a private field, often with validation; setter; usually void'),
                ('private', 'Access modifier restricting field/method to within the class only'),
                ('public', 'Access modifier allowing access from any other class')],
               ['Declare all instance variables private.',
                'Write accessor (getter) methods that return field values.',
                'Write mutator (setter) methods that update fields with validation.'],
               ['FRQ: write getters and setters for a given class skeleton.',
                'MCQ: identify an encapsulation violation.',
                'FRQ: add a mutator that validates input before updating a field.'],
               ['Add getters and setters to a BankAccount class.',
                'Explain why a public field can lead to invalid state.'],
               [('Write a getter for a private double price field.', ['public double getPrice() {', '  return price;', '}', 'Return type matches field type; method name starts with get']),
                ('Write a mutator that only sets age if it is >= 0.', ['public void setAge(int age) {', '  if (age >= 0) {', '    this.age = age;', '  }', '}', 'Validation prevents negative age from being stored']),
                ('Why should instance variables be private rather than public?', ['Public fields can be set to any value by any code — no validation', 'Private fields can only be changed through controlled mutator methods', 'Encapsulation protects object invariants (e.g., age >= 0)', 'AP® exam always expects private fields; public fields lose encapsulation credit']),
                ('What is the return type of a getter for a boolean field named active?', ['boolean — matches the field type', 'Getter: public boolean isActive() { return active; }', 'Convention: "is" prefix for boolean getters instead of "get"', 'isActive() is more readable than getActive()']),
                ('A Person class has private String name. Write the full getter method.', ['public String getName() {', '  return name;', '}', 'One-line body: just return the field', 'Graders check: correct return type, correct field name, return keyword'])],
               [('Encapsulation AP® CS A', 'Private fields, getters, setters', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy OOP Java', 'Object-oriented design with encapsulation', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['All instance variables should be private.',
                'Accessors return field values; mutators change them with validation.',
                'Encapsulation protects invariants and hides implementation details.']),

            _l('Static Members and Method Design',
               [_t('Static vs Instance Members', 'static fields and methods belong to the class, not to any object. Called with ClassName.method(). Instance methods need an object. Math.sqrt() and Integer.MAX_VALUE are static. Use static for shared data or utilities.', 'Calling a static method on an object (obj.staticMethod()) compiles but is misleading — the call ignores the object. Call static methods on the class name.', 'Distinguish static from instance; call static methods correctly using the class name.'),
                _t('Writing Complete Methods', 'A method has: access modifier, return type (or void), name, parameters, and body. Return type must match what is returned. void methods may contain return; with no value to exit early.', 'Forgetting the return statement in a non-void method causes a compile error. Every path through the method must end in a return.', 'Write complete method implementations with correct return types; ensure all paths return a value.'),
                _t('toString and equals Methods', 'toString() returns a String representation of the object: @Override public String toString(). equals(Object other) checks content equality. Both inherited from Object but should be overridden.', 'Without overriding toString, printing an object shows a cryptic address like Dog@7a81197d — not useful for debugging or output.', 'Override toString to produce a readable representation; use it in output statements.')],
               [('static', 'Modifier making a field or method belong to the class, not a specific object'),
                ('instance method', 'Method requiring an object to be called; accesses instance variables'),
                ('static method', 'Method called on the class name; cannot access instance variables'),
                ('toString()', 'Returns a String representation of the object; called automatically in concatenation/println'),
                ('void', 'Return type for methods that produce no value; may use return; to exit early')],
               ['Write static utility methods and call them on the class name.',
                'Write complete methods with all paths returning the correct type.',
                'Override toString to produce meaningful output for an object.'],
               ['FRQ: write an instance method that uses fields and returns a computed value.',
                'MCQ: identify whether a method should be static or instance.',
                'FRQ: write a toString method for a given class.'],
               ['Add a static counter field to a class counting how many objects have been created.',
                'Write toString for a Point class: "Point(x, y)".'],
               [('A method computeArea() for a Rectangle class should be static or instance?', ['Instance — it needs the specific rectangle\'s width and height', 'If width and height are instance variables, the method must be non-static', 'Static methods cannot access instance variables', 'Rule: if the method uses fields, make it an instance method']),
                ('Write a toString for a Point class with fields int x, y.', ['@Override', 'public String toString() {', '  return "Point(" + x + ", " + y + ")";', '}', 'Concatenation builds the String; fields accessed directly since same class']),
                ('Every code path in a non-void method must do what?', ['Every path must end with a return statement returning the correct type', 'Missing return causes compile error: "missing return statement"', 'Example: if-else must have return in both branches', 'Use else return ... to ensure all paths covered']),
                ('Can a static method call instance methods?', ['No — static methods run without an object; instance methods need one', 'A static method cannot access instance variables or instance methods directly', 'It can if it has a reference to an object: MyClass obj = new MyClass(); obj.method();', 'AP® FRQ: static helper methods must not reference instance fields']),
                ('What does System.out.println(myDog) print if Dog has no toString?', ['Prints something like Dog@6d06d69c (class name + memory address)', 'Not useful for reading state', 'Override toString to print name, breed, etc.', 'Once overridden, println(myDog) calls your toString automatically'])],
               [('Static vs Instance AP® CS A', 'Static methods, fields, and toString', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Static Methods', 'Static vs instance in Java', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['static members belong to the class; call as ClassName.method().',
                'All non-void paths must return a value.',
                'Override toString for readable object printing.'])
        ],
        'unit_qs': [
            ('A Circle class has private double radius. Write the full class with constructor, getRadius, and area().', ['private double radius;', 'public Circle(double radius) { this.radius = radius; }', 'public double getRadius() { return radius; }', 'public double area() { return Math.PI * radius * radius; }']),
            ('Why should instance variables be declared private and not public?', ['Encapsulation: prevents arbitrary modification from outside the class', 'Public fields can be set to invalid values (e.g., negative radius)', 'Private fields are only changed through controlled methods', 'AP® CS A requires private fields for full encapsulation credit']),
            ('A class defines public Dog(String name). Can you call new Dog() elsewhere?', ['No — defining any constructor removes the default no-arg constructor', 'new Dog() causes a compile error', 'To allow no-arg construction, add: public Dog() { this.name = "Unknown"; }', 'Or use this("Unknown") to delegate to the parameterized constructor']),
            ('What is the difference between a constructor and a void method with the same name?', ['Constructor: no return type keyword; called with new to create objects', 'Method with void: has void keyword; not a constructor; called on existing objects', 'new Dog() calls the constructor; dog.Dog() would call the method', 'Confusing them compiles but does not initialize the object']),
            ('Write a BankAccount class with: private double balance, a constructor, getBalance, deposit(double) that adds only if amount>0, and withdraw(double) that deducts only if sufficient.', ['private double balance;', 'public BankAccount(double initialBalance) { this.balance = initialBalance; }', 'public double getBalance() { return balance; }', 'public void deposit(double amount) { if(amount>0) balance+=amount; }', 'public void withdraw(double amount) { if(amount>0 && amount<=balance) balance-=amount; }']),
            ('When is a method static vs instance? Give one example of each.', ['Static: no object needed; belongs to class; example: Math.sqrt()', 'Instance: needs an object; uses instance fields; example: circle.area()', 'Static declared with static keyword; instance methods implicitly have this', 'Use instance for behavior that depends on object state']),
            ('Write a toString method for a Student class with fields String name and int grade.', ['@Override', 'public String toString() {', '  return name + ", Grade: " + grade;', '}', 'Or any readable format; used when printing or concatenating the object']),
            ('What happens if you forget this.name = name in a constructor parameter named name?', ['name = name assigns the parameter to itself — the instance field is unchanged', 'Field retains its default value (null for String)', 'this.name refers to instance field; name alone refers to the parameter', 'Common FRQ mistake; graders check for this']),
            ('A method has signature: public int sumToN(int n). What must every path in the body include?', ['A return statement returning an int', 'If there is an if-else, both branches must return', 'If there is no return on some path, compile error: missing return', 'Example: return n*(n+1)/2; as a single-line formula']),
            ('What does @Override before toString() mean?', ['It tells the compiler this method is intended to override an inherited method', 'If the signature is wrong, compiler reports an error — helps catch typos', 'toString() is inherited from Object class', '@Override is optional but strongly recommended for clarity and safety'])
        ]
    },
    {
        'num': 4,
        'title': 'Data Collections',
        'file': 'ap-computer-science-a-4-unit-4-data-collections.html',
        'desc': 'Storing and processing collections of data using 1D arrays, ArrayList, and 2D arrays in Java.',
        'gateway': [
            'How do you declare, create, and initialize a 1D array in Java?',
            'When should you use an ArrayList instead of an array?',
            'How do you traverse an array with a for loop and an enhanced for loop?',
            'How are 2D arrays organized and traversed?',
        ],
        'lessons': [
            _l('1D Arrays',
               [_t('Array Declaration and Creation', 'int[] arr = new int[5]; creates an array of 5 ints (indices 0–4). Default values: 0 for numeric, false for boolean, null for objects. arr.length gives the number of elements.', 'Array indices go from 0 to arr.length-1. Accessing arr[arr.length] throws ArrayIndexOutOfBoundsException (AIOOBE).', 'Declare and create arrays; access elements by index; avoid AIOOBE.'),
                _t('Array Initialization and Access', 'Initialize inline: int[] scores = {90, 85, 78, 92}; Access: scores[0] = 90. Modify: scores[2] = 100; Arrays have fixed size — cannot grow.', 'Confusing array.length (field, no parentheses) with String.length() (method, needs parentheses) is a frequent error.', 'Initialize arrays with values; read and modify individual elements; use arr.length correctly.'),
                _t('Array Traversal', 'Traverse with for: for(int i=0; i<arr.length; i++). Enhanced for: for(int val : arr). Enhanced for is read-only — cannot modify elements or track index.', 'Use enhanced for when you only need to read values; use indexed for when you need the index or need to modify elements.', 'Write traversals to compute sum, max, min; identify when to use indexed vs enhanced for.')],
               [('array', 'Fixed-size collection of same-type elements stored contiguously; indexed 0 to length-1'),
                ('arr.length', 'Field (no parentheses) giving number of elements in the array'),
                ('ArrayIndexOutOfBoundsException', 'Runtime error when accessing index < 0 or >= arr.length'),
                ('enhanced for', 'for(type var : array) — iterates all elements; read-only; no index'),
                ('array initializer', '{val1, val2, val3} — creates and populates an array inline')],
               ['Declare, create, and initialize 1D arrays of primitive and reference types.',
                'Traverse arrays with indexed and enhanced for loops.',
                'Compute aggregate values (sum, max, count) using an array.'],
               ['FRQ: write a method that traverses an array to find the maximum.',
                'MCQ: trace array traversal to find the final state or output.',
                'MCQ: identify the AIOOBE scenario.'],
               ['Write a method that returns the sum and the average of an int array.',
                'Trace an array traversal that finds the first element greater than a threshold.'],
               [('What is the index of the last element in an array of length n?', ['Last index = n - 1', 'Indices run 0, 1, ..., n-1', 'arr[n] throws ArrayIndexOutOfBoundsException', 'Correct traversal: for(int i=0; i<arr.length; i++)']),
                ('Trace: int[] a = {2,4,6,8}; int s=0; for(int v:a) s+=v; System.out.println(s);', ['Sum: 2+4+6+8 = 20', 'Enhanced for reads each element into v', 'Accumulates s = 0+2+4+6+8 = 20', 'Output: 20']),
                ('Write a method that returns the maximum value in an int[] arr.', ['int max = arr[0];', 'for(int i=1; i<arr.length; i++) { if(arr[i] > max) max = arr[i]; }', 'return max;', 'Start from index 1; arr[0] is the initial comparison base']),
                ('What is the difference between arr.length and str.length()?', ['arr.length is a field — no parentheses; used for arrays', 'str.length() is a method — parentheses required; used for Strings', 'Confusing them is a compile error', 'Mnemonic: array is a primitive-like thing; String is an object']),
                ('What is int[] arr = new int[3]; followed by System.out.println(arr[1])?', ['new int[3] creates array with 3 elements', 'Default values for int array: all 0', 'arr[1] is 0 (default)', 'Output: 0'])],
               [('1D Arrays AP® CS A', 'Declaration, traversal, and aggregates', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Arrays Java', 'Arrays, traversal, and common patterns', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Array indices: 0 to length-1; arr[arr.length] throws AIOOBE.',
                'arr.length (field, no parens) vs str.length() (method, parens).',
                'Enhanced for is read-only; use indexed for to modify elements.']),

            _l('ArrayList',
               [_t('ArrayList vs Array', 'ArrayList<Type> is a resizable list from java.util. Key methods: add(E), remove(int), get(int), set(int,E), size(). Must import java.util.ArrayList; Requires wrapper types: ArrayList<Integer> not ArrayList<int>.', 'ArrayList size() is a method (parentheses); array length is a field (no parentheses). Mixing them up is a compile error.', 'Choose ArrayList when size varies; choose array when size is fixed or performance critical.'),
                _t('ArrayList Methods', 'add(E e): appends; add(int i, E e): inserts at i shifting others. remove(int i): removes at i (shifting); get(i): returns element; set(i,E): replaces; size(): count. Iterating while modifying can skip elements.', 'Removing an element at index i shifts later elements left. If you then increment i, you skip the element that moved into position i. Iterate backwards or use iterator when removing.', 'Write loops that add to, remove from, and search an ArrayList.'),
                _t('Traversing ArrayList', 'Standard for: for(int i=0; i<list.size(); i++). Enhanced for: for(Type item : list) — read-only. Use standard for when modifying or when index is needed.', 'Do not use an enhanced for loop to add or remove elements — causes ConcurrentModificationException.', 'Write ArrayList traversals for search, removal, and filtering.')],
               [('ArrayList<E>', 'Resizable list from java.util; stores reference types (use Integer not int)'),
                ('add(E)', 'Appends element to end of ArrayList'),
                ('remove(int i)', 'Removes element at index i and shifts remaining elements left'),
                ('size()', 'Method (with parens) returning current number of elements in ArrayList'),
                ('ConcurrentModificationException', 'Runtime error when modifying an ArrayList during enhanced for traversal')],
               ['Use ArrayList methods: add, remove, get, set, size.',
                'Traverse an ArrayList with indexed and enhanced for loops.',
                'Explain when to use ArrayList over an array.'],
               ['FRQ: write a method that removes elements from an ArrayList based on a condition.',
                'MCQ: trace ArrayList operations to find the final contents.',
                'MCQ: identify the ConcurrentModificationException scenario.'],
               ['Write a method removeNegatives(ArrayList<Integer> list) that removes all negative values.',
                'Trace add and remove operations on a small ArrayList.'],
               [('What import is needed for ArrayList?', ['import java.util.ArrayList;', 'Or import java.util.*;', 'Must be at the top of the file, before the class declaration', 'AP® exam may provide or omit imports; assume java.util is available']),
                ('Trace: ArrayList<String> list = new ArrayList<>(); list.add("a"); list.add("b"); list.add(0,"c"); System.out.println(list);', ['Start: []', 'add("a"): ["a"]', 'add("b"): ["a","b"]', 'add(0,"c"): ["c","a","b"] (inserted at index 0, others shifted)', 'Output: [c, a, b]']),
                ('Write a loop to remove all strings of length < 3 from ArrayList<String> words.', ['Iterate backwards to avoid skipping after removal:', 'for(int i=words.size()-1; i>=0; i--)', '  if(words.get(i).length() < 3) words.remove(i);', 'Forward traversal with i-- after remove also works']),
                ('What is ArrayList<Integer> vs ArrayList<int>?', ['ArrayList requires reference types', 'int is a primitive; Integer is its wrapper class', 'ArrayList<Integer> is correct', 'ArrayList<int> is a compile error']),
                ('How does ArrayList<E>.get differ from array access?', ['ArrayList: list.get(i) — method call', 'Array: arr[i] — bracket notation', 'Both throw exception if index is out of bounds', 'ArrayList is more flexible; array is slightly faster for direct access'])],
               [('ArrayList AP® CS A', 'Methods, traversal, and removal', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy ArrayList Java', 'ArrayList vs array', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['ArrayList.size() is a method (parens); array.length is a field (no parens).',
                'Removing shifts elements left — iterate backwards when removing.',
                'ArrayList requires wrapper types: Integer, Double, not int, double.']),

            _l('2D Arrays',
               [_t('2D Array Declaration', 'int[][] grid = new int[rows][cols]; Elements: grid[r][c]. First index is row (0 to rows-1), second is column (0 to cols-1). Each row is itself a 1D array: grid[r] is an int[].', '2D arrays use row-major order: grid[row][col]. Swapping row and column causes logic errors and potential AIOOBE.', 'Declare and access 2D arrays; identify row and column dimensions; trace element access.'),
                _t('Traversing 2D Arrays', 'Nested loop: outer iterates rows, inner iterates columns. grid.length gives number of rows; grid[0].length gives number of columns. Row-major traversal processes each row fully before moving to next row.', 'Using grid.length for columns instead of grid[0].length causes out-of-bounds for non-square arrays.', 'Write nested loops to traverse all elements; compute row sums and column sums.'),
                _t('2D Array Algorithms', 'Common tasks: sum all elements, find max, find row/column sums, transpose, search. AP® FRQ frequently asks to traverse a 2D array to compute a result.', 'When searching a 2D array, you need to check all elements — nested loops cannot break out of both at once. Use a boolean flag or return from method when found.', 'Write methods that search, sum, or transform 2D array contents.')],
               [('2D array', 'Array of arrays; grid[row][col]; first index is row, second is column'),
                ('grid.length', 'Number of rows in a 2D array'),
                ('grid[0].length', 'Number of columns (length of first row) in a 2D array'),
                ('row-major order', 'Traversal that processes all columns of row 0, then all of row 1, etc.'),
                ('jagged array', '2D array where rows have different lengths; not tested heavily on AP® CS A')],
               ['Declare and access 2D arrays using row and column indices.',
                'Write nested loops for row-major traversal of a 2D array.',
                'Compute aggregate values (total sum, row totals) from a 2D array.'],
               ['FRQ: write a method that processes each element of a 2D array.',
                'MCQ: trace 2D array access to find an element or sum.',
                'MCQ: identify grid.length vs grid[0].length for rows vs columns.'],
               ['Write a method that returns the sum of all elements in a 2D int array.',
                'Write a method that checks whether a 2D array is symmetric (grid[r][c] == grid[c][r]).'],
               [('Declare a 2D array of doubles with 3 rows and 4 columns.', ['double[][] matrix = new double[3][4];', 'Rows: 3 (matrix.length = 3)', 'Columns: 4 (matrix[0].length = 4)', 'Total elements: 3×4 = 12']),
                ('Write nested loops to print every element of int[][] grid.', ['for (int r=0; r<grid.length; r++) {', '  for (int c=0; c<grid[0].length; c++) {', '    System.out.print(grid[r][c] + " ");', '  }', '  System.out.println();', '}']),
                ('What does grid[2][3] access?', ['Row 2, Column 3 (both zero-indexed)', 'The element in the third row and fourth column', 'grid.length must be > 2; grid[2].length must be > 3', 'AIOOBE if either dimension is exceeded']),
                ('Write a method sumRow(int[][] grid, int r) that returns the sum of row r.', ['int sum = 0;', 'for (int c=0; c<grid[r].length; c++) {', '  sum += grid[r][c];', '}', 'return sum;']),
                ('How do you find the number of rows and columns in a 2D array?', ['Rows: grid.length', 'Columns: grid[0].length (assumes at least one row)', 'These are separate queries — no single grid.size() call', 'Swap them and you get wrong dimensions for non-square arrays'])],
               [('2D Arrays AP® CS A', 'Declaration, traversal, and algorithms', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy 2D Arrays', '2D array traversal and algorithms', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['2D array: grid[row][col]; grid.length = rows; grid[0].length = cols.',
                'Nested loops for traversal: outer over rows, inner over columns.',
                'grid.length ≠ grid[0].length for non-square arrays.']),

            _l('Array Algorithms and FRQ Practice',
               [_t('Sequential Search', 'Traverse from index 0; return index when found; return -1 if not found. Best case O(1); worst case O(n). For unsorted data only.', 'Return the index, not the value — AP® FRQ often asks for the index of the found element.', 'Write a sequential search method; trace which index is returned for a given target.'),
                _t('Selection Sort', 'Find the minimum in the unsorted portion and swap it to the front. Outer loop selects position; inner loop finds minimum. O(n²) always. Not required to memorize on AP®, but must recognize and trace.', 'Selection sort is in-place and does not need extra storage. Insertion sort (similar complexity) may also appear in AP® materials.', 'Trace selection sort for a small array; identify the number of comparisons and swaps.'),
                _t('FRQ Strategy for Arrays and ArrayLists', 'Read the problem once for context, once to extract the required algorithm. Write clean loops with correct boundaries. Methods must return the right type. Comment intent when stuck.', 'AP® graders award partial credit. Writing a correct loop that almost works earns more points than leaving the question blank. Always write something.', 'Write FRQ-style methods for array aggregation, filtering, and search.')],
               [('sequential search', 'Linear scan returning index of target or -1 if not found'),
                ('selection sort', 'Repeatedly select minimum of unsorted portion and swap to front; O(n²)'),
                ('sentinel value', 'Special value (-1, null, etc.) indicating absence or end of data'),
                ('partial credit', 'AP® FRQ awards points for partially correct solutions — always write something'),
                ('in-place', 'Algorithm that modifies the original array without creating a new one')],
               ['Write a sequential search method returning the index of a target.',
                'Trace one pass of selection sort on a small array.',
                'Write an FRQ-style method that processes array data to return a result.'],
               ['FRQ: write a complete method that searches an array and returns the index.',
                'FRQ: write a method that creates and returns a filtered copy of an ArrayList.',
                'MCQ: trace selection sort to find the array state after k passes.'],
               ['Write sequentialSearch(int[] arr, int target) returning index or -1.',
                'Trace selection sort on {5,2,8,1,4} for the first two passes.'],
               [('Write a sequential search method for int[] arr and int target.', ['public int search(int[] arr, int target) {', '  for (int i=0; i<arr.length; i++) {', '    if (arr[i] == target) return i;', '  }', '  return -1;', '}']),
                ('Trace one pass of selection sort on {4, 2, 7, 1}: what is the array after pass 1?', ['Find min in {4,2,7,1}: min = 1 at index 3', 'Swap positions 0 and 3: {1, 2, 7, 4}', 'First element is now correctly placed', 'Next pass finds min in {2,7,4}']),
                ('Write a method countEvens(int[] arr) that returns the count of even numbers.', ['int count = 0;', 'for (int val : arr) {', '  if (val % 2 == 0) count++;', '}', 'return count;']),
                ('Why should an AP® FRQ method return -1 (not 0 or throw an error) when a target is not found?', ['-1 is a sentinel: no valid index is -1', 'Returning 0 is ambiguous — element at index 0 might be the target', 'Throwing an exception is valid but more complex than required', 'AP® expects -1 as the standard not-found sentinel for search methods']),
                ('Write a method that returns an ArrayList<Integer> containing only positive values from int[] arr.', ['ArrayList<Integer> result = new ArrayList<>();', 'for (int val : arr) {', '  if (val > 0) result.add(val);', '}', 'return result;'])],
               [('Array Algorithms AP® CS A', 'Search, sort, and FRQ patterns', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4'),
                ('Khan Academy Sorting Searching', 'Sequential search and selection sort', 'https://www.youtube.com/watch?v=DO7C-H1Y5N4')],
               ['Sequential search: return index or -1; O(n).',
                'Selection sort: swap minimum to front each pass; O(n²).',
                'Always write FRQ answers — partial credit is awarded for correct partial solutions.'])
        ],
        'unit_qs': [
            ('What is the output of: int[] a = {3,1,4,1,5}; System.out.println(a[2]);', ['a[2] is the element at index 2 (zero-indexed)', '{3,1,4,1,5}: index 0=3, 1=1, 2=4, 3=1, 4=5', 'a[2] = 4', 'Output: 4']),
            ('Write a method that returns the sum of all elements in int[] arr.', ['int sum = 0;', 'for (int val : arr) sum += val;', 'return sum;', 'Enhanced for works here since we only read elements']),
            ('Trace: ArrayList<Integer> list = new ArrayList<>(); list.add(10); list.add(20); list.add(1,15); list.remove(0); System.out.println(list);', ['add(10): [10]; add(20): [10,20]', 'add(1,15): [10,15,20] (insert at index 1)', 'remove(0): [15,20] (remove index 0)', 'Output: [15, 20]']),
            ('How does grid.length differ from grid[0].length for a 2D array?', ['grid.length = number of rows', 'grid[0].length = number of columns (for row 0)', 'For a 3×5 grid: grid.length=3, grid[0].length=5', 'Confusing them gives wrong loop bounds — potential AIOOBE']),
            ('Write a method maxValue(int[][] grid) that returns the largest element.', ['int max = grid[0][0];', 'for (int r=0; r<grid.length; r++)', '  for (int c=0; c<grid[r].length; c++)', '    if (grid[r][c] > max) max = grid[r][c];', 'return max;']),
            ('What exception is thrown by int[] arr = new int[5]; arr[5] = 10;?', ['ArrayIndexOutOfBoundsException', 'Valid indices are 0 through 4 (length-1)', 'arr[5] is one past the end', 'Runtime error, not compile error']),
            ('Write a method removeNegatives(ArrayList<Integer> list) that removes all negative integers.', ['for (int i=list.size()-1; i>=0; i--)', '  if (list.get(i) < 0) list.remove(i);', 'Backwards traversal avoids skipping after removal', 'Alternative: use iterator remove']),
            ('Why does ArrayList<int> not compile but ArrayList<Integer> does?', ['ArrayList requires reference (object) types', 'int is a primitive; Integer is the wrapper class', 'Java generics do not support primitives', 'Autoboxing converts int ↔ Integer automatically when needed']),
            ('Write a sequential search for String target in String[] arr.', ['public int search(String[] arr, String target) {', '  for (int i=0; i<arr.length; i++) {', '    if (arr[i].equals(target)) return i;', '  }', '  return -1;', '}']),
            ('After selection sort pass 2 on {5,3,1,4,2}, what are the first two positions?', ['Pass 1: find min(5,3,1,4,2)=1 at index 2; swap with index 0: {1,3,5,4,2}', 'Pass 2: find min(3,5,4,2)=2 at index 4; swap with index 1: {1,2,5,4,3}', 'First two positions: 1, 2', 'Both are in their final sorted positions'])
        ]
    }
]
