NAME = 'AP® European History'
ABBREV = 'euro'
SLUG = 'ap-european-history'
COURSE_FILE = 'ap-european-history.html'
ACCENT_COLOR = '#f87171'

_H = 'https://www.youtube.com/results?search_query=Heimler+History+AP®+European+History+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 6,
        'title': 'Unit 6: Industrialization and Its Effects (c. 1815–1914)',
        'file': 'ap-european-history-6-unit-6-industrialization-and-its-effects.html',
        'desc': 'Industrial Revolution transforms economics, social structures, and politics; responses from liberalism, socialism, and nationalism emerge.',
        'gateway': [
            'Explain why the Industrial Revolution began in Britain.',
            'Describe social changes caused by industrialization.',
            'Compare liberal, conservative, and socialist responses to industrialization.',
            'Analyze the role of nationalism in 19th-century Europe.',
        ],
        'lessons': [
            _l('Origins and Spread of Industrialization',
               [
                   _t('Why Britain First', 'Britain industrialized first due to: coal and iron resources, navigable rivers and canals, mercantile capital, stable government, absence of internal tariffs, and an empire providing raw materials and markets.', 'No single factor explains British industrialization first — it was a combination of geography, capital, and institutions.', 'Identify multiple factors explaining why Britain industrialized before other European nations.'),
                   _t('Key Technologies', 'Steam engine (Watt), spinning jenny (Hargreaves), power loom (Cartwright), and railways transformed production and transportation; the factory system replaced cottage industry.', 'The Industrial Revolution was not a sudden event — it was a gradual shift accelerating over decades.', 'Describe key technologies and explain how the factory system changed work.'),
                   _t('Spread to Europe', 'Industrialization spread to Belgium, France, and German states after 1830; the railroad was the key vehicle of industrial spread; Germany industrialized late but rapidly after 1850.', 'Industrialization spread at different rates because of geography, capital availability, and political conditions.', 'Explain the spread of industrialization to continental Europe.'),
               ],
               [('Industrial Revolution', 'Shift from agricultural to industrial economy, beginning in Britain c. 1760–1840.'),
                ('steam engine', 'Machine converting steam power to mechanical work; key to factory production and railways.'),
                ('factory system', 'Centralized production system using machinery and wage labor; replaced cottage industry.'),
                ('railway', 'Steam-powered rail transportation; accelerated industrial spread and integrated national markets.'),
                ('cottage industry', 'Pre-industrial production where workers produced goods at home for merchants.')],
               ['Identify factors that enabled British industrialization.', 'Describe the factory system and its impact on work.', 'Explain how industrialization spread to continental Europe.'],
               ['Analyzing why Britain industrialized before France.', 'Explaining the role of railways in economic integration.', 'Comparing British and continental paths to industrialization.'],
               ['Khan Academy: Industrial Revolution', 'Heimler\'s History: Industrialization'],
               [('Which factor most distinguished Britain as the first to industrialize?', ['Combination of coal, capital, canals, and stable political institutions', 'Largest population in Europe', 'Most advanced university system', 'First to abolish serfdom', 'Closest proximity to African raw materials']),
                ('The factory system changed labor by:', ['Centralizing production under employer supervision with set hours and wages', 'Giving workers more independence', 'Reducing working hours immediately', 'Eliminating child labor', 'Increasing cottage production']),
                ('Railways accelerated industrialization by:', ['Integrating markets, reducing transport costs, and stimulating demand for iron and coal', 'Replacing all other transportation', 'Being built only in cities', 'Reducing the need for factories', 'Creating democratic pressure for reform']),
                ('Germany industrialized later than Britain but then rapidly because:', ['Strong state support, military demand, and access to Ruhr coal accelerated development', 'Germany had more capital than Britain', 'Germany had a larger empire', 'German workers were more skilled', 'Britain helped Germany industrialize']),
                ('Cottage industry was replaced by the factory system primarily because:', ['Factories with machines could produce goods faster and more cheaply than home workers', 'Cottages were destroyed in the Industrial Revolution', 'Home workers refused to work', 'Raw materials were only available in cities', 'The government banned cottage production']),
               ],
               [('Heimler\'s History: Industrial Revolution', 'Covers why Britain first, key technologies, and continental spread.', 'https://www.youtube.com/watch?v=vffI7U8ZSto')],
               ['Why did Britain industrialize first?', 'How did the factory system differ from cottage industry?', 'What role did railways play in spreading industrialization?']
            ),
            _l('Social Impact of Industrialization',
               [
                   _t('Urbanization and Living Conditions', 'Rapid urbanization created overcrowded cities with poor sanitation, disease (cholera epidemics), and unsafe working conditions; the industrial working class (proletariat) faced 14-hour workdays and child labor.', 'Not all workers were equally exploited — skilled craftsmen often maintained better conditions than factory workers.', 'Describe urban living and working conditions for the industrial working class.'),
                   _t('Middle Class and Gender', 'The industrial middle class (bourgeoisie) grew in wealth and political influence; the domestic sphere ideology confined middle-class women to home and family while working-class women worked in factories.', 'The "domestic sphere" was an ideal for middle-class women; working-class women always worked outside the home.', 'Analyze how industrialization affected gender roles differently by class.'),
                   _t('Reform Movements', 'Reformers like Robert Owen proposed model factory towns; Chartism sought working-class political rights; child labor and working conditions became targets of legislation (British Factory Acts).', 'Reform movements had mixed success — working conditions improved slowly over decades, not immediately.', 'Identify reform responses to industrial conditions and evaluate their effectiveness.'),
               ],
               [('proletariat', 'Industrial working class who sold their labor to factory owners.'),
                ('bourgeoisie', 'Middle class — manufacturers, merchants, professionals — who benefited most from industrialization.'),
                ('domestic sphere', 'Ideology confining middle-class women to home, motherhood, and household management.'),
                ('Chartism', 'British working-class movement demanding political rights (voting, annual parliaments).'),
                ('Robert Owen', 'British industrialist who built model factory communities (New Lanark) with better conditions; early socialist.')],
               ['Describe industrial working and living conditions.', 'Analyze how industrialization created different gender expectations by class.', 'Evaluate reform movements in response to industrial conditions.'],
               ['Document-based question on working conditions.', 'Comparing domestic sphere ideology across classes.', 'Analyzing Chartism as a political response to industrial inequality.'],
               ['Khan Academy: Social Impact', 'Heimler\'s History: Industrial Society'],
               [('Industrial urbanization was most harmful to workers because:', ['Overcrowding, poor sanitation, and disease in cities created deadly living conditions alongside dangerous work', 'All workers lived in factory towns with no community', 'City life was always preferred to rural life', 'Workers were intentionally imprisoned in factories', 'Urbanization only affected factory owners']),
                ('The domestic sphere ideology primarily affected:', ['Middle-class women, who were expected to manage the home rather than work outside it', 'All women equally across all classes', 'Working-class women who left factories for home', 'Men who preferred domestic roles', 'Factory women who worked part-time']),
                ('Chartism demanded:', ['Political rights for working-class men including universal male suffrage and annual parliaments', 'Better factory conditions only', 'Women\'s voting rights', 'Abolition of the factory system', 'Nationalization of all industry']),
                ('Robert Owen was significant because he:', ['Demonstrated that profitable industry could have better working conditions, influencing early socialism', 'Founded the Labour Party', 'Led Chartist demonstrations', 'Invented the factory system', 'Opposed all industrialization']),
                ('British Factory Acts addressed:', ['Limiting child labor and regulating working hours in factories', 'Nationalizing key industries', 'Giving workers the vote', 'Abolishing the factory system', 'Providing housing for workers']),
               ],
               [('Heimler\'s History: Social Impact of Industrialization', 'Covers urbanization, class structure, and reform movements.', 'https://www.youtube.com/watch?v=vffI7U8ZSto')],
               ['Describe three social problems caused by rapid industrialization.', 'What was the domestic sphere ideology?', 'What did Chartism demand?']
            ),
            _l('Ideological Responses: Liberalism, Conservatism, Socialism',
               [
                   _t('Classical Liberalism', 'Classical liberals (Locke, Smith, Mill) advocated free markets (laissez-faire), limited government, civil liberties, and political rights for property-owning men; they dominated 19th-century politics.', 'Classical liberalism was not democratic — most 19th-century liberals wanted voting rights limited to property owners, not all men.', 'Define classical liberalism and explain its economic and political positions.'),
                   _t('Conservatism', 'Conservatives (Burke) opposed rapid change, defended tradition, hierarchy, and established religion; they supported the Congress of Vienna\'s settlement and resisted liberalism and nationalism.', 'Conservatism was not simply reactionary — Burke acknowledged the need for gradual, organic change.', 'Explain Burkean conservatism and its opposition to revolutionary liberalism.'),
                   _t('Socialism and Marxism', 'Utopian socialists (Owen, Saint-Simon) imagined ideal communities; Marx and Engels\'s Communist Manifesto (1848) called for class struggle and proletarian revolution to overthrow capitalism.', 'Marx predicted the proletarian revolution in industrial countries — it actually occurred first in agrarian Russia, not industrial Britain or Germany.', 'Compare utopian socialism and Marxism; explain the Communist Manifesto\'s argument.'),
               ],
               [('classical liberalism', 'Political/economic ideology advocating free markets, limited government, and individual rights.'),
                ('laissez-faire', 'Economic policy of minimal government intervention in markets; championed by Adam Smith.'),
                ('Edmund Burke', 'British conservative thinker; opposed the French Revolution; argued for gradual, organic change.'),
                ('Karl Marx', 'German philosopher and economist; author of Communist Manifesto; developed scientific socialism.'),
                ('Communist Manifesto (1848)', 'Marx and Engels\'s call for proletarian revolution; analyzed capitalism as exploitative class struggle.')],
               ['Define classical liberalism and its economic implications.', 'Explain Burkean conservatism.', 'Distinguish utopian socialism from Marxism.'],
               ['Comparing liberal, conservative, and socialist responses to industrialization.', 'Analyzing the Communist Manifesto as a historical document.', 'Explaining why Marx\'s revolution did not occur in industrial Britain.'],
               ['Khan Academy: Ideologies', 'Heimler\'s History: 19th Century Ideologies'],
               [('Classical liberal economics (laissez-faire) held that:', ['Markets should operate free of government intervention to maximize efficiency and wealth', 'Government should control all industries', 'Workers should own the means of production', 'Tradition and hierarchy should guide economic decisions', 'Free trade was harmful to national interests']),
                ('Burke\'s conservatism differed from absolute monarchy in that:', ['Burke accepted gradual change — he opposed sudden revolutionary change, not all change', 'Burke supported democracy', 'Burke accepted the French Revolution\'s goals', 'Burke opposed all tradition', 'Burke had no political theory beyond defending kings']),
                ('The Communist Manifesto argued that:', ['History is driven by class struggle; capitalism will be overthrown by proletarian revolution', 'Workers should form trade unions and seek reform gradually', 'Capitalism was the best economic system', 'Revolution should be led by intellectuals, not workers', 'All property should be taxed equally']),
                ('Marxism differed from utopian socialism in that:', ['Marx claimed his socialism was scientifically based on historical analysis; utopians proposed ideal communities', 'Utopians were more radical than Marx', 'Marx accepted capitalism as the final stage', 'Utopians called for violent revolution', 'Marxism was inspired by Rousseau\'s general will']),
                ('Classical liberals in the 19th century generally believed voting rights should be:', ['Limited to property-owning men', 'Universal for all men and women', 'Restricted to the aristocracy', 'Given only to factory owners', 'Universal for all men but not women']),
               ],
               [('Heimler\'s History: 19th Century Ideologies', 'Covers liberalism, conservatism, and socialism.', 'https://www.youtube.com/watch?v=vffI7U8ZSto')],
               ['What is laissez-faire economics?', 'What did Burke believe about change?', 'How did Marx\'s socialism differ from utopian socialism?']
            ),
            _l('Nationalism and the Unifications of Italy and Germany',
               [
                   _t('Nationalism', 'Nationalism is the belief that people sharing language, culture, and history should form their own independent states; it challenged multi-ethnic empires (Austria, Ottoman) and drove Italian and German unification.', 'Nationalism is not necessarily liberal or democratic — it can justify both liberation and oppression.', 'Define nationalism and explain its challenge to multi-ethnic empires.'),
                   _t('Italian Unification', 'Italy was unified (1859–1870) through the combined efforts of Cavour (diplomacy), Garibaldi (revolutionary military force), and Piedmont-Sardinia\'s leadership; the Risorgimento was both liberal and nationalist.', 'Italian unification was not a purely popular movement — it was achieved through elite political manipulation and military force, not democratic referendum.', 'Trace Italian unification and the roles of Cavour and Garibaldi.'),
                   _t('German Unification', 'Prussia\'s Bismarck unified Germany (1864–1871) through Realpolitik — wars with Denmark, Austria, and France — rather than liberal nationalism; the German Empire was proclaimed in Versailles (1871).', 'Bismarck was not a nationalist ideologically — he used nationalism as a tool to expand Prussian power.', 'Explain Bismarck\'s Realpolitik strategy for German unification.'),
               ],
               [('nationalism', 'Belief that people sharing culture and language should form their own nation-state.'),
                ('Risorgimento', 'Italian nationalist movement for unification; involved Cavour, Garibaldi, and Piedmont.'),
                ('Cavour', 'Prime Minister of Piedmont; used diplomacy with France to expel Austria from northern Italy.'),
                ('Garibaldi', 'Italian nationalist military leader who conquered southern Italy and united it with the north.'),
                ('Realpolitik', 'Bismarck\'s pragmatic politics based on power and interest, not ideology or idealism.')],
               ['Define nationalism and explain its challenge to multi-ethnic empires.', 'Trace Italian unification through Cavour and Garibaldi.', 'Explain Bismarck\'s Realpolitik and German unification.'],
               ['Comparing Italian and German unification strategies.', 'Analyzing why multi-ethnic empires struggled with nationalism.', 'Evaluating Bismarck\'s Realpolitik as a political strategy.'],
               ['Khan Academy: Nationalism', 'Heimler\'s History: Italian and German Unification'],
               [('Nationalism most threatened which type of state?', ['Multi-ethnic empires like Austria-Hungary and the Ottoman Empire', 'Small nation-states like Belgium', 'Democratic republics', 'Constitutional monarchies like Britain', 'Colonial empires']),
                ('Cavour\'s strategy for Italian unification relied primarily on:', ['Diplomacy — allying with France to drive Austria from northern Italy', 'Military conquest by Piedmont alone', 'Popular democratic revolution', 'Papal support for unification', 'Garibaldi\'s northern campaigns']),
                ('Bismarck\'s Realpolitik meant:', ['Using pragmatic power politics and wars to achieve Prussian goals, regardless of ideology', 'Following nationalist ideology strictly', 'Pursuing liberal democratic reform', 'Negotiating diplomatically only', 'Appealing to German ethnic sentiment']),
                ('The German Empire was proclaimed in Versailles (1871) as a deliberate humiliation of:', ['France, which had just been defeated in the Franco-Prussian War', 'Austria, to assert German unity over Habsburg claims', 'Britain, to assert German imperial status', 'Russia, to claim German leadership of Europe', 'Italy, to diminish Italian unification']),
                ('Garibaldi\'s role in Italian unification was to:', ['Lead military conquest of southern Italy (Kingdom of Two Sicilies) and hand it to Piedmont', 'Negotiate with Austria diplomatically', 'Lead the Piedmontese army in the north', 'Govern unified Italy as its first prime minister', 'Seek papal support for unification']),
               ],
               [('Heimler\'s History: Unification', 'Covers Italian Risorgimento and Bismarck\'s German unification.', 'https://www.youtube.com/watch?v=vffI7U8ZSto')],
               ['What is nationalism?', 'What were the roles of Cavour and Garibaldi in Italian unification?', 'What is Realpolitik?']
            ),
        ],
        'unit_qs': [
            ('The Industrial Revolution began in Britain because of:', ['Combination of coal, capital, canals, and stable political institutions without internal tariffs', 'Britain\'s largest population and most advanced education', 'British military dominance ensuring trade', 'Britain\'s access to tropical colonies only', 'The British monarchy actively promoting industry']),
            ('The factory system harmed workers primarily by:', ['Imposing long hours, low wages, child labor, and dangerous conditions under employer control', 'Eliminating cottage production overnight', 'Forcing workers into cities with no housing', 'Paying workers in goods rather than money', 'Requiring all workers to own their tools']),
            ('Classical liberalism\'s laissez-faire economics was challenged by:', ['Socialism, which argued markets created exploitation and inequality requiring collective ownership', 'Conservatism, which preferred mercantilism', 'Nationalism, which preferred autarky', 'Catholicism, which opposed free markets on moral grounds', 'Bismarck, who preferred planned economies']),
            ('Marx predicted revolution would occur first in:', ['The most industrialized countries (Britain, Germany) — it actually occurred in agrarian Russia', 'France after the 1848 revolution', 'Italy after unification', 'Russia because of its peasant majority', 'Britain because of Chartist agitation']),
            ('Nationalism challenged the Austrian Empire because:', ['Austria ruled many different ethnic groups (Czechs, Hungarians, Poles) who wanted their own states', 'Austria was the most liberal state in Europe', 'Nationalism was a German creation that threatened German speakers', 'Austria had recently lost colonies to nationalism', 'The Austrian monarchy refused to industrialize']),
            ('Bismarck unified Germany through:', ['Wars with Denmark, Austria, and France using Prussian military power (Realpolitik)', 'Liberal democratic elections choosing Prussia as leader', 'Nationalist popular revolution', 'Economic integration through the Zollverein alone', 'Papal support for a Catholic German state']),
            ('The domestic sphere ideology affected working-class women differently from middle-class women because:', ['Working-class women always worked outside the home; domestic sphere was a middle-class aspiration', 'Working-class women embraced the domestic sphere more fully', 'It affected all women equally', 'Middle-class women worked in factories', 'Working-class women were excluded from factories']),
            ('Burke\'s conservatism was a response to the French Revolution specifically because:', ['It offered an argument for gradual, traditional change against revolutionary upheaval', 'Burke opposed all change', 'Burke supported the monarchy over parliament', 'Burke advocated for traditional religion against Enlightenment secularism', 'Burke wrote before the French Revolution']),
            ('Railway construction contributed to industrialization primarily by:', ['Integrating markets and reducing transportation costs, stimulating demand for coal and iron', 'Creating millions of jobs directly in factories', 'Replacing river transport immediately', 'Being profitable without government support', 'Connecting Britain to continental Europe directly']),
            ('Italian and German unification both relied on:', ['A powerful state (Piedmont, Prussia) leading unification rather than popular democratic revolution', 'Popular referenda choosing unification', 'Foreign intervention from France', 'Catholic Church support', 'Nationalist ideologues who became heads of state']),
        ],
    },
    {
        'num': 7,
        'title': 'Unit 7: 19th-Century Perspectives and Political Developments (c. 1815–1914)',
        'file': 'ap-european-history-7-unit-7-19th-century-perspectives-political-developments.html',
        'desc': 'Imperialism, Social Darwinism, feminism, and new political movements transform European society and the wider world.',
        'gateway': [
            'Explain the causes and justifications of New Imperialism.',
            'Describe the impact of European imperialism on Africa and Asia.',
            'Analyze Social Darwinism as a cultural and political ideology.',
            'Explain the development of feminism and working-class politics.',
        ],
        'lessons': [
            _l('New Imperialism',
               [
                   _t('Causes of New Imperialism', 'New Imperialism (1870–1914) was driven by: economic (markets, raw materials), political (national prestige, strategic advantage), and ideological (civilizing mission) motives.', 'Imperialism was not driven by economic factors alone — national pride and Social Darwinism were equally important motivations.', 'Identify economic, political, and ideological causes of New Imperialism.'),
                   _t('Scramble for Africa', 'European powers partitioned Africa at the Berlin Conference (1884–1885) without African input; by 1914, only Ethiopia and Liberia remained independent.', 'The Berlin Conference did not begin colonial conquest of Africa — Europeans had been trading there for centuries; it formalized the rapid interior partition.', 'Explain the Berlin Conference and the consequences of African partition.'),
                   _t('Imperialism in Asia', 'Britain dominated India (formal control after 1857 Sepoy Mutiny), while China was subjected to unequal treaties, spheres of influence, and the Boxer Rebellion (1900). Japan industrialized and became an imperial power itself.', 'China was not formally colonized — it was subjected to informal empire through unequal treaties, extraterritoriality, and economic dominance.', 'Compare formal and informal imperialism in Asia using India and China as cases.'),
               ],
               [('New Imperialism', 'European colonial expansion in Africa and Asia c. 1870–1914; driven by industrial capitalism and nationalism.'),
                ('Berlin Conference (1884–1885)', 'Meeting of European powers to divide Africa; no African representatives; formalized the "Scramble for Africa."'),
                ('civilizing mission', 'Ideological justification for imperialism claiming Europeans were bringing civilization and progress to "inferior" peoples.'),
                ('Sepoy Mutiny (1857)', 'Indian uprising against British East India Company; led to direct British Crown rule of India.'),
                ('informal empire', 'Control through economic and political pressure rather than direct territorial annexation; used in China.')],
               ['Identify causes of New Imperialism.', 'Explain the Berlin Conference and African partition.', 'Compare formal and informal imperialism.'],
               ['Document-based question on justifications for imperialism.', 'Analyzing the Berlin Conference as an example of European power dynamics.', 'Comparing British rule in India with informal imperialism in China.'],
               ['Khan Academy: Imperialism', 'Heimler\'s History: New Imperialism'],
               [('The "civilizing mission" justified imperialism by claiming:', ['Europeans were bringing civilization, Christianity, and progress to inferior peoples', 'Colonialism was economically beneficial to colonized peoples', 'Imperial powers had legal right to unclaimed territory', 'African and Asian peoples requested European rule', 'Trade required political control']),
                ('The Berlin Conference (1884–1885) was significant because:', ['European powers partitioned Africa among themselves without any African representation', 'It ended the slave trade', 'African nations agreed to partition in exchange for protection', 'It established free trade across Africa', 'It formalized British dominance in Africa']),
                ('Informal empire in China meant:', ['Economic and political control through unequal treaties without direct territorial annexation', 'No European presence in China', 'Chinese rulers invited European governance', 'Military occupation of all major cities', 'China was divided between Britain and France equally']),
                ('The Sepoy Mutiny (1857) changed British rule in India by:', ['Leading to direct Crown rule replacing the East India Company', 'Granting India independence', 'Establishing Indian self-governance', 'Ending British presence in South Asia', 'Inspiring other colonial revolts']),
                ('New Imperialism differed from earlier European colonialism in:', ['Its speed, scale, and systematic use of industrial military technology to control interior territories', 'Being motivated primarily by religious conversion', 'Focusing only on trade posts rather than territorial control', 'Being driven by individual explorers rather than states', 'Occurring only in Africa']),
               ],
               [('Heimler\'s History: New Imperialism', 'Covers causes, Berlin Conference, and Asian imperialism.', 'https://www.youtube.com/watch?v=MrK2tFDsiMA')],
               ['What were the three main causes of New Imperialism?', 'What was decided at the Berlin Conference?', 'What is informal empire and where was it applied?']
            ),
            _l('Social Darwinism and Racism',
               [
                   _t('Social Darwinism', 'Herbert Spencer applied Darwin\'s evolutionary ideas to human society — "survival of the fittest" justified inequality, imperialism, and laissez-faire capitalism as natural outcomes of competition.', 'Darwin did not support Social Darwinism — Spencer misapplied biological concepts to social policy.', 'Define Social Darwinism and explain how it was used to justify imperialism and inequality.'),
                   _t('Scientific Racism', 'Europeans used pseudo-scientific theories of racial hierarchy to justify colonialism; racial classifications were used to rank peoples and cultures from "civilized" to "primitive."', 'Scientific racism had no valid scientific basis — it was ideology dressed as science, now completely discredited.', 'Explain how racial pseudo-science justified imperialism and identify its flaws.'),
                   _t('Anti-Imperialism', 'Some Europeans (J.A. Hobson, Lenin) criticized imperialism as exploitative and economically harmful to colonized peoples; colonized peoples organized resistance movements.', 'Anti-imperial criticism came from both European intellectuals and colonized peoples — the voices of the colonized are often underrepresented in traditional narratives.', 'Identify European critics of imperialism and indigenous resistance movements.'),
               ],
               [('Social Darwinism', 'Misapplication of Darwin\'s evolution to human society; used to justify inequality and imperialism.'),
                ('Herbert Spencer', 'British philosopher who coined "survival of the fittest"; applied Darwinian ideas to social competition.'),
                ('scientific racism', 'Pseudo-scientific racial hierarchy used to justify colonialism and racial inequality.'),
                ('J.A. Hobson', 'British economist who criticized imperialism as economically harmful in Imperialism: A Study (1902).'),
                ('Social Darwinist argument', 'Claim that stronger nations "naturally" dominate weaker ones; used to justify colonial conquest.')],
               ['Define Social Darwinism and its misapplication of evolution.', 'Explain scientific racism and its use in justifying imperialism.', 'Identify critics of imperialism.'],
               ['Analyzing a Social Darwinist text for flawed reasoning.', 'Connecting scientific racism to imperialist policy.', 'Evaluating anti-imperial critiques from European and colonial perspectives.'],
               ['Khan Academy: Social Darwinism', 'Heimler\'s History: Social Darwinism'],
               [('Social Darwinism misused Darwin\'s theory by:', ['Applying biological competition to human society to justify inequality and imperialism as "natural"', 'Correctly applying evolutionary theory to politics', 'Arguing that all humans were equally evolved', 'Supporting socialist equality as the endpoint of evolution', 'Darwin himself endorsed Spencer\'s social applications']),
                ('Scientific racism was used to justify imperialism by:', ['Claiming non-European peoples were biologically inferior and needed European civilization', 'Providing statistical evidence of economic benefit', 'Basing claims on controlled scientific experiments', 'Being accepted by colonized peoples themselves', 'Being endorsed by all European scientists']),
                ('Hobson\'s critique of imperialism argued that:', ['Imperialism primarily benefited investors and capitalists while harming both colonized peoples and European workers', 'Imperialism was economically beneficial to all', 'Only military expansion without economic motive was harmful', 'Informal empire was acceptable but formal colonialism was not', 'Social Darwinism was the real problem with imperialism']),
                ('Darwin\'s actual evolutionary theory differed from Social Darwinism because:', ['Darwin described biological selection, not a moral hierarchy; Spencer misapplied these concepts', 'Darwin did support racial hierarchy', 'Darwin opposed all social applications of his work explicitly', 'Social Darwinism accurately extended Darwin\'s findings', 'Darwin wrote about social evolution in later works']),
                ('Indigenous resistance to imperialism was limited by:', ['European military technological advantage (machine guns, repeating rifles) and industrial logistics', 'Lack of motivation to resist', 'Geographic isolation preventing coordination', 'Acceptance of European cultural superiority', 'Colonial divide-and-rule tactics alone']),
               ],
               [('Heimler\'s History: Social Darwinism', 'Covers Social Darwinism, scientific racism, and anti-imperialism.', 'https://www.youtube.com/watch?v=MrK2tFDsiMA')],
               ['What is Social Darwinism and how was it misapplied from biology?', 'How was scientific racism used to justify imperialism?', 'What did Hobson argue about imperialism?']
            ),
            _l('19th-Century Political Movements',
               [
                   _t('Women\'s Suffrage', 'The suffrage movement demanded voting rights for women; British suffragettes (WSPU, Emmeline Pankhurst) used militant tactics; women first won voting rights after World War I.', 'Suffrage was not the only feminist cause — education, property rights, and legal equality were also central demands.', 'Describe the women\'s suffrage movement and its tactics and achievements.'),
                   _t('Labor Movement and Socialism', 'Trade unions organized workers for better wages and conditions; socialist parties (SPD in Germany, Labour in Britain) entered electoral politics; anarchism challenged all state authority.', 'The labor movement was more focused on practical improvements (wages, hours) than on Marxist revolution in most cases.', 'Trace the development of the labor movement from trade unions to socialist political parties.'),
                   _t('Revolutions of 1848', 'The Revolutions of 1848 spread across Europe as liberal and nationalist movements challenged conservative order; most were suppressed, but they accelerated constitutional reforms and strengthened nationalism.', '1848 revolutions mostly failed in the short term but had long-term impact — they demonstrated the power of nationalist and liberal ideas.', 'Explain causes and outcomes of the 1848 revolutions.'),
               ],
               [('suffragette', 'Woman who campaigned militantly for voting rights; especially in Britain with the WSPU.'),
                ('Emmeline Pankhurst', 'Founder of the Women\'s Social and Political Union (WSPU); led militant British suffrage campaign.'),
                ('trade union', 'Worker organization bargaining collectively for wages, hours, and conditions.'),
                ('Social Democratic Party (SPD)', 'German socialist political party; largest in Reichstag by 1912; pursued reform over revolution.'),
                ('Revolutions of 1848', 'Wave of liberal and nationalist revolutions across Europe in 1848; mostly suppressed but influential.')],
               ['Describe the women\'s suffrage movement and its tactics.', 'Trace the development of the labor movement.', 'Explain causes and outcomes of the 1848 revolutions.'],
               ['Comparing militant and moderate suffrage tactics.', 'Explaining why the SPD pursued reform over revolution.', 'Analyzing why the 1848 revolutions mostly failed.'],
               ['Khan Academy: 19th Century Politics', 'Heimler\'s History: Revolutions of 1848'],
               [('The British suffragette movement under Pankhurst used militant tactics because:', ['Peaceful campaigning had failed for decades; militancy drew attention to the cause', 'Violence was their preferred method of protest', 'The government had offered partial suffrage that they rejected', 'Other countries had adopted suffrage and Britain refused', 'World War I gave them the opportunity']),
                ('Trade unions were important because they:', ['Allowed workers to collectively bargain for wages and conditions rather than negotiating individually', 'Were controlled by socialist governments', 'Abolished child labor directly', 'Were only for skilled craftsmen', 'Led the 1848 revolutions']),
                ('The Revolutions of 1848 mostly failed because:', ['Conservative armies remained loyal to existing governments; nationalist and liberal movements lacked coordination', 'The working class did not participate', 'France\'s republic survived and inspired others to give up', 'The revolutions achieved their goals quickly', 'Marx led them to defeat']),
                ('The German SPD pursued reform through elections rather than revolution because:', ['Workers could improve conditions through the existing political system', 'Revolution was illegal in Germany', 'Marx opposed political participation', 'The SPD was controlled by the government', 'Working-class voters preferred conservatism']),
                ('The 1848 revolutions had long-term significance because:', ['They demonstrated the power of nationalism and liberalism even in defeat, accelerating later reform', 'They were completely suppressed with no lasting impact', 'They established democracies across Europe', 'They triggered German and Italian unification directly', 'They eliminated the Austrian Empire']),
               ],
               [('Heimler\'s History: 19th Century Politics', 'Covers suffrage, labor movements, and 1848 revolutions.', 'https://www.youtube.com/watch?v=MrK2tFDsiMA')],
               ['What tactics did British suffragettes use and why?', 'Why did the SPD pursue reform rather than revolution?', 'Why did most 1848 revolutions fail?']
            ),
            _l('Culture and Thought in the 19th Century',
               [
                   _t('Romanticism', 'Romanticism (c. 1780–1850) reacted against Enlightenment rationalism by emphasizing emotion, nature, nationalism, and individual genius; major figures include Wordsworth, Byron, Delacroix, Beethoven.', 'Romanticism was not anti-intellectual — it valued different kinds of knowledge, particularly intuition and imagination over pure reason.', 'Define Romanticism and contrast it with Enlightenment rationalism.'),
                   _t('Realism and Naturalism', 'Realism (c. 1850–1900) depicted everyday life and social problems honestly; Dickens exposed industrial poverty; Zola\'s naturalism applied scientific observation to human behavior.', 'Realist literature was not pessimistic for its own sake — it aimed to expose social problems and drive reform.', 'Explain Realism as a response to industrialization.'),
                   _t('Darwin and Religion', 'Darwin\'s On the Origin of Species (1859) threatened religious accounts of creation; some Christians rejected evolution; others (liberal theology) accommodated it; it accelerated secularization of European thought.', 'Darwin\'s theory was controversial in its time but was rapidly accepted by most scientists within a decade.', 'Analyze the impact of Darwinian evolution on European religious and intellectual life.'),
               ],
               [('Romanticism', 'Cultural movement (c. 1780–1850) emphasizing emotion, nature, and individual genius over reason.'),
                ('Realism', 'Artistic movement depicting everyday life and social conditions honestly.'),
                ('Charles Dickens', 'English novelist who exposed industrial poverty and social inequality; exemplar of social realism.'),
                ('Émile Zola', 'French novelist; developed naturalism — applying scientific observation to human behavior.'),
                ('secularization', 'Long-term decline in the public role of religion in European intellectual and political life.')],
               ['Define Romanticism and contrast it with Enlightenment values.', 'Explain Realism as a literary response to industrialization.', 'Analyze Darwin\'s impact on European religious thought.'],
               ['Comparing Romantic and Realist cultural movements.', 'Analyzing a Dickens passage for social criticism.', 'Explaining how Darwin accelerated secularization.'],
               ['Khan Academy: 19th Century Culture', 'Heimler\'s History: Romanticism and Realism'],
               [('Romanticism reacted against the Enlightenment by:', ['Emphasizing emotion, intuition, and imagination over pure reason and scientific analysis', 'Rejecting all forms of knowledge', 'Returning to medieval religious values', 'Opposing nationalism', 'Embracing industrial progress']),
                ('Dickens\'s novels contributed to social reform by:', ['Exposing the human cost of industrial poverty to middle-class readers who could influence reform', 'Being read only by the working class', 'Directly lobbying Parliament', 'Proposing specific legislative solutions', 'Endorsing socialist revolution']),
                ('Darwin\'s On the Origin of Species threatened religious belief by:', ['Providing a natural explanation for species diversity that contradicted literal Biblical accounts of creation', 'Disproving the existence of God directly', 'Arguing that religion had always been harmful', 'Claiming evolution was random and purposeless', 'Being endorsed by major religious institutions immediately']),
                ('Zola\'s naturalism differed from Realism by:', ['Applying scientific observation and determinism to explain human behavior through environment and heredity', 'Focusing on upper-class subjects', 'Rejecting social criticism in favor of aesthetic beauty', 'Using fantasy elements to comment on society', 'Being entirely optimistic about human nature']),
                ('Secularization in 19th-century Europe referred to:', ['Long-term decline in religion\'s public role in education, politics, and intellectual life', 'The complete disappearance of religious belief', 'Government nationalization of church property only', 'Scientists actively attacking religious institutions', 'Religion retreating only from science while remaining in politics']),
               ],
               [('Heimler\'s History: 19th Century Culture', 'Covers Romanticism, Realism, and Darwin\'s impact.', 'https://www.youtube.com/watch?v=MrK2tFDsiMA')],
               ['How did Romanticism differ from Enlightenment values?', 'How did Dickens use literature as social criticism?', 'How did Darwin\'s theory affect European religious thought?']
            ),
        ],
        'unit_qs': [
            ('New Imperialism was "new" compared to earlier colonialism in that it:', ['Was more systematic, faster, and used industrial technology to penetrate and control interior territories', 'Was motivated solely by religious conversion', 'Focused on trade posts rather than territorial control', 'Was driven by individual adventurers, not states', 'Occurred only in Africa']),
            ('The Berlin Conference (1884) demonstrated:', ['European powers\' willingness to partition Africa among themselves without consulting Africans', 'African leaders\' acceptance of European rule in exchange for development', 'Britain\'s dominance over all other European imperial powers', 'The end of the slave trade', 'Democratic principles applied to colonial governance']),
            ('Social Darwinism was used to justify imperialism by:', ['Claiming that European dominance was the natural result of superiority in the competition for survival', 'Providing scientific evidence of European technological advantage', 'Connecting Darwin\'s genetics to cultural differences', 'Being endorsed by Darwin himself', 'Proving economic benefits of colonialism']),
            ('The Revolutions of 1848 failed primarily because:', ['Conservative armies remained loyal; nationalist and liberal movements lacked unity', 'Workers refused to participate', 'The ideas were insufficiently popular', 'Foreign intervention suppressed them', 'The revolutions succeeded and led to stability']),
            ('Romanticism emerged as a reaction to:', ['Enlightenment rationalism; it emphasized emotion, nature, and individual genius', 'Industrial capitalism; it was purely political', 'The French Revolution\'s failure', 'Religious authority in European culture', 'Scientific Darwinism']),
            ('Darwin\'s theory accelerated secularization by:', ['Providing a scientific explanation for human origins, reducing dependence on religious explanation', 'Proving God did not exist', 'Being endorsed by the Catholic Church', 'Being accepted only in Protestant countries', 'Eliminating interest in ethics']),
            ('Trade unions were most important for:', ['Giving workers collective bargaining power to improve wages and conditions', 'Leading political revolutions against capitalism', 'Being controlled by socialist governments', 'Organizing only skilled craftsmen', 'Directing the 1848 revolutions']),
            ('Informal empire in China differed from formal colonialism in India because:', ['China retained formal sovereignty but was economically and politically subordinate through unequal treaties', 'China was never subject to European power', 'China was annexed by Britain after the Boxer Rebellion', 'Britain had formal control of both', 'China successfully resisted all European influence']),
            ('The women\'s suffrage movement in Britain succeeded partly because:', ['World War I demonstrated women\'s contributions to the national effort, making exclusion harder to justify', 'Pankhurst\'s militant tactics immediately convinced Parliament', 'Men universally supported women\'s voting rights', 'International pressure forced Britain to act', 'British law already recognized women as equal citizens']),
            ('Scientific racism was dangerous because:', ['It used the prestige of science to legitimize racial hierarchy and justify colonial exploitation', 'It was based on valid biological research', 'It was rejected by all European governments', 'It applied only to African peoples', 'It was a fringe theory with no mainstream acceptance']),
        ],
    },
    {
        'num': 8,
        'title': 'Unit 8: 20th-Century Global Conflicts (c. 1914–present)',
        'file': 'ap-european-history-8-unit-8-20th-century-global-conflicts.html',
        'desc': 'World War I, the Russian Revolution, the rise of fascism, and World War II reshape European society and global politics.',
        'gateway': [
            'Explain the causes of World War I using MAIN.',
            'Analyze the Russian Revolution and the rise of the Soviet state.',
            'Explain the conditions that enabled fascism in Italy and Germany.',
            'Describe World War II\'s causes and the Holocaust.',
        ],
        'lessons': [
            _l('World War I',
               [
                   _t('Causes of WWI (MAIN)', 'MAIN causes: Militarism (arms race), Alliance system (Triple Alliance vs. Triple Entente), Imperialism (colonial competition), Nationalism (especially in the Balkans). Immediate trigger: assassination of Franz Ferdinand (June 1914).', 'The assassination of Franz Ferdinand was the spark, not the underlying cause — the powder keg of militarism, alliances, and Balkan nationalism was already built.', 'Identify MAIN causes and explain the assassination as trigger vs. underlying cause.'),
                   _t('Total War', 'WWI was a total war involving mass mobilization, industrial-scale killing (machine guns, artillery, poison gas), home front involvement, and propaganda; trench warfare characterized the Western Front.', 'Trench warfare was a result of the stalemate between offensive and defensive military technology — no one planned for static trench warfare.', 'Explain why WWI became a total war and describe trench warfare on the Western Front.'),
                   _t('Consequences of WWI', 'The Treaty of Versailles (1919) imposed war guilt, reparations, territorial losses, and military restrictions on Germany; it humiliated Germany without destroying its capacity for revenge.', 'The "stab in the back" myth — that Germany was betrayed from within — was false but politically powerful in Weimar Germany.', 'Analyze the Treaty of Versailles and explain how it contributed to German resentment.'),
               ],
               [('MAIN', 'Acronym for WWI causes: Militarism, Alliance system, Imperialism, Nationalism.'),
                ('Triple Alliance', 'Pre-WWI alliance of Germany, Austria-Hungary, and Italy.'),
                ('Triple Entente', 'Pre-WWI alliance of France, Russia, and Britain.'),
                ('Treaty of Versailles (1919)', 'WWI peace treaty imposing harsh terms on Germany; source of interwar resentment.'),
                ('total war', 'War involving entire society — military, economy, and civilian population — not just armies.')],
               ['Explain MAIN causes of WWI.', 'Describe total war and trench warfare.', 'Analyze the Treaty of Versailles.'],
               ['Long-essay on causes of WWI.', 'Analyzing Versailles terms as causes of WWII.', 'Explaining the home front as part of total war.'],
               ['Khan Academy: WWI', 'Heimler\'s History: World War I'],
               [('The alliance system in WWI caused a local conflict to become a world war by:', ['Automatically drawing major powers into conflict when Austria-Hungary attacked Serbia', 'Preventing Germany from acting independently', 'Creating economic competition between great powers', 'Allowing smaller nations to resist great powers', 'Encouraging peaceful resolution through guaranteed mutual defense']),
                ('Trench warfare on the Western Front resulted from:', ['Stalemate between defensive technology (machine guns) and offensive strategy; neither side could advance', 'German strategic choice to fight defensively', 'French refusal to advance past the Rhine', 'Generals planning for trench warfare in advance', 'The terrain of Belgium and France requiring trenches']),
                ('The Treaty of Versailles contributed to WWII by:', ['Humiliating Germany without destroying its industrial capacity, creating conditions for nationalist reaction', 'Being so harsh that Germany had no capacity to rearm', 'Satisfying German nationalist demands for territory', 'Creating a viable democratic Germany', 'Establishing effective international institutions']),
                ('WWI was a "total war" because:', ['It mobilized entire economies and societies, involving civilians through production, rationing, and propaganda', 'More soldiers died than in any previous conflict', 'It was fought on every continent', 'New weapons of mass destruction were used', 'Government controlled all media for the first time']),
                ('Nationalism in the Balkans contributed to WWI by creating:', ['Intense ethnic tensions and rivalry between Austria-Hungary and rising Serbia', 'Conflict over colonial territories', 'Competition for industrial resources', 'Religious wars between Catholic and Orthodox populations', 'Demand for democracy in autocratic empires']),
               ],
               [('Heimler\'s History: World War I', 'Covers MAIN causes, trench warfare, and Versailles.', 'https://www.youtube.com/watch?v=HXiq5VLWXug')],
               ['What does MAIN stand for as causes of WWI?', 'Why did WWI become a war of trenches?', 'How did the Treaty of Versailles contribute to WWII?']
            ),
            _l('The Russian Revolution and Soviet State',
               [
                   _t('February and October Revolutions', 'February 1917: Tsar Nicholas II fell after bread riots and military mutinies; October 1917: Lenin\'s Bolsheviks seized power with the slogan "Peace, Land, Bread."', 'The October Revolution was a coup by a small Bolshevik minority, not a popular mass uprising — Lenin exploited chaos and Provisional Government weakness.', 'Distinguish the February and October Revolutions in terms of causes, actors, and outcomes.'),
                   _t('Lenin and Bolshevik State', 'Lenin established a one-party state, signed Treaty of Brest-Litovsk (1918) leaving WWI, won the Civil War, and introduced NEP (New Economic Policy) to stabilize the economy.', 'The NEP was a pragmatic retreat from communism, not an ideological shift — Lenin called it "one step backward to take two steps forward."', 'Describe Lenin\'s policies and how he consolidated Bolshevik power.'),
                   _t('Stalinism', 'Stalin collectivized agriculture (causing famine killing millions), industrialized rapidly through Five-Year Plans, and purged rivals through show trials and the Gulag system.', 'Stalin\'s purges eliminated both real enemies and loyal communists — fear, not just ideology, drove the Terror.', 'Evaluate Stalin\'s methods and the human cost of forced modernization.'),
               ],
               [('Bolsheviks', 'Lenin\'s faction of Russian Marxists; seized power in October 1917; became Communist Party.'),
                ('Soviet', 'Workers\' and soldiers\' council; became the basic unit of the Soviet state.'),
                ('Treaty of Brest-Litovsk (1918)', 'Peace treaty with Germany; Russia gave up vast territory to exit WWI.'),
                ('collectivization', 'Stalin\'s forced merging of private farms into collective farms; caused famine killing millions.'),
                ('Gulag', 'Soviet forced labor camp system; millions imprisoned or died under Stalin.')],
               ['Distinguish the February and October Revolutions.', 'Describe Lenin\'s consolidation of Bolshevik power.', 'Evaluate the costs of Stalinist modernization.'],
               ['Comparing February and October Revolutions.', 'Analyzing Lenin\'s NEP as pragmatic retreat.', 'Evaluating Stalin\'s Five-Year Plans in terms of human cost.'],
               ['Khan Academy: Russian Revolution', 'Heimler\'s History: Russian Revolution'],
               [('The Bolshevik slogan "Peace, Land, Bread" addressed:', ['Russian war exhaustion, peasant desire for land reform, and urban food shortages', 'Industrial workers\' demands for higher wages', 'The middle class\'s desire for constitutional government', 'Military officers\' desire for better equipment', 'Nationalist demands for Russian territorial expansion']),
                ('The Treaty of Brest-Litovsk (1918) was a costly decision for Russia because:', ['It gave up vast territories in exchange for exit from WWI, but preserved the Bolshevik regime', 'It brought Germany into the Russian Civil War', 'It ended the October Revolution', 'It restored the Tsar', 'It united all socialist factions behind Lenin']),
                ('Stalin\'s collectivization caused famine primarily because:', ['Peasant resistance and the destruction of productive farms killed millions in Ukraine and Kazakhstan', 'Collective farms were less productive than private farms in all cases', 'Stalin deliberately starved the peasantry as political punishment', 'Drought struck all collective farms simultaneously', 'Food was all exported to Germany']),
                ('Lenin\'s New Economic Policy (NEP) represented:', ['A pragmatic retreat to limited capitalism to stabilize the economy after War Communism', 'Permanent abandonment of communism', 'Full adoption of free-market economics', 'A response to democratic pressure', 'Stalin\'s first major economic initiative']),
                ('Stalin\'s purges (1936–1938) primarily targeted:', ['Both actual enemies and loyal Bolsheviks; the terror destroyed much of the Soviet military leadership', 'Only actual opponents of Stalin', 'The peasantry who resisted collectivization', 'German spies in the Soviet Union', 'The Red Army officers who fought in WWI']),
               ],
               [('Heimler\'s History: Russian Revolution', 'Covers February, October, Lenin, and Stalin.', 'https://www.youtube.com/watch?v=HXiq5VLWXug')],
               ['What were the February and October Revolutions?', 'What was the NEP?', 'What was the human cost of Stalinist collectivization?']
            ),
            _l('Fascism and World War II',
               [
                   _t('Rise of Fascism', 'Fascism rose in Italy (Mussolini, 1922) and Germany (Hitler, 1933) from conditions of economic crisis, national humiliation, weak democracy, and fear of communism; fascism was ultranationalist, anti-communist, and totalitarian.', 'Fascism was not simply socialism — it rejected both Marxist class struggle and liberal democracy in favor of ultranationalist authoritarian rule.', 'Explain the conditions enabling fascism and compare Italian and German fascism.'),
                   _t('Nazi Germany', 'Hitler\'s NSDAP® used propaganda, legal and violent means to seize power; the Nuremberg Laws (1935) stripped Jews of citizenship; Kristallnacht (1938) accelerated persecution toward genocide.', 'Nazism did not become genocidal overnight — it escalated from discrimination to segregation to mass murder over a decade.', 'Trace the escalation of Nazi persecution from 1933 to the Holocaust.'),
                   _t('World War II and the Holocaust', 'WWII began with German invasion of Poland (1939); Holocaust killed 6 million Jews and 5–6 million others; war ended with atomic bombs on Japan (1945) and Soviet victory in the East.', 'The Holocaust was not a secret — it required widespread participation and knowledge across occupied Europe.', 'Explain the Holocaust as an intentional genocide enabled by Nazi ideology and state power.'),
               ],
               [('fascism', 'Ultranationalist, authoritarian ideology rejecting liberalism and communism; promoted in Italy by Mussolini.'),
                ('Mussolini', 'Italian fascist dictator (1922–1943); first fascist leader to gain power in Europe.'),
                ('Nuremberg Laws (1935)', 'German laws stripping Jews of citizenship and prohibiting marriage with non-Jews.'),
                ('Holocaust', 'Systematic Nazi genocide of 6 million Jews and millions of others (Roma, disabled, political opponents).'),
                ('Weimar Republic', 'German democratic government (1919–1933); undermined by economic crisis, political extremism, and weak institutions.')],
               ['Explain the conditions enabling the rise of fascism.', 'Trace Nazi persecution from 1933 to genocide.', 'Analyze the Holocaust as organized state genocide.'],
               ['Long-essay on why Weimar Germany fell to Hitler.', 'Analyzing the Nuremberg Laws as a step toward genocide.', 'Comparing Italian and German fascism.'],
               ['Khan Academy: Rise of Fascism', 'Heimler\'s History: WWII and Holocaust'],
               [('Fascism appealed to many Europeans in the 1920s–30s because:', ['It promised order, national greatness, and anti-communism during economic crisis and democratic failure', 'It offered economic equality', 'It was the most moderate political option', 'Democratic parties endorsed it', 'It had a clear program of individual rights']),
                ('The Nuremberg Laws (1935) were significant as a step toward the Holocaust because:', ['They legally defined and segregated Jews as non-citizens, making further persecution acceptable and legal', 'They ordered the immediate deportation of Jews', 'They established concentration camps', 'They were the final step before genocide', 'They were opposed by most Germans']),
                ('The Holocaust was enabled by all of the following EXCEPT:', ['Popular German opposition that delayed its implementation', 'Nazi ideology dehumanizing Jews', 'Modern bureaucratic and industrial infrastructure', 'Collaboration from occupied territories', 'Widespread social indifference or active participation']),
                ('The Weimar Republic was vulnerable to Hitler because:', ['Economic crisis, weak democratic culture, and political extremism on left and right undermined its legitimacy', 'It was never truly established after WWI', 'Hitler won a democratic majority immediately', 'Germany had no liberal tradition', 'The Treaty of Versailles directly banned the Weimar Republic']),
                ('Mussolini came to power in Italy in 1922 through:', ['A combination of political pressure, threat of violence (March on Rome), and royal appointment', 'A democratic election', 'Military coup', 'Popular revolution', 'German support']),
               ],
               [('Heimler\'s History: Fascism and WWII', 'Covers fascism, Nazi persecution, and the Holocaust.', 'https://www.youtube.com/watch?v=HXiq5VLWXug')],
               ['What conditions enabled fascism in Europe?', 'How did Nazi persecution of Jews escalate from 1933 to 1941?', 'Why was the Weimar Republic vulnerable to Hitler?']
            ),
            _l('The Interwar Period',
               [
                   _t('Great Depression', 'The Great Depression (1929–1939) caused mass unemployment across Europe; governments responded with austerity (worsening it) or Keynesian stimulus; it destabilized democracies and boosted extremist parties.', 'The Great Depression was global, not just American — European banks and industries were tightly connected to U.S. markets.', 'Explain how the Great Depression affected European politics.'),
                   _t('Appeasement', 'Britain and France appeased Hitler at Munich (1938), giving him the Sudetenland; this failed to prevent war; Chamberlain\'s "peace in our time" was discredited by Germany\'s invasion of the rest of Czechoslovakia (1939).', 'Appeasement was not cowardice — it reflected genuine desire to avoid another catastrophic war and belief that Hitler\'s demands were limited.', 'Evaluate appeasement as a policy and explain why it failed.'),
                   _t('Soviet-Nazi Pact', 'The Molotov-Ribbentrop Pact (1939) between the USSR and Germany shocked the world; it included secret protocols dividing Eastern Europe; it enabled Germany to invade Poland without Soviet interference.', 'The Soviet-Nazi Pact was a pragmatic, not ideological, agreement — both Stalin and Hitler planned to eventually betray each other.', 'Explain the Molotov-Ribbentrop Pact and its consequences.'),
               ],
               [('Great Depression', 'Global economic crisis beginning 1929; caused mass unemployment and political instability.'),
                ('appeasement', 'British/French policy of making concessions to Hitler to avoid war; failed at Munich (1938).'),
                ('Munich Agreement (1938)', 'Britain and France granted Hitler the Sudetenland to preserve peace; discredited by Hitler\'s subsequent aggression.'),
                ('Molotov-Ribbentrop Pact (1939)', 'Soviet-Nazi non-aggression pact with secret protocols dividing Eastern Europe.'),
                ('Keynesian economics', 'Economic theory advocating government spending to stimulate economy during depression.')],
               ['Explain the Great Depression\'s impact on European politics.', 'Evaluate appeasement as a rational policy choice.', 'Explain the Molotov-Ribbentrop Pact and its consequences.'],
               ['Analyzing Munich Agreement as rational or naive.', 'Explaining how the Great Depression boosted fascism.', 'Predicting consequences of the Soviet-Nazi Pact.'],
               ['Khan Academy: Interwar Period', 'Heimler\'s History: Great Depression and Appeasement'],
               [('The Great Depression increased support for fascist parties by:', ['Creating desperation and making promises of order and national greatness more attractive', 'Proving that democracy could not solve economic problems', 'Enabling fascists to control elections directly', 'Being caused by democratic governments\' policies', 'Making workers communist, driving the middle class to fascism']),
                ('Appeasement at Munich (1938) failed because:', ['Hitler\'s demands were not limited — he took the rest of Czechoslovakia within months', 'Britain was not sincere in its concessions', 'France refused to honor the agreement', 'The Soviet Union intervened in Czechoslovakia', 'Hitler had already planned to invade Poland before Munich']),
                ('The Molotov-Ribbentrop Pact allowed Germany to invade Poland because:', ['It eliminated the risk of a two-front war by securing Soviet neutrality', 'The Soviet Union agreed to support Germany', 'It established a military alliance against France', 'Britain and France recognized it and withdrew their guarantee to Poland', 'Poland was already in the Soviet sphere']),
                ('Keynesian economics responded to the Great Depression by advocating:', ['Government deficit spending to stimulate demand and reduce unemployment', 'Austerity — reducing government spending to balance budgets', 'Nationalizing all industry', 'Returning to the gold standard', 'Eliminating trade barriers globally']),
                ('Chamberlain\'s appeasement policy was based on the reasonable assumption that:', ['Hitler was a rational statesman with limited, achievable territorial demands', 'Another war would be impossible after WWI\'s devastation', 'France and Britain could defeat Germany militarily', 'The Soviet Union would balance German power', 'America would intervene if war began']),
               ],
               [('Heimler\'s History: Interwar Period', 'Covers Depression, appeasement, and Soviet-Nazi Pact.', 'https://www.youtube.com/watch?v=HXiq5VLWXug')],
               ['How did the Great Depression destabilize European democracy?', 'Why did appeasement fail?', 'What was the Molotov-Ribbentrop Pact and why was it shocking?']
            ),
        ],
        'unit_qs': [
            ('The assassination of Franz Ferdinand in 1914 triggered WWI because:', ['The alliance system automatically drew great powers into conflict', 'It killed the heir to the British throne', 'It directly threatened German security', 'No peacefully negotiated solution was attempted', 'Austria-Hungary lacked the army to fight without allies']),
            ('The Treaty of Versailles\' war guilt clause was harmful because:', ['It humiliated Germany and provided a grievance that nationalists (including Hitler) exploited', 'It was so harsh it destroyed Germany\'s industrial capacity', 'Germany accepted it willingly as fair', 'It satisfied German nationalist demands', 'It prevented German economic recovery entirely']),
            ('The Bolsheviks succeeded in October 1917 because:', ['They exploited the Provisional Government\'s weakness and promised peace, land, and bread', 'They had majority support across Russia', 'The Tsar supported their seizure of power', 'The army defected entirely to the Bolsheviks', 'Western powers helped them seize power']),
            ('Stalin\'s Five-Year Plans achieved rapid industrialization at the cost of:', ['Millions of lives through forced labor, collectivization famine, and the purges', 'Abandoning Marxist ideology', 'Making Russia dependent on foreign capital', 'Destroying Russia\'s agricultural capacity permanently', 'Creating a consumer economy']),
            ('Fascism appealed to middle classes in the 1930s because:', ['It promised order and national greatness while opposing both communist revolution and liberal failure', 'It offered economic equality', 'It was democratic and popular', 'The Church endorsed it universally', 'It had successfully governed other countries']),
            ('The Holocaust was unprecedented because:', ['It was an industrially organized, state-directed genocide of an entire people', 'Genocide was unknown before 1939', 'Only one country (Germany) was involved', 'It killed only Jews', 'It was completed in a single operation']),
            ('Trench warfare on the Western Front demonstrated that:', ['Industrial defensive technology had temporarily outpaced offensive tactics, creating stalemate', 'Generals had planned for this type of warfare', 'Chemical weapons were the primary cause of death', 'Air power decided the outcome of WWI', 'The war could not be won by either side']),
            ('The Weimar Republic was most threatened by:', ['Both left-wing communist and right-wing fascist extremists exploiting economic crisis and institutional weakness', 'Only right-wing parties', 'Soviet interference', 'Democratic parties that refused to form coalitions', 'The Treaty of Versailles directly banning democratic government']),
            ('Mussolini\'s fascism in Italy differed from Hitler\'s Nazism primarily in:', ['Nazism\'s explicit racial ideology and systematic genocide; Italian fascism initially lacked racial ideology', 'Mussolini being more democratic', 'Italy being more economically successful', 'Hitler opposing all aspects of Mussolini\'s program', 'Nazism being less authoritarian']),
            ('The Munich Agreement (1938) is considered a failure of appeasement because:', ['Hitler violated it immediately, showing that concessions emboldened rather than satisfied aggressive dictators', 'Britain gained nothing from the agreement', 'Hitler had not made any demands at Munich', 'France refused to honor the agreement', 'The Soviet Union warned it would fail']),
        ],
    },
    {
        'num': 9,
        'title': 'Unit 9: Cold War and Contemporary Europe (c. 1945–present)',
        'file': 'ap-european-history-9-unit-9-cold-war-and-contemporary-europe.html',
        'desc': 'Post-WWII reconstruction, Cold War division, decolonization, European integration, and contemporary challenges.',
        'gateway': [
            'Explain the origins and key events of the Cold War.',
            'Describe decolonization and its impact on Europe.',
            'Analyze European integration through the EU.',
            'Evaluate contemporary challenges facing Europe.',
        ],
        'lessons': [
            _l('Origins of the Cold War',
               [
                   _t('Yalta and Division of Europe', 'At Yalta (1945), the Big Three agreed on postwar reconstruction; the Soviet Union established satellite states in Eastern Europe; Germany was divided; the Iron Curtain fell across Europe.', 'The Cold War did not begin at Yalta — it emerged gradually 1945–1947 as cooperation broke down.', 'Explain how Europe was divided after WWII and the concept of the Iron Curtain.'),
                   _t('Truman Doctrine and Marshall Plan', 'The Truman Doctrine (1947) committed the U.S. to containing communism; the Marshall Plan ($13 billion) rebuilt Western European economies and reduced communist appeal.', 'The Marshall Plan was both humanitarian and strategic — a prosperous Western Europe was less vulnerable to communist movements.', 'Explain the Truman Doctrine and Marshall Plan as containment strategy.'),
                   _t('NATO and the Arms Race', 'NATO (1949) was a collective security alliance against Soviet expansion; the Soviets tested their own atomic bomb (1949) and created the Warsaw Pact (1955); nuclear deterrence (MAD) prevented direct superpower conflict.', 'MAD (Mutually Assured Destruction) was a paradox — peace was maintained by the guaranteed destruction of both sides in any nuclear war.', 'Explain the formation of NATO and the logic of nuclear deterrence.'),
               ],
               [('Iron Curtain', 'Churchill\'s term for the division between Soviet-controlled Eastern Europe and the West.'),
                ('Truman Doctrine (1947)', 'U.S. policy committing to support nations threatened by communist takeover.'),
                ('Marshall Plan (1948)', 'U.S. economic aid program rebuilding Western Europe; reduced communist appeal.'),
                ('NATO (1949)', 'Western military alliance formed to counter Soviet expansion in Europe.'),
                ('MAD (Mutually Assured Destruction)', 'Nuclear deterrence strategy where any attack would result in total destruction of both sides.')],
               ['Explain the Iron Curtain and division of Europe.', 'Analyze the Marshall Plan as both economic aid and strategic policy.', 'Explain nuclear deterrence and its paradoxical logic.'],
               ['Comparing the Truman Doctrine and Marshall Plan as containment tools.', 'Analyzing why the Cold War never became "hot" in Europe.', 'Explaining the Soviet perspective on Western alliances.'],
               ['Khan Academy: Cold War Origins', 'Heimler\'s History: Cold War'],
               [('The Iron Curtain divided Europe between:', ['Soviet-dominated Eastern Europe and the democratic, capitalist West', 'Germany\'s eastern and western zones only', 'Catholic and Protestant regions', 'Industrial and agricultural zones', 'NATO and non-aligned nations']),
                ('The Marshall Plan was strategically valuable to the U.S. because:', ['A prosperous, stable Western Europe was less vulnerable to communist political movements', 'It gave the U.S. economic control of Europe', 'It was cheaper than military intervention', 'It repaid Europe for fighting in WWII', 'It created American military bases in Europe']),
                ('MAD (Mutually Assured Destruction) prevented direct nuclear conflict by:', ['Making nuclear war suicidal for both sides, deterring first strikes', 'Giving one superpower superiority', 'Creating a hot line for communication', 'Limiting nuclear weapons through treaties', 'Making conventional wars preferable']),
                ('NATO was formed in 1949 primarily in response to:', ['Soviet expansion in Eastern Europe and the Berlin Blockade', 'The Korean War', 'The Chinese Communist Revolution', 'Spread of communism in Western Europe', 'Nuclear weapons development']),
                ('The Truman Doctrine committed the U.S. to:', ['Supporting free peoples threatened by communist takeover anywhere in the world', 'Military intervention in the Soviet Union', 'Economic aid to all war-damaged nations', 'Nuclear weapons sharing with NATO allies', 'Liberating Eastern Europe from Soviet control']),
               ],
               [('Heimler\'s History: Cold War', 'Covers Iron Curtain, Marshall Plan, and NATO.', 'https://www.youtube.com/watch?v=xnsx6xwRchk')],
               ['What was the Iron Curtain?', 'How did the Marshall Plan serve as a containment strategy?', 'What is MAD and what is its paradox?']
            ),
            _l('Cold War Europe and Decolonization',
               [
                   _t('Cold War Crises in Europe', 'Berlin Blockade (1948–49), Hungarian Revolution (1956), building of Berlin Wall (1961), and Prague Spring (1968) demonstrated Soviet determination to maintain Eastern European control.', 'The Hungarian Revolution (1956) showed Western powers would not actually militarily intervene to liberate Eastern Europe despite rhetoric.', 'Trace key Cold War crises in Europe and explain Western limitations.'),
                   _t('Decolonization', 'European empires collapsed after WWII; India (1947), African nations (1960s), Algeria (1962, after brutal war); decolonization was driven by nationalist movements, Western hypocrisy after WWII, and European exhaustion.', 'Decolonization was not peaceful everywhere — Algeria, Kenya, and Vietnam involved prolonged, brutal wars against French and British power.', 'Explain why European empires decolonized after WWII.'),
                   _t('Guest Workers and Immigration', 'Post-war economic growth led European nations to recruit guest workers from Mediterranean and colonial areas (Turks to Germany, North Africans to France); many stayed, creating multiethnic societies that challenged national identities.', 'Guest worker programs were not intended to create permanent immigration — European governments assumed workers would return home.', 'Explain post-war immigration to Europe and its cultural and political consequences.'),
               ],
               [('Berlin Wall', 'Wall built by East Germany in 1961 to stop emigration to West; symbol of Cold War division.'),
                ('Prague Spring (1968)', 'Czechoslovak reform movement; crushed by Soviet invasion; confirmed Brezhnev Doctrine.'),
                ('Brezhnev Doctrine', 'Soviet policy of intervening in any socialist country that threatened to leave the Soviet bloc.'),
                ('decolonization', 'Process by which European colonial empires granted or lost independence to colonies, especially 1945–1970.'),
                ('guest workers (Gastarbeiter)', 'Migrant workers recruited for post-war European labor shortage; many settled permanently.')],
               ['Trace key Cold War crises in Europe.', 'Explain decolonization and its causes.', 'Analyze post-war immigration and its cultural consequences.'],
               ['Explaining why the Berlin Wall was built.', 'Comparing violent and peaceful decolonization.', 'Analyzing the cultural impact of immigration on European identity.'],
               ['Khan Academy: Decolonization', 'Heimler\'s History: Cold War Crises'],
               [('The Berlin Wall (1961) was built primarily to:', ['Stop the massive emigration of skilled East Germans to the West', 'Defend East Germany from Western attack', 'Separate East and West Berlin militarily', 'Mark the formal division of Germany', 'Prevent West German intelligence from entering East Berlin']),
                ('The Prague Spring (1968) was crushed by Soviet invasion because:', ['The Brezhnev Doctrine stated that the USSR would not allow socialist states to leave the Soviet bloc', 'Czechoslovakia had requested Soviet military assistance', 'The reforms threatened to bring Czechoslovakia into NATO', 'The U.S. encouraged Soviet intervention', 'Czechoslovakia attempted to form a military alliance with West Germany']),
                ('European decolonization accelerated after WWII because:', ['The war exhausted European powers, nationalist movements were strengthened, and WWII discredited racial hierarchy', 'Europeans chose to decolonize for moral reasons', 'The U.S. forced European powers to decolonize', 'Colonies had already achieved economic independence', 'The United Nations ended all colonial rule']),
                ('Guest worker programs in Europe created long-term consequences by:', ['Creating permanent immigrant communities as workers settled rather than returning home', 'Being fully integrated into European citizenship immediately', 'Remaining temporary as intended', 'Causing immediate cultural conflict', 'Being limited to European workers from poorer countries']),
                ('The Hungarian Revolution (1956) revealed that:', ['Western powers would not militarily intervene to liberate Eastern Europe despite anti-communist rhetoric', 'The Soviet Union was militarily weak', 'Hungary could successfully resist Soviet power', 'NATO would defend all European countries', 'The U.S. was willing to risk nuclear war for Eastern Europe']),
               ],
               [('Heimler\'s History: Cold War Crises and Decolonization', 'Covers Berlin Wall, Prague Spring, and decolonization.', 'https://www.youtube.com/watch?v=xnsx6xwRchk')],
               ['Why was the Berlin Wall built?', 'What was the Brezhnev Doctrine?', 'Why did decolonization accelerate after WWII?']
            ),
            _l('European Integration',
               [
                   _t('Origins of European Integration', 'The European Coal and Steel Community (ECSC, 1951) and EEC (Treaty of Rome, 1957) began economic integration to prevent another war; integration was driven by the vision that economic interdependence would make war irrational.', 'European integration was not primarily economic at its core — it was a peace project based on the belief that economic ties would prevent war.', 'Explain the origins and purposes of European integration.'),
                   _t('Development of the EU', 'The EU (formalized by Maastricht Treaty, 1992) created a single market, common currency (euro, 1999/2002), and supranational institutions (European Parliament, Commission, Court); membership expanded after 1989 to include Eastern Europe.', 'EU integration has always been contested — "Euroscepticism" exists in many member states, culminating in Brexit (2016).', 'Trace the development of European integration from ECSC to EU.'),
                   _t('Brexit and Challenges', 'Brexit (Britain leaving the EU, voted 2016, completed 2020) reflected tensions between national sovereignty and supranational integration; challenges include immigration, inequality, and populist nationalism.', 'Brexit was not solely about economics — sovereignty, cultural identity, and immigration anxiety drove the Leave vote.', 'Analyze Brexit as a symptom of tensions within European integration.'),
               ],
               [('European Coal and Steel Community (ECSC)', 'First European integration body (1951); pooled coal and steel production to prevent economic nationalism.'),
                ('Treaty of Rome (1957)', 'Founded the European Economic Community (EEC); created a common market.'),
                ('Maastricht Treaty (1992)', 'Created the European Union; established criteria for the euro and supranational institutions.'),
                ('euro', 'Common currency adopted by 20 EU member states; eliminates exchange rate barriers.'),
                ('Brexit', 'British withdrawal from the EU; voted in 2016 referendum; completed January 2020.')],
               ['Explain the origins and goals of European integration.', 'Trace the EU\'s development.', 'Analyze Brexit as a challenge to European integration.'],
               ['Evaluating economic and political benefits of EU membership.', 'Explaining the appeal of Euroscepticism.', 'Analyzing Brexit\'s causes and consequences.'],
               ['Khan Academy: EU', 'Heimler\'s History: European Integration'],
               [('The European Coal and Steel Community (1951) was designed primarily to:', ['Prevent future war by making French and German economies interdependent', 'Create a military alliance', 'Respond to the Marshall Plan', 'Compete economically with the United States', 'Integrate Europe under American leadership']),
                ('The Maastricht Treaty (1992) advanced European integration by:', ['Creating the EU with a common currency, open borders, and supranational institutions', 'Establishing NATO', 'Ending the Cold War', 'Creating a federal European state', 'Admitting Eastern European nations immediately']),
                ('Brexit revealed fundamental tensions about:', ['National sovereignty vs. supranational integration; cultural identity vs. immigration; economic elites vs. working class', 'Whether Britain was European geographically', 'Economic competition between Britain and the EU', 'Military integration vs. national armies', 'Immigration policy toward non-EU countries']),
                ('Euroscepticism argues that EU integration has gone too far by:', ['Limiting national sovereignty in economic and legal policy without sufficient democratic accountability', 'Making Europe too militarized', 'Being too favorable to poorer member states', 'Preventing trade with non-European countries', 'Concentrating all power in Germany and France']),
                ('The EU\'s single market benefited member states by:', ['Eliminating tariffs and allowing free movement of goods, services, capital, and people', 'Creating a single European government', 'Standardizing culture and language across Europe', 'Giving all members the same currency immediately', 'Eliminating all national governments']),
               ],
               [('Heimler\'s History: EU', 'Covers ECSC, Maastricht, and Brexit.', 'https://www.youtube.com/watch?v=xnsx6xwRchk')],
               ['What was the original purpose of European integration?', 'What did the Maastricht Treaty establish?', 'What tensions did Brexit reveal?']
            ),
            _l('The Fall of Communism and Contemporary Europe',
               [
                   _t('Collapse of Soviet Communism', 'Gorbachev\'s glasnost (openness) and perestroika (restructuring) loosened Soviet control; 1989 revolutions freed Eastern Europe; Berlin Wall fell November 9, 1989; USSR dissolved December 1991.', 'The USSR dissolved because of internal economic failure, not Western military pressure — Gorbachev\'s reforms inadvertently accelerated the collapse.', 'Explain why the Soviet Union collapsed.'),
                   _t('Post-Cold War Europe', 'NATO expanded eastward despite informal promises to the contrary; Yugoslavia broke apart in ethnic wars (1991–1999); the EU expanded to include former communist states; Germany reunified (1990).', 'NATO expansion eastward is a key Russian grievance underlying the 2022 Ukraine war — Europe after 1989 did not become fully peaceful.', 'Analyze the consequences of the Soviet collapse for European politics.'),
                   _t('Contemporary Challenges', 'Contemporary Europe faces: climate change, immigration and refugees, economic inequality, rise of populism and far-right parties, Russian aggression (Ukraine 2022), and questions about European identity and solidarity.', 'Populism challenges liberal democracy not by rejecting elections but by attacking independent institutions (courts, press) and minority rights.', 'Identify contemporary challenges facing Europe and connect them to historical patterns.'),
               ],
               [('glasnost', 'Gorbachev\'s policy of openness; allowed public discussion of Soviet problems.'),
                ('perestroika', 'Gorbachev\'s policy of restructuring the Soviet economy toward limited markets.'),
                ('1989 revolutions', 'Wave of peaceful (mostly) revolutions freeing Eastern European states from Soviet control.'),
                ('German reunification (1990)', 'Merger of West and East Germany after the fall of the Berlin Wall.'),
                ('populism', 'Political approach appealing to "the people" against corrupt elites; often authoritarian; rising in contemporary Europe.')],
               ['Explain why the Soviet Union collapsed.', 'Analyze post-Cold War European developments.', 'Identify contemporary challenges facing Europe.'],
               ['Explaining why 1989 was peaceful in most countries.', 'Connecting Yugoslavia\'s collapse to unresolved nationalist tensions.', 'Analyzing the rise of populism in contemporary Europe.'],
               ['Khan Academy: End of Cold War', 'Heimler\'s History: 1989 and Contemporary Europe'],
               [('The Soviet Union collapsed primarily because:', ['Internal economic stagnation and Gorbachev\'s reforms inadvertently undermined the regime\'s capacity to maintain control', 'Western military pressure forced it to spend itself into collapse', 'All Soviet citizens became anti-communist', 'NATO threatened invasion', 'China withdrew support from the USSR']),
                ('The 1989 revolutions in Eastern Europe were mostly peaceful because:', ['Gorbachev abandoned the Brezhnev Doctrine; Soviet troops did not intervene as they had in 1956 and 1968', 'Eastern European states had strong armies', 'Western Europe provided military support', 'The U.S. issued ultimatums to the Soviet Union', 'Communist leaders willingly surrendered power']),
                ('German reunification (1990) was significant because:', ['It ended the Cold War\'s most visible symbol in Europe and created the EU\'s most populous and economically powerful state', 'It restored the German Empire', 'It brought Germany into the Soviet bloc briefly', 'France strongly opposed it', 'It was rejected by East Germans in a referendum']),
                ('The rise of populism in contemporary Europe challenges democracy by:', ['Attacking independent institutions (courts, press) and minority rights while using democratic elections', 'Rejecting all elections as corrupt', 'Being exclusively a right-wing phenomenon', 'Being caused only by immigration', 'Being limited to Eastern European countries']),
                ('NATO expansion eastward after 1989 is significant because:', ['It is a key Russian grievance that contributed to the Ukraine conflict', 'It violated the UN Charter', 'It was immediately opposed by all Western European nations', 'It included Russia as a member', 'It was proposed by Gorbachev as a condition for German reunification']),
               ],
               [('Heimler\'s History: End of Cold War', 'Covers 1989 revolutions, Soviet collapse, and contemporary challenges.', 'https://www.youtube.com/watch?v=xnsx6xwRchk')],
               ['Why did the Soviet Union collapse?', 'Why were the 1989 revolutions mostly peaceful?', 'What contemporary challenges does Europe face?']
            ),
        ],
        'unit_qs': [
            ('The Marshall Plan served U.S. strategic interests by:', ['Rebuilding Western European economies to make them resistant to communist political movements', 'Establishing U.S. military bases', 'Creating economic dependency on the United States', 'Repaying European allies for WWI debts', 'Funding NATO directly']),
            ('The Berlin Wall symbolized the Cold War because:', ['It physically embodied the Iron Curtain dividing free and communist Europe', 'It was built by the United States to contain the Soviet Union', 'It separated Germany from Poland', 'It was the site of the most dangerous nuclear confrontation', 'It demonstrated NATO\'s military superiority']),
            ('The Prague Spring (1968) demonstrated that:', ['The Soviet Union would use military force to maintain control over Eastern European socialism', 'Czechoslovakia could reform communism successfully', 'NATO would defend all European democracies', 'The Cold War was ending', 'Soviet military power was declining']),
            ('Decolonization accelerated after WWII primarily because:', ['WWII discredited racial hierarchy and exhausted European powers; nationalist movements were strengthened', 'The U.S. forced decolonization', 'Colonies were no longer economically valuable', 'The UN mandated decolonization immediately', 'European populations demanded decolonization for moral reasons']),
            ('European integration was primarily a peace project because:', ['Economic interdependence was intended to make war between France and Germany irrational', 'Military integration was the main goal', 'Economic competition replaced political rivalry', 'The U.S. required integration as a condition for NATO', 'Integration created a single European army']),
            ('Brexit reflected tensions between:', ['National sovereignty and supranational EU integration; cultural identity and immigration', 'Economic and military priorities', 'Eastern and Western Europe within the EU', 'NATO and the EU\'s different memberships', 'Britain\'s desire to join the euro vs. keeping the pound']),
            ('The Soviet Union collapsed because of:', ['Internal economic stagnation and Gorbachev\'s reforms inadvertently undermining Communist Party control', 'Western military pressure through NATO', 'Successful Eastern European revolutions that spread to the USSR', 'American economic sanctions', 'Military failure in Afghanistan alone']),
            ('NATO expansion after 1989 created tensions because:', ['Russia viewed it as a security threat; it violated informal promises made during German reunification', 'It included former Soviet republics immediately', 'It was opposed by Germany and France', 'Eastern European nations refused to join', 'It required all members to give up nuclear weapons']),
            ('Contemporary European populism is most associated with:', ['Opposition to immigration, distrust of EU institutions, and nationalist identity politics', 'Support for more European integration', 'Economic socialism and redistribution', 'Military expansion and confrontation with Russia', 'Youth-led climate activism']),
            ('The 1989 revolutions were mostly peaceful because:', ['Gorbachev abandoned the Brezhnev Doctrine and Soviet troops did not intervene', 'Communist regimes immediately accepted democratic transition', 'Western Europe provided military guarantees', 'Eastern European militaries joined the revolution', 'The U.S. ultimatums prevented Soviet intervention']),
        ],
    },
]
