NAME        = 'AP® Music Theory'
ABBREV      = 'musth'
SLUG        = 'ap-music-theory'
COURSE_FILE = 'ap-music-theory.html'
ACCENT_COLOR = '#e879f9'

_Y = 'https://www.youtube.com/results?search_query=AP®+Music+Theory+'
_M = 'https://www.youtube.com/results?search_query=musictheory.net+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 6,
        'title': 'Harmony and Voice Leading III',
        'file': 'ap-music-theory-6-unit-6-harmony-and-voice-leading-iii.html',
        'desc': 'Augmented sixth chords, Neapolitan harmony, mode mixture, and extended harmonic analysis.',
        'gateway': [
            'Identify Italian, French, and German augmented sixth chords.',
            'Use borrowed chords (mode mixture) in analysis and composition.',
            'Analyze complex harmonic progressions including chromatic chords.',
            'Describe the function of the Neapolitan chord.',
        ],
        'lessons': [
            _l('Augmented Sixth Chords',
               [_t('Italian, French, and German 6th', 'All three augmented sixth chord types share ♭6̂ and ♯4̂ in the outer voices, creating the augmented sixth interval that expands to an octave (to 5̂) on the dominant. Italian 6th: ♭6̂, 1̂, ♯4̂. French adds 2̂. German adds ♭3̂ (often written as ♯2̂ to avoid parallel fifths).', 'Students confuse the three types; remember Ger+6 = It+6 + ♭3̂, and Fr+6 = It+6 + 2̂.', 'Label augmented sixth chords by type in a score; build each type above a given bass pitch.'),
                _t('Resolution of Aug6 Chords', 'The augmented sixth interval (♭6̂ to ♯4̂) expands outward by half step to the octave on 5̂ (both notes move to the dominant). The German +6 typically resolves via a cadential 6/4 to avoid parallel fifths with the bass.', 'Students resolve the ♯4̂ downward; it must move upward by half step to 5̂, while ♭6̂ moves downward by half step.', 'Resolve any augmented sixth chord correctly in SATB; identify the resolution in a score.')],
               [('augmented sixth chord', 'A chromatic predominant chord containing the interval of an augmented sixth between ♭6̂ and ♯4̂, which resolves to the dominant'),
                ('Italian +6', 'Contains ♭6̂, 1̂, and ♯4̂'),
                ('French +6', 'Contains ♭6̂, 1̂, 2̂, and ♯4̂'),
                ('German +6', 'Contains ♭6̂, 1̂, ♭3̂, and ♯4̂; resolves to V or V via I6/4')],
               ['Build and identify all three augmented sixth chord types', 'Resolve Aug6 chords to V', 'Explain why the German +6 needs a cadential 6/4'],
               ['Write an Italian +6 in D minor and resolve it', 'Identify the type of Aug6 in a Bach passage'],
               [('Write the German +6 in A minor and show its resolution to I6/4–V')],
               [('The augmented sixth interval in an Aug6 chord is formed between',
                 '♭6̂ and ♯4̂ (flat sixth and raised fourth scale degrees)',
                 ['1̂ and 7̂', '♭3̂ and ♯5̂', '2̂ and 7̂']),
                ('The French augmented sixth chord differs from the Italian +6 by adding',
                 'scale degree 2̂ (the supertonic)',
                 ['♭3̂', '♯5̂', '1̂']),
                ('Augmented sixth chords typically resolve to',
                 'the dominant (V) chord',
                 ['the tonic (I)', 'the subdominant (IV)', 'the supertonic (ii)']),
                ('The German +6 often resolves through I6/4 to avoid',
                 'parallel perfect fifths between the bass and another voice',
                 ['an augmented second in the soprano', 'voice crossing', 'a tritone in the outer voices']),
                ('In C minor, the Italian augmented sixth chord contains the notes',
                 'A♭, C, F♯',
                 ['A♭, C, G', 'A, C, F♯', 'A♭, E♭, F♯'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Aug6 Chords Explained', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['How do the three augmented sixth chords differ?', 'What is the function of the augmented sixth interval?', 'How does the German +6 avoid parallel fifths?']),
        ],
        'unit_qs': [
            ('Mode mixture uses chords from',
             'the parallel mode (major borrows from parallel minor, or vice versa)',
             ['the relative major or minor', 'a distant key', 'the subdominant key']),
            ('The Neapolitan chord in C minor (♭II6) contains',
             'D♭, F, A♭ — a major triad built on ♭2̂, typically in first inversion',
             ['C♭, E♭, G♭', 'D, F, A♭', 'D♭, F♭, A♭']),
            ('Common borrowed chords in a major key include',
             'iv, ♭VI, ♭VII — chords from the parallel minor',
             ['VI, III, VII from the relative minor', 'II♭, ♭III, ♭V only', 'Any chord with a sharp']),
            ('The French augmented sixth chord is unique because it',
             'contains two tritones (making it enharmonically equivalent to a dominant seventh chord)',
             ['has four notes like a seventh chord while the others have three', 'resolves to the tonic instead of the dominant', 'appears only in major keys']),
            ('The function of the Neapolitan (♭II) is',
             'predominant — it typically precedes the dominant or cadential 6/4',
             ['dominant function (like V)', 'tonic function (like I)', 'secondary dominant function']),
            ('An enharmonic modulation reinterprets a chord as',
             'belonging to a new key by respelling its notes (e.g., German +6 respelled as V7 in a new key)',
             ['using a pivot chord both keys share diatonically', 'abruptly jumping to an unrelated key', 'repeating the same chord in both keys']),
            ('The chord ♭VI (flat six) borrowed from the parallel minor in C major is',
             'A♭ major (A♭-C-E♭)',
             ['Ab minor', 'F minor', 'Bb major']),
            ('An augmented sixth chord is considered a "predominant" because',
             'it strongly intensifies the approach to the dominant through chromatic voice leading',
             ['it comes before the tonic in every progression', 'it shares two notes with the tonic triad', 'it is the most dissonant chord in tonal music']),
            ('When analyzing with Roman numerals, ♭VII in C major refers to',
             'B♭ major chord (borrowed from C minor)',
             ['B diminished', 'B major', 'A♭ major']),
            ('The difference between an appoggiatura and a suspension is that an appoggiatura is',
             'approached by leap (not prepared), while a suspension is held from the previous chord',
             ['resolved upward while a suspension resolves downward', 'always in the soprano voice', 'longer in duration than a suspension']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=rgaTLrZGlk0',
    },
    {
        'num': 7,
        'title': 'Harmony and Voice Leading IV',
        'file': 'ap-music-theory-7-unit-7-harmony-and-voice-leading-iv.html',
        'desc': 'Phrase structure, musical form, counterpoint fundamentals, and stylistic analysis.',
        'gateway': [
            'Identify period and sentence phrase structures.',
            'Recognize binary, ternary, rondo, and sonata forms.',
            'Describe species counterpoint principles.',
            'Analyze a short work discussing form, texture, and harmonic rhythm.',
        ],
        'lessons': [
            _l('Phrase Structure and Musical Form',
               [_t('Period and Sentence', 'A period consists of two phrases (antecedent + consequent): the antecedent ends on a half cadence, the consequent ends on an authentic cadence. A sentence has a basic idea, its repetition/variation, and a continuation fragmenting to a cadence.', 'Students label any two phrases as a period; a true period requires the antecedent to end on HC and the consequent on PAC or IAC.', 'Identify whether a passage is a period or sentence; label antecedent and consequent phrases.'),
                _t('Binary, Ternary, and Rondo Forms', 'Binary (AB or A:||:BA): two sections, often both repeated. Ternary (ABA): three sections, return of A after contrasting B. Rondo (ABACADA): theme A returns between contrasting episodes. Sonata form: exposition (I → V), development (fragmentation, modulation), recapitulation (returns to I).', 'Students call any three-part form a "ternary"; sonata form has exposition/development/recapitulation, which is different from simple ABA.', 'Label the formal sections of a short piece; identify cadence types at section boundaries.')],
               [('period', 'A musical structure of two related phrases: antecedent (ending on HC) + consequent (ending on authentic cadence)'),
                ('antecedent', 'First phrase of a period; ends on a half cadence or weak authentic cadence, creating a question-like feeling'),
                ('consequent', 'Second phrase of a period; ends on a perfect authentic cadence, providing closure'),
                ('binary form', 'Two-section form (AB); often both sections repeat'),
                ('ternary form', 'Three-section form (ABA or ABA\'); contrasting middle section between two outer sections')],
               ['Identify period structure in a four-measure excerpt', 'Distinguish binary from ternary form', 'Label sections of a short work with letters'],
               ['Analyze a Haydn minuet for phrase structure and form', 'Label all cadences in a period'],
               [('Analyze the given 8-measure excerpt: identify phrase structure, cadences, and whether it forms a period')],
               [('In a musical period, the antecedent phrase ends with',
                 'a half cadence (HC), creating an open, questioning feeling',
                 ['a perfect authentic cadence', 'a deceptive cadence', 'a plagal cadence']),
                ('Sonata form consists of three main sections:',
                 'Exposition, Development, and Recapitulation',
                 ['Introduction, Theme, and Coda', 'A, B, and A sections', 'Prelude, Fugue, and Postlude']),
                ('In a sentence phrase structure, the continuation section',
                 'fragments the basic idea and drives toward a cadence',
                 ['repeats the basic idea exactly', 'introduces completely new melodic material', 'begins with a modulation']),
                ('Rounded binary form (ABa) differs from simple binary because',
                 'the A section returns at the end of the B section (in abbreviated or full form)',
                 ['both sections are exactly the same length', 'the B section never modulates', 'the repeat signs are written differently']),
                ('The development section of sonata form is characterized by',
                 'fragmentation, sequence, and modulation through multiple keys',
                 ['stable tonic harmony throughout', 'introduction of new main themes', 'exact restatement of the exposition'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Musical Form Analysis', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What distinguishes a period from a sentence?', 'What are the three sections of sonata form?', 'How does rondo form work (ABACADA)?']),
        ],
        'unit_qs': [
            ('Polyphonic texture features',
             'two or more independent melodic lines heard simultaneously',
             ['a single melody with harmonic accompaniment', 'chords with no independent voice', 'unison singing or playing']),
            ('Homophonic texture is characterized by',
             'a primary melody supported by chords or subordinate accompaniment',
             ['multiple independent melodies of equal importance', 'one unaccompanied melodic line', 'alternating solo voices']),
            ('A fugue subject is',
             'the main melodic theme that is stated alone at the beginning and imitated by successive voices',
             ['a countermelody heard against the subject', 'the final cadence of the fugue', 'the key signature change between sections']),
            ('In first-species counterpoint, the rule is',
             'one note in the added voice against each note in the cantus firmus, using consonances',
             ['the added voice must move by step at all times', 'dissonances are freely used', 'parallel motion is required']),
            ('The perfect authentic cadence (PAC) requires',
             'V or V7 in root position moving to I in root position, with the soprano on scale degree 1̂',
             ['V in first inversion moving to I', 'V moving to I with soprano on 3̂', 'IV moving to I (plagal)']),
            ('Imitative polyphony means',
             'voices enter successively with the same or similar melodic idea',
             ['voices always move in parallel motion', 'only one voice is active at a time', 'the melody is always in the bass']),
            ('The recapitulation in sonata form differs from the exposition by',
             'presenting both theme groups in the tonic key rather than moving to the dominant',
             ['introducing new themes not heard in the exposition', 'ending on the dominant', 'always being shorter than the exposition']),
            ('A coda in musical form is',
             'a concluding section added after the main formal structure to reinforce the final cadence',
             ['the opening introduction before the first theme', 'the contrasting middle section', 'a development section']),
            ('Harmonic rhythm refers to',
             'the rate at which chords change in a passage',
             ['the rhythm of the melody', 'the tempo marking of the piece', 'the rhythmic pattern in the bass voice']),
            ('The difference between a PAC and an IAC (imperfect authentic cadence) is',
             'an IAC uses V→I but the soprano does not end on 1̂ (or the chords are inverted)',
             ['an IAC does not include the dominant chord', 'an IAC ends on the subdominant', 'a PAC requires the tonic chord in first inversion']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=rgaTLrZGlk0',
    },
    {
        'num': 8,
        'title': 'Exam Integration: Aural, Written, and Sight Singing',
        'file': 'ap-music-theory-8-unit-8-exam-integration-aural-written-and-sight-singing.html',
        'desc': 'Full exam preparation: sight singing, error detection, harmonic dictation, and free-response strategies.',
        'gateway': [
            'Sing a diatonic melody at sight using solfège or scale degree numbers.',
            'Detect melodic and harmonic errors in a short musical passage.',
            'Write a harmonic progression from dictation (identify chords by ear).',
            'Complete part writing given a bass line and figured bass.',
        ],
        'lessons': [
            _l('Sight Singing and Melodic Dictation',
               [_t('Sight Singing Strategies', 'Establish the key and beat, then sing using solfège (Do-Re-Mi) or scale degree numbers. Look ahead, maintain steady tempo, and connect melodic intervals to familiar songs for challenging leaps.', 'Students rush or stop when they see a difficult interval; preparation — identifying the key, clef, and first pitch — prevents most errors.', 'Sing prepared melodies; sight sing unfamiliar diatonic melodies; identify errors in a given melody.'),
                _t('Melodic Dictation Process', 'Listen for: (1) the starting pitch\'s scale degree, (2) melodic contour, (3) rhythmic patterns, (4) specific intervals. Write what you hear in fragments, filling gaps on subsequent hearings.', 'Students try to transcribe everything in one listening; the multi-pass approach (rhythm first, then pitches) is more reliable.', 'Transcribe a short melody played 3 times; notate rhythm and pitches correctly.')],
               [('solfège', 'A system of syllables (Do, Re, Mi, Fa, Sol, La, Ti) assigned to scale degrees for sight singing'),
                ('dictation', 'Writing down music as it is played — can be melodic, rhythmic, or harmonic'),
                ('error detection', 'Identifying discrepancies between a performed melody and the printed score'),
                ('tonic sol-fa', 'A moveable-do system where "Do" is always the tonic regardless of key')],
               ['Sing diatonic melodies at sight', 'Transcribe a short melody from dictation', 'Detect errors in a melody performed differently from the score'],
               ['Practice sight singing 8-measure melodies in major and minor keys', 'Do 3 rounds of 4-measure melodic dictation exercises'],
               [('Sight sing the following melody in G major at m.m. = 72')],
               [('The most reliable first step in sight singing a new melody is',
                 'identifying the key and time signature, then finding and singing the tonic pitch',
                 ['singing as fast as possible to get through mistakes quickly', 'memorizing the melody before performing', 'starting on whatever pitch feels comfortable']),
                ('In moveable-do solfège, scale degree 5̂ is always sung as',
                 'Sol',
                 ['La', 'Do', 'Mi']),
                ('A melodic dictation exercise typically involves',
                 'hearing the melody multiple times and notating it with correct rhythm and pitch',
                 ['harmonizing a given melody', 'identifying the key only from the first note', 'writing lyrics to match the melody']),
                ('When error detection asks you to find a rhythmic error, you should',
                 'follow the score while listening and mark where the performed rhythm deviates from what is written',
                 ['rewrite the melody in correct notation', 'identify the key first before checking rhythm', 'listen for wrong pitches only']),
                ('Interval recognition in sight singing is improved by',
                 'associating each interval with a familiar song (e.g., P5 = "Star Wars" opening)',
                 ['practicing only stepwise melodies', 'avoiding leaps larger than a third', 'always using a piano as a reference'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Sight Singing for AP® Exam', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What is the multi-pass approach to melodic dictation?', 'How do you establish the key before sight singing?', 'What is error detection and how is it tested on the AP® exam?']),

            _l('Harmonic Dictation and Part Writing',
               [_t('Harmonic Dictation Strategies', 'Listen for: (1) bass line movement, (2) chord quality (major, minor, diminished), (3) inversions, (4) non-chord tones. Work from the bass up. Identify cadences first (ends of phrases), then fill in interior chords.', 'Students try to identify every chord on first hearing; identifying the bass line, cadence types, and phrase endings first makes chord identification easier.', 'Complete a harmonic dictation by identifying chord quality, root, and inversion from recorded examples.'),
                _t('Free Response Part Writing', 'For part writing questions: check soprano for range/leaps, space bass-tenor 1.5 octave max, double the root in root-position triads, resolve the leading tone (7̂→1̂) and the chordal seventh (down by step), avoid parallel 5ths/8ths. Write I-V7-I with correct voice leading as a warm-up pattern.', 'Students forget to check all four voices for errors; a systematic check (parallel fifths, leading tone resolution, spacing, range) after writing prevents lost points.', 'Complete a short part-writing question with figured bass or Roman numerals; check self for all common errors.')],
               [('harmonic dictation', 'Writing down the chords of a progression as heard — identifying root, quality, and inversion'),
                ('part writing', 'Writing all four SATB voices to realize a given harmonic progression or figured bass'),
                ('resolution', 'The movement of a dissonant or unstable tone to a consonant or stable one'),
                ('voice crossing', 'When a lower voice moves above a higher voice or vice versa — a voice-leading error to avoid')],
               ['Identify chords from a recorded 4-chord progression', 'Complete an SATB part-writing exercise from Roman numerals', 'Check own part writing for all common errors'],
               ['Do 5 harmonic dictation exercises using I, IV, V, ii, vi', 'Complete a part-writing realization of a Bach chorale opening'],
               [('Complete the following part-writing exercise: given Bass E, F, G, C; add the upper voices for I6-IV-V-I in C major')],
               [('In harmonic dictation, the best strategy for identifying chord inversions is to',
                 'listen carefully to the bass line and determine which chord tone is in the bass',
                 ['count the number of notes in the chord', 'identify the soprano line first', 'wait until all hearings are complete to write anything']),
                ('When resolving V7 → I, the chordal seventh must',
                 'resolve down by step to the third of the tonic chord',
                 ['resolve up by step to the octave', 'stay in place', 'leap to the tonic note']),
                ('Voice crossing is considered a voice-leading error because',
                 'it makes voices difficult to follow independently and often produces dissonance',
                 ['it always creates parallel fifths', 'it breaks the key signature', 'it is impossible on keyboard instruments']),
                ('The fastest way to check for parallel fifths after writing SATB is',
                 'compare each pair of voices (SATB × 6 pairs) at consecutive beats and verify no consecutive perfect fifths appear',
                 ['check only the soprano and bass', 'check only adjacent voices', 'count all the intervals in the final chord']),
                ('After completing a part-writing exercise, the leading tone (7̂) must',
                 'resolve upward by half step to the tonic (1̂) in the same voice',
                 ['stay in place to avoid leaps', 'resolve downward to 5̂', 'jump to 3̂ for good voice leading'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Harmonic Dictation Strategies', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What is the multi-step strategy for harmonic dictation?', 'List five things to check after completing a part-writing exercise', 'How does the chordal seventh of V7 resolve?']),
        ],
        'unit_qs': [
            ('The AP® Music Theory exam includes which of the following aural skill sections?',
             'Sight singing and harmonic dictation (identifying chords by ear)',
             ['Only written theory questions with no aural component', 'Composition of an original piece', 'Performance on a chosen instrument']),
            ('In sight singing, a "prepared" performance means',
             'you have studied the melody and practiced difficult intervals before performing',
             ['you sang it for the first time without looking at the score', 'you memorized the melody completely', 'you used a piano to learn every note']),
            ('Scale degree 7̂ (the leading tone) in a minor key requires',
             'raising it by a half step (using the harmonic minor scale) to create a strong pull to 1̂',
             ['lowering it by a half step', 'leaving it as in the natural minor scale always', 'omitting it from all chords']),
            ('The most common cadence used at the end of a complete musical idea (full close) is',
             'the perfect authentic cadence (PAC): V or V7 in root position → I in root position, soprano on 1̂',
             ['the half cadence (ends on V)', 'the plagal cadence (IV → I)', 'the deceptive cadence (V → vi)']),
            ('Harmonic rhythm in a Bach chorale typically',
             'changes chords on every beat or every two beats, creating steady harmonic motion',
             ['changes chords only at the beginning and end of phrases', 'is always slower than the melodic rhythm', 'uses one chord per measure exclusively']),
            ('When sight singing in a minor key, which scale (natural, harmonic, or melodic) is most commonly used?',
             'Melodic minor (ascending: raised 6̂ and 7̂; descending: natural minor) for smooth melodic lines',
             ['Only natural minor', 'Only harmonic minor', 'The same pattern as major always']),
            ('A modulation to the dominant (V) is confirmed in a score by',
             'a cadence in the new key (the fifth scale degree of the original key), often preceded by its own leading tone',
             ['the use of any chromatic note', 'the return of the opening theme', 'a change in time signature']),
            ('Figured bass realization requires the performer to',
             'add upper voices above the bass note using the intervals specified by the figures',
             ['improvise freely with no constraints', 'play only the bass note and its octave', 'write out chords in modern notation before playing']),
            ('Part writing rules about spacing state that',
             'the distance between tenor and bass may be up to an octave, soprano and alto up to an octave, but tenor and bass together with alto may span up to 1.5 octaves',
             ['all voices must be within one octave of each other', 'soprano and bass may be any distance apart', 'tenor must always be adjacent to alto']),
            ('Before sight singing, the singer should establish the key by',
             'singing the tonic triad or scale from the given pitch, then finding the starting note\'s scale degree',
             ['humming any comfortable pitch', 'reading the time signature only', 'looking at the final bar line first']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=rgaTLrZGlk0',
    },
]
