NAME        = 'AP® Music Theory'
ABBREV      = 'musth'
SLUG        = 'ap-music-theory'
COURSE_FILE = 'ap-music-theory.html'
ACCENT_COLOR = '#e879f9'

_Y = 'https://www.youtube.com/results?search_query=AP®+Music+Theory+'
_M = 'https://www.youtube.com/results?search_query=musictheory.net+'

COURSE_QS = [
    ('The treble clef (G clef) circles around the line that represents',
     'the note G4 (the G above middle C)',
     ['Middle C (C4)', 'D4', 'F4']),
    ('A major scale is constructed using the pattern of whole and half steps',
     'W-W-H-W-W-W-H (starting from the tonic)',
     ['W-H-W-W-H-W-W', 'H-W-W-W-H-W-W', 'W-W-W-H-W-W-H']),
    ('A minor scale (natural minor) uses the pattern',
     'W-H-W-W-H-W-W',
     ['W-W-H-W-W-W-H (same as major)', 'H-W-W-H-W-W-W', 'W-H-W-W-W-H-W']),
    ('The key signature with four sharps (F#, C#, G#, D#) corresponds to the key of',
     'E major (or C# minor)',
     ['A major', 'D major', 'B major']),
    ('A perfect fifth interval spans',
     '7 half steps (e.g., C to G)',
     ['5 half steps', '8 half steps', '6 half steps']),
    ('A tritone (augmented fourth / diminished fifth) consists of',
     '6 half steps — exactly half an octave, creating strong dissonance',
     ['5 half steps', '7 half steps', '4 half steps']),
    ('In 4/4 time (common time), the quarter note receives',
     'one beat, and there are four beats per measure',
     ['two beats', 'half a beat', 'four beats and a whole note gets two']),
    ('A triad in root position has the root in the bass, with intervals of',
     'a third and a fifth above the root (e.g., C-E-G)',
     ['a fourth and a sixth above the root', 'a second and a fourth above the root', 'a third and a sixth above the root']),
    ('The dominant chord (V) in a major key typically contains',
     'scale degrees 5, 7, and 2 (a major triad, often with an added seventh)',
     ['scale degrees 1, 3, and 5 (the tonic triad)', 'scale degrees 4, 6, and 1 (the subdominant)', 'scale degrees 2, 4, and 6 (the supertonic)']),
    ('An authentic cadence (V → I) is considered',
     'a strong, conclusive cadence that creates a sense of resolution and closure',
     ['a half cadence ending on the dominant', 'a plagal cadence (IV → I)', 'an imperfect cadence with an inverted chord']),
    ('Parallel fifths (consecutive perfect fifths between two voices) are avoided in',
     'common-practice voice leading because they weaken the independence of the voices',
     ['all music including 20th-century styles', 'only keyboard music', 'only harmonic minor progressions']),
    ('The term "soprano" in SATB four-part writing refers to',
     'the highest voice part, with typical range about C4 to G5',
     ['the second-highest voice (alto)', 'the lowest male voice', 'a solo female voice of any range']),
    ('In Roman numeral analysis, a chord labeled "viio" in a major key is',
     'a diminished triad built on the seventh scale degree (e.g., B-D-F in C major)',
     ['a major triad on the seventh degree', 'an augmented triad on the leading tone', 'a dominant seventh chord']),
    ('Compound meter has beats that are divided into',
     'groups of three (e.g., 6/8 has two main beats each divided into three eighth notes)',
     ['groups of two (like simple meter)', 'four beats per measure always', 'unequal divisions of five or seven']),
    ('Modulation in tonal music refers to',
     'a change of tonal center (key) that is confirmed by a cadence in the new key',
     ['a change of tempo within the same key', 'the use of chromatic notes without key change', 'alternating between two modes (major/minor)']),
    ('Secondary dominants are chords that',
     'temporarily tonicize a non-tonic chord by acting as the V (or V7) of that chord within the original key',
     ['replace the dominant in a cadence', 'use only notes from the current scale', 'appear only in minor keys']),
    ('The harmonic minor scale differs from the natural minor scale by',
     'raising the 7th scale degree by a half step, creating a leading tone and a V major chord',
     ['lowering the 6th scale degree', 'raising both the 6th and 7th degrees', 'using the same pitch material as major']),
    ('A suspension (4-3, 7-6, 9-8) in counterpoint involves',
     'holding a note from the previous chord into a new harmony where it creates dissonance, then resolving down by step',
     ['moving a voice up by step to create tension', 'skipping to a dissonant note then holding', 'changing the bass while the upper voices hold']),
    ('Enharmonic equivalents are pitches that',
     'sound identical (same frequency) but are written differently (e.g., C# and Db)',
     ['are exactly one octave apart', 'share the same letter name but different accidentals in the same octave', 'are a tritone apart']),
    ('A Picardy third refers to',
     'the use of a major tonic chord (raised 3rd) at the final cadence of a piece in minor key',
     ['the use of a minor chord in a major-key ending', 'a modulation to the relative major at the end', 'a chromatic passing tone in the bass']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
    {
        'num': 1,
        'title': 'Music Fundamentals I',
        'file': 'ap-music-theory-1-unit-1-music-fundamentals-i.html',
        'desc': 'Staff notation, clefs, pitch names, accidentals, major and minor scales, and key signatures.',
        'gateway': [
            'Read treble and bass clef notation fluently.',
            'Construct major and natural/harmonic/melodic minor scales from any starting pitch.',
            'Identify and write key signatures with up to 7 sharps or flats.',
            'Apply accidentals (sharps, flats, naturals, double sharps/flats) correctly.',
        ],
        'lessons': [
            _l('Staff, Clefs, and Pitch Notation',
               [_t('Reading the Staff', 'The staff has five lines and four spaces; pitch names depend on which clef is used. Treble clef circles G4; bass clef marks F3.', 'Students mix up which line the clef marks; treble clef circles the second line (G), not the first.', 'Identify any note on treble or bass staff; write a given pitch name on the staff.'),
                _t('Ledger Lines and Middle C', 'Ledger lines extend the staff above and below; middle C (C4) sits on a ledger line just below the treble staff and just above the bass staff.', 'Students forget that C4 is on a ledger line in both treble and bass clef, not on a main staff line.', 'Identify notes on ledger lines; write C4 in both clefs.')],
               [('treble clef', 'G clef: circles around the second line, identifying it as G4'),
                ('bass clef', 'F clef: two dots around the fourth line, identifying it as F3'),
                ('ledger line', 'Short line added above or below the staff for notes outside its range'),
                ('middle C', 'C4 — the C in the middle of the piano keyboard; written on a ledger line in both treble and bass clef')],
               ['Identify any note on treble and bass staff', 'Write notes in treble and bass clef from letter names', 'Explain the function of ledger lines'],
               ['Identify pitch names from notation', 'Write given pitches on a staff', 'Recognize clef symbols and their reference pitches'],
               ['Write all C pitches on a grand staff', 'Name every note in a short melody in treble and bass clef'],
               [('On the treble staff, the note on the first line from the bottom is',
                 'E4',
                 ['G4', 'F4', 'D4']),
                ('Middle C (C4) in treble clef appears on',
                 'a ledger line below the staff',
                 ['the first line of the staff', 'the third space', 'a ledger line above the staff']),
                ('The bass clef identifies which line as F?',
                 'The fourth line from the bottom',
                 ['The second line', 'The third line', 'The first line']),
                ('A flat sign before a note lowers its pitch by',
                 'one half step',
                 ['one whole step', 'two half steps', 'depends on the key signature']),
                ('If the key signature has two flats, the flats are',
                 'B♭ and E♭',
                 ['F♯ and C♯', 'B♭ and A♭', 'E♭ and A♭'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Staff and Clef Review', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['Name all lines and spaces of the treble and bass staff', 'Write C major scale in treble clef from memory', 'What does a key signature tell you?']),

            _l('Major Scales and Key Signatures',
               [_t('Major Scale Construction', 'A major scale follows W-W-H-W-W-W-H. Starting on any pitch and applying this pattern gives that major scale.', 'Students forget the exact placement of the half steps (between 3-4 and 7-8). Counting semitones rather than using the pattern leads to errors.', 'Build any major scale from a given starting pitch; identify the key from a key signature.'),
                _t('Circle of Fifths and Key Signatures', 'Moving clockwise around the circle of fifths adds sharps; counter-clockwise adds flats. The mnemonic for sharps: F C G D A E B; for flats: B E A D G C F.', 'Students confuse the order of sharps and flats; each new key adds exactly one sharp/flat in a specific order.', 'Identify the major key from any key signature; write the correct key signature given a key name.')],
               [('whole step', 'Two half steps; skips one key on the keyboard'),
                ('half step', 'The smallest interval; adjacent keys on the keyboard'),
                ('key signature', 'Sharps or flats placed at the beginning of a staff to indicate the prevailing key'),
                ('circle of fifths', 'Diagram showing all 12 major (and minor) keys arranged by the number of sharps/flats')],
               ['Construct major scales using the W-W-H-W-W-W-H pattern', 'Identify any major key from its key signature', 'Write correct key signatures for any major key'],
               ['Write the key signature for F major', 'Identify the key from 3 sharps', 'Spell a D major scale'],
               ['Write all major scales starting from C, G, D, A, E, B, F, B♭, E♭, A♭, D♭, G♭'],
               [('The key signature for G major contains',
                 'F♯',
                 ['C♯', 'B♭', 'F♭']),
                ('How many flats does E♭ major have?',
                 '3 (B♭, E♭, A♭)',
                 ['2', '4', '1']),
                ('The order of sharps added to key signatures is',
                 'F, C, G, D, A, E, B',
                 ['B, E, A, D, G, C, F', 'C, G, D, A, E, B, F', 'F, G, C, D, A, E, B']),
                ('In D major, scale degree 7 is',
                 'C♯',
                 ['C♮', 'D', 'B']),
                ('The relative minor of C major is',
                 'A minor (shares the same key signature)',
                 ['E minor', 'G minor', 'D minor'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Circle of Fifths Explained', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['Build F major, B♭ major, and A major scales', 'Identify the key from 4 flats', 'What is the relative minor of E♭ major?']),
        ],
        'unit_qs': [
            ('The treble clef establishes which line as which note?',
             'The second line as G4',
             ['The first line as E4', 'The third line as B4', 'The middle line as C4']),
            ('The interval between adjacent keys on the piano (e.g., C to C#) is',
             'a half step (semitone)',
             ['a whole step', 'a minor second only in the context of a scale', 'a major second']),
            ('A key signature with 3 sharps indicates the key of',
             'A major (or F# minor)',
             ['G major', 'D major', 'E major']),
            ('The harmonic minor scale raises which scale degree compared to natural minor?',
             'The 7th scale degree by a half step (creating a leading tone)',
             ['The 6th scale degree', 'The 3rd scale degree', 'The 2nd and 6th scale degrees']),
            ('Relative major and minor keys share',
             'the same key signature (same pitches, different tonal center)',
             ['the same starting pitch (tonic)', 'the same scale pattern', 'the same harmonic functions']),
            ('A double sharp raises a pitch by',
             'two half steps (one whole step)',
             ['one half step only', 'a minor third', 'three half steps']),
            ('In 4/4 time, a dotted quarter note receives',
             '1.5 beats (the dot adds half the note\'s value)',
             ['2 beats', '1 beat', '3 beats']),
            ('The subdominant scale degree (4̂) in C major is',
             'F',
             ['G', 'D', 'E']),
            ('The dominant (5̂) scale degree forms a __________ above the tonic.',
             'perfect fifth',
             ['major third', 'minor seventh', 'tritone']),
            ('The natural minor scale uses the same pitches as its',
             'relative major scale but starts and ends on the 6th degree of that major scale',
             ['parallel major scale but with a flatted 3rd', 'tonic major scale with all degrees lowered by a half step', 'harmonic minor scale without the raised 7th']),
        ],
    },
    {
        'num': 2,
        'title': 'Music Fundamentals II',
        'file': 'ap-music-theory-2-unit-2-music-fundamentals-ii.html',
        'desc': 'Intervals, triads (major, minor, augmented, diminished), and seventh chord quality identification.',
        'gateway': [
            'Identify and construct all diatonic intervals (unison through octave).',
            'Distinguish perfect, major, minor, augmented, and diminished intervals.',
            'Build major, minor, augmented, and diminished triads.',
            'Identify seventh chord qualities (MM7, Mm7, mm7, dm7, dd7).',
        ],
        'lessons': [
            _l('Intervals',
               [_t('Measuring Intervals', 'An interval is the distance between two pitches. Count the number of letter names (including both notes) for the generic name; then count semitones to determine quality (perfect, major, minor, etc.).', 'Students count only the space between notes, forgetting to include both endpoints — C to E is a third, not a second.', 'Identify intervals by name and quality from notation or letter names.'),
                _t('Interval Quality', 'Perfect intervals (unison, 4th, 5th, octave) can be diminished or augmented. Major/minor intervals (2nd, 3rd, 6th, 7th) can be major, minor, diminished, or augmented. A diminished interval is one half step smaller than perfect/minor; augmented is one half step larger than perfect/major.', 'Students confuse the rules for perfect vs. major/minor intervals; perfect intervals cannot be "major" or "minor."', 'Classify an interval as P, M, m, A, or d; invert intervals correctly (P stays P, M↔m, A↔d).')],
               [('interval', 'The distance in pitch between two notes'),
                ('perfect interval', 'Intervals of unison, 4th, 5th, and octave; associated with a stable, open sound'),
                ('major interval', 'Interval that is a half step larger than a minor interval of the same number'),
                ('tritone', 'The augmented 4th or diminished 5th — exactly 6 half steps; highly dissonant')],
               ['Name any interval on sight', 'Construct a requested interval above or below a given pitch', 'Invert intervals correctly'],
               ['Invert a major 3rd', 'Build a perfect 5th above D', 'Identify a diminished 7th'],
               ['Fill an interval identification worksheet covering all diatonic and chromatic intervals'],
               [('From C up to A is a',
                 'major sixth (9 semitones, 6 letter names)',
                 ['minor sixth', 'major seventh', 'perfect fifth']),
                ('A minor 7th above G is',
                 'F',
                 ['F#', 'Gb', 'E']),
                ('The inversion of a major third is a',
                 'minor sixth',
                 ['major sixth', 'minor third', 'perfect fifth']),
                ('A tritone above C is',
                 'F# (or Gb) — 6 half steps',
                 ['G', 'F', 'E']),
                ('The interval C to G is a',
                 'perfect fifth',
                 ['major fifth', 'augmented fourth', 'minor sixth'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Intervals Tutorial', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What is the difference between a major and minor interval?', 'Construct a diminished 5th above B', 'Why is the tritone considered dissonant?']),

            _l('Triads and Seventh Chords',
               [_t('Triad Quality', 'Triads are three-note chords built in thirds. Quality is determined by the intervals: major (M3+m3), minor (m3+M3), augmented (M3+M3), diminished (m3+m3).', 'Students rely only on "major sounds happy, minor sounds sad" — on the exam, they must build and identify triads by interval content, not by listening.', 'Build and identify major, minor, augmented, and diminished triads from any root.'),
                _t('Seventh Chords', 'A seventh chord adds a 7th above the root to a triad. Types: major-major (MM7, e.g., C-E-G-B), dominant (Mm7, e.g., G-B-D-F), minor-minor (mm7), half-diminished (dm7 or ø7), fully-diminished (dd7 or °7).', 'Students confuse the half-diminished (dm7) and fully-diminished (°7) seventh chords; the former has a diminished triad plus a minor 7th, the latter has a diminished triad plus a diminished 7th.', 'Identify seventh chord quality from notation; build any requested seventh chord.')],
               [('major triad', 'Root + major third + perfect fifth (M3 + m3)'),
                ('minor triad', 'Root + minor third + perfect fifth (m3 + M3)'),
                ('diminished triad', 'Root + minor third + diminished fifth (m3 + m3)'),
                ('dominant seventh', 'Major triad + minor seventh (Mm7); the chord most strongly implying resolution to tonic'),
                ('leading tone', 'Scale degree 7 — a half step below the tonic, creates strong pull toward resolution')],
               ['Build major, minor, diminished, and augmented triads', 'Identify seventh chord types', 'Explain why the dominant seventh chord creates tension'],
               ['Identify chord quality from a score excerpt', 'Build a Mm7 chord above D', 'Spell a fully-diminished seventh chord on B'],
               ['Analyze chord quality for all triads built on each scale degree of C major'],
               [('The D minor triad contains',
                 'D, F, A',
                 ['D, F#, A', 'D, F, Ab', 'D, Fb, A']),
                ('A dominant seventh chord (Mm7) built on G contains',
                 'G, B, D, F',
                 ['G, B♭, D, F', 'G, B, D, F#', 'G, B, D♭, F']),
                ('An augmented triad is made of',
                 'two major thirds stacked (M3+M3)',
                 ['two minor thirds stacked', 'a major third plus a diminished fifth', 'a perfect fourth plus a major third']),
                ('In the key of C major, the chord built on scale degree ii is',
                 'D minor (d, f, a)',
                 ['D major', 'D diminished', 'D augmented']),
                ('A fully-diminished seventh chord contains',
                 'three stacked minor thirds (m3+m3+m3)',
                 ['a diminished triad plus a major seventh', 'two minor thirds and one major third', 'a minor triad plus a diminished seventh'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Seventh Chord Types', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What are the four triad qualities?', 'Build a half-diminished seventh chord on B', 'How do you distinguish Mm7 from mm7?']),
        ],
        'unit_qs': [
            ('The interval from C to E is a',
             'major third (4 half steps)',
             ['minor third', 'perfect third', 'augmented third']),
            ('A major triad built on F contains',
             'F, A, C',
             ['F, Ab, C', 'F, A, C#', 'F, A♭, C♭']),
            ('The dominant seventh chord in C major is built on',
             'G (the fifth scale degree): G-B-D-F',
             ['C (tonic): C-E-G-B', 'F (subdominant): F-A-C-E', 'D (supertonic): D-F-A-C']),
            ('A diminished triad differs from a minor triad in that it has a',
             'diminished fifth instead of a perfect fifth',
             ['minor third instead of major third', 'augmented fourth instead of perfect fifth', 'major third']),
            ('The interval of a perfect 4th contains',
             '5 half steps',
             ['4 half steps', '6 half steps', '7 half steps']),
            ('Inversion of a minor 3rd produces a',
             'major 6th',
             ['minor 6th', 'major 3rd', 'perfect 4th']),
            ('The leading tone of G major is',
             'F♯',
             ['G♯', 'F♮', 'E♯']),
            ('A half-diminished seventh chord (ø7) is spelled as',
             'a diminished triad plus a minor 7th',
             ['a diminished triad plus a diminished 7th (that\'s fully diminished)', 'a minor triad plus a major 7th', 'a major triad plus a minor 7th']),
            ('The chord built on scale degree VII in a major key is',
             'a diminished triad',
             ['a major triad', 'a minor triad', 'an augmented triad']),
            ('Two notes played simultaneously form a',
             'harmonic interval (also called a dyad)',
             ['melodic interval', 'chord', 'polyphonic texture']),
        ],
    },
    {
        'num': 3,
        'title': 'Music Fundamentals III',
        'file': 'ap-music-theory-3-unit-3-music-fundamentals-iii.html',
        'desc': 'Rhythm, meter, beat subdivision, syncopation, and score reading fundamentals.',
        'gateway': [
            'Identify and notate rhythmic values from whole notes to sixty-fourth notes.',
            'Understand simple and compound meter signatures.',
            'Recognize and write syncopated rhythms.',
            'Conduct a basic 4/4 pattern and identify beat groupings.',
        ],
        'lessons': [
            _l('Note Values and Rhythmic Notation',
               [_t('Note Duration Relationships', 'Each note value is half the duration of the one above: whole = 2 halves = 4 quarters = 8 eighths = 16 sixteenths. A dot adds half the note\'s own value.', 'Students forget that a dotted half note = 3 beats (not 2.5) in 4/4 time; a dot is always + half of the original value.', 'Write correct rhythmic notation for a given beat count; identify note values in a score.'),
                _t('Simple vs. Compound Meter', 'In simple meter, the beat divides into 2 (e.g., 4/4, 3/4, 2/4). In compound meter, the beat divides into 3 (e.g., 6/8, 9/8, 12/8). The top number of a compound meter gives the number of divisions, not beats.', 'Students read 6/8 as "six beats per measure"; it actually has two dotted-quarter beats, each divided into three eighth notes.', 'Identify simple or compound meter from a time signature; determine how many beats are in a measure.')],
               [('simple meter', 'Meter where the beat divides into 2 equal parts (top numbers: 2, 3, or 4)'),
                ('compound meter', 'Meter where the beat divides into 3 equal parts (top numbers: 6, 9, or 12)'),
                ('syncopation', 'Accenting a normally weak beat or the off-beat, creating rhythmic tension'),
                ('tie', 'A curved line connecting two notes of the same pitch, combining their durations')],
               ['Determine the beat value and beat count in any meter', 'Write rhythms using notes and rests', 'Distinguish simple from compound meter'],
               ['Clap and count a 6/8 excerpt', 'Rewrite a simple meter rhythm in compound meter', 'Write a measure of syncopated 4/4'],
               ['Transcribe a 4-measure rhythm by ear using eighth note level precision'],
               [('In 6/8 time, the main beat unit is the',
                 'dotted quarter note (divides into three eighth notes)',
                 ['quarter note', 'half note', 'eighth note']),
                ('A dotted quarter note in 4/4 time receives',
                 '1.5 beats',
                 ['1 beat', '2 beats', '3 beats']),
                ('Syncopation typically involves',
                 'emphasizing a weak beat or the off-beat within a measure',
                 ['slowing the tempo significantly', 'adding extra beats to a measure', 'playing without a steady pulse']),
                ('In 3/4 time, each measure contains',
                 '3 quarter-note beats',
                 ['3 half-note beats', '6 eighth-note beats as main beats', '4 quarter-note beats']),
                ('Which note value receives the beat in 9/8?',
                 'The dotted quarter note (three eighth notes per beat, three beats per measure)',
                 ['The eighth note', 'The half note', 'The quarter note'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Compound Meter Tutorial', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['How does simple meter differ from compound meter?', 'How many dotted-quarter beats are in a measure of 12/8?', 'What is syncopation and give an example?']),
        ],
        'unit_qs': [
            ('In 4/4 time, a dotted half note receives',
             '3 beats',
             ['2 beats', '4 beats', '1.5 beats']),
            ('A measure of 9/8 contains how many main beats?',
             '3 dotted-quarter beats',
             ['9 eighth-note beats', '3 half beats', '6 beats']),
            ('A tie connects two notes of the same pitch to',
             'extend the duration of the first note without re-articulating',
             ['create a slur effect', 'lower the second note a half step', 'add emphasis (accent) to both notes']),
            ('The beat in 2/2 (cut time) is the',
             'half note (two half-note beats per measure)',
             ['quarter note', 'whole note', 'eighth note']),
            ('An eighth note rest looks like',
             'a small 7-shaped symbol (𝄾)',
             ['a solid filled notehead', 'a whole rest hanging below a line', 'a slanted line with flags']),
            ('Hemiola is a rhythmic device where',
             'a rhythm of 3 beats is superimposed over a 2-beat framework (or vice versa)',
             ['two voices play identical rhythms one beat apart', 'notes are played faster than written', 'syncopation is used in every measure']),
            ('In 12/8 time, there are',
             '4 dotted-quarter beats per measure',
             ['12 eighth-note main beats', '6 beats per measure', '3 beats per measure']),
            ('The bottom number of a time signature indicates',
             'the note value that receives one beat (4 = quarter note, 8 = eighth note)',
             ['the number of beats per measure', 'the tempo in BPM', 'the dynamic level']),
            ('Anacrusis (pickup measure) means the piece begins',
             'with an incomplete measure before the first full measure',
             ['with a rest on beat one', 'with a very fast tempo', 'with a mezzo-forte dynamic']),
            ('A fermata over a note means',
             'hold the note longer than its written value (duration at the performer\'s or conductor\'s discretion)',
             ['play the note at half its written speed', 'skip the note', 'play the note very loudly (fortissimo)']),
        ],
    },
    {
        'num': 4,
        'title': 'Harmony and Voice Leading I',
        'file': 'ap-music-theory-4-unit-4-harmony-and-voice-leading-i.html',
        'desc': 'Roman numeral analysis, chord inversions, figured bass, and basic voice leading in SATB.',
        'gateway': [
            'Assign Roman numerals to chords in major and minor keys.',
            'Identify first and second inversion chords from bass figures.',
            'Write basic SATB four-part harmony following voice leading rules.',
            'Recognize and avoid parallel octaves and fifths.',
        ],
        'lessons': [
            _l('Roman Numeral Analysis and Chord Inversions',
               [_t('Roman Numerals in Major and Minor', 'Roman numerals label chords by scale degree: I, II, III, IV, V, VI, VII. Uppercase = major; lowercase = minor; ° = diminished; + = augmented. In minor keys, common chords use raised 7th (harmonic minor).', 'Students use uppercase for all chords in minor; the chords built on each scale degree in minor must be derived from the actual scale in use.', 'Analyze a short chord progression with Roman numerals in both major and minor.'),
                _t('Chord Inversions and Figured Bass', 'Root position has the root in the bass. First inversion (6) has the third in the bass. Second inversion (6/4) has the fifth in the bass. Figured bass numbers indicate intervals above the bass note.', 'Students confuse the figure "6" with a sixth interval in the chord; the 6 indicates a first inversion, specifying what interval appears above the bass.', 'Read figured bass notation and write the correct chord voicing; identify inversions from notation.')],
               [('root position', 'Chord with the root in the bass voice'),
                ('first inversion', 'Chord with the third in the bass; figured bass symbol "6"'),
                ('second inversion', 'Chord with the fifth in the bass; figured bass symbol "6/4"; used in specific contexts (cadential, passing, pedal)'),
                ('figured bass', 'Numbers below a bass line indicating which intervals to build above it')],
               ['Label any chord with Roman numeral and inversion symbol', 'Write a chord from figured bass notation', 'Explain when to use second inversion chords'],
               ['Analyze a 4-measure Bach chorale excerpt with Roman numerals', 'Write I6 and V6/4 chords in D major'],
               [('Analyze the chords in C major: C-E-G, F-A-C, G-B-D, C-E-G using Roman numerals'),
                ('Identify whether E-G-C in C major is I6 or IV in root position')],
               [('In C major, the chord D-F-A is labeled',
                 'ii (D minor triad, supertonic)',
                 ['II (D major)', 'iv (D minor in minor key context)', 'viio']),
                ('A chord in first inversion has __________ in the bass.',
                 'The third of the chord',
                 ['The root', 'The fifth', 'The seventh']),
                ('The figured bass "6/4" indicates a',
                 'second inversion chord (fifth in the bass)',
                 ['first inversion chord', 'root position seventh chord', 'dominant chord']),
                ('In G major, the viio chord is',
                 'F#-A-C (a diminished triad on the leading tone)',
                 ['F-A-C', 'F#-A-C#', 'G-B♭-D']),
                ('The I6/4 chord (tonic in second inversion) is most commonly used as',
                 'a cadential 6/4 immediately before the dominant (V) chord at a cadence',
                 ['a substitute for the tonic in the middle of a phrase', 'the final chord of any cadence', 'a way to avoid parallel fifths'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Roman Numeral Harmony', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What does each Roman numeral quality (uppercase/lowercase/°/+) tell you?', 'Explain the difference between I6 and I6/4', 'When is second inversion appropriate?']),

            _l('SATB Voice Leading Fundamentals',
               [_t('Range and Spacing in SATB', 'Each voice has a standard range: Soprano C4–G5, Alto G3–C5, Tenor C3–G4, Bass E2–C4. Voices should stay within these ranges and avoid large leaps (especially augmented/diminished intervals).', 'Students write soprano notes in the tenor range or create chord spellings with wide gaps; SATB spacing follows specific guidelines for consonance.', 'Check voice ranges and spacing in a given SATB setting; rewrite with corrections.'),
                _t('Parallel Motion and Voice Independence', 'Parallel perfect octaves and fifths between any two voices are prohibited because they destroy the independence of those voices, making them sound like one. Contrary motion is preferred to maintain independence.', 'Students confuse "parallel" with "similar" motion; parallel fifths means both voices move in the same direction by a perfect fifth each time, not just any fifth.', 'Identify parallel fifths and octaves in a score; rewrite to avoid them.')],
               [('SATB', 'Four-part chorale texture: Soprano, Alto, Tenor, Bass'),
                ('parallel fifths', 'When two voices both move by a perfect fifth in the same direction — prohibited in common practice'),
                ('contrary motion', 'Two voices moving in opposite directions — preferred for voice independence'),
                ('doubling', 'In SATB, which pitch of a chord is duplicated across voices; typically the root is doubled in root-position chords')],
               ['Write smooth SATB voice leading from I to V to I', 'Identify and correct parallel octaves or fifths', 'Apply proper doubling to triads'],
               ['Write a 4-chord I-IV-V-I progression in C major in SATB', 'Find and fix all voice-leading errors in a given chorale'],
               [('Identify the voice leading error in this progression and explain how to fix it')],
               [('In SATB, the soprano voice typically occupies the range',
                 'C4 to G5',
                 ['E3 to C5', 'G3 to D5', 'C3 to G4']),
                ('Parallel perfect octaves between soprano and alto violate voice-leading rules because',
                 'they make the two voices sound like one, destroying voice independence',
                 ['they create dissonance', 'they break the key signature', 'they are impossible on keyboard']),
                ('When writing a root-position triad in SATB, the note most commonly doubled is',
                 'the root',
                 ['the third', 'the fifth', 'the seventh']),
                ('Contrary motion in voice leading means',
                 'two voices move in opposite directions simultaneously',
                 ['both voices stay on the same pitch', 'both voices move in the same direction', 'one voice holds while the other moves']),
                ('Which of the following is an example of a voice-leading error?',
                 'Soprano moving from C5 to G5 while Alto simultaneously moves from F4 to C5 (parallel perfect fifths)',
                 ['Soprano moving C5 to E5 while Alto holds G4', 'Bass moving G2 to C3 by a perfect fourth', 'Tenor leaping a minor third upward'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'SATB Voice Leading', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What are the four SATB voice ranges?', 'Why are parallel fifths and octaves prohibited?', 'Which note is typically doubled in a root-position triad?']),
        ],
        'unit_qs': [
            ('In A major, the iii chord (mediant) is',
             'C# minor (C#-E-G#)',
             ['C# major', 'C# diminished', 'C minor']),
            ('The cadential 6/4 (I6/4 → V) is effective because',
             'the dissonant second inversion creates tension that resolves to the dominant before final tonic',
             ['it avoids parallel fifths automatically', 'it contains the leading tone in the bass', 'it substitutes for the subdominant']),
            ('An authentic cadence (V → I) is "perfect" when',
             'the soprano ends on the tonic (scale degree 1̂) and the chord is in root position',
             ['the soprano ends on scale degree 5̂', 'the bass leaps a fourth downward', 'the V chord is in first inversion']),
            ('A deceptive cadence resolves V to',
             'vi (the submediant) instead of I, surprising the listener',
             ['IV (the subdominant)', 'I6 (first inversion tonic)', 'ii (the supertonic)']),
            ('The half cadence ends on',
             'the dominant (V), creating an inconclusive, open feeling',
             ['the tonic (I)', 'the subdominant (IV)', 'the leading tone (viio)']),
            ('In figured bass, "7" above a bass note indicates',
             'a seventh chord in root position',
             ['a chord in second inversion', 'an octave doubling of the bass', 'a suspension resolving to the 6']),
            ('Oblique motion in voice leading means',
             'one voice stays on the same pitch while the other moves',
             ['both voices move in the same direction', 'both voices move in opposite directions', 'one voice skips while the other steps']),
            ('The Neapolitan chord (♭II) in a minor key is a',
             'major triad built on the lowered second scale degree (♭2̂)',
             ['diminished seventh chord on ♭2̂', 'minor triad on the lowered 2nd', 'augmented sixth chord']),
            ('In C major, a plagal cadence is IV → I, which means',
             'the F major chord resolves to C major — often called the "Amen" cadence',
             ['the G major chord resolves to C major', 'the D minor chord resolves to G major', 'the B diminished chord resolves to C major']),
            ('Which scale degree must always resolve upward by half step to the tonic in common practice?',
             'Scale degree 7̂ (the leading tone), which creates the strongest resolution pull',
             ['Scale degree 2̂', 'Scale degree 6̂ (in minor)', 'Scale degree 4̂']),
        ],
    },
    {
        'num': 5,
        'title': 'Harmony and Voice Leading II',
        'file': 'ap-music-theory-5-unit-5-harmony-and-voice-leading-ii.html',
        'desc': 'Secondary dominants, modulation, non-chord tones, and more complex harmonic progressions.',
        'gateway': [
            'Identify and resolve secondary dominant chords (V/x, V7/x).',
            'Describe common modulation techniques (pivot chord, chromatic).',
            'Identify non-chord tones (passing, neighbor, suspension, appoggiatura, etc.).',
            'Analyze extended harmonic progressions with Roman numerals.',
        ],
        'lessons': [
            _l('Secondary Dominants',
               [_t('Secondary Dominant Function', 'A secondary dominant chord (V/x) temporarily tonicizes a non-tonic chord. It contains the leading tone of the target chord. Example: V/V in C major is D major (D-F#-A), which strongly pulls to G.', 'Students confuse secondary dominants with borrowed chords; secondary dominants tonicize a chord within the key, while borrowed chords come from the parallel mode.', 'Identify and label secondary dominants; write the correct resolution.'),
                _t('Resolution of Secondary Dominants', 'A secondary dominant must resolve to the chord it tonicizes: V/IV → IV; V/V → V; V/ii → ii. The secondary leading tone resolves upward by half step; the chordal seventh resolves downward by step.', 'Students write the secondary dominant but fail to resolve it correctly, especially when the seventh is involved.', 'Write a secondary dominant with correct resolution in a given key.')],
               [('secondary dominant', 'A major triad or dominant seventh chord built on the fifth of a non-tonic chord, temporarily tonicizing that chord'),
                ('tonicization', 'Briefly treating a chord other than the tonic as a temporary tonal center, usually for one or two chords'),
                ('borrowed chord', 'A chord taken from the parallel major or minor key (mode mixture), not to be confused with a secondary dominant'),
                ('applied chord', 'Another term for secondary dominant — a chord "applied" to make the next chord sound like a temporary tonic')],
               ['Identify secondary dominants from a score', 'Build V/V, V/IV, and V/ii in any key', 'Resolve secondary dominants correctly in SATB'],
               ['Analyze a Bach chorale excerpt for secondary dominants', 'Write a 4-measure progression that includes V7/V → V → I'],
               [('Identify the secondary dominant in the progression I-V7/IV-IV-I in C major')],
               [('In the key of F major, V/V is the chord',
                 'C major (C-E-G), which tonicizes the dominant G major',
                 ['G major', 'D major', 'Bb major']),
                ('The chord V7/ii in D major contains',
                 'E-G#-B-D (the dominant seventh of E minor, the ii chord)',
                 ['A-C#-E-G (the dominant seventh of D)', 'F#-A-C#-E', 'E-G-B-D']),
                ('When a secondary dominant resolves, the secondary leading tone moves',
                 'up by half step to the root of the tonicized chord',
                 ['down by step to the seventh', 'to the nearest chord tone', 'stays in place']),
                ('Secondary dominants are NOT the same as borrowed chords because',
                 'secondary dominants tonicize a chord within the key; borrowed chords come from the parallel mode',
                 ['secondary dominants always contain a flat', 'borrowed chords always tonicize the dominant', 'they differ only in their bass note']),
                ('V/VI in A major is',
                 'E major (E-G#-B), which tonicizes F# minor (vi)',
                 ['F# major', 'C# major', 'B major'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Secondary Dominants Explained', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['What is a secondary dominant and how does it differ from the main dominant?', 'Write V7/ii in Bb major', 'What is the difference between a secondary dominant and a borrowed chord?']),

            _l('Non-Chord Tones',
               [_t('Types of Non-Chord Tones', 'Non-chord tones (NCTs) are notes that do not belong to the prevailing chord. Passing tone (PT): stepwise between chord tones. Neighbor tone (NT): step away and back. Suspension (SUS): held from previous chord, resolves down by step. Appoggiatura: approached by leap, resolved by step. Escape tone: step then leap away.', 'Students label all non-chord tones as "passing tones"; each type has specific approach and resolution requirements.', 'Identify NCT type from its approach and resolution pattern; label correctly in a score.'),
                _t('Suspensions by Number', 'Suspensions are labeled by the intervals of preparation, suspension, and resolution: 4-3 (suspension of 4th resolving to 3rd), 7-6, 9-8, 2-3 (bass suspension). The suspension must be prepared (same pitch in previous chord) and resolved downward by step.', 'Students confuse 4-3 and 9-8 suspensions; the numbers describe the interval above the bass at each stage.', 'Prepare and resolve 4-3 and 7-6 suspensions correctly; label them in a score.')],
               [('passing tone', 'NCT approached and left by step in the same direction'),
                ('neighbor tone', 'NCT that steps away from a chord tone then returns to it'),
                ('suspension', 'NCT held over from the previous chord, creating dissonance that resolves downward by step'),
                ('appoggiatura', 'NCT approached by leap and left by step in the opposite direction'),
                ('anticipation', 'NCT that arrives early — the note belongs to the next chord')],
               ['Identify NCT type from notation', 'Write a 4-3 suspension correctly', 'Distinguish accented from unaccented NCTs'],
               ['Label all NCTs in a short chorale excerpt', 'Add a 7-6 suspension to a V-I cadence'],
               [('Identify the type of NCT in measure 2 of the given excerpt')],
               [('A 4-3 suspension resolves by the 4th (suspended note) moving',
                 'down by step to the 3rd of the chord',
                 ['up by step to the 5th', 'staying in place', 'leaping to the 3rd']),
                ('A passing tone is categorized by its',
                 'stepwise approach and stepwise departure in the same direction',
                 ['leap to and step away', 'step to and leap away', 'preparation, suspension, resolution']),
                ('The preparation of a suspension requires',
                 'the suspended pitch to appear as a chord tone in the immediately preceding chord',
                 ['a rest before the suspended note', 'a leap to the suspended note', 'the suspended note to be in the bass']),
                ('An appoggiatura differs from a suspension in that it is',
                 'approached by leap (not prepared as a chord tone)',
                 ['resolved upward by step', 'held longer than a suspension', 'always in the bass voice']),
                ('A neighbor tone is identified by',
                 'a step away from a chord tone, then a return step back to the same chord tone',
                 ['a step away from the chord tone then a leap', 'two steps in the same direction', 'a leap from the chord tone'])],
               [('https://www.youtube.com/watch?v=rgaTLrZGlk0', 'Non-Chord Tones Tutorial', 'https://www.youtube.com/watch?v=rgaTLrZGlk0')],
               ['Define and distinguish passing tone, neighbor tone, and suspension', 'How is a 7-6 suspension prepared and resolved?', 'What makes an appoggiatura different from a suspension?']),
        ],
        'unit_qs': [
            ('A modulation is confirmed when',
             'a cadence establishes the new key center',
             ['a chromatic note appears in the melody', 'the tempo changes', 'the composer marks "Fine" in the score']),
            ('Pivot chord modulation uses a chord that',
             'belongs to both the original key and the new key, smoothly connecting them',
             ['does not exist in either key', 'is always the dominant of the new key', 'is borrowed from the parallel minor']),
            ('In a 7-6 suspension, the 7th resolves to',
             'the 6th above the bass (down by step)',
             ['the 5th above the bass', 'the 8th (octave)', 'the 4th']),
            ('The pedal point (organ point) is a',
             'sustained note (usually the tonic or dominant) in one voice while other voices move harmonically',
             ['repeated pattern in the bass that changes every two beats', 'non-chord tone that leaps to resolution', 'trill on the leading tone']),
            ('Mode mixture (borrowed chords) means',
             'using chords from the parallel mode (e.g., iv in a major key, borrowed from parallel minor)',
             ['modulating to the relative minor permanently', 'using secondary dominants', 'applying the harmonic minor scale']),
            ('An augmented sixth chord (e.g., Italian, French, German 6th) functions as',
             'a predominant chord that approaches the dominant through intensified half-step motion in the outer voices',
             ['a substitute for the dominant seventh', 'a tonic chord in second inversion', 'a borrowed chord from the relative major']),
            ('A sequence in harmony is a pattern that',
             'repeats at successively higher or lower pitch levels',
             ['uses only the I, IV, and V chords', 'avoids any repetition', 'modulates to a new key each measure']),
            ('Chromatic modulation differs from diatonic (pivot chord) modulation because',
             'chromatic modulation moves directly to the new key using chromatic alteration without a shared chord',
             ['chromatic modulation is more gradual', 'pivot chord modulation requires a tritone relationship', 'chromatic modulation always uses the circle of fifths']),
            ('The Neapolitan (♭II) chord in minor is typically used in',
             'first inversion (♭II6) as a predominant, resolving to V',
             ['root position resolving to I', 'second inversion resolving to I6/4', 'any position resolving to iv']),
            ('An elision (overlap) in phrase structure occurs when',
             'the last chord of one phrase serves simultaneously as the first chord of the next phrase',
             ['the same chord is repeated for two full measures', 'a phrase ends with a half cadence', 'two voices exchange melodies']),
        ],
    },
]
