NAME        = 'AP® Physics C: Electricity & Magnetism'
ABBREV      = 'physem'
SLUG        = 'ap-physics-c-electricity-and-magnetism'
COURSE_FILE = 'ap-physics-c-electricity-and-magnetism.html'
ACCENT_COLOR = '#38bdf8'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+C+Magnetism+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+C+EM+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content,
            'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 4, 'title': 'Magnetic Fields',
        'file': 'ap-physics-c-electricity-and-magnetism-4-unit-11-electric-circuits.html',
        'desc': 'Magnetic forces on charges and currents, Biot-Savart law, and Ampere\'s law.',
        'gateway': [
            'Calculate magnetic force on moving charges and current-carrying wires.',
            'Apply the Biot-Savart law to compute fields from simple current configurations.',
            'Use Ampere\'s law to find B for symmetric current distributions.',
            'Explain the motion of charges in magnetic fields.',
        ],
        'lessons': [
            _l('Magnetic Force on Charges and Currents',
               [_t('Magnetic Force on a Charge', 'F = qv × B; magnitude F = qvB sinθ. Magnetic force is perpendicular to both v and B — it does no work on the charge.', 'Magnetic force does zero work (F perpendicular to v) — it changes direction but not speed.', 'Calculate magnetic force on moving charges using F = qvB sinθ.'),
                _t('Cyclotron Motion', 'A charge in a uniform B perpendicular to v moves in a circle: r = mv/(qB); T = 2πm/(qB). Period is independent of speed.', 'The cyclotron radius depends on speed, but the period does NOT — all speeds have the same period in a given B.', 'Find cyclotron radius and period for a charged particle in a magnetic field.'),
                _t('Magnetic Force on a Current', 'F = IL × B; for a straight wire of length L carrying current I in field B: F = ILB sinθ. This is the basis of electric motors.', 'Force on wire is F = ILB sinθ, not F = IB — length and angle matter.', 'Calculate force on a current-carrying wire in a magnetic field.')],
               [('Magnetic force', 'F = qv × B; perpendicular to v and B'),
                ('Cyclotron radius', 'r = mv/(qB); radius of circular path in uniform B'),
                ('Cyclotron period', 'T = 2πm/(qB); independent of particle speed'),
                ('Right-hand rule', 'Direction of F = qv × B; fingers from v to B, thumb gives F direction for +q'),
                ('Force on wire', 'F = IL × B = ILB sinθ for straight wire')],
               ['Calculate F on a charge using F = qvB sinθ.',
                'Find cyclotron radius and period for a given charge and field.',
                'Calculate force on a current-carrying wire in a B field.'],
               ['Free-response: find path of a charge entering B field region.',
                'Derivation: show that cyclotron period is independent of v.',
                'Calculate force on a rectangular current loop in a uniform B.'],
               ['Practice right-hand rule for F = qv × B.',
                'Solve cyclotron radius problems for electrons and protons.'],
               [('An electron (m = 9.11×10⁻³¹ kg, q = 1.6×10⁻¹⁹ C) moves at 10⁶ m/s perpendicular to B = 0.01 T. Find cyclotron radius.', ['F_mag = F_centripetal: qvB = mv²/r → r = mv/(qB)', 'r = (9.11×10⁻³¹)(10⁶)/((1.6×10⁻¹⁹)(0.01))', 'r = 9.11×10⁻²⁵/1.6×10⁻²¹ = 5.69×10⁻⁴ m = 0.569 mm', 'Period: T = 2πm/(qB) = 2π(9.11×10⁻³¹)/(1.6×10⁻²¹) ≈ 3.57 ns']),
                ('Why does a magnetic force do no work on a moving charge?', ['F_mag = qv × B is always perpendicular to v', 'Work = F · d = F · v dt = 0 (perpendicular)', 'No work → no change in kinetic energy → constant speed', 'Magnetic force changes direction of v, not magnitude']),
                ('A wire (L = 0.5 m, I = 3 A) is in B = 0.2 T perpendicular to the wire. Find the force.', ['F = ILB sinθ = 3 × 0.5 × 0.2 × sin90° = 0.3 N', 'Direction: right-hand rule (I direction × B direction)', 'Maximum force when wire is perpendicular to B', 'Zero force when wire is parallel to B (sinθ = 0)']),
                ('A proton (m = 1.67×10⁻²⁷ kg) circles in B = 1.5 T. Find T and f.', ['T = 2πm/(qB) = 2π(1.67×10⁻²⁷)/((1.6×10⁻¹⁹)(1.5))', 'T = 10.49×10⁻²⁷/(2.4×10⁻¹⁹) = 4.37×10⁻⁸ s ≈ 43.7 ns', 'f = 1/T = 22.9 MHz (cyclotron frequency)', 'This frequency is used in cyclotron particle accelerators']),
                ('Explain how a DC electric motor uses the force on current-carrying wires.', ['Current loop in magnetic field experiences torque: τ = NIAB sinθ', 'Torque tends to align the loop with B', 'Commutator reverses current direction when loop is at equilibrium', 'Continuous rotation results from repeated torque-reversal cycle'])],
               [('Bozeman Magnetic Force', 'F = qvB, cyclotron motion, F on wire', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Magnetic Force', 'Lorentz force and cyclotron motion', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['F = qvB sinθ; perpendicular to v → no work done.',
                'Cyclotron: r = mv/(qB); T = 2πm/(qB) independent of v.',
                'Wire: F = ILB sinθ; maximum when I perpendicular to B.']),

            _l('Biot-Savart Law',
               [_t('Biot-Savart Law', 'dB = (μ₀/4π) I dl × r̂/r²; integrate over current distribution. μ₀ = 4π×10⁻⁷ T·m/A. For a long straight wire: B = μ₀I/(2πr).', 'The Biot-Savart law gives dB from a current element — you must integrate over the whole wire.', 'Apply Biot-Savart to find B for straight wires, loops, and arcs.'),
                _t('Field of a Circular Current Loop', 'On the axis: B = μ₀IR²/(2(R²+x²)^{3/2}). At center (x = 0): B = μ₀I/(2R). The field is along the axis.', 'The field of a current loop on its axis decreases as 1/r³ far from the loop (like a magnetic dipole).', 'Derive B on the axis of a current loop using Biot-Savart.'),
                _t('Force Between Parallel Wires', 'Two parallel wires with currents I₁ and I₂ separated by distance d: F/L = μ₀I₁I₂/(2πd). Parallel currents attract; antiparallel currents repel.', 'Parallel currents attract each other (not repel) — this is opposite to parallel electric charges.', 'Calculate force per unit length between parallel current-carrying wires.')],
               [('μ₀', 'Permeability of free space = 4π×10⁻⁷ T·m/A'),
                ('Biot-Savart law', 'dB = (μ₀/4π) I dl × r̂/r²; integrate for total B'),
                ('Long wire B', 'B = μ₀I/(2πr); field circles the wire; decreases as 1/r'),
                ('Loop center B', 'B = μ₀I/(2R) at center of circular loop of radius R'),
                ('Force between wires', 'F/L = μ₀I₁I₂/(2πd); attract if currents parallel')],
               ['Apply Biot-Savart to find B for straight wires and loops.',
                'Derive B on the axis of a current loop by integration.',
                'Calculate force per unit length between parallel wires.'],
               ['Free-response: derive B at center of a circular arc of angle θ.',
                'Biot-Savart: derive B for infinite straight wire by integration.',
                'Force: find direction and magnitude between two parallel wires.'],
               ['Derive Biot-Savart result for infinite wire by integration.',
                'Find B at center of square current loop.'],
               [('Derive B for an infinite straight wire using Biot-Savart.', ['dB = (μ₀/4π) I dx sinθ/r²; r² = x²+d²; sinθ = d/√(x²+d²)', 'B = (μ₀I/4π) ∫_{-∞}^{∞} d dx/(x²+d²)^{3/2}', 'B = (μ₀I/4π)(2/d) = μ₀I/(2πd)', 'Field circles the wire; direction given by right-hand rule']),
                ('Find B at the center of a circular loop (I, radius R).', ['By symmetry, all dB contributions point in the same direction (along axis)', 'dB = μ₀I dl/(4πR²) for each element; total: B = μ₀I(2πR)/(4πR²)', 'B = μ₀I/(2R)', 'Direction: right-hand rule for loop current; B along axis through center']),
                ('Derive B on the axis of a loop at distance x from center.', ['Each element dB has component along axis: dB_x = μ₀I dl cos α/(4π(R²+x²))', 'cos α = R/√(R²+x²); integrate over full loop (2πR)', 'B = μ₀IR²/(2(R²+x²)^{3/2})', 'At x = 0: B = μ₀I/(2R) ✓; at x >> R: B ≈ μ₀IR²/(2x³) ∝ 1/x³ (dipole)']),
                ('Two wires carry 5 A and 10 A in the same direction, separated by 0.1 m. Find force per unit length.', ['F/L = μ₀I₁I₂/(2πd) = (4π×10⁻⁷)(5)(10)/(2π×0.1)', 'F/L = (4π×10⁻⁷ × 50)/(0.2π) = 10⁻⁴ N/m', 'Attractive (same-direction currents)', 'Force decreases as 1/d (linear, not quadratic)']),
                ('Compare the magnetic field behavior of a straight wire (B ∝ 1/r) vs. a magnetic dipole (B ∝ 1/r³).', ['Wire: B = μ₀I/(2πr); field decreases as 1/r', 'Dipole (current loop): B ∝ 1/r³ at large distances', 'Monopole electric: E ∝ 1/r²; no magnetic monopole equivalent', 'Long wire is not a dipole; has no end point to form a monopole'])],
               [('Bozeman Biot-Savart', 'B from current elements and loops', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Biot-Savart', 'Deriving B for wire and loop', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Biot-Savart: dB = (μ₀I/4π) dl×r̂/r².',
                'Wire: B = μ₀I/(2πr); loop center: B = μ₀I/(2R).',
                'Parallel currents attract; F/L = μ₀I₁I₂/(2πd).']),

            _l('Ampere\'s Law',
               [_t('Ampere\'s Law', '∮B·dl = μ₀I_enc; the line integral of B around a closed loop equals μ₀ times the enclosed current. Choose an Amperian loop that simplifies the integral.', 'Ampere\'s law applies to all B fields, but it is only useful for finding B when there is sufficient symmetry.', 'Apply Ampere\'s law for straight wires, solenoids, and toroids.'),
                _t('Solenoid', 'Ideal solenoid (n turns/m, I): B = μ₀nI inside; B = 0 outside. Field is uniform and axial inside.', 'The solenoid formula B = μ₀nI uses n = turns per meter, not total turns N.', 'Calculate B inside a solenoid; explain why B = 0 outside an ideal solenoid.'),
                _t('Toroid', 'Toroid (N total turns, mean radius R, current I): B = μ₀NI/(2πr) inside; B = 0 outside. B varies with radius inside the toroid.', 'In a toroid, B is NOT uniform inside — it varies as 1/r. The toroid concentrates flux within the torus.', 'Apply Ampere\'s law to derive B inside a toroid.')],
               [('Ampere\'s law', '∮B·dl = μ₀I_enc; analogous to Gauss\'s law for B'),
                ('Amperian loop', 'Closed path chosen to simplify ∮B·dl'),
                ('Solenoid B', 'B = μ₀nI inside (uniform); B = 0 outside'),
                ('Turns density n', 'n = N/L; turns per unit length'),
                ('Toroid B', 'B = μ₀NI/(2πr) inside; B = 0 outside')],
               ['Apply Ampere\'s law to find B for straight wires, solenoids, and toroids.',
                'Identify appropriate Amperian loops for each geometry.',
                'Derive B inside a solenoid using Ampere\'s law.'],
               ['Free-response: derive B inside a toroidal coil using Ampere\'s law.',
                'Show B = 0 outside an ideal solenoid using Amperian rectangles.',
                'Find B inside a thick cylindrical conductor using Ampere\'s law.'],
               ['Derive B for solenoid and toroid from scratch.',
                'Apply Ampere\'s law to a hollow cylindrical conductor.'],
               [('Apply Ampere\'s law to derive B for a long straight wire.', ['Amperian circle of radius r centered on wire; by symmetry B is tangential and constant', '∮B·dl = B(2πr) = μ₀I_enc', 'B = μ₀I/(2πr)', 'Same result as Biot-Savart — both are correct']),
                ('Derive B inside an ideal solenoid (n turns/m, current I).', ['Amperian rectangle: one side inside (length L), one outside', 'Inside: B is uniform and parallel to axis; outside B ≈ 0', '∮B·dl = BL = μ₀(nL)I → B = μ₀nI', 'B is uniform, independent of position inside solenoid']),
                ('An ideal solenoid has 2000 turns, length 50 cm, and carries 3 A. Find B inside.', ['n = N/L = 2000/0.5 = 4000 turns/m', 'B = μ₀nI = (4π×10⁻⁷)(4000)(3) = 1.508×10⁻² T ≈ 15.1 mT', 'Uniform field along solenoid axis', 'For comparison: Earth\'s field ≈ 50 μT; this is 300× stronger']),
                ('Derive B inside a toroid (N turns, mean radius R).', ['Amperian circle of radius r inside the torus; by symmetry B tangential and constant', '∮B·dl = B(2πr) = μ₀NI → B = μ₀NI/(2πr)', 'B varies as 1/r inside the torus (not uniform)', 'Outside: Amperian loop encloses zero net current → B = 0']),
                ('Why is B = 0 outside an ideal solenoid?', ['Ideal solenoid: infinite length, uniform winding', 'Apply Amperian rectangle with both long sides outside', 'By symmetry, field outside must be zero (any B outside would imply a non-physical situation)', 'Formally: total current enclosed by exterior loop is zero → B_ext = 0'])],
               [('Bozeman Ampere\'s Law', 'Amperian loops, solenoid, toroid', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Ampere', 'Deriving B with Ampere\'s law', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Ampere: ∮B·dl = μ₀I_enc; choose loop with B constant.',
                'Solenoid: B = μ₀nI inside (uniform); 0 outside.',
                'Toroid: B = μ₀NI/(2πr) inside; 0 outside.']),

            _l('Magnetic Dipoles and Matter',
               [_t('Magnetic Dipole Moment', 'Magnetic dipole moment μ = NIA (A·m²) for a current loop. Torque: τ = μ × B = μB sinθ. PE = -μ·B. Analogous to electric dipole p in electric field.', 'Magnetic dipole moment μ is the magnetic equivalent of electric dipole p — all formulas are directly analogous.', 'Calculate μ, torque, and PE for current loops in magnetic fields.'),
                _t('Magnetic Materials', 'Diamagnetic materials (χ_m < 0) weakly repel B; paramagnetic (χ_m > 0) weakly attract; ferromagnetic (χ_m >> 0) strongly attract and retain magnetization.', 'Not all magnets are the same — ferromagnets (iron, nickel) are permanently magnetizable; paramagnets are only temporarily attracted.', 'Classify materials by magnetic behavior and explain at the atomic level.'),
                _t('Magnetization and B in Matter', 'B = μ₀(H + M) where H is the applied field and M is magnetization. For linear magnetic materials: M = χ_m H; B = μ₀(1+χ_m)H = μ₀μ_r H.', 'H and B are different fields — H is determined by free currents; B includes the contribution from magnetized matter.', 'Apply B = μ₀μ_r H to find B in a magnetic material.')],
               [('Magnetic dipole moment μ', 'μ = NIA; torque τ = μ × B; PE = -μ·B'),
                ('Diamagnetic', 'χ_m < 0; weakly repelled by B; no permanent moment'),
                ('Paramagnetic', 'χ_m > 0 (small); weakly attracted to B; temporary alignment'),
                ('Ferromagnetic', 'χ_m >> 0; permanently magnetized; domains align'),
                ('Relative permeability μ_r', 'μ_r = 1 + χ_m; B = μ₀μ_r H in linear media')],
               ['Calculate magnetic dipole moment, torque, and PE for a current loop.',
                'Classify materials as dia-, para-, or ferromagnetic.',
                'Apply B = μ₀μ_r H in magnetized materials.'],
               ['Free-response: find net torque on a current loop in a nonuniform B field.',
                'Multiple choice: classify materials by magnetic behavior.',
                'Calculate B inside a material from H using given χ_m.'],
               ['Practice torque and PE calculations for magnetic dipoles.',
                'Compare atomic origins of diamagnetic, paramagnetic, and ferromagnetic behavior.'],
               [('A square loop (side 0.1 m, N = 50 turns, I = 2 A) is in B = 0.5 T at θ = 30°. Find τ.', ['μ = NIA = 50 × 2 × (0.1)² = 1 A·m²', 'τ = μB sinθ = 1 × 0.5 × sin30° = 0.25 N·m', 'Maximum torque at θ = 90°: τ_max = μB = 0.5 N·m', 'Stable equilibrium at θ = 0 (aligned with B)']),
                ('Find PE when loop is anti-aligned with B in the example above.', ['PE = -μ·B = -μB cosθ', 'Anti-aligned (θ = 180°): PE = -μB cos180° = +μB = +0.5 J', 'Aligned (θ = 0°): PE = -μB = -0.5 J', 'Energy to flip from aligned to anti-aligned = 2μB = 1 J']),
                ('Explain why iron is attracted to a magnet but copper is not.', ['Iron is ferromagnetic: magnetic domains align strongly with external B', 'Induced magnetization greatly amplifies B inside iron → large attraction', 'Copper is diamagnetic: electrons slightly oppose the applied field → very weak repulsion', 'Even diamagnetic repulsion requires very strong fields to observe']),
                ('In a material with μ_r = 200, H = 1000 A/m. Find B and M.', ['B = μ₀μ_r H = (4π×10⁻⁷)(200)(1000) = 2.513×10⁻¹ T ≈ 251 mT', 'M = χ_m H = (μ_r - 1)H = 199 × 1000 = 199 000 A/m', 'B_vacuum = μ₀H = 1.26×10⁻³ T; material amplifies B by factor 200', 'This is how ferromagnetic cores increase transformer efficiency']),
                ('Why do ferromagnets have a Curie temperature above which they become paramagnetic?', ['Below Curie temperature: thermal energy < exchange energy → domains stay aligned', 'Above Curie temperature: thermal fluctuations destroy domain order', 'Iron Curie T ≈ 770°C; above this, domains randomize → paramagnetic behavior', 'Permanent magnets must be kept below their Curie temperature'])],
               [('Bozeman Magnetic Dipoles', 'Magnetic moment, torque, and magnetic materials', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Magnetic Matter', 'Diamagnetic, paramagnetic, ferromagnetic', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['μ = NIA; τ = μB sinθ; PE = -μB cosθ.',
                'Ferromagnetic: strongly attracted; domains; permanent magnets.',
                'B = μ₀μ_r H; μ_r >> 1 for ferromagnets.']
               )
        ],
        'unit_qs': [
            ('A proton enters a magnetic field B = 0.5 T at v = 2×10⁶ m/s perpendicular to B. Find radius and period. (m_p = 1.67×10⁻²⁷ kg)',
             ['r = mv/(qB) = (1.67×10⁻²⁷)(2×10⁶)/((1.6×10⁻¹⁹)(0.5))', 'r = 3.34×10⁻²¹/8×10⁻²⁰ = 0.0418 m ≈ 4.18 cm', 'T = 2πm/(qB) = 2π(1.67×10⁻²⁷)/(1.6×10⁻¹⁹×0.5) = 1.31×10⁻⁷ s', 'Period independent of speed — key cyclotron property']),
            ('Derive B at the center of a square current loop (side a, current I) using Biot-Savart.',
             ['Each side: B_side = μ₀I/(4π) × 2a/(a/2)² × ... apply result for finite wire', 'For finite wire of length a at distance a/2: B = μ₀I/(4π×a/2) × 2sin45°/1... = μ₀I√2/(πa)', 'Four sides add up: B_total = 4 × μ₀I√2/(4πa) = √2 μ₀I/(πa)', 'Actually: B = μ₀I/(2π) × (2√2/a) — verify by integration']),
            ('A solenoid (L = 0.3 m, diameter = 2 cm, 600 turns, I = 2 A) find B inside and energy stored per unit length.',
             ['n = 600/0.3 = 2000 turns/m; B = μ₀nI = 4π×10⁻⁷ × 2000 × 2 = 5.03 mT', 'u = B²/(2μ₀) = (5.03×10⁻³)²/(2×4π×10⁻⁷) = 10.1 J/m³', 'Volume per unit length: A = π(0.01)² = 3.14×10⁻⁴ m²', 'Energy/length = u × A = 10.1 × 3.14×10⁻⁴ = 3.17 mJ/m']),
            ('Two parallel wires 0.2 m apart carry I₁ = 8 A and I₂ = 6 A in opposite directions. Find force/length and direction.',
             ['F/L = μ₀I₁I₂/(2πd) = (4π×10⁻⁷)(8)(6)/(2π×0.2)', 'F/L = (4π×10⁻⁷ × 48)/(0.4π) = 2.4×10⁻⁵ N/m', 'Opposite currents: repulsive force', 'Direction: away from each other (right-hand rule)']),
            ('A charged particle (q = 2 μC, m = 4×10⁻¹⁴ kg) enters crossed E and B fields (E = 100 V/m, B = 0.02 T) and travels in a straight line. Find v.',
             ['Straight line: F_E = F_B → qE = qvB', 'v = E/B = 100/0.02 = 5000 m/s', 'This is the velocity selector principle', 'Only particles with exactly this speed pass straight through']),
            ('Derive B inside a thick cylindrical conductor of radius R carrying current I uniformly distributed.',
             ['For r < R: Amperian circle, I_enc = I(r/R)²', 'B(2πr) = μ₀I(r/R)² → B = μ₀Ir/(2πR²); ∝ r inside', 'For r > R: B(2πr) = μ₀I → B = μ₀I/(2πr); ∝ 1/r outside', 'B is maximum at r = R (the surface)']),
            ('A rectangular current loop (width a = 0.1 m, length b = 0.2 m, I = 5 A, N = 100) is in B = 0.3 T. Find maximum torque.',
             ['μ = NIA = 100 × 5 × (0.1 × 0.2) = 10 A·m²', 'τ_max = μB = 10 × 0.3 = 3 N·m', 'Maximum torque at θ = 90° (plane of loop parallel to B)', 'This is the principle behind electric motor torque']),
            ('An electron enters a 1 T field at 45° to the field direction. Describe the resulting motion.',
             ['Component v_perp = v sin45° → circular motion in plane perpendicular to B', 'Component v_parallel = v cos45° → constant velocity along B direction', 'Combined: helical (corkscrew) motion along B direction', 'Helical pitch = v_parallel × T = v cos45° × 2πm/(qB)']),
            ('Compare Gauss\'s law for magnetism (∮B·dA = 0) with Gauss\'s law for electricity.',
             ['Electric: ∮E·dA = Q_enc/ε₀; flux ≠ 0 if charge enclosed', 'Magnetic: ∮B·dA = 0; always zero (no magnetic monopoles)', 'There are no isolated magnetic charges — every magnet has N and S', 'All magnetic field lines are closed loops; no starting or ending point']),
            ('Explain why a solenoid with 1000 turns and 1 A in 0.1 m has the same B as one with 2000 turns and 0.5 A in 0.2 m.',
             ['Both have same n and I: n₁ = 1000/0.1 = 10 000 m⁻¹, I₁ = 1 A → nI = 10 000', 'n₂ = 2000/0.2 = 10 000 m⁻¹, I₂ = 0.5 A → nI = 5000 (different!)', 'Actually nI = 10 000 vs 5000 — they are NOT the same; second has B = half', 'B = μ₀nI depends on turns per meter (n), not total turns'])
        ]
    },

    {
        'num': 5, 'title': 'Electromagnetism',
        'file': 'ap-physics-c-electricity-and-magnetism-5-unit-12-magnetic-fields-and-electromagnetism.html',
        'desc': 'Faraday\'s law, Lenz\'s law, inductance, RL circuits, and Maxwell\'s equations.',
        'gateway': [
            'Apply Faraday\'s law to calculate induced EMF from changing magnetic flux.',
            'Use Lenz\'s law to determine the direction of induced current.',
            'Calculate self-inductance and analyze RL circuit transient behavior.',
            'State and interpret all four of Maxwell\'s equations.',
        ],
        'lessons': [
            _l('Faraday\'s Law and Electromagnetic Induction',
               [_t('Faraday\'s Law', 'ε = -dΦ_B/dt; induced EMF equals the negative rate of change of magnetic flux. Flux: Φ_B = ∫B·dA.', 'The negative sign in Faraday\'s law is Lenz\'s law — the induced EMF opposes the change that caused it.', 'Calculate induced EMF from changing flux; apply Lenz\'s law for direction.'),
                _t('Motional EMF', 'A conductor of length L moving at velocity v in field B generates EMF = BLv (perpendicular case). Current flows if circuit is closed.', 'Motional EMF is the work done per unit charge by the magnetic force on moving charges in the conductor (F = qv × B).', 'Calculate motional EMF for conductors moving in B fields.'),
                _t('Lenz\'s Law', 'The induced current creates a magnetic field that opposes the change in flux. If flux is increasing, induced B opposes original B; if decreasing, induced B reinforces original B.', 'Lenz\'s law says induced current opposes the change in flux, not the flux itself — if flux is decreasing, induced current tries to maintain it.', 'Apply Lenz\'s law to determine induced current direction in various scenarios.')],
               [('Magnetic flux', 'Φ_B = ∫B·dA = BA cosθ for uniform B (Wb = T·m²)'),
                ('Faraday\'s law', 'ε = -dΦ_B/dt; induced EMF from changing flux'),
                ('Motional EMF', 'ε = BLv for conductor moving perpendicular to B'),
                ('Lenz\'s law', 'Induced current opposes change in flux (consequence of energy conservation)'),
                ('Eddy currents', 'Induced currents in bulk conductors due to changing B; cause heating and braking')],
               ['Calculate induced EMF using Faraday\'s law for various flux changes.',
                'Find motional EMF for a moving conductor in a B field.',
                'Apply Lenz\'s law to determine induced current direction.'],
               ['Free-response: find induced EMF and current for a loop entering a B field region.',
                'Motional EMF: find current and force on a sliding bar in a magnetic field.',
                'Lenz\'s law: determine direction of induced current in several scenarios.'],
               ['Practice Faraday\'s law for changing B, changing area, and moving conductors.',
                'Apply Lenz\'s law consistently for at least 5 different scenarios.'],
               [('A circular loop (r = 0.1 m) is in a field B = 0.5t T (increasing). Find induced EMF at t = 2 s.', ['Φ_B = B × A = 0.5t × π(0.1)² = 0.005πt', 'ε = -dΦ/dt = -0.005π V ≈ -15.7 mV', 'Magnitude: 15.7 mV; direction: opposes increasing B (Lenz)', 'Constant magnitude (dB/dt = 0.5 T/s is constant)']),
                ('A bar (L = 0.5 m) moves at v = 4 m/s perpendicular to B = 0.3 T in a U-channel (R = 2 Ω). Find EMF, I, and force on bar.', ['ε = BLv = 0.3 × 0.5 × 4 = 0.6 V', 'I = ε/R = 0.6/2 = 0.3 A', 'Force on bar: F = BIL = 0.3 × 0.3 × 0.5 = 0.045 N (opposing motion, Lenz)', 'Power: P = Fv = 0.045 × 4 = 0.18 W = I²R ✓']),
                ('A bar magnet is dropped through a copper ring. Describe the forces and motion.', ['As magnet approaches: increasing flux → induced current opposes increase → induced B repels magnet', 'As magnet passes through: flux decreases → induced B now attracts magnet (Lenz)', 'Net effect: eddy current braking — magnet falls slower than free fall', 'This is the basis of magnetic braking (maglev, eddy current brakes)']),
                ('A square loop (0.2 m side, R = 4 Ω) moves at 3 m/s into a region where B = 0.5 T (perpendicular). Find induced EMF and current.', ['While entering: one side (L = 0.2 m) cuts field lines', 'ε = BLv = 0.5 × 0.2 × 3 = 0.3 V', 'I = 0.3/4 = 0.075 A', 'Direction: by Lenz\'s law, opposes the increasing flux (counterclockwise when facing B)']),
                ('Explain why Lenz\'s law is a consequence of energy conservation.', ['If induced current aided the change in flux, it would increase the changing flux further', 'This would induce more current, more flux, more current — runaway positive feedback', 'Violates energy conservation (free energy from nowhere)', 'Lenz\'s law ensures the induced effects resist the cause, requiring energy input'])],
               [('Bozeman Faraday\'s Law', 'Faraday\'s law, motional EMF, Lenz\'s law', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Induction', 'Faraday\'s law and Lenz\'s law applications', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['ε = -dΦ/dt; Φ = BA cosθ.',
                'Motional EMF: ε = BLv for conductor moving perp. to B.',
                'Lenz\'s law: induced current opposes change in flux.']),

            _l('Inductance and RL Circuits',
               [_t('Self-Inductance', 'L = NΦ/I; induced EMF: ε = -L(dI/dt). For a solenoid: L = μ₀n²V = μ₀n²Al. Units: henry (H = V·s/A).', 'Self-inductance L depends on geometry only (like capacitance C) — not on current or applied EMF.', 'Calculate L for solenoids; use ε = -L(dI/dt) for inductors.'),
                _t('RL Circuit Transients', 'Charging: I(t) = (ε/R)(1 - e^{-Rt/L}) = I_max(1 - e^{-t/τ}); τ = L/R. Discharging: I(t) = I₀e^{-t/τ}.', 'At t = 0, an inductor opposes change in current (acts like open circuit); at t = ∞, acts like a short circuit (wire).', 'Derive and apply the RL transient equations.'),
                _t('Energy in an Inductor', 'U = ½LI²; stored in the magnetic field. Energy density in B field: u = B²/(2μ₀). Total energy in solenoid: U = ½LI² = B²Vol/(2μ₀).', 'Energy in an inductor is stored in the magnetic field throughout the volume, not at the terminals.', 'Calculate energy stored in an inductor and energy density of a B field.')],
               [('Self-inductance L', 'L = NΦ/I; units henry (H); opposes current changes'),
                ('Inductor EMF', 'ε = -L(dI/dt); inductor opposes changing current'),
                ('RL time constant', 'τ = L/R; larger L or smaller R → slower transient'),
                ('RL charging', 'I(t) = I_max(1-e^{-t/τ}); current increases exponentially toward I_max'),
                ('Energy in inductor', 'U = ½LI²; magnetic field energy density u = B²/(2μ₀)')],
               ['Calculate self-inductance for solenoids.',
                'Derive and apply RL transient equations for charging and discharging.',
                'Calculate energy stored in an inductor and in a B field.'],
               ['Free-response: derive I(t) for RL charging from the differential equation.',
                'Calculate L for a toroid and find energy stored at given I.',
                'Compare RL and RC transients: similarities and differences.'],
               ['Derive the RL charging equation by solving the KVL ODE.',
                'Calculate magnetic energy density for several B values.'],
               [('Derive L for an ideal solenoid (n turns/m, length l, area A).', ['B = μ₀nI; flux through one turn: Φ = BA = μ₀nIA', 'Total flux linkage: NΦ = (nl)(μ₀nIA) = μ₀n²lAI', 'L = NΦ/I = μ₀n²lA = μ₀n²V', 'Units: if μ₀ in T·m/A, L is in H']),
                ('Derive I(t) for RL charging from KVL.', ['KVL: ε = IR + L(dI/dt)', 'L(dI/dt) = ε - IR → dI/(ε-IR) = dt/L', 'Integrate: -1/R ln(ε-IR) = t/L + C', 'I(t) = (ε/R)(1 - e^{-Rt/L}) with I(0) = 0']),
                ('An inductor L = 0.5 H is in series with R = 100 Ω and ε = 12 V. Find τ, I at t = τ, and final I.', ['τ = L/R = 0.5/100 = 5 ms', 'I_max = ε/R = 12/100 = 0.12 A', 'I(τ) = I_max(1 - e^{-1}) = 0.12 × 0.632 = 75.8 mA', 'After 5τ = 25 ms: I ≈ 99.3% of 0.12 A ≈ 119 mA']),
                ('Find energy stored in inductor at final state and energy density in the solenoid if V = 0.01 m³.', ['U = ½LI_max² = ½(0.5)(0.12)² = 3.6 mJ', 'B = μ₀nI = μ₀(n)I; need n = √(L/(μ₀A l)) — or just use u = U/V', 'u = U/V = 3.6×10⁻³/0.01 = 0.36 J/m³', 'Check: u = B²/(2μ₀) → B = √(2μ₀u)']),
                ('Compare RL and RC transients side by side.', ['RC charging: q(t) = Cε(1-e^{-t/RC}); τ = RC; C↔L, q↔Φ, V↔I', 'RL charging: I(t) = (ε/R)(1-e^{-t/(L/R)}); τ = L/R', 'Both: exponential approach to steady state', 'RC: capacitor eventually blocks current; RL: inductor eventually passes current freely'])],
               [('Bozeman RL Circuits', 'Self-inductance, RL transients, energy in L', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Inductance', 'L = NΦ/I and RL charging derivation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['L = μ₀n²V for solenoid; ε = -L(dI/dt).',
                'RL: I = I_max(1-e^{-t/τ}); τ = L/R.',
                'Energy: U = ½LI²; density u = B²/(2μ₀).']),

            _l('Maxwell\'s Equations',
               [_t('Gauss\'s Law for E and B', '∮E·dA = Q_enc/ε₀ and ∮B·dA = 0. The first shows electric monopoles exist; the second shows magnetic monopoles do not.', 'The divergence of B is always zero — there are no magnetic monopole charges in nature.', 'State Gauss\'s law for both E and B and explain the physical difference.'),
                _t('Faraday\'s Law and Ampere-Maxwell Law', 'Faraday: ∮E·dl = -dΦ_B/dt. Ampere-Maxwell: ∮B·dl = μ₀I_enc + μ₀ε₀dΦ_E/dt. The displacement current μ₀ε₀dΦ_E/dt is Maxwell\'s addition.', 'Displacement current is not actual current — it is an equivalent term for changing electric flux, producing a B field as if it were a real current.', 'State all four Maxwell\'s equations and identify each\'s physical meaning.'),
                _t('Electromagnetic Waves', 'Maxwell\'s equations predict EM waves traveling at c = 1/√(μ₀ε₀) ≈ 3×10⁸ m/s. E and B are perpendicular to each other and to the direction of propagation; in phase.', 'E and B in an EM wave are in phase (both reach max at the same time), not 90° out of phase.', 'State the wave speed prediction from Maxwell\'s equations and describe E and B in an EM wave.')],
               [('Gauss E', '∮E·dA = Q_enc/ε₀; electric monopoles exist'),
                ('Gauss B', '∮B·dA = 0; no magnetic monopoles'),
                ('Faraday\'s law', '∮E·dl = -dΦ_B/dt; changing B induces E'),
                ('Ampere-Maxwell', '∮B·dl = μ₀I_enc + μ₀ε₀dΦ_E/dt; changing E induces B'),
                ('Displacement current', 'ε₀dΦ_E/dt; Maxwell\'s addition; allows EM waves to propagate')],
               ['State all four Maxwell\'s equations in integral form.',
                'Explain the physical meaning of the displacement current.',
                'Derive the wave speed c = 1/√(μ₀ε₀) from Maxwell\'s equations.'],
               ['Free-response: write and name all four Maxwell\'s equations.',
                'Calculate c from μ₀ and ε₀ numerically.',
                'Conceptual: explain why a changing E field produces B even with no current.'],
               ['Memorize all four Maxwell\'s equations in integral form.',
                'Explain displacement current in a charging capacitor.'],
               [('State all four Maxwell\'s equations and identify each physically.', ['1. ∮E·dA = Q_enc/ε₀ (Gauss E: electric charges create diverging E)', '2. ∮B·dA = 0 (Gauss B: no magnetic monopoles)', '3. ∮E·dl = -dΦ_B/dt (Faraday: changing B creates circulating E)', '4. ∮B·dl = μ₀I_enc + μ₀ε₀dΦ_E/dt (Ampere-Maxwell: current and changing E create B)']),
                ('Show that c = 1/√(μ₀ε₀) gives c ≈ 3×10⁸ m/s.', ['c = 1/√(μ₀ε₀) = 1/√(4π×10⁻⁷ × 8.85×10⁻¹²)', 'c = 1/√(1.113×10⁻¹⁷) = 1/(3.34×10⁻⁹)', 'c = 2.998×10⁸ m/s ≈ 3×10⁸ m/s', 'Maxwell predicted the speed of light from electrical constants — a landmark result']),
                ('Explain displacement current in a charging capacitor between the plates.', ['Conduction current I flows into the capacitor plates', 'Between plates: no actual charges, so I_conduction = 0', 'But E field between plates changes as capacitor charges: dE/dt ≠ 0', 'Displacement current I_d = ε₀dΦ_E/dt = I_conduction (continuous across gap)']),
                ('What would happen to electromagnetic waves if magnetic monopoles existed?', ['If magnetic monopoles existed: ∮B·dA = Q_m/μ₀ (nonzero)', 'Maxwell\'s equations would be symmetric in E and B', 'EM waves would still propagate; the theory would gain higher symmetry', 'No monopoles observed yet — the universe has this asymmetry']),
                ('What physical phenomenon does each pairing (Faraday + Ampere-Maxwell) describe?', ['Faraday: changing B → circulating E field (transformers, generators)', 'Ampere-Maxwell: changing E → circulating B field (makes waves self-sustaining)', 'Together: changing E creates B; changing B creates E — mutual sustaining wave', 'This self-regenerating pair is the electromagnetic wave'])],
               [('Bozeman Maxwell\'s Equations', 'All four equations and electromagnetic waves', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Maxwell', 'Displacement current and Maxwell\'s equations', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Maxwell: Gauss E, Gauss B, Faraday, Ampere-Maxwell.',
                'Displacement current: ε₀dΦ_E/dt; ensures B continuity.',
                'EM waves: c = 1/√(μ₀ε₀); E and B perpendicular, in phase.']),

            _l('LC and RLC Circuits',
               [_t('LC Oscillations', 'An ideal LC circuit oscillates: q(t) = Q₀cos(ωt); ω = 1/√(LC). Energy alternates between capacitor (½CV²) and inductor (½LI²). Analogous to SHM.', 'LC oscillations are analogous to mechanical SHM: L↔m, C↔1/k, q↔x, I↔v. All SHM results apply.', 'Derive the LC oscillation equation and find ω, T.'),
                _t('RLC Circuits', 'Adding R to an LC circuit causes damped oscillations: q(t) = Q₀e^{-Rt/(2L)} cos(ω\'t); ω\' = √(1/(LC)-(R/2L)²). R dissipates energy.', 'The RLC circuit is the electrical analog of a damped mechanical oscillator — same differential equation structure.', 'Classify RLC damping regime; describe effect of R on oscillations.'),
                _t('Resonance in RLC', 'In a driven RLC circuit, maximum current at resonance ω_d = ω₀ = 1/√(LC). Quality factor Q = ω₀L/R. Impedance: Z = √(R² + (ωL-1/(ωC))²).', 'At resonance, impedance Z = R (minimum); maximum current flows. Below resonance: capacitive; above: inductive.', 'Calculate resonance frequency, impedance, and Q for an RLC circuit.')],
               [('LC angular frequency', 'ω = 1/√(LC); analogous to √(k/m) in SHM'),
                ('LC energy', 'U = ½LI² + ½q²/C = const; alternates between L and C'),
                ('RLC damping', 'R causes exponential decay; ω\' < ω₀'),
                ('Resonance frequency', 'ω₀ = 1/√(LC); maximum current in driven RLC'),
                ('Q factor', 'Q = ω₀L/R; sharpness of resonance; higher Q → sharper peak')],
               ['Derive the LC oscillation equation and solve for q(t).',
                'Classify RLC damping and describe effect on oscillations.',
                'Calculate resonance frequency and Q factor for RLC circuit.'],
               ['Free-response: derive LC oscillation ODE and identify ω.',
                'RLC: find condition for critical damping.',
                'Resonance: plot I vs. ω_d and identify key features.'],
               ['Compare LC and SHM analogies systematically.',
                'Calculate Q and bandwidth for a given RLC resonant circuit.'],
               [('Derive the LC oscillation equation from KVL.', ['KVL: L(dI/dt) + q/C = 0; I = dq/dt → L(d²q/dt²) + q/C = 0', 'd²q/dt² = -q/(LC) = -ω²q; ω = 1/√(LC)', 'Solution: q(t) = Q₀cos(ωt + φ)', 'Identical to SHM ODE; L↔m, 1/C↔k, q↔x']),
                ('An LC circuit has L = 0.1 H and C = 10 μF. Find ω, T, and f.', ['ω = 1/√(LC) = 1/√(0.1 × 10⁻⁵) = 1/√(10⁻⁶) = 1000 rad/s', 'T = 2π/ω = 2π/1000 ≈ 6.28 ms', 'f = 1/T = 159 Hz', 'Energy oscillates between C and L at this frequency']),
                ('Describe the RLC circuit differential equation and its solution for underdamping.', ['L(d²q/dt²) + R(dq/dt) + q/C = 0', 'Analogous to damped oscillator: m x\'\' + bx\' + kx = 0', 'Underdamped: q(t) = Q₀e^{-Rt/(2L)} cos(ω\'t)', 'ω\' = √(ω₀² - (R/2L)²) < ω₀']),
                ('Find the resonance frequency and Q of an RLC circuit with R = 10 Ω, L = 0.5 H, C = 50 μF.', ['ω₀ = 1/√(LC) = 1/√(0.5 × 50×10⁻⁶) = 1/√(25×10⁻⁶) = 200 rad/s', 'Q = ω₀L/R = 200 × 0.5/10 = 10', 'Bandwidth = ω₀/Q = 200/10 = 20 rad/s', 'High Q: sharp resonance; low R means little energy lost per cycle']),
                ('Compare LC circuit energy to SHM mechanical energy.', ['LC: E = ½LI² + ½q²/C (magnetic + electric PE)', 'SHM: E = ½mv² + ½kx² (kinetic + spring PE)', 'L↔m, q↔x, I=dq/dt↔v, 1/C↔k', 'Both: total energy constant; each type oscillates at ω'])],
               [('Bozeman LC/RLC Circuits', 'LC oscillations, RLC damping, resonance', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics LC Circuit', 'Deriving LC oscillation from KVL', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['LC ODE: d²q/dt² = -q/(LC); ω = 1/√(LC).',
                'RLC: damped oscillations; ω\' < ω₀.',
                'Resonance: ω₀ = 1/√(LC); Q = ω₀L/R.']
               )
        ],
        'unit_qs': [
            ('A circular loop (r = 0.05 m, R = 2 Ω) has its B field changing at dB/dt = 50 T/s. Find induced EMF and current.',
             ['Φ = B × A = B × π(0.05)² = 7.85×10⁻³B', 'ε = -dΦ/dt = -A(dB/dt) = -7.85×10⁻³ × 50 = -0.393 V', 'I = |ε|/R = 0.393/2 = 0.196 A', 'Direction: Lenz\'s law — opposes increasing B']),
            ('A solenoid (L = 0.2 H, R = 5 Ω) is connected to 10 V. Find I at t = 0, t = τ, and t = ∞. Find energy stored at t = ∞.',
             ['τ = L/R = 0.2/5 = 0.04 s', 'I(0) = 0 (inductor opposes instantaneous change)', 'I(τ) = (10/5)(1-e⁻¹) = 2 × 0.632 = 1.26 A', 'I(∞) = ε/R = 2 A; U = ½LI² = ½(0.2)(4) = 0.4 J']),
            ('Derive the Ampere-Maxwell equation and explain the need for displacement current.',
             ['Original Ampere: ∮B·dl = μ₀I_enc (only real current)', 'Problem: in capacitor gap, I = 0 but B is nonzero (measured)', 'Fix: add displacement current I_d = ε₀dΦ_E/dt', 'Full law: ∮B·dl = μ₀(I_enc + ε₀dΦ_E/dt) — consistent with charge conservation']),
            ('A sliding bar (L = 0.3 m, v = 5 m/s) moves in B = 0.4 T with R = 0.6 Ω. Find EMF, I, braking force, and power.',
             ['ε = BLv = 0.4 × 0.3 × 5 = 0.6 V', 'I = 0.6/0.6 = 1 A', 'F_brake = BIL = 0.4 × 1 × 0.3 = 0.12 N (opposing v)', 'P_mech = Fv = 0.12 × 5 = 0.6 W = I²R ✓ (energy conservation)']),
            ('An LC circuit (L = 0.08 H, C = 200 μF) oscillates with Q₀ = 400 μC. Find ω, period, max current, and max energy.',
             ['ω = 1/√(LC) = 1/√(0.08 × 2×10⁻⁴) = 1/√(1.6×10⁻⁵) = 250 rad/s', 'T = 2π/250 ≈ 25.1 ms', 'I_max = Q₀ω = 400×10⁻⁶ × 250 = 0.1 A', 'U = Q₀²/(2C) = (4×10⁻⁴)²/(4×10⁻⁴) = 4×10⁻⁴ J = ½LI_max² ✓']),
            ('Explain how a transformer works using Faraday\'s law.',
             ['Primary coil: alternating current → changing B in core', 'Changing B → changing Φ in secondary coil (Faraday)', 'Induced EMF in secondary: ε₂/ε₁ = N₂/N₁ (turns ratio)', 'Ideal transformer: P₁ = P₂ → I₁V₁ = I₂V₂']),
            ('Find the condition for critical damping in an RLC circuit.',
             ['ω\' = √(ω₀² - (R/2L)²) = 0 for critical damping', '(R/2L)² = ω₀² = 1/(LC)', 'R/2L = 1/√(LC) → R = 2√(L/C)', 'Critical damping: fastest return to equilibrium without oscillating']),
            ('A rectangular loop (0.2 m × 0.1 m, N = 100, R = 5 Ω) rotates at 60 Hz in B = 0.3 T. Find peak EMF.',
             ['ε = NBAω sin(ωt); peak at sin = 1', 'A = 0.2 × 0.1 = 0.02 m²; ω = 2π × 60 = 120π rad/s', 'ε_max = NBA ω = 100 × 0.3 × 0.02 × 120π', 'ε_max = 0.6 × 120π ≈ 226 V']),
            ('Calculate the energy density in a magnetic field of B = 2 T (typical MRI field).',
             ['u = B²/(2μ₀) = (2)²/(2 × 4π×10⁻⁷)', 'u = 4/(8π×10⁻⁷) = 4/(2.513×10⁻⁶) = 1.59×10⁶ J/m³', 'u ≈ 1.59 MJ/m³ — enormous energy density', 'MRI machine stores this energy in the superconducting solenoid']),
            ('An RLC circuit has R = 20 Ω, L = 0.5 H, C = 500 μF driven at resonance. Find I_max for ε₀ = 50 V peak.',
             ['At resonance: Z = R = 20 Ω (reactive terms cancel)', 'I_max = ε₀/Z = 50/20 = 2.5 A', 'V_L and V_C are both large but cancel: V_L = I_max ω₀L, V_C = I_max/(ω₀C)', 'Q factor = ω₀L/R = (200)(0.5)/20 = 5; voltage across L or C = QV_source'])
        ]
    },

    {
        'num': 6, 'title': 'Electromagnetic Induction and Applications',
        'file': 'ap-physics-c-electricity-and-magnetism-6-unit-13-electromagnetic-induction.html',
        'desc': 'Advanced induction: mutual inductance, generators, transformers, AC circuits, and electromagnetic wave energy.',
        'gateway': [
            'Calculate mutual inductance and induced EMF between coupled coils.',
            'Analyze AC circuits using phasors and impedance.',
            'Explain the operation of transformers, generators, and motors.',
            'Calculate energy and momentum carried by electromagnetic waves.',
        ],
        'lessons': [
            _l('Mutual Inductance and Coupled Circuits',
               [_t('Mutual Inductance', 'M = NΦ₁₂/I₂; when current in coil 2 changes, EMF is induced in coil 1: ε₁ = -M(dI₂/dt). M is symmetric: M₁₂ = M₂₁.', 'Mutual inductance M is symmetric — the effect of coil 1 on coil 2 equals the reverse.', 'Calculate M for coaxial solenoids and determine induced EMF.'),
                _t('Coupled Circuits and Transformers', 'Ideal transformer: ε₂/ε₁ = N₂/N₁; I₁/I₂ = N₂/N₁; P₁ = P₂. The coupling coefficient k = M/√(L₁L₂) (k = 1 ideal).', 'An ideal transformer conserves power (P₁ = P₂) — not charge or current — and assumes no flux leakage.', 'Apply transformer ratios; explain step-up and step-down configurations.'),
                _t('Generators and Motors', 'Generator: mechanical rotation → electrical energy; EMF = NBAω sinωt. Motor: electrical energy → mechanical; torque τ = NIABsinθ. Both use Faraday\'s law.', 'Generators and motors are the same device operated in reverse — a motor acts as a generator and vice versa.', 'Derive the generator EMF equation; explain back-EMF in a motor.')],
               [('Mutual inductance M', 'M = NΦ₁₂/I₂; coupling between two coils (H)'),
                ('Induced EMF (mutual)', 'ε₁ = -M(dI₂/dt); changing current in 2 induces EMF in 1'),
                ('Ideal transformer', 'V₂/V₁ = N₂/N₁; I₁/I₂ = N₂/N₁; P₁ = P₂'),
                ('Generator EMF', 'ε = NBAω sinωt; peak EMF = NBAω'),
                ('Back-EMF', 'EMF generated by motor opposing source voltage; limits current')],
               ['Calculate M for coupled coils and find induced EMF.',
                'Apply transformer ratios for step-up and step-down configurations.',
                'Derive and apply the generator EMF equation.'],
               ['Free-response: derive EMF of a rotating rectangular loop in B field.',
                'Transformer: find secondary voltage, current, and power.',
                'Motor: explain how back-EMF limits current and why motors draw more current at start.'],
               ['Practice M and transformer calculations.',
                'Derive the peak EMF formula for a generator.'],
               [('Two coaxial solenoids: inner (N₁ = 500, L = 0.1 m, A = 4 cm²) and outer (N₂ = 200). Find M.', ['B in inner solenoid: B = μ₀(N₁/L)I₁ = μ₀ × 5000 × I₁', 'Flux through outer: Φ₂₁ = B × A = μ₀ × 5000 × 4×10⁻⁴ × I₁', 'M = N₂Φ₂₁/I₁ = 200 × μ₀ × 5000 × 4×10⁻⁴', 'M = 200 × 4π×10⁻⁷ × 5000 × 4×10⁻⁴ = 502 μH']),
                ('A step-up transformer has N₁ = 100, N₂ = 500, primary V₁ = 120 V, I₁ = 2 A. Find V₂, I₂, and power.', ['V₂ = V₁(N₂/N₁) = 120 × 5 = 600 V (step-up)', 'I₂ = I₁(N₁/N₂) = 2/5 = 0.4 A', 'P₁ = V₁I₁ = 240 W = P₂ = V₂I₂ = 600 × 0.4 = 240 W ✓', 'High voltage reduces current → less resistive loss in transmission lines']),
                ('A rectangular loop (N = 50, A = 0.01 m², B = 0.3 T) rotates at 60 Hz. Find peak EMF.', ['ω = 2π × 60 = 120π rad/s', 'ε_peak = NBAω = 50 × 0.3 × 0.01 × 120π', 'ε_peak = 0.15 × 120π = 56.5 V', 'ε(t) = 56.5 sin(120πt) V']),
                ('Explain why a motor draws more current at startup than at full speed.', ['At startup: ω = 0 → back-EMF = 0', 'Current I = (V_source - ε_back)/R; at start, ε_back = 0 → I = V/R (high)', 'At full speed: ε_back = NBAω ≈ V_source → I ≈ 0 (ideally)', 'Large starting current can cause damage → starter resistors or soft-start controls']),
                ('Derive the formula ε = NBAω sinωt for a generator.', ['Loop rotates at angular speed ω; angle θ = ωt', 'Flux: Φ = NBA cosθ = NBA cos(ωt)', 'EMF: ε = -dΦ/dt = NBAω sin(ωt)', 'Peak EMF: ε₀ = NBAω; occurs when plane of loop is parallel to B'])],
               [('Bozeman Mutual Inductance', 'M, transformers, and generators', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Generator', 'Generator EMF derivation and transformer ratios', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['M = NΦ₁₂/I₂; ε₁ = -M(dI₂/dt).',
                'Transformer: V₂/V₁ = N₂/N₁; P₁ = P₂.',
                'Generator: ε = NBAω sinωt; peak EMF = NBAω.']),

            _l('AC Circuits and Phasors',
               [_t('AC Voltage and Current', 'V(t) = V₀ sin(ωt); I(t) = I₀ sin(ωt + φ). RMS values: V_rms = V₀/√2; I_rms = I₀/√2. Power: P_avg = V_rms I_rms cosφ.', 'RMS voltage, not peak voltage, is used for power calculations and is what household "120 V" refers to.', 'Convert between peak and RMS values; calculate average power with power factor.'),
                _t('Phasors and Impedance', 'Resistor: V and I in phase. Inductor: V leads I by 90° (ELI). Capacitor: V lags I by 90° (ICE). Impedance Z: Z_R = R, Z_L = jωL, Z_C = 1/(jωC). Total Z = √(R² + (X_L - X_C)²).', 'In a phasor diagram, rotating vectors (phasors) represent V and I — their projections onto the real axis give instantaneous values.', 'Calculate impedance and phase angle for series RLC circuits.'),
                _t('Power Factor and Resonance', 'Power factor cosφ = R/Z; average power P = I_rms² R. At resonance (X_L = X_C), cosφ = 1 and P is maximum. Q = ω₀L/R.', 'Average power is dissipated only in resistors, not in ideal L or C — reactive elements store and return energy.', 'Calculate power factor and average power for AC circuits.')],
               [('V_rms', 'V_rms = V₀/√2 ≈ 0.707V₀; root-mean-square voltage'),
                ('Impedance Z', 'Z = √(R² + (X_L - X_C)²); total opposition to AC current'),
                ('Inductive reactance X_L', 'X_L = ωL; increases with frequency'),
                ('Capacitive reactance X_C', 'X_C = 1/(ωC); decreases with frequency'),
                ('Power factor', 'cosφ = R/Z; fraction of apparent power that does real work')],
               ['Calculate V_rms and I_rms from peak values.',
                'Find impedance and phase angle for series RLC circuits.',
                'Calculate average power and power factor for AC circuits.'],
               ['Free-response: find I₀, phase angle, and P_avg for a series RLC at given ω.',
                'Phasor diagram: draw and label V and I phasors for RLC circuit.',
                'Resonance: find ω₀ for max power; calculate Q.'],
               ['Practice impedance calculations at different frequencies.',
                'Draw phasor diagrams for R, RL, RC, and RLC circuits.'],
               [('A series RLC circuit (R = 30 Ω, L = 0.1 H, C = 100 μF) at ω = 200 rad/s. Find X_L, X_C, Z, and I if V₀ = 100 V.', ['X_L = ωL = 200 × 0.1 = 20 Ω', 'X_C = 1/(ωC) = 1/(200 × 10⁻⁴) = 50 Ω', 'Z = √(30² + (20-50)²) = √(900+900) = √1800 ≈ 42.4 Ω', 'I₀ = V₀/Z = 100/42.4 ≈ 2.36 A']),
                ('Find phase angle and average power for the circuit above.', ['tanφ = (X_C - X_L)/R = (50-20)/30 = 1 → φ = 45° (capacitive, I leads V)', 'P_avg = ½V₀I₀cosφ = ½(100)(2.36)(cos45°) = ½(100)(2.36)(0.707) ≈ 83.5 W', 'Or: P_avg = I_rms² R = (2.36/√2)² × 30 = 2.78 × 30 = 83.5 W ✓', 'Only R dissipates power; L and C store energy cyclically']),
                ('A power plant delivers 50 MW at 345 kV. Find the current in the transmission line.', ['I = P/V = 50×10⁶/(345×10³) = 144.9 A ≈ 145 A', 'If at 1000 V instead: I = 50000 A — huge resistive loss', 'High voltage → low current → small I²R losses in transmission lines', 'Transformers enable efficient long-distance power transmission']),
                ('Explain the mnemonic ELI the ICE man for phase in AC circuits.', ['ELI: in an inductor (L), Voltage (E) leads Current (I)', 'ICE: in a capacitor (C), Current (I) leads Voltage (E) — or equivalently V lags I', 'Resistor: E and I are in phase', 'These phase relationships come from V_L = L(dI/dt) and I_C = C(dV/dt)']),
                ('At resonance in a series RLC circuit, what happens to X_L, X_C, and Z?', ['At resonance: X_L = X_C → ωL = 1/(ωC) → ω₀ = 1/√(LC)', 'Z = √(R² + 0) = R (minimum impedance at resonance)', 'I = V/R (maximum current)', 'φ = 0: voltage and current in phase; power factor = 1'])],
               [('Bozeman AC Circuits', 'Impedance, phasors, and AC power', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics AC', 'RLC impedance and resonance', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['V_rms = V₀/√2; Z = √(R² + (X_L-X_C)²).',
                'ELI (inductor): V leads I; ICE (capacitor): I leads V.',
                'P_avg = I_rms² R; power factor cosφ = R/Z.']),

            _l('Electromagnetic Wave Energy and Momentum',
               [_t('Poynting Vector', 'S = E × B/μ₀ (W/m²); energy flux density of EM wave. Intensity I = |S| = E₀B₀/(2μ₀) = E₀²/(2μ₀c) = cε₀E₀²/2.', 'The Poynting vector gives power per unit area flowing in the direction of wave propagation.', 'Calculate intensity from E₀ or B₀ of an EM wave.'),
                _t('Radiation Pressure', 'EM waves carry momentum: p = U/c (absorbed) or p = 2U/c (reflected). Radiation pressure P = I/c (absorbed) or 2I/c (reflected).', 'Radiation pressure is extremely small for normal light intensities — significant only for high-power lasers or in space.', 'Calculate radiation pressure and momentum transfer from EM waves.'),
                _t('Electromagnetic Spectrum', 'EM waves span radio to gamma rays; all travel at c = 3×10⁸ m/s; E = hf (photon energy, quantum). Wavelength-frequency: c = fλ.', 'All EM waves travel at c in vacuum; speed changes in media (c/n).', 'Apply c = fλ to convert between frequency and wavelength; identify spectrum regions.')],
               [('Poynting vector S', 'S = E×B/μ₀; power per unit area (W/m²)'),
                ('Intensity I', 'I = |S_avg| = E₀²/(2μ₀c); power per unit area of EM wave'),
                ('Radiation momentum', 'p = U/c (absorbed); p = 2U/c (reflected)'),
                ('Radiation pressure', 'P = I/c (absorbed) or 2I/c (reflected)'),
                ('EM spectrum', 'Radio → microwave → IR → visible → UV → X-ray → gamma; all at c in vacuum')],
               ['Calculate intensity and Poynting vector from E₀ of an EM wave.',
                'Find radiation pressure for absorbed and reflected waves.',
                'Convert between frequency and wavelength across the EM spectrum.'],
               ['Free-response: find intensity and radiation pressure for a laser beam.',
                'Calculate force on a solar sail due to radiation pressure.',
                'Identify regions of EM spectrum from wavelength or frequency.'],
               ['Practice intensity calculations from E₀ and B₀.',
                'Calculate solar radiation pressure on spacecraft surfaces.'],
               [('An EM wave has E₀ = 100 V/m. Find B₀, intensity, and energy density.', ['B₀ = E₀/c = 100/(3×10⁸) = 3.33×10⁻⁷ T', 'I = E₀²/(2μ₀c) = (10⁴)/(2 × 4π×10⁻⁷ × 3×10⁸) = 13.3 W/m²', 'u = ε₀E₀² (total: electric + magnetic) = (8.85×10⁻¹²)(10⁴) = 8.85×10⁻⁸ J/m³ (instantaneous peak)', 'Average: u_avg = I/c = 13.3/(3×10⁸) ≈ 4.43×10⁻⁸ J/m³']),
                ('A laser (P = 1 kW) is focused to A = 1 mm² spot. Find intensity and radiation pressure on a perfect absorber.', ['I = P/A = 1000/(10⁻⁶) = 10⁹ W/m²', 'Radiation pressure: P_rad = I/c = 10⁹/(3×10⁸) = 3.33 Pa', 'Force on spot = P_rad × A = 3.33 × 10⁻⁶ = 3.33 μN', 'Small force — but extremely intense; could vaporize material']),
                ('A solar sail (area = 1 km² = 10⁶ m²) at Earth orbit (I = 1360 W/m²). Find force if sail reflects all light.', ['P_rad = 2I/c = 2(1360)/(3×10⁸) = 9.07×10⁻⁶ Pa', 'Force = P_rad × A = 9.07×10⁻⁶ × 10⁶ = 9.07 N', 'Small force but no propellant needed — accelerates over time', 'After 1 year: Δv = F×t/m (substantial for light spacecraft)']),
                ('Visible light has wavelength 550 nm. Find its frequency and photon energy. (h = 6.63×10⁻³⁴ J·s)', ['f = c/λ = 3×10⁸/(550×10⁻⁹) = 5.45×10¹⁴ Hz', 'E_photon = hf = (6.63×10⁻³⁴)(5.45×10¹⁴) = 3.61×10⁻¹⁹ J = 2.26 eV', 'Green light: 550 nm wavelength', 'UV (λ < 400 nm) has higher energy → can damage DNA']),
                ('Why do E and B have the relationship E = cB in an EM wave?', ['From Faraday: ∂E/∂t relates to ∂B/∂x in a wave', 'From Ampere-Maxwell: ∂B/∂t relates to ∂E/∂x', 'Wave solution gives: E/B = ω/k = c (wave speed)', 'E = cB holds for EM waves in vacuum; in media, c → c/n'])],
               [('Bozeman EM Waves Energy', 'Poynting vector, radiation pressure, EM spectrum', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics EM Wave', 'Intensity and radiation pressure', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['S = E×B/μ₀; I = E₀²/(2μ₀c).',
                'Radiation pressure: I/c absorbed; 2I/c reflected.',
                'c = fλ; E and B perpendicular, in phase; E = cB.']),

            _l('Applications: Motors, Generators, and Power Systems',
               [_t('AC Power Generation', 'Power plants convert mechanical energy → AC power. Three-phase power provides constant total power (no zero crossings). Transmitted at high voltage to minimize I²R losses.', 'Three-phase power is used because single-phase power is zero twice per cycle — three-phase provides constant power.', 'Explain qualitatively why AC is used for power transmission and three-phase for motors.'),
                _t('Induction Motors and Eddy Currents', 'Induction motors: rotating magnetic field induces currents in the rotor, creating torque. No brushes or commutator. Eddy currents in transformers cause energy loss — laminated cores reduce them.', 'Eddy currents are induced by changing flux — using laminated cores breaks the current loops and reduces losses.', 'Explain induction motor operation and how eddy currents are minimized.'),
                _t('Practical Circuit Applications', 'Rectifiers convert AC to DC using diodes. Filters smooth ripple. Voltage regulators maintain constant DC output. These are the basis of all electronic power supplies.', 'A diode allows current in one direction — a bridge rectifier uses four diodes to convert full-wave AC to pulsating DC.', 'Trace the path of current through a full-wave bridge rectifier; explain filter capacitor function.')],
               [('Three-phase power', 'Three AC voltages 120° apart; sum is constant; used industrially'),
                ('Induction motor', 'Rotating field induces rotor currents; torque without brushes'),
                ('Eddy currents', 'Currents induced in bulk conductors by changing B; cause power loss'),
                ('Laminated core', 'Thin insulated sheets break eddy current paths → reduced loss'),
                ('Rectifier', 'Diode circuit converting AC to pulsating DC')],
               ['Explain why AC power is transmitted at high voltage.',
                'Describe how an induction motor and eddy current braking work.',
                'Trace current through a bridge rectifier and explain the filter capacitor.'],
               ['Free-response: calculate power loss in a transmission line at high vs. low voltage.',
                'Multiple choice: identify the effect of increasing transmission voltage.',
                'Conceptual: explain why transformer cores are laminated.'],
               ['Calculate transmission line losses for different voltages.',
                'Research practical applications of induction motors in industry.'],
               [('A power plant outputs 100 MW at 1000 V. Transmission line R = 10 Ω. Find power loss. Compare to 100 kV.', ['At 1000 V: I = P/V = 100×10⁶/1000 = 10⁵ A', 'P_loss = I²R = (10⁵)² × 10 = 10¹¹ W → 100 GW (impossible!)', 'At 100 kV: I = 10⁶/10⁵ = 1000 A; P_loss = 10⁶ × 10 = 10 MW (10%)', 'High voltage reduces current 100×, losses by 10 000×']),
                ('How does an induction motor rotate without any mechanical contact to the rotor?', ['Stator coils with three-phase current create a rotating magnetic field', 'Rotating B induces currents in the conducting rotor (Faraday)', 'Induced currents experience force from the rotating B (Lenz) → torque', 'Rotor tries to "catch" the rotating field — slight slip maintains current induction']),
                ('Why does a transformer core need to be laminated to reduce losses?', ['Changing B in core induces eddy currents in the metal core', 'Eddy currents: I²R loss (heat) and opposing flux (reduced efficiency)', 'Lamination: thin insulated layers perpendicular to eddy currents', 'Breaks large current loops → much smaller eddy currents → much less loss']),
                ('A bridge rectifier converts 120 V rms to DC. What is the peak output voltage?', ['V_peak = V_rms × √2 = 120 × 1.414 = 169.7 V', 'Rectifier: full-wave, so output is |sin| — positive pulses at 120 Hz', 'Without filter: DC_avg = (2/π)V_peak ≈ 108 V', 'With large filter capacitor: output ≈ V_peak with small ripple ≈ 170 V']),
                ('Explain the role of a filter capacitor in a DC power supply.', ['Rectifier output is pulsating DC (not steady)', 'Capacitor charges to V_peak, discharges slowly through load during zero crossing', 'Large C → small ripple; slow discharge between peaks', 'RC time constant must be >> period of AC (1/120 s ≈ 8 ms)'])],
               [('Bozeman Power Systems', 'AC generation, motors, and power transmission', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Power Transmission', 'Why high voltage; eddy currents', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['High voltage transmission: low I → low I²R loss.',
                'Induction motor: rotating B field induces rotor currents → torque.',
                'Laminated cores: reduce eddy current losses in transformers.'])
        ],
        'unit_qs': [
            ('A generator (N = 200 turns, A = 0.02 m², B = 0.5 T) rotates at 3000 rpm. Find peak EMF and rms voltage.',
             ['ω = 3000 rev/min × 2π/60 = 100π rad/s ≈ 314 rad/s', 'ε₀ = NBAω = 200 × 0.5 × 0.02 × 314 = 628 V', 'V_rms = ε₀/√2 = 628/1.414 ≈ 444 V', 'This is a large generator; commercial power systems use similar principles']),
            ('An RLC series circuit (R = 50 Ω, L = 0.2 H, C = 20 μF) at ω = 500 rad/s. Find Z, I_rms for V_rms = 120 V, and P_avg.',
             ['X_L = ωL = 500 × 0.2 = 100 Ω; X_C = 1/(ωC) = 1/(500×20×10⁻⁶) = 100 Ω', 'Z = √(50² + (100-100)²) = 50 Ω (resonance!)', 'I_rms = V_rms/Z = 120/50 = 2.4 A', 'P_avg = I_rms² R = (2.4)²(50) = 288 W; cosφ = 1']),
            ('Derive the energy density of EM wave in terms of E₀: u_avg = ε₀E₀²/2.',
             ['Electric energy density: u_E = ½ε₀E² = ½ε₀E₀²sin²(ωt-kx)', 'Magnetic energy density: u_B = B²/(2μ₀) = E²/(2μ₀c²) = ε₀E²/2 = u_E', 'Total instantaneous: u = ε₀E²; average: u_avg = ε₀E₀²/2', 'Intensity: I = u_avg × c = ε₀cE₀²/2 = E₀²/(2μ₀c)']),
            ('Two transformers step 120 V up to 12 000 V, transmit through 100 Ω line, then step down to 120 V. Find P_loss and efficiency for P = 10 kW.',
             ['Transmission I = P/V = 10 000/12 000 = 0.833 A', 'P_loss = I²R = (0.833)²(100) = 69.4 W', 'Efficiency = (P - P_loss)/P = (10 000 - 69.4)/10 000 = 99.3%', 'High-voltage transmission is essential for efficient power delivery']),
            ('An inductor L = 50 mH carries AC I = 3 sin(100πt) A. Find EMF across inductor, peak and rms values.',
             ['ε_L = -L(dI/dt) = -L × 3 × 100π cos(100πt)', 'ε_L = -0.05 × 300π cos(100πt) = -47.1 cos(100πt) V', 'Peak EMF = 47.1 V; V_rms = 47.1/√2 ≈ 33.3 V', 'Voltage leads current by 90° in inductor (ELI)']),
            ('Calculate mutual inductance M between two coaxial solenoids (inner: 1000 turns, 0.2 m, 2 cm radius; outer: 500 turns).',
             ['B_inner = μ₀(1000/0.2)I = 5000μ₀I', 'Flux through outer: Φ = B × π(0.02)² = 5000μ₀I × π×4×10⁻⁴', 'M = N_outer × Φ / I = 500 × 5000μ₀ × 4π×10⁻⁴', 'M = 500 × 5000 × 4π×10⁻⁷ × 4π×10⁻⁴ ≈ 394 μH']),
            ('At what frequency does a 0.5 H inductor have the same reactance as a 50 μF capacitor?',
             ['X_L = X_C: ωL = 1/(ωC) → ω² = 1/(LC)', 'ω = 1/√(0.5 × 50×10⁻⁶) = 1/√(25×10⁻⁶) = 200 rad/s', 'f = ω/(2π) = 200/(2π) ≈ 31.8 Hz', 'This is the resonance frequency of an LC circuit with these values']),
            ('Explain why eddy current heating is used in induction cooktops.',
             ['Changing B from coil induces eddy currents in ferromagnetic pot', 'Eddy currents (I²R) heat the pot directly — not the cooktop surface', 'Only magnetic materials heat up; glass cooktop stays relatively cool', 'Efficient, precise, and safe heating; no open flame or hot element']),
            ('An EM wave has I = 500 W/m². Find E₀, B₀, radiation pressure on perfect absorber, and force on 1 m² surface.',
             ['E₀ = √(2Iμ₀c) = √(2 × 500 × 4π×10⁻⁷ × 3×10⁸) = √(376.9) ≈ 614 V/m', 'B₀ = E₀/c = 614/(3×10⁸) = 2.05 μT', 'P_rad = I/c = 500/(3×10⁸) = 1.67 μPa', 'F = P_rad × A = 1.67×10⁻⁶ × 1 = 1.67 μN']),
            ('Describe the operation of a three-phase induction motor from first principles.',
             ['Three coil sets in stator, driven by three-phase AC (120° apart in phase)', 'At each instant, currents create a resultant rotating magnetic field in the stator', 'Rotating B induces currents in the short-circuited squirrel-cage rotor (Faraday)', 'Induced currents and rotating B create torque (Lenz) — rotor follows the field'])
        ]
    },
]
