NAME = 'AP® Physics 1 & 2'
ABBREV = 'phys12'
SLUG = 'ap-physics-1-2'
COURSE_FILE = 'ap-physics-1-2.html'
ACCENT_COLOR = '#34d399'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+1+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+1+'

def _t(title, content, mis, tested):
    return {'title': title, 'content': content, 'misconception': mis, 'how_tested': tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
{
  'num': 6, 'title': 'Energy and Waves',
  'file': 'ap-physics-1-2-6-physics-1-unit-6-simple-harmonic-motion.html',
  'desc': 'Analyze mechanical waves, their properties, and energy transport; apply the wave model to sound and standing waves.',
  'gateway': [
      'Describe transverse and longitudinal waves using amplitude, wavelength, frequency, and period.',
      'Apply v = fλ to wave problems.',
      'Explain the behavior of waves at boundaries (reflection, transmission, superposition).',
      'Describe standing waves and resonance on strings and in air columns.',
  ],
  'lessons': [
      _l('Wave Properties',
         [_t('Transverse and Longitudinal Waves', 'Transverse waves have particle motion perpendicular to wave propagation (e.g., string waves). Longitudinal waves have particle motion parallel to propagation (e.g., sound). Both transport energy without transporting matter.', 'Students think the medium moves with the wave; particles oscillate about equilibrium — the wave pattern moves, not the particles.', 'Classify waves as transverse or longitudinal; draw the particle oscillation direction relative to wave propagation.'),
          _t('Wave Speed, Frequency, Wavelength', 'v = fλ. Wave speed depends on the medium, not the source frequency. Frequency f = 1/T where T is the period.', 'Students think increasing frequency increases wave speed; v depends on the medium (e.g., tension and mass density for strings), not f.', 'Apply v=fλ to find any one of the three quantities given the other two.'),
          _t('Amplitude and Energy', 'The energy carried by a wave is proportional to the square of the amplitude (E ∝ A²). Doubling amplitude quadruples the energy. Intensity I = P/A (power per area).', 'Students think energy is proportional to amplitude (linear); wave energy scales as A², not A.', 'Calculate the ratio of energies or intensities when amplitude or distance changes.')],
         [('transverse wave', 'Particle motion perpendicular to wave direction'),
          ('longitudinal wave', 'Particle motion parallel to wave direction (e.g., sound)'),
          ('v = fλ', 'Wave speed equals frequency times wavelength'),
          ('amplitude', 'Maximum displacement from equilibrium; energy ∝ A²')],
         ['Classify wave types and describe particle motion', 'Apply v=fλ to solve for wave speed, frequency, or wavelength', 'Relate amplitude to energy carried by a wave'],
         ['Wave property calculations in MC', 'Transverse vs. longitudinal identification in MC', 'Energy/amplitude ratio questions in FR'],
         ['Find wavelength of sound (v=340 m/s) at 440 Hz', 'If amplitude doubles, by what factor does wave energy change?'],
         [('Sound travels at 340 m/s. A 680 Hz sound wave has what wavelength?', ['v=fλ → λ=v/f=340/680=0.5 m', 'Wavelength = 0.5 m', 'Higher frequency → shorter wavelength', 'At 34 Hz: λ=10 m']),
          ('A wave has amplitude 3 cm. Another has amplitude 6 cm. What is the ratio of their energies?', ['E ∝ A²', 'E₂/E₁=(6/3)²=4', 'The larger wave has 4 times more energy', 'Doubling amplitude quadruples energy']),
          ('A transverse wave moves right. Describe the motion of a particle in the medium.', ['Particle moves up and down (perpendicular to wave motion)', 'Oscillates about equilibrium position', 'Does not travel with the wave', 'String wave example: pluck a guitar string']),
          ('A wave has period T=0.04 s. Find frequency and wavelength if v=8 m/s.', ['f=1/T=1/0.04=25 Hz', 'λ=v/f=8/25=0.32 m', 'Both calculations use the relationship v=fλ', 'Wavelength=0.32 m']),
          ('How does changing medium affect wave speed vs. frequency?', ['Speed depends on medium properties (tension, density, elasticity)', 'Frequency is set by the source and does not change when medium changes', 'When wave enters new medium: v changes, λ changes, f stays constant', 'v=fλ; f fixed → λ adjusts to new v'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Wave Properties', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State v=fλ and the units of each variable', 'Classify sound as transverse or longitudinal', 'Explain why energy is proportional to A² not A']),

      _l('Reflection, Transmission, and Superposition',
         [_t('Reflection at Boundaries', 'At a fixed (hard) boundary, a wave inverts on reflection (phase shift of π). At a free (soft) boundary, the wave reflects without inversion. Some energy is transmitted into the new medium.', 'Students think waves always invert on reflection; inversion only occurs at fixed/hard boundaries, not at free/soft ones.', 'Predict whether a wave inverts or not at a given boundary type.'),
          _t('Superposition Principle', 'When two waves meet, the resultant displacement is the algebraic sum of individual displacements (superposition). After passing through, each wave continues unchanged.', 'Students think waves collide and are destroyed; waves pass through each other — superposition is temporary and each wave continues independently.', 'Apply superposition to find the resultant of two overlapping wave pulses.'),
          _t('Constructive and Destructive Interference', 'Constructive interference: crests align → amplitude doubles. Destructive interference: crest meets trough → cancellation. For complete cancellation, amplitudes must be equal.', 'Students think destructive interference destroys energy; energy is redistributed — where destructive interference occurs, energy appears elsewhere.', 'Identify constructive and destructive interference from wave diagrams; calculate resultant amplitude.')],
         [('fixed boundary', 'Rigid end; wave inverts on reflection'),
          ('free boundary', 'Open end; wave reflects without inversion'),
          ('superposition', 'Resultant = algebraic sum of individual displacements'),
          ('constructive interference', 'Crests align; amplitude doubles'),
          ('destructive interference', 'Crest meets trough; amplitude decreases or cancels')],
         ['Predict wave reflection (inverted or upright) based on boundary type', 'Apply superposition to determine resultant displacement', 'Identify constructive and destructive interference'],
         ['Boundary reflection type tested in MC', 'Superposition of two pulses drawn/described in FR', 'Interference described in MC and explained in FR'],
         ['Draw result of two equal pulses meeting: one upright, one inverted', 'Predict what happens when a wave pulse reaches a fixed vs. free end'],
         [('A wave pulse reaches a fixed wall. Describe the reflected pulse.', ['Reflects with inverted shape (phase shift of 180°)', 'If crest goes in, trough comes out', 'Amplitude unchanged (assuming no energy loss)', 'Fixed boundary = hard wall']),
          ('Two identical pulses (height 2 cm) approach each other on a string. When they overlap completely, what is the displacement?', ['Constructive interference: amplitudes add', '2+2=4 cm at peak overlap', 'After passing: each pulse continues with original shape', 'Superposition is temporary']),
          ('A crest (amplitude +3 cm) and trough (amplitude −3 cm) overlap completely. What is the displacement?', ['Destructive interference: +3+(−3)=0', 'Complete cancellation at that instant', 'Energy is not destroyed; it reappears as they separate', 'Perfect cancellation requires equal amplitudes']),
          ('Explain why energy is not lost in destructive interference.', ['At point of cancellation, displacement=0 but velocity is maximum', 'KE is maximum where displacement=0', 'Energy stored in motion (kinetic), not in displacement', 'Total energy conserved; redistributed in space']),
          ('A wave on a light string reaches the junction with a heavier string. Describe reflected and transmitted waves.', ['Heavier string = harder boundary for the wave', 'Reflected wave: inverted (partial inversion)', 'Transmitted wave: continues, slower, shorter wavelength (same f)', 'Both reflection and transmission occur'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Superposition and Interference', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Describe what happens at fixed vs. free boundaries', 'Sketch the result of two upright equal pulses overlapping', 'Explain why energy is conserved during destructive interference']),

      _l('Standing Waves and Resonance',
         [_t('Standing Waves on Strings', 'Standing waves form when a wave and its reflection interfere to create nodes (zero displacement) and antinodes (max displacement). For string fixed at both ends: λₙ=2L/n; fₙ=nv/(2L); n=1,2,3,...', 'Students memorize the formula without understanding it comes from the condition that L must fit a whole number of half-wavelengths (nodes at both ends).', 'Calculate resonant frequencies for standing waves on strings using fₙ=nv/(2L).'),
          _t('Open and Closed Pipes', 'Open pipe (both ends open): fₙ=nv/(2L), all harmonics. Closed pipe (one closed end): fₙ=nv/(4L) for odd n only (1st, 3rd, 5th harmonics).', 'Students use the string formula for all wave resonance situations; closed pipes have different boundary conditions and produce only odd harmonics.', 'Calculate resonant frequencies for open and closed pipes; state which harmonics are present.'),
          _t('Beats', 'When two waves of slightly different frequencies f₁ and f₂ interfere, the perceived beat frequency is f_beat=|f₁−f₂|. The sound alternately gets louder and softer at f_beat.', 'Students think beat frequency is the average of f₁ and f₂; it is the difference.', 'Calculate beat frequency from two given frequencies; explain what is heard.')],
         [('node', 'Point of zero displacement in a standing wave'),
          ('antinode', 'Point of maximum displacement in a standing wave'),
          ('fundamental frequency', 'f₁=v/(2L) for string or open pipe; f₁=v/(4L) for closed pipe'),
          ('beat frequency', 'f_beat=|f₁−f₂|; rate of amplitude variation')],
         ['Calculate resonant frequencies for strings and pipes', 'Distinguish open vs. closed pipe harmonics', 'Calculate beat frequency'],
         ['Standing wave problems appear every year in AP® Physics 1', 'Open vs. closed pipe tested in MC', 'Beat frequency in MC'],
         ['Find first three harmonics for a 0.8 m string if v=200 m/s', 'Two tuning forks at 442 Hz and 446 Hz; find beat frequency'],
         [('A 1 m guitar string has wave speed 200 m/s. Find the first three resonant frequencies.', ['fₙ=nv/(2L)=n(200)/(2)=100n Hz', 'f₁=100 Hz, f₂=200 Hz, f₃=300 Hz', 'These are the first three harmonics', 'Fundamental wavelength: λ₁=2L=2 m']),
          ('A 0.5 m closed pipe has sound speed 340 m/s. Find the fundamental and second resonant frequency.', ['Closed pipe: fₙ=nv/(4L) for odd n', 'f₁=340/(4×0.5)=170 Hz', 'Second resonance: n=3; f₃=3(170)=510 Hz', 'No even harmonics in closed pipe']),
          ('Two guitars are tuned: one at 440 Hz, one at 437 Hz. What do you hear?', ['f_beat=|440−437|=3 Hz', 'The sound pulses louder 3 times per second', 'Used by musicians to tune instruments', 'Eliminate beats → instruments are in tune']),
          ('Draw the standing wave pattern for the 3rd harmonic on a string fixed at both ends.', ['Three half-wavelengths fit in the string length', 'Nodes at: both ends and at L/3 and 2L/3', 'Four antinodes in total... actually three loops', 'Actually: n=3 → 3 half-wavelengths → 4 nodes, 3 antinodes']),
          ('Why does a closed pipe produce only odd harmonics?', ['Closed end is a node; open end is an antinode', 'Pattern must have node at one end, antinode at other', 'Only odd numbers of quarter-wavelengths fit: L=λ/4, 3λ/4, 5λ/4', 'Even harmonics would require antinode at closed end — impossible'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Standing Waves', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the formula for resonant frequencies of a string fixed at both ends', 'Explain the difference between open and closed pipe harmonics', 'Two sources at 500 Hz and 503 Hz; describe what is heard']),

      _l('Doppler Effect and Wave Intensity',
         [_t('Doppler Effect', 'When source and observer move relative to each other, the observed frequency differs from emitted. Source approaches: higher f. Source recedes: lower f. Formula: f_obs = f_s(v ± v_obs)/(v ∓ v_s).', 'Students think the speed of sound changes with source motion; the speed of sound is determined by the medium, not the source — only the frequency perceived changes.', 'Apply qualitative Doppler effect reasoning; state whether observed frequency is higher or lower.'),
          _t('Wave Intensity and Inverse Square Law', 'Intensity I = P/(4πr²) for a point source radiating spherically. As distance doubles, intensity decreases by factor of 4. Intensity ∝ 1/r².', 'Students think intensity halves when distance doubles; it quarters because area increases as r².', 'Apply inverse square law to compare intensities at different distances.'),
          _t('Shock Waves', 'When a source moves faster than the wave speed, a shock wave (Mach cone) forms. The Mach number M = v_source/v_wave. For M>1, the source outruns its own waves.', 'Students think shock waves are only relevant for supersonic aircraft; any wave source exceeding wave speed produces a shock wave.', 'Explain the conditions for shock wave formation and the meaning of the Mach number.')],
         [('Doppler effect', 'Observed frequency change due to relative motion of source and observer'),
          ('intensity', 'I = P/(4πr²); power per unit area, W/m²'),
          ('inverse square law', 'I ∝ 1/r²; intensity decreases with distance squared'),
          ('shock wave', 'Wave front formed when source exceeds wave speed; M>1')],
         ['Predict direction of Doppler frequency shift qualitatively', 'Apply inverse square law to find intensity at different distances', 'Explain shock wave formation'],
         ['Doppler qualitative reasoning in MC', 'Inverse square law ratio problems in MC', 'Shock wave conceptual explanation in FR'],
         ['An ambulance approaches; does pitch of siren increase or decrease?', 'Source has intensity 100 W/m² at 2 m; find intensity at 6 m'],
         [('An ambulance siren emits 800 Hz. As it approaches you, what frequency do you hear? As it recedes?', ['Approaching: wavefronts compress → higher f (e.g., >800 Hz)', 'Receding: wavefronts stretch → lower f (e.g., <800 Hz)', 'Sound speed unchanged; apparent frequency changes', 'Classic Doppler effect']),
          ('A source has intensity 400 W/m² at 3 m. What is intensity at 9 m?', ['I ∝ 1/r²; I₂/I₁=(r₁/r₂)²=(3/9)²=1/9', 'I₂=400/9≈44.4 W/m²', 'Tripling distance reduces intensity by factor of 9', 'Inverse square law']),
          ('What conditions produce a shock wave?', ['Source must move faster than the wave speed in that medium', 'Mach number M = v_source/v_wave > 1', 'Wavefronts pile up at a cone angle behind the source', 'Creates a pressure boom (sonic boom for sound)']  ),
          ('An observer moves toward a stationary sound source. Is the observed frequency higher or lower?', ['Observer approaching: encounters wavefronts more frequently', 'Observed frequency is higher than emitted', 'Same qualitative result as source approaching observer', 'Quantitative formula accounts for which one is moving']),
          ('A point source emits 100 W uniformly. Find intensity at 5 m.', ['I=P/(4πr²)=100/(4π·25)=100/(100π)=1/π≈0.32 W/m²', 'Spherical surface area = 4πr²', 'Intensity = 0.32 W/m²', 'Decreases with square of distance'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Doppler Effect', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the qualitative Doppler effect for approaching and receding sources', 'Apply inverse square law: source at 10 m has I=16 W/m²; find I at 40 m', 'Define Mach number']),
  ],
  'unit_qs': [
      ('A wave has v=300 m/s and λ=0.75 m. Find frequency and period.', ['f=v/λ=300/0.75=400 Hz', 'T=1/f=1/400=0.0025 s', 'f=400 Hz, T=2.5 ms', 'v=fλ rearranged']),
      ('A string fixed at both ends is 0.6 m long with wave speed 120 m/s. Find 2nd harmonic frequency.', ['f₂=2v/(2L)=v/L=120/0.6=200 Hz', 'Or: f_n=nv/(2L); f₂=2(120)/(1.2)=200 Hz', '2nd harmonic = 200 Hz', 'First harmonic: 100 Hz']),
      ('Two pulses of equal amplitude meet: one positive, one negative. Describe the displacement at overlap.', ['Superposition: positive + negative = zero displacement', 'Complete destructive interference at that instant', 'Energy not lost; in kinetic form', 'Pulses continue after passing through each other']),
      ('A siren at 1000 Hz moves away from you at speed much less than v_sound. Is f_obs higher or lower?', ['Source moving away: wavefronts spread out', 'Observed frequency is lower than 1000 Hz', 'Doppler effect: recession → lower frequency', 'Classic red-shift analogy']),
      ('Wave energy increases from 10 J to 40 J. By what factor did amplitude change?', ['E ∝ A²; E₂/E₁=4', 'A₂²/A₁²=4 → A₂/A₁=2', 'Amplitude doubled', 'E quadruples when A doubles']),
      ('An open pipe is 0.85 m long with v_sound=340 m/s. Find the 3rd harmonic.', ['Open pipe: f_n=nv/(2L)', 'f₃=3(340)/(2×0.85)=1020/1.7=600 Hz', '3rd harmonic=600 Hz', 'All harmonics present for open pipe']),
      ('A closed pipe has fundamental 85 Hz. What is its next resonant frequency?', ['Closed pipe: odd harmonics only', 'n=1: 85 Hz; n=3: 3×85=255 Hz', 'Next resonant = 255 Hz', 'Skips n=2 (even harmonics absent)']),
      ('Intensity at 4 m from a source is 36 W/m². Find intensity at 12 m.', ['I₂/I₁=(r₁/r₂)²=(4/12)²=1/9', 'I₂=36/9=4 W/m²', 'Tripling distance → 1/9 intensity', 'I=4 W/m²']),
      ('Two tuning forks produce 3 beats per second. One is at 512 Hz. What are the possible frequencies of the other?', ['f_beat=|f₁−f₂|=3', 'f₂=512+3=515 Hz or f₂=512−3=509 Hz', 'Either value gives 3 beats/s', 'Need more info to determine which']),
      ('A wave hits a fixed boundary. Is the reflected wave in phase or out of phase?', ['Fixed boundary → inverted reflection', 'Reflected wave is 180° out of phase (inverted)', 'Crest reflects as trough', 'Free boundary: reflects in phase']),
  ],
},

{
  'num': 7, 'title': 'Electric Charge and Electric Force',
  'file': 'ap-physics-1-2-7-physics-1-unit-7-torque-and-rotational-motion.html',
  'desc': 'Analyze electric charge, Coulomb\'s law, and electric fields for point charges and charged objects.',
  'gateway': [
      'Explain charge conservation and charge transfer by conduction and induction.',
      'Apply Coulomb\'s law to find electric force between point charges.',
      'Define electric field and relate it to force on test charges.',
      'Analyze the motion of charged particles in electric fields.',
  ],
  'lessons': [
      _l('Electric Charge and Coulomb\'s Law',
         [_t('Electric Charge', 'Charge is quantized in units of e=1.6×10⁻¹⁹ C. Protons have +e, electrons −e. Like charges repel, unlike attract. Charge is conserved: net charge of a closed system is constant.', 'Students think charge can be created or destroyed; it can only be transferred. Rubbing objects transfers electrons, not protons.', 'Apply charge conservation to determine final charge distribution after charge transfer.'),
          _t('Coulomb\'s Law', 'F = kq₁q₂/r² where k=9×10⁹ N·m²/C². Force is attractive for unlike charges, repulsive for like charges. Force follows inverse-square law.', 'Students forget to square r; F ∝ 1/r² means doubling distance reduces force by factor of 4, not 2.', 'Calculate Coulomb force magnitude; determine direction using sign of charges.'),
          _t('Superposition of Electric Forces', 'The total electric force on a charge is the vector sum of forces from all other charges. Must find both magnitude and direction of each force, then add as vectors.', 'Students add forces as scalars; Coulomb forces are vectors — direction depends on the sign of the charges and their positions.', 'Find net force on a charge from multiple point charges using vector addition.')],
         [('elementary charge', 'e = 1.6×10⁻¹⁹ C; smallest unit of charge'),
          ('Coulomb\'s law', 'F = kq₁q₂/r²; k=9×10⁹ N·m²/C²'),
          ('charge conservation', 'Net charge in a closed system is constant'),
          ('inverse square law', 'Force decreases as 1/r²; doubles distance → 1/4 force')],
         ['Apply charge conservation to charge transfer scenarios', 'Calculate Coulomb force and its direction', 'Find net electric force from multiple charges using superposition'],
         ['Coulomb\'s law ratio problems in MC (halving distance → 4× force)', 'Charge direction and sign interpretation in FR', 'Superposition of forces in FR'],
         ['Find force between +3 μC and −2 μC charges 0.3 m apart', 'Three charges in a line; find net force on middle charge'],
         [('Find the force between q₁=+4 μC and q₂=−2 μC separated by 0.2 m.', ['F=kq₁q₂/r²=9×10⁹(4×10⁻⁶)(2×10⁻⁶)/(0.04)', 'F=9×10⁹(8×10⁻¹²)/0.04=72×10⁻³/0.04=1.8 N', 'Attractive force (opposite signs)', 'F=1.8 N toward each other']),
          ('Two charges were 0.3 m apart with force F. They are moved to 0.9 m. New force?', ['F ∝ 1/r²; r tripled → F decreases by 3²=9', 'F_new=F/9', 'Inverse square law', 'Must SQUARE the distance ratio']),
          ('Three equal +q charges are at corners of equilateral triangle. Find net force on one charge.', ['Each adjacent charge repels with equal force', 'Forces at 60° to each other', 'By symmetry, net force points away from centroid', 'Magnitude = F·√3 by vector addition']),
          ('A glass rod rubbed with silk becomes positive. Explain.', ['Rubbing transfers electrons from glass to silk', 'Glass loses electrons → becomes positive', 'Silk gains electrons → becomes negative', 'Charge is conserved: total charge unchanged']),
          ('Two identical metal spheres touch: one has +6 μC, other −2 μC. Find charge on each after separation.', ['Charge is shared: total=+6+(−2)=+4 μC', 'Divided equally: each gets +2 μC', 'Charge distributes equally on identical conductors', 'Each sphere: +2 μC'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Coulomb\'s Law', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Write Coulomb\'s law and identify each symbol', 'If distance is halved, by what factor does force change?', 'Explain charge transfer by friction using electron movement']),

      _l('Electric Field',
         [_t('Electric Field Definition', 'E = F/q (force per unit test charge). Unit: N/C. Electric field exists in space surrounding a charge; a positive test charge placed in the field would experience force in the field direction.', 'Students think the electric field only exists when a test charge is present; the field exists in space regardless of whether a test charge is there.', 'Calculate E from a point charge using E=kQ/r²; determine direction.'),
          _t('Electric Field Lines', 'Field lines start on + charges and end on − charges. Line density represents field strength. Lines never cross. Between parallel plates: uniform field, parallel lines (fringe fields neglected).', 'Students draw field lines that cross; field lines NEVER cross because the field has a unique direction at each point.', 'Sketch field lines for single charges, dipoles, and parallel plate configurations.'),
          _t('Superposition of Electric Fields', 'The net electric field is the vector sum of fields from all source charges: E_net = Σ(kQᵢ/rᵢ²)r̂ᵢ. Same principle as force superposition.', 'Students add field magnitudes without considering direction; fields are vectors and must be added as vectors.', 'Find the net electric field at a point due to multiple charges using vector addition.')],
         [('electric field', 'E = F/q; force per unit positive test charge, N/C'),
          ('field from point charge', 'E = kQ/r²; direction: away from + charge, toward − charge'),
          ('field lines', 'Start on + charges, end on − charges; never cross; density ∝ field strength'),
          ('uniform electric field', 'Constant E between parallel plates of a capacitor')],
         ['Calculate electric field at a point from a point charge', 'Sketch electric field lines for various charge configurations', 'Find net electric field from multiple charges using superposition'],
         ['E field direction from charge sign tested in MC', 'Field line sketches in FR', 'Superposition of E fields in FR and MC'],
         ['Find E at 0.3 m from a +5 μC charge', 'Sketch field lines for two equal positive charges'],
         [('Find the electric field at 0.3 m from a +5 μC charge.', ['E=kQ/r²=9×10⁹(5×10⁻⁶)/(0.09)', 'E=45×10³/0.09=5×10⁵ N/C', 'Direction: away from positive charge', 'E=500,000 N/C outward']),
          ('At point P midway between +q and −q separated by 2d, what is the electric field direction?', ['Field from +q at P: points away from +q → toward −q', 'Field from −q at P: points toward −q → same direction', 'Both fields point in the same direction (from + to −)', 'Net E is doubled compared to single charge']),
          ('Describe the electric field between two oppositely charged parallel plates.', ['Uniform field: constant magnitude and direction', 'E = V/d (for uniform field)', 'Field lines are parallel, equally spaced, perpendicular to plates', 'Field direction: from positive to negative plate']),
          ('How does a positive charge move in a uniform electric field?', ['Force F=qE in direction of field (for positive charge)', 'Accelerates in field direction', 'Analogous to mass in gravitational field', 'Negative charge accelerates opposite to E']),
          ('A charge q=−3×10⁻⁶ C is in a field E=2×10⁴ N/C. Find force and direction.', ['F=qE=−3×10⁻⁶×2×10⁴=−0.06 N', 'Magnitude: 0.06 N', 'Direction: opposite to E (negative charge)', 'Force = 0.06 N opposite field direction'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Electric Fields', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Define electric field in terms of force per test charge', 'Explain why field lines never cross', 'Find the force on a +2 μC charge in a field E=3×10⁴ N/C']),

      _l('Conductors and Insulators; Charging Methods',
         [_t('Conductors and Insulators', 'Conductors allow free electron movement (metals); insulators resist charge flow (rubber, glass). In a conductor, excess charge distributes on the outer surface; the interior has E=0 in electrostatic equilibrium.', 'Students think charge is distributed throughout a conductor; excess charge resides only on the outer surface in electrostatic equilibrium.', 'Explain why E=0 inside a conductor and why charge distributes on the surface.'),
          _t('Charging by Conduction and Induction', 'Conduction: direct contact transfers charge; object gains same sign as the charging object. Induction: no contact; charging object attracts opposite charges to near side; ground removes excess; same sign charges remain when ground is removed.', 'Students confuse conduction (contact) with induction (no contact); in induction, the induced charge is opposite to the inducing charge.', 'Describe the steps of charging by induction including grounding and what charge results.'),
          _t('Polarization', 'A charged object can attract a neutral conductor or insulator by polarizing it — shifting charge distributions without transferring net charge. This explains how a comb attracts paper bits.', 'Students think attraction requires transfer of charge; polarization creates attractive forces without any charge transfer.', 'Explain the attraction of a neutral object to a charged one using polarization.')],
         [('conductor', 'Material with free electrons that can move; charge on outer surface'),
          ('insulator', 'Material where charge cannot flow freely'),
          ('charging by conduction', 'Direct contact; object gains same sign as charger'),
          ('charging by induction', 'No contact; induced charge is opposite to inducing charge'),
          ('polarization', 'Charge redistribution in neutral object near charged object')],
         ['Explain charge distribution in conductors vs. insulators', 'Describe charging by conduction and induction with correct charge signs', 'Explain polarization and the attraction of neutral objects'],
         ['Charging method identification in MC', 'Induction steps described in FR', 'Conductor interior field=0 tested in FR and MC'],
         ['Describe steps to charge a neutral sphere by induction (negative rod available)', 'Why is E=0 inside a conductor at electrostatic equilibrium?'],
         [('Describe how to charge a neutral metal sphere negative by induction using a positively charged rod.', ['Bring +rod near sphere (do not touch)', 'Negative charges in sphere are attracted to near side; positive charges move to far side', 'Ground the sphere: negative charges from ground enter to neutralize far positive side', 'Remove ground; remove rod: sphere now has net negative charge']),
          ('Explain why a metal sphere has E=0 in its interior.', ['Free electrons redistribute until no net force on any electron', 'If E were nonzero inside, electrons would continue moving', 'At equilibrium, E=0 everywhere inside conductor', 'Excess charge arranges on outer surface']),
          ('A charged rod attracts a small piece of neutral aluminum foil. Explain.', ['Rod polarizes foil: near side gets opposite charge, far side gets same charge', 'Near-side force is attractive and stronger (closer)', 'Far-side force is repulsive but weaker (farther)', 'Net force is attractive even with no charge transfer']),
          ('A neutral conducting sphere is charged by conduction with a negative rod. What charge does the sphere get?', ['Direct contact: electrons transfer from rod to sphere', 'Sphere gets negative charge (same as rod)', 'Rod\'s charge decreases (shared)', 'Conduction → same sign as charger']),
          ('Why does excess charge on a conductor go to the outer surface?', ['Like charges repel; they move as far apart as possible', 'Outer surface maximizes distance between charges', 'In equilibrium, no charge inside → E=0 inside', 'Gauss\'s law confirms: enclosed charge = 0 inside'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Electric Charge', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Distinguish charging by conduction from induction', 'What charge sign results from induction with a negative rod?', 'Explain in one sentence why E=0 inside a conductor']),

      _l('Motion of Charges in Electric Fields',
         [_t('Acceleration of Charged Particles', 'A charged particle in a uniform electric field experiences F=qE and accelerates at a=F/m=qE/m. For a positive charge: acceleration in the direction of E. This is analogous to gravity for projectile motion.', 'Students forget to include the sign of the charge; negative charges accelerate opposite to E.', 'Calculate the acceleration of a charge in a uniform field; set up kinematic equations for its motion.'),
          _t('Horizontal Deflection (like CRT)', 'A charge entering a uniform vertical electric field horizontally is deflected like a projectile: constant horizontal velocity, constant vertical acceleration qE/m. The trajectory is parabolic.', 'Students apply circular motion equations to this; charge in uniform E-field moves in a parabola like projectile motion in gravity.', 'Analyze horizontal beam deflection by a vertical electric field using kinematic equations.'),
          _t('Electric Potential Energy', 'Work done by electric field on charge q moving through potential difference ΔV: W=qΔV. Energy gained = qΔV (for positive charge moving with field). Unit: Joule; eV = 1.6×10⁻¹⁹ J.', 'Students confuse electric potential (V, volts) with electric potential energy (PE=qV, joules); potential is per-unit-charge, potential energy depends on the specific charge.', 'Calculate work done by electric field on moving charges using W=qΔV.')],
         [('acceleration in E field', 'a = qE/m; direction: with E for positive, against E for negative charge'),
          ('parabolic trajectory', 'Charge in uniform E field moves in a parabola (like projectile in gravity)'),
          ('electric potential energy', 'PE = qV; work done by field = qΔV'),
          ('electron-volt', 'eV = 1.6×10⁻¹⁹ J; energy of one electron through 1 V potential difference')],
         ['Calculate acceleration of a charge in a uniform electric field', 'Analyze parabolic trajectory of charge entering perpendicular to E field', 'Calculate work done on a charge moving through a potential difference'],
         ['Charge acceleration in E field in FR', 'Parabolic path analysis in MC', 'Work done by E field using W=qΔV in MC and FR'],
         ['Find acceleration of electron (m=9.1×10⁻³¹ kg) in E=1000 N/C field', 'Find work done on +2 μC charge moved through 50 V potential difference'],
         [('Find the acceleration of a proton (m=1.67×10⁻²⁷ kg) in E=5000 N/C field.', ['F=qE=1.6×10⁻¹⁹(5000)=8×10⁻¹⁶ N', 'a=F/m=8×10⁻¹⁶/1.67×10⁻²⁷≈4.8×10¹¹ m/s²', 'Enormous acceleration due to tiny mass', 'Direction: in direction of E (positive charge)']),
          ('A proton enters a uniform field E horizontally and is deflected vertically. Describe the path.', ['Horizontal: constant velocity (no horizontal force)', 'Vertical: constant acceleration a=qE/m upward (if E points up)', 'Combined: parabolic trajectory', 'Identical analysis to projectile in gravity']),
          ('Find work done on a +3 μC charge moved from A to B through ΔV=−100 V.', ['W=qΔV=3×10⁻⁶(−100)=−3×10⁻⁴ J', 'Negative work: field opposes motion', 'Or: charge moves against the field direction', 'W=−0.0003 J']),
          ('An electron is accelerated through 1000 V. Find its kinetic energy in joules and eV.', ['KE=qΔV=1.6×10⁻¹⁹(1000)=1.6×10⁻¹⁶ J', 'In eV: 1000 eV (by definition of electron-volt)', '1 eV = energy gained by e through 1V', 'KE=1.6×10⁻¹⁶ J = 1000 eV']),
          ('In a CRT, how is the electron beam deflected to hit a specific point on the screen?', ['Vertical deflection plates create vertical E field', 'Electron deflected vertically by qE/m acceleration', 'Horizontal deflection by separate perpendicular field', 'Combination of parabolic deflections targets any screen point'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Charge Motion in Fields', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the formula for acceleration of a charge in an E field', 'Explain why a charge in a uniform field follows a parabolic path', 'Calculate KE gained by an electron accelerated through 500 V']),
  ],
  'unit_qs': [
      ('Find force between +6 μC at origin and −4 μC at x=0.3 m.', ['F=kq₁q₂/r²=9×10⁹(6×10⁻⁶)(4×10⁻⁶)/(0.09)', 'F=9×10⁹(24×10⁻¹²)/0.09=2400×10⁻³/0.09≈2.4 N', 'Attractive (opposite signs)', 'F≈2.4 N']),
      ('Two charges 1 m apart with force F. What force when 2 m apart? When 0.5 m apart?', ['F ∝ 1/r²', 'At 2 m: F_new=F/(2)²=F/4', 'At 0.5 m: F_new=F/(0.5)²=4F', 'Inverse square law: halving distance → 4× force']),
      ('Find E at 0.6 m from a −8 μC charge.', ['E=kQ/r²=9×10⁹(8×10⁻⁶)/0.36=2×10⁵ N/C', 'Direction: toward the negative charge', 'E=200,000 N/C pointing toward −8 μC charge', 'Magnitude same as for positive charge; direction reversed']),
      ('A +2 μC charge is placed in E=4×10⁵ N/C. Find force and direction.', ['F=qE=2×10⁻⁶(4×10⁵)=0.8 N', 'Direction: same as E (positive charge)', 'F=0.8 N in E-field direction', 'For −2 μC: force would be opposite to E']),
      ('Describe charging a metal sphere negative by induction using a positive rod.', ['Bring +rod near sphere: negative charges attracted to near side', 'Ground sphere: electrons from ground enter far side', 'Remove ground: sphere now net negative', 'Remove rod: charge distributes on surface of sphere']),
      ('Two equal charges +q are placed 0.4 m apart. Find E at the midpoint between them.', ['Field from left +q: points right (away from +)', 'Field from right +q: points left (away from +)', 'Equal magnitude, opposite direction', 'Net E at midpoint = 0']),
      ('Find work done on an electron (q=−e) accelerated through ΔV=+200 V.', ['W=qΔV=(−1.6×10⁻¹⁹)(200)=−3.2×10⁻¹⁷ J... ', 'Wait: electron moves opposite to E field (from − to + plate)', 'Actually W=|q|ΔV=1.6×10⁻¹⁹(200)=3.2×10⁻¹⁷ J (gained KE)', 'KE gained = 3.2×10⁻¹⁷ J = 200 eV']),
      ('A +5 μC and +5 μC charge are 0.5 m apart. Find E at a point 0.5 m to the right of the right charge.', ['Right charge field at that point: E=kq/r²=9×10⁹(5×10⁻⁶)/0.25=180,000 N/C pointing right', 'Left charge: distance=1 m; E=9×10⁹(5×10⁻⁶)/1=45,000 N/C pointing right', 'Both point away from respective positive charges (same direction)', 'Net E=225,000 N/C pointing right']),
      ('Explain why a neutral cork is attracted to a charged plastic rod.', ['Rod polarizes cork: near side gets opposite charge, far side same', 'Attraction from near side > repulsion from far side (closer=stronger)', 'Net attractive force without charge transfer', 'Polarization explains attraction of neutral objects']),
      ('An electron enters perpendicular to a uniform E field of 3000 N/C. Find its vertical acceleration.', ['F=eE=1.6×10⁻¹⁹(3000)=4.8×10⁻¹⁶ N', 'a=F/m=4.8×10⁻¹⁶/9.11×10⁻³¹≈5.27×10¹⁴ m/s²', 'Parabolic trajectory (like projectile)', 'a≈5.3×10¹⁴ m/s²']),
  ],
},

{
  'num': 8, 'title': 'DC Circuits',
  'file': 'ap-physics-1-2-8-physics-2-unit-1-fluids-thermodynamics-foundations-as-applicable.html',
  'desc': 'Analyze resistive circuits using Ohm\'s law, Kirchhoff\'s rules, and energy/power relationships.',
  'gateway': [
      'Apply Ohm\'s law (V=IR) to find voltage, current, and resistance.',
      'Analyze series and parallel resistor combinations.',
      'Apply Kirchhoff\'s current and voltage laws to circuit analysis.',
      'Calculate power dissipated and energy stored in circuit elements.',
  ],
  'lessons': [
      _l('Ohm\'s Law and Resistance',
         [_t('Ohm\'s Law', 'V = IR. Voltage (V) drives current (I) through resistance (R). Unit: V=Volts, I=Amperes, R=Ohms (Ω). Ohm\'s law applies to ohmic resistors where R is constant.', 'Students rearrange V=IR incorrectly; always identify which two are known and solve for the third. R is not a variable in ohmic resistors.', 'Apply V=IR to find voltage, current, or resistance in simple circuits.'),
          _t('Resistance and Resistivity', 'R=ρL/A where ρ is resistivity, L is length, A is cross-sectional area. Longer wire → more R; thicker wire → less R. Resistivity depends on material and temperature.', 'Students think resistance equals resistivity; R depends on both material (ρ) and geometry (L and A).', 'Predict how resistance changes when length or cross-section changes.'),
          _t('Current and Charge Flow', 'Current I = ΔQ/Δt (charge per time, Amperes). Conventional current flows from + to − (opposite to electron flow). In a DC circuit, current is the same throughout a series circuit.', 'Students think current is used up in a resistor; current is conserved (Kirchhoff\'s current law), but energy (voltage) is used up.', 'Distinguish current from voltage; explain why current is the same throughout a series circuit.')],
         [('Ohm\'s law', 'V = IR; voltage = current × resistance'),
          ('resistance', 'R = ρL/A; opposition to current flow, Ohms'),
          ('current', 'I = ΔQ/Δt; rate of charge flow, Amperes'),
          ('conventional current', 'Flows from + to − terminal; opposite to electron flow')],
         ['Apply V=IR to simple circuits', 'Predict resistance changes from geometry', 'Explain the distinction between current and voltage in a circuit'],
         ['Ohm\'s law in every AP® Physics 1 exam', 'Resistance and resistivity ratios in MC', 'Series current conservation in FR'],
         ['Find current through 20 Ω resistor with 12 V battery', 'If wire length doubles and diameter doubles, how does R change?'],
         [('A 12 V battery is connected to a 30 Ω resistor. Find current.', ['I=V/R=12/30=0.4 A', 'Voltage drives current through resistance', 'I=0.4 A', 'Larger R → less current for same voltage']),
          ('A wire has R=5 Ω. If its length doubles and cross-section doubles, find new R.', ['R=ρL/A; new R=ρ(2L)/(2A)=ρL/A=5 Ω', 'Length doubles (+R) but area doubles (−R)', 'Effects cancel: R unchanged', 'R=5 Ω']),
          ('Explain why current is the same at every point in a series circuit.', ['Charge is conserved: whatever charge enters a junction must exit', 'In a series circuit, there\'s only one path', 'Current cannot accumulate in resistors', 'Kirchhoff\'s current law: ΣI_in=ΣI_out']),
          ('If R is halved and V is doubled, by what factor does I change?', ['I=V/R; new I=(2V)/(R/2)=4V/R=4I', 'Current quadruples', 'Both changes increase current', 'I ∝ V/R']),
          ('A wire carries 2 A for 5 min. How much charge passes a cross-section?', ['Q=IΔt=2(300)=600 C', '1 Ampere = 1 Coulomb per second', 'Q=600 C', 'About 3.75×10²¹ electrons'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Ohm\'s Law', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State Ohm\'s law and units', 'If wire cross-section is halved, how does R change?', 'Explain why current doesn\'t "get used up" in a resistor']),

      _l('Series and Parallel Circuits',
         [_t('Series Resistors', 'In series: same current, voltages add. R_total=R₁+R₂+... Removing one component breaks the entire circuit.', 'Students add voltages instead of resistances, or think adding resistors in series decreases total resistance; series always increases R.', 'Calculate total resistance, current, and voltage drops in a series circuit.'),
          _t('Parallel Resistors', 'In parallel: same voltage, currents add. 1/R_total=1/R₁+1/R₂+... Adding resistors in parallel always decreases total resistance.', 'Students use 1/R_total formula incorrectly by taking 1/(1/R₁+1/R₂) = R_total; they often forget to take the reciprocal of the sum at the end.', 'Calculate equivalent resistance of parallel resistors; find individual branch currents.'),
          _t('Mixed (Series-Parallel) Circuits', 'Reduce complex circuits stepwise: combine parallel branches into single equivalent resistance, then combine series. Work from innermost grouping outward.', 'Students try to analyze the whole circuit at once; always reduce parallel groups first, then series combinations, iteratively.', 'Apply stepwise reduction to find total resistance and individual currents/voltages in mixed circuits.')],
         [('series circuit', 'Same current; voltages add; R_total = ΣRᵢ'),
          ('parallel circuit', 'Same voltage; currents add; 1/R_total = Σ(1/Rᵢ)'),
          ('voltage divider', 'In series, voltage divides proportionally to resistance: V₁/V₂=R₁/R₂'),
          ('current divider', 'In parallel, current divides inversely proportional to resistance')],
         ['Calculate series and parallel equivalent resistance', 'Find voltage and current for each resistor in series/parallel circuit', 'Reduce mixed circuits stepwise to find total resistance'],
         ['Series/parallel circuits guaranteed in AP® FR', 'Stepwise reduction in FR; show all work', 'Voltage divider and current divider tested in MC'],
         ['Three 6 Ω resistors: find total R in series and in parallel', 'A 4 Ω and 12 Ω in parallel; series with 6 Ω; find total R'],
         [('Three 12 Ω resistors in series with a 24 V battery. Find I and voltage across each.', ['R_total=3×12=36 Ω', 'I=V/R=24/36=2/3 A', 'V each=IR=2/3×12=8 V', 'Verify: 3×8=24 V ✓']),
          ('Three 12 Ω resistors in parallel with 24 V. Find total current and current through each.', ['R_total: 1/R=3/12=1/4 → R=4 Ω', 'I_total=24/4=6 A', 'I each=24/12=2 A', 'Verify: 3×2=6 A ✓']),
          ('A 6 Ω and 3 Ω are in parallel; combination is in series with 4 Ω. Battery=18 V. Find total current.', ['R_parallel: 1/R=1/6+1/3=1/6+2/6=3/6=1/2 → R_p=2 Ω', 'R_total=2+4=6 Ω', 'I_total=18/6=3 A', 'V across parallel combination: 3×2=6 V']),
          ('In the above circuit, find current through 6 Ω and 3 Ω resistors.', ['Voltage across parallel=6 V', 'I_6Ω=6/6=1 A; I_3Ω=6/3=2 A', 'Verify: 1+2=3 A (total current) ✓', 'More current through smaller resistance']),
          ('Why does adding resistors in parallel decrease total resistance?', ['More parallel paths → more routes for current to flow', 'Total current = sum of branch currents', 'Same voltage drives more total current', 'More current for same V means less total R (R=V/I_total)'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Series and Parallel Circuits', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Write the total resistance formula for series and parallel', 'Find total R for 4 Ω and 6 Ω in parallel', 'Explain why adding a parallel branch always reduces total resistance']),

      _l('Kirchhoff\'s Laws and Power',
         [_t('Kirchhoff\'s Current Law (KCL)', 'At any junction, the sum of currents entering equals the sum of currents leaving: ΣI_in = ΣI_out. This follows from charge conservation.', 'Students think current is "split evenly" at a junction; current divides inversely proportional to resistance in parallel branches.', 'Apply KCL at junctions to write current equations for complex circuits.'),
          _t('Kirchhoff\'s Voltage Law (KVL)', 'Around any closed loop, the sum of voltage changes is zero: ΣΔV = 0. Gains across batteries; drops across resistors (voltage drops in direction of current).', 'Students don\'t account for sign conventions; voltage rises across battery (EMF), drops across resistors.', 'Apply KVL to closed loops; identify voltage rises (batteries) and drops (resistors) with correct signs.'),
          _t('Electric Power', 'P = IV = I²R = V²/R. Power is dissipated as heat in resistors. A circuit element with more resistance dissipates more power in series (same I); less power in parallel (same V).', 'Students apply P=IV in series using the full battery voltage instead of the voltage across that resistor; use P=I²R (same I in series) or P=V²/R (same V in parallel).', 'Calculate power dissipated in each resistor and the total power delivered by the battery.')],
         [('KCL', 'ΣI_in = ΣI_out at any junction'),
          ('KVL', 'ΣΔV = 0 around any closed loop'),
          ('power', 'P = IV = I²R = V²/R; Watts'),
          ('power in series', 'P=I²R; larger R dissipates more power in series')],
         ['Apply KCL to write junction equations', 'Apply KVL to write loop equations', 'Calculate power for each element in a circuit'],
         ['KCL and KVL appear in FR circuit analysis', 'Power calculations in both MC and FR', 'Which resistor dissipates most power: series vs. parallel context'],
         ['Write KCL and KVL equations for a two-loop circuit', 'Find power in each resistor: 4 Ω and 8 Ω in series with 12 V'],
         [('At a junction, 3 A enters from the left and 1 A exits upward. Find the current exiting to the right.', ['KCL: ΣI_in = ΣI_out', '3 = 1 + I_right', 'I_right = 2 A', 'Charge conservation at junction']),
          ('A loop contains: 12 V battery, 4 Ω, 2 Ω resistors. Write KVL and find I.', ['KVL: 12 − I(4) − I(2) = 0', '12 = 6I → I = 2 A', 'Battery gain = sum of resistor drops', 'I=2 A']),
          ('Find power in each resistor: 6 Ω and 3 Ω in series with 18 V battery.', ['I=18/9=2 A', 'P_6Ω=I²R=4(6)=24 W; P_3Ω=4(3)=12 W', 'Total P=36 W=IV=2(18)=36 W ✓', 'Higher R → more power in series']),
          ('Find power in each: 6 Ω and 3 Ω in parallel with 18 V.', ['V=18 V across each', 'P_6Ω=V²/R=324/6=54 W; P_3Ω=324/3=108 W', 'Total P=162 W; check: I=6+3=9 A, P=18×9=162 W ✓', 'Lower R → more power in parallel']),
          ('Why does a 100 W light bulb have lower resistance than a 60 W bulb (same voltage)?', ['P=V²/R; for same V, P ∝ 1/R', 'Higher power → lower resistance', '100 W: R=V²/P (smaller)', '60 W: R=V²/P (larger)', 'More current flows through lower R bulb'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Kirchhoff\'s Laws', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State Kirchhoff\'s current law and voltage law', 'Find power in a 5 Ω resistor carrying 3 A', 'Explain why larger R dissipates more power in a series circuit']),

      _l('Capacitors (Introductory)',
         [_t('Capacitance', 'C = Q/V (charge stored per volt). Unit: Farad (F). A capacitor stores charge on two conducting plates separated by an insulator. Energy stored: U = ½CV² = ½QV = Q²/(2C).', 'Students think capacitors work like batteries; capacitors store charge (not chemical energy) and discharge quickly.', 'Calculate charge stored and energy stored in a capacitor given C and V.'),
          _t('Capacitors in Circuits', 'In a DC steady state, no current flows through a capacitor (acts as open circuit). Voltage across a capacitor equals the voltage between the nodes it connects.', 'Students think current flows through capacitors in DC steady state; in DC steady state, capacitor is fully charged and current stops.', 'Analyze a simple RC circuit in steady state; find voltage across capacitor.'),
          _t('Charging and Discharging', 'Capacitor charges exponentially through a resistor: Q(t)=Q_max(1−e^{−t/RC}). Time constant τ=RC. After 5τ, the capacitor is considered fully charged.', 'Students think charging is instantaneous; charging follows exponential growth; time constant τ=RC determines the charging rate.', 'Identify the time constant τ=RC and describe the shape of the charging curve.')],
         [('capacitance', 'C = Q/V; Farads'),
          ('energy stored', 'U = ½CV²'),
          ('time constant', 'τ = RC; time to reach ~63% of final charge'),
          ('steady state', 'No current through capacitor; fully charged in DC circuit')],
         ['Calculate charge and energy stored in a capacitor', 'Analyze capacitor voltage in DC steady-state circuits', 'Describe charging curve and time constant'],
         ['Capacitor energy in MC', 'Steady-state capacitor voltage in FR', 'Charging curve description in FR'],
         ['Find charge and energy stored: C=100 μF, V=12 V', 'RC circuit with R=1000 Ω, C=100 μF; find time constant'],
         [('A 50 μF capacitor is charged to 20 V. Find Q and stored energy.', ['Q=CV=50×10⁻⁶(20)=1×10⁻³ C=1 mC', 'U=½CV²=½(50×10⁻⁶)(400)=0.01 J=10 mJ', 'Q=1 mC, U=10 mJ', 'Energy in electric field between plates']),
          ('In a series RC circuit in DC steady state, where does the voltage appear?', ['Capacitor fully charged: no current flows', 'Voltage across resistor = IR = 0 (no current)', 'All battery voltage appears across capacitor', 'V_capacitor = V_battery']),
          ('An RC circuit has R=2000 Ω and C=500 μF. Find τ and describe charging.', ['τ=RC=2000(500×10⁻⁶)=1 s', 'After 1τ: 63% of final charge', 'After 5τ=5 s: essentially fully charged', 'Exponential approach to full charge']),
          ('How does doubling the voltage affect charge and energy stored?', ['Q=CV: doubling V doubles Q', 'U=½CV²: quadruples (proportional to V²)', 'Same as amplitude-energy relationship in waves', 'Charge doubles, energy quadruples']),
          ('Why is a capacitor useful in a circuit that needs rapid bursts of energy?', ['Battery delivers energy slowly (limited by internal resistance)', 'Capacitor discharges quickly through low resistance', 'Provides large instantaneous current when needed', 'Camera flash, defibrillator are examples'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Capacitors', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the formula for capacitance and energy stored', 'In a DC steady state circuit, what current flows through a capacitor?', 'Find the time constant for R=500 Ω, C=200 μF']),
  ],
  'unit_qs': [
      ('A 9 V battery drives current through a 45 Ω resistor. Find I and power dissipated.', ['I=V/R=9/45=0.2 A', 'P=IV=0.2(9)=1.8 W or P=I²R=0.04(45)=1.8 W', 'P=1.8 W', 'Consistent from both formulas']),
      ('Three resistors: 2 Ω, 3 Ω, 6 Ω in parallel. Find total resistance.', ['1/R=1/2+1/3+1/6=3/6+2/6+1/6=6/6=1', 'R_total=1 Ω', 'Parallel: 1/R_total=sum of reciprocals', 'R=1 Ω (less than smallest branch)']),
      ('A 24 V battery drives a series circuit: 4 Ω and 8 Ω resistors. Find power in each.', ['I=24/(4+8)=24/12=2 A', 'P_4Ω=I²R=4(4)=16 W; P_8Ω=4(8)=32 W', 'Total=48 W=IV=2(24)=48 W ✓', 'Larger R → more power in series']),
      ('Apply KVL to find I in a loop: 10 V battery, 5 Ω and 3 Ω resistors in series.', ['KVL: 10−5I−3I=0', '10=8I → I=1.25 A', 'Check: V_5Ω=6.25, V_3Ω=3.75; sum=10 ✓', 'I=1.25 A']),
      ('A junction has 4 A coming from the left and 5 A entering from below. Find current exiting right.', ['KCL: 4+5=I_right', 'I_right=9 A', 'All entering current must exit', 'I=9 A right']),
      ('A 200 μF capacitor is charged to 50 V. Find stored charge and energy.', ['Q=CV=200×10⁻⁶(50)=0.01 C=10 mC', 'U=½CV²=½(200×10⁻⁶)(2500)=0.25 J', 'Q=10 mC, U=0.25 J', 'Energy = 250 mJ']),
      ('Find current through 6 Ω branch: 6 Ω and 12 Ω in parallel with 18 V across combination.', ['V=18 V across each', 'I_6Ω=18/6=3 A; I_12Ω=18/12=1.5 A', 'Total I=4.5 A', 'More current through lower resistance']),
      ('If a wire\'s length is tripled and radius is halved, by what factor does resistance change?', ['R=ρL/A; A=πr²', 'New R=ρ(3L)/(π(r/2)²)=ρ(3L)/(πr²/4)=12ρL/A=12R', 'R increases by factor of 12', 'Length triples (+3); area quarters (×4): 3×4=12']),
      ('Two 6 Ω resistors in series total 12 Ω. In parallel? Which configuration allows more current for same V?', ['Parallel: 1/R=1/6+1/6=2/6 → R=3 Ω', 'Parallel has less R → more current', 'Series R=12 Ω vs. parallel R=3 Ω', 'Parallel allows 4× more current for same voltage']),
      ('Describe the energy transformation in a simple resistor circuit (battery + resistor).', ['Battery: chemical energy → electrical energy', 'Resistor: electrical energy → thermal energy (heat)', 'Energy conserved throughout', 'Power input by battery = power dissipated in resistor']),
      ('An RC circuit has τ=0.5 s. How long until capacitor is effectively fully charged?', ['Effectively fully charged after 5τ=5(0.5)=2.5 s', 'At 5τ, 99.3% of maximum charge', 'Charging follows exponential curve', '2.5 seconds'])
  ],
},

{
  'num': 9, 'title': 'Magnetism and Electromagnetic Induction',
  'file': 'ap-physics-1-2-9-physics-2-unit-2-electric-force-field-and-potential.html',
  'desc': 'Analyze magnetic forces on moving charges and current-carrying conductors, and describe electromagnetic induction.',
  'gateway': [
      'Apply the right-hand rule to find the direction of magnetic force on moving charges.',
      'Describe the magnetic field produced by straight wires and solenoids.',
      'Apply Faraday\'s law to describe electromagnetic induction qualitatively.',
      'Explain Lenz\'s law and the direction of induced current.',
  ],
  'lessons': [
      _l('Magnetic Force on Moving Charges',
         [_t('Magnetic Force', 'F = qv × B (vector cross product). Magnitude: F = qvBsinθ. Force is perpendicular to both v and B — it does no work (cannot change speed, only direction). Right-hand rule gives direction.', 'Students think magnetic force does work; since F ⊥ v, the magnetic force is always perpendicular to displacement and W=Fd·cosθ=0.', 'Apply F=qvBsinθ to find the magnitude of magnetic force; use RHR for direction.'),
          _t('Circular Motion in Magnetic Field', 'A charge moving perpendicular to B moves in a circle. Magnetic force provides centripetal force: qvB = mv²/r → r = mv/(qB). Cyclotron motion.', 'Students think the charge spirals inward due to energy loss; in an ideal field with no energy loss, the radius is constant and the motion is circular.', 'Calculate the radius of circular motion for a charge in a magnetic field using r=mv/(qB).'),
          _t('Right-Hand Rule for Magnetic Force', 'For F = qv × B: point fingers in v direction, curl toward B, thumb points in F direction (for positive charge). For negative charge, reverse the thumb direction.', 'Students reverse the RHR for negative charges; the RHR gives direction for positive charge — flip for negative charge.', 'Apply RHR to determine the direction of magnetic force in various configurations.')],
         [('magnetic force', 'F = qvBsinθ; perpendicular to both v and B'),
          ('right-hand rule', 'Fingers: v direction; curl toward B; thumb: F direction (positive charge)'),
          ('circular orbit', 'r = mv/(qB); magnetic force provides centripetal force'),
          ('zero work', 'Magnetic force ⊥ velocity → W=0; speed constant')],
         ['Calculate magnetic force magnitude and direction', 'Apply RHR to determine force direction on moving charge', 'Calculate radius of circular motion in a magnetic field'],
         ['RHR direction problems in MC', 'Circular orbit radius calculation in FR', 'Zero work explanation in FR'],
         ['Find force on proton moving at 3×10⁶ m/s perpendicular to B=0.2 T', 'Find radius of circular orbit for an electron at v=5×10⁶ m/s in B=0.5 T'],
         [('Find the magnetic force on a proton (q=1.6×10⁻¹⁹ C) moving at 2×10⁶ m/s ⊥ to B=0.3 T.', ['F=qvBsinθ=1.6×10⁻¹⁹(2×10⁶)(0.3)sin90°', 'F=1.6×10⁻¹⁹(6×10⁵)=9.6×10⁻¹⁴ N', 'Direction: use RHR (v × B)', 'F=9.6×10⁻¹⁴ N perpendicular to v and B']),
          ('An electron moves east in a field B pointing north. Find direction of force.', ['For positive charge: east × north = ? Use RHR: fingers east, curl toward north, thumb points up', 'For negative charge (electron): force reverses → downward', 'F is downward', 'Electron deflects downward']),
          ('A proton moves at v=4×10⁶ m/s ⊥ to B=0.2 T. Find orbital radius.', ['r=mv/(qB)=1.67×10⁻²⁷(4×10⁶)/(1.6×10⁻¹⁹×0.2)', 'r=6.68×10⁻²¹/(3.2×10⁻²⁰)=0.209 m', 'r≈0.21 m', 'Larger mass or speed → larger radius; larger B → smaller radius']),
          ('Does a magnetic force do work on a moving charge? Explain.', ['F is always perpendicular to v', 'W=F·d·cosθ; angle between F and displacement = 90°', 'cos90°=0 → W=0', 'Magnetic force changes direction but not speed or KE']),
          ('A positive charge moves in a circle in a magnetic field. The field points into the page. Describe the rotation.', ['Use RHR to trace the force at each point', 'At top: v is right, B into page → F=qv×B points downward (center)', 'Motion: clockwise circle when viewed from above', 'Centripetal force provided by magnetic force'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Magnetic Force', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the formula for magnetic force on a moving charge', 'Why does magnetic force do no work?', 'Find direction of force on positive charge moving north in B pointing east']),

      _l('Magnetic Field Sources',
         [_t('Magnetic Field from Straight Wire', 'A long straight wire carrying current I produces circular magnetic field lines around it. Direction: right-hand rule (curl fingers in direction of B if thumb points in current direction). B ∝ I/r.', 'Students think field lines are straight near a wire; they form concentric circles around the wire, decreasing with distance.', 'Use RHR to determine the direction of B around a current-carrying wire; state how B varies with distance.'),
          _t('Force Between Parallel Wires', 'Parallel currents in the same direction attract; in opposite directions they repel. Each wire is in the field of the other, and F=BIL applies.', 'Students reverse the attraction/repulsion rule; same-direction currents attract (unlike charges which repel for same sign).', 'Determine whether two parallel wires attract or repel based on current directions.'),
          _t('Solenoids and Magnetic Dipoles', 'A solenoid (coil of wire) produces a nearly uniform field inside. B inside ∝ nI where n=N/L. The field resembles a bar magnet with N and S poles. Right-hand rule for solenoid: curl fingers in current direction, thumb points to N pole.', 'Students think the field is only inside a solenoid; the field also exists outside, but is weaker and non-uniform. Only inside is it uniform.', 'Determine the magnetic poles of a solenoid using the right-hand rule for coils.')],
         [('B from wire', 'B = μ₀I/(2πr); decreases with distance from wire'),
          ('same-direction currents', 'Attract each other'),
          ('opposite-direction currents', 'Repel each other'),
          ('solenoid', 'Coil of wire producing uniform field inside; B ∝ nI')],
         ['Apply RHR to find B direction around a wire', 'Determine attraction/repulsion of parallel current-carrying wires', 'Identify poles of a solenoid using RHR'],
         ['Wire field direction in MC', 'Parallel wire force type (attract/repel) in MC', 'Solenoid pole identification in FR'],
         ['Find B direction around a vertical wire carrying current upward', 'Identify N and S poles of a solenoid with current direction shown'],
         [('A wire carries current upward. What is the direction of B to its right?', ['RHR: thumb up (current direction)', 'Fingers curl from front, wrap around to right side', 'At a point to the right: fingers point out of the page', 'B points out of the page to the right of upward current']),
          ('Two parallel wires carry current in the same direction. Do they attract or repel?', ['Each wire is in the other\'s magnetic field', 'F=ILB; direction from F=IL×B', 'Using RHR: forces on each wire point toward the other wire', 'Same-direction currents ATTRACT']),
          ('A solenoid has current flowing counterclockwise as viewed from the left end. Which end is the North pole?', ['RHR for coil: curl fingers in current direction (CCW from left = CCW from perspective of left end)', 'Thumb points to the left', 'Left end is the North pole', 'Field exits the North pole']),
          ('How does the field inside a solenoid compare to outside?', ['Inside: nearly uniform, parallel to axis', 'Outside: non-uniform, much weaker (fringe field)', 'B_inside ∝ nI (turns per length × current)', 'Increasing number of turns or current increases B_inside']),
          ('Why are solenoids used as electromagnets?', ['Strong, controllable, uniform field inside', 'Can be turned on/off by controlling current', 'Stronger than permanent magnets when high current used', 'Used in MRI machines, relays, speakers'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Magnetic Field from Wire', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State the RHR for current-carrying wire', 'State whether parallel wires with same-direction currents attract or repel', 'Identify poles of a solenoid with current flowing clockwise from right end']),

      _l('Electromagnetic Induction and Faraday\'s Law',
         [_t('Magnetic Flux and Faraday\'s Law', 'Magnetic flux Φ=BAcosθ (B through area A at angle θ). Faraday\'s law: induced EMF = −ΔΦ/Δt. A changing flux induces an EMF (and current in a closed circuit). Greater rate of change → greater EMF.', 'Students think a strong magnetic field induces EMF; it is the CHANGING flux that induces EMF, not the static field itself.', 'Calculate magnetic flux and determine whether EMF is induced based on whether flux is changing.'),
          _t('Lenz\'s Law', 'The induced current flows in a direction that opposes the change in flux that caused it. If flux is increasing, induced current creates field opposing the increase. If decreasing, induced current reinforces the original field.', 'Students confuse Lenz\'s law with "the induced current opposes the original current"; it opposes the CHANGE in flux, not the current causing the flux.', 'Apply Lenz\'s law to determine the direction of induced current in various scenarios.'),
          _t('Applications: Generators and Transformers', 'Generator: rotating coil in magnetic field → changing flux → alternating EMF. Transformer: changing flux in primary coil induces EMF in secondary coil (AC only). V_s/V_p = N_s/N_p.', 'Students think transformers work with DC; transformers require changing flux (AC) to operate.', 'Explain how generators and transformers use electromagnetic induction; apply transformer ratio.')],
         [('magnetic flux', 'Φ = BAcosθ; Webers (Wb)'),
          ('Faraday\'s law', 'EMF = −ΔΦ/Δt; changing flux induces EMF'),
          ('Lenz\'s law', 'Induced current opposes the change in flux'),
          ('transformer ratio', 'V_s/V_p = N_s/N_p; AC only')],
         ['Calculate magnetic flux and apply Faraday\'s law', 'Apply Lenz\'s law to determine induced current direction', 'Explain generator operation and apply transformer equation'],
         ['Faraday\'s law qualitative reasoning in FR', 'Lenz\'s law direction in both MC and FR', 'Transformer ratio calculation in MC'],
         ['A coil of 100 turns, area 0.01 m², B changes from 0 to 2 T in 0.5 s; find EMF', 'A magnet plunges into a solenoid; determine direction of induced current by Lenz\'s law'],
         [('A 50-turn coil (area 0.02 m²) has B increase from 0 to 4 T in 2 s. Find induced EMF.', ['ΔΦ per turn = ΔB·A = 4(0.02)=0.08 Wb', 'EMF=N·ΔΦ/Δt=50(0.08)/2=2 V', 'Magnitude of induced EMF = 2 V', 'Negative sign indicates opposing the change']),
          ('A bar magnet\'s north pole plunges into a solenoid. What is the direction of induced current?', ['Entering N pole: flux through solenoid increases', 'Lenz\'s law: induced current opposes the increase', 'Induced current creates its own N pole facing the entering magnet', 'Current flows to oppose the approaching N pole (repel it)']),
          ('A loop moves out of a region of uniform B. Describe what happens to flux and induced current.', ['Flux decreases as loop exits the field', 'Lenz\'s law: induced current tries to maintain the flux (oppose decrease)', 'Induced current creates field in same direction as original B', 'Current flows to create field in same direction as external B']),
          ('A transformer has 200 primary turns and 50 secondary turns. Input voltage = 120 V. Find output.', ['V_s/V_p = N_s/N_p', 'V_s = 120(50/200) = 120/4 = 30 V', 'Step-down transformer', 'Output = 30 V']),
          ('A generator converts mechanical energy to electrical energy. How?', ['Rotating coil in magnetic field', 'As coil rotates, flux through coil changes continuously', 'ΔΦ/Δt → continuous alternating EMF', 'Mechanical rotation → AC electrical output'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Bozeman Science — Electromagnetic Induction', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['State Faraday\'s law in words', 'Apply Lenz\'s law: magnet pulled away from solenoid; which direction is induced current?', 'Calculate transformer output voltage given turns ratio']),

      _l('Applications and Review',
         [_t('Hall Effect', 'When a current-carrying conductor is placed in a magnetic field perpendicular to the current, charges are deflected sideways, creating a transverse voltage (Hall voltage). Polarity depends on the sign of the charge carriers.', 'Students confuse the Hall voltage with the driving voltage of the circuit; the Hall voltage is perpendicular to both current and magnetic field.', 'Predict the direction of charge accumulation in the Hall effect and its relevance to determining charge carrier sign.'),
          _t('Mass Spectrometry', 'Ions are accelerated through a voltage, then enter a magnetic field where they travel in circular arcs. r=mv/(qB). Different masses → different radii → separation.', 'Students think all ions travel the same arc; radius depends on m/q ratio, so different isotopes take different paths.', 'Apply r=mv/(qB) to explain how a mass spectrometer separates isotopes.'),
          _t('Connections Across Units', 'Magnetic force, electric force, and gravity all follow inverse-square (or similar distance) laws. Energy and momentum are conserved in electromagnetic as well as mechanical interactions. Forces and fields are deeply connected.', 'Students treat each unit in isolation; AP® FR questions often combine topics (e.g., charge in a gravitational + electric field, or energy stored in capacitor + mechanical work).', 'Identify cross-unit connections and apply multiple laws in combination for integrated problems.')],
         [('Hall effect', 'Transverse voltage from magnetic deflection of charge carriers'),
          ('mass spectrometry', 'r=mv/(qB); separates ions by mass-to-charge ratio'),
          ('cross-unit connections', 'E, B, gravity, energy conservation combine in FR problems'),
          ('charge carrier sign', 'Hall effect polarity reveals whether carriers are + or −')],
         ['Explain Hall effect and its application', 'Apply r=mv/(qB) to mass spectrometry', 'Identify connections between mechanics and electromagnetism'],
         ['Cross-unit integration in AP® FR', 'Mass spectrometry calculation in MC', 'Hall effect conceptual explanation in FR'],
         ['Describe how Hall effect is used to determine semiconductor type (n vs. p)', 'Find radius of ¹²C⁺ ion in mass spectrometer given v and B'],
         [('An ion of charge q and mass m is accelerated through V and enters magnetic field B perpendicular to v. Find the radius of its circular orbit.', ['KE=qV: ½mv²=qV → v=√(2qV/m)', 'r=mv/(qB)=m·√(2qV/m)/(qB)', 'r=(1/(qB))·√(2mV/q)', 'r depends on √(m/q): heavier or less charged → larger radius']),
          ('Describe the Hall effect and its use in measuring current.', ['Current in conductor + perpendicular B → sideways force on charges', 'Charges accumulate on one side → transverse voltage (V_H)', 'V_H ∝ I and B; measuring V_H gives I when B known', 'Hall probes used as non-contact current sensors']),
          ('A proton and deuteron (2× mass, same charge) enter the same mass spectrometer. What is the ratio of their radii?', ['r=mv/(qB); same v and qB', 'r_d/r_p=m_d/m_p=2/1=2', 'Deuteron travels in circle with twice the radius', 'Heavier isotope → larger radius']),
          ('An electron moves in a circle of radius 0.05 m in B=0.01 T. Find its speed.', ['r=mv/(eB) → v=erB/m', 'v=(1.6×10⁻¹⁹)(0.05)(0.01)/(9.11×10⁻³¹)', 'v=8×10⁻²³/9.11×10⁻³¹≈8.8×10⁷ m/s', 'Relativistic effects significant but ignored here']),
          ('Explain how electromagnetic induction powers a bicycle generator (dynamo).', ['Wheel rotation spins a magnet near a coil', 'Rotating magnet causes changing flux through coil', 'Changing flux induces EMF → drives current to lights', 'Mechanical energy (rider) → electrical energy (lights)'])],
         [('https://www.youtube.com/watch?v=Hn7IIBHXN3U', 'Flipping Physics — Induction Applications', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
         ['Describe the Hall effect in one sentence', 'Explain how different masses are separated in a mass spectrometer', 'Connect electromagnetic induction to how generators work']),
  ],
  'unit_qs': [
      ('Find magnitude of force on an electron (q=1.6×10⁻¹⁹ C) moving at 10⁶ m/s ⊥ to B=0.4 T.', ['F=qvBsinθ=1.6×10⁻¹⁹(10⁶)(0.4)(1)', 'F=6.4×10⁻¹⁴ N', 'Perpendicular to both v and B', 'Does no work on electron']),
      ('A proton moves perpendicular to B=0.5 T in a circle of radius 0.04 m. Find its speed.', ['r=mv/(qB) → v=qBr/m=1.6×10⁻¹⁹(0.5)(0.04)/1.67×10⁻²⁷', 'v=3.2×10⁻²¹/1.67×10⁻²⁷≈1.92×10⁶ m/s', 'Speed≈1.92×10⁶ m/s', 'Cyclotron motion']),
      ('Two parallel wires carry currents in opposite directions. Do they attract or repel?', ['Opposite-direction currents REPEL', 'Each wire is in the other\'s magnetic field', 'F=ILB; direction: away from each other', 'Unlike same-direction currents which attract']),
      ('A 200-turn coil has area 0.05 m². B decreases from 1.5 T to 0.5 T in 0.1 s. Find induced EMF.', ['ΔΦ=ΔB·A=1 T×0.05 m²=0.05 Wb', 'EMF=N·ΔΦ/Δt=200(0.05)/0.1=100 V', 'Induced EMF=100 V', 'Lenz\'s law determines current direction']),
      ('A transformer has 400 primary and 100 secondary turns, input 240 V. Find output V and type.', ['V_s=240(100/400)=60 V', 'N_s < N_p → step-down transformer', 'Output = 60 V', 'Turns ratio = 1:4']),
      ('State what Lenz\'s law says will happen when a bar magnet is pulled away from a solenoid.', ['Flux through solenoid decreases as magnet is withdrawn', 'Lenz\'s law: induced current opposes the DECREASE', 'Induced current tries to maintain flux (attract magnet back)', 'Current flows to create B in same direction as original flux']),
      ('A wire carries current to the right. A positive charge is directly above the wire, moving right. What is the direction of magnetic force on the charge?', ['B from wire (current right): above wire B points out of page (RHR for wire)', 'Force on charge: F=qv×B; v is right, B is out of page', 'v×B = right × out-of-page = downward', 'Force on positive charge is downward (toward wire)']),
      ('Find the radius of a ¹²C⁺ ion (m=2×10⁻²⁶ kg, q=1.6×10⁻¹⁹ C) at v=5×10⁵ m/s in B=0.1 T.', ['r=mv/(qB)=2×10⁻²⁶(5×10⁵)/(1.6×10⁻¹⁹×0.1)', 'r=10⁻²⁰/1.6×10⁻²⁰=0.625 m', 'r=0.625 m', 'Larger mass → larger radius in mass spec']),
      ('A generator spins faster. How does this affect induced EMF?', ['Faster spin → faster change in flux (ΔΦ/Δt increases)', 'EMF=NΔΦ/Δt → larger EMF', 'Frequency of AC output also increases', 'More mechanical input → more electrical output']),
      ('Explain why a stationary charge in a magnetic field experiences no force.', ['F=qvBsinθ; if v=0, F=0', 'Magnetic force requires charge to be moving', 'Stationary charge: no current, no deflection', 'Electric field needed to exert force on stationary charge']),
  ],
},
]
