NAME        = 'AP® Physics 1 & 2'
ABBREV      = 'phys12'
SLUG        = 'ap-physics-1-2'
COURSE_FILE = 'ap-physics-1-2.html'
ACCENT_COLOR = '#34d399'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+1+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+1+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content,
            'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 10, 'title': 'Simple Harmonic Motion and Oscillations',
        'file': 'ap-physics-1-2-10-physics-2-unit-3-electric-circuits.html',
        'desc': 'Periodic motion, springs, pendulums, and the energy of oscillating systems.',
        'gateway': [
            'Define simple harmonic motion and state its restoring force condition.',
            'Apply Hooke\'s law and find period of spring and pendulum systems.',
            'Describe energy exchange between kinetic and potential in SHM.',
            'Analyze how amplitude, mass, and length affect period.',
        ],
        'lessons': [
            _l('Conditions for Simple Harmonic Motion',
               [_t('Restoring Force', 'SHM occurs when the net force on an object is proportional to displacement and directed toward equilibrium: F = -kx.', 'Larger amplitude does not change the period of SHM.', 'Free-response derivation of restoring force or period.'),
                _t('Hooke\'s Law', 'A spring exerts a restoring force F = -kx; the spring constant k (N/m) measures stiffness.', 'The minus sign means restoring, not that force is always negative.', 'Calculate spring force given k and displacement.'),
                _t('Equilibrium and Displacement', 'At equilibrium the net force is zero; displacement x is measured from that point, and SHM oscillates symmetrically about it.', 'Equilibrium is not the same as rest position—the object passes through it with maximum speed.', 'Identify equilibrium position on a force-displacement graph.')],
               [('Simple harmonic motion (SHM)', 'Oscillatory motion with restoring force proportional to displacement'),
                ('Restoring force', 'Net force directed toward equilibrium'),
                ('Spring constant k', 'Stiffness of a spring in N/m'),
                ('Amplitude A', 'Maximum displacement from equilibrium'),
                ('Equilibrium position', 'Position where net force is zero')],
               ['State the condition for SHM in terms of force and displacement.',
                'Apply Hooke\'s law F = -kx to find force or displacement.',
                'Identify equilibrium on force-displacement graphs.'],
               ['Multiple choice on identifying SHM vs. non-SHM systems.',
                'Calculation of spring force given k and stretch.',
                'Free-response: describe restoring force for a spring-mass system.'],
               ['Practice identifying which systems exhibit SHM.',
                'Calculate spring forces for several values of k and x.'],
               [('A 0.5 kg block compresses a spring (k=200 N/m) by 0.1 m. What is the restoring force?', ['F = kx = 200 × 0.1 = 20 N', 'Direction is toward equilibrium (opposing compression)', 'This confirms Hooke\'s law: F = -kx', 'The negative sign means force opposes displacement']),
                ('What condition must be met for a system to undergo SHM?', ['Net force proportional to displacement from equilibrium', 'Force directed toward equilibrium (restoring)', 'This gives F = -kx form', 'Results in sinusoidal position vs. time graph']),
                ('A spring-mass system is at x = +0.2 m from equilibrium. Describe the net force direction.', ['Force is directed toward equilibrium (negative direction)', 'Magnitude: F = kx', 'At equilibrium x = 0, force = 0', 'System accelerates back toward equilibrium']),
                ('Why does a larger amplitude NOT change the period of a spring-mass system?', ['Period T = 2π√(m/k) depends only on m and k', 'Amplitude does not appear in the period formula', 'Larger amplitude means larger force AND larger distance—they cancel', 'This is a key feature of SHM']),
                ('A spring with k = 400 N/m is compressed 0.05 m. Find the elastic potential energy stored.', ['PE = ½kx² = ½(400)(0.05)² ', 'PE = ½(400)(0.0025) = 0.5 J', 'Energy stored in spring, released as kinetic energy', 'At maximum compression, all energy is potential'])],
               [('Bozeman SHM Intro', 'Restoring force and SHM conditions', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics SHM', 'Spring-mass system and Hooke\'s law', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['SHM requires a restoring force proportional to displacement.',
                'Hooke\'s law: F = -kx; k is spring stiffness.',
                'Amplitude does not affect the period of SHM.']),

            _l('Period and Frequency of Oscillation',
               [_t('Period of a Spring-Mass System', 'T = 2π√(m/k); period increases with mass and decreases with spring stiffness.', 'Period does not depend on amplitude or gravitational acceleration for a spring.', 'Calculate period given m and k, or solve for m given T and k.'),
                _t('Period of a Simple Pendulum', 'T = 2π√(L/g); period depends only on length and gravitational field, not mass.', 'Heavier pendulums do NOT swing faster—mass cancels in the derivation.', 'Compare pendulum periods at different gravitational fields.'),
                _t('Frequency and Angular Frequency', 'Frequency f = 1/T (Hz); angular frequency ω = 2πf = √(k/m) for springs and √(g/L) for pendulums.', 'Angular frequency ω is in rad/s, not Hz—they are related by 2π.', 'Convert between T, f, and ω in problems.')],
               [('Period T', 'Time for one complete oscillation (s)'),
                ('Frequency f', 'Oscillations per second (Hz)'),
                ('Angular frequency ω', 'Rate of oscillation in rad/s; ω = 2πf'),
                ('Simple pendulum', 'Mass on a string where T = 2π√(L/g)'),
                ('Spring-mass system', 'Block on spring where T = 2π√(m/k)')],
               ['Calculate period and frequency for spring and pendulum systems.',
                'Explain why pendulum period is independent of mass.',
                'Convert between T, f, and ω.'],
               ['Multiple choice comparing pendulum periods at different lengths.',
                'Calculation: find new period when mass or spring constant changes.',
                'Free-response: predict period change if taken to the Moon.'],
               ['Derive T for spring-mass and pendulum from memory.',
                'Practice unit conversions between T, f, and ω.'],
               [('A spring-mass system has m = 0.4 kg and k = 100 N/m. Find the period.', ['T = 2π√(m/k) = 2π√(0.4/100)', 'T = 2π√(0.004) = 2π(0.0632)', 'T ≈ 0.397 s ≈ 0.4 s', 'Period depends on m and k only']),
                ('A pendulum of length 1 m swings on Earth (g = 9.8 m/s²). Find T.', ['T = 2π√(L/g) = 2π√(1/9.8)', 'T = 2π(0.319) ≈ 2.0 s', 'Period independent of mass', 'Doubling length multiplies T by √2']),
                ('How does the period change if the mass of a spring-mass system is quadrupled?', ['T = 2π√(m/k); if m → 4m, T → 2π√(4m/k) = 2T', 'Period doubles when mass is quadrupled', 'Period is proportional to √m', 'Spring constant k is unchanged']),
                ('A pendulum on the Moon (g_moon = 1.6 m/s²) has the same length as one on Earth. Compare periods.', ['T ∝ √(1/g); smaller g → longer period', 'T_moon/T_earth = √(g_earth/g_moon) = √(9.8/1.6) ≈ 2.47', 'Pendulum swings about 2.5× slower on Moon', 'This is used to measure gravitational acceleration']),
                ('Convert a frequency of 5 Hz to period and angular frequency.', ['T = 1/f = 1/5 = 0.2 s', 'ω = 2πf = 2π(5) = 10π ≈ 31.4 rad/s', 'ω in rad/s, f in Hz, T in s', 'All three describe the same oscillation'])],
               [('Bozeman Period and Frequency', 'Spring and pendulum period formulas', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Pendulum', 'Simple pendulum period derivation', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['T_spring = 2π√(m/k); T_pendulum = 2π√(L/g).',
                'Pendulum period is independent of mass.',
                'f = 1/T; ω = 2πf.']),

            _l('Energy in Simple Harmonic Motion',
               [_t('Energy Conservation in SHM', 'Total mechanical energy E = ½kA² is constant; it converts between PE = ½kx² and KE = ½mv².', 'Energy is NOT zero at maximum displacement—it is all potential.', 'Find velocity at any position using energy conservation.'),
                _t('Maximum Speed and Acceleration', 'Maximum speed v_max = Aω occurs at equilibrium; maximum acceleration a_max = Aω² occurs at maximum displacement.', 'Maximum speed is NOT at maximum displacement—it is at equilibrium.', 'Calculate v_max and a_max from amplitude and ω.'),
                _t('Position, Velocity, and Acceleration Functions', 'x(t) = A cos(ωt), v(t) = -Aω sin(ωt), a(t) = -Aω² cos(ωt); each is a sinusoidal function shifted by 90°.', 'Velocity and acceleration are not in phase with position—they are 90° and 180° offset.', 'Read or sketch position/velocity/acceleration graphs for SHM.')],
               [('Elastic potential energy', 'PE = ½kx² stored in a spring'),
                ('Total mechanical energy', 'E = ½kA² = KE + PE in SHM'),
                ('v_max', 'Maximum speed at equilibrium = Aω'),
                ('a_max', 'Maximum acceleration at amplitude = Aω²'),
                ('Phase relationship', 'Velocity leads position by 90° in SHM')],
               ['Apply energy conservation to find speed at any position in SHM.',
                'Identify positions of maximum KE, PE, speed, and acceleration.',
                'Read and interpret x-t, v-t, and a-t graphs for SHM.'],
               ['Multiple choice: identify where KE and PE are maximum or minimum.',
                'Calculation: find speed at x = A/2 using energy methods.',
                'Free-response: graph position, velocity, and acceleration over time.'],
               ['Practice energy bar charts for SHM at different positions.',
                'Calculate v and a at several positions given A, k, m.'],
               [('A spring-mass system (k=50 N/m, m=0.5 kg, A=0.2 m) oscillates. Find the total energy.', ['E = ½kA² = ½(50)(0.2)²', 'E = ½(50)(0.04) = 1.0 J', 'This is constant throughout the motion', 'All energy is potential at maximum displacement']),
                ('Find the speed of the block at x = 0 (equilibrium) for the system above.', ['At equilibrium, all energy is kinetic: KE = E = 1.0 J', '½mv² = 1.0 → v² = 2(1.0)/0.5 = 4.0', 'v = 2.0 m/s = v_max', 'Check: v_max = Aω = A√(k/m) = 0.2√(100) = 2.0 m/s ✓']),
                ('Find the speed at x = 0.1 m (half amplitude) for the same system.', ['E = KE + PE: 1.0 = ½mv² + ½kx²', '1.0 = ½(0.5)v² + ½(50)(0.1)²', '1.0 = 0.25v² + 0.25 → 0.25v² = 0.75', 'v = √3 ≈ 1.73 m/s']),
                ('When is acceleration maximum in SHM, and what is its direction?', ['Acceleration is maximum at x = ±A (maximum displacement)', 'At x = +A: a is negative (toward equilibrium)', 'a_max = kA/m = ω²A', 'Acceleration is always opposite to displacement in SHM']),
                ('Sketch how KE and PE vary over one complete oscillation.', ['PE = ½kx² is maximum at x = ±A, zero at x = 0', 'KE is maximum at x = 0, zero at x = ±A', 'Total energy E = KE + PE is constant (horizontal line)', 'Both PE and KE oscillate at twice the frequency of x(t)'])],
               [('Bozeman Energy in SHM', 'KE and PE exchange in simple harmonic motion', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics SHM Energy', 'Energy conservation and v_max', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['E = ½kA² is constant; KE and PE exchange throughout motion.',
                'Maximum speed occurs at equilibrium; maximum acceleration at amplitude.',
                'Use E = KE + PE to find speed at any position.']),

            _l('Applications: Coupled Oscillators and Real Systems',
               [_t('Damping and Driven Oscillations', 'Damping removes energy from an oscillator, reducing amplitude; driven oscillations occur when an external periodic force is applied.', 'Lightly damped systems still oscillate—they just lose amplitude over time, not frequency.', 'Conceptual questions on how damping changes amplitude vs. period.'),
                _t('Resonance', 'Resonance occurs when the driving frequency equals the natural frequency of the system; amplitude increases dramatically.', 'Resonance does not mean infinite amplitude in reality—damping limits it.', 'Identify resonance conditions in physical scenarios.'),
                _t('Springs in Series and Parallel', 'Springs in series: 1/k_eff = 1/k₁ + 1/k₂ (softer); springs in parallel: k_eff = k₁ + k₂ (stiffer). Both affect the period.', 'Series springs are NOT stiffer—they stretch more for the same force.', 'Calculate k_eff and new period for spring combinations.')],
               [('Damping', 'Force opposing motion that removes energy from an oscillator'),
                ('Driven oscillation', 'Oscillation maintained by a periodic external force'),
                ('Resonance', 'Maximum amplitude when driving frequency equals natural frequency'),
                ('Natural frequency', 'Frequency at which a system freely oscillates'),
                ('Series/parallel springs', 'Combinations that change effective spring constant')],
               ['Describe the effects of damping on amplitude and period.',
                'Identify conditions for resonance and explain its significance.',
                'Calculate effective spring constant for series and parallel combinations.'],
               ['Multiple choice on resonance in physical systems.',
                'Calculation of k_eff and period for springs in series or parallel.',
                'Free-response: describe effect of increasing damping on motion.'],
               ['Practice k_eff calculations for spring combinations.',
                'Research real-world examples of resonance (bridges, instruments).'],
               [('Two springs (k₁ = 100 N/m, k₂ = 100 N/m) are in parallel. Find k_eff and T for m = 1 kg.', ['k_eff = k₁ + k₂ = 200 N/m', 'T = 2π√(m/k_eff) = 2π√(1/200)', 'T = 2π(0.0707) ≈ 0.444 s', 'Parallel springs are stiffer → shorter period']),
                ('Same springs connected in series. Find k_eff and T.', ['1/k_eff = 1/100 + 1/100 = 2/100, so k_eff = 50 N/m', 'T = 2π√(1/50) = 2π(0.1414) ≈ 0.889 s', 'Series springs are softer → longer period', 'T_series = √2 × T_single spring']),
                ('What is resonance and why is it important in engineering?', ['Resonance occurs when driving frequency = natural frequency', 'Amplitude of oscillation becomes very large', 'Can cause structural failure (Tacoma Narrows Bridge)', 'Engineers design to avoid resonance or add damping']),
                ('How does damping affect amplitude and period of an oscillator?', ['Damping reduces amplitude over time as energy is removed', 'Period is only slightly affected by light damping', 'Heavy damping can prevent oscillation entirely (overdamping)', 'Damping converts mechanical energy to thermal energy']),
                ('A system oscillates freely at 5 Hz. At what driving frequency does resonance occur?', ['Resonance at natural frequency = 5 Hz', 'Driving frequency must match natural frequency', 'At resonance, amplitude is maximized', 'In a damped system, amplitude is large but finite'])],
               [('Bozeman Resonance', 'Resonance and driven oscillations', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Springs', 'Series and parallel spring combinations', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Damping reduces amplitude; resonance occurs at natural frequency.',
                'Springs in parallel: k_eff = k₁ + k₂ (stiffer).',
                'Springs in series: 1/k_eff = 1/k₁ + 1/k₂ (softer).'])
        ],
        'unit_qs': [
            ('A spring-mass system oscillates with amplitude 0.3 m, k = 200 N/m. Find total energy and maximum speed for m = 0.5 kg.',
             ['E = ½kA² = ½(200)(0.3)² = 9.0 J', 'v_max = A√(k/m) = 0.3√(200/0.5) = 0.3(20) = 6.0 m/s', 'Or: ½mv² = 9.0 → v = √(18/0.5) = 6.0 m/s', 'Maximum speed occurs at equilibrium position']),
            ('Compare the periods of a pendulum on Earth vs. a planet where g = 4g_Earth.', ['T = 2π√(L/g); larger g → smaller T', 'T_planet = 2π√(L/4g) = ½ × T_earth', 'Period is halved on the high-gravity planet', 'Period ∝ 1/√g']),
            ('A 0.2 kg block on a spring (k = 80 N/m) is displaced 0.15 m and released. Find the speed at x = 0.10 m.', ['E = ½kA² = ½(80)(0.15)² = 0.90 J', 'At x = 0.10 m: PE = ½(80)(0.10)² = 0.40 J', 'KE = 0.90 - 0.40 = 0.50 J', 'v = √(2KE/m) = √(1.0/0.2) = √5 ≈ 2.24 m/s']),
            ('Describe qualitatively how the motion of a spring-mass system changes if placed in a viscous fluid.', ['Damping force opposes motion and removes energy', 'Amplitude decreases over time (exponential decay)', 'Period is nearly unchanged for light damping', 'System eventually comes to rest at equilibrium']),
            ('Two identical springs (k = 60 N/m each) support a 3 kg mass in parallel. Find the period.', ['k_eff = 60 + 60 = 120 N/m', 'T = 2π√(m/k_eff) = 2π√(3/120)', 'T = 2π√(0.025) = 2π(0.158) ≈ 0.995 s', 'Period ≈ 1.0 s']),
            ('A pendulum has a period of 2 s on Earth. What length is required?', ['T = 2π√(L/g) → 2 = 2π√(L/9.8)', '1/π = √(L/9.8) → L/9.8 = 1/π²', 'L = 9.8/π² ≈ 9.8/9.87 ≈ 0.993 m ≈ 1.0 m', 'A 1-meter pendulum has a period of approximately 2 s on Earth']),
            ('At what position in SHM is acceleration maximum, and in what direction?', ['Acceleration is maximum at x = ±A (extremes of motion)', 'At x = +A: acceleration points toward equilibrium (negative x)', 'a_max = kA/m = ω²A', 'Acceleration is always directed toward equilibrium (restoring)']),
            ('A student claims amplitude affects the period of a mass-spring system. How would you refute this?', ['Period formula: T = 2π√(m/k) — amplitude A is absent', 'Experimental evidence: period is same for large and small amplitudes', 'Mathematically: larger amplitude means larger force over larger distance — effects cancel', 'This is a defining property of SHM']),
            ('A spring system has angular frequency ω = 8 rad/s and amplitude 0.25 m. Find v_max and a_max.', ['v_max = Aω = 0.25 × 8 = 2.0 m/s', 'a_max = Aω² = 0.25 × 64 = 16 m/s²', 'v_max at x = 0; a_max at x = ±A', 'These are the extremes of velocity and acceleration']),
            ('Explain resonance using an example from everyday life.', ['Resonance occurs when driving frequency matches natural frequency', 'Example: pushing a swing at its natural period amplifies motion', 'Example: Tacoma Narrows Bridge — wind matched natural frequency', 'At resonance, small periodic forces produce large oscillations']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=Hn7IIBHXN3U',
    },

    {
        'num': 11, 'title': 'Fluid Statics',
        'file': 'ap-physics-1-2-11-physics-2-unit-4-magnetism-and-electromagnetic-induction.html',
        'desc': 'Pressure in fluids, buoyancy, and Archimedes\' principle.',
        'gateway': [
            'Define pressure and calculate it for fluids at various depths.',
            'Apply Pascal\'s law to hydraulic systems.',
            'State Archimedes\' principle and determine whether objects float or sink.',
            'Explain buoyant force in terms of displaced fluid weight.',
        ],
        'lessons': [
            _l('Pressure in Fluids',
               [_t('Fluid Pressure', 'Pressure P = F/A (Pa = N/m²); in a static fluid P = P₀ + ρgh, where ρ is fluid density, g is gravitational field, and h is depth.', 'Pressure depends on depth, not the total amount of fluid or container shape.', 'Calculate pressure at depth in a fluid column.'),
                _t('Atmospheric Pressure', 'Atmospheric pressure (≈ 101 325 Pa = 1 atm) acts on all surfaces exposed to the atmosphere; gauge pressure is pressure above atmospheric.', 'Gauge pressure is relative to atmosphere—absolute pressure includes atmosphere.', 'Distinguish gauge from absolute pressure in problems.'),
                _t('Pascal\'s Law', 'A pressure change applied to an enclosed fluid is transmitted equally to all parts of the fluid; the basis for hydraulic systems.', 'Pascal\'s law applies to static enclosed fluids, not open channels.', 'Solve hydraulic lift problems using F₁/A₁ = F₂/A₂.')],
               [('Pressure', 'Force per unit area: P = F/A (Pa)'),
                ('Hydrostatic pressure', 'Pressure in a fluid at rest: P = P₀ + ρgh'),
                ('Gauge pressure', 'Pressure above atmospheric pressure'),
                ('Pascal\'s law', 'Pressure change transmitted uniformly in enclosed fluid'),
                ('Hydraulic system', 'Machine using Pascal\'s law to multiply force')],
               ['Calculate pressure at a given depth in a liquid.',
                'Distinguish gauge pressure from absolute pressure.',
                'Apply Pascal\'s law to hydraulic lifts.'],
               ['Multiple choice: compare pressures at different depths or container shapes.',
                'Calculation of force output in a hydraulic system.',
                'Free-response: explain why pressure depends on depth not volume.'],
               ['Practice pressure calculations at multiple depths.',
                'Solve hydraulic system problems for force and distance.'],
               [('Find the pressure at 10 m depth in water (ρ = 1000 kg/m³, P₀ = 101 325 Pa).', ['P = P₀ + ρgh = 101 325 + (1000)(9.8)(10)', 'P = 101 325 + 98 000 = 199 325 Pa', 'P ≈ 2 atm (pressure doubles every ~10 m in water)', 'Gauge pressure = ρgh = 98 000 Pa ≈ 1 atm']),
                ('Two identical containers have different shapes but same liquid depth. Compare bottom pressures.', ['Pressure P = ρgh depends only on depth h and fluid density ρ', 'Bottom pressure is the same regardless of container shape', 'This is the hydrostatic paradox — volume does not affect bottom pressure', 'Force on bottom may differ if areas differ, but pressure is equal']),
                ('A hydraulic lift has pistons with areas A₁ = 0.01 m² and A₂ = 0.5 m². A force of 200 N is applied to the small piston. Find the output force.', ['Pascal: P₁ = P₂ → F₁/A₁ = F₂/A₂', 'F₂ = F₁(A₂/A₁) = 200(0.5/0.01) = 200 × 50 = 10 000 N', 'Hydraulic systems multiply force by area ratio', 'Energy is conserved: small piston moves far, large piston moves little']),
                ('What is gauge pressure and how does it differ from absolute pressure?', ['Absolute pressure = total pressure including atmosphere', 'Gauge pressure = absolute pressure − atmospheric pressure', 'A tire at 200 kPa gauge is at 301 kPa absolute', 'Most instruments measure gauge pressure']),
                ('Why does a fluid exert pressure in all directions, not just downward?', ['Fluid molecules move randomly and collide with all surfaces', 'Pressure = force per area from molecular collisions', 'In a static fluid, pressure at a point is the same in all directions', 'This is a property of fluids (not solids, which transmit force only along the solid)'])],
               [('Bozeman Fluid Pressure', 'Pressure in static fluids and Pascal\'s law', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Pressure', 'Hydrostatic pressure calculation', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['P = P₀ + ρgh; pressure depends on depth, not container shape.',
                'Pascal\'s law: pressure change transmitted uniformly in enclosed fluid.',
                'Hydraulic systems: F₁/A₁ = F₂/A₂.']),

            _l('Buoyancy and Archimedes\' Principle',
               [_t('Archimedes\' Principle', 'The buoyant force on an object equals the weight of fluid displaced: F_b = ρ_fluid × V_displaced × g.', 'Buoyant force equals displaced fluid weight, not object weight.', 'Calculate buoyant force given displaced volume and fluid density.'),
                _t('Floating and Sinking Conditions', 'Object floats if ρ_object < ρ_fluid; sinks if ρ_object > ρ_fluid; neutrally buoyant if equal. For floating objects, F_b = weight of object.', 'A floating object displaces its own weight in fluid, not its own volume.', 'Determine fraction of object submerged using density ratio.'),
                _t('Buoyant Force and Net Force', 'Net upward force on a submerged object = F_b - W_object = (ρ_fluid - ρ_object) × V × g; this determines apparent weight.', 'Buoyant force does not depend on depth—only on displaced volume and fluid density.', 'Calculate apparent weight of submerged object.')],
               [('Buoyant force', 'Upward force on object equal to weight of displaced fluid'),
                ('Archimedes\' principle', 'F_b = ρ_fluid × V_disp × g'),
                ('Apparent weight', 'Actual weight minus buoyant force'),
                ('Neutral buoyancy', 'Object floats within fluid when densities are equal'),
                ('Displacement', 'Volume of fluid pushed aside by submerged object')],
               ['Calculate buoyant force using Archimedes\' principle.',
                'Determine whether an object floats, sinks, or is neutrally buoyant.',
                'Find the fraction of a floating object submerged.'],
               ['Multiple choice comparing buoyant forces for objects of different densities.',
                'Calculation of apparent weight of submerged object.',
                'Free-response: explain why a steel ship floats.'],
               ['Practice buoyant force calculations for objects in water and oil.',
                'Determine submerged fraction for various floating objects.'],
               [('A wooden block (V = 0.02 m³, ρ = 600 kg/m³) floats in water (ρ = 1000 kg/m³). What fraction is submerged?', ['For floating: ρ_object × V_total = ρ_fluid × V_submerged', 'V_sub/V_total = ρ_obj/ρ_fluid = 600/1000 = 0.60', '60% of the block is submerged', '40% remains above water surface']),
                ('A 5 kg aluminum block (ρ = 2700 kg/m³) is submerged in water. Find buoyant force and apparent weight.', ['V = m/ρ = 5/2700 = 1.85 × 10⁻³ m³', 'F_b = ρ_water × V × g = 1000 × 1.85×10⁻³ × 9.8 = 18.1 N', 'Weight = mg = 5 × 9.8 = 49 N', 'Apparent weight = 49 - 18.1 = 30.9 N']),
                ('An object has apparent weight 60 N in air and 40 N when submerged in water. Find its volume.', ['Buoyant force = W_air - W_water = 60 - 40 = 20 N', 'F_b = ρ_water × V × g → V = F_b/(ρ_water × g)', 'V = 20/(1000 × 9.8) = 2.04 × 10⁻³ m³', 'This is the Archimedes principle method for finding volume']),
                ('Why does a dense steel ship float when solid steel sinks?', ['The ship is hollow, so average density of (steel + air) < ρ_water', 'F_b = weight of displaced water; large hull displaces much water', 'Total weight < buoyant force when hull shape displaces enough water', 'This is why ships have displacement tonnage ratings']),
                ('Two objects have the same mass but different densities. Which has greater buoyant force when fully submerged?', ['F_b = ρ_fluid × V × g; larger volume → greater F_b', 'Lower density object has greater volume for same mass', 'Lower density object experiences greater buoyant force', 'The denser object is more likely to sink'])],
               [('Bozeman Buoyancy', 'Archimedes\' principle and floating/sinking', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Buoyancy', 'Buoyant force calculations', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['F_b = ρ_fluid × V_displaced × g.',
                'Float if ρ_object < ρ_fluid; fraction submerged = ρ_obj/ρ_fluid.',
                'Apparent weight = actual weight - buoyant force.']),

            _l('Pressure Measurement and Applications',
               [_t('Manometers and Barometers', 'A manometer measures gauge pressure using a U-tube of fluid; a barometer measures atmospheric pressure using a sealed column of mercury or fluid.', 'The barometer reading depends on atmospheric pressure, not on the tube diameter.', 'Read and interpret pressure from manometer and barometer diagrams.'),
                _t('Pressure in Connected Containers', 'In connected static fluids, pressure at the same height is equal throughout; this determines fluid levels in U-tubes.', 'The heavier (denser) fluid settles lower; equal pressure at same depth.', 'Solve for unknown fluid heights in U-tube problems.'),
                _t('Surface Tension and Capillarity', 'Surface tension results from intermolecular cohesion; capillary action is the rise (or fall) of liquid in narrow tubes due to adhesion and cohesion.', 'Surface tension is not the same as atmospheric pressure—it is a surface property of liquids.', 'Qualitative AP® questions on capillarity and surface tension.')],
               [('Manometer', 'U-tube device measuring gauge pressure using fluid height'),
                ('Barometer', 'Device measuring atmospheric pressure using a fluid column'),
                ('Surface tension', 'Inward cohesive force at the surface of a liquid'),
                ('Capillary action', 'Rise of liquid in narrow tubes due to adhesion > cohesion'),
                ('U-tube', 'Connected tube used to compare pressures using fluid levels')],
               ['Read pressure from manometer diagrams.',
                'Apply equal-pressure-at-same-depth principle to connected fluids.',
                'Explain surface tension and capillary action qualitatively.'],
               ['Multiple choice on U-tube fluid heights with different fluid densities.',
                'Calculation of atmospheric pressure from barometer reading.',
                'Free-response: sketch and analyze a manometer diagram.'],
               ['Solve U-tube problems with two different fluids.',
                'Explain capillary rise for water in glass vs. mercury in glass.'],
               [('A mercury barometer reads 760 mm Hg. What is atmospheric pressure? (ρ_Hg = 13 600 kg/m³)', ['P_atm = ρgh = 13 600 × 9.8 × 0.760', 'P_atm = 101 069 Pa ≈ 101 kPa ≈ 1 atm', '760 mm Hg is the standard definition of 1 atm', 'Using water: height would be 13.6× greater ≈ 10.3 m']),
                ('In a U-tube with water on one side and oil (ρ = 800 kg/m³) on the other, the oil column is 15 cm higher. Find the pressure difference.', ['At the water-oil interface, pressures must be equal', 'The oil column provides extra pressure: ΔP = ρ_oil × g × h_extra', 'ΔP = 800 × 9.8 × 0.15 = 1176 Pa', 'Water side is 1176 Pa higher in pressure at the bottom interface']),
                ('Why does the width of a barometer tube not affect the reading?', ['Pressure P = ρgh; height h is what matters, not tube area', 'Pressure is independent of the cross-sectional area of the tube', 'Wider tube has more mercury weight but also more area—pressure is the same', 'Barometer height is a pure pressure measurement']),
                ('Water rises in a glass capillary tube but mercury is depressed. Explain.', ['Water adheres to glass strongly (adhesion > cohesion) → rises', 'Mercury cohesion > adhesion to glass → mercury is depressed', 'Surface tension creates a meniscus that pulls or pushes fluid', 'Narrower tubes produce greater capillary rise (inversely proportional to radius)']),
                ('Two connected tanks are filled with water and connected at the bottom. One is heated. What happens to the water levels?', ['Hot water expands: density decreases', 'Less dense hot water rises; cooler denser water flows down', 'Hot water tank level rises, cool tank level falls slightly', 'Equal pressure at connection maintained by flow'])],
               [('Bozeman Fluid Statics', 'Pressure measurement and U-tube problems', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Barometer', 'Barometer and manometer reading', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Barometer: P_atm = ρgh; reading independent of tube width.',
                'Equal pressure at same depth in connected static fluids.',
                'Surface tension: cohesion > adhesion depresses; adhesion > cohesion raises.']),

            _l('Fluid Statics in Real-World Contexts',
               [_t('Submarines and Depth Control', 'Submarines control depth by adjusting buoyancy with ballast tanks: adding water increases weight, releasing water increases buoyancy.', 'Submarines do not change volume to control depth—they change mass by flooding tanks.', 'Explain submarine buoyancy control qualitatively.'),
                _t('Atmospheric Layers and Pressure', 'Atmospheric pressure decreases with altitude because there is less air above; the pressure equation P = P₀ + ρgh applies approximately in thin layers.', 'Air density also decreases with altitude, so pressure drops faster than linearly.', 'Qualitative explanation of why mountains have lower air pressure.'),
                _t('Blood Pressure and Medicine', 'Blood pressure is gauge pressure (mmHg); systolic/diastolic values describe peak/minimum pressure during heartbeats; measured relative to atmospheric pressure.', 'Blood pressure is gauge pressure, not absolute pressure.', 'Apply fluid pressure concepts to biological/medical contexts.')],
               [('Ballast tank', 'Tank filled with water or air to adjust submarine buoyancy'),
                ('Systolic pressure', 'Peak blood pressure during heart contraction'),
                ('Diastolic pressure', 'Minimum blood pressure between heartbeats'),
                ('mmHg', 'Millimeters of mercury; unit of blood pressure'),
                ('Altitude effect', 'Air pressure decreases with altitude due to less air above')],
               ['Explain how submarines control depth using ballast tanks.',
                'Apply P = ρgh to biological and atmospheric contexts.',
                'Interpret blood pressure readings as gauge pressure.'],
               ['Multiple choice applying fluid statics to medical or engineering contexts.',
                'Free-response: design a system to measure depth underwater.',
                'Conceptual: explain why ears pop in airplane or at altitude.'],
               ['Research how diving bells and submarines maintain pressure.',
                'Calculate pressure at various blood-vessel heights in the body.'],
               [('A submarine at 200 m depth. Find water pressure at that depth. (ρ_water = 1025 kg/m³ for seawater)', ['P = ρgh = 1025 × 9.8 × 200 = 2 009 000 Pa', 'P ≈ 2.0 MPa ≈ 20 atm (gauge)', 'Total absolute pressure ≈ 21 atm', 'Submarine hull must withstand this enormous pressure']),
                ('How does a submarine descend and ascend using ballast tanks?', ['To descend: flood ballast tanks with seawater → weight increases > buoyancy → sinks', 'To ascend: blow compressed air into tanks → water expelled → buoyancy > weight → rises', 'At neutral buoyancy: weight = buoyant force → hovers', 'Volume stays constant; mass changes']),
                ('Blood pressure of 120/80 mmHg is measured at heart level. What is the gauge pressure in Pa?', ['Systolic: 120 mmHg = 120 × 133.3 = 16 000 Pa gauge', 'Diastolic: 80 mmHg = 80 × 133.3 = 10 664 Pa gauge', '1 mmHg ≈ 133.3 Pa (from ρ_Hg × g × 0.001 m)', 'These are gauge pressures above atmospheric']),
                ('Why does air pressure decrease with altitude?', ['P = weight of air column above per unit area', 'At higher altitude, less air above → less weight → less pressure', 'Air density also decreases, so decrease is not perfectly linear', 'At sea level: 101 kPa; at 8850 m (Everest): ~34 kPa']),
                ('Your ears pop in an airplane as it pressurizes. Explain using fluid pressure.', ['Cabin pressure changes rapidly during ascent/descent', 'Pressure inside ear canal is initially at ground pressure', 'Pressure difference across eardrum causes discomfort', 'Yawning/swallowing opens Eustachian tube to equalize pressure'])],
               [('Bozeman Real-World Fluid Applications', 'Fluid statics in biology and engineering', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Archimedes', 'Archimedes principle applied to submarines', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Submarines change mass (ballast water) to adjust buoyancy.',
                'Atmospheric pressure decreases with altitude due to less air above.',
                'Blood pressure is gauge pressure measured in mmHg.'])
        ],
        'unit_qs': [
            ('Calculate the pressure at the bottom of a lake 30 m deep. (ρ_water = 1000 kg/m³, P_atm = 101 325 Pa)',
             ['P = P₀ + ρgh = 101 325 + 1000(9.8)(30)', 'P = 101 325 + 294 000 = 395 325 Pa', 'P ≈ 395 kPa ≈ 3.9 atm absolute', 'Gauge pressure = 294 000 Pa ≈ 2.9 atm']),
            ('A wooden cube (ρ = 500 kg/m³, side = 0.2 m) floats in water. Find the submerged depth.',
             ['V_total = 0.2³ = 0.008 m³; ρ_obj/ρ_fluid = 500/1000 = 0.5', 'Half submerged → submerged depth = 0.5 × 0.2 = 0.10 m', 'F_b = ρ_water × V_sub × g = 1000(0.004)(9.8) = 39.2 N', 'Weight = ρ_obj × V × g = 500(0.008)(9.8) = 39.2 N ✓']),
            ('A hydraulic press has a small piston of area 0.002 m² and large piston of 0.10 m². A 50 N force is applied to the small piston. Find output force and pressure throughout the fluid.',
             ['P = F₁/A₁ = 50/0.002 = 25 000 Pa throughout the fluid', 'F₂ = P × A₂ = 25 000 × 0.10 = 2500 N', 'Force is multiplied by area ratio = 50', 'Pascal\'s law: pressure is equal everywhere in the enclosed fluid']),
            ('An object weighs 80 N in air and 50 N when submerged in water. Find the density of the object.',
             ['Buoyant force = 80 - 50 = 30 N', 'V = F_b/(ρ_water × g) = 30/(1000 × 9.8) = 3.06 × 10⁻³ m³', 'Mass = W/g = 80/9.8 = 8.16 kg', 'ρ = m/V = 8.16/(3.06 × 10⁻³) = 2667 kg/m³ (≈ aluminum)']),
            ('Explain why a ship made of dense iron can float while a solid iron ball sinks.',
             ['A hollow ship has average density (iron + enclosed air) < ρ_water', 'The ship displaces a large volume of water equal to its own weight', 'Solid iron ball displaces water equal only to ball volume, which weighs less than iron', 'Buoyancy depends on displaced volume relative to object weight']),
            ('A mercury U-tube manometer reads a height difference of 5 cm. Find the gauge pressure. (ρ_Hg = 13 600 kg/m³)',
             ['P_gauge = ρgh = 13 600 × 9.8 × 0.05', 'P_gauge = 6664 Pa ≈ 6.7 kPa', 'In mmHg: 50 mmHg', 'This pressure difference acts across the U-tube']),
            ('A scuba diver descends to 20 m in seawater (ρ = 1025 kg/m³). What is the gauge pressure? Why must tanks be pressurized?',
             ['P_gauge = ρgh = 1025 × 9.8 × 20 = 201 100 Pa ≈ 2 atm', 'At 2 atm gauge, diver breathes air at 3 atm absolute', 'Tank must supply air at ambient pressure or lungs cannot inhale', 'This is why pressure regulators are needed']),
            ('A floating ice cube melts. Does the water level in the glass rise, fall, or stay the same? Explain.',
             ['Floating ice displaces water equal to its own weight', 'Melted ice has same mass → same volume of water', 'Water level remains unchanged when floating ice melts', 'This has implications for sea-level rise from floating vs. land ice']),
            ('Two liquids of densities ρ₁ = 800 and ρ₂ = 1200 kg/m³ are poured into a U-tube. Find the height ratio h₁/h₂ when in equilibrium.',
             ['Equal pressure at the bottom interface: ρ₁gh₁ = ρ₂gh₂', 'h₁/h₂ = ρ₂/ρ₁ = 1200/800 = 1.5', 'The lighter fluid (ρ₁) has the taller column', 'Heights are inversely proportional to densities']),
            ('Explain how atmospheric pressure is measured with a mercury barometer and why the diameter of the tube does not matter.',
             ['Mercury is pushed up by atmospheric pressure; vacuum above holds no air', 'Height h of mercury column satisfies P_atm = ρ_Hg × g × h', 'Wider tube has more weight but also more area; pressure is weight/area — area cancels', 'Standard atmosphere = 760 mm Hg regardless of tube width']),
        ],
    'review_video': 'https://www.youtube.com/watch?v=Hn7IIBHXN3U',
    },

    {
        'num': 12, 'title': 'Fluid Dynamics',
        'file': 'ap-physics-1-2-12-physics-2-unit-5-geometric-and-physical-optics.html',
        'desc': 'Moving fluids, the continuity equation, and Bernoulli\'s principle.',
        'gateway': [
            'Distinguish ideal fluid assumptions from real-fluid behavior.',
            'Apply the continuity equation: A₁v₁ = A₂v₂ for incompressible flow.',
            'Apply Bernoulli\'s equation to connect pressure, height, and speed.',
            'Explain everyday phenomena using Bernoulli\'s principle.',
        ],
        'lessons': [
            _l('Ideal Fluids and Fluid Flow',
               [_t('Ideal Fluid Assumptions', 'An ideal fluid is incompressible (constant density), non-viscous (no friction), and has steady (laminar) flow. Real fluids deviate from these.', 'Real fluids have viscosity (internal friction) and can have turbulent flow at high speeds.', 'Identify which assumptions are being made in a given fluid problem.'),
                _t('Streamlines and Flow Rate', 'Streamlines show the path of fluid particles in steady flow; they never cross. Volume flow rate Q = Av (m³/s) measures how much fluid passes a cross-section per second.', 'Streamlines represent velocity direction, not the speed—closer streamlines mean higher speed.', 'Calculate volume flow rate from cross-section area and fluid speed.'),
                _t('Continuity Equation', 'For incompressible fluids in a pipe, A₁v₁ = A₂v₂ (continuity equation). Narrower pipe → higher speed.', 'The continuity equation is for volume flow rate, not mass, for incompressible fluids.', 'Solve for speed or area at different points in a pipe using continuity.')],
               [('Ideal fluid', 'Incompressible, non-viscous fluid with laminar flow'),
                ('Viscosity', 'Internal friction within a real fluid resisting flow'),
                ('Streamline', 'Path of a fluid element in steady flow; never cross'),
                ('Volume flow rate Q', 'Q = Av; volume of fluid passing per unit time (m³/s)'),
                ('Continuity equation', 'A₁v₁ = A₂v₂ for incompressible flow in a pipe')],
               ['State the ideal fluid assumptions and identify deviations in real fluids.',
                'Calculate volume flow rate from area and speed.',
                'Apply continuity to find speed changes in pipes of varying cross-section.'],
               ['Multiple choice: predict speed change when pipe narrows.',
                'Calculation of speed at a constriction using continuity.',
                'Free-response: explain why a river flows faster in a narrow canyon.'],
               ['Practice continuity equation problems with various pipe shapes.',
                'Draw and interpret streamline diagrams.'],
               [('Water flows in a pipe with radius 0.05 m at 2 m/s. It enters a narrower section of radius 0.02 m. Find the speed there.', ['A₁ = π(0.05)² = 7.85 × 10⁻³ m²; A₂ = π(0.02)² = 1.26 × 10⁻³ m²', 'A₁v₁ = A₂v₂ → v₂ = v₁(A₁/A₂) = 2(7.85/1.26)', 'v₂ = 2 × 6.25 = 12.5 m/s', 'Narrower pipe: faster flow']),
                ('Calculate the volume flow rate for the pipe above.', ['Q = A₁v₁ = 7.85 × 10⁻³ × 2 = 1.57 × 10⁻² m³/s', 'Or Q = A₂v₂ = 1.26 × 10⁻³ × 12.5 = 1.57 × 10⁻² m³/s ✓', 'Flow rate is constant throughout the pipe', 'Q is conserved in steady incompressible flow']),
                ('A river is 10 m wide and 2 m deep flowing at 1 m/s. It narrows to 4 m wide and 1 m deep. Find new speed.', ['A₁ = 10 × 2 = 20 m²; A₂ = 4 × 1 = 4 m²', 'v₂ = v₁(A₁/A₂) = 1.0(20/4) = 5.0 m/s', 'Narrow canyon → faster current (rapids)', 'Continuity applies to natural waterways too']),
                ('What is the difference between laminar and turbulent flow?', ['Laminar (streamline) flow: smooth parallel layers, low speed', 'Turbulent flow: chaotic, irregular eddies form at high speed', 'Reynolds number characterizes transition between the two', 'Ideal fluid assumes laminar flow throughout']),
                ('Why does blowing across a straw opening cause liquid to rise? (qualitative)', ['Fast air across the top lowers pressure above the straw', 'Atmospheric pressure below pushes liquid up', 'This previews Bernoulli\'s principle', 'Pressure is lower where fluid speed is higher'])],
               [('Bozeman Fluid Dynamics', 'Continuity equation and fluid flow', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Continuity', 'A₁v₁ = A₂v₂ derivation and application', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Ideal fluid: incompressible, non-viscous, laminar flow.',
                'Q = Av is constant; continuity: A₁v₁ = A₂v₂.',
                'Narrower pipe → faster flow speed.']),

            _l('Bernoulli\'s Equation',
               [_t('Bernoulli\'s Principle', 'P + ½ρv² + ρgh = constant along a streamline. Faster-moving fluid has lower pressure; this arises from energy conservation.', 'Bernoulli\'s equation applies along a streamline, not between different streamlines.', 'Apply Bernoulli\'s equation at two points along a flow to find pressure or speed.'),
                _t('Applications of Bernoulli\'s Principle', 'Lift on wings (faster air above → lower pressure), Venturi meter (pressure drop in constriction), Pitot tube (speed from pressure difference), and spray atomizers all use Bernoulli\'s equation.', 'Airplane lift is more complex than just "Bernoulli"—angle of attack and Newtonian reaction also contribute.', 'Identify which Bernoulli applications appear in AP® free-response.'),
                _t('Torricelli\'s Theorem', 'Speed of fluid exiting a hole in a tank at depth h below the surface: v = √(2gh). This is derived from Bernoulli\'s equation with the tank top as the reference.', 'Torricelli\'s theorem applies when the hole is small compared to the tank (so surface speed ≈ 0).', 'Calculate efflux speed from hole depth using Torricelli\'s theorem.')],
               [('Bernoulli\'s equation', 'P + ½ρv² + ρgh = const; energy conservation in fluid flow'),
                ('Dynamic pressure', '½ρv²; kinetic energy per unit volume of flowing fluid'),
                ('Venturi effect', 'Pressure drop in a constriction due to increased flow speed'),
                ('Lift', 'Net upward pressure force on a wing from faster airflow above'),
                ('Torricelli\'s theorem', 'Efflux speed v = √(2gh) for fluid exiting a hole at depth h')],
               ['Apply Bernoulli\'s equation between two points in a flow.',
                'Explain how faster fluid speed relates to lower pressure.',
                'Calculate efflux speed using Torricelli\'s theorem.'],
               ['Multiple choice: predict pressure change when fluid speeds up.',
                'Calculation using Bernoulli\'s equation for connected pipes.',
                'Free-response: design a Venturi meter and explain how it measures speed.'],
               ['Practice Bernoulli\'s equation with combined continuity.',
                'Calculate efflux speed for various hole positions in a tank.'],
               [('Water flows horizontally; at point 1 (A₁ = 0.01 m², v₁ = 2 m/s, P₁ = 150 kPa). At point 2 the pipe narrows to A₂ = 0.004 m². Find v₂ and P₂. (ρ = 1000 kg/m³)', ['v₂ = v₁(A₁/A₂) = 2(0.01/0.004) = 5 m/s (continuity)', 'Bernoulli (same height): P₁ + ½ρv₁² = P₂ + ½ρv₂²', 'P₂ = 150 000 + ½(1000)(4 - 25) = 150 000 - 10 500', 'P₂ = 139 500 Pa = 139.5 kPa']),
                ('A large tank of water has a small hole 3 m below the water surface. Find the efflux speed.', ['Torricelli: v = √(2gh) = √(2 × 9.8 × 3)', 'v = √58.8 ≈ 7.67 m/s', 'Same result as free fall from 3 m height', 'Assumes tank surface area >> hole area']),
                ('Explain qualitatively why an airplane wing generates lift using Bernoulli.', ['Wing shape (airfoil) makes air travel faster over the top surface', 'Faster air → lower pressure on top (Bernoulli)', 'Higher pressure below → net upward force (lift)', 'Angle of attack also contributes to lift in real wings']),
                ('A Venturi meter has throat area = 0.25 × pipe area. Pipe velocity is 4 m/s. Find throat velocity and pressure drop. (ρ = 1000 kg/m³)', ['v_throat = v_pipe × (A_pipe/A_throat) = 4 × 4 = 16 m/s', 'ΔP = ½ρ(v_throat² - v_pipe²) = ½(1000)(256 - 16)', 'ΔP = 500 × 240 = 120 000 Pa = 120 kPa', 'This pressure drop is measured to calculate flow rate']),
                ('Bernoulli\'s equation is derived from energy conservation. Identify what each term represents.', ['P: pressure energy per unit volume (work done by pressure)', '½ρv²: kinetic energy per unit volume', 'ρgh: gravitational potential energy per unit volume', 'Sum is constant: total mechanical energy per unit volume is conserved'])],
               [('Bozeman Bernoulli', 'Bernoulli\'s equation derivation and applications', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Bernoulli', 'Bernoulli applied to pipes and airfoils', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['P + ½ρv² + ρgh = constant; faster flow means lower pressure.',
                'Torricelli: v = √(2gh) for efflux from a hole at depth h.',
                'Venturi effect: narrowing → speed up → pressure drops.']),

            _l('Real Fluids: Viscosity and Turbulence',
               [_t('Viscosity', 'Viscosity is a fluid\'s resistance to flow (internal friction); it causes a velocity gradient across a pipe, with fluid moving fastest at the center.', 'Viscous flow does not violate continuity — total volume flow rate is still conserved.', 'Qualitative questions on how viscosity affects flow in pipes.'),
                _t('Poiseuille\'s Law (Qualitative)', 'Flow rate through a pipe Q ∝ r⁴ × ΔP / (μL); flow drops dramatically with smaller radius. Used in medicine (arteries, syringes).', 'Because Q ∝ r⁴, halving the radius reduces flow to 1/16—a strong effect.', 'Predict flow rate changes for different pipe radii qualitatively.'),
                _t('Turbulence and Reynolds Number', 'Turbulence occurs at high speeds or large dimensions; the Reynolds number Re = ρvL/μ predicts transition. High Re → turbulent; low Re → laminar.', 'Turbulence is not necessarily bad — it promotes mixing but increases resistance.', 'Identify conditions likely to produce turbulent flow.')],
               [('Viscosity μ', 'Measure of fluid\'s resistance to flow (Pa·s)'),
                ('Laminar flow', 'Smooth, layered flow with parallel streamlines'),
                ('Turbulent flow', 'Chaotic irregular flow at high speed or Reynolds number'),
                ('Poiseuille\'s law', 'Q ∝ r⁴ΔP/(μL) for viscous flow in a cylinder'),
                ('Reynolds number Re', 'Dimensionless ratio predicting laminar vs. turbulent flow')],
               ['Describe the velocity profile in viscous pipe flow.',
                'Predict qualitatively how radius changes affect flow rate (Poiseuille).',
                'Identify conditions leading to turbulent vs. laminar flow.'],
               ['Multiple choice: predict effect of artery narrowing on blood flow rate.',
                'Conceptual: why does reducing pipe radius by half drastically reduce flow?',
                'Free-response: explain the significance of Reynolds number.'],
               ['Research medical applications of Poiseuille\'s law (arteries, IV drips).',
                'Compare viscosities of common fluids (water, honey, oil).'],
               [('How does viscosity affect fluid flow in a pipe compared to ideal flow?', ['Ideal: uniform velocity across cross-section; viscous: parabolic profile', 'Fluid moves fastest at center, zero at the walls (no-slip condition)', 'Viscosity causes energy loss as heat, reducing flow rate', 'Real fluids require a pressure difference to maintain flow']),
                ('An artery is partially blocked, reducing radius by 50%. By what factor does blood flow change? (Poiseuille)', ['Q ∝ r⁴; r → 0.5r → Q → (0.5)⁴ × Q = 0.0625Q', 'Flow rate drops to 6.25% of original (factor of 16 reduction)', 'This explains why arterial blockage is medically dangerous', 'To restore flow, blood pressure must increase 16-fold']),
                ('What is the Reynolds number and what does a high value indicate?', ['Re = ρvL/μ; dimensionless ratio of inertial to viscous forces', 'Low Re (< ~2000): laminar flow; high Re (> ~4000): turbulent', 'High Re means inertial forces dominate — flow becomes chaotic', 'Re depends on fluid speed, density, viscosity, and pipe diameter']),
                ('Why does honey flow much slower than water through the same tube?', ['Honey has much higher viscosity μ than water', 'Viscosity resists relative motion between fluid layers', 'Q ∝ 1/μ; higher μ → much lower flow rate', 'Honey viscosity ≈ 1000× that of water at room temperature']),
                ('Give an example where turbulence is beneficial.', ['Turbulent flow in heat exchangers increases heat transfer', 'Turbulence in rivers mixes oxygen into water for aquatic life', 'Dimples on golf balls cause controlled turbulence to reduce drag', 'Mixing of fuel and air in combustion engines'])],
               [('Bozeman Viscosity', 'Viscosity, laminar and turbulent flow', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Real Fluids', 'Viscosity and Reynolds number', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Viscous flow has a parabolic velocity profile; center fastest.',
                'Q ∝ r⁴ — small radius changes greatly affect flow rate.',
                'High Reynolds number predicts turbulent flow.']),

            _l('Fluid Dynamics Applications and Problem Solving',
               [_t('Combined Bernoulli and Continuity', 'Most AP® fluid dynamics problems combine both equations. Set up Bernoulli between two points, use continuity to find unknown speeds, then solve for pressure or height.', 'Students often forget to use continuity to find v₂ before applying Bernoulli.', 'Multi-step AP® free-response combining both equations.'),
                _t('Fluid Dynamics in the Human Body', 'Blood flow obeys continuity (A₁v₁ = A₂v₂) in the circulatory system; blood pressure varies with height in the body (P = P₀ + ρgh); heart acts as a pressure pump.', 'Blood pressure at the feet is higher than at the heart due to the added hydrostatic column.', 'Apply fluid principles to physiological contexts.'),
                _t('Environmental Fluid Dynamics', 'Wind speed over hills, ocean currents, and river flow all follow fluid principles. Faster wind over a hill → lower pressure → can affect structures (roof lift).', 'Atmospheric flow is more complex than ideal fluid; Bernoulli is approximate.', 'Qualitative application of Bernoulli to wind and weather.')],
               [('Pressure head', 'ρgh term in Bernoulli; hydrostatic contribution to pressure'),
                ('Stagnation point', 'Point where fluid velocity is zero; maximum pressure'),
                ('Efflux', 'Fluid exiting a container through an opening'),
                ('Circulatory system', 'Closed-loop fluid system; obeys continuity and pressure'),
                ('Draft', 'Low-pressure region created by fast-moving fluid (Bernoulli)')],
               ['Combine continuity and Bernoulli to solve multi-step problems.',
                'Apply fluid principles to the circulatory system.',
                'Explain qualitatively how wind creates lift on rooftops.'],
               ['Multi-part free-response combining continuity and Bernoulli.',
                'Calculation of blood pressure at foot level given heart-level pressure.',
                'Multiple choice on environmental Bernoulli applications.'],
               ['Solve 3–4 multi-step pipe problems from past AP® exams.',
                'Calculate blood pressure changes due to body position.'],
               [('Water flows from a large tank through a horizontal pipe. Tank depth h = 4 m, pipe radius r = 0.03 m. Find the flow rate out. (ρ = 1000 kg/m³)', ['Torricelli: v = √(2gh) = √(2 × 9.8 × 4) = √78.4 ≈ 8.85 m/s', 'A = π r² = π(0.03)² = 2.83 × 10⁻³ m²', 'Q = Av = 2.83 × 10⁻³ × 8.85 ≈ 0.025 m³/s', 'Q ≈ 25 L/s']),
                ('Blood pressure at heart level is 120 mmHg systolic. Estimate blood pressure at foot level (1.4 m below heart). (ρ_blood = 1060 kg/m³)', ['ΔP = ρgh = 1060 × 9.8 × 1.4 = 14 543 Pa', 'In mmHg: 14 543 / 133.3 ≈ 109 mmHg', 'Foot pressure ≈ 120 + 109 = 229 mmHg systolic', 'This is why people with poor circulation have leg swelling']),
                ('A roof panel is 10 m × 5 m. Wind blows at 30 m/s above roof; assume 0 m/s below. Find net upward force. (ρ_air = 1.2 kg/m³)', ['Bernoulli: P_below - P_above = ½ρ_air × v²_above', 'ΔP = ½(1.2)(30²) = ½(1.2)(900) = 540 Pa', 'F = ΔP × A = 540 × 50 = 27 000 N = 27 kN', 'Strong winds can lift roofs — this is how tornadoes damage houses']),
                ('Explain the siphon: water flows upward over a barrier then downward out.', ['Siphon works by Bernoulli + pressure considerations', 'Once started, atmospheric pressure pushes water up into the tube', 'Water flows because output end is lower — gravity drives flow', 'Siphon fails when height exceeds ~10 m (atmospheric pressure limit)']),
                ('Two points in a horizontal pipe: P₁ = 200 kPa, v₁ = 3 m/s, A₁ = 0.02 m². At point 2, A₂ = 0.008 m². Find P₂.', ['v₂ = v₁(A₁/A₂) = 3(0.02/0.008) = 7.5 m/s (continuity)', 'Bernoulli: P₂ = P₁ + ½ρ(v₁² - v₂²)', 'P₂ = 200 000 + ½(1000)(9 - 56.25)', 'P₂ = 200 000 - 23 625 = 176 375 Pa ≈ 176 kPa'])],
               [('Bozeman Bernoulli Applications', 'Multi-step fluid dynamics problems', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Fluid Problems', 'Combined continuity and Bernoulli problems', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Combine continuity (find v₂) then apply Bernoulli.',
                'Blood pressure increases below heart level by ρgh.',
                'Wind over a surface creates upward pressure force via Bernoulli.'])
        ],
        'unit_qs': [
            ('Water flows in a pipe: A₁ = 0.05 m², v₁ = 1.5 m/s, P₁ = 180 kPa. Pipe narrows to A₂ = 0.015 m² at the same height. Find v₂ and P₂.',
             ['v₂ = v₁(A₁/A₂) = 1.5(0.05/0.015) = 5.0 m/s', 'Bernoulli: P₂ = P₁ + ½ρ(v₁² - v₂²)', 'P₂ = 180 000 + ½(1000)(2.25 - 25) = 180 000 - 11 375', 'P₂ = 168 625 Pa ≈ 169 kPa']),
            ('Explain Torricelli\'s theorem and derive v = √(2gh) using Bernoulli\'s equation.',
             ['Apply Bernoulli at the tank surface (point 1) and the hole (point 2)', 'P₁ = P₂ = atmospheric (both open to air); h₁ = h, h₂ = 0; v₁ ≈ 0', 'ρgh + 0 = 0 + ½ρv₂² → v₂ = √(2gh)', 'Same result as free-fall from height h']),
            ('An ideal fluid flows through a pipe that rises 3 m. At the lower section: P₁ = 250 kPa, v₁ = 2 m/s, A₁ = 0.04 m². At the upper section A₂ = 0.04 m². Find P₂.',
             ['Same area → same speed (continuity): v₂ = v₁ = 2 m/s', 'Bernoulli: P₁ + ½ρv₁² + ρgh₁ = P₂ + ½ρv₂² + ρgh₂', 'P₂ = P₁ - ρg(h₂ - h₁) = 250 000 - 1000(9.8)(3)', 'P₂ = 250 000 - 29 400 = 220 600 Pa ≈ 221 kPa']),
            ('An artery narrows from radius 0.4 cm to 0.1 cm due to plaque. Blood velocity before is 0.3 m/s. Find velocity and pressure drop in the narrowed section. (ρ_blood = 1060 kg/m³)',
             ['A₁/A₂ = (r₁/r₂)² = (0.4/0.1)² = 16; v₂ = 16 × 0.3 = 4.8 m/s', 'ΔP = ½ρ(v₂² - v₁²) = ½(1060)(23.04 - 0.09)', 'ΔP = 530 × 22.95 = 12 164 Pa ≈ 12.2 kPa ≈ 91 mmHg', 'Significant pressure drop — heart must work harder']),
            ('Compare streamlines of flow through a converging pipe. Where are they denser and what does that indicate?',
             ['Streamlines are closer together in the narrower section', 'Denser streamlines indicate higher fluid speed', 'Speed increases as area decreases (continuity)', 'This visual representation is used in CFD simulations']),
            ('A liquid exits a tank through a hole 5 m below the surface. Find efflux speed and the horizontal range if the hole is 2 m above the ground.',
             ['v = √(2gh) = √(2 × 9.8 × 5) = √98 ≈ 9.9 m/s (horizontal)', 'Projectile from h = 2 m: t = √(2h/g) = √(2×2/9.8) ≈ 0.639 s', 'Range = v × t = 9.9 × 0.639 ≈ 6.3 m', 'Classic Torricelli projectile problem']),
            ('Why is Bernoulli\'s equation limited to streamlines and ideal fluids? Describe two real-world complications.',
             ['Bernoulli assumes no viscosity (no energy loss) — violated in real fluids', 'Assumes steady flow — turbulent flow violates this assumption', 'Real complication 1: viscosity dissipates energy as heat (Poiseuille loss)', 'Real complication 2: flow separation and turbulence around sharp corners']),
            ('A Venturi meter has pipe area 0.02 m² and throat area 0.005 m². The pressure difference is 8000 Pa. Find the flow rate. (ρ = 1000 kg/m³)',
             ['Continuity: v₂ = v₁ × (A₁/A₂) = 4v₁', 'Bernoulli: ΔP = ½ρ(v₂² - v₁²) = ½ρ(16v₁² - v₁²) = 7.5ρv₁²', 'v₁ = √(ΔP/(7.5ρ)) = √(8000/7500) = √1.067 ≈ 1.033 m/s', 'Q = A₁v₁ = 0.02 × 1.033 ≈ 0.0207 m³/s']),
            ('How does a spray atomizer (perfume bottle) use Bernoulli\'s principle?',
             ['Squeezing bulb forces air rapidly across the top of a narrow tube', 'Fast-moving air has lower pressure (Bernoulli)', 'Atmospheric pressure below pushes liquid up the tube', 'Liquid meets the fast air stream and is atomized into fine droplets']),
            ('Describe the velocity profile in a viscous pipe and contrast it with ideal flow.',
             ['Ideal flow: uniform (plug) velocity across entire cross-section', 'Viscous flow: parabolic profile — maximum at center, zero at walls', 'No-slip condition: fluid velocity = 0 at pipe wall', 'Average velocity in viscous flow is half the centerline maximum velocity'])
        ],
    'review_video': 'https://www.youtube.com/watch?v=Hn7IIBHXN3U',
    },

    {
        'num': 13, 'title': 'Thermodynamics',
        'file': 'ap-physics-1-2-13-physics-2-unit-6-waves-sound-and-modern-physics-connections.html',
        'desc': 'Temperature, heat transfer, thermal energy, and the laws of thermodynamics.',
        'gateway': [
            'Distinguish temperature from thermal energy and heat.',
            'Apply the laws of thermodynamics to thermal processes.',
            'Calculate heat transfer using specific heat and latent heat.',
            'Explain entropy and the direction of natural processes.',
        ],
        'lessons': [
            _l('Temperature, Thermal Energy, and Heat',
               [_t('Temperature and Thermal Energy', 'Temperature is a measure of average kinetic energy of particles; thermal energy (internal energy) is the total kinetic energy of all particles. They are related but not the same.', 'A large cold object can have more thermal energy than a small hot object.', 'Distinguish temperature from thermal energy in conceptual questions.'),
                _t('Heat Transfer', 'Heat Q is energy transferred between objects due to a temperature difference. Q flows from hot to cold until thermal equilibrium is reached. Sign convention: Q > 0 means heat added to the system.', 'Heat is a transfer of energy, not a substance — objects don\'t "contain heat."', 'Apply sign conventions for heat in thermodynamics problems.'),
                _t('Thermal Equilibrium and the Zeroth Law', 'Two objects in thermal contact reach equilibrium when temperatures equalize. Zeroth Law: if A is in equilibrium with C, and B is with C, then A and B are in equilibrium with each other.', 'Thermal equilibrium means no heat flows — temperatures are equal, not necessarily energies.', 'Apply the zeroth law to thermometry and calibration.')],
               [('Temperature', 'Measure of average random kinetic energy of particles'),
                ('Thermal energy', 'Total internal kinetic energy of all particles in a substance'),
                ('Heat Q', 'Energy transferred due to temperature difference (J)'),
                ('Thermal equilibrium', 'State when no heat flows; temperatures are equal'),
                ('Zeroth law', 'Two objects each in equilibrium with a third are in equilibrium with each other')],
               ['Distinguish temperature, thermal energy, and heat.',
                'Apply the sign convention for heat (Q > 0 = added to system).',
                'State and apply the zeroth law of thermodynamics.'],
               ['Multiple choice distinguishing temperature from thermal energy.',
                'Conceptual: explain which object has more thermal energy.',
                'Free-response: apply zeroth law to thermometer calibration.'],
               ['Practice distinguishing thermal energy from temperature in examples.',
                'Solve mixing problems using Q_lost = Q_gained.'],
               [('Is it possible for a large block of ice to have more thermal energy than a small flame? Explain.', ['Yes — thermal energy depends on total number of particles and temperature', 'A massive ice block has many particles even at low temperature', 'Thermal energy = N × (average KE per particle)', 'The flame has higher temperature but fewer particles, so less total energy']),
                ('Heat flows from a hot cup of tea at 90°C to a room at 22°C. What happens when they reach equilibrium?', ['Heat flows from high T to low T: tea → room', 'Equilibrium: both reach same temperature (slightly above 22°C)', 'Tea loses thermal energy; room gains thermal energy', 'Heat flow stops when ΔT = 0']),
                ('State the zeroth law and explain its importance in thermometry.', ['Zeroth law: if A↔C and B↔C then A↔B (thermal equilibrium is transitive)', 'This allows a thermometer to measure temperature: T_object = T_thermometer', 'Without zeroth law, temperature scales would not be self-consistent', 'It is the logical basis for all temperature measurement']),
                ('A 2 kg block of steel at 100°C is placed in 5 kg of water at 20°C. In which direction does heat flow initially?', ['Heat flows from steel (100°C) to water (20°C)', 'Steel is at higher temperature → gives up heat', 'Water is at lower temperature → receives heat', 'Process continues until they reach the same equilibrium temperature']),
                ('Distinguish between temperature and heat.', ['Temperature: property of an object (measure of avg KE)', 'Heat: energy in transit due to temperature difference', 'Objects have temperature; heat exists only during transfer', 'After transfer ends, the energy is internal energy, not "heat"'])],
               [('Bozeman Temperature and Heat', 'Temperature vs. thermal energy vs. heat', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Heat Transfer', 'Heat flow and thermal equilibrium', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Temperature ≠ thermal energy; heat is energy in transit.',
                'Heat flows from hot to cold until thermal equilibrium.',
                'Zeroth law: basis of thermometry.']),

            _l('Specific Heat and Calorimetry',
               [_t('Specific Heat Capacity', 'Q = mcΔT; specific heat c (J/kg·K) is the heat per unit mass per degree. Water has an unusually high specific heat (4186 J/kg·K).', 'The "c" in Q = mcΔT is specific heat, not the speed of light.', 'Calculate heat added or removed using Q = mcΔT.'),
                _t('Calorimetry', 'In a calorimeter, heat lost by hot object = heat gained by cold object: m₁c₁ΔT₁ = m₂c₂ΔT₂. This assumes no heat escapes.', 'The heat equation uses |ΔT| or sets Q_lost negative and Q_gained positive — don\'t double-sign.', 'Solve mixing calorimetry problems to find equilibrium temperature.'),
                _t('Latent Heat and Phase Changes', 'During a phase change, temperature is constant; heat is used to change phase: Q = mL. L_fusion (melting) and L_vaporization (boiling) are tabulated values.', 'During a phase change, adding heat does NOT raise temperature — it converts phase.', 'Calculate heat required for phase change using Q = mL.')],
               [('Specific heat c', 'Heat per unit mass per unit temperature change (J/kg·K)'),
                ('Calorimetry', 'Measuring heat exchange using Q_lost = Q_gained'),
                ('Latent heat L', 'Heat per unit mass during a phase change (J/kg)'),
                ('Phase change', 'Melting, freezing, evaporation, or condensation at constant T'),
                ('Q = mcΔT', 'Heat for temperature change; Q = mL for phase change')],
               ['Calculate heat transfer using Q = mcΔT.',
                'Solve calorimetry problems for equilibrium temperature.',
                'Calculate heat for phase changes using Q = mL.'],
               ['Multiple choice: find equilibrium temperature of two mixed materials.',
                'Multi-step calculation combining temperature change and phase change.',
                'Free-response: design a calorimetry experiment.'],
               ['Practice calorimetry problems with different materials.',
                'Calculate total heat to convert ice at −20°C to steam at 120°C.'],
               [('How much heat is needed to raise 2 kg of water from 20°C to 80°C? (c_water = 4186 J/kg·K)', ['Q = mcΔT = 2 × 4186 × 60', 'Q = 502 320 J ≈ 502 kJ', 'ΔT = 80 - 20 = 60°C = 60 K', 'Large c of water means significant energy is needed']),
                ('A 0.5 kg piece of iron (c = 450 J/kg·K) at 200°C is placed in 2 kg of water at 25°C. Find equilibrium temperature.', ['Heat lost by iron = heat gained by water', '0.5(450)(200 - T) = 2(4186)(T - 25)', '22 500 - 225T = 8372T - 209 300', '231 800 = 8597T → T ≈ 26.96°C ≈ 27°C', 'Water barely changes because its heat capacity is much larger']),
                ('How much heat is required to melt 3 kg of ice at 0°C? (L_fusion = 334 000 J/kg)', ['Q = mL = 3 × 334 000 = 1 002 000 J = 1.0 MJ', 'Temperature remains at 0°C throughout the melting', 'This heat breaks intermolecular bonds in ice', 'After melting, further heat raises water temperature']),
                ('Why does water have such a significant effect on climate regulation?', ['Water has the highest specific heat of common substances (4186 J/kg·K)', 'Oceans absorb large amounts of heat with small temperature change', 'Moderates coastal climates — warms slowly, cools slowly', 'High latent heat of vaporization also regulates evaporation cooling']),
                ('How much total heat is needed to convert 1 kg of ice at −10°C to steam at 100°C? (c_ice = 2090, L_f = 334 000, c_water = 4186, L_v = 2 260 000 J/kg·K)', ['Step 1: warm ice: Q₁ = 1(2090)(10) = 20 900 J', 'Step 2: melt ice: Q₂ = 1(334 000) = 334 000 J', 'Step 3: warm water: Q₃ = 1(4186)(100) = 418 600 J', 'Step 4: boil water: Q₄ = 1(2 260 000) = 2 260 000 J; Total ≈ 3.03 MJ'])],
               [('Bozeman Specific Heat', 'Q = mcΔT and calorimetry', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Calorimetry', 'Heat exchange and equilibrium temperature', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Q = mcΔT for temperature change; Q = mL for phase change.',
                'Calorimetry: Q_lost = Q_gained at thermal equilibrium.',
                'During phase changes, temperature is constant.']),

            _l('Laws of Thermodynamics',
               [_t('First Law: Energy Conservation', 'ΔU = Q - W; change in internal energy equals heat added minus work done by the system. Energy is conserved in all thermal processes.', 'W is work done BY the system; if system is compressed (work done ON it), W is negative.', 'Apply ΔU = Q - W to thermodynamic processes.'),
                _t('Second Law: Direction of Heat Flow', 'Heat spontaneously flows from hot to cold, never the reverse. Entropy (disorder) of an isolated system always increases or stays the same.', 'The second law doesn\'t say heat can never flow from cold to hot—it says it can\'t do so spontaneously without work input (refrigerators need work).', 'Identify processes that violate the second law.'),
                _t('Heat Engines and Efficiency', 'A heat engine converts heat from a hot reservoir to work, rejecting waste heat to a cold reservoir. Efficiency e = W/Q_H ≤ 1 - T_C/T_H (Carnot limit).', 'No heat engine can be 100% efficient — the Carnot efficiency is the theoretical maximum.', 'Calculate efficiency of heat engines and identify Carnot limit.')],
               [('First law of thermodynamics', 'ΔU = Q − W; energy conservation for thermal systems'),
                ('Second law of thermodynamics', 'Entropy of isolated systems never decreases; heat flows hot → cold'),
                ('Entropy S', 'Measure of disorder or number of microstates in a system'),
                ('Heat engine', 'Device converting heat to work with efficiency ≤ Carnot'),
                ('Carnot efficiency', 'e_Carnot = 1 − T_C/T_H; maximum possible efficiency (temperatures in Kelvin)')],
               ['Apply the first law ΔU = Q - W to thermal processes.',
                'State the second law and identify forbidden processes.',
                'Calculate heat engine efficiency and compare to Carnot limit.'],
               ['Multiple choice: identify which process violates the second law.',
                'Calculation of Carnot efficiency given reservoir temperatures.',
                'Free-response: apply first and second laws to a cyclic process.'],
               ['Practice ΔU = Q - W with signs for various processes.',
                'Calculate efficiencies for engines and compare to Carnot maximum.'],
               [('A gas absorbs 500 J of heat and does 200 J of work. Find the change in internal energy.', ['ΔU = Q - W = 500 - 200 = 300 J', 'Internal energy increases by 300 J', 'Q > 0: heat added; W > 0: work done by gas', 'Energy is conserved: 500 J in = 200 J out (work) + 300 J stored']),
                ('A heat engine operates between 600 K and 300 K. What is the maximum (Carnot) efficiency?', ['e_Carnot = 1 - T_C/T_H = 1 - 300/600 = 1 - 0.5 = 0.50 = 50%', 'No real engine can exceed 50% efficiency with these reservoirs', 'Higher temperature difference → higher Carnot efficiency', 'T must be in Kelvin for this formula']),
                ('Identify which of the following violates the second law: (a) heat flows hot → cold; (b) a room spontaneously becomes colder while surrounding air warms.', ['(a) Heat from hot to cold: allowed — this is what the second law says happens', '(b) Spontaneous heat flow cold → hot without work: violates second law', 'Second law: entropy of isolated system cannot decrease spontaneously', 'A refrigerator moves heat cold → hot but requires work input']),
                ('A heat engine absorbs 1000 J from a hot reservoir and exhausts 600 J. Find efficiency and work output.', ['W = Q_H - Q_C = 1000 - 600 = 400 J', 'e = W/Q_H = 400/1000 = 0.40 = 40%', 'Compare to Carnot: actual efficiency ≤ Carnot efficiency', 'This engine is not 100% efficient (second law forbids it)']),
                ('Explain entropy in terms of everyday experience.', ['Entropy measures disorder or number of possible arrangements of particles', 'Broken eggs don\'t spontaneously reassemble (entropy would decrease)', 'Heat spreads from hot to cold — more disordered final state', 'Nature evolves toward more probable (higher entropy) states'])],
               [('Bozeman Laws of Thermodynamics', 'First and second laws, entropy, heat engines', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics First Law', 'ΔU = Q - W applications', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['ΔU = Q - W; energy conserved in all thermal processes.',
                'Second law: entropy increases; heat flows hot to cold spontaneously.',
                'Carnot efficiency = 1 - T_C/T_H (max possible).']),

            _l('Heat Transfer Mechanisms',
               [_t('Conduction', 'Conduction is heat transfer through direct particle collisions in a material. Rate ∝ k × A × ΔT / L (Fourier\'s law); k is thermal conductivity.', 'Metals conduct heat well not because they are "cold" but because free electrons transfer energy rapidly.', 'Rank materials by thermal conductivity and explain insulation.'),
                _t('Convection', 'Convection transfers heat via bulk fluid motion; hot fluid rises (less dense), cool fluid sinks, creating convection currents. Natural and forced convection both occur.', 'Convection requires a fluid — it cannot occur in solids or a vacuum.', 'Explain convection currents qualitatively in weather or heating systems.'),
                _t('Radiation', 'All objects emit electromagnetic radiation proportional to T⁴ (Stefan-Boltzmann law: P = εσAT⁴). Radiation requires no medium — it travels through vacuum.', 'All objects above absolute zero emit thermal radiation — even cold objects, just less.', 'Compare radiation rates for objects at different temperatures.')],
               [('Thermal conductivity k', 'Material property determining heat conduction rate'),
                ('Convection', 'Heat transfer by bulk fluid motion; hot fluid rises'),
                ('Radiation', 'Heat transfer by electromagnetic waves; requires no medium'),
                ('Stefan-Boltzmann law', 'P = εσAT⁴; radiated power depends strongly on temperature'),
                ('Emissivity ε', 'Ratio of actual radiation to blackbody radiation (0 to 1)')],
               ['Compare conduction, convection, and radiation mechanisms.',
                'Explain convection currents in weather and building heating.',
                'Apply Stefan-Boltzmann law qualitatively to radiation problems.'],
               ['Multiple choice comparing heat transfer mechanisms.',
                'Conceptual: identify which mechanism dominates in a given scenario.',
                'Free-response: explain why a thermos bottle uses vacuum insulation.'],
               ['List everyday examples of each heat transfer mechanism.',
                'Explain why a fan makes you feel cooler (forced convection).'],
               [('Explain how a thermos bottle minimizes all three heat transfer mechanisms.', ['Double-wall vacuum eliminates convection (no fluid) and conduction (no medium)', 'Silvered walls minimize radiation (reflect infrared, high reflectance = low emissivity)', 'Vacuum: no air to conduct or convect heat', 'All three mechanisms are simultaneously reduced']),
                ('Why do metals feel colder than wood at the same temperature?', ['Metals have high thermal conductivity — they conduct heat away from skin rapidly', 'Wood has low thermal conductivity — heat transfer to skin is slow', 'Both are at room temperature, but heat flows out faster from skin to metal', 'Sensation of "cold" is determined by heat flow rate, not object temperature']),
                ('How does the greenhouse effect relate to radiation?', ['Sun emits short-wavelength radiation that passes through the atmosphere', 'Earth re-emits longer-wavelength (infrared) radiation', 'Greenhouse gases absorb and re-emit this IR, trapping heat near the surface', 'Net effect: Earth\'s surface is warmer than it would be without greenhouse gases']),
                ('A body at 400 K radiates 4 times as much power as the same body at 200 K. Explain why.', ['Stefan-Boltzmann: P = εσAT⁴; P ∝ T⁴', 'P₁/P₂ = (T₁/T₂)⁴ = (400/200)⁴ = 2⁴ = 16', 'The body at 400 K radiates 16× more power, not 4×', 'The T⁴ dependence makes radiation very sensitive to temperature']),
                ('Explain how convection currents drive weather patterns.', ['Solar heating warms equatorial air → air expands, becomes less dense, rises', 'Cooler polar air is denser → sinks and flows toward equator', 'This creates global convection cells (Hadley cells)', 'Coriolis effect + these cells produce trade winds and jet streams'])],
               [('Bozeman Heat Transfer', 'Conduction, convection, and radiation compared', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Radiation', 'Stefan-Boltzmann law and thermal radiation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Conduction: direct contact; Convection: fluid motion; Radiation: EM waves.',
                'Radiation: P = εσAT⁴; doubles T → 16× power.',
                'Vacuum eliminates conduction and convection; silvered walls reduce radiation.'])
        ],
        'unit_qs': [
            ('A 3 kg block of aluminum (c = 900 J/kg·K) cools from 150°C to 30°C. How much heat is released?',
             ['Q = mcΔT = 3 × 900 × (150 - 30) = 3 × 900 × 120', 'Q = 324 000 J = 324 kJ released by aluminum', 'ΔT = 120°C = 120 K', 'Heat released = heat absorbed by surroundings']),
            ('A gas is compressed (work done ON it = 300 J) and releases 150 J of heat. Find ΔU.',
             ['Work done BY system = -300 J (work done on system)', 'Q = -150 J (heat released by system)', 'ΔU = Q - W = -150 - (-300) = -150 + 300 = 150 J', 'Internal energy increases by 150 J despite releasing heat']),
            ('Calculate the Carnot efficiency for a heat engine operating between 800 K and 400 K.',
             ['e_Carnot = 1 - T_C/T_H = 1 - 400/800 = 1 - 0.5 = 0.50', 'Maximum efficiency is 50%', 'No real engine can exceed this value', 'To improve efficiency, increase T_H or decrease T_C']),
            ('Ice (0.5 kg) at 0°C is mixed with water (2 kg) at 80°C. Will all the ice melt? Find equilibrium temperature. (L_f = 334 000 J/kg, c_water = 4186 J/kg·K)',
             ['Heat available from water cooling to 0°C: Q = 2(4186)(80) = 669 760 J', 'Heat to melt all ice: Q = 0.5(334 000) = 167 000 J', '167 000 < 669 760, so all ice melts', 'After melting: 669 760 - 167 000 = 502 760 J warms 2.5 kg water; T = 502 760/(2.5 × 4186) ≈ 48°C']),
            ('Rank conduction, convection, and radiation by whether they require a material medium.',
             ['Conduction: requires material medium (direct particle contact)', 'Convection: requires fluid medium (liquid or gas)', 'Radiation: requires NO medium — travels through vacuum', 'Only radiation can transfer heat across space (e.g., from Sun to Earth)']),
            ('State the second law of thermodynamics and give one example of a process it forbids.',
             ['Second law: entropy of an isolated system never decreases', 'Heat never spontaneously flows from cold to hot', 'Forbidden: a cup of water spontaneously becoming partly ice and partly boiling water', 'Another: a broken glass spontaneously reassembling — entropy would decrease']),
            ('A metal rod (k = 50 W/m·K, L = 0.5 m, A = 0.01 m²) connects a 300°C source to a 20°C sink. Find the heat flow rate.',
             ['Q/t = kAΔT/L = 50 × 0.01 × (300 - 20) / 0.5', 'Q/t = 50 × 0.01 × 280 / 0.5 = 50 × 0.01 × 560', 'Q/t = 280 W', 'Higher conductivity, area, or ΔT all increase heat flow rate']),
            ('An object at 600 K radiates with emissivity 0.8 and area 0.05 m². Find radiated power. (σ = 5.67 × 10⁻⁸ W/m²·K⁴)',
             ['P = εσAT⁴ = 0.8 × 5.67 × 10⁻⁸ × 0.05 × (600)⁴', '(600)⁴ = 1.296 × 10¹¹', 'P = 0.8 × 5.67 × 10⁻⁸ × 0.05 × 1.296 × 10¹¹', 'P = 0.8 × 5.67 × 0.05 × 12960 ≈ 2940 W ≈ 2.94 kW']),
            ('Explain why sweating cools the human body using thermodynamics concepts.',
             ['Sweat evaporates from skin surface → phase change (liquid to gas)', 'Evaporation requires latent heat of vaporization (≈ 2.43 MJ/kg for water)', 'This latent heat comes from body surface, cooling the skin', 'Forced convection (wind) speeds evaporation → greater cooling']),
            ('A heat engine absorbs 2000 J from a hot reservoir at 500 K and rejects heat to a cold reservoir at 250 K. If it operates at 80% of Carnot efficiency, find W and Q_C.',
             ['e_Carnot = 1 - 250/500 = 0.50; actual e = 0.80 × 0.50 = 0.40', 'W = e × Q_H = 0.40 × 2000 = 800 J', 'Q_C = Q_H - W = 2000 - 800 = 1200 J rejected', 'Even at 80% of Carnot, 60% of input heat becomes waste'])
        ],
    'review_video': 'https://www.youtube.com/watch?v=Hn7IIBHXN3U',
    },
]
