NAME = 'AP® Physics 1 & 2'
ABBREV = 'phys12'
SLUG = 'ap-physics-1-2'
COURSE_FILE = 'ap-physics-1-2.html'
ACCENT_COLOR = '#34d399'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+1+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+1+'

COURSE_QS = [
    ('Newton\'s second law states that the net force on an object equals',
     'the product of its mass and acceleration: F_net = ma',
     ['the product of its weight and velocity', 'the change in momentum over time (impulse)', 'the sum of all individual forces acting on it (they are the same thing, but this answer is incomplete without the "net" part)']),
    ('The work-energy theorem states that the net work done on an object equals',
     'the change in the object\'s kinetic energy: W_net = ΔKE',
     ['the object\'s total mechanical energy', 'the product of force and mass', 'the change in potential energy']),
    ('Conservation of momentum applies when',
     'the net external force on the system is zero (closed, isolated system)',
     ['kinetic energy is conserved', 'the objects are in contact', 'gravitational potential energy is neglected']),
    ('A wave\'s frequency and period are related by',
     'f = 1/T — frequency is the reciprocal of the period',
     ['f = T × wavelength', 'f = T/2 for mechanical waves', 'f = T × wave speed']),
    ('In simple harmonic motion, the restoring force is',
     'proportional to and directed opposite to the displacement from equilibrium',
     ['constant regardless of displacement', 'proportional to velocity', 'directed toward maximum displacement']),
    ('Torque is defined as',
     'τ = r × F sin θ — the product of the force, the lever arm, and the sine of the angle between them',
     ['τ = mass × angular acceleration only', 'τ = F/r (force divided by radius)', 'τ = mass × velocity × radius']),
    ('Bernoulli\'s principle states that in a flowing fluid,',
     'as fluid speed increases, pressure decreases (energy conservation in fluid flow)',
     ['pressure is constant throughout any closed pipe', 'faster flow always creates more turbulence', 'fluid speed is inversely proportional to density']),
    ('Electric potential (voltage) is defined as',
     'the electric potential energy per unit charge at a given point: V = U/q',
     ['the force per unit charge (that\'s electric field)', 'charge divided by capacitance', 'power divided by current']),
    ('Ohm\'s Law states',
     'V = IR — voltage equals current times resistance',
     ['P = IV (that\'s power)', 'R = V × I', 'I = V × R']),
    ('In a parallel circuit, the voltage across each branch is',
     'equal to the voltage of the source (same across all branches)',
     ['divided equally among the branches', 'proportional to each branch\'s resistance', 'zero for all but the branch with least resistance']),
    ('The magnitude of the electric force between two point charges is given by',
     'Coulomb\'s Law: F = kq₁q₂/r², proportional to the product of charges and inversely proportional to distance squared',
     ['F = q₁q₂ × r²', 'F = kq/r (analogous to gravity with mass)', 'F = qE for charges at rest']),
    ('The direction of the magnetic force on a positive charge moving in a magnetic field is given by',
     'the right-hand rule: F = qv × B (perpendicular to both v and B)',
     ['parallel to the magnetic field', 'opposite to the charge\'s velocity', 'always toward the north pole']),
    ('Electromagnetic induction (Faraday\'s Law) states that an EMF is induced in a loop when',
     'the magnetic flux through the loop changes over time: ε = −dΦ_B/dt',
     ['a current flows through the wire', 'the magnetic field is constant but strong', 'the loop moves at constant velocity in a uniform field']),
    ('The index of refraction n of a material is defined as',
     'n = c/v — the ratio of the speed of light in vacuum to the speed in the material',
     ['n = v/c (speed in material divided by c)', 'n = wavelength in vacuum / wavelength in medium', 'n = frequency × wavelength in medium']),
    ('In a converging (convex) lens, the focal length is',
     'the distance from the lens at which parallel rays converge to a focus',
     ['the distance from the object to the lens', 'the magnification times the object distance', 'negative for all converging lenses']),
    ('The first law of thermodynamics (energy conservation) states',
     'ΔU = Q − W: the change in internal energy equals heat added to the system minus work done by the system',
     ['the entropy of an isolated system always decreases', 'heat flows from cold to hot with added work', 'total energy = kinetic + potential at all times']),
    ('Projectile motion is analyzed by',
     'separating horizontal (constant velocity) and vertical (constant acceleration g downward) components independently',
     ['applying Newton\'s second law only vertically', 'treating the trajectory as a straight line at the launch angle', 'using the same equations for horizontal and vertical components']),
    ('Centripetal acceleration is directed',
     'toward the center of the circular path (inward)',
     ['tangent to the circular path', 'outward (centrifugal direction)', 'in the direction of velocity']),
    ('The period of a mass-spring system in simple harmonic motion is',
     'T = 2π√(m/k) — depends on mass and spring constant, not amplitude',
     ['T = 2π√(k/m)', 'T = 2π√(g/L)', 'T = 2π × amplitude']),
    ('Standing waves form in a medium when',
     'two waves of equal frequency and amplitude travel in opposite directions and interfere to create nodes and antinodes',
     ['a single wave reflects from a fixed end with no interference', 'the frequency equals the wave speed', 'the medium has no resistance to wave propagation']),
]

def _t(title, content, mis, tested):
    return {'title': title, 'content': content, 'misconception': mis, 'how_tested': tested}

def _l(title, topics, vocab, obj, ht, prac, qs, vids, exit_t):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': obj,
            'how_tested': ht, 'practice': prac, 'questions': qs, 'videos': vids, 'exit_ticket': exit_t}

UNITS = [
{
  'num': 1, 'title': 'Kinematics',
  'file': 'ap-physics-1-2-1-physics-1-unit-1-kinematics.html',
  'desc': 'Describe and analyze motion in one and two dimensions using kinematic equations and graphical representations.',
  'gateway': [
      'Distinguish displacement, velocity, and acceleration as vector quantities.',
      'Apply kinematic equations to constant-acceleration motion.',
      'Analyze position-time, velocity-time, and acceleration-time graphs.',
      'Solve projectile motion problems by decomposing into components.',
  ],
  'lessons': [
      _l('Describing Motion: Position, Velocity, Acceleration',
         [_t('Displacement vs. Distance', 'Displacement is the vector change in position (Δx = x_f − x_i); distance is the total path length (scalar). An object returning to its start has zero displacement but non-zero distance.', 'Students use distance and displacement interchangeably; only displacement is a vector and can be negative.', 'Given a position-time graph, identify intervals where displacement and distance differ.'),
          _t('Average vs. Instantaneous Velocity', 'Average velocity = Δx/Δt (slope of secant on x-t graph). Instantaneous velocity = slope of tangent on x-t graph. Speed = |velocity|.', 'Students think average speed equals average velocity; they agree only for constant-speed motion in one direction.', 'Calculate average velocity over an interval from a graph; estimate instantaneous velocity from tangent slope.'),
          _t('Acceleration', 'Acceleration a = Δv/Δt is the rate of change of velocity. Positive a does not always mean speeding up — an object moving in the negative direction with positive a is slowing down.', 'Students equate positive acceleration with speeding up; acceleration direction relative to velocity direction determines speeding up vs. slowing down.', 'From a v-t graph, identify where an object is speeding up, slowing down, and momentarily at rest.')],
         [('displacement', 'Vector change in position: Δx = x_f − x_i'),
          ('average velocity', 'v_avg = Δx/Δt; slope of secant on x-t graph'),
          ('instantaneous velocity', 'Slope of tangent on x-t graph at a specific moment'),
          ('acceleration', 'a = Δv/Δt; rate of change of velocity')],
         ['Compute displacement and distance from a path description', 'Read velocity and acceleration from kinematic graphs', 'Determine when an object is speeding up or slowing down'],
         ['Multiple representations tested: graphs, diagrams, equations', 'Graph interpretation in both MC and FR', 'Speeding up/slowing down reasoning required in FR justification'],
         ['Given an x-t graph, find average velocity from t=0 to t=4 s', 'From a v-t graph, identify when the object is at rest and when it is speeding up'],
         [('An object moves from x=2 m to x=−3 m then back to x=1 m. Find displacement and distance.', ['Displacement: Δx=1−2=−1 m', 'Distance: |−3−2|+|1−(−3)|=5+4=9 m', 'Displacement is signed (vector); distance is total path (scalar)', 'Different quantities with different meanings']),
          ('From an x-t graph, the position goes from 4 m at t=0 to −2 m at t=3 s. Find average velocity.', ['v_avg=Δx/Δt=(−2−4)/3=−6/3=−2 m/s', 'Negative sign indicates motion in negative direction', 'Average velocity is a vector quantity', 'Not the same as average speed unless motion is one-directional']),
          ('A v-t graph shows v going from +8 m/s to 0 to −4 m/s. When is the object speeding up?', ['From +8 to 0: decelerating (v and a have opposite signs)', 'From 0 to −4: velocity is negative and becoming more negative → speeding up in negative direction', 'Object is speeding up when v and a have same sign', 'Object is at rest instantaneously when v=0']),
          ('An object has a=−3 m/s² and v=−6 m/s. Is it speeding up or slowing down?', ['v and a both negative → same direction', 'Speed = |v| is increasing', 'Object is speeding up', 'Positive a with negative v would be slowing down']),
          ('Sketch an x-t graph for: moving right at constant velocity, then stopping, then moving left faster.', ['Right at constant v: positive slope line', 'Stopping: flat horizontal segment', 'Moving left faster: steeper negative slope line', 'Slope = velocity throughout'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Kinematics Overview', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the difference between displacement and distance', 'How do you find velocity from an x-t graph?', 'Explain when positive acceleration means slowing down']),

      _l('Kinematic Equations for Constant Acceleration',
         [_t('The Big Four Kinematic Equations', 'For constant acceleration: (1) v=v₀+at, (2) x=x₀+v₀t+½at², (3) v²=v₀²+2aΔx, (4) x=x₀+(v+v₀)/2·t. Choose the equation missing the unknown you do not need.', 'Students try to memorize all four; instead, identify which variable is missing (not given, not asked) and choose the equation without it.', 'Identify the given and unknown quantities, select the appropriate kinematic equation, and solve.'),
          _t('Free Fall', 'Near Earth\'s surface, all objects fall with a=−g=−9.8 m/s² (taking up as positive). Horizontal velocity is unaffected. Neglect air resistance unless stated.', 'Students use g=+9.8 m/s² without a sign convention and get wrong directions; always define a positive direction first.', 'Apply kinematic equations to free-fall problems with defined sign conventions.'),
          _t('Graphical Relationships', 'Slope of x-t graph = velocity. Slope of v-t graph = acceleration. Area under v-t graph = displacement. Area under a-t graph = Δv.', 'Students confuse slope and area; slope gives rate of change, area gives accumulated quantity.', 'Extract displacement and acceleration from v-t and a-t graphs using slope and area.')],
         [('kinematic equations', 'Four equations valid for constant-acceleration motion'),
          ('free fall', 'Motion under gravity alone; a=−9.8 m/s² (up positive)'),
          ('area under v-t graph', 'Equals displacement over that time interval'),
          ('slope of v-t graph', 'Equals acceleration at that moment')],
         ['Select and apply kinematic equations for given scenarios', 'Solve free-fall problems with correct sign conventions', 'Use graphical methods to find displacement and acceleration'],
         ['Kinematic equations tested in MC and FR', 'Graph area/slope questions appear frequently', 'Free-fall problems include vertical launch and dropped objects'],
         ['A ball is thrown upward at 15 m/s; find max height and time to return', 'From a v-t graph, find displacement from t=0 to t=5 s using area'],
         [('A car accelerates from rest at 4 m/s² for 5 s. Find final velocity and distance.', ['v=v₀+at=0+4(5)=20 m/s', 'x=v₀t+½at²=0+½(4)(25)=50 m', 'Or: v²=2ax → 400=2(4)x → x=50 m', 'Consistent results from multiple equations']),
          ('A ball is dropped from rest at h=20 m. Find time to hit ground (g=10 m/s²).', ['Take down as positive: a=10, x=20', '20=0+½(10)t² → t²=4 → t=2 s', 'Final velocity: v=gt=20 m/s downward', 'Or: v²=2(10)(20)=400 → v=20 m/s']),
          ('A ball thrown upward at 20 m/s. Find max height (g=10 m/s²).', ['At max height, v=0', 'v²=v₀²+2aΔy: 0=400+2(−10)Δy', 'Δy=400/20=20 m', 'Time to top: v=v₀+at → 0=20−10t → t=2 s']),
          ('From a v-t graph: v=0 at t=0, increases linearly to 12 m/s at t=4 s. Find displacement.', ['Area = triangle: ½·base·height=½(4)(12)=24 m', 'Also: avg velocity=(0+12)/2=6 m/s; x=6×4=24 m', 'Both methods give same result for constant acceleration', 'Slope: a=12/4=3 m/s²']),
          ('Two objects fall from rest, one from twice the height. What is the ratio of their speeds at impact?', ['v²=2gh; v∝√h', 'If h₂=2h₁: v₂/v₁=√(2h/h)=√2', 'Speed ratio is √2', 'Speed does not double when height doubles'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Kinematic Equations', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['List the four kinematic equations and identify each missing variable', 'Explain the sign convention for free fall', 'Find displacement from a v-t graph using area']),

      _l('Projectile Motion',
         [_t('Independence of Horizontal and Vertical Motion', 'A projectile has constant horizontal velocity (aₓ=0) and constant downward acceleration (aᵧ=−g). The two directions are completely independent.', 'Students think horizontal speed decreases during projectile flight; only air resistance (not gravity) affects horizontal velocity.', 'Decompose projectile motion into independent horizontal and vertical components; solve each separately.'),
          _t('Range and Time of Flight', 'Time of flight determined entirely by vertical component. Horizontal range R=vₓ·t. For symmetric launch/landing at same height: t=2v₀sin θ/g, R=v₀²sin(2θ)/g.', 'Students add horizontal and vertical components vectorially to find range; range is just vₓ × total time.', 'Calculate range, max height, and time of flight for angled projectiles.'),
          _t('Relative Velocity', 'Velocity of A relative to B = v_A − v_B. Used for boats crossing rivers, planes in wind. Add vectors using component method.', 'Students forget that relative velocity requires vector subtraction, not just magnitude comparison.', 'Find velocity of object A relative to reference frame B using vector addition/subtraction.')],
         [('projectile', 'Object launched with initial velocity and subject only to gravity'),
          ('horizontal component', 'v_x = v₀cos θ; constant throughout flight'),
          ('vertical component', 'v_y = v₀sin θ − gt; changes due to gravity'),
          ('range', 'Horizontal distance traveled during flight: R = v_x · t')],
         ['Decompose initial velocity into components', 'Find time of flight, max height, and range', 'Apply relative velocity for observers in different reference frames'],
         ['Projectile problems in FR require component decomposition explicitly shown', 'Range formula and angle-for-max-range tested in MC', 'Relative velocity in both MC and FR'],
         ['A ball launched at 30° above horizontal at 20 m/s; find range and max height', 'A boat can travel 5 m/s in still water; river flows at 3 m/s; find actual velocity'],
         [('A projectile is launched at v₀=20 m/s at θ=37° above horizontal. Find range (g=10 m/s²).', ['v_x=20cos37°=16 m/s; v_y0=20sin37°=12 m/s', 'Time of flight: 0=12t−5t² → t=0 or t=2.4 s', 'Range=v_x·t=16×2.4=38.4 m', 'Use t=2v_y0/g=2(12)/10=2.4 s']),
          ('Find max height of the previous projectile.', ['At max height, v_y=0', 'v_y²=v_y0²−2gΔy: 0=144−20Δy', 'Δy=7.2 m', 'Time to top: 12−10t=0 → t=1.2 s']),
          ('A ball is thrown horizontally at 10 m/s from a 45 m cliff. Find where it lands.', ['Vertical: 45=½(10)t² → t=3 s', 'Horizontal: x=10×3=30 m', 'Lands 30 m from base of cliff', 'Horizontal velocity unchanged; vertical component grows']),
          ('A boat travels at 8 m/s north; river flows 6 m/s east. Find actual velocity.', ['v = √(8²+6²)=√(64+36)=√100=10 m/s', 'Direction: θ=arctan(6/8)=37° east of north', 'Vector addition: v_actual=v_boat+v_river', 'Speed is 10 m/s at 37° east of north']),
          ('Why does increasing launch angle beyond 45° decrease range?', ['Range = v₀²sin(2θ)/g; max when sin(2θ)=1 → 2θ=90° → θ=45°', 'For θ>45°: 2θ>90°; sin(2θ) decreases', 'More vertical velocity means more air time but less horizontal speed', 'Same range for complementary angles: 30° and 60°'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Projectile Motion', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Explain why horizontal and vertical motions are independent', 'Calculate range of a projectile launched at 45°', 'Describe how relative velocity is computed vectorially']),

      _l('Circular Motion and Reference Frames',
         [_t('Uniform Circular Motion', 'An object moving at constant speed in a circle has centripetal acceleration a_c=v²/r directed toward the center. The net force equals ma_c=mv²/r (centripetal force).', 'Students think there is a centrifugal force pushing outward; in an inertial frame only the centripetal force (inward) exists. "Centrifugal force" is a fictitious force felt in the rotating frame.', 'Calculate centripetal acceleration and force for circular motion; identify the physical source of the centripetal force.'),
          _t('Period and Frequency', 'Period T = 2πr/v = time for one revolution. Frequency f = 1/T = revolutions per second (Hz). Speed v = 2πr/T = 2πrf.', 'Students confuse period with frequency; T is seconds per cycle, f is cycles per second.', 'Calculate T, f, and v for circular motion; convert between them.'),
          _t('Non-Uniform Circular Motion', 'If speed changes, there is a tangential component of acceleration in addition to the centripetal component. The net acceleration is the vector sum of centripetal and tangential.', 'Students add centripetal and tangential accelerations as scalars; they are perpendicular and must be added as vectors.', 'Identify when both centripetal and tangential acceleration are present and find their resultant.')],
         [('centripetal acceleration', 'a_c = v²/r directed toward center of circle'),
          ('centripetal force', 'Net inward force = mv²/r; provided by tension, gravity, friction, or normal force'),
          ('period', 'T = time for one full revolution; T = 2πr/v'),
          ('frequency', 'f = 1/T; revolutions per second')],
         ['Calculate centripetal acceleration and force for circular motion', 'Find period, frequency, and speed for circular motion', 'Identify the source of centripetal force in physical scenarios'],
         ['Centripetal force problems: identify source (tension, gravity, friction)', 'Period and frequency conversions in MC', 'Free-body diagrams for circular motion in FR'],
         ['Find centripetal acceleration of a 2 kg ball on a 0.5 m string at 4 m/s', 'A car rounds a curve of radius 40 m at 20 m/s; find centripetal acceleration and required friction'],
         [('A 0.5 kg ball on a 0.8 m string moves at 3 m/s. Find centripetal acceleration and tension.', ['a_c=v²/r=9/0.8=11.25 m/s²', 'T=ma_c=0.5×11.25=5.625 N', 'Tension provides centripetal force (horizontal circle)', 'Direction: toward center (inward)']),
          ('A car travels a circular curve of radius 50 m. If μ=0.4 and g=10 m/s², find max speed.', ['Friction provides centripetal force: f=μmg=mv²/r', 'μg=v²/r → v²=μgr=0.4×10×50=200', 'v=√200≈14.1 m/s', 'Maximum speed without sliding']),
          ('A satellite orbits Earth at radius r with period T. Express orbital speed.', ['v=circumference/period=2πr/T', 'Also: T=2πr/v', 'Period determines speed for given orbit radius', 'Longer orbit → slower speed (inverse relationship via gravity)']),
          ('A 1 kg object moves in a circle of radius 2 m. T=4 s. Find a_c.', ['v=2πr/T=2π(2)/4=π m/s', 'a_c=v²/r=π²/2≈4.9 m/s²', 'Or: a_c=(4π²r)/T²=4π²(2)/16=π²/2', 'Both methods consistent']),
          ('Why is centrifugal force considered fictitious in an inertial frame?', ['In an inertial frame, only real (contact and field) forces act', 'Centrifugal force appears in rotating reference frames as a pseudo-force', 'From inertial frame: object\'s inertia resists change in direction', 'The only real force is centripetal (inward)'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Circular Motion', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the formula for centripetal acceleration', 'Identify the physical source of centripetal force for a car on a curved road', 'Convert period T=0.25 s to frequency']),
  ],
  'unit_qs': [
      ('A car travels 60 km north then 80 km east. Find displacement magnitude.', ['Displacement: √(60²+80²)=√(3600+6400)=√10000=100 km', 'Direction: arctan(80/60)=53° east of north', 'Distance = 60+80=140 km', 'Displacement < distance']),
      ('A ball decelerates from 30 m/s to 0 in 6 s. Find acceleration and distance.', ['a=Δv/Δt=(0−30)/6=−5 m/s²', 'x=v₀t+½at²=30(6)+½(−5)(36)=180−90=90 m', 'Or: v²=v₀²+2ax → 0=900−10x → x=90 m', 'Deceleration is −5 m/s²']),
      ('A v-t graph shows constant v=5 m/s for 3 s, then linear decrease to −3 m/s over next 4 s. Find total displacement.', ['First segment: Δx₁=5×3=15 m', 'Second segment: area of trapezoid =(5+(−3))/2×4=4 m', 'Total displacement=15+4=19 m', 'Area below axis subtracts']),
      ('A ball is thrown horizontally at 15 m/s from 80 m height. Find time to land and range (g=10).', ['80=½(10)t² → t=4 s', 'Range=15×4=60 m', 'Horizontal velocity unchanged', 'Vertical free fall independent']),
      ('An object in circular motion has r=3 m and T=2π s. Find centripetal acceleration.', ['v=2πr/T=2π(3)/(2π)=3 m/s', 'a_c=v²/r=9/3=3 m/s²', 'Or: a_c=4π²r/T²=4π²(3)/(4π²)=3 m/s²', 'Centripetal acceleration=3 m/s²']),
      ('Explain why two balls dropped simultaneously from different heights do not land at the same time.', ['Both have same vertical acceleration (g)', 'Greater height means greater distance to fall', 'More distance requires more time: h=½gt²', 'Different heights → different times']),
      ('A car starts from rest and accelerates at 3 m/s² for 8 s. How far does it travel?', ['x=½at²=½(3)(64)=96 m', 'v_f=3×8=24 m/s', 'Check: v²=2ax=2(3)(96)=576=24²  ✓', 'Distance = 96 m']),
      ('A projectile has v_x=20 m/s and v_y=−15 m/s at some instant. Find speed and angle below horizontal.', ['Speed=√(400+225)=√625=25 m/s', 'Angle=arctan(15/20)=arctan(0.75)=36.9°', '36.9° below horizontal', 'Velocity vector points down and forward']),
      ('A 2 kg ball on a 1 m string swings in a vertical circle. At top, v=4 m/s. Find tension at top (g=10).', ['At top: both T and mg point toward center (downward)', 'T+mg=mv²/r', 'T=mv²/r−mg=2(16)/1−2(10)=32−20=12 N', 'Tension=12 N']),
      ('An object moves right at constant speed. From inertial frame, is it in equilibrium?', ['Constant velocity means zero acceleration', 'By Newton\'s first law, net force = 0', 'Object is in equilibrium (dynamic)', 'Forces balance but object is in motion']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
},

{
  'num': 2, 'title': 'Forces and Newton\'s Laws of Motion',
  'file': 'ap-physics-1-2-2-physics-1-unit-2-dynamics.html',
  'desc': 'Apply Newton\'s three laws to analyze forces and predict motion of objects and systems.',
  'gateway': [
      'Draw and interpret free-body diagrams for objects in various situations.',
      'Apply Newton\'s second law (F_net = ma) to solve for acceleration or forces.',
      'Analyze static and kinetic friction using the friction model.',
      'Apply Newton\'s laws to multi-body systems and connected objects.',
  ],
  'lessons': [
      _l('Newton\'s First and Third Laws',
         [_t('Newton\'s First Law (Inertia)', 'An object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted on by a net external force. Inertia is the resistance to change in motion.', 'Students think objects need a force to keep moving; only a net force changes velocity — constant velocity requires zero net force.', 'Identify scenarios where net force is zero and predict constant-velocity (or rest) motion.'),
          _t('Newton\'s Third Law (Action-Reaction)', 'For every force A exerts on B, B exerts an equal and opposite force on A. Action-reaction pairs act on different objects and never cancel each other.', 'Students think third-law pairs cancel; they act on different objects and cannot be combined into net force on one object.', 'Identify Newton\'s third law pairs; explain why they don\'t cancel when finding net force on one object.'),
          _t('Identifying Forces', 'Common forces: gravity (Fg=mg, down), normal (FN, perpendicular to surface), tension (along rope), friction (along surface, opposing relative motion), applied force. All forces require physical contact or a field.', 'Students invent forces like "the force of motion" or "momentum force"; every force must have a physical agent.', 'List and label all real forces on a free-body diagram; identify each force\'s agent.')],
         [('inertia', 'Resistance to change in motion; proportional to mass'),
          ('Newton\'s first law', 'Zero net force → zero acceleration (constant velocity or rest)'),
          ('action-reaction pair', 'Equal and opposite forces on different objects (Newton\'s 3rd law)'),
          ('free-body diagram', 'Diagram showing all forces acting on a single object as vectors')],
         ['Apply Newton\'s first law to predict motion when net force is zero', 'Identify Newton\'s third law pairs in physical scenarios', 'Draw complete and accurate free-body diagrams'],
         ['Free-body diagrams required in almost every AP® Physics FR', 'Third-law pair identification in MC', 'First law scenarios: "why doesn\'t it keep accelerating?"'],
         ['Draw FBD for a book resting on a table', 'Identify all third-law pairs when a horse pulls a cart'],
         [('A book sits on a table. The table pushes up on the book with 20 N. What is the third-law partner?', ['Newton\'s 3rd law: book pushes down on table with 20 N', 'The pair: table-on-book and book-on-table', 'Equal magnitude (20 N), opposite direction', 'Acts on different objects — cannot cancel']),
          ('A car moves at constant 60 mph. What is the net force on it?', ['Constant velocity → zero acceleration', 'F_net=ma=m(0)=0', 'Engine force equals drag+friction', 'No net force despite being in motion']),
          ('Draw a free-body diagram for a box on a rough ramp inclined at θ.', ['Forces: weight (mg down), normal (perpendicular to ramp), friction (up the ramp if sliding down)', 'Weight components: mg sinθ parallel, mg cosθ perpendicular', 'FN=mg cosθ for equilibrium perpendicular to ramp', 'Net force along ramp: mg sinθ − friction']),
          ('A 5 kg object is pushed with 30 N. It accelerates. Is there friction? Explain.', ['If F_net=30 N: a=30/5=6 m/s²', 'If friction exists: F_net=30−f; a=(30−f)/5', 'Must be given more info to determine friction', 'Look for constant velocity, rough surface clues']),
          ('Identify all third-law pairs when you push a wall.', ['You push wall (you exert force on wall)', 'Wall pushes you back (wall exerts equal force on you)', 'Earth pulls you down; you pull Earth up (gravity pair)', 'Floor pushes you up; you push floor down (normal pair)'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Newton\'s Laws', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State Newton\'s first law', 'Why don\'t action-reaction pairs cancel?', 'List three forces that never appear on an FBD']),

      _l('Newton\'s Second Law',
         [_t('F_net = ma', 'The net force on an object equals its mass times its acceleration. Direction of acceleration matches direction of net force. Must sum all force components along each axis separately.', 'Students use the magnitude of individual forces without considering direction; net force requires vector addition.', 'Set up ΣF=ma equations for x and y components separately; solve for unknown force or acceleration.'),
          _t('Mass and Weight', 'Weight W=mg is the gravitational force on an object (in Newtons). Mass is the amount of matter (in kg). Weight varies with g; mass does not.', 'Students use mass and weight interchangeably; weight is a force (N), mass is a scalar (kg).', 'Calculate weight from mass; distinguish conditions where g differs (e.g., on the Moon).'),
          _t('Normal Force', 'The normal force is perpendicular to the surface and adjusts to prevent penetration. On a horizontal surface, FN=mg for a stationary object. On an incline, FN=mg cosθ. In an elevator, FN changes.', 'Students always set FN=mg regardless of context; FN varies whenever there is vertical acceleration or the surface is inclined.', 'Calculate normal force for inclines, elevators, and curved surfaces.')],
         [('Newton\'s second law', 'ΣF = ma; net force causes acceleration'),
          ('weight', 'W = mg; gravitational force in Newtons'),
          ('normal force', 'Perpendicular surface force; FN = mg cosθ on incline'),
          ('component method', 'Decompose forces into x and y components; apply ΣF=ma to each')],
         ['Apply F_net=ma to find acceleration or unknown forces', 'Distinguish mass from weight', 'Calculate normal force in various contexts (incline, elevator, curve)'],
         ['ΣF=ma is the core equation of AP® Physics 1 mechanics', 'Incline problems require force components along and perpendicular to ramp', 'Elevator normal force problems test understanding of apparent weight'],
         ['A 4 kg block on a frictionless incline at 30°; find acceleration', 'A 70 kg person in an elevator accelerating up at 2 m/s²; find normal force'],
         [('A 5 kg block on a frictionless surface is pulled with 20 N. Find acceleration.', ['F_net=20 N; a=F/m=20/5=4 m/s²', 'No friction, so F_net=applied force', 'Direction: same as applied force', 'If friction were present: a=(20−f)/5']),
          ('A 10 kg block is on a 37° frictionless incline. Find acceleration (g=10 m/s²).', ['Along incline: F_net=mg sinθ=10(10)(0.6)=60 N', 'a=F_net/m=60/10=6 m/s²', 'Perpendicular: FN=mg cosθ=10(10)(0.8)=80 N', 'Acceleration down the incline at 6 m/s²']),
          ('A 60 kg person in an elevator accelerates upward at 3 m/s². Find normal force.', ['ΣF=FN−mg=ma', 'FN=m(g+a)=60(10+3)=780 N', 'Normal force > weight because accelerating upward', 'Apparent weight = 780 N']),
          ('Two forces act on a 3 kg object: 12 N east and 9 N north. Find acceleration magnitude.', ['F_net=√(12²+9²)=√(144+81)=√225=15 N', 'a=F_net/m=15/3=5 m/s²', 'Direction: arctan(9/12)=37° north of east', 'Same direction as net force vector']),
          ('An elevator decelerates downward at 2 m/s². A 50 kg person stands inside. Find FN.', ['Decelerating downward means acceleration is upward', 'FN−mg=ma (upward positive)', 'FN=m(g+a)=50(10+2)=600 N', 'Apparent weight > true weight'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Newton\'s Second Law', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write Newton\'s second law as a vector equation', 'Calculate FN for a 5 kg block on a 53° incline', 'Explain why normal force changes in an accelerating elevator']),

      _l('Friction',
         [_t('Static and Kinetic Friction', 'Static friction (f_s ≤ μ_s·FN) prevents motion; it adjusts up to its maximum. Kinetic friction (f_k = μ_k·FN) acts on sliding objects and is constant. μ_s > μ_k always.', 'Students use kinetic friction when an object is not sliding; use static friction until the applied force exceeds μ_s·FN.', 'Determine which friction applies; calculate maximum static and kinetic friction for given μ and FN.'),
          _t('Friction on Inclines', 'On an incline: FN=mg cosθ; friction force = μFN=μmg cosθ. Object slides if mg sinθ > μ_s·mg cosθ, i.e., tan θ > μ_s.', 'Students forget that FN=mg cosθ on an incline, not mg; friction depends on the normal force, which is reduced by the angle.', 'Set up and solve friction-on-incline problems using correct FN expression.'),
          _t('Friction in Newton\'s Second Law Problems', 'Friction opposes the direction of relative motion (kinetic) or impending motion (static). Draw friction in the correct direction on the FBD, then sum forces along the axis of motion.', 'Students draw friction in the wrong direction; kinetic friction always opposes actual motion, not applied force direction.', 'Correctly identify friction direction and include it in ΣF=ma equations.')],
         [('static friction', 'f_s ≤ μ_s·FN; prevents motion; adjusts as needed'),
          ('kinetic friction', 'f_k = μ_k·FN; constant during sliding'),
          ('coefficient of friction', 'μ; dimensionless ratio relating friction to normal force'),
          ('friction on incline', 'f = μ·FN = μ·mg cosθ')],
         ['Calculate static and kinetic friction forces', 'Determine whether an object slides on an incline', 'Include friction correctly in F_net=ma problems'],
         ['Friction problems appear in FR as multi-part with FBD + calculation', 'Incline friction tested frequently in MC', 'Must distinguish static vs. kinetic friction based on context'],
         ['Find if a 10 kg block slides on 30° incline with μ_s=0.6', 'A 5 kg block pulled at 15 N on μ_k=0.3 surface; find acceleration'],
         [('A 10 kg block is on a 30° incline with μ_s=0.6. Does it slide (g=10)?', ['mg sinθ=10(10)(0.5)=50 N (component down)', 'FN=mg cosθ=10(10)(√3/2)≈86.6 N', 'Max static friction=0.6(86.6)≈52 N', '52 N > 50 N → block does not slide']),
          ('A 6 kg block is pulled with 30 N on a surface with μ_k=0.25. Find acceleration (g=10).', ['FN=mg=6(10)=60 N', 'f_k=μ_k·FN=0.25(60)=15 N', 'F_net=30−15=15 N', 'a=15/6=2.5 m/s²']),
          ('At what minimum angle does an object begin to slide if μ_s=0.5?', ['Slides when tan θ > μ_s', 'tan θ = 0.5 → θ=arctan(0.5)≈26.6°', 'Object slides for θ > 26.6°', 'Angle of friction depends only on μ, not on mass']),
          ('A 4 kg block on a rough surface decelerates from 12 m/s to rest in 6 s. Find μ_k.', ['a=(0−12)/6=−2 m/s²', 'F_net=ma=4(−2)=−8 N (friction)', 'f_k=8 N; FN=mg=40 N', 'μ_k=8/40=0.2']),
          ('Why is μ_s > μ_k in most cases?', ['Static friction must overcome molecular adhesion at rest', 'Once sliding starts, contact area and adhesion decrease', 'Kinetic friction involves less interlocking', 'Static friction requires more force to initiate motion than to maintain sliding'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Friction', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the formula for kinetic friction', 'Calculate whether a box slides on a 40° ramp with μ_s=0.8', 'Explain why the angle of sliding onset depends only on μ, not mass']),

      _l('Multi-Body Systems and Atwood Machines',
         [_t('System Approach', 'For a system of connected objects, apply F_net=m_total·a if they move together. Then use individual object FBDs to find internal forces (like tension).', 'Students apply F=ma to each object individually for the system acceleration; using the total mass is faster and avoids sign errors.', 'Use the system approach to find acceleration, then isolate one object to find the tension.'),
          _t('Atwood Machine', 'Two masses over a pulley: the heavier mass descends, lighter ascends. Net force = (m₁−m₂)g; total mass = m₁+m₂. Acceleration a=(m₁−m₂)g/(m₁+m₂). Tension T=2m₁m₂g/(m₁+m₂).', 'Students apply F=ma to the system including the pulley mass; ideal pulley has no mass and only redirects tension.', 'Set up and solve Atwood machine problems using system equation and individual object equations.'),
          _t('Connected Objects with Friction', 'For a horizontal surface system: net force = applied force − friction on surface-contacting objects. Pulley redirects forces but does not change tension magnitude (ideal pulley).', 'Students add friction from all objects in the system; only objects touching the rough surface experience kinetic friction.', 'Identify which objects have friction, set up system equation, and solve for acceleration and tension.')],
         [('system approach', 'Apply ΣF=m_total·a to find acceleration when objects move as one'),
          ('Atwood machine', 'Two masses over pulley; a=(m₁−m₂)g/(m₁+m₂)'),
          ('tension', 'Internal force in a rope/string; same throughout ideal (massless) rope'),
          ('internal vs. external force', 'External force causes system acceleration; internal forces (tension) are found from individual FBDs')],
         ['Apply system method to find acceleration of connected objects', 'Solve Atwood machine for acceleration and tension', 'Find tension between objects in a horizontal two-body system'],
         ['Connected object problems in FR: system acceleration then tension', 'Atwood machine tested in both MC and FR', 'Must draw FBD for each object in FR'],
         ['Two blocks: 8 kg pulled by 40 N, connected to 2 kg on frictionless surface; find a and T', 'Atwood: m₁=6 kg, m₂=4 kg; find a and T'],
         [('Two blocks: 3 kg (A) and 5 kg (B), connected by string, pulled by 32 N on frictionless surface. Find a and T.', ['System: F=m_total·a → 32=8a → a=4 m/s²', 'Isolate A: T=m_A·a=3(4)=12 N', 'Check B: 32−T=5(4) → 32−12=20 ✓', 'T=12 N']),
          ('Atwood: m₁=8 kg, m₂=5 kg. Find acceleration and tension (g=10).', ['a=(8−5)·10/(8+5)=30/13≈2.31 m/s²', 'T=m₁(g−a)=8(10−2.31)=8(7.69)≈61.5 N', 'Or: T=2m₁m₂g/(m₁+m₂)=2(8)(5)(10)/13≈61.5 N', 'Tension between weight and m₁g: T < m₁g']),
          ('A 10 kg block on a table is connected via rope over pulley to a hanging 4 kg block. μ_k=0.2. Find a (g=10).', ['F_net=m_hang·g−f_k=4(10)−0.2(10)(10)=40−20=20 N', 'a=F_net/(m₁+m₂)=20/14≈1.43 m/s²', 'Friction acts on table block only', 'T found by isolating hanging block']),
          ('In an Atwood machine, if both masses are equal, what is the acceleration?', ['a=(m₁−m₂)g/(m₁+m₂)=0/2m=0', 'System is in equilibrium', 'Tension=mg (each mass)', 'Equal masses: no net force on system']),
          ('Why is tension the same on both sides of an ideal pulley?', ['Ideal pulley is massless and frictionless', 'No torque equation needed for massless system', 'Tension is an internal force transmitted through the rope', 'Real pulleys with mass would have different tensions on each side'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Atwood Machine', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write the Atwood machine acceleration formula', 'Explain the system approach and when to use individual FBDs', 'Find tension for two blocks on frictionless surface pulled by 50 N']),
  ],
  'unit_qs': [
      ('A 2 kg book rests on a table. List all forces and their third-law partners.', ['Book weight (Earth pulls book down) ↔ book pulls Earth up', 'Normal force (table pushes book up) ↔ book pushes table down', 'Two pairs, not four separate forces', 'Third-law pairs act on different objects']),
      ('A 5 kg block is pushed at constant velocity by 20 N. Find friction force.', ['Constant v → a=0 → F_net=0', 'Applied force = friction force: f=20 N', 'f_k=20 N', 'μ_k=f/FN=20/50=0.4']),
      ('A 3 kg block on 40° frictionless incline. Find acceleration (g=10).', ['a=g sinθ=10 sin40°≈6.43 m/s²', 'FN=mg cos40°=3(10)(0.766)=23 N', 'Net force along incline=3(6.43)=19.3 N', 'Acceleration=6.43 m/s² down the slope']),
      ('Atwood: m₁=3 kg, m₂=7 kg. Find a and T (g=10).', ['a=(7−3)(10)/(7+3)=40/10=4 m/s²', 'T=m₁(g+a)=3(10+4)=42 N', 'Check: 7(10−4)=42 ✓', 'T=42 N']),
      ('A 60 kg person in elevator feels normal force 480 N. Find elevator acceleration (g=10).', ['FN−mg=ma: 480−600=60a', '−120=60a → a=−2 m/s²', 'Downward acceleration at 2 m/s²', 'Decelerating if moving up or accelerating down']),
      ('A 4 kg block on μ_s=0.5, μ_k=0.3 surface is pushed with 22 N. Does it move? If so, find a (g=10).', ['Max static: μ_s·mg=0.5(40)=20 N', '22 N > 20 N → block moves', 'f_k=0.3(40)=12 N; F_net=22−12=10 N', 'a=10/4=2.5 m/s²']),
      ('A 10 kg object has two horizontal forces: 50 N east, 30 N west. Find acceleration and direction.', ['F_net=50−30=20 N east', 'a=20/10=2 m/s² east', 'Net force determines acceleration direction', 'Object accelerates east']),
      ('Two blocks (6 kg and 4 kg) are connected by a string on a frictionless surface. A 20 N force pulls the 6 kg block. Find tension.', ['System: a=20/10=2 m/s²', 'Isolate 4 kg block: T=4(2)=8 N', 'Or isolate 6 kg: 20−T=6(2)=12 → T=8 N', 'T=8 N']),
      ('A 5 kg block slides down a 30° ramp with μ_k=0.2. Find acceleration (g=10).', ['FN=mg cos30°=5(10)(√3/2)≈43.3 N', 'f_k=0.2(43.3)≈8.66 N', 'F_net=mg sin30°−f_k=25−8.66≈16.34 N', 'a=16.34/5≈3.27 m/s²']),
      ('Explain the difference between mass and weight using the Moon as context.', ['Mass is invariant; same on Moon and Earth', 'Weight = mg; on Moon g≈1.6 m/s² → weight is 1/6 of Earth weight', 'A 60 kg person weighs 600 N on Earth, 96 N on Moon', 'Mass (60 kg) unchanged']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
},

{
  'num': 3, 'title': 'Work, Energy, and Power',
  'file': 'ap-physics-1-2-3-physics-1-unit-3-circular-motion-and-gravitation.html',
  'desc': 'Apply the work-energy theorem and conservation of energy to analyze motion and forces.',
  'gateway': [
      'Calculate work done by constant and variable forces.',
      'Apply the work-energy theorem: W_net = ΔKE.',
      'Use conservation of mechanical energy for isolated systems.',
      'Calculate power and relate it to work and energy.',
  ],
  'lessons': [
      _l('Work Done by Forces',
         [_t('Definition of Work', 'W = F·d·cosθ where θ is the angle between force and displacement. Work is a scalar. Positive work when force has component in direction of motion; negative when opposite.', 'Students use W=Fd regardless of angle; if force is perpendicular to motion (e.g., normal force, centripetal), W=0.', 'Calculate work done by each force in a scenario including gravity, friction, and applied forces.'),
          _t('Work Done by Gravity', 'W_gravity = −mg·Δh = mg(h_i − h_f). Positive when descending (force and displacement both have downward component), negative when ascending.', 'Students forget the sign of gravitational work; W_gravity = mgΔh only when downward displacement is positive.', 'Calculate gravitational work for objects moving along ramps or arbitrary paths.'),
          _t('Net Work and Work-Energy Theorem', 'W_net = ΔKE = ½mv_f² − ½mv_i². All forces contributing work can be summed, or alternatively the net force can be used. Forces perpendicular to motion do no work.', 'Students sum work done by individual forces using incorrect angles; the work-energy theorem provides a powerful scalar alternative to F=ma.', 'Apply work-energy theorem to find final speed or work done by an unknown force.')],
         [('work', 'W = Fdcosθ; scalar quantity, unit: Joules (J)'),
          ('work-energy theorem', 'W_net = ΔKE = ½mv_f² − ½mv_i²'),
          ('zero work', 'When force is perpendicular to motion (θ=90°)'),
          ('gravitational work', 'W_g = −mgΔh; positive when descending')],
         ['Calculate work done by each force in various configurations', 'Apply work-energy theorem to find speed or distance', 'Identify forces that do no work'],
         ['Work by friction in FR: W_friction = f_k·d (negative)', 'Work-energy theorem replaces kinematics in many FR problems', 'Zero-work forces tested in MC'],
         ['Find work done by gravity on a 5 kg block sliding 3 m down a 30° ramp', 'Apply W-E theorem to find final speed of pulled block'],
         [('A 10 N force at 30° above horizontal moves a box 5 m on a flat surface. Find work done by the force.', ['W=Fdcosθ=10(5)cos30°=50(√3/2)≈43.3 J', 'Only horizontal component does work', 'Vertical component: no vertical displacement', 'W≈43.3 J']),
          ('A 4 kg block slides from rest down a 5 m, 37° ramp (frictionless). Find final speed (g=10).', ['W_gravity=mgh=4(10)(5sin37°)=4(10)(3)=120 J', 'W_net=ΔKE: 120=½(4)v²', 'v²=60 → v=√60≈7.75 m/s', 'Or use kinematics: a=g sin37°=6; v²=2(6)(5)=60 ✓']),
          ('How much work does the normal force do on a block sliding down a ramp?', ['Normal force is perpendicular to the ramp surface', 'Motion is along the ramp surface', 'Angle between FN and displacement = 90°', 'W_N = F·d·cos90° = 0']),
          ('A 5 kg box starts at rest and ends at 10 m/s after 20 N of net force is applied. How far did it move?', ['W_net=ΔKE=½(5)(100)−0=250 J', 'W_net=F_net·d: 250=20·d', 'd=12.5 m', 'Work-energy theorem replaces kinematics']),
          ('A 3 kg ball is lifted 4 m. What is the work done by gravity?', ['W_gravity=−mgh=−3(10)(4)=−120 J', 'Gravity acts down; displacement is up', 'θ=180°; cos180°=−1; W=mg(d)(−1)=−120 J', 'Negative work means force opposes motion'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Work and Energy', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the work formula and identify θ', 'Explain why the normal force does no work on a horizontal surface', 'Apply W-E theorem: a 2 kg block accelerates from 3 to 7 m/s; find net work done']),

      _l('Kinetic and Potential Energy',
         [_t('Kinetic Energy', 'KE = ½mv². Depends on both mass and speed. Doubling speed quadruples KE. KE is always ≥ 0.', 'Students think doubling mass doubles KE equivalently with doubling speed; KE scales linearly with m but quadratically with v.', 'Compare kinetic energies of objects with different masses and speeds.'),
          _t('Gravitational Potential Energy', 'PE_g = mgh where h is height above a chosen reference level. The choice of reference level is arbitrary, but must be consistent. Only changes in PE (ΔPE) are physically meaningful.', 'Students think the reference level must be at ground level; any consistent reference is valid, and only ΔPE matters in energy conservation.', 'Set reference level, calculate PE and ΔPE for objects at different heights.'),
          _t('Elastic Potential Energy', 'PE_spring = ½kx² where k is spring constant and x is compression/extension from equilibrium. Spring stores energy when compressed or stretched.', 'Students think PE_spring = kx (linear); it is ½kx², which increases with the square of deformation.', 'Calculate elastic PE for compressed/stretched springs; use in energy conservation problems.')],
         [('kinetic energy', 'KE = ½mv²; energy of motion'),
          ('gravitational PE', 'PE_g = mgh; energy due to height'),
          ('elastic PE', 'PE_spring = ½kx²; energy stored in spring'),
          ('reference level', 'Arbitrary zero for PE; only changes in PE matter')],
         ['Calculate KE, gravitational PE, and spring PE', 'Understand that only ΔPE is physically meaningful', 'Compare energies of objects with different masses and speeds'],
         ['Energy bar diagrams tested in AP® FR (show KE, PE, thermal energy)', 'Spring PE in both MC and FR', 'Reference level: stated or implied in FR problems'],
         ['Compare KE of 2 kg at 6 m/s vs. 4 kg at 4 m/s', 'Find PE stored in spring (k=200 N/m) compressed 0.15 m'],
         [('Compare KE of: (A) 2 kg at 6 m/s and (B) 4 kg at 3 m/s.', ['KE_A=½(2)(36)=36 J', 'KE_B=½(4)(9)=18 J', 'Object A has twice the KE', 'Quadratic dependence on speed; A is much faster']),
          ('A 3 kg object is at h=5 m above the floor. Find PE_g with floor as reference.', ['PE_g=mgh=3(10)(5)=150 J', 'Reference level: floor (h=0)', 'If reference were at h=5 m: PE_g=0 at that height', 'Only changes in PE are physically meaningful']),
          ('A spring with k=400 N/m is compressed 0.1 m. Find PE_spring.', ['PE=½kx²=½(400)(0.01)=2 J', 'Compressed or stretched gives same PE (x² is positive)', '0.1 m compression → 2 J stored', 'If compressed 0.2 m: PE=½(400)(0.04)=8 J (4× more for 2× compression)']),
          ('A 0.5 kg ball is thrown upward at 10 m/s. Find max height using energy (g=10).', ['KE_i=½(0.5)(100)=25 J', 'At max height, KE=0; all converted to PE', '25=mgh=0.5(10)h → h=5 m', 'Energy conservation: KE→PE']),
          ('A 1 kg ball is dropped from 20 m. Find KE just before hitting ground.', ['PE lost = mgh = 1(10)(20)=200 J', 'KE gained = 200 J (frictionless)', 'v=√(2KE/m)=√400=20 m/s', 'All PE converted to KE'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — KE and PE', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write formulas for KE, PE_g, and PE_spring', 'Explain why PE depends on reference level choice', 'Find the spring constant if 3 J is stored at 0.2 m compression']),

      _l('Conservation of Mechanical Energy and Power',
         [_t('Conservation of Mechanical Energy', 'In the absence of non-conservative forces (friction, air resistance), total mechanical energy E = KE + PE is constant. ΔKE + ΔPE = 0, or KE_i + PE_i = KE_f + PE_f.', 'Students apply energy conservation when friction is present; friction converts mechanical energy to thermal energy, reducing total ME.', 'Verify no non-conservative forces are present, then apply energy conservation to find speed or height.'),
          _t('Energy with Non-Conservative Forces', 'W_non-conservative = ΔE_mech = ΔKE + ΔPE. Friction does negative work equal to −f·d (energy converted to heat). Total energy (mechanical + thermal) is always conserved.', 'Students think energy is lost due to friction; energy is converted from mechanical to thermal, not lost.', 'Apply energy methods with friction: KE_f = KE_i + PE_i − f_k·d (for descending case).'),
          _t('Power', 'P = W/t = Fv (for constant force and velocity). Unit: Watt (W) = J/s. Average power = ΔE/t. P = Fv when force and velocity are in same direction.', 'Students use P=Fv even when force and velocity are not parallel; use P = F·v·cosθ = F_parallel·v.', 'Calculate power from work and time, and from force and velocity.')],
         [('conservation of ME', 'KE_i + PE_i = KE_f + PE_f (no friction)'),
          ('non-conservative force', 'Force that converts mechanical energy to thermal (friction, air resistance)'),
          ('thermal energy', 'ΔE_thermal = f_k·d; mechanical energy lost to friction'),
          ('power', 'P = W/t = Fv; rate of energy transfer, Watts')],
         ['Apply conservation of mechanical energy to find speed or height', 'Account for energy lost to friction in energy equations', 'Calculate power from work/time and from F·v'],
         ['Energy conservation problems appear in every AP® Physics 1 exam', 'Friction energy losses tested in FR', 'Power calculations in both MC and FR'],
         ['Ball rolls off table; find speed at bottom using energy conservation', 'Car engine exerts 3000 N at 20 m/s; find power output'],
         [('A 2 kg block starts at rest at height 8 m and slides down a frictionless ramp. Find speed at bottom (g=10).', ['KE_i+PE_i=KE_f+PE_f', '0+mgh=½mv²+0', 'v=√(2gh)=√(2(10)(8))=√160≈12.6 m/s', 'Mass cancels; speed independent of mass']),
          ('A 4 kg block slides down a 5 m ramp (h=3 m) with f_k=6 N. Find final speed (g=10).', ['E_i=KE_i+PE_i=0+4(10)(3)=120 J', 'E_f=E_i−f_k·d=120−6(5)=90 J', 'E_f=½mv_f²: 90=½(4)v_f² → v_f²=45', 'v_f=√45≈6.7 m/s']),
          ('A 70 kg runner runs at 5 m/s. The engine (legs) exerts 350 N at that speed. Find power output.', ['P=Fv=350(5)=1750 W', 'Or: P=W/t; need more info for this form', 'P≈1750 W≈2.3 horsepower', 'High power output for a sprint']),
          ('A spring (k=500 N/m) is compressed 0.2 m and launches a 0.1 kg ball. Find launch speed.', ['PE_spring=½kx²=½(500)(0.04)=10 J', 'All PE converts to KE: 10=½(0.1)v²', 'v²=200 → v=√200≈14.1 m/s', 'Energy conservation, no friction']),
          ('A 1500 kg car accelerates from 0 to 30 m/s in 10 s. What is average power?', ['ΔKE=½(1500)(900)=675,000 J', 'P_avg=ΔKE/t=675,000/10=67,500 W', '=67.5 kW≈90 hp', 'Enormous power for vehicle acceleration'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Conservation of Energy', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the conditions for conservation of mechanical energy', 'Write the energy equation including friction losses', 'Calculate power for a 500 N force applied at 3 m/s']),

      _l('Momentum and Impulse Preview',
         [_t('Momentum', 'p = mv (vector). Unit: kg·m/s. Momentum depends on both mass and velocity. A heavy slow object can have the same momentum as a light fast object.', 'Students think momentum and kinetic energy are equivalent; p is linear in v, KE is quadratic. Doubling v doubles p but quadruples KE.', 'Calculate momentum of objects and compare momenta in different situations.'),
          _t('Impulse-Momentum Theorem', 'J = FΔt = Δp. Impulse is the product of force and time over which it acts. A large force over short time or small force over long time can produce the same impulse.', 'Students confuse impulse with work; impulse = FΔt = Δp; work = Fd = ΔKE. Time vs. distance is the key difference.', 'Apply impulse-momentum theorem to find change in momentum or average force.'),
          _t('Conservation of Momentum', 'In an isolated system (no external forces), total momentum is conserved: Σp_i = Σp_f. Applied to collisions and explosions.', 'Students apply momentum conservation when external forces are present; friction, gravity, or normal forces on the system can change total momentum.', 'Verify the system is isolated, then apply momentum conservation to collisions.')],
         [('momentum', 'p = mv; vector, units kg·m/s'),
          ('impulse', 'J = FΔt = Δp; units N·s = kg·m/s'),
          ('impulse-momentum theorem', 'F_avg·Δt = mv_f − mv_i'),
          ('conservation of momentum', 'Σp_i = Σp_f for isolated systems')],
         ['Calculate momentum and relate it to kinetic energy', 'Apply impulse-momentum theorem to find force or time', 'Apply momentum conservation to simple collision problems'],
         ['Momentum and impulse in Unit 4; preview here connects to energy', 'Impulse from area under F-t graph tested in MC', 'Conservation of momentum in FR every year'],
         ['Find impulse needed to stop a 1000 kg car moving at 30 m/s', 'Two 5 kg carts collide; find final velocity after perfectly inelastic collision'],
         [('A 0.1 kg ball moves at 20 m/s. Find its momentum.', ['p=mv=0.1(20)=2 kg·m/s', 'Direction: same as velocity', 'KE=½mv²=½(0.1)(400)=20 J', 'p and KE are different quantities']),
          ('A 0.5 kg ball hits a wall at 10 m/s and bounces back at 8 m/s. Find impulse.', ['Impulse = Δp = m(v_f − v_i)', 'Take initial direction as positive: Δp=0.5(−8−10)=0.5(−18)=−9 N·s', 'Magnitude: 9 N·s', 'Direction: into the wall (opposing initial motion)']),
          ('A 1200 kg car moving at 15 m/s collides and sticks with a stationary 800 kg car. Find final velocity.', ['p_i=1200(15)+800(0)=18000 kg·m/s', 'p_f=(1200+800)v_f=2000v_f', '18000=2000v_f → v_f=9 m/s', 'Perfectly inelastic collision; KE is not conserved']),
          ('A 10 N force acts on a 2 kg object for 5 s. Find impulse and change in velocity.', ['J=FΔt=10(5)=50 N·s', 'Δp=J=50 kg·m/s', 'Δv=Δp/m=50/2=25 m/s', 'Object speeds up by 25 m/s']),
          ('Why does the area under a force-time graph equal impulse?', ['Impulse = FΔt for constant force', 'For variable force: J=∫F dt (area under F-t graph)', 'Narrow tall spike can equal broad shallow force (same area)', 'Car airbag: extends time to reduce peak force'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Impulse and Momentum', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the impulse-momentum theorem', 'Calculate impulse from a force-time graph (triangle area)', 'Explain why momentum is conserved but energy is not in a perfectly inelastic collision']),
  ],
  'unit_qs': [
      ('A 3 kg block is pushed 8 m by a 15 N force at 40° above horizontal. Find work done by the applied force.', ['W=Fdcosθ=15(8)cos40°≈15(8)(0.766)≈91.9 J', 'Only horizontal component does work on horizontal motion', 'Vertical component balanced by normal force change', 'W≈91.9 J']),
      ('A 5 kg ball falls from rest at 10 m. Find speed just before impact using energy conservation (g=10).', ['PE=mgh=5(10)(10)=500 J → KE=500 J', 'v=√(2KE/m)=√200≈14.1 m/s', 'Or v=√(2gh)=√200≈14.1 m/s', 'Mass cancels']),
      ('A spring (k=800 N/m) launches a 0.5 kg ball from x=0.3 m compression. Find launch speed.', ['PE=½(800)(0.09)=36 J', '36=½(0.5)v² → v²=144 → v=12 m/s', 'All spring PE converts to KE', 'Speed = 12 m/s']),
      ('A 6 kg block descends 4 m on a rough ramp (f_k=12 N, length=6 m). Find final KE (g=10).', ['ΔPE=mgh=6(10)(4)=240 J (lost)', 'W_friction=−f_k·d=−12(6)=−72 J', 'ΔKE=240−72=168 J', 'KE_f=168 J']),
      ('Calculate power output of a 600 N cyclist traveling at 8 m/s.', ['P=Fv=600(8)=4800 W', '=4.8 kW', 'At constant velocity, engine force = drag', 'Power = 4800 W']),
      ('Two 1 kg putty balls collide head-on at 5 m/s each. They stick together. Find final velocity.', ['p_i=1(5)+1(−5)=0 kg·m/s', 'p_f=(2)v_f=0 → v_f=0', 'They stop completely', 'Momentum conserved; KE not conserved']),
      ('A 2 kg book rests on a shelf 3 m high. What is its gravitational PE relative to the floor? Relative to the ceiling at 5 m?', ['Relative to floor: PE=2(10)(3)=60 J', 'Relative to ceiling: h=3−5=−2 m; PE=2(10)(−2)=−40 J', 'Only differences in PE are meaningful', 'Reference choice is arbitrary']),
      ('A force of 100 N acts on a 10 kg object for 3 s. Find impulse and final speed if starting from rest.', ['J=FΔt=100(3)=300 N·s', 'Δp=300 kg·m/s; v_f=300/10=30 m/s', 'Impulse = change in momentum', 'v_f=30 m/s']),
      ('A 2 kg block falls from rest, hits the ground at 10 m/s, and stops. Find work done by the ground (g=10).', ['KE just before impact=½(2)(100)=100 J', 'Ground brings it to rest: W_ground=ΔKE=0−100=−100 J', 'Ground exerts a large force over short distance', 'Work = −100 J (force opposite to motion)']),
      ('Compare: which requires more power — lifting 100 kg at 2 m/s or 50 kg at 5 m/s? (g=10)', ['P₁=Fv=mg·v=100(10)(2)=2000 W', 'P₂=50(10)(5)=2500 W', '50 kg at 5 m/s requires more power', 'Higher speed has greater power even with less mass']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
},

{
  'num': 4, 'title': 'Systems of Particles, Linear Momentum',
  'file': 'ap-physics-1-2-4-physics-1-unit-4-energy.html',
  'desc': 'Apply impulse-momentum theorem and conservation of momentum to collisions and explosions.',
  'gateway': [
      'Apply impulse-momentum theorem: J = FΔt = Δp.',
      'Distinguish elastic and inelastic collisions.',
      'Apply conservation of momentum to one-dimensional collisions.',
      'Use the center of mass concept for systems of particles.',
  ],
  'lessons': [
      _l('Impulse and Momentum in Depth',
         [_t('Impulse from Variable Force', 'When force is not constant, J = area under the F-t graph = ∫F dt. A force-time graph can have triangles, rectangles, or other shapes; total impulse is the total area (signed).', 'Students use J=FΔt only for constant forces; for variable force, integrate (find area under curve).', 'Calculate impulse from F-t graphs by finding the area under the curve.'),
          _t('Impulse and Stopping Time', 'For a given momentum change (Δp), longer stopping time means smaller average force: F_avg = Δp/Δt. This is the physics of seatbelts and airbags.', 'Students think more force always means faster stopping; impulse (Δp) is fixed by the collision, but time determines peak force.', 'Analyze safety device scenarios using the impulse-momentum relationship.'),
          _t('Rocket Propulsion (Preview)', 'A rocket gains momentum by expelling mass at high velocity. Even with no external forces, the rocket accelerates because expelled exhaust provides an equal and opposite impulse. This is conservation of momentum.', 'Students think a rocket needs air to push against; rocket thrust is reaction to exhaust momentum, not air resistance.', 'Explain rocket propulsion using Newton\'s third law and momentum conservation.')],
         [('impulse', 'J = FΔt = Δp = area under F-t graph'),
          ('average force', 'F_avg = Δp/Δt; larger time → smaller force for same Δp'),
          ('F-t graph area', 'Total impulse = signed area under force-time graph'),
          ('safety devices', 'Extend collision time to reduce peak force for given Δp')],
         ['Calculate impulse from constant and variable forces', 'Explain the physics of safety devices using impulse-momentum', 'Relate rocket propulsion to Newton\'s third law'],
         ['F-t graph area problems in MC', 'Safety device explanations in FR (seatbelts, airbags)', 'Rocket/explosion momentum problems in FR'],
         ['From F-t graph (triangle peak 800 N over 0.02 s), find impulse', 'A 1500 kg car stops in 0.1 s vs. 2 s; compare average forces'],
         [('From a triangular F-t graph with peak 600 N at t=0.1 s and back to 0 at t=0.2 s. Find impulse.', ['Area = ½·base·height = ½(0.2)(600)=60 N·s', 'Impulse = 60 N·s', 'F_avg=60/0.2=300 N', 'Average force = half the peak']),
          ('A 0.5 kg ball rebounds. Before: 8 m/s right. After: 6 m/s left. Find impulse.', ['Δp=m(v_f−v_i)=0.5(−6−8)=0.5(−14)=−7 N·s', 'Magnitude: 7 N·s directed left', 'If contact time = 0.02 s: F_avg=7/0.02=350 N', 'Large force, short time']),
          ('A 1000 kg car crashes: v goes from 20 m/s to 0. Compare F_avg for stopping in 0.1 s vs. 2 s.', ['Δp=1000(0−20)=−20,000 N·s (magnitude: 20,000)', 'F₁=20000/0.1=200,000 N (rigid wall)', 'F₂=20000/2=10,000 N (crumple zone)', 'Crumple zone reduces force by factor of 20']),
          ('A 3 kg object has initial momentum 15 kg·m/s east. A 10 N force acts west for 2 s. Find final momentum.', ['J=FΔt=−10(2)=−20 N·s (west)', 'p_f=p_i+J=15+(−20)=−5 kg·m/s', 'Object now moves west at 5/3 m/s', 'Direction reversed']),
          ('Explain in terms of momentum why rocket propulsion works in vacuum.', ['Rocket expels gas with large momentum backward', 'System (rocket+gas) total p is conserved', 'Rocket gains equal and opposite momentum forward', 'No air needed; reaction is to exhaust, not environment'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Impulse-Momentum Theorem', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Find impulse from a rectangular F-t graph (F=200 N, Δt=0.5 s)', 'Explain why airbags reduce injury using physics', 'State how rocket propulsion uses Newton\'s 3rd law']),

      _l('Conservation of Momentum: Collisions',
         [_t('Perfectly Inelastic Collisions', 'Objects collide and stick together. Momentum is conserved (p_i=p_f), but kinetic energy is not — some KE converts to thermal/sound energy. Final velocity: v_f=(m₁v₁+m₂v₂)/(m₁+m₂).', 'Students apply KE conservation to inelastic collisions; only elastic collisions conserve KE.', 'Solve perfectly inelastic collision problems using momentum conservation only.'),
          _t('Elastic Collisions', 'Both momentum and kinetic energy are conserved. For elastic collision between equal masses: the first stops and the second moves with the first\'s original velocity (1D).', 'Students think elastic means colliding objects bounce back with same speed; elastic just means KE conserved, not that objects reverse direction.', 'Apply both momentum and energy conservation to elastic collisions.'),
          _t('Explosions', 'In an explosion, a stationary system breaks apart. Total momentum before = 0 = total momentum after. Fragments move in opposite directions with momenta equal in magnitude.', 'Students think explosion creates momentum from nothing; internal forces cannot change total momentum; initial p=0 means final p_total=0.', 'Apply momentum conservation to explosion problems where initial velocity is zero.')],
         [('perfectly inelastic', 'Objects stick; KE not conserved; p conserved'),
          ('elastic collision', 'Both p and KE conserved; objects separate'),
          ('explosion', 'Object breaks apart; p_initial=0=p_final; KE increases from chemical energy'),
          ('KE conservation', 'Only valid for elastic collisions')],
         ['Solve perfectly inelastic collisions using momentum conservation', 'Apply both conservation laws to elastic collisions', 'Analyze explosions using initial p=0'],
         ['Collision type identification in MC', 'Multi-part FR: calculate p, determine KE change, state collision type', 'Explosion problems: find fragment velocities from p=0 initial'],
         ['3 kg at 4 m/s hits stationary 2 kg and they stick; find final v', '2 kg at 6 m/s hits stationary 2 kg elastically; find both final velocities'],
         [('A 4 kg cart at 6 m/s collides and sticks with a 2 kg cart at rest. Find final velocity.', ['p_i=4(6)+2(0)=24 kg·m/s', 'p_f=(4+2)v_f=6v_f', '6v_f=24 → v_f=4 m/s', 'KE lost: ½(4)(36)−½(6)(16)=72−48=24 J']),
          ('Calculate KE before and after the previous collision. What happened to the lost energy?', ['KE_i=72 J (from above)', 'KE_f=48 J', 'ΔKE=−24 J', 'Converted to thermal energy, sound, deformation']),
          ('A 3 kg ball at 8 m/s elastically hits a stationary 3 kg ball. Find final velocities.', ['Equal masses, 1D elastic: first stops, second moves at 8 m/s', 'v₁_f=0; v₂_f=8 m/s', 'Check p: 3(8)=24 → 3(0)+3(8)=24 ✓', 'Check KE: ½(3)(64)=96 → 96 ✓']),
          ('A 2 kg bomb at rest explodes into two pieces: 0.5 kg moves at 12 m/s. Find velocity of 1.5 kg piece.', ['p_i=0; p_f=0.5(12)+1.5v=0', '6+1.5v=0 → v=−4 m/s', '1.5 kg piece moves at 4 m/s opposite direction', 'KE increased from chemical energy']),
          ('Two equal-mass balls collide head-on at equal speeds. They stick. What is the final velocity?', ['p_i=mv+(−mv)=0', 'p_f=(2m)v_f=0', 'v_f=0', 'They come to complete rest (KE all converted to thermal)'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Collisions', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State what is conserved in elastic vs. inelastic collisions', 'Solve: 5 kg at 4 m/s hits stationary 5 kg and sticks', 'Explain why KE is not conserved in perfectly inelastic collisions']),

      _l('Center of Mass',
         [_t('Center of Mass Position', 'x_cm = Σ(mᵢxᵢ)/Σmᵢ. The center of mass (CM) is the weighted average position of all masses. For uniform objects, CM is at the geometric center.', 'Students place the CM at the heavier mass or at the midpoint for all cases; CM is at the midpoint only for equal masses.', 'Calculate the CM position for systems of two or more point masses.'),
          _t('Motion of the Center of Mass', 'The CM of a system moves as if all mass were concentrated there and all external forces acted on it: F_net,ext = M·a_cm. Internal forces don\'t affect CM motion.', 'Students think internal forces (collisions, explosions) change CM motion; only external forces move the CM.', 'Predict the CM trajectory during a collision or explosion; it continues unchanged by internal events.'),
          _t('Applying CM to Collisions', 'In a collision, if external forces are negligible, CM velocity is constant. For perfectly inelastic collision, the final velocity equals the CM velocity. For elastic collisions, each object oscillates about the CM.', 'Students think the CM moves to where the masses stick; CM velocity is the constant final velocity in perfectly inelastic collision.', 'Use CM velocity to predict outcome of perfectly inelastic collisions without computing individual momenta.')],
         [('center of mass', 'x_cm = Σ(mᵢxᵢ)/M; weighted average position'),
          ('CM velocity', 'v_cm = Σ(mᵢvᵢ)/M = p_total/M'),
          ('CM trajectory', 'Determined by external forces only; unaffected by internal forces'),
          ('CM and collisions', 'v_cm before = v_cm after (when external forces negligible)')],
         ['Calculate center of mass position for point mass systems', 'Explain why internal forces don\'t affect CM motion', 'Use CM velocity to predict perfectly inelastic collision outcome'],
         ['CM problems in both MC and FR', 'CM trajectory during explosion is tested conceptually', 'System CM used in FR to analyze momentum'],
         ['Find CM of: 2 kg at x=1 m and 6 kg at x=5 m', 'An isolated system: how does the CM move during a collision?'],
         [('Find CM of: 3 kg at x=0 and 1 kg at x=8 m.', ['x_cm=(3(0)+1(8))/(3+1)=8/4=2 m', 'CM is at x=2 m', 'Closer to heavier mass at x=0', 'CM divides distance in inverse ratio of masses (3:1 from right)']),
          ('A 2 kg and 4 kg mass are connected by a rod. 2 kg moves at 6 m/s right; 4 kg at 3 m/s left. Find v_cm.', ['v_cm=Σmv/M=(2(6)+4(−3))/(2+4)', '=(12−12)/6=0', 'CM is stationary', 'Total momentum = 0; if they collide and stick, they stop']),
          ('During an explosion, a rocket initially at rest splits. How does the CM move afterward?', ['Initially at rest: v_cm=0', 'Explosion is internal; external forces negligible', 'CM continues with v_cm=0 after explosion', 'Fragments move in opposite directions; CM stays at original position']),
          ('A 5 kg ball at x=2 m and 3 kg ball at x=10 m. Where is the CM?', ['x_cm=(5(2)+3(10))/(5+3)=(10+30)/8=40/8=5 m', 'CM at x=5 m', 'Closer to heavier 5 kg mass', 'If they collide at CM speed: use total p/total m']),
          ('Why does the center of mass of a thrown, freely rotating wrench follow a parabolic path?', ['Only external force is gravity (no air resistance)', 'F_net,ext=Mg acts on CM', 'CM follows projectile motion (parabola)', 'Internal rotational motion doesn\'t affect CM trajectory'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Center of Mass', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write the center of mass formula', 'Explain why CM is unaffected by internal forces', 'Find the CM of 4 kg at 0 m and 2 kg at 6 m']),

      _l('Two-Dimensional Collisions',
         [_t('Conservation of Momentum in 2D', 'In 2D collisions, momentum is conserved in both x and y directions independently. Σp_x (before) = Σp_x (after) and Σp_y (before) = Σp_y (after). Treat each component separately.', 'Students try to conserve the magnitude of momentum without separating components; momentum conservation is a vector equation.', 'Write separate momentum conservation equations for x and y components of a 2D collision.'),
          _t('Glancing Collisions', 'In a glancing collision, one object is initially moving and the other is at rest. After, both objects move at angles. Use x and y momentum equations plus one more (angle or elasticity).', 'Students try to solve glancing collisions with one equation; two equations needed (x and y components).', 'Set up and identify the equations needed for a 2D glancing collision.'),
          _t('Pool Ball Analogy', 'Billiard ball collisions approximate elastic 2D collisions. For elastic collision of equal masses where one is at rest, the angle between the two final velocity vectors is exactly 90°.', 'Students think the 90° rule applies to all 2D collisions; it is specific to equal-mass elastic collisions with one initially at rest.', 'Apply the 90° result to equal-mass elastic collisions and verify with momentum/energy conservation.')],
         [('2D momentum conservation', 'Separate x and y equations: Σp_x conserved, Σp_y conserved'),
          ('glancing collision', '2D collision where objects scatter at angles'),
          ('elastic 2D collision', 'Equal masses: angle between final velocities = 90°'),
          ('vector components', 'Must use cosθ and sinθ to resolve final velocities into components')],
         ['Write x and y momentum conservation equations for 2D collisions', 'Set up equations for glancing collisions', 'Apply 90° rule for equal-mass elastic collisions'],
         ['2D collisions appear in AP® Physics 1 FR', 'Must write both x and y equations explicitly', 'Equal-mass elastic 2D rule tested in MC'],
         ['Set up 2D momentum equations for a 4 kg ball hitting stationary 2 kg ball at an angle', 'Verify 90° rule for a billiard ball collision'],
         [('A 2 kg ball at 10 m/s east hits a stationary 3 kg ball. After, 2 kg moves at 30° N of E. Set up equations.', ['p_x: 2(10)=2(v₁cosθ₁)+3(v₂cosθ₂)', 'p_y: 0=2(v₁sinθ₁)−3(v₂sinθ₂)', 'Two equations, multiple unknowns; need more info', 'Elastic: also apply KE conservation']),
          ('A 1.5 kg ball at 8 m/s north and a 2.5 kg ball at 5 m/s east collide and stick. Find final velocity.', ['p_x: 2.5(5)=4v_x → v_x=12.5/4=3.125 m/s', 'p_y: 1.5(8)=4v_y → v_y=12/4=3 m/s', 'v=√(3.125²+3²)=√(9.77+9)≈4.33 m/s', 'θ=arctan(3/3.125)=43.8° north of east']),
          ('For an elastic collision between equal masses where m₂ is at rest, show the angle between v₁_f and v₂_f = 90°.', ['p conservation: m·v₁₀ = m·v₁_f + m·v₂_f', 'KE conservation: v₁₀² = v₁_f² + v₂_f²', 'From p: v₁₀ = v₁_f + v₂_f (vector)', 'Square both: v₁₀²=v₁_f²+2v₁_f·v₂_f+v₂_f²; subtract KE eqn: v₁_f·v₂_f=0 → 90°']),
          ('A 3 kg ball moving at 6 m/s east strikes a 3 kg stationary ball elastically. What are the final velocities?', ['Equal mass elastic: first stops, second moves at 6 m/s east', 'v₁_f=0; v₂_f=6 m/s east', 'In 2D: same rule applies, but 90° between them', 'Head-on: 1D result applies']),
          ('In a 2D collision, why must you conserve momentum separately in x and y?', ['Momentum is a vector; x and y are independent', 'A collision can transfer x-momentum without affecting y-momentum', 'Each component conserved independently by Newton\'s laws', 'Cannot use magnitude alone — direction matters'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — 2D Collisions', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write the two momentum conservation equations for a 2D collision', 'Explain why you need both x and y equations', 'State the angle rule for equal-mass elastic 2D collisions']),
  ],
  'unit_qs': [
      ('A 500 N force acts for 0.04 s on a 0.1 kg ball. Find the impulse and resulting velocity change.', ['J=FΔt=500(0.04)=20 N·s', 'Δv=J/m=20/0.1=200 m/s', 'Impulse = 20 N·s', 'Large force, short time → large velocity change']),
      ('Find the CM of 5 kg at x=0, 3 kg at x=4 m, and 2 kg at x=9 m.', ['x_cm=(5(0)+3(4)+2(9))/(5+3+2)=(0+12+18)/10=30/10=3 m', 'CM at x=3 m', 'Weighted average of positions', 'Closer to heavier masses near x=0']),
      ('A 6 kg object at 4 m/s hits a stationary 2 kg object and sticks. Find final v and KE lost.', ['v_f=6(4)/(6+2)=24/8=3 m/s', 'KE_i=½(6)(16)=48 J; KE_f=½(8)(9)=36 J', 'KE lost=12 J (to thermal)', 'Perfectly inelastic']),
      ('A 4 kg object at 3 m/s east and 2 kg object at 9 m/s west collide and stick. Find final v.', ['p_i=4(3)+2(−9)=12−18=−6 kg·m/s', 'p_f=6v_f=−6 → v_f=−1 m/s', 'Moves west at 1 m/s', 'Total p was westward']),
      ('A gun (3 kg) fires a bullet (0.01 kg) at 400 m/s. Find recoil speed of gun.', ['p_i=0 (both at rest)', 'p_f=0.01(400)+3(−v_gun)=0', '4=3v_gun → v_gun=4/3≈1.33 m/s', 'Gun recoils at 1.33 m/s']),
      ('A 0.4 kg ball hits a wall at 15 m/s and bounces back at 10 m/s. Wall exerts force for 0.01 s. Find F_avg.', ['Δp=0.4(−10−15)=0.4(−25)=−10 N·s', 'F_avg=Δp/Δt=−10/0.01=−1000 N', 'Wall exerts 1000 N on ball (inward)', 'Magnitude: 1000 N']),
      ('Two 2 kg balls move toward each other at 5 m/s each. They collide elastically head-on. Find final velocities.', ['Equal mass elastic, head-on: they exchange velocities', 'Ball 1: now moves at 5 m/s in direction ball 2 was going', 'Ball 2: now moves at 5 m/s in direction ball 1 was going', 'They simply swap velocities']),
      ('Describe how the CM of a two-object system moves during a perfectly inelastic collision in empty space.', ['Before collision: CM has velocity v_cm=p_total/M (constant)', 'During collision: internal forces only; CM unaffected', 'After collision: CM continues at same velocity (equal to final velocity of stuck objects)', 'External forces = 0 → CM moves at constant velocity throughout']),
      ('A 3 kg cart at 6 m/s east collides and sticks with a 2 kg cart moving at 3 m/s west. Find final velocity.', ['p=3(6)+2(−3)=18−6=12 kg·m/s east', 'v_f=12/5=2.4 m/s east', 'Stays eastward', 'Heavier object dominates']),
      ('How does seatbelt physics use the impulse-momentum theorem?', ['Momentum change is fixed: Δp=m·Δv=same for any stopping method', 'Seatbelt extends stopping time (large Δt)', 'F_avg=Δp/Δt: larger Δt → smaller F_avg', 'Smaller force means less injury']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
},

{
  'num': 5, 'title': 'Torque and Rotational Motion',
  'file': 'ap-physics-1-2-5-physics-1-unit-5-momentum.html',
  'desc': 'Apply rotational analogues of Newton\'s laws to analyze torque, angular motion, and rotational equilibrium.',
  'gateway': [
      'Calculate torque using τ = rF sinθ.',
      'Apply conditions for rotational equilibrium (Στ = 0).',
      'Relate angular kinematics to linear kinematics.',
      'Apply Newton\'s second law for rotation: Στ = Iα.',
  ],
  'lessons': [
      _l('Torque',
         [_t('Torque Definition', 'τ = rF sinθ where r is the moment arm length, F is the force, and θ is the angle between r and F. Torque is the rotational equivalent of force.', 'Students use r as the distance to the force application point without accounting for the angle; τ = r × F × sinθ (or lever arm × F).', 'Calculate torque for various force directions using τ = r·F·sinθ or lever arm × F.'),
          _t('Lever Arm', 'The lever arm (or moment arm) is the perpendicular distance from the rotation axis to the line of action of the force. τ = lever arm × F.', 'Students confuse the distance to where force is applied with the lever arm; the lever arm is the perpendicular distance to the force\'s line of action.', 'Find the lever arm geometrically and calculate torque for angled forces.'),
          _t('Sign of Torque', 'Choose a sign convention: counterclockwise (CCW) positive, clockwise (CW) negative (or reverse). Must be consistent throughout a problem. Net torque = Στ determines rotation direction.', 'Students forget to assign signs to torques; a torque that produces CCW rotation must be opposite in sign to one producing CW rotation.', 'Assign correct signs to all torques and sum them to find net torque.')],
         [('torque', 'τ = rFsinθ; rotational effect of a force, unit N·m'),
          ('lever arm', 'Perpendicular distance from axis to force\'s line of action'),
          ('CCW positive convention', 'Counterclockwise torques are positive; clockwise are negative'),
          ('net torque', 'Στ = algebraic sum of all torques on an object')],
         ['Calculate torque from force and distance using the angle formula', 'Identify the lever arm for angled forces', 'Sum torques with correct signs to find net torque'],
         ['Torque calculations in both MC and FR', 'Lever arm must be identified geometrically in FR', 'Sign of torque crucial for equilibrium problems'],
         ['A 30 N force at 90° acts 0.5 m from pivot; find τ', 'A 40 N force at 30° from horizontal acts 0.8 m from pivot; find τ'],
         [('A 20 N force acts perpendicular to a 0.6 m wrench. Find torque.', ['τ=rFsinθ=0.6(20)sin90°=12 N·m', 'Maximum torque when force is perpendicular (θ=90°)', 'Direction: depends on rotation caused', 'τ=12 N·m']),
          ('A 50 N force acts at 30° to a 1 m rod. Find torque about the pivot at one end.', ['τ=rFsinθ=1(50)sin30°=1(50)(0.5)=25 N·m', 'Alternatively: lever arm=1·sin30°=0.5 m; τ=50(0.5)=25 N·m', 'Both methods give same answer', 'If perpendicular, would get 50 N·m']),
          ('Find net torque about point A: 30 N upward at 2 m right; 20 N upward at 3 m left.', ['Assume CCW positive', '30 N at 2 m right of A: produces CCW → +30(2)=+60 N·m', '20 N at 3 m left of A: produces CW → −20(3)=−60 N·m', 'Net torque = 0 → rotational equilibrium']),
          ('A 40 N force acts horizontally 0.3 m above the pivot. Find the torque.', ['The perpendicular distance from horizontal force to pivot is the vertical distance', 'Lever arm = 0.3 m', 'τ=40(0.3)=12 N·m', 'Force direction matters for lever arm identification']),
          ('A wrench applies more torque with a longer handle. Explain using the torque formula.', ['τ=rFsinθ; longer handle means larger r', 'For same applied force F, torque increases linearly with r', 'This is why long wrenches are easier to use on stuck bolts', 'Torque ∝ lever arm'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Torque', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write the torque formula and identify each symbol', 'Find the lever arm for a 45° force applied 1 m from pivot', 'Determine if a torque is CW or CCW for a given force']),

      _l('Rotational Equilibrium',
         [_t('Conditions for Static Equilibrium', 'For static equilibrium: (1) ΣF=0 (translational equilibrium) and (2) Στ=0 (rotational equilibrium). Both must hold. The torque equation can be taken about any convenient pivot point.', 'Students apply only ΣF=0; rotational equilibrium (Στ=0) is an additional independent condition required for static equilibrium.', 'Apply both ΣF=0 and Στ=0 to solve for unknown forces in static equilibrium problems.'),
          _t('Choosing the Pivot Point', 'Choose the pivot where an unknown force acts to eliminate it from the torque equation. This simplifies the algebra significantly.', 'Students take torques about an arbitrary point that includes unknowns; strategic pivot choice eliminates unknowns.', 'Select the pivot to minimize unknowns in the torque equation; explain why the choice simplifies the solution.'),
          _t('Uniform Beam Problems', 'A uniform beam has its weight acting at its geometric center (CM). For beam problems: identify all forces (weight, supports, applied loads), write ΣF=0 and Στ=0.', 'Students forget the beam\'s own weight at the center; every object has weight acting at its CM.', 'Include the weight of the beam at its midpoint when setting up equilibrium equations for beam problems.')],
         [('translational equilibrium', 'ΣF=0 in all directions'),
          ('rotational equilibrium', 'Στ=0 about any pivot'),
          ('static equilibrium', 'Both ΣF=0 and Στ=0; object at rest'),
          ('uniform beam weight', 'Acts at geometric center; always include in torque sum')],
         ['Apply both equilibrium conditions to solve for unknown forces', 'Choose strategic pivot points to simplify torque equations', 'Solve uniform beam problems with multiple support forces'],
         ['Beam equilibrium is a classic AP® Physics FR problem', 'Must write both ΣF=0 and Στ=0 explicitly', 'Pivot choice strategy tested in MC and FR'],
         ['A 4 m uniform beam (20 kg) rests on two supports at ends; find support forces', 'A 6 m beam supported at left end and 1 m from right end with 100 N load at right end'],
         [('A uniform 3 m, 10 kg beam is supported at both ends. A 30 kg person stands 1 m from the left. Find support forces (g=10).', ['Weight of beam: 100 N at center (1.5 m)', 'Person\'s weight: 300 N at 1 m', 'Take torques about left support: F_R(3)=100(1.5)+300(1)', 'F_R=250/3≈83.3 N; F_L=400−83.3=316.7 N']),
          ('A horizontal beam extends 2 m from a wall (hinge). A rope at 30° to the horizontal supports the far end. A 50 N weight hangs at 1.5 m. Beam weight 20 N at center. Find rope tension.', ['Take torques about hinge (eliminates hinge force)', 'Rope component causing torque: T sin30°=T/2', 'Στ=0: T/2(2)=50(1.5)+20(1)', 'T(1)=75+20=95 → T=95 N']),
          ('Explain why taking torques about the hinge simplifies the problem.', ['Hinge exerts unknown force (two components)', 'Taking torque about hinge: hinge force has zero lever arm', 'It drops out of the torque equation', 'One equation in one unknown (tension)']),
          ('A 5 m uniform 40 kg ladder leans against a frictionless wall at 60°. Find normal forces (g=10).', ['ΣF_y=0: FN_floor=mg=400 N', 'ΣF_x=0: FN_wall=f_floor', 'Take τ about base: FN_wall(5sin60°)=400(2.5cos60°)', 'FN_wall=400(1.25)/4.33≈115.5 N=f_floor']),
          ('A person stands on a uniform plank (m=20 kg) balanced at one end on a support. Where is the support?', ['If balanced at one end, support must be at the CM (center) for a uniform beam', 'CM at L/2 from one end', 'Actually if cantilevered: support would have to exert enough torque', 'Simplest answer: support at CM of plank (L/2)'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Rotational Equilibrium', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State the two conditions for static equilibrium', 'Explain how to choose the best pivot point', 'Find support forces for a 4 m uniform 30 kg beam with 50 N load at the right end']),

      _l('Rotational Kinematics and Dynamics',
         [_t('Angular Kinematic Quantities', 'Angular position θ (radians), angular velocity ω (rad/s), angular acceleration α (rad/s²). Equations mirror linear kinematics: ω=ω₀+αt; θ=ω₀t+½αt²; ω²=ω₀²+2αθ.', 'Students mix linear and angular equations; angular equations use θ, ω, α; linear use x, v, a. Use arc length s=rθ and v=rω to connect them.', 'Apply angular kinematic equations to rotating objects; convert between angular and linear quantities using s=rθ and v=rω.'),
          _t('Newton\'s Second Law for Rotation', 'Στ_net = Iα where I is the moment of inertia (I=Σmr² for point masses). The angular equivalent of F=ma.', 'Students use F=ma for rotational problems; for rotation, use Στ=Iα, where I depends on mass distribution.', 'Apply Στ=Iα to find angular acceleration from net torque and moment of inertia.'),
          _t('Moment of Inertia', 'I = Σmᵢrᵢ² for point masses. For extended objects: disk I=½MR², solid sphere I=2/5MR², rod about center I=1/12ML². Larger I means harder to angularly accelerate.', 'Students think I=MR² for all objects; I depends on how mass is distributed relative to the axis.', 'Identify the correct I formula for the shape, calculate I, and use in Στ=Iα.')],
         [('angular velocity', 'ω = Δθ/Δt; rad/s'),
          ('angular acceleration', 'α = Δω/Δt; rad/s²'),
          ('moment of inertia', 'I = Σmr²; resistance to angular acceleration'),
          ('Στ=Iα', 'Rotational Newton\'s second law')],
         ['Apply angular kinematic equations to rotating systems', 'Apply Στ=Iα to find angular acceleration', 'Calculate moment of inertia for point mass systems'],
         ['Angular kinematics tested in MC using τ=Iα', 'Moment of inertia tables not needed — AP® gives I formulas', 'Converting between linear and angular with v=rω'],
         ['A disk (I=2 kg·m²) has τ=6 N·m applied; find α', 'A point mass (0.5 kg) at 0.4 m from axis; calculate I'],
         [('A disk with I=3 kg·m² starts from rest. A torque of 9 N·m is applied for 4 s. Find ω.', ['α=τ/I=9/3=3 rad/s²', 'ω=ω₀+αt=0+3(4)=12 rad/s', 'Angular speed after 4 s = 12 rad/s', 'θ=½αt²=½(3)(16)=24 rad']),
          ('A 0.3 kg ball on a 0.5 m string spins in a circle. Find its moment of inertia about the center.', ['I=mr²=0.3(0.5)²=0.3(0.25)=0.075 kg·m²', 'Point mass approximation', 'All mass at same radius', 'I=0.075 kg·m²']),
          ('A 2 m uniform rod (mass 1.2 kg) rotates about one end. Find I.', ['For rod about end: I=1/3ML²=1/3(1.2)(4)=1.6 kg·m²', 'About center: I=1/12ML²=0.4 kg·m² (less)', 'More mass near axis → smaller I', 'Formula given on AP® reference sheet']),
          ('Relate linear speed v of a point on a rotating disk to ω.', ['v=rω where r is distance from axis', 'Points farther from axis move faster', 'All points have same ω (same angular speed)', 'Outer edge has greater v than inner edge']),
          ('A grinding wheel (I=0.5 kg·m²) decelerates from 20 rad/s to 0. Find torque if it stops in 5 s.', ['α=(0−20)/5=−4 rad/s²', 'τ=Iα=0.5(−4)=−2 N·m', 'Magnitude: 2 N·m (friction torque)', 'Negative sign: torque opposes rotation'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Bozeman Science — Rotational Kinematics', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['Write the rotational analogue of F=ma', 'Find I for a 1 kg mass on a 0.6 m string', 'Explain why I is different for a disk vs. a ring of same mass']),

      _l('Angular Momentum',
         [_t('Angular Momentum', 'L = Iω for a rigid body rotating about a fixed axis. Unit: kg·m²/s. L is a vector (direction given by right-hand rule): curl fingers in rotation direction, thumb points in L direction.', 'Students compute L=Iω and forget that L is a vector; direction is determined by the right-hand rule for the axis of rotation.', 'Calculate angular momentum and state its direction using the right-hand rule.'),
          _t('Conservation of Angular Momentum', 'If the net external torque is zero, angular momentum is conserved: L_i = L_f (Iω_i = Iω_f). When I decreases (e.g., arms pulled in), ω increases to maintain L.', 'Students think ω is conserved; it is L=Iω that is conserved. If I changes, ω changes oppositely.', 'Apply conservation of angular momentum to spinning skater, collapsing star, and rolling problems.'),
          _t('Angular Impulse', 'τ_net·Δt = ΔL (angular impulse-momentum theorem). Analogous to J=FΔt=Δp. A net torque over time changes angular momentum.', 'Students forget that angular impulse (not torque alone) changes L; just as force changes linear momentum, torque over time changes angular momentum.', 'Apply angular impulse-momentum theorem to find change in angular momentum from a torque applied over time.')],
         [('angular momentum', 'L = Iω; rotational analogue of linear momentum'),
          ('conservation of L', 'If Στ_ext=0, then L_i=L_f; Iω=constant'),
          ('right-hand rule', 'Curl fingers in rotation direction; thumb = L direction'),
          ('angular impulse', 'τ·Δt = ΔL; rotational analogue of FΔt=Δp')],
         ['Calculate angular momentum of rotating objects', 'Apply conservation of angular momentum when I changes', 'Use angular impulse-momentum theorem'],
         ['Conservation of L tested in skater/diver problems in MC and FR', 'L direction (right-hand rule) in MC', 'Angular impulse in FR'],
         ['A skater with I=4 kg·m² at ω=3 rad/s pulls arms in to I=1 kg·m²; find new ω', 'Apply τ=5 N·m for 2 s to a stationary disk; find final L'],
         [('A spinning skater has I=4 kg·m² and ω=2 rad/s. She pulls in arms to I=1 kg·m². Find new ω.', ['L_i=Iω=4(2)=8 kg·m²/s', 'L_f=L_i=8 (no external torque)', '1·ω_f=8 → ω_f=8 rad/s', 'Angular speed quadruples when I quarters']),
          ('A stationary disk (I=2 kg·m²) has τ=6 N·m applied for 3 s. Find final angular momentum.', ['ΔL=τ·Δt=6(3)=18 kg·m²/s', 'L_f=0+18=18 kg·m²/s', 'ω_f=L/I=18/2=9 rad/s', 'Angular impulse → angular momentum']),
          ('A star collapses from radius R to R/10. By what factor does ω increase? (Assume uniform sphere: I=2/5MR²)', ['I_i=2/5M R²; I_f=2/5M(R/10)²=I_i/100', 'L_i=L_f: I_i·ω_i=I_f·ω_f', 'ω_f=ω_i·(I_i/I_f)=100ω_i', 'Angular speed increases by factor of 100']),
          ('A ball on a string swings in a horizontal circle. The string is shortened. Does ω change?', ['Shortening string reduces r, reducing I (I=mr²)', 'Angular momentum L=Iω is conserved (no torque)', 'I decreases → ω increases', 'Yes, ω increases']),
          ('Determine the direction of angular momentum for a wheel spinning counterclockwise as viewed from above.', ['Use right-hand rule: curl fingers counterclockwise', 'Thumb points upward', 'L points upward (out of the page)', 'CCW from above → L upward'])],
         [('https://www.youtube.com/watch?v=Yd1RgfCjLC8', 'Flipping Physics — Angular Momentum', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
         ['State conservation of angular momentum condition', 'Calculate new ω when a skater doubles their moment of inertia', 'Apply right-hand rule to find the direction of L for a spinning disk']),
  ],
  'unit_qs': [
      ('A 40 N force acts at 2 m from pivot at 60° to the lever arm. Find torque.', ['τ=rFsinθ=2(40)sin60°=2(40)(√3/2)=40√3≈69.3 N·m', 'Sin(60°) accounts for the angle', 'Would be 80 N·m if perpendicular', 'τ≈69.3 N·m']),
      ('A uniform 4 m, 30 kg beam is supported at both ends. Find support forces if a 50 kg person stands 1 m from left (g=10).', ['Total weight: 300+500=800 N', 'Take τ about left support: F_R(4)=300(2)+500(1)', 'F_R=1100/4=275 N', 'F_L=800−275=525 N']),
      ('A disk (I=5 kg·m²) starts from rest under τ=15 N·m. Find ω after 6 s.', ['α=τ/I=15/5=3 rad/s²', 'ω=αt=3(6)=18 rad/s', 'θ=½αt²=½(3)(36)=54 rad', 'ω=18 rad/s']),
      ('A spinning skater has L=12 kg·m²/s. She increases I from 3 to 4 kg·m². Find new ω.', ['L conserved: L=Iω', 'ω_f=L/I_f=12/4=3 rad/s', 'ω_i=L/I_i=12/3=4 rad/s', 'ω decreased as I increased']),
      ('A 0.2 kg ball on a 0.8 m string rotates at 5 rad/s. Find L.', ['I=mr²=0.2(0.64)=0.128 kg·m²', 'L=Iω=0.128(5)=0.64 kg·m²/s', 'Direction by right-hand rule', 'L=0.64 kg·m²/s']),
      ('Apply τ=8 N·m for 4 s to a disk initially at ω=2 rad/s with I=2 kg·m². Find final ω.', ['ΔL=τΔt=8(4)=32 kg·m²/s', 'L_i=Iω_i=2(2)=4 kg·m²/s', 'L_f=4+32=36 kg·m²/s', 'ω_f=36/2=18 rad/s']),
      ('A 60 N force is applied at the end of a 1.5 m door perpendicular to the door. Find torque about the hinges.', ['τ=rFsinθ=1.5(60)sin90°=90 N·m', 'Force perpendicular: maximum torque', 'Hinges are the pivot', 'τ=90 N·m']),
      ('A rod (I=1/12ML², M=2 kg, L=3 m) rotates about its center. Find I and α if τ=6 N·m.', ['I=1/12(2)(9)=1.5 kg·m²', 'α=τ/I=6/1.5=4 rad/s²', 'Matches linear analogue: a=F/m', 'α=4 rad/s²']),
      ('Explain why a diver pulls into a tuck position during a flip.', ['In tuck: arms/legs close to body → smaller I', 'Conservation of L: Iω=constant', 'Smaller I → larger ω (faster spin)', 'Can complete more rotations before entering water']),
      ('A 5 m uniform 50 kg beam is supported by a rope at the right end and a pivot at the left. Find rope tension (g=10).', ['Take τ about left pivot (eliminate pivot force)', 'Rope tension T acts upward at right end', 'T(5)=mg(2.5)=50(10)(2.5)=1250', 'T=250 N']),
  ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
},
]
