NAME        = 'AP® Physics C: Mechanics'
ABBREV      = 'physc'
SLUG        = 'ap-physics-c-mechanics'
COURSE_FILE = 'ap-physics-c-mechanics.html'
ACCENT_COLOR = '#10b981'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+C+Mechanics+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+C+'

COURSE_QS = [
    ('Newton\'s second law in rotational form states that the net torque equals',
     'τ_net = Iα — the product of moment of inertia and angular acceleration',
     ['τ = mv²/r', 'τ = Iω²', 'τ = rF (without moment of inertia)']),
    ('The moment of inertia of a system of point masses about an axis is',
     'I = Σmᵢrᵢ² — the sum of each mass times its distance squared from the axis',
     ['I = mr (linear, not squared)', 'I = Σmᵢ/rᵢ²', 'I = total mass × radius of gyration / 2']),
    ('The parallel axis theorem states that',
     'I = I_cm + Md² — the moment of inertia about any axis equals I_cm plus mass times distance squared',
     ['I = I_cm × d²', 'I = I_cm / Md²', 'I_cm = I + Md²']),
    ('Angular momentum L of a rigid body is conserved when',
     'the net external torque on the system is zero',
     ['the net external force is zero', 'the object is in static equilibrium', 'kinetic energy is conserved']),
    ('The work-energy theorem for rotation states that',
     'W_net = ΔKE_rot = Δ(½Iω²) — net rotational work equals change in rotational kinetic energy',
     ['W = τ × t (torque times time)', 'W = Iω (not squared)', 'W = Fv (translational only)']),
    ('Universal gravitation states F = Gm₁m₂/r², where F is',
     'attractive, directed along the line connecting the two masses',
     ['repulsive for like-sign masses', 'attractive only for spherical objects', 'proportional to distance (not inverse square)']),
    ('Escape velocity is the minimum speed needed to',
     'leave a gravitational field without further propulsion: v_esc = √(2GM/R)',
     ['achieve circular orbit at height R', 'escape Earth\'s atmosphere only', 'travel from one planet to another']),
    ('Kepler\'s third law states that the square of the orbital period is',
     'proportional to the cube of the semi-major axis: T² ∝ a³',
     ['inversely proportional to orbital speed', 'proportional to the square of the radius only', 'equal to the orbital speed squared']),
    ('Simple harmonic motion (SHM) is characterized by a restoring force that is',
     'proportional to and opposite in sign to the displacement from equilibrium',
     ['constant regardless of displacement', 'proportional to velocity', 'always directed upward']),
    ('The angular frequency ω of a mass-spring system is',
     'ω = √(k/m) — independent of amplitude',
     ['ω = √(m/k)', 'ω = 2πf/m', 'ω = mg/k']),
    ('In a two-body collision, conservation of linear momentum requires',
     'the total momentum before equals total momentum after: Σp_before = Σp_after',
     ['kinetic energy is conserved in all collisions', 'the objects must stick together', 'the net external force may be nonzero']),
    ('A perfectly inelastic collision is one in which',
     'the colliding objects stick together and move as one; kinetic energy is not conserved',
     ['kinetic energy is fully conserved', 'the objects bounce apart elastically', 'momentum is not conserved']),
    ('Power is defined in mechanics as',
     'P = dW/dt = F·v — the rate at which work is done',
     ['P = W/d (work divided by distance)', 'P = F/v', 'P = mv²']),
    ('A conservative force is one where',
     'the work done is path-independent; potential energy can be defined (e.g., gravity, spring force)',
     ['the force is always directed downward', 'the work done is always positive', 'the force acts over infinite distance']),
    ('The center of mass of a system moves as if',
     'all external forces act on the total mass concentrated at that point',
     ['internal forces are the only forces acting', 'the system has no angular momentum', 'no external forces act on the system']),
    ('In circular motion, the centripetal acceleration is directed',
     'toward the center of the circle with magnitude v²/r = ω²r',
     ['tangent to the circle', 'away from the center (centrifugal)', 'in the direction of increasing speed']),
    ('The impulse-momentum theorem states that',
     'J = ΔP = F_avg × Δt — impulse equals the change in momentum',
     ['F = ma (Newton\'s second law only)', 'J = mv² − mv₀²', 'J = W/v (work divided by velocity)']),
    ('Rolling without slipping requires that the contact point\'s velocity is',
     'zero (v_contact = 0): the velocity of the center equals ωR',
     ['equal to the center of mass velocity', 'twice the rotational velocity', 'equal to the translational plus rotational velocity']),
    ('In simple harmonic motion, when displacement is maximum, velocity is',
     'zero, and when displacement is zero (equilibrium), velocity is maximum',
     ['also maximum', 'equal to ω times displacement', 'always constant']),
    ('The gravitational potential energy of an object at height h above Earth\'s surface (near-surface) is',
     'U = mgh (taking the surface as reference)',
     ['U = −GMm/h', 'U = mv²/2', 'U = mgh² (squared)']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content,
            'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 1, 'title': 'Kinematics',
        'file': 'ap-physics-c-mechanics-1-unit-1-kinematics.html',
        'desc': 'Calculus-based 1D and 2D motion: derivatives and integrals applied to position, velocity, and acceleration.',
        'gateway': [
            'Differentiate position to obtain velocity and acceleration functions.',
            'Integrate acceleration to recover velocity and position.',
            'Solve 2D projectile motion using component analysis.',
            'Apply kinematic equations and graphical interpretation.',
        ],
        'lessons': [
            _l('Position, Velocity, and Acceleration via Calculus',
               [_t('Derivative Definitions of v and a', 'Velocity is the derivative of position: v(t) = dx/dt. Acceleration is the derivative of velocity: a(t) = dv/dt = d²x/dt². These are exact, not approximations.', 'Average velocity (Δx/Δt) is the slope of the secant; instantaneous velocity is the slope of the tangent (derivative).', 'Given x(t), find v(t) and a(t) by differentiation.'),
                _t('Integral Definitions', 'Position change: Δx = ∫v dt. Velocity change: Δv = ∫a dt. The constant of integration is determined by initial conditions.', 'Indefinite integrals produce functions with a constant C; definite integrals give numerical displacements over an interval.', 'Given a(t), integrate to find v(t) and x(t) with initial conditions.'),
                _t('Graphical Interpretation', 'Slope of x-t graph = v; slope of v-t graph = a; area under v-t graph = Δx; area under a-t graph = Δv.', 'Area under an a-t graph is Δv, not v — it gives the CHANGE in velocity.', 'Sketch or interpret x(t), v(t), a(t) graphs and relate them.')],
               [('x(t)', 'Position as a function of time'),
                ('v(t) = dx/dt', 'Instantaneous velocity; slope of x-t graph'),
                ('a(t) = dv/dt', 'Instantaneous acceleration; slope of v-t graph'),
                ('Δx = ∫v dt', 'Displacement equals area under v-t graph'),
                ('Initial conditions', 'Values of x₀ and v₀ used to evaluate constants of integration')],
               ['Differentiate position functions to find velocity and acceleration.',
                'Integrate acceleration (with initial conditions) to find velocity and position.',
                'Relate graphical slopes and areas to kinematic quantities.'],
               ['Free-response: given x(t) = 3t³ - 5t, find v and a as functions of t.',
                'Integration: given a(t) = 6t and v(0) = 2, find v(t) and x(t) with x(0) = 0.',
                'Graph interpretation: sketch a-t, v-t, x-t for a given a(t).'],
               ['Differentiate and integrate polynomial, sinusoidal, and exponential position functions.',
                'Practice finding constants of integration using initial conditions.'],
               [('Given x(t) = 4t³ - 6t² + 2, find v(t) and a(t).', ['v(t) = dx/dt = 12t² - 12t', 'a(t) = dv/dt = 24t - 12', 'Use power rule: d/dt(tⁿ) = ntⁿ⁻¹', 'Constants differentiate to zero']),
                ('Given a(t) = 3t - 2, v(0) = 5, x(0) = 0. Find x(t).', ['v(t) = ∫(3t - 2)dt = (3/2)t² - 2t + C₁; v(0) = 5 → C₁ = 5', 'v(t) = (3/2)t² - 2t + 5', 'x(t) = ∫v dt = (1/2)t³ - t² + 5t + C₂; x(0) = 0 → C₂ = 0', 'x(t) = (1/2)t³ - t² + 5t']),
                ('A v-t graph shows v increasing linearly from 0 to 20 m/s over 4 s. Find displacement.', ['Δx = area under v-t graph = area of triangle', 'Δx = ½ × base × height = ½ × 4 × 20 = 40 m', 'Also: a = Δv/Δt = 20/4 = 5 m/s²; Δx = ½at² = ½(5)(16) = 40 m', 'Both methods give same answer']),
                ('If x(t) = A sin(ωt), find v(t) and a(t).', ['v(t) = dx/dt = Aω cos(ωt)', 'a(t) = dv/dt = -Aω² sin(ωt) = -ω²x(t)', 'This shows that a ∝ -x: classic SHM condition', 'Amplitude of v is Aω; amplitude of a is Aω²']),
                ('Explain the difference between average and instantaneous velocity.', ['Average velocity: v_avg = Δx/Δt over a finite time interval', 'Instantaneous velocity: v = lim(Δt→0) Δx/Δt = dx/dt', 'Instantaneous is the limit of average as interval shrinks to zero', 'Only instantaneous velocity appears in Newton\'s laws'])],
               [('Bozeman Calculus Kinematics', 'Derivatives and integrals applied to motion', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Calculus Motion', 'x(t), v(t), a(t) with calculus', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['v = dx/dt; a = dv/dt — exact calculus definitions.',
                'Integrate a (with initial conditions) to recover v and x.',
                'Graphical: slope → derivative; area → integral.']),

            _l('1D Kinematics: Constant and Variable Acceleration',
               [_t('Constant Acceleration Equations', 'For constant a: v = v₀ + at, x = x₀ + v₀t + ½at², v² = v₀² + 2aΔx. These are derived from integration of a = const.', 'These equations ONLY apply when acceleration is constant — do not use them if a varies with t.', 'Solve 1D kinematics problems analytically and verify with integrals.'),
                _t('Variable Acceleration', 'When a is not constant, use a(t) directly: integrate to get v(t), integrate again to get x(t). Numerical methods or exact integration may be required.', 'Constant-acceleration equations give wrong answers for variable acceleration — always check if a is constant.', 'Solve problems where a = f(t) using integration.'),
                _t('Jerk', 'Jerk j = da/dt = d³x/dt³ is the rate of change of acceleration. It appears in smooth motion design (elevators, vehicles).', 'Jerk is not commonly tested in AP® C but appears in questions about smoothness of motion.', 'Differentiate a(t) to find jerk; integrate j(t) to find a(t).')],
               [('Constant acceleration equations', 'v = v₀ + at; x = x₀ + v₀t + ½at²; v² = v₀² + 2aΔx'),
                ('Free fall', 'Constant downward acceleration g = 9.8 m/s² near Earth\'s surface'),
                ('Variable acceleration', 'a = f(t); requires integration to find v and x'),
                ('Jerk', 'j = da/dt = d³x/dt³; rate of change of acceleration'),
                ('Integration constant C', 'Determined by initial conditions v(0) = v₀, x(0) = x₀')],
               ['Derive and apply constant-acceleration equations using integration.',
                'Solve variable-acceleration problems using definite integrals.',
                'Identify when constant-acceleration assumptions break down.'],
               ['AP® free-response: derive v = v₀ + at by integrating a = const.',
                'Problem: a(t) = 6t²; given v(0) = 3, x(0) = 0, find x at t = 2 s.',
                'Conceptual: identify which equation applies to which scenario.'],
               ['Derive the three constant-acceleration equations from v = v₀ + at.',
                'Practice integration problems with polynomial a(t).'],
               [('A car accelerates from rest with a(t) = 2t m/s². Find v and x at t = 3 s.', ['v(t) = ∫2t dt = t² + C; v(0) = 0 → C = 0; v(t) = t²', 'v(3) = 9 m/s', 'x(t) = ∫t² dt = t³/3 + C; x(0) = 0; x(t) = t³/3', 'x(3) = 27/3 = 9 m']),
                ('Derive x = x₀ + v₀t + ½at² from a = const by integration.', ['a = const → v = ∫a dt = at + C₁; v(0) = v₀ → v = v₀ + at', 'x = ∫v dt = ∫(v₀ + at) dt = v₀t + ½at² + C₂', 'x(0) = x₀ → x = x₀ + v₀t + ½at²', 'This is the exact result from integration']),
                ('A ball is dropped from rest from 80 m. Find time to hit ground and impact speed.', ['y = ½gt² → 80 = ½(9.8)t² → t² = 16.33 → t ≈ 4.04 s', 'v = gt = 9.8 × 4.04 ≈ 39.6 m/s', 'Or: v² = 2gΔy = 2(9.8)(80) = 1568; v ≈ 39.6 m/s', 'Both methods agree']),
                ('Why can\'t you use v = v₀ + at when a depends on time?', ['The equation v = v₀ + at assumes a is constant throughout the interval', 'For variable a, v = v₀ + ∫₀ᵗ a(t\') dt\'', 'Using constant-a equation with variable a gives incorrect displacement and velocity', 'Always verify that acceleration is constant before applying kinematic equations']),
                ('Given a(t) = -4 (constant) m/s², v(0) = 12 m/s, x(0) = 0. When and where does the object stop?', ['v = 0: 12 - 4t = 0 → t = 3 s', 'x(3) = 12(3) - ½(4)(9) = 36 - 18 = 18 m', 'Object stops at x = 18 m after 3 s', 'After t = 3 s it moves in reverse (a still -4 m/s²)'])],
               [('Bozeman Constant Acceleration', 'Kinematic equations and integration derivation', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Variable a', 'Variable acceleration integration problems', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Constant-a equations derived from integration of a = const.',
                'Variable a: always integrate a(t) with initial conditions.',
                'Jerk j = da/dt; appears in smooth-motion design.']),

            _l('2D Kinematics: Projectile and Circular Motion',
               [_t('Projectile Motion', 'Decompose into x (constant v_x) and y (a_y = -g). x(t) = x₀ + v_x t; y(t) = y₀ + v_y0 t - ½gt². Horizontal and vertical are independent.', 'Air resistance is neglected in AP® projectile problems unless stated; horizontal speed is constant throughout.', 'Solve for range, max height, time of flight using component equations.'),
                _t('Uniform Circular Motion', 'Speed is constant but direction changes; centripetal acceleration a_c = v²/r directed toward center. Period T = 2πr/v; frequency f = 1/T.', 'Centripetal acceleration changes direction of velocity, not its magnitude — the object is accelerating even at constant speed.', 'Calculate centripetal acceleration and net centripetal force for circular motion.'),
                _t('Non-Uniform Circular Motion', 'When speed changes in circular motion, there is both centripetal acceleration (a_c = v²/r, toward center) and tangential acceleration (a_t = dv/dt, along path).', 'The total acceleration vector is the vector sum of centripetal and tangential components.', 'Find magnitude and direction of total acceleration in non-uniform circular motion.')],
               [('Projectile', 'Object under gravity alone; a_x = 0, a_y = -g'),
                ('Range', 'Horizontal distance traveled by a projectile'),
                ('Centripetal acceleration', 'a_c = v²/r directed toward center of circular path'),
                ('Period T', 'Time for one complete revolution in circular motion'),
                ('Tangential acceleration', 'a_t = dv/dt; component along the velocity direction in circular motion')],
               ['Solve projectile problems by separating x and y components.',
                'Calculate centripetal acceleration and associated centripetal force.',
                'Find total acceleration vector components in non-uniform circular motion.'],
               ['Free-response: find range and time of flight for projectile launched at angle θ.',
                'Calculation of centripetal force on a car rounding a curve.',
                'Non-uniform: find tangential and centripetal acceleration at a given instant.'],
               ['Solve projectile problems systematically by listing x and y equations separately.',
                'Practice centripetal force problems with various geometries.'],
               [('A projectile is launched at 30° above horizontal with v₀ = 40 m/s. Find range. (g = 9.8 m/s²)', ['v_x = 40 cos30° = 34.64 m/s; v_y0 = 40 sin30° = 20 m/s', 'Time of flight: t = 2v_y0/g = 2(20)/9.8 = 4.08 s', 'Range = v_x × t = 34.64 × 4.08 = 141 m', 'Or: R = v₀² sin(2θ)/g = 1600(sin60°)/9.8 = 141 m']),
                ('A 1000 kg car rounds a flat curve of radius 50 m at 20 m/s. Find centripetal force.', ['F_c = mv²/r = 1000(400)/50 = 8000 N', 'This force is provided by static friction from the road', 'If friction < 8000 N, car slides outward', 'Centripetal force is directed toward center of the curve']),
                ('An object moves on a circle with r = 4 m. At some instant v = 6 m/s and dv/dt = 3 m/s². Find total acceleration magnitude.', ['a_c = v²/r = 36/4 = 9 m/s² (toward center)', 'a_t = dv/dt = 3 m/s² (tangential)', 'a_total = √(a_c² + a_t²) = √(81 + 9) = √90 ≈ 9.49 m/s²', 'Direction: angle from centripetal = arctan(3/9) ≈ 18.4°']),
                ('Why is centripetal acceleration directed toward the center?', ['Velocity vector is tangent to circle; for direction to change, Δv must point toward center', 'As Δt → 0, Δv/Δt points toward center of curvature', 'This is a consequence of constant-speed circular motion geometry', 'Without centripetal force, object would continue in a straight line (Newton\'s 1st law)']),
                ('At maximum range, what angle should a projectile be launched? Prove using calculus.', ['R = v₀² sin(2θ)/g; maximize over θ', 'dR/dθ = v₀²(2 cos2θ)/g = 0 → cos2θ = 0 → 2θ = 90°', 'θ = 45° gives maximum range on flat ground', 'For unequal heights, optimal angle differs from 45°'])],
               [('Bozeman Projectile Motion', 'Component method for projectiles', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Circular Motion', 'Centripetal acceleration and force', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Projectile: x and y components are independent; a_x = 0, a_y = -g.',
                'Centripetal: a_c = v²/r toward center.',
                'Non-uniform: total a is vector sum of centripetal and tangential components.']),

            _l('Relative Motion and Reference Frames',
               [_t('Relative Velocity in 1D', 'Velocity of A relative to B: v_AB = v_A - v_B. Velocities add or subtract depending on direction of observation.', 'Relative velocity is not symmetric: v_AB = -v_BA.', 'Solve 1D relative-velocity problems (boats in rivers, trains).'),
                _t('Relative Velocity in 2D', 'In 2D, v_AB = v_A - v_B vectorially. For a boat crossing a river, the resultant velocity is the vector sum of boat velocity and current velocity.', 'To find shortest path across a river, aim the boat upstream at the right angle.', 'Solve river-crossing and airplane-wind problems using vector addition.'),
                _t('Non-Inertial Reference Frames', 'In an accelerating frame, pseudo-forces (fictitious forces) appear. An observer in a non-inertial frame sees fictitious forces opposite to the frame\'s acceleration.', 'Pseudo-forces are not real forces — they appear only in accelerating frames, not in inertial frames.', 'Describe motion from both inertial and non-inertial frames.')],
               [('Relative velocity', 'v_AB = v_A - v_B; velocity of A as seen by observer B'),
                ('Inertial frame', 'Reference frame with no acceleration; Newton\'s laws hold exactly'),
                ('Non-inertial frame', 'Accelerating reference frame where fictitious forces appear'),
                ('Pseudo-force', 'Apparent force in an accelerating frame = -ma_frame'),
                ('River crossing', 'Classic 2D relative motion problem with cross-current')],
               ['Calculate relative velocities in 1D and 2D.',
                'Solve boat/plane problems with vector addition of velocities.',
                'Describe fictitious forces in non-inertial frames.'],
               ['Free-response: find the heading for minimum crossing time vs. minimum drift.',
                'Multiple choice: determine velocity of one object relative to another.',
                'Conceptual: explain why passengers feel pushed back during acceleration.'],
               ['Practice river-crossing and airplane-wind vector problems.',
                'Compare the same motion described from different reference frames.'],
               [('A boat can travel 5 m/s in still water. A river flows east at 3 m/s. What is the boat\'s actual velocity when headed north?', ['v_boat_ground = v_boat_water + v_current', 'v = (3 m/s east) + (5 m/s north)', 'Magnitude: √(25 + 9) = √34 ≈ 5.83 m/s', 'Direction: θ = arctan(3/5) ≈ 31° east of north']),
                ('To cross the river directly (no drift), at what angle should the boat head?', ['Boat heads at angle θ west of north to cancel current', 'v_east = 5 sinθ - 3 = 0 → sinθ = 3/5 → θ = 36.9°', 'Boat aims 36.9° west of north', 'Effective northward speed = 5 cosθ = 5(0.8) = 4 m/s']),
                ('Train A moves east at 60 m/s; train B moves west at 40 m/s. Find v_A relative to B.', ['v_AB = v_A - v_B = 60 - (-40) = 100 m/s east', 'Observer on B sees A approaching at 100 m/s', 'This is NOT the relativistic result — valid for v << c', 'v_BA = -v_AB = -100 m/s (B sees itself as moving west at 100 m/s relative to A)']),
                ('Why does a person in an accelerating car feel pushed into the seat?', ['In the car\'s (non-inertial) frame, a pseudo-force acts backward = -ma_car', 'This is not a real force — no object exerts it', 'In an inertial frame: the seat pushes the person forward (Newton\'s 2nd law)', 'The sensation is the contact force from the seat accelerating the person']),
                ('An airplane heading north at 300 m/s encounters a crosswind of 40 m/s east. Find actual velocity.', ['v_actual = √(300² + 40²) = √(90000 + 1600) = √91600 ≈ 302.7 m/s', 'Direction: θ = arctan(40/300) ≈ 7.6° east of north', 'Pilot must correct heading to compensate for drift', 'To go directly north: head west of north at angle arcsin(40/300) ≈ 7.7°'])],
               [('Bozeman Relative Motion', 'Relative velocity and reference frames', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Reference Frames', 'River crossing and relative velocity problems', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['v_AB = v_A - v_B; not symmetric.',
                'River crossing: resultant = vector sum of boat + current velocities.',
                'Non-inertial frame: pseudo-force = -ma_frame appears to observers.']
        ),
        ],
        'unit_qs': [
            ('Given x(t) = 5t⁴ - 3t² + 7, find velocity and acceleration as functions of time.',
             ['v(t) = dx/dt = 20t³ - 6t', 'a(t) = dv/dt = 60t² - 6', 'At t = 1: v = 14 m/s, a = 54 m/s²', 'Use power rule: d/dt(tⁿ) = ntⁿ⁻¹']),
            ('Given a(t) = 12t - 6 m/s², with v(0) = 4 m/s and x(0) = 0. Find x(t) and x at t = 2 s.',
             ['v(t) = ∫(12t - 6)dt = 6t² - 6t + 4 (using v(0) = 4)', 'x(t) = ∫(6t² - 6t + 4)dt = 2t³ - 3t² + 4t (using x(0) = 0)', 'x(2) = 2(8) - 3(4) + 4(2) = 16 - 12 + 8 = 12 m', 'Always apply initial conditions after integrating']),
            ('A projectile is launched horizontally at 25 m/s from a 45 m cliff. Find time of flight, range, and impact speed.',
             ['t: y = ½gt² → 45 = ½(9.8)t² → t = √(90/9.8) ≈ 3.03 s', 'Range: x = v_x × t = 25 × 3.03 = 75.8 m', 'v_y at impact = gt = 9.8(3.03) = 29.7 m/s', 'Impact speed: √(25² + 29.7²) = √(625 + 882) ≈ 38.8 m/s']),
            ('Derive the range formula R = v₀² sin(2θ)/g for a projectile on level ground.',
             ['v_x = v₀cosθ; v_y0 = v₀sinθ', 'Time of flight: 0 = v_y0 t - ½gt² → t = 2v_y0/g = 2v₀sinθ/g', 'R = v_x × t = v₀cosθ × 2v₀sinθ/g = v₀²(2sinθcosθ)/g', 'R = v₀² sin(2θ)/g using double angle identity']),
            ('A car moves in a circle of radius 20 m. At one instant v = 10 m/s and the speed is increasing at 2 m/s². Find the total acceleration.',
             ['a_c = v²/r = 100/20 = 5 m/s² (toward center)', 'a_t = dv/dt = 2 m/s² (tangential, along velocity)', 'a_total = √(5² + 2²) = √29 ≈ 5.39 m/s²', 'Angle: arctan(2/5) ≈ 21.8° from centripetal direction']),
            ('A ball is thrown upward at 20 m/s. Find maximum height, time to top, and total time in air.',
             ['At top: v = 0 = 20 - 9.8t → t_top = 20/9.8 ≈ 2.04 s', 'h_max = v₀t - ½gt² = 20(2.04) - ½(9.8)(2.04²) ≈ 20.4 m', 'Total air time = 2 × t_top ≈ 4.08 s (symmetric)', 'Also: h_max = v₀²/(2g) = 400/19.6 ≈ 20.4 m']),
            ('Compare the instantaneous vs. average acceleration of an object following v(t) = t² over the interval t = 0 to t = 3 s.',
             ['Average a = Δv/Δt = (9 - 0)/(3 - 0) = 3 m/s²', 'Instantaneous a(t) = dv/dt = 2t', 'At t = 0: a = 0; at t = 3: a = 6 m/s²; average ≠ instantaneous', 'Instantaneous varies; average is the secant slope over the interval']),
            ('A 2 kg object moves in a circle of radius 0.5 m at constant speed 4 m/s. Find centripetal force magnitude and direction.',
             ['F_c = mv²/r = 2(16)/0.5 = 64 N', 'Direction: toward center of circle at all times', 'This is the NET force — provided by tension, friction, gravity, etc.', 'Centripetal force is not a new type of force — it is the name for the net inward force']),
            ('A boat heads perpendicular to a 60 m wide river flowing at 2 m/s. The boat\'s speed in still water is 4 m/s. Find time to cross and downstream drift.',
             ['Crossing time: t = width/v_boat = 60/4 = 15 s', 'Drift = v_current × t = 2 × 15 = 30 m downstream', 'Actual path length: √(60² + 30²) = √4500 ≈ 67 m', 'The boat does NOT head at an angle — it goes straight across']),
            ('An object has position x(t) = cos(ωt). Find when velocity is zero and when acceleration is maximum in magnitude.',
             ['v(t) = -ω sin(ωt); v = 0 when sin(ωt) = 0 → t = 0, π/ω, 2π/ω, ...', 'a(t) = -ω² cos(ωt); |a| max when |cos| = 1 → t = 0, π/ω, 2π/ω, ...', 'Velocity is zero exactly when acceleration is maximum', 'These are the turning points of oscillatory motion'])
        ]
    },

    {
        'num': 2, 'title': 'Newton\'s Laws of Motion',
        'file': 'ap-physics-c-mechanics-2-unit-2-force-and-translational-dynamics.html',
        'desc': 'Forces, free-body diagrams, Newton\'s laws in calculus-based form, friction, and constraint systems.',
        'gateway': [
            'Draw accurate free-body diagrams for systems with multiple forces.',
            'Apply ΣF = ma in component form to solve for acceleration and forces.',
            'Analyze systems connected by strings or surfaces using constraint equations.',
            'Distinguish static and kinetic friction and apply them correctly.',
        ],
        'lessons': [
            _l('Forces and Free-Body Diagrams',
               [_t('Types of Forces', 'Contact forces (normal, friction, tension, spring) and field forces (gravity, electric, magnetic). Normal force is perpendicular to the surface; friction is parallel.', 'Normal force is not always equal to weight — it depends on the surface orientation and other forces.', 'Draw FBDs for objects on inclines, in elevators, and in circular motion.'),
                _t('Free-Body Diagram Technique', 'Represent each object as a point; draw all forces acting ON the object (not by it); label with symbols; choose a coordinate system aligned with the acceleration.', 'Common error: including velocity or acceleration as forces — these are not forces.', 'Draw and label FBDs for multi-body problems with correct force identification.'),
                _t('Newton\'s Third Law', 'For every force, there is an equal and opposite reaction force acting on a different object. Newton\'s 3rd law pairs always act on different objects.', '3rd law pairs act on different objects and are always of the same type; do not include both in one object\'s FBD.', 'Identify Newton\'s 3rd law pairs in complex systems.')],
               [('Normal force N', 'Contact force perpendicular to a surface'),
                ('Tension T', 'Pulling force exerted by a rope or string along its length'),
                ('Friction f', 'Contact force parallel to surface opposing relative motion'),
                ('Free-body diagram (FBD)', 'Diagram showing all external forces on one object'),
                ('Newton\'s 3rd law pair', 'Equal and opposite forces on two different objects')],
               ['Draw complete, accurate FBDs for objects in various scenarios.',
                'Identify all forces acting on each object in a system.',
                'Apply Newton\'s 3rd law to identify action-reaction pairs.'],
               ['Free-response: draw FBD for box on an incline and an Atwood machine.',
                'Multiple choice: which forces are present on an object on a curved surface?',
                'Identify which forces belong to 3rd-law pairs in a given system.'],
               ['Practice FBDs for at least 5 different scenarios.',
                'Identify all 3rd-law pairs in a system of two connected blocks.'],
               [('Draw the FBD for a box resting on an inclined surface at angle θ.', ['Forces: weight W = mg downward, normal N perpendicular to incline, friction f up the incline (if stationary)', 'Weight components: W_parallel = mg sinθ (down incline), W_perp = mg cosθ (into incline)', 'N = mg cosθ in equilibrium; f ≤ μN', 'Acceleration (if any) is along the incline direction']),
                ('A book rests on a table. List all Newton\'s 3rd law pairs.', ['Book weight (Earth pulls book down) ↔ Book pulls Earth up', 'Table pushes book up (normal) ↔ Book pushes table down', 'These pairs act on different objects', 'The normal force and weight are NOT a 3rd-law pair (different types of force)']),
                ('Why is the normal force on a box in an elevator not always equal to mg?', ['N = m(g + a) when accelerating upward; N = m(g - a) when accelerating downward', 'At constant velocity: N = mg', 'In free fall: N = 0 (weightless)', 'Normal force provides the net vertical force needed for acceleration']),
                ('What is wrong with a FBD that shows "velocity" or "acceleration" as forces?', ['Velocity and acceleration describe motion, not forces', 'Forces cause acceleration — acceleration is the effect, not a cause', 'Only include actual forces (push, pull, gravity, friction) on the FBD', 'Showing ma as a force double-counts; use ΣF = ma separately']),
                ('Identify all forces on a skydiver at terminal velocity.', ['Weight W = mg downward (constant)', 'Air drag D upward (equals weight at terminal velocity)', 'ΣF = 0 → acceleration = 0 → constant velocity', 'No thrust, no normal force — only gravity and drag'])],
               [('Bozeman Free-Body Diagrams', 'Drawing and using FBDs in AP® Physics C', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Newton\'s Laws FBD', 'Force identification and FBD technique', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Normal ⊥ surface; tension along string; friction ∥ surface.',
                'FBD: only forces ON the object, not by it.',
                'Newton\'s 3rd law pairs always act on different objects.']),

            _l('Newton\'s Second Law: Applications',
               [_t('ΣF = ma in Components', 'Apply Newton\'s 2nd law separately in x and y (and z) directions. Align coordinate axes with the acceleration direction for simplicity.', 'The net force ΣF must be the vector sum of all forces — do not omit any.', 'Solve for unknown forces and accelerations using component equations.'),
                _t('Inclined Planes', 'On an incline at angle θ: a = g(sinθ - μcosθ) for sliding down with kinetic friction. Choose x along incline, y perpendicular.', 'On an incline, weight must be resolved into components — mg is not along or perpendicular to the incline.', 'Derive and apply the acceleration formula for an incline with friction.'),
                _t('Atwood Machine', 'Two masses over a frictionless pulley: a = (m₁ - m₂)g/(m₁ + m₂); T = 2m₁m₂g/(m₁ + m₂). Treat rope as single constraint.', 'In an Atwood machine, the two masses have the SAME magnitude of acceleration (connected by inextensible rope).', 'Set up and solve the Atwood machine equations with and without friction.')],
               [('Component equations', 'ΣFx = max; ΣFy = may applied separately'),
                ('Incline angle θ', 'Angle of slope; W_parallel = mg sinθ; W_perp = mg cosθ'),
                ('Kinetic friction', 'f_k = μ_k N; opposes direction of sliding motion'),
                ('Static friction', 'f_s ≤ μ_s N; adjusts to prevent motion up to maximum'),
                ('Atwood machine', 'Two masses on a pulley; constraint: |a₁| = |a₂|')],
               ['Apply ΣF = ma in component form to incline and pulley problems.',
                'Derive acceleration of an Atwood machine from first principles.',
                'Distinguish static and kinetic friction and apply correctly.'],
               ['Free-response: two blocks on a table connected by a string over a pulley.',
                'Incline: find minimum μ_s to prevent sliding.',
                'Atwood: find T and a given m₁ and m₂.'],
               ['Solve at least 5 incline problems with varying friction conditions.',
                'Derive the Atwood machine equations independently.'],
               [('A 5 kg block slides down a 30° incline with μ_k = 0.2. Find acceleration.', ['N = mg cos30° = 5(9.8)(0.866) = 42.5 N', 'f_k = μ_k N = 0.2(42.5) = 8.5 N', 'a = g(sin30° - μ_k cos30°) = 9.8(0.5 - 0.2×0.866) = 9.8(0.327) ≈ 3.20 m/s²', 'Acceleration is down the incline']),
                ('Atwood machine: m₁ = 3 kg, m₂ = 5 kg. Find acceleration and tension.', ['a = (m₂ - m₁)g/(m₁ + m₂) = (2)(9.8)/8 = 2.45 m/s²', 'T = 2m₁m₂g/(m₁+m₂) = 2(3)(5)(9.8)/8 = 36.75 N', 'Check: for m₂: 5(9.8) - T = 5a → 49 - 36.75 = 12.25 = 5(2.45) ✓', 'Both masses have the same |a| but opposite directions']),
                ('A 10 kg box on a flat surface has μ_s = 0.4. What minimum horizontal force causes it to slide?', ['Maximum static friction: f_s,max = μ_s × N = 0.4 × 10 × 9.8 = 39.2 N', 'Applied force must exceed 39.2 N to initiate sliding', 'Once sliding, f_k = μ_k N < f_s,max', 'Static friction adjusts up to this maximum before sliding occurs']),
                ('A person pushes a box up a wall with horizontal force F. Find minimum F to stop sliding. (μ_s, mass m)', ['Normal force N = F (from wall; horizontal force creates normal to wall)', 'Weight = mg downward; friction f = μ_s N = μ_s F upward (to stop downward slide)', 'For equilibrium: μ_s F = mg → F_min = mg/μ_s', 'Interesting: heavier object requires larger F']),
                ('Explain the difference between static and kinetic friction.', ['Static friction prevents relative motion; adjusts from 0 to f_s,max = μ_s N', 'Kinetic friction opposes sliding motion; f_k = μ_k N (constant)', 'μ_s > μ_k always: harder to start sliding than to maintain it', 'Static friction is variable; kinetic friction is constant at f_k = μ_k N'])],
               [('Bozeman Newton\'s 2nd Law Applications', 'Inclines, Atwood machine, multi-body systems', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Atwood Machine', 'Full Atwood machine derivation', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Resolve all forces into components along chosen axes.',
                'Incline: a = g(sinθ - μcosθ); choose axes along/perpendicular to incline.',
                'Atwood: a = (m₁-m₂)g/(m₁+m₂); same |a| for both masses.']),

            _l('Newton\'s Law of Universal Gravitation',
               [_t('Gravitational Force', 'F_g = Gm₁m₂/r² where G = 6.674 × 10⁻¹¹ N·m²/kg². Force is attractive, along the line joining the masses, inversely proportional to r².', 'Gravitational force decreases as r increases — doubling r reduces force by a factor of 4 (inverse square law).', 'Calculate gravitational force and field strength at various distances.'),
                _t('Gravitational Field', 'Gravitational field g = GM/r² at distance r from mass M. Near Earth\'s surface, g ≈ 9.8 m/s². Field lines point toward the center of the source mass.', 'The "g" in F = mg is the local gravitational field strength, not a universal constant.', 'Compute g at different altitudes above Earth\'s surface.'),
                _t('Shell Theorem', 'A uniform spherical shell exerts no gravitational force on objects inside it; outside, it acts as if all mass is concentrated at its center.', 'Inside a solid uniform sphere, g ∝ r (not constant) — students often wrongly apply 1/r² inside.', 'Apply shell theorem to objects inside and outside spherical mass distributions.')],
               [('Universal gravitation', 'F = Gm₁m₂/r²; attractive inverse-square law'),
                ('G', 'Universal gravitational constant = 6.674 × 10⁻¹¹ N·m²/kg²'),
                ('Gravitational field g', 'g = GM/r²; force per unit mass at a point'),
                ('Shell theorem', 'Spherical shell: zero field inside; acts as point mass outside'),
                ('Inverse square law', 'Force ∝ 1/r²; doubles distance → quarter force')],
               ['Calculate gravitational force between two masses.',
                'Find g at a given altitude above Earth\'s surface.',
                'Apply the shell theorem to inside/outside sphere problems.'],
               ['Free-response: find g at altitude h above Earth\'s surface.',
                'Calculate the gravitational force between two specified masses.',
                'Shell theorem: find force on a mass inside a hollow sphere.'],
               ['Compute g at the surface, 1 R_E, and 2 R_E above Earth.',
                'Compare gravitational force at different orbital radii.'],
               [('Find the gravitational force between two 100 kg spheres 1 m apart.', ['F = Gm₁m₂/r² = 6.674×10⁻¹¹ × 100 × 100 / 1²', 'F = 6.674 × 10⁻⁷ N', 'Very small! Gravity between ordinary objects is negligible', 'Only significant for very massive or very close objects']),
                ('Find g at altitude h = R_E above Earth\'s surface. (M_E = 6×10²⁴ kg, R_E = 6.4×10⁶ m)', ['Distance from center = 2R_E', 'g = GM_E/(2R_E)² = GM_E/(4R_E²) = g_surface/4', 'g = 9.8/4 = 2.45 m/s²', 'At altitude = R_E, g is one-quarter of surface value']),
                ('A 500 kg satellite orbits at r = 8×10⁶ m from Earth\'s center. Find orbital speed.', ['Centripetal force = gravity: mv²/r = GM_E m/r²', 'v² = GM_E/r = (6.674×10⁻¹¹)(6×10²⁴)/(8×10⁶)', 'v² = 5.0×10⁷ → v ≈ 7071 m/s ≈ 7.1 km/s', 'Orbital speed independent of satellite mass']),
                ('Using the shell theorem, what is the gravitational force on a mass inside a hollow spherical shell?', ['Zero force — field inside a uniform spherical shell is zero', 'The shell contributions from all sides cancel exactly', 'Outside: acts as if all mass at center (point mass)', 'This is a fundamental result proved by Newton using calculus']),
                ('How does g vary inside a uniform solid sphere as r decreases from the surface to the center?', ['Inside: g = GM_enclosed/r² = G(4πρr³/3)/r² = (4πGρ/3)r', 'g ∝ r inside → g decreases linearly to zero at center', 'Outside: g ∝ 1/r²', 'g is maximum at the surface'])],
               [('Bozeman Gravitation', 'Newton\'s law of gravitation and gravitational field', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Gravity', 'F = Gm₁m₂/r² and shell theorem', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['F = Gm₁m₂/r²; inverse square law — double r, quarter force.',
                'g = GM/r²; at altitude R_E, g = g_surface/4.',
                'Shell theorem: zero field inside shell; point mass outside.']),

            _l('Dynamics: Circular Motion and Drag',
               [_t('Circular Dynamics', 'The net centripetal force ΣF = mv²/r must be provided by real forces (gravity, tension, normal, friction). Identify which force(s) provide centripetal force in each geometry.', 'Centripetal force is not a new force — it is the name for the net inward force provided by real forces.', 'Solve circular dynamics problems at the top and bottom of loops, banked curves.'),
                _t('Banked Curves', 'For a frictionless banked curve: tan θ = v²/(rg). For a curve with friction, there is a range of speeds. Choose axes along and perpendicular to the bank.', 'On a frictionless bank, the horizontal component of N provides centripetal force — no friction needed at the correct speed.', 'Derive and apply the banked curve formula.'),
                _t('Linear Drag (Stokes\' Law)', 'In viscous fluids, drag force F_d = bv (linearly proportional to velocity) or F_d = ½ρCₐAv² (quadratic). Terminal velocity when drag equals weight.', 'Terminal velocity is reached asymptotically — object never truly reaches it instantaneously.', 'Write and solve the differential equation for motion with linear drag.')],
               [('Centripetal force', 'Net inward force = mv²/r; provided by gravity, tension, N, or friction'),
                ('Banked curve', 'Inclined road that allows circular motion without friction at design speed'),
                ('Terminal velocity', 'Speed at which drag force = weight; net force = 0'),
                ('Linear drag', 'F_d = bv; drag proportional to velocity in viscous flow'),
                ('Quadratic drag', 'F_d = ½ρCₐAv²; dominant at high speeds in air')],
               ['Identify the force(s) providing centripetal acceleration in circular dynamics problems.',
                'Derive and apply the frictionless banked curve formula.',
                'Set up and solve the differential equation for linear drag.'],
               ['Free-response: car at top and bottom of a circular loop — find N at each.',
                'Derive terminal velocity for linear drag from F_net = 0.',
                'Multi-part: banked curve problem with and without friction.'],
               ['Solve loop-the-loop problems at top and bottom.',
                'Practice the banked curve derivation from scratch.'],
               [('A car goes over a circular hill of radius 30 m at 15 m/s. Find normal force on a 1000 kg car.', ['At top of hill: N and weight both act; N points up, W down', 'Net downward (centripetal): mg - N = mv²/r', 'N = m(g - v²/r) = 1000(9.8 - 225/30) = 1000(9.8 - 7.5)', 'N = 2300 N (less than weight of 9800 N)']),
                ('Find the design speed for a frictionless banked curve with r = 100 m and θ = 20°.', ['tanθ = v²/(rg) → v² = rg tanθ', 'v² = 100 × 9.8 × tan20° = 100 × 9.8 × 0.364 = 356.7', 'v = 18.9 m/s ≈ 19 m/s', 'At this speed, N alone provides centripetal force on a frictionless bank']),
                ('A mass m falls with linear drag F_d = bv. Write the equation of motion and find terminal velocity.', ['m(dv/dt) = mg - bv', 'At terminal velocity: dv/dt = 0 → mg = bv_t → v_t = mg/b', 'Before terminal: v increases from 0 toward v_t asymptotically', 'Solution: v(t) = v_t(1 - e^(-bt/m))']),
                ('At the bottom of a loop of radius R, what is N for a mass m traveling at speed v?', ['Net upward (centripetal): N - mg = mv²/R', 'N = m(g + v²/R) > mg', 'Normal force exceeds weight at the bottom of a loop', 'This is why riders feel heavy at the bottom (apparent weight > actual weight)']),
                ('What is the minimum speed at the top of a loop of radius R for the car to maintain contact?', ['At top: mg + N = mv²/R; minimum when N = 0', 'mg = mv_min²/R → v_min = √(gR)', 'Below this speed, normal force would need to be negative (can\'t push up)', 'Track loses contact with car if v < √(gR) at top'])],
               [('Bozeman Circular Dynamics', 'Forces in circular motion, loops, banked curves', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Terminal Velocity', 'Linear drag and terminal velocity equation', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Centripetal force = real forces (N, T, f, gravity) pointing inward.',
                'Frictionless bank: tanθ = v²/(rg).',
                'Linear drag: v_terminal = mg/b; v(t) = v_t(1 - e^{-bt/m}).'])
        ],
        'unit_qs': [
            ('A 2 kg block is on a 40° frictionless incline. Find acceleration and normal force.',
             ['N = mg cos40° = 2(9.8)(0.766) = 15.01 N', 'a = g sin40° = 9.8(0.643) = 6.3 m/s²', 'No friction: a = g sinθ; N = mg cosθ', 'Block slides down with a ≈ 6.3 m/s²']),
            ('Three blocks (m₁ = 1 kg, m₂ = 2 kg, m₃ = 3 kg) are on a frictionless surface, pushed by F = 12 N. Find acceleration and force between m₂ and m₃.',
             ['Total mass = 6 kg; a = F/M = 12/6 = 2 m/s²', 'Force on m₃ from m₂: F₂₃ = m₃ × a = 3 × 2 = 6 N', 'Force on m₁ from push: m₁×a = 2 N; F between m₁ and m₂: 4 N (pushes m₂+m₃)', 'All blocks have same acceleration (inextensible contact)']),
            ('Find the gravitational field strength at the surface of Mars. (M_Mars = 6.4 × 10²³ kg, R_Mars = 3.4 × 10⁶ m)',
             ['g_Mars = GM/R² = (6.674×10⁻¹¹)(6.4×10²³)/(3.4×10⁶)²', 'g_Mars = (4.27×10¹³)/(1.156×10¹³) = 3.7 m/s²', 'About 38% of Earth\'s surface gravity', 'Mars has lower mass and smaller radius than Earth']),
            ('A satellite orbits at radius r. Derive the orbital period T using Newton\'s 2nd law and gravity.',
             ['F_gravity = F_centripetal: GMm/r² = mv²/r → v² = GM/r', 'v = 2πr/T (circumference/period)', '(2πr/T)² = GM/r → T² = 4π²r³/(GM)', 'T = 2π√(r³/GM) — Kepler\'s 3rd law result']),
            ('An object on a string swings in a vertical circle of radius 1 m. Find minimum speed at the top to maintain circular motion. (g = 9.8 m/s²)',
             ['At top, N = 0 for minimum speed: mg = mv²/r', 'v_min = √(gr) = √(9.8 × 1) = √9.8 ≈ 3.13 m/s', 'Below this, string goes slack', 'Tension at bottom (using energy): T_bottom = mg + mv²_bottom/r = mg + m(v²_top + 4gr)/r']),
            ('Derive the equation of motion for an object falling with drag F_d = bv and solve for v(t).',
             ['ma = mg - bv → m(dv/dt) = mg - bv', 'Separable: dv/(mg - bv) = dt/m → -1/b ln(mg - bv) = t/m + C', 'At t = 0, v = 0: v(t) = (mg/b)(1 - e^{-bt/m})', 'As t → ∞: v → mg/b = v_terminal']),
            ('A car (1500 kg) rounds a flat curve (r = 80 m) at 25 m/s. Find minimum static friction coefficient required.',
             ['Centripetal force = friction: μ_s mg = mv²/r', 'μ_s = v²/(rg) = 625/(80 × 9.8) = 0.797', 'Minimum μ_s ≈ 0.80', 'If μ_s < 0.80, the car cannot complete the turn']),
            ('A 3 kg and 5 kg mass hang from a pulley. If the system starts from rest, how far does the heavier mass fall in 2 s?',
             ['a = (5-3)(9.8)/(5+3) = 2(9.8)/8 = 2.45 m/s²', 'Δy = ½at² = ½(2.45)(4) = 4.9 m', 'The 5 kg mass falls 4.9 m; 3 kg rises 4.9 m', 'Both masses have the same magnitude of displacement']),
            ('Explain why a rider feels heavier at the bottom and lighter at the top of a roller coaster loop.',
             ['At bottom: N - mg = mv²/r → N = m(g + v²/r) > mg → apparent weight > real weight', 'At top: N + mg = mv²/r → N = m(v²/r - g) < mg → apparent weight < real weight', 'Apparent weight = normal force, not gravity', 'At v = √(gR) at top, N = 0 → apparent weightlessness']),
            ('Two identical spheres of mass m are 10 cm apart. The gravitational force is F. If the distance is halved, what is the new force?',
             ['F = Gm²/r²; halving r: F_new = Gm²/(r/2)² = 4Gm²/r² = 4F', 'Force is quadrupled', 'This is the inverse square law: F ∝ 1/r²', 'Halving distance → 4× force'])
        ]
    },

    {
        'num': 3, 'title': 'Work, Energy, and Power',
        'file': 'ap-physics-c-mechanics-3-unit-3-work-energy-and-power.html',
        'desc': 'Work as a line integral, kinetic and potential energy, energy conservation, and power in calculus-based mechanics.',
        'gateway': [
            'Calculate work using W = ∫F·ds for variable forces.',
            'Apply the work-energy theorem: W_net = ΔKE.',
            'Define and use gravitational and elastic potential energy.',
            'Apply conservation of mechanical energy and identify non-conservative forces.',
        ],
        'lessons': [
            _l('Work as a Line Integral',
               [_t('Work Definition', 'W = ∫F·ds = ∫F cosθ ds; for constant force and straight path, W = F·d cosθ. Work is a scalar; positive work increases KE.', 'Work can be negative if force opposes displacement (e.g., friction does negative work).', 'Calculate work for constant and variable forces using integrals.'),
                _t('Work Done by Variable Forces', 'W = ∫F(x) dx from x₁ to x₂. For a spring: W = ½kx₂² - ½kx₁² (or -ΔPE_spring). Graphically, work = area under F-x graph.', 'The work done BY a spring on a block is negative if the spring is pushing the block back to equilibrium.', 'Compute work using F(x) integration and F-x graph areas.'),
                _t('Work-Energy Theorem', 'W_net = ΔKE = ½mv₂² - ½mv₁². Net work equals the change in kinetic energy — this is a fundamental result derived from Newton\'s 2nd law.', 'W_net includes all forces; individual force work can be positive or negative — only the net determines ΔKE.', 'Apply work-energy theorem to find speeds after forces act.')],
               [('Work W', 'W = ∫F·ds; scalar quantity (J = N·m)'),
                ('Work-energy theorem', 'W_net = ΔKE; net work equals change in KE'),
                ('Variable force work', 'W = ∫F(x)dx; area under F-x graph'),
                ('Spring work', 'W = ½kx² for spring compressed/stretched by x from natural length'),
                ('Negative work', 'Work done by friction or opposing forces that decrease KE')],
               ['Calculate work for constant forces using W = Fd cosθ.',
                'Compute work for variable forces using integration.',
                'Apply the work-energy theorem to find final speed.'],
               ['Free-response: find work done by a spring using integration.',
                'Calculation: use W-E theorem to find speed after a net force acts.',
                'F-x graph: find work from area under the curve.'],
               ['Practice ∫F(x)dx for several force functions.',
                'Verify work-energy theorem using kinematics as a check.'],
               [('A force F(x) = 3x² + 2 (N) acts on an object from x = 0 to x = 3 m. Find work done.', ['W = ∫₀³ (3x² + 2) dx = [x³ + 2x]₀³', 'W = (27 + 6) - 0 = 33 J', 'Work is the integral of F(x) over the displacement', 'For constant force F, W = F × d (special case of integral)']),
                ('A spring (k = 200 N/m) is compressed 0.1 m from natural length. Find work done by spring when released back to natural length.', ['W_spring = -ΔPE_spring = -(0 - ½kx²) = ½kx²', 'W = ½(200)(0.1)² = 1.0 J', 'The spring does positive work as it pushes back to natural length', 'Alternatively: W = ∫₀.₁ kx dx = ½kx² (magnitude)']),
                ('Derive the work-energy theorem from Newton\'s second law.', ['F_net = ma = m(dv/dt)', 'W_net = ∫F_net dx = ∫m(dv/dt) dx = ∫mv dv (using v = dx/dt)', 'W_net = m∫v dv = ½mv₂² - ½mv₁² = ΔKE', 'This derivation shows W-E theorem follows directly from F = ma']),
                ('A 2 kg object moving at 5 m/s has a net force of F(x) = -4x N applied for 0 to 2 m. Find final speed.', ['W_net = ∫₀² (-4x) dx = [-2x²]₀² = -8 J', 'W_net = ΔKE: ½mv₂² = ½mv₁² + W_net = ½(2)(25) - 8 = 25 - 8 = 17 J', 'v₂ = √(2 × 17/2) = √17 ≈ 4.12 m/s', 'Negative work → final KE less than initial']),
                ('Find the work done by gravity on a 3 kg ball falling 10 m.', ['W_gravity = Fd cosθ = mgd cos0° = 3(9.8)(10)(1) = 294 J', 'Gravity does positive work when object moves in direction of gravitational force', 'Or: W_gravity = -ΔPE_grav = -(mgh₂ - mgh₁) = mg(h₁ - h₂) = mg(10) = 294 J', 'Both approaches give same result'])],
               [('Bozeman Work Integral', 'Work as an integral for variable forces', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Work-Energy Theorem', 'Deriving and applying W_net = ΔKE', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['W = ∫F·ds; positive W increases KE; negative W decreases KE.',
                'Variable force: W = ∫F(x)dx = area under F-x graph.',
                'Work-energy theorem: W_net = ΔKE (derived from F = ma).']),

            _l('Potential Energy and Conservation of Energy',
               [_t('Conservative Forces and Potential Energy', 'A force is conservative if the work done is path-independent. PE is defined as ΔU = -W_conservative. For gravity: U_g = mgh; for spring: U_s = ½kx².', 'Only conservative forces can be associated with potential energy — friction is not conservative.', 'Identify conservative forces and compute their potential energies.'),
                _t('Conservation of Mechanical Energy', 'When only conservative forces act: KE + PE = constant. E_mech = ½mv² + U is conserved when friction is absent.', 'Mechanical energy is NOT conserved when friction or other non-conservative forces do work.', 'Apply energy conservation to find speed at any point in a conservative system.'),
                _t('Work by Non-Conservative Forces', 'W_nc = ΔKE + ΔPE = ΔE_mech. Non-conservative forces (friction, drag) change the total mechanical energy of the system.', 'Energy is always conserved (1st law); mechanical energy decreases only because it converts to thermal energy via friction.', 'Calculate energy lost to friction using W_nc = ΔE_mech.')],
               [('Conservative force', 'Force for which work is path-independent; associated with PE'),
                ('Non-conservative force', 'Force (friction, drag) for which work is path-dependent'),
                ('Gravitational PE', 'U_g = mgh; reference point chosen arbitrarily'),
                ('Elastic PE', 'U_s = ½kx²; stored in a compressed/stretched spring'),
                ('Energy dissipation', 'Mechanical energy converted to thermal by friction: ΔE_thermal = |W_friction|')],
               ['Define conservative forces and compute associated potential energies.',
                'Apply energy conservation when only conservative forces act.',
                'Use W_nc = ΔE_mech to account for friction.'],
               ['Free-response: ball on a curved track — find speed at various heights.',
                'Calculation: spring-launched block with friction — find speed at specific point.',
                'Identify energy transformations throughout a given process.'],
               ['Solve at least 5 conservation of energy problems with and without friction.',
                'Practice energy bar charts at multiple points in a system.'],
               [('A 1 kg ball rolls from rest down a 5 m high ramp (frictionless). Find speed at bottom.', ['KE_f = PE_i: ½mv² = mgh', 'v = √(2gh) = √(2 × 9.8 × 5) = √98 ≈ 9.9 m/s', 'All PE converted to KE (no friction)', 'Height, not path shape, determines final speed in frictionless case']),
                ('A spring (k = 500 N/m) launches a 0.2 kg block from compression x = 0.3 m on a frictionless surface. Find launch speed.', ['½kx² = ½mv² → v = x√(k/m)', 'v = 0.3√(500/0.2) = 0.3√2500 = 0.3 × 50 = 15 m/s', 'All elastic PE converted to KE', 'v = Aω for SHM (confirms result)']),
                ('Friction (f = 5 N) acts over 3 m on a 2 kg block. Initial KE = 40 J. Find final KE.', ['W_friction = -f × d = -5 × 3 = -15 J (friction does negative work)', 'W_nc = ΔKE: KE_f = KE_i + W_nc = 40 + (-15) = 25 J', 'Or: ΔE_mech = W_nc = -15 J; ME_f = 40 - 15 = 25 J', '15 J is converted to thermal energy (heat)']),
                ('Why can\'t friction be described by potential energy?', ['PE is only defined for conservative (path-independent) forces', 'Friction work depends on path length and direction — it is path-dependent', 'Friction always removes mechanical energy from the system', 'Cannot define a PE function U(x) such that F = -dU/dx for friction']),
                ('A pendulum swings down from height h. Find speed at lowest point and height reached on the other side.', ['Energy conservation (frictionless): ½mv² = mgh → v = √(2gh)', 'Since energy is conserved, it rises to same height h on other side', 'KE at bottom converts back to PE on upswing', 'Period and amplitude don\'t affect final height in frictionless case'])],
               [('Bozeman Conservation of Energy', 'Conservative forces and energy conservation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Potential Energy', 'PE for gravity and springs; energy conservation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Conservative forces: path-independent work; define PE.',
                'Energy conservation: KE + PE = const when no friction.',
                'Friction: W_nc = ΔE_mech < 0; converts ME to thermal energy.']),

            _l('Power and Energy in Complex Systems',
               [_t('Power', 'P = dW/dt = F·v; average power P_avg = W/t. SI unit: watt (W = J/s).', 'Power depends on force AND velocity — a slow, large force can have the same power as a fast, small force.', 'Calculate instantaneous and average power for various situations.'),
                _t('Center of Mass Energy', 'The kinetic energy of a system has a center-of-mass component (½Mv_cm²) and an internal component (KE relative to CM). Only the CM KE is affected by external forces.', 'In a collision, only CM kinetic energy changes if external forces are absent — internal KE is unchanged by external impulse.', 'Decompose KE into CM and relative components for two-body systems.'),
                _t('Energy in Gravitational Fields', 'Gravitational PE: U = -GMm/r (negative for bound orbits). At r → ∞, U = 0. Escape velocity: v_esc = √(2GM/r).', 'Gravitational PE is negative for bound systems — binding energy is how much must be added to free the object.', 'Calculate escape velocity and binding energy for orbital systems.')],
               [('Power P', 'P = dW/dt = F·v; rate of energy transfer (W = J/s)'),
                ('Average power', 'P_avg = W_total/Δt'),
                ('Instantaneous power', 'P = F·v at a specific instant'),
                ('Escape velocity', 'v_esc = √(2GM/r); minimum speed to escape gravity'),
                ('Gravitational PE (orbit)', 'U = -GMm/r; negative for bound orbit')],
               ['Calculate instantaneous power using P = Fv.',
                'Find escape velocity from a planet using energy conservation.',
                'Explain why U = -GMm/r is negative and what that means physically.'],
               ['Free-response: find power output of a motor lifting a mass at constant velocity.',
                'Calculation: find orbital KE, PE, and total energy at radius r.',
                'Derive escape velocity from energy conservation.'],
               ['Practice power problems with varying force and velocity.',
                'Compute total orbital energy at various radii.'],
               [('A 100 kg elevator rises at constant 2 m/s. Motor output power?', ['Constant v → a = 0 → motor force = weight = mg = 980 N', 'P = Fv = 980 × 2 = 1960 W ≈ 2 kW', 'At constant velocity, all power goes against gravity', 'If accelerating, additional power needed for KE increase']),
                ('Find the escape velocity from Earth\'s surface. (M_E = 6×10²⁴ kg, R_E = 6.4×10⁶ m)', ['Energy conservation: ½mv_esc² = GMm/R_E', 'v_esc = √(2GM/R) = √(2 × 6.674×10⁻¹¹ × 6×10²⁴ / 6.4×10⁶)', 'v_esc = √(1.25×10⁸) ≈ 11 180 m/s ≈ 11.2 km/s', 'Note: escape velocity is independent of the escaping mass']),
                ('A satellite orbits at radius r. Find KE, PE, and total energy.', ['Circular orbit: GMm/r² = mv²/r → v² = GM/r → KE = ½mv² = GMm/(2r)', 'PE = -GMm/r', 'Total E = KE + PE = GMm/(2r) - GMm/r = -GMm/(2r)', 'Total energy is negative (bound orbit); |PE| = 2 × KE (virial theorem)']),
                ('An engine provides a force F(v) = 2000 - 5v² N on a car (at velocity v). Find maximum speed.', ['At maximum speed, a = 0 → F_drive = F_drag', '2000 - 5v_max² = 0 → v_max² = 400 → v_max = 20 m/s', 'At v_max, engine force exactly balances drag', 'Power at v_max: P = Fv = 2000(20) - 5(20³) = 40 000 - 40 000 = 0... wait: P = F_engine × v = (2000-5v²)v — different F_drag model needed']),
                ('Explain why escape velocity is independent of the mass of the escaping object.', ['Energy conservation: ½mv² = GMm/r; mass m cancels', 'v_esc = √(2GM/r) depends only on planet mass M and radius r', 'Analogous to free fall: acceleration g = GM/r² is independent of falling mass', 'A feather and a rocket have the same escape velocity from Earth'])],
               [('Bozeman Orbital Energy', 'Escape velocity and orbital energy', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Power', 'Power calculations and P = Fv', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['P = Fv instantaneous; P_avg = W/t.',
                'Orbital energy: KE = GMm/(2r); PE = -GMm/r; E_total = -GMm/(2r).',
                'Escape velocity: v_esc = √(2GM/r).']),

            _l('Potential Energy Functions and Force',
               [_t('Force from Potential Energy', 'F = -dU/dx in 1D; the force is the negative gradient of potential energy. Equilibrium where dU/dx = 0; stable if d²U/dx² > 0.', 'The minus sign is essential: force points "downhill" on a potential energy curve.', 'Derive force from a given U(x) by differentiation.'),
                _t('Potential Energy Diagrams', 'A U(x) graph (energy landscape) shows equilibrium points, turning points (where KE = 0), and stability. Total energy E is a horizontal line on the diagram.', 'At a turning point, v = 0 but a ≠ 0 (force still acts); the object reverses direction.', 'Analyze motion qualitatively from a U(x) diagram.'),
                _t('Multiple Conservative Forces', 'Total mechanical energy E = KE + U_gravity + U_spring + U_other. Each conservative force contributes its own PE term.', 'Do not mix PE and W_by_force in the same equation — use either all PE or all work, not both.', 'Apply energy conservation with combined gravitational and elastic PE.')],
               [('F = -dU/dx', 'Force is the negative derivative of potential energy'),
                ('Equilibrium', 'Point where F = 0; dU/dx = 0'),
                ('Stable equilibrium', 'F restores object after displacement; d²U/dx² > 0 (U is minimum)'),
                ('Turning point', 'Position where KE = 0; object momentarily at rest, then reverses'),
                ('Energy landscape', 'Graph of U(x) with total energy E shown as horizontal line')],
               ['Derive force from a given potential energy function.',
                'Identify stable and unstable equilibria from a U(x) diagram.',
                'Find turning points and describe motion using U(x) graphs.'],
               ['Free-response: given U(x), find F(x), equilibria, and describe motion.',
                'Graph: sketch U(x) for a spring-mass system and gravity combined.',
                'Multiple choice: interpret energy landscape for a particle.'],
               ['Practice F = -dU/dx for several U(x) functions.',
                'Analyze energy diagrams for 2–3 different physical systems.'],
               [('Given U(x) = 3x⁴ - 16x² + 10. Find F(x) and equilibrium positions.', ['F(x) = -dU/dx = -(12x³ - 32x) = -12x³ + 32x', 'Equilibria: F = 0 → 32x - 12x³ = 0 → x(32 - 12x²) = 0', 'x = 0 or x = ±√(32/12) = ±√(8/3) ≈ ±1.63 m', 'x = 0: d²U/dx² = -32 < 0 → unstable; x = ±1.63: stable']),
                ('A particle has E = 10 J and U(x) given graphically. Describe its motion between turning points.', ['Turning points: where U(x) = E = 10 J (KE = 0)', 'KE = E - U(x) > 0 between turning points', 'Particle oscillates between turning points; moves fastest where U is minimum', 'Cannot access regions where U > E (classically forbidden)']),
                ('A spring (k = 100 N/m) hangs vertically with mass m = 1 kg. Find equilibrium extension and total PE.', ['At equilibrium: kx = mg → x = mg/k = (1)(9.8)/100 = 0.098 m', 'U_total = ½kx² - mgx = ½(100)(0.098)² - (1)(9.8)(0.098)', 'U_total = 0.480 - 0.960 = -0.480 J (negative — gravity does net work)', 'Equilibrium is at the minimum of U_total']),
                ('Explain why F = -dU/dx has a negative sign.', ['The force pushes objects toward lower potential energy (downhill)', 'If U increases with x (dU/dx > 0), force is in -x direction (back downhill)', 'This is the definition that makes potential energy consistent with work', 'Analogy: ball rolls toward the bottom of a potential energy "valley"']),
                ('Given U(x) = ½kx² (spring PE). Show that F = -kx.', ['F = -dU/dx = -d/dx(½kx²) = -kx', 'This confirms Hooke\'s law is recovered from spring PE', 'The minus sign means force opposes displacement (restoring force)', 'F = -kx is the defining equation of SHM'])],
               [('Bozeman Potential Energy Functions', 'F = -dU/dx and energy diagrams', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Energy Landscape', 'Analyzing U(x) diagrams', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['F = -dU/dx; force is "downhill" on energy curve.',
                'Equilibrium: dU/dx = 0; stable if d²U/dx² > 0.',
                'Turning points: where KE = 0 (E = U); oscillation between them.'])
        ],
        'unit_qs': [
            ('A force F(x) = 6x - 2 N acts on a 1 kg object from x = 0 to x = 4 m. Find work done and final speed if v(0) = 0.',
             ['W = ∫₀⁴(6x - 2)dx = [3x² - 2x]₀⁴ = (48 - 8) - 0 = 40 J', 'W = ΔKE: 40 = ½(1)v² → v = √80 ≈ 8.94 m/s', 'Work-energy theorem used directly', 'Check: F at x=4 is 22 N; average F ≈ 10 N × 4 m = 40 J ✓']),
            ('A 0.5 kg block compresses a spring (k = 800 N/m) by 0.15 m on a surface with μ_k = 0.3. Find speed when spring is at natural length.',
             ['Spring PE: ½kx² = ½(800)(0.0225) = 9 J', 'Friction work: W_f = -μ_k mg d = -0.3(0.5)(9.8)(0.15) = -0.221 J', 'KE = 9.0 - 0.221 = 8.78 J', 'v = √(2 × 8.78/0.5) = √35.1 ≈ 5.92 m/s']),
            ('Derive the total energy for a circular orbit: E = -GMm/(2r).',
             ['Circular orbit: v² = GM/r → KE = ½mv² = GMm/(2r)', 'Gravitational PE: U = -GMm/r', 'E_total = KE + PE = GMm/(2r) - GMm/r = -GMm/(2r)', 'Negative total energy means the object is gravitationally bound']),
            ('A motor lifts a 500 kg load 10 m in 8 s. Find power output assuming 80% efficiency.',
             ['W_useful = mgh = 500(9.8)(10) = 49 000 J', 'P_useful = W/t = 49 000/8 = 6125 W', 'P_input = P_useful/efficiency = 6125/0.80 = 7656 W ≈ 7.7 kW', 'Efficiency < 1 means more power input required than useful work output']),
            ('Given U(x) = x³ - 3x + 2. Find equilibria, classify their stability, and sketch the motion.',
             ['F = -dU/dx = -(3x² - 3) = 3 - 3x²; F = 0 → x = ±1', 'x = +1: d²U/dx² = 6x = 6 > 0 → stable (minimum of U)', 'x = -1: d²U/dx² = -6 < 0 → unstable (maximum of U)', 'Particle oscillates around x = +1 for E slightly above U_min']),
            ('A 2 kg block slides down a 4 m incline (30°) with friction (μ_k = 0.25). Using energy methods, find speed at the bottom.',
             ['Height: h = 4 sin30° = 2 m; PE_lost = mgh = 2(9.8)(2) = 39.2 J', 'Friction work: W_f = -μ_k mg cos30° × d = -0.25(2)(9.8)(0.866)(4) = -17.0 J', 'KE_f = 39.2 - 17.0 = 22.2 J', 'v = √(2 × 22.2/2) = √22.2 ≈ 4.71 m/s']),
            ('Find escape velocity from the Moon. (M_Moon = 7.35×10²² kg, R_Moon = 1.74×10⁶ m)',
             ['v_esc = √(2GM/R) = √(2 × 6.674×10⁻¹¹ × 7.35×10²² / 1.74×10⁶)', 'v_esc = √(5.63×10⁶) ≈ 2373 m/s ≈ 2.37 km/s', 'About 21% of Earth\'s escape velocity', 'Low escape velocity explains why Moon has essentially no atmosphere']),
            ('A 1 kg object moves in 1D with U(x) = 2x² - 8x. Find equilibrium, minimum PE, and oscillation frequency (treat as spring-like).',
             ['F = -dU/dx = -(4x - 8) = 8 - 4x; F = 0 at x = 2 m', 'U_min = 2(4) - 8(2) = 8 - 16 = -8 J', 'Effective spring constant: k_eff = d²U/dx² = 4 N/m', 'f = (1/2π)√(k/m) = (1/2π)√(4/1) = 1/π ≈ 0.318 Hz']),
            ('Explain what negative total orbital energy means physically.',
             ['E_total = -GMm/(2r) < 0 means the satellite is gravitationally bound', 'To escape, energy must be increased to E = 0 (at r → ∞)', 'Binding energy = |E| = GMm/(2r) — energy needed to free the satellite', 'Positive E would mean unbound (hyperbolic) trajectory']),
            ('A variable force F(x) = 10/x² N acts on a 0.5 kg object moving from x = 1 m to x = 5 m. Find the work and final speed if v(1) = 2 m/s.',
             ['W = ∫₁⁵ (10/x²)dx = [-10/x]₁⁵ = (-2) - (-10) = 8 J', 'KE_i = ½(0.5)(4) = 1 J; KE_f = KE_i + W = 1 + 8 = 9 J', 'v_f = √(2 × 9/0.5) = √36 = 6 m/s', 'This type of force (1/x²) models gravity in 1D'])
        ]
    },

    {
        'num': 4, 'title': 'Systems of Particles and Linear Momentum',
        'file': 'ap-physics-c-mechanics-4-unit-4-linear-momentum.html',
        'desc': 'Center of mass, linear momentum, impulse, and collisions analyzed using calculus-based methods.',
        'gateway': [
            'Find the center of mass of discrete and continuous mass distributions.',
            'Apply the impulse-momentum theorem using integrals.',
            'Distinguish elastic, inelastic, and perfectly inelastic collisions.',
            'Apply conservation of momentum and energy to collision analysis.',
        ],
        'lessons': [
            _l('Center of Mass',
               [_t('Center of Mass for Discrete Systems', 'r_cm = Σ(m_i r_i)/M_total. For a two-body system: x_cm = (m₁x₁ + m₂x₂)/(m₁ + m₂). CM is weighted average of positions.', 'CM is not necessarily inside the object (e.g., ring, horseshoe).', 'Calculate CM coordinates for multiple point masses.'),
                _t('Center of Mass for Continuous Distributions', 'x_cm = (1/M)∫x dm; use linear density λ, surface density σ, or volume density ρ to express dm.', 'For uniform density, dm = ρ dV (volume element); for a rod, dm = λ dx.', 'Compute CM of uniform rods, triangles, and other shapes using integration.'),
                _t('Motion of the Center of Mass', 'The CM of an isolated system moves with constant velocity: v_cm = Σ(m_i v_i)/M. External forces change v_cm: F_ext = Ma_cm.', 'Internal forces between particles do NOT affect the CM\'s acceleration — only external forces do.', 'Apply F_ext = Ma_cm to find CM acceleration in complex systems.')],
               [('Center of mass', 'r_cm = Σm_i r_i/M; mass-weighted average position'),
                ('Linear density λ', 'Mass per unit length (kg/m); dm = λ dx for a rod'),
                ('CM velocity', 'v_cm = p_total/M = Σm_i v_i/M'),
                ('F_ext = Ma_cm', 'Net external force governs CM acceleration'),
                ('Isolated system CM', 'CM moves at constant velocity if no external forces act')],
               ['Calculate center of mass for point masses and uniform rods.',
                'State and apply the theorem that external forces cause CM acceleration.',
                'Find CM velocity from individual particle velocities.'],
               ['Free-response: find CM of L-shaped uniform plate or rod combination.',
                'Integration: find CM of a non-uniform rod with λ(x) = λ₀(1 + x/L).',
                'Apply F_ext = Ma_cm to a system of connected objects.'],
               ['Practice CM calculations for discrete systems of 3–4 masses.',
                'Integrate to find CM of a uniform triangle or wedge.'],
               [('Three masses: m₁ = 1 kg at x = 0, m₂ = 2 kg at x = 3 m, m₃ = 3 kg at x = 6 m. Find CM.', ['x_cm = (1×0 + 2×3 + 3×6)/(1+2+3) = (0 + 6 + 18)/6 = 24/6 = 4 m', 'CM is closest to the heaviest mass', 'For equal masses, CM would be at x = 3 m (geometric center)', 'CM can be computed separately for x and y coordinates']),
                ('Find the CM of a uniform rod of mass M and length L.', ['λ = M/L (uniform); dm = λ dx', 'x_cm = (1/M)∫₀ᴸ x(M/L)dx = (1/L)[x²/2]₀ᴸ = L/2', 'CM is at the midpoint, as expected by symmetry', 'For non-uniform rod, λ = λ(x) and integral must be evaluated']),
                ('A non-uniform rod has λ(x) = 2x kg/m for 0 ≤ x ≤ 3 m. Find total mass and CM.', ['M = ∫₀³ 2x dx = [x²]₀³ = 9 kg', 'x_cm = (1/9)∫₀³ x(2x)dx = (1/9)∫₀³ 2x² dx = (1/9)[2x³/3]₀³', 'x_cm = (1/9)(18) = 2 m', 'CM is at x = 2 m, displaced toward the heavier (higher x) end']),
                ('Two blocks (3 kg and 5 kg) connected by a spring are on a frictionless surface. A 30 N external force is applied to the system. Find CM acceleration.', ['F_ext = (m₁ + m₂)a_cm → a_cm = F/M = 30/8 = 3.75 m/s²', 'Internal spring forces do NOT affect CM acceleration', 'CM accelerates as if entire mass were at one point', 'Individual block accelerations differ (spring stretches/compresses)']),
                ('After an explosion, two fragments (2 kg at 10 m/s right; 3 kg at v₂ left) are produced from a stationary object. Find v₂.', ['CM was at rest; p_total = 0 must be conserved', '2(10) - 3v₂ = 0 → v₂ = 20/3 ≈ 6.67 m/s to the left', 'CM remains stationary after the explosion (no external force)', 'Heavier fragment moves slower to conserve momentum'])],
               [('Bozeman Center of Mass', 'Discrete and continuous mass distributions', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics CM Integration', 'Integrating to find CM of continuous objects', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['r_cm = Σm_i r_i/M; for rod: x_cm = (1/M)∫x dm.',
                'F_ext = Ma_cm; internal forces don\'t affect CM acceleration.',
                'Isolated system: CM velocity is constant.']),

            _l('Linear Momentum and Impulse',
               [_t('Linear Momentum', 'p = mv; a vector quantity in the direction of velocity. Newton\'s 2nd law in terms of momentum: F_net = dp/dt (more general than F = ma).', 'dp/dt = ma only when mass is constant; F = dp/dt handles variable-mass systems (rockets).', 'Apply F = dp/dt to situations with changing mass.'),
                _t('Impulse', 'J = ∫F dt = Δp; impulse equals the area under the F-t graph. For constant force: J = FΔt. Impulse-momentum theorem: J = p_f - p_i.', 'Impulse is NOT force times time — that is only for constant force; in general, J = ∫F dt.', 'Calculate impulse from F-t graphs (area) and from change in momentum.'),
                _t('Conservation of Linear Momentum', 'If F_ext = 0, then dp/dt = 0 → p_total = constant. Conservation applies separately in each direction when that component of F_ext = 0.', 'Momentum can be conserved in one direction but not another (e.g., ball bouncing on floor: x conserved, y not).', 'Apply momentum conservation to collisions and explosions.')],
               [('Linear momentum p', 'p = mv; vector in direction of motion (kg·m/s)'),
                ('Impulse J', 'J = ∫F dt = Δp; change in momentum'),
                ('F = dp/dt', 'Newton\'s 2nd law in general form; handles variable-mass problems'),
                ('Impulse-momentum theorem', 'J = Δp = p_f - p_i'),
                ('Momentum conservation', 'p_total constant when F_ext = 0')],
               ['Calculate impulse from F-t graphs and from momentum change.',
                'Apply F = dp/dt to variable-mass problems (rockets).',
                'Identify conditions for momentum conservation and apply it.'],
               ['Free-response: find impulse from a given F(t) and resulting velocity change.',
                'Rocket: apply F = dp/dt with varying mass.',
                'Collision: conserve momentum (and energy for elastic) to find post-collision velocities.'],
               ['Practice impulse calculations using both F-t integration and Δp.',
                'Solve rocket problems using the rocket equation qualitatively.'],
               [('A 0.5 kg ball changes velocity from 10 m/s east to 6 m/s west. Find impulse.', ['p_i = 0.5(+10) = +5 kg·m/s; p_f = 0.5(-6) = -3 kg·m/s', 'J = Δp = p_f - p_i = -3 - 5 = -8 kg·m/s (westward)', 'Magnitude of impulse = 8 N·s', 'Requires average force of -8/Δt N for duration Δt']),
                ('A force F(t) = 4t² - 2t N acts for 0 ≤ t ≤ 3 s. Find impulse.', ['J = ∫₀³ (4t² - 2t) dt = [4t³/3 - t²]₀³', 'J = (36 - 9) - 0 = 27 N·s', 'Impulse is the area under the F-t graph = integral', 'Change in momentum = 27 kg·m/s']),
                ('A 2 kg block moves at 8 m/s and collides with a stationary 3 kg block. They stick together. Find post-collision velocity.', ['p_initial = 2(8) = 16 kg·m/s', 'Conservation: 16 = (2+3)v_f → v_f = 3.2 m/s', 'This is a perfectly inelastic collision', 'KE lost = ½(2)(64) - ½(5)(10.24) = 64 - 25.6 = 38.4 J (converted to heat/deformation)']),
                ('Apply F = dp/dt to a rocket ejecting mass at rate dm/dt = -α (α > 0). Find thrust force.', ['p = Mv; dp/dt = M(dv/dt) + v(dM/dt)', 'Thrust = -v_exhaust × (dM/dt) = v_exhaust × α', 'Rocket equation: Ma = v_exhaust × α - external forces', 'As fuel burns (M decreases), acceleration increases for same thrust']),
                ('Why is F = ma a special case of F = dp/dt?', ['p = mv; dp/dt = m(dv/dt) + v(dm/dt)', 'When mass is constant: dm/dt = 0 → dp/dt = m(dv/dt) = ma', 'F = dp/dt is more general and handles variable-mass systems', 'Rockets, conveyor belts: must use F = dp/dt'])],
               [('Bozeman Momentum and Impulse', 'p = mv, J = ∫F dt, and impulse-momentum theorem', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Impulse', 'Calculating impulse from F(t) and F-t graphs', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['p = mv; F = dp/dt (general Newton\'s 2nd law).',
                'Impulse J = ∫F dt = Δp; area under F-t graph.',
                'Conservation of momentum: p_total = constant when F_ext = 0.']),

            _l('Collisions',
               [_t('Elastic Collisions', 'In a perfectly elastic collision, both momentum and kinetic energy are conserved. For 1D elastic collision of m₁ (moving) with m₂ (at rest): v₁\' = (m₁-m₂)v₁/(m₁+m₂); v₂\' = 2m₁v₁/(m₁+m₂).', 'In a perfectly elastic collision, the relative speed of approach = relative speed of separation (coefficient of restitution = 1).', 'Solve 1D and 2D elastic collisions using momentum and energy conservation.'),
                _t('Inelastic and Perfectly Inelastic Collisions', 'In a perfectly inelastic collision, objects stick together (maximum KE loss). Partial inelastic: KE lost but objects separate. Only momentum is conserved in all collisions.', 'In ANY collision (elastic or not), total momentum is conserved; only in elastic collisions is KE also conserved.', 'Identify the type of collision and apply appropriate conservation laws.'),
                _t('2D Collisions', 'In 2D, apply momentum conservation separately for x and y components. At angles, resolve initial and final velocities into components.', 'In 2D collisions, the objects need not travel along the original axis — resolve all vectors into components.', 'Solve 2D glancing collision problems using component momentum conservation.')],
               [('Elastic collision', 'Both p and KE conserved; coefficient of restitution = 1'),
                ('Inelastic collision', 'p conserved; KE not conserved; some energy converted to heat'),
                ('Perfectly inelastic', 'Objects stick together; maximum KE loss'),
                ('Coefficient of restitution', 'e = |v_rel after|/|v_rel before|; e = 1 elastic, e = 0 perfectly inelastic'),
                ('Glancing collision', '2D collision where object changes direction')],
               ['Apply both momentum and energy conservation to elastic collisions.',
                'Solve perfectly inelastic collision problems and find KE lost.',
                'Set up momentum conservation in x and y for 2D collisions.'],
               ['Free-response: 2D elastic collision with one mass initially at rest.',
                'Calculate KE lost in a perfectly inelastic collision.',
                'Derive elastic collision formulas from momentum + energy conservation.'],
               ['Derive 1D elastic collision formulas algebraically.',
                'Solve 3–4 collision problems including at least one 2D case.'],
               [('Derive the formulas for elastic collision of m₁ (v₁) with stationary m₂.', ['Momentum: m₁v₁ = m₁v₁\' + m₂v₂\'  ... (1)', 'Energy: ½m₁v₁² = ½m₁v₁\'² + ½m₂v₂\'²  ... (2)', 'Factor energy eq: m₁(v₁-v₁\')(v₁+v₁\') = m₂v₂\'²; divide by momentum eq', 'Result: v₁\' = (m₁-m₂)/(m₁+m₂) × v₁; v₂\' = 2m₁/(m₁+m₂) × v₁']),
                ('Equal-mass elastic collision: m₁ = m₂ = m, v₁ initial. Find v₁\' and v₂\'.', ['v₁\' = (m-m)/(m+m) × v₁ = 0', 'v₂\' = 2m/(m+m) × v₁ = v₁', 'First ball stops; second ball takes on first ball\'s velocity', 'This is Newton\'s cradle — all momentum and KE transfer']),
                ('A 2 kg ball (5 m/s) hits a stationary 3 kg ball. They stick together. Find v_f and KE lost.', ['v_f = (2)(5)/(2+3) = 2.0 m/s', 'KE_i = ½(2)(25) = 25 J; KE_f = ½(5)(4) = 10 J', 'KE lost = 25 - 10 = 15 J (converted to heat/sound/deformation)', 'This is a perfectly inelastic collision']),
                ('A 1 kg ball (8 m/s east) glances off a 2 kg ball and deflects north at 4 m/s. Find final velocity of 2 kg ball.', ['x-momentum: 1(8) + 0 = 1(0) + 2v₂x → v₂x = 4 m/s east', 'y-momentum: 0 + 0 = 1(4) + 2v₂y → v₂y = -2 m/s south', 'v₂ = √(16+4) = √20 ≈ 4.47 m/s at angle arctan(-2/4) below east', 'Check KE to determine if elastic or inelastic']),
                ('When can kinetic energy be conserved in a collision?', ['Only in perfectly elastic collisions (no deformation, no heat)', 'Billiard balls, atomic/nuclear collisions (approximately elastic)', 'Macroscopic objects always deform → always some KE loss', 'Elastic collisions: no permanent deformation, all forces conservative'])],
               [('Bozeman Collisions', 'Elastic and inelastic collisions — conservation laws', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Elastic Collision', '1D elastic collision derivation and examples', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Elastic: both p and KE conserved; equal mass → velocities exchange.',
                'Perfectly inelastic: stick together; maximum KE loss; only p conserved.',
                '2D: apply Δp_x = 0 and Δp_y = 0 separately.']),

            _l('Variable-Mass Systems and Rocket Propulsion',
               [_t('Rocket Equation', 'Thrust T = v_ex × |dM/dt|; rocket equation: M(dv/dt) = T - F_drag - Mg. As fuel burns, M decreases and acceleration increases for constant thrust.', 'The rocket equation requires careful sign conventions: v_exhaust is relative to the rocket.', 'Apply rocket thrust equation to find acceleration or velocity change.'),
                _t('Tsiolkovsky Rocket Equation', 'Δv = v_ex ln(M_i/M_f) for a rocket in gravity-free space. This is derived by integrating M dv = -v_ex dM.', 'The mass ratio M_i/M_f determines Δv — large fuel fraction means large velocity change.', 'Apply the Tsiolkovsky equation to find Δv for given mass ratio and exhaust speed.'),
                _t('Conveyor Belt and Rain Problems', 'When mass is added to a moving object (rain on a car, sand on a belt), F_ext = dp/dt = d(Mv)/dt. If v is maintained constant, extra force is required to compensate for increased mass.', 'Force to maintain constant speed on a conveyor belt with added mass: F = v × (dm/dt) — additional force needed for momentum of added mass.', 'Apply F = dp/dt to variable-mass problems other than rockets.')],
               [('Thrust', 'F_thrust = v_ex × |dM/dt|; force from ejected propellant'),
                ('Tsiolkovsky equation', 'Δv = v_ex ln(M_i/M_f) for rocket in free space'),
                ('Mass ratio', 'M_i/M_f; determines Δv; larger ratio → greater velocity change'),
                ('Exhaust velocity', 'v_ex; speed of exhaust relative to rocket; determines efficiency'),
                ('Conveyor belt problem', 'Variable-mass system: F = v(dm/dt) to maintain constant speed')],
               ['Calculate thrust force from exhaust velocity and mass flow rate.',
                'Apply Tsiolkovsky equation to find Δv or required mass ratio.',
                'Solve conveyor belt and rain-on-cart problems using F = dp/dt.'],
               ['Free-response: rocket in gravity — write and analyze equation of motion.',
                'Tsiolkovsky: find mass ratio required for Δv = 8 km/s with v_ex = 3 km/s.',
                'Conveyor belt: find motor power to maintain belt speed with added sand.'],
               ['Derive the Tsiolkovsky equation from M dv = -v_ex dM.',
                'Practice rocket problems with and without gravity.'],
               [('A rocket ejects 10 kg/s of exhaust at 3000 m/s. Find the thrust force.', ['Thrust = v_ex × |dM/dt| = 3000 × 10 = 30 000 N = 30 kN', 'This is the force that accelerates the rocket', 'For a 1000 kg rocket: a = (30 000 - mg)/1000 ≈ 20.2 m/s²', 'As fuel burns, M decreases and a increases for same thrust']),
                ('Apply Tsiolkovsky: v_ex = 4000 m/s, M_i = 10 000 kg, M_f = 2000 kg. Find Δv.', ['Δv = v_ex ln(M_i/M_f) = 4000 ln(10 000/2000)', 'Δv = 4000 ln(5) = 4000 × 1.609 = 6437 m/s ≈ 6.4 km/s', 'Burning 80% of mass gives this Δv', 'Earth orbital speed ≈ 7.9 km/s → near-orbital capability']),
                ('Derive the Tsiolkovsky equation from first principles.', ['M(dv) = -v_ex dM (rocket ejects dm at speed v_ex)', 'Separate: dv = -v_ex dM/M', 'Integrate: Δv = ∫dv = -v_ex ∫(dM/M) = -v_ex [ln M]_{M_i}^{M_f}', 'Δv = v_ex ln(M_i/M_f) (positive since M_i > M_f)']),
                ('Sand falls at 5 kg/s onto a flatcar (1000 kg) moving at 2 m/s. What force is needed to maintain constant speed?', ['F = v × (dm/dt) = 2 × 5 = 10 N', 'Without this force, momentum of added sand would slow the car', 'F maintains v = const by giving incoming sand the car\'s velocity', 'Power required: P = Fv = 10 × 2 = 20 W']),
                ('Why do multistage rockets achieve higher Δv than single-stage rockets?', ['Single stage must carry entire empty fuel tank mass throughout flight', 'Multistage drops empty tanks → reduces M_f for subsequent stages', 'Lower M_f → larger M_i/M_f ratio → larger Δv per Tsiolkovsky', 'Mass ratio exponential effect makes staging highly effective'])],
               [('Bozeman Rocket Propulsion', 'Thrust, Tsiolkovsky equation, and variable mass', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Variable Mass', 'Variable-mass systems and rocket equation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Thrust = v_ex × |dM/dt|.',
                'Tsiolkovsky: Δv = v_ex ln(M_i/M_f).',
                'Conveyor belt: F = v(dm/dt) to maintain constant speed.'])
        ],
        'unit_qs': [
            ('Four masses: 1 kg at (0,0), 2 kg at (3,0), 3 kg at (0,4), 4 kg at (3,4) m. Find the center of mass.',
             ['x_cm = (1×0 + 2×3 + 3×0 + 4×3)/10 = (0+6+0+12)/10 = 18/10 = 1.8 m', 'y_cm = (1×0 + 2×0 + 3×4 + 4×4)/10 = (0+0+12+16)/10 = 28/10 = 2.8 m', 'CM is at (1.8, 2.8) m', 'Closer to the heavier masses in both dimensions']),
            ('A 3 kg ball moving at 6 m/s collides elastically with a stationary 1 kg ball. Find both final velocities.',
             ['v₁\' = (m₁-m₂)v₁/(m₁+m₂) = (2/4)(6) = 3 m/s (forward)', 'v₂\' = 2m₁v₁/(m₁+m₂) = (6/4)(6) = 9 m/s (forward)', 'Check momentum: 3(6) = 3(3) + 1(9) = 18 ✓', 'Check KE: ½(3)(36) = ½(3)(9) + ½(1)(81) = 13.5 + 40.5 = 54 ✓']),
            ('A force F(t) = 8sin(πt) N acts on a 2 kg object for 0 ≤ t ≤ 1 s. The object starts at rest. Find final speed.',
             ['J = ∫₀¹ 8sin(πt) dt = [-8/π cos(πt)]₀¹ = (-8/π)(-1-1) = 16/π ≈ 5.09 N·s', 'J = Δp = mv_f - 0 → v_f = J/m = 5.09/2 ≈ 2.55 m/s', 'Impulse from oscillating force is found by integration', 'Average force = J/Δt = 5.09 N']),
            ('A 5 kg block (10 m/s) hits a 3 kg block (2 m/s, same direction). After collision, the 5 kg block moves at 6 m/s. Find 3 kg final velocity and KE change.',
             ['p_initial = 5(10) + 3(2) = 56 kg·m/s', 'p_final: 5(6) + 3v₂ = 56 → 3v₂ = 26 → v₂ ≈ 8.67 m/s', 'KE_i = ½(5)(100) + ½(3)(4) = 250 + 6 = 256 J', 'KE_f = ½(5)(36) + ½(3)(75.2) = 90 + 112.8 = 202.8 J; ΔKE = -53.2 J']),
            ('A rocket in space (M_i = 5000 kg, M_f = 1000 kg) uses exhaust speed v_ex = 2500 m/s. Find Δv.',
             ['Δv = v_ex ln(M_i/M_f) = 2500 ln(5000/1000) = 2500 ln(5)', 'Δv = 2500 × 1.609 = 4023 m/s ≈ 4.0 km/s', 'Starting from rest, final speed = 4.0 km/s', '80% of initial mass was fuel']),
            ('Explain why momentum is conserved in a collision even though kinetic energy is not.',
             ['Momentum is related to impulse: Δp = F_ext × Δt; in a collision, no external horizontal force acts → p conserved', 'KE is related to work; internal forces (deformation) can do negative work → KE can decrease', 'Energy is dissipated as heat/sound/deformation — lost from mechanical energy', 'The first law of thermodynamics is not violated; total energy IS conserved']),
            ('A 0.3 kg ball (15 m/s east) bounces off a wall and returns at 12 m/s west. Contact time = 0.05 s. Find average force.',
             ['Δp = m(v_f - v_i) = 0.3(-12 - 15) = 0.3(-27) = -8.1 kg·m/s (westward)', 'F_avg = Δp/Δt = -8.1/0.05 = -162 N (wall pushes west on ball)', 'Magnitude of force = 162 N', 'Short contact time → large average force (why padding matters)']),
            ('Derive F = dp/dt from Newton\'s 2nd law for a variable-mass system.',
             ['p = Mv (momentum of system with variable mass M)', 'F_net = dp/dt = d(Mv)/dt = M(dv/dt) + v(dM/dt)', 'M(dv/dt) = Ma is the usual term; v(dM/dt) is the momentum-change term', 'For a rocket: dM/dt < 0 (losing mass) → thrust from exhausted mass']),
            ('A 2 kg block moving right at 5 m/s collides with a 2 kg block moving left at 3 m/s. They stick. Find final velocity and KE lost.',
             ['p_i = 2(5) + 2(-3) = 10 - 6 = 4 kg·m/s', 'p_f = (2+2)v_f = 4 → v_f = 1 m/s (rightward)', 'KE_i = ½(2)(25) + ½(2)(9) = 25 + 9 = 34 J', 'KE_f = ½(4)(1) = 2 J; KE lost = 32 J']),
            ('A uniform semicircular rod of mass M and radius R. Find the y-coordinate of its center of mass.',
             ['Parameterize: x = R cosθ, y = R sinθ, 0 ≤ θ ≤ π', 'dm = (M/πR) R dθ = (M/π) dθ', 'y_cm = (1/M)∫y dm = (1/M)∫₀^π R sinθ (M/π) dθ', 'y_cm = (R/π)[-cosθ]₀^π = (R/π)(2) = 2R/π ≈ 0.637R above diameter'])
        ]
    },
]
