NAME        = 'AP® Physics C: Mechanics'
ABBREV      = 'physc'
SLUG        = 'ap-physics-c-mechanics'
COURSE_FILE = 'ap-physics-c-mechanics.html'
ACCENT_COLOR = '#10b981'

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+C+Mechanics+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+C+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content,
            'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 5, 'title': 'Rotation',
        'file': 'ap-physics-c-mechanics-5-unit-5-torque-and-rotational-dynamics.html',
        'desc': 'Rotational kinematics, torque, moment of inertia, rotational energy, and angular momentum.',
        'gateway': [
            'Apply calculus-based rotational kinematics: α = dω/dt, ω = dθ/dt.',
            'Calculate torque and apply Newton\'s 2nd law for rotation: τ_net = Iα.',
            'Compute moment of inertia for common shapes using integrals.',
            'Apply conservation of angular momentum to isolated systems.',
        ],
        'lessons': [
            _l('Rotational Kinematics',
               [_t('Angular Position, Velocity, and Acceleration', 'θ = angular position (rad); ω = dθ/dt (rad/s); α = dω/dt = d²θ/dt² (rad/s²). All directly analogous to linear kinematics with x→θ, v→ω, a→α.', 'Angular quantities are not vectors in 3D (they are for ω and α), but in AP® C problems they are treated as scalars with sign indicating direction.', 'Differentiate and integrate angular position functions; apply rotational kinematic equations.'),
                _t('Constant Angular Acceleration Equations', 'For constant α: ω = ω₀ + αt; θ = θ₀ + ω₀t + ½αt²; ω² = ω₀² + 2αΔθ. These mirror the linear equations.', 'Do NOT use these equations if α is a function of time — integrate α(t) instead.', 'Solve rotational problems with constant α analogously to linear kinematics.'),
                _t('Relating Linear and Rotational Quantities', 'For a point at radius r: s = rθ; v_t = rω; a_t = rα; a_c = v²/r = rω². Rolling without slipping: v_cm = rω; a_cm = rα.', 'Tangential and centripetal accelerations are distinct: a_t = rα (changing speed); a_c = rω² (changing direction).', 'Convert between linear and angular quantities using radius.')],
               [('θ (angular position)', 'Angle measured in radians from a reference line'),
                ('ω = dθ/dt', 'Angular velocity (rad/s)'),
                ('α = dω/dt', 'Angular acceleration (rad/s²)'),
                ('v_t = rω', 'Tangential speed of a point at radius r'),
                ('Rolling condition', 'v_cm = rω for rolling without slipping')],
               ['Differentiate θ(t) to find ω(t) and α(t).',
                'Apply constant-α rotational equations.',
                'Convert between tangential and angular quantities using r.'],
               ['Free-response: find α(t) by differentiating given ω(t).',
                'Constant α: find angle rotated and angular speed after time t.',
                'Rolling: find speed of a point on the rim of a rolling wheel.'],
               ['Derive constant-α equations by integrating α = const.',
                'Practice linear-rotational quantity conversions for various radii.'],
               [('A wheel starts at rest and has α(t) = 4t rad/s². Find ω(t) and θ after 3 s.', ['ω(t) = ∫4t dt = 2t²; ω(0) = 0 → ω(t) = 2t²', 'ω(3) = 18 rad/s', 'θ = ∫₀³ 2t² dt = [2t³/3]₀³ = 18 rad', 'θ ≈ 18 rad ≈ 2.86 revolutions']),
                ('A wheel (r = 0.5 m) rotates at ω = 10 rad/s. Find v_t and a_c at the rim.', ['v_t = rω = 0.5 × 10 = 5 m/s', 'a_c = rω² = 0.5 × 100 = 50 m/s²', 'a_c directed toward center; v_t tangent to rim', 'For a_t: would need α ≠ 0']),
                ('A disk starts at ω₀ = 5 rad/s and decelerates at α = -2 rad/s². Find time to stop and θ traveled.', ['ω = 0 = 5 - 2t → t = 2.5 s', 'θ = ω₀t + ½αt² = 5(2.5) + ½(-2)(6.25) = 12.5 - 6.25 = 6.25 rad', 'Or: ω² = ω₀² + 2αθ → 0 = 25 - 4θ → θ = 6.25 rad ✓', 'About 1 revolution (2π ≈ 6.28 rad)']),
                ('A bicycle wheel (r = 0.35 m) rolls without slipping at 5 m/s. Find ω and the speed of the top of the wheel.', ['ω = v_cm/r = 5/0.35 ≈ 14.3 rad/s', 'Speed of top = v_cm + rω = 5 + 5 = 10 m/s (top moves at 2v_cm)', 'Speed of bottom contact point = 0 (rolling condition)', 'Instantaneous axis of rotation is at the contact point']),
                ('Derive the rolling-without-slipping condition v_cm = rω from geometry.', ['As wheel rolls, arc length on ground = arc length on wheel', 'Distance traveled by CM = s = rθ', 'Differentiate: v_cm = ds/dt = r(dθ/dt) = rω', 'This holds only if there is no slipping at the contact point'])],
               [('Bozeman Rotational Kinematics', 'Angular velocity, acceleration, and rolling', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Angular Kinematics', 'ω, α, θ derivations and constant-α problems', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['ω = dθ/dt; α = dω/dt; integrate to get θ(t) from α(t).',
                'Constant α: same structure as linear equations.',
                'Rolling: v_cm = rω; top of wheel moves at 2v_cm; bottom at 0.']),

            _l('Torque and Newton\'s Second Law for Rotation',
               [_t('Torque', 'τ = r × F = rF sinθ (N·m). Torque is the rotational analog of force; it depends on force, lever arm, and angle. Choose the correct pivot point.', 'Torque is NOT the same as force — it includes the lever arm (perpendicular distance from pivot to line of action).', 'Calculate torques from multiple forces about a specified pivot point.'),
                _t('Newton\'s Second Law for Rotation', 'τ_net = Iα, where I is the moment of inertia (kg·m²) and α is angular acceleration. Analogous to F_net = ma.', 'I is not constant if mass distribution changes; τ_net must include all torques about the same axis.', 'Apply τ = Iα to rotating systems; combine with translational F = ma for rolling objects.'),
                _t('Static Equilibrium', 'For a rigid body in static equilibrium: ΣF = 0 and Στ = 0 about any point. Choose the pivot to eliminate unknown forces and simplify calculation.', 'The condition Στ = 0 must be satisfied about ANY axis — choosing wisely can eliminate unknowns.', 'Solve static equilibrium problems (beams, ladders, levers).')],
               [('Torque τ', 'τ = rF sinθ = r⊥F = rF⊥; rotational effect of a force'),
                ('Lever arm', 'Perpendicular distance from pivot to line of action of force'),
                ('Moment of inertia I', 'I = Σm_i r_i² or ∫r² dm; rotational inertia'),
                ('τ_net = Iα', 'Rotational Newton\'s 2nd law'),
                ('Static equilibrium', 'ΣF = 0 and Στ = 0; no translation or rotation')],
               ['Calculate torque for forces at various angles about a given pivot.',
                'Apply τ_net = Iα to find angular acceleration.',
                'Solve static equilibrium problems using ΣF = 0 and Στ = 0.'],
               ['Free-response: beam supported at two points — find both normal forces.',
                'Rotation: find α for a disk given net torque and I.',
                'Ladder leaning against wall: find minimum friction coefficient.'],
               ['Practice torque calculations for multiple forces.',
                'Solve at least 3 static equilibrium problems (beam, ladder, see-saw).'],
               [('A 4 m uniform beam (mass 30 kg) is supported at one end and at 3 m from that end. A 20 kg mass hangs at 4 m. Find the support forces.', ['Pivot at left end; Στ = 0: R₂(3) = 30g(2) + 20g(4)', 'R₂(3) = 588 + 784 = 1372 → R₂ = 457 N', 'ΣF_y = 0: R₁ + R₂ = (30+20)g = 490 N → R₁ = 33 N', 'Choose pivot to eliminate one unknown; find the other from force balance']),
                ('A disk (I = 0.5 kg·m²) has a net torque of 3 N·m applied. Find α.', ['τ = Iα → α = τ/I = 3/0.5 = 6 rad/s²', 'Analogous to a = F/m in linear dynamics', 'Larger I → smaller α for same torque', 'I depends on mass distribution, not just total mass']),
                ('What is the torque of a 100 N force applied at 30° to a 2 m wrench?', ['τ = rF sinθ = 2 × 100 × sin30° = 2 × 100 × 0.5 = 100 N·m', 'Maximum torque when θ = 90° (force perpendicular to lever arm)', 'Lever arm = r sinθ = 2 sin30° = 1 m', 'τ = F × lever arm = 100 × 1 = 100 N·m (same answer)']),
                ('A uniform ladder (5 m, 20 kg) leans at 60° against a frictionless wall. Find friction force at floor.', ['Pivot at floor: Στ = 0: N_wall(5 sin60°) = mg(2.5 cos60°)', 'N_wall(4.33) = 20(9.8)(1.25) = 245 → N_wall = 56.6 N', 'ΣF_x = 0: f = N_wall = 56.6 N', 'Minimum μ_s = f/N_floor = 56.6/(20 × 9.8) = 0.289']),
                ('Why is choosing the pivot point at an unknown force\'s location useful in static equilibrium?', ['If the unknown force passes through the pivot, its torque = 0', 'This removes that unknown from the torque equation', 'Simplifies problem to solving for one unknown at a time', 'Torque equilibrium must hold about ANY chosen point'])],
               [('Bozeman Torque and Equilibrium', 'Torque, τ = Iα, and static equilibrium', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Torque', 'Torque calculations and rotational Newton\'s law', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['τ = rF sinθ; lever arm is perpendicular distance.',
                'τ_net = Iα; choose pivot to eliminate unknowns.',
                'Static equilibrium: ΣF = 0 AND Στ = 0 simultaneously.']),

            _l('Moment of Inertia',
               [_t('Discrete System Moment of Inertia', 'I = Σm_i r_i² for point masses. I depends on both mass and distribution — farther from axis means larger I.', 'I depends on which axis is chosen — always specify the rotation axis.', 'Calculate I for systems of point masses about a given axis.'),
                _t('Continuous Distribution: Integration', 'I = ∫r² dm; use geometric relationships to express dm in terms of the integration variable. Common results: disk = ½MR², rod about CM = (1/12)ML², sphere = (2/5)MR².', 'The moment of inertia of a solid disk is ½MR², NOT MR² — the mass is distributed at various distances, not all at the rim.', 'Derive moments of inertia for rods and disks using integration.'),
                _t('Parallel Axis Theorem', 'I_parallel = I_cm + Md², where d is the distance from CM to the new axis. Allows calculation of I about any axis from the CM result.', 'The parallel axis theorem ADDS Md² to I_cm — it never gives a smaller I than the CM result.', 'Apply the parallel axis theorem to find I about axes not through the CM.')],
               [('Moment of inertia I', 'I = ∫r² dm; measure of rotational inertia (kg·m²)'),
                ('Parallel axis theorem', 'I = I_cm + Md²; I about any axis from CM result'),
                ('I for common shapes', 'Disk: ½MR²; rod (CM): (1/12)ML²; solid sphere: (2/5)MR²'),
                ('Radius of gyration k', 'I = Mk²; effective radius at which all mass could be concentrated'),
                ('Hollow vs. solid cylinder', 'Hollow shell I = MR²; solid I = ½MR² (mass is closer to axis)')],
               ['Calculate I for point mass systems.',
                'Derive I for a uniform rod and disk using integration.',
                'Apply the parallel axis theorem for off-CM axes.'],
               ['Free-response: derive I for a thin rod about one end using integration.',
                'Calculate I for a system of a disk plus attached masses.',
                'Apply parallel axis theorem to find I for a disk about its rim.'],
               ['Derive I_rod (end) from I_rod (CM) using the parallel axis theorem.',
                'Verify I_disk = ½MR² using integration.'],
               [('Find I of a uniform rod (mass M, length L) about one end using integration.', ['dm = (M/L)dx; r = x (distance from end)', 'I = ∫₀ᴸ x²(M/L)dx = (M/L)[x³/3]₀ᴸ = (M/L)(L³/3) = (1/3)ML²', 'Compare: I_cm (center) = (1/12)ML²', 'I_end = I_cm + M(L/2)² = ML²/12 + ML²/4 = ML²/3 ✓ (parallel axis)']),
                ('Derive I for a uniform disk of mass M, radius R about its axis.', ['dm = σ(2πr dr) where σ = M/(πR²)', 'I = ∫₀ᴿ r²(2πσr)dr = 2πσ∫₀ᴿ r³ dr = 2πσ(R⁴/4) = πσR⁴/2', 'Substituting σ = M/(πR²): I = M R²/2 = ½MR²', 'Result: solid disk I = ½MR²']),
                ('Apply the parallel axis theorem to find I for a disk about a point on its rim.', ['I_cm = ½MR²; d = R (CM to rim)', 'I_rim = I_cm + Md² = ½MR² + MR² = (3/2)MR²', 'I about rim is 3× the CM value about center', 'Use for rolling disk problems where contact point is the instantaneous axis']),
                ('Why does a figure skater spin faster when pulling in their arms?', ['Pulling arms in reduces I (mass moves closer to spin axis)', 'No external torque → angular momentum L = Iω conserved', 'If I decreases, ω must increase to keep L constant', 'Kinetic energy actually increases — comes from work done by skater\'s muscles']),
                ('Which has greater I: a hollow cylinder or solid cylinder of the same M and R? Why?', ['Hollow cylinder I = MR² (all mass at radius R)', 'Solid cylinder I = ½MR² (mass distributed from 0 to R)', 'Hollow cylinder has larger I because all mass is at maximum radius', 'Greater I requires more torque for same angular acceleration'])],
               [('Bozeman Moment of Inertia', 'I integration, parallel axis theorem', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics I Integration', 'Deriving moment of inertia by integration', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['I = ∫r² dm; rod (end) = ⅓ML²; disk = ½MR².',
                'Parallel axis: I = I_cm + Md².',
                'Greater distance from axis → larger I → harder to angularly accelerate.']),

            _l('Angular Momentum and Rotational Energy',
               [_t('Angular Momentum', 'L = Iω for a rigid body; L = r × p = r × mv for a particle. Conservation: if τ_ext = 0, then L = constant.', 'Angular momentum of a point mass is not zero even for straight-line motion — it is r × mv about any point not on the line of motion.', 'Calculate L for rotating bodies and for particles in linear or circular motion.'),
                _t('Conservation of Angular Momentum', 'When τ_ext = 0: L_i = L_f → I_i ω_i = I_f ω_f. Applies to collisions involving rotation, spinning skaters, etc.', 'Angular momentum is conserved for the system — internal forces and torques do not change the total.', 'Apply L conservation to collisions with rotating objects and changing moment of inertia.'),
                _t('Rotational Kinetic Energy', 'KE_rot = ½Iω²; rolling objects have both KE_trans = ½mv_cm² and KE_rot = ½Iω². Total KE = ½mv² + ½Iω².', 'A rolling object has MORE kinetic energy than a sliding object of the same mass and speed — some energy is in rotation.', 'Apply energy conservation to rolling objects including rotational KE.')],
               [('Angular momentum L', 'L = Iω (rigid body); L = r × p (particle); units: kg·m²/s'),
                ('L conservation', 'L = const when τ_ext = 0; I_i ω_i = I_f ω_f'),
                ('Rotational KE', 'KE_rot = ½Iω²; must add to translational KE for rolling'),
                ('Total rolling KE', 'KE_total = ½mv² + ½Iω² = ½mv²(1 + I/(mr²))'),
                ('Rotational work', 'W_rot = τΔθ; work done by a torque over an angular displacement')],
               ['Calculate angular momentum for rotating rigid bodies and particles.',
                'Apply L conservation to solve rotation + collision problems.',
                'Include rotational KE in energy conservation for rolling objects.'],
               ['Free-response: ball rolling down a ramp — find speed using energy with rotation.',
                'Collision: mass lands on a rotating disk — find final ω.',
                'L conservation: spinning skater changes I; find final ω.'],
               ['Practice energy conservation with rolling for several shapes.',
                'Solve angular momentum collision problems.'],
               [('A solid sphere (M = 2 kg, R = 0.1 m) rolls from rest down a 3 m high ramp. Find speed at bottom.', ['Energy: mgh = ½mv² + ½Iω²; I_sphere = (2/5)MR²; ω = v/R', 'mgh = ½mv² + ½(2/5)MR²(v/R)² = ½mv²(1 + 2/5) = (7/10)mv²', 'v = √(10gh/7) = √(10 × 9.8 × 3/7) = √42 ≈ 6.48 m/s', 'Compare: no rotation gives v = √(2gh) = 7.67 m/s (faster without rotation)']),
                ('A disk (I = 0.4 kg·m²) spins at ω = 20 rad/s. A 0.5 kg mass is placed at r = 0.8 m from center. Find new ω.', ['L_i = Iω = 0.4 × 20 = 8 kg·m²/s', 'I_f = 0.4 + (0.5)(0.8)² = 0.4 + 0.32 = 0.72 kg·m²', 'ω_f = L_i/I_f = 8/0.72 ≈ 11.1 rad/s', 'Adding mass at distance increases I → ω decreases']),
                ('A 0.1 kg ball (v = 5 m/s) hits a stationary rod (M = 0.5 kg, L = 1 m) at its end; they stick. Find ω after. (I_rod_end = (1/3)ML²)', ['Angular momentum about pivot (rod end): L_i = m × v × L = 0.1 × 5 × 1 = 0.5 kg·m²/s', 'I_total = (1/3)ML² + m(L)² = (1/3)(0.5)(1) + 0.1(1) = 0.167 + 0.1 = 0.267 kg·m²', 'ω_f = L_i/I_total = 0.5/0.267 ≈ 1.87 rad/s', 'Momentum is NOT conserved (pivot exerts force); only angular momentum is']),
                ('A disk (KE_rot = 50 J) rotates at ω = 10 rad/s. Find its moment of inertia.', ['KE_rot = ½Iω² → I = 2 KE/ω² = 2(50)/100 = 1.0 kg·m²', 'Equivalent to I = 2(50)/10² = 1.0 kg·m²', 'KE depends on both I and ω', 'A larger I at the same ω stores more rotational KE']),
                ('A planet in elliptical orbit speeds up as it approaches the Sun. Explain using angular momentum.', ['No torque acts on the planet about the Sun (gravity is along r)', 'Angular momentum L = mvr sin90° = mv⊥r = const', 'Closer to Sun: smaller r → larger v⊥ (must increase)', 'This is Kepler\'s 2nd law: equal areas in equal times'])],
               [('Bozeman Angular Momentum', 'L = Iω, conservation, and rolling energy', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Rolling Energy', 'Rolling KE = translational + rotational', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['L = Iω; conserved when τ_ext = 0.',
                'Rolling KE = ½mv² + ½Iω²; use energy conservation.',
                'L conservation: I_i ω_i = I_f ω_f when no external torque.'])
        ],
        'unit_qs': [
            ('A wheel starts at ω₀ = 2 rad/s and has constant α = 3 rad/s². Find ω and θ at t = 4 s.',
             ['ω = ω₀ + αt = 2 + 3(4) = 14 rad/s', 'θ = ω₀t + ½αt² = 2(4) + ½(3)(16) = 8 + 24 = 32 rad', 'θ = 32 rad × (1 rev/2π) ≈ 5.09 revolutions', 'ω² = 4 + 2(3)(32) = 196 → ω = 14 rad/s ✓']),
            ('Derive I for a uniform disk of radius R and mass M about its symmetry axis.',
             ['dm = σ(2πr dr) where σ = M/(πR²)', 'I = ∫₀ᴿ r²(2πσr)dr = 2πσ[r⁴/4]₀ᴿ = 2π(M/πR²)(R⁴/4)', 'I = MR²/2 = ½MR²', 'Result I = ½MR² applies to solid disk; hollow cylinder has I = MR²']),
            ('A solid cylinder (M, R) rolls without slipping down an incline (height h). Find speed at bottom using energy conservation.',
             ['mgh = ½mv² + ½(½mR²)(v/R)² = ½mv²(1 + ½) = ¾mv²', 'v = √(4gh/3)', 'Compare: solid sphere gives v = √(10gh/7), hollow cylinder gives v = √(gh)', 'More rotational inertia → slower linear speed at bottom']),
            ('A uniform beam (M = 10 kg, L = 4 m) is hinged at a wall and held horizontal by a cable at 30° at its far end. Find tension and hinge forces.',
             ['Pivot at hinge; Στ = 0: T sin30°(4) = Mg(2)', '2T = Mg = 98 → T = 49 N', 'ΣF_x: H_x = T cos30° = 49(0.866) = 42.4 N; ΣF_y: H_y + T sin30° = Mg', 'H_y = 98 - 24.5 = 73.5 N']),
            ('A potter\'s wheel (I = 1.2 kg·m²) spins at 100 rpm. A 0.4 kg lump of clay is dropped onto the rim (r = 0.3 m). Find new ω.',
             ['ω_i = 100 rpm × (2π/60) ≈ 10.47 rad/s', 'L_i = Iω_i = 1.2 × 10.47 = 12.57 kg·m²/s', 'I_f = 1.2 + 0.4(0.3)² = 1.2 + 0.036 = 1.236 kg·m²', 'ω_f = L_i/I_f = 12.57/1.236 ≈ 10.17 rad/s ≈ 97 rpm']),
            ('A torque τ = 6t - 2 N·m acts on a flywheel (I = 3 kg·m²) starting from rest. Find ω at t = 4 s.',
             ['α(t) = τ/I = (6t-2)/3 = 2t - 2/3', 'ω(t) = ∫₀ᵗ α dt\' = t² - (2/3)t', 'ω(4) = 16 - 8/3 = 16 - 2.67 = 13.33 rad/s', 'This requires integration since τ (and α) varies with time']),
            ('Explain why a hollow sphere rolls slower than a solid sphere down the same frictionless ramp.',
             ['Both convert mgh to KE; hollow sphere I_hollow = (2/3)MR² > I_solid = (2/5)MR²', 'Larger I → more energy goes into rotation → less into translation', 'v_hollow = √(6gh/5) < v_solid = √(10gh/7)', 'Greater rotational inertia means more energy is "tied up" in spinning']),
            ('A 0.2 kg mass is attached to the end of a 0.8 m massless rod that can rotate about the other end. Starting from horizontal, it swings down. Find ω at the bottom.',
             ['PE lost = mgh = 0.2(9.8)(0.8) = 1.568 J', 'KE = ½Iω²; I = mL² = 0.2(0.64) = 0.128 kg·m²', '1.568 = ½(0.128)ω² → ω² = 24.5 → ω ≈ 4.95 rad/s', 'v_t at bottom = Lω = 0.8(4.95) ≈ 3.96 m/s']),
            ('Two students (50 kg each) stand at the ends of a 3 m long uniform plank (30 kg) that can rotate. They walk toward each other. How does ω change?',
             ['As students walk in: r_student decreases → I_students decreases', 'Total I = I_plank + 2(m_student)(r_student²)', 'If L conserved (no external torque): ω increases as I decreases', 'Eventually when both at center: I = I_plank only → ω is maximum']),
            ('Angular momentum is a vector. For a spinning top, L is along the spin axis. If gravity exerts a torque on the top, explain what happens (precession).',
             ['τ = dL/dt; gravity torque τ = r × Mg perpendicular to L', 'dL = τ dt is perpendicular to L → L changes direction, not magnitude', 'L vector precesses (rotates) around vertical axis', 'Precession angular velocity: Ω = Mgr/(Lω) — faster spin → slower precession'])
        ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
    },

    {
        'num': 6, 'title': 'Oscillations',
        'file': 'ap-physics-c-mechanics-6-unit-6-energy-and-momentum-of-rotating-systems.html',
        'desc': 'Simple harmonic motion analyzed with calculus: differential equations, energy, and complex systems.',
        'gateway': [
            'Derive SHM from the differential equation d²x/dt² = -ω²x.',
            'Apply energy methods to find amplitude, speed, and acceleration in SHM.',
            'Analyze the pendulum and spring-mass as SHM systems with calculus.',
            'Describe damped and driven oscillations qualitatively and quantitatively.',
        ],
        'lessons': [
            _l('The SHM Differential Equation',
               [_t('Deriving the SHM Equation', 'From F = -kx and F = ma: m(d²x/dt²) = -kx → d²x/dt² = -(k/m)x = -ω²x where ω = √(k/m). The solution is x(t) = A cos(ωt + φ).', 'The angular frequency ω is not chosen — it is determined by the physical parameters k and m (or g and L for a pendulum).', 'Verify that x = A cos(ωt + φ) satisfies d²x/dt² = -ω²x.'),
                _t('General Solution and Initial Conditions', 'x(t) = A cos(ωt + φ); the constants A (amplitude) and φ (phase angle) are determined by initial conditions x(0) and v(0).', 'A and φ are not always 0 — they depend on when and how the motion was initiated.', 'Determine A and φ from initial conditions x₀ and v₀.'),
                _t('Velocity and Acceleration in SHM', 'v(t) = -Aω sin(ωt + φ); a(t) = -Aω² cos(ωt + φ) = -ω²x. The relationships v_max = Aω and a_max = Aω² follow.', 'v and a are 90° out of phase: v is maximum when x = 0; a is maximum (magnitude) when x = ±A.', 'Write and use v(t) and a(t) for a given SHM system.')],
               [('ω = √(k/m)', 'Angular frequency of spring-mass SHM'),
                ('x(t) = A cos(ωt + φ)', 'General SHM position function'),
                ('Phase angle φ', 'Determined by initial conditions; shifts the cosine function'),
                ('v_max = Aω', 'Maximum speed at x = 0'),
                ('a = -ω²x', 'SHM: acceleration proportional to and opposite to displacement')],
               ['Derive that x = A cos(ωt + φ) satisfies d²x/dt² = -ω²x.',
                'Determine A and φ from initial conditions.',
                'Compute v(t) and a(t) by differentiation.'],
               ['Free-response: given x(0) = 0.1 m and v(0) = 0, write x(t), v(t), a(t).',
                'Verify x = A sin(ωt) also satisfies the SHM ODE.',
                'Find maximum speed and acceleration for a given A and ω.'],
               ['Solve for A and φ for various initial conditions.',
                'Practice differentiating x(t) = A cos(ωt + φ) twice to verify a = -ω²x.'],
               [('A spring-mass (k = 100 N/m, m = 0.25 kg) starts at x(0) = 0.2 m, v(0) = 0. Write x(t).', ['ω = √(k/m) = √(400) = 20 rad/s', 'x(0) = A cosφ = 0.2 and v(0) = -Aω sinφ = 0 → sinφ = 0 → φ = 0', 'A = 0.2 m (since cosφ = 1)', 'x(t) = 0.2 cos(20t) m']),
                ('For the system above, find v(t) and a(t).', ['v(t) = dx/dt = -0.2(20) sin(20t) = -4 sin(20t) m/s', 'a(t) = dv/dt = -4(20) cos(20t) = -80 cos(20t) m/s²', 'Or: a = -ω²x = -(400)(0.2 cos20t) = -80 cos(20t) ✓', 'v_max = Aω = 4 m/s; a_max = Aω² = 80 m/s²']),
                ('Verify that x = A cos(ωt) satisfies d²x/dt² + ω²x = 0.', ['dx/dt = -Aω sin(ωt); d²x/dt² = -Aω² cos(ωt)', 'd²x/dt² + ω²x = -Aω² cos(ωt) + ω²(A cos(ωt)) = 0 ✓', 'Any A and phase angle φ works — constants determined by initial conditions', 'This confirms x = A cos(ωt + φ) is the general solution']),
                ('A spring-mass starts at x(0) = 0, v(0) = 3 m/s, ω = 6 rad/s. Find A and x(t).', ['x(0) = A cosφ = 0 → φ = ±π/2; take φ = π/2 (or use sine form)', 'v(0) = -Aω sin(π/2) = -Aω = 3 → A = -3/6 ... use sin form instead', 'x(t) = A sin(ωt): v(0) = Aω = 3 → A = 3/6 = 0.5 m', 'x(t) = 0.5 sin(6t) m']),
                ('The phase angle φ = π/4 for some oscillator. Describe the initial state.', ['x(0) = A cos(π/4) = A/√2 ≈ 0.707A (between 0 and A)', 'v(0) = -Aω sin(π/4) = -Aω/√2 < 0 (moving toward equilibrium)', 'Phase angle encodes both initial position and direction of motion', 'φ = 0 → starts at amplitude moving toward equilibrium from positive side'])],
               [('Bozeman SHM Differential Equation', 'Deriving and solving the SHM ODE', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics SHM Calculus', 'x(t), v(t), a(t) via calculus for SHM', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['SHM ODE: d²x/dt² = -ω²x; solution x = A cos(ωt + φ).',
                'A and φ from initial conditions; v = dx/dt; a = d²x/dt².',
                'v_max = Aω; a_max = Aω².']),

            _l('Energy in SHM and Pendulums',
               [_t('Energy in SHM', 'E = ½kA² = ½mv² + ½kx² (constant). At x = 0: all KE; at x = ±A: all PE. Speed at position x: v = ω√(A² - x²).', 'Total energy E = ½kA² is fixed by amplitude; energy continuously converts between KE and PE.', 'Apply energy conservation to find speed at any position in SHM.'),
                _t('Simple Pendulum as SHM', 'For small θ: F_restoring ≈ -mg sinθ ≈ -mgθ. Setting F = m(d²(Lθ)/dt²) gives d²θ/dt² = -(g/L)θ → ω = √(g/L). Valid only for small angles.', 'The pendulum is SHM only for small angles (θ < ~10°); for large angles, the period increases and the problem requires elliptic integrals.', 'Derive the pendulum ODE and apply it for small oscillations.'),
                _t('Physical Pendulum', 'A rigid body oscillating about a pivot: τ = -MgD sinθ ≈ -MgDθ for small θ; d²θ/dt² = -(MgD/I)θ → ω = √(MgD/I) where D is distance from pivot to CM.', 'The physical pendulum ODE requires knowing both I and the CM distance from the pivot.', 'Derive ω for a physical pendulum (disk, rod) about a given pivot.')],
               [('Energy in SHM', 'E = ½kA² = const; converts between KE and PE'),
                ('Speed in SHM', 'v = ω√(A² - x²) from energy conservation'),
                ('Simple pendulum', 'ω = √(g/L) for small oscillations'),
                ('Physical pendulum', 'ω = √(MgD/I); D = CM distance from pivot'),
                ('Small angle approximation', 'sinθ ≈ θ (in radians) for θ < 10°')],
               ['Apply energy conservation to find speed at any x in SHM.',
                'Derive the pendulum equation of motion and identify ω.',
                'Calculate ω for a physical pendulum given I and geometry.'],
               ['Free-response: derive d²θ/dt² + (g/L)θ = 0 for a simple pendulum.',
                'Physical pendulum: find period for a rod pivoting at one end.',
                'Energy: find position where KE = PE in SHM.'],
               ['Derive v = ω√(A² - x²) from energy conservation.',
                'Calculate ω for a uniform disk pendulum about its rim.'],
               [('A spring-mass (k = 50 N/m, m = 0.5 kg, A = 0.3 m). Find v when x = 0.1 m.', ['ω = √(k/m) = √(100) = 10 rad/s', 'v = ω√(A² - x²) = 10√(0.09 - 0.01) = 10√0.08', 'v = 10(0.283) = 2.83 m/s', 'Or: E = ½kA² = 2.25 J; KE = E - ½kx² = 2.25 - 0.25 = 2.0 J; v = √(2×2/0.5) = 2.83 m/s']),
                ('Derive the equation of motion for a simple pendulum and find T.', ['Net tangential force: F = -mg sinθ ≈ -mgθ', 'Tangential acceleration: a = L(d²θ/dt²)', 'mL(d²θ/dt²) = -mgθ → d²θ/dt² = -(g/L)θ', 'ω = √(g/L) → T = 2π/ω = 2π√(L/g)']),
                ('A uniform rod (M, L) pivots at one end and oscillates. Find T.', ['I_end = (1/3)ML²; CM is at L/2 from pivot → D = L/2', 'ω = √(MgD/I) = √(Mg(L/2)/((1/3)ML²)) = √(3g/(2L))', 'T = 2π√(2L/(3g))', 'Compare to simple pendulum of same length: T_rod < T_pendulum']),
                ('At what position in SHM is KE equal to PE?', ['KE = PE → ½mv² = ½kx²; and total E = ½kA²', 'KE + PE = E: 2PE = E → PE = E/2 → ½kx² = ½(½kA²)', 'x² = A²/2 → x = ±A/√2 = ±0.707A', 'KE = PE at x = ±A/√2; about 70.7% of amplitude']),
                ('Why does increasing pendulum amplitude (large angle) increase the period?', ['Small-angle SHM approximates sinθ ≈ θ (linear restoring force)', 'For large angles, sinθ < θ → restoring force is weaker than linear', 'Weaker restoring force → slower acceleration → longer period', 'Period increase is small for θ < 30° but grows for larger amplitudes'])],
               [('Bozeman Pendulum Calculus', 'Deriving pendulum ODE and physical pendulum', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Physical Pendulum', 'Physical pendulum ω derivation', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['v = ω√(A² - x²); KE = PE at x = A/√2.',
                'Simple pendulum: ω = √(g/L); small-angle only.',
                'Physical pendulum: ω = √(MgD/I).']),

            _l('Damped and Driven Oscillations',
               [_t('Damped Oscillations', 'With linear damping F_d = -bv: md²x/dt² + b(dx/dt) + kx = 0. Solution: x(t) = Ae^(-bt/2m) cos(ω\'t + φ); ω\' = √(ω₀² - (b/2m)²). Three regimes: underdamped, critically damped, overdamped.', 'Underdamping → oscillates with decreasing amplitude; critical damping → fastest approach to equilibrium without oscillating; overdamping → slow return without oscillating.', 'Classify damping regime given b and identify qualitative behavior.'),
                _t('Driven Oscillations and Resonance', 'When driven by F₀ cos(ω_d t): amplitude peaks at ω_d ≈ ω₀ (resonance). Amplitude A = F₀/(m√((ω₀²-ω_d²)² + (bω_d/m)²)). At resonance with low damping, A can be very large.', 'Resonance occurs at ω_d ≈ ω₀, not at ω_d = 0 or infinity — the driving frequency must MATCH the natural frequency.', 'Explain how damping limits resonance amplitude and identify resonance conditions.'),
                _t('Energy in Damped Systems', 'Energy of a damped oscillator: E(t) = ½kA² e^(-bt/m) — decays exponentially. Power dissipated = bv². Quality factor Q = ω₀m/b measures sharpness of resonance.', 'Energy decays at twice the rate of amplitude (since E ∝ A²).', 'Calculate energy dissipation rate and quality factor for damped oscillators.')],
               [('Underdamped', 'Oscillates with exponentially decreasing amplitude; ω\' < ω₀'),
                ('Critical damping', 'Fastest return to equilibrium without oscillation; b = 2√(km)'),
                ('Overdamped', 'Returns to equilibrium slowly without oscillating; b > 2√(km)'),
                ('Resonance', 'Maximum amplitude when ω_d = ω₀ (natural frequency)'),
                ('Quality factor Q', 'Q = ω₀m/b; higher Q → sharper resonance peak')],
               ['Classify oscillators as under-, over-, or critically damped.',
                'Explain resonance and how damping affects maximum amplitude.',
                'Calculate energy dissipation in a damped oscillator.'],
               ['Free-response: sketch amplitude vs. ω_d for driven oscillator with different damping.',
                'Calculate Q factor for a given oscillator; predict resonance peak width.',
                'Identify which damping regime applies given b, m, k.'],
               ['Compare the three damping regimes on position-time graphs.',
                'Research real-world resonance examples (MRI, musical instruments, suspension bridges).'],
               [('For m = 1 kg, k = 100 N/m, and b = 4 kg/s, classify the damping.', ['Critical damping b_c = 2√(km) = 2√(100) = 20 kg/s', 'b = 4 < b_c = 20 → underdamped', 'ω\' = √(ω₀² - (b/2m)²) = √(100 - 4) = √96 ≈ 9.8 rad/s', 'System oscillates with slowly decreasing amplitude']),
                ('Describe the three damping regimes and their engineering applications.', ['Underdamped: rings (door springs, shock absorbers that bounce)', 'Critical: optimal damping for instruments needing fast, no-oscillation return', 'Overdamped: massive hydraulic systems, heavy doors — slow return', 'Critical damping gives fastest return without oscillation — ideal for many applications']),
                ('How does resonance lead to structural failure?', ['Resonance: driving frequency matches natural frequency → large amplitude', 'If amplitude exceeds material strength, structure fails', 'Example: Tacoma Narrows Bridge (1940) — wind matched torsional natural frequency', 'Solution: change natural frequency (stiffening) or add damping (energy dissipation)']),
                ('The amplitude of a damped oscillator is x(t) = 0.5 e^(-0.5t) cos(10t). Find the damping coefficient b for m = 1 kg.', ['Exponent: -bt/(2m) = -0.5t → b/(2m) = 0.5 → b = 2(1)(0.5) = 1 kg/s', 'Natural frequency ω\' = 10 rad/s', 'ω₀ = √(ω\'² + (b/2m)²) = √(100 + 0.25) ≈ 10.01 rad/s', 'Very lightly damped: ω\' ≈ ω₀']),
                ('What is the Q factor and what does a high Q value mean physically?', ['Q = ω₀m/b = ω₀/Δω where Δω is resonance peak width (bandwidth)', 'High Q → sharp resonance peak, low damping, slow energy loss', 'Example: tuning fork Q ≈ 1000; optical cavity Q ≈ 10¹⁰', 'Higher Q → more energy oscillations before decay'])],
               [('Bozeman Damped Oscillations', 'Damping regimes and driven resonance', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Resonance', 'Driven oscillations and resonance amplitude', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Damping: underdamped oscillates; critical = fastest no-overshoot return.',
                'Resonance: maximum amplitude at ω_d = ω₀; damping limits peak.',
                'Energy decays exponentially: E ∝ e^{-bt/m}.']),

            _l('Coupled Oscillators and Normal Modes',
               [_t('Two Coupled Oscillators', 'Two masses connected by springs can oscillate in normal modes: in-phase (both move together, lower ω) and out-of-phase (move oppositely, higher ω). Each mode has a characteristic frequency.', 'Coupled oscillators have TWO natural frequencies (modes), not one — choosing initial conditions determines which mode is excited.', 'Identify normal modes and frequencies for a symmetric two-mass system.'),
                _t('Energy Transfer Between Coupled Oscillators', 'When two identical oscillators are weakly coupled and one is started, energy transfers periodically to the other and back (beats). Beat frequency = |ω₊ - ω₋|.', 'Beat frequency is the DIFFERENCE of the two mode frequencies, not their sum.', 'Describe qualitatively how energy transfers between coupled oscillators.'),
                _t('Superposition and Normal Mode Analysis', 'Any motion of a coupled system can be written as a superposition of normal modes. Each mode oscillates independently; complex motions are sums of simple normal modes.', 'Normal modes are independent: exciting one mode does not put energy into the other.', 'Express initial conditions as superposition of normal modes.')],
               [('Normal mode', 'Collective oscillation pattern where all parts move at same frequency'),
                ('In-phase mode', 'Masses move together; frequency ω₁ = √(k/m) for outer springs only'),
                ('Out-of-phase mode', 'Masses move oppositely; frequency ω₂ = √(k/m + 2k_c/m) with coupling'),
                ('Beat frequency', '|ω₊ - ω₋|; rate of energy transfer between coupled oscillators'),
                ('Superposition', 'General motion = linear combination of normal modes')],
               ['Identify in-phase and out-of-phase modes for coupled oscillators.',
                'Calculate normal mode frequencies for a symmetric system.',
                'Explain energy transfer as a beat phenomenon.'],
               ['Free-response: find normal mode frequencies for two masses and three springs.',
                'Qualitative: describe motion if only one mass is initially displaced.',
                'Beat period calculation given two mode frequencies.'],
               ['Analyze a symmetric two-mass, three-spring system for both modes.',
                'Simulate coupled oscillator motion and identify beat pattern.'],
               [('Two masses m on a string with three identical springs k (two outer, one middle). Find normal mode frequencies.', ['In-phase mode: middle spring not stretched; ω₁ = √(k/m)', 'Out-of-phase mode: middle spring maximally stretched; ω₂ = √(3k/m) ... depends on geometry', 'For symmetric system: ω₊ = √((k+2k_c)/m); ω₋ = √(k/m)', 'Exact values depend on spring arrangement']),
                ('If one mass of a weakly coupled system is displaced and released, describe the motion.', ['Initially: energy in first mass; it oscillates at approximately ω₀', 'Energy slowly transfers to second mass due to coupling', 'After half a beat period, all energy is in second mass', 'Process reverses — energy oscillates back and forth with beat frequency']),
                ('Why do normal modes oscillate at a single frequency?', ['In a normal mode, ALL particles have the same frequency and fixed amplitude ratios', 'They are eigenmodes of the system\'s equations of motion', 'Any initial condition can be decomposed into a combination of normal modes', 'Modes are independent — energy doesn\'t transfer between different normal modes']),
                ('What is the beat frequency for two modes with ω₁ = 10 rad/s and ω₂ = 12 rad/s?', ['Beat frequency = |ω₂ - ω₁| = 2 rad/s', 'Beat period = 2π/|Δω| = 2π/2 = π ≈ 3.14 s', 'Energy oscillates between the two oscillators with this period', 'Observation: oscillation within an envelope that beats at Δω']),
                ('Explain why a guitar string produces harmonics (overtones) in terms of normal modes.', ['A guitar string is a continuous system with infinitely many normal modes', 'Fundamental (1st harmonic): half wavelength fits on string', 'Overtones: integer multiples of fundamental frequency', 'Plucking excites several modes simultaneously; ear hears a mixture'])],
               [('Bozeman Coupled Oscillators', 'Normal modes and energy transfer', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Normal Modes', 'Two-mass coupled oscillator analysis', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Coupled oscillators have two normal modes: in-phase and out-of-phase.',
                'Beat frequency = |ω₊ - ω₋|; energy transfers between oscillators.',
                'General motion = superposition of normal modes.'])
        ],
        'unit_qs': [
            ('A spring (k = 200 N/m) attached to a 2 kg mass oscillates. At t = 0: x = 0, v = 4 m/s. Write x(t).',
             ['ω = √(200/2) = 10 rad/s', 'x(0) = A cosφ = 0 → φ = π/2; x(t) = A sin(ωt)', 'v(0) = Aω cos(0) = Aω = 4 → A = 4/10 = 0.4 m', 'x(t) = 0.4 sin(10t) m']),
            ('Derive the equation of motion for a physical pendulum (rod, pivot at end) and find T.',
             ['τ = -Mg(L/2)sinθ ≈ -Mg(L/2)θ; I_end = (1/3)ML²', 'I(d²θ/dt²) = -MgDθ → d²θ/dt² = -(MgD/I)θ = -(3g/2L)θ', 'ω = √(3g/2L); T = 2π√(2L/3g)', 'Compare: simple pendulum same L gives T = 2π√(L/g) → rod period < simple pendulum']),
            ('A damped spring-mass (m = 0.5 kg, k = 50 N/m, b = 1 kg/s). Find ω\', decay constant, and classify damping.',
             ['ω₀ = √(k/m) = √100 = 10 rad/s; b_c = 2√(km) = 2√25 = 10 kg/s', 'b = 1 < b_c = 10 → underdamped', 'ω\' = √(ω₀² - (b/2m)²) = √(100 - 1) = √99 ≈ 9.95 rad/s', 'Decay constant: b/2m = 1 kg/s; amplitude → 1/e in t = 2m/b = 1 s']),
            ('For a spring-mass (A = 0.5 m, ω = 8 rad/s), find x where KE = 3PE.',
             ['E = ½kA² = ½mω²A²; KE = 3PE → 4PE = E → PE = E/4', '½kx² = (1/4)½kA² → x² = A²/4 → x = ±A/2 = ±0.25 m', 'At x = ±A/2, KE is three times larger than PE', 'KE = 3(E/4) = 3E/4 (three-fourths of total energy is kinetic)']),
            ('Two identical pendulums (L = 0.5 m) are weakly coupled. Normal mode frequencies are ω₁ = 4.43 rad/s and ω₂ = 4.58 rad/s. Find beat period.',
             ['Beat frequency Δω = ω₂ - ω₁ = 0.15 rad/s', 'Beat period = 2π/Δω = 2π/0.15 ≈ 41.9 s', 'Energy transfers back and forth with this period', 'Each individual oscillation period ≈ 2π/4.43 ≈ 1.42 s']),
            ('A spring-mass (k = 80 N/m, m = 0.2 kg) oscillates with A = 0.15 m. Find total energy and speed at x = 0.05 m.',
             ['E = ½kA² = ½(80)(0.0225) = 0.9 J', 'KE at x = 0.05 m: KE = E - ½kx² = 0.9 - ½(80)(0.0025) = 0.9 - 0.1 = 0.8 J', 'v = √(2KE/m) = √(2 × 0.8/0.2) = √8 ≈ 2.83 m/s', 'Or: v = ω√(A² - x²) = 20√(0.0225-0.0025) = 20√0.02 ≈ 2.83 m/s ✓']),
            ('Explain why critical damping is ideal for a car\'s shock absorbers.',
             ['Underdamped: car bounces after a bump — uncomfortable and unsafe', 'Overdamped: car returns slowly — handling suffers on rough roads', 'Critical: fastest return to equilibrium without overshooting', 'Real shock absorbers are slightly underdamped for ride comfort']),
            ('A spring-mass oscillates as x(t) = 0.3 cos(5t + π/3) m. Find A, ω, T, x(0), and v(0).',
             ['A = 0.3 m; ω = 5 rad/s; T = 2π/5 ≈ 1.26 s', 'x(0) = 0.3 cos(π/3) = 0.3(0.5) = 0.15 m', 'v(0) = -0.3(5) sin(π/3) = -1.5(√3/2) = -1.299 m/s', 'Negative v(0): initially moving toward equilibrium from x > 0']),
            ('Describe qualitatively how resonance amplitude depends on damping at ω_d = ω₀.',
             ['At resonance: A = F₀/(bω₀) for linear damping', 'Lower damping b → larger amplitude at resonance', 'In the limit b → 0: A → ∞ (unrealistic; materials fail first)', 'Higher damping reduces and broadens the resonance peak (lower Q)']),
            ('Show that the power dissipated by linear damping is P = bv².',
             ['Damping force: F_d = -bv', 'Power: P = F · v = F_d × v = (-bv)(v) = -bv²', 'Negative sign: power removed from oscillator (dissipated)', 'Average power over one cycle: <P> = ½bω²A²e^(-bt/m) (for underdamped)'])
        ],
    'review_video': 'https://www.youtube.com/watch?v=Yd1RgfCjLC8',
    },

    {
        'num': 7, 'title': 'Gravitation',
        'file': 'ap-physics-c-mechanics-7-unit-7-oscillations.html',
        'desc': 'Newton\'s law of gravitation, gravitational fields, orbits, Kepler\'s laws, and escape velocity with calculus.',
        'gateway': [
            'Apply Newton\'s law of gravitation and the shell theorem rigorously.',
            'Derive Kepler\'s laws from Newton\'s law and conservation principles.',
            'Calculate orbital speed, period, and energy for circular and elliptical orbits.',
            'Find escape velocity using energy conservation; define binding energy.',
        ],
        'lessons': [
            _l('Gravitational Force and Field',
               [_t('Newton\'s Law of Gravitation', 'F = -Gm₁m₂/r² r̂ (vector form). The force is attractive, along the line joining the masses, and obeys an inverse square law.', 'The inverse square law means FORCE drops as 1/r², not 1/r — doubling distance quarters the force.', 'Calculate gravitational force and field at various positions; apply superposition for multiple masses.'),
                _t('Gravitational Field and Potential', 'g = -GM/r² r̂; gravitational potential V = -GM/r (J/kg). Potential energy U = mV = -GMm/r. ΔV = -∫g·dr.', 'Gravitational potential V is negative (bound system); gravitational field g = -∇V.', 'Compute V and g at a given point; use V to find PE for orbital problems.'),
                _t('Shell Theorem via Integration', 'The shell theorem states that a uniform spherical shell exerts no force inside (field = 0) and acts as a point mass outside. This is proved by integrating contributions from all shell elements.', 'The shell theorem requires a UNIFORM spherical shell — irregularly shaped shells do not have zero interior field.', 'Apply the shell theorem result; describe qualitatively how to prove it by integration.')],
               [('Gravitational field g', 'g = -GM/r² r̂; force per unit mass (N/kg = m/s²)'),
                ('Gravitational potential V', 'V = -GM/r; potential energy per unit mass (J/kg)'),
                ('Potential energy U', 'U = -GMm/r; negative for bound orbit'),
                ('Superposition', 'Total field = vector sum of individual mass contributions'),
                ('Shell theorem', 'Uniform sphere: g = 0 inside shell; point mass outside')],
               ['Calculate g and V at a given distance from a mass.',
                'Apply superposition to find total field from multiple masses.',
                'State and apply the shell theorem for inside and outside a sphere.'],
               ['Free-response: find g and V at altitude h above Earth.',
                'Superposition: find total gravitational field at midpoint between two masses.',
                'Shell theorem: state and explain why field = 0 inside a shell.'],
               ['Practice g and V calculations at several radii.',
                'Compute total gravitational PE for a two-body system.'],
               [('Find g and V at r = 2R_E above Earth\'s center. (M_E, R_E)', ['g = GM_E/(2R_E)² = GM_E/(4R_E²) = g_surface/4', 'V = -GM_E/(2R_E) = ½ × V_surface', 'V_surface = -GM_E/R_E; at r = 2R_E, V is half as negative', 'U = mV = -GMm/(2R_E)']),
                ('Two equal masses M are at x = -d and x = +d. Find g at the origin.', ['g₁ = GM/d² toward -x (from mass at +d)', 'g₂ = GM/d² toward +x (from mass at -d)', 'By symmetry, g_total = g₁ + g₂ = 0 at the origin', 'The two equal-mass contributions cancel exactly at the midpoint']),
                ('Qualitatively explain how to prove the shell theorem by integration.', ['Divide shell into rings of angular width dθ', 'Each ring contributes a gravitational force toward its own center', 'For an interior point, rings on both sides exert forces that exactly cancel', 'The cancellation is exact for a uniform spherical shell — proved by Newton using calculus']),
                ('Find g inside a uniform solid sphere of mass M and radius R at radius r < R.', ['By shell theorem: only mass inside r contributes', 'M_enclosed = M(r/R)³ (proportional to volume)', 'g = GM_enclosed/r² = GM(r/R)³/r² = GMr/R³ → g ∝ r', 'g increases linearly from 0 at center to g_surface at r = R']),
                ('Find the gravitational potential at the center of a solid uniform sphere.', ['V_center = 3V_surface/2... requires integration of shell contributions', 'Each shell contributes V_shell = -GM_shell/R (constant inside)', 'Integrating from 0 to R: V_center = -(3GM)/(2R)', 'This is 3/2 × V_surface — the potential is deeper (more negative) at center'])],
               [('Bozeman Gravitational Field', 'g, V, shell theorem, and superposition', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Shell Theorem', 'Shell theorem derivation and applications', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['g = GM/r²; V = -GM/r; U = -GMm/r.',
                'Superposition: vector sum of field contributions.',
                'Shell theorem: g = 0 inside shell; point mass outside.']),

            _l('Kepler\'s Laws',
               [_t('Kepler\'s First Law: Elliptical Orbits', 'Planets orbit the Sun in ellipses with the Sun at one focus. For circular orbits, the Sun is at the center. Ellipse parameters: semi-major axis a, eccentricity e.', 'The Sun is at a FOCUS of the ellipse, not the center — the planet is sometimes closer, sometimes farther.', 'Identify periapsis, apoapsis, and semi-major axis from orbital parameters.'),
                _t('Kepler\'s Second Law: Equal Areas', 'A line from the Sun to a planet sweeps equal areas in equal times. This is a consequence of conservation of angular momentum (no torque acts along orbital plane).', 'Kepler\'s 2nd law does NOT say the planet moves at constant speed — it moves faster at periapsis.', 'Apply the second law: if orbital radius decreases, speed must increase proportionally.'),
                _t('Kepler\'s Third Law: Period-Radius', 'T² = (4π²/GM)r³ for circular orbits (r = semi-major axis a for elliptical). Derived from F_grav = F_centripetal. T² ∝ a³ for all planets orbiting the same star.', 'T² ∝ a³ only applies when orbiting the SAME central body — comparing planets in different solar systems requires different GM.', 'Apply T² = (4π²/GM)a³ to find orbital periods and radii.')],
               [('Semi-major axis a', 'Half the longest diameter of an ellipse; average orbital radius'),
                ('Periapsis/Apoapsis', 'Closest/farthest points in the orbit from the focus'),
                ('Eccentricity e', 'e = 0 is circular; e → 1 is highly elongated ellipse'),
                ('Kepler\'s 3rd law', 'T² = (4π²/GM)a³; T ∝ a^{3/2}'),
                ('Angular momentum in orbit', 'L = mvr (constant for circular orbit; v×r = const generally)')],
               ['Identify orbital parameters (a, e, periapsis, apoapsis) from given data.',
                'Apply Kepler\'s 2nd law to compare orbital speeds at different positions.',
                'Use T² = (4π²/GM)a³ to find period or orbital radius.'],
               ['Free-response: derive Kepler\'s 3rd law for circular orbit.',
                'Comparison: find ratio of speeds at periapsis and apoapsis using L conservation.',
                'Calculate T for a given orbit radius using Kepler\'s 3rd law.'],
               ['Derive Kepler\'s 3rd law from Newton\'s law for circular orbits.',
                'Apply L = mvr to find speed ratio at two orbital points.'],
               [('Derive Kepler\'s 3rd law for a circular orbit.', ['Gravity = centripetal: GMm/r² = mv²/r → v² = GM/r', 'Period: v = 2πr/T → (2πr/T)² = GM/r', '4π²r²/T² = GM/r → T² = 4π²r³/GM', 'T ∝ r^{3/2}: outer planets have longer periods']),
                ('Earth\'s orbital radius is 1 AU, period 1 year. Mars orbits at 1.52 AU. Find Mars\'s period.', ['T² ∝ a³: (T_Mars/T_Earth)² = (a_Mars/a_Earth)³', 'T_Mars² = (1.52)³ = 3.51 year²', 'T_Mars = √3.51 ≈ 1.874 years ≈ 1.88 years', 'Same central body: Kepler\'s 3rd law applies directly']),
                ('A satellite has periapsis r_p and apoapsis r_a. Find the speed ratio v_p/v_a.', ['Angular momentum: L = mv_p r_p = mv_a r_a', 'v_p/v_a = r_a/r_p', 'Satellite moves faster at periapsis (smaller r) — Kepler\'s 2nd law', 'Speed ratio equals inverse of radius ratio']),
                ('State all three of Kepler\'s laws and identify which conservation law underlies each.', ['1st law (ellipse): result of inverse-square gravity + Newton\'s laws', '2nd law (equal areas): conservation of angular momentum (no torque)', '3rd law (T² ∝ a³): energy/force balance; G and M of central body determine constant', 'All three follow from Newton\'s law of gravitation + Newton\'s laws of motion']),
                ('Why does a comet move fastest at perihelion?', ['No torque from gravity along orbital plane → L = mvr = constant', 'At perihelion, r is smallest → v must be largest', 'This is conservation of angular momentum, not energy', 'KE at perihelion is maximum; PE is minimum (most negative)'])],
               [('Bozeman Kepler\'s Laws', 'All three Kepler laws derived from Newton', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Orbital Mechanics', 'Kepler\'s 3rd law and speed comparison', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Kepler 1: ellipses; 2: equal areas (L conserved); 3: T² = 4π²a³/GM.',
                'Speed at periapsis/apoapsis: v_p/v_a = r_a/r_p (from L = mvr).',
                'T ∝ a^{3/2}; same central body.']),

            _l('Orbital Energy and Escape Velocity',
               [_t('Total Orbital Energy', 'For a circular orbit: E = KE + PE = GMm/(2r) - GMm/r = -GMm/(2r). Negative E means bound orbit. Larger orbit → higher (less negative) total energy.', 'A satellite in a higher orbit has MORE total energy (less negative), not less — this is counterintuitive.', 'Calculate KE, PE, and total energy for circular orbits at various radii.'),
                _t('Escape Velocity', 'E = 0 at escape (v = 0 at r = ∞). Energy conservation: ½mv_esc² - GMm/R = 0 → v_esc = √(2GM/R). Independent of the escaping mass.', 'Escape velocity is a minimum speed at launch, not a requirement for all altitudes — above atmosphere, any constant speed eventually escapes.', 'Calculate escape velocity from planets and moons.'),
                _t('Elliptical Orbit Energy', 'For an elliptical orbit, E = -GMm/(2a) where a is the semi-major axis. T = 2π√(a³/GM). E depends only on a, not on eccentricity.', 'Two orbits with the same semi-major axis a have the same energy and period, regardless of eccentricity.', 'Apply E = -GMm/(2a) and T = 2π√(a³/GM) to elliptical orbits.')],
               [('Orbital energy', 'E = -GMm/(2r) for circular orbit; negative → bound'),
                ('Binding energy', 'Energy needed to escape from orbit: |E| = GMm/(2r)'),
                ('Escape velocity', 'v_esc = √(2GM/R); set E_total = 0'),
                ('Elliptical orbit energy', 'E = -GMm/(2a); period T = 2π√(a³/GM)'),
                ('Virial theorem', 'For circular orbit: |PE| = 2KE; E = -KE = PE/2')],
               ['Calculate KE, PE, and total energy for circular orbits.',
                'Derive and apply escape velocity formula.',
                'Apply E = -GMm/(2a) and T = 2π√(a³/GM) to elliptical orbits.'],
               ['Free-response: calculate energy needed to transfer from low orbit to geostationary orbit.',
                'Derive v_esc from energy conservation.',
                'Elliptical orbit: find period and energy given periapsis and apoapsis radii.'],
               ['Compute orbital energy at several radii for Earth orbit.',
                'Find orbital speed and period for GPS satellites (r = 26 560 km).'],
               [('A satellite orbits at r = 8×10⁶ m from Earth\'s center. Find KE, PE, and total energy. (M_E = 6×10²⁴ kg)', ['KE = GMm/(2r); PE = -GMm/r; E = -GMm/(2r)', 'GM_E = 6.674×10⁻¹¹ × 6×10²⁴ = 4.0×10¹⁴ m³/s²', 'For m = 1 kg: KE = 4.0×10¹⁴/(2×8×10⁶) = 2.5×10⁷ J/kg', 'PE = -5.0×10⁷ J/kg; E = -2.5×10⁷ J/kg']),
                ('Derive escape velocity from energy conservation.', ['Set E_total = 0: ½mv_esc² + (-GMm/R) = 0', '½mv_esc² = GMm/R → v_esc² = 2GM/R', 'v_esc = √(2GM/R)', 'For Earth: v_esc = √(2 × 4.0×10¹⁴/6.4×10⁶) ≈ 11 200 m/s = 11.2 km/s']),
                ('An elliptical orbit has periapsis 7000 km and apoapsis 45 000 km from Earth\'s center. Find a, E, and T.', ['a = (r_p + r_a)/2 = (7000 + 45000)/2 = 26 000 km = 2.6×10⁷ m', 'E = -GMm/(2a) = -4.0×10¹⁴ m/(2×2.6×10⁷) = -7.69×10⁶ m J/kg', 'T = 2π√(a³/GM) = 2π√((2.6×10⁷)³/4.0×10¹⁴) ≈ 2π√(4.39×10⁷) ≈ 41 700 s ≈ 11.6 hr', 'Note: period depends only on a']),
                ('Why does a satellite in a higher orbit move slower but have more total energy?', ['v = √(GM/r): larger r → smaller v (slower speed)', 'E = -GMm/(2r): larger r → less negative E (higher/more energy)', 'PE decreases faster than KE as r increases', 'Energy for higher orbit must be added (rocket burn))']),
                ('What is the binding energy of a satellite in orbit at r?', ['Binding energy = energy needed to escape from orbit = |E| = GMm/(2r)', 'From r, must add GMm/(2r) of energy to reach v_esc from orbit speed', 'Already moving at v_orbit; less energy needed than from surface', 'Total energy at r + binding energy = 0 (escape condition)'])],
               [('Bozeman Orbital Energy', 'E = -GMm/2r, escape velocity, elliptical orbits', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Escape Velocity', 'Deriving and applying v_esc = √(2GM/R)', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Circular orbit: E = -GMm/(2r); KE = |E|; PE = 2E.',
                'Escape: v_esc = √(2GM/R); E_total = 0.',
                'Elliptical: E = -GMm/(2a); T = 2π√(a³/GM).']),

            _l('Gravitational Potential and Advanced Applications',
               [_t('Gravitational Potential Energy in Extended Systems', 'U = -Gm₁m₂/r for two point masses; for a system of N bodies, U_total = -G Σ_{i<j} m_i m_j/r_{ij}. Total mechanical energy determines bound vs. unbound state.', 'The total potential energy of three bodies has THREE pair terms — not just one.', 'Calculate total PE for a system of point masses.'),
                _t('Tidal Forces', 'Tidal forces arise because the gravitational field is not uniform; the near side of a body is pulled more than the far side, stretching the body. Magnitude ∝ M/r³.', 'Tidal forces are differential forces — they are the difference in gravity across the body, not the average gravity.', 'Explain qualitatively why tides have two bulges and why r³ dependence matters.'),
                _t('Lagrange Points', 'Lagrange points (L1–L5) are positions in a two-body orbital system where a third small body can orbit with the same period as the two main bodies. L4 and L5 are stable.', 'Lagrange points are special solutions, not a general property — they exist only for small mass third bodies.', 'Identify the L1 point location qualitatively and explain its significance for space missions.')],
               [('Gravitational PE system', 'U_total = -G Σ m_i m_j/r_{ij} summed over all pairs'),
                ('Tidal force', 'Differential gravity across a body; stretches objects toward/away from source'),
                ('Roche limit', 'Distance within which tidal forces overcome self-gravity of a satellite'),
                ('Lagrange point', 'Location where third body orbits with same period as binary system'),
                ('Tidal locking', 'Rotation period equals orbital period; Moon is tidally locked to Earth')],
               ['Calculate total gravitational PE for a system of three masses.',
                'Explain tidal forces and why they scale as 1/r³.',
                'Identify Lagrange points qualitatively and their significance.'],
               ['Free-response: find total energy of a three-body system.',
                'Conceptual: explain why the Moon shows only one face to Earth.',
                'Calculation: estimate tidal force on an astronaut near a black hole.'],
               ['Calculate binding energy of Earth-Moon-Sun system.',
                'Research how tidal forces affect geological processes on Io and Earth.'],
               [('Calculate the total gravitational PE of three masses: m₁ = m₂ = m₃ = m at the vertices of an equilateral triangle with side L.', ['Three pairs: U₁₂ = -Gm²/L; U₁₃ = -Gm²/L; U₂₃ = -Gm²/L', 'U_total = -3Gm²/L', 'Each pair contributes equally by symmetry', 'Binding energy = |U_total| = 3Gm²/L']),
                ('Explain why tidal forces scale as 1/r³ while gravity scales as 1/r².', ['Tidal force = difference in gravity across a body of size d', 'Δg = dg/dr × d = (2GM/r³) × d → tidal ∝ GM/(r³)', 'Gravity itself: g ∝ 1/r²; differential (tidal) ∝ 1/r³', 'Tidal forces drop off more rapidly — they are insignificant at large distances']),
                ('Why does the Moon keep the same face toward Earth (tidal locking)?', ['Tidal forces from Earth distort the Moon slightly (bulge)', 'If Moon rotated faster, Earth\'s tidal bulge would lag behind → braking torque', 'This tidal friction slows rotation until rotation period = orbital period', 'Result: synchronous rotation — same face always toward Earth']),
                ('What is the Roche limit and what happens when a satellite crosses it?', ['Roche limit: distance where tidal forces exceed satellite\'s self-gravity', 'Inside Roche limit: satellite is torn apart by tidal forces', 'Saturn\'s rings are within Saturn\'s Roche limit — material cannot coalesce', 'd_Roche ≈ 2.46 R_planet (ρ_planet/ρ_satellite)^{1/3}']),
                ('Why are the L4 and L5 Lagrange points stable while L1, L2, L3 are unstable?', ['L4 and L5 form equilateral triangles with the two main bodies — Coriolis force stabilizes them', 'L1, L2, L3 are on the line between the bodies — slight perturbation grows exponentially', 'Trojan asteroids occupy L4 and L5 in the Jupiter-Sun system (stable for billions of years)', 'L2 hosts James Webb Space Telescope — requires station-keeping to stay at unstable point'])],
               [('Bozeman Tidal Forces', 'Tidal forces, Roche limit, Lagrange points', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Advanced Gravitation', 'Gravitational potential and tidal effects', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Three-body U_total: sum all pair terms (-Gm_im_j/r_ij).',
                'Tidal force ∝ 1/r³; stronger than average gravity at small r.',
                'L4 and L5 are stable Lagrange points (Trojan asteroids).'])
        ],
        'unit_qs': [
            ('Derive Kepler\'s 3rd law T² = 4π²r³/GM for a circular orbit from Newton\'s law of gravitation.',
             ['Set gravity = centripetal: GMm/r² = mv²/r → v² = GM/r', 'Period: v = 2πr/T → v² = 4π²r²/T²', '4π²r²/T² = GM/r → T² = 4π²r³/GM', 'Constant of proportionality is 4π²/GM — same for all satellites of same central body']),
            ('A satellite orbits Earth at r = 1.2×10⁷ m. Find its speed, period, and total energy per unit mass.',
             ['v = √(GM/r) = √(4×10¹⁴/1.2×10⁷) = √(3.33×10⁷) ≈ 5774 m/s', 'T = 2πr/v = 2π(1.2×10⁷)/5774 ≈ 13 066 s ≈ 3.63 hr', 'E/m = -GM/(2r) = -4×10¹⁴/(2.4×10⁷) = -1.67×10⁷ J/kg', 'Negative energy confirms bound orbit']),
            ('Find g inside Earth at r = R_E/2 (halfway to center). Assume uniform density.',
             ['Inside uniform sphere: g = GM_enclosed/r²; M_enclosed = M(r/R)³', 'g = G[M(r/R)³]/r² = GMr/R³ = g_surface × (r/R)', 'g(R/2) = g_surface × ½ = 9.8/2 = 4.9 m/s²', 'g varies linearly inside; zero at center']),
            ('An elliptical orbit has periapsis r_p = 6.8×10⁶ m and apoapsis r_a = 1.5×10⁷ m. Find a, T, and speeds at periapsis and apoapsis.',
             ['a = (r_p + r_a)/2 = (6.8 + 15)/2 × 10⁶ = 1.09×10⁷ m', 'T = 2π√(a³/GM) = 2π√((1.09×10⁷)³/4×10¹⁴) ≈ 2π√(3.24×10⁶) ≈ 11 320 s', 'L = mv_p r_p = mv_a r_a → v_p/v_a = r_a/r_p = 15/6.8 ≈ 2.21', 'Also energy: ½mv_p² - GMm/r_p = ½mv_a² - GMm/r_a (two equations, two unknowns)']),
            ('Calculate the escape velocity from the surface of Mars. (M = 6.4×10²³ kg, R = 3.4×10⁶ m)',
             ['v_esc = √(2GM/R) = √(2 × 6.674×10⁻¹¹ × 6.4×10²³ / 3.4×10⁶)', 'v_esc = √(2 × 4.27×10¹³ / 3.4×10⁶) = √(2.51×10⁷)', 'v_esc ≈ 5007 m/s ≈ 5.0 km/s', 'About 45% of Earth\'s escape velocity; explains why Mars has thin atmosphere']),
            ('Three equal masses m are at the vertices of an equilateral triangle with side d. Find the gravitational force on one mass.',
             ['Force from mass 2 on mass 1: F₁₂ = Gm²/d² at 60° above horizontal', 'Force from mass 3 on mass 1: F₁₃ = Gm²/d² at 60° above horizontal (other side)', 'By symmetry: horizontal components cancel; vertical components add', 'F_net = 2(Gm²/d²)sin60° = √3 Gm²/d² (directed toward center of triangle)']),
            ('Show that for a circular orbit, |PE| = 2KE and E = -KE (virial theorem).',
             ['KE = ½mv² = GMm/(2r) (from v² = GM/r)', 'PE = -GMm/r = -2KE → |PE| = 2KE', 'E = KE + PE = GMm/(2r) - GMm/r = -GMm/(2r) = -KE', 'E = ½PE: total energy equals half the PE; virial theorem for gravity']),
            ('How much energy is required to move a satellite from r₁ = 7×10⁶ m to r₂ = 14×10⁶ m?',
             ['E₁ = -GMm/(2r₁); E₂ = -GMm/(2r₂)', 'ΔE = E₂ - E₁ = -GMm/2(1/r₂ - 1/r₁) = GMm/2(1/r₁ - 1/r₂)', 'ΔE = GMm/2(1/7×10⁶ - 1/14×10⁶) = 4×10¹⁴m/2 × (1/14×10⁶)', 'ΔE = 4×10¹⁴m/(2.8×10⁷) ≈ 1.43×10⁷m J (where m is satellite mass)']),
            ('A binary star system has two equal stars (each M) separated by distance 2d, orbiting their CM. Find orbital period.',
             ['Each star orbits at r = d from CM; gravity provides centripetal force', 'F = GM²/(2d)² = GM²/(4d²)', 'F = Mv²/d → v² = GM/(4d)', 'T = 2πd/v = 2πd/√(GM/(4d)) = 2π√(4d³/GM) = 4π√(d³/GM)']),
            ('Explain physically why satellites closer to Earth orbit faster but have less total energy.',
             ['Faster orbit: v = √(GM/r); smaller r → larger v', 'KE = GMm/(2r) is larger at smaller r', 'PE = -GMm/r is more negative (lower) at smaller r', 'E = -GMm/(2r) more negative at smaller r → less total energy (more tightly bound)'])
        ],
    'review_video': 'https://www.youtube.com/watch?v=Hn7IIBHXN3U',
    },
]
