NAME        = 'AP® Physics C: Electricity & Magnetism'
ABBREV      = 'physem'
SLUG        = 'ap-physics-c-electricity-and-magnetism'
COURSE_FILE = 'ap-physics-c-electricity-and-magnetism.html'
ACCENT_COLOR = '#38bdf8'

COURSE_QS = [
    ('Gauss\'s Law states that the electric flux through a closed surface equals',
     'the total enclosed charge divided by the permittivity of free space: Φ_E = Q_enc / ε₀',
     ['the surface area times the field magnitude', 'the work done by the electric field', 'the line integral of E around the surface']),
    ('The electric field inside a conductor in electrostatic equilibrium is',
     'zero — free charges redistribute until no net field exists inside',
     ['uniform and parallel to the surface', 'proportional to the surface charge density', 'directed radially outward from the center']),
    ('The capacitance of a parallel-plate capacitor is',
     'C = ε₀A/d — proportional to plate area and inversely proportional to plate separation',
     ['C = Q × V', 'C = ε₀d/A', 'C = V/Q²']),
    ('When capacitors are connected in parallel, the equivalent capacitance is',
     'the sum of individual capacitances: C_eq = C₁ + C₂ + ...',
     ['less than the smallest individual capacitance', '1/C_eq = 1/C₁ + 1/C₂', 'the average of the individual capacitances']),
    ('Kirchhoff\'s Voltage Law (KVL) states that',
     'the sum of all voltage drops around any closed loop equals zero (energy conservation)',
     ['the sum of currents into a node equals zero', 'voltage is constant throughout any loop', 'the voltage across each element is equal']),
    ('The magnetic force on a moving charge q in field B is given by',
     'F = qv × B — perpendicular to both v and B, with magnitude qvB sinθ',
     ['F = qvB cosθ', 'F = qE (using the electric field)', 'F = q|v|²/r']),
    ('Ampere\'s Law relates the magnetic field along a closed path to',
     'the total current enclosed by that path: ∮ B · dl = μ₀ I_enc',
     ['the total charge enclosed', 'the electric flux through the surface', 'the magnetic flux through the path']),
    ('Faraday\'s Law of Induction states that the induced EMF is',
     'ε = −dΦ_B/dt — the negative rate of change of magnetic flux through a circuit',
     ['ε = BLv always', 'ε = Q/C', 'ε = μ₀I/2πr']),
    ('Lenz\'s Law states that the induced current flows in a direction that',
     'opposes the change in magnetic flux that caused it (conservation of energy)',
     ['reinforces the magnetic flux change', 'maximizes the induced EMF', 'is always clockwise']),
    ('The energy stored in an inductor with inductance L carrying current I is',
     'U = (1/2)LI²',
     ['U = LI', 'U = (1/2)I²/L', 'U = LV/I']),
    ('In an RC circuit, the time constant τ represents',
     'τ = RC — the time for the capacitor to charge to about 63% of its final voltage',
     ['the time to fully charge or discharge the capacitor', 'τ = R/C', 'the frequency of oscillation']),
    ('Maxwell\'s addition to Ampere\'s Law introduced the concept of',
     'displacement current — a changing electric flux creates a magnetic field even without charge flow',
     ['magnetic monopoles', 'the speed of light depending on medium', 'charge conservation in circuits']),
    ('The electric potential V at a distance r from a point charge q is',
     'V = kq/r — potential decreases with distance for a positive charge',
     ['V = kq/r²', 'V = qr/k', 'V = E/r']),
    ('Work done to move charge q through a potential difference ΔV is',
     'W = qΔV',
     ['W = q/ΔV', 'W = qΔV²', 'W = ΔV/q']),
    ('The magnetic field at the center of a circular loop of radius R carrying current I is',
     'B = μ₀I/(2R) — proportional to current, inversely proportional to radius',
     ['B = μ₀I/(2πR)', 'B = μ₀IR', 'B = I/(2μ₀R)']),
    ('Ohm\'s Law in terms of resistivity ρ, length L, and cross-section A gives resistance as',
     'R = ρL/A',
     ['R = ρA/L', 'R = L/(ρA)', 'R = ρ/(LA)']),
    ('The dielectric constant κ increases the capacitance of a capacitor by',
     'a factor of κ: C = κε₀A/d (the dielectric reduces E, allowing more charge for same voltage)',
     ['decreasing the plate separation by κ', 'increasing the permittivity to ε₀/κ', 'reducing the stored energy by κ']),
    ('Electromagnetic waves are transverse waves in which E and B fields are',
     'perpendicular to each other and to the direction of wave propagation',
     ['parallel to each other and to the direction of propagation', 'perpendicular to each other but parallel to propagation', 'in phase with the current source']),
    ('Self-inductance L is defined such that the back-EMF in an inductor is',
     'ε = −L(dI/dt) — proportional to the rate of change of current',
     ['ε = L × I', 'ε = L/I²', 'ε = (dI/dt)/L']),
    ('The energy density of an electric field E in free space is',
     'u = (1/2)ε₀E²',
     ['u = ε₀E', 'u = E²/(2μ₀)', 'u = (1/2)ε₀E (linear, not squared)']),
]

_B = 'https://www.youtube.com/results?search_query=Bozeman+Science+AP®+Physics+C+Electricity+'
_F = 'https://www.youtube.com/results?search_query=Flipping+Physics+AP®+Physics+C+EM+'

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content,
            'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 1, 'title': 'Electrostatics',
        'file': 'ap-physics-c-electricity-and-magnetism-1-unit-8-electric-charges-fields-and-gauss-s-law.html',
        'desc': 'Coulomb\'s law, electric field, Gauss\'s law, and electric potential using calculus.',
        'gateway': [
            'Apply Coulomb\'s law and calculate electric fields using superposition.',
            'Use Gauss\'s law to find fields for symmetric charge distributions.',
            'Calculate electric potential V and relate it to field E = -∇V.',
            'Find work done by and energy stored in electric fields.',
        ],
        'lessons': [
            _l('Coulomb\'s Law and Electric Fields',
               [_t('Coulomb\'s Law', 'F = kq₁q₂/r² = q₁q₂/(4πε₀r²); force between point charges. Force is repulsive for like charges, attractive for unlike. k = 8.99×10⁹ N·m²/C².', 'The force on q₁ due to q₂ is equal and opposite to the force on q₂ — Newton\'s 3rd law applies.', 'Calculate force between point charges; use superposition for multiple charges.'),
                _t('Electric Field', 'E = F/q₀ = kq/r² (point charge); the electric field E is force per unit positive test charge. Field lines start on + charges and end on − charges.', 'Electric field exists even where there is no test charge — it is a property of the region, not dependent on q₀.', 'Find E from a charge distribution using superposition; draw and interpret field line diagrams.'),
                _t('Superposition Principle', 'Total E or F from multiple charges = vector sum of individual contributions. Each charge contributes independently; integrate for continuous distributions.', 'Superposition applies to fields, not potentials squared — E_total = ΣE_i (vector sum).', 'Compute E at a point from multiple charges by vector addition.')],
               [('Coulomb\'s law', 'F = kq₁q₂/r²; force between point charges'),
                ('Electric field E', 'E = F/q₀ = kq/r²; force per unit positive charge (N/C)'),
                ('Permittivity ε₀', 'ε₀ = 8.85×10⁻¹² C²/(N·m²); vacuum permittivity'),
                ('Field lines', 'Directed curves showing E direction; density ∝ |E|'),
                ('Superposition', 'E_total = ΣE_i; fields add as vectors')],
               ['Calculate Coulomb force for multiple point charges.',
                'Find E at a point using superposition.',
                'Draw electric field lines for simple charge configurations.'],
               ['Free-response: find E at midpoint between two charges.',
                'Calculation: find E on the axis of a uniformly charged ring by integration.',
                'Superposition: find net force on a charge in a system of three.'],
               ['Practice superposition problems with 2–3 point charges.',
                'Derive E for a ring of charge along the axis.'],
               [('Two charges q₁ = +3 μC and q₂ = -3 μC are 10 cm apart. Find force magnitude.', ['F = kq₁q₂/r² = (8.99×10⁹)(3×10⁻⁶)(3×10⁻⁶)/(0.1)²', 'F = (8.99×10⁹)(9×10⁻¹²)/0.01 = 8.09 N', 'Attractive (opposite charges)', 'Newton\'s 3rd law: equal magnitude force on each charge']),
                ('Find E at the midpoint between the two charges above (midpoint is 5 cm from each).', ['From q₁ = +3μC at left: E₁ = kq/r² = (8.99×10⁹)(3×10⁻⁶)/(0.05)² = 10.79 MN/C pointing right', 'From q₂ = -3μC at right: E₂ = kq/r² = 10.79 MN/C pointing right (toward negative charge)', 'Both point rightward: E_total = 21.58 MN/C', 'Superposition: E fields from both charges point in the same direction here']),
                ('A ring of radius R has total charge Q uniformly distributed. Find E on the axis at distance x.', ['Each element dq contributes dE = k dq/(x²+R²) along the axis component cos θ', 'cos θ = x/√(x²+R²); by symmetry perpendicular components cancel', 'E_x = ∫k dq x/(x²+R²)^{3/2} = kQx/(x²+R²)^{3/2}', 'Maximum E at x = R/√2']),
                ('What does a uniform electric field look like in field line representation?', ['Parallel, evenly spaced field lines pointing in the direction of E', 'Uniform spacing indicates same magnitude everywhere', 'Example: between parallel plates of a capacitor', 'Field lines always perpendicular to equipotential surfaces']),
                ('Three charges +q, -q, +q are placed at corners of an equilateral triangle with side a. Find E at the center.', ['At center, each charge is at distance a/√3 from center', 'E from each charge points toward (-q) or away from (+q)', 'By symmetry: contributions from two +q charges cancel along the axis', 'Net E from -q pulls toward it; calculate magnitude from remaining component'])],
               [('Bozeman Electric Fields', 'Coulomb\'s law and field superposition', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics E Field', 'Electric field from point charges', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['F = kq₁q₂/r²; E = kq/r² for point charge.',
                'Superposition: E_total = vector sum of all contributions.',
                'Field lines: + to −; density proportional to |E|.']),

            _l('Gauss\'s Law',
               [_t('Electric Flux', 'Φ_E = ∮E·dA = Q_enc/ε₀; flux is the integral of E·dA over a closed surface (Gaussian surface). Positive flux when E points outward.', 'Flux depends on Q_enclosed, not on the shape or size of the Gaussian surface.', 'Calculate flux through various closed surfaces given charge distributions.'),
                _t('Applying Gauss\'s Law', 'Choose a Gaussian surface with the same symmetry as the charge distribution. E is constant on the surface: EA = Q_enc/ε₀.  Works for spheres, cylinders, and planes.', 'Gauss\'s law is always true, but only useful for finding E when symmetry allows E to be pulled out of the integral.', 'Apply Gauss\'s law to find E for spherically, cylindrically, and planar symmetric charge distributions.'),
                _t('Conductors in Electrostatics', 'In electrostatic equilibrium: E = 0 inside a conductor; all excess charge is on the surface; E is perpendicular to the surface outside. Surface charge density σ relates to external E via E = σ/ε₀.', 'E = 0 inside a conductor only in STATIC equilibrium — current-carrying conductors have nonzero E inside.', 'Apply Gauss\'s law to find E and charge distribution for conducting surfaces.')],
               [('Electric flux', 'Φ_E = ∮E·dA; proportional to field lines passing through surface'),
                ('Gaussian surface', 'Imaginary closed surface chosen to apply Gauss\'s law'),
                ('Gauss\'s law', 'Φ_E = Q_enc/ε₀; total flux equals enclosed charge over ε₀'),
                ('Conductor equilibrium', 'E = 0 inside; all charge on surface; E perpendicular to surface'),
                ('Surface charge density σ', 'Charge per unit area (C/m²) on a conductor surface')],
               ['Calculate electric flux for closed surfaces.',
                'Apply Gauss\'s law to find E for spherical, cylindrical, and planar symmetry.',
                'Explain properties of conductors in electrostatic equilibrium.'],
               ['Free-response: derive E for an infinite line charge using a cylindrical Gaussian surface.',
                'Gauss\'s law: find E inside and outside a uniformly charged sphere.',
                'Conductor: find E just outside a conductor with surface charge σ.'],
               ['Derive E for all three symmetric distributions from Gauss\'s law.',
                'Practice explaining why each Gaussian surface shape is chosen.'],
               [('Derive E outside a uniformly charged sphere (charge Q, radius R) using Gauss\'s law.', ['Gaussian surface: sphere of radius r > R centered on charge', 'Symmetry: E is radially outward and constant on surface', 'Gauss: E(4πr²) = Q/ε₀ → E = Q/(4πε₀r²) = kQ/r²', 'Same result as point charge — shell theorem for E field']),
                ('Find E inside a uniformly charged solid sphere (volume charge density ρ) at radius r < R.', ['Gaussian sphere of radius r: Q_enc = ρ(4πr³/3)', 'E(4πr²) = ρ(4πr³/3)/ε₀ → E = ρr/(3ε₀)', 'E ∝ r inside; E ∝ 1/r² outside', 'Maximum at surface r = R']),
                ('Derive E for an infinite line charge with linear density λ.', ['Gaussian cylinder: radius r, length L; by symmetry E is radial', 'E(2πrL) = λL/ε₀ → E = λ/(2πε₀r) = 2kλ/r', 'Field drops as 1/r (not 1/r² like a point charge)', 'Applies to long straight wires and axis of coaxial cable']),
                ('Why must E = 0 inside a conductor at electrostatic equilibrium?', ['If E ≠ 0 inside, free electrons would accelerate — equilibrium would not exist', 'In equilibrium, all free charges are stationary → net force = 0 → E = 0', 'Any excess charge moves to the surface until E = 0 inside', 'This is proved by applying Gauss\'s law to a surface just inside the conductor']),
                ('An infinite plane of charge has surface charge density σ. Find E using Gauss\'s law.', ['Gaussian pillbox: area A, extending equal distances on both sides', 'E is perpendicular to plane; flux through sides = 0; two ends: 2EA = σA/ε₀', 'E = σ/(2ε₀)', 'Between two opposite plates: E = σ/ε₀ (fields add)'])],
               [('Bozeman Gauss\'s Law', 'Applying Gauss\'s law to symmetric distributions', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Gauss', 'Sphere, cylinder, and plane using Gauss\'s law', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Gauss: Φ = Q_enc/ε₀; E constant on Gaussian surface by symmetry.',
                'Sphere: E = kQ/r²; cylinder: E = λ/(2πε₀r); plane: E = σ/(2ε₀).',
                'Conductor: E = 0 inside; all charge on surface at equilibrium.']),

            _l('Electric Potential',
               [_t('Electric Potential V', 'V = kq/r for a point charge; V = W/q₀ = -∫E·dl (potential is work per unit positive charge from reference). V is a scalar.', 'Potential V is not the same as potential energy U; U = qV. V is potential energy per unit charge.', 'Calculate V by superposition (sum of kq_i/r_i) and by integrating E.'),
                _t('Relationship Between E and V', 'E = -∇V; in 1D: E_x = -dV/dx. Equipotential surfaces are perpendicular to field lines. Moving along an equipotential does zero work.', 'E points from high V to low V (negative gradient), not from positive to negative charge.', 'Find E from V by differentiation; find V from E by integration.'),
                _t('Electric Potential Energy', 'U = qV = kq₁q₂/r for two point charges. For a system of charges, U = sum of all pair potentials. Work done by E field: W = qΔV = -ΔU.', 'The potential energy is zero at infinite separation — negative U means the system is bound.', 'Calculate potential energy of charge configurations and work done by electric fields.')],
               [('Electric potential V', 'V = kq/r (point charge); work per unit charge (J/C = V)'),
                ('Potential difference ΔV', 'ΔV = V_B - V_A = -∫_A^B E·dl'),
                ('E = -dV/dx', 'E is negative gradient of V in the direction of steepest descent'),
                ('Equipotential surface', 'Surface on which V is constant; perpendicular to field lines'),
                ('Potential energy U', 'U = qV = kq₁q₂/r; zero at infinite separation')],
               ['Calculate V for point charge systems using superposition.',
                'Relate E and V via E = -dV/dx.',
                'Calculate work done by E field on a charge moving through a potential difference.'],
               ['Free-response: find V at a point from multiple charges; derive E from V.',
                'Derive V for a uniformly charged ring on its axis.',
                'Work/energy: find speed of charge released from rest at a given potential.'],
               ['Practice V superposition for 3–4 charge systems.',
                'Derive E from V for several functions V(x).'],
               [('Find V at the midpoint between q₁ = +2 μC at x = 0 and q₂ = -2 μC at x = 4 cm.', ['V₁ = kq₁/r₁ = (8.99×10⁹)(2×10⁻⁶)/(0.02) = +899 000 V', 'V₂ = kq₂/r₂ = (8.99×10⁹)(-2×10⁻⁶)/(0.02) = -899 000 V', 'V_total = V₁ + V₂ = 0 V', 'Midpoint has zero potential despite nonzero E field (scalar cancellation)']),
                ('Given V(x) = 3x² - 5x. Find E_x.', ['E_x = -dV/dx = -(6x - 5) = 5 - 6x', 'At x = 0: E_x = 5 N/C; at x = 1: E_x = -1 N/C', 'E is the negative gradient of V', 'Where V is increasing, E points in -x direction']),
                ('A charge q = +2 μC moves from V = 100 V to V = 30 V. Find work done by E field.', ['W = qΔV = q(V_i - V_f) = (2×10⁻⁶)(100 - 30) = 140 μJ', 'E field does positive work when + charge moves to lower potential', 'Or: W = -ΔU = -(qV_f - qV_i) = q(V_i - V_f) = 140 μJ', 'KE increases by 140 μJ if no other forces act']),
                ('Derive V on the axis of a uniformly charged ring (charge Q, radius R, axial distance x).', ['V = ∫k dq/r where r = √(x²+R²) for all elements dq', 'Since r is the same for all elements: V = kQ/√(x²+R²)', 'V is a scalar — much easier to sum than E (a vector)', 'Compare to E = kQx/(x²+R²)^{3/2} derived earlier']),
                ('Why is it easier to find V first, then derive E from V, rather than computing E directly?', ['V is a scalar: sum scalar contributions kq_i/r_i', 'E is a vector: must sum x, y, z components separately', 'V = Σkq_i/r_i → much simpler for complex distributions', 'Then E = -∇V yields the vector field from one scalar function'])],
               [('Bozeman Electric Potential', 'V = kq/r, E = -dV/dx, and potential energy', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Electric Potential', 'V superposition and E from V', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['V = kq/r; scalar superposition.',
                'E = -dV/dx; E points from high V to low V.',
                'W = qΔV; K increases when + charge moves to lower V.']),

            _l('Continuous Charge Distributions: Advanced Integration',
               [_t('E and V for Lines, Rings, and Disks', 'For continuous distributions: E = ∫k dq/r² r̂; V = ∫k dq/r. Use symmetry to simplify; identify which components cancel. Results: infinite line (1/r), ring (on axis), disk (on axis).', 'When integrating for E, always check which components cancel by symmetry before computing the integral.', 'Set up and evaluate integrals for E and V from continuous charge distributions.'),
                _t('Volume Charge Distributions', 'For volume charge density ρ: dq = ρ dV. Use Gauss\'s law when symmetry permits; otherwise integrate directly. Example: uniformly charged sphere, E ∝ r inside.', 'dq = ρ dV uses the VOLUME element, not area or length — verify the correct density and element are used.', 'Compute E and V for volumetrically distributed charges.'),
                _t('Dipoles', 'An electric dipole has charges +q and -q separated by distance d; dipole moment p = qd. E on axis: E ≈ 2kp/r³; perpendicular: E ≈ kp/r³ (far field). Torque τ = p × E; PE = -p·E.', 'Dipole field falls off as 1/r³, faster than monopole 1/r².', 'Calculate E from a dipole and the torque on a dipole in a uniform field.')],
               [('Volume charge density ρ', 'ρ = dq/dV; charge per unit volume (C/m³)'),
                ('Dipole moment p', 'p = qd; vector from - to + charge; determines far-field behavior'),
                ('Dipole torque', 'τ = p × E = pE sinθ; torque aligns dipole with field'),
                ('Dipole PE', 'U = -p·E = -pE cosθ; minimum when p parallel to E'),
                ('Far-field dipole E', 'E ∝ 1/r³; faster falloff than monopole')],
               ['Set up integrals for E and V for line, ring, and disk charge distributions.',
                'Apply Gauss\'s law for volume distributions with symmetry.',
                'Calculate torque and PE for a dipole in an external field.'],
               ['Free-response: E and V on axis of a uniformly charged disk by integration.',
                'Derive E inside and outside a uniformly charged solid sphere.',
                'Dipole: find torque angle for maximum torque; find stable equilibrium.'],
               ['Set up and solve the ring and disk E integrals from scratch.',
                'Compute E of a dipole at two standard positions.'],
               [('Find V on the axis of a uniformly charged disk (charge density σ, radius R) at axial distance x.', ['Ring element at radius r, width dr: dq = σ(2πr dr)', 'dV = k dq/√(x²+r²); integrate from 0 to R', 'V = kσ(2π)∫₀ᴿ r dr/√(x²+r²) = 2πkσ[√(x²+r²)]₀ᴿ', 'V = 2πkσ(√(x²+R²) - x)']),
                ('Derive E_x from the V above.', ['E_x = -dV/dx = -2πkσ d/dx(√(x²+R²) - x)', 'E_x = -2πkσ(x/√(x²+R²) - 1)', 'E_x = 2πkσ(1 - x/√(x²+R²)) = σ/(2ε₀)(1 - x/√(x²+R²))', 'As R → ∞: E_x → σ/(2ε₀) — consistent with infinite plane result']),
                ('A dipole has p = 5×10⁻³⁰ C·m in a field E = 1×10⁶ N/C at θ = 90°. Find torque.', ['τ = pE sinθ = (5×10⁻³⁰)(1×10⁶) sin90°', 'τ = 5×10⁻²⁴ N·m', 'Maximum torque at θ = 90° (dipole perpendicular to field)', 'Minimum torque (= 0) at θ = 0° (dipole aligned with field)']),
                ('What is the stable equilibrium orientation of a dipole in a uniform field?', ['PE = -pE cosθ; minimum PE at θ = 0 (p parallel to E)', 'At θ = 0, torque = 0 and any displacement brings it back', 'At θ = 180°, PE is maximum (unstable equilibrium)', 'Dipole naturally aligns with the external field']),
                ('Compare the fall-off rates of monopole, dipole, and quadrupole fields.', ['Monopole (single charge): E ∝ 1/r²', 'Dipole (two opposite charges): E ∝ 1/r³', 'Quadrupole (two dipoles): E ∝ 1/r⁴', 'Higher multipoles fall off faster — dominant term at large r is the lowest nonzero multipole'])],
               [('Bozeman Continuous Charge', 'Integration for E and V from continuous distributions', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Electric Dipole', 'Dipole fields and torque', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Disk V: 2πkσ(√(x²+R²) - x); differentiate to get E.',
                'Dipole E ∝ 1/r³; torque τ = pE sinθ.',
                'Stable equilibrium: dipole aligned with E (θ = 0).']
               )
        ],
        'unit_qs': [
            ('Two charges +4 μC and -2 μC are 30 cm apart. Find the point on the line between them where E = 0.',
             ['Let x be distance from +4μC; E₁ = k(4×10⁻⁶)/x² = E₂ = k(2×10⁻⁶)/(0.3-x)²', '4/x² = 2/(0.3-x)² → 2(0.3-x)² = x² → √2(0.3-x) = x', '0.3√2 - √2 x = x → x(1+√2) = 0.3√2 → x = 0.3√2/(1+√2) ≈ 0.176 m', 'Between charges, 17.6 cm from +4μC']),
            ('Derive E for an infinite cylindrical shell of radius R with surface charge λ using Gauss\'s law.',
             ['For r > R: Gaussian cylinder radius r, length L; E(2πrL) = λL/ε₀ → E = λ/(2πε₀r)', 'For r < R: Q_enc = 0 → E = 0 inside the shell', 'Same result as solid line charge outside; no field inside', 'Shell theorem for E field in cylindrical geometry']),
            ('A solid conducting sphere (radius R) has charge Q. Find E just inside and just outside the surface.',
             ['Inside (r < R): E = 0 (conductor at equilibrium)', 'Just outside (r → R⁺): use Gauss sphere: E(4πR²) = Q/ε₀ → E = kQ/R² = σ/ε₀', 'E jumps from 0 to σ/ε₀ at the surface', 'This discontinuity equals σ/ε₀ for any conductor surface']),
            ('Find V at the center of an equilateral triangle with +q at each vertex, side length a.',
             ['Each vertex is at distance r = a/√3 from center', 'V = Σkq/r = 3(kq/(a/√3)) = 3√3 kq/a', 'V is a scalar sum — no direction needed', 'This is the advantage of using V over E for symmetric configurations']),
            ('A ring of charge (Q, R) and a disk of charge (σ, R) are coaxial. Compare their V on-axis far from the ring/disk.',
             ['Ring: V_ring = kQ/√(x²+R²) → kQ/x for x >> R', 'Disk: V_disk = 2πkσ(√(x²+R²) - x) → 2πkσR²/(2x) = kQ_disk/x for x >> R', 'Both approach kQ_enc/x for x >> R — they look like point charges', 'Far from any finite distribution, it approaches a monopole']),
            ('Describe how Gauss\'s law applies to a non-symmetric charge distribution.',
             ['Gauss\'s law is always true: Φ = Q_enc/ε₀', 'However, for non-symmetric distributions, E is not constant on the Gaussian surface', 'Cannot pull E outside the integral → can\'t solve for E from Gauss\'s law alone', 'Gauss\'s law is only USEFUL for finding E when there is sufficient symmetry']),
            ('Find V at a point P located 3 cm from a +5 μC charge and 4 cm from a -3 μC charge.',
             ['V = kq₁/r₁ + kq₂/r₂ = k(5×10⁻⁶/0.03) + k(-3×10⁻⁶/0.04)', 'V = (8.99×10⁹)(1.667×10⁻⁴ - 7.5×10⁻⁵)', 'V = (8.99×10⁹)(9.17×10⁻⁵) = 824 000 V ≈ 824 kV', 'V is scalar sum; much simpler than E calculation']),
            ('A dipole with p = 2×10⁻²⁹ C·m is in a uniform field E = 5×10⁴ N/C. Find the PE when aligned and anti-aligned.',
             ['Aligned (θ = 0): U = -pE cos0 = -pE = -(2×10⁻²⁹)(5×10⁴) = -1×10⁻²⁴ J (stable)', 'Anti-aligned (θ = π): U = -pE cosπ = +pE = +1×10⁻²⁴ J (unstable)', 'Energy needed to flip from stable to unstable = 2pE = 2×10⁻²⁴ J', 'Stable equilibrium is at θ = 0 (minimum PE)']),
            ('A charge q = 1 μC is released from rest at a potential V = 500 V and moves to V = 200 V. Find its final kinetic energy.',
             ['W = qΔV = (1×10⁻⁶)(500-200) = 3×10⁻⁴ J = 0.3 mJ', 'KE_f = KE_i + W = 0 + 0.3 mJ = 0.3 mJ', 'Positive charge moves from high to low potential — E does positive work', 'Speed: v = √(2KE/m); need mass for speed']),
            ('Use Gauss\'s law to show that E = 0 everywhere inside a hollow conducting spherical shell with charge Q on its outer surface.',
             ['Draw Gaussian sphere of radius r < R (inner radius) inside the conductor', 'No charge is enclosed by this surface (charge is only on the outer surface)', 'Gauss: Φ = Q_enc/ε₀ = 0; by symmetry E is constant on surface', 'E(4πr²) = 0 → E = 0 inside the cavity'])
        ]
    },

    {
        'num': 2, 'title': 'Conductors, Capacitors, and Dielectrics',
        'file': 'ap-physics-c-electricity-and-magnetism-2-unit-9-electric-potential.html',
        'desc': 'Capacitance, energy storage in electric fields, dielectrics, and conductor boundary conditions.',
        'gateway': [
            'Calculate capacitance for parallel plates, spheres, and cylinders.',
            'Apply the energy stored in a capacitor and in an electric field.',
            'Analyze capacitor combinations in series and parallel.',
            'Explain the effect of dielectrics on capacitance and field strength.',
        ],
        'lessons': [
            _l('Capacitance',
               [_t('Definition of Capacitance', 'C = Q/V (F = C/V). Capacitance depends only on geometry, not on Q or V. Parallel plate: C = ε₀A/d; isolated sphere: C = 4πε₀R.', 'Capacitance does not depend on the charge stored — it is a property of the geometry.', 'Calculate C for parallel plates; derive C for cylindrical and spherical capacitors.'),
                _t('Derivation for Cylindrical Capacitor', 'Coaxial cylinders of radii a and b: E = λ/(2πε₀r) between cylinders; V = λ/(2πε₀) ln(b/a); C = 2πε₀L/ln(b/a).', 'The logarithm in the cylindrical capacitor formula is essential — it is not linear in the radius ratio.', 'Derive C for a cylindrical capacitor by integrating E to find V.'),
                _t('Series and Parallel Capacitors', 'Parallel: C_eq = Σ C_i (same V); Series: 1/C_eq = Σ1/C_i (same Q). Charge on capacitors in series is equal; voltage divides.', 'In series, capacitors share the same charge (not voltage); in parallel they share the same voltage (not charge).', 'Reduce capacitor networks to a single equivalent capacitance.')],
               [('Capacitance C', 'C = Q/V; charge stored per unit voltage (F = C/V)'),
                ('Parallel plate capacitance', 'C = ε₀A/d; increases with area, decreases with separation'),
                ('Cylindrical capacitor', 'C = 2πε₀L/ln(b/a)'),
                ('Series capacitors', '1/C_eq = Σ1/C_i; same charge on each'),
                ('Parallel capacitors', 'C_eq = ΣC_i; same voltage across each')],
               ['Calculate C for parallel plate, spherical, and cylindrical capacitors.',
                'Derive C by integrating E to find V for non-planar geometries.',
                'Reduce series/parallel combinations to a single equivalent C.'],
               ['Free-response: derive C for a cylindrical capacitor step by step.',
                'Series-parallel network: find equivalent C and charge on each capacitor.',
                'Comparison: how does doubling plate separation affect C, Q, V?'],
               ['Derive C for cylindrical and spherical capacitors.',
                'Practice reducing complex capacitor networks.'],
               [('Derive the capacitance of a cylindrical capacitor with inner radius a, outer radius b, length L.', ['E between cylinders: E = λ/(2πε₀r) from Gauss\'s law', 'V = -∫_a^b E dr = λ/(2πε₀) ln(b/a)', 'C = Q/V = λL/V = λL/[λ/(2πε₀) ln(b/a)] = 2πε₀L/ln(b/a)', 'Larger L or smaller ln(b/a) → larger C']),
                ('Two capacitors (C₁ = 4 μF, C₂ = 6 μF) are in series. Find C_eq and charge on each if V = 12 V.', ['1/C_eq = 1/4 + 1/6 = 5/12 → C_eq = 12/5 = 2.4 μF', 'Q = C_eq × V = 2.4 × 12 = 28.8 μC on each (series)', 'V₁ = Q/C₁ = 28.8/4 = 7.2 V; V₂ = 28.8/6 = 4.8 V', 'V₁ + V₂ = 12 V ✓']),
                ('Same capacitors in parallel. Find C_eq, total charge, and charge on each.', ['C_eq = 4 + 6 = 10 μF', 'Total Q = C_eq × V = 10 × 12 = 120 μC', 'Q₁ = C₁V = 4×12 = 48 μC; Q₂ = C₂V = 6×12 = 72 μC', 'Q₁ + Q₂ = 120 μC ✓']),
                ('A parallel plate capacitor has C = 5 μF. The plates are pulled to twice the original separation. Find new C, Q, V if it was disconnected from battery (Q constant).', ['C_new = ε₀A/(2d) = C/2 = 2.5 μF', 'Q is constant (disconnected): Q stays the same', 'V_new = Q/C_new = 2Q/C = 2V_original', 'Pulling apart disconnected capacitor doubles voltage']),
                ('How does the capacitance of a spherical capacitor (radii a and b) compare to a cylindrical one?', ['Spherical: C = 4πε₀/(1/a - 1/b) = 4πε₀ab/(b-a)', 'Cylindrical: C/L = 2πε₀/ln(b/a)', 'Spherical scales as ~a for a << b (isolated sphere limit)', 'Both require integrating E to find V — key approach'])],
               [('Bozeman Capacitance', 'Capacitance formula, derivations, series/parallel', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Capacitors', 'Series and parallel capacitor combinations', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['C = Q/V; parallel plate: C = ε₀A/d.',
                'Cylindrical: C = 2πε₀L/ln(b/a).',
                'Series: 1/C_eq = Σ1/C_i; parallel: C_eq = ΣC_i.']),

            _l('Energy in Capacitors and Electric Fields',
               [_t('Energy Stored in a Capacitor', 'U = ½QV = ½CV² = Q²/(2C). Derived by integrating dW = V dq as charge is added. Energy is stored in the electric field between the plates.', 'U = ½CV² — the factor of ½ is essential; it arises from the linear relationship Q = CV as Q builds up.', 'Calculate energy stored in a capacitor for given C and V or Q.'),
                _t('Energy Density in Electric Field', 'u = ½ε₀E² (J/m³); energy per unit volume in an electric field. Total energy = ∫u dV.', 'Energy density depends on E², not E — doubling the field quadruples the energy density.', 'Calculate total field energy by integrating u = ½ε₀E² over a volume.'),
                _t('Force Between Capacitor Plates', 'The force between capacitor plates can be found from U = Q²/(2C) using F = -dU/dx. For parallel plates: F = Q²/(2ε₀A).', 'The force between plates uses U held at constant Q (isolated) or constant V (connected) — results differ.', 'Derive the force between plates using the energy method.')],
               [('Energy stored U', 'U = ½QV = ½CV² = Q²/(2C)'),
                ('Energy density u', 'u = ½ε₀E²; energy per unit volume in electric field'),
                ('Parallel plate E', 'E = σ/ε₀ = Q/(ε₀A) between plates (uniform field)'),
                ('Force from energy', 'F = -dU/dx; force from spatial derivative of energy'),
                ('Charging work', 'W = ½CV²; work done to charge a capacitor from zero')],
               ['Derive and calculate energy stored in a capacitor.',
                'Find energy density in a uniform electric field.',
                'Calculate force between plates using energy methods.'],
               ['Free-response: find energy stored in series/parallel capacitor networks.',
                'Integration: compute total energy in the field between coaxial cylinders.',
                'Force: derive force between plates using F = -dU/dx.'],
               ['Compare energy stored at constant V vs. constant Q when plates are moved.',
                'Compute u and total field energy for given E.'],
               [('Derive U = ½CV² for a capacitor by integrating the work done as charge is added.', ['dW = V dq = (q/C) dq', 'W = ∫₀^Q (q/C) dq = Q²/(2C)', 'Also: Q = CV → U = Q²/(2C) = (CV)²/(2C) = ½CV²', 'U = ½QV by substituting Q = CV']),
                ('A parallel plate capacitor (C = 10 μF, V = 100 V). Find energy stored.', ['U = ½CV² = ½(10×10⁻⁶)(100)² = ½(10⁻⁵)(10⁴) = 0.05 J', 'U = 50 mJ', 'Or: Q = CV = 10⁻³ C; U = ½QV = ½(10⁻³)(100) = 0.05 J ✓', 'Larger C or larger V → more energy stored']),
                ('Find total energy stored in the electric field of a spherical capacitor (charge Q, inner R, gap to outer).', ['u = ε₀E²/2; E = kQ/r² for a < r < b', 'U = ∫u dV = ∫_a^b (ε₀/2)(kQ/r²)² 4πr² dr', 'U = (kQ²/2)∫_a^b (1/r²) dr = (kQ²/2)(1/a - 1/b)', 'This equals Q²/(2C) with C = 4πε₀ab/(b-a) ✓']),
                ('A capacitor is connected to a battery (V = 6 V, C = 100 μF). Then the battery is disconnected and the plate separation doubled. Compare initial and final energy.', ['Initial: U_i = ½CV² = ½(100×10⁻⁶)(36) = 1.8 mJ; Q = CV = 6×10⁻⁴ C', 'After disconnection: Q fixed; C_new = C/2 = 50 μF', 'U_f = Q²/(2C_new) = (6×10⁻⁴)²/(2×50×10⁻⁶) = 3.6 mJ', 'Energy doubles — from work done against attractive plate force']),
                ('What is the energy density between parallel plates if V = 200 V and d = 2 mm?', ['E = V/d = 200/0.002 = 100 000 V/m', 'u = ½ε₀E² = ½(8.85×10⁻¹²)(10¹⁰) = 44.25 J/m³', 'Total energy = u × volume = u × A × d', 'Increasing E greatly increases energy density (u ∝ E²)'])],
               [('Bozeman Capacitor Energy', 'U = ½CV², energy density, energy methods', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Capacitor Energy', 'Deriving U = ½CV² and energy density', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['U = ½CV² = Q²/(2C); factor of ½ from linear charging.',
                'Energy density u = ½ε₀E².',
                'Force from energy: F = -dU/dx at constant Q.']),

            _l('Dielectrics',
               [_t('Dielectric Effect', 'Inserting a dielectric of constant κ: C_new = κC₀; E_new = E₀/κ; V_new = V₀/κ (at constant Q). Dielectric weakens the field and increases capacitance.', 'Inserting a dielectric INCREASES capacitance (C = κC₀ with κ > 1), reducing E and V for the same charge.', 'Predict effects of inserting a dielectric at constant V vs. constant Q.'),
                _t('Molecular Explanation', 'Polar molecules align with the field; nonpolar molecules develop induced dipoles. The aligned dipoles create an opposing field that reduces the net field inside the dielectric.', 'The dielectric does not cancel E — it REDUCES E by a factor κ, not to zero.', 'Explain qualitatively why κ > 1 for all materials.'),
                _t('Gauss\'s Law in Dielectrics', 'Modified Gauss\'s law: ∮D·dA = Q_free/ε₀ where D = ε₀κE. D is the displacement field; it is determined by free charges only.', 'D is not the same as E — D accounts for dielectric polarization; E is the actual field in the material.', 'Apply Gauss\'s law with D to find E in the presence of a dielectric.')],
               [('Dielectric constant κ', 'κ = C/C₀ ≥ 1; dimensionless; ratio of capacitance with/without dielectric'),
                ('Permittivity ε', 'ε = κε₀; effective permittivity in the dielectric'),
                ('Bound charge', 'Charge induced on dielectric surface by polarization; reduces E'),
                ('Displacement field D', 'D = ε₀κE = εE; determined by free charges only'),
                ('Dielectric breakdown', 'Maximum E before dielectric conducts; dielectric strength (V/m)')],
               ['Predict how a dielectric changes C, E, V, Q, and energy.',
                'Explain the molecular origin of dielectric polarization.',
                'Apply D = εE to find E in a dielectric using Gauss\'s law.'],
               ['Free-response: capacitor fully filled with dielectric — compare all quantities.',
                'Molecular: explain why κ_water >> κ_glass.',
                'Calculate new capacitance and charge for a partially filled capacitor.'],
               ['Compare dielectric insertion at constant V (battery connected) vs. constant Q.',
                'Analyze energy before and after inserting a dielectric at constant V.'],
               [('A parallel plate capacitor (C₀ = 5 μF) is charged to V = 100 V (battery then disconnected). A dielectric κ = 3 is inserted. Find new C, V, E, and U.', ['C_new = κC₀ = 15 μF; Q stays: Q = C₀V = 5×10⁻⁴ C', 'V_new = Q/C_new = 5×10⁻⁴/15×10⁻⁶ = 33.3 V', 'E_new = E₀/κ = 33.3 V reduction (E ∝ V for same d)', 'U_new = Q²/(2C_new) = (5×10⁻⁴)²/(30×10⁻⁶) = 8.33 mJ vs. initial 25 mJ — energy decreased!']),
                ('Same capacitor but battery remains connected (V = 100 V constant). Dielectric κ = 3 inserted. Find new C, Q, E, U.', ['C_new = 15 μF (V unchanged)', 'Q_new = C_new × V = 15×10⁻⁶ × 100 = 1500 μC (tripled)', 'E unchanged (V/d same); U_new = ½C_new V² = ½(15×10⁻⁶)(10⁴) = 75 mJ vs. 25 mJ', 'Energy increased 3×; battery supplied extra charge']),
                ('Explain why inserting a dielectric at constant Q decreases energy.', ['Dielectric molecules become polarized, lowering system energy', 'Net effect: like adding a spring — stored elastic PE less than electrostatic PE lost', 'Force pulls dielectric in (energy decreases → F = -dU/dx negative, meaning force inward)', 'This is analogous to why a capacitor pulls its plates together']),
                ('Water has κ ≈ 80. Explain why water is a much better dielectric than glass (κ ≈ 7).', ['Water is highly polar (H₂O has large permanent dipole moment)', 'Polar molecules align strongly with the applied field', 'Greater alignment → more bound charge → stronger field reduction', 'Glass has smaller dipoles; polarization is mostly induced rather than permanent']),
                ('What is dielectric breakdown, and why is it relevant to capacitor design?', ['At sufficiently high E, electrons are freed from atoms — dielectric becomes conducting', 'Typical dielectric strength: 10⁶ to 10⁸ V/m', 'Once breakdown occurs, capacitor shorts out — catastrophic failure', 'Capacitor ratings include maximum working voltage to avoid breakdown'])],
               [('Bozeman Dielectrics', 'κ, bound charges, and dielectric effects on capacitors', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Dielectrics', 'Inserting dielectrics at constant V and constant Q', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Dielectric: C = κC₀; E reduces at constant Q.',
                'Constant Q: V, E reduce by κ; energy decreases.',
                'Constant V: Q, C increase by κ; energy increases.']),

            _l('Conductors: Advanced Boundary Conditions',
               [_t('Uniqueness Theorem', 'The Poisson equation ∇²V = -ρ/ε₀ has a unique solution given boundary conditions. This means any valid solution is THE solution — useful for finding fields by guessing and verifying.', 'The uniqueness theorem applies to the Poisson equation, not to general electromagnetic scenarios — boundary conditions must fully specify the problem.', 'State uniqueness theorem and apply the method of images qualitatively.'),
                _t('Method of Images', 'A charge q near a grounded conducting plane can be modeled by replacing the conductor with an image charge -q at the mirror position. The field above the plane is the same.', 'The method of images works only for specific geometries (infinite planes, spheres); it does not generalize to arbitrary shapes.', 'Apply the method of images to find the force on a charge near a grounded plane.'),
                _t('Induced Charges and Shielding', 'Charges near conductors induce surface charges. A Faraday cage (hollow conductor) shields interior from external E. A grounded conductor shields more completely.', 'A Faraday cage blocks static E fields and transient fields — it does NOT block magnetic fields at low frequency.', 'Explain how induced charges on conductors redistribute and shield the interior.')],
               [('Poisson equation', '∇²V = -ρ/ε₀; governs V given charge distribution'),
                ('Laplace equation', '∇²V = 0 in charge-free regions'),
                ('Method of images', 'Replace conductor with image charge to satisfy boundary conditions'),
                ('Faraday cage', 'Hollow conductor shielding interior from external E field'),
                ('Uniqueness theorem', 'Solution to Poisson equation with given BCs is unique')],
               ['State the uniqueness theorem and explain its significance.',
                'Apply the method of images to a point charge near a grounded plane.',
                'Explain Faraday cage shielding qualitatively.'],
               ['Free-response: use method of images to find force on charge q at distance d from grounded plane.',
                'Conceptual: explain why interior of a car is safe during a lightning strike.',
                'Derive E just outside a conductor using boundary conditions.'],
               ['Solve the method-of-images problem for a point charge near a conducting plane.',
                'Explain how a Faraday cage works in practical shielding applications.'],
               [('A charge q is at distance d above an infinite grounded conducting plane. Describe the method of images solution.', ['Replace the conductor with an image charge -q at distance d below the plane', 'The combined field of q and -q satisfies V = 0 at the plane (boundary condition)', 'Force on q: attractive, magnitude F = kq²/(2d)² = kq²/(4d²)', 'Induced charge on plane: nonuniform distribution with total charge = -q']),
                ('Find the energy of the charge-image system and relate it to force on the charge.', ['U = k(q)(-q)/(2d) = -kq²/(2d)', 'F = -dU/dd = -kq²/(2d²)... careful: image moves at rate 2 as d changes', 'F = -dU/d(2d) = kq²/(4d²) (attractive)', 'Image method gives exact force on q above the conductor']),
                ('Why does a Faraday cage shield the interior from external electric fields?', ['External E induces surface charges that cancel external field inside', 'Induced surface charges redistribute until E = 0 inside conductor', 'Interior of closed conductor is completely shielded', 'Even non-closed mesh works at high frequency (wavelength >> gap size)']),
                ('What is the Poisson equation and where does it come from?', ['From Gauss\'s law: ∇·E = ρ/ε₀ and E = -∇V', 'Substituting: ∇·(-∇V) = ρ/ε₀ → ∇²V = -ρ/ε₀', 'Laplace equation: ∇²V = 0 where ρ = 0', 'These are the fundamental equations governing electrostatic potential']),
                ('Explain why conductors connected to ground are more effective shields than isolated conductors.', ['Grounded conductor can supply or remove charge freely', 'Induced charges can exactly cancel external field for any external source', 'Isolated conductor has fixed total charge — partial cancellation only', 'Grounding ensures V = 0 on the conductor, satisfying the exact boundary condition'])],
               [('Bozeman Method of Images', 'Uniqueness theorem and method of images', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U'),
                ('Flipping Physics Conductors Advanced', 'Conductor boundary conditions and shielding', 'https://www.youtube.com/watch?v=Hn7IIBHXN3U')],
               ['Method of images: replace conductor with mirror charge; satisfies V = 0 BCs.',
                'Faraday cage: interior shielded from external E field.',
                'Poisson: ∇²V = -ρ/ε₀; Laplace: ∇²V = 0 in charge-free regions.'])
        ],
        'unit_qs': [
            ('Derive C for a spherical capacitor with inner radius a, outer radius b.',
             ['E between shells: E = kQ/r² from Gauss (radial symmetry)', 'V = -∫_a^b E dr = kQ(1/a - 1/b) = kQ(b-a)/(ab)', 'C = Q/V = Q/[kQ(b-a)/(ab)] = ab/(k(b-a)) = 4πε₀ab/(b-a)', 'For a << b: C ≈ 4πε₀a (isolated sphere limit)']),
            ('A 2 μF and 4 μF capacitor are in series, connected to 12 V. Find charge, voltage on each, and total energy.',
             ['C_eq = (2×4)/(2+4) = 4/3 μF; Q = C_eq × V = (4/3)(12) = 16 μC', 'V₁ = Q/C₁ = 16/2 = 8 V; V₂ = Q/C₂ = 16/4 = 4 V; V₁+V₂ = 12 ✓', 'U = ½C_eq V² = ½(4/3×10⁻⁶)(144) = 96 μJ', 'Or: U = Q²/(2C_eq) = (16×10⁻⁶)²/(2×4/3×10⁻⁶) = 96 μJ ✓']),
            ('A parallel plate capacitor with area A = 0.01 m², d = 1 mm, κ = 4. Find C, and energy stored at V = 50 V.',
             ['C₀ = ε₀A/d = (8.85×10⁻¹²)(0.01)/0.001 = 88.5 pF', 'C = κC₀ = 4 × 88.5 = 354 pF', 'U = ½CV² = ½(354×10⁻¹²)(2500) = 442.5 nJ', 'Dielectric increased C by 4× and energy by 4×']),
            ('A capacitor (C = 20 μF, V₀ = 200 V) is disconnected and then connected to an uncharged capacitor (C = 60 μF). Find final voltage.',
             ['Q₀ = C₁V₀ = 20×10⁻⁶ × 200 = 4×10⁻³ C', 'After connection: charge distributes; Q total conserved', 'V_f = Q₀/(C₁+C₂) = 4×10⁻³/(80×10⁻⁶) = 50 V', 'Energy before: ½C₁V₀² = 400 mJ; after: ½(C₁+C₂)V_f² = 100 mJ; 300 mJ dissipated']),
            ('Derive the energy density u = ½ε₀E² and show that total energy U = u × (volume between plates) for a parallel plate capacitor.',
             ['U = ½CV² = ½(ε₀A/d)(Ed)² = ½ε₀E² × (Ad)', 'Volume between plates = A × d', 'U = u × Volume where u = ½ε₀E²', 'Confirms energy is stored in the field, distributed throughout the volume']),
            ('Explain why C increases when a dielectric is inserted at constant voltage (battery connected).',
             ['Battery maintains constant V → E = V/d remains constant', 'Dielectric reduces E by factor κ (bound charges oppose E)', 'To maintain same V with reduced field: more free charge Q must be deposited', 'More Q for same V means larger C = Q/V → C increases by κ']),
            ('Find the force per unit area (electrostatic pressure) between the plates of a charged parallel plate capacitor.',
             ['E between plates = σ/ε₀; each plate is in the field of the other plate = σ/(2ε₀)', 'Force per area = σ × E_other = σ²/(2ε₀) = ε₀E²/2 = u', 'Electrostatic pressure = energy density u = ½ε₀E²', 'This is also F = Q²/(2ε₀A²) × A = Q²/(2ε₀A)']),
            ('A charge q = 5 nC is 0.1 m above an infinite grounded conducting plane. Find the force on the charge using the method of images.',
             ['Image: charge -5 nC at 0.1 m below the plane', 'Distance between q and image = 0.2 m', 'F = k|q|²/(0.2)² = (8.99×10⁹)(5×10⁻⁹)²/(0.04)', 'F = (8.99×10⁹)(25×10⁻¹⁸)/0.04 = 5.62×10⁻⁶ N = 5.62 μN attractive']),
            ('Compare capacitor energy before and after inserting a dielectric (κ = 2) at constant Q.',
             ['Initial: U_i = Q²/(2C₀); after: C = 2C₀, U_f = Q²/(2×2C₀) = U_i/2', 'Energy decreases by factor 2', 'Where did energy go? The dielectric is pulled in — work done by the electric force', 'Energy transferred to kinetic/thermal energy of the dielectric slab']),
            ('A spherical conductor of radius R has charge Q. Find V at r = R, r = 2R, and r = 0.',
             ['r > R: V = kQ/r (point charge); at r = 2R: V = kQ/(2R)', 'At r = R: V = kQ/R', 'Inside conductor (0 < r < R): V = kQ/R (constant, same as surface)', 'V is continuous at r = R; E = 0 inside → V constant inside'])
        ]
    },

    {
        'num': 3, 'title': 'Electric Circuits',
        'file': 'ap-physics-c-electricity-and-magnetism-3-unit-10-conductors-and-capacitors.html',
        'desc': 'Current, resistance, EMF, Kirchhoff\'s laws, and RC circuits analyzed with calculus.',
        'gateway': [
            'Apply Ohm\'s law and Kirchhoff\'s laws to multi-loop DC circuits.',
            'Solve RC circuit differential equations for charging and discharging.',
            'Calculate power dissipation and apply energy conservation in circuits.',
            'Analyze complex resistor networks and apply the node/loop method.',
        ],
        'lessons': [
            _l('Current, Resistance, and Ohm\'s Law',
               [_t('Electric Current', 'I = dq/dt (A = C/s); current is the rate of charge flow. Conventional current flows from + to −; electron current flows opposite.', 'Conventional current direction is historically defined as + charge flow — opposite to actual electron flow in metals.', 'Calculate current from dq/dt; apply charge continuity in circuit junctions.'),
                _t('Resistance and Ohm\'s Law', 'R = V/I (Ω); for ohmic materials, R is constant. Resistivity: R = ρL/A where ρ depends on material and temperature. Ohm\'s law: V = IR.', 'Ohm\'s law (V = IR with constant R) is a special case, not a fundamental law — many devices are non-ohmic.', 'Calculate resistance from geometry and resistivity; apply V = IR.'),
                _t('Power Dissipation', 'P = IV = I²R = V²/R; power is dissipated as heat in a resistor. In a battery, P = εI (emf × current).', 'P = IV applies to any circuit element; P = I²R and V²/R are for resistors specifically (Ohm\'s law assumed).', 'Calculate power for resistors and sources in various circuit configurations.')],
               [('Current I', 'I = dq/dt; rate of charge flow (A = C/s)'),
                ('Resistance R', 'R = V/I; opposition to current (Ω)'),
                ('Resistivity ρ', 'R = ρL/A; material property (Ω·m)'),
                ('Ohm\'s law', 'V = IR; holds for ohmic materials'),
                ('Power P', 'P = IV = I²R = V²/R; electrical energy per unit time (W)')],
               ['Calculate current using I = dq/dt.',
                'Apply R = ρL/A and Ohm\'s law to circuit elements.',
                'Calculate power dissipated by and supplied to circuit elements.'],
               ['Free-response: find current and power in a multi-resistor circuit.',
                'Temperature effect: explain how R changes with temperature (R = R₀(1+αΔT)).',
                'Power: find efficiency of a real battery with internal resistance.'],
               ['Practice V = IR and power calculations for various circuit configurations.',
                'Calculate R from material dimensions and resistivity.'],
               [('A wire (ρ = 1.7×10⁻⁸ Ω·m, L = 2 m, diameter = 1 mm). Find R.', ['A = π(d/2)² = π(0.0005)² = 7.85×10⁻⁷ m²', 'R = ρL/A = (1.7×10⁻⁸)(2)/(7.85×10⁻⁷) = 0.0433 Ω ≈ 43 mΩ', 'Copper wire has very low resistance', 'Doubling length doubles R; quadrupling diameter reduces R by 16']),
                ('A 60 Ω resistor has 12 V across it. Find current and power.', ['I = V/R = 12/60 = 0.2 A', 'P = IV = 0.2 × 12 = 2.4 W', 'Or: P = V²/R = 144/60 = 2.4 W; Or: P = I²R = 0.04×60 = 2.4 W', 'All three formulas give same result (as they must)']),
                ('A battery (ε = 9 V, internal resistance r = 1 Ω) is connected to external R = 8 Ω. Find I, terminal voltage, and power to each component.', ['I = ε/(R+r) = 9/9 = 1 A', 'Terminal voltage V_T = ε - Ir = 9 - 1 = 8 V', 'P_R = I²R = 1²×8 = 8 W; P_r = I²r = 1 W (wasted)', 'P_total = εI = 9 W = P_R + P_r ✓']),
                ('How does current relate to dq/dt and what does this mean physically?', ['I = dq/dt: current is the instantaneous rate of charge flow', 'High current means many charges passing a point per second', 'Total charge: q = ∫I dt (integral of current over time)', 'In a circuit, current is continuous (Kirchhoff\'s current law)']),
                ('What is the difference between a 60 W and a 100 W light bulb at 120 V?', ['60 W: R = V²/P = 14400/60 = 240 Ω; I = P/V = 0.5 A', '100 W: R = 14400/100 = 144 Ω; I = 100/120 ≈ 0.833 A', 'Lower R → more current → more power for same voltage', '100 W bulb is brighter but draws more current'])],
               [('Bozeman Current and Resistance', 'I = dq/dt, R = ρL/A, Ohm\'s law, power', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Circuits', 'Basic circuit elements and power', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['I = dq/dt; R = ρL/A; V = IR.',
                'P = IV = I²R = V²/R; all equivalent for resistors.',
                'Battery power: P = εI; terminal voltage = ε - Ir.']),

            _l('Kirchhoff\'s Laws and Circuit Analysis',
               [_t('Kirchhoff\'s Current Law (KCL)', 'Sum of currents into a node = sum out; ΣI_in = ΣI_out. Conservation of charge; no charge accumulates at a node.', 'KCL applies to all circuits — steady-state AND transient. It is a statement of charge conservation.', 'Write and solve KCL equations for multi-junction circuits.'),
                _t('Kirchhoff\'s Voltage Law (KVL)', 'Sum of voltage drops around any closed loop = 0: ΣV = 0. This is a statement of energy conservation (path-independent potential).', 'Sign convention: voltage rises across EMFs in the direction of current; voltage drops across resistors.', 'Write and solve KVL equations for multi-loop circuits.'),
                _t('Solving Multi-Loop Circuits', 'Assign unknown currents to each branch, apply KCL at nodes, and KVL around independent loops. Solve the resulting system of linear equations.', 'Choose loop directions consistently — currents that come out negative just flow in the opposite direction.', 'Solve 2- and 3-loop circuits using KCL and KVL systems of equations.')],
               [('KCL', 'ΣI_in = ΣI_out at any circuit node (charge conservation)'),
                ('KVL', 'ΣV = 0 around any closed loop (energy conservation)'),
                ('Branch current', 'Current through a specific element; assigned as unknown'),
                ('Loop current', 'Hypothetical current circling a loop in mesh analysis'),
                ('Node voltage', 'Voltage at a node relative to reference; used in nodal analysis')],
               ['Write and apply KCL and KVL to multi-loop circuits.',
                'Assign branch currents and set up a system of equations.',
                'Solve 2-loop circuits numerically and symbolically.'],
               ['Free-response: solve a 3-element 2-loop circuit using Kirchhoff\'s laws.',
                'Verify solution by checking power balance (total power supplied = total dissipated).',
                'Wheatstone bridge: find conditions for zero current through the galvanometer.'],
               ['Practice setting up and solving KCL/KVL equations for 3 different circuits.',
                'Verify each solution by checking all KCL and KVL conditions.'],
               [('Two batteries (ε₁ = 12 V, r₁ = 1 Ω and ε₂ = 6 V, r₂ = 2 Ω) and R = 5 Ω in one loop. Find I.', ['KVL (single loop): ε₁ - ε₂ - I(r₁ + r₂ + R) = 0', '12 - 6 - I(1 + 2 + 5) = 0 → 6 = 8I → I = 0.75 A', 'Positive I means assumed direction is correct', 'Check: power from ε₁ = 9 W; power to ε₂ + R + r = 9 W ✓']),
                ('A circuit has nodes A and B connected by three parallel branches: R₁ = 6 Ω, R₂ = 3 Ω, R₃ = 2 Ω, with ε = 12 V from A to B. Find currents in each branch.', ['V_AB = 12 V for each branch (parallel)', 'I₁ = 12/6 = 2 A; I₂ = 12/3 = 4 A; I₃ = 12/2 = 6 A', 'Total I = 2 + 4 + 6 = 12 A', 'R_eq = 12/12 = 1 Ω; verify: 1/(1/6+1/3+1/2) = 1/1 ✓']),
                ('Three resistors (R₁ = 2, R₂ = 4, R₃ = 6 Ω) in complex 2-loop circuit with ε = 10 V. Set up equations.', ['Assign I₁, I₂ branch currents; I₃ through R₃ = I₁ - I₂ (KCL)', 'Loop 1: ε - I₁R₁ - (I₁-I₂)R₃ = 0', 'Loop 2: -(I₁-I₂)R₃ + I₂R₂ ... depends on topology', 'Method: always draw circuit, assign consistently, solve linear system']),
                ('Explain why KVL is a consequence of the conservative nature of the electric field.', ['Conservative field: work done around any closed path = 0', 'V is path-independent: going around a loop returns to same V', 'ΣV = ΣΔV = 0 in any loop is just energy conservation for charges', 'Non-conservative forces (EMF from batteries) are explicitly included as voltage rises']),
                ('What is the Wheatstone bridge and when is it balanced?', ['Four resistors R₁, R₂, R₃, R₄ in a diamond with galvanometer across middle', 'Balanced when R₁/R₂ = R₃/R₄ (no current through galvanometer)', 'Used to measure unknown resistance by adjusting one known resistor to balance', 'At balance: V_A = V_B across galvanometer'])],
               [('Bozeman Kirchhoff\'s Laws', 'KCL, KVL, and multi-loop circuits', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Kirchhoff', 'Applying KCL and KVL to complex circuits', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['KCL: ΣI_in = ΣI_out (charge conservation).',
                'KVL: ΣV = 0 per loop (energy conservation).',
                'Multi-loop: assign branch currents, write KCL/KVL, solve system.']),

            _l('RC Circuits',
               [_t('Charging an RC Circuit', 'When a battery charges a capacitor through R: q(t) = Cε(1 - e^{-t/RC}); I(t) = (ε/R)e^{-t/RC}. Time constant τ = RC. After 5τ, the capacitor is ~99% fully charged.', 'The time constant τ = RC depends on both R and C — larger R or C means slower charging.', 'Derive the charging equation by solving the KVL differential equation.'),
                _t('Discharging an RC Circuit', 'When a charged capacitor (initial V₀) discharges through R: q(t) = Q₀ e^{-t/RC}; I(t) = (V₀/R)e^{-t/RC}. Current decreases exponentially.', 'During discharge, I is not constant — it decreases as the capacitor empties and V drops.', 'Derive the discharge equation and calculate time for charge to reach a fraction of Q₀.'),
                _t('Energy in RC Circuits', 'Energy delivered by battery = Cε²; energy stored in capacitor = ½Cε²; energy dissipated in R = ½Cε². Exactly half the battery energy is always dissipated, regardless of R.', 'The energy lost in R is always ½Cε², regardless of the value of R — changing R only changes the speed of charging, not the energy dissipated.', 'Calculate energy balance in RC charging from first principles.')],
               [('Time constant τ', 'τ = RC; characteristic time scale for RC circuit response'),
               ('Charging equation', 'q(t) = Cε(1 - e^{-t/τ}); I(t) = (ε/R)e^{-t/τ}'),
                ('Discharging equation', 'q(t) = Q₀e^{-t/τ}; V(t) = V₀e^{-t/τ}'),
                ('Energy balance', 'Battery energy Cε²: half stored in C, half dissipated in R'),
                ('Five time constants', 'After 5τ, capacitor is ≈99.3% fully charged or discharged')],
               ['Derive the charging and discharging equations for an RC circuit.',
                'Calculate charge, current, and voltage at any time t in an RC circuit.',
                'Explain the energy balance: half the battery energy is always dissipated.'],
               ['Free-response: derive q(t) for charging by writing and solving the KVL ODE.',
                'Find time for capacitor to reach 90% of final charge.',
                'Energy: show that energy dissipated = ½Cε² regardless of R.'],
               ['Solve the charging ODE by separation of variables.',
                'Practice energy balance calculations for several RC scenarios.'],
               [('Derive the charging equation q(t) = Cε(1 - e^{-t/RC}) from KVL.', ['KVL: ε = V_R + V_C = IR + q/C = R(dq/dt) + q/C', 'R(dq/dt) = ε - q/C → dq/(ε - q/C) = dt/R', 'Separate: -C d(ε-q/C) / (ε-q/C) = dt/R... or let u = ε - q/C', 'q(t) = Cε(1 - e^{-t/RC}) with q(0) = 0']),
                ('An RC circuit (R = 10 kΩ, C = 100 μF, ε = 5 V). Find τ and q at t = τ.', ['τ = RC = 10⁴ × 10⁻⁴ = 1 s', 'q(τ) = Cε(1 - e^{-1}) = (100×10⁻⁶)(5)(1 - 0.368) = 316 μC', 'Final charge Q_f = Cε = 500 μC; at t = τ: 63.2% charged', 'I(τ) = (ε/R)e^{-1} = 5/10⁴ × 0.368 = 0.184 mA']),
                ('Show that exactly half the battery energy is dissipated as heat during charging.', ['E_battery = εQ_f = ε(Cε) = Cε²', 'E_stored = ½Cε²', 'E_dissipated = E_battery - E_stored = Cε² - ½Cε² = ½Cε²', 'This is independent of R — changing R changes time, not energy balance']),
                ('A capacitor (Q₀ = 500 μC, C = 100 μF) discharges through R = 5 kΩ. Find τ and time to discharge to 10% of Q₀.', ['τ = RC = 5000 × 100×10⁻⁶ = 0.5 s', 'q(t) = Q₀e^{-t/τ} = 0.1Q₀ → e^{-t/0.5} = 0.1', 't = -0.5 ln(0.1) = -0.5(-2.303) = 1.15 s = 2.30τ', '2.30τ for 10% remaining; 4.61τ for 1% remaining']),
                ('If R is doubled in an RC charging circuit (battery and C fixed), how does the energy dissipated change?', ['Energy dissipated = ½Cε² (independent of R)', 'R affects only the time scale (τ = RC doubles)', 'Same total energy is dissipated — just more slowly', 'This is surprising but follows from the exact cancellation in the energy integral'])],
               [('Bozeman RC Circuits', 'Charging/discharging equations, time constant, energy', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics RC Circuit', 'Deriving RC charging ODE and exponential solution', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['RC charging: q = Cε(1-e^{-t/τ}); τ = RC.',
                'Discharging: q = Q₀e^{-t/τ}; V = V₀e^{-t/τ}.',
                'Energy: half of battery energy (½Cε²) always dissipated, regardless of R.']),

            _l('Circuit Theorems and Power Delivery',
               [_t('Thevenin and Norton Equivalents', 'Any linear circuit can be replaced by a Thevenin equivalent (V_th in series with R_th) or Norton equivalent (I_N in parallel with R_N). V_th = open-circuit voltage; R_th = resistance with sources zeroed.', 'To find R_th, replace voltage sources with short circuits and current sources with open circuits, then measure resistance between terminals.', 'Find Thevenin and Norton equivalents for simple circuits.'),
                _t('Maximum Power Transfer', 'Maximum power is delivered to the load when R_load = R_th (Thevenin resistance). Maximum P_max = V_th²/(4R_th).', 'Maximum power transfer does NOT maximize efficiency — at maximum P transfer, 50% is wasted in R_th.', 'Find R_load for maximum power transfer and calculate P_max.'),
                _t('Superposition in Circuits', 'In a linear circuit with multiple sources, find the contribution of each source separately (deactivate others) and add results. Applies to voltage and current.', 'Superposition applies to voltages and currents, NOT to power — P = I²R is nonlinear.', 'Apply superposition to find current or voltage in a circuit with multiple sources.')],
               [('Thevenin equivalent', 'V_th and R_th in series; equal to original circuit at terminals'),
                ('Norton equivalent', 'I_N and R_N in parallel; I_N = V_th/R_th'),
                ('Maximum power transfer', 'P_max when R_load = R_th; P_max = V_th²/(4R_th)'),
                ('Superposition', 'Find response from each source separately; sum for total response'),
                ('Efficiency', 'η = P_load/P_total; at max power transfer η = 50%')],
               ['Find Thevenin equivalent of a circuit at a pair of terminals.',
                'Calculate R_load for maximum power transfer and P_max.',
                'Apply superposition to find current from multiple sources.'],
               ['Free-response: find V_th and R_th for a given two-terminal network.',
                'Calculate power delivered to load as function of R_load; find maximum.',
                'Superposition: find current through a specific resistor with two batteries.'],
               ['Practice Thevenin reduction for 3 different circuit topologies.',
                'Verify superposition result using Kirchhoff\'s laws.'],
               [('Find the Thevenin equivalent for a circuit with ε = 12 V, R₁ = 4 Ω in series, R₂ = 8 Ω in parallel with the terminals.', ['V_th = V_oc = ε × R₂/(R₁+R₂) = 12 × 8/12 = 8 V (voltage divider)', 'R_th: zero ε (short), R₁ and R₂ in parallel: R_th = 4×8/(4+8) = 8/3 Ω', 'Thevenin: 8 V source in series with 8/3 Ω', 'For any load R_L: I = V_th/(R_th + R_L)']),
                ('Find R_L for maximum power transfer and P_max in the circuit above.', ['R_L = R_th = 8/3 Ω ≈ 2.67 Ω', 'P_max = V_th²/(4R_th) = 64/(4×8/3) = 64/(32/3) = 6 W', 'Check: I = V_th/(R_th+R_L) = 8/(16/3) = 1.5 A; P = I²R_L = (1.5)²(8/3) = 6 W ✓', 'Only 50% efficiency: same power in R_th']),
                ('Circuit has two batteries ε₁ = 6 V and ε₂ = 4 V with R = 10 Ω. Use superposition to find I through R.', ['Source 1 alone (ε₂ = 0 → short): I₁ = ε₁/R = 6/10 = 0.6 A', 'Source 2 alone (ε₁ = 0 → short): I₂ = ε₂/R = 4/10 = 0.4 A', 'Total I = I₁ + I₂ = 1.0 A (if aiding) or 0.2 A (if opposing)', 'Direction matters — add with correct signs']),
                ('Why does superposition NOT apply to power?', ['P = I²R is nonlinear in I', 'Superposition gives I = I₁ + I₂; but P ≠ P₁ + P₂', 'P = (I₁+I₂)²R = I₁²R + I₂²R + 2I₁I₂R ≠ P₁ + P₂', 'Superposition only applies to linear quantities (V and I)']),
                ('Explain the physical meaning of R_th in the Thevenin theorem.', ['R_th is the "output impedance" of the circuit seen from the terminals', 'It equals the resistance measured at the terminals with all independent sources zeroed', 'Determines how much current drops when load is connected', 'Maximum power transfer occurs when load resistance equals R_th'])],
               [('Bozeman Thevenin Theorem', 'Thevenin equivalent and maximum power transfer', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8'),
                ('Flipping Physics Superposition', 'Superposition theorem in circuits', 'https://www.youtube.com/watch?v=Yd1RgfCjLC8')],
               ['Thevenin: V_th = V_oc; R_th = resistance with sources zeroed.',
                'Max power: R_L = R_th; P_max = V_th²/(4R_th).',
                'Superposition: linear (V, I) only; power is nonlinear.'])
        ],
        'unit_qs': [
            ('Derive the RC discharge equation q(t) = Q₀e^{-t/RC} from KVL.',
             ['KVL (no EMF): 0 = IR + q/C → R(dq/dt) + q/C = 0', 'Separate: dq/q = -dt/RC → ln(q/Q₀) = -t/RC', 'q(t) = Q₀e^{-t/RC}; I = -dq/dt = (Q₀/RC)e^{-t/RC}', 'I and q decrease exponentially with time constant τ = RC']),
            ('A circuit: ε = 20 V, R₁ = 2 Ω (internal), R₂ = 3 Ω, R₃ = 6 Ω (R₂ ∥ R₃). Find I from battery and power from each element.',
             ['R₂₃ = (3×6)/(3+6) = 2 Ω; total R = 2 + 2 = 4 Ω', 'I = 20/4 = 5 A; V_R₂₃ = I × R₂₃ = 10 V', 'I₂ = 10/3 = 3.33 A; I₃ = 10/6 = 1.67 A; I₂+I₃ = 5 A ✓', 'P_battery = 100 W; P_r₁ = 50 W; P_R₂ = 33.3 W; P_R₃ = 16.7 W']),
            ('Solve a two-loop circuit: ε₁ = 10 V in loop 1, ε₂ = 5 V in loop 2; R₁ = 1 Ω, R₂ = 2 Ω, R₃ = 3 Ω.',
             ['Assign I₁ (loop 1), I₂ (loop 2); shared branch carries I₁ - I₂', 'Loop 1 KVL: 10 = I₁R₁ + (I₁-I₂)R₃ = I₁ + 3(I₁-I₂) = 4I₁ - 3I₂', 'Loop 2 KVL: 5 = I₂R₂ + (I₂-I₁)R₃ = 2I₂ + 3(I₂-I₁) = -3I₁ + 5I₂', 'Solve: 4I₁ - 3I₂ = 10; -3I₁ + 5I₂ = 5 → I₁ = 3.18 A, I₂ = 2.91 A']),
            ('An RC circuit (R = 1 MΩ, C = 10 μF) charges from ε = 9 V. Find τ, time to 63% and 99% charge.',
             ['τ = RC = 10⁶ × 10⁻⁵ = 10 s', 'At t = τ: q = Cε(1-e⁻¹) = 0.632 × Cε → 63.2% charged', 'At t = 5τ = 50 s: q = Cε(1-e⁻⁵) = 0.9933 × Cε → 99.3% charged', 'Time to 99.3% = 5τ = 50 s in this circuit']),
            ('Find the Thevenin equivalent for a bridge circuit and determine maximum power to a load.',
             ['Measure V_oc across terminals A-B (no load)', 'Remove load, zero sources, measure R_AB', 'R_L_opt = R_th for P_max; P_max = V_th²/(4R_th)', 'Thevenin simplification enables quick load analysis']),
            ('A 100 μF capacitor (initially uncharged) is charged through 50 kΩ from 12 V. Find time to reach 8 V.',
             ['V_C(t) = ε(1 - e^{-t/τ}); τ = RC = 50×10³ × 100×10⁻⁶ = 5 s', '8 = 12(1 - e^{-t/5}) → e^{-t/5} = 1/3 → t = 5 ln3 ≈ 5.49 s', 't ≈ 5.49 s ≈ 1.1τ', 'Voltage approaches 12 V asymptotically']),
            ('Calculate total energy delivered by the battery and energy dissipated in R for the charging process above.',
             ['Q_f = Cε = 100×10⁻⁶ × 12 = 1.2 mC', 'E_battery = εQ_f = 12 × 1.2×10⁻³ = 14.4 mJ', 'E_stored = ½Cε² = ½(10⁻⁴)(144) = 7.2 mJ', 'E_dissipated = 14.4 - 7.2 = 7.2 mJ = ½Cε² (50%)']),
            ('Three resistors (R₁ = R₂ = R₃ = 6 Ω) are connected in a delta (triangle) configuration. Find the equivalent resistance between any two terminals.',
             ['Delta to star: R_star = R_delta/3 = 2 Ω each', 'Between two nodes of delta: two paths — one direct and one through third', 'R_direct = R₁ = 6 Ω; R_other = R₂ + R₃ = 12 Ω', 'R_eq = 6 || 12 = (6×12)/(6+12) = 4 Ω']),
            ('Two resistors (R₁ = 10 Ω, R₂ = 40 Ω) in series with V = 50 V. Find current, power in each, and verify energy balance.',
             ['I = V/(R₁+R₂) = 50/50 = 1 A', 'P₁ = I²R₁ = 10 W; P₂ = I²R₂ = 40 W', 'P_total = 50 W = IV = 1 × 50 ✓', 'Energy balance: power in = power out']),
            ('An RC circuit has τ = 2 s. At t = 0 the capacitor is fully charged to V₀ = 10 V. Find V_C at t = 1 s, 2 s, 4 s.',
             ['V_C(t) = V₀e^{-t/τ}', 'V_C(1) = 10e^{-0.5} = 10 × 0.607 = 6.07 V', 'V_C(2) = 10e^{-1} = 10 × 0.368 = 3.68 V', 'V_C(4) = 10e^{-2} = 10 × 0.135 = 1.35 V'])
        ]
    },
]
