NAME        = 'AP® Precalculus'
ABBREV      = 'precalc'
SLUG        = 'ap-precalculus'
COURSE_FILE = 'ap-precalculus.html'
ACCENT_COLOR = '#818cf8'
_K = 'https://www.khanacademy.org/search?page_search_query='
_PL = 'https://www.youtube.com/results?search_query=Professor+Leonard+'
_Y = 'https://www.youtube.com/results?search_query=AP®+Precalculus+'

COURSE_QS = [
    ('A function f is one-to-one (injective) if',
     'each output value is produced by exactly one input — it passes the horizontal line test',
     ['each input produces exactly one output (that\'s the definition of any function)', 'f(x) > 0 for all x', 'f is increasing on its entire domain']),
    ('The inverse function f⁻¹(x) satisfies',
     'f(f⁻¹(x)) = x and f⁻¹(f(x)) = x — it "undoes" f',
     ['f⁻¹(x) = 1/f(x) (multiplicative inverse)', 'f⁻¹(x) = −f(x)', 'f⁻¹ is always defined for any f']),
    ('An exponential function f(x) = bˣ (b > 0, b ≠ 1) is increasing when',
     'b > 1 (the base is greater than 1)',
     ['b < 1', '0 < b < 1', 'x > 0 always']),
    ('The natural logarithm ln(x) is the logarithm with base',
     'e ≈ 2.718... (Euler\'s number)',
     ['10', '2', 'π']),
    ('A polynomial of degree n can have at most',
     'n real zeros (roots) and n−1 turning points (local extrema)',
     ['n+1 zeros', 'infinitely many zeros', 'exactly n turning points']),
    ('The Rational Root Theorem states that any rational zero of a polynomial with integer coefficients must be',
     'a fraction p/q where p divides the constant term and q divides the leading coefficient',
     ['an integer factor of the leading coefficient', 'a factor of the degree of the polynomial', 'between −1 and 1']),
    ('The period of f(x) = sin(bx) is',
     '2π/b',
     ['2πb', 'b/2π', 'π/b']),
    ('The amplitude of f(x) = A sin(x) is',
     '|A| — the maximum displacement from the midline',
     ['A (which can be negative)', '2A', 'A/2']),
    ('A unit circle definition of sine and cosine gives sin(θ) and cos(θ) as',
     'the y-coordinate and x-coordinate of the point where the terminal ray intersects the unit circle',
     ['the ratio of adjacent/hypotenuse and opposite/hypotenuse', 'the arc length and radius of a circle', 'the slope and y-intercept of the terminal ray']),
    ('The Pythagorean identity states that for any angle θ',
     'sin²(θ) + cos²(θ) = 1',
     ['tan²(θ) + 1 = sec²(θ) only', 'sin(θ)/cos(θ) = 1', 'sin(θ) × cos(θ) = 1/2']),
    ('A geometric sequence has a common ratio r, meaning consecutive terms satisfy',
     'aₙ = aₙ₋₁ × r (each term is multiplied by a constant ratio)',
     ['aₙ = aₙ₋₁ + r (common difference)', 'aₙ = r × n (proportional to n)', 'aₙ = aₙ₋₁ − r']),
    ('The sum of an infinite geometric series converges when',
     '|r| < 1, and the sum is a₁/(1 − r)',
     ['r > 0', '|r| > 1', 'the series has at least 10 terms']),
    ('To find the vertical asymptote of a rational function f(x) = p(x)/q(x), set',
     'q(x) = 0 and verify p(x) ≠ 0 at those values',
     ['p(x) = 0', 'p(x) = q(x)', 'the numerator degree > denominator degree']),
    ('The horizontal asymptote of f(x) = (3x² + 1)/(x² − 4) as x → ±∞ is',
     'y = 3 (ratio of leading coefficients when degrees are equal)',
     ['y = 0 (numerator degree < denominator degree)', 'y = −1/4', 'no horizontal asymptote']),
    ('An even function satisfies f(−x) = f(x), meaning it is symmetric about',
     'the y-axis',
     ['the origin', 'the x-axis', 'y = x']),
    ('The change of base formula for logarithms is',
     'log_b(x) = ln(x)/ln(b) = log(x)/log(b)',
     ['log_b(x) = b × log(x)', 'log_b(x) = ln(b)/ln(x)', 'log_b(x) = log(b)/log(x)']),
    ('Completing the square on x² + bx converts it to',
     '(x + b/2)² − (b/2)²',
     ['(x + b)² − b²', '(x + b/2)²', '(x − b/2)² + (b/2)²']),
    ('A complex number z = a + bi has modulus (absolute value) equal to',
     '√(a² + b²)',
     ['a + b', '|a| + |b|', '√(a² − b²)']),
    ('The vertex form of a quadratic function is',
     'f(x) = a(x − h)² + k, where (h, k) is the vertex',
     ['f(x) = ax² + bx + c', 'f(x) = a(x + h)² + k', 'f(x) = a(x − h)² − k']),
    ('A polar coordinate (r, θ) converts to rectangular coordinates as',
     'x = r cos θ, y = r sin θ',
     ['x = r sin θ, y = r cos θ', 'x = r/cos θ, y = r/sin θ', 'x = θ cos r, y = θ sin r']),
]

def _t(title, content, misconception, how_tested):
    return {'title': title, 'content': content, 'misconception': misconception, 'how_tested': how_tested}

def _l(title, topics, vocab, objectives, how_tested, practice, questions, videos, exit_ticket):
    return {'title': title, 'topics': topics, 'vocab': vocab, 'objectives': objectives,
            'how_tested': how_tested, 'practice': practice, 'questions': questions,
            'videos': videos, 'exit_ticket': exit_ticket}

UNITS = [
    {
        'num': 1,
        'title': 'Polynomial and Rational Functions',
        'file': 'ap-precalculus-1-unit-1-polynomial-and-rational-functions.html',
        'desc': 'Polynomial behavior, zeros, end behavior, and rational function asymptotes.',
        'gateway': [
            'How does the degree and leading coefficient determine a polynomial\'s end behavior?',
            'What is the relationship between zeros and factors of a polynomial?',
            'What conditions produce vertical, horizontal, and slant asymptotes in rational functions?',
            'How do you find and interpret average rate of change for a polynomial?',
        ],
        'lessons': [
            _l('Polynomial Functions and Their Behavior',
               [_t('Degree and Leading Coefficient', 'The degree is the highest power of x. The leading coefficient determines end behavior with the degree: even degree, positive LC → both ends up (↑↑); even, negative → both down (↓↓); odd, positive → down-up (↓↑); odd, negative → up-down (↑↓).', 'End behavior depends only on degree and leading coefficient — not on any other terms.', 'State end behavior from the leading term; match polynomial graphs to their degree and LC.'),
                _t('Zeros, Multiplicity, and Graphs', 'A zero of multiplicity 1 crosses the x-axis; multiplicity 2 (even) touches and bounces; multiplicity 3 (odd, ≥3) crosses with inflection. Total degree = sum of multiplicities.', 'Multiplicity tells you the behavior at each zero — multiplicity 2 does NOT always bounce at 45°, it touches smoothly.', 'Determine zeros and their multiplicities from a factored polynomial; sketch behavior at each zero.'),
                _t('Average Rate of Change', 'ARC = [f(b) − f(a)] / (b − a): the slope of the secant line from a to b. Measures how fast a function changes over an interval. AP® Precalculus tests ARC for polynomial, exponential, and log functions.', 'ARC is not the instantaneous rate of change (derivative) — it is the average over an interval. These are not the same for nonlinear functions.', 'Calculate and interpret ARC for polynomials; compare ARC across different intervals.')],
               [('degree', 'Highest power of x in the polynomial; determines end behavior category'),
                ('leading coefficient', 'Coefficient of the highest-degree term; sign determines up/down end behavior'),
                ('zero (root)', 'x-value where f(x) = 0; where the graph crosses or touches the x-axis'),
                ('multiplicity', 'How many times a factor (x−r) appears; determines crossing vs bouncing at r'),
                ('average rate of change', '(f(b)−f(a))/(b−a); slope of the secant line; average change per unit x')],
               ['Determine end behavior from the leading term of a polynomial.',
                'Identify zeros and their multiplicities from a factored polynomial.',
                'Calculate and interpret average rate of change over an interval.'],
               ['MCQ/FRQ: state end behavior from leading term; match graph to description.',
                'FRQ: find zeros and multiplicities; sketch graph behavior.',
                'FRQ: calculate ARC and explain what it represents in context.'],
               ['Sketch polynomial graphs using end behavior, zeros, and multiplicities.',
                'Calculate ARC for a polynomial on different intervals and compare.'],
               [('State the end behavior of f(x) = −2x⁵ + 3x² − 1.', ['Leading term: −2x⁵ (odd degree, negative leading coefficient)', 'As x→+∞: f(x)→−∞ (down right)', 'As x→−∞: f(x)→+∞ (up left)', 'Pattern: odd, negative → up-down (↑↓)']),
                ('f(x) = (x−1)²(x+3)(x−2). List the zeros and their multiplicities.', ['x = 1 (multiplicity 2): graph touches and bounces at x=1', 'x = −3 (multiplicity 1): graph crosses at x=−3', 'x = 2 (multiplicity 1): graph crosses at x=2', 'Degree = 2+1+1 = 4']),
                ('Find the ARC of f(x) = x³ − 2x on [1, 3].', ['f(1) = 1 − 2 = −1; f(3) = 27 − 6 = 21', 'ARC = (21 − (−1))/(3 − 1) = 22/2 = 11', 'The function increases an average of 11 units per unit of x on [1,3]', 'Compare to f(2) = 8−4=4; faster growth in [2,3] than [1,2]']),
                ('How many x-intercepts can a degree-5 polynomial have?', ['At most 5 (one per zero counting multiplicity)', 'Minimum: 1 (odd degree must cross x-axis at least once)', 'Exactly 5 distinct zeros is possible if all multiplicities are 1', 'Even multiplicities reduce crossing count: (x−1)²(x+2)³ → 2 intercepts despite degree 5']),
                ('Why does x-multiplicity 2 cause bouncing instead of crossing?', ['f(x) = (x−r)² ≥ 0 for all x (it cannot go below x-axis near r)', 'At r, f(r) = 0 and f changes from positive to zero and back to positive', 'The graph touches but does not cross — it bounces off', 'Odd multiplicity (1, 3, ...): f changes sign → graph crosses'])],
               [('Polynomial Graphs AP® Precalc', 'End behavior, zeros, multiplicities', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Polynomials', 'Zeros, multiplicity, and end behavior', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['End behavior: odd/even degree + sign of LC → two of ↑↑, ↓↓, ↑↓, ↓↑.',
                'Multiplicity even: bounce; odd: cross.',
                'ARC = (f(b)−f(a))/(b−a): slope of secant, not derivative.']),

            _l('Rational Functions',
               [_t('Vertical and Horizontal Asymptotes', 'VA: x-values where denominator = 0 (and numerator ≠ 0). HA: compare degrees of numerator (n) and denominator (d). n < d → y = 0; n = d → y = leading coefficients ratio; n > d → no HA (slant instead).', 'A zero of the denominator is NOT always a vertical asymptote — it may be a hole if the factor cancels with a numerator factor.', 'Find VAs, HAs, and holes; explain the difference between holes and asymptotes.'),
                _t('Holes and Removable Discontinuities', 'A hole occurs when the same factor appears in both numerator and denominator. Cancel the common factor to find the simplified form; hole is at that x-value in the original function.', 'Holes are NOT visible as gaps on a typical graphing calculator screen — you must find them algebraically.', 'Find holes by factoring and canceling; evaluate the y-coordinate of a hole.'),
                _t('Graphing Rational Functions', 'Procedure: factor → find domain → find intercepts → find asymptotes → find holes → analyze sign and sketch. End behavior follows the simplified rational expression.', 'The graph approaches but never touches asymptotes for large |x|, but the function CAN cross its HA for smaller x-values.', 'Sketch a rational function using all key features; interpret the graph in context.')],
               [('vertical asymptote', 'x = a where denominator = 0 and numerator ≠ 0; function approaches ±∞'),
                ('horizontal asymptote', 'y = L that the function approaches as x → ±∞; depends on degree comparison'),
                ('hole (removable discontinuity)', 'Open point on graph where a common factor cancels; function undefined there'),
                ('slant (oblique) asymptote', 'When numerator degree = denominator degree + 1; found by polynomial long division'),
                ('domain of rational function', 'All real x except zeros of the denominator')],
               ['Find all asymptotes and holes of a rational function.',
                'Determine the horizontal asymptote by comparing numerator and denominator degrees.',
                'Sketch a rational function using all key features.'],
               ['FRQ: find domain, intercepts, asymptotes, and holes; describe end behavior.',
                'MCQ: identify the type of asymptote given degree comparison.',
                'FRQ: explain why a feature is a hole vs a vertical asymptote.'],
               ['Complete a sign analysis to sketch a rational function.',
                'Compare two rational functions: one with HA y=0, one with HA y=2.'],
               [('Find the asymptotes of f(x) = (2x²−8)/(x²−x−6).', ['Factor: numerator = 2(x²−4) = 2(x−2)(x+2); denominator = (x−3)(x+2)', 'Hole at x = −2 (common factor); VA at x = 3', 'Degrees equal → HA: y = 2/1 = 2', 'Graph: HA y=2, VA x=3, hole at (−2, 8/5)']),
                ('What is the HA of (3x+1)/(5x²−2)?', ['Numerator degree 1 < denominator degree 2', 'HA: y = 0', 'Function approaches x-axis for large |x|', 'Dominant term in denominator grows faster']),
                ('f(x) = (x²+3x+2)/(x+1). Factor fully.', ['Numerator: (x+1)(x+2); denominator: (x+1)', 'Cancel (x+1): simplified = x+2', 'Hole at x = −1; no VA', 'Graph is the line y = x+2 with a hole at x=−1: point (−1, 1) missing']),
                ('How can a graph cross its horizontal asymptote?', ['HA describes behavior as x→±∞; finite crossing is possible for intermediate x', 'Example: (x+1)/(x−1) crosses y=1? No, but (x²+1)/(x²) = 1 + 1/x² crosses no HA', 'Some rational functions do cross y = c for specific finite x', 'HA is about limits at infinity, not about all of the function\'s behavior']),
                ('What is a slant asymptote and when does it occur?', ['When degree of numerator = degree of denominator + 1', 'Divide numerator by denominator using polynomial long division', 'Quotient (without remainder) is the slant asymptote equation', 'Example: (x²+1)/x → x + 1/x → slant asymptote y = x'])],
               [('Rational Functions AP® Precalc', 'Asymptotes, holes, and graphing', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Rational Functions', 'Graphing rational functions', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['VA: denominator = 0 (no cancellation); Hole: common factor cancels.',
                'HA: n<d → y=0; n=d → lead coeff ratio; n>d → slant.',
                'Function can cross HA for finite x; asymptote describes behavior at ±∞.']),

            _l('Polynomial Inequalities and Systems',
               [_t('Solving Polynomial Inequalities', 'Find zeros → set up sign chart → test intervals → identify where inequality is satisfied. Include endpoints if ≤ or ≥; exclude for strict inequalities. Use factored form for sign analysis.', 'When multiplying or dividing both sides of an inequality by a negative, flip the inequality sign. This is a common algebra error.', 'Solve polynomial and rational inequalities using sign charts; write solution in interval notation.'),
                _t('Polynomial Division and Remainder Theorem', 'Remainder Theorem: f(a) = remainder when f(x) is divided by (x−a). Factor Theorem: (x−a) is a factor iff f(a) = 0. Synthetic division is efficient for linear divisors.', 'The Remainder Theorem gives the function value at x=a without dividing — a powerful shortcut for evaluating and factoring.', 'Use synthetic division to find the remainder; apply the Factor Theorem to test potential zeros.'),
                _t('Rational Root Theorem', 'Rational zeros of f(x) must have the form p/q where p divides the constant term and q divides the leading coefficient. Provides a finite list of candidates to test.', 'The Rational Root Theorem lists CANDIDATES — not all candidates are actual zeros. You must test each one.', 'List rational zero candidates; use synthetic division to confirm zeros; factor completely.')],
               [('sign chart', 'Table or number line showing where a function/expression is positive or negative'),
                ('Remainder Theorem', 'f(a) equals the remainder when f(x) is divided by (x−a)'),
                ('Factor Theorem', '(x−a) is a factor of f(x) if and only if f(a) = 0'),
                ('synthetic division', 'Shorthand method for dividing a polynomial by a linear factor (x−a)'),
                ('Rational Root Theorem', 'Rational zeros have form p/q: p|constant term, q|leading coefficient')],
               ['Solve polynomial inequalities using sign charts and interval notation.',
                'Apply the Remainder and Factor Theorems to evaluate and factor polynomials.',
                'Use the Rational Root Theorem to find possible rational zeros.'],
               ['FRQ: find all zeros of a cubic using Rational Root Theorem and synthetic division.',
                'MCQ: apply the Remainder Theorem to find f(a) without dividing.',
                'FRQ: solve a polynomial inequality and write the solution set.'],
               ['Practice synthetic division on several examples.',
                'Solve (x−1)(x+2)(x−3) ≥ 0 using a sign chart.'],
               [('Solve x² − 5x + 6 > 0.', ['Factor: (x−2)(x−3) > 0', 'Zeros at x=2 and x=3; sign chart: +|−|+ on (−∞,2), (2,3), (3,∞)', '> 0 on (−∞,2) ∪ (3,∞)', 'Endpoints excluded (strict inequality)']),
                ('Use the Remainder Theorem to find f(3) for f(x) = x³ − 4x + 1.', ['Divide f(x) by (x−3) — remainder = f(3)', 'f(3) = 27 − 12 + 1 = 16', 'Remainder Theorem: easier than synthetic division here', 'Alternatively: synthetic division gives remainder 16']),
                ('List the rational zero candidates for f(x) = 2x³ − 3x + 6.', ['p: factors of 6: ±1, ±2, ±3, ±6', 'q: factors of 2: ±1, ±2', 'p/q: ±1, ±2, ±3, ±6, ±1/2, ±3/2', 'Total 12 candidates; test each with synthetic division or substitution']),
                ('If f(2) = 0, what can you conclude about (x−2)?', ['Factor Theorem: since f(2) = 0, (x−2) is a factor of f(x)', 'Can use synthetic division with r=2 to find the other factor', 'Write f(x) = (x−2)·q(x) where q(x) is the quotient', 'Repeat to factor q(x) if needed']),
                ('Solve (x+1)/(x−3) ≤ 0.', ['Critical values: x = −1 (numerator zero) and x = 3 (denominator zero)', 'Sign chart: −|+|− on (−∞,−1), (−1,3), (3,∞)', '≤ 0 on (−∞,−1] ∪ [−1,3) ... wait: (−∞,−1] ∪ x=−1 included, x=3 excluded', 'Solution: [−1, 3) — include x=−1 (numerator zero), exclude x=3 (denominator zero)'])],
               [('Polynomial Inequalities', 'Sign charts and interval notation', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Remainder Theorem', 'Remainder and Factor Theorems', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Sign chart: find zeros → test intervals → identify satisfying regions.',
                'Remainder Theorem: f(a) = remainder when divided by (x−a).',
                'Rational Root candidates: p/q where p|constant, q|leading coeff.']),

            _l('Complex Numbers and Polynomial Completeness',
               [_t('Complex Numbers', 'i = √(−1); i² = −1. Complex number: a + bi. Add/subtract: combine real and imaginary parts. Multiply: FOIL then replace i² with −1. Conjugate of a+bi is a−bi. Divide by multiplying numerator and denominator by the conjugate.', 'i² = −1, not 1. This is the defining property and is used every time you multiply complex numbers.', 'Perform arithmetic on complex numbers; find conjugates; divide complex numbers.'),
                _t('Complex Zeros and Conjugate Pairs', 'Fundamental Theorem of Algebra: a degree-n polynomial has exactly n zeros (in ℂ, counting multiplicity). Complex zeros of real polynomials always come in conjugate pairs: if a+bi is a zero, so is a−bi.', 'A real polynomial of odd degree must have at least one real zero — complex zeros come in pairs, so an odd total requires at least one real.', 'Find a polynomial with given complex zeros; apply conjugate pair theorem; count zeros.'),
                _t('Writing Polynomials from Zeros', 'Given zeros (real and complex), construct the polynomial: multiply the factors (x − zero) for each zero. For complex conjugate pairs: (x−(a+bi))(x−(a−bi)) = x² − 2ax + (a²+b²), a quadratic with real coefficients.', 'Each complex zero contributes a quadratic factor (not two separate complex linear factors) when writing a real-coefficient polynomial.', 'Construct a polynomial with specified real and complex zeros; verify by expanding.')],
               [('imaginary unit i', 'i = √(−1); i² = −1; foundation of complex number system'),
                ('complex number', 'Number of the form a + bi where a (real part) and b (imaginary part) are real'),
                ('complex conjugate', 'Conjugate of a+bi is a−bi; product (a+bi)(a−bi) = a²+b² (real)'),
                ('Fundamental Theorem of Algebra', 'Every degree-n polynomial has exactly n zeros in ℂ counting multiplicity'),
                ('conjugate pair theorem', 'Complex zeros of real-coefficient polynomials come in conjugate pairs')],
               ['Perform arithmetic with complex numbers.',
                'Apply the conjugate pair theorem to find all zeros of a real polynomial.',
                'Write a polynomial with specified real and complex zeros.'],
               ['FRQ: given some zeros (including complex), find all zeros and write the polynomial.',
                'MCQ: identify a complex arithmetic result.',
                'FRQ: explain why complex zeros come in conjugate pairs for real polynomials.'],
               ['Practice dividing complex numbers using conjugates.',
                'Find all zeros of x⁴ − x² − 12, including complex ones if they exist.'],
               [('Simplify (3+2i)(1−4i).', ['FOIL: 3(1) + 3(−4i) + 2i(1) + 2i(−4i)', '= 3 − 12i + 2i − 8i²', '= 3 − 10i − 8(−1)', '= 11 − 10i']),
                ('Divide (4+2i)/(1+i).', ['Multiply by conjugate (1−i)/(1−i)', 'Numerator: (4+2i)(1−i) = 4−4i+2i−2i² = 4−2i+2 = 6−2i', 'Denominator: (1+i)(1−i) = 1−i² = 1+1 = 2', 'Result: (6−2i)/2 = 3−i']),
                ('A degree-4 polynomial with real coefficients has zeros 2+3i and 1. Find all zeros.', ['2+3i is a zero → conjugate 2−3i is also a zero (conjugate pair theorem)', '1 is a real zero; total so far: 3 zeros', 'Degree 4 needs 4 zeros → one more real zero', 'Need another real zero; if polynomial is given, find it by dividing out known factors']),
                ('Write a polynomial with zeros 1, −2, and 3i.', ['3i is a zero → −3i is also a zero', 'Factors: (x−1)(x+2)(x−3i)(x+3i)', '(x−3i)(x+3i) = x² + 9', 'Polynomial: (x−1)(x+2)(x²+9) — expand for standard form']),
                ('What does the Fundamental Theorem of Algebra guarantee?', ['Every non-constant polynomial with complex coefficients has at least one complex zero', 'A degree-n polynomial has exactly n zeros in ℂ counting multiplicity', 'Guarantees existence of zeros — does not provide a formula for finding them', 'Degree 4 → exactly 4 zeros (may be real, complex, or repeated'])],
               [('Complex Numbers AP® Precalc', 'Complex arithmetic and polynomial zeros', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Complex Numbers', 'Imaginary and complex arithmetic', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['i² = −1; conjugate of a+bi is a−bi.',
                'Real polynomial: complex zeros come in conjugate pairs.',
                'Fundamental Theorem: degree-n polynomial has exactly n zeros in ℂ.'])
        ],
        'unit_qs': [
            ('State the end behavior of g(x) = 4x⁶ − 7x³ + 1.', ['Leading term: 4x⁶ (even degree, positive leading coefficient)', 'As x→+∞: g(x)→+∞; as x→−∞: g(x)→+∞', 'Even degree, positive LC: both ends up (↑↑)', 'Intercepts and internal behavior do not affect end behavior']),
            ('Find all asymptotes of f(x) = (3x²)/(x²−4).', ['Factor denominator: (x−2)(x+2); numerator: 3x²', 'VA: x = 2 and x = −2 (denominator zeros, no cancellation)', 'HA: degrees equal → y = 3/1 = 3', 'No holes (no common factors)']),
            ('Find the ARC of f(x) = 2x² − 3x on [0, 4].', ['f(0) = 0; f(4) = 32−12 = 20', 'ARC = (20−0)/(4−0) = 20/4 = 5', 'The function increases an average of 5 units per unit x on [0,4]', 'Secant line slope from (0,0) to (4,20) is 5']),
            ('Solve x² − x − 6 ≤ 0 using a sign chart.', ['Factor: (x−3)(x+2) ≤ 0', 'Zeros: x = 3 and x = −2', 'Sign chart: + on (−∞,−2), − on (−2,3), + on (3,∞)', 'Solution: [−2, 3] (include endpoints for ≤)']),
            ('What does f(5) tell you if found by the Remainder Theorem?', ['f(5) = remainder when f(x) is divided by (x−5)', 'If f(5) = 0, then (x−5) is a factor of f(x)', 'Easier than substituting large values for complex polynomials', 'Apply: compute f(5) directly rather than doing long/synthetic division']),
            ('Simplify (2+5i) − (3−4i).', ['Real parts: 2−3 = −1', 'Imaginary parts: 5i−(−4i) = 9i', 'Result: −1 + 9i', 'Treat i as a variable and combine like terms']),
            ('f(x) = x⁴ − 1. Find all zeros including complex ones.', ['Factor: (x²−1)(x²+1) = (x−1)(x+1)(x−i)(x+i)', 'Real zeros: x = 1 and x = −1', 'Complex zeros: x = i and x = −i (conjugate pair)', 'Total: 4 zeros matching degree 4']),
            ('Identify the hole in f(x) = (x²−9)/(x−3).', ['Numerator: (x−3)(x+3); denominator: (x−3)', 'Common factor (x−3) cancels → hole at x = 3', 'Simplified: f(x) = x+3 (for x ≠ 3)', 'Hole at (3, 6): substitute x=3 into simplified form']),
            ('A degree-6 polynomial with real coefficients has zeros 1+2i, 3 (double), and −1. How many more zeros are needed?', ['1+2i → conjugate 1−2i also a zero (2 complex zeros)', '3 (double) → counts as 2 zeros', '−1 → 1 zero', 'Total so far: 5 zeros; need 1 more (real, since complex come in pairs)']),
            ('List rational zero candidates for f(x) = 3x³ + x² − 4.', ['Constant term: −4; factors: ±1, ±2, ±4', 'Leading coefficient: 3; factors: ±1, ±3', 'Candidates p/q: ±1, ±2, ±4, ±1/3, ±2/3, ±4/3', 'Test each; f(1) = 3+1−4 = 0 → x=1 is a zero'])
        ]
    },
    {
        'num': 2,
        'title': 'Exponential and Logarithmic Functions',
        'file': 'ap-precalculus-2-unit-2-exponential-and-logarithmic-functions.html',
        'desc': 'Properties of exponential growth and decay, logarithm laws, and solving exponential and log equations.',
        'gateway': [
            'How do exponential functions differ from polynomial growth?',
            'What is the inverse relationship between exponential and logarithmic functions?',
            'How do you solve exponential equations using logarithms?',
            'What are the key properties of logarithms used to simplify expressions?',
        ],
        'lessons': [
            _l('Exponential Functions',
               [_t('Exponential Growth and Decay', 'f(x) = ab^x: base b > 1 → growth; 0 < b < 1 → decay. The base determines the constant multiplicative factor per unit increase in x. Continuous: f(x) = ae^(rx); r > 0 growth, r < 0 decay.', 'Exponential growth is NOT linear — doubling is a multiplicative relationship, not additive. 2ˣ grows much faster than x².', 'Identify growth vs decay from the base; calculate values and interpret percent change.'),
                _t('Properties of Exponential Functions', 'Domain: all reals; Range: (0,∞) for a>0. y-intercept: (0, a). No x-intercepts (always positive). Horizontal asymptote y=0. Transformations apply as usual (shifts, stretches).', 'The horizontal asymptote of a basic exponential is y=0, not an x-intercept. The graph gets very close but never reaches zero.', 'State domain, range, asymptote, and intercepts; apply transformations to exponential functions.'),
                _t('Compound and Continuous Interest', 'Compound: A = P(1+r/n)^(nt). Continuous: A = Pe^(rt). More frequent compounding → higher effective rate. Effective annual rate (EAR) = (1+r/n)^n − 1.', 'Continuous compounding does not give infinite money — it gives a slightly higher amount than annual compounding, approaching the limit e^r per dollar per year.', 'Apply compound and continuous interest formulas; compare effective annual rates.')],
               [('exponential function', 'f(x) = ab^x; base b > 1 → growth; 0 < b < 1 → decay; constant % change per unit x'),
                ('base e', 'Euler\'s number ≈ 2.718; base of natural exponential; continuous growth model'),
                ('horizontal asymptote', 'y = 0 for basic exponential; graph approaches but never reaches 0'),
                ('compound interest', 'A = P(1+r/n)^(nt); interest computed n times per year'),
                ('continuous growth', 'A = Pe^(rt); limiting case of compound interest as n→∞')],
               ['Identify exponential growth vs decay and state their properties.',
                'Apply compound and continuous interest formulas.',
                'Describe transformations of exponential functions.'],
               ['FRQ: model exponential growth/decay from a table or description.',
                'MCQ: identify the correct exponential model for a described situation.',
                'FRQ: compare compound vs continuous interest.'],
               ['Graph f(x) = 2ˣ and g(x) = (1/2)ˣ on the same axes and compare.',
                'Compare daily vs continuous compounding for a 5-year investment.'],
               [('Does f(x) = 3(0.6)ˣ represent growth or decay? What is the rate?', ['b = 0.6; 0 < 0.6 < 1 → exponential decay', 'Each unit increase in x multiplies f by 0.6', 'Decay rate: 1 − 0.6 = 0.4 or 40% decrease per unit x', 'Initial value: f(0) = 3']),
                ('Find the y-intercept and asymptote of f(x) = 2·(1.5)ˣ − 4.', ['y-intercept: x=0 → f(0) = 2·1 − 4 = −2; point (0, −2)', 'Asymptote: y = −4 (vertical shift down 4 from y=0)', 'Range: (−4, ∞)', 'Transformed exponential: parent y=0 shifted down 4']),
                ('$1000 invested at 6% compounded monthly for 3 years: find A.', ['A = P(1+r/n)^(nt) = 1000(1+0.06/12)^(12×3)', '= 1000(1.005)^36', '= 1000 × 1.1967 ≈ $1196.68', 'Monthly compounding: n=12']),
                ('Why does e appear in continuous growth models?', ['e = lim(n→∞)(1+1/n)^n ≈ 2.71828', 'As compounding becomes more frequent: A = Pe^(rt)', 'e is the natural base for continuous processes', 'Appears naturally in many growth/decay phenomena in science']),
                ('Compare ARC of f(x)=2ˣ on [0,1] vs [2,3].', ['f(0)=1, f(1)=2: ARC = (2−1)/1 = 1', 'f(2)=4, f(3)=8: ARC = (8−4)/1 = 4', 'ARC increases → exponential growth is accelerating', 'This increasing ARC distinguishes exponential from linear'])],
               [('Exponential Functions AP® Precalc', 'Growth, decay, and interest formulas', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Exponential', 'Exponential functions and applications', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['f(x) = ab^x: b>1 growth; 0<b<1 decay; HA y=0.',
                'Compound: A = P(1+r/n)^(nt); Continuous: A = Pe^(rt).',
                'Exponential ARC increases over time — distinguishes it from linear.']),

            _l('Logarithmic Functions',
               [_t('Logarithm Definition', 'log_b(x) = y means b^y = x. Natural log: ln(x) = log_e(x). Common log: log(x) = log_10(x). Inverse of b^x. Key values: log_b(1) = 0; log_b(b) = 1; log_b(b^x) = x; b^(log_b x) = x.', 'The argument of a logarithm must be positive — log(negative) is undefined. This restricts the domain of log functions.', 'Convert between exponential and logarithmic forms; evaluate logs at key values.'),
                _t('Properties of Logarithms', 'Product: log(AB) = log A + log B. Quotient: log(A/B) = log A − log B. Power: log(A^p) = p·log A. Change of base: log_b(x) = log(x)/log(b). These properties are used to expand or condense log expressions.', 'These properties require the same base — you cannot mix log_2 and log_5 without converting. Also log(A+B) ≠ log A + log B.', 'Expand and condense logarithmic expressions using product, quotient, and power rules.'),
                _t('Graphs of Logarithmic Functions', 'y = log_b(x): domain (0,∞); range (−∞,∞); x-intercept (1,0); VA x=0. Transformations shift the domain. The log function is the reflection of b^x over y=x.', 'log_b(x) has a vertical asymptote at x=0, not at y=0. The graph approaches x=0 but extends infinitely in y.', 'State domain, range, intercepts, and asymptote; sketch y = log_b(x) and transformations.')],
               [('logarithm', 'log_b(x) = y means b^y = x; exponent needed to get x from base b'),
                ('natural logarithm ln', 'log_e(x); inverse of e^x; ln(e^x) = x; e^(ln x) = x'),
                ('common logarithm log', 'log_10(x); often written log without base; log(10^x) = x'),
                ('change of base formula', 'log_b(x) = log(x)/log(b) or ln(x)/ln(b); converts any base to a calculable form'),
                ('domain of log', '(0, ∞); argument must be strictly positive')],
               ['Convert between exponential and logarithmic forms.',
                'Apply product, quotient, and power rules of logarithms.',
                'State the domain, range, intercepts, and asymptote of logarithmic functions.'],
               ['FRQ: expand or condense a complex logarithmic expression.',
                'MCQ: evaluate a logarithm or identify a domain restriction.',
                'FRQ: apply change of base to evaluate log_5(30) on a calculator.'],
               ['Expand log₂(8x³/y²) fully using log properties.',
                'Evaluate log₃(81) and log₂(1/8) without a calculator.'],
               [('Evaluate log₂(32).', ['log₂(32) = y means 2^y = 32', '2⁵ = 32 → y = 5', 'log₂(32) = 5', 'Alternatively: log₂(2⁵) = 5 using log_b(b^x) = x']),
                ('Expand: log(√(x³y)/z²).', ['Rewrite √(x³y) = (x³y)^(1/2)', 'log((x³y)^(1/2)/z²) = (1/2)log(x³y) − log(z²)', '= (1/2)[log(x³)+log(y)] − 2log(z)', '= (3/2)log(x) + (1/2)log(y) − 2log(z)']),
                ('What is the domain of f(x) = log(2x − 6)?', ['Argument must be positive: 2x − 6 > 0', '2x > 6 → x > 3', 'Domain: (3, ∞)', 'VA at x = 3']),
                ('Use change of base to evaluate log₇(100).', ['log₇(100) = log(100)/log(7)', '= 2/log(7)', '≈ 2/0.8451 ≈ 2.366', 'Check: 7^2.366 ≈ 100 ✓']),
                ('Why is log(A+B) ≠ log A + log B?', ['Product rule: log(A×B) = log A + log B', 'Sum inside logarithm does not simplify', 'Common error: students treat log like a linear function', 'Example: log(10+90) = log(100) = 2; but log(10)+log(90) ≈ 1+1.95 = 2.95 ≠ 2'])],
               [('Logarithms AP® Precalc', 'Properties, graphs, and change of base', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Logarithms', 'Logarithm properties and graphs', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['log_b(x)=y means b^y=x; domain (0,∞), VA x=0.',
                'Product/Quotient/Power rules: log(AB)=logA+logB; etc.',
                'log(A+B) ≠ log A + log B — a very common error.']),

            _l('Solving Exponential and Logarithmic Equations',
               [_t('Solving Exponential Equations', 'Strategy: make bases equal (if possible) or take logarithm of both sides. ln(b^x) = x·ln(b). Solve for x by dividing by ln(b). Check for extraneous solutions.', 'Taking log of both sides is always valid when both sides are positive. If one side could be negative (due to transformation), check the domain first.', 'Solve exponential equations by equating bases or applying logarithms; verify solutions.'),
                _t('Solving Logarithmic Equations', 'Isolate the log, then convert to exponential form. If multiple logs, condense using properties first. Always check: argument of log must be positive after solving.', 'Extraneous solutions arise when the derived x value makes a log argument non-positive. Always substitute back to verify.', 'Solve logarithmic equations; identify and reject extraneous solutions.'),
                _t('Exponential and Log Models', 'Exponential models: population P(t) = P₀e^(rt), half-life: t₁/₂ = ln(2)/k, doubling time: t_d = ln(2)/r. Solve for unknowns by taking ln. Log models: sound level (decibels), pH = −log[H⁺].', 'Half-life and doubling time are different values from the rate constant k — compute them separately using ln(2)/k.', 'Set up and solve exponential/log models; find doubling time, half-life, or rate from data.')],
               [('one-to-one property', 'b^a = b^c implies a = c; log_b(a) = log_b(c) implies a = c; used to solve equations'),
                ('extraneous solution', 'A solution derived algebraically that does not satisfy the original equation'),
                ('doubling time', 'Time for a quantity to double: t_d = ln(2)/r'),
                ('half-life', 'Time for a quantity to halve: t_{1/2} = ln(2)/k'),
                ('pH', 'pH = −log₁₀[H⁺]; logarithmic scale for acidity; decreases by 1 for every 10× increase in [H⁺]')],
               ['Solve exponential equations using logarithms.',
                'Solve logarithmic equations and check for extraneous solutions.',
                'Apply exponential/log models to real-world problems.'],
               ['FRQ: solve for unknown in an exponential growth model.',
                'MCQ: identify an extraneous solution in a log equation.',
                'FRQ: find doubling time or half-life from a growth/decay model.'],
               ['Solve 3^(x+1) = 50 using natural log; check with a calculator.',
                'Find the half-life of a substance decaying at 8% per year.'],
               [('Solve 5^x = 120.', ['Take ln of both sides: ln(5^x) = ln(120)', 'x·ln(5) = ln(120)', 'x = ln(120)/ln(5) = 4.787/1.609 ≈ 2.975', 'Check: 5^2.975 ≈ 120 ✓']),
                ('Solve log₂(x) + log₂(x−2) = 3.', ['Condense: log₂(x(x−2)) = 3', 'x(x−2) = 2³ = 8', 'x²−2x−8 = 0 → (x−4)(x+2) = 0', 'x = 4 or x = −2; check: log₂(−2) undefined → reject x=−2; solution: x=4']),
                ('A population doubles every 12 years. Find the annual growth rate r.', ['Doubling time: 12 = ln(2)/r', 'r = ln(2)/12 ≈ 0.0578 or 5.78% per year', 'Model: P(t) = P₀·e^(0.0578t)', 'Verify: P(12)/P(0) = e^(0.0578×12) = e^(0.693) ≈ 2 ✓']),
                ('If [H⁺] = 10⁻⁴, find pH.', ['pH = −log₁₀[H⁺] = −log₁₀(10⁻⁴)', '= −(−4) = 4', 'This is an acidic solution (pH < 7)', 'Each unit decrease in pH = 10× increase in [H⁺]']),
                ('Solve for x: e^(2x) − 3e^x + 2 = 0.', ['Substitution: u = e^x → u² − 3u + 2 = 0', '(u−1)(u−2) = 0 → u=1 or u=2', 'e^x = 1 → x=0; e^x = 2 → x = ln(2)', 'Both solutions valid; x=0 or x=ln(2)'])],
               [('Exponential Equations AP® Precalc', 'Solving using logarithms', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Log Equations', 'Solving log and exponential equations', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Take ln of both sides for exponential equations: x = ln(A)/ln(b).',
                'Check log equation solutions — extraneous if argument ≤ 0.',
                'Doubling time = ln(2)/r; half-life = ln(2)/k.']),

            _l('Regression and Modeling with Functions',
               [_t('Choosing a Model', 'Select the best function type by analyzing the data. Linear: constant first differences. Quadratic: constant second differences. Exponential: constant ratios. Logarithmic: rapid then slowing growth. Evaluate fit with r² (coefficient of determination).', 'A high r² does not guarantee the model is correct — it only measures linear correlation. Always check a residual plot and whether the model makes contextual sense.', 'Determine the appropriate regression model from a data table; interpret r² and residuals.'),
                _t('Exponential Regression', 'Use data to find y = ab^x. Linearize by taking log: log(y) = log(a) + x·log(b). On a calculator: ExpReg or enter log(y) values for linear regression then convert. Extrapolation beyond data range is unreliable.', 'Extrapolating an exponential model far beyond the data range produces unreliable predictions — exponential growth does not continue indefinitely in the real world.', 'Perform or interpret exponential regression; extrapolate with appropriate caution.'),
                _t('Piecewise and Composition of Functions', 'Piecewise functions use different rules for different domain pieces. Function composition: (f∘g)(x) = f(g(x)). Order matters: f∘g ≠ g∘f in general. Domain of f∘g: valid inputs for g that produce outputs in domain of f.', 'Composition order: f∘g means apply g first, then f. Many students reverse the order.', 'Evaluate and graph piecewise functions; compute and interpret function compositions.')],
               [('residuals', 'Differences between observed data and predicted model values; should show no pattern'),
                ('r² (coefficient of determination)', 'Measures proportion of variance explained by model; 1 = perfect fit; 0 = no fit'),
                ('exponential regression', 'Finding ab^x that best fits data; linearized by taking log'),
                ('piecewise function', 'Function defined by different rules on different intervals of the domain'),
                ('function composition', '(f∘g)(x) = f(g(x)): apply g first, then apply f to the result')],
               ['Choose the appropriate function type to model a dataset.',
                'Interpret r² and residual plots for model quality.',
                'Evaluate function compositions and piecewise functions.'],
               ['FRQ: given a table of values, determine the best model type and justify.',
                'MCQ: identify whether a dataset is better fit by linear or exponential regression.',
                'FRQ: compute f(g(x)) for given functions.'],
               ['Use a graphing calculator to find exponential regression for a dataset.',
                'Evaluate and graph a piecewise function with three pieces.'],
               [('A data table has consecutive ratios: 3, 3, 3, 3. What model fits?', ['Constant ratios → exponential model y = ab^x', 'Ratio of 3 → base b = 3', 'Find a from the initial value', 'Constant first differences → linear; second differences → quadratic; ratios → exponential']),
                ('f(x) = 2x+1 and g(x) = x². Find f(g(3)).', ['g(3) = 3² = 9', 'f(g(3)) = f(9) = 2(9)+1 = 19', 'Apply g first, then f', 'f∘g at x=3 = f(g(3)) = 19']),
                ('f(x) = {2x if x<0; x² if x≥0}. Evaluate f(−3) and f(4).', ['f(−3): use 2x (x<0): 2(−3) = −6', 'f(4): use x² (x≥0): 4² = 16', 'At boundary x=0: f(0) = 0² = 0', 'Piecewise: check which interval the input falls in']),
                ('What does r² = 0.92 mean for a regression model?', ['92% of the variation in y is explained by the model', 'Strong fit but not perfect', 'Look at residuals: are they random or patterned?', 'A patterned residual plot suggests wrong model even with high r²']),
                ('Why is extrapolation beyond the data range unreliable for exponential models?', ['Exponential growth assumes constant percent change, which rarely holds indefinitely', 'Small changes in b compound dramatically over long time periods', 'Real systems have limits: resources, space, competition', 'Model is valid only near the data range; extrapolation grows uncertain quickly'])],
               [('Regression and Modeling', 'Choosing and interpreting regression models', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Modeling', 'Choosing and using function models', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Constant ratios → exponential; constant differences → linear/quadratic.',
                'r² measures fit; check residuals for pattern.',
                'Composition: f∘g = apply g first, then f; order matters.'])
        ],
        'unit_qs': [
            ('Does f(x) = 5(0.8)ˣ represent growth or decay? What is the percent change per unit x?', ['b = 0.8; 0 < 0.8 < 1 → exponential decay', 'Each unit increase in x multiplies by 0.8', 'Percent decrease: 1 − 0.8 = 0.2 = 20% decrease per unit', 'Starting value: f(0) = 5']),
            ('Convert: log₃(81) = 4 to exponential form.', ['log_b(x) = y ↔ b^y = x', '3⁴ = 81', 'Verify: 3⁴ = 3×3×3×3 = 81 ✓', 'This is the definition of logarithm']),
            ('Expand: ln(x²√y/z³).', ['ln(x²√y/z³) = ln(x²) + ln(y^(1/2)) − ln(z³)', '= 2ln(x) + (1/2)ln(y) − 3ln(z)', 'Used product, quotient, and power rules', 'All terms must have positive arguments']),
            ('Solve: 2^(3x) = 64.', ['64 = 2⁶ → same base', '3x = 6 → x = 2', 'Or: ln(2^(3x)) = ln(64) → 3x·ln2 = ln64 = 6ln2 → x=2', 'Check: 2^6 = 64 ✓']),
            ('Solve: log(x) + log(x+21) = 2.', ['Condense: log(x(x+21)) = 2', 'x(x+21) = 10² = 100', 'x²+21x−100=0 → (x+25)(x−4)=0', 'x=4 or x=−25; check: log(−25) undefined → solution: x=4']),
            ('$5000 invested at 4% continuously compounded for 10 years. Find A.', ['A = Pe^(rt) = 5000·e^(0.04×10)', '= 5000·e^0.4', '≈ 5000 × 1.4918 ≈ $7459', 'Compare to annual compounding: 5000(1.04)^10 ≈ $7401']),
            ('A radioactive substance has half-life of 25 years. What is the decay rate k?', ['Half-life: 25 = ln(2)/k', 'k = ln(2)/25 ≈ 0.0277 or 2.77% per year', 'Model: A(t) = A₀e^(−0.0277t)', 'Verify: A(25)/A(0) = e^(−0.0277×25) = e^(−0.693) ≈ 0.5 ✓']),
            ('f(x) = 3x−2 and g(x) = x²+1. Find g(f(x)) and f(g(x)).', ['g(f(x)) = g(3x−2) = (3x−2)²+1 = 9x²−12x+5', 'f(g(x)) = f(x²+1) = 3(x²+1)−2 = 3x²+1', 'These are different — composition is not commutative', 'Always apply the inner function first']),
            ('Data has constant ratios of 2. Which model fits, and what is the base?', ['Constant ratios → exponential model y = ab^x', 'Ratio of 2 → base b = 2', 'Form: y = a·2^x where a is the initial value', 'Check: first differences would not be constant for exponential']),
            ('Why must you check solutions to log equations for extraneous values?', ['Log is only defined for positive arguments', 'Algebraic manipulation can produce solutions that make log arguments negative or zero', 'Example: solution x=−5 rejected if log(x+5) appears (x+5 would be 0)', 'Always substitute back and verify all log arguments are positive'])
        ]
    },
    {
        'num': 3,
        'title': 'Trigonometric and Polar Functions',
        'file': 'ap-precalculus-3-unit-3-trigonometric-and-polar-functions.html',
        'desc': 'The unit circle, trigonometric functions, identities, inverse trig, and polar coordinates.',
        'gateway': [
            'How are sine and cosine defined using the unit circle?',
            'What are the key properties of sinusoidal functions (amplitude, period, phase shift)?',
            'How do you use trigonometric identities to simplify expressions?',
            'What is the relationship between polar and Cartesian coordinates?',
        ],
        'lessons': [
            _l('The Unit Circle and Trig Functions',
               [_t('Unit Circle Definition', 'Unit circle: radius 1 centered at origin. For angle θ (in radians), the point on the unit circle is (cos θ, sin θ). Key angles: 0, π/6, π/4, π/3, π/2 and their reflections in all four quadrants.', 'Sine is the y-coordinate and cosine is the x-coordinate on the unit circle — NOT the other way around.', 'Find exact values of sin and cos for special angles; determine quadrant signs.'),
                _t('Trig Functions and Their Properties', 'sin θ: odd function (range [−1,1]); cos θ: even function (range [−1,1]); tan θ = sin/cos (range all reals, undefined where cos=0). Period of sin and cos: 2π; period of tan: π.', 'Tangent is undefined at θ = π/2 + nπ (where cosine is zero) — not at θ = nπ.', 'State domain, range, period, and key properties of sin, cos, and tan.'),
                _t('Radians vs Degrees', 'Radian measure: angle whose arc length equals radius. π radians = 180°. Convert: radians = degrees × (π/180); degrees = radians × (180/π). AP® Precalculus works primarily in radians.', 'Calculators must be in RADIAN mode for AP® Precalculus. Forgetting to switch is a common error.', 'Convert between radians and degrees; evaluate trig functions in radian measure.')],
               [('unit circle', 'Circle of radius 1 centered at origin; point at angle θ is (cosθ, sinθ)'),
                ('radian', 'Angle measure equal to arc length / radius; 2π radians = 360°'),
                ('sin θ', 'y-coordinate on unit circle at angle θ; range [−1,1]; period 2π; odd function'),
                ('cos θ', 'x-coordinate on unit circle at angle θ; range [−1,1]; period 2π; even function'),
                ('tan θ', 'sin θ / cos θ; range (−∞,∞); period π; undefined where cos θ = 0')],
               ['State exact values of sin, cos, and tan at special angles.',
                'Convert between radians and degrees.',
                'State domain, range, and period of each trig function.'],
               ['MCQ: evaluate sin(5π/6) or cos(7π/4) using the unit circle.',
                'FRQ: find the exact value and explain using the unit circle.',
                'MCQ: identify the quadrant of an angle given its trig signs.'],
               ['Memorize or derive the unit circle values for all special angles.',
                'Convert 210° and 3π/4 between degrees and radians.'],
               [('What is the exact value of sin(5π/6)?', ['5π/6 is in the second quadrant (π/2 to π)', 'Reference angle: π − 5π/6 = π/6', 'sin(π/6) = 1/2; sin is positive in Q2', 'sin(5π/6) = 1/2']),
                ('Convert 135° to radians.', ['Multiply by π/180: 135 × π/180 = 3π/4', '135° = 3π/4 radians', 'Check: 180° = π, so 90° = π/2, 135° is halfway between → 3π/4']),
                ('What is tan(π)?', ['tan(π) = sin(π)/cos(π) = 0/(−1) = 0', 'Point on unit circle at π: (−1, 0)', 'x = −1 (cos), y = 0 (sin)', 'tan(π) = 0/(-1) = 0']),
                ('In which quadrants is sin θ negative?', ['sin θ = y-coordinate on unit circle', 'y is negative in quadrants III and IV', 'Q3: both sin and cos negative; Q4: sin negative, cos positive', 'Mnemonic ASTC: All, Sin, Tan, Cos positive in Q1,Q2,Q3,Q4']),
                ('Why is tan undefined at π/2?', ['tan(π/2) = sin(π/2)/cos(π/2) = 1/0', 'Division by zero is undefined', 'Graph of tan has vertical asymptote at x = π/2', 'Undefined at all x = π/2 + nπ'])],
               [('Unit Circle AP® Precalc', 'Trig definitions and special angles', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Unit Circle', 'Unit circle and radian measure', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Unit circle: (cosθ, sinθ); sinθ is y, cosθ is x.',
                'Period: sin, cos = 2π; tan = π.',
                'ASTC: All positive Q1; Sin positive Q2; Tan positive Q3; Cos positive Q4.']),

            _l('Graphing Sinusoidal Functions',
               [_t('Amplitude and Period', 'f(x) = A sin(Bx + C) + D. |A| = amplitude (half the vertical range). Period = 2π/|B|. Midline: y = D. Phase shift: −C/B (horizontal shift). AP® Precalculus tests all four parameters.', 'Amplitude is |A|, not A — it is always positive. A = −3 gives amplitude 3, not −3.', 'Determine amplitude, period, midline, and phase shift from an equation or graph.'),
                _t('Phase Shift and Vertical Shift', 'Phase shift = −C/B shifts the graph horizontally. Vertical shift D moves the midline. Transformations combine: sketch the parent sin/cos, then apply shifts and stretches.', 'Phase shift is −C/B, not C. For sin(2x−π), B=2, C=−π: phase shift = −(−π)/2 = π/2 (right).', 'Determine the phase shift from f(x) = A sin(Bx + C) + D; sketch the transformed graph.'),
                _t('Modeling with Sinusoidal Functions', 'Real-world periodic phenomena (tides, temperature, sound) modeled by A sin(Bx+C)+D. Given max, min, and period: A = (max−min)/2; D = (max+min)/2; B = 2π/period.', 'The midline (D) is not the minimum — it is the average of max and min.', 'Build a sinusoidal model from given real-world data; interpret amplitude and period in context.')],
               [('amplitude', '|A| in A sin(Bx+C)+D; half the vertical range (max−min)/2; always positive'),
                ('period', '2π/|B|; horizontal length of one complete cycle'),
                ('phase shift', '−C/B; horizontal translation; positive → right, negative → left'),
                ('midline', 'y = D; horizontal line equidistant from max and min; vertical shift of parent'),
                ('sinusoidal function', 'Function of the form A sin(Bx+C)+D or A cos(Bx+C)+D')],
               ['Identify amplitude, period, phase shift, and midline from an equation.',
                'Write a sinusoidal equation from given graph features.',
                'Build a sinusoidal model from real-world max/min/period data.'],
               ['FRQ: find all parameters from a graph and write the equation.',
                'MCQ: identify amplitude or period from a given equation.',
                'FRQ: model real-world periodic data with a sinusoidal function.'],
               ['Graph f(x) = 3 sin(2x − π) + 1; label all key features.',
                'Write a cosine model for ocean tides with max 4m, min −2m, period 12 hours.'],
               [('Find amplitude, period, midline, and phase shift of f(x) = 4cos(3x+π/2)−2.', ['A=4: amplitude = 4', 'B=3: period = 2π/3', 'D=−2: midline y=−2', 'Phase shift: −(π/2)/3 = −π/6 (left π/6)']),
                ('Write a sine equation with amplitude 3, period π, no phase shift, midline y=1.', ['A=3; B=2π/period=2π/π=2; C=0; D=1', 'f(x) = 3 sin(2x) + 1', 'Check: amplitude 3, period 2π/2=π, midline y=1 ✓']),
                ('Temperature: max 85°F (t=3 months), min 45°F (t=9 months). Write a model.', ['A = (85−45)/2 = 20; D = (85+45)/2 = 65', 'Period = 12 months → B = 2π/12 = π/6', 'Max at t=3: use cosine shifted right 3: f(t)=20cos(π/6·(t−3))+65', 'Or sine with appropriate phase shift']),
                ('What is the amplitude of f(x) = −5 sin(x)?', ['Amplitude = |A| = |−5| = 5', 'The negative flips the graph (reflection over midline)', 'Amplitude is always positive', 'Range of f: [−5, 5] since |A| = 5']),
                ('A sound wave has equation P = 0.02 sin(440πt). Find the frequency in Hz.', ['Period = 2π/(440π) = 2/440 = 1/220 seconds', 'Frequency = 1/period = 220 Hz', 'This is A4, the standard tuning pitch', 'Amplitude 0.02 represents pressure variation (small for sound)'])],
               [('Sinusoidal Graphs AP® Precalc', 'Amplitude, period, phase shift, midline', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Sinusoidal', 'Graphing trig functions with transformations', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['A sin(Bx+C)+D: amplitude=|A|, period=2π/B, phase shift=−C/B, midline=D.',
                'Phase shift = −C/B (not C); positive → right.',
                'Build model: A=(max−min)/2, D=(max+min)/2, B=2π/period.']),

            _l('Trigonometric Identities and Inverse Functions',
               [_t('Fundamental Identities', 'Pythagorean: sin²θ + cos²θ = 1 → also 1+tan²θ = sec²θ; 1+cot²θ = csc²θ. Reciprocal: csc=1/sin, sec=1/cos, cot=1/tan. Quotient: tan=sin/cos. These are verified for all θ where defined.', 'Identities hold for all valid θ (not specific values). An equation true for only some θ is a conditional equation, not an identity.', 'Use fundamental identities to simplify trig expressions and verify identities.'),
                _t('Sum and Difference, Double Angle', 'sin(A±B) = sinA cosB ± cosA sinB. cos(A±B) = cosA cosB ∓ sinA sinB. Double angle: sin(2A)=2sinA cosA; cos(2A)=cos²A−sin²A=1−2sin²A=2cos²A−1.', 'cos(2A) has three equivalent forms — choose the one that makes simplification easiest based on context.', 'Apply sum/difference and double angle identities to simplify or evaluate expressions.'),
                _t('Inverse Trigonometric Functions', 'sin⁻¹(x) (arcsin): range [−π/2, π/2]. cos⁻¹(x) (arccos): range [0, π]. tan⁻¹(x) (arctan): range (−π/2, π/2). These restricted ranges ensure the inverse is a function.', 'sin⁻¹(sin(x)) ≠ x in general — only for x in [−π/2, π/2]. The restricted range matters.', 'Evaluate inverse trig functions; solve trig equations using inverse functions with correct quadrants.')],
               [('Pythagorean identity', 'sin²θ + cos²θ = 1; derived from unit circle definition; three equivalent forms'),
                ('double angle formulas', 'sin(2A)=2sinAcosA; cos(2A)=cos²A−sin²A (three equivalent forms)'),
                ('arcsin (sin⁻¹)', 'Inverse sine; range [−π/2, π/2]; outputs angle whose sine equals the input'),
                ('arccos (cos⁻¹)', 'Inverse cosine; range [0, π]; restricted to make it a function'),
                ('restricted domain', 'Domain limitation applied to trig functions to make their inverses functions')],
               ['Apply the Pythagorean and other fundamental identities.',
                'Use sum/difference and double angle formulas.',
                'Evaluate inverse trig functions and interpret their restricted ranges.'],
               ['FRQ: simplify a trig expression using identities.',
                'MCQ: evaluate sin⁻¹ or cos⁻¹ for a specific value.',
                'FRQ: solve a trig equation over a specified interval.'],
               ['Verify the identity: (1−cos²θ)/sinθ = sinθ.',
                'Solve sin(2x) = cos(x) for x ∈ [0, 2π).'],
               [('Simplify: (1−sin²θ)/cosθ.', ['1−sin²θ = cos²θ (Pythagorean identity)', 'cos²θ/cosθ = cosθ', 'Simplified: cosθ', 'Assuming cosθ ≠ 0']),
                ('Evaluate sin⁻¹(−√2/2).', ['Need angle θ in [−π/2, π/2] where sinθ = −√2/2', 'sin(π/4) = √2/2; sin is negative in Q4 restricted range', 'θ = −π/4', 'sin⁻¹(−√2/2) = −π/4']),
                ('Use double angle formula: find sin(2θ) if sinθ = 3/5 and θ is in Q1.', ['sin(2θ) = 2sinθcosθ', 'cosθ: from sin²+cos²=1: cosθ = √(1−9/25) = 4/5 (positive in Q1)', 'sin(2θ) = 2(3/5)(4/5) = 24/25']),
                ('Solve sinθ = 0.5 for θ ∈ [0, 2π).', ['sin⁻¹(0.5) = π/6', 'sin is positive in Q1 and Q2', 'Solutions: θ = π/6 and θ = π − π/6 = 5π/6', 'These are the only solutions in [0, 2π)']),
                ('Why does arcsin have range [−π/2, π/2] rather than [0, π]?', ['Sine is not one-to-one over its full domain — must restrict to make an inverse', 'The interval [−π/2, π/2] is chosen because sin is strictly increasing there', 'It covers all output values [−1,1] exactly once', 'arccos uses [0,π] because cosine is strictly decreasing there'])],
               [('Trig Identities AP® Precalc', 'Pythagorean, sum/difference, double angle', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Identities', 'Fundamental and double angle identities', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['sin²+cos²=1; 1+tan²=sec²; 1+cot²=csc².',
                'sin(2A)=2sinAcosA; cos(2A)=cos²A−sin²A.',
                'arcsin range [−π/2,π/2]; arccos range [0,π].']),

            _l('Polar Coordinates',
               [_t('Polar Coordinate System', 'Point (r, θ): r is distance from origin (pole), θ is angle from positive x-axis. Convert: x = rcosθ; y = rsinθ; r² = x²+y²; tanθ = y/x. Multiple representations: (r,θ) = (r,θ+2π) = (−r,θ+π).', 'Polar coordinates are NOT unique — the same point has infinitely many representations. This is different from Cartesian coordinates.', 'Convert between polar and Cartesian; identify multiple polar representations of a point.'),
                _t('Polar Equations and Graphs', 'Common polar curves: circle r=a; rose r=cos(nθ); limaçon r=a+bcosθ; cardioid r=1+cosθ (limaçon with a=b). Number of petals in r=cos(nθ): n petals if n odd; 2n petals if n even.', 'The number of petals in a rose curve depends on whether n is odd or even — different formula for each.', 'Sketch common polar curves; identify curve type from a polar equation.'),
                _t('Converting and Analyzing Polar Curves', 'Convert polar to Cartesian by substituting r²=x²+y², rcosθ=x, rsinθ=y. Symmetry tests: if f(θ) = f(−θ), symmetric about polar axis; if f(π−θ)=f(θ), symmetric about θ=π/2.', 'Symmetry tests in polar are sufficient but not necessary — a curve may be symmetric even if the test fails.', 'Convert a polar equation to Cartesian; test and apply polar symmetry.')],
               [('polar coordinates', '(r, θ): r = radial distance, θ = angle from positive x-axis'),
                ('pole', 'Origin (0,0) of the polar coordinate system'),
                ('cardioid', 'Polar curve r = a(1+cosθ) or r = a(1+sinθ); heart-shaped'),
                ('rose curve', 'r = a cos(nθ); n petals if n odd; 2n petals if n even'),
                ('limaçon', 'r = a + b cosθ; shape depends on ratio a/b: loop, cardioid, or dimpled')],
               ['Convert between polar and Cartesian coordinates.',
                'Identify and sketch common polar curves.',
                'Test polar curves for symmetry about the polar axis or θ=π/2.'],
               ['FRQ: convert a polar equation to Cartesian; identify the shape.',
                'MCQ: identify the number of petals in a rose curve.',
                'FRQ: find all polar representations of a given point.'],
               ['Graph r = 2 + 2cosθ (cardioid) by creating a table of (r,θ) values.',
                'Convert r = 4cosθ to Cartesian and identify the shape.'],
               [('Convert (r=3, θ=π/3) to Cartesian coordinates.', ['x = rcosθ = 3cos(π/3) = 3(1/2) = 3/2', 'y = rsinθ = 3sin(π/3) = 3(√3/2) = 3√3/2', 'Cartesian: (3/2, 3√3/2)', 'Verify: r² = (3/2)²+(3√3/2)² = 9/4+27/4 = 36/4 = 9, r=3 ✓']),
                ('How many petals does r = cos(3θ) have?', ['n=3 is odd → 3 petals', 'r = cos(nθ) with n odd: n petals; n even: 2n petals', '3 petals, equally spaced at angles 0, 2π/3, 4π/3', 'Petals have length 1 (the coefficient)']),
                ('Convert r = 4cosθ to Cartesian.', ['Multiply both sides by r: r² = 4rcosθ', 'x²+y² = 4x (using r²=x²+y², rcosθ=x)', 'x²−4x+y² = 0 → (x−2)²+y² = 4', 'Circle centered at (2,0) with radius 2']),
                ('Find two additional polar representations of (2, π/4).', ['(2, π/4 + 2π) = (2, 9π/4) — same direction, same r', '(−2, π/4 + π) = (−2, 5π/4) — opposite direction, negated r', 'All three represent the same point', 'Polar representations are not unique']),
                ('What does r = 1 + 2cosθ produce? Is it a cardioid?', ['a=1, b=2; a/b = 1/2 < 1 → limaçon with inner loop', 'Cardioid requires a = b exactly', 'When a < b: inner loop; a = b: cardioid; a > b: dimpled limaçon; a/b large: convex', 'r=1+2cosθ is a limaçon with inner loop, not a cardioid'])],
               [('Polar Coordinates AP® Precalc', 'Polar system, curves, and conversion', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Professor Leonard Polar', 'Polar equations and graphs', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Polar (r,θ) → Cartesian: x=rcosθ, y=rsinθ.',
                'Rose r=cos(nθ): n petals (n odd); 2n petals (n even).',
                'Polar representations are not unique: (r,θ) = (r,θ+2π) = (−r,θ+π).'])
        ],
        'unit_qs': [
            ('Find the exact value of cos(5π/3).', ['5π/3 is in Q4 (between 3π/2 and 2π)', 'Reference angle: 2π − 5π/3 = π/3', 'cos(π/3) = 1/2; cos is positive in Q4', 'cos(5π/3) = 1/2']),
            ('State the amplitude, period, and midline of f(x) = −3sin(πx/2) + 4.', ['Amplitude: |−3| = 3', 'Period: 2π/(π/2) = 4', 'Midline: y = 4', 'Phase shift: 0 (no horizontal shift)']),
            ('A temperature model: max 95° (August), min 35° (February), period 12 months. Write a cosine model.', ['A = (95−35)/2 = 30; D = (95+35)/2 = 65', 'B = 2π/12 = π/6', 'Max in August (month 8): T(t) = 30cos(π/6(t−8))+65', 'Or use sine with different phase shift']),
            ('Simplify: tanθ·cosθ.', ['tanθ = sinθ/cosθ', 'tanθ·cosθ = (sinθ/cosθ)·cosθ = sinθ', 'Simplified: sinθ', 'Quotient identity applied']),
            ('Solve cosθ = −√3/2 for θ ∈ [0, 2π).', ['cos⁻¹(√3/2) = π/6; cosine negative in Q2 and Q3', 'θ = π − π/6 = 5π/6 (Q2)', 'θ = π + π/6 = 7π/6 (Q3)', 'Solutions: {5π/6, 7π/6}']),
            ('Convert Cartesian (−3, 3) to polar.', ['r = √((-3)²+3²) = √18 = 3√2', 'tanθ = y/x = 3/(−3) = −1; in Q2: θ = 3π/4', 'Polar: (3√2, 3π/4)', 'Also valid: (−3√2, 7π/4)']),
            ('Find sin(2θ) if cosθ = −5/13 and θ is in Q2.', ['sinθ: sin²+cos²=1 → sinθ=√(1−25/169)=12/13 (positive in Q2)', 'sin(2θ) = 2sinθcosθ = 2(12/13)(−5/13) = −120/169', 'Negative: 2θ is in Q3 or Q4 (since θ in Q2, 2θ in Q3/Q4)']),
            ('How many petals does r = 3sin(4θ) have?', ['n=4, even → 2n = 8 petals', 'r = a sin(nθ): same petal rule as cos', '8 petals symmetrically arranged', 'Maximum r = 3 at each petal tip']),
            ('Evaluate: arctan(−1).', ['arctan range is (−π/2, π/2)', 'tan(π/4) = 1; tan(−π/4) = −1', 'arctan(−1) = −π/4', 'Equivalent to −45°']),
            ('Describe the symmetry of r = 3 + 3sinθ (cardioid).', ['Test θ → π−θ: sin(π−θ) = sinθ → r unchanged', 'Symmetric about θ = π/2 (vertical axis)', 'This cardioid opens upward (sin-based)', 'Maximum r = 6 at θ=π/2; r=0 at θ=3π/2'])
        ]
    },
    {
        'num': 4,
        'title': 'Functions Involving Parameters, Vectors, and Matrices',
        'file': 'ap-precalculus-4-unit-4-functions-involving-parameters-vectors-and-matrices.html',
        'desc': 'Parametric equations, vectors in the plane, matrices, and inverse functions.',
        'gateway': [
            'How do parametric equations describe curves differently than Cartesian equations?',
            'How do you add, subtract, and find the magnitude of vectors?',
            'What is a matrix inverse and how does it solve a system of equations?',
            'How do you find the inverse of a function algebraically?',
        ],
        'lessons': [
            _l('Parametric Equations',
               [_t('Introduction to Parametric Equations', 'Parametric equations express x and y as functions of a parameter t: x=f(t), y=g(t). The parameter t often represents time. Eliminates t by solving one equation for t and substituting.', 'The orientation (direction of travel as t increases) is part of the parametric curve — the same Cartesian curve can have different orientations from different parameterizations.', 'Trace a parametric curve by evaluating at key t-values; eliminate t to find the Cartesian equation.'),
                _t('Graphing and Interpreting Parametric Curves', 'To graph: make a table of (t, x, y) → plot (x,y). Eliminating t gives the underlying shape; restrictions on t may limit the portion of the curve. Parametric form is natural for projectile motion: x=v₀t cosα, y=v₀t sinα − (1/2)gt².', 'Eliminating t may lose information about direction and range — always consider the domain of t.', 'Graph parametric curves; interpret the parameter as time in motion problems.'),
                _t('Parametric to Cartesian Conversion', 'For trig parameterizations: x = cosθ, y = sinθ → x²+y²=1 (unit circle). Use Pythagorean identity. For x=at+b: solve t=(x−b)/a, substitute into y equation. Verify the restriction on t matches the desired curve portion.', 'A parameterization can trace only PART of a curve if t has a limited range — the Cartesian equation may be broader.', 'Convert parametric equations to Cartesian form; identify any restrictions.')],
               [('parameter', 'Variable (often t or θ) that defines both x and y in parametric equations'),
                ('parametric equations', 'Pair x=f(t), y=g(t) describing a curve by position at each parameter value'),
                ('eliminating the parameter', 'Solving for t in one equation and substituting to get a Cartesian relation'),
                ('orientation', 'Direction of travel along a parametric curve as t increases'),
                ('projectile motion', 'x=v₀cosα·t; y=v₀sinα·t−½gt²; natural parametric form with t=time')],
               ['Graph parametric curves using tables of t-values.',
                'Eliminate the parameter to find the Cartesian equation.',
                'Interpret parametric equations in the context of motion.'],
               ['FRQ: eliminate the parameter to find a Cartesian equation.',
                'MCQ: identify the Cartesian shape from parametric equations.',
                'FRQ: find position, velocity, or time from a parametric motion model.'],
               ['Graph x = 2cosθ, y = 3sinθ and identify the shape.',
                'Eliminate t from x = t+1, y = t² to find the Cartesian equation.'],
               [('Eliminate t from x = 3t − 1, y = t² + 2.', ['Solve for t: t = (x+1)/3', 'Substitute: y = ((x+1)/3)² + 2', 'y = (x+1)²/9 + 2', 'Parabola with vertex (−1, 2)']),
                ('Identify the curve: x = 4cosθ, y = 4sinθ.', ['x² + y² = 16cos²θ + 16sin²θ = 16(cos²θ+sin²θ) = 16', 'x² + y² = 16: circle of radius 4', 'As θ goes 0→2π: traces the full circle counterclockwise', 'Orientation: counterclockwise']),
                ('A ball is launched at angle 45° with speed 20 m/s. Find x and y at t=1s.', ['x = 20cos(45°)·t = 20(√2/2)(1) ≈ 14.14 m', 'y = 20sin(45°)·t − 4.9t² = 14.14 − 4.9 ≈ 9.24 m', 'g = 9.8 m/s² used; half is 4.9', 'Position after 1 second: (14.14, 9.24)']),
                ('Parameterize the upper semicircle of x²+y²=9.', ['Use x = 3cosθ, y = 3sinθ for θ ∈ [0, π]', 'y = 3sinθ ≥ 0 for θ ∈ [0,π] → upper semicircle only', 'Counterclockwise from (3,0) to (−3,0)', 'Alternatively: x=t, y=√(9−t²) for t ∈ [−3,3]']),
                ('What information is lost when you eliminate the parameter?', ['Orientation (direction of travel as t increases)', 'Portion traced (t range may trace only part of the Cartesian curve)', 'Speed of traversal (how fast the point moves)', 'Parametric form preserves all motion information'])],
               [('Parametric Equations AP® Precalc', 'Graphing and eliminating parameter', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Parametric', 'Parametric equations and curves', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Parametric: x=f(t), y=g(t); eliminate t to get Cartesian form.',
                'Orientation (direction of travel) is part of parametric, lost in Cartesian.',
                'Trig parametric: use Pythagorean identity to eliminate.']),

            _l('Vectors in the Plane',
               [_t('Vector Basics', 'A vector has magnitude and direction. Notation: v = ⟨a,b⟩ or v = ai + bj. Magnitude: |v| = √(a²+b²). Direction angle: tanθ = b/a. Vector addition: ⟨a,b⟩+⟨c,d⟩=⟨a+c,b+d⟩. Scalar multiplication: k⟨a,b⟩=⟨ka,kb⟩.', 'Vectors are NOT points — they represent displacement. Two vectors with the same components are equal regardless of where they start.', 'Compute vector magnitude, direction angle; perform vector addition and scalar multiplication.'),
                _t('Unit Vectors and Components', 'Unit vector: magnitude 1. Unit vector in direction of v: û = v/|v|. i = ⟨1,0⟩; j = ⟨0,1⟩. Any vector: v = ai + bj. Component form from magnitude and angle: a = |v|cosθ, b = |v|sinθ.', 'A unit vector has magnitude 1, not component 1. ⟨3,4⟩ has magnitude 5; unit vector = ⟨3/5, 4/5⟩.', 'Find unit vectors; express vectors in component form from magnitude and angle.'),
                _t('Dot Product and Applications', 'Dot product: u·v = u₁v₁+u₂v₂ = |u||v|cosθ. Orthogonal vectors: u·v = 0. Projection of u onto v: proj_v u = (u·v/|v|²)v. Work: W = F·d.', 'Dot product is a scalar (number), not a vector. This distinguishes it from cross product (which is a vector in 3D).', 'Compute dot products; determine if vectors are orthogonal; find the angle between vectors.')],
               [('vector', 'Mathematical object with magnitude and direction; represented as ⟨a,b⟩'),
                ('magnitude |v|', '√(a²+b²) for v=⟨a,b⟩; length of the vector arrow'),
                ('unit vector', 'Vector of magnitude 1; found by dividing v by |v|'),
                ('dot product', 'u·v = u₁v₁+u₂v₂; scalar result; equals |u||v|cosθ'),
                ('orthogonal vectors', 'Vectors whose dot product is 0; perpendicular; angle between them is 90°')],
               ['Compute vector magnitude and direction angle.',
                'Perform vector addition, subtraction, and scalar multiplication.',
                'Compute dot products and use them to find angles or test orthogonality.'],
               ['FRQ: find magnitude and direction of a vector sum.',
                'MCQ: determine if two vectors are orthogonal.',
                'FRQ: find the work done by a force vector over a displacement.'],
               ['Find the unit vector in the direction of ⟨3,−4⟩.',
                'Find the angle between u=⟨2,1⟩ and v=⟨1,3⟩ using dot product.'],
               [('Find the magnitude and direction of v = ⟨−3, 4⟩.', ['|v| = √(9+16) = √25 = 5', 'tanθ = 4/(−3) → reference angle = arctan(4/3) ≈ 53.1°', 'x-component negative, y positive → Q2: θ ≈ 180°−53.1° = 126.9°', 'Direction: ≈ 126.9° from positive x-axis']),
                ('Are u = ⟨3,−2⟩ and v = ⟨4,6⟩ orthogonal?', ['u·v = 3(4)+(−2)(6) = 12−12 = 0', 'Dot product is 0 → vectors are orthogonal (perpendicular)', 'Angle between them: cos θ = 0 → θ = 90°', 'Yes, they are orthogonal']),
                ('Find the unit vector in direction of u = ⟨5,12⟩.', ['|u| = √(25+144) = √169 = 13', 'Unit vector: ⟨5/13, 12/13⟩', 'Verify: |(5/13)²+(12/13)²|^(1/2) = √(25+144)/13 = 1 ✓']),
                ('Find the angle between a = ⟨1,0⟩ and b = ⟨1,1⟩.', ['a·b = 1(1)+0(1) = 1', '|a| = 1; |b| = √2', 'cosθ = 1/(1·√2) = 1/√2 → θ = π/4 = 45°', '⟨1,0⟩ is positive x-axis; ⟨1,1⟩ is 45° above it ✓']),
                ('A force F=⟨4,3⟩ N moves an object by displacement d=⟨5,0⟩ m. Find work.', ['W = F·d = 4(5)+3(0) = 20 J', 'Only the component of force in the direction of displacement does work', 'Here d is along x-axis; only Fx=4 contributes', 'Physical check: moving object rightward; only horizontal force component matters'])],
               [('Vectors AP® Precalc', 'Magnitude, dot product, direction', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Vectors', 'Vector operations and dot product', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['|v| = √(a²+b²); unit vector = v/|v|.',
                'Dot product: u·v = u₁v₁+u₂v₂ = |u||v|cosθ.',
                'u·v = 0 → orthogonal (perpendicular) vectors.']),

            _l('Matrices and Inverse Functions',
               [_t('Matrix Operations', 'Matrix: rectangular array of numbers. Addition/subtraction: element-wise, must have same dimensions. Multiplication: (A×B)ᵢⱼ = row i of A · column j of B; need inner dimensions to match. Not commutative: AB ≠ BA generally.', 'Matrix multiplication requires columns of A = rows of B. A 2×3 times a 3×2 gives 2×2; 3×2 times 2×3 gives 3×3.', 'Perform matrix multiplication; identify when dimensions are compatible.'),
                _t('Inverse Matrices and Systems', 'For 2×2 matrix A = [[a,b],[c,d]]: det(A) = ad−bc; A⁻¹ = (1/det)[[d,−b],[−c,a]] if det≠0. Solve AX = B by X = A⁻¹B. If det = 0, the matrix is singular (no unique solution).', 'A⁻¹B ≠ BA⁻¹ because matrix multiplication is not commutative. Always multiply on the correct side.', 'Find the inverse of a 2×2 matrix; use it to solve a system of equations.'),
                _t('Inverse Functions', 'f⁻¹ is the inverse of f if f(f⁻¹(x)) = x and f⁻¹(f(x)) = x. To find: replace f(x) with y, swap x and y, solve for y. The inverse exists only if f is one-to-one (passes horizontal line test).', 'f⁻¹(x) is NOT 1/f(x). The notation f⁻¹ means the inverse function, not the reciprocal.', 'Find the inverse of a function algebraically; verify by composition; state the domain.')],
               [('matrix', 'Rectangular array of numbers organized in rows and columns'),
                ('determinant (2×2)', 'det[[a,b],[c,d]] = ad−bc; non-zero means inverse exists'),
                ('matrix inverse A⁻¹', 'Matrix such that AA⁻¹ = A⁻¹A = I (identity matrix); exists only if det ≠ 0'),
                ('inverse function f⁻¹', 'Function that reverses f; f(f⁻¹(x))=x; found by swapping x and y'),
                ('one-to-one function', 'Function passing horizontal line test; each output corresponds to one input; invertible')],
               ['Multiply matrices and check dimension compatibility.',
                'Find the inverse of a 2×2 matrix and use it to solve a system.',
                'Find and verify the inverse of a function; state its domain.'],
               ['FRQ: find A⁻¹ and use it to solve AX = B.',
                'MCQ: determine if two matrices can be multiplied given their dimensions.',
                'FRQ: find the inverse of f(x) = (2x+1)/(x−3) and state its domain.'],
               ['Find the inverse of [[3,1],[5,2]] and verify by computing A·A⁻¹.',
                'Find f⁻¹(x) for f(x) = 3x−7 and verify f(f⁻¹(x)) = x.'],
               [('Find the inverse of A = [[2,3],[1,4]].', ['det(A) = 2(4)−3(1) = 8−3 = 5', 'A⁻¹ = (1/5)[[4,−3],[−1,2]]', 'Verify: A·A⁻¹ = I: [[2,3],[1,4]]·(1/5)[[4,−3],[−1,2]] = I ✓', 'Elements: (1/5)[[4,−3],[−1,2]] = [[0.8,−0.6],[−0.2,0.4]]']),
                ('Find f⁻¹(x) for f(x) = 5x − 3.', ['y = 5x−3; swap x and y: x = 5y−3', 'Solve for y: y = (x+3)/5', 'f⁻¹(x) = (x+3)/5', 'Verify: f(f⁻¹(x)) = 5·(x+3)/5−3 = x+3−3 = x ✓']),
                ('Is f(x) = x² invertible? Explain.', ['No — f fails the horizontal line test', 'f(2) = f(−2) = 4: two inputs map to same output', 'Not one-to-one over all reals', 'Restrict domain to [0,∞): then f⁻¹(x) = √x is valid']),
                ('Find f⁻¹(x) for f(x) = (3x+1)/(x−2). State the domain.', ['y = (3x+1)/(x−2); swap: x = (3y+1)/(y−2)', 'x(y−2) = 3y+1 → xy−2x = 3y+1', 'xy−3y = 2x+1 → y(x−3) = 2x+1', 'f⁻¹(x) = (2x+1)/(x−3); domain: x ≠ 3']),
                ('Can you multiply a 3×2 matrix by a 2×4 matrix? What is the result size?', ['Yes: inner dimensions match (2=2)', 'Result: 3×4 matrix (outer dimensions)', 'Rule: (m×n)(n×p) = (m×p)', 'Cannot multiply 2×4 times 3×2: 4 ≠ 3'])],
               [('Matrices AP® Precalc', 'Inverse matrices and systems', 'https://www.youtube.com/watch?v=9OOrhA2iKak'),
                ('Khan Academy Inverse Functions', 'Finding and verifying inverse functions', 'https://www.youtube.com/watch?v=9OOrhA2iKak')],
               ['Matrix mult: (m×n)(n×p)=(m×p); not commutative.',
                'A⁻¹ exists if det(A) ≠ 0; solve AX=B as X=A⁻¹B.',
                'f⁻¹: swap x and y, solve for y; verify by composition.'])
        ],
        'unit_qs': [
            ('Eliminate t from x = 2t − 3, y = t² + 1 and identify the shape.', ['t = (x+3)/2', 'y = ((x+3)/2)² + 1 = (x+3)²/4 + 1', 'Parabola with vertex (−3, 1) opening upward', 'Original t range affects which portion of parabola is traced']),
            ('Find the magnitude and unit vector for v = ⟨6, −8⟩.', ['|v| = √(36+64) = √100 = 10', 'Unit vector: ⟨6/10, −8/10⟩ = ⟨0.6, −0.8⟩', 'Verify: |⟨0.6,−0.8⟩| = √(0.36+0.64) = 1 ✓']),
            ('Find the dot product of u = ⟨2, −5⟩ and v = ⟨4, 3⟩. Are they orthogonal?', ['u·v = 2(4)+(−5)(3) = 8−15 = −7', 'Not zero → not orthogonal', 'The angle between them: cosθ = −7/(|u||v|)', '|u|=√29, |v|=5; cosθ=−7/(5√29)']),
            ('Find A⁻¹ for A = [[5, 2], [3, 1]].', ['det(A) = 5(1)−2(3) = 5−6 = −1', 'A⁻¹ = (1/−1)[[1,−2],[−3,5]] = [[−1,2],[3,−5]]', 'Verify: A·A⁻¹ should = I', 'Check: [[5,2],[3,1]][[−1,2],[3,−5]] = [[1,0],[0,1]] ✓']),
            ('Find f⁻¹(x) for f(x) = 2x + 7.', ['y = 2x+7; swap x and y: x = 2y+7', 'y = (x−7)/2', 'f⁻¹(x) = (x−7)/2', 'Verify: f(f⁻¹(x)) = 2·(x−7)/2+7 = x ✓']),
            ('Can matrices A (4×3) and B (3×5) be multiplied? What size is AB?', ['Inner dimensions: 3=3 ✓ (columns of A = rows of B)', 'Result AB: outer dimensions → 4×5', '(4×3)(3×5) = 4×5', 'Cannot compute BA: (3×5)(4×3) fails since 5≠4']),
            ('The curve x=cosθ, y=sinθ for θ∈[0,π/2]. What part of the unit circle is traced?', ['cos and sin are both non-negative for θ∈[0,π/2]', 'Traces the first-quadrant arc from (1,0) to (0,1)', 'Orientation: counterclockwise', 'Cartesian equation: x²+y²=1 (full circle); parameter restriction limits to Q1 arc']),
            ('Compute AB: A = [[1,2],[3,4]], B = [[0,1],[2,3]].', ['Row 1 of A × columns of B: [1·0+2·2, 1·1+2·3] = [4, 7]', 'Row 2 of A × columns of B: [3·0+4·2, 3·1+4·3] = [8, 15]', 'AB = [[4,7],[8,15]]', 'Check: (2×2)(2×2)=(2×2) ✓']),
            ('A force F = ⟨6,8⟩ N acts on an object. What is its magnitude and the angle it makes with the x-axis?', ['|F| = √(36+64) = √100 = 10 N', 'tanθ = 8/6 = 4/3 → θ = arctan(4/3) ≈ 53.1°', 'Both components positive → Q1: angle ≈ 53.1° from positive x-axis', 'Unit vector: ⟨0.6, 0.8⟩']),
            ('Why does f(x) = x³ have an inverse but f(x) = x² does not (without restriction)?', ['x³ is strictly increasing everywhere → one-to-one → invertible', 'x² has f(2)=f(−2)=4 → not one-to-one over all reals', 'Horizontal line test: x³ never hit by a horizontal line twice; x² is', 'f(x)=x² restricted to [0,∞) is invertible with inverse √x'])
        ]
    }
]
